### ISSUE TITLE
Support TLS Expiry alerts

### ISSUE THREAD

**Issue by proffalken** [louislam/uptime-kuma#1]
This is an amazing project, I had it up and running within minutes of your post on Reddit, thank you so much!

It would be awesome if you could add TLS monitoring alongside the "uptime" monitoring.

Although [LetsEncrypt](https://letsencrypt.org) does a great job of auto-renewing certs, it would be great to monitor the following metrics as well:

1. Days until certificate expires
2. Whether the certificate is valid or invalid

I've been bitten by this so many times in the past!

**Comment by TheGuyDanish** [comment]
The ability to import a trusted root CA (for internal CA's) would be a welcome addition to the above.

**Comment by 12nick12** [comment]
Adding to this domain expiration would also be great.

**Comment by joe-eklund** [comment]
> The ability to import a trusted root CA (for internal CA's) would be a welcome addition to the above.

Hi I detailed how you can do this in https://github.com/louislam/uptime-kuma/issues/21#issuecomment-881757886 using an environment variable.

**Comment by proffalken** [comment]
@tmarly nope, not wrong, this is working well in the latest version.

**Comment by jsloane** [comment]
Is there a way to disable these alerts? I don't want to be notified when the certificate is going to expire in 14 days, I just need outage notifications.

**Comment by chakflying** [comment]
See #844, config is currently not implemented yet.
