### ISSUE TITLE
App Engine

### ISSUE THREAD

**Issue by capriciousduck** [louislam/uptime-kuma#1001]
How can I host uptime kuma on Google App Engine free-tier?

**Comment by louislam** [comment]
I personally do not suggest it, as I remember that there is a lot of hidden costs of Google Cloud Platform such as the bandwidth costs across two different countries. 

Oracle Cloud free-tier is my suggestion.

**Comment by capriciousduck** [comment]
Yeah...I totally agree with you. I've signed up at Oracle months ago but didn't use it much. Unfortunately, due to account inactivity, they disabled my account. Now they don't even respond to my emails.
