### ISSUE TITLE
Monitors missing in Dashboard  Quick start page

### ISSUE THREAD

**Issue by doc75** [louislam/uptime-kuma#1005]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### Description

On my installation of uptime-kuma, i have 17 monitors defined.
When going to the default dashboard page, I can see the 17 monitors on the left part of the page.
But on the right part, it indicates 17 monitors are up, but it only list 15 of them

![image](https://user-images.githubusercontent.com/926263/144744310-f3a05742-cc4f-4556-932b-c5a8a0883027.png)

### 👟 Reproduction steps

- Create several monitors
- go to the default dashboard page
- You see a difference between the number of monitors Up and the list just below

### 👀 Expected behavior

See all monitors in the list

### 😓 Actual Behavior

15 monitors listed while 17 are mentionned to be up

### 🐻 Uptime-Kuma Version

1.10.2

### 💻 Operating System and Arch

Official Docker 1-alpine image (as of 2021-12-05)

### 🌐 Browser

Firefox 94.0

### 🟩 NodeJS Version

20.10.11

### 📝 Relevant log output

```shell
If needed, let me know how to generate useful logs. I'll be happy to add them
```

**Comment by louislam** [comment]
It is a event list.

**Comment by chakflying** [comment]
Ref. #169 for posterity.

**Comment by doc75** [comment]
@louislam sorry for this misunderstanding.
May I suggest that we change the title of this section to make it more obvious that this is the list of event. Indeed to me (English is not my native language), the title **Quick stats** (French translation tranlated back to English is **Summary**) does not make me think at first that it was a list of events.
