### ISSUE TITLE
uptime kuma show blank page

### ISSUE THREAD

**Issue by audio99** [louislam/uptime-kuma#1006]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

uptime kuma show blank page even when redirect to dashboard, etc

![image](https://user-images.githubusercontent.com/9496025/144750156-9ce1f8a6-3cf0-4daa-897a-de192fc87e09.png)

### 🐻 Uptime-Kuma Version

1.10.2

### 💻 Operating System and Arch

Windows 11 x64

### 🌐 Browser

Google Chrome 96.0.4664.45 (Official Build) (64-bit)

### 🐋 Docker Version

-

### 🟩 NodeJS Version

v14.18.0

**Comment by louislam** [comment]
It is not the way for normal users, please follow the installation guide.

If you want to develop Uptime Kuma, please read https://github.com/louislam/uptime-kuma/blob/master/CONTRIBUTING.md for how to setup the dev environment.

**Comment by audio99** [comment]
> It is not the way for normal users, please follow the installation guide.
> 
> If you want to develop Uptime Kuma, please read https://github.com/louislam/uptime-kuma/blob/master/CONTRIBUTING.md for how to setup the dev environment.

i've been following this
======================================
Set the env var NODE_ENV to "development".

Start the frontend dev server by the following command.

npm run dev
It binds to 0.0.0.0:3000 by default.

You can use Vue.js devtools Chrome extension for debugging.

Build the frontend
npm run build
============================================

but it became blank page when opened in web browser 😢

**Comment by Patchfox** [comment]
What does your webdev tools say in the network tab when you load to the page?

**Comment by benchonaut** [comment]
( same with current version , the /api/monitor-list endpoint only returns `[]` )

**Comment by tarocjsu** [comment]
This issue keep happen, no matter to through Niinx Proxy Manager or not, just use http://local_IP_address:3001/ still got the blank page too.

**Comment by CommanderStorm** [comment]
Because of the age of this issue, I am assuming this is not actually the same issue.

- What does your webdev tools say in the network tab when you load to the page?
- Did you follow the [contribution guide](https://github.com/louislam/uptime-kuma/blob/master/CONTRIBUTING.md) or the [installation guide](https://github.com/louislam/uptime-kuma/wiki/%F0%9F%94%A7-How-to-Install)?
- What environment are you using? How is it set up?
- does your browser support javascript?

**Comment by tarocjsu** [comment]
This issue or sympton never solve before, always happen again and again.

**Comment by tarocjsu** [comment]
Till version 1.23.13 stil happen everyday.

**Comment by CommanderStorm** [comment]
Please refer to the questions in https://github.com/louislam/uptime-kuma/issues/1006#issuecomment-2161527893
