### ISSUE TITLE
Include Duration of Downtime

### ISSUE THREAD

**Issue by darksky82** [louislam/uptime-kuma#1008]
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

Other

### 🔖 Feature description

When a monitor comes "up" again after a down time. The notification must include the HH:MM:SS the monitor was down. Uptime robot nicely does this. 
![image](https://user-images.githubusercontent.com/63789013/144787229-f45acf2d-967b-47f8-b588-a5b26c22295b.png)

### ✔️ Solution

Modify the notification content/text

**Comment by ivanbratovic** [comment]
This seems to be a duplicate of #428
