### ISSUE TITLE
ssl cert chain not trusted 

### ISSUE THREAD

**Issue by dennismi** [louislam/uptime-kuma#1012]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

I have purchased a public SSL Certificate, and added it to the my reverse proxy (traefik/traefik2). A SSL Check is failing because it cannot verify the certificate. 

Apparently it cannot verify that certificate chain. 

### 🐻 Uptime-Kuma Version

1.10.2

### 💻 Operating System and Arch

both debian and Alpine

### 🌐 Browser

Brave Version 1.32.113 Chromium: 96.0.4664.45 (Official Build) (64-bit)

### 🐋 Docker Version

docker swarm 20.11

**Comment by rezzorix** [comment]
### ⚠️ Please verify that this bug has NOT been raised before.

I dont believe that your checkmark is honest 😜 

Anyway, probably has something to do with missing CA etc.

Read further for example here:
https://github.com/louislam/uptime-kuma/issues/850

And here:
https://github.com/louislam/uptime-kuma/issues/90

**Comment by dennismi** [comment]
Well, **I** checked - and didn't find anything - but apparently I was searching with wrong wording. 

but reading those answers pointed me in a direction, and through some more testing (on a new day) 

And I found that it wasn't directly related to the UptimeKuma. 

Thank you for your time.
