### ISSUE TITLE
How to remove

### ISSUE THREAD

**Issue by Nikolai980** [louislam/uptime-kuma#1013]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

How to remove powered by Uptime Kuma text and link in the footer ?

### 🐻 Uptime-Kuma Version

1.10.0

### 💻 Operating System and Arch

Ubuntu 20.04

### 🌐 Browser

Google Chrome

**Comment by rezzorix** [comment]
On the "Status Page" you can easily remove/adjust the text and logo to whatever you require.

For the Dashboard, Settings etc. you would have to change the source files...

**Comment by ivanbratovic** [comment]
This question is a duplicate of #607. More information about this topic is in that issue.

**Comment by devarti** [comment]
@rezzorix  where and how do you change the source for the dashboard and settings? changing src/components/settings/About.vue?

**Comment by devarti** [comment]
Ok, so that sounds like money matters 🤔, 😆.  Anyways thanks for the reply
although nir very useful as I did try what mentioned on that issue 1013.

Speaking on changes what is on your mind regarding hourly charges if I ask
you three minor ones?

**Comment by rezzorix** [comment]
I think there was misunderstanding. 
So let me clarify: People probably would charge for a customisation job to your specific (commercial?) needs. Especially if it is a commercial need, then it should be paid for. 

If it is for you personally then my advise is to read, learn and get it done yourself. Ask for help when you cant get further but dont ask people to spoon feed you. In the end the source is there.

**Comment by devarti** [comment]
That was rude, nobody is asking for spoon feeding here, I'm not dumb if you
think, the original question was asked politely as there was a confusion.

**Comment by CommanderStorm** [comment]
@osahang 
It is unclear what you mean.

I would recomend to use the setting we provide
![image](https://github.com/louislam/uptime-kuma/assets/26258709/c43aef35-53a9-44e2-b4e7-8cfef974620e)

**Comment by osahang** [comment]
Sorry just noticed the setting now
