### ISSUE TITLE
Multiple monitor notification and lower heartbeat Interval

### ISSUE THREAD

**Issue by a2940uw** [louislam/uptime-kuma#1015]
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

New Notification, New Monitor

### 🔖 Feature description

Hi, I would like to know possible to request a feature to setup multiple notification for the monitor items, such as email + telegram to notification for default or individual monitor items, and change the heartbeat interval up to 1 second. Thank you   

### ✔️ Solution

Hi, I would like to know possible to request a feature to setup multiple notification for the monitor items, such as email + telegram to notification for default or individual monitor items, and change the heartbeat interval up to 1 second. Thank you

**Comment by Furrypaw** [comment]
1 Second heartbeat would be indeed nice.

**Comment by beg1294** [comment]
4 month later, we still need this feature

**Comment by ylluminate** [comment]
Indeed, this is essential. I have a usecase where I need 1 second for gateway monitoring.

**Comment by jwklijnsma** [comment]
any update on this ?

**Comment by CommanderStorm** [comment]
Multiple notification-providers per monitors is curently implemeted => resolved
Removing the minimum interval is currently tracked in #1645 as we like our issues to not contain two issues with one of with being unrelated to the other.

Closing as a resolved/duplicate
