### ISSUE TITLE
Blank Settings page after update

### ISSUE THREAD

**Issue by Kriiiiiiiz** [louislam/uptime-kuma#1016]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### Description

I've just updated to latest version and now settings page shows nothing.

### 👟 Reproduction steps

Just updated to 1.11.0

### 👀 Expected behavior

Should display settings page

### 😓 Actual Behavior

Theres nothing on the settings page.

### 🐻 Uptime-Kuma Version

1.11.0

### 💻 Operating System and Arch

Ubuntu 20.04 x86

### 🌐 Browser

Safari

### 🐋 Docker Version

Not running with Docker

### 🟩 NodeJS Version

v16.11.1

**Comment by Kriiiiiiiz** [comment]
Just tested on Chrome and it works as expected, looks like the issue comes when trying to load Settings page using Safari

**Comment by rezzorix** [comment]
Did just try the same... no issues on Safari.

Did you fully refresh the page properly? 
Delete cookies & site data?
Try in Incognito window?

**Comment by hansenc0705** [comment]
Also having the issue in Safari Version 15.0 (16612.1.29.41.4, 16612)

**Comment by Kriiiiiiiz** [comment]
@hansenc0705 
> Did just try the same... no issues on Safari.
> 
> Did you fully refresh the page properly? Delete cookies & site data? Try in Incognito window?

Yes already tried !

**Comment by Kriiiiiiiz** [comment]
@rezzorix 
> Also having the issue in Safari Version 15.0 (16612.1.29.41.4, 16612) on macOS 11.6 (20G165)
> 
> Also does not work in Safari Private Window

Same as me :(

**Comment by louislam** [comment]
Confirmed, it seems that it is related to `useRoute` is undefined in Safiri.

https://github.com/louislam/uptime-kuma/blob/f9cd0eb084bda06dd20d6a1d7533bf682a889fda/src/pages/Settings.vue#L52

![image](https://user-images.githubusercontent.com/1336778/145224651-92ca9508-86a6-4183-a1b5-3197e41dcb20.png)

**Comment by louislam** [comment]
Found the issue and fixed in 1.11.1. 

The issue is that Safari is not supporting array.at()

https://caniuse.com/mdn-javascript_builtins_array_at

I really hope that caniuse would be a IDE plugin in the future, so it would warn me that I should not use these features in the frontned.

**Comment by Kriiiiiiiz** [comment]
Many thanks @louislam for that fast release, i really appreciate your work !

**Comment by chakflying** [comment]
Ugh I guess that's why no one's using such a useful function. I admit I did not check before adding that in.
