### ISSUE TITLE
Update monitor results from API

### ISSUE THREAD

**Issue by Quentinvarquet** [louislam/uptime-kuma#1019]
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

API

### 🔖 Feature description

Hello,

Do you think it's possible to get an API to update the monitor results (for example from another monitoring tools) ?

For example site24x7 does it  https://www.site24x7.com/help/statusiq/api/#introduction

Thank you !

### ✔️ Solution

None

### ❓ Alternatives

None

### 📝 Additional Context

None

**Comment by louislam** [comment]
#118
