### ISSUE TITLE
Uptime Docker Container via SSH or Portainer

### ISSUE THREAD

**Issue by reddexx** [louislam/uptime-kuma#1020]
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

New Monitor, UI Feature, Other

### 🔖 Feature description

Uptime Container via SSH or Portainer

### ✔️ Solution

SSH Connection to Host Server

### ❓ Alternatives

over Portainer

**Comment by rezzorix** [comment]
Sorry... very unclear to me and maybe others.
Can you explain a bit more specifically what you are trying to suggest?

**Comment by reddexx** [comment]
Ich habe meine Anwendungen über Docker Container am Laufen, da wäre es nice das die überwacht werden, da die Isoliert sind, sind die via netzwerk nicht erreichbar

Example: (Running on Portainer)
![image](https://user-images.githubusercontent.com/6242840/145221974-73bb9e80-e829-42cb-8b3c-b72ab1defd76.png)

**Comment by rezzorix** [comment]
Adding one more; you could get the status of all your containers via Portainer API and setup monitors to check the status there...

https://docs.portainer.io/v/ce-2.9/api/examples

**Comment by FM1337** [comment]
> Adding one more; you could get the status of all your containers via Portainer API and setup monitors to check the status there...
> 
> https://docs.portainer.io/v/ce-2.9/api/examples

That requires authentication though and I don't believe it supports basic auth.

**Comment by rezzorix** [comment]
With the HTTP(S) monitor you have HTTP Options to get/post etc. headers and body.

**Comment by FM1337** [comment]
> With the HTTP(S) monitor you have HTTP Options to get/post etc. headers and body.

Ah I see now, turns out my portainer version was outdated and didn't have access keys yet.

**Comment by corasaniti** [comment]
I wanted to make a similar request. I think the solution is to support portainer-agent
Thanks

**Comment by Havock94** [comment]
+1 to request portainer-agent support, would be so handy for those who run several portainer instances in different servers

**Comment by CommanderStorm** [comment]
@Havock94 @corasaniti 
Please don't necropost on closed, resolved issues.
It is unlikely that this approach is going to achive what you want
