### ISSUE TITLE
error in logs: "TypeError: Cannot read property 'daysRemaining' of null"

### ISSUE THREAD

**Issue by jbenguira** [louislam/uptime-kuma#1024]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### Description

I can see this error in my logs from uptime-kuma every few minutes:

TypeError: Cannot read property 'daysRemaining' of null
at Prometheus.update (/app/server/prometheus.js:63:91)
at beat (/app/server/model/monitor.js:396:24)
at async Timeout.safeBeat [as _onTimeout] (/app/server/model/monitor.js:419:17)

FYI I'm not using Prometheus, just the base docker image with just a few http monitors configured, no special settings or anything

### 👟 Reproduction steps

deploy uptime kuma, add a monitor, wait and check the container logs

### 👀 Expected behavior

we should not have this error every few minutes in the logs

### 😓 Actual Behavior

I can see this error in my logs from uptime-kuma every few minutes:

TypeError: Cannot read property 'daysRemaining' of null
at Prometheus.update (/app/server/prometheus.js:63:91)
at beat (/app/server/model/monitor.js:396:24)
at async Timeout.safeBeat [as _onTimeout] (/app/server/model/monitor.js:419:17)

### 🐻 Uptime-Kuma Version

1.11.1

### 💻 Operating System and Arch

Ubuntu 20.04 - x64

### 🌐 Browser

Chrome

### 📝 Relevant log output

```shell
TypeError: Cannot read property 'daysRemaining' of null
at Prometheus.update (/app/server/prometheus.js:63:91)
at beat (/app/server/model/monitor.js:396:24)
at async Timeout.safeBeat [as _onTimeout] (/app/server/model/monitor.js:419:17)
```

**Comment by chakflying** [comment]
Can you check if any of your HTTP monitors has missing "certificate info" shown in the monitor page? While this is an easy fix I wonder if there is something else going on.

**Comment by jbenguira** [comment]
I have checked quickly the 26 monitors I have not trace about that
some of my monitors are on HTTP some others on HTTPS and also some more with PING

**Comment by jbenguira** [comment]
Just wanted to let you know that the issue is still present in the latest version 1.11.3

every minute I have this in my log
Jan 12 08:06:52 uptime-u3 19a2273a2382[788]:     at Prometheus.update (/app/server/prometheus.js:63:91)
Jan 12 08:06:52 uptime-u3 19a2273a2382[788]:     at beat (/app/server/model/monitor.js:420:24)
Jan 12 08:06:52 uptime-u3 19a2273a2382[788]:     at async Timeout.safeBeat [as _onTimeout] (/app/server/model/monitor.js:443:17)
