### ISSUE TITLE
SSL error in Uptime-kuma

### ISSUE THREAD

**Issue by shardharma** [louislam/uptime-kuma#1027]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

Hi,

We are getting errors while configuring the slack integration for notification, please help. 
Error-  self signed certificate in certificate chain
Attached screenshot for your reference. 
![uptimekuma](https://user-images.githubusercontent.com/59441855/145378548-1b5f2f7c-7f67-4ddf-a0a8-118e3ba2d090.JPG)

### 🐻 Uptime-Kuma Version

1.6.2

### 💻 Operating System and Arch

No

### 🌐 Browser

Chrome

### 🐋 Docker Version

Docker desktop 2.2.0.5

### 🟩 NodeJS Version

No

**Comment by cruzanstx** [comment]
I am also having a similar issue with the mattermost notifications. I think we may be able to over come it by adding the CA cert to the image or if we could expose a flag to ignore certificate errors.

**Comment by xiazeyu** [comment]
Hey, I also met the problem, and it is solved by https://github.com/louislam/uptime-kuma/issues/850.

**Comment by zafarasyed** [comment]
> I am also having a similar issue with the mattermost notifications. I think we may be able to over come it by adding the CA cert to the image or if we could expose a flag to ignore certificate errors.

There is a much easier way, upon investigating the code I realized that there are two variables and if they are set properly it will automatically default to https.

  - UPTIME_KUMA_SSL_KEY=data/certs/uptimekuma.key
  - UPTIME_KUMA_SSL_CERT=data/certs/uptimekuma.crt
set the above enviroment variable in your docker compose file also make sure that you have the certificate in the data/certs directory below is the sample example

version: "3.1"

services:
uptime-kuma:
image: louislam/uptime-kuma:1
container_name: UptimeKuma
volumes:
- /home/user/UptimeKuma/data:/app/data
- /home/user/UptimeKuma/data/certs:/certs:ro
environment:
- PUID=1000
- PGID=1000
- TZ=America/location
- UMASK_SET=022 # optional
- UPTIME_KUMA_SSL_KEY=data/certs/uptime.key
- UPTIME_KUMA_SSL_CERT=data/certs/uptime.crt
ports:
- 3001:3001
restart: unless-stopped
security_opt:
- no-new-privileges:true

**Comment by DaniW42** [comment]
Hey @zafarasyed,
I was trying to follow your environment variable hint but didn't had any success. Which certificate needs to go to the container? The one for my uptime-kuma or the intermediate?
