### ISSUE TITLE
Error during update 

### ISSUE THREAD

**Issue by kfra71** [louislam/uptime-kuma#1029]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

Hi, I am following this guide https://github.com/louislam/uptime-kuma/wiki/🆙-How-to-Update in order to update to latest version, but I am getting this error while running  the command npm ci --production (the server is not running anymore):

 vue-demi@0.11.4 postinstall /opt/uptime-kuma/node_modules/vue-qrcode/node_modules/vue-demi
> node ./scripts/postinstall.js

internal/fs/utils.js:332
    throw err;
    ^

Error: EACCES: permission denied, open '/opt/uptime-kuma/node_modules/vue-qrcode/node_modules/vue-demi/lib/index.cjs'
    at Object.openSync (fs.js:497:3)
    at Object.writeFileSync (fs.js:1528:35)
    at copy (/opt/uptime-kuma/node_modules/vue-qrcode/node_modules/vue-demi/scripts/utils.js:24:6)
    at switchVersion (/opt/uptime-kuma/node_modules/vue-qrcode/node_modules/vue-demi/scripts/utils.js:52:3)
    at Object.<anonymous> (/opt/uptime-kuma/node_modules/vue-qrcode/node_modules/vue-demi/scripts/postinstall.js:12:3)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:76:12) {
  errno: -13,
  syscall: 'open',
  code: 'EACCES',
  path: '/opt/uptime-kuma/node_modules/vue-qrcode/node_modules/vue-demi/lib/index.cjs'
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! vue-demi@0.11.4 postinstall: `node ./scripts/postinstall.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the vue-demi@0.11.4 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-12-09T11_58_57_769Z-debug.log

Can you kindly help me?

Looking forward to hearing from you. 

Best regards, 

Francesco. 

### 🐻 Uptime-Kuma Version

1.11.1

### 💻 Operating System and Arch

Ubuntu 20.10

### 🌐 Browser

N/A

### 🟩 NodeJS Version

14.18.2

**Comment by nbranquinho** [comment]
I have the same problem installing using this guideline:
https://github.com/louislam/uptime-kuma/wiki/%F0%9F%94%A7-How-to-Install

**Comment by nbranquinho** [comment]
I was able to overcome the error by running the commands as root. It may not be the best, but it worked.

I hope this helps!

**Comment by SimonTod** [comment]
I have the same problem, no matter the version of uptime-kuma i am trying to install. 

I am running node v14.19.1, npm version 6.14.16.

I have tried using user root, no success.

Please help ?

**Comment by louislam** [comment]
Please follow the readme, you have to upgrade your npm.

**Comment by SimonTod** [comment]
My node version wasn't the problem.

The installation was initially made by root.

I managed to make it work by reinstalling as a non root user.

**Comment by christopherpickering** [comment]
I think the problem is because the default dir `opt/uptime-kuma` requires sudo, and in the install script (installing as local) the npm install command is not called with sudo.

If you run it without `sudo` and change the default install dir to a place not requiring `sudo` it seems to work.
