### ISSUE TITLE
DKIM settings for SMTP notifications

### ISSUE THREAD

**Issue by ilogus** [louislam/uptime-kuma#1030]
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

Other

### 🔖 Feature description

Hello,

Would it be possible to sign SMTP emails with DKIM?
This will increase the security of sending mail if the SPF and DMARC fields are correctly configured.
This also prevents emails from ending up in spam.

### ✔️ Solution

To make this possible, from an interface point of view in SMTP notifications, I see the addition of 3 fields:
- one for the domain,
- another for the DKIM key selector,
- and finally a field to be able to fill in the private key.

Technically modify the sending of emails in order to sign them with the information provided.

### 📝 Additional Context

Some sources on this technology :

https://wikipedia.org/wiki/DomainKeys_Identified_Mail

**Comment by NixNotCastey** [comment]
It's outside uptime-kuma scope. That's Your SMTP server should sign messages with DKIM.

**Comment by rezzorix** [comment]
Y

> It's outside uptime-kuma scope. That's Your SMTP server should sign messages with DKIM. SMTP notification from Uptime-Kuma is an MUA/SMTP Client not MSA or MTA.

Exactly - DKIM is a key that you set into your mail-servers DNS records, nothing that uptime can do for you.

Think of uptime in this case as an email-client just connecting to the server sending an email.


You can read more here:
https://www.sparkpost.com/resources/email-explained/dkim-domainkeys-identified-mail/

Aside from that I think this topic can be closed.

**Comment by ilogus** [comment]
I can't set my DKIM keys on my SMTP servers (1&1 for the quoted ones).
Sorry I thought it was possible to add it in this project, I don't develop in javascript. 
All my applications have a private key with a selector on their domain name.
(The equivalent in PHP is PHPMailer, where it is possible to use this feature.) 

Here is an example of a project (Wiki.js) that allows to define directly in the application the DKIM : https://github.com/Requarks/wiki

But if this is not possible for technical reasons, no worries, you can close the ticket ;)

**Comment by rezzorix** [comment]
Ok, but still key needs also to be present in the DNS entries of the domain... do you have this?

Aside from that, the phpmailer can indeed work with the private DKIM keys, however, not sure how Uptime-Kuma exactly sends emails.

**Comment by ilogus** [comment]
Yes I have 3 applications that already use DKIM perfectly, I suggest it here if it is technically possible.
I really don't know js, so I don't know if there is already a DKIM support.

If I had the possibility to set the DKIM directly on the SMTP servers I would do it, but the solution I found is to sign the mail from the client. What I find more logical is to sign the mail closest to the sender to avoid that the message is modified by an SMTP.

If you want to check one of my DNS records, here is my DKIM public key from my bot discord : phpmailer._domainkey.marya.fr
