### ISSUE TITLE
Easier translation process

### ISSUE THREAD

**Issue by PopcornPanda** [louislam/uptime-kuma#1034]
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

Other

### 🔖 Feature description

Nowadays, translations often lack of translated lines. Checking the English language file for additional lines is not an optimal solution. It would be handy if translation could be done by https://localazy.com/ or https://www.transifex.com/open-source/

Also, that would eliminate potential translation/code breakage if a contributor forgets to add a comma at the end of a line.

### ✔️ Solution

Use TMS platform to streamline translation process. Transifex for open-source projects is free, there is also a localazy.

### ❓ Alternatives

Switch up to standard .po and .mo files, that would enable translation by poedit and similar software.

**Comment by deluxghost** [comment]
the web editor of transifex is really laggy on my side

here are some other choices:

- crowdin
- weblate (hosted)
- poeditor

i think they all have solutions for open source project
