### ISSUE TITLE
Is it possible to monitor Xibo clients via its API?

### ISSUE THREAD

**Issue by JacobCoffee** [louislam/uptime-kuma#1035]
I have a Xibo host and a bunch of clients doing digital signage. Sometimes the clients go down and I have no clue without walking through our many buildings or logging onto the web gui. 

With UKs current feature set, Is it possible to create a monitor for the Xibo client endpoints? Maybe using the API?

- https://xibo.org.uk/docs/developer/cms-api

**Comment by rezzorix** [comment]
Sorry, but thats a real low effort post - even trying others to get the things done for you. 😉 

Xibo Api:
Using HTTP formData requests.
All PUT requests require Content-Type:application/x-www-form-urlencoded header.

Just glancing at that it should be possible to setup a monitor accordingly to fulfil your needs.
I guess in this special-use-case you need to read the manual yourself and then implement it.

If you run into a specific problem, then ask again.

For a subreddit: well, if you would actually read and not just drop a request; scroll down on main uptime-kuma github...

What you will find is the info regarding reddit: https://www.reddit.com/r/UptimeKuma/

**Comment by JacobCoffee** [comment]
> Sorry, but thats a real low effort post - even trying others to get the things done for you. 😉
> 
> Xibo Api: Using HTTP formData requests. All PUT requests require Content-Type:application/x-www-form-urlencoded header.
> 
> Just glancing at that it should be possible to setup a monitor accordingly to fulfil your needs. I guess in this special-use-case you need to read the manual yourself and then implement it.


Thanks! I will read more on this:
Using HTTP formData requests.
All PUT requests require Content-Type:application/x-www-form-urlencoded header.
