### ISSUE TITLE
Option to add other users

### ISSUE THREAD

**Issue by funky123** [louislam/uptime-kuma#1039]
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

UI Feature, Other

### 🔖 Feature description

You should add the option to add other user accout to view details from status-page e.g. the value of dns checks or the ping delays/history.

### ✔️ Solution

Adding the UI Feature for the logged-in admin User to add new users via E-Mail or simple username and password as "Viewer" only.

### ❓ Alternatives

implement a user-rights-management

### 📝 Additional Context

If there is feature already (and i can't find

**Comment by V1P-J0K3R** [comment]
That were great if i can add more Admins or Viewer Only Users.
Please add this Feature.

**Comment by gruessung** [comment]
Yes, this would be very helpful.

**Comment by hteibler** [comment]
- a view only user would be great
- or to view without login ( limit via my Firewall )
- limit view  access via source IP list/ranges

**Comment by koen20** [comment]
Duplicate of #128

**Comment by CommanderStorm** [comment]
@funky123 I think this is a duplicate of #128
Duplicates only hurt issue discoverability and lead to zombies, could you either
- clairify why this is not a duplicate
- or close this issue?
