### ISSUE TITLE
after 4 months with no issues today: This site can’t be reached anymore ....

### ISSUE THREAD

**Issue by JchDupuy38** [louislam/uptime-kuma#1040]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

My Uptime-Kuma is running in a rancher environment with no issues for 4 months. I shutdown the server for 2 weeks and on reboot yesterday, the container runs but I cannot access the web page, error message "ERR_CONNECTION_REFUSED".

Logs show the following:
Version: 1.11.1
Creating express and socket.io instance
Server Type: HTTP
Data Dir: ./data/
Connecting to the Database
SQLite config:
[ { journal_mode: 'wal' } ]
[ { cache_size: -12000 } ]
SQLite Version: 3.36.0
Connected
Your database version: 10
Latest database version: 10
Database patch not needed
Database Patch 2.0 Process
Load JWT secret from database.
Adding route
Adding socket handler
Init the server
Trace: RangeError [ERR_SOCKET_BAD_PORT]: options.port should be >= 0 and < 65536. Received NaN.
    at new NodeError (internal/errors.js:322:7)
    at validatePort (internal/validators.js:216:11)
    at Server.listen (net.js:1457:5)
    at /app/server/server.js:1336:12 {
  code: **'ERR_SOCKET_BAD_PORT**'
}
    at process.<anonymous> (/app/server/server.js:1542:13)
    at process.emit (events.js:400:28)
    at processPromiseRejections (internal/process/promises.js:245:33)
    at processTicksAndRejections (internal/process/task_queues.js:96:32)

### 🐻 Uptime-Kuma Version

1.11.1

### 💻 Operating System and Arch

Ubuntu 20.04.3 LTS

### 🌐 Browser

Chrome

### 🐋 Docker Version

Rancher 2.4-6254-head

### 🟩 NodeJS Version

No

**Comment by louislam** [comment]
Usually related to K8s, removing all auto environment variables could solve this problem. In this case, I think Rancher added `UPTIME_KUMA_PORT` with `null` value which causes this problem. 

Related issue: https://github.com/louislam/uptime-kuma/issues/895
