### ISSUE TITLE
not available after installation

### ISSUE THREAD

**Issue by timbo036** [louislam/uptime-kuma#1041]
Hi,

I install Uptime Kuma with your Instruction on my Raspberry 3B+. After install i see this Display in Terminal(below)

![Unbenannt](https://user-images.githubusercontent.com/52106726/145639449-4766a71c-f916-4778-94a1-fd92636a1517.PNG)

The Problem is I dont see the Webinterface on Localhost but the Port 3001 is aviable.

Thanks.

timbo036

**Comment by louislam** [comment]
You need to provide more info, browser error? Which guide did you follow?

**Comment by timbo036** [comment]
I follow this guide:

![image](https://user-images.githubusercontent.com/52106726/145672872-419c9829-d094-431d-952c-510ddc6322b4.png)

My Browser Show this:

![image](https://user-images.githubusercontent.com/52106726/145673070-42fd9825-3104-4000-b670-a2dd77403bad.png)

apache2 is running

**Comment by tompjep** [comment]
Got same problem. Used same steps

**Comment by louislam** [comment]
Cannot reproduce, please make sure there was no error during installation and start the server with pure node first:

`node server/server.js`

The last line should be `Listening on 3001`

**Comment by timbo036** [comment]
node server/server.js
I try this and Syntax Error

![image](https://user-images.githubusercontent.com/52106726/145685450-7f20c685-3cb8-4bcc-8d81-5e5269d2eff6.png)

**Comment by louislam** [comment]
Are you using Node.js >= 14 ?

**Comment by tompjep** [comment]
![image](https://user-images.githubusercontent.com/62673710/145686079-ede31c18-abe9-4f67-aef1-3e98294d0438.png)

**Comment by tompjep** [comment]
It's working again. Don't know what fixed the problem. 
![image](https://user-images.githubusercontent.com/62673710/145686188-0010653d-60f6-4306-a3e2-f47daa430cf6.png)

**Comment by timbo036** [comment]
> Are you using Node.js >= 14 ?

it was the node.js version... thank you

closed

**Comment by benalla** [comment]
I have the same issue, followed the same steps.
But using node server/server.js it gives:
bash: /usr/local/bin/node: No such file or directory

Using Option 2 to start Uptime-Kuma works.
![image](https://user-images.githubusercontent.com/3511603/161021459-2a75610b-6c49-4d3a-ad8c-91e1d2e97724.png)

What am I missing?
How to install Node.js using 'apk'?

**Comment by louislam** [comment]
> I have the same issue, followed the same steps. But using node server/server.js it gives: bash: /usr/local/bin/node: No such file or directory
> 
> Using Option 2 to start Uptime-Kuma works. ![image](https://user-images.githubusercontent.com/3511603/161021459-2a75610b-6c49-4d3a-ad8c-91e1d2e97724.png)
> 
> What am I missing? How to install Node.js using 'apk'?

Since you can start pm2, I guess you have installed node.js.

Try to restart your terminal.

**Comment by benalla** [comment]
I restarted (and reboot command) terminal, restarted HA.
No effect.
