### ISSUE TITLE
Using Ansible to deploy

### ISSUE THREAD

**Issue by jlebleu** [louislam/uptime-kuma#1051]
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

Other

### 🔖 Feature description

Hello, 

Thanks for this project, we started to use it at [pâquerette](https://paquerette.eu/) here https://uptime-kuma.paquerette.eu/status
I have added a new role to our ansible roles to easily deploy uptime-kuma using docker-compose.
You may find the role here : 
https://git.paquerette.eu/paquerette/infrastructure/ansible-paquerette/-/tree/master/roles/uptime-kuma

This role is linked to our set of roles https://git.paquerette.eu/paquerette/infrastructure/ansible-paquerette/ that we use to setup our services within pâquerette.
You may build your own role from this one if needed.
Do not hesitate if you have any questions

### ✔️ Solution

Ansible role :

https://git.paquerette.eu/paquerette/infrastructure/ansible-paquerette/-/tree/master/roles/uptime-kuma

**Comment by louislam** [comment]
Unofficial Ansible is now supported. Credit to @mhkarimi1383.

https://github.com/louislam/uptime-kuma/tree/ansible-unofficial/ansible

**Comment by jlebleu** [comment]
That's great it was just to share what we did @Pâquerette, thank you for this work
