### ISSUE TITLE
Incident system upgrade

### ISSUE THREAD

**Issue by Hendalf-DEV** [louislam/uptime-kuma#1056]
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

UI Feature

### 🔖 Feature description

When an incident ends, It will appear at the bottom of the website and will not disappear. Like at statuspage.io. Would be cooler. 

### ✔️ Solution

So, you're creating an incident. When it has ended you will click on "end incident". But make it anyway editable if needed. When you have ended an incident it should appear at the bottom of the website with timestamp and date.

### ❓ Alternatives

No response

### 📝 Additional Context

No response

**Comment by karelkryda** [comment]
I'll add it to my TODO list and try to add this great functionality. Just yesterday, I was thinking about improving incident creation.
