### ISSUE TITLE
Two factor token not accepted

### ISSUE THREAD

**Issue by kekonn** [louislam/uptime-kuma#1057]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

After getting logged out from a certain machine I tried to log in, but it's not accepting my 2FA token. Is there a way to reset this? I am hosting a dockerized version on unRAID.

I have no way to check the version that I know of. It is not mentioned on the login or status page.

### 🐻 Uptime-Kuma Version

unknown

### 💻 Operating System and Arch

unRaid x86_64

### 🌐 Browser

Firefox 95.0

### 🐋 Docker Version

Docker version 20.10.5, build 55c4c88

**Comment by chakflying** [comment]
`remove-2fa` command was added in `1.11`, which was about a week ago. Upgrading to the latest version to run this command would be your option if you don't want to manually edit the SQLite database.

If it's the correct 2FA token but it's not working, this might be a bug. Are you sure the date & time between your phone (or other authenticator) and your server are correct and in sync?

**Comment by kekonn** [comment]
How would I execute this? `docker exec -it uptimekuma ` and then?

**Comment by louislam** [comment]
> How would I execute this? `docker exec -it uptimekuma ` and then?

Should be something like this
`docker exec -it <container name> npm run remove-2fa`

**Comment by kekonn** [comment]
That removed the 2FA alright. I tried enabling it again, but it wouldn't accept the generated code. I am using the BitWarden browser extension to generate TOTP passwords. I copy the url into the authenticator key field and click on save.

The generated TOTP code is then not accepted by Kuma. I have checked now and I am on version 1.11.1 btw.

**Comment by louislam** [comment]
As I remember, Bitwarden Mobile is working fine. I did not test BitWarden browser extension though.

**Comment by kekonn** [comment]
That would mean that there is a difference between the url you show (or gets copied) and the information embedded in the QR code. I will investigate a bit further

**Comment by kekonn** [comment]
I have traced the issue to a timezone setting issue in unRaid. When selecting Paris, Brussels etc from the list, it incorrectly sets the timezone to Europe/Paris and apparently that is 10 minutes or so off from Europe/Brussels (which is set on the pc).
