### ISSUE TITLE
[Feature] Allow to specify Resolver Port for DNS Monitor

### ISSUE THREAD

**Issue by spali** [louislam/uptime-kuma#1059]
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

UI Feature, Other

### 🔖 Feature description

Allow to specify Port for the Resolver in a DNS Monitor.

### ✔️ Solution

Simplest would be to allow `:` to specify a port in the Resolver field and pass it down as entered.
If I'm not completely wrong, the underlying code would already support it:
https://github.com/louislam/uptime-kuma/blob/6d6cb2ad494aad7fed29f01cdea715f1c63c2bc4/server/util-server.js#L93
Regarding the Node docs, it would accept a colon already.

### ❓ Alternatives

Separate field for port would be an alternate solution.

### 📝 Additional Context

Currently it's only possible to define an IP. The syntax check if the Resolver field does not allow to specify a port.
In my use-case, I have an "internal" DNS server which is responsible for any internal name lookup's and I have AdGuardHome in front of it to block requests. Because both sit on the same OPNsense instance, the "internal" DNS runs on another port and AdGuardHome is forwarding internal queries to it.
I would like to monitor them independently to easier find the root cause in case of a problem.

**Comment by thomasglauser** [comment]
+1

**Comment by Computroniks** [comment]
I could take a crack at this
