### ISSUE TITLE
Uptime kuma can't monitor the up status of Airdc Webclient

### ISSUE THREAD

**Issue by Horuyuki** [louislam/uptime-kuma#1067]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

So I added a HTTPS for this self hosted app: https://github.com/airdcpp-web/airdcpp-webclient

This is the link of the public demo: https://webdemo.airdcpp.net/login

And adding it into a monitor shows down even though I can visit the site. Any ideas?

### 🐻 Uptime-Kuma Version

1.10.0

### 💻 Operating System and Arch

Ubuntu

### 🌐 Browser

Firefox

### 🐋 Docker Version

Latest Portainer

**Comment by chakflying** [comment]
This is a bug on the target server where it doesn't work with request header `Accept: */*`.

**Comment by rezzorix** [comment]
If you curl this website then it gives you 2 headers:
_(If you dont have a shell on hand you could you this: https://reqbin.com/curl)_

```
HTTP/1.1 200 OK
HTTP/1.1 404 Invalid file path (hint: use "Accept: text/html" if you want index.html)
Server: nginx/1.16.0
Date: Thu, 16 Dec 2021 04:46:47 GMT
Content-Length: 72
Connection: keep-alive

Invalid file path (hint: use "Accept: text/html" if you want index.html)
```

Add the following to the "Headers" section in Uptime-Kuma and you will get the correct status:

`{
    "Accept": "text/html"
}`

**Comment by rezzorix** [comment]
> This is a bug on the target server where it doesn't work with request header `Accept: */*`.

It is not a bug, I think it is intended as they are specifically mention a "hint" in their error message.
See my above answer.

**Comment by louislam** [comment]
Interesting, I just checked how Chrome deal with it.

Turn out that Chrome request with a following header:
```
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9
```

**Comment by louislam** [comment]
Improved, will be released in the next version. Thank you for your report.

**Comment by Joshfindit** [comment]
Just popping in to say thanks for this. For my particular use-case (Neo4j) I ended up overriding `Accept` with "Accept": "application/json"`. That returned the JSON and keyword search matched.

Also thanks to everyone who made the choice to build the options object in a way that the users could override the keys.

**Comment by louislam** [comment]
> Just popping in to say thanks for this. For my particular use-case (Neo4j) I ended up overriding `Accept` with "Accept": "application/json"`. That returned the JSON and keyword search matched.
> 
> Also thanks to everyone who made the choice to build the options object in a way that the users could override the keys.

Nice, you found this post from Google?

**Comment by Joshfindit** [comment]
> Nice, you found this post from Google?

I actually ended up going through every issue that mentioned the http(s) request. I added multiple keywords to my reply so that the next users might be able to google easily
