### ISSUE TITLE
Second or Third Inciedent Field

### ISSUE THREAD

**Issue by V1P-J0K3R** [louislam/uptime-kuma#1069]
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

New Notification, UI Feature

### 🔖 Feature description

It would be Great if you can add a Second Incident or Notification Field on the Status Site.

### ✔️ Solution

Second or Third Info Field in Top of Uptime Kuma

**Comment by koen20** [comment]
Duplicate of #579
