### ISSUE TITLE
Change Uptime Kuma Head User-Agent

### ISSUE THREAD

**Issue by dono-zz** [louislam/uptime-kuma#1070]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

I am looking for a configuration example for json head user-agent instead "uptime-kuma" that blocked by cloudflare or what ever is that using `User-Agent: Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.111 Safari/537.36`

Example case to add http(s) keyword on content: https://www.globalincidentmap.com/

It said just down.

thanks in advance

### 🐻 Uptime-Kuma Version

1.10

### 💻 Operating System and Arch

Centos

### 🌐 Browser

Chrome

### 🟩 NodeJS Version

14.18

**Comment by rezzorix** [comment]
> ### ⚠️ Please verify that this bug has NOT been raised before.
>     ❗ 

I dont believe you checked... 😉 

There was a similar issue just in recent days: https://github.com/louislam/uptime-kuma/issues/1067

I think @louislam already implemented some changes for a future version.

In the meantime you can adjust and send any headers you need/like in the "Headers"-Section of every monitor.

**Comment by louislam** [comment]
> > ### ⚠️ Please verify that this bug has NOT been raised before.
> > ```
> > ❗ 
> > ```
> 
> I dont believe you checked... 😉
> 
> There was a similar issue just in recent days: #1067
> 
> I think @louislam already implemented some changes for a future version.
> 
> In the meantime you can adjust and send any headers you need/like in the "Headers"-Section of every monitor.

Should be a different request. 

But as @rezzorix said, op could change the user-agent in the header textarea,
