### ISSUE TITLE
Change logging to warning or error

### ISSUE THREAD

**Issue by agneevX** [louislam/uptime-kuma#1072]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

Uptime-kuma writes a new line to stdout for each measurement. 

This makes very frequent writes.

Would be nice to set log levels to either of `DEBUG`, `INFO`, `WARN` or `ERROR`, if that's not already possible.

### 🐻 Uptime-Kuma Version

-

### 💻 Operating System and Arch

-

### 🌐 Browser

-

**Comment by ivanbratovic** [comment]
This is related to a currently open PR #910

**Comment by thueske** [comment]
Any news on this @ivanbratovic @louislam?

Especially on devices like Raspberry Pi it would be nice to have as few write accesses as possible. However, the logs become significantly large with many monitors due to the log level. It would be nice if this could be configured via environment variables.

**Comment by flok** [comment]
> Any news on this @ivanbratovic @louislam?
> 
> Especially on devices like Raspberry Pi it would be nice to have as few write accesses as possible. However, the logs become significantly large with many monitors due to the log level. It would be nice if this could be configured via environment variables.

if you want an easy fix just add the environment variable to the docker

`UPTIME_KUMA_HIDE_LOG=debug_monitor,info_monitor`

This disables the INFO log for the Successful Response

**Comment by thueske** [comment]
Very nice! Thank you. Are there any docs about the env?

**Comment by louislam** [comment]
> Very nice! Thank you. Are there any docs about the env?

It can be found in the wiki.



I also noticed that the log is large, because it includes datetime and maybe too detailed. I am thinking whether disabling it or showing less info.

**Comment by thueske** [comment]
> > Very nice! Thank you. Are there any docs about the env?
> 
> It can be found in the wiki.
> 
> I also noticed that the log is large, because it includes datetime and maybe too detailed. I am thinking whether disabling it or showing less info.

Thanks, good to know! Very nice project btw.
