### ISSUE TITLE
Make the DNS check also validate a specific record value

### ISSUE THREAD

**Issue by d3xt3r01** [louislam/uptime-kuma#1081]
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

UI Feature

### 🔖 Feature description

I'd like to be able to validate the dns reply value also, not just that there is an answer

### ✔️ Solution

I'd like to be able to specify the expected value (optional) for a dns check

**Comment by reitermarkus** [comment]
Would we very useful for monitoring whether my LanCache is working as intended.

**Comment by m0dd3r43v3r** [comment]
This would be amazing to monitor unexpected DNS changes by registrar.

**Comment by cocoonkid** [comment]
This would be super useful indeed.

**Comment by jemand771** [comment]
while the suggested config options are different, this feels similar to #432 
also note that another possible solution was/is being discussed in #518

**Comment by CommanderStorm** [comment]
@d3xt3r01 
I think this is a duplicate of https://github.com/louislam/uptime-kuma/issues/432
If you agree, could you please close this Issue, as duplicates only create immortal zombies and are really hard to issue-manage?
If not, what makes this issue unique enough to require an additional issue? (Could this be integrated into the issue linked above?) ^^

**Comment by d3xt3r01** [comment]
See #432
