### ISSUE TITLE
Ability to add status badges for specified websites

### ISSUE THREAD

**Issue by StrangeRanger** [louislam/uptime-kuma#1084]
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

API, Other

### 🔖 Feature description

Similar to how Up Time Robot has done it, create a feature allowing you to place badges on external web pages, displaying the status of a specified website that has already been configured on an instance of Uptime-Kuma.

### ✔️ Solution

I want to be able to place badges/tags on web pages displaying the status of any one of the websites that I have my instance monitoring. I see this more as a feature relying on an API, but I do remember one of the motivations of this project being to use WebSockets over the REST API, so I'm unsure how this feature would be implemented.

**Comment by fbartels** [comment]
Feature was implemented in https://github.com/louislam/uptime-kuma/pull/1119

**Comment by StrangeRanger** [comment]
Thanks you for letting me know. Was meaning to close this issue when I saw the changelog, but forgot.
