### ISSUE TITLE
Autoclose alert

### ISSUE THREAD

**Issue by duylong** [louislam/uptime-kuma#1085]
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

UI Feature

### 🔖 Feature description

Autoclose alert popup after a defined time. This is useful if the page is displayed on a TV screen for example. 

### ✔️ Solution

Add a timeout option in the configuration. Default timeout to 1min ?

**Comment by trogper** [comment]
please explain what do you mean by the autoclose. What is being closed and when?

**Comment by nekitoblack** [comment]
> @trogper : please explain what do you mean by the autoclose. What is being closed and when?

Usually when a server goes down, the alert remains visible on the screen..
And, when you add a new server, modify something (or a server goes up again), the success alert disappear (auto close) after a few seconds.

---
My personal fix for that alerts, was modify the `index.html` for add jQuery (I was lazy that day for write vanilla JS in that moment) for add minimal aditional functions and also, just for click the close button each 1 minute based on the class name (just for avoid modify another files and just backup that one file when required)
