### ISSUE TITLE
Webpage checksum check

### ISSUE THREAD

**Issue by xpliz** [louislam/uptime-kuma#1091]
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

New Monitor

### 🔖 Feature description

It would be nice if http monitor type offered checksum option for a page content. 

Keywords are fine but they don't offer much detection if things go wrong with css or minify, which checksum should notice.

### ✔️ Solution

Someone wrote a util for monit - monitoring utility which represents what I would like with more words and example.

https://prefetch.net/blog/2006/07/21/verifying-site-content-with-checksums/

### ❓ Alternatives

-

### 📝 Additional Context

-

**Comment by trogper** [comment]
I think it is too specific usecase to monitor checksum of a webpage that a very few people will use. This would apply only for static pages and would require changing the monitor settings every time you change a single byte.
I suggest you to use heartbeat monitor with cron job bash script. The script will implement the checksum calculation and push successful result to kuma using the heartbeat monitor.

**Comment by trogper** [comment]
duplicate #1064

**Comment by CommanderStorm** [comment]
@xpliz Given that this is a duplicate issue, could you please close this Issue, as duplicates only create immortal zombies and are really hard to issue-manage?
If not, what makes this issue unique enough to require an additional issue? (Could this be integrated into the issue linked above?) ^^
