### ISSUE TITLE
Is there a way to view incident history?

### ISSUE THREAD

**Issue by dillfrescott** [louislam/uptime-kuma#1100]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

A list of unpinned incidents.

### 🐻 Uptime-Kuma Version

1.11.1

### 💻 Operating System and Arch

Ubuntu 20.04 LTS

### 🌐 Browser

Firefox Nightly

### 🐋 Docker Version

Latest version

### 🟩 NodeJS Version

n/a

**Comment by jamesmacwhite** [comment]
All created incidents are stored in the `incidents` table in the SQLite DB, with their title, content, created date, type (style i.e. warning/info etc), so the data is there, but there isn't any front end for viewing past incidents currently I don't think.

**Comment by RangersMS** [comment]
+1

**Comment by RangersMS** [comment]
I would love to see that feature too. Maybe even expanding incidents with updates like initial incident, issue found, watching and fixed. Or is this a new feature request?

**Comment by ricardosorroche** [comment]
+1

**Comment by Zyphrono** [comment]
+1

**Comment by DillFrescott** [comment]
Are we any closer to having this feature?

**Comment by dillfrescott** [comment]
comment

**Comment by haihq88** [comment]
+1

**Comment by feriahmad** [comment]
+1

**Comment by paquinoofferwise** [comment]
+1

**Comment by MasonColoretti** [comment]
currently have an open pr for this https://github.com/louislam/uptime-kuma/pull/4943
