### ISSUE TITLE
Editing check type causes monitor to vanish from Quick Stats

### ISSUE THREAD

**Issue by bt90** [louislam/uptime-kuma#1103]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### Description

I've edited a couple of monitors and switched them from simple Ping to HTTP(S) checks. While this worked perfectly fine in the status page and the left list in the dashboard, i couldn't find them in the quick stats anymore.

I did a full page refresh(ctrl+f5) but couldn't get them to show up again. The checks have been carried out just fine though and i can open the details with the left listing in the dashboard.

### 👟 Reproduction steps

1. Create a ping monitor
2. Switch it to HTTP(S)
3. The monitor disappears from the quick stats

### 👀 Expected behavior

The quick stats should display the values of the edited monitor.

### 😓 Actual Behavior

The monitor completely vanishes from the quick stats.

### 🐻 Uptime-Kuma Version

1.11.1

### 💻 Operating System and Arch

Ubuntu 20.04

### 🌐 Browser

Firefox 95

**Comment by chakflying** [comment]
Can't reproduce on master. Do you mean the total number of monitors in the Quick Stats decreased after you changed a monitor type?

**Comment by bt90** [comment]
The monitor itself isn't part of the list anymore. I also tried a to search it using ctrl+f because i didn't trust my eyes but Firefox could only find it in the left pane.

**Comment by chakflying** [comment]
I think what you are referring to is in fact the "Notable Events" list, which will only update if there is a UP/DOWN change on a monitor. There was discussion before about this being confusing, but no improvement has been implemented yet.

**Comment by bt90** [comment]
Exactly. From a user perspective this is highly confusing. I would have expected that the monitor either sticks with last ping change or that it treats the first HTTP check as the last UP change. As the check is completely changed, it would also be acceptable IMHO to clear the history.
