### ISSUE TITLE
What can I do with body options?

### ISSUE THREAD

**Issue by cyrano007** [louislam/uptime-kuma#1107]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

hi, cool tool.
do you have an example for the body options somewhere?
What can I do with it ?
Can I get return values there e.g. from a healthcheck ?

Thanks for your answer and a happy new year

### 🐻 Uptime-Kuma Version

Version: 1.11.1

### 💻 Operating System and Arch

Ubuntu

### 🌐 Browser

Edge Version 95.0.1020.53 (Offizielles Build) (64-Bit)

### 🐋 Docker Version

Kubernetes Runtme

**Comment by jamesmacwhite** [comment]
Body options are for sending additional data with the request, which may be required for some tests, particularly APIs. For example if you were using an RPC based API, you might need to set a body request, that describes the method being queried.

There is keyword matching functionality under the "HTTP(s) - Keyword" test, that allows you to search for a specific word or phrase from a response. For example a JSON like the example below:

```
{ 
    "result": "success"
}```

You could have a keyword of "success" for the test to match, this would be addition to setting the "accepted status codes" option as 200-299.

**Comment by key-str0ke** [comment]
@jamesmacwhite when testing HTTP(s) - Keyword match with a POST request I have the following post BODY options setup.  This isn't an API call, just a regular POST request.

`{
    "name": "test",
    "email": "test@test.com",
    "attention": "Technical",
    "message": "test"
}`

The curl command works fine.  This doesn't though, not really sure why.  Any ideas?

**Comment by jamesmacwhite** [comment]
What is the HTTP response and the value you used in the keyword field?

**Comment by edworldstar** [comment]
Actually it looks like the POST requests is sent over as json instead of as an actual post request.

`{"name":"test","email":"test@test.com","attention":"Technical","message":"test","g-recaptcha-response":"test"}`

Compared to:

`name=test&email=test%40test.com&attention=Technical&message=test&g-recaptcha-response=test`

**Comment by mathiskir** [comment]
Can this be closed?
