### ISSUE TITLE
How to uninstall

### ISSUE THREAD

**Issue by PandaMC66** [louislam/uptime-kuma#1110]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [x] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

Hey, how can i uninstall Uptime Kuma? 

### 🐻 Uptime-Kuma Version

latest

### 💻 Operating System and Arch

Ubuntu

### 🌐 Browser

OperaGX

**Comment by trogper** [comment]
How did you install? There are multiple options and each has different uninstall procedure

**Comment by PandaMC66** [comment]
I have install it with docker

**Comment by PandaMC66** [comment]
> How did you install? There are multiple options and each has different uninstall procedure

I install it with docker

**Comment by trogper** [comment]
run `docker ps -a`, note the name of your kuma container
run `docker stop container_name`
run `docker rm container_name`
run `docker volume rm uptime-kuma`
run `docker rmi uptime-kuma`

**Comment by only4freedom** [comment]
if not docker
how to uninstall

**Comment by trogper** [comment]
> if not docker how to uninstall

How did you install? What commands?

**Comment by PandaMC66** [comment]
> > if not docker how to uninstall
> 
> 
> 
> How did you install? Which commands?

With the install cmd xD

**Comment by trogper** [comment]
skip the first line if you did not use pm2
```
pm2 stop uptime-kuma
rm -r uptime-kuma
```

**Comment by only4freedom** [comment]
> > if not docker how to uninstall
> 
> How did you install? Which commands?

[](https://github.com/louislam/uptime-kuma/wiki/%F0%9F%94%A7-How-to-Install#advanced-installation)curl -o kuma_install.sh http://git.kuma.pet/install.sh && sudo bash kuma_install.sh

I USE THIS WAY TO INSTALL

**Comment by louislam** [comment]
> > > if not docker how to uninstall
> > 
> > 
> > How did you install? Which commands?
> 
> curl -o kuma_install.sh http://git.kuma.pet/install.sh && sudo bash kuma_install.sh
> 
> I USE THIS WAY TO INSTALL

1. Stop Uptime Kuma `pm2 stop uptime-kuma`
2. Delete the directory `/opt/uptime-kuma`

**Comment by kiraitachi** [comment]
> > > > if not docker how to uninstall
> > > 
> > > 
> > > How did you install? Which commands?
> > 
> > 
> > curl -o kuma_install.sh http://git.kuma.pet/install.sh && sudo bash kuma_install.sh
> > I USE THIS WAY TO INSTALL
> 
> 1. Stop Uptime Kuma `pm2 stop uptime-kuma`
> 2. Delete the directory `/opt/uptime-kuma`

Sorry for reopening but I installed manually local on /home and then with script manually also in /opt.

When running:

``pm2 status uptime-kuma``

I find 2 instances running although I already deleted the /home/uptime-kuma directory.

How can I delete the first instances which is stopped?

![image](https://user-images.githubusercontent.com/40744673/199132545-a62afe0b-a5ab-4849-bd8a-01da587737e0.png)

**Comment by mr-bolle** [comment]
Hi @kiraitachi,

could you try `pm2 delete 0` than you can remove the first instance of uptime-kuma

```
$ pm2 status uptime-kuma
┌─────┬──────────────────┬─────────────┬─────────┬─────────┬──────────┬────────┬──────┬───────────┬──────────┬──────────┬──────────┬──────────┐
│ id  │ name             │ namespace   │ version │ mode    │ pid      │ uptime │ ↺    │ status    │ cpu      │ mem      │ user     │ watching │
├─────┼──────────────────┼─────────────┼─────────┼─────────┼──────────┼────────┼──────┼───────────┼──────────┼──────────┼──────────┼──────────┤
│ 1   │ uptime-kuma      │ default     │ 1.20.1  │ fork    │ 0        │ 0      │ 7    │ stopped   │ 0%       │ 0b       │ dietpi   │ disabled │
└─────┴──────────────────┴─────────────┴─────────┴─────────┴──────────┴────────┴──────┴───────────┴──────────┴──────────┴──────────┴──────────┘
Module
┌────┬──────────────────────────────┬───────────────┬──────────┬──────────┬──────┬──────────┬──────────┬──────────┐
│ id │ module                       │ version       │ pid      │ status   │ ↺    │ cpu      │ mem      │ user     │
├────┼──────────────────────────────┼───────────────┼──────────┼──────────┼──────┼──────────┼──────────┼──────────┤
│ 0  │ pm2-logrotate                │ 2.7.0         │ 24191    │ online   │ 0    │ 0%       │ 44.4mb   │ dietpi   │
└────┴──────────────────────────────┴───────────────┴──────────┴──────────┴──────┴──────────┴──────────┴──────────┘

dietpi at rp0-pihole in ~
$ pm2 delete 1
[PM2] Applying action deleteProcessId on app [1](ids: [ '1' ])
[PM2] [uptime-kuma](1) ✓
┌─────┬──────────────────┬─────────────┬─────────┬─────────┬──────────┬────────┬──────┬───────────┬──────────┬──────────┬──────────┬──────────┐
│ id  │ name             │ namespace   │ version │ mode    │ pid      │ uptime │ ↺    │ status    │ cpu      │ mem      │ user     │ watching │

```
