### ISSUE TITLE
Pushover notification device not working

### ISSUE THREAD

**Issue by radimsejk** [louislam/uptime-kuma#1114]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

I have set up a Pushover notification and I wanted to use the Device field to specify only my devices. But when the notification is fired it is delivered to every device in my Pushover account.

### 🐻 Uptime-Kuma Version

1.11.1

### 💻 Operating System and Arch

 DietPi v7.9.3

### 🌐 Browser

Chrome 96.0.4664.110

### 🐋 Docker Version

20.10.12

**Comment by kovaga** [comment]
i have come across the same issue. specifyin a device name does not work. the messages are sent to all devices.

**Comment by radimsejk** [comment]
> i have come across the same issue. specifyin a device name does not work. the messages are sent to all devices.

Thank you for confirmation. So it is not my fault but it is a bug.

**Comment by orpheus1120** [comment]
I am having the same issue. Is this bug gonna be fixed soon?
