### ISSUE TITLE
prevent http basic auth fields from being auto-filled

### ISSUE THREAD

**Issue by k4ds3** [louislam/uptime-kuma#1115]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### Description

The problem is that the HTTP basic auth fields in HTTP(S) monitors get auto-filled with the uptime-kuma webinterface credentials.

The reason why this is a problem and even a potential security issue is that this way - if you don't notice it - uptime-kuma sends your credentials to the monitored target which could result in leakage of your credentials.

Mitigating this issue is pretty straightforward: https://developer.mozilla.org/en-US/docs/Web/Security/Securing_your_site/Turning_off_form_autocompletion#the_autocomplete_attribute_and_login_fields

I haven't tested it, but it should be enough to add `autocomplete="off"` to these input fields in question.

### 👟 Reproduction steps

Sign into uptime-kuma, let the browser save your credentials for auto-fill, open the settings of a HTTP(S) monitor, the browser will automatically fill the username and password fields with your uptime-kuma credentials.

### 👀 Expected behavior

The browser should not fill the HTTP Basic Auth fields with your uptime-kuma credentials.

### 😓 Actual Behavior

The browser fills the HTTP Basic Auth fields with your uptime-kuma credentials.

### 🐻 Uptime-Kuma Version

1.11.1

### 💻 Operating System and Arch

Client: Windows 10

### 🌐 Browser

Chrome Dev 98, Firefox 95

**Comment by louislam** [comment]
Duplicate of #1061
