### ISSUE TITLE
Is it possible to have the database outside of docker?

### ISSUE THREAD

**Issue by ClearSEM** [louislam/uptime-kuma#1125]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

Is there a way to have the database running outside of docker?

### 🐻 Uptime-Kuma Version

1.11.1

### 💻 Operating System and Arch

Ubuntu 20.04 LTS

### 🌐 Browser

Google

### 🐋 Docker Version

Docker 20.10.8

### 🟩 NodeJS Version

10.19.0

**Comment by jamesmacwhite** [comment]
When creating your docker container, you can specify a path to store the database:

```
docker volume create uptime-kuma
docker run -d --restart=always -p 3001:3001 -v /home/user/path:/app/data --name uptime-kuma louislam/uptime-kuma:1
```

Where the `-v` parameter, you can specific where you want the data directory and the database to be written to. The only recommendation as per the README.md is don't use a NFS location, needs to be local.

**Comment by ClearSEM** [comment]
Thank you jamesmacwhite, that is exactly what I needed! Now I gotta learn about sqlite!

**Comment by jamesmacwhite** [comment]
@ClearSEM Great, no worries.
