### ISSUE TITLE
Google Chat notification error

### ISSUE THREAD

**Issue by thomasleveil** [louislam/uptime-kuma#1126]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### Description

The new Google Chat notification produces an error upon testing sending a notification

### 👟 Reproduction steps

1. create a notification of type Google Chat
2. click the test button

### 👀 Expected behavior

a notification is sent to Google Chat

### 😓 Actual Behavior

an error is shown :  `Error: Notification type is not supported`

### 🐻 Uptime-Kuma Version

1.11.2

### 💻 Operating System and Arch

docker

### 🌐 Browser

Google Chrome 96.0.4664.110 (Build officiel) (32 bits)

### 🐋 Docker Version

20.10.12

### 📝 Relevant log output

```shell
server log


kuma_1    | Error: Notification type is not supported
kuma_1    |     at Function.send (/app/server/notification.js:96:19)
kuma_1    |     at Socket.<anonymous> (/app/server/server.js:1036:46)
kuma_1    |     at Socket.emit (events.js:400:28)
kuma_1    |     at Socket.emitUntyped (/app/node_modules/socket.io/dist/typed-events.js:69:22)
kuma_1    |     at /app/node_modules/socket.io/dist/socket.js:428:39
kuma_1    |     at processTicksAndRejections (internal/process/task_queues.js:77:11)
```
```

**Comment by thomasleveil** [comment]
Looking at the data by exporting a backup, I discovered that the type of the notification is `Google Chat (Google Workspace only)` instead of `Google Chat`.

```json
{
    "version": "1.11.2",
    "notificationList": [
        {
            "id": 1,
            "name": "Google Chat \"test\"",
            "config": "{\"name\":\"Google Chat \\\"test\\\"\",\"type\":\"Google Chat (Google Workspace only)\",\"isDefault\":true,\"appriseURL\":\"https://chat.googleapis.com/v1/spaces/xxxxxx/messages?key=xxxxxxx&token=xxxxxxx\",\"applyExisting\":false,\"googleChatWebhookURL\":\"https://chat.googleapis.com/v1/spaces/xxxxxx/messages?key=xxxxxxxx&token=xxxxxxx\"}",
            "active": 1,
            "userId": 1,
            "isDefault": 1
        }
]
}
```

This seems to be a regression introduced with https://github.com/louislam/uptime-kuma/commit/f6fc3737fcb7d27582bd0dde6732157efc43138f#diff-4635d2896a4302c16ae5deb9f7075a0183ba388f249f1850a86fccb0efd66e6fR61

But the fix is probably to make sure the correct type is considered when creating a new notification

**Comment by bilipp** [comment]
True, I now extracted the translation for the notification type to the translation files and fixed the mismatch for the type in the notification provider. Once the PR https://github.com/louislam/uptime-kuma/pull/1130 is merged, it will work again.

**Comment by thomasleveil** [comment]
Thank you @bilipp, unfortunately there is still an error when sending Google Chat notification. This time the error in the server log is : `Error: TypeError: Cannot read property 'id' of null`

```
kuma_1    | Error: Error: TypeError: Cannot read property 'id' of null 
kuma_1    |     at GoogleChat.throwGeneralAxiosError (/app/server/notification-providers/notification-provider.js:32:15)
kuma_1    |     at GoogleChat.send (/app/server/notification-providers/google-chat.js:41:18)
kuma_1    |     at async Socket.<anonymous> (/app/server/server.js:1036:27)
```
see https://github.com/louislam/uptime-kuma/blob/master/server/notification-providers/google-chat.js#L31

the notification settings data is : 

```
        {
            "id": 4,
            "name": "test",
            "config": "{\"name\":\"test\",\"type\":\"GoogleChat\",\"isDefault\":false,\"googleChatWebhookURL\":\"https://chat.googleapis.com/v1/spaces/xxxxx/messages?key=xxxxxx&token=xxxxxxx\"}",
            "active": 1,
            "userId": 1,
            "isDefault": 0
        }
```
