### ISSUE TITLE
Clearing Event Data - No Refreshed Status Showing

### ISSUE THREAD

**Issue by cfitzw** [louislam/uptime-kuma#1128]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### Description

After using the Clear Data > Events button, the monitor fails to refresh with the latest status again, including the status page itself.

### 👟 Reproduction steps

Reproduce by (via https://demo.uptime.kuma.pet):
1.  Create an HTTP(S) monitor
2.  Ensure you have 200 - OK status
3.  Clear Data > Events
4.  Stays in a "No important events" state; no new/refreshed status, meaning it also does not show on the Status Page

### 👀 Expected behavior

After removing the event data, it should trigger to poll to get the latest state again.

### 😓 Actual Behavior

Stays in a "No important events" state; no new/refreshed status, meaning it also does not show on the Status Page

### 🐻 Uptime-Kuma Version

1.11.1

### 💻 Operating System and Arch

Ubuntu 20.04

### 🌐 Browser

Firefox

### 🐋 Docker Version

20.10.12

**Comment by louislam** [comment]
I believe that It is how the function works.

**Comment by cfitzw** [comment]
@louislam Should this then be a feature request? It seems it should give an up-to-date status after purging the history, otherwise it goes missing from the status page.
