### ISSUE TITLE
Docker upgrade to 1.11.2 causes restart loop (Email/DKIM related)

### ISSUE THREAD

**Issue by jamesmacwhite** [louislam/uptime-kuma#1129]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### Description

My Docker instance auto updated to 1.11.2 via watchtower and it caused Uptime Kuma to be in a restart loop. The error below captured from the console logs seems to be the reason, the stacktrace seems to relate to email related functionality, given it's nodemailer with reference to DKIM. I do currently have an email notifier enabled.

Downgrading the container to 1.11.1 allows Uptime Kuma to start correctly.

### 👟 Reproduction steps

1. Upgrade Docker container to 1.11.2
2. Observe restart loop, referencing nodemailer/DKIM properties.

### 👀 Expected behavior

Uptime Kuma to start up correctly without restart looping

### 😓 Actual Behavior

Stacktrace and restart loop related to nodemailer.

### 🐻 Uptime-Kuma Version

1.11.2

### 💻 Operating System and Arch

macOS 15.7

### 🌐 Browser

Chrome 96.0.4664.110

### 🐋 Docker Version

Docker Desktop 4.3.2

### 📝 Relevant log output

```shell
punycode.js:73
	const parts = string.split('@');
	                     ^

TypeError: Cannot read property 'split' of undefined
    at mapDomain (punycode.js:73:23)
    at Object.toASCII (punycode.js:406:9)
    at generateDKIMHeader (/app/node_modules/nodemailer/lib/dkim/sign.js:58:25)
    at module.exports (/app/node_modules/nodemailer/lib/dkim/sign.js:34:22)
    at signNextKey (/app/node_modules/nodemailer/lib/dkim/index.js:114:29)
    at DKIMSigner.sendSignedOutput (/app/node_modules/nodemailer/lib/dkim/index.js:128:20)
    at RelaxedBody.<anonymous> (/app/node_modules/nodemailer/lib/dkim/index.js:191:18)
    at RelaxedBody.emit (events.js:400:28)
    at endReadableNT (internal/streams/readable.js:1334:12)
    at processTicksAndRejections (internal/process/task_queues.js:82:21)
```

**Comment by jamesmacwhite** [comment]
I'm going to potentially suggest it might be related to this commit:

https://github.com/louislam/uptime-kuma/pull/1080/commits/624cd862a5e38980cfce5b25b78acc0451ea45dc

**Comment by jamesmacwhite** [comment]
@louislam Thank you for pushing out a new release so quickly to fix this. I can confirm, 1.11.3 runs great.

**Comment by zsinba** [comment]
The question came up again

**Comment by CommanderStorm** [comment]
> The question came up again

@zsinba Could you please open another Issue with a full bug report? Currently this is too little information do debug on
