### ISSUE TITLE
Unusual Detection

### ISSUE THREAD

**Issue by caotangdaiduong** [louislam/uptime-kuma#1132]
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

UI Feature

### 🔖 Feature description

The Unusual Detection calculates the average (for example 1 hour) from the last measurement on, and then compares it with the current (hourly) average.

### ✔️ Solution

Calculates the average or set threshold value for sensor.

**Comment by CommanderStorm** [comment]
@caotangdaiduong 
We are consolidating duplicate issues a bit to make issue management easier.
I think, we should track this issue in #1813 as there is no functional difference (maybe just small naming differences, but nothing that would require a different issue imo)
⇒ I am going to close this as a duplicate.
