### ISSUE TITLE
Monitor filter online and offline

### ISSUE THREAD

**Issue by Titintgn** [louislam/uptime-kuma#1134]
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

UI Feature

### 🔖 Feature description

If you have several monitors down, you have to look at the list by hand which ones are not working. 

### ✔️ Solution

In fast statistic, clicking on the offline monitors will show us which are only

**Comment by ashupp** [comment]
Was about to write the exact same. 
Could be also possible to put a quickfilter to show only offline monitors next to the search bar above the monitors list.

**Comment by rob1998** [comment]
+1

**Comment by jaspercuvelier** [comment]
+2 ;-)

**Comment by vipii** [comment]
+3 :-)

**Comment by luckman212** [comment]
+4

**Comment by llimz** [comment]
Filtering offline by clicking on the Down count is a great idea and a must have when you have (a lot) of monitors ;o)

**Comment by Devineavenger** [comment]
+5

**Comment by CommanderStorm** [comment]
This issue seeems very similar to #1585 which has an open PR (#1971).

@Titintgn if you agree please close this issue, 


@Devineavenger @llimz @luckman212 @vipii @jaspercuvelier @rob1998 
Please refrain from posting `+1` / requests for updates things on issues, as this makes issue-management harder.
Issues are for discussing what needs to be done how by whom.
[We use 👍🏻 on issues to prioritise work](https://github.com/louislam/uptime-kuma/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).

**Comment by borgogelli** [comment]
+1
