### ISSUE TITLE
iframe display not supported

### ISSUE THREAD

**Issue by bigcookie** [louislam/uptime-kuma#1135]
I am using uptime-kuma in an internal network and would like to display the status page inside "Home Assistant", which works via iframe...
Currently I receive an err_blocked_by_response - this seems to be due to a x-frame-options setting (X-Frame-Options: SAMEORIGIN)
https://stackoverflow.com/questions/44572387/failed-to-load-resource-neterr-blocked-by-response

Not sure if this is intended and no bug or not intended and a bug.

**Comment by chakflying** [comment]
See comment of #851

**Comment by bigcookie** [comment]
Thanks @chakflying ,

I found a way by checking the source code. There are environmental Arguments  I can provide in the docker setup to turn this off and make my use case functioning.
I am aware of the security issues, though you can also call a short pho scriot in iframe which calls the header protected site :-).

i added the env variable „ UPTIME_KUMA_DISABLE_FRAME_SAMEORIGIN=true“
And now I can see the status page in my Home Assistant setup :-).

of course settings etc are available, but works for me.

thanks again!

**Comment by KRider92** [comment]
Hi @bigcookie - I've tried the same as you, but it doesn't want to work for me...

I've tried with the following command line:
`docker run -d --restart=always -p 8080:3001 -e UPTIME_KUMA_DISABLE_FRAME_SAMEORIGIN='true' -v uptime-kuma-Internet:/app/data --name uk-Internet louislam/uptime-kuma:1`

as well as the values:
- true
- 'true'
- 1
- '1'

but none work... Can you help me out?

**Comment by bigcookie** [comment]
Hello Marian,

 

please check out https://github.com/louislam/uptime-kuma/issues/1142

(Just found this).

 

Example from the page:

docker run -d -e UPTIME_KUMA_DISABLE_FRAME_SAMEORIGIN=1 --restart=always -p 8080:3001 -v uptime-kuma-Internet:/app/data --name uk-Internet louislam/uptime-kuma:1


 

Probably the order makes a difference. I checked on my docker setup and 

 

This


docker inspect --format '{{ (index .Config.Env) }}' CONTAINER_ID

give me

[NODE_VERSION=14.18.2 PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin YARN_VERSION=1.22.15 UPTIME_KUMA_DISABLE_FRAME_SAMEORIGIN=true]

so the environmental variable "UPTIME_KUMA_DISABLE_FRAME_SAMEORIGIN=true" is being respected.

Probably you need to use latest uptime-kuma?

regards,

André


 


 
 

Gesendet: Freitag, 07. Januar 2022 um 23:54 Uhr
Von: "Marian Lein" ***@***.***>
An: "louislam/uptime-kuma" ***@***.***>
Cc: "bigcookie" ***@***.***>, "Mention" ***@***.***>
Betreff: Re: [louislam/uptime-kuma] iframe display not supported (Issue #1135)


 

Hi @bigcookie - I've tried the same as you, but it doesn't want to work for me...

I've tried with the following command line:
docker run -d --restart=always -p 8080:3001 -e UPTIME_KUMA_DISABLE_FRAME_SAMEORIGIN='true' -v uptime-kuma-Internet:/app/data --name uk-Internet louislam/uptime-kuma:1

as well as the values:


	true
	'true'
	1
	'1'


but none work... Can you help me out?

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by KRider92** [comment]
> please check out #1142 (Just found this).
Yeah, that's been my topic as well - It's now solved, but thanks @bigcookie

**Comment by svewag** [comment]
ℹ️  The value has to be set to `1` and not to `true`.

`UPTIME_KUMA_DISABLE_FRAME_SAMEORIGIN=1`

At least this was the case in my lxc container.

**Comment by AJolly** [comment]
Is there a way to set this for the uptime kuma HA addon easily?
