### ISSUE TITLE
Introduction of new environment variables for HOST and PORT add non-overridable regression to kubernetes deployments

### ISSUE THREAD

**Issue by marcules** [louislam/uptime-kuma#1138]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### Description

The introduction of UPTIME_KUMA_PORT introduces a regression in kubernetes deployments, if the deployment is called "uptime-kuma" kubernetes will auto-generate the environment variable UPTIME_KUMA_PORT with a non-parsable value for parseInt()

![image](https://user-images.githubusercontent.com/2453108/148581746-059901dc-0feb-422d-aed1-8f2ab60b754a.png)

The commit that introduces environment variable parsing is here:
https://github.com/louislam/uptime-kuma/commit/f75c9e4f0ca4f7417ea0c7f2184be4dd1332be05#diff-8cf1ffe3788af127768748703e2f15dcfb3a05ffd20b4c2375223637e3260938R75

Similar issue reported here:

- https://github.com/louislam/uptime-kuma/issues/741
- https://github.com/louislam/uptime-kuma/issues/1040
- https://github.com/louislam/uptime-kuma/issues/1118 (no real / feasible resolution in ticket)

Similar issue in helm repository:
https://github.com/dirsigler/uptime-kuma-helm/issues/26 (has the name of the deployment set to "uptime-kuma", see `kubelet                  Created container uptime-kuma`)

Similar issue with redis:
https://github.com/kubernetes/kubernetes/issues/60099#issuecomment-384767701

JavaScript will only "skip" the values, if they are not set with the current implementation, but produces a NaN value, if one of the values inside the else-shorthand is set.

![image](https://user-images.githubusercontent.com/2453108/148581155-974dde68-b49e-43d1-83c3-8696c95c7950.png)

As a proposal, please either change the order in which the parameters are parsed (so it can be overridden in the deployment manifest in kubernetes) or implement it with validation, e.g. like this:

    const port = [process.env.UPTIME_KUMA_PORT, process.env.PORT, args.port, 3001].map(el => parseInt(el)).find(el => !isNaN(el));

![image](https://user-images.githubusercontent.com/2453108/148581199-391852fa-9218-46b7-bce7-4faa8e3a339b.png)

### 👟 Reproduction steps

- Create an environment variable named UPTIME_KUMA_PORT with a non-integer value
- Start server

### 👀 Expected behavior

Uptime Kuma will fall back to the next parsable integer value in the priority list
(UPTIME_KUMA_PORT -> PORT -> ARGS.PORT -> 3001)

### 😓 Actual Behavior

Uptime Kuma crashes with the port being NaN

### 🐻 Uptime-Kuma Version

1.11.1-alpine

### 💻 Operating System and Arch

node:14-alpine3.12

### 🌐 Browser

none

### 🐋 Docker Version

k8s

### 📝 Relevant log output

```shell
Load JWT secret from database.
No user, need setup
Adding route
Adding socket handler
Init the server
Trace: RangeError [ERR_SOCKET_BAD_PORT]: options.port should be >= 0 and < 65536. Received NaN.
    at new NodeError (internal/errors.js:322:7)
    at validatePort (internal/validators.js:216:11)
    at Server.listen (net.js:1457:5)
    at /app/server/server.js:1336:12 {
  code: 'ERR_SOCKET_BAD_PORT'
}
    at process.<anonymous> (/app/server/server.js:1542:13)
    at process.emit (events.js:400:28)
    at processPromiseRejections (internal/process/promises.js:245:33)
    at processTicksAndRejections (internal/process/task_queues.js:96:32)
If you keep encountering errors, please report to https://github.com/louislam/uptime-kuma/issues
Shutdown requested
Called signal: SIGTERM
Stopping all monitors
Trace: Error [ERR_SERVER_NOT_RUNNING]: Server is not running.
    at new NodeError (internal/errors.js:322:7)
    at Server.close (net.js:1624:12)
    at Object.onceWrapper (events.js:519:28)
    at Server.emit (events.js:412:35)
    at emitCloseNT (net.js:1677:8)
    at processTicksAndRejections (internal/process/task_queues.js:81:21) {
  code: 'ERR_SERVER_NOT_RUNNING'
}
    at process.<anonymous> (/app/server/server.js:1542:13)
    at process.emit (events.js:400:28)
    at processPromiseRejections (internal/process/promises.js:245:33)
    at processTicksAndRejections (internal/process/task_queues.js:96:32)
If you keep encountering errors, please report to https://github.com/louislam/uptime-kuma/issues
Closing the database
SQLite closed
Graceful shutdown successful!
```

**Comment by chakflying** [comment]
Your fix for avoiding NaN looks good to me! Would you like to create a PR for this?
