### ISSUE TITLE
No-Send notification option

### ISSUE THREAD

**Issue by LeSupaPoney** [louislam/uptime-kuma#1140]
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

Other

### 🔖 Feature description

Hello,

Add an option to temporarily disable notifications between 2 moments.
I have an important server that I have to monitore every 20seconds but every night I have to reboot it.
It takes about 2 minutes to be up again.

### ✔️ Solution

Example:
When create/edit notification, a case "Disable between" to check and 2 boxes: 2:40am / 03:00am
So if the server is down at 2:40am it will not notify, and after 03:00am it reworks as usual

**Comment by chakflying** [comment]
Duplicate of #191

**Comment by LeSupaPoney** [comment]
Oops my bad, I checked and did not found it, thanks.
Sorry
