### ISSUE TITLE
iFrame embedding not working

### ISSUE THREAD

**Issue by KRider92** [louislam/uptime-kuma#1142]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

I'm running four instances of uptime-kuma as docker containers on a Raspberry Pi.
In order to have them displayed side-by-side I'm using iFrames in HTML
```
<html>
	<head>
	</head>
	<body>
		<iframe style="width:25%; height:99%; border:0" scrolling="no" src="//10.0.2.240:8080/list">Internet</iframe>
		<iframe style="width:25%; height:99%; border:0" scrolling="no" src="//10.0.2.240:8081/list">Infrastructure</iframe>
		<iframe style="width:25%; height:99%; border:0" scrolling="no" src="//10.0.2.240:8082/list">Smart Home</iframe>
		<iframe style="width:24%; height:99%; border:0" scrolling="no" src="//10.0.2.240:8083/list">RasPi</iframe>
	</body>
</html>
```
Trying several values for the environment variable, such as `1`, `'1'`, `true`, `'true'`, `TRUE `and `'TRUE'` the iframes are still empty.

To run the docker containers, I'm using these commands:
```
docker run -d -e UPTIME_KUMA_DISABLE_FRAME_SAMEORIGIN=1 --restart=always -p 8080:3001 -v uptime-kuma-Internet:/app/data --name uk-Internet louislam/uptime-kuma:1
docker run -d -e UPTIME_KUMA_DISABLE_FRAME_SAMEORIGIN=1 --restart=always -p 8081:3001 -v uptime-kuma-Infrastructure:/app/data --name uk-Infrastructure louislam/uptime-kuma:1
docker run -d -e UPTIME_KUMA_DISABLE_FRAME_SAMEORIGIN=1 --restart=always -p 8082:3001 -v uptime-kuma-SmartHome:/app/data --name uk-SmartHome louislam/uptime-kuma:1
docker run -d -e UPTIME_KUMA_DISABLE_FRAME_SAMEORIGIN=1 --restart=always -p 8083:3001 -v uptime-kuma-RasPi:/app/data --name uk-RasPi louislam/uptime-kuma:1
```
I've even pruned my whole docker setup, but no avail, the issue stays the same. Can anyone help me?

### 🐻 Uptime-Kuma Version

1.11.3

### 💻 Operating System and Arch

Raspbian Linux 5.10.89-v7l+

### 🌐 Browser

Google Chrome

### 🐋 Docker Version

20.10.12

### 🟩 NodeJS Version

v10.24.0

**Comment by KRider92** [comment]
Already saw & read about this in #1135 #851 #245 #234, but still couldn't get it working.

**Comment by chakflying** [comment]
Your iframe src is missing `http:`. Did you try having that in?

**Comment by KRider92** [comment]
GOD damn it...
Thanks, how could I have missed this >.<

**Comment by KRider92** [comment]
Final iFrame code:
```
<html>
	<head>
	</head>
	<body>
		<iframe style="width:25%; height:99%; border:0" scrolling="no" src="http://10.0.2.240:8080/list">Internet</iframe>
		<iframe style="width:25%; height:99%; border:0" scrolling="no" src="http://10.0.2.240:8081/list">Infrastructure</iframe>
		<iframe style="width:25%; height:99%; border:0" scrolling="no" src="http://10.0.2.240:8082/list">Smart Home</iframe>
		<iframe style="width:24%; height:99%; border:0" scrolling="no" src="http://10.0.2.240:8083/list">RasPi</iframe>
	</body>
</html>
```
