### ISSUE TITLE
Heartbeat Interval should have a max allowed value.

### ISSUE THREAD

**Issue by xpufx** [louislam/uptime-kuma#1145]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### Description

(I actually did not read the security policy. this is not a security issue)

I tried to get Uptime Kuma Push mode and wanted it to wait for a request indefinetely. Tried setting interval to 0 which is not supported. Then I entered a random large number and noticed after a certain point uptime kuma started actingn as if I had entered fractions of a second. Browser cpu usage shot up and the heartbeat bar went crazy. It happens with 10000000000000  seconds (if you remove one zero it doesn't happen. Something must be flipping in the calculation around there.)

In short heartbeat interval shoud not accept an arbitrarily large value. 10000000000000  seconds is close to 317 million years and the interface allows going way past that.

In addition, could a 0 value be accepted? I am not sure if all monitoring would stop currently - even when a push request comes in. A passive check like the push service should work without an interval set in my opinion. One possible scenario being to only push a status when something fails.

### 👟 Reproduction steps

Set hearbeat interval to >= 10000000000000  . I did not try to find the actual turning point. Lower values can trigger the same.

### 👀 Expected behavior

I expected it to wait 387 millenia between heartbeats.

### 😓 Actual Behavior

It started checking heartbeat status many times per second.

### 🐻 Uptime-Kuma Version

1.11.3

### 💻 Operating System and Arch

docker image

### 🌐 Browser

firefox 95.0.2

### 🐋 Docker Version

20.10.12

### 📝 Relevant log output

```shell
Did not check.
```

**Comment by louislam** [comment]
> I ran into this scenario by accident. I was looking to setup a passive monitor that expects a ping from a cron script that's going to run every 28 days (+ 1 hour grace) = 2422800 seconds. As described here, the UI became unresponsive and server CPU spiked, almost like it was stuck in a loop.
> 
> `2147483` is the highest value before the problem occurs. Interestingly, that might have something to do with [signed 32-bit integers](https://en.wikipedia.org/wiki/2,147,483,647#In_computing). `2073600` seconds (24 days) seems like a reasonable maximum if the root cause is unfixable.

Thank you for your explanation. Should be fixed now.
