### ISSUE TITLE
Header displays wrong logo and label on /list page

### ISSUE THREAD

**Issue by KRider92** [louislam/uptime-kuma#1147]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### Description

Having set a  custom label and logo in the `/status` page, this name and logo are not transferred to the `/list`, `/dashboard` and `/settings` pages.

### 👟 Reproduction steps

1. Set a custom name and logo on the `/status` page
2. Navigate to the `/list`, `/dashboard` or `/settings` pages.

### 👀 Expected behavior

Showing custom name and logo on all pages

### 😓 Actual Behavior

Showing Uptime Kuma name and logo on all pages

### 🐻 Uptime-Kuma Version

1.11.3

### 💻 Operating System and Arch

Raspbian Linux 5.10.89-v7l+

### 🌐 Browser

Google Chrome 97.0.4692.71 x64

### 🐋 Docker Version

20.10.12

### 🟩 NodeJS Version

v10.24.0

**Comment by jamesmacwhite** [comment]
I think this is more of a feature enhancement, not a bug, because the status page allows customisation, where as the backend dashboard doesn't currently allow customisations.

**Comment by louislam** [comment]
The /list is actually for mobile only currently.

**Comment by louislam** [comment]
I read it wrong, but it is still not a bug, custom logo is for status page only.
