### ISSUE TITLE
Error for Gotify down notifications

### ISSUE THREAD

**Issue by Syntoxr** [louislam/uptime-kuma#1148]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### Description

I'm using Gotify as my Notification service but only getting notifications, if a service goes online again. If it goes offline, I'm not getting notified and the log throws out an error.

### 👟 Reproduction steps

Manually turning off a monitored docker container or other service

### 👀 Expected behavior

Getting notified if as service goes down

### 😓 Actual Behavior

Getting no notification but an error message in log

### 🐻 Uptime-Kuma Version

1.11.3

### 💻 Operating System and Arch

ubuntu5~20.04.2

### 🌐 Browser

Brave: Version 1.34.80 Chromium: 97.0.4692.71 (Official Build) (64-Bit)

### 🐋 Docker Version

20.10.7, build 20.10.7-0

### 📝 Relevant log output

```shell
Cannot send notification to Gotify
Error: Error: Error: Request failed with status code 500 {"error":"Internal Server Error","errorCode":500,"errorDescription":"Error 1366: Incorrect string value: '\\xF0\\x9F\\x94\\xB4 D...' for column `gotify`.`messages`.`message` at row 1"}
    at Gotify.throwGeneralAxiosError (/app/server/notification-providers/notification-provider.js:32:15)
    at Gotify.send (/app/server/notification-providers/gotify.js:23:18)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async Function.sendNotification (/app/server/model/monitor.js:684:21)
    at async beat (/app/server/model/monitor.js:391:17)
    at async Timeout.safeBeat [as _onTimeout] (/app/server/model/monitor.js:443:17)
```

**Comment by Syntoxr** [comment]
Just had the Idea of using the gotify component of apprise, but even there the down notifications don't work. Maybe some illegal characters in the down message?

**Comment by Sev455** [comment]
I have this happening too.

I'm using a MySQL db on the backend.

Cannot send notification to Uptime Alert
Error: Error: Error: Request failed with status code 500 {"error":"Internal Server Error","errorCode":500,"errorDescription":"Error 1366: Incorrect string value: '\\xF0\\x9F\\x94\\xB4 D...' for column `gotify`.`messages`.`message` at row 1"}
at Gotify.throwGeneralAxiosError (/app/server/notification-providers/notification-provider.js:32:15)
at Gotify.send (/app/server/notification-providers/gotify.js:23:18)
at processTicksAndRejections (internal/process/task_queues.js:95:5)
at async Function.sendNotification (/app/server/model/monitor.js:684:21)
at async beat (/app/server/model/monitor.js:391:17)
at async safeBeat (/app/server/model/monitor.js:443:17)
Monitor #6 'Insurgency': Failing: Server not found on Steam | Interval: 60 seconds | Type: steam

**Comment by kimpenhaus** [comment]
@Syntoxr / @Sev455 I assume you are running gotify against mysql/maria db? Most probably your collations are not setup properly.
I had the same problems and fixed it by changing 

1) table collations to `utf8mb4_unicode_ci` (I've changed them on the complete database)
<img width="411" alt="image" src="https://user-images.githubusercontent.com/575109/156658197-f56389c1-416e-4a26-83ac-da2070ef7ff1.png">

2) added `charset=utf8mb4` to the connection string of gotify
<img width="877" alt="image" src="https://user-images.githubusercontent.com/575109/156658518-00d6dddd-f9e8-406b-9269-547d7af1bd14.png">

I don't see an issue with uptime kuma here...

<img width="744" alt="image" src="https://user-images.githubusercontent.com/575109/156658957-08e6d240-06ce-47ba-9751-7aa7f2195c36.png">

**Comment by Syntoxr** [comment]
@kimpenhaus Wow, many thanks! 
My collations were right, but my connection string just had utf8.
Your detailed description is also very appreciated! :+1:

**Comment by kimpenhaus** [comment]
@Syntoxr glad I could help :+1:

**Comment by tan-yong-sheng** [comment]
I used sqlite3 and i faced similar error. Any way to mitigate it, thanks in advance.

**Comment by CommanderStorm** [comment]
What do you mean by "similar"?
Also when you mean you use sqlite, do you mean you use sqlite for gotify or uptime-kuma?
