### ISSUE TITLE
Custom logo and title

### ISSUE THREAD

**Issue by sovushik** [louislam/uptime-kuma#1149]
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

UI Feature

### 🔖 Feature description

Add the ability to place your own logo and name instead of "Uptime Kuma". Thank you

### ✔️ Solution

Add a separate section with customization of the script

**Comment by jamesmacwhite** [comment]
This is possible on the status page currently:

![image](https://user-images.githubusercontent.com/8067792/148678621-8492d6d4-eee6-4840-86cb-ea34e16c1955.png)

You would go to `/status` and the edit to bring up the fields, or are you referring to the dashboard?

![image](https://user-images.githubusercontent.com/8067792/148678647-1bf85643-1dca-4850-bf2c-3738fba3531a.png)

**Comment by sovushik** [comment]
Good evening! I understood it, thank you - changed it! but how to do it on the main screen of the program? Is there no editing mode?

**Comment by jamesmacwhite** [comment]
Currently `/dashboard` does not any customisation, so that would be a feature request, for being able to customise the dashboard header, with a logo and title. Or have the customisations of the status page, also apply to the dashboard.

**Comment by sovushik** [comment]
> Currently `/dashboard` does not any customisation, so that would be a feature request, for being able to customise the dashboard header, with a logo and title. Or have the customisations of the status page, also apply to the dashboard.

OK thanks! Then I'll be waiting in future updates! Thanks to the developer and who answered!
