### ISSUE TITLE
Requests: make comments on downtime

### ISSUE THREAD

**Issue by malicioustoker** [louislam/uptime-kuma#115]
First of all, thank you for your hard work on this! I have 2 requests that I’d love to see.

<s>1. Is there a way to add a public view, so that guests will not need an account to check downtime?</s> Duplicated
2. I would love a way to make comments on downtime, such as status’ on any errors, if they are resolved, and also a way to put notes if there is future planned down time.

Again, thanks for everything!

**Comment by Saibamen** [comment]
I think 1st is already mentioned in https://github.com/louislam/uptime-kuma/issues/21 (separate issue: https://github.com/louislam/uptime-kuma/issues/4)

**Comment by LeviSnoot** [comment]
The second is also already in #21 as "Incident Reports".
