### ISSUE TITLE
show minutes a service is down

### ISSUE THREAD

**Issue by robkooper** [louislam/uptime-kuma#1158]
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

Other

### 🔖 Feature description

Right now it will show me the date and time when a service goes down and when it comes back up. It would be nice to also show how long it was down for in the notifications. This comes really hand if a lot of services go down (reboot) and come back up. This way I don't have to try and find different notifications to see how long a service was down for.

### ✔️ Solution

As part of the notification say:

[:white_check_mark: Up] 200 - OK, it was down for 4 minutes and 3 seconds

**Comment by csjoh** [comment]
+1 for this.

It would also be nice to show the amount of time the service was down in the dashboard.

**Comment by gavinsauder** [comment]
+1 for this.

**Comment by feriahmad** [comment]
+1 for this

**Comment by rpgscience** [comment]
+1 for this

**Comment by CommanderStorm** [comment]
Duplicate of #177 => closing and contributing to track there
