### ISSUE TITLE
False positive failed checks

### ISSUE THREAD

**Issue by yuriw** [louislam/uptime-kuma#1162]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

I see several false positive emails from Kuma claiming that the port or ping failed every day, but in fact it’s not true.  And 1 minute later it’s green again.

My question - is it a known issue?  Is there maybe a setting that can help make it go away?

Thx

### 🐻 Uptime-Kuma Version

1.11.1

### 💻 Operating System and Arch

Ubuntu 20.04

### 🌐 Browser

Chrome

**Comment by jamesmacwhite** [comment]
I have experienced this as well. I have monitoring from external services as well so I have cross over on some monitors and Uptime Kuma often states a service has timed out but it hasn't. External monitoring shows no issues.

This is when using a Docker container.

**Comment by louislam** [comment]
Which docker image are you using? 
As far as I known the alpine base image is having this issue.

Also you could increase "Retries" value to 1 or 2 to minimize the problem.
![image](https://user-images.githubusercontent.com/1336778/148966113-e298fd40-a3ba-49d2-b7b9-be3c67d24076.png)

**Comment by Michaelpalacce** [comment]
I'm also experiencing this issue. Switched from alpine to Debian, but with  ~ 40 monitors I can still see it happening
