### ISSUE TITLE
Multiple selection on probes

### ISSUE THREAD

**Issue by qdupuy** [louislam/uptime-kuma#1163]
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

UI Feature

### 🔖 Feature description

Having the multiple selection would allow to deactivate or delete the probes already in place

### ✔️ Solution

The goal would be to have the ability to select multiple probes in order to disable or set the probe and/or notifications.

Example: 

Pause sites that are on a shared sql server to avoid being notified when the SQL server is updated, which can lead to outages

**Comment by CommanderStorm** [comment]
Closing as resovled since `v1.23.0`
![image](https://github.com/louislam/uptime-kuma/assets/26258709/08cc27a5-5451-48ed-bfde-0812ff41105c)
