### ISSUE TITLE
Sort monitor list by status (down on top)

### ISSUE THREAD

**Issue by teoxrr** [louislam/uptime-kuma#1165]
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

UI Feature

### 🔖 Feature description

Would be helpful to get monitors in down status, on top of monitors list

### ✔️ Solution

A "sort by" button in monitors list

**Comment by pitichampi** [comment]
It would be a great feature !

**Comment by ASpr80** [comment]
Sort monitor list by status (down on top) :(

**Comment by cuzun-net** [comment]
Yes definitely. It would be really helpful for those whose must monitor lots of endpoints.

**Comment by EdgeCCTV-Austen** [comment]
Definitely needs this, it's really a mandatory feature for mass monitoring. We monitor over 800 bare metal servers, would love to switch over to this from phpservermon as this is so much cleaner, but I can't until we can get offline servers on top somehow.

**Comment by rob1998** [comment]
+1

**Comment by Zandor300** [comment]
+1

**Comment by zolotarev** [comment]
Realized in #1585

**Comment by lsanders** [comment]
+1

**Comment by jeremyrnelson** [comment]
Seems like we've got a lot of tickets open referencing the same features.  @teoxrr - is there anything in this ticket that's not covered in #1585 where there's already a pull request?  If not, can you close this?

**Comment by teoxrr** [comment]
Yes https://github.com/louislam/uptime-kuma/issues/1585 covers my issue,
I'll close it.
Thank you, regards

Il Mar 29 Nov 2022, 21:57 Jeremy Nelson ***@***.***> ha
scritto:
