### ISSUE TITLE
Some ping monitors show "Warning time of day goes back, taking countermeasures" in monitor data

### ISSUE THREAD

**Issue by jamesmacwhite** [louislam/uptime-kuma#1166]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### Description

I've noticed a couple of ping monitor tests show this message in the data within Uptime Kuma at random intervals such as:

```
Warning: time of day goes back (-17749us), taking countermeasures. Warning: time of day goes back (-17654us), taking countermeasures.
```

There are different measurements of us values in examples such as:

```
Warning: time of day goes back (-19502us), taking countermeasures. Warning: time of day goes back (-19420us), taking countermeasures.
Warning: time of day goes back (-20526us), taking countermeasures. Warning: time of day goes back (-20330us), taking countermeasures.
```

These are occurring at different times sometimes days apart. So far it only appears to be happening on two specific ping monitors but these are completely unrelated in terms of the device being tested.

The devices in question are:

* A DOCSIS modem
* A TP-Link network switch

There is no NTP/time source to be configured on these devices. They have web interfaces but no ability to set or control the time source. No SSH access, just web interfaces.

I do not get any warnings when using ping from another client i.e. Windows/Linux outside of Uptime Kuma.

### 👟 Reproduction steps

1. Setup ping monitor
2. Wait for a while
3. See "Warning: time of day goes back" messages in data.

### 👀 Expected behavior

No warnings related to time source.

### 😓 Actual Behavior

"Warning: time of day goes back" messages logged against certain ping monitors.

### 🐻 Uptime-Kuma Version

1.11.3

### 💻 Operating System and Arch

macOS 15.7

### 🌐 Browser

Chrome Version 97.0.4692.71 (Official Build) (64-bit)

### 🐋 Docker Version

Docker Desktop 4.3.2

**Comment by louislam** [comment]
The error is coming from OS's ping tools. Uptime Kuma just call it and get the result from stdout.

**Comment by jamesmacwhite** [comment]
@louislam Thank you. It's interesting though because pinging both from within Docker and the host I cannot reproduce that message. I even caught this happen live and tested ping in the container and on the host (macOS) didn't show the "Warning: time of day goes back" errors. It is also strange how this is transient and doesn't happen consistently.

**Comment by chakflying** [comment]
Running docker on macOS seems to have issue with keeping the clock inside the VM in sync. I don't use mac but you can read about it in [this docker blog post](https://www.docker.com/blog/addressing-time-drift-in-docker-desktop-for-mac/). Looks like docker desktop runs a NTP server in the host and a client in the VM, which will make periodic adjustments to the time. How it end up going backwards for 19ms I'm not sure.

**Comment by jamesmacwhite** [comment]
@chakflying Thank you for this, this would explain the weird drifting of time and why ping responds with this but only sometimes. It doesn't look like there is a solution, given platform limitations.

**Comment by jamesmacwhite** [comment]
Honestly, I'd advise anyone not to run Docker on Mac, it's awful. Docker for Mac is that bad, I dumped MacOS entirely on Mac Mini and installed Ubuntu Server on it, Docker being native with Linux, sooooo much better.
