### ISSUE TITLE
Mattermost Notifications not working

### ISSUE THREAD

**Issue by philippkayser** [louislam/uptime-kuma#1173]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### Description

We've setup Mattermost notifications.

1. We used the test Button in the NOtifcation setup-page which sends a message to mattermost successfully
2. We've enabled the Notification on a service. When the service goes down, no message we're send.

### 👟 Reproduction steps

Setup mattermost notifications.

### 👀 Expected behavior

Mattermost notification should be send if service goes down.

### 😓 Actual Behavior

No Notification were send.

### 🐻 Uptime-Kuma Version

1.11.1

### 💻 Operating System and Arch

Kubernetes/Docker

### 🌐 Browser

Chrome

### 📝 Relevant log output

```shell
No output
```

**Comment by Syno0** [comment]
Same here, the test button works great but no notif when a service goes down :/

**Comment by osc86** [comment]
I tried with the latest beta 1.13.0-beta and 1.12.1 but it's still not working

**Comment by lazee486** [comment]
having similiar issue, test works but no alerts generated, has anyone else found a solution? created new channel, new webhook, new notification alert

**Comment by osc86** [comment]
For me it worked after also setting the "Channel Name". Alternatively you can use a lower case channel name.
[nietzscheanic](https://github.com/nietzscheanic) explained what's wrong with the "fix" in https://github.com/louislam/uptime-kuma/pull/1298#issuecomment-1062858339

**Comment by windware-ono** [comment]
This is confusing but if you have some non alphanumeric characters, Mattermost truncates those characters and you should check it from the channel URL what the actual name is.

For example, if your channel name is example.com, the actual name becomes examplecom.

**Comment by cobenash** [comment]
I face the same issue at v1.14.0.

Test works but no alert fires.

**Comment by louislam** [comment]
> I face the same issue at v1.14.0.
> 
> Test works but no alert fires.

Are there any error log?

**Comment by cobenash** [comment]
> > I face the same issue at v1.14.0.
> > Test works but no alert fires.
> 
> Are there any error log?
Thanks.
Yes, the error message said the channel not found, but it works when I use test function at the set up process.
```
Error: Error: Error: Request failed with status code 404 {"id":"web.incoming_webhook.channel.app_error","message":"找不到頻道","detailed_error":"","request_id":"5g8ji1b76tyxjxnj81kwei1nmr","status_code":404}
    at Mattermost.throwGeneralAxiosError (/app/server/notification-providers/notification-provider.js:32:15)
    at Mattermost.send (/app/server/notification-providers/mattermost.js:122:18)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Function.sendNotification (/app/server/model/monitor.js:729:21)
    at async beat (/app/server/model/monitor.js:438:17)
    at async Timeout.safeBeat [as _onTimeout] (/app/server/model/monitor.js:482:17)
```

**Comment by cobenash** [comment]
Aha,  I set up the channel in the mattermost app directly and left the channel in the notification settings empty.
It works now.

Uptime Kuma 1.14.0
Mattmost 6.6.0

Thanks. :)

**Comment by mikebakke** [comment]
Just a note for others who follow my trail: 

I had the same symptom - test worked but alerts never showed. 

I first removed the space in my channel name so it went from "Kuma Alerts" to "Kuma" - still no good - then I changed the channel name in the Kuma notification definition from "Kuma" to "kuma" (ie Lowercase K) and it started working.

**Comment by CommanderStorm** [comment]
Can other users reproduce this? cc @cobenash 
If yes, we should likely add a helptext

**Comment by cypherpork** [comment]
@CommanderStorm I just went through the setup, had the same problem, and followed the recipe from @mikebakke, which helped.
