### ISSUE TITLE
API docs/example to create new check/monitor via API

### ISSUE THREAD

**Issue by codeagencybe** [louislam/uptime-kuma#1176]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

Is there any example or docs available where I can use the uptime Kuma API to create a new check/monitor programmatically? 
I would like to automatically create a new check/monitor after I spin up a new application and sent an HTTP request to uptime kuma API backend. 
But I can't find anything related to read up on this and give it a try. 

Thanks. 

### 🐻 Uptime-Kuma Version

1.11.3

### 💻 Operating System and Arch

not relevant to question

### 🌐 Browser

not relevant to question

### 🐋 Docker Version

not relevant to question

### 🟩 NodeJS Version

not relevant to question

**Comment by chakflying** [comment]
Ref #118, API for monitors is not supported yet.
