### ISSUE TITLE
Error PRAGMA

### ISSUE THREAD

**Issue by FM-500** [louislam/uptime-kuma#1177]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### Description

Hello,

after a planned reboot of the docker host, UptimeKuma won't restart:

### 👟 Reproduction steps

Planned reboot

### 👀 Expected behavior

Startup

### 😓 Actual Behavior

Container is unhealthy

### 🐻 Uptime-Kuma Version

latest

### 💻 Operating System and Arch

Ubuntu 20.04

### 🌐 Browser

Chrome

### 📝 Relevant log output

```shell
==> Performing startup jobs and maintenance tasks
==> Starting application with user 0 group 0
Welcome to Uptime Kuma
Node Env: production
Importing Node libraries
Importing 3rd-party libraries
Importing this project modules
Prepare Notification Providers
Version: 1.11.3
Creating express and socket.io instance
Server Type: HTTP
Data Dir: ./data/
Connecting to the Database
Trace: [Error: PRAGMA journal_mode = WAL - SQLITE_NOTADB: file is not a database] {

  errno: 26,
  code: 'SQLITE_NOTADB'
}
    at process.<anonymous> (/app/server/server.js:1542:13)
    at process.emit (events.js:400:28)
    at processPromiseRejections (internal/process/promises.js:245:33)
    at processTicksAndRejections (internal/process/task_queues.js:96:32)
```

**Comment by louislam** [comment]
I cannot reproduce the problem, how did you restart the docker?
I believe that your db file is corrupted or the volume is missing.
You should check the /app/data directory.

**Comment by FM-500** [comment]
I suppose the container got corrupted during a resize of the partition where docker is installed.
Never mind, it was a bit of a pain, but I did a fresh start and set up everything again. Now I exported the Backup JSON for next time.
