### ISSUE TITLE
Auto Dismissing Down (Red) Notifications

### ISSUE THREAD

**Issue by chrislowthian** [louislam/uptime-kuma#1178]
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

UI Feature

### 🔖 Feature description

Have an option to change Down Notifications to the Auto Dismiss type like the Up Notifications do automatically.

### ✔️ Solution

When a "Down" (Red) Notification appears on screen it auto dismisses when items comes back online.

### ❓ Alternatives

Maybe a toggle in settings to choose between "Auto Dismiss" or "Persistant"

**Comment by KRider92** [comment]
I second this - For using on a "status" info display (without touch) this would be great, so that the display is not eventually "flooded" by notifications.

**Comment by pitichampi** [comment]
When you monitor a lot of servers, it happens sometime that some servers fall for 2 or 3 minutes. These errors triger an error toast. After a big week end, you end up with lot of toasts to discard manually (as set on line 123 of src/mixins/socket.js).
That means that you need an input to the computer which displays uptime kuda. As I use it on a raspberry connected on a tv this can be unpractical.
In some cases the toasts aren't even useful at all as you have other ways to be notified.

**Comment by VindicoShaun** [comment]
Agreed, this would be a useful feature, I've got a similar use case to @pitichampi as we have the dashboard on an unattended PC with no interface, would be nice to have the option to hide all Toast notifs, or set an auto-dismiss time.

**Comment by chakflying** [comment]
PR in #2555
