### ISSUE TITLE
More available colors for the tags

### ISSUE THREAD

**Issue by magyarlatin** [louislam/uptime-kuma#1180]
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

UI Feature

### 🔖 Feature description

Some people might need more colors available at the time of creating or setting up tags on Monitors as an easier and more comfortable way classify them.

### ✔️ Solution

Would be nice to have a broader list of colors available within the tag creating options.

**Comment by Zellmer** [comment]
do you have any suggestions for colors?

**Comment by magyarlatin** [comment]
> do you have any suggestions for colors?

Sure, here are some of my suggestions:  SaddleBrown, SandyBrown, Beige, SteelBlue, Aqua, Yellow, IndianRed, Khaki, Olive, YellowGreen, PeachPuff, Plum, Goldenrod, PowderBlue, MediumSpringGreen, LightSalmon, Tan.

**Comment by Computroniks** [comment]
I thinks for this, perhaps we should add the option of a colour picker to choose custom colours. It would save having too long a list of colours. Although the issue I see is handling how the current colours are stored in the database. In future they could be stored as hex values but I am not sure how they are stored currently.

**Comment by Computroniks** [comment]
Actually, given that the colours are already saved as hex values, it shouldn't be too hard to implement. I would say I would take a crack at this so I wouldn't be able to start it any time soon. I will add it to my TODO list but if anyone else feels like taking this, please feel free.

**Comment by Computroniks** [comment]
Looks like #1690 should handle this

**Comment by CommanderStorm** [comment]
![image](https://github.com/louislam/uptime-kuma/assets/26258709/dc06a5b6-1388-4f62-8e0a-e10e0629edc0)

Closing as resolved by #1690 and released in `v1.20.0`
