### ISSUE TITLE
Run script on alerts

### ISSUE THREAD

**Issue by HeuristicPerson** [louislam/uptime-kuma#1193]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

I have a simple web logging/alert system running on my LAN that you can access by simply pushing the message you want to log. So, in my machines running Linux I can simply run a curl command to store a log message.

Now I'd like to use that system with uptime-kuma but I haven't found anything similar to running a script in the alerts menu. Do you know if there is anything suitable option available? Otherwise I think I could try to write a run-script alert plugin myself.

Regards and thanks in advance

### 🐻 Uptime-Kuma Version

1.11.3

### 💻 Operating System and Arch

Ubuntu 20.04 x86

### 🌐 Browser

Firefox 96.0

### 🐋 Docker Version

20.10.7

**Comment by KRider92** [comment]
Don't think there's anything available like this...
Most likely you'd have to develop this yourself.

**Comment by David-Lor** [comment]
I'd love to see this integration. An alternative workaround is to somehow have an HTTP server that triggers your on-alert actions, then use the Webhook alert for triggering it.

**Comment by scorpio2k2** [comment]
I'd love to have this option as well. I'd like to be able to use my own webhook for sms alerting.

**Comment by go2tom42** [comment]
> I'd love to see this integration. An alternative workaround is to somehow have an HTTP server that triggers your on-alert actions, then use the Webhook alert for triggering it.

Yep, I went with https://github.com/adnanh/webhook/

**Comment by evdbovenkamp** [comment]
> > I'd love to see this integration. An alternative workaround is to somehow have an HTTP server that triggers your on-alert actions, then use the Webhook alert for triggering it.
> 
> Yep, I went with https://github.com/adnanh/webhook/

Thank you! Fantastic solution.

**Comment by mrkeuz** [comment]
Just for linking - this duplicate for #2363
