### ISSUE TITLE
Cannot check local websites with kuma

### ISSUE THREAD

**Issue by xamerintime** [louislam/uptime-kuma#1200]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

I am able to HTTP(s) monitor public websites, however I am not able to HTTP(s) monitor my pihole instance or my bittorrent webui. Pinging sites like https://google.com work but not http://192.168.50.40. I believe the container should be able to as I am able to ping 192.168.50.40

### 🐻 Uptime-Kuma Version

1.11.3

### 💻 Operating System and Arch

Debian 5.10

### 🌐 Browser

Firefox

### 🐋 Docker Version

Docker version 20.10.12, build e91ed57

### 🟩 NodeJS Version

v14.18.3

**Comment by xamerintime** [comment]
> It should work, as I monitor a lot of internal sites in my LAN, what error do you get from the monitor when trying to monitor your PiHole or Bittorrent client?

I get a connection timed out error. Do you think this would have anything to do w kuma being installed via portainer? Pihole and bittorrent are installed on the host machine as well.

**Comment by jamesmacwhite** [comment]
It would suggest there is a network issue between your container and the services you are testing. I haven't used portainer myself, but connection timeout sounds like a network related issue.

Uptime Kuma should be able to query LAN endpoints fine in a container, are you using the official Docker image?

**Comment by xamerintime** [comment]
> It would suggest there is a network issue between your container and the services you are testing. I haven't used portainer myself, but connection timeout sounds like a network related issue.
> 
> Uptime Kuma should be able to query LAN endpoints fine in a container, are you using the official Docker image?

yes am using the command from the official github. The only difference is I am using a bridged network within docker.

**Comment by jamesmacwhite** [comment]
I think it's possibly the network configuration of your Docker instance, try switching it to confirm.

**Comment by xamerintime** [comment]
> 

I will try switching it around. also its not a timed out error, the log says it's " 'Bittorrent': Failing: connect ECONNREFUSED 192.168.50.40:8080"

**Comment by xamerintime** [comment]
dude im so dumb im sorry for wasting anyones time, there was a firewall active.
