### ISSUE TITLE
What is the correct way to transfer an active installation to another server?

### ISSUE THREAD

**Issue by davemaxx** [louislam/uptime-kuma#1204]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

I am in the process of changing server. What are the steps to properly move my installation? Should I just install everything new on the server and then import the database? Thanks.

### 🐻 Uptime-Kuma Version

1.8.0

### 💻 Operating System and Arch

Ubuntu

### 🌐 Browser

Firefox

**Comment by jamesmacwhite** [comment]
The main area is the SQLite DB. There is a import/export function through the dashboard `/settings/backup`.

You could also just migrate the DB yourself, shutdown your existing Uptime Kuma installation copy the contents of your data directory and move that to the new instance.

**Comment by aborghiz** [comment]
HI , what is the best way to migrate an active installation now that the backup page has :

Deprecated: Since a lot of features were added and this backup feature is a bit unmaintained, it cannot generate or restore a complete backup.

Please backup the volume or the data folder (./data/) directly instead.

**Comment by CommanderStorm** [comment]
You shut down the installation and move (or backup-restore) the data folder the data folder to the new place.
No secret sauce there..

**Comment by aborghiz** [comment]
If I am using a docker installation method

docker run -d --restart=always -p 3001:3001 -v uptime-kuma:/app/data --name uptime-kuma louislam/uptime-kuma:1

How I do it?

I am moving this into a container with MYSQL running an aurora serverless



Andrea Borghi
. . . . . . . . . . . . . . . . . . . . . . . . . .
Cloud Engineer III
Zivaro, Inc.
10807 New Allegiance Drive
Colorado Springs, CO 80921
o: 720.836.7415
c: 719.271.4834
e: ***@***.******@***.***>

***@***.***
LinkedIn<https://linkedin.com/company/zivarobrilliance> |  Facebook<https://www.facebook.com/ZivaroDenver/> |  Twitter<https://twitter.com/zivaro_> |  Instagram<https://www.instagram.com/zivaro.co/>

**Comment by CommanderStorm** [comment]
(We will obviously release a migration guide for going from V1 on SQLite3 to V2 on SQLite3/MariaDB/MySQL)

**Comment by CommanderStorm** [comment]
As only sqlite is offered in the v1.X series, this won't be possible in the CURRENT release.
In v2.0, mysql/maridb is a supported database.
Please refer to https://github.com/louislam/uptime-kuma/issues/4500 for the status of the v2.0 release and where areas are people can get involved to speed this process up. ^^
