### ISSUE TITLE
What is the Webhook JSON Schema?

### ISSUE THREAD

**Issue by nickshanks347** [louislam/uptime-kuma#1207]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

Just testing out the webhook functionality... I can think of some good use cases for it. I've made an extremely simple Flask app to get an idea of the JSON schema:

```python
@app.route('/v1/status', methods=['POST', 'GET'])
def status_v1():
    request_data = request.get_json()
    p = Serial(devfile='/dev/ttyUSB0', baudrate=9600, bytesize=8, parity='N', stopbits=1, timeout=1.00, dsrdtr=True)
    print(request_data)
    return make_response(jsonify({'status': 'success'}), 200)
```
It literally takes the POST request and prints it out in terminal. This is the output I get:

```json
{'heartbeat': {'monitorID': 10, 'status': 0, 'time': '2022-01-21 14:06:38', 'msg': 'PING 10.13.13.13 (10.13.13.13) 56(84) bytes of data.\n\n--- 10.13.13.13 ping statistics ---\n10 packets transmitted, 0 received, 100% packet loss, time 400ms\n\n', 'important': True, 'duration': 0}, 'monitor': {'id': 10, 'name': 'Testing', 'url': 'https://', 'method': 'GET', 'body': None, 'headers': None, 'basic_auth_user': None, 'basic_auth_pass': None, 'hostname': '10.13.13.13', 'port': None, 'maxretries': 0, 'weight': 2000, 'active': 1, 'type': 'ping', 'interval': 60, 'retryInterval': 60, 'keyword': None, 'ignoreTls': False, 'upsideDown': False, 'maxredirects': 10, 'accepted_statuscodes': ['200-299'], 'dns_resolve_type': 'A', 'dns_resolve_server': '1.1.1.1', 'dns_last_result': None, 'pushToken': None, 'notificationIDList': {'2': True}, 'tags': []}, 'msg': '[Testing] [🔴 Down] PING 10.13.13.13 (10.13.13.13) 56(84) bytes of data.\n\n--- 10.13.13.13 ping statistics ---\n10 packets transmitted, 0 received, 100% packet loss, time 400ms\n\n'}
```

Pasted the output into Notepad++ and a couple of online tools, yet they all say the JSON is invalid. Could you please provide the JSON schema?

Note, the versions below are where Uptime Kuma is running, NOT where the Flask app is running.

### 🐻 Uptime-Kuma Version

1.11.3

### 💻 Operating System and Arch

Raspberry OS Lite armv7

### 🌐 Browser

Google Chrome 97.0.4692.99

### 🐋 Docker Version

Docker version 20.10.12, build e91ed57

**Comment by tdannecy** [comment]
I also have this question. Is there a doc somewhere with the JSON schema for webhook notifications?

**Comment by CommanderStorm** [comment]
Not currently, but you can dump the content via https://webhook.sites or similar.

Please make sure to test all 3 different notifications types (UP/Down, Cert-Expiry, Testing) to ensure the webhooks does what you expect. Not all events have all context (for example testing does not have a monitor)
