### ISSUE TITLE
How to change domain 

### ISSUE THREAD

**Issue by LolikoHD** [louislam/uptime-kuma#1211]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

I want to change the domain for my Uptime Kuma page

### 🐻 Uptime-Kuma Version

1.11.3

### 💻 Operating System and Arch

Ubuntu 20.04.3

### 🌐 Browser

Opera Gx

**Comment by Computroniks** [comment]
I assume that you mean the domain that you use to access the page. E.g `uptime.example.com`. I don't think that there is an option to set the domain name in kuma in the first place. I know when I set it up there wasn't one and it just worked straight away. I think that all you would need to do is change the DNS entry that points to your server to your new name. If you are running kuma behind a reverse proxy then you would also have to change the config on that to make sure that your request gets sent to the correct place. See https://github.com/louislam/uptime-kuma/wiki/Reverse-Proxy for settings for some common reverse proxys.

**Comment by rezzorix** [comment]
`Settings -> General -> Primary Base URL`

Aside from that Computroniks already explained all, if anything else, we would require more info.
