### ISSUE TITLE
check UP by <title>

### ISSUE THREAD

**Issue by nbctcp** [louislam/uptime-kuma#1218]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

I want to check up of my page by checking existence of this title
<title>PNETLab | Lab is Simple</title>
what to type in header json?
tq

### 🐻 Uptime-Kuma Version

1

### 💻 Operating System and Arch

Alpine

### 🌐 Browser

Opera Win 82.0.4227.58

### 🐋 Docker Version

20.10.11

**Comment by chakflying** [comment]
Have not tested this but using the keyword monitor should work.

**Comment by nbctcp** [comment]
I don't understand what u mean
if u can gimme example in header or body json
I would like to try that and update here

**Comment by louislam** [comment]
Try this

![image](https://user-images.githubusercontent.com/1336778/150781399-fe996fde-719b-4e54-9bcb-38df32c70b47.png)

**Comment by nbctcp** [comment]
that's the correct answer
