### ISSUE TITLE
ERROR - mqtt:// is disabled on this system

### ISSUE THREAD

**Issue by Rustymage** [louislam/uptime-kuma#1227]
### ⚠️ Please verify that this bug has NOT been raised before.

- [x] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

Trying to use the apprise mqtt notification agent and I'm getting this:

`ERROR - mqtt:// is disabled on this system.`

The URL is

`mqtt://user:password@192.168.1.141:1883/UPTIME`

I can't find much on this, except that Apprise state they support mqtt, but the notifications pinned tab in this repo doesn't show mqtt as available?

Thanks.

### 🐻 Uptime-Kuma Version

1.11.3

### 💻 Operating System and Arch

Ubuntu 20.04.2 LTS (GNU/Linux 5.4.0-92-generic x86_64)

### 🌐 Browser

Firefox 96.0.2 (64-bit)

### 🐋 Docker Version

Docker version 20.10.8, build 3967b7d

### 🟩 NodeJS Version

v10.19.0

**Comment by mindlesstux** [comment]
I think the docker image needs to be rebuilt with a package.  See @louislam 's comment and beyond on Issue 125: https://github.com/louislam/uptime-kuma/issues/125#issuecomment-927139135

**Comment by Rustymage** [comment]
Thanks - I have just installed both via Exec in the container and the issue still persists, even after rebooting.

**Comment by agustinvinao** [comment]
Same for me, installing all python libs
```
pip3 install --upgrade --no-cache-dir wheel setuptools
pip3 install --no-cache-dir paho-mqtt
```
using Apprise to send mqtt:
```

Error: 2022-02-02 23:29:40,933 - ERROR - mqtt:// is disabled on this system.
2022-02-02 23:29:40,933 - ERROR - You must specify at least one server URL or populated configuration file.
Usage:  [OPTIONS] SERVER_URL [SERVER_URL2 [SERVER_URL3]]

  Send a notification to all of the specified servers identified by their
  URLs the content provided within the title, body and notification-type.

  For a list of all of the supported services and information on how to use
  them, check out at https://github.com/caronc/apprise

Options:
  -b, --body TEXT                Specify the message body. If no body is
                                 specified then content is read from <stdin>.
  -t, --title TEXT               Specify the message title. This field is
                                 complete optional.
  -c, --config CONFIG_URL        Specify one or more configuration locations.
  -a, --attach ATTACHMENT_URL    Specify one or more attachment.
  -n, --notification-type TYPE   Specify the message type (default=info).
                                 Possible values are "info", "success",
                                 "warning", and "failure".
  -i, --input-format FORMAT      Specify the message input format
                                 (default=text). Possible values are "text",

```

**Comment by agustinvinao** [comment]
For now, I'm using this image to solve the problem, it works ok.
```
FROM louislam/uptime-kuma:latest
RUN apt update
RUN apt --yes install python3
RUN apt-get install python3-setuptools
RUN pip3 install --no-cache --upgrade pip paho-mqtt
```

**Comment by dadcoachengineer** [comment]
@agustinvinao - thank you for the build file. I have it pushed to my repo here:

https://hub.docker.com/repository/docker/jasonshearer/uptime-kuma-mqtt

**Comment by dadcoachengineer** [comment]
Any thoughts on adding paho-mqtt to the build file?

<img width="1231" alt="image" src="https://user-images.githubusercontent.com/6666082/196544075-ec49908d-f85b-4376-b586-ca23dd5dda8f.png">

**Comment by mwolter805** [comment]
Trying to help others avoid this rabbit hole. Anyone having MQTT issues and thinking `paho-mqtt` not being installed could be the cause of the issue, uptime-kuma docker image version 1.19.2 does not have `paho-mqtt` and does not need it. On version 1.19.2, MQTT works fine without `paho-mqtt`.

**Comment by dadcoachengineer** [comment]
> Trying to help others avoid this rabbit hole. Anyone having MQTT issues and thinking `paho-mqtt` not being installed could be the cause of the issue, uptime-kuma docker image version 1.19.2 does not have pip package `paho-mqtt` and does not need it. On version 1.19.2, MQTT works fine without needing to install anything.

That is good to know! What MQTT client is included in 1.19.2?

**Comment by mwolter805** [comment]
@dadcoachengineer Apologize, I was mistaken and didn't realize this issue was related to notifications via MQTT. I was having an issue with monitoring an MQTT server.

**Comment by dadcoachengineer** [comment]
> 

Agreed. Would love to see Palo-mqtt incorporated into the base image.

In the meantime.....I have this build but I do not update it on a regular basis.

https://hub.docker.com/r/jasonshearer/uptime-kuma-mqtt

**Comment by douginoz** [comment]
It's been nearly a year and it seems this problem still exists.
Ubuntu 23.10
Using latest Uptime Kuma docker image: louislam/uptime-kuma:latest

Trying to set up Notification:

Notification Type:  Apprise
Apprise URL: mqtt://blah:blahpass@192.168.1.20:1883/homeassistant/uptime_kuma/plex

Status:  Apprise is installed

Pressing Test produces 'Process Exited with Code 1'
Docker log files show:
```
2024-06-16T00:48:11-07:00 [AUTH] INFO: Login by username + password. IP=192.168.1.35
2024-06-16T00:48:11-07:00 [RATE-LIMIT] INFO: remaining requests: 19
2024-06-16T00:48:11-07:00 [AUTH] INFO: Successfully logged in user moa. IP=192.168.1.35
Error: Process exited with code 1
    at ChildProcess.done (/app/node_modules/promisify-child-process/index.cjs:70:19)
    at ChildProcess.emit (node:events:517:28)
    at maybeClose (node:internal/child_process:1098:16)
    at ChildProcess._handle.onexit (node:internal/child_process:303:5) {
  code: 1,
  signal: null,
  stdout: '2024-06-16 00:48:21,526 - ERROR - mqtt:// is disabled on this system.\n' +
    '2024-06-16 00:48:21,527 - ERROR - There are no service(s) to notify\n',
  stderr: ''

}
```

**Comment by seanosteen** [comment]
### Temporary Fix:

I was able to get MQTT notifications working again. The root cause was some breaking changes in the paho-mqtt library between versions 1.6.1 and version 2.0.0 ([link](https://github.com/eclipse/paho.mqtt.python/blob/v2.0.0/docs/migrations.rst)). It appears that the Apprise libraries included in the uptime-kuma:latest are not yet compatible with the v2 initialization calls.

By pinning the paho-mqtt library to v1.6.1 in my Dockerfile, I was able to get MQTT event notifications via Apprise to work again. Including my Dockerfile below:

```
FROM louislam/uptime-kuma:latest
RUN apt update
RUN apt --yes install python3
RUN apt-get install python3-setuptools
RUN pip3 install --upgrade pip
RUN pip3 install --no-cache-dir paho-mqtt==1.6.1
```
