### ISSUE TITLE
Set expected http response code

### ISSUE THREAD

**Issue by Gaz492** [louislam/uptime-kuma#123]
**Is your feature request related to a problem? Please describe.**
Ability to set expected HTTP response code

**Describe the solution you'd like**
Add a new monitoring type that allows you to specify an expected HTTP response code

**Comment by Panja0** [comment]
Already requested in: https://github.com/louislam/uptime-kuma/issues/21

_Accepted HTTP codes: I would like to add status codes to some HTTP request, 401 for instance_

**Comment by Gaz492** [comment]
Ahh, my bad must have missed that when I searched, ill close this to avoid duplicates.
