### ISSUE TITLE
Filter which event (`UP`/`DOWN`/`CERT-EXPIRY`/...) triggers alerts

### ISSUE THREAD

**Issue by raviwarrier** [louislam/uptime-kuma#1233]
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

New Notification

### 🔖 Feature description

Could you allow users to select when they would like to be alerted - when service is up, down or both?

I would just like to be alerted when the service is down, but not when it goes back up (mainly because it might be restored because of something I fixed/did).

Thanks. Appreciate your great work. Take care. Stay safe.

W.

### ✔️ Solution

A switch that lets users to select Alert when up, Alert when down, Alert either ways. 

### ❓ Alternatives

N/A

### 📝 Additional Context

N/A

**Comment by Hydrano** [comment]
I'm also very interested in this Feature!

**Comment by beavis6511** [comment]
Also interested !

**Comment by L1so** [comment]
This is much needed !

**Comment by adammckay** [comment]
I'm interested as well.  However - it would be nice to have it all three ways:
1. Up Alert
2. Down Alert
3. Both Alert

That would allow me to do something like a higher priority alert when down, just an email alert when up, etc. etc.  Right now, my alert client has to implement logic to filter based on text ('up', 'down', etc.).
