### ISSUE TITLE
Can't monitor a port that's behind a firewall from a Docker container

### ISSUE THREAD

**Issue by RubenHetKonijn** [louislam/uptime-kuma#1238]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### Description

When trying to monitor a Minecraft server that's behind a firewall (and not available from the outside world), on the same machine the monitor shows offline

### 👟 Reproduction steps

Host a service and block it from the outside world (without a proxy). Then (from the same machine in a docker container) try to monitor the service

### 👀 Expected behavior

The service would show online

### 😓 Actual Behavior

The service shows as offline

### 🐻 Uptime-Kuma Version

1.11.3

### 💻 Operating System and Arch

Ubuntu 20.04 LTS ARM

### 🌐 Browser

Brave Browser 1.34.81 Chromium: 97.0.4692.99 

### 🐋 Docker Version

20.10.12, build e91ed57

### 🟩 NodeJS Version

14.18.2

**Comment by rezzorix** [comment]
Thats not a bug, your firewall just did what you most likely set it to do 😉 

I suspect a restrictive firewall setting: did you block access from ALL except local subnet the server is on?

Enter the docker container and see if you can ping the IP you want to reach... 

Check your docker subnet and just whitelist it in the firewall.
If you haven't made any changes, then the default docker subnet is 172.17.0.0/16
You could also check your specific container to narrow that down to a /24 subnet or to a single IP.

**Comment by resu-cireneg** [comment]
- use "docker inspect mycontainter" to find the ip
- if you have an ingress ssl proxy-> take its ip , it also has the real ssl certs 

-> pro tipp: use docker-compose or docker-run with pre-created networks "docker network create" and fixed netmasks+ip

**Comment by RubenHetKonijn** [comment]
I'll try this

**Comment by RubenHetKonijn** [comment]
Alright, so in the `docker inspect uptime-kuma` info i found the ip 172.17.0.5, which appears to be the container ip, what I need is the host local ip for the container. in `ip addr` the ip is 172.17.0.1, both don't seem to work

**Comment by rezzorix** [comment]
Do you use UFW? 
Whats the status? Which rules did you set?
`#ufw status`
If you switch off UFW ... does it work then?

**Comment by RubenHetKonijn** [comment]
UFW Config:
```
Status: active

To                         Action      From
--                         ------      ----
9090                       ALLOW       Anywhere
443                        ALLOW       Anywhere
25565                      ALLOW       Anywhere
22                         ALLOW       Anywhere
4449                       ALLOW       Anywhere
25566                      ALLOW       Anywhere
9443                       ALLOW       Anywhere
9090 (v6)                  ALLOW       Anywhere (v6)
443 (v6)                   ALLOW       Anywhere (v6)
25565 (v6)                 ALLOW       Anywhere (v6)
22 (v6)                    ALLOW       Anywhere (v6)
4449 (v6)                  ALLOW       Anywhere (v6)
25566 (v6)                 ALLOW       Anywhere (v6)
9443 (v6)                  ALLOW       Anywhere (v6)
```

Turning off UFW does work, but i'd rather not have that disabled all the time
My config: 
![image](https://user-images.githubusercontent.com/64010592/151833606-1f528604-0c6d-4078-8c7a-fbbb46d17590.png)

**Comment by rezzorix** [comment]
OK, I dont know much about Minecraft servers; just 2 thoughts:

1) you query port 25401, this port isnt opened in your firewall.

2) the query port in Minecraft is actually UDP .. you are querying it via TCP
That most likely why you get "offline".

**Comment by RubenHetKonijn** [comment]
I'm querying the normal port (eq of 25565 on TCP) which does work because the port used is 25566 which is enabled.

**Comment by RubenHetKonijn** [comment]
Okay, clarification, another server running 25566 is working fine
config
![image](https://user-images.githubusercontent.com/64010592/151835105-8a1e91ed-ec66-42db-8c8d-ce27a273282a.png)

my guess is to open the port for only the docker container, but how would i do that with ufw?

**Comment by rezzorix** [comment]
Well again,

your firewall allows 25566
but it does not allow 25401

So you need to open 25401, too.

**Comment by resu-cireneg** [comment]
172.17.0.1 is the host in your case, BUT

Binding at program start might not necesarily bind later coming-up interfaces

you might need `iptables -I INPUT -d 0.0.0.0 -p tcp --dport 12345 -j ACCEPT;iptables -I FORWARD -d 0.0.0.0 -p tcp --dport  -j ACCEPT` 
( 0.0.0.0 == hostip , 12345 == port ) 

since newer docker versions sometimes block this
if the minecraft server is open anyway , take its external IP and port ( e.g. `curl -s -4 ifconfig.co/json` )
and add the iptables rules ;)

**Comment by RubenHetKonijn** [comment]
I've decided to just turn off the firewall which works, thanks for helping!
