### ISSUE TITLE
Search Headers with Keyword

### ISSUE THREAD

**Issue by resu-cireneg** [louislam/uptime-kuma#1240]
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

API, New Monitor

### 🔖 Feature description

A Search for the Keyword in the Headers and not only the body, since checking newer standards (e.g CSP  ) is impossible only by meta tags

### ✔️ Solution

extend the search to the returned HTTP headers as well

### ❓ Alternatives

using proxy scripts that return the headers as body part (least-preferred)

### 📝 Additional Context

thanks if you do so

**Comment by CommanderStorm** [comment]
This is not reproducible:
![image](https://github.com/louislam/uptime-kuma/assets/26258709/350e67d9-fe71-4c51-a4d6-82e7a95b658c)

Uptime Kuma checks aproximatly
```py
def monitor_if_site_is_down(url, keyword)
  response=request.get(url)
  return keyword in response.text
```

Could you please provide a testcase of what you mean?

**Comment by CommanderStorm** [comment]
We are going to continue to track this issue in #3568, as said issue is more concrete in how header searching should be implemented
=> closing as a duplicate (despite this being the older issue)
