### ISSUE TITLE
Multi Keyword search

### ISSUE THREAD

**Issue by resu-cireneg** [louislam/uptime-kuma#1241]
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

API, New Monitor, UI Feature

### 🔖 Feature description

* it would be cool to just set a json ( or ui table) for multiple monitors like
```
{ 
  "dom1.tld":"hasTOIncludeThis",
  "dom2.tld":"hasTOIncludeThat"
}
```

### ✔️ Solution

clone or abstract http monitor class

### ❓ Alternatives

multiple monitors or watching external instances of Cabot/UptimeRobot/UptimeKuma(?) for a whole service-set(stack) to be ok 

### 📝 Additional Context

thanksalot

**Comment by CommanderStorm** [comment]
I don't know what you mean by the following (you are missing some context)

> multiple monitors or watching external instances of Cabot/UptimeRobot/UptimeKuma(?) for a whole service-set(stack) to be ok

> clone or abstract http monitor class

It is not clear what you are reaaly requesting here.
I think you are requesting one of the below, which is much more clear in the feature request:
- #1323
- https://github.com/louislam/uptime-kuma/issues/379
- #2693 

=> I am going to close this as a duplicate. We can reopen if this is not already tracked in a different isssue.
