### ISSUE TITLE
disk I/O error with SQLite

### ISSUE THREAD

**Issue by planetetv** [louislam/uptime-kuma#1244]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

Hello there,

I recently tried to install uptime-kuma on DigitalOcean (paid plan). 
When I add the the container in the app section, I have this error : 

<img width="1268" alt="Capture d’écran 2022-01-31 à 22 29 14" src="https://user-images.githubusercontent.com/61663234/151876616-7a1fe93d-3c7e-481a-937e-f19d61bba6bb.png">

Do you know what cause the issue, maybe a misconfiguration on my side?
(I used the "app" section of DigitalOcean).

Thanks :) 

### 🐻 Uptime-Kuma Version

Latest

### 💻 Operating System and Arch

DigitalOcean

### 🌐 Browser

Chrome

**Comment by louislam** [comment]
I am running Uptime Kuma too on Digital Ocean Droplet without any problems.

Make sure you are not running on a mounted volume.

**Comment by anilpedamallu** [comment]
<img width="699" alt="image" src="https://user-images.githubusercontent.com/13312999/206900396-22df0d14-448a-4f01-91df-9c0dccc2e7d7.png">

**Comment by anilpedamallu** [comment]
Hello all, any idea what needs to be done here ^^? Tried all ways but nothing worked.
please let me know, thanks in advance
