### ISSUE TITLE
show hosts which are down first

### ISSUE THREAD

**Issue by theoneandonly-vector** [louislam/uptime-kuma#1245]
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

UI Feature

### 🔖 Feature description

To see better what currently needs attention, list the Monitors which report "down" on the left side before all other Monitors.

### ✔️ Solution

To see better what currently needs attention, list the Monitors which report "down" on the left side before all other Monitors.

**Comment by koen20** [comment]
Duplicate of #654 and #1165

**Comment by jeremyrnelson** [comment]
@theoneandonly-vector  - it seems like we've got a lot of tickets open referencing the same features.  Is there anything in this ticket that's not covered in #1585 where there's already a pull request?  If not, can you close this?
