### ISSUE TITLE
Uptime is always 100%

### ISSUE THREAD

**Issue by Scheggia0** [louislam/uptime-kuma#1248]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

My services went offline and the uptime rate dropped immediately afterwards. The problem is that after 1-2 days it is back to 100%, this shouldn't happen because I have been using uptime for more than 2/3 weeks, and it should be 99 ....%

### 🐻 Uptime-Kuma Version

1.11.3

### 💻 Operating System and Arch

Ubuntu 20.04 x86

### 🌐 Browser

Mozilla Firefox

### 🐋 Docker Version

No docker

### 🟩 NodeJS Version

16.13.1

**Comment by Scheggia0** [comment]
> Where did you see the uptime return to 100%? The status page and the list on the dashboard only show uptime for the last 24 hours. If you looked there, that is the reason that it went to 100% after 24 hours.

Thanks, can I change this option and make sure it doesn't reset after 24h?

**Comment by koen20** [comment]
I don't think that's possible currently. You can view the uptime for longer periods on the dashboard page when opening a monitor. Someone opened a feature request 4 days ago for configurable time periods on the status page #1234 .

**Comment by Scheggia0** [comment]
Thanks
