### ISSUE TITLE
Copy / duplicate a notification

### ISSUE THREAD

**Issue by brainshower** [louislam/uptime-kuma#1249]
In Settings, under Notifications, when setting up a notification, it would be helpful to duplicate an existing notification as a starting point.

Some notifications have a lot of parameters (e.g. email), and duplicating a previously saved notification type as a starting point for a new notification allows for minor edits without copying/pasting everything else from the original notification config.

**Comment by cryptedx** [comment]
Great idea. I was searching for that. Can you please add that feature? Thanks.
