### ISSUE TITLE
Add MQTT notification

### ISSUE THREAD

**Issue by thennart** [louislam/uptime-kuma#125]
Be able to notify to MQTT queue

**Comment by louislam** [comment]
apprise maybe supports in the future.

Related request: https://github.com/caronc/apprise/issues/388

**Comment by louislam** [comment]
Just check again, MQTT has been supported by apprise. 

https://github.com/caronc/apprise/releases/tag/v0.9.5.1

However, you need to install a library, so I believe it can be done for non-Docker users only.
```
pip install paho-mqtt
```

**Comment by gaby** [comment]
He could also build his own Docker image via:

```
FROM louislam/uptime-kuma:1-debian

RUN pip3 install --no-cache-dir paho-mqtt
```
