### ISSUE TITLE
Cannot connect to the socket server. [Error: websocket error] Reconnecting...

### ISSUE THREAD

**Issue by rexdivakar** [louislam/uptime-kuma#1250]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

I have configured my reverse proxy using nginx and cloudflare with strict ssl support but my uptime kuma setup fails to open up.

Error: Cannot connect to the socket server. [Error: websocket error] Reconnecting...

### 🐻 Uptime-Kuma Version

1.11.3

### 💻 Operating System and Arch

Ubuntu 20.1

### 🌐 Browser

Chrome

### 🐋 Docker Version

Docker version 20.10.7

**Comment by koen20** [comment]
Did you use the Nginx config from the wiki with the required headers?
https://github.com/louislam/uptime-kuma/wiki/Reverse-Proxy#nginx

Do you have websockets enabled in Cloudflare?
Please post the Nginx config if that's not the problem.

**Comment by rexdivakar** [comment]
i added proxy headers and it started working, thanks for the info

**Comment by Merlynr** [comment]
你好，我根据文档进行配置了，依旧出现这种问题。

![Snipaste_2022-03-22_18-36-19](https://user-images.githubusercontent.com/30440094/159463270-5f195eec-dd3b-4e5e-b6af-5178676d73b7.png)
