### ISSUE TITLE
create another account

### ISSUE THREAD

**Issue by W3T3R4NN** [louislam/uptime-kuma#1255]
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

Other

### 🔖 Feature description

another users can create another acount in website. This user can see their own uptimes and can create dashboard

### ✔️ Solution

another users can create another acount in website. This user can see their own uptimes and can create dashboard

**Comment by Appoxo** [comment]
+1

**Comment by darks00ul** [comment]
+1

**Comment by thompol** [comment]
Possible duplicate of #128

**Comment by adiastra** [comment]
I am unclear if this has been implemented but I would really like this feature. Aven basic multi user functionality would be a great place to start
