### ISSUE TITLE
Search Headers with Keyword

### ISSUE THREAD

**Issue by Appoxo** [louislam/uptime-kuma#1256]
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

UI Feature

### 🔖 Feature description

Search body for things like "Healthy"

### ✔️ Solution

Search for specific word in <body></body>

### 📝 Additional Context

Would be appreciated :)

**Comment by rezzorix** [comment]
Do I understand your quesiton right; you dont want to check "HTML headers" you want to check "text headers" on a website?
If so, then the monitor you require is in the list and literally called "HTTP(s) - Keyword".

**Comment by rezzorix** [comment]
If you want "html headers", then the request would be a duplicate with https://github.com/louislam/uptime-kuma/issues/1256

**Comment by Appoxo** [comment]
> Do I understand your quesiton right; you dont want to check "HTML headers" you want to check "text headers" on a website? If so, then the monitor you require is in the list and literally called "HTTP(s) - Keyword".

Fo example with jellyfin:
If you open jellyfin:8096/status you get a nearly blank page with the word "Healthy" on it.
Iwant to search the page for a keyword in the <body>-tag.
I think I explained my request badly
