### ISSUE TITLE
Repoted time in notifications

### ISSUE THREAD

**Issue by amastelek** [louislam/uptime-kuma#1262]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

The time in notifications is reported in UTC but I'm on SAST.  The dashboard has the correct time in SAST.

How do I align the notifications in the email?

### 🐻 Uptime-Kuma Version

1.11.3

### 💻 Operating System and Arch

Debian 10

### 🌐 Browser

Firefox

**Comment by neevot** [comment]
Hello there,

I am also having the same issue. It is showing the correct time (UTC+1) but when a service goes down it, in the notification it is the wrong time (UTC+0)

**Comment by Shourai** [comment]
The issue is being discussed here: https://github.com/louislam/uptime-kuma/issues/40
It would be great to have this implemented.
