### ISSUE TITLE
Help for custom domain (NODEJS)

### ISSUE THREAD

**Issue by GCGabry** [louislam/uptime-kuma#1268]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

Hi guys, I want to add a custom domain for my public uptime kuma status page.

I'm not a programmer, could you please list all the precise commands below? Thank you

### 🐻 Uptime-Kuma Version

latest version of uptime kuma

### 💻 Operating System and Arch

Online DanBot Hosting

### 🌐 Browser

Brave Browser

### 🟩 NodeJS Version

latest version of nodejs

**Comment by uiyash** [comment]
Use Nginx Reverse Proxy!

**Comment by GCGabry** [comment]
Can you write for me a tutorial? @uiyash

**Comment by uiyash** [comment]
https://www.tecmint.com/nginx-as-reverse-proxy-for-nodejs-app/

Hope this helps!

**Comment by uiyash** [comment]
this is my uptime kuma application

https://uptime.daxy.in/status
