### ISSUE TITLE
Email blacklist monitoring

### ISSUE THREAD

**Issue by armandofcom** [louislam/uptime-kuma#1271]
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

New Monitor

### 🔖 Feature description

Being able to monitor the IP of the mail servers to see if they are on the blacklist

### ✔️ Solution

Systems like https://mxtoolbox.com/blacklists.aspx can be used

**Comment by rezzorix** [comment]
You could use a HTTP(S) Keyword for that...

With mxtoolbox the link to monitor would look like this: 
`https://mxtoolbox.com/SuperTool.aspx?action=blacklist%3ayoururl.com&run=toolpage`

The keyword to check for is "LISTED"

**Comment by arch1v1st** [comment]
I had hoped @rezzorix suggestion would work, but it seems that the mxtoolbox page uses JavaScript to render the blacklist DIV hence a keyword check can't see the values.  Does anyone else have any suggestions on how to accomplish this, for free?

**Comment by Computroniks** [comment]
I found this Stack exchange post about the issue, but I don't think that the solution would be much help in terms of uptime-kuma as you would have to monitor each individual blacklist https://serverfault.com/questions/496759/how-to-check-ip-blacklist-using-curl-wget-request-to-mxtoolbox. I did also find this bash script https://github.com/adionditsak/blacklist-check-unix-linux-utility/blob/master/bl but that also seems to just query the blacklist dns servers directly.

**Comment by rezzorix** [comment]
> I had hoped @rezzorix suggestion would work, but it seems that the mxtoolbox page uses JavaScript to render the blacklist DIV hence a keyword check can't see the values. Does anyone else have any suggestions on how to accomplish this, for free?

You could check each RBL direcly, only downside is that you need to setup several monitors...

As a multi-check, well aside from mxtoolbox.com there are many many others; Google is your friend
This one here should work with Uptime Kuma: https://multirbl.valli.org/

**Comment by arch1v1st** [comment]
@Computroniks - thanks!  I came across that github project too from my research after posting this as well.  

@rezzorix - Appreciated, and I also came across multirbl.valli.org along the way (via Google too! :) ), however the same issue with the HTML vs JavaScript filling in the actual check data in the DOM remains.  Uptime Kuma's Keyword search can't really 'see' the word "Listed" there either.

**Comment by rezzorix** [comment]
Ha yes, you are right, I made the mistake by using "listed" as keyword, which is in the top part of the html... thats why it was found.

"Listed" with capital "L" is indeed not found...

Nevertheless, another thought.... I have several IP-addresses... all of them are at least listed in some of the lists, mainly the ones that block whole IP ranges just because of bad apples (e.g. UCEPROTECT Level 3)...

So the result of setting up a monitor for pages that collect results from many blacklists most likely will always give you a warning...

**Comment by simplysexyboy** [comment]
anyone gonna do this feature?

**Comment by CommanderStorm** [comment]
mxtoolbox do offer an api: https://mxtoolbox.com/c/products/mxtoolboxapi
Said API should be monitorable via the json-query monitor.

We now support the more resource intensive Real browser (chromium) monitoring type.
Said monitor does allow execution of arbitrary js code.
=> closing as resolved

Adding such a dedicated monitor would have significant maintenance burden which I don't think could/should support.
If you are maintaining a commercial service = making money and being on a blacklist is something that could disrupt your buisness, I would consider adding a monitoring plan:
https://mxtoolbox.com/Public/UpgradeV2.aspx?feature=no-feature-selected&source=pricing

If not, the free tier likely is sufficient.
