### ISSUE TITLE
Increase "Hit- Hoverbox" for '<div class="beat"' on the Statuspage for better Userexperience

### ISSUE THREAD

**Issue by JAKAMI99** [louislam/uptime-kuma#1272]
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

UI Feature

### 🔖 Feature description

The boxes where you can hover your mouse over to see the individual timestamps for the boxes have a too small "triggerarea". There is no reason why they should have spaces between them, it would look and feel better if you could fluidly "scroll" over those single beats.

### ✔️ Solution

Increase the Area where the mouse triggers a '--hover-scale' and show the 'title' including the time

### 📝 Additional Context

Thanks for this awesome project <3

**Comment by codexkunal** [comment]
@CommanderStorm @JAKAMI99 
I'd like to work on this. I'll expand the hover trigger area for smoother transitions between boxes and ensure the time title is displayed consistently. I'll submit a PR soon with these changes!

**Comment by adityarawat007** [comment]
@CommanderStorm please assign me this issue

**Comment by CommanderStorm** [comment]
@adityarawat007 we don't assign people. First of all because we can't (only contributors and the issue creates can be assigned) and secondly because we don't think that the additional burocracy is better.

In this case let's see what @codexkunal has done => let's not do duplicate effort ^^

**Comment by R-HNF** [comment]
I'll try this issue.

**Comment by R-HNF** [comment]
@CommanderStorm 
I have submitted the following PR! Cloud you please review it? Thank you.
* #5223
