### ISSUE TITLE
Uptime kuma showing blank screen when connecting through domain & reverse proxy

### ISSUE THREAD

**Issue by maxtheking** [louislam/uptime-kuma#1275]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

Hi all,

I'm running Uptime Kuma in a docker container, and can access it using it's local IP/hostname just fine.
However, when I try accessing it through my domain (status.mydomain.com) it just presents a blank page.

This is the uptime kuma server block in my nginx reverse proxy:
![image](https://user-images.githubusercontent.com/43993269/153037306-b2909b00-c726-4e27-b1d5-0186d66c6b28.png)

I am using CloudFlare as well. WebSockets are turned on.

Any ideas what's going wrong here?

### 🐻 Uptime-Kuma Version

1.11.3

### 💻 Operating System and Arch

Debian 10

### 🌐 Browser

Google Chrome 98.0.4758.82

### 🐋 Docker Version

Docker 19.03.8

**Comment by 1arrcy1** [comment]
Same issue here, have been trying to fix it for hours.
Also getting blank screen. Im using nginx proxy manager (also direct acces locally works)
![Knipsel](https://user-images.githubusercontent.com/69429134/153304270-9233c5f5-b453-4b5a-86a3-ce9328d1c2f4.PNG)

**Comment by rezzorix** [comment]
I had this problems frequently with Nginx Proxy Manager and different Proxy Hosts that I forward to (not only uptime-kuma).
Sometimes when SSL settings or certificate of the proxy host are changed; the page will not be reachable and you get a blank page.
Restarting/Recreating the Nginx Proxy Manager might solve this problem.
I think this issues were fixed with Nginx Proxy Manager v2.19.4 / v2.19.5 - at least for me.

**Comment by appuchias** [comment]
Also have the problem. I'm using traefik 2.6.1 and I'm sure the request is reaching uptime kuma but it just shows a blank page.
I have tried setting the 'Primary Base URL' in the general settings to the hostname I'm using to access it but it hasn't helped.
I also tried restarting everything without success. Any idea?

**Comment by appuchias** [comment]
> Also have the problem. I'm using traefik 2.6.1 and I'm sure the request is reaching uptime kuma but it just shows a blank page. I have tried setting the 'Primary Base URL' in the general settings to the hostname I'm using to access it but it hasn't helped. I also tried restarting everything without success. Any idea?
> 
> Edit: Uptime Kuma version 1.11.4

I no longer have the issue. Now the website loads normally. I'm not sure what I did to solve it. Maybe it was some kind of problem with Traefik, it's the only thing I may have changed from then until now.

**Comment by xavier-hernandez** [comment]
Using NPM I have the same issue. The vendor.js, manifest, etc are going to the root URL. 

I'm trying to reverse proxy using a custom location.
proxy host
test.com - main website, plain html (server 1)
test.com/kuma - uptime kuma (server 2)

Blank page when I visit test.com/kuma

I tried changing the Primary Base URL but that doesn't look like it does anything. My expectation is that if I change the Primary Base URL to say something like https://google.com/ I should break Uptime Kuma. Am I wrong?

Looks like it keeps looking for js files at the root of the domain.

**Comment by gaby** [comment]
This is a known issue, tracked here #147
