### ISSUE TITLE
I need to send Email via SMTP port (465) it uses SSL security but app allows only (none/starttls & tls) 

### ISSUE THREAD

**Issue by uiyash** [louislam/uptime-kuma#1277]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

I need to send Email via SMTP port (465) it uses SSL security but app allows only (none/starttls & tls) 
when i choose tls and set port 465 
the app shows email sent but haven't actually recieved the mail! 

### 🐻 Uptime-Kuma Version

1.11.3

### 💻 Operating System and Arch

Ubuntu 20.04

### 🌐 Browser

Chrome

**Comment by mindlesstux** [comment]
Is the mailserver one you control?

I just setup the notification like you indicated, TLS, not none/startls.  Port 465.  Supplied the other fields for my mailcow server.  It sends the message.  Any chance you might be able to look at the logs that kuma generates to see if there is a error message that might be occuring "after" it thinks the mail sent?  If the mail server is under your control, any chance of looking at those logs to see if maybe its doing something there?
