### ISSUE TITLE
Does the https keyword search actually work?

### ISSUE THREAD

**Issue by famewolf** [louislam/uptime-kuma#1279]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

I've tried 3 or 4 https with keyword search and all have come back with keyword not found...one was my asus router login page and I searched for "Username".  Another was a sold out item at target and I searched for "Sold Out" so I'd be notified when it came back in stock...but it also said not found.  Am I missing something?

### 🐻 Uptime-Kuma Version

1.11.3

### 💻 Operating System and Arch

Truenas (based on Debian Buster x86_64)

### 🌐 Browser

Mozilla Firefox

### 🐋 Docker Version

K3S

**Comment by FlorianMifsud** [comment]
Log (http server+uptime kuma) ? behind CF/WAF ?

Site link and word?

**Comment by famewolf** [comment]
https://www.target.com/p/motorola-ma1-wireless-android-auto-car-adapter/-/A-85692043  with keyword "Sold Out".    I changed the keyword to "notifyMeUrl" and it find it so I'm getting sold out is coming from a script of some type.  Sorry for the inconvenience.
