### ISSUE TITLE
Add Notification Service Line notify

### ISSUE THREAD

**Issue by whosawhosa** [louislam/uptime-kuma#1281]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

line message notifycation 500 free broadcasts/messages a month,
can use line notify notifycation unlimited?
thanks!

### 🐻 Uptime-Kuma Version

latest

### 💻 Operating System and Arch

ubuntu20

### 🌐 Browser

google chrome

**Comment by wezmag** [comment]
The built-in Apprise can be used to send notification via Line Notify.

You can setup notification with the following settings:

**Notification Type:** Apprise
**Friendly Name:** use whatever name you want, I just used "Line Notify"
**Apprise URL:** forms://notify-api.line.me/api/notify/?+Authorization=Bearer%20{your token}

You can create your token here: https://notify-bot.line.me/

That's it!
