### ISSUE TITLE
DNS check doesn't work through IPv6 DNS server

### ISSUE THREAD

**Issue by Revertron** [louislam/uptime-kuma#1290]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### Description

If I try to monitor AAAA records through some particular IPv6 DNS server (for example Googles `2001:4860:4860::8888`) I always have negative results.

### 👟 Reproduction steps

Just try to use DNS over IPv6 server like on screenshot:
![image](https://user-images.githubusercontent.com/105154/153302812-35153bf0-f7a4-4141-8009-ce11163b8461.png)

### 👀 Expected behavior

It would be good to use IPv6 DNS servers.

### 😓 Actual Behavior

Now it is impossible to use DNS over IPv6.

### 🐻 Uptime-Kuma Version

1.11.4

### 💻 Operating System and Arch

Debian 11

### 🌐 Browser

Firefox 93

### 🐋 Docker Version

Docker version 20.10.12, build e91ed57

**Comment by louislam** [comment]
Cannot reproduce with my demo site. 

Did you IPv6 support in your Docker config?

![image](https://user-images.githubusercontent.com/1336778/153387811-b7532324-bfee-47fa-a3b4-3d12160245e8.png)

**Comment by Revertron** [comment]
> Did you IPv6 support

Enable? Or what?

**Comment by Revertron** [comment]
Okay, if I start docker image with `--network host` instead of `-p 3001:3001` everything works.
But FYI, the simple HTTP(s) kind of check for `https://ipv6.google.com` is not working with default docker run string in wiki.

**Comment by louislam** [comment]
Yes, enable ipv6. Please check docker's documentation, IPv6 is not enabled by default.
https://docs.docker.com/config/daemon/ipv6/

As far as I know, if you use the host network, all ports inside Uptime Kuma container will bind to your host. It may affect future update, so I am not recommended.

**Comment by shaojs321** [comment]
> Okay, if I start docker image with `--network host` instead of `-p 3001:3001` everything works. But FYI, the simple HTTP(s) kind of check for `https://ipv6.google.com` is not working with default docker run string in wiki.

Encountered the same problem, changed to --network host, it has been solved
