### ISSUE TITLE
Uptime kuma adds HTML as playlists in Logitech media server

### ISSUE THREAD

**Issue by tonyt321** [louislam/uptime-kuma#1291]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### Description

<img width="647" alt="Capture" src="https://user-images.githubusercontent.com/34804458/153314695-cec6de75-e4cd-4c47-a094-119780d8ab29.PNG">

### 👟 Reproduction steps

install uptime kuma and logitech media server at the same time wait about 10 min and it will do it

### 👀 Expected behavior

for it to not add html as playlists

### 😓 Actual Behavior

html from uptime kuma is some how being added each line as a new playlist

### 🐻 Uptime-Kuma Version

Version: 1.9.1

### 💻 Operating System and Arch

windows

### 🌐 Browser

chrome

**Comment by rezzorix** [comment]
Interesting. 
Have you set up a monitor checking your Media Server?
If yes, can you share the details?

**Comment by louislam** [comment]
Please check the plugins of Logitech Media Server, I believe some plugins try to import playlists from http://xxxx:3000.

**Comment by tonyt321** [comment]
I removed some plugins that do with playlists seems to be working good now
, thanks so much
