### ISSUE TITLE
impossible to use my domain to administer the site

### ISSUE THREAD

**Issue by YunoOkamii** [louislam/uptime-kuma#1293]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

Hello,

I installed Kuma on my server using docker and I made a port redirection from my domain but when I want to go on the direct domain I have this error 

https://s.yunookami.com/msedge_aUNPftV6uM.png

this is what my ngnix configuration file looks like : https://haste.yunookami.com/elulubalis.nginx

Do you have any idea what the problem is?

### 🐻 Uptime-Kuma Version

1.11.3

### 💻 Operating System and Arch

Debian 11

### 🌐 Browser

Brave

### 🐋 Docker Version

20.10.5+dfsg1, build 55c4c88

**Comment by louislam** [comment]
Please read the wiki: https://github.com/louislam/uptime-kuma/wiki/Reverse-Proxy#nginx

**Comment by YunoOkamii** [comment]
Thank you it works !

good day to you :D
