### ISSUE TITLE
Cloudflare Error 523: Origin is unreachable - Direct over IP is fine

### ISSUE THREAD

**Issue by BothimTV** [louislam/uptime-kuma#1294]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

I can access the server over the IP address, but not over my Cloudflare domain, with correct records, nginx configuration. I want with SSL and I alredy created a certificate but its not working with or without certificate. Its just Error 523:
![image](https://user-images.githubusercontent.com/50715457/153486425-2f8d643e-1e4d-4319-ac16-4c8eef863234.png)

### 🐻 Uptime-Kuma Version

1.11.4

### 💻 Operating System and Arch

Ubuntu 20.04.3 LTS

### 🌐 Browser

Google Chrome 98.0.4758.82

### 🐋 Docker Version

Docker version 20.10.12, build e91ed57

**Comment by BothimTV** [comment]
![image](https://user-images.githubusercontent.com/50715457/153487028-86a609c7-79a9-4f36-aa7a-dd3763a564b5.png)

/etc/nginx/sites-enabled/uptime-kuma.conf:

`server {
  listen 443 ssl http2;
  server_name uptime.xxxxxxxx.com;
  ssl_certificate     /home/ubuntu/.acme.sh/uptime.bothimtv.com/uptime.xxxxxxxx.com.cer;
  ssl_certificate_key /home/ubuntu/.acme.sh/uptime.bothimtv.com/uptime.xxxxxxxx.com.key;

  location / {
    proxy_set_header   X-Real-IP $remote_addr;
    proxy_set_header   X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_pass         http://localhost:3001/;
    proxy_http_version 1.1;
    proxy_set_header   Upgrade $http_upgrade;
    proxy_set_header   Connection "upgrade";
  }
}`

**Comment by mathiskir** [comment]
Hey,
Could you try accessing the status page directly like ip:port and see if that works.
With this we can find out if the problem is related to uptime kuma or nginx

**Comment by mathiskir** [comment]
Have you tried taking a look at your nginx error log?
Its located here: `/var/log/nginx/error.log`

**Comment by rezzorix** [comment]
Have you tried changing localhost to the ip-address of the docker-container?

**Comment by BothimTV** [comment]
> Have you tried taking a look at your nginx error log? Its located here: `/var/log/nginx/error.log`

The file is empty

**Comment by BothimTV** [comment]
> Have you tried changing localhost to the ip-address of the docker-container?

still now working

**Comment by jamesmacwhite** [comment]
@rezzorix I think that's a typo, they mean "Still not working".

@BothimTV The error from Cloudflare is a network issue between Cloudflare and your server. It isn't directly related to Uptime Kuma. Have you had a look at the [Cloudflare troubleshooting](https://support.cloudflare.com/hc/en-us/articles/115003011431-Troubleshooting-Cloudflare-5XX-errors#523error) docs?

**Comment by louislam** [comment]
It seems that it is not a uptume kuma issue.
Most likely you have a wrong dns record which is pointing to a unreachable ip.

If it is reachable, the error should be 521, not 523.

**Comment by DatDraggy** [comment]
What port is your instance running on? Cloudflare only allows proxy for a select list of ports https://developers.cloudflare.com/fundamentals/get-started/network-ports
