### ISSUE TITLE
Where do I get the token 2FA

### ISSUE THREAD

**Issue by xgusto** [louislam/uptime-kuma#1299]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

If I want to use 2FA, where do I get the token?

### 🐻 Uptime-Kuma Version

1.11.4

### 💻 Operating System and Arch

Debian 11

### 🌐 Browser

Mozilla, Chrome ...

**Comment by xgusto** [comment]
If I want to use 2FA, where do I get the token?

**Comment by koen20** [comment]
You need to add the account to a 2FA application. You can use an app like Google Authenticator or andOTP. The 2FA settings in Uptime Kuma can be found in the settings in the security tab.
When you add an account, the application generates a token.

**Comment by xgusto** [comment]
thank you it works

**Comment by xgusto** [comment]
I used this https://2fas.com/
thx
