### ISSUE TITLE
Systemd Unit

### ISSUE THREAD

**Issue by 12nick12** [louislam/uptime-kuma#13]
Any chance someone might be able to get a systemd unit to work? I tried, but was failing. I ended up creating a basic bash script then calling that via systemd. Not the greatest, but works. I'd love to get that script out of the picture.

**Comment by louislam** [comment]
PM2 did a great job for this, it is recommended.

```
# Install PM2
npm install pm2 -g

# Start Uptime Kuma Server
pm2 start npm --name uptime-kuma -- run start-server

# add PM2 to systemd
pm2 save
pm2 startup

```

More info: https://pm2.keymetrics.io/docs/usage/startup/

**Comment by TheGuyDanish** [comment]
```ini
[Unit]
Description=Uptime-Kuma - A free and open source uptime monitoring solution
Documentation=https://github.com/louislam/uptime-kuma
After=network.target

[Service]
Type=simple
User=uptime
WorkingDirectory=/home/uptime/uptime-kuma
ExecStart=/usr/bin/npm run start-server
Restart=on-failure

[Install]
WantedBy=multi-user.target
```

Tested by putting it into /etc/systemd/system/uptime-kama.service, running systemctl daemon-reload, systemctl enable uptime-kama.service and restarting. Works a charm.
