### ISSUE TITLE
Webhook notification to LunaSea

### ISSUE THREAD

**Issue by cnelson-pdx** [louislam/uptime-kuma#130]
I use LunaSea for a lot of device notifications [https://docs.lunasea.app/lunasea/notifications/custom-notifications](https://docs.lunasea.app/lunasea/notifications/custom-notifications)

 you can see at their wiki that they support custom notifications in JSON format, but are specifically title and body in the payload. 

I used [Webhook.site](https://webhook.site/#!/) to view the payload you're sending and would love to see the title be "UptimeKuma: MonitorFriendlyName" and the body would be the msg currently sent "msg": "[Posterr] [🔴 Down] Request failed with status code 502" but maybe without the Monitor friendly name in brackets as that'd be in the Title already.

If this is beyond capability i understand, just thought i'd try as i really like the products look and feel so far

Thanks,
Christian

**Comment by louislam** [comment]
You can get the error msg and the monitor name here:

```json
{
  "heartbeat": {
    "monitorID": 2,
    "status": 0,
    "time": "2021-07-31 03:58:23",
    "msg": "getaddrinfo ENOTFOUND test",👈🏻👈🏻👈🏻👈🏻
    "important": true,
    "duration": 0
  },
  "monitor": {
    "id": 2,
    "name": "test",👈🏻👈🏻👈🏻👈🏻👈🏻
    "url": "https://test",
    "hostname": null,
    "port": null,
    "maxretries": 0,
    "weight": 2000,
    "active": 1,
    "type": "http",
    "interval": 60,
    "keyword": null,
    "notificationIDList": {
      "3": true
    }
  },
  "msg": "[test] [🔴 Down] getaddrinfo ENOTFOUND test"
}
```

**Comment by NiNiyas** [comment]
@cnelson-pdx is this what you had in mind?
![LunaSea](https://user-images.githubusercontent.com/54862871/127729034-5dcec152-12c3-4d1f-b9da-37cbe7d4b138.jpg)

**Comment by cnelson-pdx** [comment]
> @cnelson-pdx is this what you had in mind?
> ![LunaSea](https://user-images.githubusercontent.com/54862871/127729034-5dcec152-12c3-4d1f-b9da-37cbe7d4b138.jpg)

Yes, that is exactly what I was looking for. Is this something you modified yourself? or found via google? I tried my hand at looking through monitor.js and notification.js in UptimeKuma, but I'm no javascript developer and didn't have much luck.

Is this something I can modify myself pretty easy to work?

Thank you!

**Comment by NiNiyas** [comment]
I'll open a PR just in a minute.

**Comment by louislam** [comment]
Tested it successfully. Will be supported in next release. Thanks.

**Comment by sassanix** [comment]
How can I set this up now on lunasea? I don't see any customized webhook options.

**Comment by CommanderStorm** [comment]
> How can I set this up

![image](https://github.com/louislam/uptime-kuma/assets/26258709/aef6677b-07f8-475a-a01b-7bc471e55530)

**Comment by sassanix** [comment]
Figured it out, I had to click on any of the webhooks in the lunasea app and then I got my id that way. 

There isn't one setup just for uptime-kuma. 

Thank you for your help though.

**Comment by CommanderStorm** [comment]
If there is something we can improve, we try to put it into the UI.

I don't have enough context on said notification provider.
Could you write 1-2 sentences for https://github.com/louislam/uptime-kuma/blob/master/src/components/notifications/LunaSea.vue where the parameter can be found and how to get said notification provider working?

**Comment by sassanix** [comment]
> If there is something we can improve, we try to put it into the UI.
> 
> I don't have enough context on said notification provider. Could you write 1-2 sentences for https://github.com/louislam/uptime-kuma/blob/master/src/components/notifications/LunaSea.vue where the parameter can be found and how to get said notification provider working?

I can definitely help with that; I will see how to add instructions there.
