### ISSUE TITLE
Telegram auto get not working

### ISSUE THREAD

**Issue by mathiskir** [louislam/uptime-kuma#1300]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### Description

![image](https://user-images.githubusercontent.com/65130981/153773919-9c09951e-490f-40c7-8bbc-ef78c9b7a9ed.png)
If i try autoget in telegram notification it throws me this error.

### 👟 Reproduction steps

Create a telegram notification and use autoget

### 👀 Expected behavior

It should auto get the chatid

### 😓 Actual Behavior

It throwed an error and didn't get the chat id

### 🐻 Uptime-Kuma Version

1.11.4

### 💻 Operating System and Arch

Debian 11

### 🌐 Browser

Opera GX LVL3 (core: 83.0.4254.46)

### 🐋 Docker Version

-

### 🟩 NodeJS Version

v13.19.0

### 📝 Relevant log output

```shell
No errors in log
```

**Comment by xgusto** [comment]
Use this method to obtain a Chat ID https://api.telegram.org/bot5228804154:AAHE0IyuSqTdwvogRZXndNbkTAJtPvVBE-k/getUpdates

**Comment by mathiskir** [comment]
> Use this method to obtain a Chat ID https://sean-bradley.medium.com/get-telegram-chat-id-80b575520659
> `https://api.telegram.org/botXXX:YYYYY/getUpdates`
> xxx:yyyyy = your bot token

I know how that works, I just wanted to report that autoget isn't working

**Comment by louislam** [comment]
Thanks for the report. Fixed.
