### ISSUE TITLE
uptime-kuma working but not web access

### ISSUE THREAD

**Issue by darks00ul** [louislam/uptime-kuma#1303]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

I'm running uptime-kuma in a docker-swarm stack using Portainer to deploy it.
I just started to use this tool three days ago and I noted the following issue:

- At first I configured the monitors (http and icmp mix) and the email alert that I want to use.
- Everything is working just fine but I noted that after a day (or maybe less) of the container being up for some reason the web access at port 3001 stop responding.
- The wear thing is that the monitor still works when this happens because I continue to received alerts.
- If a restart the container everything works just fine until this happen again (It happens twice so far)

### 🐻 Uptime-Kuma Version

1.11.4

### 💻 Operating System and Arch

Ubuntu 20.04.3 LTS

### 🌐 Browser

Google Chrome Versión 98.0.4758.82 (Build oficial) (64 bits) 

### 🐋 Docker Version

20.10.12

**Comment by darks00ul** [comment]
Same here, I added a new monitor to the self uptime-kuma and so far I didn't loose web access..
Anything that I can look at to debug this?

**Comment by sachinwadhwa** [comment]
Happens again today. Monitor working as I can get alerts but UI down.

**Comment by darks00ul** [comment]
Hi @sachinwadhwa, no, I dont use traefik.
So far, after enabling self monitor on the uptime kuma (http probe itselft at port 3001) it doesn't stop working.
I hope this works to you too...
