### ISSUE TITLE
SMTP notification test fails. "Lost connection to the socket server"

### ISSUE THREAD

**Issue by kingannoy** [louislam/uptime-kuma#1304]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### Description

When configuring SMTP notification all goes well until I want to perform a test of the connection. This results in the following text showing in a red bar:
```
Lost connection to the socket server. Reconnecting...
```
Sometimes (about one in three times) it will also show this after the first one:
```
Cannot connect to the socket server. [Error: websocket error] Reconnecting...
```
The notification modal will not progress after this, showing a infinite spinning "save" button:
![image](https://user-images.githubusercontent.com/36500946/153963383-5c4bd465-0629-48ef-b04f-0c2620ea5abe.png)

It's possible to close the modal with the :x: at the right top, but when you reopen it, it's still spinning. Refreshing the page let's you try again.

Looking in the browser console I see:
```
Content Security Policy: This site (https://up.example.com) has a Report-Only policy without a report URI. CSP will not block and cannot report violations of this policy. 2
Content Security Policy: The page’s settings observed the loading of a resource at wss://up.example.com/socket.io/?EIO=4&transport=websocket (“default-src”). A CSP report is being sent. vendor.f2e417fe.js:55:57144
```

I see a similar issue mentioned in #143 so I checked the TLS versions of NodeJS and the server I'm connecting to. For NodeJS I see this uses `openssl: '1.1.1m+quic'`. This should support TLSv1.3. The mailserver is also offering a TLSv1.3 certificate.

### 👟 Reproduction steps

I'm not sure what steps were relevant for coming to this result, so I'll be a bit broad:
- Install uptime Kuma via Yunohost
- create a few monitors
- create a notification based on SMTP 
  - (I tried with both security options, and with "ignore TLS error" checked and unchecked.)
- Click test

### 👀 Expected behavior

A test email gets sent. Or a error is shown explaining what went wrong

### 😓 Actual Behavior

See description

### 🐻 Uptime-Kuma Version

1.11.3

### 💻 Operating System and Arch

Debian GNU/Linux 10 (buster)

### 🌐 Browser

96.0 (64-bit)

### 🐋 Docker Version

Unsure, I'm using [Yunohost](https://github.com/YunoHost-Apps/uptime-kuma_ynh)

### 🟩 NodeJS Version

'16.14.0'

**Comment by louislam** [comment]
It seems that the uptime-kuma was crashed. Was there any error log in the console?

Also could you able to reproduce the error in our demo site:
http://demo.uptime.kuma.pet/

**Comment by kingannoy** [comment]
> It seems that the uptime-kuma was crashed. Was there any error log in the console?

In the Console in the browser you mean? Under Webdeveloper tools? There I saw the `Content Security Policy` errors listed above.

If you mean another console please let me know. I have SSH access to the VPS it's installed on, but I'm not sure where to find the logs...

> Also could you able to reproduce the error in our demo site: http://demo.uptime.kuma.pet/

No, I can't reproduce the error, but I get another error, and this one I know how to solve!
```
Mail command failed: 550-verification failed for <up@example.com> 
550-Previous (cached) callout verification failure
550 Unknown sender
```

I will see if solving this will also solve the issue on my installation, but I'm not too hopeful. It seems like something is wrong with my installation.

**Comment by louislam** [comment]
If you cannot reproduce in demo site, it probably is not a uptime kuma bug. I suspected that it is related to YunoHost which is a unofficial way to install Uptime Kuma.

> If you mean another console please let me know. I have SSH access to the VPS it's installed on, but I'm not sure where to find the logs...

I am not familiar with YunoHost, you should check where is the application log.

**Comment by kingannoy** [comment]
Just for completion, I found the logs, I think this is the relevant part:
```
os.js:68
      throw new ERR_SYSTEM_ERROR(ctx);
      ^

SystemError [ERR_SYSTEM_ERROR]: A system error occurred: uv_interface_addresses returned Unknown system error 97 (Unknown system error 97)
    at Object.networkInterfaces (os.js:259:16)
    at resolver (/var/www/uptime-kuma/node_modules/nodemailer/lib/shared/index.js:16:34)
    at Object.module.exports.resolveHostname (/var/www/uptime-kuma/node_modules/nodemailer/lib/shared/index.js:74:5)
    at SMTPConnection.connect (/var/www/uptime-kuma/node_modules/nodemailer/lib/smtp-connection/index.js:326:27)
    at /var/www/uptime-kuma/node_modules/nodemailer/lib/smtp-transport/index.js:263:24
    at Immediate._onImmediate (/var/www/uptime-kuma/node_modules/nodemailer/lib/smtp-transport/index.js:70:35)
    at processImmediate (internal/timers.js:464:21) {
  code: 'ERR_SYSTEM_ERROR',
  info: {
    errno: 97,
    code: 'Unknown system error 97',
    message: 'Unknown system error 97',
    syscall: 'uv_interface_addresses'
  },
  errno: [Getter/Setter],
  syscall: [Getter/Setter]
}
```
