### ISSUE TITLE
Client zone

### ISSUE THREAD

**Issue by xgusto** [louislam/uptime-kuma#1305]
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

UI Feature

### 🔖 Feature description

I would accept creating new clients.

### ✔️ Solution

Possibility to view graphs for clients.

**Comment by CommanderStorm** [comment]
@xgusto 
We are consolidating duplicate issues a bit to make issue management easier.
I think, we should track this issue in #128 as there is no functional difference (maybe just small naming differences, but nothing that would require a different issue imo)
⇒ I am going to close this as a duplicate.
