### ISSUE TITLE
Apprise Update?

### ISSUE THREAD

**Issue by theoneandonly-vector** [louislam/uptime-kuma#1306]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

I would like to use Nextcloud Talk in Apprise, but it seems that the verison shipped with Kuma isn't up2date for it:
https://github.com/caronc/apprise/wiki/Notify_nextcloudtalk

### 🐻 Uptime-Kuma Version

1.11.4

### 💻 Operating System and Arch

ubuntu 21.04

### 🌐 Browser

Google Chrome 98

**Comment by jschwindt** [comment]
I still see apprise version 0.96 in the latest docker image pulled from dockerhub. Was that images pushed before the modifications of the `debian-base.dockerfile` file?

**Comment by theoneandonly-vector** [comment]
there's a new version now

**Comment by louislam** [comment]
https://github.com/louislam/uptime-kuma/commit/3681934d0519b425dda65f075301ac49c68d5bfc

Updated, would be available in the next release.
