### ISSUE TITLE
Tag color and text color with hexcode

### ISSUE THREAD

**Issue by Appoxo** [louislam/uptime-kuma#1309]
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

UI Feature

### 🔖 Feature description

Be able to create custom colors with hexcode instead of pre-selection. 
Not enough colors for different usecases

### ✔️ Solution

In addition to the pre-selection being able to create custom color tags by using hexcode
Because yellow tag and white text are bad we should also be able to change color of text.

**Comment by x-tk** [comment]
+1

**Comment by simone80an** [comment]
+1

**Comment by EVIL-Teken** [comment]
Would love to see this feature implemented in the next major release.

**Comment by chakflying** [comment]
Since 1.20.0 you can set a custom tag color by going into Settings -> Tags -> click on a tag.
