### ISSUE TITLE
Down Monitor is Automatically order up in list

### ISSUE THREAD

**Issue by vslknsgr** [louislam/uptime-kuma#1313]
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

UI Feature, Other

### 🔖 Feature description

Hello Team,

Down Monitor is Automatically order up in list 

otherwise , You just give the new link only show down monitor 

### ✔️ Solution

-

**Comment by teoxrr** [comment]
duplicate of #1165

**Comment by jeremyrnelson** [comment]
@vslknsgr - it seems like we've got a lot of tickets open referencing the same features.  Is there anything in this ticket that's not covered in #1585 where there's already a pull request?  If not, can you close this?

**Comment by CommanderStorm** [comment]
#3312 was merged and is available since `1.23.0`.
This likely covers this issue.
Selecting these parameters via query parameters is tracked in #3672
Filtering/sorting on the status page is tracked in #1512
