### ISSUE TITLE
Install karelkryda/uptime-kuma new incident-system

### ISSUE THREAD

**Issue by mathiskir** [louislam/uptime-kuma#1314]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

Hey,
so I wanted to test the new [incident system](https://github.com/karelkryda/uptime-kuma/tree/incident-system) that was made by karelkryda, but I don't know how to actually install it.
I'm on Debian 11.
I tried
I did

`git clone -b incident-system https://github.com/karelkryda/uptime-kuma`
`cd uptime-kuma`
`npm ci --production && npm run download-dist`
`node server/server.js`
got me this
![image](https://user-images.githubusercontent.com/65130981/154581547-129330f8-76cd-4bd2-b99b-d0ad37f684e4.png)
Seems like it's downloading the latest dist from this repository, how to change that?

### 🐻 Uptime-Kuma Version

custom karelkryda/uptime-kuma

### 💻 Operating System and Arch

Debian 11

### 🌐 Browser

Opera GX LVL3 (core: 83.0.4254.46)

### 🐋 Docker Version

-

### 🟩 NodeJS Version

v16.13.2

**Comment by louislam** [comment]
You may have to build the frontend dist by yourself. 

```
# without --production
npm ci 
npm run build
```


More details
https://github.com/louislam/uptime-kuma/blob/master/CONTRIBUTING.md#build-the-frontend
