### ISSUE TITLE
Autostart on reboot

### ISSUE THREAD

**Issue by pavl21** [louislam/uptime-kuma#1317]
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

Other

### 🔖 Feature description

start uptime kuma automatically by reboot linux. 

### ✔️ Solution

a script

**Comment by mathiskir** [comment]
You can just create a systemd service, [this](https://nodesource.com/blog/running-your-node-js-app-with-systemd-part-1/) is an example for ubuntu, It's probably roughly the same for other distros that are debian based.

**Comment by louislam** [comment]
> https://github.com/louislam/uptime-kuma/wiki/Systemd-Unit-File Here you are, just saw that there are already docs for that
> 
> This built in to uptime kuma doesn't really make that much sense

Agree, also pm2 or docker did the job already.
