### ISSUE TITLE
Prometheus requires HTTP Basic Auth even though auth is disabled

### ISSUE THREAD

**Issue by JaneJeon** [louislam/uptime-kuma#1318]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### Description

On the wiki, regarding the prometheus configuration, it says:

```
 basic_auth: # Only needed if authentication is enabled (default) 
      username: <your user>
      password: <your password>
```

However, even though my site has auth explicitly turned off, it still requires username and password when I visit the `/metrics` endpoint...!

It should _not_ require HTTP Basic Auth when auth is turned off.

### 👟 Reproduction steps

See above - just have an installation with auth setup, then try to visit `/metrics`

### 👀 Expected behavior

I'd expect to be able to GET `/metrics` without the basic auth!

### 😓 Actual Behavior

It requires username and password...!

### 🐻 Uptime-Kuma Version

1.11.4

### 💻 Operating System and Arch

alpine (docker)

### 🌐 Browser

Chrome

### 🐋 Docker Version

20.10.12

**Comment by proffalken** [comment]
@JaneJeon I've stumbled across this today as well, and I'm currently unable to get *any* response from the `/metrics` endpoint in my browser from the latest code on `master`.

I managed to hack together the original Promethus exporter code, but Javascript really isn't a language I'm comfortable with so I'm now trying to troubleshoot this too!

**Comment by proffalken** [comment]
I've done a bit more digging into this, and for some reason the web interface no longer returns data for the /metrics endpoint correctly.

### Targeting the front-end
```bash
curl "http://<user>:password>@localhost:3000/metrics"
<!DOCTYPE html>
<html lang="en">
<head>
  <script type="module" src="/@vite/client"></script>

    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png">
    <link rel="icon" type="image/svg+xml" href="/icon.svg" />
    <link rel="manifest" href="/manifest.json" />
    <meta name="theme-color" id="theme-color" content="" />
    <meta name="description" content="Uptime Kuma monitoring tool" />
    <title>Uptime Kuma</title>
</head>
<body>
<div id="app"></div>
<script type="module" src="/src/main.js"></script>
</body>
</html>
```

### Targeting the back-end
```bash
curl "http://<user>:<pass>@localhost:3001/metrics" | head -n 10
# HELP monitor_cert_days_remaining The number of days remaining until the certificate expires
# TYPE monitor_cert_days_remaining gauge
monitor_cert_days_remaining{monitor_name="Make Monmouth",monitor_type="http",monitor_url="https://www.makemonmouth.co.uk",monitor_hostname="null",monitor_port="null"} 87

# HELP monitor_cert_is_valid Is the certificate still valid? (1 = Yes, 0= No)
# TYPE monitor_cert_is_valid gauge
monitor_cert_is_valid{monitor_name="Make Monmouth",monitor_type="http",monitor_url="https://www.makemonmouth.co.uk",monitor_hostname="null",monitor_port="null"} 1

# HELP monitor_response_time Monitor Response Time (ms)
# TYPE monitor_response_time gauge
```

**Comment by chakflying** [comment]
Bug confirmed, for now you should be able to completely disable basic auth by replacing `server.js:213` with
```js
    app.get("/metrics", prometheusAPIMetrics());
```

**Comment by louislam** [comment]
Just checked this. For current implementation, you can pass empty or random username/password.

Let's see if I can fully disable the basicAuth middleware.
