### ISSUE TITLE
Method: POST Body: Not working.

### ISSUE THREAD

**Issue by key-str0ke** [louislam/uptime-kuma#1329]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

I have the following POST request setup under HTTP Options Body and Method is set to POST.

URL == https://test.local/index.php

`{
    "nocaptcha": "yes",
    "name": "test",
    "email": "test@test.com",
    "attention": "Technical",
    "message": "test",
    "g-recaptcha-response": "test"
}`

When testing it via curl, it works fine, not so much when I'm utilizing the above feature.

`curl 'https://test.local/index.php' \
  --data-raw 'nocaptcha=yes&name=test&email=test%40test.com&attention=Technical&message=test&g-recaptcha-response=test' \
  --compressed`

### 🐻 Uptime-Kuma Version

1.11.4

### 💻 Operating System and Arch

docker

### 🌐 Browser

chrome

### 🐋 Docker Version

latest

**Comment by key-str0ke** [comment]
Actually it looks like the POST requests is sent over as json instead of as a normal POST request.  Is there anyway to utilize the POST feature without using json?

`{"name":"test","email":"test@test.com","attention":"Technical","message":"test","g-recaptcha-response":"test"}`

Compared to:

`name=test&email=test%40test.com&attention=Technical&message=test&g-recaptcha-response=test`

**Comment by neilborromeo** [comment]
I believe this is still not fixed. I can only see options for JSON and XML. Should we add RAW?
