### ISSUE TITLE
Ignore error "dh key too small"

### ISSUE THREAD

**Issue by Lordingard** [louislam/uptime-kuma#1331]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

Hello,

I try to monitor the web interface of an internet box, but I have the error "dh key too small", so, the website is marked as down.
Can I ignore this error ?
The case for ignore ssl error is already ticked.
Thanks.

### 🐻 Uptime-Kuma Version

1.11.4

### 💻 Operating System and Arch

Docker container on Debian 11

### 🌐 Browser

Chrome, last version

### 🐋 Docker Version

20.10.12

**Comment by 8fXvSYUcRD7u** [comment]
Is this an HTTPS or HTTP website?
If both, then try the HTTP version, if not, could you send your config for that monitor? 
Of course, anonymizing things like the URL.

**Comment by Lordingard** [comment]
Unfortunaly, it's an HTTPS only web interface on an appliance (so, I can't change anything on the web server).
The configuration is basic with the case "ignore ssl error" ticked.

**Comment by jaxjexjox** [comment]
I am getting this error when attempting to configure smtp based email notification, nothing to do with my monitoring.  Is anyone else seeing this?



140615271229312:error:141A318A:SSL routines:tls_process_ske_dhe:dh key too small:../deps/openssl/openssl/ssl/statem/statem_clnt.c:2158:

**Comment by Lordingard** [comment]
It's an SSL error, so I suppose we can encounter that in multiple situations.
Here the screenshot of the error from Uptime Kuma
![Capture](https://user-images.githubusercontent.com/100278277/156359657-09096c40-ee8c-49bd-bd5b-e5ee13dfc679.PNG)
a

**Comment by Lordingard** [comment]
And here a screenshot of the config 
![Capture](https://user-images.githubusercontent.com/100278277/156360161-bf4e4db9-b373-497a-957d-72672f3e783e.PNG)
:

**Comment by jaxjexjox** [comment]
I figured it out, I had to mess with my notification settings a little and confirm the port from my ISP, I had that wrong.

I am now getting emails.

Nice little program, simple, lite, useful.   I used to fiddle with LibreNMS for similar functionality (and it's hella powerful!) but it was wildly complicated when this does so much for less.

Thanks for the help!

**Comment by 8fXvSYUcRD7u** [comment]
Yes, this is because of OpenSSL.
A view years back, they changed the Security configuration, to protect users from using weak encryption methods.
This can manifest in multiple errors.
```
Unable to connect with TLS encryption
routines:tls_process_ske_dhe:dh key too small
stream_socket_client(): SSL operation failed with code 1
OpenSSL Error messages: error:141A318A:SSL
```
Are the ones that I encountered.

The solution, as described [here](https://askubuntu.com/questions/1233186/ubuntu-20-04-how-to-set-lower-ssl-security-level) is to set a lower security level.

On a normal machine, this is done by:
finding your openssl.cnf ```openssl version -d```
and add to the top of that file:
```
openssl_conf = default_conf
```
and to the bottom:
```
[ default_conf ]

ssl_conf = ssl_sect

[ssl_sect]

system_default = system_default_sect

[system_default_sect]
MinProtocol = TLSv1.2
CipherString = DEFAULT:@SECLEVEL=1
```
Where ```CipherString = DEFAULT:@SECLEVEL=1``` defines the security level.

However, I don't know how to do this in a docker container.



> I am getting this error when attempting to configure smtp based email notification, nothing to do with my monitoring. Is anyone else seeing this?
>
> 140615271229312:error:141A318A:SSL routines:tls_process_ske_dhe:dh key too small:../deps/openssl/openssl/ssl/statem/statem_clnt.c:2158:

Yes, me to.
Same with a lot of other applications, like Nextcloud, zabbix, etc.
Seems like my Email Provider only supports weak encryption...

**Comment by Lordingard** [comment]
I think the best way is to add an environement variable on the Uptime Kuma Docker image, but I suppose the only way actualy is to redirect the openssl folder who contain the conf on the host (not a good practical...).
What do you think ?

**Comment by 8fXvSYUcRD7u** [comment]
The environment Variable would have to be implemented by the developers, which would be amazing, as I currently can't receive email notifications, but I guess it's a wider "problem".
In a perfect world, everything would provide good enough encryption that you won't have to set security levels down.

**Comment by beavis6511** [comment]
Hello,
I also have this error with a SMTP server for notifications.
I'm not using SSL, my SMTP server runs on port 25.

**Comment by chakflying** [comment]
We could support it as demonstrated in [this](https://stackoverflow.com/a/60367796/17569333) answer, but it would require users to build their own container locally. See if you guys are comfortable with this.
