### ISSUE TITLE
Add suport for basic application/x-www-form-urlencoded POST requests

### ISSUE THREAD

**Issue by key-str0ke** [louislam/uptime-kuma#1332]
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

Other

### 🔖 Feature description

The current POST request feature, only allows for the body to contain { json data }.  Would be super helpful to have the option to POST key values as 'application/x-www-form-urlencoded'.

### ✔️ Solution

Example of output I want to send via the POST request.

`name=test&email=test%40test.com&attention=Technical&message=test`

Rather than the json output that it currently sends via the POST request.

`{"name":"test","email":"test@test.com","attention":"Technical","message":"test"}`

**Comment by thblckjkr** [comment]
I just checked my recently installed uptime-kuma instance (v1.11.4) and it appears to have this feature already.

<img width="933" alt="Screen Shot 2022-02-25 at 11 32 19" src="https://user-images.githubusercontent.com/16421524/155768920-1db97b8a-ef93-482d-aacf-48af3a62ea6e.png">

**Comment by key-str0ke** [comment]
The current post feature only posts via json.  { }

**Comment by thblckjkr** [comment]
Yup! I was editing my comment to say that i'm sorry, I think i didn't understood the question at first.

On the bright side, I think the change isn't too difficult, and I will try to create a Merge Request this weekend to see if I can add the functionality.

**Comment by key-str0ke** [comment]
You rock Teo!!!  Appreciate your time b.

**Comment by foliovision** [comment]
I was going to request the same feature, but then I found this issues and also two more which are related:

* https://github.com/louislam/uptime-kuma/issues/1351
* https://github.com/louislam/uptime-kuma/issues/1679

We need to do basic application/x-www-form-urlencoded POST request to be able to log into WordPress. That way we will be able to check some basic membership-only pages using a low-privileged users.

I tried to use the Header fields to change the type of the POST data:

```
{
    "Content-Type": "application/x-www-form-urlencoded"
}
```

But then it simply sent the whole POST JSON as text and did not set the individual keys.

Seems like this only needs a way of setting the POST type. So I hope this won't be hard to improve.

Thanks,
Martin

**Comment by spradeep** [comment]
> It feels like it's thinking too much. Just send the body. Exactly as it's entered. If we need to send JSON, we'll put JSON in the body. I need to sometimes send SOAP, sometimes send form data, sometimes send arbitrary rubbish. I just want to paste the body in and have it be sent. And I can set whatever headers I need. The monitor software should be completely agnostic to the content.

Right, is this possible
