### ISSUE TITLE
Outbout proxy configuration

### ISSUE THREAD

**Issue by beavis6511** [louislam/uptime-kuma#1336]
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

New Notification

### 🔖 Feature description

Uptime KUMA is installed into a network. 
It's OK to monitor servers (https) in the network but it's not working for servers in another network.
To join this network, I need to set an outbout proxy.
For instance, with a curl command, I need to use the option -x <myproxy>:<port>.

### ✔️ Solution

Into the screen "New monitor", for https, please add new fields:

- proxy URL
- proxt port
- proxy user (optional)
- proxy password (optioanal)

**Comment by suvl** [comment]
this is critical for us too.

**Comment by xorguy** [comment]
This will help a lot, it is very normal to have a proxy for Internet connection.

**Comment by chakflying** [comment]
Implemented in #840

**Comment by gaby** [comment]
@beavis6511 this issue is fixed now, can you close it? 

Fixed in #840

**Comment by beavis6511** [comment]
Close #840
