### ISSUE TITLE
Notifications during working hours

### ISSUE THREAD

**Issue by beavis6511** [louislam/uptime-kuma#1337]
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

Other

### 🔖 Feature description

I would like to receive notification only during working hours.
During nights, my services are down for backup. I don't whant to receive notifications.

### ✔️ Solution

In the Monitor screen, add 2 fields to configure a time window where notifications will not be sent.
Or the oposite, a time window where notifications will be sent.

**Comment by itsupportengineer** [comment]
I would prefer a more detailed notification rule structure, that could be built on an internal IFTTT.

**Comment by x86dev** [comment]
That's actually the most-needed feature I'm waiting for -- I also do run nightly backups which of course trigger alarms when a service goes down for the (planned) backup.

**Comment by soflane** [comment]
I would need that for my company too, for the same cause (backups)

**Comment by AlexandreGagner** [comment]
+1
Could be usefull to have "service time" per notification type.
eg: Only SMS on daytime, or another SMS number only in nightime.

**Comment by runchunzhang** [comment]
确实有这种需要,比如公司内网项目,通过ddns映射到外网,每天重启路由器时,公网ip会随之变更,这个时候就会收到预警
希望加入工作静默时间的模块,在指定时间段区间不去请求和预警

**Comment by csakaszamok** [comment]
+1

**Comment by louislam** [comment]
Maintenance Mode will be available in 1.19.0
