### ISSUE TITLE
I'm getting a following errors over the reverse proxy 

### ISSUE THREAD

**Issue by irfanarif-ia** [louislam/uptime-kuma#134]
**Console Error** over reverse proxy; Deployed on synology nas, No errors while on the local network..
```
[Error] WebSocket connection to 'wss://ut.***********/socket.io/?EIO=4&transport=websocket' failed: Unexpected response code: 400
[Error] Failed to connect to the backend. Socket.io connect_error: websocket error
	(anonymous function) (index.6297b778.js:1:52982)
	(anonymous function) (vendor.a54d5402.js:12:115757)
	emitReserved (vendor.a54d5402.js:12:140767)
	onerror (vendor.a54d5402.js:12:142782)
	onerror
	(anonymous function) (vendor.a54d5402.js:12:115757)
	emitReserved (vendor.a54d5402.js:12:140767)
	(anonymous function) (vendor.a54d5402.js:12:148245)
	(anonymous function) (vendor.a54d5402.js:12:115757)
	onError (vendor.a54d5402.js:12:134523)
	onError
	(anonymous function) (vendor.a54d5402.js:12:115757)
	onError (vendor.a54d5402.js:12:116239)
[Error] TypeError: undefined is not an object (evaluating 'loader.style.display = "none"')
	(anonymous function) (script.js:310)
	(anonymous function) (script.js:20)
```

Thanks in Advance

**Comment by louislam** [comment]
If this is nginx,you can read this https://github.com/louislam/uptime-kuma/issues/14#issuecomment-878150549.

**Comment by irfanarif-ia** [comment]
Thanks @louislam that fixed it I'm posting a link below if anyone else can find useful

[Synology Builtin Reverse Proxy Solution](https://mlohr.com/websockets-for-synology-dsm/)

**Comment by louislam** [comment]
> Thanks @louislam that fixed it I'm posting a link below if anyone else can find useful
> 
> [Synology Builtin Reverse Proxy Solution](https://mlohr.com/websockets-for-synology-dsm/)

Nice, I added your link to wiki. https://github.com/louislam/uptime-kuma/wiki/Reverse-Proxy
