### ISSUE TITLE
RTL language translation

### ISSUE THREAD

**Issue by yasharne** [louislam/uptime-kuma#1341]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

Hi
I would like to translate this platform to farsi (persian), but our language is RTL and it may encounter problems if it is displayed on a LTR platform, is there any way to support RTL as well?

### 🐻 Uptime-Kuma Version

any

### 💻 Operating System and Arch

any

### 🌐 Browser

any

### 🐋 Docker Version

any

### 🟩 NodeJS Version

any

**Comment by louislam** [comment]
I believe that @cmandesign had implemented it. Feel free to add new translation.

https://github.com/louislam/uptime-kuma/blob/master/src/languages/fa.js

**Comment by cmandesign** [comment]
@yasharne  RTL and Farsi language has been implemented previously, feel free to enhance it.
