### ISSUE TITLE
Is is possible to have no subpath for status page?

### ISSUE THREAD

**Issue by realEthanZou** [louislam/uptime-kuma#1346]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

I have uptime-kuma on status.my.domain and expect people to use the status page. It's imho a bit strange to have status.my.domain/status as the status page. Is it possible to have the status page at root, i.e. status.my.domain/ instead?

I use Nginx to reverse proxy btw.

### 🐻 Uptime-Kuma Version

1.12.1

### 💻 Operating System and Arch

Ubuntu 20.04 amd64

### 🌐 Browser

Chrome

**Comment by hectorskypl** [comment]
I agree with @Grucqq, it should be a option to choose between these paths.
