### ISSUE TITLE
Werid problem or just me? 

### ISSUE THREAD

**Issue by puregreen59** [louislam/uptime-kuma#135]
Anyone else having issues coming back to uptime kuma after a few hours.

I just woke up after a long sleep, loaded her up and had to wait almost a whole minute for the page to load and it did it in stages. 

The first 30 seconds the screen bllank with just uptime kuma and the logo, after about 30 seconds they all came up "unknown" 

After a while longer came up as all green like it went oh wait yeah of course here you go I've got that data for you actually  no problem mate! Coming right up!!! 😂😂

**Comment by louislam** [comment]
My guess is your cpu or harddisk are busy. Please check the usage if you see this again.

**Comment by puregreen59** [comment]
Hmm good call! Will keep an eye out and report back
