### ISSUE TITLE
Monitor stucks at PENDING

### ISSUE THREAD

**Issue by karelkryda** [louislam/uptime-kuma#1355]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### Description

Today I had an outage on two services that I monitor. 
Both services were stuck in the PENDING state and did not go to the DOWN state. 
Truth be told, both services are of the PUSH type. Unfortunately (thankfully) I didn't have an outage on another type of monitor, so I can't say if it's just PUSH. 

![Screenshot_20220304-223754_Chrome](https://user-images.githubusercontent.com/59953812/156847496-628f5a29-c281-480c-bbcb-f9f93dfc62d2.jpg)
![Screenshot_20220304-223738_Chrome](https://user-images.githubusercontent.com/59953812/156847499-1c51919e-355f-4e6b-b002-0c405e279aaf.jpg)

### 👟 Reproduction steps

- Create a push monitor 
- Visit URL to make push online
- Leave the push without activity 

### 👀 Expected behavior

The monitor should go down after 3 failed attempts 

### 😓 Actual Behavior

Monitor remains in pending state 

### 🐻 Uptime-Kuma Version

1.12.1

### 💻 Operating System and Arch

Debian 11

### 🌐 Browser

Latest Google Chrome

### 🐋 Docker Version

20.10.12

**Comment by TimothyGillespie** [comment]
This ticket is closed but related. I have the same issue.

https://github.com/louislam/uptime-kuma/issues/922

**Comment by karelkryda** [comment]
@TimothyGillespie I'm not sure if this is exactly the same issue, but ok.

**Comment by DPerkunas** [comment]
I don't consider this related to Timothy's. I have same issue. Fresh install. Status shows pending for the monitor, rather than up or down. Nothing to do with notifications.

**Comment by chakflying** [comment]
I can confidently say this was fixed with #1627 and #1428.

Back then, the push code looks like this:
```js
                } else if (this.type === "push") {      // Type: Push
                    const time = R.isoDateTime(dayjs.utc().subtract(this.interval, "second"));

                    let heartbeatCount = await R.count("heartbeat", " monitor_id = ? AND time > ? ", [
                        this.id,
                        time
                    ]);

                    debug("heartbeatCount" + heartbeatCount + " " + time);

                    if (heartbeatCount <= 0) {
                        // Fix #922, since previous heartbeat could be inserted by api, it should get from database
                        previousBeat = await Monitor.getPreviousHeartbeat(this.id);

                        throw new Error("No heartbeat in the time window");
                    } else {
                        // No need to insert successful heartbeat for push type, so end here
                        retries = 0;
                        this.heartbeatInterval = setTimeout(beat, beatInterval * 1000);
                        return;
                    }

```

`heartbeatCount` only looks for heartbeats since the last regular interval, and doesn't consider retries. The result is that it counted the last `PENDING` beat, goes to the else branch and `retries` keep getting reset to `0`.

**Comment by CommanderStorm** [comment]
@chakflying you are missing a call to action in your descriptions:

@karelkryda (only you or Louis can close issues 😉)
I believe this issue has been resolved and you can safely close this issue.
The fix for this issue is available after `1.16.1`

**Comment by chakflying** [comment]
Alright, I will try to include that and copy your template if you don't mind ;)

**Comment by karelkryda** [comment]
You're probably right. I'm not aware of having dealt with anything like this recently. I'm closing this issue.

**Comment by siimots** [comment]
In latest version (1.23.3) also many of my services were down but Uptime Kuma stayed "Pending" state for 12 hours and did not send out alerts.

Maybe send alerts also out if "Pending" is more than 60 minutes?
