### ISSUE TITLE
Code injection ( header / bottom )

### ISSUE THREAD

**Issue by EVOTk** [louislam/uptime-kuma#1356]
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

UI Feature

### 🔖 Feature description

Hello,
Code injection via Dashboard.

### ✔️ Solution

Have a menu dedicated to this in the dashboard

### 📝 Additional Context

For collect statistics of my status page.
 I would like to be able to include from the administration webui a tracking code ( header/bottom code injection )

**Comment by thetayloredman** [comment]
"code injection" makes this sound like a security issue, which should be reported to uptime@kuma.pet.

This doesn't seem like a security issue, so would you consider naming the issue "webui custom javascript" or something similar?

**Comment by EVOTk** [comment]
Hello,
sorry, but my English is not good.
I took this title, because this function exists under Ghost, with this name.

![2022-03-05 22_50_42-Window](https://user-images.githubusercontent.com/45015615/156901028-6657b230-f2f8-4e03-9747-7d80450ec7f8.png)

![2022-03-05 22_51_41-Window](https://user-images.githubusercontent.com/45015615/156901039-d007e344-6e18-4767-b8d1-ea07034f2adf.png)

**Comment by ririko5834** [comment]
Good idea to add way to include custom code in header

**Comment by thomasrosen** [comment]
I search for this right now :D
As there is already style injection, general html injection should be easy.

**Comment by CommanderStorm** [comment]
@EVOTk 
We are consolidating duplicate issues a bit to make issue management eazier.
I think, we should track this issue in https://github.com/louislam/uptime-kuma/issues/2818 as there is no functional difference (maybe just small naming differences, but nothing that would require a different issue imo) and said issue is a bit clearer ^^
=> I am going to close this as a duplicate (despite being the older issue)
