### ISSUE TITLE
Uptime-kuma on OpenWRT ?

### ISSUE THREAD

**Issue by shodanx2** [louislam/uptime-kuma#1357]
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

Other

### 🔖 Feature description

Add uptime-kuma to openwrt 

See the following guide on how to add packages to the openwrt repository

https://openwrt.org/docs/guide-developer/packages

I think uptime-kuma would be a great addition to openwrt, what better place for uptime monitoring than your router ?

### ✔️ Solution

Add the package, integrate UI to the openwrt web interface called LuCi

More resources

https://github.com/openwrt/luci/wiki/

https://openwrt.org/docs/techref/luci

**Comment by laleeroy** [comment]
Would love to see it!

**Comment by CommanderStorm** [comment]
I don't see us having the resources to maintain this
=> Closing as not planned.

If someone wants to maintain this packaging, we can add this under third party section in the wiki

**Comment by cgonIT** [comment]
Would be fine to have something like Kuma Uptime or similar that helps you monitor things. As example, I have a server connected through an access point, and some tools running on that server. If something is not working in the access Point, I would be notified by Kuma if it was installed in the main router.

So Kuma or another alternative would be "nice to have".
