### ISSUE TITLE
Empty Dashboard and Settings pages?

### ISSUE THREAD

**Issue by jonathanlaniado** [louislam/uptime-kuma#136]
After deploying with Docker, I used a reverse proxy to access Uptime Kuma. Seeing empty Dashboard and Settings pages. I can switch between them, but nothing loads.

<img width="1792" alt="CleanShot 2021-07-31 at 11 34 41@2x" src="https://user-images.githubusercontent.com/8929491/127744984-ab3879bf-9dcc-4e41-873c-d906457f7005.png">

**Comment by louislam** [comment]
Please read this: https://github.com/louislam/uptime-kuma/wiki/Reverse-Proxy

**Comment by jonathanlaniado** [comment]
Ah, perfect. For NPM users, enabling Websockets Support worked for me.
