### ISSUE TITLE
Update to 1.12.1

### ISSUE THREAD

**Issue by afuerbass** [louislam/uptime-kuma#1363]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

After updating to version 1.12.1 according to https://github.com/louislam/uptime-kuma/wiki/%F0%9F%86%99-How-to-Update with docker running on Ubuntu 20.04.3 all monitors added after a certain date have vanished. Can those be restored somehow? The library ./uptime-kuma has been copied to a different location before upgrading. 

### 🐻 Uptime-Kuma Version

1.12.1

### 💻 Operating System and Arch

Ubuntu 20.04.3

### 🌐 Browser

Version 98.0.4758.102 (Official Build) (64-bit)

### 🐋 Docker Version

Docker version 20.10.12, build e91ed57

**Comment by chakflying** [comment]
Which version did you upgrade from?
