### ISSUE TITLE
(Unwanted) Notifications "Certificate will expire in xx days"

### ISSUE THREAD

**Issue by rezzorix** [louislam/uptime-kuma#1364]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

It seems that for HTTP(S) monitors a notification is triggered whenever a certificate expires in 21 or 14 or 7  days and each day if expiry is in less than 4 days.

I am aware of the option to "Ignore TLS/SSL error for HTTPS websites" but an "expiry notice" is not an "error".

Is there any option to change this behaviour or toggle it on/off?

### 🐻 Uptime-Kuma Version

1.12.1 

### 💻 Operating System and Arch

Ubuntu 20.04

### 🌐 Browser

Chrome / FF / Edge

### 🐋 Docker Version

20.10.12

**Comment by louislam** [comment]
I am planning to add a checkbox for this.
