### ISSUE TITLE
Can you have repeated notifications?

### ISSUE THREAD

**Issue by heffneil** [louislam/uptime-kuma#1365]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

Is there a way to set up a repeated notification if / when a service or monitor is down?

### 🐻 Uptime-Kuma Version

1.12.1

### 💻 Operating System and Arch

Ubuntu 20.1

### 🌐 Browser

Chrome

**Comment by koen20** [comment]
I don't think this is possible currently. This is a duplicate of #233
