### ISSUE TITLE
Problem with TCP

### ISSUE THREAD

**Issue by KasaiKonoru** [louislam/uptime-kuma#1368]
![grafik](https://user-images.githubusercontent.com/45830738/158017366-06a8ec0b-feab-4410-b247-131a825e82b4.png)
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

I want to check the port 3033, because that a node express service.

But it doesnt work because :c

I use Apache2 and its listen to 80/443.

Error: "Request Timeout" or "connect ECONNREFUSED"

### 🐻 Uptime-Kuma Version

latest

### 💻 Operating System and Arch

Debian

### 🌐 Browser

Firefox

### 🟩 NodeJS Version

v16.14.0

**Comment by camnoalive** [comment]
Im having this problem also.
