### ISSUE TITLE
Domain name expiration

### ISSUE THREAD

**Issue by guanhuimeng** [louislam/uptime-kuma#1369]
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

New Monitor

### 🔖 Feature description

The panel can display the domain name expiration days and push warnings

### ✔️ Solution

Maybe we can integrate the detection function of whois

### ❓ Alternatives

I've used this ： https://github.com/caarlos0/domain_exporter ，But many domain names cannot be resolved

**Comment by pelligrag** [comment]
it would be great!
