### ISSUE TITLE
How I can create a new admin account?

### ISSUE THREAD

**Issue by KasaiKonoru** [louislam/uptime-kuma#1370]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

How I can renew the admin account or add a new account?

### 🐻 Uptime-Kuma Version

latest

### 💻 Operating System and Arch

Ububto 20.40

### 🌐 Browser

Firefox

**Comment by koen20** [comment]
It is currently not possible to add an account.
Multiple users has already been requested in issue #128 #1039 #1255
