### ISSUE TITLE
Login Name

### ISSUE THREAD

**Issue by skull-fir** [louislam/uptime-kuma#1371]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

So I used this code to make an uptime website, and I named the service HyperHost, so I want to change the login page name from Uptime Kuma to HyperHost, but when you login, I don't mind it saying Uptime Kuma, I only want to change the login page, and I want to write Powered By Uptime Kuma

Is that possible?

### 🐻 Uptime-Kuma Version

Version: 1.11.3

### 💻 Operating System and Arch

MacOS Catalina

### 🌐 Browser

Google Chrome

**Comment by louislam** [comment]
Yes, Uptime Kuma is under MIT license. You can do anything, just make sure to keep my copyright info.

https://github.com/louislam/uptime-kuma/blob/master/LICENSE

**Comment by obrian96** [comment]
Do you Make These Changes before or after running the command npm run setup?
