### ISSUE TITLE
[Documentation] - How to manage TAGS ( delete / rename ) 

### ISSUE THREAD

**Issue by bengivre** [louislam/uptime-kuma#1372]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

Hello, 

Just wondering how I can edit/delete a tag after creation ?
I am not able to find any information on the documentation and could not figure it out in the dashboard/settings. 

Thanks .

### 🐻 Uptime-Kuma Version

1.12.1

### 💻 Operating System and Arch

Ubuntu 20.04.3 LTS

### 🌐 Browser

Version 99.0.4844.51 (Official Build) (x86_64)

### 🐋 Docker Version

N/A

### 🟩 NodeJS Version

14.19.0

**Comment by xtianpaiva** [comment]
+1

**Comment by tamahau30494** [comment]
Try to do the same.

**Comment by BBaoVanC** [comment]
Don't close this

**Comment by bengivre** [comment]
So we went 
From Version: 1.12.1
To: Version: 1.17.1

And there is still no way to manage the tags or even just DELETE a tag you don't want.
You make a typo on your TAG and your a done. Mazing

**Comment by bengivre** [comment]
Hey @louislam what is the issue with the pull-request waiting since May to be merged ?

**Comment by BBaoVanC** [comment]
> I wish I could just make a pull request for that , but i'm no expert

There's currently a draft #1690

**Comment by madpeteguy** [comment]
For me this one is most wanted feature.
Hope it will go live soon 🙏

**Comment by romeolazar** [comment]
I need this too. Please add it as soon as possible. TY

**Comment by UltimateByte** [comment]
We still can't edit or remove tags.
Now I'm stuck with tags of the same color that I can't change.
Valve, please fix. I mean, please, merge!

**Comment by WorkNinja** [comment]
I found a work around to editing the colors.  If you export the settings into the json file, open it up in Notepad++ and change the hex color code for the tag, or edit the name of the tag.  You can do a find/replace to change them faster.  You're also not limited to the color choices when creating the tag in the web ui as it will accept and use any hex color code you put in it.

After you have edited the json, you can then import it and make it overwrite the current settings.  The changes will be immediate.  Also, if you need to remove a tag, just delete all the json entries for that tag and it won't show up in the list on the web ui.  Just make sure you adhere to the json formatting when you delete the entries or you will get import errors.

**Comment by WaiserHai** [comment]
wait, why is this closed now ? is there a way to edit in the dashboard ?

**Comment by UltimateByte** [comment]
@WaiserHai
Look closer to the upper notification buddy, change has been added to the code, it's merged! #1690 

Thank you @louislam !
By the way, can we donate to support the hard work?

**Comment by louislam** [comment]
> @WaiserHai Look closer to the upper notification buddy, change has been added to the code, it's merged! #1690
> 
> Thank you @louislam ! By the way, can we donate to support the hard work?

This feature will be released along with 1.20.0.

Yes, of course, you could donate through OpenCollective or GitHub. You should find the links in this repo's home page.
