### ISSUE TITLE
Cannot run on linux/arm/v6?

### ISSUE THREAD

**Issue by petebocken** [louislam/uptime-kuma#1375]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

I can't seem to get it running on my Raspberry Pi Zero W. I get the below message.

```
$ docker volume create uptime-kuma
docker run -d --restart=always -p 3001:3001 -v uptime-kuma:/app/data --name uptime-kuma louislam/uptime-kuma:1
uptime-kuma
WARNING: The requested image's platform (linux/arm/v7) does not match the detected host platform (linux/arm/v6) and no specific platform was requested
1aade93579b7bc0bf20759fdbdccb411a28d0cbe98c91a0010d77d41f20fe5e8
```

### 🐻 Uptime-Kuma Version

1.12.1

### 💻 Operating System and Arch

Raspbian GNU/Linux 11 (bullseye)

### 🌐 Browser

Firefox 98.0

### 🐋 Docker Version

20.10.13

### 🟩 NodeJS Version

16.14.0

**Comment by petebocken** [comment]
After I install the container and check running containers, it shows it is constantly restarting:
```
$ docker container ls -a
CONTAINER ID   IMAGE                    COMMAND                  CREATED         STATUS                            PORTS     NAMES
1aade93579b7   louislam/uptime-kuma:1   "/usr/bin/dumb-init …"   4 minutes ago   Restarting (139) 16 seconds ago             uptime-kuma
```

**Comment by louislam** [comment]
The node.js base image does not provide armv6 image, so Uptime Kuma is not officially supported armv6 docker.

Please run it on your machine directly without Docker, or build your own docker image.

**Comment by petebocken** [comment]
> Please run it on your machine directly without Docker, or build your own docker image.

I tried the Non-Docker install at first and just tried it again. The install appears to complete fine and shows uptime-kuma is online. However, when I go to http://server-ip:3001, it doesn't load. I get "Unable to connect".

```
[PM2] Spawning PM2 daemon with pm2_home=/root/.pm2
[PM2] PM2 Successfully daemonized
[PM2] Starting /home/pi/uptime-kuma/server/server.js in fork_mode (1 instance)
[PM2] Done.
┌────┬────────────────────┬──────────┬──────┬───────────┬──────────┬──────────┐
│ id │ name               │ mode     │ ↺    │ status    │ cpu      │ memory   │
├────┼────────────────────┼──────────┼──────┼───────────┼──────────┼──────────┤
│ 0  │ uptime-kuma        │ fork     │ 0    │ online    │ 0%       │ 25.6mb   │
└────┴────────────────────┴──────────┴──────┴───────────┴──────────┴──────────┘
```

**Comment by louislam** [comment]
Ops, since SQLite is using a native library which also does not provide armv6.

So it is very hard to use Uptime Kuma on armv6 platform right now, unless you know how to compile [node-sqlite3](https://github.com/louislam/node-sqlite3) to armv6.

**Comment by petebocken** [comment]
@louislam ok thanks.

**Comment by danielrnrz** [comment]
Hi, I just got it running on docker on armv6 (Raspberry pi 1 model B) based on the pastebin (thanks to @olli991). There is an image build for node 18.9.1 based on alpine 3.15 and running on armv6.
I had to use also WSL to compile the frontend.
Here is what I did : 

# On WSL (Debian) :

# Install NVM to get the correct nodejs version (18.9.1):
```
curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.7/install.sh | bash

export NVM_DIR="$HOME/.nvm"
source "$NVM_DIR/nvm.sh
```

# Install and use NodeJS :

```
nvm install 18.9.1
nvm use 18.9.1
```

# Then download and build the frontend :

```
git clone https://github.com/louislam/uptime-kuma.git
cd uptime-kuma
npm install
npm run build
```


Take the dist/ folder and copy it in the same folder that contains your Dockerfile and here is the Dockerfile :

```

FROM node:18.9.1-alpine3.15

#Install dependencies
RUN apk add --no-cache \
    python3 \
    make \
    g++ \
    git \
    bash \
    curl

#Clone Uptime Kuma
WORKDIR /opt/kuma
RUN git clone https://github.com/louislam/uptime-kuma.git . 

#Install
RUN NODE_OPTIONS="--max-old-space-size=256" \
    npm install --omit=dev --fetch-timeout=600000 --fetch-retries=5

#Remove unusable version and build the correctone
RUN rm -rf node_modules/@louislam/sqlite3 && \
    npm pkg delete dependencies.@louislam/sqlite3 && \
    npm install sqlite3 --build-from-source --omit=dev

#Fix the import 
RUN sed -i 's/@louislam\/sqlite3/sqlite3/' ./server/database.js

COPY dist/ /opt/kuma/dist/

EXPOSE 3001

#Run
CMD ["node", "server/server.js"]
```


The build for the Dockerfile is quite slow it took almost 5 hours on my Pi. 


Hope it helps.

**Comment by louislam** [comment]
> The build for the Dockerfile is quite slow it took almost 5 hours on my Pi.

5 hours is crazy.

I guess it could be faster using `docker buildx` on your PC.

But is it really usable? I own Pi 2B before, it was so slow.

**Comment by danielrnrz** [comment]
Hi, yes it works very well , I have 9 services to monitor every 5 minutes and the interface works pretty smoothly.

**Comment by louislam** [comment]
@danielrnrz Btw, I think you can push your armv6 image to Docker Hub.

And then, feel free to add it into the "Unofficial" section: https://github.com/louislam/uptime-kuma-wiki/blob/master/%F0%9F%94%A7-How-to-Install.md
