### ISSUE TITLE
Is mongo db / redis supported?

### ISSUE THREAD

**Issue by ghost** [louislam/uptime-kuma#1376]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

just read title

### 🐻 Uptime-Kuma Version

1.10.0

### 💻 Operating System and Arch

irrelevant for my question

### 🌐 Browser

irrelevant for my question

### 🐋 Docker Version

irrelevant for my question

### 🟩 NodeJS Version

irrelevant for my question

**Comment by koen20** [comment]
Only SQLite is supported currently. An issue has already been created for this #1361 .
