### ISSUE TITLE
How can I change the  message template  of  DingDing 

### ISSUE THREAD

**Issue by hlf2016** [louislam/uptime-kuma#1377]
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

Other

### 🔖 Feature description

How can I change the  message template  of  DingDing , such as @ someone by DingDing bot or  change the massage type

### ✔️ Solution

How can I change the  message template  of  DingDing , such as @ someone by DingDing bot or  change the massage type

**Comment by koen20** [comment]
Duplicate of #975 and #646

**Comment by CommanderStorm** [comment]
User notification was merged in https://github.com/louislam/uptime-kuma/pull/4718
The rest (templating) a duplicate of https://github.com/louislam/uptime-kuma/issues/646

this issue is resolved if I subtract the duplicate
=> closing as resolved
