### ISSUE TITLE
Find all 'Uptime Kuma' and Replace all 'Your Company name' and leave only Powered by Uptime kuma 

### ISSUE THREAD

**Issue by obrian96** [louislam/uptime-kuma#1378]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

is it possible to rename the project name on the dashboard and status page from 'Uptime Kuma' to a custom name i.e 'Your Company Name'?
and also the logo's 

like find all and replace all from 
'Uptime Kuma' to 'Your Company Name
 

### 🐻 Uptime-Kuma Version

latest

### 💻 Operating System and Arch

windows 10

### 🌐 Browser

chrome

### 🟩 NodeJS Version

lastest

**Comment by louislam** [comment]
Similar to https://github.com/louislam/uptime-kuma/issues/1371#issuecomment-1066080465

> Yes, Uptime Kuma is under MIT license. You can do anything, just make sure to keep my copyright info.
> 
> More info: GitHub explained what is MIT License in the header.
> https://github.com/louislam/uptime-kuma/blob/master/LICENSE
