### ISSUE TITLE
Heartbeat vs Heartbeat Retry interval?

### ISSUE THREAD

**Issue by binarydad** [louislam/uptime-kuma#1379]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

What is the difference between the two? Is Heartbeat Interval the interval of checking the health status and is Heartbeat Retry Interval the interval for when the monitor is down (and hence checking for when it comes back online)? Can someone please clarify? Thank you.

### 🐻 Uptime-Kuma Version

1.12.1

### 💻 Operating System and Arch

Ubuntu 20

### 🌐 Browser

Any

### 🐋 Docker Version

20

**Comment by louislam** [comment]
Yes, you are right.
