### ISSUE TITLE
Discord notification

### ISSUE THREAD

**Issue by keitje** [louislam/uptime-kuma#1381]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

I've configured notifications of my monitoring to a discord webhook. But I wont receive the service down or up text in Discord. Only the text that you can configure in 'Prefix Custom Message'
![service_down](https://user-images.githubusercontent.com/45143839/158830060-c2076c6c-5853-44e8-ab5b-26efe4bafb22.JPG)
![empty_servicename_discord](https://user-images.githubusercontent.com/45143839/158830163-4c7e671b-9332-47ee-a670-0d15f6b7871a.JPG)

### 🐻 Uptime-Kuma Version

1.12.1

### 💻 Operating System and Arch

Ubuntu server 20.04.4

### 🌐 Browser

Chrome 99.0.4844.74

### 🐋 Docker Version

Docker version 20.10.7, build 20.10.7-0ubuntu5~20.04.2

**Comment by louislam** [comment]
It is working in my side.

You could try to create a new monitor and take it down by using invalid hostname.

![image](https://user-images.githubusercontent.com/1336778/158936313-684843e0-3e1d-4b83-8cea-bcbf2465607d.png)

**Comment by luwol03** [comment]
Can you check if your embed contains hostnames that are not resolveable by discord? I already experienced that on another software trying to connect to discord webhooks. (See this [issue](https://github.com/go-gitea/gitea/issues/11124) for context)

**Comment by keitje** [comment]
> You didn't get it. Discord embeds are not valid and won't be send if they contain Hostnamen in (icon) urls that are not resolvable by discords servers. The content of the message is still send as I know. So try to adjust your setup temporarily to IP addresses for educational purposes.

I've changed my DNS name to an local ipadres of one of my systems. Again the text does not show in the Discord channel. The integration works, its there... but you don't get to see the text in Discord.

**Comment by luwol03** [comment]
If you want to investigate and solve that issue, can you somehow check the response and request body by modifying the code if possible?

**Comment by cmulk** [comment]
Just wanted to make a note here in case someone with the same problem finds this thread like I did.
In Discord app settings you have to enable `Text & Media > Show embeds and preview website links pasted into chat`
