### ISSUE TITLE
WS Issues

### ISSUE THREAD

**Issue by donzee529** [louislam/uptime-kuma#1382]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

I setup Uptime Kuma with the .sh installer script and chose the local version. When I go to the site, it says Could not connect to socket server. So I checked browser console and it says 

<img width="982" alt="Screen Shot 2022-03-17 at 10 17 30 PM" src="https://user-images.githubusercontent.com/43678009/158924973-308ba759-5546-41a4-bd0e-734015174686.png">

What do I do?

My Apache Config:
```
<VirtualHost IP REDACTED:80>
        ServerName status.pyrohost.cloud
        ServerAdmin admin@pyrohost.cloud
        ServerAlias www.status.pyrohost.cloud
        Redirect permanent / https://status.pyrohost.cloud/

ProxyPass / http://localhost:3001/
  RewriteEngine on
  RewriteCond %{HTTP:Upgrade} websocket [NC]
  RewriteCond %{HTTP:Connection} upgrade [NC]
  RewriteRule ^/?(.*) "ws://localhost:3001/$1" [P,L]
</VirtualHost>

<VirtualHost IP REDACTED:443>
        ServerName status.pyrohost.cloud
        ServerAdmin admin@pyrohost.cloud
        ServerAlias www.status.pyrohost.cloud
        SSLEngine on
        SSLCertificateFile /etc/apache2/sites-ssl/pyrohost.cloud.crt
        SSLCertificateKeyFile /etc/apache2/sites-ssl/pyrohost.cloud.key

Protocols h2 http/1.1

  ProxyPass / http://localhost:3001/
  RewriteEngine on
  RewriteCond %{HTTP:Upgrade} websocket [NC]
  RewriteCond %{HTTP:Connection} upgrade [NC]
  RewriteRule ^/?(.*) "ws://localhost:3001/$1" [P,L]
</VirtualHost>
```
### 🐻 Uptime-Kuma Version

1.12.1

### 💻 Operating System and Arch

Ubuntu 20.04

### 🌐 Browser

Safari

### 🟩 NodeJS Version

14.19.0

**Comment by louislam** [comment]
Please read wiki:
https://github.com/louislam/uptime-kuma/wiki/Reverse-Proxy

**Comment by blip2** [comment]
suggest `sudo a2enmod proxy_wstunnel` is added to the wiki page under the apache section. I also had a similar problem.
