### ISSUE TITLE
Http auth broken after update

### ISSUE THREAD

**Issue by gregfr** [louislam/uptime-kuma#1383]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### Description

Greetings

I've about 20 monitors which were working fine ; among them 2 are http check with http auth.

I just updated Kuma Docker this morning and the 2 http auth are reported as "Request failed with status code 401" (the sites are working fine, ssl certs are ok).

### 👟 Reproduction steps

Update Kuma while having http auth checks previously configured.

### 👀 Expected behavior

Same behavior as previous version: check ok

### 😓 Actual Behavior

Request failed with status code 401

### 🐻 Uptime-Kuma Version

1.12.1

### 💻 Operating System and Arch

Debian 10.11

### 🌐 Browser

Google Chrome  98.0.4758.80

### 🐋 Docker Version

Docker version 20.10.12, build e91ed57

### 🟩 NodeJS Version

n/a

### 📝 Relevant log output

```shell
Monitor #15 'My website': Failing: Request failed with status code 401 | Interval: 60 seconds | Type: http
```

**Comment by louislam** [comment]
Basic Auth? It is working in my side, could you double check the username and password both are correct.

![image](https://user-images.githubusercontent.com/1336778/158985120-989bb7db-8307-4ce6-afe1-906bbf30f342.png)

**Comment by gregfr** [comment]
Yes I checked before posting ; nothing changed apart the Kuma upgrade (neither on the monitored server or the configuration in Kuma)... is there a debug mode I can check with?

**Comment by ivanbratovic** [comment]
Status code 401 suggests that the credentials were sent correctly, but are not valid for some reason. Are you sure the site is using Basic auth, and not some other form like Digest auth? Also, is there some way for you to check that Uptime Kuma has not been IP blacklisted/banned from sending requests?

**Comment by gregfr** [comment]
Thanks for your answer.
Credentials were valid before the update ; nothing changed on the monitored server, but I set the credentials again in Kuma to be sure.
I see no reason why there could be a blacklist issue (the monitored server is a very old application with nothing of the sort).

Maybe I could try to dump the actual request received by the monitored server, I'll try.

**Comment by RaphMad** [comment]
I get the same problem - with the current version, HTTP basic auth results in 401s on all my pages that use basic auth, re-checked credentials 3x.

**Comment by Computroniks** [comment]
> I just updated Kuma Docker this morning and the 2 http auth are reported as "Request failed with status code 401" (the sites are working fine, ssl certs are ok).

Can you use something like tcpdump to capture the http request and response and post the packet output here (Make sure to replace any sensitive information with something like `REDACTED`).

**Comment by CommanderStorm** [comment]
Closing as unreproducible and no comment from the author
