### ISSUE TITLE
Global maintenance window where uptime is not monitored?

### ISSUE THREAD

**Issue by johanneskastl** [louislam/uptime-kuma#1384]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

Sorry if this was raised before, I might be lacking the right key words.

Is it possible to set a daily/weekly window where machines are being rebooted and where downtime will be ignored?

I can set the retries option, so it only fails after some consecutive errors, but I need to configure that on every monitor. And it is not just in that specific time window, but also during normal operations, where I might get alerts quicker.

### 🐻 Uptime-Kuma Version

v1.11.1

### 💻 Operating System and Arch

not relevant, as Kubernetes only

### 🌐 Browser

Firefox

**Comment by koen20** [comment]
It is currently not possible to pause monitoring for a scheduled time. This is a duplicate of #191 .
Someone opened a pull request #1213 which adds this feature.

**Comment by johanneskastl** [comment]
Thanks for the pointers, indeed I had the wrong key words for my search... :-)
