### ISSUE TITLE
Every time I commit changes all my data gets lost.

### ISSUE THREAD

**Issue by UPDOWNUP-64BIT** [louislam/uptime-kuma#1391]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

When i made changes to code like the notifications everything gets reset and i have to create the admin account again i was wondering if there was a way to stop.  

### 🐻 Uptime-Kuma Version

1.12.1

### 💻 Operating System and Arch

Ubuntu 20.04

### 🌐 Browser

OperaGX

### 🐋 Docker Version

20.10.9

### 🟩 NodeJS Version

16.14.2

**Comment by proffalken** [comment]
Have you added a docker volume on which to store the database? If not then every time you restart the container it will start with a fresh database.

Make sure that you are running docker [as detailed in the readme](https://github.com/louislam/uptime-kuma#-docker) and that you have `-v uptime-kuma:/app/data` or similar in your docker launch configuration

**Comment by rezzorix** [comment]
Just glancing at it I am quite certain that the variables you use in the yml file are the culprit...

`- ${FILE1}:/app/data`
Why file? Should be a directory.
