### ISSUE TITLE
Support for multiple users

### ISSUE THREAD

**Issue by CoolCoderSJ** [louislam/uptime-kuma#1392]
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

Other

### 🔖 Feature description

Would it be possible to add support for multiple users being able to have an account on the same server?

### ✔️ Solution

Multiple users can use the same website

**Comment by koen20** [comment]
Duplicate of #128 #1039 #1255

**Comment by CoolCoderSJ** [comment]
Sorry, didn't find those

**Comment by dkay-zaxxx** [comment]
I have recently found this amazing piece of software, it would be really nice if there was support for multiple users as well as a permission based system, where you can have admin users :

Global Admin - Root power :)
Group Admin - Ability to edit devices and status pages in a specific group
Status Admin - Only has access to updating status pages, can also be group based
Read Only - Has ability to ready only

What I think would be really great, is that the default landing page isn't a login page and someone would be able to browse all the status pages that you give access to be show on the default landing page. Then you could do use something like this https://example.com/admin/ to navigate to the administrator panel.

From a person that works in ISP field this is definitely something viable that we could us for network status, in a basic form of monitoring.

Thoughts?

**Comment by koen20** [comment]
@dkay-zaxxx It might be better if you add this to the existing issue for user management #128 rather than a closed issue.

It is currently possible to set the landing page to redirect to the default status page in the settings.
