### ISSUE TITLE
Scheduled Down Monitors

### ISSUE THREAD

**Issue by athornfam2** [louislam/uptime-kuma#1394]
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

UI Feature

### 🔖 Feature description

I have several platforms and servers that are not online 24/7/365 due to costs for that service and only run during hours of operation (8:00 AM to 5:00 PM). Of course, this tool is to notify in an outage but it would be nice to have scheduled monitoring so I don't get alarms at 10:00 PM constantly but having all the nice monitoring when needed.

### ✔️ Solution

Add a setting in each monitor to setup scheduled monitoring during the creation of the new monitor and after the monitor has been created. Checkbox to enable and time range to monitor during.

**Comment by koen20** [comment]
This is a duplicate of #191 
Someone opened a pull request https://github.com/louislam/uptime-kuma/pull/1213 which adds adds a maintenance planning system.

**Comment by athornfam2** [comment]
@koen20 Oh... I did not look back that far. I guess this can be closed out and I'll add input to that request.
