### ISSUE TITLE
Not starting?

### ISSUE THREAD

**Issue by ZIODIOZIO** [louislam/uptime-kuma#1398]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

Hello, i start the status page with pm2 start server/server.js --name uptime-kuma but it seems not running if i check listening port.
80 and 443 port opens NGNIX.

![image](https://user-images.githubusercontent.com/74601229/159289293-ea72a4e9-f13a-41a0-b362-1f52a89ebca4.png)

### 🐻 Uptime-Kuma Version

Last

### 💻 Operating System and Arch

Ubuntu 20

### 🌐 Browser

Chrome

### 🐋 Docker Version

/

### 🟩 NodeJS Version

/

**Comment by louislam** [comment]
Please start the server using this to see the log.
`node server/server.js`

**Comment by ZIODIOZIO** [comment]
> Please start the server using this to see the log. `node server/server.js`

![image](https://user-images.githubusercontent.com/74601229/159302047-b030236b-0a68-41c9-abfc-95d33696137b.png)

**Comment by ZIODIOZIO** [comment]
thank you but i am facing this now

![image](https://user-images.githubusercontent.com/74601229/159304058-d80e78da-6f01-46e1-b3e7-d1cbc671dfae.png)

**Comment by ZIODIOZIO** [comment]
> Your installation should be incomplete.
> 
> Try to run `npm run setup` again.
> 
> If it is still not working, I would suggest that you should try again with README's installation guide.

![image](https://user-images.githubusercontent.com/74601229/159308458-f234519c-5875-49ff-91f9-d7b4f4a826d0.png)


I have really a lot, really a lot of monitor. I took me a lot of configure all the keywords and notifications.
Is there any way to let it work?

**Comment by louislam** [comment]
I thought you were a new user.

Then first, you should backup /opt/uptime-kuma/data first.

Second, it looks like your hard disk is full.

You should check with `df -h`

**Comment by ZIODIOZIO** [comment]
What is using all the space? I mean Is this software generating many things?

**Comment by louislam** [comment]
If there are no other services in the same server. It could be pm2 logs.

Related issue: https://www.reddit.com/r/UptimeKuma/comments/t5fcux/disk_usage_is_crazy_high/

**Comment by ZIODIOZIO** [comment]
> If there are no other services in the same server. It could be pm2 logs.
> 
> Related issue: https://www.reddit.com/r/UptimeKuma/comments/t5fcux/disk_usage_is_crazy_high/

So I should run before “pm2 set pm2-logrotate:max_size 1G”? Also where are the log files located. Thank you in advice?

**Comment by ZIODIOZIO** [comment]
Hello? Anyone?

**Comment by ZIODIOZIO** [comment]
i was able to free space but i am not able to see the online webpage at port 80 or 443 
![image](https://user-images.githubusercontent.com/74601229/160165094-a1f4d0d0-9d16-4616-8f29-01a00b1181c1.png)

**Comment by chakflying** [comment]
If you are using nginx as reverse proxy, did you check that localhost:3001 actually works first?

**Comment by ZIODIOZIO** [comment]
I am still not able...
I would like to reinstall everything. What should i export in order to import after in the new installation?
