### ISSUE TITLE
Settings page doesn't load

### ISSUE THREAD

**Issue by 12nick12** [louislam/uptime-kuma#14]
Settings page doesn't load behind NGiNX reverse proxy.

**Comment by louislam** [comment]
I cannot reproduce your problem. It is working for me. I am using this nginx conf.

```
server  {
    server_name    test2.mydomain;
    location / {
        proxy_pass            http://localhost:3001;
        proxy_http_version    1.1;
        proxy_set_header      Upgrade $http_upgrade;
        proxy_set_header      Connection "upgrade";
        proxy_set_header      Host $host;
        proxy_read_timeout    124416000;
    }
}

```

![image](https://user-images.githubusercontent.com/1336778/125232058-72ccbe00-e30e-11eb-8b16-fc027af2165e.png)

**Comment by 0mni** [comment]
Can confirm, I am running with the following docker compose file, without any issues described, it's possible you have a reconfiguration on your nginx, or uptime kuma isn't actually listening on port 3001.

`version: '2.3'

services:

  nginx:
    container_name: nginx
    image: jwilder/nginx-proxy
    ports:
      - 0.0.0.0:80:80
      - 0.0.0.0:443:443
    labels:
      - "com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy"
    networks:
      - internet
    restart: always
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./statup/nginx/certs:/etc/nginx/certs:ro
      - ./statup/nginx/vhost:/etc/nginx/vhost.d
      - ./statup/nginx/html:/usr/share/nginx/html:ro
      - ./statup/nginx/dhparam:/etc/nginx/dhparam
    environment:
      DEFAULT_HOST: uptime.yourdomain.com

  letsencrypt:
    container_name: letsencrypt
    image: jrcs/letsencrypt-nginx-proxy-companion
    networks:
      - internet
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./statup/nginx/certs:/etc/nginx/certs
      - ./statup/nginx/vhost:/etc/nginx/vhost.d
      - ./statup/nginx/html:/usr/share/nginx/html
      - ./statup/nginx/dhparam:/etc/nginx/dhparam

  uptime-kuma:
    container_name: uptime-kuma
    image: louislam/uptime-kuma
    restart: always
    networks:
      - internet
    volumes:
      - ./uptime-kuma/app:/app/data
    environment:
      VIRTUAL_HOST: uptime.yourdomain.com
      VIRTUAL_PORT: 3001
      LETSENCRYPT_HOST: uptime.yourdomain.com
      LETSENCRYPT_EMAIL: your@email.com

networks:
  internet:
    driver: bridge`

**Comment by antoine2tt** [comment]
Hi

I have the same bug

Using simple docker compose and nginx proxy manager

**Comment by TheGuyDanish** [comment]
@antoine2tt Check your browser developer tools and look in the Javascript console. Are you seeing any websockets-related errors?

**Comment by antoine2tt** [comment]
@TheGuyDanish Yes i'm having a lot of 

And it keeps going (the same error)

![kuma](https://user-images.githubusercontent.com/979136/125270301-d0124080-e309-11eb-9ae0-5a9e35ed44d9.png)

**Comment by TheGuyDanish** [comment]
@antoine2tt Your nginx config is not passing through the websocket connection properly. See the nginx configuration in #3, specifically the proxy_set_header lines.

```
    proxy_pass           http://localhost:3001/;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection $connection_upgrade;
```

Without these, nginx doesn't successfuly pass through the websocket connection.

**Comment by antoine2tt** [comment]
@TheGuyDanish 

@TheGuyDanish It seems like that Nginx Proxy Manager is not happy with these settings. It breaks my proxy

**Comment by TheGuyDanish** [comment]
@antoine2tt I'm not that familiar with Nginx Proxy Manager, but it seems you need to set Websockets support in the Details tab on your proxy host, as well as HTTP/2 Support in the SSL tab. According to what I can find on Google.

**Comment by antoine2tt** [comment]
@TheGuyDanish 

Alright, i have upgraded Nginx Proxy Manager to the last version

Enable Websocket + HTTP/2, and it's working.

Thank you !!

**Comment by antoine2tt** [comment]
@TheGuyDanish 

Short story, i was in 2.9.1 of nginx proxy manager, here's a part of the 2.9.2 release : 

> Fix websockets not working for new/edited proxy hosts in v2.9.0/v2.9.1. After upgrading, just edit and save existing proxy hosts to apply the fix

That's why it was not working :p

**Comment by 12nick12** [comment]
I get the following error. I have verified America/New_York is the timezone on the system and the TZ variable. 

 Invalid time zone specified: Asia/Qostana

**Comment by TheGuyDanish** [comment]
What distribution are you running? Check if your /usr/share/zoneinfo directory is populated, and that you have /usr/share/zoneinfo/Asia/Qostanay. If you do not, you may need to install the tzdata package found in most distros.

**Comment by 12nick12** [comment]
Debian 10. The /usr/share/zoneinfo/Asia/Qostanay exists.

**Comment by louislam** [comment]
> I get the following error. I have verified America/New_York is the timezone on the system and the TZ variable.
> 
> Invalid time zone specified: Asia/Qostanay

Oh, I think I know the problem. I got the timezone list from here: https://stackoverflow.com/questions/38399465/how-to-get-list-of-all-timezones-in-javascript

However, I guess old version of Chrome browsers or other browsers maybe missing some timezones like Asia/Qostanay. So it throws error. 

Let's see how to fix it.

**Comment by TheGuyDanish** [comment]
Given that most (if not all) servers should have tzdata installed. You could recursively look for timezones in /usr/share/zoneinfo. That would give you all the zones the server supports and not cause any trouble with the browser.

**Comment by louislam** [comment]
> Given that most (if not all) servers should have tzdata installed. You could recursively look for timezones in /usr/share/zoneinfo. That would give you all the zones the server supports and not cause any trouble with the browser.

Because I handle the timezone in the frontend, so it is not related to the server.

**Comment by 12nick12** [comment]
Just verifying it's due to the browser (like you've already figured out). Using Firefox and the settings is working. Thank you.
