### ISSUE TITLE
Secure SMTP notification triggers SSL error

### ISSUE THREAD

**Issue by ctrlbrk42** [louislam/uptime-kuma#140]
**Describe the bug**
Error after setting up secure SMTP notification:

```
0|uptime-k | ] {
0|uptime-k |   library: 'SSL routines',
0|uptime-k |   function: 'ssl3_get_record',
0|uptime-k |   reason: 'wrong version number',
0|uptime-k |   code: 'ESOCKET',
0|uptime-k |   command: 'CONN'
0|uptime-k | }
0|uptime-k | [Error: 140492299540416:error:1408F10B:SSL routines:ssl3_get_record:wrong version number:../deps/openssl/openssl/ssl/record/ssl3_record.c:332:
0|uptime-k | ] {
0|uptime-k |   library: 'SSL routines',
0|uptime-k |   function: 'ssl3_get_record',
0|uptime-k |   reason: 'wrong version number',
0|uptime-k |   code: 'ESOCKET',
0|uptime-k |   command: 'CONN'
0|uptime-k | }
```

**To Reproduce**
1. Add new SMTP notification
2. Using port 587
3. Checked "secure" option
4. Click "test"

 - Uptime Kuma Version: 1.0.7
 - Using Docker?: No
 - OS: Debian 11 bullseye

```
11:19 PM [kuma]~ root # npm -v
7.20.3
11:19 PM [kuma]~ root # pm2 -v
5.1.0
11:19 PM [kuma]~ root # node -v
v16.6.0
```

![image](https://user-images.githubusercontent.com/1001097/127803706-410823ad-13f6-4300-b305-c39a3e276fcb.png)

**Comment by louislam** [comment]
According to Nodemailer' suggestion, you should  uncheck the "Secure" for 587 port
Related issue: https://github.com/nodemailer/nodemailer/issues/165

**Comment by ctrlbrk42** [comment]
Thanks @louislam, I can confirm that did the trick.  I do assume it's using TLS automatically w/o "secure" being checked, because my SMTP server requires it and the Test worked.
