### ISSUE TITLE
Error: Cannot find 'dist/index.html', did you install correctly?

### ISSUE THREAD

**Issue by NotKisshore** [louislam/uptime-kuma#1402]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

Error: Cannot find 'dist/index.html', did you install correctly?

### 🐻 Uptime-Kuma Version

1.12.1

### 💻 Operating System and Arch

Windows x64

### 🌐 Browser

brave Version 1.36.119 Chromium: 99.0.4844.83 (Official Build) (64-bit)

### 🟩 NodeJS Version

Node.js version: 16

**Comment by louislam** [comment]
Just realize the setup command is broken. If you are a new user, please delete everything and try to install again.

**Comment by tomihbk** [comment]
@louislam Which command should a new user use ?

**Comment by louislam** [comment]
Just follow https://github.com/louislam/uptime-kuma#-how-to-install

**Comment by tomihbk** [comment]
Thanks, works! I guess you can close this issue.

**Comment by MohitBansal321** [comment]
This error still exist 
`Error: Cannot find 'dist/index.html', did you install correctly?`

**Comment by louislam** [comment]
It is because you didn't follow the instructions.

**Comment by MohitBansal321** [comment]
I did the
npm install
node server/server.js

**Comment by chakflying** [comment]
You should be able to identify that error is caused by something with your local git repository. You should search and find out how to solve this problem first, instead of running random commands you think should work.

**Comment by o-i-i-o** [comment]
I'm having the same issue，just run 'pm2 stop 1' and 'pm2 start server/server.js --name uptime-kuma',node.js version 18.19.1 ,uptime version 1.23.13, ‘dist/index.html’ exists and correctly

**Comment by o-i-i-o** [comment]
> I'm having the same issue，just run 'pm2 stop 1' and 'pm2 start server/server.js --name uptime-kuma',node.js version 18.19.1 ,uptime version 1.23.13, ‘dist/index.html’ exists and correctly

I've solved it （machine translation）

**Comment by pjotrsavitski** [comment]
In case it will be useful to someone. In our case the issue was with how the hosting provider was handling things by default and setting the `cwd` (current working directory option) to a directory that was different from app home catalog. The solution was to use the pm2 configuration instead that has the corresponding setting present.

**Comment by baharalidurrani** [comment]
> I've solved it （machine translation），run 'sudo pm2 start server/server.js --name uptime-kuma'

This is not working either.
I'm using a freshly setup ubuntu server 24.04

**Comment by pjotrsavitski** [comment]
@baharalidurrani Run that from within the directory or check with pm2 describe  APP-ID. It was incorrect current working directory in my case and I've used the configuration file instead and gave that to pm2.
