### ISSUE TITLE
Dashboard not Loading  when Hosted on Azure App Services 

### ISSUE THREAD

**Issue by obrian96** [louislam/uptime-kuma#1403]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

I have hosted uptime Kuma on azure  app services but sadly the dashboard is throwing an error below 

"Cannot connect to the socket server. [Error: websocket error] Reconnecting..." and the console in the browser " Failed to connect to the backend. Socket.io connect_error: websocket error"

but the StatusPage is Working Fine 

### 🐻 Uptime-Kuma Version

latest

### 💻 Operating System and Arch

windows 10

### 🌐 Browser

Version 99.0.4844.82 

### 🟩 NodeJS Version

16

**Comment by louislam** [comment]
Usually due to the reverse proxy of WebSocket.

Explanation:
https://github.com/louislam/uptime-kuma/wiki/Reverse-Proxy

**Comment by sanderdam** [comment]
Websockets are an optional feature of Azure App Services. 
You should enable it in the configuration section of the Azure App Service.
