### ISSUE TITLE
Error: Websocker Error

### ISSUE THREAD

**Issue by SuperDexter23** [louislam/uptime-kuma#1407]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

Hi everyone

hi i've install Uptime Kuma and it works fine internally, but i configure Nginx Proxy Manager and if i try yo connect from domain name uptime.domainname.tld i receive this error:

![immagine](https://user-images.githubusercontent.com/81813145/159502603-fcd08fd0-106c-44e8-9895-eac310b61f0f.png)

### 🐻 Uptime-Kuma Version

1.12.1

### 💻 Operating System and Arch

5.13.19-3-pve

### 🌐 Browser

Firefox

### 🐋 Docker Version

Docker version 20.10.13, build a224086

**Comment by SuperDexter23** [comment]
Ok thankyou again

**Comment by Saibamen** [comment]
@SuperDexter23: Please close this issue
