### ISSUE TITLE
Can't access status page after setting the URL to `/status/`

### ISSUE THREAD

**Issue by ouuan** [louislam/uptime-kuma#1409]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 👟 Reproduction steps

1. Change the URL of the default status page from `/status/default` to `/status/`.
2. Try to access `/status/` but the page is empty.

### 👀 Expected behavior

One or some of these possible solutions:

1. Make the multi-status-page feature opt-in.
2. Support setting the URL to `/status/`, and only redirect to `/status/default` if there's no such status page with the URL `/status/`.
3. Prevent setting the URL to `/status/`.

### 😓 Actual Behavior

After setting the path of the default status page to empty, i.e. changing `/status/default` to `/status/`, I can't access the status page, and can't find out how to change it back without accessing the status page.

### 🐻 Uptime-Kuma Version

1.13.0

### 💻 Operating System and Arch

Arch Linux x86_64 5.15.29-1-lts

### 🌐 Browser

Mozilla Firefox 98.0.2

### 🐋 Docker Version

Docker version 20.10.13

**Comment by louislam** [comment]
I recover the empty slug to `/status/empty-slug-recover`, so that you can access your status page again.

And also `default` is a special slug which `/status` redirects to `/status/default`.
