### ISSUE TITLE
Dark Mode for Kuma?

### ISSUE THREAD

**Issue by ctrlbrk42** [louislam/uptime-kuma#141]
I didn't see this listed elsewhere.  I would appreciate offering a dark mode, please :)

If anyone else agrees, feel free to upvote.

**Comment by Panja0** [comment]
It's already mentioned in https://github.com/louislam/uptime-kuma/issues/21

_Dark mode: based on system settings (thx @LeviSnoot)_

**Comment by philippdormann** [comment]
already did a PR for this at https://github.com/louislam/uptime-kuma/pull/32 which unfortunately had some issues in lightmode

my fork currently is not up to date, still has a working darkmode tho.

in #32 Louis stated he wants 
> that users can choose light/dark theme in the settings


In my opinion, the darkmode should be based on system settings via `prefers-color-scheme` media query
I guess we can vote via GitHub reactions
- **for application preferences (👍)**
- vs
- **system settings via `prefers-color-scheme` (♥)**

**Comment by LeviSnoot** [comment]
Ideally we could have both, I've seen a number of websites have the options of `Light`, `Dark` and `Auto`.

**Comment by Panja0** [comment]
I'm with @LeviSnoot in this one! Light, Dark and auto would be great.

**Comment by moquito64** [comment]
I like to have options as well.

**Comment by chakflying** [comment]
Per [this](https://css-tricks.com/a-complete-guide-to-dark-mode-on-the-web/#using-javascript-local-storage) reference we can switch to a js & css class based approach, and get the `prefers-color-scheme` on load. We can then combine that with a setting set by the user.

**Comment by louislam** [comment]
I put this request to the next milestone. Will try to improve @philippdormann 's dark theme code.

**Comment by louislam** [comment]
![image](https://user-images.githubusercontent.com/1336778/128622302-ae86f812-5415-42f4-8aca-3fed8927a77b.png)

Will be available in the next release.
