### ISSUE TITLE
Keep getting Invalid Token when enabling 2FA

### ISSUE THREAD

**Issue by pwlgrzs** [louislam/uptime-kuma#1411]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

I have installed UpTime Kuma, created user account and wanted to enable 2FA (I use Aegis to handle all 2FA tokens). I scanned the barcode, account has been added to the app but validating token ends with "Invalid Token" error message.
I have checked TZ setting and running "date" inside container returns same time as my PC/phone.

### 🐻 Uptime-Kuma Version

1.13.1

### 💻 Operating System and Arch

Synology NAS Docker

### 🌐 Browser

Edge 99.0.1150.46

### 🐋 Docker Version

20.10.3

**Comment by louislam** [comment]
I just tested with Aegis, it is working fine with my demo site:
https://demo.uptime.kuma.pet/

You could also try the demo site, so it is easier to determine the root issue.

**Comment by pwlgrzs** [comment]
It works fine on demo site with my app. I have restarted container once again, verified time but it keeps giving me invalid token error.
