### ISSUE TITLE
Upgrading Kuma Wipes Out Data

### ISSUE THREAD

**Issue by athornfam2** [louislam/uptime-kuma#1412]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

Thankfully not too critical but when upgrading to the latest version of kuma it wipes out the data collected from monitors. The upgrade basically makes it start from scratch.

https://github.com/louislam/uptime-kuma/wiki/%F0%9F%86%99-How-to-Update#-docker 

### 🐻 Uptime-Kuma Version

1.13.1

### 💻 Operating System and Arch

Ubuntu 20.04 LTS

### 🌐 Browser

99.0.4844.82

### 🐋 Docker Version

20.10.13

### 🟩 NodeJS Version

none

**Comment by louislam** [comment]
My guess is you are using different volume name. Which guide did you follow while you install Uptime Kuma?

**Comment by athornfam2** [comment]
> My guess is you are using different volume name. Which guide did you follow while you install Uptime Kuma?

https://www.wpdoze.com/install-uptime-kuma/. I was pretty sure it aligned with your update guide. I think the dock volume may be different though now looking at it again?

**Comment by louislam** [comment]
> > My guess is you are using different volume name. Which guide did you follow while you install Uptime Kuma?
> 
> https://www.wpdoze.com/install-uptime-kuma/. I was pretty sure it aligned with your update guide. I think the dock volume may be different though now looking at it again?

This guide is using `/docker-vol/uptime-kuma` which is different. You should map to /docker-vol/uptime-kuma.

I would suggest you should backup `/docker-vol/uptime-kuma` first.

And since you are using docker-compose, update through docker-compose is recommended.

Here is the similar question:
https://github.com/louislam/uptime-kuma/issues/918#issuecomment-968197917

**Comment by athornfam2** [comment]
Thanks. I'll take a look at it tonight or tomorrow. Didn't think before the /app would matter but looks like it does. Don't use docker much but seems pretty slick for container based apps.

**Comment by TechWilk** [comment]
I have also run into this issue upgrading from `1.16.1` to `1.17.1`.

I installed using the main docker instructions, and have upgraded each previous time without any issue. 
1. First I ran the usual commands from the upgrade page
```bash
docker pull louislam/uptime-kuma:1
docker stop uptime-kuma
docker rm uptime-kuma

# Default
docker run -d --restart=always -p 3001:3001 -v uptime-kuma:/app/data --name uptime-kuma louislam/uptime-kuma:1```
```
2. Then I navigated to the site as usual to check it `https://uptime.example.com`. Initially I got an Nginx error 502
3. Then after a few mins, I it loaded the "create an account" page and didn't have any of my previously configured monitors

As you can see, I'm using the same docker volume and have access to all the previous backups. The "current" databases are much smaller than the previous backups at `61440` vs `29356032` bytes.

```bash
root@23:/home/uptime# ls /var/lib/docker/volumes/uptime-kuma/_data/ -la
total 1442000
drwxr-xr-x 3 root root      4096 Jun 26 15:46 .
drwx-----x 3 root root      4096 Oct  6  2021 ..
-rw-r--r-- 1 root root     29531 Jun 26 15:46 error.log
-rwxr-xr-x 1 root root     61440 Jun 26 15:46 kuma.db
-rwxr-xr-x 1 root root     61440 Jun 26 15:46 kuma.db.bak0
-rwxr-xr-x 1 root root  29356032 Oct 20  2021 kuma.db.bak20211020083107
-rwxr-xr-x 1 root root  59138048 Nov  3  2021 kuma.db.bak20211103194554
-rwxr-xr-x 1 root root 243339264 Feb  5 14:30 kuma.db.bak20220205143018
-rwxr-xr-x 1 root root 381595648 Apr  7 13:04 kuma.db.bak20220407130434
-rwxr-xr-x 1 root root 382758912 Apr 12 13:08 kuma.db.bak20220412130822
-rwxr-xr-x 1 root root 379420672 Apr 25 14:27 kuma.db.bak20220425142706
-rwxr-xr-x 1 root root     32768 Jun 26 15:47 kuma.db-shm
-rwxr-xr-x 1 root root     32768 Jun 26 15:46 kuma.db-shm.bak0
-rwxr-xr-x 1 root root     32768 Oct 20  2021 kuma.db-shm.bak20211020083107
-rwxr-xr-x 1 root root     32768 Nov  3  2021 kuma.db-shm.bak20211103194554
-rwxr-xr-x 1 root root     32768 Feb  5 14:30 kuma.db-shm.bak20220205143018
-rwxr-xr-x 1 root root     32768 Apr  7 13:04 kuma.db-shm.bak20220407130434
-rwxr-xr-x 1 root root     32768 Apr 12 13:08 kuma.db-shm.bak20220412130822
-rwxr-xr-x 1 root root     32768 Apr 25 14:27 kuma.db-shm.bak20220425142706
-rwxr-xr-x 1 root root    539752 Jun 26 15:47 kuma.db-wal
-rwxr-xr-x 1 root root         0 Jun 26 15:46 kuma.db-wal.bak0
-rwxr-xr-x 1 root root         0 Oct 20  2021 kuma.db-wal.bak20211020083107
-rwxr-xr-x 1 root root         0 Nov  3  2021 kuma.db-wal.bak20211103194554
-rwxr-xr-x 1 root root         0 Feb  5 14:30 kuma.db-wal.bak20220205143018
-rwxr-xr-x 1 root root         0 Apr  7 13:04 kuma.db-wal.bak20220407130434
-rwxr-xr-x 1 root root         0 Apr 12 13:08 kuma.db-wal.bak20220412130822
-rwxr-xr-x 1 root root      4152 Apr 25 14:27 kuma.db-wal.bak20220425142706
drwxr-xr-x 2 root root      4096 Oct  6  2021 upload
```

I can also see the last entry in `error.log` has the same timestamp.

```
[2022-06-26 15:46:22] Error: ENOENT: no such file or directory, copyfile './data/kuma.db.bak20220626154617' -> './data/kuma.db'
    at Object.copyFileSync (node:fs:2817:3)
    at Function.restore (/app/server/database.js:478:16)
    at Function.patch2 (/app/server/database.js:240:18)
    at async Function.patch (/app/server/database.js:203:9)
    at async initDatabase (/app/server/server.js:1560:5)
    at async /app/server/server.js:154:5 {
  errno: -2,
  syscall: 'copyfile',
  code: 'ENOENT',
  path: './data/kuma.db.bak20220626154617',
  dest: './data/kuma.db'
}
```

**Comment by louislam** [comment]
@TechWilk Really strange, because the backup ./data/kuma.db.bak20220626154617 should be created before patch. 


You can rename these 3 files to get back the data of 2022-04-25.
kuma.db.bak20220425142706
kuma.db-shm.bak20220425142706
kuma.db-wal.bak20220425142706

**Comment by TechWilk** [comment]
Yes you're quite right, I've just gone back to take another look and it's a disk space issue which I hadn't noticed. Turns out uptime-kuma didn't handle it gracefully either.

I've rolled back fine now thanks.

`docker logs uptime-kuma` shows that the copy failed and instead of waiting for manual input to resolve this it seemed to empty the db.

```
...
2022-06-26T15:46:17.591Z [DB] INFO: Backing up the database
2022-06-26T15:46:20.896Z [DB] INFO: Closing the database
2022-06-26T15:46:22.906Z [DB] INFO: SQLite closed
Error: ENOSPC: no space left on device, copyfile './data/kuma.db' -> './data/kuma.db.bak20220626154617'
    at Object.copyFileSync (node:fs:2817:3)
    at Function.backup (/app/server/database.js:435:16)
    at Function.patch2Recursion (/app/server/database.js:343:18)
    at Function.patch2 (/app/server/database.js:226:28)
    at async Function.patch (/app/server/database.js:203:9)
    at async initDatabase (/app/server/server.js:1560:5)
    at async /app/server/server.js:154:5 {
  errno: -28,
  syscall: 'copyfile',
  code: 'ENOSPC',
  path: './data/kuma.db',
  dest: './data/kuma.db.bak20220626154617'
}
2022-06-26T15:46:22.910Z [DB] ERROR: Start Uptime-Kuma failed due to issue patching the database
2022-06-26T15:46:22.910Z [DB] ERROR: Please submit the bug report if you still encounter the problem after restart: https://github.com/louislam/uptime-kuma/issues
2022-06-26T15:46:22.911Z [DB] ERROR: Patching the database failed!!! Restoring the backup
Trace: Error: ENOENT: no such file or directory, copyfile './data/kuma.db.bak20220626154617' -> './data/kuma.db'
    at Object.copyFileSync (node:fs:2817:3)
    at Function.restore (/app/server/database.js:478:16)
    at Function.patch2 (/app/server/database.js:240:18)
    at async Function.patch (/app/server/database.js:203:9)
    at async initDatabase (/app/server/server.js:1560:5)
    at async /app/server/server.js:154:5 {
  errno: -2,
  syscall: 'copyfile',
  code: 'ENOENT',
  path: './data/kuma.db.bak20220626154617',
  dest: './data/kuma.db'
}
    at process.<anonymous> (/app/server/server.js:1699:13)
    at process.emit (node:events:527:28)
    at emit (node:internal/process/promises:140:20)
    at processPromiseRejections (node:internal/process/promises:274:27)
    at processTicksAndRejections (node:internal/process/task_queues:97:32)
If you keep encountering errors, please report to https://github.com/louislam/uptime-kuma/issues
==> Performing startup jobs and maintenance tasks
==> Starting application with user 0 group 0
Welcome to Uptime Kuma
Your Node.js version: 16
2022-06-26T15:46:24.033Z [SERVER] INFO: Welcome to Uptime Kuma
2022-06-26T15:46:24.034Z [SERVER] INFO: Node Env: production
...
```
