### ISSUE TITLE
Service was running fine for months and is running into WebSocket error all of a sudden. 

### ISSUE THREAD

**Issue by zell-mbc** [louislam/uptime-kuma#1413]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

My site has been up and running fine for months, but I recently noticed that I am running into the Websockets error again.
```
Cannot connect to the socket server. [Error: timeout] Reconnecting...
Using a Reverse Proxy? Check how to config it for WebSocket
```

I did make the changes required for nginx back when installing for the first time and didn't make any changes to the nginx config since, at least I can't remember.
I just now copied the nginx settings from your link just in case, but no change I am afraid. Here's what I'm running with:

```
server {
    server_name  status.mydomain.de;

    location / {
      proxy_set_header   X-Real-IP $remote_addr;
      proxy_set_header   X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_pass         http://localhost:3001/;
      proxy_http_version 1.1;
      proxy_set_header   Upgrade $http_upgrade;
      proxy_set_header   Connection "upgrade";
    }

    listen 443 ssl; # managed by Certbot
    ssl_certificate /etc/letsencrypt/live/status.mydomain.de/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/status.mydomain.de/privkey.pem; # managed by Certbot
    include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot

}

server {
    if ($host = status.mydomain.de) {
        return 301 https://$host$request_uri;
    } # managed by Certbot

    server_name  status.mydomain.de;
    listen 80;
    return 404; # managed by Certbot
}
```

Nothing in the nginx error log, nothing outstanding in the access log.
Tried different browsers

Is there anything else which might block Websockets?

Environment:
- 
- Docker

```
cat docker-compose.yml
version: '2.3'

services:
  uptime-app:
    container_name: uptime-app
    image: louislam/uptime-kuma:1
    restart: always
    volumes:
      - ./data:/app/data
    ports:
      - 3001:3001
```

### 🐻 Uptime-Kuma Version

Latest docker image

### 💻 Operating System and Arch

Ubuntu 20.04.4 LTS x86_64

### 🌐 Browser

Chromium, Firefox

### 🐋 Docker Version

Docker version 20.10.14, build a224086

### 🟩 NodeJS Version

Not that I know

**Comment by louislam** [comment]
Have you tried to reload nginx? I suspect that the Certbot was modified your nginx config wrongly.

**Comment by zell-mbc** [comment]
I did, even a reboot by now. There are a few more services on this server which Certbot needs to look after (Nextcloud) which work fine.

**Comment by louislam** [comment]
Just found a similar problem.

https://www.reddit.com/r/selfhosted/comments/tew7a9/uptime_kuma_suddenly_not_work/i0xtm03

**Comment by louislam** [comment]
It may be a nginx issue.
https://github.com/mattermost/mattermost-mobile/issues/4557

**Comment by Drazzizzi** [comment]
Does the issue happen when you visit the site from other clients/devices? I had the same issue and it turned out to be my vpn, windscribe. In a recent update, they added extra features to block ads/tracking which seems to have messed with uptime-kuma's websocket connection. After whitelisting my uptime-kuma subdomain on my vpn client, it started working fine again.

**Comment by zell-mbc** [comment]
Good find, that TLS 1.3 sounds promising, I'll definitely check this out and will report back!
Coincidentally I am running Mattermost on a different server, so this is good to know anyway.
