### ISSUE TITLE
Allow searching for multiple tags in search box

### ISSUE THREAD

**Issue by tiakun** [louislam/uptime-kuma#1416]
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

UI Feature

### 🔖 Feature description

Allow searching for multiple tags in search box

### ✔️ Solution

When typing "tag1 tag2" in search box, the UI should display the monitors that tagged both "tag1" and "tag2". The monitors that is tagged only "tag1" or "tag2" should not be displayed.

Currently, if I type "tag1 tag2" in search box, it doesn't match any tags at all.

**Comment by CommanderStorm** [comment]
@tiakun
https://github.com/louislam/uptime-kuma/pull/3312 has been merged and will be released in the upcoming [`1.23`-release](https://github.com/louislam/uptime-kuma/milestone/34)

The current UI looks like this:
![image](https://github.com/louislam/uptime-kuma/assets/26258709/3317caef-d35a-427c-980e-ee083c6f7156)

Is this issue resolved? I think at the current state, I would not expect a user to use the search bar to search for tags…

**Comment by tiakun** [comment]
Thank you so much. I will mark it as resolved for now because now there is UI for searching tags.
