### ISSUE TITLE
Monitoring satisfactory server and pterodactyl pannel

### ISSUE THREAD

**Issue by DrTableBasse** [louislam/uptime-kuma#1417]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

Hey, i want to monitor my satisfactory server host on my own pterodactyl server. So everytime i have "Steam API Key not found" error and idk what can i do to solve it. Could u help ?

thx a lot ! 

### 🐻 Uptime-Kuma Version

Version: 1.13.1

### 💻 Operating System and Arch

ubuntu 20.04 LTS

### 🌐 Browser

firefox 98.02

### 🟩 NodeJS Version

16

**Comment by louislam** [comment]
You have to set this api key.

![image](https://user-images.githubusercontent.com/1336778/160227446-5249c188-e644-4778-a46f-05994feb92d3.png)

**Comment by DrTableBasse** [comment]
Oh ok but now i have "server not found" but i create a API key and put in on the panel so i dont understand why it doesn't work 🤔 maybe bc i'm behind my router ? (internet<--->router<---->pterodactyl)

**Comment by aogmike** [comment]
@DrTableBasse Hey, I have the same setup and I have the same issue as you. Did you find a solution?

**Comment by MCOfficer** [comment]
Had a similar issue with valheim - if the server you're monitoring is exposing multiple ports, there's no guarantee uptime-kuma will recognize the port the steam server browser shows. For example, valheim exposes 2456, 2457 and 2458 by default. The steam server browser shows 2456 as the active port, yet uptime-kuma only works with 2457.

**Comment by RomeoNotaLoka** [comment]
> Had a similar issue with valheim - if the server you're monitoring is exposing multiple ports, there's no guarantee uptime-kuma will recognize the port the steam server browser shows. For example, valheim exposes 2456, 2457 and 2458 by default. The steam server browser shows 2456 as the active port, yet uptime-kuma only works with 2457.

so how did you fixed it?
I am running valheim locally. it is not expose to the internet and only available to play within my network. any hints ?

**Comment by MCOfficer** [comment]
i fixed it by telling kuma to use 2457, but my valheim server is public. If uptime-kuma isn't even in the same network, you're out of luck.

**Comment by Destreyf** [comment]
@DrTableBasse 

I haven't tested this with satisfactory yet, but with Ark I had to specify the IP Address and not a host name.

Further more, I am not certain local will work correctly because the monitor uses the steam server list web API to pull the data.

I haven't done enough testing with other games, but I believe the game determines the public IP and then it reports it to the Steam Server List API.

**Comment by Destreyf** [comment]
Additionally monitoring game servers is a bit complicated because most of the communication is done via UDP or undocumented TCP endpoints/calls, making it hard to ping the endpoint to see if it responds in order to verify it's up.
