### ISSUE TITLE
Request to add DNS query

### ISSUE THREAD

**Issue by ctrlbrk42** [louislam/uptime-kuma#142]
I would love to see the ability to submit a simple DNS query to verify name resolution is working.

**Comment by Ponkhy** [comment]
> I would love to see the ability to submit a simple DNS query to verify name resolution is working.

What kind of DNS query have you been thinking about?
Sounds like you want a normal DNS Lookup for a domain or is there something more specific you need?

**Comment by ctrlbrk42** [comment]
> > I would love to see the ability to submit a simple DNS query to verify name resolution is working.
> 
> What kind of DNS query have you been thinking about?
> Sounds like you want a normal DNS Lookup for a domain or is there something more specific you need?

A record would work fine for me. So basically just need IP of DNS server, and the query input. Success/fail based on getting back a response vs timeout.

**Comment by Ponkhy** [comment]
I think we can close this issue, since it'll be implemented in Version `1.5.0`.
