### ISSUE TITLE
ADD OPTION TO MONITOR TELEGRAM BOTS

### ISSUE THREAD

**Issue by adarsh-goel** [louislam/uptime-kuma#1420]
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

New Monitor

### 🔖 Feature description

Uptime kuma is a great service but what it lacks is that it can't track the live uptime of telegram bots.

### ✔️ Solution

I want to track whether bot is up also so could you please add that

**Comment by adarsh-goel** [comment]
also it would be great if you add external database support because restart or redeploy = data gone for now

**Comment by louislam** [comment]
> also it would be great if you add external database support because restart or redeploy = data gone for now

It is not true. It is persistent. Most likely you forgot to set the volume. Please follow `how to install` in README.md and `How to Update` in the wiki.

**Comment by temamagic** [comment]
@adarsh-goel Telegram bot is a simple service. You should implement health checks and monitor them

**Comment by adarsh-goel** [comment]
hmm ok
