### ISSUE TITLE
DNS Overwrite/Assignment for URL in Monitoring

### ISSUE THREAD

**Issue by Lakr233** [louislam/uptime-kuma#1421]
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

Other

### 🔖 Feature description

I have a domain (let's say www.example.com) redirected to a local host device (let's say 10.10.10.15) on my router so I can access my service quickly when I connect to my local network, but I may want to check it's public ip (let's say 123.123.123.123) for service availability matters, I've got jump/reversed proxy for that port mapping it to public.

### ✔️ Solution

 I'd like to have an option for overwrite server ip address without changing the dns server it self.

<img width="509" alt="截屏2022-03-28 00 10 58" src="https://user-images.githubusercontent.com/25259084/160290550-9f01e2e3-de45-446a-9488-a74152e3d6cc.png">

**Comment by gaby** [comment]
👍🏻 for this feature!

**Comment by dkay-zaxxx** [comment]
This would be a great feature to add to the project!

Great tool overall!

**Comment by UbioZur** [comment]
I am also looking for a similar option.

I know it's possible to do a similar 'outside check' through a proxy. But finding a free proxy to do that check is annoying and they never live long enough to make it useful through uptime-kuma.

The possibility to bypass the docker DNS, would make it easier to be able to check local DNS and remote DNS for a service.

**Comment by miHaMu** [comment]
I'm also looking for this feature!
I want to customize the DNS for each HTTP type of monitor to differentiate between internal and external networks.

**Comment by CommanderStorm** [comment]
@Lakr233 

You can do that with the tools currently at your disposal:
- you enter the ip into the url field
- you enter the [`Host` header](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Host) as described in https://github.com/louislam/uptime-kuma/issues/2991

I think this is a duplicate of https://github.com/louislam/uptime-kuma/issues/2991 https://github.com/louislam/uptime-kuma/issues/3979
If you agree, could you please close this Issue, as duplicates only create immortal zombies and are really hard to issue-manage?
If not, what makes this issue unique enough to require an additional issue? (Could this be integrated into the issue linked above?) ^^

Note that [our contribution guide can be found here](https://github.com/louislam/uptime-kuma/blob/master/CONTRIBUTING.md) and that we are open to contributions if you adhere to this

**Comment by Lakr233** [comment]
@CommanderStorm Thank you for providing this level of detail, and I have confirmed that it is working as expected.
