### ISSUE TITLE
Remote probes available.

### ISSUE THREAD

**Issue by zimbres** [louislam/uptime-kuma#1424]
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

Other

### 🔖 Feature description

Since some people is bean crating some kind of remote probe to use with "push" option, would be good to have it listed so this way people can use it and contribute.

### ✔️ Solution

Update Readme to list available remote probes know available.

### ❓ Alternatives

NA

### 📝 Additional Context

Mine is here: [UptimeKumaRemoteProbe](https://github.com/zimbres/UptimeKumaRemoteProbe)

Available methods in the probe are: Ping, Tcp, Http with expected keyword and Certificate expiration.

**Comment by CommanderStorm** [comment]
@zimbres You seem to have dropped the project you mentioned. Could you close this issue?
Also note that adding links to 3rd party apps/... is possible in the wiki: https://github.com/louislam/uptime-kuma/wiki
=> If this is still active, please add your probe there
