### ISSUE TITLE
duplicate monitor when information changed

### ISSUE THREAD

**Issue by mhkarimi1383** [louislam/uptime-kuma#1429]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### Description

when I change name, labels, etc it will duplicate it in the metrics (e.g. when changing name, one with older name one with new name)

### 👟 Reproduction steps

changing the name or any other information of the monitor from uptime kuma

I have also tried to remove data with old name but the problem was from the actual exporter

### 👀 Expected behavior

no duplicate metric

### 😓 Actual Behavior

got duplicate metrics

### 🐻 Uptime-Kuma Version

1.13.1

### 💻 Operating System and Arch

debian buster, alpine docker image X86

### 🌐 Browser

any browser

### 🐋 Docker Version

Docker 20.10.11

**Comment by chakflying** [comment]
Fixed in #1136, will be available in next release.

**Comment by mhkarimi1383** [comment]
Thanks.... waiting for update ;)
