### ISSUE TITLE
SMTP Error: Client network socket disconnected before secure TLS connection was established

### ISSUE THREAD

**Issue by PeterXQChen** [louislam/uptime-kuma#143]
Trying to setup Email SMTP notification but keep getting this error when testing.

I've used the same setting for other services and they work fine.

Tried playing around with the settings and changing ports and what not. Nothing works.

**Comment by louislam** [comment]
Can't find related issues. 

I suggest you could check/uncheck the "Secure".

https://github.com/louislam/uptime-kuma/issues/140#issuecomment-890712067

**Comment by PeterXQChen** [comment]
Yes i've tried that setting, nothing works.

**Comment by louislam** [comment]
Found a possible reason, the smtp's TLS probably too old and Node.js no longer supports it. 
https://github.com/nodejs/node/issues/21088#issuecomment-486149589

If you installed the Uptime Kuma via Docker, I built-in Apprise, which also supports SMTP and it is based on Pyhton, it maybe works:

https://github.com/caronc/apprise/wiki/Notify_email


![image](https://user-images.githubusercontent.com/1336778/127889095-1421952d-a338-4efa-96f8-286c4899718b.png)

**Comment by PeterXQChen** [comment]
Thanks! I'll give Apprise a try.
