### ISSUE TITLE
Add Support To Monitor SQL Server "Uptime"

### ISSUE THREAD

**Issue by dutchie027** [louislam/uptime-kuma#1430]
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

New Monitor

### 🔖 Feature description

You should add the ability to have a new monitor that can monitor SQL type services. Currently there are HTTP/S, TCP, PING, DNS and Push, but nothing that allows additional information to be "queried.

### ✔️ Solution

I'd like to be able to supply a server name, credentials and a basic query and have Uptime Kuma store the ms return time and based on either (a) the time returned or (b) the status of the server it would return "down". I.e. a supplied query that takes > 5000 ms should be considered "DOWN" or of course a "DOWN" server should also be considered down (theoretically a DOWN server wouldn't return a query result in less than 5000 ms, but it could be handled with different connectivity logic, etc)

### ❓ Alternatives

You can check for the opening on port 3306, but that doesn't actual check for a TRUE return from a query, nor does it give you a process time for the database.

You could also write a HTTP check that returns a 200 on the front end, that checks on the back end, but that would be multiple "hops" and it would be nice to keep all of the "checks" centralized and coming from the same source.

**Comment by zimbres** [comment]
Based in your idea, I started to add option to monitor SQL Server in the Remote Probe that I am developing.

Take a Look:

[UptimeKumaRemoteProbe](https://github.com/zimbres/UptimeKumaRemoteProbe)

**Comment by dutchie027** [comment]
@zimbres That's making a connection, but it's not doing a true select. I've seen all too often where admins assume that because a TCP 3306 with credentials is open that their SQL server is up, when in all actuality, there is a problem with credentials and you can't select or even worse, the database is overloaded and the select takes much longer than anticipated...

**Comment by zimbres** [comment]
@dutchie027 

In fact, in my app, Im doing a select, its a simple one, `"Select VERSION() AS Version"`, but should be ok to make sure SQL is answering queries.

You are right when say that just a port open helps, but, is not enough in some scenarios.

**Comment by dutchie027** [comment]
@zimbres 

That's good to know. I was simply going by the config you have:
```
      {
        "Type": "DataBase",
        "PushUri": "http://localhost:3001/api/push/ehhghF8HLA?msg=OK&ping=",
        "ConnectionString": "server=localhost;database=mysql;user=root;password=my-secret-pw",
        "Brand": "MYSQL",
        "Timeout": 1000
      }
```
which didn't seem to denote any SQL queries in it. Also, why do you need the brand if you have the type in the connection string? Isn't that overkill? Further, shouldn't the notifications of Uptime Kuma also suffice for the `PushUri`?

**Comment by zimbres** [comment]
@dutchie027 

Hi, the query that will be run against SQL Server is inside code in `DbService.cs`

I need to differ if is MSSQL or MYSQL for instance, it is possible to do this by ConnectionString, but requires more logic.

My app is very fresh and for sure lack documentation of how to use.

I could not understand your question about the PushUri, once I create a new monitor in Uptime Kuma and chose Push, this is a unique URL that will be called by the app, in case of failure the URL will not be called, and according to settings defined in UK for heartbeat interval, alert will be triggered.

**Comment by zimbres** [comment]
Hi, any .Net except .Net Full Framework is cross plataform.

To run you issue "dotnet UptimeKumaRemoteProbe.dll" or "./UptimeKumaRemoteProbe" for file inside Linux folder.
