### ISSUE TITLE
Import exported settings to docker container

### ISSUE THREAD

**Issue by pyropy** [louislam/uptime-kuma#1431]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

Would it be possible to load exported JSON settings to docker container by mapping volumes?

### 🐻 Uptime-Kuma Version

1.13.1

### 💻 Operating System and Arch

OSX

### 🌐 Browser

Brave

### 🐋 Docker Version

Docker Desktop 4.5.0 74594

**Comment by LoaderB0T** [comment]
AFAIK there are two options at the moment.
You can either use the WEB UI (settings/backup) to export and import your settings **or** backup the docker volume to restore it elsewhere.

The files inside of the docker volume are not in JSON format and are not manually editable. So taking the exported values from the web UI and putting them directly inside the volume is not possible.
You'll have to decide, either manually backing up via UI or backing up via scripts that backup docker volumes.

The docker volume backups have the advantage that the history and event data will also be included in the backup.

**Comment by pyropy** [comment]
Got it, thank you @LoaderB0T for your response 🙏🏻
