### ISSUE TITLE
HTTP Redirection check: Status 308 interpreted as 301

### ISSUE THREAD

**Issue by johanneskastl** [louislam/uptime-kuma#1432]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 👟 Reproduction steps

1. Define a HTTP check (not HTTPS!) for a website that has a permanent redirection enabled. 
2. Set the `redirects` to 0.
3. Set the expected status code to 308
4. Verify via curl that you really get a 308
5. Uptime-Kuma reports the monitor as down, as it got thinks it got a 301 status code

Example:
```
$ curl -sI http://johanneskastl.de |head -n 1
HTTP/1.1 308 Permanent Redirect
```

Log from Uptime-Kuma:
```
Request failed with status code 301
```

### 👀 Expected behavior

Uptime-Kuma should properly recognize the 308 status code and report the monitor as UP.

### 😓 Actual Behavior

Uptime-Kuma detects a status code 301 where in reality it is getting a 308. Hence it sets the monitor to DOWN.

### 🐻 Uptime-Kuma Version

v1.11.1

### 💻 Operating System and Arch

not relevant, as Kubernetes only

### 🌐 Browser

Firefox

**Comment by chakflying** [comment]
Interesting. I did some testing and looks like curl is the odd one that's handling 308 correctly. Python `requests`, Chrome, Firefox and Node 17's `fetch()` all reports 301, so I guess the limitation runs pretty deep.

**Comment by louislam** [comment]
Would you mind to share the part of redirect logic of your website?

Tested with several platforms, they are different too.

Chrome = 307
curl -sI = 308
curl -v = 301

php = 301
```php
$curl = new \Curl\Curl();
$curl->get("http://johanneskastl.de");
print_r($curl->httpStatusCode);
```

Node.js = 301
```javascript
const options = {
    host: "johanneskastl.de",
};

http.get(options, (res) => {
    console.log(res.statusCode);
    res.resume();
});
```

**Comment by johanneskastl** [comment]
> Would you mind to share the part of redirect logic of your website?

In my case this is a Traefik Proxy running in Kubernetes that redirects HTTP to HTTPS using a redirectScheme middleware:
https://doc.traefik.io/traefik/middlewares/http/redirectscheme/

```
# Redirect to https
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: test-redirectscheme
spec:
  redirectScheme:
    scheme: https
    permanent: true
```

**Comment by louislam** [comment]
https://github.com/traefik/traefik/issues/7829#issuecomment-770210080

Found this, I think it is by design of traefik.

**Comment by johanneskastl** [comment]
> [traefik/traefik#7829 (comment)](https://github.com/traefik/traefik/issues/7829#issuecomment-770210080)
> 
> Found this, I think it is by design of traefik.

Thanks for your help, funny that Traefik is reporting different status codes depending on who is asking... :-(
