### ISSUE TITLE
Graph history

### ISSUE THREAD

**Issue by rmonn** [louislam/uptime-kuma#1434]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

Is it normal that graph history is limited to 1 week at maximum ?

Could we have 1 month and 1 year ?

### 🐻 Uptime-Kuma Version

1.13.1

### 💻 Operating System and Arch

Rocky 8.5

### 🌐 Browser

Google Chrome 99.0.4844.84

### 🐋 Docker Version

Podman 3.4.2

**Comment by Computroniks** [comment]
Currently the graphs only go back to 1 week. I think I remember seeing an issue or PR about increasing it but I can't find it now (I will add it here if I find it again). There was some discussion over making sure that the implementation wasn't going to slow down the rest of the system.
