### ISSUE TITLE
Slack Alert

### ISSUE THREAD

**Issue by sunflowerno0b** [louislam/uptime-kuma#1436]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

hi there,

I have an instance of uptime-kuma and I took a service down to test the slack notification. I have used the test feature and that works just fine. Uptimee-kuma see's that the service is down and is reporting it accurately but I am not receiving the slack notificaiton to let me know that the service is down. 

### 🐻 Uptime-Kuma Version

3.3

### 💻 Operating System and Arch

AWS Linux Server 20.04 lTS

### 🌐 Browser

Firefox

### 🐋 Docker Version

Docker version 20.10.7, build 20.10.7-0ubuntu5~20.04.2

**Comment by xeruf** [comment]
Please use a more descriptive title and add some logs
