### ISSUE TITLE
Not available in browser after installation

### ISSUE THREAD

**Issue by benalla** [louislam/uptime-kuma#1439]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

I installed it on a RaspBerryPi 4 (HomeAssistant) using these steps:

![image](https://user-images.githubusercontent.com/3511603/161023104-8a7e43b5-adfb-45ac-8def-8bd351d5c79b.png)

But using node server/server.js it gives:
bash: /usr/local/bin/node: No such file or directory

Using Option 2 to start Uptime-Kuma works.
![image](https://user-images.githubusercontent.com/3511603/161023164-6c9674f7-9b5f-49e5-ab38-a041dd2fac14.png)

What am I missing?
How to install Node.js using 'apk'?

### 🐻 Uptime-Kuma Version

1.13.1

### 💻 Operating System and Arch

Aarch64

### 🌐 Browser

Google Chrome 99.0.4844.82

**Comment by LoaderB0T** [comment]
What's the output of `node -v` in that folder? Maybe something's funky with your node installation?

**Comment by benalla** [comment]
I reintstalled Uptime-Kuma but still not available in the browser.
Output for node -v:   **v14.19.0**

Starting Uptime-Kuma with '_node server/server.js_' gives:
![image](https://user-images.githubusercontent.com/3511603/161346182-7e7c4e1f-1368-41ad-b0d1-d1ba2d244b5a.png)

**Comment by temamagic** [comment]
@benalla port 3001 open?

**Comment by temamagic** [comment]
Oh my

![image](https://user-images.githubusercontent.com/15264697/161417397-8395525c-e0ff-4fb9-9059-b3ade1d5d7ff.png)

**Comment by benalla** [comment]
'already in use' is because Uptime-Kuma was already running and I started it again with node command.

Port 3001 is open:
![image](https://user-images.githubusercontent.com/3511603/161424362-93a0196d-9668-41d0-b0f7-0b730400042a.png)

**Comment by LoaderB0T** [comment]
I am confused, in your original post you wrote 

> But using node server/server.js it gives:
bash: /usr/local/bin/node: No such file or directory

But now you posted a screenshot of the port error, that was caused by it already running in the background.
I thought the original node error `bash: /usr/local/bin/node: No such file or directory` would appear directly without any log from uptime-kuma. Could you post the complete log of running `node server/server.js` without the port being blocked?
