### ISSUE TITLE
SQL foreign key

### ISSUE THREAD

**Issue by parityhero** [louislam/uptime-kuma#144]
Updated from 1.0.4 to 1.0.7 with docker, tried to update a monitor with retries from 0 to 3....

Get a monitor_notification error for SQLITE.

See screenshot:

![08-2021-AEo7DW4RHV6UCMPLQEnY](https://user-images.githubusercontent.com/9137721/127930579-71e3f73f-38b5-4ba1-ad0a-4fec62d5f5c7.jpg)

**Comment by louislam** [comment]
Strange, it is related to notifications. Try to temporarily disable notifications, see if it enables to save.

**Comment by parityhero** [comment]
Not sure what happened but it seemed to have fixed it self, I did try disabling notifications and still got the same error, but I did restart the docker container, so maybe a combination of both fixed it.

Either way it seems to be resolved now.
