### ISSUE TITLE
Notification Apprise - Sent but not received

### ISSUE THREAD

**Issue by PiDroid-B** [louislam/uptime-kuma#1440]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

Hello,

I used Uptime-Kuma under docker : `louislam/uptime-kuma:latest`

I try to set notification to apprise-api through GUI :

- Notification type : `Apprise (+50...)`
- Apprise URL : `apprise://apprise:8000/my_key?tag=kuma`
- Default enabled : :white_check_mark: 
- Apply to all : :white_check_mark: 

When i click on `Test` then there is `Sent Successfully` message but nothing receive in my apprise.
When i down a container to turn to red the probe, i receive nothing.

When i go into the kuma's container and i type `apprise --body="Test Message" "apprise://apprise:8000/my_key?tags=kuma" -vvv`, the notification is sent and received.

I don't know what i miss.
Thank's for your help

### 🐻 Uptime-Kuma Version

1.13.1

### 💻 Operating System and Arch

Container docker under Debian bullseye

### 🌐 Browser

Firefox 98.0.2 (64 bits)

### 🐋 Docker Version

docker 20.10.14

### 🟩 NodeJS Version

N/A

**Comment by louislam** [comment]
It is working in my side, I config-ed Telegram in my apprise api.

![image](https://user-images.githubusercontent.com/1336778/161374357-824b974c-8011-430d-9490-47351a222dcb.png)

Uptime Kuma is using this command to call Apprise: `apprise -vv -b <msg> <url>`, maybe you should try this in your container.

https://github.com/louislam/uptime-kuma/blob/4738581c66da59218df821a953606bab392991e4/server/notification-providers/apprise.js#L9

**Comment by PiDroid-B** [comment]
Thank's it works !

I'm sorry i think i miss an 's' to my parameter 'tags'

This is the output of my docker in interactive mode (`docker exec -it kuma bash`) :
```
2022-04-02 11:42:09,473 - INFO - Notifying 1 service(s) asynchronously.
2022-04-02 11:42:09,501 - WARNING - Failed to send Apprise API notification: error=424.
```

I miss something because i see nothing outside the container, only information like that in my docker.log and nothing in error.log :
`Apr  2 11:47:42 my_host/kuma[1357067]: Monitor #4 'my_probe': Successful Response: 59 ms | Interval: 60 seconds | Type: http`
Maybe there is a place to define level of error.log somewhere ?

Thank's for this amazing project :+1:
