### ISSUE TITLE
Incidents does not survive container recreation

### ISSUE THREAD

**Issue by vedmaka** [louislam/uptime-kuma#1447]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### Description

Incidents disappear on container recreation

### 👟 Reproduction steps

* Create status page
* Create an incident
* Stop & remove the container (but not the volume)
* Start new container (attaching the same volume)

### 👀 Expected behavior

Incident on the status page is in place

### 😓 Actual Behavior

No incident present on the status page

### 🐻 Uptime-Kuma Version

1.13.1

### 💻 Operating System and Arch

CentOS 7

### 🌐 Browser

Chrome

### 🐋 Docker Version

1.13.1

**Comment by louislam** [comment]
Cannot reproduce. The incident is still there after restarted. Detailed steps or video may be needed.

![image](https://user-images.githubusercontent.com/1336778/161432949-bd8c29ad-3334-4372-a5a7-01ed4e38c718.png)

**Comment by CommanderStorm** [comment]
I am going to close this as this is not reproducible on our side and @vedmaka did not respond what they did to get into this state
