### ISSUE TITLE
Discord notifications : the Service URL is empty for some tests

### ISSUE THREAD

**Issue by Tagadda** [louislam/uptime-kuma#1448]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### Description

In the Discord notification, the Service URL is empty or only contain "https://" when the Monitor type is not HTTP.

![image](https://user-images.githubusercontent.com/36127788/161433699-cbe79d51-1752-49fd-93f3-1115fcd24919.png)

### 👟 Reproduction steps

1. Setup a Discord Notification
2. Create a Ping Monitor with this notification enabled
3. Make it fail or succed

### 👀 Expected behavior

The Service URL should not be here.

### 😓 Actual Behavior

The Sevice URL field is empty or only contain "https://".

### 🐻 Uptime-Kuma Version

1.11.3

### 💻 Operating System and Arch

Debian 10

### 🌐 Browser

Firefox 98

### 📝 Relevant log output

https://github.com/louislam/uptime-kuma/blob/dd183e2ec25d74429541ca06c412d53c92e2cb92/server/notification-providers/discord.js#L50-L53

**Comment by jordanbertasso** [comment]
I'll take a crack at this
