### ISSUE TITLE
Blank page in unexist statuspage slug

### ISSUE THREAD

**Issue by AnnAngela** [louislam/uptime-kuma#1451]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### Description

Using master branch to start up dev backend & frontend server, made a monitor an a statuspage. Then open the statuspages, changed url in address bar to an unexist statuspage slug, the page went to blank.

![image](https://user-images.githubusercontent.com/9762652/161471810-dde15124-29e4-4d18-a01b-24eb036486c4.png)

### 👟 Reproduction steps

1. Clone master branch.
2. Run `npm ci --dev`.
3. Run `npm run start-server-dev`.
4. Run `npm run dev`.
5. Open `http://localhost:3000/`.
6. Create a monitor and a status page.
7. Open the status page.
8. Change the url in address bar to an unexist statuspage slug.

### 👀 Expected behavior

Something shows `Page Not Found`-like message.

### 😓 Actual Behavior

Blank page

### 🐻 Uptime-Kuma Version

1.14.0-beta.1

### 💻 Operating System and Arch

Windows 10 Pro 21H2 x64 19044.1620

### 🌐 Browser

Microsoft Edge Dev x64 101.0.1210.2

### 🐋 Docker Version

N/A

### 🟩 NodeJS Version

v16.13.0

### 📝 Relevant log output

```shell
Both servers shows nothing.
```

**Comment by AnnAngela** [comment]
I figured out that [this axios request](https://github.com/louislam/uptime-kuma/blob/99042e6991e5fa7f83a333bfd603e00270b0c0af/src/pages/StatusPage.vue#L458) doesn't handle error. Maybe this is the point.

**Comment by louislam** [comment]
In deep, most non-existing resources are unhandled currently, may plan to review all vue routes later.

**Comment by Electrenator** [comment]
It looks like the 404 status page is no longer displaying with an status page which don't exists. The page is blank again within version 1.21.2 like this issue had described from last year
