### ISSUE TITLE
Resample datas instead of deleting

### ISSUE THREAD

**Issue by duylong** [louislam/uptime-kuma#1458]
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

Other

### 🔖 Feature description

Hi, 

Instead of deleting the data after 180 days (default), we could resample the data to reduce the size of the database.

### ✔️ Solution

We can after 180 days average over a period of time of one day. We could also keep only the state changes.

**Comment by CommanderStorm** [comment]
v2.0 does use resampling to get around the performance limts of v1
