### ISSUE TITLE
Problem running kuma on ipv4 only host

### ISSUE THREAD

**Issue by particeps1** [louislam/uptime-kuma#1459]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

I recently disabled ipv6 on my host via grub and sysctl, rebooted and got following kuma error message on a monitored host with monitor-type ping: "/bin/ping: socket: Address family not supported by protocol"

any ideas?

### 🐻 Uptime-Kuma Version

1.13.1

### 💻 Operating System and Arch

Ubuntu 21.10

### 🌐 Browser

firefox

### 🐋 Docker Version

n/a

### 🟩 NodeJS Version

v17.8.0

**Comment by louislam** [comment]
https://github.com/iputils/iputils/issues/293

I think your current iputils is having this bug. Try to update your iputils to the latest version.
