### ISSUE TITLE
Support X-Remote-User for reverse proxy authentication

### ISSUE THREAD

**Issue by dougmaitelli** [louislam/uptime-kuma#146]
It would be nice to be able to authenticate using my reverse proxy so I can have a single sign-on without needing a separate password for kuma.

**Comment by louislam** [comment]
No auth mode is coming.

https://github.com/louislam/uptime-kuma/commit/6f868c9ec3bc8814f385dcd353aeec5e32ef0939

**Comment by louislam** [comment]
> No auth mode is coming.
> 
> [6f868c9](https://github.com/louislam/uptime-kuma/commit/6f868c9ec3bc8814f385dcd353aeec5e32ef0939)

Implemented in 1.0.8

 https://github.com/louislam/uptime-kuma/releases/tag/1.0.8

**Comment by dougmaitelli** [comment]
Thanks @louislam!

That definitely helps, but I still feel that X-Remote-User would be a nice addition. Based on what I see it looks like the no auth mode uses "admin" as default.

If someone wants to use a reverse proxy to control access to the tool but having different access types (eg. Viewer and admin) the no auth mode would not be enough.
