### ISSUE TITLE
chartjs dependency issue during installation

### ISSUE THREAD

**Issue by ctrl-Felix** [louislam/uptime-kuma#1460]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

I am trying to install uptime-kuma through nodejs manually. When I run ``npm run setup`` I keep getting this:
```npm ERR! code ERESOLVE
npm ERR! ERESOLVE could not resolve
npm ERR! 
npm ERR! While resolving: chartjs-adapter-dayjs@1.0.0
npm ERR! Found: chart.js@3.6.2
npm ERR! node_modules/chart.js
npm ERR!   chart.js@"~3.6.2" from the root project
npm ERR!   peer chart.js@"=> ^3.1.0" from vue-chart-3@3.0.9
npm ERR!   node_modules/vue-chart-3
npm ERR!     vue-chart-3@"3.0.9" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer chart.js@">= 2.8.0 < 3" from chartjs-adapter-dayjs@1.0.0
npm ERR! node_modules/chartjs-adapter-dayjs
npm ERR!   chartjs-adapter-dayjs@"~1.0.0" from the root project
npm ERR! 
npm ERR! Conflicting peer dependency: chart.js@2.9.4
npm ERR! node_modules/chart.js
npm ERR!   peer chart.js@">= 2.8.0 < 3" from chartjs-adapter-dayjs@1.0.0
npm ERR!   node_modules/chartjs-adapter-dayjs
npm ERR!     chartjs-adapter-dayjs@"~1.0.0" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! See /root/.npm/eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2022-04-06T10_41_05_774Z-debug-0.log
```

``npm install`` is throwing the same

https://www.npmjs.com/package/chartjs-adapter-dayjs -> There isn't much information there

### 🐻 Uptime-Kuma Version

1.13.1

### 💻 Operating System and Arch

Debian 11

### 🌐 Browser

None

### 🟩 NodeJS Version

16.14.2

**Comment by louislam** [comment]
> `npm install` is throwing the same

The setup script should execute `npm ci --prodcution` instead of `npm install`. Did you really using `npm run setup`?

https://github.com/louislam/uptime-kuma/blob/ffc5bca51df1e4a9961cddad21a5791460faa247/package.json#L39

**Comment by ctrl-Felix** [comment]
> The setup script should execute `npm ci --prodcution` instead of `npm install`. Did you really using `npm run setup`?

Yes, I initially executed ``npm run setup`` and I got that error .I then tried ``npm ci --production`` and got the same. That's when I tried ``npm install`` just to see if it would make any difference. It didn't.

**Comment by louislam** [comment]
Strange, because it is a known issue for npm 8. `npm ci --prodcution` should be ok.

I can only reproduce the problem by deleting the `package-lock.json` file.

Is there the `package-lock.json` file in the directory?

Alternative you can install it by `npm run install-legacy`, but it is not recommended, because you may face file conflict issue later when you try to upgrade Uptime Kuma.

**Comment by ctrl-Felix** [comment]
There is a ``package-lock.json`` in there. I tried it with Nodejs v17 and it was working now. v16 wasn't working

**Comment by ctrl-Felix** [comment]
I will close this now as it's working with Node 17.

There might be a bug with v16 tho.

**Comment by usuall** [comment]
I was occured same problem. 
C:\virtualbox\uptime-kuma>node -v
v16.14.2

**Comment by louislam** [comment]
Work fine on my Node 16.14.1, will test 16.14.2.

And what is your npm version? `npm -v`

**Comment by louislam** [comment]
Ops, after update npm to 8.6.0, I can now reproduce the problem.

Related issue: https://github.com/npm/cli/issues/4664
