### ISSUE TITLE
App checck

### ISSUE THREAD

**Issue by minster586** [louislam/uptime-kuma#1462]
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [x] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

Other

### 🔖 Feature description

so i have a app that links to the net and want to make sure it is running is there any way say to have a pluging check if said app is running then report back to uptime-kuma

### ✔️ Solution

Discord bot is runnig report app online
discord bot not running show as offline

**Comment by Computroniks** [comment]
Uptime Kuma provides a number of ways to check an application. Depending on what the app is depends on which monitor you select. Without knowing exactly what app you are trying to check I would recommend trying the HTTP or TCP monitor or if you just want to make sure that the server is up you could try the ping monitor.

**Comment by minster586** [comment]
so i have a app bot for discord that does not have a web interface (https://nadeko.bot/) sometime it crashes and I don't know that it has can uptime-kuma check something like that or is there a was to say have app watch it the say the status is up to uptime-kuma

**Comment by Computroniks** [comment]
What ports does it listen on if any, and are these TCP or UDP

**Comment by minster586** [comment]
that's the thing I have no clue I don't understand it that much just know that the app works for me but would like to know the status of it with uptime-kuma

**Comment by Computroniks** [comment]
Sorry, if you don't know at least some information about the app, then I have no way to help you. Do you know what it is called? Does it have a website?

**Comment by minster586** [comment]
this is all I know (https://nadeko.bot/) is the website but the app itself doesn't have a website and if there is maybe other info then idk where or what to find

**Comment by Computroniks** [comment]
Having had a look at the docs, the best I can find is perhaps a HTTP monitor. Without knowing more I can't help you here.

**Comment by minster586** [comment]
ok because I asked it the discord for that app aka bot and someone said something like an endpoint if there was something I can get say install and it watches the app then makes an endpoint that would work I think

**Comment by Computroniks** [comment]
> ok because I asked it the discord for that app aka bot and someone said something like an endpoint if there was something I can get say install and it watches the app then makes an endpoint that would work I think

I don't understand

**Comment by minster586** [comment]
hard to explain but I will try so i think for example MS word has no way to know from uptime-kuma that it is running but say there was a piece of software that one could get that you tell it to watch (word.exe) if that app or buy its PID stops then it changes the status of uptime-kuma I tried

**Comment by Computroniks** [comment]
Ok. What you are looking for is an external push monitor. I would suggest using a bash script if you are on Linux or a bat or PowerShell script on windows that checks the process and sends a request to the push monitor.

**Comment by minster586** [comment]
so i have uptime-kuma in docker on ubuntu 20.04 can you point me in the right direction of what I can use out what is need and thank you

**Comment by Computroniks** [comment]
Here are some sites that you might find useful:
https://www.cyberciti.biz/faq/bash-check-if-process-is-running-or-notonlinuxunix/
https://curl.se/docs/httpscripting.html

Other than that, I can't really help you much more as I don't know the bot and this is a bit out of scope for this repo

**Comment by minster586** [comment]
ok thank

**Comment by Computroniks** [comment]
Also check out this comment for some more help. https://github.com/louislam/uptime-kuma/issues/279#issuecomment-942099654
