### ISSUE TITLE
New monitors not available to add to status page in Safari

### ISSUE THREAD

**Issue by DJFraz** [louislam/uptime-kuma#1465]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### Description

Currently running UptimeKuma 1.13.2 and have multiple status pages. Any monitor that was already in the system prior to being able to have numerous status pages can be added. I have added a new monitor to 1.13.2 and I do not get the option to add a new monitor while using Safari on MacOS. I only see the message `No monitors available. Add one`.

If I open the page in Chrome or Edge, I have the option to add the new monitor.

### 👟 Reproduction steps

Using Safari (15.3) on MacOS (12.2.1), create a new monitor in Uptime Kuma and save it. Go to any status page and click `Edit Status Page`. The list of monitors does not display to add a new one to the status page.

### 👀 Expected behavior

The user should be able to see the list of available monitors to add to the page.

### 😓 Actual Behavior

List of available monitors does not appear. I only see message `No monitors available. Add one`

### 🐻 Uptime-Kuma Version

1.13.2

### 💻 Operating System and Arch

Ubuntu 20.04.4 LTS

### 🌐 Browser

Safari 15.3

### 🐋 Docker Version

Docker 20.10.14

**Comment by louislam** [comment]
Tested with Safari 15.3 on BrowserStack and cannot reproduce the issue.

![image](https://user-images.githubusercontent.com/1336778/162562710-257ae790-d352-4e7a-a531-d6cfbb7cdeb7.png)

**Comment by DJFraz** [comment]
I have confirmed it working again here too. Odd because I cleared cache and all the other basic steps to ensure the issue was present. Anyways, thanks for the quick response.
