### ISSUE TITLE
Uptime Kuma reporting fake downtimes.

### ISSUE THREAD

**Issue by Kriiiiiiiz** [louislam/uptime-kuma#1467]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

Idk exactly why my Uptime Kuma Install (latest version) it is reporting fake downtimes, the donwtime lasts 1min and then service is back up. I'm using a TCP port monitor that should check every 1 min.

I'm monitoring 2 different ports on same IP and the issue goes from one to another monitor.

### 🐻 Uptime-Kuma Version

1.13.2

### 💻 Operating System and Arch

Ubuntu 20.04

### 🌐 Browser

Safari

**Comment by pemassi** [comment]
I recommend that you might check your network environment first. Sometimes, TCP connection can be failed because of the network or local environment, even if the service is online.

**Comment by Computroniks** [comment]
What is your retry count set to?
![image](https://user-images.githubusercontent.com/67638596/162567298-1c05f2f9-4f06-4db6-b3b6-881f600b2005.png)

**Comment by Kriiiiiiiz** [comment]
> I recommend that you might check your network environment first. Sometimes, TCP connection can be failed because of the network or local environment, even if the service is online.

But what exactly should I check ? I assume something related to NAT

**Comment by Kriiiiiiiz** [comment]
> What is your retry count set to?
> ![image](https://user-images.githubusercontent.com/67638596/162567298-1c05f2f9-4f06-4db6-b3b6-881f600b2005.png)

It is set to 1

**Comment by Computroniks** [comment]
> But what exactly should I check ? I assume something related to NAT

I wouldn't have though that the issue would be related to NAT if other outgoing connections are working. It could be to do with a poor network connection. I would try increasing the retry count a bit and decreasing the retry interval to somewhere between 10 and 30 seconds (something less than the heartbeat interval to allow for all retrys to complete before then next heartbeat).

**Comment by rihards-simanovics** [comment]
Hi not sure if this is related but I've got a weird issue where a downtime for the last 24 hours is 0.2% but, in the graph, and event's no downtime is registered. My usual config is to check every 20 seconds and have 2 retries before the service is marked as down. Also, just to be clear, my server (VPS) is plenty powerful for this application to run well so I can rule this one out.
