### ISSUE TITLE
No Mattermost notification after update to 1.13.1

### ISSUE THREAD

**Issue by Dolo3000** [louislam/uptime-kuma#1468]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### Description

Hi,

i am using Uptime Kuma on a Raspberry device in docker.

Used docker container:

- uptime-kuma:1-alpine

After update from Version 1.11.4 to 1.13.1 the configured Mattermost notification seems
not to work anymore for downtimes etc.
- The Test notification from configuration menu works fine

### 👟 Reproduction steps

- Setup a Monitoring for a website
- Configure Mattermost notification (+ Test)
- Wait or cause a downtime for the website
- Downtime is tracked by Kuma Monitoring
- But no notification is send in Mattermost

The Mattermost notification is set as default.

### 👀 Expected behavior

- A notification in Mattermost when the monitored website has a downtime

### 😓 Actual Behavior

- But no notification is send in Mattermost

### 🐻 Uptime-Kuma Version

1.13.1

### 💻 Operating System and Arch

Debian 9.13 (ARM)

### 🌐 Browser

Firefox (does not really metter for this issue)

### 🐋 Docker Version

19.03.15, build 99e3ed8919 (ARM)

### 🟩 NodeJS Version

n/a (Docker container)

**Comment by louislam** [comment]
Just checked the last Mattermost pull request, and found that I missed @nietzscheanic's comment. The problem should be fixed in the next release.

https://github.com/louislam/uptime-kuma/pull/1298#issuecomment-1062858339

**Comment by Dolo3000** [comment]
> Just checked the last Mattermost pull request, and found that I missed @nietzscheanic's comment. The problem should be fixed in the next release.
> 
> [#1298 (comment)](https://github.com/louislam/uptime-kuma/pull/1298#issuecomment-1062858339)

Wow! Thanks a lot for the quick check and response!

Looking forward to test out next release!

Have a great weekend!

Best,
Dolo
