### ISSUE TITLE
after Update to 1.13.2, the DNS of the docker host isn't used for TCP pings

### ISSUE THREAD

**Issue by FaySmash** [louislam/uptime-kuma#1470]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### Description

After the Update to Version 1.13.2, the DNS set for the docker host isn't used inside uptime-kuma for TCP pings although the network mode is set to bridge. I use a local DNS Server with custom domain entries. 

### 👟 Reproduction steps

Lets assume I've added `test.example.com` as custom domain entry with the bind IP 10.0.0.100 (which hosts a Webserver on Port 80 and 8080).

When I add a ping Monitor for `test.example.com`, it works.

If I add a TCP Monitor for `test.example.com:80` it works too.

### 👀 Expected behavior

If I change it to `test.example.com:8080` it should work too.

### 😓 Actual Behavior

But if I change it to `test.example.com:8080` it throws an `connect EHOSTUNREACH 93.184.216.34:8080` error (where `93.184.216.34` is the public IP address of `example.com` ). So uptime-kuma no longer tries to use my local but some public DNS (but in my testing only for ports which aren't 80 or 443).

I fixed it by adding the IP of my local domain server as `docker run` argument: `--dns=10.0.0.254`

### 🐻 Uptime-Kuma Version

1.13.2

### 💻 Operating System and Arch

Raspbian GNU/Linux 11 (bullseye)

### 🌐 Browser

Waterfox G4.0.8

### 🐋 Docker Version

20.10.14, build a224086

**Comment by louislam** [comment]
Uptime Kuma is using this `tcp-ping` library for this. The library is pretty straightforward.
https://github.com/apaszke/tcp-ping/blob/master/ping.js

If `--dns=10.0.0.254` is working, I think It is usually a docker issue or a dns issue.

1. You can check the dns setting inside the running container.
```
docker exec -it uptime-kuma bash
cat /etc/resolv.conf
```

2. Check if `test.example.com` is having two A records at the same time: `93.184.216.34` and `10.0.0.100`

**Comment by FaySmash** [comment]
Thanks for the suggestions! The Issue probably wasn't the update but the container restart. Somehow the resolv.conf entry of my docker host changed from `10.0.0.254` to `10.0.0.254/24` which didn't work for the container. After changing it back and another container restart, it's working again. I'm sorry for waiting your time 😅
