### ISSUE TITLE
How to install Uptime Kuma on Replit

### ISSUE THREAD

**Issue by HOUSSAMATFI** [louislam/uptime-kuma#1472]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### Description

Peace be upon you. I have a problem with the **database**. Please help me. **Thank you**

### 👟 Reproduction steps

![31f2ac7d-aeea-4664-9db9-f07780e1b31b](https://user-images.githubusercontent.com/95652741/162727512-3317bc65-79db-444d-80ea-35ee25d0746a.png)

### 👀 Expected behavior

![31f2ac7d-aeea-4664-9db9-f07780e1b31b](https://user-images.githubusercontent.com/95652741/162727615-7df97712-a056-4dba-9615-e8f145267a76.png)

### 😓 Actual Behavior

![31f2ac7d-aeea-4664-9db9-f07780e1b31b](https://user-images.githubusercontent.com/95652741/162727645-2945197e-37ae-4df1-b932-96e51902ba1b.png)

### 🐻 Uptime-Kuma Version

V2

### 💻 Operating System and Arch

replit

### 🌐 Browser

Google Chrome

**Comment by louislam** [comment]
I changed to a better title, see if anyone could help.

However, VPS is always suggested.

**Comment by HOUSSAMATFI** [comment]
Ok Thank You , And Please Add Button sing up

**Comment by tarun7singh** [comment]
@HOUSSAMATFI 
I did some tweaking and found that with a couple of changes you can easily run the uptime kuma on replit.com. I'm not sure if any other functionality of uptime kuma will be impacted by shortcomings of repl from a full-fledged vps server.

Here's running screenshot of the repo on repl.com 
<img width="1438" alt="Screen Shot 2022-04-20 at 5 17 41 PM" src="https://user-images.githubusercontent.com/12068093/164324545-f3b4ab8e-9fb5-4977-9400-e3d1a34e33ab.png">

Please follow these steps to get it running on your end.
1. Create a new repl > Choose "Import from Github" button
2. Use the Repository URL (https://github.com/louislam/uptime-kuma) and import
3. Create new file in the base of repo named `.replit` with the following content
```
run="npm run setup && node server/server.js port=80"
language="nodejs"
```
4. Use the "run" button 
5. Use "open in new tab" button after the server starts up
