### ISSUE TITLE
Pause all notifications button

### ISSUE THREAD

**Issue by matthew-larner** [louislam/uptime-kuma#1475]
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

UI Feature

### 🔖 Feature description

Sometimes I get woken up in the middle of the night from notifications that don't need to be fixed straight away. It would be great to pause all notifications for a period of time.

### ✔️ Solution

Have a pause all notifications button. This button should pause notifications for a certain period of time e.g. 5 minutes/1 hour/1 day.

### ❓ Alternatives

Pausing each individual notification has 2 issues:
1. if multiple services are down, you will have to pause each one of them individually
2. you may forget that you have them paused. The pause all notifications button will have an option to pause for a certain amount of time.

### 📝 Additional Context

none

**Comment by Authorises** [comment]
Maybe a way to do it for specific monitors/tags aswell?

**Comment by Keyproco** [comment]
Pausing by a certain range of time would be a good idea, like a maintenance/quite mode using a calender with options like every DAY, WEEK, MONTH, also adding a label to specify the severity of the notification with conditions of which notification service to use, and if the failure duration is greater than a certain value you can send me an SMS for example for emergencies, like a threshold so some of them don't have to wake you up at 3AM.
I would also be happy to find more options to notify members by team or only for some users.

**Comment by Kasstoum** [comment]
Hi
I was looking for a maintenance mode.
I think this PR is a good response to your feature request ? https://github.com/louislam/uptime-kuma/pull/1213

**Comment by Furrypaw** [comment]
Could have used "pause all notifications button" right about now. So +1 to request.
