### ISSUE TITLE
Issue with import backup.json

### ISSUE THREAD

**Issue by Alexandre-Gliganic** [louislam/uptime-kuma#1478]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### Description

I export the backup file on my first server and I try to import this file to my new server. But I encounter an issue when I try that with all methods (Keep both, Skip existing, Overwrite), I've got this log: `cannot read property of undefined (reading 'length')`. I use this method a lot of time and it's the first time I've got problems.

The 2 servers run with the latest version of docker on Debian 11 with Kuma 1.14.0

### 👟 Reproduction steps

- Export Backup
- Import Backup 

### 👀 Expected behavior

It will import the backup.json without any issues.

### 😓 Actual Behavior

Got an issue with this log: `cannot read property of undefined (reading 'length')`

### 🐻 Uptime-Kuma Version

1.14.0

### 💻 Operating System and Arch

Debian 11 x86

### 🌐 Browser

Safari and Firefox

### 🐋 Docker Version

Docker 20.10.5

**Comment by egondadalt** [comment]
Same here

**Comment by jmros** [comment]
Same here:

Cannot read properties of undefined (reading 'length')

**Comment by trydovitch** [comment]
same here

**Comment by anniextra** [comment]
same here！

**Comment by chakflying** [comment]
Looks like the backup process is not updated to include proxies. In the meantime, you can fix this by opening the `backup.json` file, and add a new line between `version` and `notificationList`:
```json
{
    "version": "1.14.0",
    "proxyList": [],
    "notificationList": [
        ...
```
save this and now import should work.

**Comment by JohnRossZA** [comment]
Had the same problem, on 1.12.0. Updated to 1.14.0 and applied above fix in backup file. Thank you.

**Comment by trojan20161207** [comment]
thx，it's work!
