### ISSUE TITLE
custom port in url is ignored

### ISSUE THREAD

**Issue by srgvg** [louislam/uptime-kuma#148]
**Describe the bug**

**To Reproduce**
1. I configured an url with a custom port: `https://host.blah..net:6443`
2. The check yields the error `connect ECONNREFUSED 172.x.y..13:443`

**Expected behavior**
Check shoudl succeed, referencing the exact port `6443`

**Screenshots**
![20210803101520](https://user-images.githubusercontent.com/382239/127982118-0adcfff9-3731-4f26-9098-7977b0bec087.png)

**Desktop (please complete the following information):**
 - Uptime Kuma Version: 1.0.7
 - Using Docker?: Using container `louislam/uptime-kuma:1.0.7` on Kubernetes
 - OS: K3OS
 - Browser: firefox

**Comment by rezzorix** [comment]
I have just tried to replicate the error but all seems to be working fine.

Are you sure the port (in your case 6443) is reachable by uptime-kuma? 
Please check ingress firewall rules.

**Comment by srgvg** [comment]
I must admit it seems to be a strange issue. Another config where set that up (other host, other port) didn't have the issue.
I now just tried adding the same check a second time, and can't reproduce it again myself :-(
I may have filed this bug a bit too quick, my apologies.
On the other hand, as shown in the screenshot, there was a clear issue where the tested port (`443`) was different than the configured port (`6443`), so that remains some issue, I think?

**Comment by rezzorix** [comment]
Indeed. @louislam What is your thought?

**Comment by louislam** [comment]
My guess is that Uptime Kuma here is a bit confused you, because Uptime Kuma only shows the first down beat's error msg in consequence in the event list. 


You can hover the beat to see the actual error.
![image](https://user-images.githubusercontent.com/1336778/128001522-df652a62-e2d4-418f-bd6f-94eb292b91e8.png)

**Comment by louislam** [comment]
I am not familiar with K8s, but Uptime Kuma is a stateful application, the number of replicas should set to 1.

**Comment by srgvg** [comment]
Yes, I checked the beat too, and yes, it is deployed as a single pod.
The one thing I might have overlooked, is I initially forgot to put the 6443 port into it, and updated it right after. That might have caused the effect as seen in the screenshot.
But can't remember if that was the case.

**Comment by rezzorix** [comment]
Yeah as you and I cant reproduce this error, I guess what you described was the reason and this issue can be closed.

**Comment by louislam** [comment]
> Yeah as you and I cant reproduce this error, I guess what you described was the reason and this issue can be closed.

Agree, I close for now, free feel to re-open if you see the problem again.
