### ISSUE TITLE
Add Button Sign Up

### ISSUE THREAD

**Issue by HOUSSAMATFI** [louislam/uptime-kuma#1484]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### Description

Peace be upon you. Please add the Create account button. Thank you for your great efforts

### 👟 Reproduction steps

![unknown](https://user-images.githubusercontent.com/95652741/163005230-758a3164-874e-49fc-b775-0fe37ff863a3.png)

### 👀 Expected behavior

![unknown](https://user-images.githubusercontent.com/95652741/163005539-8c74f05e-8ccf-412c-abb8-edd3cb02abd3.png)

### 😓 Actual Behavior

![unknown](https://user-images.githubusercontent.com/95652741/163005487-cf3ea813-ed65-4d02-8b37-767b1c9bbc51.png)

### 🐻 Uptime-Kuma Version

V2

### 💻 Operating System and Arch

replit

### 🌐 Browser

Google Chrome

**Comment by louislam** [comment]
Replit is not an official way to use Uptime Kuma. Please read How to Install in the home page.
