### ISSUE TITLE
Ways to integrate external status pages?

### ISSUE THREAD

**Issue by JaneJeon** [louislam/uptime-kuma#1490]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

I'm wondering what the recommended way of integrating external status pages are - if there is any - into uptime kuma.

For example, with something like statuspage, you can "embed" status pages for external dependencies (e.g. AWS).

Right now, I "consume" such status pages by subscribing to their email and getting alerts, but I wonder if there's a way to do this natively. Inverse webhooks maybe? But how will you know when the status has been resolved? And what about status pages other than just up/down?

Love to hear the community's thoughts on this, and if anybody actually does this with their installations, what is the way they go about doing this. Thanks

### 🐻 Uptime-Kuma Version

N/A

### 💻 Operating System and Arch

N/A

### 🌐 Browser

N/A

**Comment by janbaykara** [comment]
One way I've done this is, for example with Stripe, by HTTP pinging their API once a minute with basic auth.

**Comment by JaneJeon** [comment]
Bump! Still no good solution for this

**Comment by JaneJeon** [comment]
:(

**Comment by janbaykara** [comment]
Would be pretty fantastic if one could just plug in APIs (or scrape the frontend) of prominent status page software.

**Comment by JaneJeon** [comment]
Hello - still relevant!

As I have tons of "external dependencies" (e.g. VPS provider, other "cloud services" that my stack relies on), being able to display *their* uptime (or status pages) is going to be pretty crucial.

**Comment by camilonova** [comment]
I support having this as a way to link external dependencies too. Would be great to track uptime from external services like email, infrastructure, payments, etc.

How others are doing it?

**Comment by CommanderStorm** [comment]
@JaneJeon 
This is being autoclosed as you chose the `help` Template.
If the cloud provider has a healthcheck, you an monitor it that way.
Otherwise I don't see what you mean by integrating other status pages.
Other websites may be monitored via the keyword monitor and an api or via keyword montoring the status page.

**Comment by camilonova** [comment]
Keyword monitor worked for me:

<img width="504" alt="CleanShot 2023-06-09 at 12 20 59@2x" src="https://github.com/louislam/uptime-kuma/assets/202559/fdab34c8-2527-4e8e-9728-151d366367cf">
