### ISSUE TITLE
I can't save a new monitor

### ISSUE THREAD

**Issue by Coll147** [louislam/uptime-kuma#1493]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### Description

Hello, it happens to me that it does not let me save the monitor that I want to create. I have 7 monitors created and I use docker.
![image](https://user-images.githubusercontent.com/91793263/163359418-22d35f4a-acd1-4b1e-b3c2-d0c66ab91efd.png)

### 👟 Reproduction steps

- Install uptime-kuma in docker
- Create 7 monitors

### 👀 Expected behavior

I don't know

### 😓 Actual Behavior

That i can't create new monitors.

### 🐻 Uptime-Kuma Version

1.14.0

### 💻 Operating System and Arch

Ubuntu 20.04

### 🌐 Browser

google chrome 100.0.4896.88 (Build oficial) (64 bits)

### 🐋 Docker Version

Docker version 20.10.14, build a224086

### 🟩 NodeJS Version

0

**Comment by Coll147** [comment]
Sorry it was an error in my browser

**Comment by Computroniks** [comment]
@Coll147 Could you perhaps give some details on the error in your browser and how you fixed it? It might come in useful in future if anyone else has the same issue.

**Comment by Coll147** [comment]
I just noticed that my computer was running a bit slow and sluggish. So I proceeded to restart it and it worked again. This is how I solved the error.
