### ISSUE TITLE
Publicly display the ping for the API response time on the status page

### ISSUE THREAD

**Issue by Bobby99as** [louislam/uptime-kuma#1495]
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

UI Feature

### 🔖 Feature description

Ability to publicly display the ping for the API response time on the status page

### ✔️ Solution

This would be useful to display that the API for the service that is being monitored is experiencing higher demand or could be experiencing a problem that isn't immediately causing downtime

**Comment by Computroniks** [comment]
This seems to be related to #1480

**Comment by Bobby99as** [comment]
> This seems to be related to #1480

Oh okay thanks for letting me know
