### ISSUE TITLE
如何用企业微信群部署预警？

### ISSUE THREAD

**Issue by qxaa169832** [louislam/uptime-kuma#1496]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

我用的docker部署，怎么进行配置？有大神能帮忙分享下流程嘛？

### 🐻 Uptime-Kuma Version

1.14.0

### 💻 Operating System and Arch

linux

### 🌐 Browser

google

**Comment by Computroniks** [comment]
I just translated this using Google translate incase anyone can help. As it is Google translate it probably isn't the best translation ever.

Title:  How to deploy early warning in enterprise WeChat group?  (Issue #1496)

📝 Describe your problem

How do I configure the docker deployment I use?  Can someone help share the process?

**Comment by louislam** [comment]
@LeslieLeung had implemented WeCom, I guess it is for 企业微信群.

Related pull request: https://github.com/louislam/uptime-kuma/pull/1095

**Comment by LeslieLeung** [comment]
Indeed WeCom is for 企业微信.

@qxaa169832 可以看一下企业微信的文档 https://work.weixin.qq.com/api/doc/90000/90136/91770

**Comment by qxaa169832** [comment]
> 事实上，WeCom 是为企业微信服务的。
> 
> @qxaa169832可以看一下企业微信的文档https://work.weixin.qq.com/api/doc/90000/90136/91770

文档没太看明白。。。或者有其他比较容易配置预警通知的方式嘛？

**Comment by qxaa169832** [comment]
> WeCom 是为企业微信服务的。
> 
> @qxaa169832可以看一下企业微信的文档https://work.weixin.qq.com/api/doc/90000/90136/91770

@LeslieLeung 文档没太看明白，或者有其他比较容易配置预警通知的方式嘛？

**Comment by LeslieLeung** [comment]
如果你需要使用企业微信作为通知方式，请在企业微信中创建群机器人，并记录其webhook url（详细操作方式见企业微信文档），在Uptime Kuma的设置->消息通知->设置通知，在消息类型中选择WeCom（即企业微信），`WeCom Bot Key` 填入上一步获取到的webhook url即可。

**Comment by xgdgsc** [comment]
注意填写的是key，不是整个url，这个还挺怪的，本来复制url是最快的
