### ISSUE TITLE
how to add bulk domain. like  i have 500 domain  website. add in 1min

### ISSUE THREAD

**Issue by linuxtoddler** [louislam/uptime-kuma#1498]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

 i have 500 domain  website. how to quickly add in kuma?
api?  but i did not find it .

### 🐻 Uptime-Kuma Version

1.14.0

### 💻 Operating System and Arch

ubuntu

### 🌐 Browser

chrome

### 🐋 Docker Version

dockor

### 🟩 NodeJS Version

14.18

**Comment by Computroniks** [comment]
This is related to #1457. Currently it has not been implemented but I will probably start implementing it sometime next week hopefully.
