### ISSUE TITLE
custom domain names for status pages not working

### ISSUE THREAD

**Issue by RobertRR11** [louislam/uptime-kuma#1505]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### Description

Adding a custom domain name to a status page changes nothing at all and still redirects to /status/[name]

### 👟 Reproduction steps

- open a status page and edit it
- add a custom domain name
- visit the custom domain
- be redirected to slug

### 👀 Expected behavior

To not be redirected to the slug like shown in #1415

### 😓 Actual Behavior

You get redirected to the status page slug.

### 🐻 Uptime-Kuma Version

1.14.0 and 1.15.0-beta.0 

### 💻 Operating System and Arch

Ubuntu 20.04.4 LTS x86_64

### 🌐 Browser

Brave 1.37.116 (Chromium 100.0.4896.127)

### 🟩 NodeJS Version

17.9.0

**Comment by louislam** [comment]
Just tested again. My instance is working.
https://status.kuma.pet
https://status2.kuma.pet
https://status.louislam.net

Is your input value like?
![image](https://user-images.githubusercontent.com/1336778/163725027-6ca8e87c-dc69-4a72-a11a-7bf5e88e9896.png)

**Comment by RobertRR11** [comment]
Yes it is.
![image](https://user-images.githubusercontent.com/57044042/163726384-a723aeff-4fae-4fa4-ac32-ed1038819f62.png)

**Comment by marcel-sch** [comment]
hi,

i have the same issue. but i use nginx as my reverse-proxy and not cloudflare like you did.

**Comment by marcel-sch** [comment]
> hi,
> 
> i have the same issue. but i use nginx as my reverse-proxy and not cloudflare like you did.

i found a solution, after adding
`proxy_set_header    Host            $host;`
to my nginx-config it is working as expected.

**Comment by louislam** [comment]
> > hi,
> > i have the same issue. but i use nginx as my reverse-proxy and not cloudflare like you did.
> 
> i found a solution, after adding `proxy_set_header Host $host;` to my nginx-config it is working as expected.

Oh no, I thought `Host` is always provided by reverse proxyies or browsers.

**Comment by marcel-sch** [comment]
> > > hi,
> > > i have the same issue. but i use nginx as my reverse-proxy and not cloudflare like you did.
> > 
> > 
> > i found a solution, after adding `proxy_set_header Host $host;` to my nginx-config it is working as expected.
> 
> Oh no, I thought `Host` is always provided by reverse proxyies or browsers.

it has to be defined because as i understand the value `proxy_set_header Host $proxy_host` is the default, found here [http://nginx.org/en/docs/http/ngx_http_proxy_module.html#proxy_set_header](url)

**Comment by RobertRR11** [comment]
> hi,
> 
> i have the same issue. but i use nginx as my reverse-proxy and not cloudflare like you did.

Actually I am using Apache.

**Comment by louislam** [comment]
> > hi,
> > i have the same issue. but i use nginx as my reverse-proxy and not cloudflare like you did.
> 
> Actually I am using Apache.

You should enable this:

ProxyPreserveHost On

https://stackoverflow.com/questions/9316683/apache-host-header-proxy

**Comment by RobertRR11** [comment]
It worked, thank you very much.
