### ISSUE TITLE
[Help] Need help with CNAME / Reverse Proxy configuration

### ISSUE THREAD

**Issue by VP-EN** [louislam/uptime-kuma#1507]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

**Help needed!**
I need help figuring out how to setup the status pages.

I setup a reverse proxy in nginx for the Uptime-Kuma dashboard. I set it to use the subdomain `uptimekuma.example.com` which is a reverse proxy for the dashboard url `XX.XX.XX.XX:3001`.
I tried to read the status page wiki page about setting up CNAMES, but I'm not great with DNS setups in general :(. So any help would be appreciated.

Does this look right?
**My NGINX conf file:** `uptimekuma.example.com.conf`
```
https://paste.ec/paste/u-l7x82G#UdWnhm-b4oYbGhLCZPWPg7z7gKtqZwYVyBiAXv4RYiY
```

I can access `uptimekuma.example.com` just fine, and everything works fine in there. Certbot also worked fine getting SSL certificate(s).

**My DNS records:**
https://shx.is/5tKVoAX_O.png

OR:
```
uptimekuma    IN    A       88.88.88.88
status        IN    CNAME   uptimekuma.example.com.
up            IN    CNAME   uptimekuma.example.com.
```

**My status page dashboard:**
https://shx.is/5tKWgaE0S.png

When I try to access `status.example.com` or `up.example.com` it doesn't work.
It just gives me a failed to load page :(

### 🐻 Uptime-Kuma Version

1.14.0 

### 💻 Operating System and Arch

Ubuntu 20.04.4 LTS || Kernel: 5.13.0-39-generic

### 🌐 Browser

LibreWolf 99.0-1

### 🐋 Docker Version

20.10.14

**Comment by tbsbckr** [comment]
Hi! Did you specify the other server names in a nginx config? If not, requests will be discarded if there is no default nginx config available.

You could try to add status.example.com to the server_names list in your nginx conf (separated by a space) and access it via HTTPS - of course the certificate won't be valid so you have to run certbot again on your nginx.

**Comment by VP-EN** [comment]
> Hi! Did you specify the other server names in a nginx config? If not, requests will be discarded if there is no default nginx config available.
> 
> You could try to add status.example.com to the server_names list in your nginx conf (separated by a space) and access it via HTTPS - of course the certificate won't be valid so you have to run certbot again on your nginx.

Ah! That was it 👍 Can't believe I missed that.
Thanks a lot for the quick reply ❤️
