### ISSUE TITLE
How can I monit a docker container?

### ISSUE THREAD

**Issue by ItzMiracleOwO** [louislam/uptime-kuma#1508]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

Can I somehow monit the uptime of a docker container? thanks!

### 🐻 Uptime-Kuma Version

1.14.0

### 💻 Operating System and Arch

Synology DSM 6

### 🌐 Browser

Opera 85.0.4341.60

### 🐋 Docker Version

Docker version 20.10.3, build b35e731

### 🟩 NodeJS Version

-

**Comment by AnnAngela** [comment]
For now, there is no specify way to monit a docker container.

But if the docker container runs a website or other things, uptime-kuma can monit that website.

**Comment by ItzMiracleOwO** [comment]
Hi!
Ive firgured out a way to monit the container with a node.js app. Here is the simple code:
```js
const http = require('http');

console.log("Started monitor!");

async function send() {
    try {
        await http.request({
            host: "uptime.miracleds.xyz",
            port: 80,
            path: encodeURI('/api/push/<YOUR MONITOR API KEY>?msg=200 - OK&ping=0'),
            method: 'GET'
        }).end();
        console.log("Successfully sent data to uptime kuma!")
    } catch (e) {
        console.log(e)
    }

}

setInterval(send, 30000);
```
By using the PUSH methos, and <YOUR MONITOR API KEY> is the key from the url, and the code will send a request every 30 seconds to make uptime kuma know its online! I am running it using `pm2 start monit.js`
Thank you!
