### ISSUE TITLE
uptime-kuma reset password err

### ISSUE THREAD

**Issue by xdeng** [louislam/uptime-kuma#1510]
### ⚠️ Please verify that this bug has NOT been raised before.

- [x] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

There was an error resetting my password 
```
docker exec -it uptime-kuma npm run reset-password

> uptime-kuma@1.14.0 reset-password
> node extra/reset-password.js

== Uptime Kuma Reset Password Tool ==
Connecting the database
Data Dir: ./data/
Found user: admin
New Password: 123456
Confirm New Password: 123456
Error: user.resetPassword is not a function
Closing the database
SQLite closed
Finished.
```

### 🐻 Uptime-Kuma Version

1.14.0

### 💻 Operating System and Arch

Debian 10

### 🌐 Browser

Google Chrome

### 🐋 Docker Version

Docker version 20.10.12, build e91ed57

### 🟩 NodeJS Version

v16.14.2

**Comment by louislam** [comment]
Confirmed it is a bug.

**Comment by louislam** [comment]
Workaround before the fix release:

1. Stop your 1.14.0 container
2. Create another 1.13.2 container
3. Change password using 1.13.2 container
4. Delete 1.13.2 container
5. Start 1.14.0 container

**Comment by xdeng** [comment]
@louislam 3Q
