### ISSUE TITLE
Monitor test function

### ISSUE THREAD

**Issue by casperklein** [louislam/uptime-kuma#1514]
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

UI Feature

### 🔖 Feature description

Recently, I've added some monitors in batch.

Some of them did not work at first, because the expected HTTP code or redirect count was wrong - no big deal. After adding these monitors, they immediately failed. Then I had to edit and fix them. Then I deleted the corresponding events/heartbeats to have a clean start.

It would be nice to be able to test a monitor before saving.

### ✔️ Solution

A test button next to the save button.

### ❓ Alternatives

Getting the necessary information (redirect count etc) upfront. But when adding many monitors in batch, trial & error & fixing is probably faster 😉

**Comment by CommanderStorm** [comment]
@casperklein
We are consolidating duplicate issues a bit to make issue management easier.
I think, we should track this issue in #2725 as there is no functional difference and said issue is more popular + had a more in-depth discussion.
⇒ I am going to close this as a duplicate (despite this being the earlier one ^^)
