### ISSUE TITLE
whats the api page

### ISSUE THREAD

**Issue by duckytutorials** [louislam/uptime-kuma#1517]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

I  need api page for uptime kuma

### 🐻 Uptime-Kuma Version

1.14.0

### 💻 Operating System and Arch

20.04

### 🌐 Browser

Chrome

### 🟩 NodeJS Version

17

**Comment by Computroniks** [comment]
I don't think that there currently is a public api. You can see #118 for more details about the ongoing work to create a more public api
