### ISSUE TITLE
Can't import 1.13.1 backup - Cannot read properties of undefined (reading 'length')

### ISSUE THREAD

**Issue by RFlintstone** [louislam/uptime-kuma#1518]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

I can't seem to import a 1.13.1 backup to version uptime kuma 1.14.0. Is this a bug, or is this normal?

### 🐻 Uptime-Kuma Version

1.14.0

### 💻 Operating System and Arch

Ubuntu 20.04.4 LTS x86_64

### 🌐 Browser

Brave

### 🐋 Docker Version

Docker version 20.10.14, build a224086

### 🟩 NodeJS Version

v16.14.2

**Comment by louislam** [comment]
Read https://github.com/louislam/uptime-kuma/issues/1478
