### ISSUE TITLE
Wanted to create email alerts from uptimekuma monitors to email

### ISSUE THREAD

**Issue by sjreddy445** [louislam/uptime-kuma#1521]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

facing issue whe i ma configuring email alerts from uptimekuma monitors to email id.

### 🐻 Uptime-Kuma Version

1.13.1

### 💻 Operating System and Arch

ubuntu 20.04 x86

### 🌐 Browser

google chrome

### 🐋 Docker Version

20.10.7

**Comment by louislam** [comment]
Please try to provide more info, so other people can help you.
