### ISSUE TITLE
UDP Ping 

### ISSUE THREAD

**Issue by Alfedov** [louislam/uptime-kuma#1522]
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

New Monitor

### 🔖 Feature description

I suggest adding a udp ping monitor. We are using the GTA Sandres game, and we want to ping it. There is port 7777, and from the available monitors we cannot check this port.

### ✔️ Solution

Add udp ping

**Comment by louislam** [comment]
Please read #9
