### ISSUE TITLE
I want to create a new docker image of project

### ISSUE THREAD

**Issue by sm0w0ms** [louislam/uptime-kuma#1526]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

So initially my main problem was to bring to kuma status UI to my dashboard by using iframs.
To do that I commented this
on line 98: // const disableFrameSameOrigin = !!process.env.UPTIME_KUMA_DISABLE_FRAME_SAMEORIGIN || args["disable-frame-sameorigin"] || false;
====================AND=====================
on line 129:
// app.use(function (req, res, next) {
//     if (!disableFrameSameOrigin) {
//         res.setHeader("X-Frame-Options", "SAMEORIGIN");
//     }
//     res.removeHeader("X-Powered-By");
//     next();
// });

after this the iframe was working, but now to deploy the project I have to create docker image but it was not working
So I want to create a docker image with this changes please help me.

### 🐻 Uptime-Kuma Version

1.14.1

### 💻 Operating System and Arch

Ubuntu 20

### 🌐 Browser

Chrome

### 🐋 Docker Version

20.10.14

### 🟩 NodeJS Version

14.18.3

**Comment by jordanbertasso** [comment]
You should just be able to run the standard docker image with the `UPTIME_KUMA_DISABLE_FRAME_SAMEORIGIN=true`.

Example:
```
docker run -d \
    --restart=always \
    -p 3001:3001 \
    -v uptime-kuma:/app/data \
    --name uptime-kuma \
    -e "UPTIME_KUMA_DISABLE_FRAME_SAMEORIGIN=true" \
    louislam/uptime-kuma:1
```

**Comment by sm0w0ms** [comment]
Thanks for helping
