### ISSUE TITLE
Updating Uptime Kuma 1.13.1 Docker install does nothing.

### ISSUE THREAD

**Issue by compgeniuses** [louislam/uptime-kuma#1528]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

I have been trying to update my current installation instance of Uptime Kuma using the below command, but the version is not updated, it remains on the same version as initial. what could be error. is the Docker version also updated to the current release of uptime-kuma

```
docker pull louislam/uptime-kuma:1
docker stop uptime-kuma
docker rm uptime-kuma
docker run -d --restart=always -p 4381:3001 -v /opt/uptime-kuma:/app/data --name uptime-kuma louislam/uptime-kuma
```

### 🐻 Uptime-Kuma Version

1.13.1

### 💻 Operating System and Arch

Centos 7

### 🌐 Browser

Chrome

### 🐋 Docker Version

19.03.8

### 🟩 NodeJS Version

16.14.1

**Comment by jordanbertasso** [comment]
You need to either pull the `latest` tag or run the image that you just pulled by specifying the `1` tag.

i.e.
```
docker run -d --restart=always -p 4381:3001 -v /opt/uptime-kuma:/app/data --name uptime-kuma louislam/uptime-kuma:1
```

**Comment by compgeniuses** [comment]
Thank you very much @jordanbertasso i don't know how i missed that, yeah, it worked and now is latest version. 1.14.1
