### ISSUE TITLE
Request support for reverse proxy under subfolder

### ISSUE THREAD

**Issue by xorguy** [louislam/uptime-kuma#153]
Add support to host the application under a subfolder with reverse proxy, like:
https://mydomain.xyz/kuma

Setting as subdomain works like a charm but it will be very handy to support for subfolder, maybe an environmental variable set at Docker so the app use that to be able to load all the resources under the subfolder path.

Tried a few settings with Caddy v2 and there is no way to make it work in subfolder.

**Comment by louislam** [comment]
duplicate with #147
