### ISSUE TITLE
Telegram notification fail to send alert with error "Cannot read properties of undefined (reading 'data')"

### ISSUE THREAD

**Issue by a2940uw** [louislam/uptime-kuma#1532]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

Hi, I have to setup Telegram notification and fill the required Bot token and Chat ID correctly, but the Test was fail and prompted "Cannot read properties of undefined (reading 'data'), my network require to use proxy for internet access, the uptime-kuma hosts already have proxy setting and internet access is ok, I don't know this error is related to internet access or other issue.

### 🐻 Uptime-Kuma Version

1.14.0

### 💻 Operating System and Arch

Raspberry Pi OS 11 (bullseye)

### 🌐 Browser

Chrome

### 🐋 Docker Version

Docker version 20.10.14, build a224086

**Comment by louislam** [comment]
Proxy is not support for notifications.

**Comment by a2940uw** [comment]
> Proxy is not support for notifications.

Hi Louis, Thank you for your reply, it is possible to apply the proxy setting in the notification ?

**Comment by thmarti** [comment]
See #616

**Comment by screencomuser** [comment]
I am seeing this error in 1.21.0 - both notifications and test.

Tried to recreate using a standalone script and the only way to get this exception is to have some error in the try/catch that doesn't set a response property

```javascript
const axios = require("axios");

async function send(telegramBotToken) {
  let okMsg = "Sent Successfully.";

  try {
    let params = {
      chat_id: '12345678',
      text: 'Test message',
      disable_notification: false,
      protect_content: false,
    };

    await axios.get(`https://api.telegram.org/bot${telegramBotToken}/sendMessage`, {
      params: params,
    });
    return okMsg;

  } catch (error) {
    let msg = (error.response.data.description) ? error.response.data.description : "Error without description";
    throw new Error(msg);
  }
}

(async () => {
  send('12345678900:token-characters');
})();
```

When I remove the line `const axios = require("axios");` I get the following error, which leads me to believe a non-axios error is being thrown

```text
TypeError: Cannot read properties of undefined (reading 'data')
    at send (/home/workspace/temp/telegram/test.js:20:31)
    at /home/workspace/temp/telegram/test.js:26:3
    at Object.<anonymous> (/home/workspace/temp/telegram/test.js:27:3)
    at Module._compile (node:internal/modules/cjs/loader:1254:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
    at Module.load (node:internal/modules/cjs/loader:1117:32)
    at Module._load (node:internal/modules/cjs/loader:958:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:23:47
```

A fix could be to check if the exception has a response property
