### ISSUE TITLE
Impossible to save status page: Invalid array

### ISSUE THREAD

**Issue by Starfight** [louislam/uptime-kuma#1537]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### Description

After status page creation, I cannot save my modification and error "Invalid Array" appears. 
But in browser console, I see in websocket domainNameList is an array:

```
["statusPageList",{"1":{"id":1,"slug":"services","title":"Services","description":null,"icon":"/icon.svg","theme":"dark","published":true,"showTags":false,"domainNameList":[]}}]
```

Debugging myself, I print domainNameList in error and value is `undefined`. 

### 👟 Reproduction steps

Create Status page with arbitrary name
Click on Save button.

### 👀 Expected behavior

Status page is saved.

### 😓 Actual Behavior

Error Invalid Array.

### 🐻 Uptime-Kuma Version

1.14.1

### 💻 Operating System and Arch

Debian 10

### 🌐 Browser

Firefox 99.0.1

### 🟩 NodeJS Version

14

### 📝 Relevant log output

```shell
Error: Invalid array
    at Proxy.updateDomainNameList (/var/www/uptime-kuma/server/model/status_page.js:36:19)
    at Socket.<anonymous> (/var/www/uptime-kuma/server/socket-handlers/status-page-socket-handler.js:162:30)
```

**Comment by louislam** [comment]
Is it always reproducible in your side?

**Comment by nicon-dev** [comment]
same issue. You can even check it on the demo page

**Comment by louislam** [comment]
> same issue. You can even check it on the demo page

Thanks, I forgot to run `npm run download-dist` in the demo site.

I think it is similar issue, please follow the update guide.
https://github.com/louislam/uptime-kuma/wiki/%F0%9F%86%99-How-to-Update

**Comment by Starfight** [comment]
Work perfectly. Thanks
