### ISSUE TITLE
Fav Icon color alert status

### ISSUE THREAD

**Issue by bigsk1** [louislam/uptime-kuma#1540]
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

UI Feature

### 🔖 Feature description

I have many browser tabs open during the day. One of those is uptime kuma, I was thinking how nice it would be to look up at the tab with favicon and if any service was down it would turn red instead of green. 

Once all the services are up again turn back to green. Just a quick visual to know all it ok or not. I find myself actually opening the browser page just to take a look and then moving on to something else. 

I have no clue how this could be done just tossing a feature idea out there. If this has been brought up already sorry. Thank you!

### ✔️ Solution

Once a service ( any service out of all that are enabled ) goes down the favicon turns RED, maybe even start blicking. Once all is resumed and back to normal it goes back to solid green. 

### ❓ Alternatives

page refreshes from noticing a service is down and another H1 name is displayed. Instead of "Uptime Kuma" it could say "Uptime Kuma Down" or "Downtime Kuma"

If possible have a enable / disable button for this feature in settings.

**Comment by MarcHagen** [comment]
Can confirm it is working in latest versions (1.14.0+)
![image](https://user-images.githubusercontent.com/980978/164972287-30d38c68-d526-4586-9948-eb5002ea7144.png)
