### ISSUE TITLE
Security policy not up to date

### ISSUE THREAD

**Issue by mathiskir** [louislam/uptime-kuma#1545]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### Description

The security policy isn't up to date. The only supported version is 1.9.X if you read that policy.

### 👟 Reproduction steps

-

### 👀 Expected behavior

-

### 😓 Actual Behavior

-

### 🐻 Uptime-Kuma Version

-

### 💻 Operating System and Arch

-

### 🌐 Browser

-

**Comment by louislam** [comment]
https://github.com/louislam/uptime-kuma/blob/master/SECURITY.md

As all 1.x.x are actually upgradable at the moment, I also changed to a better description. So I don't need to update this file every time.
