### ISSUE TITLE
Request adaptation to vercel

### ISSUE THREAD

**Issue by muyangplus** [louislam/uptime-kuma#1546]
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

Other

### 🔖 Feature description

We request that this project be adapted to vercel one-click deployment, which can greatly reduce the cost of use.

### ✔️ Solution

One-click deployment using vercel.

**Comment by hexaaagon** [comment]
is there any update about uptime kuma w/ vercel?

**Comment by CommanderStorm** [comment]
Please refer to our [istalation instructions](https://github.com/louislam/uptime-kuma/wiki/%F0%9F%94%A7-How-to-Install) => no

Currently, nobody has explored what requirements vercel has.
I am somewhat uncertain that our architecture would work, as we don't support serverless for architectural reasons. See #3026 for the amount of work necessary.
 
Here is our [contribution guide](https://github.com/louislam/uptime-kuma/blob/c9fe6b5d0166f66a9837f489aa453fb128ce53db/CONTRIBUTING.md) ^^

**Comment by CommanderStorm** [comment]
According to https://vercel.com/guides/do-vercel-serverless-functions-support-websocket-connections the limits on execution time and how we would need to restructure the socket.io communication is very substantial.

Secondly, we need a serverto run cleanup and checks consistently which seems not trivial in vercel.

Thirdly, only external MariaDB would be a viable database as SQLite3 is not supported: https://vercel.com/guides/is-sqlite-supported-in-vercel

Given the effort required, I am classifying this as out of scope.
