### ISSUE TITLE
请问支持api吗，例如api增删改查一些功能

### ISSUE THREAD

**Issue by waxi-i** [louislam/uptime-kuma#1547]
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

API

### 🔖 Feature description

请问支持api吗，想通过api接口增删改查一些功能

### ✔️ Solution

请问支持api吗，想通过api接口增删改查一些功能

**Comment by mathiskir** [comment]
目前还没有公开的api来做这些事情，尽管它正在计划中。#118
对于未来的问题，请使用翻译，以便每个人都能轻松地帮助你。
(There is no publicly available api to do this yet, although it is being planned. #118
For future questions, please use a [translator](www.deepl.com) so that everyone can easily help you.)
