### ISSUE TITLE
Error during import backup

### ISSUE THREAD

**Issue by tomsteenbakkers** [louislam/uptime-kuma#1549]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### Description

I have installed Uptime Kuma on a Raspberry Pi Zero 2 using docker. This works well but when I save a new monitor it takes a long time and most of the time resulting in a error (something about a pool). So, I created a backup and installed a version of Uptime Kuma without Docker but on the same Raspberry Pi Zero 2.

First impression is that is is very fast. But, when I want to restore the backup I get an error: 
`Cannot read properties of undefined (reading "length")`

Any idea what this is. I have 36 monitors running so adding them to the new system will take me a while.

### 👟 Reproduction steps

Doing a restore in the UI

### 👀 Expected behavior

That the Restore will work with a backup created on a Docker based Uptime Kuma

### 😓 Actual Behavior

An error during restore

### 🐻 Uptime-Kuma Version

14.1.1 

### 💻 Operating System and Arch

Bullseye 64 bits

### 🌐 Browser

Safari

### 🟩 NodeJS Version

16.14.2

**Comment by mathiskir** [comment]
Read #1478
