### ISSUE TITLE
apdex : satisfaying response time

### ISSUE THREAD

**Issue by melvinlemoine** [louislam/uptime-kuma#1551]
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

Other

### 🔖 Feature description

Add the possibility to add the apdex for each monitor : set the satisfaying response time.

### ✔️ Solution

Possibility to set a satisfying response time for each monitor (apdex). If the apdex is for exemple higher than 500ms, the monitor is displayed with a different color or special icon.

**Comment by Computroniks** [comment]
This could be a good feature to have. Maybe it is because I don't entirely undestand how we would get the tollerating samples or frustrated samples from just one monitor. Perhaps this would be something that would be across all monitors. Again, this could be me just not entirely understanding this article https://en.wikipedia.org/wiki/Apdex

**Comment by melvinlemoine** [comment]
> This could be a good feature to have. Maybe it is because I don't entirely undestand how we would get the tollerating samples or frustrated samples from just one monitor. Perhaps this would be something that would be across all monitors. Again, this could be me just not entirely understanding this article https://en.wikipedia.org/wiki/Apdex

The process is simple : I have a monitor "My personal website", I set the satisfaying response time to "500ms". If the response time average is under 500ms, it's green, if it's higher, it's orange/red. This feature requires a new information field on each monitor.

**Comment by Computroniks** [comment]
Ahh, ok. It was me just misunderstanding the article. I though that we would be taking an average over all to get the apdex score using the formula 
![image](https://user-images.githubusercontent.com/67638596/166167765-2af4f7ef-208c-4797-ac65-7a7b2b4c3a1d.png)
(source https://en.wikipedia.org/wiki/Apdex).
This makes slightly more sense

**Comment by CommanderStorm** [comment]
@melvinlemoine
We are consolidating duplicate issues a bit to make issue management easier.
I think, we should track this issue in https://github.com/louislam/uptime-kuma/issues/1813 as there is no functional difference (maybe just small naming differences apdex vs slow, but nothing that would require a different issue imo)
⇒ I am going to close this as a duplicate.
