### ISSUE TITLE
SSL reminder

### ISSUE THREAD

**Issue by melvinlemoine** [louislam/uptime-kuma#1552]
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

UI Feature

### 🔖 Feature description

Have a reminder to renew the SSL certificate of monitors : 14 days, 7 days, 3 days, 1 day...

### ✔️ Solution

Actually, I have the days left for a certificate but nothing tell me "Hey, in 14 days, you need renew your certificate". 
Have a reminder to renew the SSL certificate of monitors : 14 days, 7 days, 3 days, 1 day...
Maybe with a little SSL lock icon on the monitor with the number of days remaining under 14 days ?

**Comment by HolgerAusB** [comment]
That would be very great! I use Lets Encrypt with a wildcard domain. That means, no automatic renewal possible. So a warning 30 days before would be lovely. Should send a push-message via one of the supprted services, sometime between 9am and noon (configurable).

**Comment by acki** [comment]
+1

**Comment by waxi-i** [comment]
+1

**Comment by iamheru** [comment]
+1

**Comment by chakflying** [comment]
Implemented in #781 and #1641.

**Comment by ansred** [comment]
Would be great to extend the feature to do a POST request as @HolgerAusB mentioned and maybe send a specific notification in POST with body so it can trigger the certificate renewal and other flows.

**Comment by CommanderStorm** [comment]
> Would be great to extend the feature to do a POST request as @HolgerAusB mentioned and maybe send a specific notification in POST with body so it can trigger the certificate renewal and other flows.

Please see the webhook notification type

**Comment by CommanderStorm** [comment]
@melvinlemoine
This issue seems to be implemented, but it appears that we have forgotten to link this issue ⇒ this issue has become an immortal zombie

Could you close this issue? (only you or Louis can do so)
