### ISSUE TITLE
How to use "Domain Names"

### ISSUE THREAD

**Issue by chredeur0** [louislam/uptime-kuma#1555]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

Hello,

I can't use this: 

![image](https://user-images.githubusercontent.com/50155089/164990866-d04e0288-ee6e-4a26-a99b-b8c8c695f3fd.png)

Can you help me?

### 🐻 Uptime-Kuma Version

1.15.0

### 💻 Operating System and Arch

Ubuntu 20.04 x86

### 🌐 Browser

Google Chrome 100

**Comment by Computroniks** [comment]
These are for when you want to use a custom domain to access your status page. 
Example:
Your Uptime Kuma instance is on `uptime.example.com`
You have a status page with the slug `main`
Normally you would access `main` by going to `uptime.example.com/status/main`. Now, you don't want your user to access it like this, instead you want to access it through it's own domain e.g `status.example.com`. In this case you would add `status.example.com` to the domain section and add a `CNAME` record in the domain DNS server. For more details on this see https://en.wikipedia.org/wiki/CNAME_record

**Comment by chredeur0** [comment]
I did everything right but I get the following error:
![image](https://user-images.githubusercontent.com/50155089/164993757-3edf4231-3505-47d4-9b4f-6c2263173546.png)

**Comment by chredeur0** [comment]
> These are for when you want to use a custom domain to access your status page. Example: Your Uptime Kuma instance is on `uptime.example.com` You have a status page with the slug `main` Normally you would access `main` by going to `uptime.example.com/status/main`. Now, you don't want your user to access it like this, instead you want to access it through it's own domain e.g `status.example.com`. In this case you would add `status.example.com` to the domain section and add a `CNAME` record in the domain DNS server. For more details on this see https://en.wikipedia.org/wiki/CNAME_record

I did everything right but I get the following error:
![image](https://user-images.githubusercontent.com/50155089/164993770-c0aad90f-6612-4b2a-b68f-c36b3734753c.png)

**Comment by Computroniks** [comment]
Are you using a reverse proxy? That looks like an nginx error page. Uptime Kuma doesn't use nginx in any way.

**Comment by chredeur0** [comment]
> Are you using a reverse proxy? That looks like an nginx error page. Uptime Kuma doesn't use nginx in any way.

Yes

**Comment by Computroniks** [comment]
Ok, in which case, you need to ensure that nginx is passing the status page domain as well as the original domain to the uptime instance

**Comment by chredeur0** [comment]
> Ok, in which case, you need to ensure that nginx is passing the status page domain as well as the original domain to the uptime instance

I don't think I have it all figured out, but my current nginx configuration looks like this:
```
server {
  listen 443 ssl http2;
  charset utf-8;
  server_name servers.domain.com;
  
  ssl_certificate /etc/letsencrypt/live/servers.domain.com/fullchain.pem;
  ssl_certificate_key /etc/letsencrypt/live/servers.domain.com/privkey.pem;
  
  location / {
    proxy_set_header   X-Real-IP $remote_addr;
    proxy_set_header   X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header Host $host;
    proxy_pass         http://localhost:3001;
    proxy_http_version 1.1;
    proxy_set_header   Upgrade $http_upgrade;
    proxy_set_header   Connection "upgrade";
  }
}
```

**Comment by Computroniks** [comment]
I am no expert in nginx, but I think that you need to add your status page domain to the server_name line seperated from servers.example.com by a space. E.g
```
server {
  listen 443 ssl http2;
  charset utf-8;
  server_name servers.domain.com statuspage.example.com;
  
  ssl_certificate /etc/letsencrypt/live/servers.domain.com/fullchain.pem;
  ssl_certificate_key /etc/letsencrypt/live/servers.domain.com/privkey.pem;
  
  location / {
    proxy_set_header   X-Real-IP $remote_addr;
    proxy_set_header   X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header Host $host;
    proxy_pass         http://localhost:3001;
    proxy_http_version 1.1;
    proxy_set_header   Upgrade $http_upgrade;
    proxy_set_header   Connection "upgrade";
  }
}
```

**Comment by chredeur0** [comment]
> I am no expert in nginx, but I think that you need to add your status page domain to the server_name line seperated from servers.example.com by a space. E.g
> 
> ```
> server {
>   listen 443 ssl http2;
>   charset utf-8;
>   server_name servers.domain.com statuspage.example.com;
>   
>   ssl_certificate /etc/letsencrypt/live/servers.domain.com/fullchain.pem;
>   ssl_certificate_key /etc/letsencrypt/live/servers.domain.com/privkey.pem;
>   
>   location / {
>     proxy_set_header   X-Real-IP $remote_addr;
>     proxy_set_header   X-Forwarded-For $proxy_add_x_forwarded_for;
>     proxy_set_header Host $host;
>     proxy_pass         http://localhost:3001;
>     proxy_http_version 1.1;
>     proxy_set_header   Upgrade $http_upgrade;
>     proxy_set_header   Connection "upgrade";
>   }
> }
> ```

its working thank you !

**Comment by NeekoGta** [comment]
Hi,

If I may answer.
I'm also having difficulties with the configuration of my domain names (Apache).

_Should I recreate an issue?_

I have a domain name managed by Cloudflare (**my-domain.com**).
I have a private server (**1.2.3.4**) with Apache and Uptime-Kuma.

I have **uptime.my-domain.com** configured like this :

```
<VirtualHost *:443>
    ServerName uptime.my-domain.com
    ServerAlias www.uptime.my-domain.com
 
    ErrorLog ${APACHE_LOG_DIR}/error.log
    CustomLog ${APACHE_LOG_DIR}/access.log combined

    SSLEngine on
    SSLCertificateFile /etc/cloudflare/my-domain.com.pem # Generated from Cloudflare
    SSLCertificateKeyFile /etc/cloudflare/my-domain.com.key # Generated from Cloudflare

    Protocols h2 http/1.1
    ProxyPass / http://localhost:3001/
    RewriteEngine on
    RewriteCond %{HTTP:Upgrade} websocket [NC]
    RewriteCond %{HTTP:Connection} upgrade [NC]
    RewriteRule ^/?(.*) "ws://localhost:3001/$1" [P,L]
</VirtualHost>
```

I have a status page created accessible by default at this address : **https://uptime.my-domain.com/status/default**

But I want to remove this **/status/default** for public.
So I added **status.my-domain.com** to the "Domain names" in the settings.

**status.my-domain.com** is configured like this :

```
<VirtualHost *:443>
    ServerName status.my-domain.com
    ServerAlias www.status.my-domain.com
 
    ErrorLog ${APACHE_LOG_DIR}/error.log
    CustomLog ${APACHE_LOG_DIR}/access.log combined

    SSLEngine on
    SSLCertificateFile /etc/cloudflare/my-domain.com.pem # Generated from Cloudflare
    SSLCertificateKeyFile /etc/cloudflare/my-domain.com.key # Generated from Cloudflare

    Protocols h2 http/1.1
    ProxyPass / http://localhost:3001/
    RewriteEngine on
    RewriteCond %{HTTP:Upgrade} websocket [NC]
    RewriteCond %{HTTP:Connection} upgrade [NC]
    RewriteRule ^/?(.*) "ws://localhost:3001/$1" [P,L]
</VirtualHost>
```

But as soon as we access to **status.my-domain.com** we are redirected to **status.my-domain.com/status/default**

Did I forget something?

Thank you 😃
