### ISSUE TITLE
MQTT does not accept scheme in frontend

### ISSUE THREAD

**Issue by karmanyaahm** [louislam/uptime-kuma#1557]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### Description

The backend for MQTT lets the hostname include a scheme like mqtt:// or mqtts://, but the frontend regex doesn't allow for a scheme. When I inspect element and remove the regex, everything works fine for my mqtts:// monitor.

https://github.com/louislam/uptime-kuma/blob/f8f19d8dc5cd668665f4a4a6d3b46782fe556383/src/pages/EditMonitor.vue#L76

https://github.com/louislam/uptime-kuma/blob/f8f19d8dc5cd668665f4a4a6d3b46782fe556383/server/util-server.js#L97-L99

### 👟 Reproduction steps

Create a new mqtt monitor with a secure server, mqtts://yourserver.com, 

### 👀 Expected behavior

MQTT has a URL field not a hostname field, that allows mqtt:// and mqtts://

### 😓 Actual Behavior

The browser won't let you submit mqtts://yourserver.com. If you remove the 'pattern' from the html in inspect element, everything works perfectly.

### 🐻 Uptime-Kuma Version

1.15.0

### 💻 Operating System and Arch

n/a

### 🌐 Browser

Firefox 96.0b8

Thanks for making Uptime Kuma, the recent MQTT addition is really helpful to my setup.

**Comment by gaby** [comment]
@karmanyaahm  I think this PR is also showing another bug, the server code by default assumes you are using `mqtt`, could be the case that the user is actually using `mqtts`, which will fail.

**Comment by karmanyaahm** [comment]
Also, the library https://www.npmjs.com/package/mqtt
supports many more protocols than just (mqtt|http)s?,
> The URL can be on the following protocols: 'mqtt', 'mqtts', 'tcp', 'tls', 'ws', 'wss', 'wxs', 'alis'.

I don't know what some of those protocols do, but it might be easier to just pass in whatever URL is entered by the user to the MQTT library.

**Comment by novirium** [comment]
I think either removing the frontend validation altogether or at least allowing any scheme would be a good idea.

For anyone trying to get this working with an MQTT broker via TLS in the meantime (which should be most people using a broker open to the internet), I can confirm that putting "mqtts://" in front of your broker hostname when editing the monitor as described by @karmanyaahm does work (right-click the hostname edit field in your browser, hit "Inspect", then delete the "pattern" field in the "<input>" element, allowing you to save the change to the monitor).

**Comment by Rem-V** [comment]
@karmanyaahm / @novirium : thank you for the tip. On my side, I had to use `pattern="(.*)"` to save hostname beginning with mqtts://...

**Comment by chakflying** [comment]
This issue should be closed as fixed.

**Comment by CommanderStorm** [comment]
Closing this issue as it was resolved by https://github.com/louislam/uptime-kuma/pull/2540 and released in `v1.19.5`

**Comment by ezequielfalcon** [comment]
Hello!
In addition to these schemes, it doesn't support URL paths. When using WebSocket schemes you can set the websocket connection in a URL subpath like `/mqtt` or `/ws`.
The connection regex should accept a subpath in the URL definition.

**Comment by chakflying** [comment]
Maybe you should open a new issue since the original issue is specifically about the scheme.
