### ISSUE TITLE
After disabling auth there is still a login page.

### ISSUE THREAD

**Issue by nick1boot** [louislam/uptime-kuma#156]
**Describe the bug**
After disabling auth there is still a login page.
No option to pass the login again.

**To Reproduce**
Disable auth
refresh page
login page appears

**Expected behavior**
No login page

**Screenshots**
No screenshot needed, its te login page of kuma

**Desktop (please complete the following information):**
 - Uptime Kuma Version: 1.0.8
 - Using Docker?: Yes
 - OS: unRAID
 - Browser: Google Chrome 

**Additional context**
Great project though 😉keep up the good work 👌

**Comment by louislam** [comment]
It's strange. I can't reproduce the problem. What is your previous version?

**Comment by Oskaria** [comment]
Error in server.js:596 - "Cannot read property 'id' of null"
You call autoLogin() without all fields for user
@louislam

**Comment by Oskaria** [comment]
`Disabled Auth: auto login to admin
uptime-kuma    | (node:20) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'id' of null
uptime-kuma    |     at afterLogin (/app/server/server.js:596:26)
uptime-kuma    |     at Namespace.<anonymous> (/app/server/server.js:119:19)`

**Comment by louislam** [comment]
> Error in server.js:596 - "Cannot read property 'id' of null"
> You call autoLogin() without all fields for user
> @louislam

Thanks, I can reproduce the problem now.

**Comment by Oskaria** [comment]
For now I can`t see all monitors and settings page) I think for this mode you can show all monitors, but hide buttons for add, edit, delete and pause. And setting page close for auth.

**Comment by louislam** [comment]
Should be fixed in 1.0.9. 

Sorry for the inconvenience.🙏🏻

**Comment by Oskaria** [comment]
Never mind, good luck ;-)

**Comment by louislam** [comment]
The 1.0.9 docker image has been uploaded,you could update now.

**Comment by nick1boot** [comment]
It’s working again 👌
Nice work !
