### ISSUE TITLE
OAuth2.0 support for API monitors

### ISSUE THREAD

**Issue by sm0w0ms** [louislam/uptime-kuma#1561]
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

API, New Monitor

### 🔖 Feature description

Kuma only supports basic Auth for monitors, It would be better to have multiple type of authorization such as **OAuth 2.0** .

### ✔️ Solution

APIs which supports OAuth2.0 Authorization cannot be added to monitor so it need OAuth 2.0 support

**Comment by CommanderStorm** [comment]
Related #1798

**Comment by CommanderStorm** [comment]
![image](https://github.com/louislam/uptime-kuma/assets/26258709/85b4a411-1f47-4f12-8a42-2fccfca313e4)

this issue was forgotten to close in https://github.com/louislam/uptime-kuma/pull/3119.
The feature is avaliable since `1.23.0`
