### ISSUE TITLE
Monitoring Uptimerobot via API?

### ISSUE THREAD

**Issue by alexw1982** [louislam/uptime-kuma#1564]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

I am using uptimerobot to verify service availability from outside my network.
I would like to integrate the checks in uptime-kuma, however I have been unable to get it to work with HTTP(S) keyword mode.

uptimerobot provides the following JSON response to a POST to the API at `https://api.uptimerobot.com/v2/getMonitors?api_key=[APIKEY]`

```
{
    "stat": "ok",
    "pagination": {
        "offset": 0,
        "limit": 50,
        "total": 1
    },
    "monitors": [
        {
            "id": 791577850,
            "friendly_name": "my url",
            "url": "https://myurl.com",
            "type": 1,
            "sub_type": "",
            "keyword_type": null,
            "keyword_case_type": null,
            "keyword_value": "",
            "http_username": "",
            "http_password": "",
            "port": "",
            "interval": 300,
            "timeout": 30,
            "status": 2,
            "create_datetime": 1650777551
        }
    ]
}
```

I have to trying to get it to work by setting the keyword to `"status": 2,` which is the code for the service being up but I am unable to get it to work ... help is much appreciated

### 🐻 Uptime-Kuma Version

1.15.0

### 💻 Operating System and Arch

Ubuntu 20.04

### 🌐 Browser

Firefox 99.0.1

**Comment by louislam** [comment]
You can specify the env var `UPTIME_KUMA_LOG_RESPONSE_BODY_MONITOR_ID=<your monitor id>` to print the whole response to your console.

https://github.com/louislam/uptime-kuma/wiki/Environment-Variables

**Comment by alexw1982** [comment]
the issue appear to that is it technically multiple keywords since `"status": 2,` include a space before the 2. Anyone got an idea how to make it search for the whole phrase? setting the keyword to `"status":` or `"2,` works as expected but I would like the keyword to be the complete phrase
