### ISSUE TITLE
Change data directory

### ISSUE THREAD

**Issue by SwaggaRitz** [louislam/uptime-kuma#1569]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

I am currently making an Uptime Kuma add on for home assistant. I have had to make a container from scratch which is working fine and running in Home Assistant. My issue is that home assistant requires set directories to be mapped, in this case /media/<YOUR_FOLDER>

At the moment the data gets stored in the working directory/data. Is there an option to choose where the data is stored?

My Docker file is below if it helps?

```
ARG BUILD_FROM=ghcr.io/hassio-addons/base/armhf:11.1.0
# hadolint ignore=DL3006
FROM ${BUILD_FROM}

# Setup base
# hadolint ignore=DL3003
RUN \
    apk add --no-cache --virtual .build-dependencies \
      py3-pip=20.3.4-r1 \
      python3-dev=3.9.7-r4 \
    \
    && apk add --no-cache \
        git=2.34.2-r0 \
        nodejs=16.14.2-r0 \
        npm=8.1.3-r0 \
        python3=3.9.7-r4 \
        sqlite=3.36.0-r0 \
        iputils=20210722-r0 \
        util-linux

COPY rootfs /

RUN git clone https://github.com/louislam/uptime-kuma.git --branch 1.15.0 --depth 1

WORKDIR /uptime-kuma

RUN npm run setup
```

Many Thanks

### 🐻 Uptime-Kuma Version

1.15.0

### 💻 Operating System and Arch

Alpine Docker

### 🌐 Browser

Chrome

### 🟩 NodeJS Version

16.14.2-r0

**Comment by gaby** [comment]
@SwaggaRitz Have you tried symlinking the folder?

**Comment by SwaggaRitz** [comment]
Yeah it's in my startup script but for the life of me don't know why it doesn't work. This run prior to kuma's initialisation

```
if [ ! -d /media/uptime-kuma ]; then
  mkdir /media/uptime-kuma
fi

ln -s /uptime-kuma/data /media/uptime-kuma
```

**Comment by SwaggaRitz** [comment]
Actually I might know why the symlink doesn't work I've got it the wrong way around. Let me go test.

**Comment by gaby** [comment]
@SwaggaRitz awesome! i may submit a PR later to make the data folder configurable via ENV variable.
