### ISSUE TITLE
One-click app for Cloudron is up

### ISSUE THREAD

**Issue by atridadl** [louislam/uptime-kuma#157]
Cloudron (https://cloudron.io) has a one click app available here: https://www.cloudron.io/store/louislam.uptimekuma.app.html

It's listed as unstable for now since to get stable, cloudron requires tests in the package. Just an FYI that this is an option :)

Also, I had originally packaged this one so if anyone notices anything off please let me know.

**Comment by louislam** [comment]
Yes, I want to spent my spare time on features development currently. Will make unit tests later.

Btw, I am reading Cloudron's website, I think it is a bit expensive to pay USD 15 per month in order to install unlimited apps, lol. It is of course easier if someone do not know what are docker and revers proxy though.

**Comment by gramakri** [comment]
I added selenium tests for the Cloudron package a week or so ago - https://git.cloudron.io/cloudron/uptime-kuma-app/-/tree/master/test . In fact, I just found a minor regression in the latest release (#159) .

@louislam If you would like to use Cloudron, please email me at support@cloudron.io and I can set you up with a contributor license. Thanks for the fantastic project!

**Comment by atridadl** [comment]
> Yes, I want to spent my spare time on features development currently. Will make unit tests later.
> 
> Btw, I am reading Cloudron's website, I think it is a bit expensive to pay USD 15 per month in order to install unlimited apps, lol. It is of course easier if someone do not know what are docker and revers proxy though.

Oh sorry yeah its something that the person packaging an app would do, not the app developer. And for the pricing, yeah its the trade-off between convenience vs affordability.

Thanks for chiming in @gramakri :D
