### ISSUE TITLE
Secure access to specific Status ages using auth

### ISSUE THREAD

**Issue by jamesinger-zephr** [louislam/uptime-kuma#1570]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

I want to be able to restrict access to Status pages behind  a login wall
e.g. i have  http://localhost:3001/status/google
and I want that to be restricted to specific users with a valid username and password
http://localhost:3001/status/google could have different users that http://localhost:3001/status/facebook, so has to be status page specific

### 🐻 Uptime-Kuma Version

1.15.0

### 💻 Operating System and Arch

AWS Linux

### 🌐 Browser

Chrome

### 🐋 Docker Version

NA

**Comment by mathiskir** [comment]
Duplicate of #1401 ?

**Comment by t3cneo** [comment]
IMO it is outside of the project' scope

You can do it with apache : 
[Here is a detailed How-To](https://www.digitalocean.com/community/tutorials/how-to-set-up-password-authentication-with-apache-on-ubuntu-14-04)

But managing credentials and access with apache can be tidious

You might want to check [authelia](https://github.com/authelia/authelia) for a nice and full featured auth system if you have other services you'd like to secure as well

**Comment by pivica** [comment]
> IMO it is outside of the project' scope

I disagree that this is outside of a project scope. For example pikapods.com service is now offering uptime-kuma as a pod container and there you do not have an option to edit Apache .htaccess file and limit access to status pages. Setting something like authelia is also probably not possible.

Additionally having access restriction to status pages built in in uptime-kuma would be very beneficial for most users that do not know or do not have time to work on custom access restriction implementations.

**Comment by louislam** [comment]
> Duplicate of #1401 ?

**Comment by darkstudio** [comment]
This Functionality will be apprecied: made credentials to protect each status page.
