### ISSUE TITLE
Allow html in status page footer

### ISSUE THREAD

**Issue by mathiskir** [louislam/uptime-kuma#1576]
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

Other

### 🔖 Feature description

Allow html in the footer text of a status page, if you put html into the footer text it is like this 
![image](https://user-images.githubusercontent.com/65130981/165488244-9e9fd944-f777-49d2-a671-22bba0731286.png)

### ✔️ Solution

Render html and do not display it as text

**Comment by mathiskir** [comment]
@louislam pleaaaasee allow it, it was already in a pr.

**Comment by NicoDreamzZ** [comment]
I would love to see this feature...

**Comment by CommanderStorm** [comment]
> #1083 already has that feature

@mathiskir the PR you mentioned has been merged
=> has this issue been accidentally left open?
If yes, could you close this issue? (less zombies 😉)

**Comment by CommanderStorm** [comment]
can confirm this example works
=> closing as resolved
