### ISSUE TITLE
Wrong datatype error

### ISSUE THREAD

**Issue by Goldenflamer** [louislam/uptime-kuma#1577]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### Description

There is an error causing a problem when saving certain values. Even if the datatype of the input is correct, there is an error saying "Wrong Datatype?" The error appears most consistently when adding a Steam API key via the settings but I have also seen it with other values. I am using the No Auth mode if that matters,

Steam key has the form A89A....... and is copied and pasted from steam directly, so it is 100% correct.

### 👟 Reproduction steps

Go to Settings and add a Steam API key
After inserting the Steam API key press save buttton

### 👀 Expected behavior

Steam API Key should be saved

### 😓 Actual Behavior

Error popup saying "Wrong data type?"

### 🐻 Uptime-Kuma Version

1.15.0

### 💻 Operating System and Arch

Windows 10 21H2 newest Updates as of posting date

### 🌐 Browser

Google Chrome 101.0.4951.41 64 bit

### 🐋 Docker Version

Docker Standalone 20.10.14

**Comment by chakflying** [comment]
Saw this too, I think there is a bug with the authentication code but I'm not sure exactlly what's going on. Please try to logout and login again and the problem should go away.

**Comment by Goldenflamer** [comment]
> Saw this too, I think there is a bug with the authentication code when using No Auth mode, but I'm not sure exactly what's going on. Please try to enable auth and login again and the problem should go away.

Yep you are right, working fine with auth

**Comment by Goldenflamer** [comment]
The problem is that doubleCheckPassword(socket, currentPassword) is called when auth is disabled which should not be the case. There is only one occurrence where there is a check before it if authentication is disabled, maybe the check could be added to other occurrences as well.
