### ISSUE TITLE
Display name and unique name key

### ISSUE THREAD

**Issue by duylong** [louislam/uptime-kuma#1583]
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

UI Feature

### 🔖 Feature description

It should be possible to differentiate the display name (free text) and the name currently used in the ui and the database (unique key).

### ✔️ Solution

Added a new field (eg display_name)

**Comment by CommanderStorm** [comment]
@duylong 
I think what you are referring to is resolved and should have been closed some time in the past.
Currently, the database uses integers to identify monitors and the frontend displays the `Friendly Name`.

See ![image](https://github.com/louislam/uptime-kuma/assets/26258709/a8dc61cc-c745-4bce-a89a-7af32990031d)

=> If you agree, could you please close this Issue, as immortal zombies are really hard to issue-manage?
=> If not, Could you please explain what you are referring to? (use screenshots preferably)
