### ISSUE TITLE
How to enable multi user

### ISSUE THREAD

**Issue by Rakkoc** [louislam/uptime-kuma#1584]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

How i add new user to kuma. i cant found it

### 🐻 Uptime-Kuma Version

1.15.0

### 💻 Operating System and Arch

ubuntu 20.x

### 🌐 Browser

Chrome Version 100.0.4896.127 (Official Build) (x86_64)

### 🐋 Docker Version

No docuker

### 🟩 NodeJS Version

14.19.x

**Comment by mathiskir** [comment]
As @ShadowGaming100 wrote #128 is about user management, currently there's no way to create a new user.
Please close this issue if you don't have any other questions about this.

**Comment by meeaeh** [comment]
Is this something that would be considered to be implemented in later releases

**Comment by CommanderStorm** [comment]
Yes, see #128 and the associated PR for further details

**Comment by jindalakash** [comment]
Hi everyone,

I know directly altering the database might not be ideal—or maybe it is, considering it’s open source—but during my local Uptime Kuma setup, I was able to create multiple users by manually adding new rows to the users table in the SQLite database. I basically cloned the default user row that gets created during initial configuration (where you set your username and password).

This doesn’t let you assign roles or limit permissions, but it does allow different team members to log in with separate usernames and passwords, which was good enough for basic access control in our case.

That said, I definitely agree that having proper user roles and permission management is a much-needed feature.
