### ISSUE TITLE
(Cloudflare tunnel) Cannot connect to the socket server

### ISSUE THREAD

**Issue by freitasm** [louislam/uptime-kuma#1586]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

Hi folks

Installed the image, running ok on [LAN IP]:3001. Continued to create a Cloudflare tunnel and all good, with the tunnel up.

Using Entry Page set to Dashboard the [subdomain].[domain].[tld] brings up an error "Cannot connect to the socket server. [Error: websocket error] Reconnecting..."

If I change Entry Page to "Status Page" then the status page loads fine.

Any ideas?

### 🐻 Uptime-Kuma Version

1.15.0

### 💻 Operating System and Arch

Synology docker

### 🌐 Browser

Microsoft Edge 100, Google Chrome 101

### 🐋 Docker Version

20.10.3-1305

**Comment by louislam** [comment]
Not sure whether it is related, but worth to try.

![image](https://user-images.githubusercontent.com/1336778/165879320-a15e195a-9718-44ec-84ed-7caf712542aa.png)

**Comment by freitasm** [comment]
Thanks, but not related. I already had this enabled for a year now as I use https://www.myrtille.io/ and it relies on sockets.

**Comment by LiamSho** [comment]
Cloudflare Tunnel does not support WebSocket :/
But maybe you can try this: https://community.cloudflare.com/t/tunnel-with-websockets/318111

**Comment by freitasm** [comment]
Thanks. That's interesting, seeing cloudflared/tunnel is explicitly supported and recommended in the documentation. 

I will check post and work on the configuration.

Cheers

**Comment by louislam** [comment]
> Cloudflare Tunnel does not support WebSocket :/ But maybe you can try this: https://community.cloudflare.com/t/tunnel-with-websockets/318111

As I am currently using Cloudflare tunnel, I can confirm it is working with WebSocket.

**Comment by freitasm** [comment]
Interesting. I can see the WebSocket requests coming through Cloudflare firewall and being allowed. so there must be something else. 

![image](https://user-images.githubusercontent.com/20156997/165898873-8f1b5260-a955-4947-a265-c123def7db52.png)

**Comment by LiamSho** [comment]
OK, I have got it to work.
It seems like my WAF rules (Managed Challenge to any HTTP/1.x requests) have sent a Managed Challenge to the WebSocket request which it could not complete.

Just set up a WAF rule to let this request pass and you're ready to go.

<img width="1105" alt="image" src="https://user-images.githubusercontent.com/28832398/165900523-60e37f21-eb3a-4aad-9d9f-bba8b6a51be9.png">

**Comment by louislam** [comment]
May need to check the response with Chrome DevTools 

![image](https://user-images.githubusercontent.com/1336778/165905901-a1a6d28d-8cb8-409a-8b62-94b516798441.png)
