### ISSUE TITLE
UI: Partially covered bottom nav if installed as pwa on ios (IPhone X and newer) 

### ISSUE THREAD

**Issue by luisbecker-gh** [louislam/uptime-kuma#1588]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### Description

The Problem only ocours if the website is installed as pwa on an IPhone X or newer. (Maybe some Android smartphones have the same problem).
The bottom nav is partially covered by the "Home Button".

Potential Fix:
change height of bottom nav to 60px + safe-area-inset-bottom
and add a padding to the bottom with the value safe-area-inset-bottom

### 👟 Reproduction steps

1. open your Uptime-Kuma instance on safari ios
2. add to Homescreen
3. open installed pwa

### 👀 Expected behavior

The bottom nav shouldn't be covered by the "Home Button".

![uptime-kuma-fixed](https://user-images.githubusercontent.com/68783274/165919127-4d64614a-182c-406b-9f29-4b9a7bafe07a.png)

### 😓 Actual Behavior

The bottom nav is partially covered by the "Home Button".

![uptime-kuma-bug](https://user-images.githubusercontent.com/68783274/165919012-405baeac-b33d-4708-b379-d38bb5e08c99.png)

### 🐻 Uptime-Kuma Version

1.15.1

### 💻 Operating System and Arch

IOS 15.5

### 🌐 Browser

Safari/ PWA

**Comment by NihadBadalov** [comment]
@CommanderStorm Seems to be fixed. iPhone 13: ![image](https://github.com/louislam/uptime-kuma/assets/32594553/39b90ead-8748-4ab9-9c8a-2ed5bffaa226)

**Comment by CommanderStorm** [comment]
Thanks ^^
