### ISSUE TITLE
Content-type not set for the /setup page

### ISSUE THREAD

**Issue by gramakri** [louislam/uptime-kuma#159]
**Describe the bug**
content-type not set when visiting `/setup`.

**To Reproduce**
1. Install uptime kuma
2. Visit the initial page. It serves up `/` correctly with content-type as `text/html; charset=UTF-8` . I am not 100% sure but I guess it sets the URL to /setup using the history API.
3. Refresh the page. The content-type is not set. It shows a text page instead.

(This is on Cloudron, content sniffing is disabled using `x-content-type-options: nosniff` )

**Expected behavior**
`/setup` page must serve up html on refresh.

**Screenshots**
I see the plain text instead.
![image](https://user-images.githubusercontent.com/82041/128068889-0dbdf719-8a51-499f-bcb1-e2836c5b3971.png)

**Desktop (please complete the following information):**
 - Uptime Kuma Version: Seems to start with 1.0.8 and also reproducible on 1.0.9
 - Using Docker?: Yes
 - OS:  Cloudron package
 - Browser: Firefox and Chrome

**Additional context**

**Comment by gramakri** [comment]
I can also confirm that this behavior is not reproducible with 1.0.7

**Comment by chakflying** [comment]
Made a PR for this. Meanwhile see if you can disable setting nosniff on this site. Since there is no user generated content, there should be no security implications.

**Comment by louislam** [comment]
fixed in 1.0.10

**Comment by gramakri** [comment]
Can confirm this is fixed with 1.0.10. Thanks for the quick fix!
