### ISSUE TITLE
White background on account icon with Safari and dark mode

### ISSUE THREAD

**Issue by andlil** [louislam/uptime-kuma#1596]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### Description

![Skärmavbild 2022-04-30 kl  10 12 57](https://user-images.githubusercontent.com/10003475/166097737-70568c27-d9bd-4089-92a9-0a2293083482.png)

### 👟 Reproduction steps

Using Safari Version 15.4 (17613.1.17.1.13) the background will be white if using dark mode. When using Chrome it is black.

### 👀 Expected behavior

Display the background as black

### 😓 Actual Behavior

Displays the background as white

### 🐻 Uptime-Kuma Version

1.15.1

### 💻 Operating System and Arch

MacOS 12.3.1 (21E258)

### 🌐 Browser

Safari Version 15.4 (17613.1.17.1.13)

**Comment by louislam** [comment]
Ops, maybe I forgot to remove the `type=button`

https://github.com/louislam/uptime-kuma/blob/db50ba91cc12e63341fdfc9eb06d6131dd75c4f0/src/layouts/Layout.vue#L36

**Comment by Saibamen** [comment]
![image](https://user-images.githubusercontent.com/905878/167095874-4c1d42c9-f952-4600-9503-58e18d7d7e6c.png)
