### ISSUE TITLE
How to add new notification to dropdown and to the system

### ISSUE THREAD

**Issue by openstep** [louislam/uptime-kuma#1599]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

Could you provide a step-by-step instruction on how to add a new notification to the system?
I basically have written a modified SMTP notification and have the code locally. Than with gitlab ci I copy ower the smtp config file. But it would be much better if I could just add my new module. I do not want to reverse engineer the code, hence the question.

### 🐻 Uptime-Kuma Version

latest

### 💻 Operating System and Arch

n/a

### 🌐 Browser

n/a

**Comment by louislam** [comment]
You can take a look of pull request like this:
https://github.com/louislam/uptime-kuma/pull/1446/files

But first, you need to know how to setup the development environment and how to build the frontend.
https://github.com/louislam/uptime-kuma/blob/master/CONTRIBUTING.md

**Comment by openstep** [comment]
Hi,

Thanks for your tips.
I tried a quick test by following the suggestion here https://github.com/louislam/uptime-kuma/pull/1446/files 
1. added a new notification provider ie smtp2.js
2. added a reference to server/notification.js
3. created a new file smtp2.vue
4. added a reference to src/components/notifications/index.js
5. added an entry to src/languages/en.js

my dockerfile starts like this
```
FROM docker.io/louislam/uptime-kuma:1.11.4-debian AS app-src

FROM docker.io/node:14-bullseye-slim

ARG UID=3310
ARG GID=3310

COPY --from=app-src /app /app
COPY <-- I copy the exact files just as a test
```
So I do not have a dev env, setup. I just reference `FROM docker.io/louislam/uptime-kuma:` and add my changes via COPY command.
This worked so far when I only modified one of the files smtp.js but this time I got errors and I suspect that there was something missing since I followed this suggestion https://github.com/louislam/uptime-kuma/pull/1446/files

Could you review this https://github.com/louislam/uptime-kuma/pull/1446/files ? Is anything missing here? When I followed it, 
I got the below error on app startup:

```
Welcome to Uptime Kuma
Your Node.js version: 14
Node Env: production
Importing Node libraries
Importing 3rd-party libraries
Importing this project modules
internal/modules/cjs/loader.js:905
  throw err;
  ^

Error: Cannot find module './notification-providers/techulus-push'
Require stack:
- /app/server/notification.js
- /app/server/model/monitor.js
- /app/server/server.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)
    at Function.Module._load (internal/modules/cjs/loader.js:746:27)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:101:18)
    at Object.<anonymous> (/app/server/notification.js:15:22)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Module.require (internal/modules/cjs/loader.js:974:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/app/server/notification.js',
    '/app/server/model/monitor.js',
    '/app/server/server.js'
  ]
}
```

Many thanks.

**Comment by chakflying** [comment]
Unfortunately front end change would require a dev environment to transpile the js files. The docker image is also design for production and does not have dependencies needed for development.

**Comment by openstep** [comment]
> You can take a look of pull request like this: https://github.com/louislam/uptime-kuma/pull/1446/files
> 
> But first, you need to know how to setup the development environment and how to build the frontend. https://github.com/louislam/uptime-kuma/blob/master/CONTRIBUTING.md

I try to build this dev env and might come back here for help if needed.

**Comment by openstep** [comment]
Could you please direct me on how to add ie a second SMTP menu item on the frontend?
So far I have done is:
- added smtp2.js
- added SMTP2.vue
- added reference in notifications.js, notification-providers.js and in en.js

I can also modify the text appearing in the Notification Type dropdown but  for only the exisiting SMTP type not for the one I added.

**Comment by openstep** [comment]
Now I need to build it to get a docker image.

**Comment by openstep** [comment]
Hi, 
I have the git cloned and would like to build locally. 
I am able to run the app locally and make the changes. Could you please help me with the steps to build the docker image on Linux?
I am ok with Linux and docker but I do not want to reverse engineer the whole process.
