### ISSUE TITLE
Cache DNS for Notifications, saving last known-good IP(s)

### ISSUE THREAD

**Issue by ctrlbrk42** [louislam/uptime-kuma#160]
Please consider caching the last "known-good" IP of services defined within the Notifications (ie: smtp.gmail.com), so that notifications may still be sent even if DNS resolution is down.

I realize it might be an edge case where Internet is UP but DNS is down, but still this is entirely possible, and in the current configuration the notifications won't be sent if the DNS is failing.

Desired behavior is to keep the last known-good IP(s) of the notifications, and fallback to those if at the time of DNS query the resolution fails.

Thank you dev(s).

**Comment by louislam** [comment]
I think secondary DNS is enough in this case. I think it is unusual to make a dns backup solution in an application.
