### ISSUE TITLE
Support for ntfy

### ISSUE THREAD

**Issue by SMAW** [louislam/uptime-kuma#1601]
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

New Notification

### 🔖 Feature description

I would love to see integration with ntfy.sh (or the selfhosted one) and be able to send notifications to a ntfy.sh server

### ✔️ Solution

Since I don't have program skills to program it, I would like to see it build in into uptime-kuma

### 📝 Additional Context

It is well documented (https://ntfy.sh/docs/)

**Comment by louislam** [comment]
It should be supported by Apprise: https://github.com/caronc/apprise/wiki/Notify_ntfy

**Comment by SMAW** [comment]
I see!! Thanks missed that one! 

Maybe an offtopic question, but most of the notifications are also in apprise, why not only use apprise in uptime-kuma?

**Comment by gaby** [comment]
@SMAW Uptime-Kuma already uses Apprise :-)

**Comment by SMAW** [comment]
I understand but why support a bunch of notification types also seperate.... and not only use apprise, because now you have to maintain both

**Comment by gaby** [comment]
@SMAW Good point, and I agree. I'd make uptime-kuma more simple if it only supported notifications via Apprise, and anything new was contributed on that project instead.

**Comment by louislam** [comment]
> I see!! Thanks missed that one!
> 
> Maybe an offtopic question, but most of the notifications are also in apprise, why not only use apprise in uptime-kuma?

A lot of reasons here. Main reasons:
- Apprise does not support every notifications at the same.
- For non-Docker users, they don't need to install Python and Apprise which is easier for them to use Uptime Kuma, without extra effort. (Install Python things sometimes is very hard in my opinion)
- Directly make requests to the APIs, performance is much better.
