### ISSUE TITLE
smtp send mail error:A system error occurred: uv_os_gethostname returned ENOSYS (function not implemented)

### ISSUE THREAD

**Issue by gang2113920** [louislam/uptime-kuma#1606]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

smtp send mail error:

A system error occurred: uv_os_gethostname returned ENOSYS (function not implemented)
![image](https://user-images.githubusercontent.com/10305840/166300142-b3b3d329-d6ad-4f46-bfca-a5c59afdcc05.png)

![image](https://user-images.githubusercontent.com/10305840/166300297-dc8082e2-6fb6-44a5-ac42-cc2a4e1d19d2.png)

my config:
![image](https://user-images.githubusercontent.com/10305840/166300107-1541c584-d0fa-4120-bb4a-72d3d83a2d58.png)
![image](https://user-images.githubusercontent.com/10305840/166300445-7ab9a8ef-fc08-46a1-a715-1ea0171d79b4.png)

### 🐻 Uptime-Kuma Version

1.15.1

### 💻 Operating System and Arch

windows server 2008 R2 Enterprise

### 🌐 Browser

chrome 100.0.4896.60

### 🟩 NodeJS Version

16.14.0

**Comment by gang2113920** [comment]
![image](https://user-images.githubusercontent.com/10305840/166395186-c20fec44-937b-4796-ac0b-9de87789403e.png)

**Comment by gang2113920** [comment]
who can help me，thanks

**Comment by chakflying** [comment]
Sorry, looks like your Windows version is [too old](https://github.com/libuv/libuv/issues/3260) and there is no fix for it.

**Comment by gang2113920** [comment]
> Sorry, looks like your Windows version is [too old](https://github.com/libuv/libuv/issues/3260) and there is no fix for it.

what can i do to resovle this problem.

**Comment by gang2113920** [comment]
> Sorry, looks like your Windows version is [too old](https://github.com/libuv/libuv/issues/3260) and there is no fix for it.

use a other system server，the problem is gone.

thanks

**Comment by gang2113920** [comment]
close
