### ISSUE TITLE
How can i notify each X minutes current alerts

### ISSUE THREAD

**Issue by Efiartes** [louislam/uptime-kuma#1607]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

When a webpage goes down i receive a notification but only one time, if the problem persists i am not notified each X minutes, is it posssible to configure to resend active alerts each X minutes?

### 🐻 Uptime-Kuma Version

1.15.0

### 💻 Operating System and Arch

Ubuntu 22.04

### 🌐 Browser

Google Chrome  Versión 100.0.4896.127 (Build oficial) (64 bits)

### 🟩 NodeJS Version

v16.15.0

**Comment by gaby** [comment]
This is fixed by #1212 which hasnt been merged since January.
