### ISSUE TITLE
Incorrect environment variable for Docker in Wiki

### ISSUE THREAD

**Issue by palijn** [louislam/uptime-kuma#1608]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### Description

The Environment Variables in the Wiki at https://github.com/louislam/uptime-kuma/wiki/Environment-Variables
mentions Docker Specific Environment Variables as
PUID
**GUID**
however, the correct variables are :
PUID
**PGID**

PLUS
if PGID is not set and PUID is set, the actual group will be 0(root) instead of 1000.

### 👟 Reproduction steps

Prepare a Docker environment with GUID = 65543 , run it.
Journal log will show 
 Starting application with user xx **group 0**
Replace GUID with PGID = 65543 , relaunch
Journal log will show 
 Starting application with user xx **group 65543**

### 👀 Expected behavior

I expected the user group id to be set to the value of the environment variable

### 😓 Actual Behavior

The group is was set to 0 i.e. root .
This is different than the documented default of 1000.

### 🐻 Uptime-Kuma Version

1.15.1

### 💻 Operating System and Arch

x86_64 GNU/Linux synology_apollolake_218+

### 🌐 Browser

irrelevant

### 🐋 Docker Version

Docker version 20.10.3, build 55f0773

### 🟩 NodeJS Version

irrelevant

### 📝 Relevant log output

```shell
==> Starting application with user 1042 group 0
```

**Comment by louislam** [comment]
Thanks, fixed
