### ISSUE TITLE
Filter monitor list by tag

### ISSUE THREAD

**Issue by Bodge-IT** [louislam/uptime-kuma#1610]
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

UI Feature

### 🔖 Feature description

I would like to instantly filter dashboard list of monitors by clicking a tag to see all monitors with that tag.
the 

### ✔️ Solution

Tags would need to be separated from the main clickable area for the monitor or tags made available as a filter option at the top of the list

### ❓ Alternatives

search?

**Comment by rob1998** [comment]
+1

**Comment by the-northway** [comment]
+1

I have hundreds of domains to monitor - being able to quickly filter them would be real neat.

**Comment by Mereks** [comment]
+ 1

Filter or sort

**Comment by 50l3r** [comment]
Its a good idea if u have too many monitors
