### ISSUE TITLE
Proxy support for notifications

### ISSUE THREAD

**Issue by xorguy** [louislam/uptime-kuma#1611]
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

Other

### 🔖 Feature description

Add proxy support for notifications, when using in a network that requires Internet proxy notifications like Teams is not working because the application is not using the proxy even it have been added and enabled.

### ✔️ Solution

No workaround for now.

**Comment by Axarent** [comment]
This looks to be a duplicate of https://github.com/louislam/uptime-kuma/issues/616.
