### ISSUE TITLE
When set DATA_DIR, error.log is still written into ./data/error.log

### ISSUE THREAD

**Issue by CoelacanthusHex** [louislam/uptime-kuma#1612]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### Description

When set DATA_DIR, error.log is still written into ./data/error.log
It will lead "Error: EACCES: permission denied, open './data/error.log'" when we install uptime-kuma to system dir.

### 👟 Reproduction steps

install uptime-kuma system-wide, set DATA_DIR to a writable place, then run uptime-kuma without root

### 👀 Expected behavior

error.log write into $DATA_DIR/error.log rather than ./data/error.log

### 😓 Actual Behavior

Error: EACCES: permission denied, open './data/error.log'

### 🐻 Uptime-Kuma Version

1.15.1

### 💻 Operating System and Arch

Arch Linux

### 🌐 Browser

Firefox 102

**Comment by CoelacanthusHex** [comment]
https://github.com/louislam/uptime-kuma/blob/master/server/util-server.js#L531

**Comment by louislam** [comment]
Thank you for your report. Fixed in https://github.com/louislam/uptime-kuma/commit/429ad384d081ee8e228b192ff82ae27c45dfdd70
