### ISSUE TITLE
Does this one support distributed probes?

### ISSUE THREAD

**Issue by louishot** [louislam/uptime-kuma#1614]
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

New Monitor, Other

### 🔖 Feature description

Does this one support distributed probes?

### ✔️ Solution

distributed probes

### ❓ Alternatives

distributed probes

### 📝 Additional Context

distributed probes

**Comment by philippdormann** [comment]
possible duplicate, see #84
