### ISSUE TITLE
Need help in creating docker image

### ISSUE THREAD

**Issue by sm0w0ms** [louislam/uptime-kuma#1615]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

I made some changes in original source code, how do I build a new docker image out off that

### 🐻 Uptime-Kuma Version

1.15.1

### 💻 Operating System and Arch

Ubuntu 20

### 🌐 Browser

Chrome

### 🐋 Docker Version

20.10.14

### 🟩 NodeJS Version

14.18.3

**Comment by gaby** [comment]
```bash
npm run build-docker
```

**Comment by sm0w0ms** [comment]
![image](https://user-images.githubusercontent.com/104065050/167342749-14764f6b-ffb3-4808-9312-aa7b30f5b38c.png)
I am getting these error can you tell me what is going wrong

**Comment by louislam** [comment]
I think you need Node.js 16+, because replaceAll() function is new in Node.js 16.

And since the current build commands are using `buildx` and hardcoded tag names, I think you probably don't need this. I would recommend that you should write you own command to build the `docker/dockerfile`.

**Comment by sm0w0ms** [comment]
Thanks for the help :D
