### ISSUE TITLE
pinging error

### ISSUE THREAD

**Issue by marianomaluf** [louislam/uptime-kuma#1619]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

Hello, I have two installations of Uptime Kuma, one on linux and it works fine, the other on windows which sends me false alerts, that is, red alerts with the following text:

Ping 10.1.143.121 with 32 bytes of data: Response from 10.1.143.121: bytes=32 time<1m TTL=63 Ping stats for 10.1.143.121: Packets: sent = 1, received = 1, lost = 0 (0% lost), Approximate round trip times in milliseconds: Minimum = 0ms, Maximum = 0ms, Average = 0ms

As you will see the package was sent and received well.

What do you advise me to do?

thank you!

### 🐻 Uptime-Kuma Version

1.15.1

### 💻 Operating System and Arch

Windows 8.1 Pro

### 🌐 Browser

Chrome 101.0.4951.54 (Build oficial) (64 bits)

### 🟩 NodeJS Version

18.0.0

**Comment by marianomaluf** [comment]
any idea how to further analyze the problem ?

**Comment by chakflying** [comment]
Since I think nobody around here uses Windows 8, maybe you can manually open `cmd`, and enter `ping 10.1.143.121` or whatever your target IP is, and post the full output here for us to verify.

**Comment by marianomaluf** [comment]
Thanks Nelson, I don't want to use Windows 8 either, but it's the only computer available within the zone that I want to monitor...

Here is the full ping result:

C:\Windows\System32>ping 10.1.143.121

Haciendo ping a 10.1.143.121 con 32 bytes de datos:
Respuesta desde 10.1.143.121: bytes=32 tiempo<1m TTL=63
Respuesta desde 10.1.143.121: bytes=32 tiempo<1m TTL=63
Respuesta desde 10.1.143.121: bytes=32 tiempo<1m TTL=63
Respuesta desde 10.1.143.121: bytes=32 tiempo<1m TTL=63

Estadísticas de ping para 10.1.143.121:
    Paquetes: enviados = 4, recibidos = 4, perdidos = 0
    (0% perdidos),
Tiempos aproximados de ida y vuelta en milisegundos:
    Mínimo = 0ms, Máximo = 0ms, Media = 0ms


The PC (10.1.143.121) is always up when I ping from the cmd but from Uptime Kuma every 3 or 4 attempts it sends a red alert.

Well, if they consider that it is a problem caused by the version of windows, I will try to move to another computer.

thank you!!!

**Comment by louislam** [comment]
I found the issue. Some versions of Windows output `1m` instead of `1ms`. I guess it maybe a translation error of Windows' ping tool.

I will try to update regex to fix it.

**Comment by marianomaluf** [comment]
Ok, thank you very much Louis!!!
