### ISSUE TITLE
Simple ping RTT graph to record latency history

### ISSUE THREAD

**Issue by mahenkpatel** [louislam/uptime-kuma#162]
This will help in getting historical data of latency to a server. 

Can we get a simple graph of ping latency/RTT for every ping try to the server. If not graph, just a table with historical ping latency will also help in checking health of network over time.

Right now the status is in binary, either up or down but there may be instances where because of network issue the ping latency will be very high but the monitor will still show that the server is up bit it may deteriorate service quality.

Having historical ping latency data in this case will help the admin.

**Comment by proffalken** [comment]
The latest versions have a [Prometheus Endpoint](https://github.com/louislam/uptime-kuma/wiki/Prometheus-Integration) that you can use to pull this data into an existing monitoring platform, and I recently [published a Grafana dashboard](https://grafana.com/grafana/dashboards/14847) that pulls that data from Prometheus into Grafana including showing the latency trends:

![2021-08-09_15-56](https://user-images.githubusercontent.com/262545/128824759-452826b6-c172-482f-ac8a-951b034ab841.png)

Using a tool such as prometheus or similar is a much better way to access historical data than building that kind of storage in to Uptime Kuma IMHO as it means that if you get to hundreds of monitors all running at the same time you don't have to worry about concurrency issues on the backend storage.

**Comment by SpcCw** [comment]
@proffalken - this is certainly interesting! However myself I would prefer something simpler which doesn't require whole stack of other software - just a simple graph per monitor (not necessarily going very far back or having high resolution). Actually I want it to run on very small independent node and be publicly accessible (hopefully public dashboard comes soon) so people could view uptime and response times of my services and see if there is some problem with them or just their connection.

E.g. something like Statping offered.

**Comment by louislam** [comment]
Will add graph, but need to find a good grpah library to do that.

**Comment by chakflying** [comment]
Was just working on this, maybe I'll do a PR later today?

**Comment by chakflying** [comment]
@louislam suggest close as resolved.
