### ISSUE TITLE
Sometimes monitors get bogged down

### ISSUE THREAD

**Issue by Nuklon** [louislam/uptime-kuma#1621]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### Description

I have two HTTPs monitors for the same site, exactly the same parameters except one is checking every 30 seconds, and the other every minute.

This just happened for the 1 minute site:
![image](https://user-images.githubusercontent.com/23340481/167215453-155da7ab-6d9c-4cd3-bc04-e2ba68cf5fa7.png)

The 30 second site is all good:
![image](https://user-images.githubusercontent.com/23340481/167215510-9266a96f-fd2a-4062-ab34-e5e937729dfe.png)

It also happens the other way (i.e., 30s gets bogged down whereas 1m shows no faults).

### 👟 Reproduction steps

Add two sites, dockerized, one with 1m and one with 30s.

### 👀 Expected behavior

This shouldn't happen.

### 😓 Actual Behavior

Occassional bogged down monitors

### 🐻 Uptime-Kuma Version

1.15.1 (also happened with previous versions)

### 💻 Operating System and Arch

Docker

### 🌐 Browser

Firefox 100

### 🐋 Docker Version

Latest docker-win.

**Comment by Saibamen** [comment]
FYI @chakflying

**Comment by chakflying** [comment]
Tested a bit but cannot reproduce. I suspect it has something to do with how the DNS getting limited queries, which #1598 should fix.

**Comment by Nuklon** [comment]
> Tested a bit but cannot reproduce. I suspect it has something to do with how the DNS gets limited queries, which #1598 should fix.

I have three separate sites with this issue (all have 30s and 1m monitors). One site uses Cloudflare DNS and other two Gandi.

**Comment by Nuklon** [comment]
I've double checked my also adding a monitor of IP address and it has the same problem, so it's not DNS related.

**Comment by Nuklon** [comment]
Seems to be fixed by latest Windows update, so closing.
