### ISSUE TITLE
Add Notification support for Ntfy

### ISSUE THREAD

**Issue by Joeharrison94** [louislam/uptime-kuma#1622]
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

New Notification

### 🔖 Feature description

Ntfy as a notification agent, it is a rapidly growing very popular sub-pub notification service and I know lots of people who want this to be included in uptime kuma as they both would go extremely well together.

### ✔️ Solution

https://ntfy.sh/docs

Allow publishing via http or curl with options to change tags,topic,message,title, and priority, examples below:

HTTP:

```
POST / HTTP/1.1
Host: example..com

{
    "topic": "uptimekuma",
    "message": "Site is down",
    "title": "Site Down Alert",
    "tags": ["warning","loudspeaker"],
    "priority": 4
}
```

Curl:
```
curl ntfy.sh \
  -d '{
    "topic": "uptimekuma",
    "message": "Site is down",
    "title": "Low disk space alert",
    "tags": ["warning","loudspeaker"],
    "priority": 4
  }'
```

**Comment by louislam** [comment]
Related issue: https://github.com/louislam/uptime-kuma/issues/1601

**Comment by Joeharrison94** [comment]
@louislam thank you for this! will this be in the next release of the latest tag on docker?

**Comment by louislam** [comment]
> @louislam thank you for this! will this be in the next release of the latest tag on docker?

Yes, it will be in the next release. 

At the meantime, if you are using Docker, you can use Ntfy via Apprise in Uptime Kuma 1.16.1
https://github.com/caronc/apprise/wiki/Notify_ntfy
