### ISSUE TITLE
Timezone issue

### ISSUE THREAD

**Issue by pbunluesin** [louislam/uptime-kuma#1625]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### Description

Hello, 

Could you please help check time zone for docker image. I found issue that send data to notification with wrong date. I want UTC+7 but it sent UTC.I have already set time zone on docker command also uptime-Kuma UI interface. It still send notification to Line with wrong date.
( not sure if I install with installer will found this issue or not)

docker command

`docker run -d --restart=always -e 'TZ=Asia/Bangkok' -v C:\uptime-kuma:/app/data -p 3001:3001  --name uptime-kuma-test louislam/uptime-kuma:1`

datetime inside docker container
![image](https://user-images.githubusercontent.com/3583606/167330217-696fdbbd-bc93-46ba-a50d-bf8791de6919.png)

Line notification with wrong timezone
![notification](https://user-images.githubusercontent.com/3583606/167330264-e151d4fb-8974-491b-9f88-b79140a68498.JPG)

### 👟 Reproduction steps

-

### 👀 Expected behavior

It should send notification with UTC+7

### 😓 Actual Behavior

It send notification with UTC

### 🐻 Uptime-Kuma Version

1

### 💻 Operating System and Arch

Windows

### 🌐 Browser

Google Chrome

### 🐋 Docker Version

20.10.12

**Comment by pbunluesin** [comment]
I have tried with latest version still found this problem.

**Comment by louislam** [comment]
Duplicate of #40
