### ISSUE TITLE
Reset database

### ISSUE THREAD

**Issue by ShadowGaming100** [louislam/uptime-kuma#1628]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

Reset Database
edit: to remove all the data of the database 

### 🐻 Uptime-Kuma Version

1.15.1

### 💻 Operating System and Arch

Linix

### 🌐 Browser

Google Chrome

### 🟩 NodeJS Version

latest

**Comment by xoniq** [comment]
Remove all db files to start completely over. Or if you only want to remove all stats, go to Monitor History > Clear all Statistics

**Comment by ShadowGaming100** [comment]
> Remove all db files to start completely over. Or if you only want to remove all stats, go to Monitor History > Clear all Statistics

ok thanks
