### ISSUE TITLE
Where is Version: 1.15.1 on Github?

### ISSUE THREAD

**Issue by rezzorix** [louislam/uptime-kuma#1632]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

Version: 1.15.1 has disappeared from github repository ... where is it?

Further infos: I am monitoring https://github.com/louislam/uptime-kuma/releases/latest in 12 hour intervals and therefore know that the latest version went missing sometime in the morning of 2022-05-10 UTC time.

Same thing with some other repositories I monitor (e.g. [Vaultwarden](https://vaultwarden.discourse.group/t/latest-release-1-24-0-rolled-back-to-1-23-1-on-github/1619/3)), so I am wondering what happened.

### 🐻 Uptime-Kuma Version

1.15.1

### 💻 Operating System and Arch

n//a

### 🌐 Browser

n/a

**Comment by rezzorix** [comment]
Actually direct link https://github.com/louislam/uptime-kuma/releases/tag/1.15.1 is still working, it is just not shown as "latest" anymore... seems to be a Github bug in general where Github isnt choosing the correct "latest version" to show.

**Comment by louislam** [comment]
Really strange...

**Comment by louislam** [comment]
I can't find it my list too.

I go to your direct link > edit > save, it comes back now.
> https://github.com/louislam/uptime-kuma/releases/tag/1.15.1

**Comment by rezzorix** [comment]
Strange indeed... well it is back now.
Just worried a bit that github might be not too reliable anymore; so might be better to backup all preventively.

**Comment by louislam** [comment]
> Strange indeed... well it is back now. Just worried a bit that github might be not too reliable anymore; so might be better to backup all preventively.

Oh yes, GitHub is under Microsoft now. As I remember, they fired all Windows QA teams. So good luck GitHub.

Joking aside, I think you are right, I better do backup of all issues, releases and pull requests here.

**Comment by christopherpickering** [comment]
It happens on some of my projects as well - releases disappear or show up a day later. I'm sure its a GitHub server cache problem.
