### ISSUE TITLE
How can I monitor an internal service with Uptime Kuma?

### ISSUE THREAD

**Issue by iamdempa** [louislam/uptime-kuma#1642]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

Hi,

I have a simple `nginx` deployment running in the `default` namespace. And `uptime-kuma` running in its own namespace (kuma). 

But when I try to add a monitor through UI, and given the `URL` "http://nginx.default.svc.cluster.local", it fails. 

Can someone help me with this? 

### 🐻 Uptime-Kuma Version

1.15.1

### 💻 Operating System and Arch

Amazon Linux 2

### 🌐 Browser

Google Chrome

**Comment by louislam** [comment]
Any error message in Uptime Kuma?

**Comment by iamdempa** [comment]
Hi @louislam,
Find the below screen snip for the error:

<img width="594" alt="image" src="https://user-images.githubusercontent.com/32482769/168333571-645c5fc2-deed-4e8d-8da6-ba9c6bfa20e6.png">

**Comment by louislam** [comment]
I never used K8s, but I think it should be your virtual network or Nginx config issue.

There are several things you can do, you can find which part is wrong:

- Check Nginx is listening to which address and which port.
- Check if they both are in the same network.
- Uptime Kuma's image is based on Debian, you can go into the terminal and run `curl http://nginx.default.svc.cluster.local/`
- Similarly, go into Nginx's terminal and try to run `curl http://uptime-kuma:3001`
- Unlikely existing in k8s/docker I think, but should be no firewall in between them?

**Comment by iamdempa** [comment]
Hi I was able to fix this. The issue was that, I was using the wrong health check endpoint. Closing the issue.

**Comment by pen-pal** [comment]
Hi @iamdempa 
Could you share your helm chart to use?

**Comment by CommanderStorm** [comment]
https://github.com/louislam/uptime-kuma/wiki/%F0%9F%94%A7-How-to-Install#%EF%B8%8F-openshift-4-and-kubernetes-helm-3-chart-unofficial
