### ISSUE TITLE
Count uptime-kuma being down as downtime

### ISSUE THREAD

**Issue by appuchias** [louislam/uptime-kuma#1644]
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

API, Other

### 🔖 Feature description

The feature request is to allow users to count the time uptime kuma is down as downtime

### ✔️ Solution

If uptime-kuma goes down, once it recovers it should get the time gap and set it as down for everything

### ❓ Alternatives

It could be added as a per-monitor check (to set certain monitors as down when uptime-kuma goes down, for example for docker containers on the same host), or as a global check.

Also it could be shown as 'unknown' or something like that, to be easily differentiable from true uptime or downtime.

### 📝 Additional Context

It could be useful for setups when there could be unexpected or intentional power cuts if you need to show that downtime, as otherwise it could be 100% while uptime-kuma was up, but not when down

**Comment by karelkryda** [comment]
Duplicate of #1579

**Comment by karelkryda** [comment]
You mean something like in this issue #1579?

**Comment by appuchias** [comment]
Yes, something like that. Sorry for the duplicate, I didn't find it when I searched the issues.
However, I think some ideas I propose could be useful.
