### ISSUE TITLE
One click deploy

### ISSUE THREAD

**Issue by Olyno** [louislam/uptime-kuma#1648]
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

Other

### 🔖 Feature description

Hi 👋🏻 
I would like to deploy the project on [render.com](https://render.com), but unfortunately it only accepts Dockerfile for services like uptime-kuma.

Would it be possible to create a Dockerfile at the root of the project in order to deploy it on services similar to render.com?

### ✔️ Solution

Creating a Dockerfile at the root of the project.

### ❓ Alternatives

Creating another repo with only the Dockerfile to be able to deploy in "one click".

### 📝 Additional Context

You can have more information [here](https://render.com/docs/deploy-to-render)

**Comment by louislam** [comment]
I think you need to create your own repo like this: https://github.com/render-examples/wordpress

Dockerfile should be like this:
```Dockerfile
FROM louislam/uptime-kuma
```

**Comment by Olyno** [comment]
Does a simple import with "FROM" work? It seemed to me that more commands were needed, such as "RUN". I'll check on my side if it works with only the "FROM"

**Comment by alexislefebvre** [comment]
@Olyno I'm pretty sure that the commands like `RUN` will be inherited from the base image.

**Comment by brentrobbins** [comment]
Hey @Olyno I would love to use your repo, however I just tried it and it looks like it's missing a `render.yaml` file. Any change you could add that?

**Comment by Olyno** [comment]
Sorry for the issue @brentrobbins, I just added the file "render.yaml". Should be fine now.

**Comment by brentrobbins** [comment]
Thanks @Olyno for adding that, however I just tied and the deployment failed with a fairly ambiguous error. Have you tried redeploying it to render to see if this repo works as expected?

<img width="1272" alt="CleanShot 2023-03-08 at 20 52 15@2x" src="https://user-images.githubusercontent.com/727491/223912562-cc5650cc-9eab-4012-b517-24b5acd7c089.png">

**Comment by Olyno** [comment]
I do have a similar error, and i have no idea how to fix it:
![image](https://user-images.githubusercontent.com/25107942/224104631-196c1caa-5f19-4fb7-ae6e-93726dac1c94.png)

I think it's a bug that was added to the latest version of Docker, or something similar. If not, I don't see a way to fix this.

Can you try to manually add the web service by specifying the repository?
