### ISSUE TITLE
Add all sites in one shot 

### ISSUE THREAD

**Issue by babuhasib** [louislam/uptime-kuma#1649]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

Hi.

Is there a way, we can add multiple sites in one shot instead of going manually adding them one by one on GUI Dashboard. 
Or what is the folder or directory that contains all the sites we are monitoring? 

### 🐻 Uptime-Kuma Version

1.15.1 

### 💻 Operating System and Arch

Ubuntu 20

### 🌐 Browser

Chrome

### 🐋 Docker Version

Version 20.10.9

### 🟩 NodeJS Version

NON

**Comment by Computroniks** [comment]
Duplicate of #1457

**Comment by Computroniks** [comment]
As for folder, there is non. All data is stored in the SQLite database
