### ISSUE TITLE
web screenshot

### ISSUE THREAD

**Issue by rubvaz** [louislam/uptime-kuma#1650]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

Hello,

I'm trying to add an Uptime Kuma’s snapshot to our mail repot. We use wkhtmltoimage to get the screenshot of other web pages, but when I try the same with Kuma I’m not able to get anything else than a blank image. We have a bash script, running in Debian.

Does anyone else have the same issue or is doing the same in other ways?

Thanks

### 🐻 Uptime-Kuma Version

1.15.0-debian

### 💻 Operating System and Arch

debian

### 🌐 Browser

It is linux bash

### 🐋 Docker Version

v20.10.11

**Comment by Drehmini** [comment]
This may be related to [This issue over on the wkhtmltopdf github](https://github.com/wkhtmltopdf/wkhtmltopdf/issues/3920) where the resources are relative pathed instead of absolute.

Either way, this is a wkhtmltoimage issue and, in my opinion, an issue should be raised there.

**Comment by rubvaz** [comment]
Thanks
