### ISSUE TITLE
monitor from many points of earth

### ISSUE THREAD

**Issue by gedw99** [louislam/uptime-kuma#1654]
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

Other

### 🔖 Feature description

its useful to monitor from many places to see network partitions.

### ✔️ Solution

thats easy but the dashboard and reporting is harder.

This requires peering between running points, with a global data view maintained.

if you using litestream you can instead just have a central DB with read only peers.

### ❓ Alternatives

none

### 📝 Additional Context

none

**Comment by CommanderStorm** [comment]
@gedw99 
We are consolidating duplicate issues a bit to make issue management easier.
I think, we should track this issue in #84 as there is no functional difference (maybe just small naming differences, but nothing that would require a different issue imo)
⇒ I am going to close this as a duplicate.
