### ISSUE TITLE
Incident history

### ISSUE THREAD

**Issue by MeijerM1** [louislam/uptime-kuma#1663]
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

UI Feature

### 🔖 Feature description

The ability to view a chronological list of past incidents with the following information:
- Incident title
- Creation date
- Close date
- Solution
The list can be displayed below the monitors.

### ✔️ Solution

See Feature description.

### ❓ Alternatives

-

### 📝 Additional Context

I think the incident model might have to be changed to add solution information and the close date.

Ideally an incident would contain a list of updates to track its progress but that might be out of scope for this feature.

**Comment by karelkryda** [comment]
See #1253

**Comment by MeijerM1** [comment]
> See #1253

Yeah that'll do it 😀
