### ISSUE TITLE
Distributed monitoring is recommended

### ISSUE THREAD

**Issue by xz-zone** [louislam/uptime-kuma#1664]
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

Other

### 🔖 Feature description

Can we add one to adopt distributed centralized monitoring? The false alarm of single area monitoring is a little high.

### ✔️ Solution

Add a distributed centralized monitoring

### ❓ Alternatives

NO

**Comment by philippdormann** [comment]
possible duplicate, see https://github.com/louislam/uptime-kuma/issues/84
