### ISSUE TITLE
Wrong Favicon

### ISSUE THREAD

**Issue by asdfgugus** [louislam/uptime-kuma#1668]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### Description

If you want to install the website as an app, it uses the wrong favicon. 
This gets a bit confusing as soon as you use multiple status pages. 

![wrong_favicon](https://user-images.githubusercontent.com/96517369/169645941-80a747b7-9eec-4fdf-9a06-a009cb1f59b5.png)

### 👟 Reproduction steps

1. Open a status page in any browser
2. Install it as an app 

### 👀 Expected behavior

It shows the configured favicon.

### 😓 Actual Behavior

It shows the default uptime-kuma favicon.

### 🐻 Uptime-Kuma Version

1.15.1

### 💻 Operating System and Arch

Windows / Android

### 🌐 Browser

Chromium 101.0.4951.67 (Brave 1.38.119)

### 🐋 Docker Version

Docker version 18.09.1

**Comment by tamasmagyar** [comment]
I am not sure if that is related to uptime-kuma. 

Seems like a chromium feature which fetches the current site's icon
source: https://support.google.com/chrome/thread/95114900/how-can-i-customize-edit-an-internet-shortcut-icon?hl=en

**Comment by louislam** [comment]
It should be fixed along with upcoming version 1.17.0, because previously the status page did not render meta tag and icon in the server side.

**Comment by louislam** [comment]
Oh, it is not fixed yet.

I found the actual issue. It is because the Uptime Kuma icon is hard coded in manifest.json. 

To fix this issue, the manifest.json should be dynamic generated.
