### ISSUE TITLE
MQTT Monitor Type - Timeout 

### ISSUE THREAD

**Issue by tam481** [louislam/uptime-kuma#1669]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

I am unable to monitor the status of an MQTT server. I specified the URL, Port, Username and Password but it keeps returning
'MQTT': Failing: Timeout | Interval: 60 seconds | Type: mqtt

I don't know how to diagnose this problem. I searched existing issues and found nothing.

### 🐻 Uptime-Kuma Version

1.15.1

### 💻 Operating System and Arch

Debian Bullseye on Raspberry Pi 4 ARM64

### 🌐 Browser

Google Chrome 100

### 🐋 Docker Version

20.10.16

**Comment by tulamidan** [comment]
I experience a similar issue. I get frequent timeout warnings - but have no reason to believe my broker has issues. The systems behaves normal and all mqtt clients get the data just fine.

**Comment by louislam** [comment]
I think it is logged in to your mqtt broker successfully, but Uptime Kuma don't receive topic response within 40 seconds.

**Comment by tam481** [comment]
@louislam I don't think that's the case here. I tried subscribing and kept sending a message to the topic to keep it updated and still got the timeout error.

@buliwyf42 the topic case matches exactly what's on the broker. I don't think that's the case here.

**Comment by tulamidan** [comment]
- I increased the test interval to 120s and I don't get any more errors. Before I got either a message with the topic value - or with the timeout error. Now I get the availability but no ping value and therefore the graph is empty.

**Comment by tulamidan** [comment]
Maybe the issue is not really an issue: If your topic is not updated within the timeframe of the kuma update interval - the test will fail.
Yet the mqtt broker might be happy and alive - so I am not sure what to suggest.

**Comment by EricDuminil** [comment]
FWIW, I was using a wildcard as a topic, to check if any sensor was sending data.

MQTT Monitor was connecting, and receiving messages. It still failed with TIMEOUT because of this check `messageTopic === topic`: https://github.com/louislam/uptime-kuma/blob/master/server/monitor-types/mqtt.js#L109 

`sensors/+` isn't exactly `sensors/xyz`, so this condition was never true. I'm not sure why this check is here. If a message is received while the client is subscribed to a topic, its topic must be correct.

**Comment by bkkoli** [comment]
@EricDuminil 
> If a message is received while the client is subscribed to a topic, its topic must be correct.

It is very helpful for me. Thank you

**Comment by 4ley** [comment]
> FWIW, I was using a wildcard ([+ or #](https://www.hivemq.com/blog/mqtt-essentials-part-5-mqtt-topics-best-practices/#heading-what-are-mqtt-wildcards-and-how-to-use-them-with-topic-subscriptions)) as a topic, to check if any sensor was sending data.
> 
> MQTT Monitor was connecting, and receiving messages. It still failed with TIMEOUT because of this check `messageTopic === topic`: https://github.com/louislam/uptime-kuma/blob/master/server/monitor-types/mqtt.js#L109
> 
> `sensors/+` isn't exactly `sensors/xyz`, so this condition was never true. I'm not sure why this check is here. If a message is received while the client is subscribed to a topic, its topic must be correct.

I hit the same issue. Wildcards are not possible.

**Comment by EricDuminil** [comment]
I simply removed the `if (messageTopic === topic)` check, and MQTT monitor worked perfectly fine with wildcards.

`sensors/#`, `sensors/+/info` received messages and the monitor was green. If I replaced the topic with an incorrect one, e.g. `typo/#` or `#/info`, no message was received, the monitor timed out and was red.

AFAICT, it shouldn't change the behavior for topics without wildcard.
