### ISSUE TITLE
bak files pile up in /app/data

### ISSUE THREAD

**Issue by jniggemann** [louislam/uptime-kuma#1671]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

I realized my docker container's volume was quite large (not large _per se_, but large for what I assume fit for uptime-kuma) and found the reason:
/app/data has some bak files
```
-rwxr-xr-x 1 root root  32K Sep 21  2021 kuma.db-shm.bak0
-rwxr-xr-x 1 root root  32K Oct 20  2021 kuma.db-shm.bak20211020083734
-rwxr-xr-x 1 root root  32K Dec 22 15:51 kuma.db-shm.bak20211222155147
-rwxr-xr-x 1 root root  32K Apr 10 11:14 kuma.db-shm.bak20220410111431
-rwxr-xr-x 1 root root  32K Sep 24  2021 kuma.db-shm.bak9
-rwxr-xr-x 1 root root    0 Sep 21  2021 kuma.db-wal.bak0
-rwxr-xr-x 1 root root    0 Oct 20  2021 kuma.db-wal.bak20211020083734
-rwxr-xr-x 1 root root    0 Dec 22 15:51 kuma.db-wal.bak20211222155147
-rwxr-xr-x 1 root root    0 Apr 10 11:14 kuma.db-wal.bak20220410111431
-rwxr-xr-x 1 root root    0 Sep 24  2021 kuma.db-wal.bak9
-rwxr-xr-x 1 root root  60K Sep 21  2021 kuma.db.bak0
-rwxr-xr-x 1 root root  35M Oct 20  2021 kuma.db.bak20211020083734
-rwxr-xr-x 1 root root 120M Dec 22 15:51 kuma.db.bak20211222155147
-rwxr-xr-x 1 root root 256M Apr 10 11:14 kuma.db.bak20220410111431
-rwxr-xr-x 1 root root 2.8M Sep 24  2021 kuma.db.bak9
```

Is it safe to delete those manually (or is there another way)?

### 🐻 Uptime-Kuma Version

1.13.2

### 💻 Operating System and Arch

Debian 11.3

### 🌐 Browser

various

### 🐋 Docker Version

Docker 20.10.16

**Comment by louislam** [comment]
The bak files will be created when updating from old a version to a new version.

If your current Uptime Kuma is working fine, you can delete those bak files. Be careful, don't remove the actual db in the same directory.

**Comment by jniggemann** [comment]
Thank you!
