### ISSUE TITLE
An Atom (RSS) feed for notifications (including the public)

### ISSUE THREAD

**Issue by JacksonChen666** [louislam/uptime-kuma#1673]
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

New Notification

### 🔖 Feature description

Add [RSS](https://en.wikipedia.org/wiki/RSS)/[Atom](https://en.wikipedia.org/wiki/Atom_(Web_standard)) feeds as a way of notifications.

### ✔️ Solution

Add a new notification method ([RSS](https://en.wikipedia.org/wiki/RSS)/[Atom](https://en.wikipedia.org/wiki/Atom_(Web_standard)) feeds).

Also, add an option of which feed should correspond to a status page on when modifying the status page.

### 📝 Additional Context

Some examples of real world use:
- User expressing how they used the RSS feeds (or Atom feeds) available: https://github.com/louislam/uptime-kuma/pull/124#issuecomment-924280278
- [Instatus](https://instatus.com/) example: https://status.sponsor.ajay.app/ (see "Get updates" button) ([Atom feed for SponsorBlock](https://sponsorblock.instatus.com/history.atom))
- [My website](https://jacksonchen666.com/feeds/)
- A client that can do RSS stuff: [Thunderbird](https://www.thunderbird.net/) ([help page](https://support.mozilla.org/en-US/kb/how-subscribe-news-feeds-and-blogs))

**Comment by Rhaal** [comment]
@louislam , quick question! Would you be willing to consider merging a PR for this issue if one was available ?

**Comment by JacksonChen666** [comment]
> @louislam , quick question! Would you be willing to consider merging a PR for this issue if one was available ?

this does not feel like a necessary question, except for the case for if the maintainer is OK with a feature like that.

there also seems to be a lot of positive reactions/support on my issue, so at least some people are likely looking for this feature.

i suggest that you start working on it, create a draft PR, and include `resolves #1673` somewhere in the description so that merging the PR closes this issue and this issue links to that PR ([feature doc](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/using-keywords-in-issues-and-pull-requests)).

**Comment by louislam** [comment]
Yes, better discuss before work, Uptime Kuma's pull request rules:
https://github.com/louislam/uptime-kuma/blob/master/CONTRIBUTING.md#can-i-create-a-pull-request-for-uptime-kuma

I usually accept notification pull requests, but how RSS could be a notification type in Uptime Kuma? It is because for most current notification providers such as Telegram, it makes a request to Telegram API in order to send a notification. However, RSS is just a xml, it doesn't seem to be a notification type in my opinion.

**Comment by JacksonChen666** [comment]
@louislam RSS feeds are more of a "pull" model (client periodically pulls information), and the current notification in uptime kuma is more of a "push" model (server sends a notification which is pushed to the client).

i think i'm starting to see this idea fall apart.

**Comment by Rhaal** [comment]
Hi everyone - absolutely agreed, and thanks for taking the time to point me to the Contribution guidelines - I should really have read them beforehand!
I've opened the PR for discussion, and I do acknowledge your concerns are super-valid; however I'd say RSS is just another kind of view apart from HTML, used by clients that conveniently have periodic polling built within them. If you both agree I'd move the discussion on the feasibility to the draft PR as to not pollute the issue.
