### ISSUE TITLE
Website and logo title name change.

### ISSUE THREAD

**Issue by therblxgod** [louislam/uptime-kuma#1676]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

Hi I want to change the name the website name and logo but i can’t find out how?

### 🐻 Uptime-Kuma Version

1.11.3

### 💻 Operating System and Arch

Windows

### 🌐 Browser

Chrome

**Comment by Computroniks** [comment]
This is not currently a feature that is available and it is unlikely to be enabled in the future. See #607 and https://github.com/louislam/uptime-kuma/pull/1083#issuecomment-1096662487 for more details.

**Comment by KorenMarvin** [comment]
It is possible to change the title if you really want.
![image](https://user-images.githubusercontent.com/36482784/197192031-ae0d3512-ea5f-438e-8355-43af2314178c.png)

This can be done by adding some css styling in the dist/index.html:

`header span[data-v-6080d853] {
    font-family: 'Montserrat', sans-serif!important;
    font-weight: 800!important;
    font-size: 0px!important;
}
	.title[data-v-6080d853]:after {
    font-weight: 700;
    content: "MK Vision Status";
    font-family: 'Montserrat', sans-serif!important;
    font-weight: 800!important;
    font-size: 22px;
    margin-left: 8px;
}`

Offcourse this is cheating a little bit ;-)

Offcourse you can change the logo from the dist/ folder also. Just overwrite icon.svg/png :-)
