### ISSUE TITLE
Push type Monitor - Discord Alert

### ISSUE THREAD

**Issue by DasCanard** [louislam/uptime-kuma#1678]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### Description

If you create a Heartbeat Monitor and set up a Discord alert, an empty service URL will be shown in the message because of course there is none.

### 👟 Reproduction steps

1. Create Heartbeat Monitor
2. Create Discord Alert
3. Link Heartbeat Monitor to the Discord Alert

### 👀 Expected behavior

![image](https://user-images.githubusercontent.com/17070204/169901836-df851737-49ca-41ba-aac3-2db8d10d7c4e.png)

### 😓 Actual Behavior

![image](https://user-images.githubusercontent.com/17070204/169901372-feeb6c7f-980f-4f52-bab6-8aadd7d896c0.png)

### 🐻 Uptime-Kuma Version

1.15.1

### 💻 Operating System and Arch

Ubuntu 20.04 64bit

### 🌐 Browser

Edge

**Comment by karelkryda** [comment]
I think it's fixed by #1471

**Comment by karelkryda** [comment]
hmmm, looks like it's not fixed for push type?

**Comment by DasCanard** [comment]
I think it would be the best if the whole "Server URL" line would be remove on push type monitors and discord notifications

**Comment by Lordreider** [comment]
how can i delete the link in the embed?
