### ISSUE TITLE
Dashboard produces a scrollbar although there's enough space

### ISSUE THREAD

**Issue by arminus** [louislam/uptime-kuma#168]
**Describe the bug**
The dashboard produces a scrollbar although there's enough vertical space - I think this was not the case in earlier versions

**To Reproduce**
Just load the dashboard

**Expected behavior**
No scrollbar if there's enough space

**Screenshots**
![2021-08-04_110621](https://user-images.githubusercontent.com/683680/128154307-e281ab0e-bd29-48f1-8a7d-40852f324295.png)

**Desktop (please complete the following information):**
 - Uptime Kuma Version: 1.0.10
 - Using Docker?: Yes
 - OS: Ubuntu 20.04
 - Browser: Firefox, Edge and Chrome

**Comment by Saibamen** [comment]
PR: https://github.com/louislam/uptime-kuma/pull/170

**Comment by louislam** [comment]
Fixed in https://github.com/louislam/uptime-kuma/commit/6251f470506f2b00faff7e9ca3942abe587bcf32
