### ISSUE TITLE
Add Notification  Line  Messaging API

### ISSUE THREAD

**Issue by Prawit109arm** [louislam/uptime-kuma#1680]
### ⚠️ Please verify that this bug has NOT been raised before.

- [x] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

I have created a channel bot line and invited my friends but I only see the api bot, others can't see it.

- I'm the only channel admin.
- Channel access token my
- My User-ID

I followed the steps as follows.
Line Developers Console - Messaging API
First access the [Line Developers Console](https://developers.line.biz/console/), create a provider and channel (Messaging API), then you can get the channel access token and user ID from the above mentioned menu items.
<img src="https://www.img.in.th/images/4e8b6a93dcc8b225f81b0905106505be.png" alt="4e8b6a93dcc8b225f81b0905106505be.png" border="0" />

### 🐻 Uptime-Kuma Version

Uptime Kuma Version: 1.15.1

### 💻 Operating System and Arch

ubuntu20

### 🌐 Browser

Google Chrome

**Comment by Computroniks** [comment]
This seems like an issue with the notification service and not Uptime Kuma its self. Perhaps you might be better raising the issue with their support.
