### ISSUE TITLE
Add new monitor fails

### ISSUE THREAD

**Issue by PP-JN-RL** [louislam/uptime-kuma#1682]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### Description

This is a clean install on a Rocky 8.6 host, running docker version 20.10.16 using image docker pull louislam/uptime-kuma:1.
After pressing the save button at the bottom of the page, it fails with the error message: Lost connection to the socket. Reconnecting...

I can reprduch the same issue on a Centos host, however not on a Windows host running WSL
![Screenshot 2022-05-24 104353](https://user-images.githubusercontent.com/52716446/170002776-f2fe9700-a479-4ae1-b231-65db1c55d83e.png)
.

I can however import a backup and that works fine, even when editing and saving an imported monitor.

### 👟 Reproduction steps

1. Installed as per instructions on docker hub.
2. Set username and password
3. Add monitor + save
4. Page reload

### 👀 Expected behavior

The monitor should be saved

### 😓 Actual Behavior

Error message appreas and monitor does not get saved

### 🐻 Uptime-Kuma Version

1.15.1

### 💻 Operating System and Arch

Rocky 8.6, Centos 8

### 🌐 Browser

Edge

### 🐋 Docker Version

20.10.16

### 📝 Relevant log output

```shell
This happens after the error message:
2022-05-24T09:49:57.864829565Z 2022-05-24T09:49:57.864Z [AUTH] INFO: Login by token. IP=X.X.X.X
2022-05-24T09:49:57.866110871Z 2022-05-24T09:49:57.865Z [AUTH] INFO: Username from JWT: Administrator
2022-05-24T09:49:57.872023058Z 2022-05-24T09:49:57.871Z [AUTH] INFO: Successfully logged in user Administrator. IP=X.X.X.X
```

**Comment by louislam** [comment]
- Have the container actually stopped or restarted?
- Can you reproduce the issue in the demo site? https://demo.uptime.kuma.pet/

**Comment by PP-JN-RL** [comment]
Yes, I have restarted the container a few times, just to make sure it wasn't down to the inital SQLite setup.
I found that after I import a backup, I'm able to edit and add monitors. Not sure if this help?

I can't reproduce the issue on the demo site, or under WSL on Windows. But I can sonsitently reproduce it on a Rockey 8.6 and Centos 8 host.

**Comment by CommanderStorm** [comment]
Really unsure what was happening here.
I think, given that I cannot reproduce this on other linux OS'es, that this issue is resolved.
