### ISSUE TITLE
advanced statistics on status range (public)

### ISSUE THREAD

**Issue by rems25000** [louislam/uptime-kuma#1683]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

I am looking to activate advanced statistics on the status pages (public) as can be found on the dashboard.
![image](https://user-images.githubusercontent.com/97801362/170018855-5f70c0b4-e5d5-4191-a42d-5f37ff344a3c.png)

### 🐻 Uptime-Kuma Version

1.15.1

### 💻 Operating System and Arch

debian x64

### 🌐 Browser

firefox

### 🐋 Docker Version

no

### 🟩 NodeJS Version

last

**Comment by karelkryda** [comment]
It's not possible at this moment, but someone already opened issue with request to implement this feature.

**Comment by Computroniks** [comment]
Just linking the issue here, #1480
