### ISSUE TITLE
DateTime entry in dashboard is misleading

### ISSUE THREAD

**Issue by arminus** [louislam/uptime-kuma#169]
**Is your feature request related to a problem? Please describe.**
The DateTime entry in the dashboard is IMHO misleading. As long as there is no down event, it simply shows the date and time the entry was originally added (which is kind of meaningless?) I would have expected it to show the date and time of the last successful check?

**Describe the solution you'd like**
If there's a reason to keep it the way it is, I'd qualify the DateTime column somehow (i.e. don't call it DateTime but use a different term describing what it really is).

**Describe alternatives you've considered**
Alternatively, 2 columns might make sense, on for the current DateTime (date and time of the last "event" ?) and a 2nd column for the date and time of the last successful check?

**Additional context**
Other than that, great piece of software!

**Comment by chakflying** [comment]
I felt this while debugging some issues as well. The row at the top only shows when the first "Down" occurred, but it doesn't give any confidence as to what the status is now. Here are my thoughts on the possible alternatives:

- We add a row at the top of the records table, which always display the latest heartbeat time and its status. This will allow us to at least confirm the latest response, when it was checked and what happened.
or,
- We change the DateTime field to display a time range if the same event continues for more than 1 heartbeat. If it continues to be down but the message is different, we display a new item. This will be even more informative, but would require quite a bit of re-engineering of the logic of `monitor_notification`.

@louislam how do you feel about this?

**Comment by louislam** [comment]
The "DateTime" column describes the time of occurrence. It is how it looks like in UptimeRobot too.

Since the datetime of the last successful check always equals to (DateTime - interval), I prefer to keep one DateTime column only.

> but it doesn't give any confidence as to what the status is now.

I agree, but I prefer to implement something similar to UptimeRobot's "Latest downtime". The event list remains untouched.

UptimeRobot screeenshot:
<img src="https://user-images.githubusercontent.com/1336778/128302179-088c31b0-013a-4256-8be4-c434f92757ce.png" width="500" />

**Comment by arminus** [comment]
It's clearer in UptimeRobot's UI, they use the term "event" and latest events, this is missing in your UI, hence, the information is IMHO potentially misleading.
