### ISSUE TITLE
Customize notifications for twitter

### ISSUE THREAD

**Issue by elax46** [louislam/uptime-kuma#1691]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

I would need to customize a minimum of notifications by posting tweets someone has had similar needs? to automatically post use

`twitter://$TWITTER_CONSKEY/$TWITTER_CONSSECRET/$TWITTER_ACCTOKEN/$TWITTER_ACCSECRET/?mode=tweet`

### 🐻 Uptime-Kuma Version

1.15.1

### 💻 Operating System and Arch

proxmox

### 🌐 Browser

chrome

### 🐋 Docker Version

20.10.9

**Comment by Computroniks** [comment]
Currently there is no notification provider for twitter but you could try using the webhook notification and calling twitter's API. If you know about programming you could also take a crack at creating a new notification provider for twitter.
