### ISSUE TITLE
Improving the login system and adding a new page to add new users.

### ISSUE THREAD

**Issue by shawn3308** [louislam/uptime-kuma#1692]
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

Other

### 🔖 Feature description

I was thinking that you could directly ask for a username and password whenever we run the installation script so that whenever we reach out to the site it doesn't ask the new user to create my account there and add a page where we can add new users.

### ✔️ Solution

So whenever we are done setting up this monitor and go to the site you already have an username and a password to log in with so it will not ask you to create a account over there and if you want to invite one of your friends to the panel there should be a page where you can add your friends email ID and password so that they can login into the monitor.

**Comment by ShadowGaming100** [comment]
> ### ⚠️ Please verify that this feature request has NOT been suggested before.
> * [x]  I checked and didn't find similar feature request
> 
> ### 🏷️ Feature Request Type
> Other
> 
> ### 🔖 Feature description
> I was thinking that you could directly ask for a username and password whenever we run the installation script so that whenever we reach out to the site it doesn't ask the new user to create my account there and add a page where we can add new users.
> 
> ### ✔️ Solution
> So whenever we are done setting up this monitor and go to the site you already have an username and a password to log in with so it will not ask you to create a account over there and if you want to invite one of your friends to the panel there should be a page where you can add your friends email ID and password so that they can login into the monitor.
> 
> ### ❓ Alternatives
> _No response_
> 
> ### 📝 Additional Context
> _No response_

create new user 
#128

**Comment by CommanderStorm** [comment]
@shawn3308 
We are consolidating duplicate issues a bit to make issue management easier.
I think, we should track this issue in #128 as there is no functional difference (maybe just small naming differences, but nothing that would require a different issue imo)
⇒ I am going to close this as a duplicate.
