### ISSUE TITLE
"Ignore TLS error" do not recover from backup

### ISSUE THREAD

**Issue by ShadowGaming100** [louislam/uptime-kuma#1694]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### Description

i created a monitor with tag then created a status page then when check the status page not showing the tag

ticked all the options of status page

![5A6D5F76-FD11-4048-9C25-DCE1BD86322F](https://user-images.githubusercontent.com/81495140/170565080-a955d8f1-2237-4157-bae5-0767babd9b96.png)

**ignore TLS error in monitor from backup**

When loading a backup from the other website version 1.16.0.beta.0 i ticked ignore TLS Error but when i load it shows i ticked but is showing but when the website is down is showing **Client network socket disconnected before secure TLS connection was established**
![EDA6BBCE-DEA5-4A77-B042-628660942ED6](https://user-images.githubusercontent.com/81495140/170564210-42483c6a-a0ea-4848-af5c-1f2b2ae0527e.jpeg)
![F7998263-3F0B-42B5-8DDA-CA71A7F24FC5](https://user-images.githubusercontent.com/81495140/170564226-28c09f7a-d5cf-48a2-b522-1186b28ea938.jpeg)

### 👟 Reproduction steps

**Tag Problem in status**

1. I created a monitor 
2. added tag 
3. created a status page
4.  tick everything then save

**ignore TLS error in monitor from backup**
1. i created a backup from 1.16.0-beta.0 
2. uploading to 1.16.0 

### 👀 Expected behavior

**Tag Problem in status**
to show tag in status page

 **ignore TLS error in monitor from backup**
ignore TLS error from my website

### 😓 Actual Behavior

**Tag Problem in status**
doesn’t show tag in status page

**ignore TLS error in monitor from backup**
not Ignoring TLS  error from the website 

### 🐻 Uptime-Kuma Version

1.16.0

### 💻 Operating System and Arch

Linix

### 🌐 Browser

Chrome Latest

### 🟩 NodeJS Version

Latest

**Comment by Rezanans-wow** [comment]
I can confirm issue about tag

**Comment by Rezanans-wow** [comment]
Same about tags, not showing

**Comment by louislam** [comment]
I cannot reproduce, may need a video or detailed steps,

![image](https://user-images.githubusercontent.com/1336778/170830476-1d7ac160-4bd4-46f0-85c3-4dbb2b7234f8.png)

**Comment by Rezanans-wow** [comment]
> I cannot reproduce, may need a video or detailed steps,
> 
> ![image](https://user-images.githubusercontent.com/1336778/170830476-1d7ac160-4bd4-46f0-85c3-4dbb2b7234f8.png)

My laptop so slow. I cant record video, maybe AnyDesk?

**Comment by louislam** [comment]
Oh, I forgot to update to 1.16.0, now I can reproduce.

1.16.0-beta.0 is ok in this case.

**Comment by louislam** [comment]
It will be released in the next version.

**Comment by ShadowGaming100** [comment]
> It will be released in the next version.

you mean that ignore TLS error doesn’t recover from backup

**Comment by ShadowGaming100** [comment]
> It will be released in the next version.

what about ignore TLS error recover from backup
