### ISSUE TITLE
Be able to monitor specific domains, routes and even files for changes.

### ISSUE THREAD

**Issue by cocoonkid** [louislam/uptime-kuma#1699]
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

New Monitor

### 🔖 Feature description

Be able to monitor specific domains and routes for changes.

A check that runs every few hours and creates a hash fingerprint and a screenshot of a specific target domain.
Alerts if anything changed. Maybe even for specific files.

Configurable with xpath, regex, css selectors.

### ✔️ Solution

Be able to monitor specific domains and routes for changes.

### ❓ Alternatives

There are alternatives but coupled with Kuma would be better :-)

### 📝 Additional Context

https://github.com/edgi-govdata-archiving/awesome-website-change-monitoring

https://github.com/dgtlmoon/changedetection.io

**Comment by DomiiBunn** [comment]
I'm not sure how that's meant to be helpfull on an uptime monitor?

**Comment by dorianborovina** [comment]
I suppose you need something like this?

https://github.com/dgtlmoon/changedetection.io
