### ISSUE TITLE
X-Forwarded-For and X-Real-IP headers are ignored when logging

### ISSUE THREAD

**Issue by pericoloso69** [louislam/uptime-kuma#1703]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### Description

Don't know if it is really a bug or a feature request ^^ :

When using Uptime Kuma behind a reverse proxy (nginx with a configuration matching the one mentionned on the project), the IP address displayed in the log is the IP address of the proxy. The reverse proxy configuration is good (the "X-Forwarded-For" and "X-Real-IP" headers are filled correctly by the proxy), but these headers are ignored by Uptime Kuma.
It prevents, by example, the use of fail2Ban to ban IP addresses trying to log on the app.

### 👟 Reproduction steps

Use Uptime Kuma behind nginx, try to login from outside your network and check the system logs.

### 👀 Expected behavior

I expect something like :
<blablabla> [AUTH] INFO: Login by username + password. IP=<internet IP address>

### 😓 Actual Behavior

If the reverse proxy and Updtime Kuma are running on the same server, you should see :
<blablabla> [AUTH] INFO: Login by username + password. IP=127.0.0.1

### 🐻 Uptime-Kuma Version

1.16.1

### 💻 Operating System and Arch

Debian testing/bookworm

### 🌐 Browser

Firefox

**Comment by pericoloso69** [comment]
I'm not a pro of Node, but I can help solving this issue by updating the *getClientIp(socket)* defined in *server/server.js* to use these headers.

(and I didn't mention it because it as nothing to do with this issue, but this app is cool and simple as I expected :))

**Comment by louislam** [comment]
I changed it to feature-request, as Uptime Kuma is a websocket, I don't know if it can get X-Forwarded-For header.

**Comment by prohand** [comment]
Good morning,

Have you been able to make progress on this feature request?

Thanks

**Comment by chakflying** [comment]
I think this should be closed with #1862.

**Comment by prohand** [comment]
Ok thank you, i enable this option and is OK : 

![image](https://user-images.githubusercontent.com/20227162/232586298-3bcd78fb-0d83-4d03-a636-2dcf0cbc532b.png)

**Comment by CommanderStorm** [comment]
@pericoloso69 this is  resolved as commented by prohand abvoe, right?
