### ISSUE TITLE
stated 100% uptime should be lower

### ISSUE THREAD

**Issue by faultydev** [louislam/uptime-kuma#1705]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### Description

The uptime of a few of my services isn't 100%; they we're down a couple of times for a couple of minutes. Therefore the uptime is <100%.
Yet, the app is showing 100%.

---

![image](https://user-images.githubusercontent.com/17108809/170892978-26aeaa14-0947-4eb7-9dfb-38665d11b73f.png)

![image](https://user-images.githubusercontent.com/17108809/170893009-e4d4d02c-737d-4f07-b317-b5b9d8effa19.png)

### 👟 Reproduction steps

add services.
turn the service off.
turn them on, give it time.
100%!?

### 👀 Expected behavior

the status percentage be <100%.

### 😓 Actual Behavior

the status percentage is 100%

### 🐻 Uptime-Kuma Version

1.15.1

### 💻 Operating System and Arch

Debian

### 🌐 Browser

firefox 100.0.2-1

**Comment by Computroniks** [comment]
I am pretty sure that that is your 24 hour uptime. If you look at your second picture, there are two values for uptime, 24 hours and 30 days. The 30 days one is at 99.97% which would make sense if the services had been down for a few minutes. The reason that the 24h one is at 100% is that the services haven't gone down in the past 24 hours.

**Comment by faultydev** [comment]
Hmm, that seems to be true...
It would be lovely to see a "in the last 24h" and/or a way to change that.
Maybe I'll open up a FR!
Thanks anyways!
