### ISSUE TITLE
What happens when you run multiple instances of uptime kuma sharing the same data? How does the Sqlite lock mechanism works in such case?

### ISSUE THREAD

**Issue by jananathbanuka** [louislam/uptime-kuma#1706]
### ⚠️ Please verify that this bug has NOT been raised before.

- [x] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

I am running uptime kuma in a kubernetes environment and it has 3 pods up and running sharing the same data volume. My question is, since it uses `sqlite` as the data source and if it has locking mechanism in place, it (locking) should not be shared between these pods. How it has been implemented in the code level?

Could someone help me on this?

### 🐻 Uptime-Kuma Version

1.15.1

### 💻 Operating System and Arch

MacOs

### 🌐 Browser

Google Chrome

**Comment by louislam** [comment]
Uptime Kuma is not a stateless service, so single instance only.

**Comment by jananathbanuka** [comment]
Can we use `kubernetes` statefulset?

**Comment by daoudzd** [comment]
Can you give us the option to connect uptime-kuma to another database like PostgreSQL other than SQLite?

**Comment by daoudzd** [comment]
> Not familiar with k8s, as long as it is a single node + local volume, it is working.


Can you give us the option to connect uptime-kuma to another database like PostgreSQL other than SQLite?
