### ISSUE TITLE
Editing HTML content

### ISSUE THREAD

**Issue by SamuelleDX** [louislam/uptime-kuma#1708]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

Hello,

I don't figure out how to edit the HTML content.
I would like to personnalise it for my customers.

Which files should I edit?

Thank you

### 🐻 Uptime-Kuma Version

1.16.1

### 💻 Operating System and Arch

Ubuntu 20.04 x64

### 🌐 Browser

Brave 1.39.111

### 🟩 NodeJS Version

14.19.3

**Comment by louislam** [comment]
Also read https://github.com/louislam/uptime-kuma/blob/master/CONTRIBUTING.md for how to build the project.
