### ISSUE TITLE
The push message is displayed in the wrong time zone.

### ISSUE THREAD

**Issue by lxq1** [louislam/uptime-kuma#1709]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### Description

The push message is displayed in the wrong time zone.

The actual server running time is Beijing time, 2022-6-01 09:37
The time when Feishu's robot sends the alarm message is 2022-6-01 01:37

![image](https://user-images.githubusercontent.com/19929230/171312277-70c1600d-62cf-4186-aa5e-935d3c6bd1e6.png)

### 👟 Reproduction steps

Set the alarm message push of the port

### 👀 Expected behavior

Normal message push is server time

### 😓 Actual Behavior

实际的时间是UTC

### 🐻 Uptime-Kuma Version

1.15.1

### 💻 Operating System and Arch

centos7.9

### 🌐 Browser

chrome 100

**Comment by louislam** [comment]
Duplicate of #40
