### ISSUE TITLE
Save last query and response and show it somewhere

### ISSUE THREAD

**Issue by SpcCw** [louislam/uptime-kuma#171]
**Is your feature request related to a problem? Please describe.**
Currently there is only HTTP response code and latency showing which sometimes makes diagnostics difficult.

**Describe the solution you'd like**
It would be great to store both query and server response somewhere (last query per each monitor only) so these can be consulted to see how exactly check fails. It shouldn't be displayed prominently on the dashboard - maybe add a button in monitor properties or settings which opens a popup with this information?

**Describe alternatives you've considered**
If you own the monitored server and have access you can check the log :) However if you monitor some third party service it can get trickier. 

**Additional context**
For example I tried adding some Peertube instances to monitor and they fail with code 406 while curl from the same machine connects to them just fine with code 200. Seeing exact query and response could shed some light. Same with adding keyword checks - it is not always clear what exactly server returned.

**Comment by binarydad** [comment]
I'm following this more for the issue regarding adding a Peertube instance and getting back HTTP 406. I can set up a TCP ping on 443 and it works fine. Still curious as to why 406 is returned.

**Comment by SpcCw** [comment]
Some related discussion here in case someone is searching: https://github.com/louislam/uptime-kuma/issues/180#issuecomment-894487104
