### ISSUE TITLE
Custom Notification Post Data

### ISSUE THREAD

**Issue by MariusGGS** [louislam/uptime-kuma#1715]
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

New Notification, UI Feature, Other

### 🔖 Feature description

At the moment the notification is a blanket up/down message which cannot be changed. 

When certain services are expected to go down from time to time, an auto-restart might be useful, however proper data cannot be sent as the post data the notification sends cannot be changed. 

### ✔️ Solution

Add an option to make your own POST json body&headers for sending the notification, so custom messages and custom POST requests can be made upon downtime

**Comment by MWGMorningwood** [comment]
A good example of this that I was able to utilize through UptimeRobot with custom JSON data loaded into the webhook.
It would post a Discord embed that you can include any information you'd like on, as you're creating it.

This would be especially useful if they get around to #1053 as well

**Comment by CommanderStorm** [comment]
@MariusGGS 
I think this is a duplicate of https://github.com/louislam/uptime-kuma/issues/975
If you agree, could you please close this Issue, as duplicates only create immortal zombies and are really hard to issue-manage?
If not, what makes this issue unique enough to require an additional issue? (Could this be integrated into the issue linked above?) ^^

This could also have been resolved by https://github.com/louislam/uptime-kuma/pull/3088 which was merged into the [`1.23` release](https://github.com/louislam/uptime-kuma/milestone/34)

**Comment by MariusGGS** [comment]
@CommanderStorm I saw that one, but I believe they are quite different so I made a separate request

#975 seems to be asking for the ability to customize in a more user friendly way existing text sent to an existing notification channel with the possibility of having variables to indicate service name, service status(up/down) & etc. 

This one does require the variables as well so I can use e.g `$name` as a placeholder for the actual name of the service, but it asks for the ability to customize the **entire json** not just the text within it so I am able to use this with my own custom APIs or existing services without having to change them to fit Uptime Kuma's json data

For example, maybe I'd want to just send this data to a URL of my choice 
{"id":"$id","name":"$name","status":"$status","token":"some custom token I put in for authentication"}

**Comment by MariusGGS** [comment]
@CommanderStorm The issue I made was in  Jun 2, 2022

#3088  was first added in April, and pulled in just last week, so this was done way after this issue was made and I was unaware of it. Closing for now, will test and see if there's anything missing.

I need variables/placeholders for this(which exist in the templating feature you sent) to be able to get the information such as name, status, etc.
