### ISSUE TITLE
Checking for dependency before alerting

### ISSUE THREAD

**Issue by VashStampedeTRI14** [louislam/uptime-kuma#1717]
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

New Notification, UI Feature

### 🔖 Feature description

Looking to be able to set upstream dependencies preventing mass alerting on several objects when an entire location is down.

### ✔️ Solution

So if X goes down Y and Z do not alert and you receive an alert for X only.

**Comment by Computroniks** [comment]
This is tackled by #1236

**Comment by VashStampedeTRI14** [comment]
Thank you. Did not catch that one in my search.
