### ISSUE TITLE
when updating 

### ISSUE THREAD

**Issue by ShadowGaming100** [louislam/uptime-kuma#1725]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

when i am updating uptime kuma is changing branch 

### 🐻 Uptime-Kuma Version

1.16.1

### 💻 Operating System and Arch

Linix

### 🌐 Browser

Chrome

### 🟩 NodeJS Version

latest

**Comment by Computroniks** [comment]
Are you checked out onto a different branch other than master? Which branch is it changing to? Could you possibly provide the log output?

**Comment by ShadowGaming100** [comment]
> Are you checked out onto a different branch other than master? Which branch is it changing to? Could you possibly provide the log output?

no i am at master

**Comment by ShadowGaming100** [comment]
changing to status-page-inject-html

**Comment by Computroniks** [comment]
What command did you run to upgrade?

**Comment by ShadowGaming100** [comment]
cd XUptime

# Update from git
git fetch --all
git checkout 1.16.1  --force

# Install dependenies and prebuilt
npm ci --production
npm run download-dist

> What command did you run to upgrade?

**Comment by ShadowGaming100** [comment]
![Uploading 82A18344-B43F-4ADC-B696-48298A8124A9.png…]()

**Comment by ShadowGaming100** [comment]
![Uploading B05F5CE6-B7EF-4654-8E6B-49664702FAE8.png…]()

**Comment by Computroniks** [comment]
At what point does it change over to `status-page-inject-html`

**Comment by ShadowGaming100** [comment]
Fetching origin
remote: Enumerating objects: 200, done
remote: Counting objects: 100% (182/182), d
one.
remote: Compressing objects: 100% (81/81),
done.
remote: Total 200 (delta 127), reused 143 (
delta 101), pack-reused 18
Receiving objects: 100% (200/200), 649.93 K
iB | 3.44 MiB/s, done.
Resolving deltas: 100% (128/128), completed
with 21 local objects.
From https://github.com/louislam/uptime-kum
a
334cb57.. fb420fa
master
-> origin/m
aster
201a25c..091158¢
status-page-inject-htm
1
-> origin/status-page-inject-html
* [new branch]
status-page-optimize
>
origin/status-page-optimize
* [new tag]
1.16.1
-> 1.16.1
Previous HEAD position was 334cb57 Update
+
o 1.16.0
HEAD is now at 857e88b Update to 1.16.1

**Comment by ShadowGaming100** [comment]
> At what point does it change over to `status-page-inject-html`

after git checkout 1.16.1

**Comment by Computroniks** [comment]
You are not changing branch here. Git is just saying that a new branch that exists on origin has also been downloaded onto your local device. This is just what `git fetch --all` does.

**Comment by ShadowGaming100** [comment]
> You are not changing branch here. Git is just saying that a new branch that exists on origin has also been downloaded onto your local device. This is just what `git fetch --all` does.

oh thanks for explaining me
