### ISSUE TITLE
Status page not reflecting monitor state

### ISSUE THREAD

**Issue by Coolie1101** [louislam/uptime-kuma#1729]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### Description

Monitors on status page (http://192.168.200.209:3001/status/test) does not reflect the status on the monitors on the dashboard.

### 👟 Reproduction steps

Create status page and add monitors.

### 👀 Expected behavior

Both dashboard and status page monitor stats should be the same.

### 😓 Actual Behavior

Paused monitors in dashboard shows as online in status page.

### 🐻 Uptime-Kuma Version

1.16.1

### 💻 Operating System and Arch

Raspbian 10 (buster)

### 🌐 Browser

Google Chrome 102.0.5005.63

### 🐋 Docker Version

Docker 20.10.16, build aa7e414

**Comment by daeho-ro** [comment]
I think the status page is for the public, so the status should be up or down only whenever the monitoring is paused or not.

**Comment by Computroniks** [comment]
> I think the status page is for the public, so the status should be up or down only whenever the monitoring is paused or not.

Yes, this is correct. Currently, if a monitor is paused, the status is shown as the last heartbeat before it was paused. I think that this is the best solution as I am not sure if it should be public that a monitor is paused.

**Comment by Coolie1101** [comment]
> I think the status page is for the public

> I think that this is the best solution as I am not sure if it should be public that a monitor is paused.

Makes sense, thanks.
