### ISSUE TITLE
Adding "/status" to "custom monitor domain" show all monitors

### ISSUE THREAD

**Issue by pm-pm** [louislam/uptime-kuma#1737]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### Description

When adding a customer sub-domain for a customer monitor page it works, but if you add "/status" to your costomer sub-domain, the customer can see all monitors.

Is this correct? Is there a mistake on my side?

### 👟 Reproduction steps

**my**domain.org -> My main domain uptime-kuma. OK
**my**domain.org/status/default -> Show ALL my monitors. OK

customer.**his**domain.net -> (If configured) Show ONLY CUSTOMER monitor page. OK
customer.**his**domain.net/**status** -> **Show ALL my monitors. NOT OK.**

### 👀 Expected behavior

Customer should only see his monitors

### 😓 Actual Behavior

customer can see all monitors.

### 🐻 Uptime-Kuma Version

1.16.1 - latest

### 💻 Operating System and Arch

Debian 11

### 🌐 Browser

Edge

**Comment by Computroniks** [comment]
This is because when you navigate to /status, the page that has the `default` slug will be loaded. If you just delete this page or change its slug it should work fine

**Comment by louislam** [comment]
Yes, it is expected behavior, as `/status` was introduced before custom domain.

**Comment by pm-pm** [comment]
OK. Just for information:
This just means that any custom domain user can see all the monitors simply by appending /status.

**Comment by louislam** [comment]
In other words, `/status` is an alias of `/status/default`.

If you don't what to expose this, just change `default` to other slug name.
