### ISSUE TITLE
Deployment failure

### ISSUE THREAD

**Issue by zxmacc** [louislam/uptime-kuma#1739]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

I want to deploy to fly. io, but I don't know why the deployment failed.

## uptime-kuma:base-debian
![W ~MATCB JR7~5)`PN}S6 D](https://user-images.githubusercontent.com/71143103/172652890-3b290cc7-29ec-4506-83c4-ae174e6ac181.png)
## uptime-kuma:base-alpine
![6JOEI(}81`S(IP {W$A}A8](https://user-images.githubusercontent.com/71143103/172654087-fdc4fd45-54e9-4a04-a7b3-ac2f1de7c27c.png)

### 🐻 Uptime-Kuma Version

1.16.1

### 💻 Operating System and Arch

20.10.12 linux x86_64

### 🌐 Browser

Microsoft Edge 102.0.1245.33

### 🐋 Docker Version

Unknown, possibly new

**Comment by zxmacc** [comment]
It even seemed to be working, but suddenly it wasn't
（Cry ）QAQ，I don't know why~~~~~

**Comment by Computroniks** [comment]
Have you checked out these links related to the issue:
https://fly.io/docs/getting-started/troubleshooting/
https://community.fly.io/t/failed-due-to-unhealthy-allocations/199/8

**Comment by zxmacc** [comment]
> 您是否查看了与该问题相关的以下链接：https://fly.io/docs/getting-started/troubleshooting/ https://community.fly.io/t/failed-due-to-unhealthy-allocations/199/8

I tried to modify the port, but the same problem still appeared

**Comment by zxmacc** [comment]
I tried for three hours, but it still didn't work

**Comment by chakflying** [comment]
Unfortunately I think fly.io has modified init which has trouble with `chown`. I remember when I deployed to fly.io I had to modify `entrypoint.sh`. Removing lines `8-16` should do.

**Comment by zxmacc** [comment]
> Unfortunately I think fly.io has modified init which has trouble with . I remember when I deployed to fly.io I had to modify . Removing lines should do.`chown``entrypoint.sh``8-16`

Thanks for your help. Looks like it's working

But it seems to be dead again


![OG3NPT{SQ@9}_ODOG7D GL5](https://user-images.githubusercontent.com/71143103/172755952-f149af1b-0e3a-420c-ad5f-2fea5745ec94.png)

**Comment by chakflying** [comment]
Looks like you are missing the compiled frontend files. You can get those by running `npm run setup` in the local directory.

**Comment by zxmacc** [comment]
deployed successfully!!!!!!
Thank you. Thank you both. Thank you very much！！！！！！！！

**Comment by Macejdo** [comment]
Hi. I have the same issue. How can I modify the entrypoint.sh on Windows ?
