### ISSUE TITLE
Send another alert when service is back UP.

### ISSUE THREAD

**Issue by CorneliousJD** [louislam/uptime-kuma#174]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
The alerts when a services goes down is great, but I also would like the ability to be alerted when the service is back UP a well.
Sometimes a service may only be down for 5-10 minutes and come back up on its own, but right now the "down" alert is the only one triggerred.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A - should be self explanatory. 

Thank you in advance for the considseration.

**Comment by louislam** [comment]
It should send UP/DOWN notifications in current implementation. 

If you confirm that there is no UP notifications, please report back with more details.

 
![image](https://user-images.githubusercontent.com/1336778/128361916-3a490d19-7687-47c0-a66c-91209c1e65fe.png)

**Comment by CorneliousJD** [comment]
I'm sorry it does work. I didn't do my due dilligence and check my SPAM filter.

The "Down" notice came through but the "Up" notice got caught by anti-SPAM.
Sorry :)
