### ISSUE TITLE
Continuous notifications

### ISSUE THREAD

**Issue by verymilan** [louislam/uptime-kuma#1742]
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

Other

### 🔖 Feature description

...which can be very annoying, however, there are situations where multiple services a "down", eg. due to some dns hickup or a restarted service with multiple components. It is very easy (for me) not to see when a single service actually keeps being down and it is only shown on the dashboard.

### ✔️ Solution

For such an instance it would be nice to have a configurable interval where a "Still down" notification is being sent out as a reminder that something didn't get back up (or is not a false alarm but actually down).

**Comment by williamstlr** [comment]
Same thing for me, I'll miss a notification and can go a few days before I notice that I missed it, having an option for a repeating notification would be great.

**Comment by chakflying** [comment]
Should be closed with #1212.

**Comment by CommanderStorm** [comment]
A bit clearer message:

@verymilan
Could you close this issue? (only you or louis can do so)
This Feature has been released in the `1.18`-Release and is currently avalible in this form:
![image](https://github.com/louislam/uptime-kuma/assets/26258709/f6f4a0d1-a948-4ea5-bc10-5ca494d5e2b0)

**Comment by verymilan** [comment]
aye, happy to have it available :)
