### ISSUE TITLE
uptime.kuma.pet

### ISSUE THREAD

**Issue by heffneil** [louislam/uptime-kuma#1743]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

I noticed I have a lot of DNS requests on my system for uptime.kuma.pet.  Why is this?  I don't want my install providing information to a third party?  I just changed DNS servers this morning and have 1500 queries for that domain name?

### 🐻 Uptime-Kuma Version

1.12.1

### 💻 Operating System and Arch

Ubuntu 20.1

### 🌐 Browser

Chrome

**Comment by siimots** [comment]
Maybe bug in older version for too frequent requests, but you can disable it here:
uncheck "Show update if available"
![image](https://user-images.githubusercontent.com/7014925/172773319-6bf5be08-35ec-4e1f-a73b-e27dc4658e67.png)

**Comment by Computroniks** [comment]
Can you provide the result of `pm2 status`

**Comment by Computroniks** [comment]
Ok, you are on docker, instead run `docker events --filter event=restart --since=60m`. This will show if the container is constantly restarting or not

**Comment by heffneil** [comment]
Yup that was the problem!  I didn't know it but I was using my old NFS directory which for some reason causes restarts! I didn't know it was restarting a docker ps showed it hasn't been up more than a minute.  So each start it will hit that domain name?

**Comment by Computroniks** [comment]
Most likely

**Comment by tofran** [comment]
Regardless solving the restarts and disabling update checks, uptime-kuma still makes requests to `uptime.kuma.pet` every 24h.

If you actually block kuma.pet the system continues to wok as expected. But would make sense to stop this behaviour.

The affecting code is here:
https://github.com/louislam/uptime-kuma/blob/6d22ebedcaf44bcd8d69591afd5f83e3f4f63b6d/server/check-version.js#L11-L23

We should change the `if (await setting("checkUpdate") === false)` to happen before making the request.
I will submit a PR.

**Comment by tofran** [comment]
Regardless solving the restarts and disabling update checks, uptime-kuma still makes requests to `uptime.kuma.pet` every 48h.

If you actually block kuma.pet the system continues to wok as expected. But would make sense to stop this behaviour.

The affecting code is here:
https://github.com/louislam/uptime-kuma/blob/6d22ebedcaf44bcd8d69591afd5f83e3f4f63b6d/server/check-version.js#L11-L23

We should change the `if (await setting("checkUpdate") === false)` to happen before making the request.
I will submit a PR.
