### ISSUE TITLE
Monitor website behind sso

### ISSUE THREAD

**Issue by Ekouyoja** [louislam/uptime-kuma#1744]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

Hello,

I try to monitor some websites that are protected by sso (cas and oidc). To be sure to be understood, i try to access test.local that is redirected to cas.local, when the auth is ok then it redirect back to test.local
But i didn't understand how to do that with uptime-kuma, someone have exemples to show me ? 
Thanks for the beautifull work

### 🐻 Uptime-Kuma Version

1.16.1

### 💻 Operating System and Arch

rocky 8

### 🌐 Browser

Chrome 102

### 🟩 NodeJS Version

14.18.2

**Comment by christopherpickering** [comment]
Currently, I'm just assuming if the redirects are working that the site is up, I don't do login. It would be cool! ... it would be even more difficult if your sso server required 2 part with the text code.

You can always set the max redirects to 0 and then check the status code in kuma.

**Comment by Ekouyoja** [comment]
The problem is that sometimes the redirect works but after the login i get 500 error. Maybe i will do some scenario on zabbix.
Thanks for your answer.
