### ISSUE TITLE
Philips Hue Bridge, MyQ Bridge & Rheem Water Heater Ping Down, but devices up

### ISSUE THREAD

**Issue by petebocken** [louislam/uptime-kuma#1748]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

Just installed Uptime Kuma. I have 3 devices (Philips Hue hub, Chamberlain MyQ Bridge, and a Rheem Water Heater that is reporting Ping down ever since I added them.  I can ping all IPs in Terminal on the Ubuntu PC just fine.

### 🐻 Uptime-Kuma Version

1.16.1

### 💻 Operating System and Arch

Ubuntu 22.04 LTS

### 🌐 Browser

Firefox 101.0.1

### 🐋 Docker Version

Docker 20.10.17

**Comment by louislam** [comment]
If I remembered correctly, it is expected behavior.

Try to ping inside Uptime Kuma's container by:

```
docker exec -it uptime-kuma bash
```

You need to add this in your docker run command:

`--add-host=host.docker.internal:host-gateway` 

Or add this in your docker-compose:

```
 extra_hosts:
      - "host.docker.internal:host-gateway"
```

Reference: https://stackoverflow.com/questions/70725881/what-is-the-equivalent-of-add-host-host-docker-internalhost-gateway-in-a-comp

**Comment by petebocken** [comment]
> Try to ping inside Uptime Kuma's container by:
> 
> ```
> docker exec -it uptime-kuma bash
> ```

I can ping these 3 devices just fine inside the container.

I'm pretty new to docker. Where is the docker-compose file located?

**Comment by petebocken** [comment]
Got it working now, thanks!

1. Got container ID: 'docker container ls -a'
2. Stopped the container: `docker container stop {container ID}`
3. Removed the container: `docker container rm {container ID}`
4. Re-added the container: `docker run --add-host=host.docker.internal:host-gateway -d --restart=always -p 3001:3001 -v uptime-kuma:/app/data --name uptime-kuma louislam/uptime-kuma:1`
