### ISSUE TITLE
What about add no-response action to remove some issues automatically?

### ISSUE THREAD

**Issue by daeho-ro** [louislam/uptime-kuma#1750]
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

Other

### 🔖 Feature description

There are too many issues.

### ✔️ Solution

Something like https://github.com/lee-dohm/no-response, we can eliminate no-response issues.

For example, once contributor comments on any issue and add the label "waiting-for-response", then the github action will check and remove the issue that is not updated for certain dates.

**Comment by Computroniks** [comment]
This is a must. Perhaps the github stale action would also be an option here

**Comment by louislam** [comment]
I deleted stale-bot previously, because it closed feature-request unexpectedly. If anyone know what is wrong, it can be added back.

https://github.com/louislam/uptime-kuma/commit/e0175d00

**Comment by Computroniks** [comment]
Hmm, not sure about what went wrong but https://github.com/probot/stale is the action that I seem to see quite a lot across some other repos. I am not sure how different it is to github stale action but it could be worth a try

**Comment by fionnb** [comment]
As it is the countless unclosed non-issues are making it really hard to avoid duplicates.
