### ISSUE TITLE
SSL

### ISSUE THREAD

**Issue by gokkstudio** [louislam/uptime-kuma#1758]
### ⚠️ Please verify that this bug has NOT been raised before.

- [x] I checked and didn't find similar issue

### 🛡️ Security Policy

- [x] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

Hi all, how do you add a self-signed SSL certificate to Kuma?

I have fresh VPS with Ubuntu, installed latest versions of Portainer (which has SSL) and Kuma.
Thanks

### 🐻 Uptime-Kuma Version

1.16.1

### 💻 Operating System and Arch

Ubuntu 22.04

### 🌐 Browser

Chrome 102.0.5005.115

**Comment by louislam** [comment]
`SSL_KEY` and `SSL_CERT`

https://github.com/louislam/uptime-kuma/wiki/Environment-Variables

**Comment by willy695** [comment]
> `SSL_KEY` and `SSL_CERT`
> 
> https://github.com/louislam/uptime-kuma/wiki/Environment-Variables

I have same problem, how/where do I use enviroment variables? I ask because im new to ubuntu and uptime kuma and would really appreciate some guidance on how to do this
