### ISSUE TITLE
LunaSea Notification

### ISSUE THREAD

**Issue by lsultana98** [louislam/uptime-kuma#176]
Hi,

Quick one regarding LunaSea notifications. I have set it up and when pressing send get these "sent successfully" message. However I never receive the test or any of the down/up notifications. Is there something I am missing?

**Comment by louislam** [comment]
Their API is always returning OK even the device token is incorrect.
```
curl -X POST 'https://notify.lunasea.app/v1/custom/device/testhahahah'
```

```
{"message":"OK"}
```

So make sure your token is correct.
