### ISSUE TITLE
PVE安装的uptime-kuma 安装3001端口打不开，日志也没找到

### ISSUE THREAD

**Issue by haohao232323** [louislam/uptime-kuma#1783]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

在PVE虚拟机下安装了uptime-kuma，子啊安装成功后3001端口并不能打开

### 🐻 Uptime-Kuma Version

最新版

### 💻 Operating System and Arch

pveproxy（Debian）

### 🌐 Browser

Microsoft Edge 版本 102.0.1245.39 (正式版本) (64 位)

**Comment by louislam** [comment]
You should try to provide more info, so other people can help you.
