### ISSUE TITLE
Add SquadCast notification

### ISSUE THREAD

**Issue by caiohasouza** [louislam/uptime-kuma#1788]
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

New Notification

### 🔖 Feature description

Add support to [Squadcast](https://www.squadcast.com/) notifications.

### ✔️ Solution

It's possible to use the "[Incident Webhook](https://support.squadcast.com/docs/apiv2)" Squadcast integration.

### 📝 Additional Context

I'm tryed use the "Webhook" integration but the payload is different, so i have 400 error.

**Comment by kisahm** [comment]
+1
