### ISSUE TITLE
Installing the script with node on Shared Hosting

### ISSUE THREAD

**Issue by Twenty4marc** [louislam/uptime-kuma#1789]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

Hey, wonderful code.
I cloned this repo on my shared server with node and did all the istallation tasks.
How exactly can I now access my site?

### 🐻 Uptime-Kuma Version

idk

### 💻 Operating System and Arch

idk

### 🌐 Browser

idk

### 🐋 Docker Version

idk

### 🟩 NodeJS Version

14.10.1

**Comment by daeho-ro** [comment]
Your server ip + 3001 port?
