### ISSUE TITLE
error login

### ISSUE THREAD

**Issue by ShadowGaming100** [louislam/uptime-kuma#1792]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### Description

![66EF3CF3-6883-4E9E-93C4-3CAC42C2D9DE](https://user-images.githubusercontent.com/81495140/174499885-bd70f618-495f-476a-8172-f034dc623589.jpeg)

![0F3EB33D-CA32-4830-95D2-B556C7909D3B](https://user-images.githubusercontent.com/81495140/174499875-644c7976-0021-4d5f-a4d2-351f045609c6.jpeg)

![9410D8ED-60AB-4728-AA1D-972B5FAF9A93](https://user-images.githubusercontent.com/81495140/174499013-67d39017-dd9c-4a73-8b3b-1abef7a3efd9.jpeg)

It showed you are not login but when reload the page i didn’t logout

### 👟 Reproduction steps

login
check monitor 
go to settings/notifications 
add certificate notification expires in
click save
delete certificate notification expires in 
click save
add certificate notification expires in
click save
test notification 

shows you are not login 

### 👀 Expected behavior

send test notification

### 😓 Actual Behavior

showed you are not login

### 🐻 Uptime-Kuma Version

1.17.0-beta.1

### 💻 Operating System and Arch

Linix

### 🌐 Browser

Google Chrome

### 🟩 NodeJS Version

Latest

### 📝 Relevant log output

```shell
Error: You are not logged in.
at exports. checkLogin(/home/runner/XUp
time-Beta/XUptime/server/util-server.is:522
: 15)
at Socket.<anonymous> (/home/runner/XUp
time-Beta/XUptime/server/server.is:1122:17)
at Socket.emit (node:events:394:28)
at Socket.emit (node:domain:475:12)
at Socket.emitUntyped(/home/runner/XUp
time-Beta/XUptime/node_modules/socket.io/di
st/typed-events.js:69:22)
at /home/runner/XUptime-Beta/XUptime/no
de modules/socket.io/dist/socket.js:466:39
at processTicksAndRejections (node: inte
rnal/process/task queues: 78:11)
```

**Comment by ShadowGaming100** [comment]
where is the error log file

**Comment by louislam** [comment]
I cannot reproduce the issue with your steps. Is it reproducible every time in your side?

**Comment by ShadowGaming100** [comment]
> I cannot reproduce the issue with your steps. Is it reproducible every time in your side?

no

**Comment by ShadowGaming100** [comment]
it happens when the server just started then in the middle it starts  to run again 

example 
started server
few seconds 
letter it tells start server
but it tells the program is already running 

then when i open the web after sometime it shows the error

**Comment by louislam** [comment]
Same reason as #1814, Replit is not supported.
