### ISSUE TITLE
List of cheatsheet for all monitor into Ubuntu 20 from scratch 

### ISSUE THREAD

**Issue by johnfelipe** [louislam/uptime-kuma#1799]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

I want to documentation cheatsheet style for all monitor for Ubuntu 20 from scratch 

### 🐻 Uptime-Kuma Version

Latest

### 💻 Operating System and Arch

Ubuntu 20

### 🌐 Browser

Chrome

**Comment by louislam** [comment]
Uptime Kuma is using SQLite, if you need some SQL, you can query the monitor list from the database (./data/kuma.db by default) and build it by any programming languages.

**Comment by Computroniks** [comment]
If you are asking how to monitor a server, just use one of the preexisting monitors. The pint monitor is the simplest, just put in the IP of the   server to monitor and it will tell you if it is up.

If you want to integrate Uptime Kuma with an external service, you can use the /metrics page with a client able to parse Prometheus metrics.

**Comment by johnfelipe** [comment]
![SNAG-1326](https://user-images.githubusercontent.com/428820/174806663-3634a8d7-7a9b-44aa-ab4a-89938ff60ce8.png)

that way, im lost, sorry for noob questions

**Comment by johnfelipe** [comment]
![SNAG-1327](https://user-images.githubusercontent.com/428820/174807677-b93f21ad-11f2-49bb-b36f-ebf97eec9bbc.png)

ok is working now, i change felipe with ip of host

**Comment by johnfelipe** [comment]
If you want to integrate Uptime Kuma with an external service, you can use the /metrics page with a client able to parse Prometheus metrics.

Can u guide me for test prometheus

**Comment by johnfelipe** [comment]
metrics page kuma:

https://gist.github.com/7fa71812948a2265fae7d22bd4d58f5b

metrics page prometheus

https://gist.github.com/231a812535776e290c33fc89b4cda9da

pls guide me for test all of them

for example which one client able to parse Prometheus metrics is better?

**Comment by johnfelipe** [comment]
anyone?

**Comment by Computroniks** [comment]
You are missunderstanding the use of prometheus. You should set your uptime instance as a target in your prometheus config. Prometheus is the software that collects the data.

Here are some articles
https://prometheus.io/docs/introduction/overview/
https://www.howtogeek.com/devops/what-is-prometheus-and-why-is-it-so-popular/
https://www.digitalocean.com/community/tutorials/how-to-install-prometheus-on-ubuntu-16-04
