### ISSUE TITLE
Clustering - HA uptime monitor

### ISSUE THREAD

**Issue by IIPoliII** [louislam/uptime-kuma#18]
I just saw about this awesome project and really congrats.
It was missing from the opensource side.

The only thing missing by my side is a way to make a cluster with it. Because if it would be possible to run it on 2 servers + at the same time it will assure the server running uptime-kuma will never go down! 😃

**Comment by Stetsed** [comment]
This isn't really something imo you would integrate into the project, but would use your reverse proxy for(Load balancing), with a check to see which one is up. 

If you mean to be able to sync settings etc between the 2 then I might agree this would be useful.

**Comment by louislam** [comment]
Uptime Kuma is a kind of socket server and it is not a stateless service. For my current implementation, It is hard to achieve real clustering.

Docker Swarm + GlusterFS/NFS maybe a good choice if you accept small downtime. Add a uptime-kuma service with 1 replica, and sync the volume with GlusterFS/NFS.

In this setup, when uptime-kuma is down, Docker swarm will quickly spin up another node.
