### ISSUE TITLE
HTTP 406 when using Peertube instances

### ISSUE THREAD

**Issue by binarydad** [louislam/uptime-kuma#180]
When adding a Peertube instance (or at least mine,  https://video.binarydad.com), I get back a HTTP 406 rather than 200. The site is up, and running curl/wget on the server does indicate a HTTP 200. 

Using a TCP ping on port 443 works just fine, however. 

Thanks!

**Comment by SpcCw** [comment]
It is not a bug but rather lack of options implementation (like described in https://github.com/louislam/uptime-kuma/issues/11)

Update Kuma sends the following Accept header with the request:
`"application/json, text/plain, */*"'`
...and Peertube doesn't like it.

You can test it yourself with:
`curl -I -H 'Accept:"application/json, text/plain, */*"' -H 'User-Agent:Uptime-Kuma'  https://video.binarydad.com`

Note that no Accept header or text/html works fine so it is Peertube that rejects certain headers on certain URLs.

So the solution would be implementing HTTP options as in https://github.com/louislam/uptime-kuma/issues/11. Meanwhile TCP port ping is not so good for determining web host health obviously but you can use PeerTube API URLs which respond to to these headers fine, e.g. https://video.binarydad.com/api/v1/config/about - you can do even make keyword check.
