### ISSUE TITLE
New http monitors add port as empty string

### ISSUE THREAD

**Issue by joe-eklund** [louislam/uptime-kuma#1802]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### Description

Hello-

I am attempting to write my own RESTful API for Uptime Kuma and have been poking around the database. I noticed that if I add a new https monitor through the Uptime Kuma gui, the `port` column in the database is added as an empty string. 

Well in my RESTful API I am going to enforce strict type checking at the API level (both incoming and outgoing data using [pydantic](https://pydantic-docs.helpmanual.io/usage/types/)), so I want to enforce this to be an `INTEGER` only or `NULL`. This is because a port **cannot** be anything other than an `INTEGER`.

I noticed that in previous Uptime Kuma builds (months ago), https monitors had the value of `port` as `NULL`, then it was changed somewhere along the way to be empty strings.

Now I see [SQLite embraces dynamic type checking](https://www.sqlite.org/flextypegood.html), but am wondering if this was a conscious design decision to make new `port` entries an empty string as opposed to `NULL`. I can make my API handle empty strings as well, but I would prefer making it a strict `NULL` or `INTEGER`. I wanted to check if it was a bug first though. I would argue that if the front end only allows an `INTEGER` to be selected (which is the case), then it is a bug. :) 

-Joe

### 👟 Reproduction steps

1. Make a new https monitor.
2. Look in the database and see `port` is an empty string, not `NULL`.

### 👀 Expected behavior

I would expect a monitor without a used `port` to be added as `NULL`.

### 😓 Actual Behavior

It is added as an empty string.

### 🐻 Uptime-Kuma Version

1.16.1

### 💻 Operating System and Arch

MacOS 11.6.6

### 🌐 Browser

Chrome Version 102.0.5005.115

### 🐋 Docker Version

Docker version 20.10.12, build e91ed5707e

### 📝 Relevant log output

```shell
Here is the output from my pydantic logs:


pydantic.error_wrappers.ValidationError: 1 validation error for Monitor
response -> 0 -> port
  value is not a valid integer (type=type_error.integer)
<class 'str'>
```
```

**Comment by chakflying** [comment]
Git blame this and maybe it goes back to @Computroniks on #1473.

**Comment by louislam** [comment]
I never thought we could insert a string into a integer field in SQLite... 

May need to enable strict mode later
```
https://sqlite.org/src/wiki?name=StrictMode
```

**Comment by joe-eklund** [comment]
> I never thought we could insert a string into a integer field in SQLite...
> 
> May need to enable strict mode later
> 
> ```
> https://sqlite.org/src/wiki?name=StrictMode
> ```
> 
> The issue should be fixed, thanks for the report.

Neither did I until I looked into it lol. Thanks for the fix!

**Comment by joe-eklund** [comment]
> I never thought we could insert a string into a integer field in SQLite...
> 
> May need to enable strict mode later
> 
> ```
> https://sqlite.org/src/wiki?name=StrictMode
> ```
> 
> The issue should be fixed, thanks for the report.

@louislam I have continued looking into the database and found that for example, you can enter in a `name` for a monitor that is longer than the 150 characters specified in the database table.

Looks like this has to do with [type affinity in sqlite only being recommended](https://www.sqlite.org/datatype3.html).

Are you aware of this? This is another side effect of sqlite being essentially "typeless." In my API I am building I want to as closely align with the behavior in the GUI, so if you don't check the name length I won't, etc. Do you plan on doing any kind of enforcement on the front end for these types (hehe) of things in the future?
