### ISSUE TITLE
ping to other network section not working

### ISSUE THREAD

**Issue by johnfelipe** [louislam/uptime-kuma#1804]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### Description

i have ping 192.168.0.xxx and all working, because kuma is installed in that section
but i want to ping 192.168.88.xxx, other section of my local network
https://drive.google.com/file/d/1hjzWq6UlV6XotvQOh3ZspyfMy8lq10wj/view?usp=drivesdk
that video show issue

### 👟 Reproduction steps

Pls view video;
https://drive.google.com/file/d/1hjzWq6UlV6XotvQOh3ZspyfMy8lq10wj/view?usp=drivesdk

### 👀 Expected behavior

ping correctly in all network sections

### 😓 Actual Behavior

only ping in section network of ubuntu kuma installed

### 🐻 Uptime-Kuma Version

Latest

### 💻 Operating System and Arch

Ubuntu 20

### 🌐 Browser

Chrome

### 🐋 Docker Version

Docker 20

**Comment by louislam** [comment]
This is Docker issue and expected, because container may not access your local network. You need some config.

Please read this:
https://github.com/louislam/uptime-kuma/issues/1748#issuecomment-1152866296

**Comment by johnfelipe** [comment]
https://drive.google.com/file/d/1iLeP7yV-caW0pHSGCFG3H21r0rKDotnv/view?usp=drivesdk

not working

**Comment by johnfelipe** [comment]
```
root@felipe:~/uptime-kuma# docker pull louislam/uptime-kuma:1
1: Pulling from louislam/uptime-kuma
c32ce6654453: Already exists
866efb834763: Already exists
3009c2701a70: Already exists
704508b5309b: Already exists
11cc6386a88d: Already exists
50694b369ddf: Already exists
d47b92313a6b: Already exists
43eee6140fa4: Already exists
e878accd8693: Already exists
080a0086763f: Pull complete
Digest: sha256:a4eab252e5a27ead9e92f04d755d6cc968be923b277aae42ac8cf633e2da3b15
Status: Downloaded newer image for louislam/uptime-kuma:1
docker.io/louislam/uptime-kuma:1
root@felipe:~/uptime-kuma# docker stop uptime-kuma
uptime-kuma
root@felipe:~/uptime-kuma# docker rm uptime-kuma
uptime-kuma
root@felipe:~/uptime-kuma# docker run --add-host=host.docker.internal:host-gateway -d --restart=always -p 3001:3001 -v uptime-kuma:/app/data --name uptime-kuma louislam/uptime-kuma:1
98a565aee33657fd2cee4bb237520705386cf57648c7b9245e1db47d2da26d11

```
pls view video
https://drive.google.com/file/d/1TDIi35eH3piCt5magXAw-3hrOJOm8yrz/view?usp=drivesdk

still not working with latest pull
