### ISSUE TITLE
How can translate status notification to spanish and other languages?

### ISSUE THREAD

**Issue by johnfelipe** [louislam/uptime-kuma#1810]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

Telegram:

```
My Telegram Alert (1) Testing
[UBUNTU21] [🔴 Down] Flip UP to DOWN
[UBUNTU21] [✅ Up]
```

Sendgrid

`[UBUNTU21] [🔴 Down] PING 192.168.0.13 (192.168.0.13) 56(84) bytes of data. --- 192.168.0.13 ping statistics --- 10 packets transmitted, 0 received, 100% packet loss, time 210ms
`

How can edit that templates to another languages?

### 🐻 Uptime-Kuma Version

Latest

### 💻 Operating System and Arch

Ubuntu 20

### 🌐 Browser

Chrome

### 🐋 Docker Version

Docker 20

**Comment by johnfelipe** [comment]
An of course in web page:

![SNAG-1334](https://user-images.githubusercontent.com/428820/174911210-14d423f7-f947-4585-a420-eb25c00a987a.png)

**Comment by johnfelipe** [comment]
anyone?

**Comment by chakflying** [comment]
#456 Please check for existing issues before posting.
