### ISSUE TITLE
No Slug

### ISSUE THREAD

**Issue by ShadowGaming100** [louislam/uptime-kuma#1814]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 👟 Reproduction steps

https://user-images.githubusercontent.com/81495140/174977361-55da5cd8-7881-4139-b849-35a1252f1b9e.MOV

### 👀 Expected behavior

create a status page

### 😓 Actual Behavior

no slug error

### 🐻 Uptime-Kuma Version

1.17.0-beta.1

### 💻 Operating System and Arch

Linix

### 🌐 Browser

Google Chrome

### 🟩 NodeJS Version

Latest

**Comment by louislam** [comment]
From your video, the connection was dropped during creation. I think your strange issues are related to Repit.

So please do not report bug if it is using Repit. Instead, VPS such as Oracle Cloud or Digital Ocean is recommended.

**Comment by ShadowGaming100** [comment]
> From your video, the connection was dropped during creation. I think your strange issues are related to Repit.
> 
> So please do not report bug if it is using Repit. Instead, VPS such as Oracle Cloud or Digital Ocean is recommended.

it happened two times the same way as the video
