### ISSUE TITLE
False 404 at /status/ with the trailing slash

### ISSUE THREAD

**Issue by ouuan** [louislam/uptime-kuma#1815]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### Description

After upgrading to 1.17.0, `/status/` returns 404 while `/status` returns 200. Though the user will see a working web page, I discovered this because my Uptime Kuma reports itself down due to the wrong status code.

### 👟 Reproduction steps

Visit <https://up.ouuan.moe/status/>

### 👀 Expected behavior

It returns 200

### 😓 Actual Behavior

It returns 404

### 🐻 Uptime-Kuma Version

1.17.0

### 💻 Operating System and Arch

Arch Linux 5.15.48-1-lts

### 🌐 Browser

Mozilla Firefox 101.0.1

### 🐋 Docker Version

Docker version 20.10.17, build 100c70180f

**Comment by ouuan** [comment]
Oops, I just discovered that it's `/status/` with the trailing slash that causes the 404, and `/status` returns 200.

**Comment by Computroniks** [comment]
> Experiencing false down status as well on 11 of the 36 monitors on v1.17. All monitors are setup in similar manner. No prob with v1.16.1.

This is not related the issue reported here. Please open a seperate issue.

**Comment by CommanderStorm** [comment]
Cannot reproduce.
Both `/status` and `/status` report as 404

![image](https://github.com/louislam/uptime-kuma/assets/26258709/5a9e8b9e-f56c-4f3b-9ee7-d66f5f36544f)
![image](https://github.com/louislam/uptime-kuma/assets/26258709/f41fa5de-70f1-473e-8b0a-af9a75c721e1)



=> closing as resolved

**Comment by ouuan** [comment]
> Cannot reproduce.
> Both `/status` and `/status` report as 404

How did you get that? I'm still able to reproduce.

curl:

![image](https://github.com/louislam/uptime-kuma/assets/30581822/1a1f63a8-bf4e-4d26-b827-c9017c050e8f)

Firefox:

![image](https://github.com/louislam/uptime-kuma/assets/30581822/96cb1a55-6b16-4d3a-a167-3f7978dcff67)

Chrome:

![image](https://github.com/louislam/uptime-kuma/assets/30581822/b122666a-57fc-4b8a-a82b-17e50687b801)

**Comment by phuoymakara** [comment]
@louislam 
Why my uptime kuma get **404 Not Found** with slug `/status`?

**my nginx config:**
```javascript
location / {
    proxy_pass         http://localhost:50277/;
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "upgrade";
    proxy_set_header Host $host;
   
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_set_header X-Real-IP $remote_addr;
    
}
``` 
![1-kuma](https://github.com/user-attachments/assets/331b9494-6417-4ba0-9566-0d801c2ef378)
![2-kuma](https://github.com/user-attachments/assets/41ff8447-addc-4fc8-bcde-91179ae53680)

**Comment by CommanderStorm** [comment]
Are you running the beta of V2 or V1? (The fix for this is only included in the first)

**Comment by phuoymakara** [comment]
It's running of V1

**Comment by louislam** [comment]
> @louislam Why my uptime kuma get **404 Not Found** with slug `/status`?
> 
> **my nginx config:**
> 
> ```js
> location / {
>     proxy_pass         http://localhost:50277/;
>     proxy_http_version 1.1;
>     proxy_set_header Upgrade $http_upgrade;
>     proxy_set_header Connection "upgrade";
>     proxy_set_header Host $host;
>    
>     proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
>     proxy_set_header X-Forwarded-Proto $scheme;
>     proxy_set_header X-Real-IP $remote_addr;
>     
> }
> ```
> 
> ![1-kuma](https://private-user-images.githubusercontent.com/115135485/389392620-331b9494-6417-4ba0-9566-0d801c2ef378.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI1MjYzODQsIm5iZiI6MTczMjUyNjA4NCwicGF0aCI6Ii8xMTUxMzU0ODUvMzg5MzkyNjIwLTMzMWI5NDk0LTY0MTctNGJhMC05NTY2LTBkODAxYzJlZjM3OC5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEyNVQwOTE0NDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kNGMyNjU1YmYxYTVlZTY0M2YxMjVlNzgwODRkZWFiZThjNWNmNjBhYzMxZDIwNGRhZWQ3YjZhZWMwMWNjZDgzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.-sxkC3VHEw8FkueE9E5KSdiUjKLxxKshE24rrpolipk) ![2-kuma](https://private-user-images.githubusercontent.com/115135485/389392684-41ff8447-addc-4fc8-bcde-91179ae53680.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI1MjYzODQsIm5iZiI6MTczMjUyNjA4NCwicGF0aCI6Ii8xMTUxMzU0ODUvMzg5MzkyNjg0LTQxZmY4NDQ3LWFkZGMtNGZjOC1iY2RlLTkxMTc5YWU1MzY4MC5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEyNVQwOTE0NDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04YjNjMTU4OTdjY2UzZmM2ZjYwZTdiMGYyNWUxZGEzZTU0Y2JhZGM4NWM0MjFhYzgwYzlhMTE1OWZmNjZkZGMxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.vYLQWoMX8mC0oVYEIG6J8Lg3KYVcapJwOgf4WUC6teA)

It is only available for early versions of Uptime Kuma that was only allowed one status page. If I remembered that correctly, you can name your status page slug `default` to use this endpoint.

**Comment by phuoymakara** [comment]
@louislam @CommanderStorm Thank you!
