### ISSUE TITLE
[Whatsapp] support notification provider

### ISSUE THREAD

**Issue by johnfelipe** [louislam/uptime-kuma#1816]
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

New Notification

### 🔖 Feature description

Whatsapp notification

### ✔️ Solution

Whatsapp notification

**Comment by rezzorix** [comment]
There is only the paid WhatsApp Business Platform which could achieve this.
There is no official free API or other method to send WhatsApp notifications.
There are work-arounds using WhatsApp web and apps/bots on Android but they all need access to the original app.

So big doubt that this is something that can be implemented.... but maybe someone proofs me wrong.

**Comment by lpadula** [comment]
Hi, now you have this new oficial free API: https://developers.facebook.com/docs/whatsapp/cloud-api

**Comment by PichlAlex** [comment]
API is free for first 1000 messages per month (this should be enough for most users)
if this limit is exceeded the messages are not delivered anymore and after adding a payment method, you can send more tan 1000 messages/month

so from my point of view this does not block the implementation
