### ISSUE TITLE
Add support for monitoring MySQL/MariaDB databases

### ISSUE THREAD

**Issue by derekoharrow** [louislam/uptime-kuma#1817]
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

New Monitor

### 🔖 Feature description

[PR1430 ](https://github.com/louislam/uptime-kuma/issues/1430) has just added the ability to monitor MS SQL Server DB's.

It would be good to also be able to monitor other popular DBs too - specifically MySQL/MariaDB which many people use.

### ✔️ Solution

Replicate the setup for MS SQL server, but with different connection methods and parameters to connect and test MySQL/MariaDB

### ❓ Alternatives

Currently doing a TCP Port test, but this only checks if the port is open, not whether a DB is actually available on that port and functioning.

**Comment by Iliannnn** [comment]
Would be very helpful

**Comment by petittitouan** [comment]
Yes because SQL check does not work for MySQL

**Comment by Computroniks** [comment]
I will have a look at implementing this tonight

**Comment by petittitouan** [comment]
Thanks

**Comment by petittitouan** [comment]
And a Good Idea would be to make clear that SQL monitor is in fact "MS SQL" Monitor, because it's really confusing

**Comment by Computroniks** [comment]
I have implemented this in #2151. If anyone is able to help test this it would be greatly appreciated.
