### ISSUE TITLE
Error: Cannot find module 'tar'

### ISSUE THREAD

**Issue by aniqueta** [louislam/uptime-kuma#1820]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

I'm on a non-Docker install and updating from 1.16.0 to 1.17.0 and I receive the following error, when using the update instructions here. My system has upgraded from Ubuntu 20.04 to 22.04 in the intervening time, so that may have something to do with this error. I'm running Node.js v18.4.0. I have installed `tar` as a global npm package, and that has not worked. Thank you in advance for the assistance.

```
> uptime-kuma@1.17.0 download-dist
> node extra/download-dist.js

Downloading dist
node:internal/modules/cjs/loader:949
  throw err;
  ^

Error: Cannot find module 'tar'
Require stack:
- /opt/uptime-kuma/extra/download-dist.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:946:15)
    at Module._load (node:internal/modules/cjs/loader:787:27)
    at Module.require (node:internal/modules/cjs/loader:1012:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/opt/uptime-kuma/extra/download-dist.js:3:13)
    at Module._compile (node:internal/modules/cjs/loader:1112:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1166:10)
    at Module.load (node:internal/modules/cjs/loader:988:32)
    at Module._load (node:internal/modules/cjs/loader:834:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:77:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/opt/uptime-kuma/extra/download-dist.js' ]
}

Node.js v18.4.0
```

### 🐻 Uptime-Kuma Version

1.16.0 to 1.17.0

### 💻 Operating System and Arch

Ubuntu 22.04 x86_64

### 🌐 Browser

N/A

### 🐋 Docker Version

N/A

### 🟩 NodeJS Version

18.4.0

**Comment by louislam** [comment]
Strange, can you check to run this again, because `npm install` should install `tar`.

```
npm install --production
```


If it is still not working, try to install manually (not globally)
```
npm install tar
```

**Comment by aniqueta** [comment]
Sadly no change. If it's any help, this step seems to hang for a minute or more while building. 
```
(#########⠂⠂⠂⠂⠂⠂⠂⠂⠂) ⠇ reify:@azure/abort-controller: sill audit bulk request {
```
I also tried deleting and reinstalling; and then it hung indefinitely on the above…

**Comment by aniqueta** [comment]
My current hypothesis is that somehow the build now takes much more memory than before. This is on a low cost 512MB memory instance. And watching the system stats, npm consumes all the memory and then it hangs. Closing other processes to free memory causes the update/build to progress further before crashing. Not sure why it needs much more memory than prior versions and seems like it can no longer be built on a low resource instance? Thanks.

**Comment by louislam** [comment]
What is your npm version?

```
npm -v
```

You may need to upgrade or downgrade your npm.

**Comment by aniqueta** [comment]
Thanks. It's 8.13.0.

**Comment by aniqueta** [comment]
On a Ubuntu 20.04 machine with more memory, there's no issue with NodeJS 18.4.0 and npm 8.13.0.

**Comment by aniqueta** [comment]
Running the following resolved the issues:
```
npm cache clear --force 
rm -rf /opt/uptime-kuma/node_modules/   
```
