### ISSUE TITLE
HTTP checks on non-standard ports reporting as down

### ISSUE THREAD

**Issue by webworxshop** [louislam/uptime-kuma#1821]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### Description

As of version 1.17.0, HTTP checks on non-standard ports are reporting as down. The resulting notification reports that the check in unable to reach port 80, which is wrong. See screenshot below:

![image](https://user-images.githubusercontent.com/4045282/175218683-d71ab234-a8c0-435a-958f-3680d4b14b46.png)

In this case the Jellyfin service is configured on port 8096.

### 👟 Reproduction steps

Create a check for a HTTP service on a non-standard port.

### 👀 Expected behavior

The service should be reported as up when it is up and down when it is down!

### 😓 Actual Behavior

The service is always reported as down.

### 🐻 Uptime-Kuma Version

1.17.0

### 💻 Operating System and Arch

Ubuntu 20.04

### 🌐 Browser

Doesn't matter

### 🐋 Docker Version

Docker 20.10.14

**Comment by ThomasChr** [comment]
Will take a look

**Comment by louislam** [comment]
I saw someone have also reported similar issue.
https://github.com/louislam/uptime-kuma/issues/1815#issuecomment-1163520947

But I cannot reproduce:
![image](https://user-images.githubusercontent.com/1336778/175223756-9a975bef-6c6b-4341-b4ae-671836f63d03.png)


Is there any special settings like proxy or basic auth etc?

**Comment by ThomasChr** [comment]
Can't reproduce on d5da5af174644121d3d9df90e4945a32ba79eaaa / 1.17.0
Tried with leading slash and without.

Looking forward to debugging more if I get more info, like @louislam said, there must be some special configuration.
As far as I can see the port is not treated specially. We're just filling an options struct for the axiosClient with the url and let it go it's merry way.

monitor.js:
![grafik](https://user-images.githubusercontent.com/13014163/175230109-0a04b71c-a3ed-4a1b-8ba0-ec368d314f3e.png)
![grafik](https://user-images.githubusercontent.com/13014163/175230177-014c27a1-f7cc-44f4-af4d-a32dd9578314.png)

There is some trickery involved with a proxy or ntlm though:
![grafik](https://user-images.githubusercontent.com/13014163/175230290-499c13ea-d005-401c-83e9-d468b6a15ce2.png)
![grafik](https://user-images.githubusercontent.com/13014163/175230339-438083ec-b764-40d6-a2ed-666e7f745b48.png)

**Comment by osc86** [comment]
3 http(s) services are reported down since my container was updated to 1.17 today. There's definitely an issue, 1 uses a custom port, the other 2 use standard port 443. All hosts are up and reachable from the container, I just checked with curl.
I'm not using a proxy, trying to find out what's different from the ones that still work.

**Comment by louislam** [comment]
I suspect it is related to axios dns cache (#1598) or ntlm (#1639).

monitor.js diff:
https://github.com/louislam/uptime-kuma/compare/1.16.1...1.17.0#diff-0c4874f149ad01732ad730f36c95c99e37f5c3f13e9b52f628e2e284daa72d27

**Comment by louislam** [comment]
Oh no, I found an issue, if I use the tailscale domain name instead of the ip, it goes down.

@osc86 @webworxshop Are you using similar domain name too?

![image](https://user-images.githubusercontent.com/1336778/175244055-8ab09fa4-b454-4e37-88cf-0bb6c9943cb9.png)

**Comment by mads03dk** [comment]
Confirming the issue:
![image](https://user-images.githubusercontent.com/16370656/175246043-7335f871-12cd-43e2-8eea-32034f225a04.png)

Got this overnight, right after auto-update.
If it's any help; this monitor is looking through a subdomain.

**Comment by maeries** [comment]
I have a similar looking issue, but I think the cause is different. I have a monitor for `http://wg-access-server:8000`, but I got `DOWN - connect ECONNREFUSED 172.30.0.4:80`, so a different port. If I set the port to something random like 1111, I get `DOWN - connect ECONNREFUSED 172.30.0.4:1111`.

I believe the issue is that there is a forward
```
$ curl -I wg-access-server:8000
HTTP/1.1 307 Temporary Redirect
Content-Type: text/html; charset=utf-8
Location: /signin
Date: Thu, 23 Jun 2022 08:04:24 GMT
```
and when uptime kuma follows that it kinda loses the port and checks for the standard port instead. If I set the monitor to `http://wg-access-server:8000/signin` it works

**Comment by louislam** [comment]
1.17.1 has been release, it should fix the issue.

**Comment by maeries** [comment]
It does

**Comment by louislam** [comment]
@JacksonChen666 It has been fixed, please read my previous comments in this thread.

**Comment by louislam** [comment]
@JacksonChen666
The issue title is not correct actually.

It hit the users who are using such as Wireguard/Tailscale networks with custom local domain only.

**Comment by webworxshop** [comment]
Wow, looks like this got some traction while I was AFK :smiley: 

@louislam Yes, I am using a domain name, but from my local DNS server, not tailscale.

I can confirm the issue is fixed with 1.17.1.

Thank you for the awesomely quick resolution and the great software!

**Comment by davidus05** [comment]
Regarding DNS cache: Why are we using this at all? We have three (and more) caches then, at least: DNS provider cache, local server DNS cache, Uptime Kuma cache, …

I think that this is not necessary or am I missing something?

**Comment by sevmonster** [comment]
> Regarding DNS cache: Why are we using this at all? We have three (and more) caches then, at least: DNS provider cache, local server DNS cache, Uptime Kuma cache, …

Depending on the configuration, there may not be a local cache. GNU/Linux does not cache DNS by default. Projects like systemd-resolvd (not often configured to run by default on many setups even if they use systemd), dnsmasq, etc are needed. If, in your setup, you are constantly querying DNS, you will see worse, sporadic performance out of Uptime Kuna. See the screenshot on #1598.
If you already have a local caching resolver, great. But this would explain the poor ping delay I was getting with Uptime Kuma, 200~300ms or more for local services where it should probably be less. There is also the case that your services will appear to go down if your upstream resolvers disappear.
