### ISSUE TITLE
Latest release seems to not respect /etc/hosts

### ISSUE THREAD

**Issue by wneessen** [louislam/uptime-kuma#1822]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### Description

I just installed the latest 1.17.0 release and a couple of monitors started to turn red after the update and stayed like this since. After a bit of investigation it turns out these are all monitors which have a specific hostname rewrite in the `/etc/hosts` file.

Background: the server serving these services runs behind the same firewall as the server running Uptime-Kuma. To avoid having to use NAT reflection, the Uptime-Kuma server has `/etc/hosts` entries that point the public DNS entries to the internal address of the server running the services. This way the traffic does not have to pass the firewall, go to the public internet and then go back into the same firewall, while keeping the original DNS entries intact.

With the latest update it seems these `/etc/hosts` entries seems to be not respected anymore.

### 👟 Reproduction steps

* Set up a monitor pointing to service.domain.tld
* Set up `/etc/hosts` entry for service.domain.tld to point to an internal address like 10.0.0.1
* See the uptime kuma monitor fail as it's trying to resolve the DNS only not respecting the `/etc/hosts`

### 👀 Expected behavior

The `/etc/hosts` entries should be respected

### 😓 Actual Behavior

The `/etc/hosts` entries are not respected

### 🐻 Uptime-Kuma Version

1.17.0

### 💻 Operating System and Arch

Arch Linux 5.15.41-1-lts

### 🌐 Browser

Any

### 🐋 Docker Version

-

### 🟩 NodeJS Version

18.2.0

**Comment by Stevehans** [comment]
Has this issue been reverted in version 2?

I have an smtp monitor and I have an entry in /etc/hosts for this, when I ping by name from bash it's fine, when I trace the traffic to port 25 it's using a public IP, not the entry in the hosts file.

**Comment by CommanderStorm** [comment]
This issue is from 2022 and sice nobody reported issues with it likely unrelated to your problem.

Could you open a new issue with full context of what you tried and how to reproduce it?
Thanks
