### ISSUE TITLE
Plex SSL certs a being tagged as self signed

### ISSUE THREAD

**Issue by mjefferys** [louislam/uptime-kuma#1824]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### Description

Since upgrading to 1.17 my plex monitor is reporting as down with the error saying the cert is self-signed.

Prior to 1.17 this was fine.

Plex provides SSL certs automagically to its instances on the plex.direct subdomain. As far as I can tell these are perfectly valid and not self-signed. Navigating to the address in a browser instance reports that the certificate is valid.
![image](https://user-images.githubusercontent.com/11043414/175286853-c4492a14-b7aa-4be4-a8cc-ec658589899a.png)

Yet uptime kuma reports it as invalid.
![image](https://user-images.githubusercontent.com/11043414/175285988-480f686d-0401-48b3-92a9-c8836ef1dc9e.png)

Ticking 'Ignore TLS/SSL error for HTTPS websites' also does nothing.

Happy to share a test URL privately to repro this.

### 👟 Reproduction steps

Add a plex instance as a monitor via its plex.direct url Ie:

https://127.0.0.1.509a3db652b64f15a0fe26fce4fa770f.plex.direct:32400/

### 👀 Expected behavior

Instance is monitored and up

### 😓 Actual Behavior

Instance is monitored and reports as down due to the  certificate being 'self-signed'

### 🐻 Uptime-Kuma Version

1.71.1

### 💻 Operating System and Arch

docker container

### 🌐 Browser

Chrome

**Comment by louislam** [comment]
> https://127.0.0.1.509a3db652b64f15a0fe26fce4fa770f.plex.direct:32400/

Unable to resolve the domain, is it correct?

**Comment by louislam** [comment]
It is working in my side.

You can test this in the demo site:
https://demo.uptime.kuma.pet/

![image](https://user-images.githubusercontent.com/1336778/175304290-cecaf568-b1d8-42dc-99af-49e57bc966e7.png)

**Comment by mjefferys** [comment]
Hmm, yes, confirmed also how weird.

My instance is just the default uptime-kuma docker container (louislam/uptime-kuma:latest) hosted on a debian vm I assume that demo site is also just that?

``` michael@mj-mon-01 ~> uname -as
Linux mj-mon-01 5.10.0-9-cloud-amd64 #1 SMP Debian 5.10.70-1 (2021-09-30) x86_64 GNU/Linux
michael@mj-mon-01 ~> cat /etc/debian_version
11.3 ```

**Comment by louislam** [comment]
My demo site server is CentOS, but I think it is not related.

- Try to spin up an temp Uptime Kuma container `uptime-kuma:1.16.1`, see if it is really a 1.17.1 issue.
- Try to go inside your uptime kuma container and use curl to the website.

```
docker exec -it uptime-kuma bash
```

**Comment by mjefferys** [comment]
Super weird, spun up a 1.16.1 and it was fine. Upgraded that instance to 1.17.1 and it was still fine. Deleted and recreated my main instance and it's back to being fine. No idea what happened! Apologies for cluttering things up can close as non-reproducible!
