### ISSUE TITLE
How to use domain names

### ISSUE THREAD

**Issue by ShadowGaming100** [louislam/uptime-kuma#1826]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

How to use domain steps can you pls write in steps and what code I need to use I am not using any proxy

### 🐻 Uptime-Kuma Version

Latest

### 💻 Operating System and Arch

Linix

### 🌐 Browser

Chrome

### 🟩 NodeJS Version

Latest

**Comment by G1cu** [comment]
https://github.com/louislam/uptime-kuma/wiki/Reverse-Proxy

**Comment by mqu** [comment]
I don't know how to use "domain names", in status page ; there is a field named "domain names" ; when I enter something, related to domains for services I want to manage, no thing append.

**Comment by mqu** [comment]
I found this documentation: https://github.com/louislam/uptime-kuma/wiki/Status-Page#domain-names-for-status-pages
