### ISSUE TITLE
Socket.io server stops working randomly

### ISSUE THREAD

**Issue by akinnee** [louislam/uptime-kuma#1829]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### Description

Pending ws requests: https://imgur.com/a/ckDmxJq

### 👟 Reproduction steps

Start the docker container with port 3001 forwarded
Everything works fine
Wait a few hours or days
Cannot connect to the socket server. [Error: websocket error] Reconnecting...
`docker-compose restart does not fix`
`docker-compose down && docker-compose up -d` fixes it temporarily

### 👀 Expected behavior

`docker-compose up -d`
Socket.io server keeps working forever!

### 😓 Actual Behavior

After a few hours or days: Cannot connect to the socket server. [Error: websocket error] Reconnecting...

### 🐻 Uptime-Kuma Version

1.16.1

### 💻 Operating System and Arch

Digital Ocean Docker Droplet

### 🌐 Browser

Chrome

### 🐋 Docker Version

 20.10.7, build f0df350

**Comment by louislam** [comment]
What is the server status & last server log if hanged?

**Comment by akinnee** [comment]
The service is still running when this happens. If I kill the container and bring it up again I can see it was running the checks and collecting data the whole time. I still get alerts as well but am unable to go see the status.

I'll grab logs next time I see it. Is there a way to filter down the logs so they don't include every alarm/status event?

**Comment by akinnee** [comment]
Thanks, I'll try that next time it happens. I suspected it might be a docker networking issue, especially since restarting it doesn't fix it, only fully stopping and starting again does. But I'm using digital ocean's docker droplet and basing my docker-compose.yml off the examples here, so that's pretty odd.

**Comment by CommanderStorm** [comment]
Given that @akinnee stated that he will report this information the next time it happens, I am going to close this as resolved
