### ISSUE TITLE
Real Browser - Monitoring dynamic web files to confirm they are updating

### ISSUE THREAD

**Issue by ClevedonWeather** [louislam/uptime-kuma#1835]
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

Other

### 🔖 Feature description

I find Uptime Kuma great but there is a feature that would be useful to me. I run a self hosted website, [https://www.clevedonweather.co.uk/] using Apache and Nginx Reverse Proxy Manager with Uptime telling with of any network issues.  Many of my web files/data is updated ever minute. Knowing if a file was not being updated would let me know a program has crashed and I can act on this. What would be helpful if it could monitor the time a file was last updated and inform me if it had not been updated within a given time period.

### ✔️ Solution

What would be helpful if it could monitor the time a file was last updated and be notified if it had not been updated within a given time period.

**Comment by CommanderStorm** [comment]
I am going to resolve this in favor of #3568 as said issue is more clear in how this should be monitored
