### ISSUE TITLE
Support access control for ntfy

### ISSUE THREAD

**Issue by MI3Guy** [louislam/uptime-kuma#1838]
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

Other

### 🔖 Feature description

ntfy supports requiring a username and password to publish a notification for tops. See [Access control](https://ntfy.sh/docs/config/#access-control).

### ✔️ Solution

I would like to utilize access control in ntfy. Would it be possible to add support for setting the username and password?

**Comment by rolfbachmann** [comment]
Hi @philippdormann. Have you already done something on this topic? I recently implement this feature and had some time to test it today. Work as expected.

I haven't done the commits/pull-requests yet, but I can if you like?

**Comment by mustanggb** [comment]
May as well share the PR as I was looking at working on this also.
