### ISSUE TITLE
Project might want to consider a rename

### ISSUE THREAD

**Issue by Aterfax** [louislam/uptime-kuma#184]
Somewhat childish I know, but the pronunciation of Kuma is tragically the same as some newer internet colloquial which may be undesirable: [Coomer](https://www.urbandictionary.com/define.php?term=coomer)

**Comment by louislam** [comment]
No, Kuma（クマ / 熊）means bear 🐻 in Japanese.

A little bear is watching your website.🐻🐻🐻

**Comment by Aterfax** [comment]
I know :) but I suspect that westerners might get a giggle. No worries!
