### ISSUE TITLE
IPv6 missing in Docker Container

### ISSUE THREAD

**Issue by Cheatha** [louislam/uptime-kuma#1842]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### Description

My kuma can't monitor IPv6-only services. I'm running several IPv6-enabled Docker containers on my monitoring-server and they're working well, so it's neither my general docker config nor my server config . I can even access my uptime-kuma via IPv6. But adding an IPv6-only hosts results in `[DOWN] connect EADDRNOTAVAIL`. Which is no surprise, because after checking the container itself didn't got an IPv6 address.

### 👟 Reproduction steps

I checked it by entering the container via `docker exec -it uptime-kuma bash` and installing`ifconfig` with `apt update; apt install net-tools; ifconfig`. My other containers got the IPv6 subnet [I configured](https://docs.docker.com/config/daemon/ipv6/) in my `/etc/docker/daemon.json`. 

### 👀 Expected behavior

kuma should be able to monitor ipv6-only services. After entering the container and temporarily installing the neccessary tools I should be able to see an asigned IPv6 address and connect to IPv6-services.

### 😓 Actual Behavior

No IPv6 on the container.

### 🐻 Uptime-Kuma Version

1.17.1

### 💻 Operating System and Arch

Ubuntu 20.04.4 LTS

### 🌐 Browser

Safari 15.5

### 🐋 Docker Version

Docker version 20.10.17, build 100c701

**Comment by louislam** [comment]
It is a docker issue, I change it to `help`. Nothing can be fixed in Uptime Kuma codebase.

As far as I know, IPv6 in Docker is tricky sometimes. 

For me, it is working fine. It is a fresh uptime-kuma container.
![image](https://user-images.githubusercontent.com/1336778/175947141-cc1298cc-8b26-472d-a8cc-0851151205a8.png)

**Comment by Cheatha** [comment]
Solved it! I'm using docker-compose. After trying the plain docker command I got a valid IPv6 config. So I've altered the `docker-compose.yml` to look like this:

```version: '3.3'

services:
  uptime-kuma:
    image: louislam/uptime-kuma:1
    container_name: uptime-kuma
    volumes:
      - ./uptime-kuma-data:/app/data
    ports:
      - 3001:3001  
    restart: always
    networks: 
      kuma_net:
networks:
  kuma_net:
    enable_ipv6: true
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: fd00:321::/64
```

This gives me an internal IPv6 address with docker-compose and let's me monitor IPv6-only hosts.
