### ISSUE TITLE
ntfy isn't an available notification type

### ISSUE THREAD

**Issue by jonhiggs** [louislam/uptime-kuma#1846]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### Description

Running 1.17.1 I cannot see ntfy as a notification option. This was also an issue with 1.17.0beta1.

### 👟 Reproduction steps

settings -> notifications -> setup notifications
try to select ntfy as a notification type.

### 👀 Expected behavior

It should be listed in the drop down.

### 😓 Actual Behavior

It isn't listed in the drop down.

![Screen Shot 2022-06-28 at 13 26 18](https://user-images.githubusercontent.com/131466/176085911-3da0a001-2b74-4080-9eac-d52aca8826d0.png)
![Screen Shot 2022-06-28 at 13 24 26](https://user-images.githubusercontent.com/131466/176085916-dd307438-f340-4b54-937e-c9d2283525d2.png)

### 🐻 Uptime-Kuma Version

1.17.1

### 💻 Operating System and Arch

Alpine 3.16.0

### 🌐 Browser

Firefox 101.0.1

### 🐋 Docker Version

N/A

### 🟩 NodeJS Version

18.2.0

**Comment by louislam** [comment]
I think you missed download-dist step. Please check the wiki again.

**Comment by chakflying** [comment]
Maybe we should add a "Frontend Version" in the about page and set it statically during build.

**Comment by jonhiggs** [comment]
> I think you missed download-dist step. Please check the wiki again.

Thanks. That sorted me out. I believe I was following [these](https://github.com/louislam/uptime-kuma#-non-docker) instructions which doesn't mention that step.
