### ISSUE TITLE
Monitor showing offline but its online

### ISSUE THREAD

**Issue by Kaseax** [louislam/uptime-kuma#1848]
### ⚠️ Please verify that this bug has NOT been raised before.

- [x] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

I have the problem, that all of my monitors except 1 showing as offline. i can reach the website normally. 
Can someone help me by that?

One Monitor showing "error request aborted" 

The other two showing "timeout of 48000ms exceeded"

### 🐻 Uptime-Kuma Version

1.16.1

### 💻 Operating System and Arch

Debian 10 x86_64

### 🌐 Browser

Microsoft Edge 103.0.1264.37

### 🐋 Docker Version

20.10.17

**Comment by Unerheblich** [comment]
You mean with the ping command? if yes, yes. i can ping every server

**Comment by dariusdumitru** [comment]
I got the same exact problem every morning at 5-6 AM for an hour. It says that it's down, but it's not. With the same error "timeout of 48000ms exceeded". Usually there are 2 websites, but it happens to be only 1 or 3 sometimes. I've increased the Heartbeat Interval and Retries, but no luck. Anyone can help?

**Comment by d-delaey** [comment]
> I got the same exact problem every morning at 5-6 AM for an hour. It says that it's down, but it's not. With the same error "timeout of 48000ms exceeded". Usually there are 2 websites, but it happens to be only 1 or 3 sometimes. I've increased the Heartbeat Interval and Retries, but no luck. Anyone can help?

We got the same thing last night for maybe 40-50 Websites.

**Comment by Unerheblich** [comment]
Now my Discord-Webhook showing sometimes, that the Services are online but then it says there are offline.

**Comment by Nuklon** [comment]
Same issue here, see: https://github.com/louislam/uptime-kuma/issues/1621

**Comment by kfra71** [comment]
Same issue here, suddenly we are getting "timeout of 48000ms exceeded" on most of the checks.

Anyone has any clue?

**Comment by louislam** [comment]
> Same issue here, suddenly we are getting "timeout of 48000ms exceeded" on most of the checks.
> 
> Anyone has any clue?

This may help:
https://github.com/louislam/uptime-kuma/wiki/Troubleshooting

**Comment by kfra71** [comment]
Hi I have tried to run the cmd without apparently any issue.

Best regards, 

Francesco. 


***@***.*** ~]$ curl https://google.com
<HTML><HEAD><meta http-equiv="content-type" content="text/html;charset=utf-8">
<TITLE>301 Moved</TITLE></HEAD><BODY>
<H1>301 Moved</H1>
The document has moved
<A HREF="https://www.google.com/">here</A>.
</BODY></HTML>

***@***.*** ~]$ ping google.com
PING google.com (172.217.168.206) 56(84) bytes of data.
64 bytes from ams16s32-in-f14.1e100.net (172.217.168.206): icmp_seq=1 ttl=53 time=2.77 ms
64 bytes from ams16s32-in-f14.1e100.net (172.217.168.206): icmp_seq=2 ttl=53 time=2.52 ms
64 bytes from ams16s32-in-f14.1e100.net (172.217.168.206): icmp_seq=3 ttl=53 time=2.80 ms
64 bytes from ams16s32-in-f14.1e100.net (172.217.168.206): icmp_seq=4 ttl=53 time=2.36 ms
64 bytes from ams16s32-in-f14.1e100.net (172.217.168.206): icmp_seq=5 ttl=53 time=2.36 ms
64 bytes from ams16s32-in-f14.1e100.net (172.217.168.206): icmp_seq=6 ttl=53 time=2.42 ms
64 bytes from ams16s32-in-f14.1e100.net (172.217.168.206): icmp_seq=7 ttl=53 time=2.63 ms
64 bytes from ams16s32-in-f14.1e100.net (172.217.168.206): icmp_seq=8 ttl=53 time=2.67 ms
64 bytes from ams16s32-in-f14.1e100.net (172.217.168.206): icmp_seq=9 ttl=53 time=2.33 ms
^C

**Comment by Nuklon** [comment]
Yeah, that works for me as well. It's really that Uptime Kuma gets bogged down, and it happens more frequently when the container is running for a longer period of time. I've not found anything useful in the logs either, it just times out.

**Comment by Nuklon** [comment]
30s monitor (both monitors have the same settings and site, except for the interval):
![image](https://user-images.githubusercontent.com/23340481/182368392-8abf61ed-9ac3-42bc-ac72-d924577e3333.png)

1m monitor:
![image](https://user-images.githubusercontent.com/23340481/182368527-669eaae7-76ba-45d7-9714-2c8f6881ebe8.png)

**Comment by guydeschepper** [comment]
Same issue here.
When I try to ping the url from within the docker container, as suggested [here](https://github.com/louislam/uptime-kuma/wiki/Troubleshooting), I also do get a timeout.

BUT... the same website can be reached and pinged from other systems AND I can still ping other monitored websites from within the Uptime Kuma docker container, so it's not a general networking issue with the container / server / hosting.

So it seems something is getting bogged down in Uptime Kuma itself.

**Note**
Most of our monitored websites are behind Cloudflare, but some are not.
And until now I only experienced the issue with websites that are not behind Cloudflare.
Though not all those "non-cloudflare" websites are affected at the same time.
At the moment 2 of the non-cloudflare websites are affected, but several weeks ago we had the same issue with one of those 2 websites (and another one), but not the other.

We also see different errors prior to the timeout issues:

`140059089770432:error:1408F119:SSL routines:ssl3_get_record:decryption failed or bad record mac:../deps/openssl/openssl/ssl/record/ssl3_record.c:677
`

and

`getaddrinfo EAI_AGAIN <hostname>`

**Comment by d-delaey** [comment]
> Same issue here. When I try to ping the url from within the docker container, as suggested [here](https://github.com/louislam/uptime-kuma/wiki/Troubleshooting), I also do get a timeout.
> 
> BUT... the same website can be reached and pinged from other systems AND I can still ping other monitored websites from within the Uptime Kuma docker container, so it's not a general networking issue with the container / server / hosting.
> 
> So it seems something is getting bogged down in Uptime Kuma itself.
> 
> **Note** Most of our monitored websites are behind Cloudflare, but some are not. And until now I only experienced the issue with websites that are not behind Cloudflare. Though not all those "non-cloudflare" websites are affected at the same time. At the moment 2 of the non-cloudflare websites are affected, but several weeks ago we had the same issue with one of those 2 websites (and another one), but not the other.
> 
> We also see different errors prior to the timeout issues:
> 
> `140059089770432:error:1408F119:SSL routines:ssl3_get_record:decryption failed or bad record mac:../deps/openssl/openssl/ssl/record/ssl3_record.c:677 `
> 
> and
> 
> `getaddrinfo EAI_AGAIN <hostname>`

Hey, we "fixed" that issue by simply not using docker. But sometimes we are still getting the timeout error but not as often as using docker.

**Comment by guydeschepper** [comment]
Please don't close this issue as it is still not fixed!

**Comment by louislam** [comment]
> Same issue here. When I try to ping the url from within the docker container, as suggested [here](https://github.com/louislam/uptime-kuma/wiki/Troubleshooting), I also do get a timeout.
> 
> BUT... the same website can be reached and pinged from other systems AND I can still ping other monitored websites from within the Uptime Kuma docker container, so it's not a general networking issue with the container / server / hosting.
> 
> So it seems something is getting bogged down in Uptime Kuma itself.
> 
> **Note** Most of our monitored websites are behind Cloudflare, but some are not. And until now I only experienced the issue with websites that are not behind Cloudflare. Though not all those "non-cloudflare" websites are affected at the same time. At the moment 2 of the non-cloudflare websites are affected, but several weeks ago we had the same issue with one of those 2 websites (and another one), but not the other.
> 
> We also see different errors prior to the timeout issues:
> 
> `140059089770432:error:1408F119:SSL routines:ssl3_get_record:decryption failed or bad record mac:../deps/openssl/openssl/ssl/record/ssl3_record.c:677 `
> 
> and
> 
> `getaddrinfo EAI_AGAIN <hostname>`

Make sure you are not using Alpine based image.

For SSL error,  please double check `http://` vs `https://`

**Comment by guydeschepper** [comment]
> > Same issue here. When I try to ping the url from within the docker container, as suggested [here](https://github.com/louislam/uptime-kuma/wiki/Troubleshooting), I also do get a timeout.
> > BUT... the same website can be reached and pinged from other systems AND I can still ping other monitored websites from within the Uptime Kuma docker container, so it's not a general networking issue with the container / server / hosting.
> > So it seems something is getting bogged down in Uptime Kuma itself.
> > Note Most of our monitored websites are behind Cloudflare, but some are not. And until now I only experienced the issue with websites that are not behind Cloudflare. Though not all those "non-cloudflare" websites are affected at the same time. At the moment 2 of the non-cloudflare websites are affected, but several weeks ago we had the same issue with one of those 2 websites (and another one), but not the other.
> > We also see different errors prior to the timeout issues:
> > `140059089770432:error:1408F119:SSL routines:ssl3_get_record:decryption failed or bad record mac:../deps/openssl/openssl/ssl/record/ssl3_record.c:677 `
> > and
> > `getaddrinfo EAI_AGAIN <hostname>`
> 
> Make sure you are not using Alpine based image.
> 
I'm not since I'm running Uptime Kuma with Cloudron, which uses [Ubuntu based docker images](https://git.cloudron.io/cloudron/uptime-kuma-app/-/blob/master/Dockerfile)

> For SSL error, please double check `http://` vs `https://`

All sites in Uptime Kuma are configured with https, so there shoudn't be any reason for Uptime Kuma trying to access the sites over http.

**Comment by mrafols** [comment]
For me still happening 
![image](https://user-images.githubusercontent.com/1336824/214239740-936b7688-ff76-4029-95a2-7e6080bdfa7e.png)

**Comment by d-delaey** [comment]
> For me still happening ![image](https://user-images.githubusercontent.com/1336824/214239740-936b7688-ff76-4029-95a2-7e6080bdfa7e.png)

Yes it still happening to me

**Comment by xeruf** [comment]
Getting this error when trying to send a webhook, as in https://github.com/louislam/uptime-kuma/issues/1697, running via `pm2`

**Comment by webysther** [comment]
Start to happen to me after update the docker image.

**Comment by webysther** [comment]
> > Same issue here, suddenly we are getting "timeout of 48000ms exceeded" on most of the checks.
> > Anyone has any clue?
> 
> This may help: https://github.com/louislam/uptime-kuma/wiki/Troubleshooting

No curl installed in docker

**Comment by webysther** [comment]
![image](https://user-images.githubusercontent.com/750007/216165209-870582d9-34fb-4584-8d36-3001231cbf50.png)

After stop docker, pull new imagem and start docker.

**Comment by webysther** [comment]
![image](https://user-images.githubusercontent.com/750007/216166507-61d90792-d727-42b8-aff5-3acb4c1e1b2b.png)

**Comment by webysther** [comment]
ping and curl working from inside the container, nothing is working from this.

**Comment by Vanillabacke** [comment]
I can confirm that issue. the ping works just fine, but the http(s)-typ does not work and I'm getting the error `getaddrinfo EAI_AGAIN`.
- latest official docker image
- behind nginx reverse proxy (nginx proxy manager with the recommend settings)
- curl is not available inside die container and can not installed like in this article ([https://github.com/louislam/uptime-kuma/wiki/Troubleshooting](https://github.com/louislam/uptime-kuma/wiki/Troubleshooting))
tried different methods to install it, but no working solution

**Comment by alwynispat** [comment]
same here using the latest image.

**Comment by m-primo** [comment]
I have the same issue for months.. At first I thought this issue from my VPS provider, but after I had big fights with multiple VPS providers, I found out it's only happening from Uptime Kuma.

_I think I'll just look for another tool and apologize to the VPS providers!_

**Comment by XtremeOwnageDotCom** [comment]
Just a ping- its still a problem.

![image](https://user-images.githubusercontent.com/5262735/228068359-f79333c5-9745-4d4f-93a6-2b3efac9ff0b.png)

![image](https://user-images.githubusercontent.com/5262735/228068479-1d471ec5-5e0b-491b-9425-4e9de7480cf7.png)

![image](https://user-images.githubusercontent.com/5262735/228068553-24fab4db-e18d-4614-9a20-23273bdb7e32.png)

But, container logs, do tell me to report it. So. Here it is.

![image](https://user-images.githubusercontent.com/5262735/228069022-6b47b483-d6c2-4bd2-bd5f-faf98a56b2d0.png)

Deleting and recreating the monitor did nothing to help.

However, after deleting the pod, and letting it recreate, monitor did start working.

**Comment by CommanderStorm** [comment]
> stalebot, really?

Stalebot is active on all issues using the `help` template.
=> Closing stale help requests is by design because often people don't answer or issues are not reproduce or we fix things in further releases but forget to close them leading to immortal zombies.

Until now this issue has not really provided a minimally reproducible example (see https://stackoverflow.com/help/minimal-reproducible-example)
If somebody provides such an example I can have a look, but currently this issue doesn't really give enough context to debug against.
There are multiple factors which can lead to timeouts.

**Comment by michel-thomas** [comment]
I had the problem yesterday, and finally found what occurs…

After a maintenance reboot from our provider, IPv4 remains the same, but IPv6 changed. I would have never seen this change if uptime kuma didn't alert.

I don't know why yet, but my uptime kuma check https services via IPv6 while my desktop ISP still only works with IPv4.
Updating my DNS with the new IPv6 solve the problem.

**Comment by pixelbart** [comment]
Same issues here

**Comment by fantasticrabbit** [comment]
Same issue here. Was stable for 16-7 months using Node+PM2, switching to Docker was stable for 2 months and then started showing all sites down every 4-10 hours. Was not able to find anything in the container logs to troubleshoot. We're planning to switch back to just running the Node app.
