### ISSUE TITLE
Document Monitors

### ISSUE THREAD

**Issue by jordantrizz** [louislam/uptime-kuma#1849]
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

Other

### 🔖 Feature description

Document each monitor and how it functions as well as it's configuration settings.

### ✔️ Solution

Crowd source the documentation process.

### ❓ Alternatives

Do nothing.

### 📝 Additional Context

The documentation could be improved overall.

**Comment by CommanderStorm** [comment]
Indeed, I copied the wrong link for this issue.
We currently have a guide for the docker monitor (as this is more difficult to set up).

There is still not enough information in this issue to go on:
- Which monitor would you need documentation on?
- Which one is not already sufficiently documented/clear in the frontend?
