### ISSUE TITLE
Max Retries

### ISSUE THREAD

**Issue by ShadowGaming100** [louislam/uptime-kuma#1854]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### Description

![9D6E28D0-B651-4D94-91AC-A2DF795C557A](https://user-images.githubusercontent.com/81495140/176476674-4381d06a-b534-41da-970a-0d7e056d7269.jpeg)
![93537D74-830D-40A2-B589-233148865DA6](https://user-images.githubusercontent.com/81495140/176484553-99495886-50a4-4f8e-ad42-213d8ab3210e.jpeg)

### 👟 Reproduction steps

upload from backup 

### 👀 Expected behavior

after 5 retires send notification 

### 😓 Actual Behavior

only after 1 retries send notification 

### 🐻 Uptime-Kuma Version

1.17.1

### 💻 Operating System and Arch

Linix

### 🌐 Browser

Chrome

### 🟩 NodeJS Version

latest

**Comment by ThomasChr** [comment]
@ShadowGaming100 Any news on this?

To make it a little bit more clear, in an Monitor you have two seperate values:

This one, Max. Redirects tells utpime kuma how many redirects to follow when accessing a page. Webservers can tell a client "I don't have your content, but I know who has, please go to: www.newpage.com" - thats an redirect. Sometimes you wanna follow them, sometimes you don't...
![grafik](https://user-images.githubusercontent.com/13014163/176641761-f24b7923-2dd8-4b7d-b1b1-6486a17d44e5.png)

And that one is how many times to try if an error happens, thats the one you mean, but you haven't set a screenshot of it:
![grafik](https://user-images.githubusercontent.com/13014163/176642111-f7d4bbfd-a1c6-4bb9-a418-bcbf02831e6a.png)

**Comment by ShadowGaming100** [comment]
oh
