### ISSUE TITLE
After adding 1000+ monitor, the socket connection is lost when loading the dashboard

### ISSUE THREAD

**Issue by jasonmeehan11** [louislam/uptime-kuma#1855]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### Description

After adding 1000+ monitor, the socket connection is lost when loading the dashboard.
The dashboard loads the data from zero monitors to 1012 and when it gets to the end, the browser lists an error in red at the top claiming the socket connection is lost and it loads all of the monitors again in a loop.

I get the same error when trying to load my exported .json file

### 👟 Reproduction steps

Start docker container
Navigate to uptime-kuma page
wait for monitors to show status
Near the end of the loading, the message appears

### 👀 Expected behavior

Load the entire list without crashing in a loop

### 😓 Actual Behavior

Loop of socket connecting lost and reloads the monitors list

### 🐻 Uptime-Kuma Version

1.17.1

### 💻 Operating System and Arch

Docker on Debian

### 🌐 Browser

Chrome 102.0.5005.115

### 🐋 Docker Version

version 20.10.17, build 100c701

**Comment by chakflying** [comment]
Looks like a server crash, would be helpful to see the container logs.

**Comment by jasonmeehan11** [comment]
I ended up creating multiple instances of uptime-kuma

**Comment by JohnnyChiang** [comment]
Had the same issue here
