### ISSUE TITLE
Header for different domain names for status page

### ISSUE THREAD

**Issue by harryzcy** [louislam/uptime-kuma#1861]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### Description

When running behind a reverse proxy, the wiki says `For such as Apache or nginx, you need to forward the header X-Forward-Host or Host to Uptime Kuma`.

But it seems only the `Host` header works. `X-Forward-Host` doesn't work. Also, the standard header name should be `X-Forwarded-Host` instead of `X-Forward-Host`.

### 👟 Reproduction steps

Set the domain name for a status page, run behind nginx and set `proxy_set_header X-Forwarded-Host $host;`.

### 👀 Expected behavior

Going to the domain, and it shows the status page

### 😓 Actual Behavior

The page redirects to dashboard, and prompts login.

### 🐻 Uptime-Kuma Version

1.17.1

### 💻 Operating System and Arch

Debian bullseye arm64

### 🌐 Browser

Chrome 103

### 🐋 Docker Version

20.10.17

**Comment by 50l3r** [comment]
Its resolved or any way to fix temporarily? I have this config in my nginx but it redirect me to login:

```
  server {
    listen 443 ssl http2;
    server_name uptime.calltek.dev status.gestios.es;

    location / {
      proxy_set_header   X-Real-IP $remote_addr;
      proxy_set_header   X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header Host $host;
      proxy_pass         http://localhost:3001;
      proxy_http_version 1.1;
      proxy_set_header   Upgrade $http_upgrade;
      proxy_set_header   Connection "upgrade";
    }
  }
```

**Comment by harryzcy** [comment]
The same config actually works for me, are you setting the domain in Status Page? @50l3r

**Comment by 50l3r** [comment]
> The same config actually works for me, are you setting the domain in Status Page? @50l3r

Damn. My fault. There's a type error on domain setting in status page 🤦‍♂️

I take this opportunity to thank you for developing this incredible project and share with everyone 😊🍾🍾🍾.
