### ISSUE TITLE
Retries not effective for Upside Down Push monitor

### ISSUE THREAD

**Issue by gkatev** [louislam/uptime-kuma#1863]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### Description

Hi, it looks like there might be a bug regarding upside-down push monitors and the retry functionality. As soon as the monitor receives the push signal, it switches from UP to DOWN immediately. Instead, I would expect it to go into 'yellow state', according to the retry settings, the same way that it does for an upside-down ping monitor.

### 👟 Reproduction steps

I have the following monitor setup:
- Push, Upside down
- Interval 600s
- Retries 144
- Retry Interval 600s
- Use case: monitor a server that's supposed to be sleeping, and notify if it's up for a long time (144*600s=1 day). Push type instead of ping, because the server wakes up on unicast!

As soon as the heartbeat is sent, the monitor switches to down state.

As a test, a similar ping monitor:
- Ping, Upside down
- Interval 30s
- Retries 4
- Retry Interval 30s
- Non-responding IP

The ping monitor is UP, because the fake IP does not respond. When I switch it to a valid IP, it goes down after 4 'yellow' windows, and only then reports that it's down.

### 👀 Expected behavior

Only go into down state when the push signal is received for `retry_count` consequtive windows, similar to the upside-down ping monitor

### 😓 Actual Behavior

Retry count does not seem to have any effect

### 🐻 Uptime-Kuma Version

1.17.1

### 💻 Operating System and Arch

Arch Linux

### 🌐 Browser

Firefox 101.0.1

**Comment by ShadowGaming100** [comment]
it means that when is down it will show is up
when is up it will show down 
that’s what i understand

**Comment by ShadowGaming100** [comment]
> ### ⚠️ Please verify that this bug has NOT been raised before.
> * [x]  I checked and didn't find similar issue
> 
> ### 🛡️ Security Policy
> * [x]  I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)
> 
> ### Description
> Hi, it looks like there might be a bug regarding upside-down push monitors and the retry functionality. As soon as the monitor receives the push signal, it switches from UP to DOWN immediately. Instead, I would expect it to go into 'yellow state', according to the retry settings, the same way that it does for an upside-down ping monitor.
> 
> ### 👟 Reproduction steps
> I have the following monitor setup:
> 
> * Push, Upside down
> * Interval 600s
> * Retries 144
> * Retry Interval 600s
> * Use case: monitor a server that's supposed to be sleeping, and notify if it's up for a long time (144*600s=1 day). Push type instead of ping, because the server wakes up on unicast!
> 
> As soon as the heartbeat is sent, the monitor switches to down state.
> 
> As a test, a similar ping monitor:
> 
> * Ping, Upside down
> * Interval 30s
> * Retries 4
> * Retry Interval 30s
> * Non-responding IP
> 
> The ping monitor is UP, because the fake IP does not respond. When I switch it to a valid IP, it goes down after 4 'yellow' windows, and only then reports that it's down.
> 
> ### 👀 Expected behavior
> Only go into down state when the push signal is received for `retry_count` consequtive windows, similar to the upside-down ping monitor
> 
> ### 😓 Actual Behavior
> Retry count does not seem to have any effect
> 
> ### 🐻 Uptime-Kuma Version
> 1.17.1
> 
> ### 💻 Operating System and Arch
> Arch Linux
> 
> ### 🌐 Browser
> Firefox 101.0.1
> 
> ### 🐋 Docker Version
> _No response_
> 
> ### 🟩 NodeJS Version
> _No response_
> 
> ### 📝 Relevant log output
> _No response_

i tested and for me is not a bug

**Comment by gkatev** [comment]
> it means that when is down it will show is up when is up it will show down that’s what i understood

Yes that is correct. The point is the retry count/interval. It goes immediately from up to down, without the intermediate retry phase.

**Comment by ShadowGaming100** [comment]
Same thing happening to me

**Comment by gkatev** [comment]
But it does not work as intended, correct?

**Comment by ShadowGaming100** [comment]
> But it does not work as intended, correct?

Correct

**Comment by chakflying** [comment]
cc. @kaysond in case you have time to look into this.

**Comment by kaysond** [comment]
Is this how its supposed to work? @gkatev can you try v1.16.0 and let me know if that behaves the way you want it to? If so, then it's probably another regression from the race condition fix.

**Comment by gkatev** [comment]
So, I'm not certain how it's actually envisioned to work. I worked out the expected behaviour based on intuition and on the other monitor types. It seems to me like the Retry functionality currently has no effect for upside-down push monitors.

The functionality in regards to this issue appears to be the same for both v1.16.0 and on v1.17.1.

**Comment by kaysond** [comment]
Ok so it's not my fault :D

I would say that the behavior not being consistent between different kinds of monitors is a bug, though. Have you tried other monitor types?

@louislam - do you think that all types of upside down monitors with N retries should have N successful calls (i.e. http requests, pings, pushes) before going from  UP to DOWN?

I'm happy to fix the push monitor if that's the case.

**Comment by gkatev** [comment]
No, I' ve only tested push and ping

**Comment by kaysond** [comment]
Looks like http operates same as ping

**Comment by ShadowGaming100** [comment]
> Looks like http operates same as ping

I have tried http and there is no problem

**Comment by RignonNoel** [comment]
+1 for @gkatev 

For me the situation that he describe is a bug, clearly if Kuma get a push notification it should go into a "retry phase" by waiting other potential push... It should go into an error only after receiving 144 differents PUSH in a row.

**Comment by kaysond** [comment]
If someone wants to tackle this, it should be a fairly easy change. The relevant push monitor code is here:
https://github.com/louislam/uptime-kuma/blob/f2c294e9e5d7e2bd8bcd4f7dd50459e89be26999/server/model/monitor.js#L461-L489

and retries are handled here:
https://github.com/louislam/uptime-kuma/blob/f2c294e9e5d7e2bd8bcd4f7dd50459e89be26999/server/model/monitor.js#L718-L731

Just make sure you don't break anything else ;)

**Comment by kaysond** [comment]
So I took a deeper look at this, and it's a bit more complicated than I initially thought... The problem is how exactly to deal with extra pushes, retries, and the retry interval. For example, suppose you have the OP's case: 144 retries with a 600s retry interval. What do you do if you get 2 pushes within 600s? Does that make the monitor go down? I would think so, but right now there's no way to track the retry interval within a push monitor. Another way to look at this would be: how do you make sure you're only getting 1 push per retry interval?

**Comment by RignonNoel** [comment]
> Another way to look at this would be: how do you make sure you're only getting 1 push per retry interval?

Since Kuma work with time interval I think we can get for grant that `number of push inside a same interval` is not a big deal... What is important is how many time in total the same status continue to show up. So if you received two status update per interval we can just get the first one in account for example.

If we want to monitor a specific **number** of status we should have another tool or mode that is not based on time interval but on repetition count and limit.

**Comment by sypper-pit** [comment]
i create https://github.com/sypper-pit/uptime-kuma-push  may be next version https://github.com/louislam/uptime-kuma/  

**I hope give** `state=warning` - for send HDD \ CPU \ ROM 

We need to somehow make it so that when filling or loading, a message comes to the telegram
