### ISSUE TITLE
Create an incident using API

### ISSUE THREAD

**Issue by georgkrause** [louislam/uptime-kuma#1868]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

I want to create incidents automatically from other systems, eg using webhooks or an API. This way Uptime Kuma can be automatically updated

### 🐻 Uptime-Kuma Version

1.17.1

### 💻 Operating System and Arch

Debian 64bit

### 🌐 Browser

Firefox

**Comment by Computroniks** [comment]
Related to #118

**Comment by georgkrause** [comment]
Its still relevant!

**Comment by georgkrause** [comment]
Still needed

**Comment by georgkrause** [comment]
OK i get it, this project isn't interested in issues that can't be solved in a single day. I'll find another solution, thanks

**Comment by Aj7Ay** [comment]
Is this done
i want create incident using API

**Comment by CommanderStorm** [comment]
No this is not done. We currently don't have an official api. Some work has been done by third party's on the python side. An official api is currently in the works see the open PR (can't link it from GitHub mobile)
