### ISSUE TITLE
How can change UI name, css, colours in docker instance

### ISSUE THREAD

**Issue by johnfelipe** [louislam/uptime-kuma#1871]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

I want to rename to Uptime Kuma - UdeA
I want to change color for university schemma css
I have all installed in docker

```
docker-compose --version

docker-compose version 1.29.2, build 5becea4c

docker --version

Docker version 20.10.17, build 100c701
```

### 🐻 Uptime-Kuma Version

Latest

### 💻 Operating System and Arch

Ubuntu 20

### 🌐 Browser

Chrome

### 🐋 Docker Version

Docker 20

### 🟩 NodeJS Version

16

**Comment by louislam** [comment]
Cannot, you have to build it yourself.

**Comment by johnfelipe** [comment]
Can you guide me in steps for create or build by myself
Im in local enviroment

**Comment by johnfelipe** [comment]
> Cannot, you have to build it yourself.

hi pal, pls tell me how can build by myself...

**Comment by satyamsettyeswara** [comment]
Check #1950

**Comment by johnfelipe** [comment]
I will try Monday and feedback to u next
