### ISSUE TITLE
Translate to spanish latest docker pull issue

### ISSUE THREAD

**Issue by johnfelipe** [louislam/uptime-kuma#1872]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### Description

/add-status-page:

![SNAG-0011](https://user-images.githubusercontent.com/428820/177632249-9b1e4715-ac11-4858-b787-b7a85048e204.png)

/manage-status-page:

![SNAG-0012](https://user-images.githubusercontent.com/428820/177632326-fd255e4f-2ffa-4f26-8306-922eceb2b52a.png)

/status/exmple1:
![SNAG-0013](https://user-images.githubusercontent.com/428820/177632432-d82b0b92-0ceb-4153-87b0-7c3606aa418e.png)

![SNAG-0014](https://user-images.githubusercontent.com/428820/177632566-3b39f4ed-d3fe-4a0c-b3c0-681d92d0c15a.png)
![SNAG-0015](https://user-images.githubusercontent.com/428820/177632640-d2e8919a-6b0b-432a-8859-f5e294001198.png)

### 👟 Reproduction steps

pull to latest version of docker image

### 👀 Expected behavior

all strings translated to spanish

### 😓 Actual Behavior

that strings not translated to spanish

### 🐻 Uptime-Kuma Version

Latest

### 💻 Operating System and Arch

Ubuntu 20

### 🌐 Browser

Chrome

### 🐋 Docker Version

Docker 20

**Comment by Computroniks** [comment]
This is likely due to no translations being present in the spanish language file. If you speak spanish you could perhaps add some of the translations. For more info about this see https://github.com/louislam/uptime-kuma/tree/master/src/languages

**Comment by johnfelipe** [comment]
How can add that strings?

**Comment by Computroniks** [comment]
First look in the en.js file for the translation you wish to add and then copy that over to the spanish file with the translation. For example, if I wanted to translate `Services`, I would first look in `en.js` and find the following line:
https://github.com/louislam/uptime-kuma/blob/d29955f3bad013978bec9c4eb8f4aefc94fdeaba/src/languages/en.js#L355
I would then check in `es-ES.js` first that the translation has not already been copied across. If it has you can update it. If it hasnt then, in `es-ES.js` I would add the following
```javascript
Services: "<spanish translation>",
```

**Comment by johnfelipe** [comment]
How can deploy in docker?

**Comment by Computroniks** [comment]
For a docker install see https://github.com/louislam/uptime-kuma/wiki/%F0%9F%94%A7-How-to-Install#-docker
Note, this will not include any translations you make. You would first have to submit a PR and wait for the next release for any translations to be included

**Comment by johnfelipe** [comment]
https://github.com/louislam/uptime-kuma/commit/011d6f40beb720f6360a1aedd53d3a50a4000fc6

ok pls tell me if is ok, and merge

**Comment by johnfelipe** [comment]
Tech me for how to deploy uptime Kuma in docker image, pls
