### ISSUE TITLE
javascript language file to json for translate correctly to es, fr and it

### ISSUE THREAD

**Issue by johnfelipe** [louislam/uptime-kuma#1873]
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

Other

### 🔖 Feature description

Can u share me json file of en.js language?

### ✔️ Solution

https://www.convertsimple.com/convert-javascript-to-json/
but is not correctly formatted

### ❓ Alternatives

share en.js to en.json

**Comment by Computroniks** [comment]
Sorry. This is out of the scope of this repo and this sort of file does not exist. If you want such a file you will have to create it yourself.

**Comment by johnfelipe** [comment]
already PR in different branch es, it and fr
