### ISSUE TITLE
Notification via Apprise results in "No module named 'six'"

### ISSUE THREAD

**Issue by danijelst** [louislam/uptime-kuma#1879]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### Description

I'm using Homeassistant to run the Uptime Kuma via the Addon.
I wanted to define a notification config and use Apprise to push to Homeassistant. However the UI returning "No output from apprise" when I press test.
Further test was done via docker, see result in the Expected behaviour description.

### 👟 Reproduction steps

Case via UI
- Go to Settings
- Notifications
- Setup Notification
- Select Type Apprise
- Fill in the name and URL (hassio, not hassios but this also doesn't work)
- Press Test

Case via Docker
- connect to the docker
- execute `apprice -vvv hassio://myhassio/mylonglivedaccesstoken`

### 👀 Expected behavior

Receive a notification in Homeassistatnt

### 😓 Actual Behavior

Nothing happens in the UI

but the docker returns 
```
Traceback (most recent call last):
  File "/usr/bin/apprise", line 5, in <module>
    from apprise.cli import main
  File "/usr/lib/python3.10/site-packages/apprise/__init__.py", line 49, in <module>
    from .URLBase import URLBase
  File "/usr/lib/python3.10/site-packages/apprise/URLBase.py", line 27, in <module>
    import six
ModuleNotFoundError: No module named 'six'
```

### 🐻 Uptime-Kuma Version

1.16.1

### 💻 Operating System and Arch

Alpine Linux v3.16

### 🌐 Browser

Brave

### 🐋 Docker Version

20.10.14

**Comment by louislam** [comment]
Currently, Uptime Kuma bundled Apprise 0.9.8.

I suggest you should try Apprise 0.9.9. If it is still not working.

You should report to Apprise's repo.
https://github.com/caronc/apprise/issues/626

**Comment by caronc** [comment]
I'm not sure if this is an issue with Apprise.  Unless `six` is a package that is no longer supported. But as far as i can tell this isn't the case ([source](https://pypi.org/project/six/)).  I would guess that the `six` package didn't get pulled into the environment correct perhaps or there is a conflicting package in it?

`six` [is still very much a part of the Apprise `requirements.txt`](https://github.com/caronc/apprise/blob/master/requirements.txt#L3).

My best guess is that this is not a bug at all and related to the current users environment and/or how he installed Apprise. 

Perhaps  a `pip install apprise`  or `pip install  -r requirements.txt` is all that is required?

**Comment by louislam** [comment]
Oh, I just realize that @danijelst is not using the official Uptime Kuma docker image.

I checked the addon, they actually didn't follow my Dockerfile.
https://github.com/hassio-addons/addon-uptime-kuma/blob/main/uptime-kuma/Dockerfile

For Alpine, it have to install many packages in order to get it working.
https://github.com/louislam/uptime-kuma/blob/a78cb7ab42b8b7d1961ecbb4262d7f4b050decef/docker/alpine-base.dockerfile#L6-L8


Honestly, I don't know why people would like to reinvent my Dockerfile.

I would highly recommended that you should use my official docker image. It is a bit newer and I believe it is no such bug.

**Comment by danijelst** [comment]
Thank you very much for your help. I have switched to the official image and then it works. I will later create an issue in the addon's repository so that they can fix resp. switch to the official docker.
