### ISSUE TITLE
Add announcement section

### ISSUE THREAD

**Issue by stinkymonkeyph** [louislam/uptime-kuma#1882]
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

API, UI Feature

### 🔖 Feature description

We should be able to add an announcement in case we want to properly address an issue causing our services to go offline

### ✔️ Solution

We need to add a section on the status page for announcements, we should be able to write announcements.

**Comment by almereyda** [comment]
This will be very useful to communicate and announce outages to an audience.

With the post-v2 world arriving soonish and the new label having appeared last year, could we possibly consider reopening here?
