### ISSUE TITLE
Have the ability to alert if a keyword is not present

### ISSUE THREAD

**Issue by paul-pascual** [louislam/uptime-kuma#1884]
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

New Monitor

### 🔖 Feature description

Hello,
I would like to have the possibility to search for a keyword and if it is found, to alert the user.
I would be very grateful if you could do this.
Thank you very much :) !
PS: Excuse-me for my english level

### ✔️ Solution

Add a function to alert if a keyword is not present.

**Comment by Computroniks** [comment]
Is this not a good use of the upside down mode? This allows you to invert the sense of the monitor.

**Comment by Brain0Paul** [comment]
That’s right!!! I had not seen this mode, that’s what i wanted.
Thank you very much !

**Comment by JulianGro** [comment]
Could you close this issue then? Since this is already a feature.
