### ISSUE TITLE
Stop notifications if specific monitor is down

### ISSUE THREAD

**Issue by Vecsy** [louislam/uptime-kuma#1887]
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

New Notification

### 🔖 Feature description

The option to stop all notifications only if a specific monitor goes down/offline. This would prevent a user receiving a lot of down/up emails/other notifications.

### ✔️ Solution

Here is my case example: I host an ESXi server. If the ESXi server is offline, do not send down notifications for WebServer1, WebServer2, WebServer3, MailServer1, MailServer2 etc etc.

**Comment by ouuan** [comment]
I also want to request a similar but different feature: an option to stop all notifications when all monitors are down, or for example when 90% of the monitors are down. This can prevent receiving tons of notifications when there are network issues with the Uptime Kuma server itself.

**Comment by cris1** [comment]
I have a device that I want to monitor on general behaviour .. It comes up for 1 minute and sleeps 5 minutes.. I don't want to see notifications (desktop notifications) for this device.. its ok just to monitor it and I can watch the graphs to see if it still behaves as expected.

**Comment by CommanderStorm** [comment]
Is this one of the duplicates linked to https://github.com/louislam/uptime-kuma/pull/1236?

**Comment by CommanderStorm** [comment]
> Yes i want to monitor it, but no it's not relevant enough to notify me with any notifications.

You could just disable the notifiations for said monitor. Am I missing something?
![image](https://github.com/louislam/uptime-kuma/assets/26258709/3bb39bf0-3d4a-418e-8e5f-0f4a828f3a92)

**Comment by cris1** [comment]
As far as I can see this doesn't apply for the desktop notifications. 
As a (workable) workaround I increased the Retries to 60, so before it will send a notification, the device was up again. 

![image](https://github.com/louislam/uptime-kuma/assets/666701/d4921568-8ad2-425b-850e-24da34ddf614)
