### ISSUE TITLE
Discord notifications embed

### ISSUE THREAD

**Issue by MrYoogoMusic** [louislam/uptime-kuma#1889]
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

New Notification, UI Feature, Other

### 🔖 Feature description

Would it be possible to add an option for the discord webhook to modify the embed message instead of sending a message every time? Because as soon as I turn on a service I get a notification and when I turn it off I still get a notification.

### ✔️ Solution

The user should be able to choose in the settings if the web hook sends a lot of messages or if it modifies the embed. If the user chooses the second option, the webhook sends an embed message and each time the service changes state, it modifies the embed

### 📝 Additional Context

![notifications](https://user-images.githubusercontent.com/38286695/178621164-d331c049-a7b9-4c9c-ad0c-b0a9413fa4ce.png)

**Comment by Allard-B** [comment]
Hi @MrYoogoMusic maybe this will make it more clear for a developer.

![image](https://user-images.githubusercontent.com/87902614/184187535-c9c44b6b-aebc-4db7-aa0c-7acf50795841.png)

and i also found this while having a quick look online, it should be possible, i think.

https://stackoverflow.com/questions/65970556/discord-py-edit-webhook-message-embed-in-on-message

**Comment by CommanderStorm** [comment]
Closing as a duplicate (despite this being older) in favor of #3508 as said issue explores the technical hurdles in more details
