### ISSUE TITLE
Certificate Expiry Notification doesn't work for me... any ideas?

### ISSUE THREAD

**Issue by folosleg** [louislam/uptime-kuma#1890]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

Pushbullet notifications. UP/DOWN alerts arrive fine. Test notification is OK too.
Certificate Expiry Notification is set for all configured monitors.
Settings -- Notifications -- TLS Expiry default to  7 & 14 & 21 days
On the monitor's dashboard Cert Exp. determined correctly. But no mention of expiry in the log either.
What do I do wrong here? Appreciate any help.
Cheers

### 🐻 Uptime-Kuma Version

1.17.1

### 💻 Operating System and Arch

Ubuntu 20.04.04 LTS x64

### 🌐 Browser

Chrome 103.0.5060.114

### 🟩 NodeJS Version

14.19.3

**Comment by chakflying** [comment]
- Have you selected "Ignore TLS Error" for your monitor?
- What is the protocol of the url of your monitor (e.g. `https://`)?

**Comment by folosleg** [comment]
- Ignore TLS Error is turned off.
- Protocol is https
- Cert Exp. is determined properly
I'm puzzled. Cheers for the help!

![image](https://user-images.githubusercontent.com/80481320/179245742-c8314321-3b4a-495b-a759-955aa49b6667.png)
![image](https://user-images.githubusercontent.com/80481320/179246184-bd04c265-f14b-41d0-ad84-4a97f83d9da3.png)

**Comment by chakflying** [comment]
Thanks, looking at the code I realized some older notification types may not support sending the expiry message, and will default back to sending the test message. If you received a random "Testing Successful" notification that's probably why.

We will probably have to check all the notification types to see which are affected.

**Comment by folosleg** [comment]
Sure I did get those "Testing Successful" notifications... I thought they were rather a feature not a bug :)
Thanks for your time and effort fixing this.

**Comment by folosleg** [comment]
Unfortunately it's still not solved for PushBullet. Much appreciation if anybody can work on this one.

**Comment by louislam** [comment]
Just checked the implementation, it do not handle general message correctly.

https://github.com/louislam/uptime-kuma/blob/c662d259b0a59e59a650f00a04253e0d81707ab2/server/notification-providers/pushbullet.js#L21-L27
