### ISSUE TITLE
DELETE ALL THE STATS HISOTRY

### ISSUE THREAD

**Issue by ZIODIOZIO** [louislam/uptime-kuma#1896]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

Hello,

how can i delete all the stats and restore the Uptime %. I had some connectivity issue in my status VPS... and i cannot delete and re-create all the monitors.

![image](https://user-images.githubusercontent.com/74601229/179099215-abbae977-0685-4d9c-8d11-299d3b836f9b.png)

This options seems not working.

### 🐻 Uptime-Kuma Version

last

### 💻 Operating System and Arch

Ubuntu 20

### 🌐 Browser

Chrome

**Comment by chakflying** [comment]
Tested the second option should work. You may have to wait a while if your monitor has been running for a long period of time.

If you want to delete history of ALL monitors, you can go to Settings -> Monitory History -> Clear All Statistics.
