### ISSUE TITLE
Emails will not send due to SSL routines:tls_process_ske_dhe:dh key too small

### ISSUE THREAD

**Issue by amityweb** [louislam/uptime-kuma#1898]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

Emails will not send due to the following error:

`140334706751424:error:141A318A:SSL routines:tls_process_ske_dhe:dh key too small:../deps/openssl/openssl/ssl/statem/statem_clnt.c:2166:`

I am sorry I just cant figure this out, any insight why this is? I have added my SMTP settings to plenty of systems, it works, never have an issue sending through SMPT. I tried my custom mail server and then my 3rd party mail sending service smtp.com. 

### 🐻 Uptime-Kuma Version

1.17.1

### 💻 Operating System and Arch

Ubunto 20.04

### 🌐 Browser

Chrome Version 103.0.5060.114

**Comment by chakflying** [comment]
Have you checked #1331?

**Comment by amityweb** [comment]
That does not look like its resolved either? 

One solution in there did not work for me:
_I figured it out, I had to mess with my notification settings a little and confirm the port from my ISP, I had that wrong._
The other solution I have the same response:
_However, I don't know how to do this in a docker container._
then the last comment was:
_We could support it as demonstrated in [this](https://stackoverflow.com/a/60367796/17569333) answer, but it would require users to build their own container locally. See if you guys are comfortable with this._

**Comment by amityweb** [comment]
In the meantime I use Webhooks and my account with Integromat/Make to send the emails. Should have thought of Webhooks in the first place!

**Comment by louislam** [comment]
The tls version is too old which nodemailer do not support it by default.

https://stackoverflow.com/questions/60641391/nodemailer-does-not-work-with-aruba-webmail

**Comment by amityweb** [comment]
I've deployed this via docker so what's any versioning got to do with me? I though everything is in the docket container. 

How do I edit it all to change versions?

**Comment by Computroniks** [comment]
> I've deployed this via docker so what's any versioning got to do with me? I though everything is in the docker container. 
> 
> How do I edit it all to change versions?

This is not so much to do with the version of nodemailer, more the TLS version. By default it seems nodemailer does not support TLS 1 which it seems your email service is using. To get this to work it would require a code change to change the minimum TLS version.

**Comment by amityweb** [comment]
So TLS1 on my email server? I'm sure my email server uses various, including latest, protocols.  No other software complains. 

In fact I also tried using smtp.com as I have an account with them and that didn't work, same error.

**Comment by louislam** [comment]
Some directions: 
- Test it on https://demo.uptime.kuma.pet, see if it is reproducible.
- If you know Node.js, test nodemailer directly. https://nodemailer.com/about/
