### ISSUE TITLE
Self signed email certificate 

### ISSUE THREAD

**Issue by antoine2tt** [louislam/uptime-kuma#19]
Hi 

is it possible to use self signed certificat email address? 

When I tried to test my email address, it says “self signed certificate” and I had no mail 

thanks !!

**Comment by antoine2tt** [comment]
I manage to did it by adding the following environment setting : 

NODE_TLS_REJECT_UNAUTHORIZED: 0

**Comment by gitcatpeter** [comment]
> NODE_TLS_REJECT_UNAUTHORIZED: 0

Thank you @antoine2tt . That worked right off the bat.

@louislam Please include this as an official GUI config option or document somewhere.
Great App, thank you!
