### ISSUE TITLE
Reset admin password?

### ISSUE THREAD

**Issue by ctrlbrk42** [louislam/uptime-kuma#190]
Uptime Kuma is insisting that my user/pass are invalid.  Quite impossible because I have it saved both in my browser, and also a third-party password manager.

But nonetheless, I cannot login.  I prefer to not lose all my data, is there a way to reset the password?

I am using the Docker variant.

**Comment by louislam** [comment]
For 1.0.10, if you know how to use SQLite, you can reset by running the SQL command:

```sql
DELETE FROM user;
```

The db location:
```
./data/kuma.db
```


I will add a reset admin tool for the next release.

**Comment by louislam** [comment]
You can reset password via cli in 1.1.0

Please read this:
https://github.com/louislam/uptime-kuma/wiki/Reset-Password-via-CLI
