### ISSUE TITLE
Unable to update uptime-kuma

### ISSUE THREAD

**Issue by ShadowGaming100** [louislam/uptime-kuma#1901]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### Description

I am not able to update uptime-Kuma since 
[6 July](https://github.com/louislam/uptime-kuma/commit/d29955f3bad013978bec9c4eb8f4aefc94fdeaba) 

### 👟 Reproduction steps

cd XUptime
git fetch --all
git checkout 1.17.1 --force
npm install --production
npm run download-dist

### 👀 Expected behavior

Update 

### 😓 Actual Behavior

Stay the same

### 🐻 Uptime-Kuma Version

Latest

### 💻 Operating System and Arch

Linix

### 🌐 Browser

Chrome 

### 🟩 NodeJS Version

Latest

**Comment by aman207** [comment]
git pull working fine for me
