### ISSUE TITLE
Telegram monitor won't turn on

### ISSUE THREAD

**Issue by oplexz** [louislam/uptime-kuma#1902]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### Description

I have set up a Telegram notification a few months prior, and I have just tried adding a second Telegram monitor for another channel. The notification is setup properly, since the test message goes through just fine, but upon reopening the monitor settings, it appears that the second (new) notification is disabled. I have tried editing and saving this notification, and creating it from scratch, but that didn't help.

### 👟 Reproduction steps

1. Add Telegram notification to a monitor
2. Add another Telegram notification to the same monitor
3. Both notifications should be enabled
4. Switch to another monitor, then back to the first one
5. Second notification is disabled -- enable it, repeat step 4

### 👀 Expected behavior

Both notifications should be enabled

### 😓 Actual Behavior

Second notification is disabled

### 🐻 Uptime-Kuma Version

1.17.1

### 💻 Operating System and Arch

Ubuntu 20.04.4 LTS (GNU/Linux 5.4.0-121-generic x86_64)

### 🌐 Browser

Google Chrome 103.0.5060.114

### 🐋 Docker Version

Docker version 20.10.17, build 100c701

**Comment by ThomasChr** [comment]
can't reproduce on current master 5c25354682bfbf9906772ee863bd3a556febedeb

**Comment by louislam** [comment]
Close as non reproducible and no other reports.
