### ISSUE TITLE
Matrix - Unable to verify the first certificate

### ISSUE THREAD

**Issue by Chiller2019** [louislam/uptime-kuma#1904]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

I set Matrix (Synapse) as notification-provider but when I send a test-message, I get an error.

![Matrix](https://user-images.githubusercontent.com/50303399/179395556-849d4306-fbd3-4ca3-afdf-10ab6977198a.jpg)

and Log:
![Log](https://user-images.githubusercontent.com/50303399/179395568-798cb051-86c8-4d47-991f-94e82a7892bd.jpg)

Now my question, how can I install my self-signed RootCA or deactivate TLS-Check?

PS.: Uptime-Kuma has a Proxy over Traefik

I import the CA Certificate on the host, with `curl -XPOST -d '{"type": "m.login.password", "identifier": {"user": "botusername", "type": "m.id.user"}, "password": "passwordforuser"}' "https://home.server/_matrix/client/r0/login"` I became a right output without faults.

![Matrix_Output](https://user-images.githubusercontent.com/50303399/179427855-61f8206a-34bf-4336-9741-cebd8bab762f.jpg)

### 🐻 Uptime-Kuma Version

1.17.1

### 💻 Operating System and Arch

Ubuntu 20.04.4 LTS

### 🌐 Browser

GC 103.0+

### 🐋 Docker Version

20.10.17

**Comment by Chiller2019** [comment]
Can no one help?

**Comment by HolgerAusB** [comment]
I have the same problem with homebridge. It seems to be problem with the web-server part , Because curl is raising the error too.

My problem is, that checking 'Certificate Expiry' is not working when 'ignore TLS/SSL-errors' is active. That should be changed.

**Comment by Chiller2019** [comment]
> I have the same problem with homebridge. It seems to be problem with the web-server part , Because curl is raising the error too.
> 
> My problem is, that checking 'Certificate Expiry' is not working when 'ignore TLS/SSL-errors' is active. That should be changed.


And what exactly did you do to solve the problem?

**Comment by HolgerAusB** [comment]
As a user, I can't!

Kuma does not send a notification on cert expiry, when you set 'irgnore TLS/SSL-errors'. From my point this is a bug to kuma.

On the other hand, it is a bug to the webserver-engine of your/mine smarthome software. Don't know if this is nginx, Node.js etc. But as far as I researched, this first-cert-issue is on them. With a web browser there is no problem, they do know this middle-CA. But curl (and kuma) can't resolv this problem. The very same cert on Apache server does not have this problem with curl or kuma.

**Comment by hugokernel** [comment]
Same problem here.

**Comment by Chiller2019** [comment]
Yeahr but I think its possible to add a tag to curl when kuma will send a message. The tag is "--insecure"

**Comment by hugokernel** [comment]
False alarm for me, sorry, problem of conf in the certificate following renewal.

**Comment by Aterfax** [comment]
Can you not place your own CA cert into `/etc/ssl/certs/ ` via a bind mount? I'm not sure if Uptime Kuma itself as part of the upstart process will call the command `update-ca-certificates` though.

That might need to be added to the docker.

**Comment by Chiller2019** [comment]
> Can you not place your own CA cert into `/etc/ssl/certs/ ` via a bind mount? I'm not sure if Uptime Kuma itself as part of the upstart process will call the command `update-ca-certificates` though.
> 
> That might need to be added to the docker.

Tried months ago, doesn't work.

**Comment by Aterfax** [comment]
> > Can you not place your own CA cert into `/etc/ssl/certs/ ` via a bind mount? I'm not sure if Uptime Kuma itself as part of the upstart process will call the command `update-ca-certificates` though.
> > That might need to be added to the docker.
> 
> Tried months ago, doesn't work.

Did you try running `update-ca-certificates` from a console within the docker container first?

**Comment by Aterfax** [comment]
Setting a valid CA cert appears to have been handled in this thread: https://github.com/louislam/uptime-kuma/issues/1380

**Comment by HolgerAusB** [comment]
so for my problem with homebridge (via node.js) the solution was simple. In the config of homebridge I just changed the path to `cert.pem` to `fullchain.pem`.

**Comment by Aterfax** [comment]
> so for my problem with homebridge (via node.js) the solution was simple. In the config of homebridge I just changed the path to `cert.pem` to `fullchain.pem`.

In the case of certificates issued from Letsencrypt etc... the full chain of certificates including the CA (certificate authority), the intermediate CA certificate as well as your own domain's issued certificate must be supplied added to your service (e.g. homebridge / nginx etc... must use the fullchain.pem which contains the full chain) or some devices will be unable to verify the trust chain from your domain's certificate back to a trusted root CA certificate due to the missing middle link of the intermediate certificates.

This issue was originally filed by someone trying to use their own root CA and sub-certificates (I think). If using your own certificate authority, the details of adding the new CA certificates/trust chain are detailed in  https://github.com/louislam/uptime-kuma/issues/1380 using the NODE_EXTRA_CA_CERTS environment variable.

**Comment by rizkytegar** [comment]
how to solve this problem ?

**Comment by EgonHeuson** [comment]
Hello,
I noticed I have the exact same error when I use certificates that I have to replace each year by a new one (officially signed by an external accreditation platform). It's like UptimeKuma keeps in memory the first certificate it checks and doesn't replace it with the new one, or doesn't change which certificate it checks. 
Any idea?

**Comment by HolgerAusB** [comment]
Are you sure it's Kuma? I had a similar issue. But here it was Homebridge (NodeJS), that doesn't use the new certificate automatically, which I copied by script from a different machine via ssh. I need to reboot that RaspberryPi after each renewal of the LetsEncrypt Wildcard cert, which is done by the copy script, too (following night 3am via `at`).

**Comment by EgonHeuson** [comment]
Hey! I think so, but not sure. In my case it's pretty straightforward. I handle the certificates with NginxProxyManager for each of my application, and when I renew my certificate, I delete the old one, and add a new .cert file. My web browsers don't have any issue with the new certificates by the way. For now I deactivated the SSL check in Kuma, but don't really know what to do else.

**Comment by Namydad** [comment]
same problem

**Comment by berils** [comment]
Im facing this issue with services which are on "LAN".
RootCA imported succesfully.
External cert check works as expected. 
Has anyone found workaround/fix for this case?

**Comment by CommanderStorm** [comment]
click on the cert expiry link to see where the chain is failing:
![image](https://github.com/louislam/uptime-kuma/assets/26258709/037ba01f-bfed-43a0-8fae-9f3ba01b1c8a)

**Comment by fnaquira** [comment]
did you find a solution? I also get a valid certificate but getting error on Kuma

**Comment by HolgerAusB** [comment]
@fnaquira, not for kuma side, but if you are controlling the server, you want to check, it is always a good advise to prove, how you are implementing the certificates. For my letsencrypt cert, it helped to use fullchain.pem instead of chain.pem

e.g. for apache2 site config:
```
SSLCertificateFile     /etc/letsencrypt/live/example.com/fullchain.pem
SSLCertificateKeyFile  /etc/letsencrypt/live/example.com/privkey.pem
```
