### ISSUE TITLE
Powered By (editable)

### ISSUE THREAD

**Issue by kristiandg** [louislam/uptime-kuma#1907]
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

UI Feature

### 🔖 Feature description

I saw that the PoweredBy field can be enabled/disabled. But, when enabled, it should then present a text field to enter a custom line of text (supporting an embedded link, just like the existing "Uptime Kuma" line).

### ✔️ Solution

This would allow users to edit the Powered By line for their own custom branding, as well as have an embedded link to the hosting person's main website (if properly formatted when entered into this new field). The link could even be edited to say "Are you seeing a problem? Let us know [HERE](https://github.com/louislam/uptime-kuma)" (clickable link to launch an email or go to a reporting website).

### ❓ Alternatives

Considered using the Footer Text option, and disabling the Powered By field, but the Footer Text is a good place for contact info, known service outages, etc, so you'd have to forfeit that option in order to customize. Also, I'm not sure you can embed links into the Footer field (haven't tried), but I did consider this and it is an option to allow customization.

### 📝 Additional Context

None

**Comment by 401U** [comment]
Markdown is supported to use in custom footer line, you can disable the original `Powerd by` and add your own stuffs now.

This issue should be resolved.

**Comment by osahang** [comment]
1. sudo nano uptime-kuma/server/model/status_page.js
2. ctrl + w
3. Search for "powered"
4. comment out this line (1) "/** showPoweredBy: !!this.show_powered_by,*/"
5. comment out this line (2) change "/** showPoweredBy: !!this.show_powered_by, */"

This will remove the Powered by Uptime Kuma

**Comment by CommanderStorm** [comment]
@osahang 
It is unclear what you mean.

I would recomend to use the setting we provide
![image](https://github.com/louislam/uptime-kuma/assets/26258709/c43aef35-53a9-44e2-b4e7-8cfef974620e)

**Comment by osahang** [comment]
@CommanderStorm Sorry just saw that option now!
