### ISSUE TITLE
Twilio/SendGrid SMS Notifications

### ISSUE THREAD

**Issue by kristiandg** [louislam/uptime-kuma#1909]
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

New Notification

### 🔖 Feature description

Recommending a new Notification option - Twilio/SendGrid (same company).

### ✔️ Solution

This would be similar to the existing SMS provider options, just supporting Twilio/SendGrid, which is one of the top Programmable Telephony providers out there.

### ❓ Alternatives

All of the other SMS Notification options, but since I already have a SendGrid account, would hate to spin up a new account just for SMS functionality.

### 📝 Additional Context

Impressed by the several SMS options already presented, but admittedly, wanting one more. ;)

**Comment by CommanderStorm** [comment]
@kristiandg given that this is in uptime kuma since #2980, please close this issue 😅 
![image](https://github.com/louislam/uptime-kuma/assets/26258709/a00e9da7-5fe2-48d7-a74d-9707af55cb35)

**Comment by kristiandg** [comment]
No problem. I had written it before the feature was added.

**Comment by krisdahl** [comment]
> @kristiandg given that this is in uptime kuma since #2980, please close this issue 😅 

Just an FYI that is just Twilio Programatic SMS API, not Twilio's SendGrid email notification system.
