### ISSUE TITLE
Scheduled monitoring pause

### ISSUE THREAD

**Issue by NickBootOne** [louislam/uptime-kuma#191]
**Is your feature request related to a problem? Please describe**
If a Docker Container is being updated, I get a notification of all de Dockers Containers that gets an update.
This is also for backing up all the Containers

**Describe the solution you'd like**
A scheduled pause for the monitoring when the backup or update process is plannend

**Comment by 1noob4ever** [comment]
A must have feature.

**Comment by ScyllPoesis** [comment]
Bumping to signal interest.

**Comment by hkpanchani** [comment]
It would be great to have repetitive scheduled maintenance.
One of our server is scheduled to maintain 2am every Saturday.

It would be great to auto pause monitor at 1:55 am to 2:05am.

**Comment by jtagcat** [comment]
### GitHub Etiquette

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

**Comment by federicotravaini** [comment]
> 
> 
> It would be great to have repetitive scheduled maintenance. One of our server is scheduled to maintain 2am every Saturday.
> 
> It would be great to auto pause monitor at 1:55 am to 2:05am.

this is absolutely a must have feature since many services have scheduled start-stop time

**Comment by simphide** [comment]
Any news regarding this feature request?

**Comment by bodzio4749** [comment]
Having scheduled downtimes is a super idea. I have a backup Synology server, which stays powered off most of the week. It is powered on by the master server only for a few hours on weekends to receive volume snapshots. Having a "normal down" and scheduled "uptime " states,  based on the scheduled timetable, would be a perfect solution to a "negative" watch-only option.

**Comment by alexsahka** [comment]
Any news?
I have 8 Security Cameras doing a scheduled reboot every night. A scheduled pause for the monitoring is needed. Thanks.

**Comment by RyanWor** [comment]
> Any news? I have 8 Security Cameras doing a scheduled reboot every night. A scheduled pause for the monitoring is needed. Thanks.

The only real workaround I've found for this right now is just to stop the uptime-kuma container during maintenance windows. Of course this is an extremely inelegant solution and not something that can be justified in a production environment if uptime-kuma were still monitoring other critical services but it is what it is right now. The application is still very new and it's far easier and better than most other things I've tried so I'll be patient until either monitor pause scheduling/downtime windows are implemented. Other possible alternatives could be filtering the alerts uptime-kuma outputs yourself through some method which doesn't pass certain alerts during certain time periods (but of course that kinda defeats the simplicity of uptime-kuma in the first place).

**Comment by chakflying** [comment]
Thinking about this, I see 2 ways of doing this.

- Literally as the title suggest, allow the user to define a time when monitor pause should be triggered, and a time when monitor resume should be triggered. This list is stored in database, then maybe there is a background job checking every minute which monitor should be paused and which should be resumed, and execute it.

- Allow the user to define the expected state of the monitor on a timeline. For example, the user can set 00:00 - 00:02, the target should be down. The monitor keeps running normally, but it will compare the checked state of the target with the expected state, and only send notification if they are different. This has the advantage of working nicely with the currently "inverted monitor" option, and the monitor keeps gathering data.

**Comment by RyanWor** [comment]
Honestly the best approach imo would be something similar up his Uptime Robot implements this. You have certain schedules of downtime and similar to notifications they can be enabled/disabled per monitor. That way when you have Uptime Kuma monitoring a dozen or more services on the same host they can easily be assigned the same window dynamically since they'd be expected to be down together frequently. 

Alternatively (or in addition too, something I wished UR had forever) is alerts can be chained. Example: If HostA ping monitor fails, don't alert on HostA-Service1, HostA-Service2, and HostA-Service3. One server down alert that mutes 20 more service down alerts would be extremely welcome and eliminate the vast majority of alerts I get for "known down" situations.

**Comment by Peppershade** [comment]
This is a must-have. The best way to do it is on a per monitor base. We have many services that have scheduled restarts at night, already woke me up once. The other way would be to disable the notification channel between a certain time. That would also be helpful enough.

**Comment by douglasparker** [comment]
I'm hoping PR #1213 gets implemented!

I really need maintenance windows to avoid email notification spam filling my inbox during backup and update windows.

**Comment by athornfam2** [comment]
Just adding to this... Would be nice to have a one-time and continuous start and stop monitoring option. Single use for maintenance and continuous use for VM's (example - a VPN server that's turned off after business hours to save on money).

**Comment by kristiandg** [comment]
Some additional desired behavior:

The ability to schedule a maintenance window, and indicate which monitors are impacted, so they don't alert during that time (selectable to not alert, alert maintenance start/end, and alert as normal).

When a maintenance schedule is created, at the start of the window, the impacted monitors (selected at the time of creation), will go into a new mode that shows "Maintenance" (could even do this by displaying the monitor with a quaint "construction barber pole yellow/black banner over the monitor, or a set of emojis).

For alerts, if set to start/end, alerts would be send at the beginning/end of the maintenance window only. If alert as normal was set, then it would still send alerts, but an added line would indicate it's currently in maintenance so the alert should be treated accordingly.

If accessible from the API, might even allow someone's existing ticketing system to auto build maintenance windows based on approved/scheduled change activity.

**Comment by nvm-jeff** [comment]
An API call to pause/unpause a monitor would do nicely.

**Comment by CommanderStorm** [comment]
For an http api and the status of said feature, please see
- #118
