### ISSUE TITLE
Subscribe to Status Page updates.

### ISSUE THREAD

**Issue by kristiandg** [louislam/uptime-kuma#1911]
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

UI Feature

### 🔖 Feature description

Status Pages, allowing the ability to subscribe to updates, via any practical methods.

### ✔️ Solution

When visiting a status page, the user has the option to "subscribe" by some of the suggested options below:

- RSS Feeds (I saw the feature request asking for an RSS Notification, but this would be different - this would be someone subscribing to changes on a status page, not an active push).
- Email alerts (basically, allowing self-signup, though you'd want to do some sort of email validation so random emails didn't get built in the system. would also need an unsubscribe option).
- SMS (same as email alert sign-up) but with SMS numbers - again, would need some sort of code validation so random people didn't get subscribed - would also need an unsubscribe option).

### ❓ Alternatives

None that I've found.

### 📝 Additional Context

None

**Comment by webysther** [comment]
Same than #916

**Comment by webysther** [comment]
@louislam please close as repetitive or give me access to to so if you want.
