### ISSUE TITLE
"error:1408F10B:SSL routines:ssl3_get_record:wrong version number" on https monitoring

### ISSUE THREAD

**Issue by T0bst3r** [louislam/uptime-kuma#1914]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

Monitoring the URL test2.suitec.de works without problems in http, but throws following error on https:
"write EPROTO 139905839380416:error:1408F10B:SSL routines:ssl3_get_record:wrong version number:../deps/openssl/openssl/ssl/record/ssl3_record.c:332:"

The screenshot shows me switching between the http and https version multiple times
<img width="874" alt="Screenshot 2022-07-17 at 21 31 24" src="https://user-images.githubusercontent.com/61892965/179423931-b72fe270-ef2e-4dba-abc5-a19db3ce44ac.png">

Visiting the https website in the browser works without problems
A quick google search yielded me the possibility of http being provided on the https port, however trying to enforce http on port 443 returns an error and calling the https site did not seem to leave any trace of http in the wireshark logs

The Server behind the URL is running behind a proxy, however I think it to be unlikely that that is the cause of the problem, seeing as test1.suitec.de is running behind the same proxy and has no problems being monitored on both http and https.

In theory I could just monitor the status of the server itself in http and that would solve most of my problems, however then I wouldn't be notified if for some reason the renewal of certificates failed, so I would really like to get this running properly. 
Any help would be appreciated and I am open to questions

### 🐻 Uptime-Kuma Version

1.17.1

### 💻 Operating System and Arch

Ubuntu 22.04 LTS

### 🌐 Browser

Google Chrome Version 103.0.5060.114 & Safari Version 15.3 

### 🐋 Docker Version

Docker version 20.10.12, build 20.10.12-0ubuntu4 & docker-compose version 1.29.2, build unknown

**Comment by louislam** [comment]
Was it randomly happened?

I suggest that you should setup another Uptime Kuma instance in a different location, see if the issue is still existing.

**Comment by T0bst3r** [comment]
Hey, I'm sorry for the lack of response.

I have by now tried it in the Sandbox environment and there the Address was perfectly reachable under https. I will have to move my installation soon anyways, so I have the hopes that that will fix my issue. If not I'll ask here again.

Thank you for the help :)

**Comment by JohnnyChiang** [comment]
I had the same issue.
And it happens randomly

Version: 1.18.0

![螢幕快照 2022-09-20 下午1 38 21](https://user-images.githubusercontent.com/2437629/191176090-15362619-6e14-4bcf-a234-4629da120d3a.png)
