### ISSUE TITLE
Monitoring groups

### ISSUE THREAD

**Issue by nick1boot** [louislam/uptime-kuma#192]
**Is your feature request related to a problem? Please describe.**
Currently with a lot of monitoring sensors the view gets big and there is no overview

**Describe the solution you'd like**
Grouping of certain monitoring sensors, with folders or tags that you can assign for better overview

**Additional context**
![Kuma](https://user-images.githubusercontent.com/59101602/128667978-34e69a3d-46c2-4e8b-a5a2-77560feff809.png)

**Comment by louislam** [comment]
#12
