### ISSUE TITLE
How to sort by down websites first? 

### ISSUE THREAD

**Issue by amityweb** [louislam/uptime-kuma#1921]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

Sorry if been asked before, can't find it...

I can't see how to get my down status websites to the top of the list. The status list is no good, as it just shows the status changes in date descending order, not the ones that are down still. Not having down websites at the top means it's harder to review and find them. 

Example use case... Let's say one of my servers go down, so I get 100 down alerts. Then it comes back up and I have 99 up alerts. The status list will show 100 down, then 99 up. BUT if one or more of those sites stays down for whatever reason, then it's not easy to find when you have a long list of websites. Its not at the top in the status list nor the website list. I have to scroll down my website list slowly until I find it. Sometimes I like to review uptime monitor to make sure everything is up, and my old system would just list down sites at the top, but this system I have to scroll down my huge list. 

So is it possible to sort by down at the top, or do I need to make a feature request? 

Thanks

### 🐻 Uptime-Kuma Version

1.17.1

### 💻 Operating System and Arch

Ubuntu 20.04

### 🌐 Browser

Chrome latest

**Comment by zolotarev** [comment]
Realized in #1585

**Comment by amityweb** [comment]
I'd like a reply yes it's very important to have this feature

**Comment by jeremyrnelson** [comment]
@amityweb  - it seems like we've got a lot of tickets open referencing the same features, which splits up the responses and keeps this from rising to the top.  Is there anything in this ticket that's not covered in #1585 where there's already a pull request?  If not, can you close this?
