### ISSUE TITLE
How long does Uptime Kuma wait for a response? Are we able to change it? 

### ISSUE THREAD

**Issue by amityweb** [louislam/uptime-kuma#1922]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

Sorry if been asked before, can't find it...

My old system I developed waits 10 seconds before it decides a website is down. Because a website can be considered down when its response time is too long. If its too long something is wrong, people have bounced. 

My old system still sends me down alerts for these sites, but uptime kuma is not. I guess its because uptime kuma is waiting a much longer time, and eventually the site responds perhaps. 

But that website clearly has an issue I need to be alerted about. So is there a way I can change the wait time for a response, so I can get an alert when a site takes ages? 

Thanks 

### 🐻 Uptime-Kuma Version

1.17.1

### 💻 Operating System and Arch

Ubuntu 20.04

### 🌐 Browser

Chrome latest

**Comment by amityweb** [comment]
Would be good to get an answer on this one so keeping it open.

**Comment by amityweb** [comment]
Is it possible to change the timeout? I would like to be alerted to slow websites. 48s is too long. I'd like to have a "down" alert if it takes 10 seconds before it responds. Evven of the interval is 60 seconds. Thanks.

**Comment by markhc** [comment]
I also agree this is a much needed option. A 48 second timeout is way too much to monitor the availability of essential services.

**Comment by zenyr** [comment]
btw: #2142 would allow you to specify timeout milliseconds but still awaiting merge. 😅
