### ISSUE TITLE
IP with 0, get shifted

### ISSUE THREAD

**Issue by pepitooo** [louislam/uptime-kuma#1929]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### Description

The link preview and get to do the check might be wrong when a 0 is inside the IP address use as padding

### 👟 Reproduction steps

Using the HTTP Keyword functionnality
If the IP is entered with a 0 like 172.16.010.1 it will look 172.16.8.1

### 👀 Expected behavior

should get from 172.16.10.1 

### 😓 Actual Behavior

172.16.8.1

### 🐻 Uptime-Kuma Version

1.17.1

### 💻 Operating System and Arch

Docker

### 🌐 Browser

Brave current

**Comment by pepitooo** [comment]
It might be a bug from the browser.

**Comment by louislam** [comment]
It is expected. 

With leading zero, it is octal. 010 = 8


Make your simpler, don't use leading zero.
