### ISSUE TITLE
Missing donate button

### ISSUE THREAD

**Issue by ronnicek** [louislam/uptime-kuma#193]
Thanks for a great tool. I just test it in docker.. and I already love it, so I am asking.. where is the donate button? I can't donate much, but at least something. Also every penny counts :-)

**Comment by louislam** [comment]
Thank you so much! 

It's OK. I enjoy to develop applications that everyone love it. Make the world a little bit better.

If you want to support my work, share with your friends and to the world. And don't forget to give me a star on Github. ⭐🐻

**Comment by louislam** [comment]
Since a few of users would like to buy me a coffee, I eventually added Sponsor Button. 
Thank you for your support!
