### ISSUE TITLE
multi-selector for probes

### ISSUE THREAD

**Issue by HujinoKun** [louislam/uptime-kuma#1930]
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

UI Feature

### 🔖 Feature description

Hello,

Would it be possible to implement the multiple selection for the probes in order to make a mass action?

When you start to have hundreds of probes, it is quickly painful to make identical modifications between several probes.

### ✔️ Solution

Have the ability to take multiple actions on :

- removal of probes
- pause the probes
- labels
- notifications

**Comment by MrT3acher** [comment]
I need this feature too. I have 128 monitors. It's so painful to pause some of them.

**Comment by CommanderStorm** [comment]
@HujinoKun 
This feaure was implemented and merged in https://github.com/louislam/uptime-kuma/pull/1886 and will be avaliable in the upcoming `1.23` release (beta should be avaliable in a few days)

Could you close this issue as it is resolved?
Only you or Louis can close issues => otherwise this will become one of the zombies that cannot be killed

**Comment by HujinoKun** [comment]
Hello,

sorry for the response time.

concerning my request :

    removal of probes :no_good: (example: removal of probes following product shutdown (generally, we can have many probes))
    pause the probes :ok: 
    labels :no_good: (example : a customer's name has changed and we need to replicate this change on these probes)
    notifications :no_good: (example : change of notification system (migration from slack to mattermost))

It's essential that we can take mass action on these points.

**Comment by CommanderStorm** [comment]
I think the remaining issues are a duplicate of https://github.com/louislam/uptime-kuma/issues/455
If you agree, could you please close this Issue, as duplicates only create immortal zombies and are really hard to issue-manage?
If not, what makes this issue unique enough to require an additional issue? (Could this be integrated into the issue linked above?) ^^

**Comment by HujinoKun** [comment]
Bulk edit/pause : OK

For the other points, no.

I'll create another issue and close this.
