### ISSUE TITLE
Vercel : Cannot connect to the socket server

### ISSUE THREAD

**Issue by LeeSpo** [louislam/uptime-kuma#1933]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

I build it based on Vercel, it successfully built. But when I open the domain,it shows that `cannot connect to the socket server`
![image](https://user-images.githubusercontent.com/75921239/180450383-1d5a24ff-10a2-44d4-a310-2cd93f380df3.png)
How to config can I use it on vercel 
Thanks!
Build logs are given below
[Build Logs.txt](https://github.com/louislam/uptime-kuma/files/9168114/Build.Logs.txt)

### 🐻 Uptime-Kuma Version

Latest (forked from repo)

### 💻 Operating System and Arch

Vercel Server ?

### 🌐 Browser

Edge 103.0.1264.62

**Comment by cktsun1031** [comment]
Vercel doesn't support serverless function with `socket`

**Comment by asuraslash** [comment]
kzc
