### ISSUE TITLE
how to setup read-only pages ?

### ISSUE THREAD

**Issue by spamandeggs** [louislam/uptime-kuma#1935]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

Hi,
first of all thank you for this app, this is really a nice work.
Im sorry about this question but _it seems_ uptime-kuma provides a ready-only/public access to status page, or to some group in a status page, or to monitor... ?
but i cant find anything to setup this in the interface or in the wiki.
I run Node v18.6.0 with * (HEAD detached at 1.17.1) on linux mint, all installed a few hours ago/

### 🐻 Uptime-Kuma Version

1.17.1

### 💻 Operating System and Arch

Linux Mint 20.3

### 🌐 Browser

firefox

### 🐋 Docker Version

not used

### 🟩 NodeJS Version

v18.6.0

**Comment by danijelst** [comment]
@spamandeggs you can do so, by clicking on *Status Pages* on top right corner. This will bring you to the status pages where you then can create a new status page and decide what the "slug" should be for later access.

**Comment by baozitao** [comment]
I can't find any method to make status pages to read only function , any description on wiki?
