### ISSUE TITLE
Add 'from' field to mail notifications

### ISSUE THREAD

**Issue by wouterVE** [louislam/uptime-kuma#1939]
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

Other

### 🔖 Feature description

Add a  `From `field in mail notifications settings to enter the name of the sender. 

### ✔️ Solution

I've configured one mail-address on my server to use across different services. It would be nice to have an option to enter a sender's name to the mail notifications (e.g. 'My Uptime Kuma') to distinguish these mails from other mails from this server. 

See example:
currently =` From: <my.cloud@yahoo.com>`
desired = `From: **My Uptime Kuma** <my.cloud@yahoo.com>`

The text in bold is a field that can be entered in the mail notification settings (e.g. `From`)

### ❓ Alternatives

Not applicable

**Comment by miberecz** [comment]
+1

**Comment by de-es** [comment]
Just enter something like `Uptime Kuma <my.cloud@yahoo.com>` in the field `From Email`. Works for me.

**Comment by CommanderStorm** [comment]
@wouterVE 
It seems that this issue is resolved.
Is tere something missing or can I close it?

**Comment by wouterVE** [comment]
@CommanderStorm indeed this works for me. The issue may be closed.

@de-es thanks for your input
