### ISSUE TITLE
docker update to latest version of kuma not work

### ISSUE THREAD

**Issue by johnfelipe** [louislam/uptime-kuma#1941]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### Description

```bash
docker pull louislam/uptime-kuma:1
docker stop uptime-kuma
docker rm uptime-kuma

# Default
docker run -d --restart=always -p 3001:3001 -v uptime-kuma:/app/data --name uptime-kuma louislam/uptime-kuma:1
```
not working

### 👟 Reproduction steps

```bash
docker pull louislam/uptime-kuma:1
docker stop uptime-kuma
docker rm uptime-kuma

# Default
docker run -d --restart=always -p 3001:3001 -v uptime-kuma:/app/data --name uptime-kuma louislam/uptime-kuma:1
```
not working

### 👀 Expected behavior

when update view latest features like:
Postgres monitor

### 😓 Actual Behavior

is not view all new features

### 🐻 Uptime-Kuma Version

Latest

### 💻 Operating System and Arch

Ubuntu 20

### 🌐 Browser

Chrome

### 🐋 Docker Version

Docker 20

**Comment by johnfelipe** [comment]
Pls share steps and command for create docker image with latest features and strings translated to spanish with own files

**Comment by louislam** [comment]
The features which you mentioned is not yet released.

If you would like to test it, please see https://github.com/louislam/uptime-kuma/blob/master/CONTRIBUTING.md](https://github.com/louislam/uptime-kuma/blob/master/CONTRIBUTING.md

**Comment by johnfelipe** [comment]
i want to know steps for build and test docker image, and contribute
