### ISSUE TITLE
API for Android App

### ISSUE THREAD

**Issue by Abdelilah27** [louislam/uptime-kuma#1943]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

We want to develop an uptime kuma app for Android,  and we need an API for That

### 🐻 Uptime-Kuma Version

Any

### 💻 Operating System and Arch

Any

### 🌐 Browser

Any

**Comment by louislam** [comment]
See #118

**Comment by andreapx** [comment]
@Abdelilah27 did you develop the app?

**Comment by Abdelilah27** [comment]
During my 2-month internship last year, we developed the Android mobile version of Uptime Kuma, utilizing technologies such as MVVM, Coroutines, and Android Jetpack Navigation Components. We also implemented various forms of authentication, including username and password, domain name, and VPN. Despite our efforts, we were unable to fully test the app due to time constraints.

**Comment by Abdelilah27** [comment]
@busybox11, I apologize for the delayed response. The reason for the delay is that the app has not been published due to copyright reasons. We need the owner's permission before we can publish it. However, you can still download the source code and generate the apk. Please note that the app has not undergone all tests as it was developed specifically for my internship.

**Comment by Abdelilah27** [comment]
@fischer-felix, you're right

**Comment by tshipenchko** [comment]
Hello @Abdelilah27! How is it going with an application?
