### ISSUE TITLE
I can’t install / configure any type of Notification service

### ISSUE THREAD

**Issue by mala57** [louislam/uptime-kuma#1944]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

 I can’t install / configure any type of Notification service? I have tested with Telegram, SMTP and Discord. I can save them but when I’m tying to test it takes forever and I’m getting an error like EIA GAIN or something similar.
Installed local using the installation script in OPT. 

### 🐻 Uptime-Kuma Version

1.17.1

### 💻 Operating System and Arch

Raspberrry Pi

### 🌐 Browser

Chrome

**Comment by louislam** [comment]
It looks it cannot resolve domain for some reason.

Could you try `curl https://google.com` and `ping google.com`

**Comment by mala57** [comment]
Ah! Embarrassing!
But now it works thx buddy.
