### ISSUE TITLE
Stream Deck integration

### ISSUE THREAD

**Issue by MisterCookie1234** [louislam/uptime-kuma#1948]
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

API, Other

### 🔖 Feature description

First of: I couldn't decide for a proper Request Type, so please bear with me. 

I'd like to have a Stream Deck integration for uptime kuma. 
I know this might not be top priority, probably for years to come, but i'd love it. 

I'd love to be able to map certain monitors to my stream deck to instantly see if they are up or down sort of live instead of just taking a look on the status page or whatever. Just Quality of Life really.

### ✔️ Solution

![image](https://user-images.githubusercontent.com/24813669/181278999-276455a2-ee46-4d4c-9863-94cbedf136ca.png)

Something like this (Mockup using paint.net) would be suppper useful for me. 
Having a Status Page right next to me on a desk where clicking on the faulty monitor would lead me directly to a certain url would be a insane QoL feature. Like i mentioned above: Not that Important, but a nice thing to have imo.

**Comment by MarlBurroW** [comment]
I'm working on it

**Comment by MarlBurroW** [comment]
https://github.com/MarlBurroW/Streamdeck-Uptime-Kuma

**Comment by CommanderStorm** [comment]
@MisterCookie1234 Given that there is an external tool for this, I think this issue can be closed.

**Comment by CommanderStorm** [comment]
Closing as resolved by the external tool
