### ISSUE TITLE
Add the ability to monitor IPv6 only services

### ISSUE THREAD

**Issue by Kazer67** [louislam/uptime-kuma#195]
Using the docker installation, which work fine, I noticed that I could setup easily test monitoring toward Google, Qwant, Netflix etc; and it work well.

I then tried the same toward some of my IPv6 only services and I get an "getaddrinfo ENOTFOUND domain.tld" error (I can confirm those services work well because I can access it through my browser or even outside from my mobile phone without issue).

I did the testing of Uptime-Kuma on my Linux desktop and I have no issue with dig/nslookup to hit those domain (usually this error could indicate a DNS issue).

So it look that it doesn't support IPv6 currently.

**Comment by louislam** [comment]
Which monitor type did you use?

I just tested IPv6 in different cases. Although ping type is not working, it is not "getaddrinfo ENOTFOUND domain.tld" error.

Please test the dns inside Docker if you are using Docker.

![image](https://user-images.githubusercontent.com/1336778/128856037-d8fee50d-5c48-4ea6-ab91-3ab67b95f7f5.png)

**Comment by Kazer67** [comment]
I just tested the non-docker installation and it worked.

Seem to be a problem on my side with my Docker setup and not from UpKuma.
