### ISSUE TITLE
Better understanding TCP Ping Timeouts on a DNS target

### ISSUE THREAD

**Issue by polds** [louislam/uptime-kuma#1954]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

I'm trying to troubleshoot some timeouts that Kuma reports for a DNS TCP Endpoint - I can't figure out why they're being marked as timeouts.

I have 3 TCP Pings that map to local IP addresses:
s01 - 10.20.1.2
s02 - 10.20.1.3
s03 - 10.20.1.4

Each of these tests average ~4 ms ping and have a 24 hour uptime of over 98%.

I have an external DNS record that runs on Google's CloudDNS which [claims 100% availability](https://cloud.google.com/dns/sla). The record (we'll call it s.example.com) maps the internal IP addresses on a publicly available record:

ie:
```
dig +short s.example.com
10.20.1.2
10.20.1.3
10.20.1.4
```

So I have a TCP Ping to this public record `s.example.com`.  The latency is understandably higher due to roundtrip DNS lookups, I'm averaging 100ms but see responses ranging in the 25ms - 250ms range.

But, I also have DNS A Kuma test for this `s.example.com` record and has 100% availability and is in the < 60 ms range.

The thing I can't figure out is many many tests are timing out for the TCP Ping on the DNS Record, to the point that this endpoint is claiming an uptime of 64% over 24 hours. The underlying internal records have never spiked higher than 25ms, Google's DNS is definitely not down, and yet this TCP Ping that tries to use the record with 3 IPs has the highest latency and many timeouts. Even a local netcat test run locally doesn't see any downtime of any kind.

So the questions I have are:
 - Where does that average 40-150ms of additional latency come from? I can get DNS responses in less than 60 ms, the ping tests can be done in less than 4 ms. But the the tests that exercises both can be from the 100-250ms range
 - What is the TCP Timeout set to - can it be tweaked, and can Kuma correctly handle records that return multiple IP addresses for TCP Ping tests?
   - And why does an average latency of 100-250ms qualify as a timeout?
 - What DNS resolver does TCP pings use? I'm in Kubernetes, I've modified my DNS ping to use the KubeDNS and my own LAN DNS Server and neither of them receive any timeouts or latencies higher than 20ms

### 🐻 Uptime-Kuma Version

1.17.1

### 💻 Operating System and Arch

Ubuntu 22.04

### 🌐 Browser

Chrome

### 🐋 Docker Version

K3s v1.24.3+k3s1

**Comment by chakflying** [comment]
The `tcp-ping` package uses node.js's `Socket.connect()`, which uses node.js's `dns.lookup()`, which then goes to the system's resolver through `libuv`. The layers of indirection probably increased latency.

On the other hand, the DNS monitor type uses `dns.resolve()`, which does not go to the system resolver and should be much faster (I think).

The `tcp-ping` package uses a default timeout of 5s. I'm not sure about this but I think what could happen is if libuv is too busy and ran out of threads, it can lead to a timeout during the DNS query phase.

The TCP ping monitor type should work better if you don't use a hostname. This is not ideal and we could look into adding DNS cache to TCP ping as well.

**Comment by artyPD** [comment]
I am having the same issue as well.

Latency is low and my services have no down time. Yet, Uptime Kuma seems to timeout from time to time at random intervals.

Does anyone know what could cause this? Also, why is there a TCP ping but not a UDP ping?

Can this issue be re-opened?
