### ISSUE TITLE
Improve notification

### ISSUE THREAD

**Issue by Gottarocket** [louislam/uptime-kuma#1956]
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

Other

### Improvement in notification.

I use signal api to get notification and get all updates. But since I have many docker containers I get multiple Up and Down notifications all at once. This is better but sometimes some container wont be up. Since I just see all container showing up when scrolling I fail to check each containers. So when one container is down I wouldnt know. I had  a container down for 3 days and was notified but didnt know it wasnt up.

### ✔️ Solution

When a connection drops it properly notifies its down. But when it is up its better to also notify which connections arent up yet so we can know and get it up. If it is notified it will help us know among all those containers which are up one container is still down

**Comment by Gottarocket** [comment]
Similar to [this](https://github.com/louislam/uptime-kuma/pull/1212) but instead of waiting for specific time. Notify when all other containers are up.

**Comment by CommanderStorm** [comment]
@Gottarocket I think what you want is implemented currently:
![image](https://github.com/louislam/uptime-kuma/assets/26258709/b72ed258-78e0-4849-8e37-174214c82986)

=> You can entirely customize how you want a notification to be retried if a service stays down

**Comment by CommanderStorm** [comment]
Closing as notification retry settings resolves

> also notify which connections arent up
