### ISSUE TITLE
Is it possible to provide an api interface for querying the online rate of a website's time period？

### ISSUE THREAD

**Issue by dakangsiji** [louislam/uptime-kuma#1961]
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

API

### 🔖 Feature description

For example:
   use the api interface to query the online rate of  website for 1 year, and output the result in percentage row format；
format：
  https://webist-01.com  online-rate：99.99%
  https://webist-02.com  online-rate：99.00%
  .......

### ✔️ Solution

no

### ❓ Alternatives

no

**Comment by CommanderStorm** [comment]
@dakangsiji
Now I figured out of what issue this is a duplicate:
you are not requesting an API, you are in fact requesting the uptime to be added to the `/metrics` endpoint wich is tracked in https://github.com/louislam/uptime-kuma/issues/3338

=> closing as a duplicate
