### ISSUE TITLE
Support gRPC protocol

### ISSUE THREAD

**Issue by minhhoangvn** [louislam/uptime-kuma#1963]
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

New Monitor

### 🔖 Feature description

In our system, we need to monitor internal services which only support the gRPC protocol

### ✔️ Solution

Using protobufjs and @grpc/grpc-js to allow user can monitor their gRPC service

### 📝 Additional Context

<img width="1272" alt="image" src="https://user-images.githubusercontent.com/17515250/182428395-a7b39aac-89b6-4aa7-a969-dd87305d9264.png">

<img width="1252" alt="image" src="https://user-images.githubusercontent.com/17515250/182428505-0f98690f-f12f-4f40-b81c-9cf469888a48.png">

**Comment by CommanderStorm** [comment]
Closing as resolved by #1964
![image](https://github.com/louislam/uptime-kuma/assets/26258709/38d9cdf1-1dbe-4734-a6d1-9880ed827d10)
