### ISSUE TITLE
Installing on Server doesn't work

### ISSUE THREAD

**Issue by RitZz48** [louislam/uptime-kuma#1969]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

I am trying to run uptime kuma in my server. using Nodejs and pm2. I am following the installation guide provided in Readme letter to letter. in pm2 monit it shows uptime kuma is running, But when I try to open http://serverip:80 or http://serverip:3001 I am not getting any response. (This is not a docker installation)

### 🐻 Uptime-Kuma Version

1.17

### 💻 Operating System and Arch

Ubuntu 22.04

### 🌐 Browser

Brave, Edge, Chrome, Firefox

### 🐋 Docker Version

NA

### 🟩 NodeJS Version

16.16.0

**Comment by chakflying** [comment]
Did you check the pm2 logs after the server is started? Does it say `INFO: Listening on 3001`?

**Comment by RitZz48** [comment]
I don't see any such options, but this is what I see when I do Pm2 logs.

**Comment by ThomasChr** [comment]
a) is there a firewall?
b) can you see the port in netstat -atulpen ?

**Comment by RitZz48** [comment]
Hey, There is no firewall and port is open

**Comment by ThomasChr** [comment]
Is something a little bit more Uptime Kuma related in the uptime kuma logfile from the screenshot of the pm2 logs?
/root/.pm2/logs/uptime-kuma* ?

**Comment by RitZz48** [comment]
I am installing docker right now and will try to install kuma through docker. i will update you soon

**Comment by ThomasChr** [comment]
Docker is very easy, just two commands. So I'm pretty sure it will be running in no time!
