### ISSUE TITLE
Monitored device category

### ISSUE THREAD

**Issue by wglenn01** [louislam/uptime-kuma#1972]
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

UI Feature

### 🔖 Feature description

I would love to have a category per device monitored to be able to sort by device type in the dashboard. Say if I had a list of AP's a list of Routers, a list of CPE's etc.

### ✔️ Solution

I would love to have a category per device monitored to be able to sort by device type in the dashboard. Say if I had a list of AP's a list of Routers, a list of CPE's etc.

**Comment by yoxalld** [comment]
Adding to this same idea. It would be really nice to be able to create a status page that will display all monitors with a specific tag. That way you wouldn't need to add each monitor individually.

**Comment by CommanderStorm** [comment]
Filtering by tags has been implemented in `1.23`.
![image](https://github.com/louislam/uptime-kuma/assets/26258709/dd2e3a7e-b5ea-4786-98ff-d7fcfb806096)

Different sorting options (including sorting by tags) are tracked in #1308

=> closing as a duplicate
