### ISSUE TITLE
Not an issue

### ISSUE THREAD

**Issue by finnie2006** [louislam/uptime-kuma#1973]
Just wanted to point out that the project got an article in a dutch computer magazine! ![image](https://user-images.githubusercontent.com/57916807/183047009-3a64d623-41e7-4012-9a56-4b1664f2a0fc.jpeg)![image](https://user-images.githubusercontent.com/57916807/183047031-1082279c-b676-49ef-ba44-2bea425d14f1.jpeg)

**Comment by finnie2006** [comment]
****

**Comment by finnie2006** [comment]
ok then not

**Comment by louislam** [comment]
Interesting! Thanks!

**Comment by chakflying** [comment]
Cool! Surprised to see that these magazines still exists.

**Comment by CommanderStorm** [comment]
@finnie2006 
I think you can close this at this point, or is this still relevant?
