### ISSUE TITLE
More lite update ?

### ISSUE THREAD

**Issue by spencefoxtrot** [louislam/uptime-kuma#1977]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

Hello,
When I try to "update" npm, I have :
```
root@VM:~# npm install npm -g
-bash: npm: command not found
root@VM:~# 
```

So I try to "install" it :
`apt install npm`

But, like drama :
(cf screen).
![2022-08-06_18h54_50](https://user-images.githubusercontent.com/62077209/183258550-dff36e29-6cb3-49be-87ed-87bd18e2f763.jpg)

759MB needed for that...
My debian is about 160MB...

Is there more lite system plz ?

thank :)

### 🐻 Uptime-Kuma Version

0

### 💻 Operating System and Arch

Debian 11.4 64b

### 🌐 Browser

no

### 🐋 Docker Version

no

### 🟩 NodeJS Version

no

**Comment by Computroniks** [comment]
Node and NPM are both required for this project, without them the project simply will not run. Have you tried installing as per the recomendations at https://docs.npmjs.com/downloading-and-installing-node-js-and-npm?

**Comment by spencefoxtrot** [comment]
> Node and NPM are both required for this project, without them the project simply will not run. Have you tried installing as per the recomendations at https://docs.npmjs.com/downloading-and-installing-node-js-and-npm?

No.
I can't cause NPM not present.
Your link is when NPM is already install.

As you see, there is more than 2 apps (Node and NPM) in my screen... there is about one hundred apps ask to install for install NPM alone.

This installation cause 750MB of space, for a "simple" debian of 160MB current usage...

All this for a little bot.

**Comment by Computroniks** [comment]
The instructions detail how to install using node version manager as well as the downloads from the nodejs website and do not require npm to already be installed.

As for all of these other `apps`, these are dependencies of nodejs and npm. Without them, node will not function correctly. There are so many likely due to your Debian install being very light weight and as such having few libraries preinstalled.

**Comment by louislam** [comment]
Node.js is lightweight, It is just because you were not following the official Node.js installation guide.
You don't need to run `apt install npm` actually.

```bash
# Using Ubuntu
curl -fsSL https://deb.nodesource.com/setup_lts.x | sudo -E bash -
sudo apt-get install -y nodejs

# Using Debian, as root
curl -fsSL https://deb.nodesource.com/setup_lts.x | bash -
apt-get install -y nodejs
```

Reference: https://github.com/nodesource/distributions

**Comment by mabed-fr** [comment]
Hello
From my little DEBIAN 11:

```
docker system df -v
louislam/uptime-kuma           latest    4495e097b5fa   2 months ago   390.8MB   0B            390.8MB       1

du -sh /docker/volumes/uptime-kuma
27M     /docker/volumes/uptime-kuma

docker stats --no-stream
CONTAINER ID   NAME                         CPU %     MEM USAGE / LIMIT     MEM %     NET I/O           BLOCK I/O        PIDS
6dc0e2bb9e2c   kuma.exemple.com   0.81%     175.3MiB / 7.664GiB   2.23%     15.7MB / 3.28MB   90.8MB / 192MB   12
```

**Comment by spencefoxtrot** [comment]
Rewrite to avoid closing... don't have test all
