### ISSUE TITLE
[DigitalOcean one-click] Configurations lost after update

### ISSUE THREAD

**Issue by jonfairbanks** [louislam/uptime-kuma#198]
**Is it a duplicate question?**
No, was not able to find any related issues

**Describe the bug**
I used the one-click App option to deploy this application within DigitalOcean and was on version 1.0.7. When updating to the latest uptime-kuma all configuration options are lost. Monitors, notification settings, etc.

**To Reproduce**
1. Deploy the app on DigitalOcean via one-click setup
2. Wait for a version update
3. Update the app: `doctl apps update <app id> --spec uptime-kuma.yaml`
4. Load the app URL and you are requested to re-setup from scratch

**Expected behavior**
Settings persist between application updates.

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - Uptime Kuma Version: v1.0.7 --> v1.1.0
 - Using Docker?: Yes
 - OS: Linux; one-click hosted on DigitalOcean
 - Browser: N/A

**Comment by jonfairbanks** [comment]
The root cause is likely that there isn't a true database.

https://github.com/louislam/uptime-kuma/blob/master/server/database.js

Ideally the configuration would either be:
- Pulled out to an external SQLite database
- Support other database formats (NoSQL?)
- Load configs from a JSON/YAML file passed in via ENV variable(s)

**Comment by louislam** [comment]
OMG. I thought they are stored in persistent  storage, so sad.

And surprisingly, they do not provide any persistent storage for "Deploy Button".....

> There is no direct support to attach Spaces to the App Platform as of now. You might have to implement this by using Spaces in your code via the RESTful API or existing AWS S3 tools.

https://www.digitalocean.com/community/questions/mount-space-into-apps-platform


So, I removed the DigitalOcean deploy button from our README file.

For current DigitalOcean App users, I suggest you should manually backup the monitor one by one and move to another platform.

**Comment by jonfairbanks** [comment]
Thanks for the update, I will work on deploying directly for the time being. 

PS: Great app, thanks!
