### ISSUE TITLE
Tailscale Ping Integration

### ISSUE THREAD

**Issue by sc1341** [louislam/uptime-kuma#1981]
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

Other

### 🔖 Feature description

I recently installed UptimeKuma on an Ubuntu server on my Tailnet using Tailscale (https://tailscale.com/download/linux) where it monitors key infrastructure in my lab. 

To allow monitoring, I had to allow my UptimeKuma server access to ports/services/ICMP access on different aspects of my Tailnet environment. For security purposes, using Tailscale ping would be beneficial instead of ICMP level ping because it would prevent the need for making ACL rules and create better network segmentation. Tailscale would just be able to ping the device, and UptimeKuma could recieve the pong from the TS CLI interface and report the device status. 

Tailscale ping: https://tailscale.com/kb/1080/cli/?q=ping#ping

This would create some challenges in Docker container environments I would imagine, but bare-metal installs would be able to access the CLI as a user-level account as long as Tailscale is configured that way.

### ✔️ Solution

Create some sort of method for invoking the `tailscale ping {HOST}` instead of just the standard ICMP level ping.

**Comment by TerenceLiu98** [comment]
@DennisGaida Hi, I try to build the image via your Dockerfile and run the image. Somehow, I met this error from the log:

```shell
2022/08/09 16:53:16 is CONFIG_TUN enabled in your kernel? `modprobe tun` failed with: modprobe: can't change directory to '/lib/modules': No such file or directory
2022/08/09 16:53:16 wgengine.NewUserspaceEngine(tun "tailscale0") error: tstun.New("tailscale0"): operation not permitted
```
1. I first try using the host network for the docker, it can identify tailscale0 but cannot correctly ping the tailnet
2. I removed the tailscale from the host, but this still happened. 
2. Ialso map the `/dev/net/tun` to the docker, still happened

**Comment by TerenceLiu98** [comment]
@DennisGaida Still not working 😂 I just gave up using uptime for tailnet.

**Comment by MG-Sky** [comment]
ok today I wanted to test ping to my Tailscale devices from the uptimekuma inside.of the docker... and I got it working :⁠-⁠) without any significant changes 


solution: mount /etc/hosts from container to the docker host and add entry for your Tailscale IP:
IP hostname

then use this hostname for ping integration, I tested with newest version and it works well!

**Comment by sc1341** [comment]
Hi everyone,

So sorry for the delay in reply to all of this. Thank you for all of this information, and it is helpful for many use cases, however it still does not address the fundamental aspect of the potential feature I was inquiring on. I have not properly explained myself, so I apologize. 

`tailscale ping X.X.X.X` is different from `ping 100.X.X.X` 

Tailscale ping, using the first command, is not an ICMP request, rather it is an abstraction on the protocol to determine if a host is connected to Tailscale. This is similar to how it could be view in the admin console, where there are green circles next to a device to see if it is online. The requesting device (the one performing the `tailscale ping X.X.X.X` command, DOES NOT have to have any ACL access rights to the device. Any device can do a Tailscale ping to determine another's status. 

When using the standard ping command (ICMP) you must allow through ACL controls the requesting device to see those other hosts. I would like to assume we do not trust the Uptime Kuma installation, and not allow that device to access any ports. 

For example, my NAS is on Tailscale, and I use UptimeKuma hosted in a VPS to monitor its status, but UptimeKuma needs access to the device through the ACL to determine its status. This is not ideal from a security standpoint, but not the end of the world assuming an individual has properly imposed a defense-in-depth approach. This "not ideal" is what I am attempting to solve with this hypothetical feature. 

Uptime Kuma's role in this would be to implement a specific feature that basically creates a wrapper for this Tailscale utility, and determines the status of the device based on the output.

Keep in mind, this would get complex depending on how one uses Uptime Kuma, so a docker container without Tailscale directly installed would not be technically possible from my understanding (limited). This feature request is highly niche, and would require special programming specifically for Tailscale, so totally understandable if the developers do not find this to be important enough to include. 

The advantages of this would be that the Uptime Kuma installation does not have to have access to all ports on the hosts that it is monitoring.

**Comment by SGprooo** [comment]
> Yeah I know that error concerning the userspace not working - for me it works when I run the container with `--device /dev/net/tun:/dev/net/tun --cap-add=NET_ADMIN`, i.e. `sudo docker run -d -p 3001:3001 --device /dev/net/tun:/dev/net/tun --cap-add=NET_ADMIN --name kuma kuma` assuming `kuma` is the name I build the Dockerfile with.
> 
> Edit: My Dockerfile was actually inspired by this official article https://tailscale.com/kb/1132/flydotio/. Try to get that working first, maybe you'll find what you need to change.
> 
> I have uptime-kuma running on fly.io with this dockerfile :-)

I got a [existing working dockerfile](https://github.com/SGprooo/Uptime-Kuma-Tailscale-Docker) that works with tailscale, still no "tailscale ping", but its more concise and uses the tailscale image from dockerhub instead of fetching and extracting the tailscale tarball.

**Comment by sc1341** [comment]
> I totally understand your request, I just tried to provide a workaround. I'm running uptime kuma with tailscale installed. I'm also using ACLs just as you suggested. I am totally fine with those ACLs since I'm only allowing ICMP protocol for some hosts (` "proto": 1`).
> 
> `tailscale ping` support for uptime-kuma would mean including everything tailscale within uptime-kuma or allow calling custom binaries with custom flags - I don't think either will be easy to implement. Looking at the currently 800+ issues, I suppose you are better of doing this yourself ;-)

Yes thank you so much! I really appreciate it. I did hack together a work around using the proto method or just exposing 1 port in the ACL. My whole tailnet changed quite a bit sense Tailscale made their free tier even more generous. Thank you again for the information!!

**Comment by pdrive** [comment]
> solution: mount /etc/hosts file from container to the docker host and add entry for your Tailscale IP: IP hostname
> then use this hostname for ping integration, I've just tested with newest version and it works well!
> fyi: I have Tailscale installed on the same device where I host my docker containers (containers use own bridge network)

facing thesame issue. not sure what you mean by m**_ount /etc/hosts file from container to the docker host and add entry for your Tailscale IP: IP hostname_**

can you elaborate a bit please?  how exactly it's done?

**Comment by SGprooo** [comment]
`Tailscale ping` will be [added as a new monitor type](https://github.com/louislam/uptime-kuma/pull/3178) in 1.23.0, you can run this natively on your system; however, I'm in the process of creating a dockerfile for this specific monitor type.

**Comment by laitco** [comment]
I had the same challenge to monitor the tailscale devices and developed a healthcheck endpoint via the tailscale API. Maybe this solves the mentioned challenge here a bit as well. 

https://github.com/laitco/tailscale-healthcheck
