### ISSUE TITLE
[Feature] Allow anon users to set alerts to monitor status page for updates

### ISSUE THREAD

**Issue by mwatermolen** [louislam/uptime-kuma#1985]
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

New Notification, UI Feature

### 🔖 Feature description

The idea would be that a user can "Subscribe" to a status page and get notifications for any changes in status. This way an anonmous user can setup alerts for the status page. 

Jira's Status page has this functionality
![image](https://user-images.githubusercontent.com/73605619/183910008-0958937e-8347-4545-ac6b-4c593ffbcad6.png)

### ✔️ Solution

Add an option to subscribe to service status on the public status page to a non-registered user

### ❓ Alternatives

Adding many alerts or using a webhook to an external service, but there isnt a clean soultion

### 📝 Additional Context

Not sure, if you need anything else LMK

**Comment by webysther** [comment]
I have a OSS page on status page with lots of subscribers and wait to move to uptime kuma, but at this time without this is deal brek :(

https://status.packagist.com.br/

**Comment by webysther** [comment]
Same of #916

**Comment by webysther** [comment]
@louislam please close as repetitive or give me access to to so if you want.
