### ISSUE TITLE
Not able to reach Uptime-Kuma with PiVPN on same machine

### ISSUE THREAD

**Issue by hoentaex** [louislam/uptime-kuma#1986]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

Uptime-Kuma works really well. After I installed PiVPN (with Wireguard) on the same machine I can not reach the website from my internal network and not on the same machine. pm2 monit looks good. No error messages when restarting Uptime-Kuma. 

I am new to PiVPN. Not sure if this is blocking the local port 3001. But I have not found anything how to open a single port on this machine (not the router) for local use. 

Can anybody give me a hint?

Thanks a lot

### 🐻 Uptime-Kuma Version

1.17.1

### 💻 Operating System and Arch

Debian Buster 10.12

### 🌐 Browser

Safari 15.5 and Chrome 104.0.5112.79

### 🟩 NodeJS Version

18.6.0

**Comment by chakflying** [comment]
I can't find any indication in PiVPN that it is using port 3001. You can check which process is currently using the port ([guide](https://vitux.com/find-open-ports-on-debian/)).

**Comment by hoentaex** [comment]
> I can't find any indication in PiVPN that it is using port 3001. You can check which process is currently using the port ([guide](https://vitux.com/find-open-ports-on-debian/)).

Thanks for the hint. Did some research and have seen that nothing is listening on port 3001. Tried to stop and restart but without success. I renamed the Uptime-Kuma folder and installed it new from scratch (did not had so much devices set up yet) and everything worked well. Not sure what happened but everything is up again.
