### ISSUE TITLE
Downtimes probes

### ISSUE THREAD

**Issue by mabed-fr** [louislam/uptime-kuma#1988]
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

API, New Notification, New Monitor, UI Feature, Other

### 🔖 Feature description

Hello,

In some cases maintenance periods are caused on probes and sooner than deactivating and reactivating them after maintenance is it possible to have the "down time" functionality with a time range during which the probe will not check and will not send a notification and that it will not affect the % uptime

### ✔️ Solution

Exemple with nagios / centreon https://docs.centreon.com/fr/docs/alerts-notifications/downtimes/

### ❓ Alternatives

  NC

### 📝 Additional Context

   NC

**Comment by CommanderStorm** [comment]
I have severe problems parsing what is being requested in this issue.
Given that the content is not parsable for me, I am going to close this as `wontfix`.
From what I can parse this describes maintence periods as they are currently implemented.
