### ISSUE TITLE
Database doesn't shrink

### ISSUE THREAD

**Issue by pepa65** [louislam/uptime-kuma#1994]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### Description

I have 45 monitors, and I was keeping history for 400 days. This is leading to database issues, so I decided to set history to 30 days, clicked "Clear all Statistics", rebooted, and then tried to shrink the database by clicking on the button. But it stays at 1718.5 MB.

Is there a way to manually get the database to shrink without losing all my settings?

### 👟 Reproduction steps

Have a fair amount of monitors, keep all data for a long period, and run long enough.

### 👀 Expected behavior

It would keep working as intended.

### 😓 Actual Behavior

I get the knex warnings, and I don't get the current setting if I want to edit a monitor.

### 🐻 Uptime-Kuma Version

1.17.1

### 💻 Operating System and Arch

Ubuntu 18.04.6 LTS

### 🌐 Browser

Firefox

### 🐋 Docker Version

20.10.7

### 🟩 NodeJS Version

16.15.0

**Comment by lnxbil** [comment]
Have you checked the internal SQLite database in `<your-volume>/kuma.db`? You can see there if you still have a lot of measures in there and try to compact your SQLite database that way.

**Comment by pepa65** [comment]
Sure, I can try to check that. Can you provide a bit more guidance on how to do that please? I can get a shell in the docker container, and I guess then I will have to install `sqlite3`, and then how do I proceed?

**Comment by lnxbil** [comment]
Yes, one way is to use the container, e.g. with `docker-compose`:

    docker-compose exec <container-name> sqlite3 /app/data/kuma.db

then you get an SQL console in which you can investigate your data with e.g. this:

    select count(*), min(time), max(time), m.name from heartbeat h inner join monitor m on h.monitor_id = m.id group by monitor_id;

This shows all monitors with the number of measurements, the first and the last time a measurement was taken.

You can also look into [vacuuming into a new database](https://www.sqlite.org/lang_vacuum.html), but this has to be done while the app is offline, because it'll create a new database.

**Comment by pepa65** [comment]
The VPS it was running on had a long outage and just came back online. Your query indicated that three-quarters of all the entries started from 2021-12-04 and the rest from 2022-03-09 at the latest. So they haven't been purged. I'm happy to do so manually if I knew how, but I do think there must be a bug in the Kuma code for cleaning up.

**Comment by pepa65** [comment]
If I could export and import my settings, I could just start with a fresh database, that would be another good option.

But the best would be if Clear All Statistics would work. Is there a way to somehow fix the corruption? Everything seems to work OK, so it can't be that much damaged.

**Comment by pepa65** [comment]
**Database diagnosis**
I did `sqlite3 /app/data/kuma.db "PRAGMA integrity_check"` and this reported 25 different rows missing from index `monitor_id`.

I did `sqlite3 /app/data/kuma.db ".dump" | sqlite3 /app/data/new.db` and it seemed to work well. With `sqlite3 /app/data/kuma.db ".dump" >kuma.sql` I checked the dump and it seemed to be committing OK.

How could I replace my present `kuma.db` with the rebuilt database?

**Comment by NeckBeardPrince** [comment]
> **Database diagnosis** I did `sqlite3 /app/data/kuma.db "PRAGMA integrity_check"` and this reported 25 different rows missing from index `monitor_id`.
> 
> I did `sqlite3 /app/data/kuma.db ".dump" | sqlite3 /app/data/new.db` and it seemed to work well. With `sqlite3 /app/data/kuma.db ".dump" >kuma.sql` I checked the dump and it seemed to be committing OK (no "ERROR" present).
> 
> How could I replace my present `kuma.db` with the rebuilt database?

```
Backing up the database

To make a backup copy of the database, simply do a "dump" and redirect the results to a file.

cd /home/sqlite
sqlite3 sample.db .dump > sample.bak

Restoring the database

Restoring the database from a backup is just as easy as backing up, except we must make sure the destination database is empty first. Alternatively you may want to delete or rename the destination database and let sqlite create a new one for you.

cd /home/sqlite
mv sample.db sample.db.old
sqlite3 sample.db < sample.bak
```

**Comment by pepa65** [comment]
OK, for posterity: I did `sqlite3 /app/data/kuma.db "REINDEX"` and that fixed everything. The integrity check is now OK, and the database size is 172MB.

**Comment by karser** [comment]
What worked for me:

- Go to https://<uptime-kuma>/settings/monitor-history
- Click "Clear all statistics" and wait a while. Wait until kuma.db-wal stops growing.
- Click "Shrink database", the db file kuma.db should be shrinked
- Shrink kuma.db-wal:
```
docker exec -it uptime_uptime_1 bash
sqlite3 /app/data/kuma.db "PRAGMA wal_checkpoint=TRUNCATE"
```

**Comment by fabsau** [comment]
> Shrink kuma.db-wal:

Thank you! Just a little update:
The last step is not needed. Just restart the container and it will do the step automatically.
