### ISSUE TITLE
How to set DNS-server and/or hosts file in docker

### ISSUE THREAD

**Issue by HolgerAusB** [louislam/uptime-kuma#1995]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

I am quite new to docker and kuma. I tried to monitor a local https server by name `https://sub1.example.com:1234` and it lasts me hours until I realized that kuma never got an ip of that server. The Raspi got its addresses from pihole, which would deliver back a local IP for that host name. But as kuma is in a container, there is a different dns server setting in the container which asks a dns server outside the local net. But as my https-server sub1 is not reachable from the internet, the check fails.

So, is it possible somehow to set the dns server setting inside the docker container (or as new feature in kuma)? And/or is there a way to set a hosts file with static name>ip ?

Meanwhile I set the monitor to `https://192.168.1.23:1234` and ckecked 'ignore TLS/SSL-errors'.

This issue might similar to #1302 

### 🐻 Uptime-Kuma Version

1.17.1

### 💻 Operating System and Arch

Raspbian Bullseye

### 🌐 Browser

Firefox latest/stable for Windows 11

### 🐋 Docker Version

20.10.17, build 100c701

**Comment by HolgerAusB** [comment]
I was just on the search for a JSON viewer and tested that with an kuma backup. There allready is a data field for the resolver in each monitor, but how can I edit this in kuma? Or do I need to manipulate that backup ans upload this to kuma? will this be persistant?

```
            "dns_resolve_type": "A",
            "dns_resolve_server": "1.1.1.1",
```

**Comment by nbvcxz** [comment]
As far as I understand, you need:
https://docs.docker.com/config/containers/container-networking/#dns-services or https://docs.docker.com/engine/reference/commandline/run/#add-entries-to-container-hosts-file---add-host
Not Uptime-Kuma specific. You just need to add appropriate parameter to your `docker run` or compose file.

**Comment by HolgerAusB** [comment]
Thank you @nbvcxz that helped. But I think there shouldd be a (per monitor) option to set the resolver in kuma.

I have added a `--dns 192.168.0.1` to the run command. Now the monitor works with domain name. Nevertheless in a new backup the resolver-line is unchanged at 1.1.1.1
```
docker stop uptime-kuma 
docker rm uptime-kuma
docker run -d --restart=always -p 3001:3001 -v uptime-kuma:/app/data --dns 192.168.0.1 --name uptime-kuma louislam/uptime-kuma:1
```

**Comment by lnxbil** [comment]
> The Raspi got its addresses from pihole, which would deliver back a local IP for that host name. But as kuma is in a container, there is a different dns server setting in the container which asks a dns server outside the local net.

Normally the container inherits the dns settings of the client (more precisely the internal docker dns server gets it's resolvers from `/etc/resolv.conf` when it starts), so it should work as it was intended and it also works for me exactly like I described. I just had the same problem and solved it by editing the docker host `/etc/resolv.conf`.
