### ISSUE TITLE
Downtime Length

### ISSUE THREAD

**Issue by ItzYanick** [louislam/uptime-kuma#1996]
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

Other

### 🔖 Feature description

When a service is coming back up you could display for how long it was down. For example Hetrixtools shows that in there notification of the service going back up.

### ✔️ Solution

When the service comes back up calculate the current time minus the time when the service went down and display it in the notification.

### ❓ Alternatives

Could also be shown in the web panel at the message part

**Comment by mabed-fr** [comment]
Hello,

Similar or not ? https://github.com/louislam/uptime-kuma/issues/1970

**Comment by ItzYanick** [comment]
Yes Down duration would be the same. I searched for it but did not find anything like it. Thank you! Will close this then as it is a duplicate bascially :D
