### ISSUE TITLE
API functionality

### ISSUE THREAD

**Issue by TheGuyDanish** [louislam/uptime-kuma#2]
I'd love to see the ability to retrieve, update, remove or add monitors via API calls. Maybe using an API key that's tied to the user. In a way that when spinning up a new docker container or doing an automated workflow like Terraform, the new device could be added to the software automatically.

**Comment by proffalken** [comment]
ooooooh, love this idea, any chance of taking it one step further and adding service discovery for platforms such as Consul.io?
