### ISSUE TITLE
[Request] Consider moving Discord integration from bot to webhook

### ISSUE THREAD

**Issue by TheGuyDanish** [louislam/uptime-kuma#20]
Discord allows for the use of webhooks, which may be more suitable than a bot for an application like this. Using a webhook also means users will not have to generate a bot token and will just have to supply their webook URL into Uptime-Kuma.

More reading:
https://gist.github.com/Birdie0/78ee79402a4301b1faf412ab5f1cdcf9

**Comment by louislam** [comment]
Lol, google search gave me the hard way to send message before I implemented it. Your suggestion is definitely better.

**Comment by TheGuyDanish** [comment]
I can have a look at patching it into a webhook in a bit. Looks like the changes should be fairly simple.

**Comment by TheGuyDanish** [comment]
![image](https://user-images.githubusercontent.com/5776313/125288784-6ea49e80-e316-11eb-81f4-5409bc77fafd.png)

🎉🎉🎉

**Comment by TheGuyDanish** [comment]
Pull for this now in #22.
