### ISSUE TITLE
Is it allowed to remove “status” ?

### ISSUE THREAD

**Issue by wyfang** [louislam/uptime-kuma#2002]
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

Other

### 🔖 Feature description

<img width="489" alt="image" src="https://user-images.githubusercontent.com/17900420/184781452-bf4e6c8e-cda2-40a4-b63f-4011bae54a0c.png">
<img width="193" alt="image" src="https://user-images.githubusercontent.com/17900420/184781502-a5b0648f-27b9-4807-b90c-614d55724669.png">
I want to create a public page, but, I don't understand why I need a /status/ ?

### ✔️ Solution

 I would like it to be accessible by removing, for example, https://test.com/web.

### ❓ Alternatives

Null

### 📝 Additional Context

Null

**Comment by Computroniks** [comment]
This is to do with having multiple status page support. I.e you can have `/status/fizz` and `/status/buzz`. If you name the status page `default` you should be able to access it from just `/status`. If you want to have it be anything else, you could probably use a reverse proxy like NGINX and some special configuration.

**Comment by louislam** [comment]
> In my opinion, if it's default anyway, why shouldn't you be able to simply access it by going to the domain root like before? Surely this isn't hard to implement. It's quite ugly to have status.example.com/status/default instead of just status.example.com.

You can achieve this by setting a dedicated domain name to your status page. Please read:
https://github.com/louislam/uptime-kuma/wiki/Status-Page

**Comment by DatDraggy** [comment]
> > In my opinion, if it's default anyway, why shouldn't you be able to simply access it by going to the domain root like before? Surely this isn't hard to implement. It's quite ugly to have status.example.com/status/default instead of just status.example.com.
> 
> You can achieve this by setting a dedicated domain name to your status page. Please read: https://github.com/louislam/uptime-kuma/wiki/Status-Page

Oh I did not know about that. However, that makes it even worse for some reason. I entered my domain properly into the Domain Names field but now the domain root redirects me to the dashboard, even though the Entry Page setting is set to Status Page. I'm on 1.18.0 and just re-updated as well, no change

Sorry for issue-jacking btw, idk if I should make a new issue about this or if here is fine
