### ISSUE TITLE
[webhook] Option to enter Authentication (Basic Auth)

### ISSUE THREAD

**Issue by redtripleAAA** [louislam/uptime-kuma#2008]
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

API, UI Feature

### 🔖 Feature description

The reason I need basic auth, is to integrate notification via n8n to build a workflow.

### ✔️ Solution

In my case, I can use wide open webooks, and I need to use basic authentication

### ❓ Alternatives
Use public POST webhook with no authentication it works, but not secure.

![Screen Shot 2022-08-21 at 9 29 49 PM](https://user-images.githubusercontent.com/5244872/185821885-5de2fc27-1086-453d-a6f0-771d30976e5e.png)

**Comment by Joseph94m** [comment]
This would be cool if we could also post notifs to slack

**Comment by chakflying** [comment]
This should be closed with #1920.

**Comment by Azathoth88** [comment]
I would also be delighted if this were implemented.
I use an Android SMS gateway and would like to integrate it as a notification service. Unfortunately, I cannot create the notification because a Basic Auth is required.

I use this service:
https://github.com/capcom6/android-sms-gateway

**Comment by CommanderStorm** [comment]
It is implemented and released in `1.19`
Resolved by https://github.com/louislam/uptime-kuma/pull/1920

**Comment by Azathoth88** [comment]
Version: 1.23.13
Frontend-Version: 1.23.13

But not at the location of the notification configuration


![image](https://github.com/user-attachments/assets/488c3c8c-8ef6-4988-afed-5432f69d835c)

**Comment by CommanderStorm** [comment]
Those are really weird headers you have there.. I don't know what non-text headers output.

I think you want "Custom" instead of the body preset; You are currently adding test to the "Zusätzliche Header" field.

**Comment by Azathoth88** [comment]
@CommanderStorm 

The example was not correct. It doesn't matter for now, as I need the basic authentication. Unfortunately, this cannot be deactivated.

Look at a real example with curl:

curl -X POST **-u <username>:<password>** -H "Content-Type: application/json" -d '{ "message": "Hello, world!", "phoneNumbers": ["+79990001234", "+79995556677"] }' https://sms.capcom.me/api/3rdparty/v1/message

**Comment by CommanderStorm** [comment]
Basic auth is just a header you set. You can use https://www.debugbear.com/basic-auth-header-generator to help you with that.

![image](https://github.com/user-attachments/assets/03c18bee-d363-470d-b6d5-4cf6c98f7673)

**Comment by mainLink0435** [comment]
> Basic auth is just a header you set. You can use https://www.debugbear.com/basic-auth-header-generator to help you with that.

In your example, that sends the password. How do you send the username?
