### ISSUE TITLE
DNS alert features unnecessary URL field

### ISSUE THREAD

**Issue by mateuszdrab** [louislam/uptime-kuma#2009]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### Description

The Uptime Kuma notification for a DNS monitor provides an empty URL field - this can be seen in Teams as in the screenshot below:

### 👟 Reproduction steps

- Setup a DNS monitor
- Use a Teams webhook for alerts
- Trigger the alert

### 👀 Expected behavior

The URL field does not need to be displayed.

### 😓 Actual Behavior

![image](https://user-images.githubusercontent.com/26556541/185880409-134d8dc5-53cd-4cea-8d30-be0a19d81bb7.png)

### 🐻 Uptime-Kuma Version

1.17.1

### 💻 Operating System and Arch

Ubuntu 20.04

### 🌐 Browser

Edge 104

**Comment by Computroniks** [comment]
This is because of an issue when checking for the existence of a URL. I will create a PR to fix this
