### ISSUE TITLE
Add optional `Description` field for monitors

### ISSUE THREAD

**Issue by Saibamen** [louislam/uptime-kuma#2010]
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

UI Feature, Other

### 🔖 Feature description

Add optional `Description` field for monitor, visible only for admins (not visible on status page)

### ✔️ Solution

I want to add more info for my monitors, like service name on Azure, admin login account, different (private) IP, restart command/script etc., this info should not be visible on Status Page.
This field should be textarea

**Comment by ThomasChr** [comment]
Looks like there is an Issue for that which also has a Pull Request ready: #482

**Comment by Saibamen** [comment]
Duplicate of https://github.com/louislam/uptime-kuma/issues/482
