### ISSUE TITLE
How to monitor dockers containers

### ISSUE THREAD

**Issue by EpicShiield** [louislam/uptime-kuma#2016]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

Hello, i have a question, how can we monitor dockers containers as it is said in the features ?

![image](https://user-images.githubusercontent.com/38161967/186721717-0978fe59-f0b5-4f92-a68f-8001e5fa0a03.png)

in my uptime-kuma i don't have this option 

![image](https://user-images.githubusercontent.com/38161967/186721873-c3a2d6ef-2a92-46f4-a2f7-c9eb390cb0e5.png)

### 🐻 Uptime-Kuma Version

1.17.1

### 💻 Operating System and Arch

Ubuntu 22.04

### 🌐 Browser

Firefox 103.0.2

### 🐋 Docker Version

Docker version 20.10.17

**Comment by mmuenker** [comment]
you have to use the image with the version tag `1.18.0-beta.0`

```
docker run ... louislam/uptime-kuma:1.18.0-beta.0
```

**Comment by EpicShiield** [comment]
Hello, thanks for the tips :)
