### ISSUE TITLE
uptime kuma html & php

### ISSUE THREAD

**Issue by txtx3087** [louislam/uptime-kuma#2018]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

uptime kuma any none have uptime kuma html & php

### 🐻 Uptime-Kuma Version

1.10.0

### 💻 Operating System and Arch

pc

### 🌐 Browser

opera

**Comment by Computroniks** [comment]
Could you provide some more info about what you need help on?
> uptime kuma any none have uptime kuma html & php

doesn't really make sense

**Comment by txtx3087** [comment]
> Contributor

bro uptime kuma project but not .js I mean do you have a uptime kuma project html or php

**Comment by Computroniks** [comment]
Uptime Kuma is written in JavaScript using NodeJs. To deploy the server follow the installation instructions in the wiki. The easiest way is to use docker but you can also use PM2. If you are looking to upload this to some sort of web hosting that only provides a file upload, this won't work, you require a service that supports nodejs or a VPS.

**Comment by txtx3087** [comment]
> تتم كتابة Uptime Kuma في JavaScript باستخدام NodeJs. لنشر الخادم ، اتبع تعليمات التثبيت في الويكي. أسهل طريقة هي استخدام عامل الإرساء ولكن يمكنك أيضًا استخدام PM2. تحتاج إلى خدمة تدعم nodejs أو VPS.

![image](https://user-images.githubusercontent.com/111004394/187015483-417ce101-2536-466c-8abf-8b1ba9589f89.png)
When I open the index file from the uptime kuma wiki

**Comment by Computroniks** [comment]
Just to check, you are viewing this https://github.com/louislam/uptime-kuma/wiki right?

**Comment by txtx3087** [comment]
> Reference in ne

exactly

**Comment by txtx3087** [comment]
I hope that you will make a web version in html to make it easier for us to upload it to hosting, for example, uploading it to cpanel or other hosting

**Comment by Computroniks** [comment]
> I hope that you will make a web version in html to make it easier for us to upload it to hosting, for example, uploading it to cpanel or other hosting

This is not possible. There has to be the nodejs backend to run the monitors separately from the web app frontend. It simply wouldn't work with hosting services. You need to have a server or VPS with someone like Amazon AWS or Google Cloud.

**Comment by txtx3087** [comment]
> > I hope that you will make a web version in html to make it easier for us to upload it to hosting, for example, uploading it to cpanel or other hosting
> 
> This is not possible. There has to be the nodejs backend to run the monitors separately from the web app frontend. It simply wouldn't work with hosting services. You need to have a server or VPS with someone like Amazon AWS or Google Cloud.

Oh ok and thank you
![Screenshot_20220828_005253_com android chrome](https://user-images.githubusercontent.com/111004394/187049260-05f4a1e1-b875-45aa-b821-a54769cf7844.jpg)

Where can I modify this design here? Which file? I searched and did not find anything
I want to add a background to the site
