### ISSUE TITLE
direct forwarding

### ISSUE THREAD

**Issue by Gamer-Bjoern** [louislam/uptime-kuma#2019]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [x] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

I want it so that when you go to my domain, you go directly to a status page and not to the dashboard. How can I adjust that?

### 🐻 Uptime-Kuma Version

1.17.1

### 💻 Operating System and Arch

Debian 10

### 🌐 Browser

Opera GX

### 🟩 NodeJS Version

v16.17.0

**Comment by louislam** [comment]
This may help.
https://github.com/louislam/uptime-kuma/wiki/Status-Page

**Comment by Gamer-Bjoern** [comment]
it works
