### ISSUE TITLE
User and pass & design

### ISSUE THREAD

**Issue by 51-PxC-51** [louislam/uptime-kuma#2020]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

After registration, where is the name and password saved? 

Why can't I change the name or logo 
![image](https://user-images.githubusercontent.com/108440658/187084799-0a630501-1c3e-4e8a-95b9-9892d7456aa6.png)

Here too, I cannot change the words. I searched for the project and did not find the word ""
![image](https://user-images.githubusercontent.com/108440658/187084840-18ef4ab2-2b3d-4f23-923e-9441b1ef91b9.png)
![image](https://user-images.githubusercontent.com/108440658/187084887-0ae504b0-f73f-45ce-a864-8b5d7fc5bec5.png)
![image](https://user-images.githubusercontent.com/108440658/187084917-5da3ade6-7fdb-410f-a177-10addaefec59.png)
![image](https://user-images.githubusercontent.com/108440658/187084938-96bb4535-063e-4094-8a70-e22027521bd5.png)

Even the color I can not change

### 🐻 Uptime-Kuma Version

1.17.1

### 💻 Operating System and Arch

win

### 🌐 Browser

chrome

### 🐋 Docker Version

no Docker 

### 🟩 NodeJS Version

16

**Comment by louislam** [comment]
> After registration, where is the name and password saved?

SQLite database at ./data/kuma.db

> (0 hits in 0 files of 22 searched)

Uptime Kuma is definitely having more than 22 files, so please double check your software's settings.

**Comment by 51-PxC-51** [comment]
> > After registration, where is the name and password saved?
> 
> SQLite database at ./data/kuma.db
> 
> > (0 hits in 0 files of 22 searched)
> 
> Uptime Kuma is definitely having more than 22 files, so please double check your software's settings.

*SQLite database at ./data/kuma.db : It's encrypted 
![image](https://user-images.githubusercontent.com/108440658/187091175-3bdf8f08-77be-4739-bab1-f9f4ca261b81.png)


*I checked my friend and I didn't find anything indicating that I can change the design

**Comment by 51-PxC-51** [comment]
?

**Comment by ThomasChr** [comment]
The database needs a sqlite client to modify it. Nevertheless the passwords are still encrypted. Like passwords should be. You can't just encrypt them.

The design is in the code, thats normal Javascript Code, nothing too fancy here. So if you don‘t find it you‘re making some mistake.

**Comment by 51-PxC-51** [comment]
@ThomasChr  Thank you for the clarification
I modified the design but not much because I don't know much about JavaScript
