### ISSUE TITLE
remove or rename "Apprise Notifications" on Apprise Notifications

### ISSUE THREAD

**Issue by theoneandonly-vector** [louislam/uptime-kuma#2021]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

I would like to remove the "Apprise Notifications" if not possible rename it to something like "monitor".

### 🐻 Uptime-Kuma Version

1.17.1

### 💻 Operating System and Arch

ubuntu 21.04

### 🌐 Browser

104.0.5112.102

**Comment by satyamsettyeswara** [comment]
Hey, I would like to update this but i couldn't find Apprise Notification anywhere in the project. Could you give me somemore info?

**Comment by theoneandonly-vector** [comment]
Apprise is integrated in uptime-kuma so one can use many external services to send messages. And it always adds "Apprise Notification" followed by the Notification itself. But I have no idea where this resides in the code..

**Comment by satyamsettyeswara** [comment]
So this "Apprise Notification" is generated when we create a notification?
![image](https://user-images.githubusercontent.com/31738585/188302322-379359fa-5bf8-4ad9-8e97-972e46e008e5.png)

**Comment by theoneandonly-vector** [comment]
Yes it will be generated when you setup a "apprise" Notification 
![Screenshot_20220904-093150](https://user-images.githubusercontent.com/10380051/188302665-15735fd6-ded0-4898-a33d-5de2adefdd97.jpg)

**Comment by satyamsettyeswara** [comment]
hi, can you tell me how to create a apprise. I thought of using the IFTTT applet for the email notification but when i use the APIKEY  url in Apprise URL it is give this error
![image](https://user-images.githubusercontent.com/31738585/188308204-7fb78db3-c59c-4683-b251-0ae76c3d9ffd.png)

**Comment by satyamsettyeswara** [comment]
> ### ⚠️ Please verify that this bug has NOT been raised before.
> * [x]  I checked and didn't find similar issue
> 
> ### 🛡️ Security Policy
> * [x]  I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)
> 
> ### 📝 Describe your problem
> I would like to remove the "Apprise Notifications" if not possible rename it to something like "monitor".
> 
> ### 🐻 Uptime-Kuma Version
> 1.17.1
> 
> ### 💻 Operating System and Arch
> ubuntu 21.04
> 
> ### 🌐 Browser
> 104.0.5112.102
> 
> ### 🐋 Docker Version
> _No response_
> 
> ### 🟩 NodeJS Version
> _No response_

**Comment by satyamsettyeswara** [comment]
Hi,
I used the discord with apprise notification feature. I didn't get any "Apprise Notification" when i tested it. I am thinking you might be using the title as "Apprise Notification". Please check once if issue still there send me screenshot of the notification setup that your trying
Notification setup for discord: 
![image](https://user-images.githubusercontent.com/31738585/188494277-8a225991-db6e-4984-8edf-88005c5effe7.png)

Message that is triggered: 
![image](https://user-images.githubusercontent.com/31738585/188494381-7e10af1f-800b-4043-943d-c67fb88af9d0.png)

**Comment by theoneandonly-vector** [comment]
> Hi, I used the discord with apprise notification feature. I didn't get any "Apprise Notification" when i tested it. I am thinking you might be using the title as "Apprise Notification". Please check once if issue still there send me screenshot of the notification setup that your trying Notification setup for discord: ![image](https://user-images.githubusercontent.com/31738585/188494277-8a225991-db6e-4984-8edf-88005c5effe7.png)
> 
> Message that is triggered: ![image](https://user-images.githubusercontent.com/31738585/188494381-7e10af1f-800b-4043-943d-c67fb88af9d0.png)

oh, cool thx :)
I didn't set any title.. so it was automatically using "Apprise Notification".
