### ISSUE TITLE
Uptime Kuma API

### ISSUE THREAD

**Issue by openstep** [louislam/uptime-kuma#2022]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

Would like to know if Uptime Kuma has any APIs to access? I am thinking about automatically setting up monitors inside Kuma to monitor other systems.

Thanks

### 🐻 Uptime-Kuma Version

current

### 💻 Operating System and Arch

Container

### 🌐 Browser

FF

**Comment by Computroniks** [comment]
See #118
