### ISSUE TITLE
modification files design and colors

### ISSUE THREAD

**Issue by 51-PxC-51** [louislam/uptime-kuma#2024]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

**If you can put paths only for the modification files design and colors**
**How do I put an image in the background I need help I'm not good in JavaScript I hope for help**
I need to put a picture in the background like the one in the picture

![image](https://user-images.githubusercontent.com/108440658/187321176-dacb9acf-6c88-454a-a334-f75a80349822.png)
![image](https://user-images.githubusercontent.com/108440658/187321222-9f80f516-f5f0-42e5-ab82-5cc6d77bc7a5.png)

### 🐻 Uptime-Kuma Version

1.17.1

### 💻 Operating System and Arch

win

### 🌐 Browser

chrome

### 🐋 Docker Version

no Docker 

### 🟩 NodeJS Version

16

**Comment by louislam** [comment]
As the frontend is compiled, it is not easy to change. 

I think you can inject your css code at `./dist/index.html` with !important to override the default css.

Example:
```css
<style>
    body {
        background-color: red !important;
    }
</style>
```

Remember to restart the server after changed.

**Comment by 51-PxC-51** [comment]
@louislam 
**_### The code is good, it works, thank you, but take a look at the pictures_**

Where can I find the path of the site name and icon?
I changed the icons in all of the paths `./dist` & `./public` and they did not change
![Screenshot 2022-08-30 035550](https://user-images.githubusercontent.com/108440658/187419527-d604df4f-fe4d-4b4d-9ff0-30e7357169e5.png)

Which file is the website page in which I can modify it?

**Comment by 51-PxC-51** [comment]
@louislam  ؟ bro

**Comment by XHyperDEVX** [comment]
> @louislam **_### The code is good for Theme `Light ` but for `Dark `no is not work, thank you, but take a look at the pictures_**
> 
> Where can I find the path of the site name and icon? I changed the icons in all of the paths `./dist` & `./public` and they did not change ![Screenshot 2022-08-30 035550](https://user-images.githubusercontent.com/108440658/187419527-d604df4f-fe4d-4b4d-9ff0-30e7357169e5.png)
> 
> Which file is the website page in which I can modify it?

Is also very interesting for me.
I would like to change the favicon + the website title

**Comment by 51-PxC-51** [comment]
> 
@XHyperDEVX 
I changed it

**Comment by XHyperDEVX** [comment]
> > 
> 
> @XHyperDEVX I changed it

How?

**Comment by 51-PxC-51** [comment]
> > > 
> > 
> > 
> > @XHyperDEVX I changed it
> 
> How?

discord : *KING*#3268

**Comment by 51-PxC-51** [comment]
@XHyperDEVX 
if you want join [https://discord.gg/Jx78V92h](url)
