### ISSUE TITLE
Generate Report to pdf or csv

### ISSUE THREAD

**Issue by albaboryza18** [louislam/uptime-kuma#2028]
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

UI Feature

### 🔖 Feature description

a tools from ui that can generate report uptime to pdf or csv

### ✔️ Solution

to make easy when we need report

**Comment by satyamsettyeswara** [comment]
Hey! I want to do this. Before that I would like to know how to update the docker image with our changes in local. Could you help me how to do that?

**Comment by CommanderStorm** [comment]
I think this is a duplicate of #366
If you agree, could you please close this Issue, as duplicates only create immortal zombies and are really hard to issue-manage?
If not, what makes this issue unique enough to require an additional issue? (Could this be integrated into the issue linked above?) ^^
