### ISSUE TITLE
WebSockets is work erorr Reverse Proxy 

### ISSUE THREAD

**Issue by 51-PxC-51** [louislam/uptime-kuma#2029]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

WebSockets is work but ? Cannot connect to the socket server. [Error: websocket error] Reconnecting...
Using a Reverse Proxy?

![image](https://user-images.githubusercontent.com/108440658/187801877-11a6c001-299c-41f1-93ad-ea7df774fa1a.png)

![image](https://user-images.githubusercontent.com/108440658/187801922-1816977c-afea-4a89-ae02-90c778519a19.png)

![f](https://user-images.githubusercontent.com/108440658/187802866-f27a90da-5bee-4f34-b587-7ad13effd7be.PNG)

### 🐻 Uptime-Kuma Version

1.17.1

### 💻 Operating System and Arch

win

### 🌐 Browser

chrome

### 🐋 Docker Version

no Docker 

### 🟩 NodeJS Version

16

**Comment by SelfhostedPro** [comment]
If you're getting this error then your reverse proxy isn't setup to be able to use websockets. Documentation is available here to find configurations available for your reverse proxy: https://github.com/louislam/uptime-kuma/wiki/Reverse-Proxy
