### ISSUE TITLE
Delete Function-Button in Details is not aligned properly on some smaller screens

### ISSUE THREAD

**Issue by Ponkhy** [louislam/uptime-kuma#203]
In P-01 you see the issue. I figured out two fixes and wanted to ask which version you guys like better?

**To Reproduce**
That happens at a screen-width of 390px. 

**P-01:**
![P-01](https://i.imgur.com/mhtY2td.png)

The two versions:

**P-02:**
![P-02](https://i.imgur.com/Lqs40l9.png)

**P-03:**
![P-03](https://i.imgur.com/ulVeXVN.png)

**Comment by NickBootOne** [comment]
P-03 looks nice 👌
But one thing.... please align the edit button with the "UP" Status, I think that will look even better 😉

**Comment by Ponkhy** [comment]
> P-03 looks nice 👌
> But one thing.... please align the edit button with the "UP" Status, I think that will look even better 😉

Alright, i'll work on that later, thanks for the input!

**Comment by louislam** [comment]
P-03 is good.

And keep in mind that the mobile theme is not optimized yet, a lot of elements look like bad on mobile.

**Comment by Ponkhy** [comment]
> P-03 is good.
> 
> And keep in mind that the mobile theme is not optimized yet, a lot of elements look like bad on mobile.

Yea, that's why i'm trying to optimized at least a few obvious bits of it.
