### ISSUE TITLE
Regex in keyword field

### ISSUE THREAD

**Issue by BoyanBlagoev** [louislam/uptime-kuma#2030]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

I am using Uptime Kuma to check certain endpoints which consist of several strings of System: UP - if everything is fine and System:DOWN if system goes DOWN. Issue is that when I use the HTTP Keyword type monitoring and set the Keyword to UP - Uptime Kuma checks only the first occurrence of UP and never goes on into the string even though there might be a DOWN further down the json.

Can I use a REGEX into the Keyword field? Can you give me example how I can check for every occurrence of a certain word and not to stop on the first check?

Or another question - should I use it with Upside down mode and look for DOWN?

### 🐻 Uptime-Kuma Version

1.17.1

### 💻 Operating System and Arch

GCP App Engine

### 🌐 Browser

Google Chrome

### 🟩 NodeJS Version

16.14.2

**Comment by JulianGro** [comment]
Still an issue.
Any time you have multiple statuses from one source, Uptime Kuma cannot handle it.

**Comment by JulianGro** [comment]
😡

**Comment by woj-tek** [comment]
That would be very helpful to verify that the response is actually correct.

**Comment by CommanderStorm** [comment]
I think this is a duplicate of #2735
If you agree, could you please close this Issue, as duplicates only create immortal zombies and are really hard to issue-manage?
If not, what makes this issue unique enough to require an additional issue? (Could this be integrated into the issue linked above?) ^^

**Comment by JulianGro** [comment]
I agree that #2735 is a duplicate of this.

**Comment by JulianGro** [comment]
https://blog.benwinding.com/github-stale-bots/

**Comment by CommanderStorm** [comment]
@JulianGro We resolve `help` issues after 3 month
They are also not being locked as in the article you posted

As mentioned above (which you agreed with) this issue is a duplicate of https://github.com/louislam/uptime-kuma/issues/2735
=> keeping it open does not serve a purpose

**Comment by CommanderStorm** [comment]
As reasoned above, we are going to track this in https://github.com/louislam/uptime-kuma/issues/2735
=> closing as duplicate (despite this being the earlier issue ^^)
