### ISSUE TITLE
Scheduled Maintenance

### ISSUE THREAD

**Issue by Kazer67** [louislam/uptime-kuma#204]
**Is your feature request related to a problem? Please describe.**
For some services there's recurrent Scheduled Maintenance window (for example at 3am, services going down for 15 min for backup purpose).

**Describe the solution you'd like**
Ability to create Scheduled Maintenance (for example every day/day-of-the-week/month/years between 3h00 and 3h15) that I can affect to the monitor. When the monitor hit that time, it goes in "maintenance mode" which does or doesn't affect the overall uptime (depending if the "Affect Uptime" box is ticked) and it's logged as maintenance (and after 3h15 it goes back to normal monitoring).

**Comment by NickBootOne** [comment]
Duplicated enhancement #191
