### ISSUE TITLE
Uptime Kuma on Synology NAS

### ISSUE THREAD

**Issue by orthl** [louislam/uptime-kuma#2041]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

Hello,
I have installed UptimeKuma with Docker on my Synology NAS. Every Service I try to ping get an error: "connect ETIMEDOUT IP-ADRESS:443". I look like there isn't the possibility to connect to the internet, do you know which ports I have to open in my Firewall? The Monitor-Type is HTTP(S).

Thanks for you help.
Lucas

### 🐻 Uptime-Kuma Version

1.18.0

### 💻 Operating System and Arch

Synology DSM 7.0.1

### 🌐 Browser

Firefox

### 🐋 Docker Version

20.10.3

**Comment by rezzorix** [comment]
You have outgoing ports closed in your firewall?

**Comment by orthl** [comment]
> 

Hello, thanks for your reply. No, I allow every outgoing connection.

**Comment by rezzorix** [comment]
You used command line or the docker in web interface to start the container?

I did run an earlier version of uptime-kuma directly through web-gui which worked fine. 

Will try current version on the weekend and see what happens.

**Comment by rezzorix** [comment]
Tried this over the weekend; uptime-kuma runs perfectly on my DS920+...

Again if you still require help you need to give some more information on how you started it etc.
