### ISSUE TITLE
Bark is broken in 1.18.0

### ISSUE THREAD

**Issue by zuosc** [louislam/uptime-kuma#2052]
fix

**Comment by zuosc** [comment]
@Lakr233   help

**Comment by zuosc** [comment]
@SuperManito   出来挨打。 你这写的啥啊，自己都不测试的么？？

```
appendAdditionalParameters(notification, postUrl)
```

notification 哪去了？

**Comment by zuosc** [comment]
@SuperManito   你这不是挨打了。你这是个人素质问题了。 代码完全不测试，就直接提交。

https://github.com/louislam/uptime-kuma/commit/54b9698a05e21649ec78f64ec5187b41d885f9d9

这里用的是``?``  而不是 ``&``  

你这是完全没测试。  这个没法说了

**Comment by SuperManito** [comment]
## Your quality needs to be improved
## 您的素质有待高

**Comment by zuosc** [comment]
> ## Your quality needs to be improved
> ## 您的素质有待高

你自己说 ，你写的这是什么？你测试了么？

**Comment by zuosc** [comment]
@louislam  看坐标，您应该是香港人。 看得懂中文。

麻烦您审核一下 @SuperManito 的代码，已经标记出来。 相信每一个程序员都能看出来，他并没有任何测试。

**Comment by SuperManito** [comment]
> > ## Your quality needs to be improved
> > ## 您的素质有待高
> 
> 你自己说 ，你写的这是什么？你测试了么？

如果你认为别人代码有问题，你可以去提交pr并指出错误，你这种人真的很没有素质，还喜欢乱扣帽子

**Comment by Lakr233** [comment]
我没看懂这个 commit 在干嘛.............

不过如果说是 query parameter 的问题我检查了一下我写的那份貌似是好的

<img width="558" alt="截屏2022-09-14 16 36 04" src="https://user-images.githubusercontent.com/25259084/190104467-3d0c22fd-cd3e-4583-8fe0-3f56fceab11a.png">

**Comment by SuperManito** [comment]
> 我没看懂这个 commit 在干嘛.............
> 
> 不过如果说是 query parameter 的问题我检查了一下我写的那份貌似是好的
> 
> <img alt="截屏2022-09-14 16 36 04" width="558" src="https://user-images.githubusercontent.com/25259084/190104467-3d0c22fd-cd3e-4583-8fe0-3f56fceab11a.png">

加了两个参数，我没有测试，确实是我造成的问题

**Comment by Lakr233** [comment]
> > 我没看懂这个 commit 在干嘛.............
> > 不过如果说是 query parameter 的问题我检查了一下我写的那份貌似是好的
> > <img alt="截屏2022-09-14 16 36 04" width="558" src="https://user-images.githubusercontent.com/25259084/190104467-3d0c22fd-cd3e-4583-8fe0-3f56fceab11a.png">
> 
> 加了两个参数，我没有测试，确实是我造成的问题

重构一下吧 上个字典然后发的时候走一下序列化
当时我偷了个懒没想到过了几年爆炸了。。。

**Comment by zuosc** [comment]
> > > ## Your quality needs to be improved
> > > ## 您的素质有待高
> > 
> > 
> > 你自己说 ，你写的这是什么？你测试了么？
> 
> 如果你认为别人代码有问题，你可以去提交pr并指出错误，你这种人真的很没有素质，还喜欢乱扣帽子

充分说明，你没有测试。  如果是其他问题，我绝对不喷你。  


这种错误太低级了。只要测试了，就肯定能发现。

**Comment by SuperManito** [comment]
## Your quality needs to be improved

## 您的素质有待高

**Comment by Lakr233** [comment]
别吵了别吵了 赶快修掉 拉一个加急的 PR

**Comment by louislam** [comment]
請大家和平討論🙏

這個我也疏忽了，還以為只是加了幾個 Query String 應該沒問題，沒有做好測試。

**Comment by zuosc** [comment]
@Lakr233  https://github.com/zuosc/uptime-kuma/commit/ed2a14320ad435ec53b971f58909f210d8043cac

已经简单修复了。

**Comment by SuperManito** [comment]
> 請大家和平討論🙏
> 
> 這個我也疏忽了，還以為只是加了幾個 Query String 應該沒問題，沒有做好測試。

抱歉，给您填麻烦了~

**Comment by zuosc** [comment]
> @Lakr233 [zuosc@ed2a143](https://github.com/zuosc/uptime-kuma/commit/ed2a14320ad435ec53b971f58909f210d8043cac)
> 
> 已经简单修复了。 并没有去重构。 对前端不熟悉，只能这样了。大佬有空的话，可以再看看

**Comment by zuosc** [comment]
然后appendAdditionalParameters方法里，postUrl 没有encodeURIComponent

测试下来也是可以的，就是有点不统一。

不太确定如何改合适。 大佬们看看咋改吧。 @louislam @Lakr233

**Comment by SuperManito** [comment]
> > > 我没看懂这个 commit 在干嘛.............
> > > 不过如果说是 query parameter 的问题我检查了一下我写的那份貌似是好的
> > > <img alt="截屏2022-09-14 16 36 04" width="558" src="https://user-images.githubusercontent.com/25259084/190104467-3d0c22fd-cd3e-4583-8fe0-3f56fceab11a.png">
> > 
> > 
> > 加了两个参数，我没有测试，确实是我造成的问题
> 
> 重构一下吧 上个字典然后发的时候走一下序列化 当时我偷了个懒没想到过了几年爆炸了。。。

不用重构，就是加了两个URL参数和对应的vue表单，我太大意了，第一次参与大型的正式项目，以后会注意代码的测试
