### ISSUE TITLE
NGINX Proxy Manager / Monitoring

### ISSUE THREAD

**Issue by gmead09** [louislam/uptime-kuma#2057]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

Using both NGINX Proxy Mgr and Uptime Kuma in docker containers on my Synology. Items that go through NGINX return an error. 

Example if I am monitoring dns1.domain.com I get connect EHOSTUNREACH 172.16.1.99:443.

That IP is the IP of my NGINX Proxy Manager. Can anyone help????

### 🐻 Uptime-Kuma Version

1.18

### 💻 Operating System and Arch

Synology Docker

### 🌐 Browser

Safari

### 🐋 Docker Version

0

### 🟩 NodeJS Version

0

**Comment by rezzorix** [comment]
Without more detailed infos, 2 thoughts came to my mind:

1. It might be a problem around the keyword "Hairpin NAT".

2. I personally find running docker directly on Synology a nightmare.
WebGUI is complicated and somehow limited, via shell you still have limitations (permissions, lack of packages etc.)

My solution is running a VM with Debian 11 on the NAS. 
I get the reliability of a NAS, and at the same time don't have to battle weird issues/limitations of the Synology system.
