### ISSUE TITLE
Cannot connect to the socket server

### ISSUE THREAD

**Issue by Rahulsharma0810** [louislam/uptime-kuma#2059]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

<img width="638" alt="image" src="https://user-images.githubusercontent.com/9934859/189329394-512f1703-7d6e-49d7-bb0a-71dac066ed4b.png">

```
Cannot connect to the socket server. [Error: WebSocket error] Reconnecting...
Using a Reverse Proxy? [Check how to config it for WebSocket](https://github.com/louislam/uptime-kuma/wiki/Reverse-Proxy)
```

using Nginx-ingress with the below parameters

```
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
    nginx.ingress.kubernetes.io/server-snippets: |
      location / {
        proxy_set_header Upgrade $http_upgrade;
        proxy_http_version 1.1;
        proxy_set_header X-Forwarded-Host $http_host;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Forwarded-For $remote_addr;
        proxy_set_header Host $host;
        proxy_set_header Connection "upgrade";
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header   Upgrade $http_upgrade;
        proxy_cache_bypass $http_upgrade;
        }
```

### 🐻 Uptime-Kuma Version

1.8.0

### 💻 Operating System and Arch

Kubernetes On ubuntu

### 🌐 Browser

Google Chrome 105.0.5195.102

**Comment by Rahulsharma0810** [comment]
adding annotation, made it work.
```
    nginx.org/websocket-services: uptime-kuma-service

```

**Comment by Spritekin** [comment]
Just a note for anyone interested as I had a similar problem:
If you are running in AWS, make sure you are using an Application or Network load balancers. Classic Load Balancer doesn't allow websockets.

**Comment by IIIdefconIII** [comment]
i have the same error once in a while and after a few seconds its starting do

**Comment by jkrause-Gold** [comment]
> adding annotation, made it work.
> 
> ```
>     nginx.org/websocket-services: uptime-kuma-service
> ```

where do you make this notation? - Sorry im a noob.

**Comment by Slade3636** [comment]
> > adding annotation, made it work.
> > ```
> >     nginx.org/websocket-services: uptime-kuma-service
> > ```
> 
> where do you make this notation? - Sorry im a noob.


ngress:
  #enabled: false
  enabled: true
  className: nginx
  extraLabels: {}
    # vhost: uptime-kuma.company.corp
  annotations:
    nginx.org/websocket-services: uptimemonitorig-uptime-kuma
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
    nginx.ingress.kubernetes.io/server-snippets: |
      location / {
        proxy_set_header Upgrade $http_upgrade;
        proxy_http_version 1.1;
        proxy_set_header X-Forwarded-Host $http_host;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Forwarded-For $remote_addr;
        proxy_set_header Host $host;
        proxy_set_header Connection upgrade;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header   Upgrade $http_upgrade;
        proxy_cache_bypass $http_upgrade;
      }
