### ISSUE TITLE
Optimize list of monitors on smaller screens

### ISSUE THREAD

**Issue by Ponkhy** [louislam/uptime-kuma#206]
**Is your feature request related to a problem? Please describe.**
I've noticed that the HeartbeatBar takes away a lot space on screens especially smaller than 400px.

**Describe the solution you'd like**
Solutions:
- 1: Just hide the HeartbeatBar at a certain point, then you can read the name without problem.
- 2: Put the HeartbeatBar under the Uptime and Name.

I don't think it'll make much sense to make the HeartbeatBar smaller.
What do you guys think about it?
I know this project isn't 100% mobile optimized, but i'd like to improve the experience on mobile devices over time.

**Problem:**
![Problem](https://i.imgur.com/114MQz2.png)

**Comment by Ponkhy** [comment]
Okay, i've roughly worked out both solutions.
Which version do you guys like better? Especially @louislam since it's your project.

**Solution 1:**
![Solution1](https://i.imgur.com/i1ohCAG.png)

**Solution 2:**
![Solution2](https://i.imgur.com/JIbXSHY.png)

**Comment by louislam** [comment]
> **Is your feature request related to a problem? Please describe.**
> I've noticed that the HeartbeatBar takes away a lot space on screens especially smaller than 400px.
> 
> **Describe the solution you'd like**
> Solutions:
> 
> * 1: Just hide the HeartbeatBar at a certain point, then you can read the name without problem.
> * 2: Put the HeartbeatBar under the Uptime and Name.
> 
> I don't think it'll make much sense to make the HeartbeatBar smaller.
> What do you guys think about it?
> I know this project isn't 100% mobile optimized, but i'd like to improve the experience on mobile devices over time.
> 
> **Problem:**
> ![Problem](https://camo.githubusercontent.com/ea84a926c261f7449262884296e044a1b86ba9ef1a7873fdfe0d124b5a66a225/68747470733a2f2f692e696d6775722e636f6d2f3131344d517a322e706e67)

I think the solution 2 should be better.

**Comment by Ponkhy** [comment]
I'm actually also working on a solution to just have the option in settings, so the user can choose the style they want.
