### ISSUE TITLE
save the json file to an external strorage

### ISSUE THREAD

**Issue by HujinoKun** [louislam/uptime-kuma#2063]
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

UI Feature

### 🔖 Feature description

Hello,

it would be great if we could schedule backups of the json file to an external storage (s3 cloud provider, minio, nfs...)

### ✔️ Solution

Configure data sending via the administration interface or CLI to implement api keys

**Comment by chakflying** [comment]
Obsolete as the backup feature has been dropped in https://github.com/louislam/uptime-kuma/pull/3892.
