### ISSUE TITLE
Error: "Lost connection to the socket server" | It happens on adding a large json file!

### ISSUE THREAD

**Issue by perpi** [louislam/uptime-kuma#2067]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 👟 Reproduction steps

Try to add more than 500 items by one json file.

### 👀 Expected behavior

Adding json files with any size.

### 😓 Actual Behavior

By importing more than 400 addresses (>50,000 lines in JSON file), Kuma couldn't add them showing this error: 

![image](https://user-images.githubusercontent.com/7093244/189482516-927df378-4472-4312-8bf6-283e915fccd4.png)

### 🐻 Uptime-Kuma Version

1.18.0

### 💻 Operating System and Arch

Ubuntu 22.04 64bit

### 🌐 Browser

Chrome, Edge, Firefox

### 🐋 Docker Version

Docker version 20.10.12, build 20.10.12-0ubuntu4

### 🟩 NodeJS Version

v16.16.0

**Comment by wojcikm** [comment]
@louislam any ETA on this?

**Comment by arioch** [comment]
First time user, already ran into this error with a mere 10 items.

**Comment by jstewart1982** [comment]
We are encountering this issue now, we have just over 1000 sensors and the console seems to be rendered inoperable

**Comment by jkrause-Gold** [comment]
Same issue here. Dashboard just keeps cycling through all the endpoints then errors out. "Lost connection to Server Socket Reconnecting......"

Dashboard is almost useless at this point

**Comment by JohnnyChiang** [comment]
Had the same issue here

**Comment by PatyYe** [comment]
We have 3 instances, 2 of them both with ~300 monitors. These respond without issue but tend to be a bit slow starting up. Our third instance is at 1100 monitors, and we broke down around 800, it keeps loadin and loading.
I cannot use the dashbaord anymore. 

If wanted I can provide additional information if it's required to help find the issue.

**Comment by nocerainfosec** [comment]
I am able to add 600 hosts per json file, I have added 1200 hosts to monitor, although, server becomes unresponsive after every 2 minutes losing connection with these 1200 hosts.

**Comment by CommanderStorm** [comment]
v2 does include a lot of perfomance updates and should allow scaling past ~200-500 monitors.
See https://github.com/louislam/uptime-kuma/milestone/24 for further progress

**Comment by xyhcode** [comment]
I didn't add any monitors, but the actions panel is always like this, refreshes every few seconds, so why
<img width="454" alt="iShot_2023-12-09_10 55 05" src="https://github.com/louislam/uptime-kuma/assets/64968400/ac421401-7e4e-4701-b102-9bbd6886121a">

**Comment by chakflying** [comment]
Obsolete as the backup feature has been dropped in https://github.com/louislam/uptime-kuma/pull/3892.

**Comment by hrshv6** [comment]
In our case, the cause of this error was haproxy. To solve this problem, we needed to add the following two settings to our haproxy.cfg file:

![2024-04-02_192016](https://github.com/louislam/uptime-kuma/assets/5875821/77462dc8-db4a-49b0-9b68-40f2f4ed79a2)

Just wanted to comment in here for other people looking for a solution.
