### ISSUE TITLE
Help with DNS resolution - docker container

### ISSUE THREAD

**Issue by Lammiwinks** [louislam/uptime-kuma#2075]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

Hi Team,

Loving Uptime Kuma! Quick one - I can’t get DNS checks working on my container with it’s own networking. I use a Pihole for DNS with Unbound (neither works directly). 
As such im trying to use 127.0.0.1:53 to resolve www.google.com with no luck UNLESS I put my container into host networking mode. 

I’m sure this isn’t an UK issue but more likely docker - does anyone know how to achieve this but still keep the network segregated? 

I’d prefer to keep the network isolated as I eventually plan to allow UK on the internet via Cloudflare.

Thanks! 

### 🐻 Uptime-Kuma Version

1.18.9

### 💻 Operating System and Arch

Raspian OS

### 🌐 Browser

Safari

**Comment by Lammiwinks** [comment]
One solution I've kind of found is to run my DNS queries against the docker daemon's virtual DNS server (127.0.0.11:53).  I believe this passes onto my local DNS.

**Comment by rezzorix** [comment]
Just double checking so we can rule this out:

unbound port is 5335 by default, not 5053 except you changed that.
