### ISSUE TITLE
Put link to monitor instance in alert emails

### ISSUE THREAD

**Issue by binarydad** [louislam/uptime-kuma#208]
When an alert email is sent with the status of the monitor, please include the link to the monitor in the email. It would be helpful to quickly click and see the detail of the monitor as well as if any other monitors are down. This is merely for convenience.

**Comment by LiamKenyon** [comment]
An update to emails notifications would be nice.

Seems Discord notifications include all the required data so anything along those lines.

**Comment by binarydad** [comment]
In addition to this, it would be nice to have a link to the website URL as well so I can click it and view the exact error. 

So, a link to my UK instance as well as a link to the monitor's URL (if it's a HTTP monitor).

**Comment by tgxn** [comment]
I like this idea, I don't think there's any config for `EXTERNAL_APP_URL` anywhere, maybe we would need to add a config option for it?

**Comment by eric-j-ason** [comment]
Can this be reopened? I think it is still relevant, with no other open issues quite taking its place. The closest ones are about including the link in alerts through Mattermost (#2650) and Slack (#3541).

**Comment by CommanderStorm** [comment]
No, this won't be reopened (as it is resolved).
v2.0 does include https://github.com/louislam/uptime-kuma/pull/3414 which allows you to use templating on body+headers.
For further information about that release, see #4500.
