### ISSUE TITLE
Please support 'error service list' search and special label

### ISSUE THREAD

**Issue by zszen** [louislam/uptime-kuma#2088]
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

UI Feature

### 🔖 Feature description

I need a group with all error list function. I can't get error service clearly after add many monitors links.
I hope add ‘label’ or ‘specel status like down error that’ to status page

### ✔️ Solution

don't have solution now

**Comment by CommanderStorm** [comment]
> I need a group with all error list function. I can't get error service clearly after add many monitors links

I am inferring, that you want to filter the dashboard via the up/down status.
This is currently implemented:
![image](https://github.com/louislam/uptime-kuma/assets/26258709/7cc6e3af-eae9-40f2-81dd-2a785a2cc50a)

If you would like to sort the dashboard/status page or filter on the status page, this is tracked in these issues instead.
- https://github.com/louislam/uptime-kuma/issues/3743
- https://github.com/louislam/uptime-kuma/issues/1936

I am going to close this issue as a duplicate. If I missunderstood this issue, we can reopen.
