### ISSUE TITLE
How can I view the data of the last 1 year?

### ISSUE THREAD

**Issue by erencylk** [louislam/uptime-kuma#2090]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

How can I view the data of the last 1 year?  I can only see 1 week now.

### 🐻 Uptime-Kuma Version

1.18.0

### 💻 Operating System and Arch

Ubuntu 20.04

### 🌐 Browser

Chrome

**Comment by rezzorix** [comment]
Directly within uptime-kuma you can indeed only see the past week.

You may check the wiki on how to pass metrics to other platforms;
https://github.com/louislam/uptime-kuma/wiki/Prometheus-Integration

Also search for `Grafana`or `Prometheus` in issues can be helpful.

**Comment by erencylk** [comment]
Thanks you. Grafana and Prometheus is perfect on solution
