### ISSUE TITLE
Domain mapping of status page not working

### ISSUE THREAD

**Issue by timscha** [louislam/uptime-kuma#2091]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

I tried to add a subdomain to an existing status page.
Steps I did:

1. Created a status page and added the domain "status.domain2.com" on it
1. Set up a CNAME (tried it with an A record too) which points to my installation
2. Configured my nginx accordingly:

```
server {
  listen 443 ssl http2;
  server_name status.domain1.de status.domain2.com;
  ssl_certificate     /etc/letsencrypt/status.domain.de/fullchain.pem;
  ssl_certificate_key /root/.acme.sh/status.domain.de/status.hivehost.de.key;

  location / {
    proxy_set_header   X-Real-IP $remote_addr;
    proxy_set_header   X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_pass         http://localhost:3001/;
    proxy_http_version 1.1;
    proxy_set_header   Upgrade $http_upgrade;
    proxy_set_header   Connection "upgrade";
  }
}
```

3. When now opening status.domain2.com it will forward to the Dashboard, instead of the own status page.

HTTP Headers in the Settings section is set to yes, trust proxy.

Any idea if I missed something?

### 🐻 Uptime-Kuma Version

1.18

### 💻 Operating System and Arch

Debian 11

### 🌐 Browser

Chrome

### 🟩 NodeJS Version

14.20

**Comment by louislam** [comment]
Missing `X-Forward-Host` or `Host`, please read https://github.com/louislam/uptime-kuma/issues/1861

**Comment by timscha** [comment]
Oh dear. Sorry @louislam  - I missed that. Thanks, now it works well.
