### ISSUE TITLE
localhost should not be converted to 127.0.0.1 by uptimeKuma. They are !=

### ISSUE THREAD

**Issue by KleinByte** [louislam/uptime-kuma#2098]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### Description

I'm currently trying to get uptimeKuma to work with a legacy ASP.Net program. Our website is actually behind a OKTA login page, which redirects to our site after.

I don't quite know what needs to be passed in headers to authorize the http request and have okta redirect to our website. My goal was to just test and tweak request headers until I get the desired outcome. Which is where my problem came, I cant test anything locally due to our dev environment website url being "localhost:PORT"

UptimeKuma is converting 'localhost' to 127.0.0.1 , which 127.0.0.1 DOES NOT == 'localhost' .
 localhost can be a pseudonym for 127.0.0.1 ,  but localhost still has to be resolved, meaning localhost can be anything you set your IIS to. 

This is a severe misunderstanding of local networking and a fundamental flaw.

### 👟 Reproduction steps

Add a monitor to an IIS asp.net legacy website that is attached to localhost:PORT.

On uptimekuma - set url to https://localhost:PORT 
 -> uptimekuma will show that it sends a request to https://127.0.0.1:PORT

### 👀 Expected behavior

on uptimeKuma - set URL to https://localhost:PORT
--> uptimeKuma sends a request to https://localhost:PORT

### 😓 Actual Behavior

On uptimekuma - set url to https://localhost:PORT 
 -> uptimekuma will show that it sends a request to https://127.0.0.1:PORT

### 🐻 Uptime-Kuma Version

1.18.0

### 💻 Operating System and Arch

windows

### 🌐 Browser

all

### 🐋 Docker Version

latest

### 🟩 NodeJS Version

all

**Comment by louislam** [comment]
I guess the error message returned from Axios was confused you.
It does resolve the domain and put it in the header (HOST).

Simple test with PHP:

```php
<?php

if ($_SERVER['HTTP_HOST'] === "localhost") {
	print_r($_SERVER);
	http_response_code(200);
} else {
	print_r($_SERVER);
	http_response_code(404);
}

```

Start the php server:
`php -S 0.0.0.0:80`


Uptime Kuma testing monitors:
- http://localhost => 200
- http://127.0.0.1 => 404
- Stop the php server and watch http://localhost => Error (ECONNREFUSED 127.0.0.1:80)

**Comment by KleinByte** [comment]
Thanks for the swift resolution on a non-issue.
My apology for wasting your time with this one.

On that note, I'm assuming that because I'm launching my site in visual studio, its outside of the scope of uptime-kuma in docker.
Any advice you could quickly give to assist me? If not all good, just close this issue.


Again, thanks for you time and development for this great OSS product.

**Comment by louislam** [comment]
Run your Uptime Kuma in `host mode` or `bridge mode` in order to access your host.
