### ISSUE TITLE
Black Event theme display abnormal in Light background

### ISSUE THREAD

**Issue by Marionic0723** [louislam/uptime-kuma#2101]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### Description

Font color is same as background in Dark event theme.

### 👟 Reproduction steps

1.Switch dashboard to light theme
2.create an event,and select theme to dark
3.
![image](https://user-images.githubusercontent.com/76898556/190841947-7048f363-09f2-4383-be29-47a0fa36bf69.png)

### 👀 Expected behavior

![image](https://user-images.githubusercontent.com/76898556/190842059-916f5b3f-41ad-4294-9d57-993d5cfc092c.png)

### 😓 Actual Behavior

![image](https://user-images.githubusercontent.com/76898556/190842084-b83e3203-ed43-4f83-9a08-ac64f9026503.png)

### 🐻 Uptime-Kuma Version

1.18.0

### 💻 Operating System and Arch

Debian 11

### 🌐 Browser

Google Chrome 105.0.5195.79,

**Comment by rezzorix** [comment]
Hi, I have tried to reproduce the error with:

- Chrome 105.0.5195.125
- Edge 105.0.1343.50
- Firefox 105.0.1

All Windows 64bit versions; English (US) language set instead of Chinese.
With the above I could not reproduce and all was displayed correctly.

Question: Debian 11 is the system you run uptime-kuma on, or the system where you run the browser?

**Comment by louislam** [comment]
Thank you for your report. It can be reproduced in my side.

I was fixed it, but I have committed to a wrong branch. It should be release in the next version anyway.

https://github.com/louislam/uptime-kuma/blob/f11dfc8f437cb8e2ee9c77c9450bffc4d5e121af/src/assets/app.scss#L30-L32
