### ISSUE TITLE
WHATSAPP NOTIFICATION

### ISSUE THREAD

**Issue by justinthoms** [louislam/uptime-kuma#2102]
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

New Notification

### 🔖 Feature description

impilmeting whtasapp api help of https://github.com/ookamiiixd/baileys-api

### ✔️ Solution

it working iam now using it zabbix

**Comment by rezzorix** [comment]
See here https://github.com/louislam/uptime-kuma/issues/787 and here https://github.com/louislam/uptime-kuma/issues/1816

What baileys-api does is more or less simulating a browser without having to use a browser.
You still would need to login / authenticate via QR code and also is time-limited... etc.

Not sure if a workaround to use an api that usually costs money is something that should be implemented here.

**Comment by justinthoms** [comment]
It use full for what's app users Bailey's-api free of cost

**Comment by PichlAlex** [comment]
API is free for first 1000 messages per month (this should be enough for most users)
if this limit is exceeded the messages are not delivered anymore and after adding a payment method, you can send more tan 1000 messages/month
