### ISSUE TITLE
Some moniors load without a title on mobile and display ... instead.

### ISSUE THREAD

**Issue by oddlama** [louislam/uptime-kuma#2103]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### Description

Often when I open my status page on my mobile device, some of the monitors fail to load the name which just shows `...` then. I've attached a screenshot below so you can see what I mean. I've also checked all logs and neither my nginx reverse proxy nor the application itself log anything if that happens. The status also seems to work fine and shows the correct bars, just the name is not displayed.

It's not always the same item, but by chance it seems to affect some of them more often than others. This also happens on multiple browsers (I tested Chrome, Firefox) on Android and also on Safari. I'd say the chance that some of the names become `...`  is about 80% (out of ~15 items). On my desktop system I've also experienced this issue, but only once over the past week, so definitely a lot less likely. It also seems to happen more often on a mobile connection than in my WiFi.

![Untitled](https://user-images.githubusercontent.com/31919558/190923545-4d513de8-8337-4059-ae07-0cf642e0ab0a.png)

### 👟 Reproduction steps

Opening any of the status pages on a mobile device on mobile data triggers this very frequently.

### 👀 Expected behavior

Name should be fully shown.

### 😓 Actual Behavior

Name is shown as `...`.

### 🐻 Uptime-Kuma Version

1.18.0

### 💻 Operating System and Arch

Gentoo ~amd64

### 🌐 Browser

Firefox for Android 103.2.0

### 🐋 Docker Version

Running on Bare Metal

### 🟩 NodeJS Version

18.9.0

### 📝 Relevant log output

```shell
[No specific log output generated]
```

**Comment by louislam** [comment]
Duplicated of https://github.com/louislam/uptime-kuma/issues/2100
