### ISSUE TITLE
Using Kubernetes service name

### ISSUE THREAD

**Issue by hnhai** [louislam/uptime-kuma#2105]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

I want to use service name of kubernetes (Kubernetes DNS) instead of real domain because we don't publish services to internet.
Example: http://service-name-a/heath. But error: `queryA ESERVFAIL` invest-api-web apear

### 🐻 Uptime-Kuma Version

1.18.0

### 💻 Operating System and Arch

Ubuntu 20.04

### 🌐 Browser

Version 105.0.5195.102 (Official Build) (64-bit)

**Comment by kahootali** [comment]
I am also using Uptime Kuma and I can monitor my Kubernetes services using it. Is uptime-kuma and the service in the same namespace? If not, then add the `http://SERVICE_NAME.NAMESPACE_NAME/health` as host

**Comment by janhartje** [comment]
Yeah it shoud be possible, if the services are in other namespaces you can do it like @kahootali mentioned. Except you have network policies that aren't allow cross namespace communication.

**Comment by hnhai** [comment]
Uptime-Kuma and service in the same namespace.
I try exec to uptime-kuma pod and curl http://SERVICE_NAME/health, it work fine.

=> But after using 

> http://SERVICE_NAME.NAMESPACE_NAME/health

like @kahootali mentioned it work on web UI.
I don't know why in same namespace, they need cross namespace service type to connect each other.
Thanks for support @kahootali @janhartje
