### ISSUE TITLE
A friendly name with many words will disappear on small width screen

### ISSUE THREAD

**Issue by xkvnn** [louislam/uptime-kuma#2106]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### Description

A friendly name with many words will disappear on a small width screen.

![image](https://user-images.githubusercontent.com/15854252/190972364-ea2e5ae0-01b7-497b-b173-a01ce6d416a0.png)

### 👟 Reproduction steps

1. Set the friendly name of the monitor with many words.
2. View the Status page on a small width browser.

### 👀 Expected behavior

The friendly name should be break line to show.

### 😓 Actual Behavior

The friendly name show only three dots.

### 🐻 Uptime-Kuma Version

1.18.0

### 💻 Operating System and Arch

Windows

### 🌐 Browser

Google Chrome

**Comment by louislam** [comment]
Duplicate of https://github.com/louislam/uptime-kuma/issues/2100
