### ISSUE TITLE
Change discord message?

### ISSUE THREAD

**Issue by Ultra-Meloncrafter** [louislam/uptime-kuma#2109]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [x] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

Is there a way to change the discord message, because when i tried it, it didn't change much

### 🐻 Uptime-Kuma Version

1.18.0

### 💻 Operating System and Arch

Debian 10

### 🌐 Browser

Opera GX Latest

### 🟩 NodeJS Version

v16.17.0

**Comment by Alex2021cyberhuman** [comment]
Hello. I found [lines](https://github.com/louislam/uptime-kuma/blob/9a7c2d562ab6baeea96ded002ac5b8664bfb193c/server/notification-providers/discord.js#L49) where discord notification provider setting title to discord embeded object 
I think it will help you or some one else to implement custom messages
Tell me if i wrong.

**Comment by Ultra-Meloncrafter** [comment]
i already changed that and restarted uptime-kuma, but it didn't change anything

**Comment by Computroniks** [comment]
Did you only edit the title or all of the lines?
https://github.com/louislam/uptime-kuma/blob/9a7c2d562ab6baeea96ded002ac5b8664bfb193c/server/notification-providers/discord.js#L49-L71

**Comment by Hi-ImKyle** [comment]
A more concrete way of changing the sent embed would be nice to have. Even if it's just a text area that accepts an embed in json with say replacement words like %MONITOR_NAME% or %MONITOR_STATUS%

**Comment by CommanderStorm** [comment]
Please subscribe to this issue instead https://github.com/louislam/uptime-kuma/issues/1388
I think adding this would require https://github.com/louislam/uptime-kuma/issues/646 first
