### ISSUE TITLE
How to add a new item to the Kuma database in command line, not from its web interface?

### ISSUE THREAD

**Issue by perpi** [louislam/uptime-kuma#2110]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

I want to add a part in our _virtual machine creation script_ to automatically add any new machine to **Uptime Kuma** for monitoring Ping.
I looked at the DB file in `/var/lib/docker/volumes/uptime-kuma`, but I get this error when I try to connect to it by the command `sqlite`:

      Unable to open database /var/...: file is encrypted or is not a database.

I have installed Kuma by docker on Ubuntu. How can I add addresses directly from Ubuntu command line or through a script?

### 🐻 Uptime-Kuma Version

1.18.0, docker

### 💻 Operating System and Arch

Ubuntu 22.04 64bit

### 🌐 Browser

All

### 🐋 Docker Version

Docker version 20.10.12

### 🟩 NodeJS Version

v16.16.0

**Comment by Computroniks** [comment]
This is not something that is currently supported. It would be possible to manually edit the database file however this is not recommended. It is better to add the monitor using the web interface.

**Comment by louislam** [comment]
> I looked at the DB file in `/var/lib/docker/volumes/uptime-kuma`

Did you mean `/var/lib/docker/volumes/uptime-kuma/_data/kuma.db`?

It should be readable, but as @Computroniks this is not recommended.

**Comment by perpi** [comment]
I wonder if inserting a new item would work by web GET/POST on a _json_ file or not?! If yes, I will hire a web programmer for a couple of hours.

**Comment by svetoslav1303** [comment]
> on a json file

**Some script** that fill all data in sqlite db file.
 Inside [app_base_directopry]/data/kuma.db  

Need to fill data in table with name from which object are readed - 
just :insert data  in table named [**monitor**]https://github.com/louislam/uptime-kuma/blob/e5796104262b0558d70b30df49fa7902b2810d67/server/server.js#L624

**On short** - Not for `GET/POST` case !
project use for all request except few as we can see below

Normal GET/POST:  https://github.com/louislam/uptime-kuma/blob/e5796104262b0558d70b30df49fa7902b2810d67/server/server.js#L174
Socket: [here] https://github.com/louislam/uptime-kuma/blob/e5796104262b0558d70b30df49fa7902b2810d67/server/server.js#L269
[Socket.io] https://github.com/louislam/uptime-kuma/blob/master/CONTRIBUTING.md#key-technical-skills
[WebSocket] https://socket.io/docs/v4/

**Comment by Rayhubi** [comment]
I want to cooperate
Please tell me how i can do it
