### ISSUE TITLE
Disconnect while uploading big json

### ISSUE THREAD

**Issue by wojcikm** [louislam/uptime-kuma#2112]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### Description

While uploading json with ~600 domains, the web socket disconnects, hence the upload fails.

Also - while using the kuma with that amount of domains, the same situation happens while displaying dashboard - from time to time websocket connection is dropped and the dashboard has to be refreshed (which takes several seconds).
![output](https://user-images.githubusercontent.com/19979741/191575506-728ed5bf-d75a-471f-adc1-2935d0dd5fe3.gif)

### 👟 Reproduction steps

Create big json with +600 elements and try to import it

### 👀 Expected behavior

Correct import

### 😓 Actual Behavior

socket disconnected and I have to split the file into two smaller ones and then import them separately

### 🐻 Uptime-Kuma Version

1.1.8

### 💻 Operating System and Arch

docker official image

### 🌐 Browser

brave

### 🐋 Docker Version

20.10.18, build b40c2f6

### 📝 Relevant log output

```shell
no logs
```

**Comment by louislam** [comment]
Duplicateof #2067
