### ISSUE TITLE
Docker: Log to file

### ISSUE THREAD

**Issue by nopoz** [louislam/uptime-kuma#2123]
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

Other

### 🔖 Feature description

Give the Docker container the ability to log to a file. I use fail2ban and it needs to read a log file that contains failed login attempts. Currently the docker log is only written to stdout and accessible by running `docker logs <container name>`. 

### ✔️ Solution

Allow for an optional container environment variable that would specify where to write log data to.

**Comment by pimjansen** [comment]
A docker container is immutable so why log to a file? Just catch the output from stdout?

**Comment by nopoz** [comment]
> A docker container is immutable so why log to a file? Just catch the output from stdout?

Did you just read the title and write this reply?

**Comment by pimjansen** [comment]
> > A docker container is immutable so why log to a file? Just catch the output from stdout?
> 
> 
> 
> Did you just read the title and write this reply?

No, but writing all application logs to file is not the way to go. If fail2ban wants a log it can also do this from stdout i assume? Though im curious on the setup of the environment to assist you in a proper design solution

**Comment by asyba** [comment]
+1
way to save the response when the monitor fails.
right now its logged in the terminal inside docker, will be nice to save that to a file.

**Comment by HvRibbecK** [comment]
+1
Would also like to monitor Uptime Kuma's log with Fail2ban.

**Comment by wechsler42** [comment]
+1 Yes, I would also like to montior the access log of Uptime Kuma with fail2ban.

**Comment by CommanderStorm** [comment]
@wechsler42 @asyba @casudo 

Please refrain from posting `+1` / requests for updates things on issues, as this makes issue-management harder.
Issues are for discussing **what needs to be done how by whom**.
[We use 👍🏻 on issues to prioritise work](https://github.com/louislam/uptime-kuma/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc), as always: [Pull Requests](https://github.com/louislam/uptime-kuma/blob/master/CONTRIBUTING.md) welcome.

@nopoz 
Docker logs can be redirected to a file via solutions like presented in https://betterstack.com/community/questions/how-to-redirect-docker-logs-to-file/

**Comment by CommanderStorm** [comment]
Closing as resolved by https://betterstack.com/community/questions/how-to-redirect-docker-logs-to-file/ as commented above
