### ISSUE TITLE
Hardcoded ping executable path

### ISSUE THREAD

**Issue by JulienMalka** [louislam/uptime-kuma#2126]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### Description

The ping binary path is hardcoded in this file :

https://github.com/louislam/uptime-kuma/blob/443235b20b9db8fab84f2bf580bf50fbaa3a53c6/server/ping-lite.js#L35

Is there a reason hardcoded path are used instead of relying on the environment ? This assumes compliance with the linux Filesystem Hierarchy Standard which is not always the case. For example NixOS stores all the executables in /nix/store/.
If there is no specific reason, I could try to adapt this file and submit it as a PR.

### 👟 Reproduction steps

/

### 👀 Expected behavior

Utime-kuma ping monitor is working correctly.

### 😓 Actual Behavior

Uptime-kuma complains the the ping binary is not installed.

### 🐻 Uptime-Kuma Version

1.18

### 💻 Operating System and Arch

NixOS 22.05

### 🌐 Browser

Firefox

**Comment by louislam** [comment]
ping-lite.js is modified of https://github.com/ben-bradley/ping-lite.

As NixOS is not officially supported by Uptime Kuma, I change it to `feature-request`.

**Comment by JulienMalka** [comment]
Thanks for your answer, when [this](https://github.com/NixOS/nixpkgs/pull/189807) PR will be merged uptime-kuma will be officially packaged in NixOS and will even have its own module. For now, the packaging in NixOS involve patching uptime-kuma source code to replace the path of the ping binary, which is not ideal. Would you be interested if I was to put together a PR for using the path from the environment instead ?

**Comment by louislam** [comment]
Is it able to detect NixOS in Node.js?

If yes, it is better to add an `else-if` for NixOS.

**Comment by RaitoBezarius** [comment]
> Is it able to detect NixOS in Node.js?
> 
> If yes, it is better to add an `else-if` for NixOS.

Hm, I don't think it's a good idea, currently, this piece of code do not respect the UNIX derivatives standard way of detecting binaries, e.g. shelling out to use `$PATH` to find the searched binary.

Applying the suggested patch would work for *all distributions* respecting the fact that `ping` can be found out in `$PATH`, which is already the case for all distributions that are working with Uptime-Kuma.

So this change keeps the statut-quo and improves the experience for the others UNIX derivatives.

**Comment by Computroniks** [comment]
No one has implemented this yet have they? If so, I will work on this either tonight or tomorrow. I do agree with @RaitoBezarius, hard coded binary paths is just a bad idea that makes compatibility with systems with non standard configurations near impossible. We might as well use `$PATH` for this as, after all, it is what it is there for.

**Comment by JulienMalka** [comment]
@Computroniks As far as I am concerned you can go for it, I have not started to work on it :) Thanks!

**Comment by JulienMalka** [comment]
Thanks for handling that, I've been able to remove the patches rewriting the ping path on NixOS :)
