### ISSUE TITLE
Hacktoberfest 2022

### ISSUE THREAD

**Issue by Bouni** [louislam/uptime-kuma#2128]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

Hi,

[Hacktoberfest 2022](https://hacktoberfest.com/) is around the corner and it would be awesome if you could add the `hacktoberfest` label to the list of topics of this repo! 

If a user then submits a PR within the month of october and you concider to merge it (does not need to happen within october!) you can simply add the `hacktoberfest-accepted` label to that PR so that it counts for the user.

Would be awesome if you could do that 😃 

And by the way, thank you so much for Uptime Kuma, a really great piece of open source softwar 😍 

### 🐻 Uptime-Kuma Version

1.18.0

### 💻 Operating System and Arch

Arch linux

### 🌐 Browser

Firefox

### 🐋 Docker Version

20.10.17

**Comment by louislam** [comment]
Thanks for the remind, just added. 

It is all upper-case text and glowing text in their website, it is so uncomfortable to read, lol. 

Just curious, what is the price?

**Comment by Bouni** [comment]
The first 40000 participants who reach 4 accepted PRs will get either a T-shirt or a tree planted in their name.

**Comment by rezzorix** [comment]
Hehe nice! Do workflow PRs count to this? 😎😈

**Comment by louislam** [comment]
Just check again, Uptime Kuma is now on list.

![image](https://user-images.githubusercontent.com/1336778/192762711-55a79460-ac1d-4ffa-ab45-13d0be35cb5c.png)

**Comment by CommanderStorm** [comment]
@Bouni
I think this issue is not relevant anymore.
Could you close it? ^^
