### ISSUE TITLE
Cannot add Docker Host via TCP

### ISSUE THREAD

**Issue by philippkayser** [louislam/uptime-kuma#2132]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### Description

I cannot add a docker host which is accessible via tcp 2375 to uptimekuma.

Test button stucks for unlimited time.

![image](https://user-images.githubusercontent.com/41049458/192503900-e6744706-a9e9-4d6e-b8a6-54f558588008.png)

Access to the port is working.

![image](https://user-images.githubusercontent.com/41049458/192504026-9f724d21-e32d-4e8a-9b9f-b40025aee384.png)

### 👟 Reproduction steps

Allow acccess to 2375 on docker host and iptables

Add host to uptimekuma

### 👀 Expected behavior

Get a success connection.

### 😓 Actual Behavior

Test/Save button stucks in loading.

### 🐻 Uptime-Kuma Version

1.18.0

### 💻 Operating System and Arch

Ubuntu and Docker

### 🌐 Browser

Chrome

### 🐋 Docker Version

Monitoring docker: 20.10.18  |  Docker running uptimekuma: 19.03.13

### 📝 Relevant log output

```shell
no output
```

**Comment by louislam** [comment]
Cannot reproduce. 

Please test the connection inside Uptime Kuma container.
https://github.com/louislam/uptime-kuma/wiki/Troubleshooting
