### ISSUE TITLE
How to log in as admin? I don't know the password or login

### ISSUE THREAD

**Issue by Allaninio** [louislam/uptime-kuma#2138]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

What are the passwords to login to the admin panel?

### 🐻 Uptime-Kuma Version

New

### 💻 Operating System and Arch

Replit

### 🌐 Browser

Chrome

### 🐋 Docker Version

New

### 🟩 NodeJS Version

New

**Comment by Computroniks** [comment]
Replit is not supported. See https://github.com/louislam/uptime-kuma/issues/1814#issuecomment-1162913713

However, when you first accessed the web ui, you should have seen a screen to create a new user. This might not work on replit and I think other users have had issues with creating accounts when using replit as replit is not supported.

**Comment by rezzorix** [comment]
The Wiki helps here:  [Reset Password via CLI](https://github.com/louislam/uptime-kuma/wiki/Reset-Password-via-CLI)

**Comment by ShadowGaming100** [comment]
> ### ⚠️ Please verify that this bug has NOT been raised before.
> * [x]  I checked and didn't find similar issue
> 
> ### 🛡️ Security Policy
> * [x]  I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)
> 
> ### 📝 Describe your problem
> What are the passwords to login to the admin panel?
> 
> ### 🐻 Uptime-Kuma Version
> New
> 
> ### 💻 Operating System and Arch
> Replit
> 
> ### 🌐 Browser
> Chrome
> 
> ### 🐋 Docker Version
> New
> 
> ### 🟩 NodeJS Version
> New

Delete the data folder then use the update code
