### ISSUE TITLE
connect EACCES /var/run/docker.socket

### ISSUE THREAD

**Issue by SoulEater45** [louislam/uptime-kuma#2139]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

I am trying to configure a docker host in the UI and I have mounted `/var/run/docker.socket` inside the container at it is there:
```sh
$ docker exec -it kuma ls -la /var/run/
total 0
drwxr-xr-x 1 root root   38 Sep 29 15:36 .
drwxr-xr-x 1 root root  158 Sep 29 15:36 ..
srw-rw---- 1 root 65536   0 Aug 26 22:26 docker.sock
drwxrwxrwt 1 root root    0 Aug  1 00:00 lock
-rw-rw-r-- 1 root utmp    0 Aug  1 00:00 utmp
```

When I try to configure the host in the UI I get the error `connect EACCES /var/run/docker.sock`. The log output of the container says the following:
```log
Error: connect EACCES /var/run/docker.sock
    at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1187:16) {
  errno: -13,
  code: 'EACCES',
  syscall: 'connect',
  address: '/var/run/docker.sock',
  config: {
    transitional: {
      silentJSONParsing: true,
      forcedJSONParsing: true,
      clarifyTimeoutError: false
    },
    adapter: [Function: httpAdapter],
    transformRequest: [ [Function: transformRequest] ],
    transformResponse: [ [Function: transformResponse] ],
    timeout: 0,
    xsrfCookieName: 'XSRF-TOKEN',
    xsrfHeaderName: 'X-XSRF-TOKEN',
    maxContentLength: -1,
    maxBodyLength: -1,
    validateStatus: [Function: validateStatus],
    headers: { Accept: '*/*', 'User-Agent': 'Uptime-Kuma/1.18.0' },
    url: '/containers/json?all=true',
    httpsAgent: Agent {
      _events: [Object: null prototype],
      _eventsCount: 2,
      _maxListeners: undefined,
      defaultPort: 443,
      protocol: 'https:',
      options: [Object: null prototype],
      requests: [Object: null prototype] {},
      sockets: [Object: null prototype] {},
      freeSockets: [Object: null prototype] {},
      keepAliveMsecs: 1000,
      keepAlive: false,
      maxSockets: Infinity,
      maxFreeSockets: 256,
      scheduling: 'lifo',
      maxTotalSockets: Infinity,
      totalSocketCount: 0,
      maxCachedSessions: 0,
      _sessionCache: [Object],
      [Symbol(kCapture)]: false
    },
    socketPath: '/var/run/docker.sock',
    method: 'get',
    data: undefined
  },
  request: <ref *1> Writable {
    _writableState: WritableState {
      objectMode: false,
      highWaterMark: 16384,
      finalCalled: false,
      needDrain: false,
      ending: false,
      ended: false,
      finished: false,
      destroyed: false,
      decodeStrings: true,
      defaultEncoding: 'utf8',
      length: 0,
      writing: false,
      corked: 0,
      sync: true,
      bufferProcessing: false,
      onwrite: [Function: bound onwrite],
      writecb: null,
      writelen: 0,
      afterWriteTickInfo: null,
      buffered: [],
      bufferedIndex: 0,
      allBuffers: true,
      allNoop: true,
      pendingcb: 0,
      constructed: true,
      prefinished: false,
      errorEmitted: false,
      emitClose: true,
      autoDestroy: true,
      errored: null,
      closed: false,
      closeEmitted: false,
      [Symbol(kOnFinished)]: []
    },
    _events: [Object: null prototype] {
      response: [Function: handleResponse],
      error: [Function: handleRequestError],
      socket: [Function: handleRequestSocket]
    },
    _eventsCount: 3,
    _maxListeners: undefined,
    _options: {
      maxRedirects: 21,
      maxBodyLength: 10485760,
      protocol: 'http:',
      path: '/containers/json?all=true',
      method: 'GET',
      headers: [Object],
      agent: undefined,
      agents: [Object],
      auth: undefined,
      socketPath: '/var/run/docker.sock',
      nativeProtocols: [Object],
      pathname: '/containers/json',
      search: '?all=true'
    },
    _ended: true,
    _ending: true,
    _redirectCount: 0,
    _redirects: [],
    _requestBodyLength: 0,
    _requestBodyBuffers: [],
    _onNativeResponse: [Function (anonymous)],
    _currentRequest: ClientRequest {
      _events: [Object: null prototype],
      _eventsCount: 7,
      _maxListeners: undefined,
      outputData: [],
      outputSize: 0,
      writable: true,
      destroyed: false,
      _last: true,
      chunkedEncoding: false,
      shouldKeepAlive: false,
      maxRequestsOnConnectionReached: false,
      _defaultKeepAlive: true,
      useChunkedEncodingByDefault: false,
      sendDate: false,
      _removedConnection: false,
      _removedContLen: false,
      _removedTE: false,
      _contentLength: 0,
      _hasBody: true,
      _trailer: '',
      finished: true,
      _headerSent: true,
      _closed: false,
      socket: [Socket],
      _header: 'GET /containers/json?all=true HTTP/1.1\r\n' +
        'Accept: */*\r\n' +
        'User-Agent: Uptime-Kuma/1.18.0\r\n' +
        'Host: localhost\r\n' +
        'Connection: close\r\n' +
        '\r\n',
      _keepAliveTimeout: 0,
      _onPendingData: [Function: nop],
      agent: [Agent],
      socketPath: '/var/run/docker.sock',
      method: 'GET',
      maxHeaderSize: undefined,
      insecureHTTPParser: undefined,
      path: '/containers/json?all=true',
      _ended: false,
      res: null,
      aborted: false,
      timeoutCb: null,
      upgradeOrConnect: false,
      parser: null,
      maxHeadersCount: null,
      reusedSocket: false,
      host: 'localhost',
      protocol: 'http:',
      _redirectable: [Circular *1],
      [Symbol(kCapture)]: false,
      [Symbol(kNeedDrain)]: false,
      [Symbol(corked)]: 0,
      [Symbol(kOutHeaders)]: [Object: null prototype]
    },
    _currentUrl: 'http:/containers/json?all=true',
    [Symbol(kCapture)]: false
  },
  response: undefined,
  isAxiosError: true,
  toJSON: [Function: toJSON]
}
```

 I am not sure if it is related, but the UI is really slow if any pop-up is opened, e.g. the settings menu for configuring a docker host.

### 🐻 Uptime-Kuma Version

1.18.0

### 💻 Operating System and Arch

Synology DSM 7

### 🌐 Browser

Firefox 104.0.2 (64-bit)

### 🐋 Docker Version

Docker 20.10.3

**Comment by rezzorix** [comment]
Not sure; but did you try the instructions in Wiki to mount the docker.sock?

Wiki: [(Method 1) Share docker.sock with Uptime Kuma Container](https://github.com/louislam/uptime-kuma/wiki/How-to-Monitor-Docker-Containers)

**Comment by fevo21** [comment]
Do you start the container with any PUID / PGID definitions? I faced a similar issue, but it was resolved when PGID matches the docker group on host or when PUID / PGID definition was removed completely from the compose file.

**Comment by SoulEater45** [comment]
@fevo21 that did the trick. I was setting the PUID and GUID, since it only says its for accessing the data storage, but seems like it has an influence on the docker socket too. I have removed the PUID and GUID and will just make a folder owned by 1000:1000.

**Comment by SoulEater45** [comment]
@fevo21 that did the trick. I was setting the PUID and GUID, since it only says its for accessing the data storage, but seems like it has an influence on the docker socket too. I have removed the PUID and GUID and will just make a folder owned by 1000:1000.

**Comment by fbellati** [comment]
Sorry but i must re-open this issue, i have the same problem.
I tried to share the docker.socket with the kuma container but i received the same error.

Uptime-kuma-version: Version: 1.21.3  - alpine

I shared the docker sock like:
```
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./dockerfiles/kuma/rootfs/app/data:/app/data
      - /var/run/docker.sock:/var/run/docker.sock
```

Inside the container the sock is:
```
/run # ls -la
total 8
drwxr-xr-x    1 root     root          4096 May 14 10:05 .
drwxr-xr-x    1 root     root          4096 May 14 10:05 ..
srw-rw----    1 root     ping             0 Mar 12 08:58 docker.sock
```

So it's root owned (like in the host machine - right) and ping group onwned (Gid 999 - like in the host machine - right).

I added the node user  of the container (1000:1000) to the "ping-999" group

`addgroup node ping`
 And now in the /etc/group appear a line with `ping:x:999:node`

The socks now  it's writable by the user node but the error persist... i don't know Why.

If i run the container without PIG/GID the problem obiovusly disappear.

--
EffE

**Comment by Finallf** [comment]
> Desculpe, mas devo reabrir este problema, estou com o mesmo problema. Tentei compartilhar docker.socket com o contêiner kuma, mas recebi o mesmo erro.
> 
> Versão Uptime-kuma: Versão: 1.21.3 - alpine
> 
> Eu compartilhei a meia docker como:
> 
> ```
>     volumes:
>       - /etc/localtime:/etc/localtime:ro
>       - ./dockerfiles/kuma/rootfs/app/data:/app/data
>       - /var/run/docker.sock:/var/run/docker.sock
> ```
> 
> Dentro do contêiner a meia está:
> 
> ```
> /run # ls -la
> total 8
> drwxr-xr-x    1 root     root          4096 May 14 10:05 .
> drwxr-xr-x    1 root     root          4096 May 14 10:05 ..
> srw-rw----    1 root     ping             0 Mar 12 08:58 docker.sock
> ```
> 
> Portanto, é de propriedade do root (como na máquina host - certo) e do grupo de ping (Gid 999 - como na máquina host - certo).
> 
> Adicionei o usuário do nó do container (1000:1000) ao grupo "ping-999"
> 
> `addgroup node ping` E agora no /etc/group aparece uma linha com`ping:x:999:node`
> 
> As meias agora podem ser escritas pelo nó do usuário, mas o erro persiste... não sei por quê.
> 
> Se eu executar o contêiner sem PIG/GID, o problema obviamente desaparecerá.
> 
> -EfE _

I have the same problem
