### ISSUE TITLE
support for response timeout setting in http monitor

### ISSUE THREAD

**Issue by croftonweed** [louislam/uptime-kuma#2140]
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

Other

### 🔖 Feature description

support for response timeout setting in http monitor.
i think it will be a useful feature.

### ✔️ Solution

support for response timeout setting in http monitor.

**Comment by zenyr** [comment]
I also have stumbled on this case so I decided to write up a PR. (#2142) 

Please give it a casual thumbs-up if ya'll would like to see it reviewed and merged ;)

**Comment by steven-ok** [comment]
确实很需要这个功能
