### ISSUE TITLE
Freshly created backups cannot be restored: Cannot read properties of null (reading '_dockerType')

### ISSUE THREAD

**Issue by Stolz** [louislam/uptime-kuma#2141]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### Description

It's my first time using the tool and the the first thing I have done is create a backup and try to restore it right away. The restoration only works partially. The monitors are restored but some of their fields ('container name' and 'Docker Host') are not restored. The JSON backup file does contain values in the fields, so it seems there is a problem reading the backup file.

### 👟 Reproduction steps

- Start with a fresh install
- Complete user creation
- Add a Docker Host
- Add a new monitor of type 'Docker Container' that uses the Docker Host created in the previous step
- Export a JSON backup with all the monitors
- Delete the monitor 
- Try to import the JSON backup

### 👀 Expected behavior

Backups created by a version of the application should be able to be restored by the same version of the application

### 😓 Actual Behavior

Backups created by the application do not restore all the fields in the backup.

### 🐻 Uptime-Kuma Version

1.18.0

### 💻 Operating System and Arch

Gentoo Linux

### 🌐 Browser

Mozilla Firefox 104.0.2

### 🐋 Docker Version

Docker version 20.10.17, build 100c70180f

### 📝 Relevant log output

```shell
uptime-kuma   | 2022-09-30T10:05:00.835Z [MANAGE] INFO: Importing Backup, User ID: 1, Version: 1.18.0
uptime-kuma   | 2022-09-30T10:05:00.858Z [MANAGE] INFO: Resume Monitor: 2 User ID: 1
uptime-kuma   | 2022-09-30T10:05:00.868Z [MONITOR] WARN: Monitor #2 'AdGuard': Pending: Cannot read properties of null (reading '_dockerType') | Max retries: 1 | Retry: 1 | Retry Interval: 60 seconds | Type: docker
uptime-kuma   | 2022-09-30T10:05:00.876Z [MANAGE] INFO: Resume Monitor: 3 User ID: 1
uptime-kuma   | 2022-09-30T10:05:00.886Z [MONITOR] WARN: Monitor #3 'Adminer': Pending: Cannot read properties of null (reading '_dockerType') | Max retries: 1 | Retry: 1 | Retry Interval: 60 seconds | Type: docker
uptime-kuma   | 2022-09-30T10:05:00.894Z [MANAGE] INFO: Resume Monitor: 4 User ID: 1
uptime-kuma   | 2022-09-30T10:05:00.904Z [MONITOR] WARN: Monitor #4 'Authelia': Pending: Cannot read properties of null (reading '_dockerType') | Max retries: 1 | Retry: 1 | Retry Interval: 60 seconds | Type: docker
uptime-kuma   | 2022-09-30T10:05:00.911Z [MANAGE] INFO: Resume Monitor: 5 User ID: 1
uptime-kuma   | 2022-09-30T10:05:00.920Z [MONITOR] WARN: Monitor #5 'Bazarr': Pending: Cannot read properties of null (reading '_dockerType') | Max retries: 1 | Retry: 1 | Retry Interval: 60 seconds | Type: docker
uptime-kuma   | 2022-09-30T10:05:00.927Z [MANAGE] INFO: Resume Monitor: 6 User ID: 1
uptime-kuma   | 2022-09-30T10:05:00.931Z [MONITOR] WARN: Monitor #6 'cAdvisor': Pending: Cannot read properties of null (reading '_dockerType') | Max retries: 1 | Retry: 1 | Retry Interval: 60 seconds | Type: docker
```

**Comment by louislam** [comment]
In 1.18.3, the backup feature is deprecated due to unmaintained. It do not support newly added monitor type, Docker is one of them. You may need to manually create them and back the volume directly in the future instead.

Close as won't fix
