### ISSUE TITLE
Octopush Notifier not working - simple fix?

### ISSUE THREAD

**Issue by danielthedifficult** [louislam/uptime-kuma#2144]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### Description

When attempting to create a new Octopush notification, even when using correct identifiers, the testing fails with a generic notification.
![Screen Shot 2022-09-30 at 7 32 57 PM](https://user-images.githubusercontent.com/1290033/193325282-5973e0ce-4786-458d-b9a2-b04297bf5c50.png)

[Looking at the server-side code](https://github.com/louislam/uptime-kuma/blob/master/server/notification-providers/octopush.js)

This is not due to an incorrect configuration, but rather notification.octopushVersion being set to something other than 1 or 2.

I don't know Vue well enough to figure out if [this front-end code is correct or not](https://github.com/louislam/uptime-kuma/blob/master/src/components/notifications/Octopush.vue)

### 👟 Reproduction steps

On a new Uptime-Kuma instance, create a new Notification using Octopush.

API Version: 
Either

API Key:
Any string

"Login"
Any string

SMS Type:
Either

Telephone:
Any numbers

Then click the "Test" button -> Get error.

### 👀 Expected behavior

Expected Octopush to send or give a failure of credentials, etc.

### 😓 Actual Behavior

Generic message about incorrect Octopush version.

### 🐻 Uptime-Kuma Version

1.18.0

### 💻 Operating System and Arch

Mac OS Monterey 12.6

### 🌐 Browser

Brave

### 🟩 NodeJS Version

16

### 📝 Relevant log output

```shell
uptime-kuma_1  | Error: Error: Error: Unknown Octopush version! 
uptime-kuma_1  |     at Octopush.throwGeneralAxiosError (/app/server/notification-providers/notification-provider.js:38:15)
uptime-kuma_1  |     at Octopush.send (/app/server/notification-providers/octopush.js:59:18)
uptime-kuma_1  |     at Function.send (/app/server/notification.js:116:57)
uptime-kuma_1  |     at Socket.<anonymous> (/app/server/server.js:1149:46)
uptime-kuma_1  |     at Socket.emit (node:events:527:28)
uptime-kuma_1  |     at Socket.emitUntyped (/app/node_modules/socket.io/dist/typed-events.js:69:22)
uptime-kuma_1  |     at /app/node_modules/socket.io/dist/socket.js:466:39
uptime-kuma_1  |     at processTicksAndRejections (node:internal/process/task_queues:78:11)
```

**Comment by Computroniks** [comment]
I will take a look at this today and see if I can work out what is going on.

**Comment by danielthedifficult** [comment]
Thank you so much @Computroniks and @louislam 

I don't see that the nightly builds on Docker are up to date. I'm hoping to deploy this fix to my service :)

Any chance you could trigger a nightly build, and I'll switch back to prod/stable once the fix is released?

Thank you
