### ISSUE TITLE
Ability to create Dependency Relationships

### ISSUE THREAD

**Issue by hansenc0705** [louislam/uptime-kuma#216]
**Is it a duplicate question?**
maybe the grouping request, I read and understand that as grouping services together and maybe it could be used along side dependency relationships as the means to creating them.

**Is your feature request related to a problem? Please describe.**
n/a

**Describe the solution you'd like**
Example - You have a core load balancer, if it goes down all sites it is load balancing will be down as well causing not just the LB alert but all sites on that LB.

**Describe alternatives you've considered**
In the example above it would be nice to just get the alert for the load balancer.

**Additional context**
n/a

**Comment by GlassedSilver** [comment]
Please unstale
