### ISSUE TITLE
 Another VM for Demo

### ISSUE THREAD

**Issue by mhkarimi1383** [louislam/uptime-kuma#2164]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

Hi
I am using a server and providing some public services (https://apps.karimi.dev/) [Located at Europe]
I would love to make it just a another server for Uptime Kuma demo

> I have OneDev Already installed and ready to bring up docker containers :) and that's able to keep itself sync with GitHub

I'm doing it in a Ask for help issue since I don't know where to put it

### 🐻 Uptime-Kuma Version

Latest

### 💻 Operating System and Arch

Debian 11 arm64

### 🌐 Browser

Any

### 🐋 Docker Version

Latest

### 🟩 NodeJS Version

Latest

**Comment by louislam** [comment]
That is great. If you want to follow my current approach, you can take a look of my another project:
https://github.com/louislam/demo-kuma 

It can manages demo instances, shutdown them down while time is up.

**Comment by mhkarimi1383** [comment]
Done, 
But I want to know if I can just disable SSL for [demo-kuma](https://github.com/louislam/demo-kuma) itself, since I have NginX

**Comment by mhkarimi1383** [comment]
also I added a cron job like below to make it up to date

```bash
0 1 * * * cd /srv/uptime-kuma/uptime-kuma/ && git pull && npm install && npm run build
```

**Comment by Saibamen** [comment]
Please close this issue

**Comment by mhkarimi1383** [comment]
> Please close this issue

I'm waiting for the answer of my questions...

**Comment by louislam** [comment]
It seems that the demo server is no longer working.

**Comment by mhkarimi1383** [comment]
> It seems that the demo server is no longer working.

I'm having problem withing some DNS Servers (currently only 4.2.2.4 is working), I ticketing with my providers...
