### ISSUE TITLE
v1.18.1 issue with docker TCP connection

### ISSUE THREAD

**Issue by alexdelprete** [louislam/uptime-kuma#2165]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### Description

Just upgraded my two instances of UK to v1.18.1 and on both I had the same problem with docker container check via TCP:

![image](https://user-images.githubusercontent.com/7027842/193662741-b4276ac4-f5ee-4c12-8789-9626803c9872.png)

This is the error when doing the test:

![image](https://user-images.githubusercontent.com/7027842/193661922-61c6106b-f90f-4268-83eb-b7de01c01a70.png)

Reverted to v1.18.0 for now.

### 👟 Reproduction steps

Configure a connection to docker with tcp

### 👀 Expected behavior

connection to docker passing the test

### 😓 Actual Behavior

error: "unsupported TCP"

![image](https://user-images.githubusercontent.com/7027842/193662102-f1cfdf02-beb2-4505-9210-7e942da2fbc2.png)

### 🐻 Uptime-Kuma Version

1.18.1

### 💻 Operating System and Arch

Host: docker Kernel: 5.19.0-15-generic arch: x86_64 bits: 64 Distro: Ubuntu 22.10 (Kinetic Kudu)

### 🌐 Browser

Edge 107.0.1402.2 (Official build) dev (64-bit)

### 🐋 Docker Version

Docker 20.10.16

**Comment by asucrews** [comment]
rolled back to 1.18.0 and tcp socket works.

**Comment by alexdelprete** [comment]
> rolled back to 1.18.0 and tcp socket works.

Yes, like I wrote in the OP: v1.18.0 works fine.

**Comment by louislam** [comment]
Investigating, the Docker container monitor's logic is not touched in this release.

I suspect that it causes by the newer version of axios.
https://github.com/louislam/uptime-kuma/pull/2011/files

**Comment by louislam** [comment]
Workaround:

Change tcp:// to http://

**Comment by alexdelprete** [comment]
Thanks. In the final fix should we use http or you will maintain tcp for compatibility?

**Comment by louislam** [comment]
> Thanks. In the final fix should we use http or you will maintain tcp for compatibility?

You can use both in the next release.
