### ISSUE TITLE
add option to sort monitor

### ISSUE THREAD

**Issue by fernandeusto** [louislam/uptime-kuma#2166]
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

UI Feature

### 🔖 Feature description

add the option to change the order of the services to be monitored in the list

### ✔️ Solution

be able to customize the order of monitoring and not only see them in the order of creation

**Comment by rezzorix** [comment]
> ### ⚠️ Please verify that this feature request has NOT been suggested before.
> 
>     * [x]  I checked and didn't find similar feature request

Really? 😉 

https://github.com/louislam/uptime-kuma/issues/21
https://github.com/louislam/uptime-kuma/issues/1165 
https://github.com/louislam/uptime-kuma/issues/1308

**Comment by javaindian** [comment]
I am using latest 1.19.0 beta version. Sorting is not available in that too.  I am not sure how and why this thread is closed.

**Comment by rezzorix** [comment]
> I am using latest 1.19.0 beta version. Sorting is not available in that too. I am not sure how and why this thread is closed.

Because there are minimum 3 other feature-requests open with the same/similar request.

**Comment by javaindian** [comment]
Ok. Thanks. I presume the issue is still open.

**Comment by rezzorix** [comment]
If you would just read my initial answer - I even linked to the 3 issues 🤷🏼‍♂️

**Comment by jeremyrnelson** [comment]
See #1585
