### ISSUE TITLE
How to backup data?

### ISSUE THREAD

**Issue by HolgerAusB** [louislam/uptime-kuma#2168]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

Since 1.18.1 under `settings > backup`, kuma give a warning, that the backup feature is 'depricated while a bit of unmaintained' And we should backup the `./data/` folder instead. But I do not have a folder with that name.

I am using a docker with:

```
docker run -d --restart=always -p 3001:3001 -v uptime-kuma:/app/data --dns 192.168.x.x --dns 192.168.x.x --name uptime-kuma louislam/uptime-kuma:1
```

So I think I have to backup files `uptime-kuma/kuma.db*` within my dockers container folder, am I right with that?

### 🐻 Uptime-Kuma Version

1.18.1

### 💻 Operating System and Arch

Raspbian/Debian Bullseye on RaspberryPi 4

### 🌐 Browser

Firefox 105.0.1 Windows 11

### 🐋 Docker Version

20.10.18, build b40c2f6

### 🟩 NodeJS Version

16.17.1

**Comment by louislam** [comment]
Backup this folder `/var/lib/docker/volumes/uptime-kuma/_data` on your Raspberry.

**Comment by HolgerAusB** [comment]
Thank you. Just realized that the files in my dockers folder was from an older try to get the container by `docker-compose.yml`

**Comment by thomas-mc-work** [comment]
Can I do that while the container is running?

**Comment by ruimarinho** [comment]
You won't get a consistent backup if you try to backup those sqlite files while the container is running @thomas-mc-work.

**Comment by AshikNesin** [comment]
Just in case if anyone wants to use [litestream](https://litestream.io/) based approach which can be deployed in any docker environment 👇

I have tested this in fly.io

https://www.koyeb.com/tutorials/monitor-your-websites-and-apps-using-uptime-kuma
