### ISSUE TITLE
unable to update or install 1.18.2

### ISSUE THREAD

**Issue by cyril59310** [louislam/uptime-kuma#2171]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### Description

impossible to update uptime kuma or install  to version 1.18.2 even by following the wiki

### 👟 Reproduction steps

I use the installation or update commands in version without docker available on the wiki

https://github.com/louislam/uptime-kuma/wiki/%F0%9F%94%A7-How-to-Install
https://github.com/louislam/uptime-kuma/wiki/%F0%9F%86%99-How-to-Update

### 👀 Expected behavior

uptime kuma update to 1.18.2

### 😓 Actual Behavior

uptime kuma stay on version 1.18.0

![image](https://user-images.githubusercontent.com/70776486/193875619-e3754a8a-dd19-4aa8-b281-16fa01991c97.png)

### 🐻 Uptime-Kuma Version

1.18.0

### 💻 Operating System and Arch

debian 10

### 🌐 Browser

chrome

### 🟩 NodeJS Version

17.9.0

**Comment by louislam** [comment]
Fixed, please re-fetch the tags by:
```
git fetch --tags --force
```

And then you should be able to install
```
git checkout 1.18.2 --force

# Install dependencies and prebuilt
npm install --production
npm run download-dist
```
