### ISSUE TITLE
Multiple client IPs in X-Forwarded-For

### ISSUE THREAD

**Issue by benscobie** [louislam/uptime-kuma#2175]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### Description

It's possible that X-Forwarded-For contains multiple IPs when going through multiple proxies. This means [this function](https://github.com/louislam/uptime-kuma/blob/b22176d218afd1337387bfeef9fd3d3c98358bb1/server/uptime-kuma-server.js#L141) could return something like: 81.132.213.150, 172.71.178.201. Looking at https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Forwarded-For it probably makes the most sense to select the left most IP (the first one). I spotted this as I was setting up https://hub.crowdsec.net/author/timokoessler/configurations/uptime-kuma-logs which fails to parse with the log like this. E.g.
2022-10-04T12:49:23.029Z [AUTH] WARN: Incorrect username or password for user asd. IP=81.132.213.150, 172.71.178.201

I'm happy to raise a PR if this is something you agree is a bug.

### 👟 Reproduction steps

Using Cloudflare proxying with Traefik.

### 👀 Expected behavior

The returned client IP should be the correct IP address.

### 😓 Actual Behavior

A comma delimited list is returned instead.

### 🐻 Uptime-Kuma Version

1.18.2

### 💻 Operating System and Arch

Debian 11

### 🌐 Browser

Firefox

### 🐋 Docker Version

20.10.18

**Comment by louislam** [comment]
Yes, I think it is a bug, `getClientIP()` should return the first IP only (81.132.213.150 in your example).
