### ISSUE TITLE
Monitor rDNS

### ISSUE THREAD

**Issue by marek22k** [louislam/uptime-kuma#2179]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### Description

Shows down for rDNS, but works via dig
```
$dig @1.1.1.1 0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.e.1.2.2.0.f.8.e.0.a.2.ip6.arpa  PTR

; <<>> DiG 9.18.4-2~bpo11+1-Debian <<>> @1.1.1.1 0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.e.1.2.2.0.f.8.e.0.a.2.ip6.arpa PTR
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 53205
;; flags: qr rd ra ad; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 1232
;; QUESTION SECTION:
;0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.e.1.2.2.0.f.8.e.0.a.2.ip6.arpa. IN PTR

;; ANSWER SECTION:
0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.e.1.2.2.0.f.8.e.0.a.2.ip6.arpa. 604800 IN PTR	cn-pingable.byeob.de.

;; Query time: 269 msec
;; SERVER: 1.1.1.1#53(1.1.1.1) (UDP)
;; WHEN: Wed Oct 05 14:07:41 CEST 2022
;; MSG SIZE  rcvd: 135
```
![Screenshot at 2022-10-05 14-07-06](https://user-images.githubusercontent.com/46723399/194056817-3bd587a4-98dc-4807-8d27-bf1c7cd9980a.png)

### 👟 Reproduction steps

Add DNS monitor and entry rDNS Domain

### 👀 Expected behavior

Monitor rDNS domain

### 😓 Actual Behavior

Does not monitor rDNS domain

### 🐻 Uptime-Kuma Version

1.18.2

### 💻 Operating System and Arch

Debian 11

### 🌐 Browser

Firefox

### 🟩 NodeJS Version

v14.20.1

**Comment by louislam** [comment]
Normal IPv6 address is fine.

![image](https://user-images.githubusercontent.com/1336778/194101575-9a20bcb9-094a-47cf-b318-805dd25e37e1.png)

We directly use Node.js's dns.reverse() function, which do not support your format. 

If you need this, please open ask Node.js to support it.

https://nodejs.org/api/dns.html#dnsreverseip-callback
