### ISSUE TITLE
Adding Google Analytics 

### ISSUE THREAD

**Issue by J4mez** [louislam/uptime-kuma#2180]
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

API

### 🔖 Feature description

It would be nice to add the google analytics API like UptimeRobot has for example. 

### ✔️ Solution

Adding Google Analytics so that you only need to supply your Token in the settings page and it starts collecting data

### ❓ Alternatives

Allow for custom HTML snippets to add your own analytics

**Comment by lazerleif** [comment]
Would be nice to use other analytics to. Ie umami, which uses a head code snippet

**Comment by aksthelion** [comment]
I need it too. What about just adding a settings for Header/Footer code and we can paste the GA code in there.
