### ISSUE TITLE
Add support for different ports for Radius 

### ISSUE THREAD

**Issue by pbgben** [louislam/uptime-kuma#2182]
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

New Monitor

### 🔖 Feature description

Could we please have the ability to set the port for the radius monitor? 

### ✔️ Solution

Either a new field for a port, or perhaps its easier to allow hostname:port Either would be great.

**Comment by Computroniks** [comment]
I will have a look into this tomorrow evening
