### ISSUE TITLE
DNS, VPS, Docker

### ISSUE THREAD

**Issue by willy695** [louislam/uptime-kuma#2184]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

Hi all,I have existing UptimeKuma docker installation on my Ubuntu VPS, but I don't know how to use/generate SSL certificate on server.
So I found [Reverse Proxy with Cloudflare setup](https://github.com/louislam/uptime-kuma/wiki/Reverse-Proxy-with-Cloudflare-Tunnel), and did this:
1. purchased a domain name at namecheap
2. used cloudflare NS to get the DNS zone there
3. added the domain and created few DNS records at cloudflare  (A records, proxied) to point to my VPS
4. went to Cloudflare Zero Trust, in order to create token
5. ended up without my website available in the dropdown

As a result, when typing my domain name and port :3001 I get nothing, and on domain name I get:Web server is down Error code 521 (host error)
I fucked something up, can someone please help me setup this correctly?
If do, please send me a message. Thanks

### 🐻 Uptime-Kuma Version

1.18.2

### 💻 Operating System and Arch

Ubuntu 22.04

### 🌐 Browser

Chrome

**Comment by louislam** [comment]
> 5. ended up without my website available in the dropdown

Maybe try it later, since your domain just docked to Cloudflare.

Temporarily, you can go back to use your :3001 address, but you are facing this error:

> when typing my domain name and port :3001 I get nothing, and on domain name I get:Web server is down Error code 521 (host error)

![image](https://user-images.githubusercontent.com/1336778/194349914-5f8a647b-fb5e-4286-b094-37f492880d37.png)


I guess is that, you enabled this cloudflare proxy on your sub domain. You have to disable this, because it supports 443/80 only, not 3001.

**Comment by willy695** [comment]
> > 5. ended up without my website available in the dropdown
> 
> Maybe try it later, since your domain just docked to Cloudflare.
> 
> Temporarily, you can go back to use your :3001 address, but you are facing this error:
> 
> > when typing my domain name and port :3001 I get nothing, and on domain name I get:Web server is down Error code 521 (host error)
> 
> ![image](https://user-images.githubusercontent.com/1336778/194349914-5f8a647b-fb5e-4286-b094-37f492880d37.png)
> 
> I guess is that, you enabled this cloudflare proxy on your sub domain. You have to disable this, because it supports 443/80 only, not 3001.

I don't have any domain/subdomain created on my Ubuntu VPS, here is the DNS from Cloudflare:
![Screenshot (6)](https://user-images.githubusercontent.com/54405267/194371892-f3cfb8d9-345c-4a6f-9dbf-19fdcc7cf7aa.png)

**Comment by gokkstudio** [comment]
You were right, I just had to wait a little bit. Thanks mate
