### ISSUE TITLE
Script tag in Footer Text breaks window.preloadData at Status Page

### ISSUE THREAD

**Issue by siimots** [louislam/uptime-kuma#2186]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### Description

Script tag in custom footer text breaks window.preloadData and it gets added to page.
<img width="670" alt="footer bug" src="https://user-images.githubusercontent.com/7014925/194374716-72b4f5b8-4a5c-4cdd-83c3-bcb7205cca82.png">

Also side effect is that you can load custom JS/XSS there if use this footer text:
`"</script><script>alert()</script>"`

### 👟 Reproduction steps

1. Edit Status Page
2. Footer text: <script></script>
3. Save and json is added to top of the page.
4. Console error: Uncaught SyntaxError: Invalid or unexpected token

### 👀 Expected behavior

window.preloadData should escape script to avoid parse error

### 😓 Actual Behavior

window.preloadData crashes  when script tag is in Footer Text.

### 🐻 Uptime-Kuma Version

1.18.0

### 💻 Operating System and Arch

Windows 10

### 🌐 Browser

Edge latest

**Comment by louislam** [comment]
window.preloadData did parse to an JSON object.

The real problem is that, cheerio removed the end tag unexpectedly.

Normally, it should be this:
```html
<script>
    window.preloadData = { ... }
</script>
```

But if the content inside the tag have `</script> `, it will become like this.

```html
<script>
    window.preloadData = { ... "</script>" ... }
// No End Tag
```
