### ISSUE TITLE
No Notifications - Error Connect ENETUNREACH

### ISSUE THREAD

**Issue by emanueltilly** [louislam/uptime-kuma#2189]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

I can not setup any notification services.
Whenever i test the new notification services I have configured (Tried Google Chat, Pushover, Pushbullet) I get error "Error: Error: connect ENETUNREACH" followed by a IPV6 address. The host has internet access and I can successfully resolve and ping external websites.

### 🐻 Uptime-Kuma Version

1.18.3

### 💻 Operating System and Arch

Raspian 11 Bullseye

### 🌐 Browser

Google Chrome 105.0.5195.125

### 🐋 Docker Version

N/A

### 🟩 NodeJS Version

18.10.0

**Comment by louislam** [comment]
Still related to your network.

If your network supports IPv6, double check your IPv6 connection on your Pi.
If it is not supported, check why your DNS server gave you IPv6 addresses instead of IPv6

**Comment by emanueltilly** [comment]
Thank you for the quick reply.
I disabled Ipv6 on the host and now there seems to be another error:
"Error: cacheableLookup ENOTFOUND chat.googleapis.com".
I have tried pinging chat.googleapis.com from the host and it resolves and I get a response.

**Comment by CommanderRedYT** [comment]
I have the same problem. My DNS server (pihole, via dhcp) has IPv6 responses disabled and `dig` confirms that. Still, somehow this program tries to connect via IPv6

**Comment by louislam** [comment]
#2321 I guess it may be a similar issue.
