### ISSUE TITLE
Ping Graph 12-hour or 24-hour 

### ISSUE THREAD

**Issue by R0GGER** [louislam/uptime-kuma#219]
Please create a switch to change timeformat to 12-hour or 24-hour. Currently it's both :frowning_face:
![image](https://user-images.githubusercontent.com/8298741/129571354-c03bddd1-5461-4572-a81b-9e2f9d6aa591.png)

**Comment by chakflying** [comment]
Got it. I'll switch to 24-hour only for now.

**Comment by R0GGER** [comment]
Great! Thanks @chakflying
