### ISSUE TITLE
ntfy : message don't show correctly

### ISSUE THREAD

**Issue by Apashh** [louislam/uptime-kuma#2192]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### Description

The message send by uptime-kuma not show  correctly whatever the initial request.
I use ntfy 1.28.0
![image](https://user-images.githubusercontent.com/83477029/194547406-c7720e57-1da6-4cc8-9c3b-c550851d6409.png)

### 👟 Reproduction steps

1. Create notification NTFY
2. Enter URL (https) of your ntfy server
3. Enter your topic
4. Enter (not required) your topic's credentials
5. Launch a test
6. I obtain the picture above

### 👀 Expected behavior

We will obtain a message with title, message, priority...

### 😓 Actual Behavior

We obtain a single line with no designs/style.. like this : 
![image](https://user-images.githubusercontent.com/83477029/194547406-c7720e57-1da6-4cc8-9c3b-c550851d6409.png)

### 🐻 Uptime-Kuma Version

1.18.3

### 💻 Operating System and Arch

Debian 11

### 🌐 Browser

Google Chrome, Firefox, Edge

### 🟩 NodeJS Version

16.17.1

**Comment by louislam** [comment]
Cannot reproduce on https://ntfy.sh/uptime-kuma

Only effected selfhosted instance?

**Comment by barart** [comment]
Also on the latest version you can save the ntfy settings if you dont add a user and password even if it's optional, when you click on save it focus on the username and password fields if are empty and you cant save, you must put anything on those fiels in order to save the ntfy settings

**Comment by peterprumbach** [comment]
@barart I think the issue that you cannot save the properties without filling username and password in has been fixed in recently updated version `1.18.4`.

**Comment by peterprumbach** [comment]
@Apashh I also cannot reproduce this bug on my ntfy instance running version `1.28.0`.

My settings for this test look like this:
![image](https://user-images.githubusercontent.com/34021473/194749712-f52d7d66-7594-4843-827d-357e6a05879e.png)

And this is the resulting test notification:
![image](https://user-images.githubusercontent.com/34021473/194749751-9ace1019-372b-453c-89d6-cda31f966b37.png)

**Comment by Apashh** [comment]
Ok, I have deleted ntfy packet and reinstall it.. All works ! You can close this issue ! :)

**Comment by Gottarocket** [comment]
@Apashh What was removed. I have same issue now

**Comment by Apashh** [comment]
Be carefull when you enter the URL and the topic's name !

**Comment by Gottarocket** [comment]
I have copied the correct url from ntfy still shows same notification. I use ip:port so http protocol is used. Nee update has issue with that because it worked fine before
