### ISSUE TITLE
Ignore TLS/SSL-Certificate for ex. Matrix

### ISSUE THREAD

**Issue by Chiller2019** [louislam/uptime-kuma#2199]
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

Other

### 🔖 Feature description

Add for some services, like Matrix/Synapse, a "ignore TLS/SSL-Certificate" Checkbox

### ✔️ Solution

See: https://github.com/louislam/uptime-kuma/issues/1904

We cant send messages from uptime-kuma to our selfhosted, maybe localhost, Matrix-Synpase-Server.

Just add a Ignore TLS/SSL-Certificate (or a "--insecure"-Tag), when you check:
`curl -XPOST -d --insecure '{"type": "m.login.password", "identifier": {"user": "botusername", "type": "m.id.user"}, "password": "passwordforuser"}' "https://home.server/_matrix/client/r0/login"`

- Its work, but just with the Tag "--insecure"

### 📝 Additional Context

![179395556-849d4306-fbd3-4ca3-afdf-10ab6977198a](https://user-images.githubusercontent.com/50303399/194618824-0b38f061-4c21-4eb5-adf1-5ba94ac66079.jpg)
![179395568-798cb051-86c8-4d47-991f-94e82a7892bd](https://user-images.githubusercontent.com/50303399/194618829-0d0781bb-bf06-4cbc-9b57-9090dafd88cb.jpg)

**Comment by Alex11381** [comment]
I have same problem with Matrix. Please check that.

**Comment by CommanderStorm** [comment]
Closing as https://github.com/louislam/uptime-kuma/labels/wontfix.

Doing so (ignoring certs for notifications) could mean that an attacker intercepts these notifiations as they are no longer as MITM attacks are possible in this case.

Users seeking this should either
- register the CA for the self-signed cert used by the `$Notificationprovider` server you host with uptime-kuma
- or provide said `$Notificationprovider` server with a valid cert (letsencrypt/...)

Notifications are very different from monitors, where this is handy.
For notifications, you don't want them going to a potentially different server.
