### ISSUE TITLE
"getaddrinfo ENOTFOUND <url>"

### ISSUE THREAD

**Issue by meepmeep** [louislam/uptime-kuma#220]
For an unknown reason, I get some random `"[Title] [🔴 Down] getaddrinfo ENOTFOUND <url>"`.
It's never the same item (but mostly http probe), it happens one time each day maybe. And the website is not offline (and the next check is `"Up!"`).

Kuma is running on docker. What could generate this error message ?

**Comment by chakflying** [comment]
I found that if the machine or the DNS server is busy, the DNS query could timeout, resulting in this error. Unfortunately node.js is very unhelpful in DNS error reporting. For now you can increase the "Retries" setting to avoid this.
