### ISSUE TITLE
LOGIN PAGE ISSUE

### ISSUE THREAD

**Issue by CRYSTAL-HQ** [louislam/uptime-kuma#2201]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

CAN YOU TELL ME WHERE ARE DATA KEPT FOR USERNAME AND PASSWORD BECAUSE I AM USING IT BUT NOW I CAN'T ABLE TO LOGIN BECAUSE I FORGOT THE PASSWORD!

### 🐻 Uptime-Kuma Version

1.10.0

### 💻 Operating System and Arch

Linux server

### 🌐 Browser

Chrome

### 🐋 Docker Version

1.18.4

### 🟩 NodeJS Version

14

**Comment by louislam** [comment]
Please check wiki for how to reset password

**Comment by CRYSTAL-HQ** [comment]
Oh thanks for help
