### ISSUE TITLE
NTFY - Username/Password Required

### ISSUE THREAD

**Issue by adammckay** [louislam/uptime-kuma#2203]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### Description

When you set up an NTFY notification, the username and password are required even though they show on the form as optional.  Not all ntfy servers have a user/pass so having them optional is correct.  Because of this, I am unable to save a new NTFY notification to ntfy.sh (because it doesn't use username/password authentication).

### 👟 Reproduction steps

Create a new ntfy notification to a server (like ntfy.sh) that doesn't require a username / password.  It will test just fine but when you try to save it, you won't be able to.

### 👀 Expected behavior

Expected behavior is that you can save an ntfy notification without a username/password.

### 😓 Actual Behavior

You can only save an ntfy notificaiton with something filled in for the username/password but the notification will not work.  You will not be able to save one without those optional (should be) credentials.

### 🐻 Uptime-Kuma Version

1.18.3

### 💻 Operating System and Arch

Docker (Debian)

### 🌐 Browser

Firefox

### 🐋 Docker Version

20.10.18

**Comment by louislam** [comment]
Fixed on https://github.com/louislam/uptime-kuma/commit/4f6dec41c617267860ec9c686477e03c633e7c4b

Did not spot that pull requests create a lot of issues.🙈
