### ISSUE TITLE
ntfy setup requires username

### ISSUE THREAD

**Issue by sadrian80** [louislam/uptime-kuma#2204]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### Description

A new notification setup for ntfy.sh can't be saved without a value in "Username (optional)" 

### 👟 Reproduction steps

Fresh instance, setup notification, type ntfy.

### 👀 Expected behavior

Saving without giving username.

### 😓 Actual Behavior

Can't save, tooltip on field username: "Fill out this field"

### 🐻 Uptime-Kuma Version

1.18.3

### 💻 Operating System and Arch

Oracle Linux 9

### 🌐 Browser

Safari 16

### 🐋 Docker Version

Docker 20.10.18

**Comment by louislam** [comment]
Duplicate of #2203
