### ISSUE TITLE
[Status page] Custom CSS not applied

### ISSUE THREAD

**Issue by gu1ll0me** [louislam/uptime-kuma#2207]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### Description

Custom CSS works correctly when on edit mode, but not applied when visiting the status page.

Works great with v1.18.3. Broken in v1.18.4.

### 👟 Reproduction steps

Add the code below to the custom CSS of the status page :

```
.overall-status {
  display: none;
}
```

### 👀 Expected behavior

The CSS is applied on the status page when exiting the edit mode.

### 😓 Actual Behavior

The CSS is not applied on the status page when exiting the edit mode.

### 🐻 Uptime-Kuma Version

1.18.4

### 💻 Operating System and Arch

Docker

### 🌐 Browser

Firefox 105.0.3

**Comment by louislam** [comment]
1.8.4, cannot reproduce

![](https://user-images.githubusercontent.com/1336778/194773666-cd73307f-d3d1-4b85-8bd9-552d10f1a076.png)

**Comment by louislam** [comment]
Thanks for the report, just realized that I misused jsesc.

**Comment by gu1ll0me** [comment]
Thanks to you !
