### ISSUE TITLE
Status Page Line Breaks \n? 

### ISSUE THREAD

**Issue by zluckytraveler** [louislam/uptime-kuma#2212]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

For a status page description anytime there is a line break it is represented with a `\n`, which only appears on mobile browsers, not on a desktop browser.  

Is there a way for line breaks to not have this and just show as separate lines or paragraphs on mobile browsers? 

![A51C32EB-9254-4C7E-BD7F-8679C37B78C2](https://user-images.githubusercontent.com/97180817/194817132-30f46614-6a78-4902-be36-5521cb94d684.jpeg)

### 🐻 Uptime-Kuma Version

Latest

### 💻 Operating System and Arch

Mac

### 🌐 Browser

Safari & Chrome

**Comment by louislam** [comment]
I think it is a related issue. https://github.com/louislam/uptime-kuma/issues/2207

**Comment by zluckytraveler** [comment]
@louislam  I'm not using custom CSS, I'm just adding in a description. I've also checked from a non-logged in user just simply viewing the website as a user, and this still shows like this.

**Comment by louislam** [comment]
Should be fixed in 1.18.5

**Comment by zluckytraveler** [comment]
@louislam looks like it’s working now, thank you! 

Is there a way to add formatting for the description text? Things like bold, italicized, underline, etc…

**Comment by louislam** [comment]
Cannot, feel free to open a feature-request if it is not suggested by other people before.
