### ISSUE TITLE
Frontend Version do not match backend version!

### ISSUE THREAD

**Issue by maiconjs** [louislam/uptime-kuma#2213]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

I'm running Uptime Kuma 1.18.4 on an LXC instance of Proxmox, which was installed using this script: "bash -c "$(wget -qLO - https://github.com/tteck/Proxmox/raw/main/ ct/uptimekuma-v4.sh)"

and updated using this script: bash -c "$(wget -qLO - https://github.com/tteck/Proxmox/raw/main/misc/uptimekuma-update.sh)"

The application has been running fine but on the About page I see the following warning "Frontend Version do not match backend version!".

![image](https://user-images.githubusercontent.com/17902999/194889098-8d3696e3-f0bf-4b83-b87a-8e0e819692de.png)

Can I ignore this warning or is this a bug?

### 🐻 Uptime-Kuma Version

1.18.4

### 💻 Operating System and Arch

Debian GNU/Linux 11 (bullseye) LXC on Proxmox

### 🌐 Browser

Microsoft Edge 106.0.1370.34

**Comment by Computroniks** [comment]
This indicates that you haven't downloaded the most recent `dist` for the frontend. It could be the case that something hasn't entirely worked with the script or GitHub. I can't really help with the script because it is a 3rd party script. You might be better raising an issue over there. As to if it matters, yes and no. If you are still running 1.18.0 for your frontend, most stuff will still work but you will be missing some bug fixes.

**Comment by louislam** [comment]
The script is incorrect. It is not the first time I have seen like this. I honestly don't understand why people would like to re-invent the install script without following my installation/update guides.

**Comment by maiconjs** [comment]
I will follow the guidelines. Thx for the information.

**Comment by louislam** [comment]
Nice. To be cleared, I mean the unofficial install script, not your mistake.

The frontend version must be matched the backend version. Otherwise, some features will be broken.

**Comment by maiconjs** [comment]
The developer made the fixes. Now I don't see the message anymore.
