### ISSUE TITLE
Homeassistant Notifications fail with 400 error

### ISSUE THREAD

**Issue by nickm324** [louislam/uptime-kuma#2214]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### Description

With the most recent update of Home Assistant Kuma notifications fail with error 400 bad request.
Was working and I updated HA to the latest version and now using TEST in the notications dialog cause 400 error bad request.

### 👟 Reproduction steps

Triggered the bug using the TEST button when setting up the Notification for Home Assistant.

### 👀 Expected behavior

Expected Home assistant to send notification to my mobile device.

### 😓 Actual Behavior

causes 400 error bad request
Uptime Kuma log shows details but there are no entries in the Home Assistant log of even receiving the request attempt
This was working before I updated Home Assistant to the latest version.

### 🐻 Uptime-Kuma Version

 1.18.4

### 💻 Operating System and Arch

Docker Container running on Unbuntu Server

### 🌐 Browser

106.0.5249.103 

### 🐋 Docker Version

20.10.14

### 📝 Relevant log output

```shell
Error: Error: AxiosError: Request failed with status code 400 400: Bad Request
uptime-kuma    |     at HomeAssistant.throwGeneralAxiosError (/app/server/notification-providers/notification-provider.js:38:15)
uptime-kuma    |     at HomeAssistant.send (/app/server/notification-providers/home-assistant.js:33:18)
uptime-kuma    |     at processTicksAndRejections (node:internal/process/task_queues:96:5)
uptime-kuma    |     at async Socket.<anonymous> (/app/server/server.js:1150:27)
```

**Comment by louislam** [comment]
cc: @rmtsrc

**Comment by rmtsrc** [comment]
It appears to be working correctly for me when testing on my installation.

If the "Notification Service" doesn't exist or is disabled in Home Assistant you'll get a HTTP 400 error.
Does it work if you leave it bank?

Tested with:
* Uptime Kuma Uptime 1.18.5
* Home Assistant 2022.10.3
* Podman 3.0.1
* Firefox 105.0.2

Screenshots:

![Screenshot from 2022-10-11 09-21-11](https://user-images.githubusercontent.com/144435/195039332-456d4d72-d7d5-4673-b69c-eced51c257c0.png)

![screenshot-2022-10-11-093023_002](https://user-images.githubusercontent.com/144435/195039849-4346ea2c-e3c0-4fdc-9f8d-24f4e031c385.jpeg)

**Comment by nickm324** [comment]
Ironically enough it does work when the service field is left empty!
The service works fine using the mobile device in Home Assistant when calling the service in the Home Assistant Services page.

This works, 
![image](https://user-images.githubusercontent.com/6774571/195076977-fc5231e2-dac9-450e-b8f8-8882e54fc160.png)

This Does not unless I remove the service name as you described.
![image](https://user-images.githubusercontent.com/6774571/195077285-ee1bcc37-08df-4f08-a7b9-160fd77deaaf.png)

**Comment by rmtsrc** [comment]
Does running a cURL request directly to Home Assistant work?

Send to a specific device:
```bash
curl --request POST \
  --url http://localhost:8123/api/services/notify/mobile_app_pixel_3 \
  --header 'Authorization: Bearer YOUR-TOKEN' \
  --header 'Content-Type: application/json' \
  --data '{ "title": "Test title", "message": "Test message" }'
```

Send to all:
```bash
curl --request POST \
  --url http://localhost:8123/api/services/notify/notify \
  --header 'Authorization: Bearer YOUR-TOKEN' \
  --header 'Content-Type: application/json' \
  --data '{ "title": "Test title", "message": "Test message" }'
```

Change `http://localhost:8123` to match your Home Assistant install domain, `mobile_app_pixel_3` to match your mobiles name and `YOUR-TOKEN` to be the Long-Lived Access Token. This is basically what the notification plugin does under the hood.

You can also import the cURL request into [Postman](https://www.postman.com/) or [Insomnia](https://insomnia.rest/) to more easily debug it.

If that doesn't work, it might be worth checking what data the Home Assistant websocket sent in the DevTools, as perhaps the mobile name/notification service is different to what appears in the UI:

![Screenshot from 2022-10-12 15-24-46](https://user-images.githubusercontent.com/144435/195371171-dc3785e2-f44a-4b08-b9ba-c5f389195b83.png)

Also check under Settings > Devices to make sure that your mobile not disabled:

![Screenshot from 2022-10-12 15-31-33](https://user-images.githubusercontent.com/144435/195371296-441f4850-816c-4541-8203-a640d7577f37.png)

**Comment by nickm324** [comment]
Using curl works fine. I get the test message on my mobile device without issue. The only time it fails is when I use the test feature in Kuma and even if I ignore the error and save anyway, I never get any notifications from Kuma even when I manually take one of my services down.

Below is the curl I ran minus my token.

curl --request POST \
  --url https://ha.myrealdomainhidden.com/api/services/notify/mobile_app_sm_g928v \
  --header 'Authorization: Bearer XXX' \
  --header 'Content-Type: application/json' \
  --data '{ "title": "Test title", "message": "Test message" }'

**Comment by rmtsrc** [comment]
Interesting, so sounds like it should work then.

Could you try replacing `notification-providers/home-assistant.js` with this version that has extra logging around the part axios post that sends and receives the response:

```js
const NotificationProvider = require('./notification-provider');
const axios = require('axios');

const defaultNotificationService = 'notify';

class HomeAssistant extends NotificationProvider {
  name = 'HomeAssistant';

  async send(notification, message, monitor = null, heartbeat = null) {
    const notificationService =
      notification?.notificationService || defaultNotificationService;

    try {
      const url = `${notification.homeAssistantUrl}/api/services/notify/${notificationService}`;
      const data = {
        title: 'Uptime Kuma',
        message,
        ...(notificationService !== 'persistent_notification' && {
          data: {
            name: monitor?.name,
            status: heartbeat?.status,
          },
        }),
      };
      const config = {
        headers: {
          Authorization: `Bearer ${notification.longLivedAccessToken}`,
          'Content-Type': 'application/json',
        },
      };

      console.log(
        '---HA Post:',
        JSON.stringify({ url, data, config }, null, 2)
      );

      const response = await axios.post(url, data, config);
      console.log('---HA Response:', response);

      return 'Sent Successfully.';
    } catch (error) {
      console.log('---HA Error:', error);
      this.throwGeneralAxiosError(error);
    }
  }
}

module.exports = HomeAssistant;
```

You'd need to stop uptime-kuma and restart it with:

```bash
sudo docker run \
  --name uptime-kuma \
  --net=host \
  -v /home/pi/uptime-kuma/data:/app/data \
  -v /etc/localtime:/etc/localtime:ro \
  -v /home/pi/uptime-kuma/home-assistant.js:/app/server/notification-providers/home-assistant.js \
  --restart=unless-stopped \
  --privileged \
  docker.io/louislam/uptime-kuma:1
```

Updating the `/home/pi/uptime-kuma` paths to match where it's located on your server.

Then check the logs after you've pressed Test. This is what I get, followed by the notification on my phone:

```
---HA Post: {
  "url": "http://localhost:8123/api/services/notify/mobile_app_pixel_3",
  "data": {
    "title": "Uptime Kuma",
    "message": "Home Assistant Alert Testing",
    "data": {}
  },
  "config": {
    "headers": {
      "Authorization": "Bearer XXXX",
      "Content-Type": "application/json"
    }
  }
}
---HA Response: {
  status: 200,
  statusText: 'OK',
  headers: {
    'content-type': 'application/json',
    'content-length': '2',
    date: 'Thu, 13 Oct 2022 11:11:09 GMT',
    server: 'Python/3.10 aiohttp/3.8.1',
    connection: 'close'
  },
  config: {
    transitional: {
      silentJSONParsing: true,
      forcedJSONParsing: true,
      clarifyTimeoutError: false
    },
    adapter: [Function: httpAdapter],
    transformRequest: [ [Function: transformRequest] ],
    transformResponse: [ [Function: transformResponse] ],
    timeout: 0,
    xsrfCookieName: 'XSRF-TOKEN',
    xsrfHeaderName: 'X-XSRF-TOKEN',
    maxContentLength: -1,
    maxBodyLength: -1,
    env: { FormData: [Function] },
    validateStatus: [Function: validateStatus],
    headers: {
      Accept: 'application/json, text/plain, */*',
      'Content-Type': 'application/json',
      Authorization: 'Bearer XXXX',
      'User-Agent': 'axios/0.27.2',
      'Content-Length': 74
    },
    method: 'post',
    url: 'http://localhost:8123/api/services/notify/mobile_app_pixel_3',
    data: '{"title":"Uptime Kuma","message":"Home Assistant Alert Testing","data":{}}'
  },
  request: <ref *1> ClientRequest {
    _events: [Object: null prototype] {
      abort: [Function (anonymous)],
      aborted: [Function (anonymous)],
      connect: [Function (anonymous)],
      error: [Function (anonymous)],
      socket: [Function (anonymous)],
      timeout: [Function (anonymous)],
      prefinish: [Function: requestOnPrefinish]
    },
    _eventsCount: 7,
    _maxListeners: undefined,
    outputData: [],
    outputSize: 0,
    writable: true,
    destroyed: false,
    _last: true,
    chunkedEncoding: false,
    shouldKeepAlive: false,
    maxRequestsOnConnectionReached: false,
    _defaultKeepAlive: true,
    useChunkedEncodingByDefault: true,
    sendDate: false,
    _removedConnection: false,
    _removedContLen: false,
    _removedTE: false,
    _contentLength: null,
    _hasBody: true,
    _trailer: '',
    finished: true,
    _headerSent: true,
    _closed: false,
    socket: Socket {
      connecting: false,
      _hadError: false,
      _parent: null,
      _host: 'localhost',
      _readableState: [ReadableState],
      _events: [Object: null prototype],
      _eventsCount: 7,
      _maxListeners: undefined,
      _writableState: [WritableState],
      allowHalfOpen: false,
      _sockname: null,
      _pendingData: null,
      _pendingEncoding: '',
      server: null,
      _server: null,
      parser: null,
      _httpMessage: [Circular *1],
      [Symbol(async_id_symbol)]: 724,
      [Symbol(kHandle)]: [TCP],
      [Symbol(lastWriteQueueSize)]: 0,
      [Symbol(timeout)]: null,
      [Symbol(kBuffer)]: null,
      [Symbol(kBufferCb)]: null,
      [Symbol(kBufferGen)]: null,
      [Symbol(kCapture)]: false,
      [Symbol(kSetNoDelay)]: false,
      [Symbol(kSetKeepAlive)]: true,
      [Symbol(kSetKeepAliveInitialDelay)]: 60,
      [Symbol(kBytesRead)]: 0,
      [Symbol(kBytesWritten)]: 0,
      [Symbol(RequestTimeout)]: undefined
    },
    _header: 'POST /api/services/notify/mobile_app_pixel_3 HTTP/1.1\r\n' +
      'Accept: application/json, text/plain, */*\r\n' +
      'Content-Type: application/json\r\n' +
      'Authorization: Bearer XXXX\r\n' +
      'User-Agent: axios/0.27.2\r\n' +
      'Content-Length: 74\r\n' +
      'Host: localhost:8123\r\n' +
      'Connection: close\r\n' +
      '\r\n',
    _keepAliveTimeout: 0,
    _onPendingData: [Function: nop],
    agent: Agent {
      _events: [Object: null prototype],
      _eventsCount: 2,
      _maxListeners: undefined,
      defaultPort: 80,
      protocol: 'http:',
      options: [Object: null prototype],
      requests: [Object: null prototype] {},
      sockets: [Object: null prototype],
      freeSockets: [Object: null prototype] {},
      keepAliveMsecs: 1000,
      keepAlive: false,
      maxSockets: Infinity,
      maxFreeSockets: 256,
      scheduling: 'lifo',
      maxTotalSockets: Infinity,
      totalSocketCount: 1,
      createConnection: [Function (anonymous)],
      [Symbol(kCapture)]: false,
      [Symbol(cacheableLookupCreateConnection)]: [Function: connect],
      [Symbol(cacheableLookupInstance)]: [CacheableLookup]
    },
    socketPath: undefined,
    method: 'POST',
    maxHeaderSize: undefined,
    insecureHTTPParser: undefined,
    path: '/api/services/notify/mobile_app_pixel_3',
    _ended: true,
    res: IncomingMessage {
      _readableState: [ReadableState],
      _events: [Object: null prototype],
      _eventsCount: 4,
      _maxListeners: undefined,
      socket: [Socket],
      httpVersionMajor: 1,
      httpVersionMinor: 1,
      httpVersion: '1.1',
      complete: true,
      rawHeaders: [Array],
      rawTrailers: [],
      aborted: false,
      upgrade: false,
      url: '',
      method: null,
      statusCode: 200,
      statusMessage: 'OK',
      client: [Socket],
      _consuming: true,
      _dumped: false,
      req: [Circular *1],
      responseUrl: 'http://localhost:8123/api/services/notify/mobile_app_pixel_3',
      redirects: [],
      [Symbol(kCapture)]: false,
      [Symbol(kHeaders)]: [Object],
      [Symbol(kHeadersCount)]: 10,
      [Symbol(kTrailers)]: null,
      [Symbol(kTrailersCount)]: 0,
      [Symbol(RequestTimeout)]: undefined
    },
    aborted: false,
    timeoutCb: null,
    upgradeOrConnect: false,
    parser: null,
    maxHeadersCount: null,
    reusedSocket: false,
    host: 'localhost',
    protocol: 'http:',
    _redirectable: Writable {
      _writableState: [WritableState],
      _events: [Object: null prototype],
      _eventsCount: 3,
      _maxListeners: undefined,
      _options: [Object],
      _ended: true,
      _ending: true,
      _redirectCount: 0,
      _redirects: [],
      _requestBodyLength: 74,
      _requestBodyBuffers: [],
      _onNativeResponse: [Function (anonymous)],
      _currentRequest: [Circular *1],
      _currentUrl: 'http://localhost:8123/api/services/notify/mobile_app_pixel_3',
      [Symbol(kCapture)]: false
    },
    [Symbol(kCapture)]: false,
    [Symbol(kNeedDrain)]: false,
    [Symbol(corked)]: 0,
    [Symbol(kOutHeaders)]: [Object: null prototype] {
      accept: [Array],
      'content-type': [Array],
      authorization: [Array],
      'user-agent': [Array],
      'content-length': [Array],
      host: [Array]
    },
    [Symbol(kUniqueHeaders)]: null
  },
  data: []
}
```

**Comment by nickm324** [comment]
---HA Post: {
  "url": "https://ha.thinkdevtech.com/api/services/notify/ mobile_app_sm_g928v",
  "data": {
    "title": "Uptime Kuma",
    "message": "Uptime Kuma Alert Testing",
    "data": {}
  },
  "config": {
    "headers": {
      "Authorization": "Bearer REMOVED",
      "Content-Type": "application/json"
    }
  }
}
---HA Error: [AxiosError: Request failed with status code 400] {
  code: 'ERR_BAD_REQUEST',
  config: {
    transitional: {
      silentJSONParsing: true,
      forcedJSONParsing: true,
      clarifyTimeoutError: false
    },
    adapter: [Function: httpAdapter],
    transformRequest: [ [Function: transformRequest] ],
    transformResponse: [ [Function: transformResponse] ],
    timeout: 0,
    xsrfCookieName: 'XSRF-TOKEN',
    xsrfHeaderName: 'X-XSRF-TOKEN',
    maxContentLength: -1,
    maxBodyLength: -1,
    env: { FormData: [Function] },
    validateStatus: [Function: validateStatus],
    headers: {
      Accept: 'application/json, text/plain, */*',
      'Content-Type': 'application/json',
      Authorization: 'Bearer REMOVED',
      'User-Agent': 'axios/0.27.2',
      'Content-Length': 71
    },
    method: 'post',
Error: Error: AxiosError: Request failed with status code 400 400: Bad Request
    at HomeAssistant.throwGeneralAxiosError (/app/server/notification-providers/notification-provider.js:38:15)
    at HomeAssistant.send (/app/server/notification-providers/home-assistant.js:43:12)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Socket.<anonymous> (/app/server/server.js:1150:27)
    url: 'https://ha.thinkdevtech.com/api/services/notify/ mobile_app_sm_g928v',
    data: '{"title":"Uptime Kuma","message":"Uptime Kuma Alert Testing","data":{}}'
  },
  request: <ref *1> ClientRequest {
    _events: [Object: null prototype] {
      abort: [Function (anonymous)],
      aborted: [Function (anonymous)],
      connect: [Function (anonymous)],
      error: [Function (anonymous)],
      socket: [Function (anonymous)],
      timeout: [Function (anonymous)],
      prefinish: [Function: requestOnPrefinish]
    },
    _eventsCount: 7,
    _maxListeners: undefined,
    outputData: [],
    outputSize: 0,
    writable: true,
    destroyed: false,
    _last: true,
    chunkedEncoding: false,
    shouldKeepAlive: false,
    maxRequestsOnConnectionReached: false,
    _defaultKeepAlive: true,
    useChunkedEncodingByDefault: true,
    sendDate: false,
    _removedConnection: false,
    _removedContLen: false,
    _removedTE: false,
    _contentLength: null,
    _hasBody: true,
    _trailer: '',
    finished: true,
    _headerSent: true,
    _closed: false,
    socket: TLSSocket {
      _tlsOptions: [Object],
      _secureEstablished: true,
      _securePending: false,
      _newSessionPending: false,
      _controlReleased: true,
      secureConnecting: false,
      _SNICallback: null,
      servername: 'ha.thinkdevtech.com',
      alpnProtocol: false,
      authorized: true,
      authorizationError: null,
      encrypted: true,
      _events: [Object: null prototype],
      _eventsCount: 10,
      connecting: false,
      _hadError: false,
      _parent: null,
      _host: 'ha.thinkdevtech.com',
      _readableState: [ReadableState],
      _maxListeners: undefined,
      _writableState: [WritableState],
      allowHalfOpen: false,
      _sockname: null,
      _pendingData: null,
      _pendingEncoding: '',
      server: undefined,
      _server: null,
      ssl: [TLSWrap],
      _requestCert: true,
      _rejectUnauthorized: true,
      parser: null,
      _httpMessage: [Circular *1],
      [Symbol(res)]: [TLSWrap],
      [Symbol(verified)]: true,
      [Symbol(pendingSession)]: null,
      [Symbol(async_id_symbol)]: 6188,
      [Symbol(kHandle)]: [TLSWrap],
      [Symbol(lastWriteQueueSize)]: 0,
      [Symbol(timeout)]: null,
      [Symbol(kBuffer)]: null,
      [Symbol(kBufferCb)]: null,
      [Symbol(kBufferGen)]: null,
      [Symbol(kCapture)]: false,
      [Symbol(kSetNoDelay)]: false,
      [Symbol(kSetKeepAlive)]: true,
      [Symbol(kSetKeepAliveInitialDelay)]: 60,
      [Symbol(kBytesRead)]: 0,
      [Symbol(kBytesWritten)]: 0,
      [Symbol(connect-options)]: [Object],
      [Symbol(RequestTimeout)]: undefined
    },
    _header: 'POST /api/services/notify/%20mobile_app_sm_g928v HTTP/1.1\r\n' +
      'Accept: application/json, text/plain, */*\r\n' +
      'Content-Type: application/json\r\n' +
      'Authorization: BearerREMOVED' +
      'User-Agent: axios/0.27.2\r\n' +
      'Content-Length: 71\r\n' +
      'Host: ha.thinkdevtech.com\r\n' +
      'Connection: close\r\n' +
      '\r\n',
    _keepAliveTimeout: 0,
    _onPendingData: [Function: nop],
    agent: Agent {
      _events: [Object: null prototype],
      _eventsCount: 2,
      _maxListeners: undefined,
      defaultPort: 443,
      protocol: 'https:',
      options: [Object: null prototype],
      requests: [Object: null prototype] {},
      sockets: [Object: null prototype],
      freeSockets: [Object: null prototype] {},
      keepAliveMsecs: 1000,
      keepAlive: false,
      maxSockets: Infinity,
      maxFreeSockets: 256,
      scheduling: 'lifo',
      maxTotalSockets: Infinity,
      totalSocketCount: 1,
      maxCachedSessions: 100,
      _sessionCache: [Object],
      createConnection: [Function (anonymous)],
      [Symbol(kCapture)]: false,
      [Symbol(cacheableLookupCreateConnection)]: [Function: createConnection],
      [Symbol(cacheableLookupInstance)]: [CacheableLookup]
    },
    socketPath: undefined,
    method: 'POST',
    maxHeaderSize: undefined,
    insecureHTTPParser: undefined,
    path: '/api/services/notify/%20mobile_app_sm_g928v',
    _ended: true,
    res: IncomingMessage {
      _readableState: [ReadableState],
      _events: [Object: null prototype],
      _eventsCount: 4,
      _maxListeners: undefined,
      socket: [TLSSocket],
      httpVersionMajor: 1,
      httpVersionMinor: 1,
      httpVersion: '1.1',
      complete: true,
      rawHeaders: [Array],
      rawTrailers: [],
      aborted: false,
      upgrade: false,
      url: '',
      method: null,
      statusCode: 400,
      statusMessage: 'Bad Request',
      client: [TLSSocket],
      _consuming: false,
      _dumped: false,
      req: [Circular *1],
      responseUrl: 'https://ha.thinkdevtech.com/api/services/notify/%20mobile_app_sm_g928v',
      redirects: [],
      [Symbol(kCapture)]: false,
      [Symbol(kHeaders)]: [Object],
      [Symbol(kHeadersCount)]: 20,
      [Symbol(kTrailers)]: null,
      [Symbol(kTrailersCount)]: 0,
      [Symbol(RequestTimeout)]: undefined
    },
    aborted: false,
    timeoutCb: null,
    upgradeOrConnect: false,
    parser: null,
    maxHeadersCount: null,
    reusedSocket: false,
    host: 'ha.thinkdevtech.com',
    protocol: 'https:',
    _redirectable: Writable {
      _writableState: [WritableState],
      _events: [Object: null prototype],
      _eventsCount: 3,
      _maxListeners: undefined,
      _options: [Object],
      _ended: true,
      _ending: true,
      _redirectCount: 0,
      _redirects: [],
      _requestBodyLength: 71,
      _requestBodyBuffers: [],
      _onNativeResponse: [Function (anonymous)],
      _currentRequest: [Circular *1],
      _currentUrl: 'https://ha.thinkdevtech.com/api/services/notify/%20mobile_app_sm_g928v',
      [Symbol(kCapture)]: false
    },
    [Symbol(kCapture)]: false,
    [Symbol(kNeedDrain)]: false,
    [Symbol(corked)]: 0,
    [Symbol(kOutHeaders)]: [Object: null prototype] {
      accept: [Array],
      'content-type': [Array],
      authorization: [Array],
      'user-agent': [Array],
      'content-length': [Array],
      host: [Array]
    },
    [Symbol(kUniqueHeaders)]: null
  },
  response: {
    status: 400,
    statusText: 'Bad Request',
    headers: {
      date: 'Thu, 13 Oct 2022 11:45:47 GMT',
      'content-type': 'text/plain; charset=utf-8',
      'content-length': '16',
      connection: 'close',
      'cf-cache-status': 'DYNAMIC',
      'report-to': '{"endpoints":[{"url":"https:\\/\\/a.nel.cloudflare.com\\/report\\/v3?s=lm%2FkEpEVfWYn8tuAmlXv4UlfiOctBwrBNy%2ByI%2FJwyfg%2BTuSGG2JSU5uwhHCzribmKMIeiJOIJseOvb8TL77OggoqEHuQjr5hWYGOck5ndfp7%2Bix007deNfBCE59T4xMeYNDplbF5"}],"group":"cf-nel","max_age":604800}',
      nel: '{"success_fraction":0,"report_to":"cf-nel","max_age":604800}',
      server: 'cloudflare',
      'cf-ray': '7597d4bf5e44ad1b-ATL',
      'alt-svc': 'h3=":443"; ma=86400, h3-29=":443"; ma=86400'
    },
    config: {
      transitional: [Object],
      adapter: [Function: httpAdapter],
      transformRequest: [Array],
      transformResponse: [Array],
      timeout: 0,
      xsrfCookieName: 'XSRF-TOKEN',
      xsrfHeaderName: 'X-XSRF-TOKEN',
      maxContentLength: -1,
      maxBodyLength: -1,
      env: [Object],
      validateStatus: [Function: validateStatus],
      headers: [Object],
      method: 'post',
      url: 'https://ha.thinkdevtech.com/api/services/notify/ mobile_app_sm_g928v',
      data: '{"title":"Uptime Kuma","message":"Uptime Kuma Alert Testing","data":{}}'
    },
    request: <ref *1> ClientRequest {
      _events: [Object: null prototype],
      _eventsCount: 7,
      _maxListeners: undefined,
      outputData: [],
      outputSize: 0,
      writable: true,
      destroyed: false,
      _last: true,
      chunkedEncoding: false,
      shouldKeepAlive: false,
      maxRequestsOnConnectionReached: false,
      _defaultKeepAlive: true,
      useChunkedEncodingByDefault: true,
      sendDate: false,
      _removedConnection: false,
      _removedContLen: false,
      _removedTE: false,
      _contentLength: null,
      _hasBody: true,
      _trailer: '',
      finished: true,
      _headerSent: true,
      _closed: false,
      socket: [TLSSocket],
      _header: 'POST /api/services/notify/%20mobile_app_sm_g928v HTTP/1.1\r\n' +
        'Accept: application/json, text/plain, */*\r\n' +
        'Content-Type: application/json\r\n' +
        'Authorization: Bearer REMOVED' +
        'User-Agent: axios/0.27.2\r\n' +
        'Content-Length: 71\r\n' +
        'Host: ha.thinkdevtech.com\r\n' +
        'Connection: close\r\n' +
        '\r\n',
      _keepAliveTimeout: 0,
      _onPendingData: [Function: nop],
      agent: [Agent],
      socketPath: undefined,
      method: 'POST',
      maxHeaderSize: undefined,
      insecureHTTPParser: undefined,
      path: '/api/services/notify/%20mobile_app_sm_g928v',
      _ended: true,
      res: [IncomingMessage],
      aborted: false,
      timeoutCb: null,
      upgradeOrConnect: false,
      parser: null,
      maxHeadersCount: null,
      reusedSocket: false,
      host: 'ha.thinkdevtech.com',
      protocol: 'https:',
      _redirectable: [Writable],
      [Symbol(kCapture)]: false,
      [Symbol(kNeedDrain)]: false,
      [Symbol(corked)]: 0,
      [Symbol(kOutHeaders)]: [Object: null prototype],
      [Symbol(kUniqueHeaders)]: null
    },
    data: '400: Bad Request'

**Comment by louislam** [comment]
> "url": "https://ha.thinkdevtech.com/api/services/notify/ mobile_app_sm_g928v",

Haha, my eagle eye👀:

Please delete the space letter before `mobile_app_sm_g928v` and try again.

**Comment by nickm324** [comment]
What the hell! That was it.  I'm not sure how I didn't find that before posting, I must have tried this 1000 times before opening this issue.

Thanks for you help.

**Comment by louislam** [comment]
I should asked you to provide the actual reproduction steps too. 

Thanks @rmtsrc's help.

Close as resolved.
