### ISSUE TITLE
Reverse Proxy which way to add domain link

### ISSUE THREAD

**Issue by ShadowGaming100** [louislam/uptime-kuma#2215]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

In reverse proxy Https-Portal
How should I add the domain
xuptime1.shadow100.repl.co or
https://xuptime1.shadow100.repl.co

this is a sub-domain

### 🐻 Uptime-Kuma Version

1.18.5

### 💻 Operating System and Arch

Linix

### 🌐 Browser

Chrome Latest

### 🟩 NodeJS Version

Latest

**Comment by rezzorix** [comment]
Do I understand it right: you run uptime-kuma (non-docker) on replit.com?
You already have this subdomain... what you wanna achieve?
In what "reverse proxy Https-Portal"?
Which reverse proxy are you using?

**Comment by rezzorix** [comment]
Well, to help you, you would need to give some more information first e.g. answer the questions.

**Comment by ShadowGaming100** [comment]
Https-Portal

**Comment by ShadowGaming100** [comment]
Hello
