### ISSUE TITLE
Brother scanner offline while webpage is reachable

### ISSUE THREAD

**Issue by tomdh76** [louislam/uptime-kuma#2216]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

I am just starting with Uptime Kuma and try to see whether my brother scanner is online using internal website:

http://192.168.2.18/EWS/general/status.html

I tried HTTP setting with this address and all possible response codes 200-500 but it keeps being offline:

![Schermafbeelding 2022-10-10 210835](https://user-images.githubusercontent.com/42240927/194937173-8b5e541d-c9be-49b4-a5b3-e3cc9b89c622.png)

But if i click on the link in kuma it directs me to the website. Any idea?

### 🐻 Uptime-Kuma Version

1.18.4

### 💻 Operating System and Arch

LXC container on proxmox

### 🌐 Browser

edge

**Comment by tomdh76** [comment]
connect EHOSTUNREACH 192.168.2.18:80

Which is strange because the website can be reached...

**Comment by Computroniks** [comment]
This looks like a local network issue. Are you sure that you can reach the server from the server running uptime kuma. It could be the case that you can reach the site from your desktop but the server can't reach it. This could be caused by the two being on different subnets/VLANs or other local network issues.

**Comment by tomdh76** [comment]
I tried in the lxc container in proxmox to use curl:

curl http://192.168.2.18/EWS/general/reflesh.html

then I get:

Failed to connect to 192.168.2.18 port 80: No route to host

So you are right I think... No idea why there is no route...

If I use for example curl for my wireguard dashboard it works:

curl http://192.168.2.23:10086/

Could it be a firewall issue?

**Comment by Computroniks** [comment]
Not sure, without knowing your internal network topology I couldn't say. Firewall would probably be most likely in a simple network so I would check that first but it could also be something to do with proxmox

**Comment by tomdh76** [comment]
Okay thx, I will try and investigate further

**Comment by tomdh76** [comment]
I found it already, the brother scanner had a setting for ip filtering for access. I added the uptima kuma IP and it now shows being online. Thx @Computroniks to point me in the right direction

**Comment by louislam** [comment]
Close as resolved.
