### ISSUE TITLE
docker-compose.yml changes 

### ISSUE THREAD

**Issue by ShadowGaming100** [louislam/uptime-kuma#2219]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### Description

Every time I update uptime-kuma docker-compose change to the original file

### 👟 Reproduction steps

1. cd XUptime
2. git fetch --all
3. git checkout 1.18.4 --force
4. npm install --production
5. npm run download-dist
6. restart it (stop running then running it again using command)

### 👀 Expected behavior

Doesn’t change 

### 😓 Actual Behavior

It changes 

### 🐻 Uptime-Kuma Version

1.18.4

### 💻 Operating System and Arch

Linix

### 🌐 Browser

Chrome

### 🟩 NodeJS Version

Latest

**Comment by ShadowGaming100** [comment]
I know there is a new update I have to update it tomorrow

**Comment by louislam** [comment]
Expected result.

**Comment by ShadowGaming100** [comment]
> Expected result.

??
