### ISSUE TITLE
Custom HTTP_USER_AGENT/HTTP_REFERER per monitor

### ISSUE THREAD

**Issue by RixzZ** [louislam/uptime-kuma#222]
**Is it a duplicate question?**
No.

**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
Allow to set a custom user-agent and referrer for each monitor.

In my use case I have an image CDN that filters image loading by referer. If you access it without a referer or not the correct one, you get redirected to the homepage.

**Describe alternatives you've considered**
Currently I can only use Uptime Kuma to test for a 302 (the redirection that happens when you fail the referer check), but I can't check any other condition.

**Additional context**
N/A

**Comment by louislam** [comment]
I believe it is covered by #11.

**Comment by RixzZ** [comment]
You're completely right. I searched for those specific headers, so I didn't fine that issue. Sorry.
