### ISSUE TITLE
no push Monitor visible on /metrics

### ISSUE THREAD

**Issue by wahe** [louislam/uptime-kuma#2220]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### Description

Hai,
on the mydomain.xx/metrics page only incomplete (or none) PUSH entries are displayed. Out of 7 entries, sometimes only 3 are displayed. After Docker restart currently no entries. 
On the page the PUSH messages work perfectly.

Thank you

### 👟 Reproduction steps

new kvm with docker debian setup (docker run -d --restart=always -p 3001:3001 -v uptime-kuma:/app/data --name uptime-kuma louislam/uptime-kuma:1) and caddy 

Prometheus 
monitor_status{instance="xxxxxx", job="uptime", monitor_hostname="null", monitor_name="xxxxx", monitor_port="null", monitor_type="push", monitor_url="https://"} 2

### 👀 Expected behavior

sorry no example available from /metrics

### 😓 Actual Behavior

no PUSH on /metrics

### 🐻 Uptime-Kuma Version

1.18.5

### 💻 Operating System and Arch

Debian 5.10.140-1 (2022-09-02) x86_64 GNU/Linux

### 🌐 Browser

Firefox 105.0.3 (64-Bit)

### 🐋 Docker Version

Docker Engine - Community 20.10.18

### 🟩 NodeJS Version

-

**Comment by wahe** [comment]
Hi,
i suspect that this message will be displayed if the monitor with the D 84 has never been called. The message does not appear later (docker logs uptime-kuma).
```
Trace: [Error: insert into `heartbeat` (`down_count`, `duration`, `important`, `monitor_id`, `msg`, `status`, `time`) values (0, 0, true, 84, 'No heartbeat in the time window', 0, '2022-10-11 17:45:29.110') - SQLITE_CONSTRAINT: FOREIGN KEY constraint failed] {
  errno: 19,
  code: 'SQLITE_CONSTRAINT'
}
    at safeBeat (/app/server/model/monitor.js:660:25)
2022-10-11T17:45:29.131Z [MONITOR] ERROR: Please report to https://github.com/louislam/uptime-kuma/issues
2022-10-11T17:45:38.881Z [MONITOR] WARN: Monitor #84 'test_push_2_1': Failing: No heartbeat in the time window | Interval: 60 seconds | Type: push | Down Count: 0 | Resend Interval: 2
Trace: [Error: insert into `heartbeat` (`down_count`, `duration`, `important`, `monitor_id`, `msg`, `status`, `time`) values (0, 0, true, 84, 'No heartbeat in the time window', 0, '2022-10-11 17:45:38.880') - SQLITE_CONSTRAINT: FOREIGN KEY constraint failed] {
  errno: 19,
  code: 'SQLITE_CONSTRAINT'
}
    at safeBeat (/app/server/model/monitor.js:660:25)
```

**Comment by rezzorix** [comment]
Tried to replicate as below and got the following result:
A push monitor will only show in metrics if at least 1 cycle / interval (up / down) has been completed.

If someone wants to replicate that, too:
- setup a push monitor (do not call the URL, yet)
- open metrics, search for your monitor -> you will not find it
- open the push-url & search again on metrics page -> it will still not be there
- wait for the interval to mark it as down again & search again in metrics -> it will show up

**Comment by wahe** [comment]
Hi rezzorix,

> Tried to replicate as below and got the following result: A push monitor will only show in metrics if at least 1 cycle / interval (up / down) has been completed.
> 
> If someone wants to replicate that, too:
> 
>     * setup a push monitor (do not call the URL, yet)
setup: test_push_5
> 
>     * open metrics, search for your monitor -> you will not find it
> 
/metrics
monitor_status{monitor_name="test_push_5",monitor_type="push",monitor_url="https://",monitor_hostname="null",monitor_port="null"} 0

prometheus
monitor_status{monitor_type="push"}
monitor_status{instance="waer.li:80", job="uptime", monitor_hostname="null", monitor_name="test_push_5", monitor_port="null", monitor_type="push", monitor_url="https://"} 0

>     * open the push-url & search again on metrics page -> it will still not be there
> 
https://domain.tld/api/push/D967pquUa0?status=up&msg=OK&ping=
{"ok":true}

/metrics
monitor_response_time{monitor_name="test_push_5",monitor_type="push",monitor_url="https://",monitor_hostname="null",monitor_port="null"} -1

prometheus
monitor_status{instance="waer.li:80", job="uptime", monitor_hostname="null", monitor_name="test_push_5", monitor_port="null", monitor_type="push", monitor_url="https://"} | **2**

>     * wait for the interval to mark it as down again & search again in metrics -> it will show up
wait...
No heartbeat in the time window

the same as above

it seems that renaming causes another error
monitor_response_time{monitor_name="test_push_5_2",monitor_type="push",monitor_url="https://",monitor_hostname="null",monitor_port="null"} -1
monitor_response_time{monitor_name="test_push_5",monitor_type="push",monitor_url="https://",monitor_hostname="null",monitor_port="null"} -1
monitor_response_time{monitor_name="test_push_6",monitor_type="push",monitor_url="https://",monitor_hostname="null",monitor_port="null"} -1

after docker restart no PUSH in /metrics

sorry, I'm confused
Thank you

**Comment by wahe** [comment]
now 
monitor_status{monitor_name="test_push_6",monitor_type="push",monitor_url="https://",monitor_hostname="null",monitor_port="null"} 0
or
monitor_status{monitor_name="test_push_6",monitor_type="push",monitor_url="https://",monitor_hostname="null",monitor_port="null"} 2

all other 7 not displayed

**Comment by wahe** [comment]
Hallo,
after about 12 hours, the status messages appeared in the overview. However, the status is indicated by the number 2. I can live with that. Thank you

**Comment by wahe** [comment]
Sorry wanted to close it.

**Comment by wahe** [comment]
Hallo,
after about 12 hours, the status messages appeared in the overview. However, the status is indicated by the number 2. I can live with that. Thank you

**Comment by wahe** [comment]
Hallo,
after about 12 hours, the status messages appeared in the overview. However, the status is indicated by the number 2. I can live with that. Thank you
