### ISSUE TITLE
Strict MIME type error causes white page (nginx + cloudflare)

### ISSUE THREAD

**Issue by jojost1** [louislam/uptime-kuma#2221]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

When navigating to status.example.com, I see a completely white page with this error in the console:

Chrome:
`Failed to load module script: Expected a JavaScript module script but the server responded with a MIME type of "text/html". Strict MIME type checking is enforced for module scripts per HTML spec.`

Safari:
`Loading module from “https://status.example.com/assets/index.56b35390.js” was blocked because of a disallowed MIME type (“text/html”).`
&
`The stylesheet https://status.example.com/assets/index.43631e1a.css was not loaded because its MIME type, “text/html”, is not “text/css”.`

Opening `[IP]:3001/status/example`, the page does load correctly on both browsers.

I'm using cloudflare and nginx with the following config:

```
server {
    listen 80;
    listen [::]:80;
    server_name status.example.com;

    location / {
        proxy_pass http://127.0.0.1:3001/status/tsealink;
        proxy_http_version 1.1;
        proxy_set_header   Upgrade $http_upgrade;
        proxy_set_header   Connection "upgrade";
        proxy_set_header   Host $host;
    }

}
```

Anyone who can help me? Thanks!

### 🐻 Uptime-Kuma Version

1.18.5

### 💻 Operating System and Arch

Debian 11

### 🌐 Browser

Chrome, Safari, Firefox

### 🟩 NodeJS Version

14.18.1

**Comment by louislam** [comment]
It usually means that the assets files are missing. Please double check whether if you followed the installation guide and no error during it.

**Comment by jojost1** [comment]
@louislam No errors during installation, and considering this:

> Opening [IP]:3001/status/example, the page does load correctly on both browsers.

That couldn't be the issue, right? Everything works as expected when I use the IP.

**Comment by louislam** [comment]
> https://status.[REDACTED].link/assets/index.43631e1a.css

Is it your real domain? The css file is actually not accessible.

Also the top level favicon.ico is also not accessible.

You should try to bypass cloudflare first, see if it is caused by it.

**Comment by jojost1** [comment]
@louislam hmm even when pausing Cloudflare entirely, I'm still getting the error. Makes me wonder if it's anything to do with nginx (see original post).

[IP]:3001/assets/index.43631e1a.css and [IP]:3001/assets/index.56b35390.js do load.

**Comment by louislam** [comment]
>  proxy_pass http://127.0.0.1:3001/status/tsealink;

Just noticed, it should be `http://127.0.0.1:3001`

Reference:
https://github.com/louislam/uptime-kuma/wiki/Reverse-Proxy#nginx

Btw remember to delete edit history.

**Comment by jojost1** [comment]
That seems to work! It opens the login page now when I go to `status.example.com` 😄 thank you!

Is it possible to directly show /status/tsealink when going to the domain, instead of the login page?

**Comment by louislam** [comment]
Yes, see https://github.com/louislam/uptime-kuma/wiki/Status-Page#domain-names-for-status-pages

Close as resolved.

**Comment by jojost1** [comment]
You're great!
