### ISSUE TITLE
Autocompletion Password Manager

### ISSUE THREAD

**Issue by Nollknolle** [louislam/uptime-kuma#2227]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### Description

When I am using my password manager to fill my login data, then I get every time the message that my credentials are wrong.
When I type the exact credentials manually, then it works.

### 👟 Reproduction steps

Fill your credentials automatic via your password manager.

### 👀 Expected behavior

User get logged in.

### 😓 Actual Behavior

Get an error message that the credentials are wrong.

### 🐻 Uptime-Kuma Version

1.18.5

### 💻 Operating System and Arch

Raspbian Arch64

### 🌐 Browser

Firefox 105.0.3

### 🐋 Docker Version

Docker 20.10.5+dfsg1

**Comment by louislam** [comment]
Firefox's password manager?

**Comment by louislam** [comment]
Cannot reproduce.

- (Working) Firefox 105.0.3 on Windows
- (Working) Firefox ESR 91.13.0 on Raspbian (32bit)
- (Working) Firefox for Android 105.2.0

And I think it is just two very simple <input> html tags, nothing can be fixed. I assume that it is a problem of your side. I change it to `help`.

**Comment by Nollknolle** [comment]
Bitwarden is my password manager.

**Comment by Nollknolle** [comment]
> Cannot reproduce.
> 
> 
> 
> - (Working) Firefox 105.0.3 on Windows
> 
> - (Working) Firefox ESR 91.13.0 on Raspbian (32bit)
> 
> - (Working) Firefox for Android 105.2.0
> 
> 
> 
> And I think it is just two very simple <input> html tags, nothing can be fixed. I assume that it is a problem of your side. I change it to `help`.

I can show you the problem if you want.

**Comment by louislam** [comment]
Also cannot reproduce using Bitwarden.

Please check using Developer Tools, you can see what data sent to your server here.

![image](https://user-images.githubusercontent.com/1336778/196028545-e43ade11-c7b5-4814-9b01-d62ed05251b1.png)

**Comment by Nollknolle** [comment]
> ![grafik](https://user-images.githubusercontent.com/62543404/196029757-c124f9e8-e0c0-4c22-a07d-caf1241684a5.png) that is request if my pw manager fill it and i click login

the password is correct

**Comment by louislam** [comment]
It sounds weird, because the client is sending the same data to the server and only reject Bitwarden one.

Copy and paste this line in the text editor.
And then type the password manually, and also copy an paste the line in the same text editor.
Try to compare two lines, check whether they are 100% match using tools.

If they are matched, I honestly don't know what is happening.
