### ISSUE TITLE
Sending "I'm alive message" - get health status from other uptime-kuma instances

### ISSUE THREAD

**Issue by MajorTomDE** [louislam/uptime-kuma#2230]
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

Other

### 🔖 Feature description

I'm running two linux servers: One within my private LAN and one "public" one the internet.

My challenge is to know the health of my LAN uptime-kuma without VPN Connection.
Public uptime kuma has no access to LAN uptime kuma.

 

### ✔️ Solution

How about to implement a "I'm alive" function?

uptime-kuma is calling a URL (e.g. the uptime-kuma push url) all x seconds and reports his alive status.

**Comment by rezzorix** [comment]
Have you considered something like this:
https://github.com/louislam/uptime-kuma/wiki/Prometheus-Integration ?

**Comment by MajorTomDE** [comment]
I played with Prometheus over the weekend and it is too "big" for my purposes.

The easiest way for my scenario would be an option in uptime kuma to send a "I'm alive message" ... Also to run a URL

**Comment by kevingruesser** [comment]
That's exactly what I need too.

A reversed push monitoring runs on the public server and a push alarm is sent on the private server if a service cannot be reached.

**Comment by whgDosumi** [comment]
Just chiming in and saying I'd like this feature. I use a cloud hosted uptime kuma but some of the services I'd like to monitor are private, and I'd rather not give the remote server access to the internal network. 

To work around this, I just set up a "push" monitor in uptime kuma, and set up a cron job internally to monitor the services and call the monitor url if successful. Using Uptime Kuma to set up the monitors would be easier than this, but it gets the job done for me.

**Comment by MajorTomDE** [comment]
@kevingruesser @whgDosumi 
Thanks for your answers. I tried the last months a few "workarounds", e.g. with cronjobs.
But this is not really comfortable.
Unfortunately I am not a developer, otherwise I would create a pull request myself.

For me the easiest solution would be a new function in the settings: 
"Call" I'm Alive URL:
1. Active Yes/No
2. URL
3. Seconds

Function: When active, Uptime Kuma "calls" all x seconds the URL. Thats it ;-)
