### ISSUE TITLE
Display further information from Linux Servers (CPU Load, Memory Load, Temperature)

### ISSUE THREAD

**Issue by MajorTomDE** [louislam/uptime-kuma#2231]
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

Other

### 🔖 Feature description

I know, uptime-kuma is made to check the uptime and not to be a server monitoring tool.

But how about displaying at least base metrics like CPU Load, Memory Load and Temperature? Not historical, only the latest values.

### ✔️ Solution

For me it would be sufficient if the monitor type "push" can be extended.

Sending a string within the url and display the content of the string within the dashboard and status page.

So I can create a little bash script that collects all the relevant data, creates a string and send it within the push url:
e.g. "CPU Load: 20 % / MEM Load: 40 % / CPU Temp: 40 degrees"

The content of the string should be displayed:
- On the dashboard within the monitor details
- On the status page

I think that would not contradict the approach of uptime-kuma. It is only a simple solution to give the user to possibility to display more information if needed.

**Comment by TheFonix** [comment]
+1

**Comment by CommanderStorm** [comment]
@MajorTomDE 
Could we close this issue in favour of this issue? https://github.com/louislam/uptime-kuma/issues/819
Rationale:
- more discussion
- more reactions 

=> if this feature gets implemented, less of a chance to be left with immortal zombie-issues
