### ISSUE TITLE
Change admin password from root server access

### ISSUE THREAD

**Issue by ZIODIOZIO** [louislam/uptime-kuma#2233]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

Hello, how it is possible to change/reset admin password from root server access?

### 🐻 Uptime-Kuma Version

/

### 💻 Operating System and Arch

ubuntu 20

### 🌐 Browser

/

### 🐋 Docker Version

/

### 🟩 NodeJS Version

/

**Comment by rezzorix** [comment]
> ### ⚠️ Please verify that this bug has NOT been raised before.
> 
>     * [x]  I checked and didn't find similar issue

https://github.com/louislam/uptime-kuma/wiki/Reset-Password-via-CLI

**Comment by rezzorix** [comment]
You running without docker?
What is your node version?

**Comment by ZIODIOZIO** [comment]
> It should be an old bug, are you using the old version?
> 
> #1510
> 
> If you don't want to update, you can follow this workaround method to reset password: [#1510 (comment)](https://github.com/louislam/uptime-kuma/issues/1510#issuecomment-1101174699)

After updating I am getting some weird results:

![image](https://user-images.githubusercontent.com/74601229/197481567-28a0c0ca-e47a-4444-9d1a-d0aab7f1e534.png)


I would like to update in order to resolve the bug as you said before.
