### ISSUE TITLE
Password reset tool no such user

### ISSUE THREAD

**Issue by tyjtyj** [louislam/uptime-kuma#2238]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

Docker mode

```
uptime-kuma:/opt/uptime-kuma$ npm run reset-password

> uptime-kuma@1.18.0 reset-password
> node extra/reset-password.js

== Uptime Kuma Reset Password Tool ==
Connecting the database
2022-10-18T18:20:17.922Z [DB] INFO: Data Dir: ./data/
Error: select * from `user` limit 1 - SQLITE_ERROR: no such table: user
2022-10-18T18:20:18.609Z [DB] INFO: Closing the database
2022-10-18T18:20:20.625Z [DB] INFO: SQLite closed
Finished.
```

### 🐻 Uptime-Kuma Version

Version: 1.18.0

### 💻 Operating System and Arch

Debian

### 🌐 Browser

Chrome

**Comment by tyjtyj** [comment]
After container update, I cant login from other device. The password is saved, so I know it is correct.
One of the session still valid so. I an see it still running without flaws.
It just I can't login from other device, thus trying password reset

**Comment by louislam** [comment]
Is it using the default data folder?

**Comment by tyjtyj** [comment]
> Is it using the default data folder?

This is part of home assistant add-ons integration. 

the data folder is under /data. It does not seems to be wrong data folder because i am getting different error if the data folder not found. 

Anyway i managed to retrieve my saved password and able to login. Although I still unable to reset the password. 

I am closing this issue.. Thanks for looking into it.
