### ISSUE TITLE
ability to add tests so can test the data return values are valid

### ISSUE THREAD

**Issue by timrabbetts** [louislam/uptime-kuma#2242]
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

UI Feature

### 🔖 Feature description

Be good if the UI could have an area where you can specify what fields on the json you expect back and what the values should be?  With wildcards?

### ✔️ Solution

UI Update to allow tests

**Comment by CommanderStorm** [comment]
@timrabbetts 

This feature has been implemented, merged and will be released in the upcoming [`1.23`-release](https://github.com/louislam/uptime-kuma/milestone/34).
See https://github.com/louislam/uptime-kuma/pull/3253 for further details.
We forgot to add this issue to the `Resolves #xxx` list, could you close this issue? (only you or Louis can do so)

**Comment by CommanderStorm** [comment]
Closing as resolved as https://github.com/louislam/uptime-kuma/pull/3253 was merged into the `v1.23.0` release
