### ISSUE TITLE
When using NTLM got 401 errors but postman was fine.

### ISSUE THREAD

**Issue by ghost** [louislam/uptime-kuma#2243]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### Description

Using NTLM for auth, postmna worked fine but this tool didn't.  Found this post https://bobbyhadz.com/blog/react-error-digital-envelope-routines-unsupported#:~:text=To%20solve%20the%20%22error%3A0308010C,nvm%20install%20%2D%2Dlts%20command.

This sorted it, hope this helps someone.

`node --openssl-legacy-provider server/server.js`

### 👟 Reproduction steps

Use NTLM auth.

### 👀 Expected behavior

Auth should work

### 😓 Actual Behavior

HTTP 401

### 🐻 Uptime-Kuma Version

1.18.0

### 💻 Operating System and Arch

Mac OSX

### 🌐 Browser

Chrome

**Comment by louislam** [comment]
Need detailed reproduction steps.

**Comment by christopherpickering** [comment]
@timrabbetts what version of node are you using? I think that command is needed in general for 18+ and kuma.
