### ISSUE TITLE
[http] display jitter (max - min latency)

### ISSUE THREAD

**Issue by mabed-fr** [louislam/uptime-kuma#2251]
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

UI Feature

### 🔖 Feature description

Print the jitter for http probe for given period

### ✔️ Solution

Max latenci - min latenci = jitter

**Comment by CommanderStorm** [comment]
ping is tracked in #1724 => have reworded the issue to only inlcude this
