### ISSUE TITLE
Check of running Websites results in error "maxContentLength size of -1 exceeded"

### ISSUE THREAD

**Issue by rnsrv** [louislam/uptime-kuma#2253]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### Description

Hi, 

i'm trying to monitor some websites (that are definitely up) but keep receiving an error "maxContentLength size of -1 exceeded".
Thank you for your help

### 👟 Reproduction steps

Add new Monitor -> HTTP(S) -> *put in whatever * -> save

### 👀 Expected behavior

Not to receive an error of any kind, Host being up

### 😓 Actual Behavior

Error: "maxContentLength size of -1 exceeded"

### 🐻 Uptime-Kuma Version

1.18.5

### 💻 Operating System and Arch

Hypervisor: Proxmox Virtual Environment 7.2-11 Virtual Machine: Ubuntu 22.04.1 LTS Kernel: Linux 5.15.60-2-pve

### 🌐 Browser

Brave 1.44.112 (Chromium 106.0.5249.119)

### 🐋 Docker Version

20.10.20

### 🟩 NodeJS Version

No response

### 📝 Relevant log output

```shell
docker logs uptime-kuma
[...]
2022-10-20T13:18:11.703Z [MONITOR] WARN: Monitor #7 'web': Pending: maxContentLength size of -1 exceeded | Max retries: 10 | Retry: 1 | Retry Interval: 60 seconds | Type: http
2022-10-20T13:19:46.563Z [MONITOR] WARN: Monitor #6 'Gitea': Pending: maxContentLength size of -1 exceeded | Max retries: 10 | Retry: 7 | Retry Interval: 60 seconds | Type: http
2022-10-20T13:19:59.942Z [MONITOR] WARN: Monitor #7 'web': Pending: maxContentLength size of -1 exceeded | Max retries: 10 | Retry: 2 | Retry Interval: 60 seconds | Type: http
2022-10-20T13:21:34.661Z [MONITOR] WARN: Monitor #6 'Gitea': Pending: maxContentLength size of -1 exceeded | Max retries: 10 | Retry: 8 | Retry Interval: 60 seconds | Type: http
2022-10-20T13:21:48.133Z [MONITOR] WARN: Monitor #7 'web': Pending: maxContentLength size of -1 exceeded | Max retries: 10 | Retry: 3 | Retry Interval: 60 seconds | Type: http
2022-10-20T13:23:22.753Z [MONITOR] WARN: Monitor #6 'Gitea': Pending: maxContentLength size of -1 exceeded | Max retries: 10 | Retry: 9 | Retry Interval: 60 seconds | Type: http
2022-10-20T13:23:26.475Z [MONITOR] INFO: Get Monitor: 6 User ID: 1
2022-10-20T13:25:10.884Z [MONITOR] WARN: Monitor #6 'Gitea': Pending: maxContentLength size of -1 exceeded | Max retries: 10 | Retry: 10 | Retry Interval: 60 seconds | Type: http
2022-10-20T13:25:36.657Z [MONITOR] WARN: Monitor #7 'web': Pending: maxContentLength size of -1 exceeded | Max retries: 10 | Retry: 1 | Retry Interval: 60 seconds | Type: http
2022-10-20T13:26:59.201Z [MONITOR] WARN: Monitor #6 'Gitea': Failing: maxContentLength size of -1 exceeded | Interval: 60 seconds | Type: http | Down Count: 0 | Resend Interval: 20

docker-compose.yml
version: '3'
services:
uptime-kuma:
image: louislam/uptime-kuma:latest
container_name: uptime-kuma
volumes:
- /home//uptime-kuma/data:/app/data
- /var/run/docker.sock:/var/run/docker.sock
ports:
- 3001:3001
restart: always

Docker info:
Client: Docker Engine - Community
Version: 20.10.20
API version: 1.41
Go version: go1.18.7
Git commit: 9fdeb9c
Built: Tue Oct 18 18:20:18 2022
OS/Arch: linux/amd64
Context: default
Experimental: true

Server: Docker Engine - Community
Engine:
Version: 20.10.20
API version: 1.41 (minimum version 1.12)
Go version: go1.18.7
Git commit: 03df974
Built: Tue Oct 18 18:18:08 2022
OS/Arch: linux/amd64
Experimental: false
containerd:
Version: 1.6.8
GitCommit: 9cd3357b7fd7218e4aec3eae239db1f68a5a6ec6
runc:
Version: 1.1.4
GitCommit: v1.1.4-0-g5fd4c4d
docker-init:
Version: 0.19.0
GitCommit: de40ad0
```

**Comment by louislam** [comment]
It maybe an upstream issue of Axios with your local network
https://github.com/axios/axios/issues/4806

Since the issue was first reported on 2022-06-24, you could try older version of Uptime Kuma, see whether it is ok.

**Comment by wheeleran** [comment]
im getting a lot of these too, in a docker install on a Synology NAS monitoring live websites hosted on Digital Ocean running through Cloudflare. Sites are definitely up, and the Kuma UP notification comes through exactly a minute later. Heartbeat Interval and Retry is set to 60 seconds, but should i be setting the actual Retry to something other than 0 ??

**Comment by zorrobiwan** [comment]
Just got this one for a couple of (related) sites only since a couple of days only.
Running in docker on a Proxmox LXC container

**Comment by simonbouchard** [comment]
Currently monitoring 99 properties, I'm having the same issue since yesterday, every ~15m from one website only.

**Comment by louislam** [comment]
Still need a reproduce steps and try to reproduce in the demo site.

https://demo.uptime.kuma.pet

**Comment by julianengel** [comment]
I’m the next one popping in with the same issue for a few days. 

Monitoring multiple WordPress servers, with few sites each on EasyEngine. Only 1 server but 3/5 sites report this issue constantly. 

Updated everything, running Ubuntu 22.04 LTS. Sites definitely up, logs show they are up. Same config other machines don’t report any issues.

**Comment by julianengel** [comment]
Setup:

Digital Ocean
Ubuntu 22.04
Easy Engine 
WordPress 6.2 (newest)
Divi Theme

Shared plugins between then: WP Fastest Cache 

Other sites with same config, and on same server no issue.

**Comment by julianengel** [comment]
Managed to replicate on demo, before it reset. 
You can try with https://www.estiafilosofia.org.
![Uploading 9EA10A12-F024-4B6F-BAA9-6AA44B323FFE.png…]()

**Comment by louislam** [comment]
> Managed to replicate on demo, before it reset. You can try with https://www.estiafilosofia.org Just add a monitor and wait a few minutes. It does the MaxContentExceeded error and then goes back to OK randomly.

Thanks, it is able to reproduce.

**Comment by louislam** [comment]
> Managed to replicate on demo, before it reset. You can try with https://www.estiafilosofia.org Just add a monitor and wait a few minutes. It does the MaxContentExceeded error and then goes back to OK randomly.

Weird, if the Uptime Kuma container is running on my two Linux servers, it is very easy to reproduce.

However, in my local env (Windows 11 + Docker for Desktop), it is hard to reproduce. Only seen 1 error in a hour.

**Comment by wheeleran** [comment]
> Setup:
> 
> Digital Ocean Ubuntu 22.04 Easy Engine WordPress 6.2 (newest) Divi Theme
> 
> Shared plugins between then: WP Fastest Cache
> 
> Other sites with same config, and on same server no issue.

i'm getting it on one specific site, also Ubuntu, Digital Ocean, but the only Woocommerce site compared to the others, which are fine.

**Comment by louislam** [comment]
OK, I think it is still a website issue. It is also reproducible using curl I used curl and run it about 5 times on my Linux server.

```
curl https://www.estiafilosofia.org/
```

The response was incomplete and freezed for awhile. Then it throws error.

![image](https://user-images.githubusercontent.com/1336778/205484085-3bed2b5c-dccd-46a7-9de4-bf8877f90291.png)

**Comment by louislam** [comment]
After some research, I managed to fix the issue, but I don't exactly know what is happening here.

The solution is adding a header `Accept-Encoding: gzip, deflate`

https://stackoverflow.com/a/55918781/1097815


My guess is the plugin WP Fastest Cache do not handle plain text response without gzip correctly sometimes, force to gzip response fix the issue.

In curl, adding `--compress` also fix the issue

`curl --compress https://www.estiafilosofia.org/`

Free feel to try `louislam/uptime-time:nightly`

**Comment by simonbouchard** [comment]
> After some research, I managed to fix the issue, but I don't exactly know what is happening here.
> 
> The solution is adding a header `Accept-Encoding: gzip, deflate`
> 
> https://stackoverflow.com/a/55918781/1097815
> 
> My guess is the plugin WP Fastest Cache do not handle plain text response without gzip correctly sometimes, force to gzip response fix the issue.
> 
> In curl, adding `--compress` also fix the issue
> 
> `curl --compress https://www.estiafilosofia.org/`
> 
> Free feel to try `louislam/uptime-time:nightly`

Typo, `louislam/uptime-kuma:nightly`

Thank you :)

**Comment by julianengel** [comment]
> After some research, I managed to fix the issue, but I don't exactly know what is happening here.
> 
> The solution is adding a header `Accept-Encoding: gzip, deflate`
> 
> https://stackoverflow.com/a/55918781/1097815
> 
> My guess is the plugin WP Fastest Cache do not handle plain text response without gzip correctly sometimes, force to gzip response fix the issue.
> 
> In curl, adding `--compress` also fix the issue
> 
> `curl --compress https://www.estiafilosofia.org/`
> 
> Free feel to try `louislam/uptime-time:nightly`

Yes! The nightly build indeed fixed the issue. Now that you mention it, it could be WP Fastest Cache that's the common link due to its Gzipping. 

Thank you for the awesome help and resolving this @louislam!

**Comment by outofsight** [comment]
I'm experiencing the same issue with the web management interface of an HP LaserJet Printer.
Running Kuma under docker under Debian.
How can I fix?

**Comment by zorrobiwan** [comment]
> I'm experiencing the same issue with the web management interface of an HP LaserJet Printer. Running Kuma under docker under Debian. How can I fix?

It has been fixed in https://github.com/louislam/uptime-kuma/commit/3e68cf2a1cfab8cb8cc7969c915fba5535c7d827
which has been deployed in https://github.com/louislam/uptime-kuma/releases/tag/1.19.0
so ... upgrade :)

**Comment by outofsight** [comment]
> > I'm experiencing the same issue with the web management interface of an HP LaserJet Printer. Running Kuma under docker under Debian. How can I fix?
> 
> It has been fixed in [3e68cf2](https://github.com/louislam/uptime-kuma/commit/3e68cf2a1cfab8cb8cc7969c915fba5535c7d827) which has been deployed in https://github.com/louislam/uptime-kuma/releases/tag/1.19.0 so ... upgrade :)

I installed 2 days ago, I already have 1.19

**Comment by louislam** [comment]
Unfortunately, this fix causes other bugs #2468 #2455. :/

**Comment by zorrobiwan** [comment]
Damned, sorry for my too fast answer @outofsight

**Comment by louislam** [comment]
In 1.19.1, I renamed this error to `response timeout: incomplete response within a interval`.
