### ISSUE TITLE
Transition to using docker

### ISSUE THREAD

**Issue by nmcc1212** [louislam/uptime-kuma#2254]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

Is it possible to transition from running using the without docker method to using docker

### 🐻 Uptime-Kuma Version

1.18.5

### 💻 Operating System and Arch

Ubuntu 22.04 arm64 (aarch64)

### 🌐 Browser

Chrome

### 🐋 Docker Version

Docker 20.10.19

**Comment by louislam** [comment]
Yes, just mount the same `data` folder, or copy the files inside data folder to your volume.
