### ISSUE TITLE
Maintenance section not accessible on mobile layout

### ISSUE THREAD

**Issue by dallyger** [louislam/uptime-kuma#2257]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### Description

There is no link to the maintenance pane when the mobile layout is used.
The actual maintenance section does work, when accessing it before switching to the mobile layout.

On another note, maybe moving the maintenance menu to the settings page altogether would reduce the confusion for both, mobile and desktop users and resolve the issue of inconsistent menus. When I first searched for this new feature, I went straight to the settings page, assuming it is like “Notifications” or “Proxies”, and totally overlooked the new entry in this dropdown.

Desktop:
![image](https://user-images.githubusercontent.com/31095474/197336301-11b52d38-402a-40c8-b99f-076772fa4452.png)

Mobile:
![image](https://user-images.githubusercontent.com/31095474/197336357-ec967da6-d283-423a-b0ed-9e082cbc8b6d.png)

Thank you for your work on this awesome project!

### 👟 Reproduction steps

* Access web page using the mobile layout (below 768 px wide)

### 👀 Expected behavior

See maintenance button under settings page above the logout button.
The logout button has moved there too on mobile, so that would be the logical place to search for it.

### 😓 Actual Behavior

Cannot find the maintenance button anywhere.

### 🐻 Uptime-Kuma Version

1.19.0-beta.0

### 💻 Operating System and Arch

Ubuntu 20.04.5 LTS - 5.4.0-92-generic x86_64 GNU/Linux

### 🌐 Browser

Firefox 105.0.3

### 🐋 Docker Version

Docker 20.10.12-0ubuntu2~20.04.1

**Comment by x86dev** [comment]
I can confirm this bug -- first I was searching for the new maintenance functionality using my smartphone on a mobile browser (Firefox), didn't find it anywhere. Switching the Firefox mobile to retrieving the desktop version of the site showed me the maintenance entry (and user menu as a whole).

**Comment by x86dev** [comment]
Works for me now in 1.19 Beta 2 -- thanks!
