### ISSUE TITLE
Health Check restart docker container

### ISSUE THREAD

**Issue by Dofamin** [louislam/uptime-kuma#2258]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### Description

I created my own docker file [REPO](https://github.com/Dofamin/Uptime-Kuma-Docker), and [include](https://github.com/Dofamin/Uptime-Kuma-Docker/blob/main/Dockerfile#L33) health checks, which are causing container to restart, because they was in bad status.

### 👟 Reproduction steps

Create docker-compose file, with this content
```version: '3.8'
services:
  Uptime-Kuma:
    container_name: Uptime-Kuma
    image: ghcr.io/dofamin/uptime-kuma-docker:main
    volumes:
      - /srv/Uptime_Kuma/data/:/srv/uptime-kuma/data/
    restart: unless-stopped
    mem_limit: 100M
    networks:
      - 'frontend'
  
networks:
#Internal-only network
  backend:
    name: backend
    internal: true
#External network actually
  frontend:
    name: frontend
    internal: false
```
With enabled health checks, uncomment [this](https://github.com/Dofamin/Uptime-Kuma-Docker/blob/main/Dockerfile#L33)
Container running behind Nginx Proxy Manager, and for some reason cant get health checks from itself
Ports was exposed in docker file, without mapping to host

### 👀 Expected behavior

Working health checks

### 😓 Actual Behavior

Non working health checks  

### 🐻 Uptime-Kuma Version

1.18.5

### 💻 Operating System and Arch

Ubuntu 22.04.1 LTS

### 🌐 Browser

Google Chrome 106.0.5249.91

### 🐋 Docker Version

Docker version 20.10.20, build 9fdeb9c

### 🟩 NodeJS Version

v16.18.0

**Comment by rezzorix** [comment]
Can you post the logs?

**Comment by Dofamin** [comment]
Unfortunately the logs are gone.
All that was in the logs was that the entrypoint.sh killed the process.

**Comment by louislam** [comment]
Changed to `help` as it is not the official image.
