### ISSUE TITLE
`Cannot call a namespace ('dayjs')`

### ISSUE THREAD

**Issue by Saibamen** [louislam/uptime-kuma#226]
**Is it a duplicate question?**
No

**Describe the bug**
Warnings during frontend build

**To Reproduce**
1. `npm run build`

**Expected behavior**
No warnings during build

**Info**
- Uptime Kuma Version: https://github.com/louislam/uptime-kuma/commit/440c178403bb1086b4caa1c868568a6f191928c1
- Using Docker?: ---
- OS: Windows
- Browser: ---

**Screenshots**
---

**Error Log**
```
vite v2.4.4 building for production...
transforming (589) node_modules\vue-chart-3\node_modules\lodash\_hashClear.jsCannot call a namespace ('dayjs')
Cannot call a namespace ('dayjs')
✓ 606 modules transformed.
```

**Comment by Hartha-aloufi** [comment]
I also have the same issue with vite v3.2.5
`vite v3.2.5 building for production...
transforming...
Cannot call a namespace ('dayjs')`

**Comment by Saibamen** [comment]
@Hartha-aloufi 
Uptime Kuma uses Vite 3.1.8

Are you sure you are writing in correct repository?

**Comment by louislam** [comment]
> I also have the same issue with vite v3.2.5 `vite v3.2.5 building for production... transforming... Cannot call a namespace ('dayjs')`

Expexted message during building, but there are no negative impact. Just ignore it.

**Comment by ncubica** [comment]
Same issues as well; how do you know there are not issues about it? @louislam

**Comment by krsntn** [comment]
```
import * as _dayjs from 'dayjs';

const dayjs = _dayjs;
```

this works for me.

**Comment by y-sekido** [comment]
```
import dayjs from 'dayjs'
```

**Comment by hmartiins** [comment]
> > I also have the same issue with vite v3.2.5 `vite v3.2.5 building for production... transforming... Cannot call a namespace ('dayjs')`
> 
> Expexted message during building, but there are no negative impact. Just ignore it.

it's a lie, it changes the build process in vite sim. Install date-fns to solve this!

**Comment by Mrad-Hamza** [comment]
> > I also have the same issue with vite v3.2.5 `vite v3.2.5 building for production... transforming... Cannot call a namespace ('dayjs')`
> 
> Expexted message during building, but there are no negative impact. Just ignore it.

For me it had a negative impact on the build
anyone solved this ?

**Comment by Cristian-Sknz** [comment]
> For me it had a negative impact on the build 
> anyone solved this ?

Instead of using this import,
```js
import * as dayjs from 'dayjs';
```
use this:
```js
import dayjs from 'dayjs';
```

**Comment by aryef** [comment]
import * as _dayjs from 'dayjs';
const dayjs = _dayjs;

worked for me too.

**Comment by Justman10000** [comment]
> > For me it had a negative impact on the build
> > anyone solved this ?
> 
> Instead of using this import,
> 
> ```js
> import * as dayjs from 'dayjs';
> ```
> 
> use this:
> 
> ```js
> import dayjs from 'dayjs';
> ```

Does not exist for me

**Comment by QC2168** [comment]
> > For me it had a negative impact on the build
> > anyone solved this ?
> 
> Instead of using this import,
> 
> ```js
> import * as dayjs from 'dayjs';
> ```
> 
> use this:
> 
> ```js
> import dayjs from 'dayjs';
> ```

thanks you，it working
