### ISSUE TITLE
Parent/Child relation for good notification and good grafical uptime

### ISSUE THREAD

**Issue by mabed-fr** [louislam/uptime-kuma#2261]
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

UI Feature, Other

### 🔖 Feature description

My VPS is the child of the probe which pings google.fr because if I do not join google.fr it means that my internet access is down but not my VPS

### ✔️ Solution

add feature for have Parent/Child for good chart and alert

### 📝 Additional Context

This feature allows not to calculate the uptime of my VPS while google.fr is DOWN

**Comment by skaempfe** [comment]
Like #1236 ?

**Comment by CommanderStorm** [comment]
@mabed-fr 
We are consolidating duplicate issues a bit to make issue management easier.
I think, we should track this issue in https://github.com/louislam/uptime-kuma/issues/1089 and as there is no functional difference (maybe just small naming differences, but nothing that would require a different issue imo)
=> I am going to close this as a duplicate
