### ISSUE TITLE
Is there a feature available in uptime to show which users are logged in to the domain?

### ISSUE THREAD

**Issue by Mighty33** [louislam/uptime-kuma#2262]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

Is there a feature available in uptime to show which users are logged in to the domain?
Was hoping to see if there was a feature like this...

### 🐻 Uptime-Kuma Version

Latest

### 💻 Operating System and Arch

Ubuntu

### 🌐 Browser

Chrome

**Comment by rezzorix** [comment]
No - or - depends on what you mean with "logged in to the domain"...
Can you elaborate more?
