### ISSUE TITLE
Hostname/IP does not match certificate's altnames

### ISSUE THREAD

**Issue by perpi** [louislam/uptime-kuma#2263]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

I get this message for some sources added to _Uptime Kuma_:

    Hostname/IP does not match certificate's altnames: Host: sub.example.com. is not in the cert's altnames: DNS:*.duckduckgo.com, DNS:duckduckgo.com
I don't understand what it has to do with the DuckDuckGO?! Sources have their valid wildcard certificates set on their windows server. It happens two/three times per day for only one or two minutes as _Down_ status?

I did troubleshooting on the network side and didn't find anything related.

Could it be related to Kuma?

Where I can find logs of above error for more details?

### 🐻 Uptime-Kuma Version

1.18.5

### 💻 Operating System and Arch

Ubuntu 20.04

### 🌐 Browser

Chrome

**Comment by rezzorix** [comment]
Either the SSL for the domains were setup wrongly or your uptime-kuma setup or monitor has something wrong.

Either way need more information on details.

Could you provide an example of a monitor as well as how you started uptime-kuma?
With docker? Without?

**Comment by uhlhosting** [comment]
Hi this is a recurring issue every now and then since the instalation. I run too in docker/caprover. Please let me know what details to provide to help fix this.

**Comment by uhlhosting** [comment]
Yes well we checked. The websites have nothingh in commong to the gitlab server mentioned. Especially not on a ssl level.

**Comment by uhlhosting** [comment]
Plus for now for months was not occuring and now is back again. The only resolution to this is to temporarily removed ssl check.
