### ISSUE TITLE
TLS Certificate Expiry Notification

### ISSUE THREAD

**Issue by saravanan1213** [louislam/uptime-kuma#2267]
### ⚠️ Please verify that this bug has NOT been raised before.

- [x] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

Hii Team. I need a help to solve this problem , I enable the Certificate Expiry Notification & in "settings - notification i enable the days" but it doesn't notify?? 

### 🐻 Uptime-Kuma Version

1.17.1

### 💻 Operating System and Arch

Ubuntu

### 🌐 Browser

Google Chrome

**Comment by rezzorix** [comment]
> ### ⚠️ Please verify that this bug has NOT been raised before.
> 
>     ☑️ I checked and didn't find similar issue 

I guess this relates to this: https://github.com/louislam/uptime-kuma/issues/1890

You are on v1.17.1 - I didnt see it in changelogs, but can you try updating to latest version and see if it works then?

**Comment by louislam** [comment]
@saravanan1213 It is a known issue of Pushbullet's notification. Are you using it?
