### ISSUE TITLE
DDOS DETECTOR

### ISSUE THREAD

**Issue by Gauvino** [louislam/uptime-kuma#2272]
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

New Notification, UI Feature

### 🔖 Feature description

It would be so cool if kuma could add like a ddos detector of other feature like this and i've found this project that you could probably add to kuma and would be very super cool.

### ✔️ Solution

https://github.com/pavel-odintsov/fastnetmon

**Comment by tofran** [comment]
I don't think this project should shift to doing this.
In my opinion you should use software designed to do so, like fastnetmon. You could then trigger uptime-kuma with a webhook (ping monitor).
For example see how they do [webhooks for Slack](https://github.com/pavel-odintsov/fastnetmon/blob/master/src/scripts/notify_with_slack.sh).
