### ISSUE TITLE
2h notificaton delay

### ISSUE THREAD

**Issue by gokkstudio** [louislam/uptime-kuma#2273]
### ⚠️ Please verify that this bug has NOT been raised before.

- [x] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

I'm getting up/down notifications via email using HTTP(s) as a monitor type with 45s interval.
The problem is Kuma sends email notifications with **exactly 2 hours delay**, example:
[🔴 Down] timeout of 24000ms exceeded 
Time (UTC): 2022-10-27 00:45:25.539 **(received at 02:45)**
and
[✅ Up] 200 - OK
Time (UTC): 2022-10-27 00:47:15.808 **(received at 02:47)**

Both Server/Kuma timezones are the same (GMT+2), any clue on how to fix this?

### 🐻 Uptime-Kuma Version

1.18.2

### 💻 Operating System and Arch

Ubuntu 22.04

### 🌐 Browser

Chrome

**Comment by rezzorix** [comment]
I suggest you check your mail-server settings.
- Check mail queue (maybe there are hiccups)
- Check outgoing message limit (per hour/account/server)

**Comment by gokkstudio** [comment]
> I suggest you check your mail-server settings.
> 
> * Check mail queue (maybe there are hiccups)
> * Check outgoing message limit (per hour/account/server)

Hm... I'm using gmail to send notifications so this shouldn't be an issue.
Maybe switch to domain email for this?

**Comment by rezzorix** [comment]
Are you sending Gmail to Gmail?

Anyway, regardless of that, I know that Gmail often gets blocked by DNSBLs on first delivery attempt, and then lateron with second attempt (different IP) it goes through. Which could explain the 2 hours.

If you can try first with alternate Email-Providers and see how that works.

**Comment by gokkstudio** [comment]
Correct - Gmail to Gmail.
Alright, I'll test with domain email and report back.
Thanks for this!

**Comment by gokkstudio** [comment]
> Are you sending Gmail to Gmail?
> 
> Anyway, regardless of that, I know that Gmail often gets blocked by DNSBLs on first delivery attempt, and then lateron with second attempt (different IP) it goes through. Which could explain the 2 hours.
> 
> If you can try first with alternate Email-Providers and see how that works.

Unfortunately Gmail wasn't the issue, same thing with my domain email - 2h delay.
Do you have any other idea so I could check?

**Comment by gokkstudio** [comment]
I've checked `timedatectl` on Ubuntu:
Local time: Sat 2022-10-29 09:56:53 CEST
Universal time: Sat 2022-10-29 07:56:53 UTC
RTC time: Sat 2022-10-29 07:56:53
Time zone: Europe/Berlin (CEST, +0200)
System clock synchronized: yes
NTP service: active
RTC in local TZ: no

And +0200 corresponds with my timezone.

**Comment by louislam** [comment]
The notification is sent immediately and it is not a queue or a schedule task.

Did you try to take down a testing monitor, and it is really received after 2 hours? Or just timezone issue?

**Comment by rezzorix** [comment]
I just tried to reproduce this again with different email  / time zone settings.

Cannot reproduce.
Email is sent / received more or less instantly.

**Comment by louislam** [comment]
> I just tried to reproduce this again with different email / time zone settings.
> 
> Cannot reproduce. Email is sent / received more or less instantly.
> 
> Edit: saw louslams message later - yes the time zone is indeed shown as UTC in the email, but I guess this is a known issue. And it doesnt effect actual email sent time.

Just noticed too, it is clearly not a delay, close as solved.
