### ISSUE TITLE
Domain renewal check

### ISSUE THREAD

**Issue by jgardiner68** [louislam/uptime-kuma#2275]
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

New Monitor

### 🔖 Feature description

Check the expiry date on domain names and alert the user when a domain is coming up for renewal.

### ✔️ Solution

Have configurable alert options including 90, 60 and 30 days

**Comment by louislam** [comment]
Duplicate of #944
