### ISSUE TITLE
Old IP addresses are used via DNS after recreating a docker container

### ISSUE THREAD

**Issue by rcdailey** [louislam/uptime-kuma#2278]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### Description

When I configure a monitor over HTTP to a service via DNS running in a docker container using a bridge / overlay network, the old IP address continues to be used after `down`'ing and `up`-ing the target container. The recreation of the container results in very little down time, but it also generates a new IP address each time.

### 👟 Reproduction steps

Create a service in Docker Compose (using Authentik as an example; some parts are left out for brevity):

```yml
networks:
  reverse_proxy:
    external: true
    driver: overlay

server:
  image: ghcr.io/goauthentik/server:latest
  restart: unless-stopped
  command: server
  container_name: authentik
  networks:
    - reverse_proxy
```

The overlay network `reverse_proxy` can also just be a bridge network; the outcome will still be the same. Be sure to create that network external to docker compose and prior to continuing. Make sure your Uptime Kuma docker container is also using this external network in the same way Authentik is.

Next, set up the new monitor in Uptime Kuma like below:

![image](https://user-images.githubusercontent.com/1768054/198838412-55362457-6dc7-4886-a717-2eeb6901429a.png)

Run `docker compose up -d` on the Authentik service to make sure Uptime Kuma can ping it and everything is successful.

Next, take down the Authentik container and recreate it:

```sh
docker compose down
docker compose up -d
```

Because of the lengthy retries configured for the Authentik Monitor in Uptime, it will take some time but you should see notifications that the service is down eventually:

![image](https://user-images.githubusercontent.com/1768054/198838521-c6f8ec39-df92-46b7-a852-fe5d53761885.png)

(Ignore the port number in the above screenshot; this was actually taken from a different service but the error message is the same either way).

After the failure, within seconds you see it go green again with `200 - OK`.

### 👀 Expected behavior

I can only suspect the issue here is DNS. The DNS resolver for docker typically needs to disable cache or at the very least set the TTL to a very low value like 30 seconds. Because containers can be created & destroyed and be assigned different IP addresses quite often, this is necessary to avoid continuing to communicate with a service using an old IP address.

It does seem like the IP address gets refreshed eventually, but considering I have my Authentik monitor set up to retry 4 times at 60 seconds apart, it isn't nearly often enough.

I expect that the IP address be refreshed more often to avoid these false negatives.

### 😓 Actual Behavior

Old IP address is used, resulting in a false negative.

### 🐻 Uptime-Kuma Version

1.18.5

### 💻 Operating System and Arch

Unraid + Docker / x64

### 🌐 Browser

Edge Chromium

### 🐋 Docker Version

20.10.17

### 🟩 NodeJS Version

Controlled by docker; unknown

**Comment by louislam** [comment]
I think it is just a docker use case issue. Uptime Kuma respects the TTL value correctly.

https://github.com/moby/moby/issues/30029 According to this thread, they hardcoded it to 600 seconds. Not sure whether it is can be lower.

**Comment by rcdailey** [comment]
I know in NGINX, we are able to use `resolver  127.0.0.11 valid=30s` to control the TTL; I was hoping for a client-side solution implemented by Uptime.

Static IPs *are* an option but very inflexible:

- I have to define my overlay/bridge networks with a fixed subnet
- Each new service I spin up has to have additional configuration to specify a fixed IP
- I have to do the job of DHCP and manage my free/used IPs
- This gets even more complicated with overlay networks

I really want to avoid that option if possible. How hard would it be for you to offer a TTL override? Suppose it's 600s in docker; what if I want you to use some other value?

Thanks for the quick response!

**Comment by louislam** [comment]
I see your point, feel free to create a feature-request.

**Comment by rezzorix** [comment]
Isn't TTL for docker network IPs 64?
Since you are using hostnames that need to be resolved... what's your DNS server and cache doing?

**Comment by rcdailey** [comment]
@rezzorix This isn't my DNS server; rather it's using Docker's internal DNS server. The hostnames belong to the containers themselves for resolution on bridge networks.

**Comment by louislam** [comment]
Now you can disable DNS cache in Uptime Kuma's Settings, I think it could solve your problem.

**Comment by rcdailey** [comment]
@louislam Thank you for letting me know. I did a quick test and I wasn't able to reproduce the failure. I'll go ahead and close this issue.
