### ISSUE TITLE
ntfy notification broken in 1.18.5

### ISSUE THREAD

**Issue by bsdlme** [louislam/uptime-kuma#2279]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### Description

Between 1.17.1 and 1.18.5 ntfy.sh notification broke. When ntfy notification is created (standard settings, only a topic added) and the "Test" button is clicked there's an error that ntfy.sh is not found. 

The same works fine with version 1.17.1. 
DNS lookup for ntfy.sh and accessing ntfy.sh from a terminal on this machine works.

### 👟 Reproduction steps

* Add ntfy notification
* Add a top
* Click "Test"

### 👀 Expected behavior

Test succeeds

### 😓 Actual Behavior

Test fails

### 🐻 Uptime-Kuma Version

1.18.5

### 💻 Operating System and Arch

FreeBSD 13.1 / amd64

### 🌐 Browser

Google Chrome 106.0.5249.119

### 🟩 NodeJS Version

v14.20.0

### 📝 Relevant log output

```shell
Error: Error: Error: cacheableLookup ENOTFOUND ntfy.sh
    at Ntfy.throwGeneralAxiosError (/root/server/notification-providers/notification-provider.js:38:15)
    at Ntfy.send (/root/server/notification-providers/ntfy.js:28:18)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async Socket.<anonymous> (/root/server/server.js:1150:27)
```

**Comment by louislam** [comment]
Missing package, check the update guide again.

**Comment by bsdlme** [comment]
Same with a fresh installation of 1.18.15. Is the optional apprise python module needed for this?

**Comment by louislam** [comment]
I was wrongly read the error message. Your Uptime Kuma cannot resolve this domain: https://ntfy.sh.

You should check your network.

**Comment by louislam** [comment]
I wrongly read the error message, but I can't reproduce in my side. Reopen see if everyone know what happened.

**Comment by Tekgnome-svg** [comment]
System: Ryzen 5825u, 64gb ram, 
OS: Proxmox, 
Docker/Portainer, 
UpTimeKuma v1.18.5 clean install
Browser: Chrome Version 106.0.5249.119 (Official Build) (64-bit)

Couldn't reproduce this issue

**Comment by bsdlme** [comment]
I'll check which version introduced the regression on FreeBSD.

**Comment by bsdlme** [comment]
1.17.1 works, 1.18.0 does not.

**Comment by bsdlme** [comment]
ntfy notification on FreeBSD is working again in 1.20.2. Closing this issue.
