### ISSUE TITLE
Response time color

### ISSUE THREAD

**Issue by fbsanches** [louislam/uptime-kuma#2285]
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

UI Feature, Other

### 🔖 Feature description

In my opinion, the only thing missing is a visual option that gives an option to visually see the requests that are slow. Put a response time stipulated by the user and when reaching this time, he can change the color to orange or yellow on the timeline, showing that in those requests the endpoint was slow or delayed to respond. I hope I was clear and to the point. If it only shows green or red, we won't know if the endpoint has a problem. If it shows all green where the endpoint is responding doesn't mean it's fine, until then, the endpoint may have a problem if the request is slow to respond. In this case, open a field to enter in seconds or minutes a time when he believes the endpoint is slow or not according to what he knows.

### ✔️ Solution

include a time field in which if the request reaches this time it can change color and indicate that the endpoint has degraded performance and change the color in the timeline and in the history as well, if applicable.

**Comment by fbsanches** [comment]
The feature I'm looking for is exactly [this](https://github.com/louislam/uptime-kuma/pull/1878). Any news on when it will be stable?

**Comment by CommanderStorm** [comment]
> The feature I'm looking for is exactly https://github.com/louislam/uptime-kuma/pull/1878

Closing as a duplicate

> Any news on when it will be stable

Please subscribe to the PR #1878 for news.
As mentioned in the issue above:
- the current implementation is not cutting it, as it would essentially send notifications on every failed attempt and not respect the retry-mechanism.
- At this point, I think a reattempt is reasonable
