### ISSUE TITLE
Usage of NodeJS 18 LTS

### ISSUE THREAD

**Issue by etec-masterofsynapse** [louislam/uptime-kuma#2295]
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

Other

### 🔖 Feature description

The install guide for non-Docker installs in the wiki recommends NodeJS 14 or higher, but the easy install script installs 14 when using the non-Docker way.
NodeJS 14 LTS will be End-of-Maintenance in April 2023, not that far off.
Are there major headaches to be expected when using NodeJS 18 LTS today?

### ✔️ Solution

Usage of NodeJS 18 LTS

**Comment by louislam** [comment]
Uptime Kuma should be working fine on Node.js 18, you can update your Node.js manually.

**Comment by etec-masterofsynapse** [comment]
> Uptime Kuma should be working fine on Node.js 18, you can update your Node.js manually.

In that case, are there plans to refresh the install script to use 18 going forward?

**Comment by RalfSoft** [comment]
Node18 would be great. And if you update install scripts / docker containers, please consider using the user node and not root inside the container! (Security)

**Comment by christopherpickering** [comment]
If you get the `error:0308010C:digital envelope routines::unsupported` on website running on an old IIS+.net with node 18, I found that running `NODE_OPTIONS=--openssl-legacy-provider pm2 restart uptime-kuma --update-env` fixes the error.

**Comment by CommanderStorm** [comment]
@RalfSoft 
> And if you update install scripts / docker containers, please consider using the user node and not root inside the container! (Security)

This is one of the features slated for the v2 release.
See #2720

**Comment by CommanderStorm** [comment]
Installation script has been sunset and node 14 is tracked in #3746 
=> closing as resolved
