### ISSUE TITLE
Add New Monitor-batch add 

### ISSUE THREAD

**Issue by SLD-Allen** [louislam/uptime-kuma#2297]
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

New Monitor

### 🔖 Feature description

[Add New Monitor] support batch add 

### ✔️ Solution

[Add New Monitor] support batch add 

### ❓ Alternatives

[Add New Monitor] support batch add 

### 📝 Additional Context

[Add New Monitor] support batch add

**Comment by ligouras** [comment]
I have created a simple script which uses Socket.io to add monitors from a csv file. I'm adding it here for anyone who may need such functionality.

https://github.com/ligouras/kuma-init

**Comment by CommanderStorm** [comment]
Closing as a duplicate of https://github.com/louislam/uptime-kuma/issues/1323 https://github.com/louislam/uptime-kuma/issues/455 https://github.com/louislam/uptime-kuma/issues/4065
