### ISSUE TITLE
Ping check showing online for every other status check

### ISSUE THREAD

**Issue by cardtap** [louislam/uptime-kuma#2299]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

I am having an issue with a Ping status monitor. It always (without fail) pings successfully every other status check interval (first pings failure, second pings success, third failure, and so on. I have tried multiple intervals (60s, 100s, 120s) and all prove the same. 

During the error state, it says that is does not recognize the hostname which leads me to possible DNS troubles. The problem though is that every other machine we have uses the same Windows DNS server and is setup the same way as clients so I would expect them to have the issue too.

Am I missing something here?

EDIT: I double checked the DNS server is set properly within the uptime-kuma docker container. I've also confirmed I can ping the computer from the docker container itself without any issues.

Thanks in advance for any insight anyone might have.

![image](https://user-images.githubusercontent.com/68241371/200418792-d488b9f8-e493-40b6-9726-029df1a4749f.png)

### 🐻 Uptime-Kuma Version

1.18.5

### 💻 Operating System and Arch

Docker image, hosted on Proxmox Hypervisor

### 🌐 Browser

Chrome 107.0.5304.88

### 🐋 Docker Version

Docker 20.10.18

**Comment by rezzorix** [comment]
HM2 is connected via Wifi?

**Comment by cardtap** [comment]
@rezzorix, nope, everything is ethernet, and cmd has no issues with pinging at anytime. I changed the name of hm-2 in Uptime Kuma from a hostname to IP address and it stopped having issues. But that isn't optimal as now we won't know if DNS ever has issues.
