### ISSUE TITLE
Uptime kuma SQL connection string wrong port 

### ISSUE THREAD

**Issue by kelvin-codes-stuff** [louislam/uptime-kuma#2301]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

Hi. I want to monitor a SQL server. Now i specify the port in the connection string:
`server=127.0.0.1;port=3306;uid=root;pwd=12345;database=test`
Now it's still using a other port (so it says: Failed to connect to 127.0.0.1:1433 - Could not connect (sequence))
But i specified the port "3306", why it's still trying to connect to 1433?
I ruled out the beta version.
Uptime kuma runs in docker on the same server the MySQL server is in

### 🐻 Uptime-Kuma Version

Version: 1.19.0-beta.0

### 💻 Operating System and Arch

ubuntu2 20.04.1

### 🌐 Browser

Version 107.0.5304.88

### 🐋 Docker Version

Docker version 20.10.12

**Comment by louislam** [comment]
I think your connection string is incorrect.

I search it from Google:

> Server=myServerName,myPortNumber;Database=myDataBase;User Id=myUsername;Password=myPassword;

https://www.connectionstrings.com/sqlconnection/using-a-non-standard-port/

**Comment by rezzorix** [comment]
Also: if calling 127.0.0.1:1433 from inside the container, you must have the MySQL server running at this port inside the same container...

If not in same container find out either container IP of MySQL server or use the host IP:port

**Comment by Syedsv** [comment]
Is there a way to connect to cloudsql?
Is the connection string support available?

**Comment by CommanderStorm** [comment]
V1 does suppport running on sqlite3 a database.
See #4500 for additional context on the status of mariadb as a database.

If you are asking about monitoring (as the issue you commented on): if you for example run postgres, we have a monitor for that.

**Comment by CommanderStorm** [comment]
As stated above, mariadb as a database is currently not supported. See https://github.com/louislam/uptime-kuma/issues/4500 for additional context.

Please use a regular VM with persistent storage instead of going stateless.
Something like [netcup](https://www.netcup.de/vserver/vps.php) is much cheaper and simpler.
This way you also montors from a different location and privider..

I have no clue what you want to tell us with the last part
