### ISSUE TITLE
Ping Delay

### ISSUE THREAD

**Issue by ImFound** [louislam/uptime-kuma#2305]
Greetings,
Is it possible to make the ping delay user selectable without the limit of at least 20 seconds?

**Comment by Computroniks** [comment]
Addressed by #1740

**Comment by ImFound** [comment]
Thanks for your work @Computroniks , now i'll use your fork :D

**Comment by Computroniks** [comment]
Please be aware, reducing the interval below 20 seconds may result in unstable behavior and unreliable monitoring.

**Comment by ImFound** [comment]
Do you have Telegram or Discord so you can help me to install your fork? I'm not familiar with NodeJS..
Yes by the way i know

**Comment by Computroniks** [comment]
https://github.com/louislam/uptime-kuma/wiki/%F0%9F%94%A7-How-to-Install#-without-docker-recommended-for-x86x64-only
Install instructions can be found here.
Instead of cloning the main repo, you would need to clone mine instead and then checkout to the branch `feature/#1645-remove-minumum-interval-value`

I do not recommend using my fork in production as it will not have all the latest features that have been added recently, instead I would recommend waiting for #1740 to be merged

**Comment by ImFound** [comment]
> https://github.com/louislam/uptime-kuma/wiki/%F0%9F%94%A7-How-to-Install#-without-docker-recommended-for-x86x64-only Install instructions can be found here. Instead of cloning the main repo, you would need to clone mine instead and then checkout to the branch `feature/#1645-remove-minumum-interval-value`
> 
> I do not recommend using my fork in production as it will not have all the latest features that have been added recently, instead I would recommend waiting for #1740 to be merged

![immagine](https://user-images.githubusercontent.com/76497130/201174993-825c677c-0d49-4012-8710-0faad1e92a53.png)
I did all, also did "git checkout feature/#1645-remove-minumum-interval-value" on your repo

**Comment by Computroniks** [comment]
Running npm setup will not work in this instance. Instead you must run `npm ci --production` and then `npm run download-dist`

**Comment by ImFound** [comment]
@Computroniks 
still says me this: 
![immagine](https://user-images.githubusercontent.com/76497130/201176541-0c64e1fc-e542-4854-8179-10fe9905ef2f.png)

**Comment by Computroniks** [comment]
Did you checkout the feature branch by running `git checkout feature/#1645-remove-minumum-interval-value`

**Comment by Computroniks** [comment]
Just realised, the frontend won't have the required update. You need to run  `npm run build` to build the correct frontend

**Comment by ImFound** [comment]
> You need to run `npm run build` to build the correct frontend

![immagine](https://user-images.githubusercontent.com/76497130/201178445-b1dd71c5-95b2-45de-90c5-5e872270725f.png)

**Comment by Computroniks** [comment]
This looks to be an error with your environment. I would recommend waiting for #1740 to be merged and then installing normally.
