### ISSUE TITLE
Turn off Notification based on a given Timeframe

### ISSUE THREAD

**Issue by Pretender1988** [louislam/uptime-kuma#2317]
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

New Monitor, Other

### 🔖 Feature description

I would like to be able to monitor a service even if the behavior is down to a given timeframe.

In my case it looks like this:
I am monitoring my own GitLab instance and my password manager server hosted in AWS. To save some money I enabled some personal hours to automatically shut down and turn on the ec2 instances with the services. In my case, the Instances are online from 8:00 AM till 10:00 PM.

I would like to get a notification when the expectation of the availability is not matching. For example, if the Service is not reachable at 8:01 because the startup has failed. or I do would like to get informed if the Services were not shut down or gut started up outside of my defined online time.

### ✔️ Solution

In my case, it could look like extending a monitoring rule with a time frame of when the service should be offline.

### ❓ Alternatives

AlternativSolution would be 3 rules
1. Is just monitors availability from 8:00 AM - 10:00 PM. 
2. Is just monitors the not availability from 0:00 AM -7:59 PM
3. Is just monitors the not availability from 10:01 AM - 11:59 PM

### 📝 Additional Context

I have checked for this feature request exists but haven't found anything. Hope it is not a duplicate.

**Comment by Surgical71** [comment]
I was also just about to log a similar request.
It should in theory be easy to implement. Just add a option  for a monitor time frame in the UI (That's optional) And then just create a IF function to check the current time and time frame before sending a Notification

**Comment by derekoharrow** [comment]
This is probably more difficult to do well than it sounds. What about weekends? Public holidays? etc.

Maybe extending this, add the ability to create "schedules" where you can specify hours of the day, days of the week, and public holidays, etc. and then be able to attribute a schedule to one or more Monitors.

**Comment by Pretender1988** [comment]
> This is probably more difficult to do well than it sounds. What about weekends? Public holidays? etc.
> 
> Maybe extending this, add the ability to create "schedules" where you can specify hours of the day, days of the week, and public holidays, etc. and then be able to attribute a schedule to one or more Monitors.

I agree with the point of a weekend but I would not like to monitor as well on a holiday etc.

I can not execute the change because I have no clue. I just wanted to let you know about a good and nice feature. 
I would be also happy to just check it daily and not care about weekends or holidays.

**Comment by Pretender1988** [comment]
Hi,
many Thanks, I am testing it now and it looks already good. The only issue is the case: if it is still up and running but it should not! it will not notify me. 
But this is already a nice helping feature!

**Comment by Pretender1988** [comment]
> Please check 1.19.0-beta, you can define maintenance time period.

Hi,
many Thanks, I am testing it now and it looks already good. The only issue is the case: if it is still up and running but it should not! it will not notify me.
But this is already a nice helping feature!

**Comment by bdsoha** [comment]
> This is probably more difficult to do well than it sounds. What about weekends? Public holidays? etc.
> 
> Maybe extending this, add the ability to create "schedules" where you can specify hours of the day, days of the week, and public holidays, etc. and then be able to attribute a schedule to one or more Monitors.

Or simply use `cron` syntax.

**Comment by CommanderStorm** [comment]
> The only issue is the case: if it is still up and running but it should not! it will not notify me. But this is already a nice helping feature!

Maintanance mode can also help you there by blocking out the time period which in which a monitor should not be active.
Just add a monitor in upside-down mode and specify when you would like the server to be down (=you're getting notified when that monitor fails). 

Given that this feature is resolved, could you close this issue?

**Comment by CommanderStorm** [comment]
> it looks already good. The only issue is the case: if it is still up and running but it should not! it will not notify me.

> Maintanance mode can also help you there by blocking out the time period which in which a monitor should not be active.

Closing as resolved
