### ISSUE TITLE
Ability to Duplicate Monitors (UI Improvement)

### ISSUE THREAD

**Issue by PJ1004** [louislam/uptime-kuma#2319]
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

UI Feature

### 🔖 Feature description

I'd love to be able to simply click 'Duplicate' or 'Copy' on an existing Monitor for a similar monitor that has a minor change such as a url and name change but otherwise is identical to the original Monitor being copied.

Retention of the tags, notification, and all other settings would be ideal.

### ✔️ Solution

-     A button next to a monitor that when clicked would duplicate the monitor configuration

### ❓ Alternatives

 - the ability to create and then use a template could be considered for types of monitors (for example a web server template with notification settings pre-configured)

**Comment by zorrobiwan** [comment]
Would be great :)

**Comment by mateuszdrab** [comment]
I'd also love that feature

**Comment by taimaiduc** [comment]
Up This will very useful in case we have a lot if config

**Comment by Saibamen** [comment]
@louislam please close this as duplicated of #565
