### ISSUE TITLE
Add timestamp to notifications

### ISSUE THREAD

**Issue by ctrlbrk42** [louislam/uptime-kuma#232]
Sometimes the notifications are not received (or sent) on time, for various such as no internet.

In this scenario, I'm receiving email alerts later but don't know from the alert the exact time the event itself was triggered.

Would appreciate adding a pretty date/time to notifications.

Thank you to the dev(s)

**Comment by tgxn** [comment]
Some notifications do seem to have timestamps; I'm looking at notification content in #315 perhaps you could add some examples of what format you might appreciate?

for reference; for pushbullet I get something like this:  
![image](https://user-images.githubusercontent.com/293107/131858106-c980a9cd-10f1-4e87-be47-4d38c1f5edd1.png)

I kinda want to have standard notification content for each platform, but not sure on certain platform's intricacies, so not sure about email alerts (yet), could you attach what they look like?
