### ISSUE TITLE
Can we sent notification on timeout?

### ISSUE THREAD

**Issue by fzn0x** [louislam/uptime-kuma#2323]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

I need to sent notification to Slack on timeout, is that possible?

### 🐻 Uptime-Kuma Version

1.18.5

### 💻 Operating System and Arch

Debian 10

### 🌐 Browser

Version 107.0.5304.107 (Official Build) (64-bit)

### 🟩 NodeJS Version

16.18.1

**Comment by rezzorix** [comment]
Timeout would mean monitored service is considered as down; so yes you can send a notification. You can even set the “accepted [status codes](https://en.m.wikipedia.org/wiki/List_of_HTTP_status_codes)” for a HTTP(s) monitor if a timeout eg results in an error page.

**Comment by zenyr** [comment]
btw: #2142 would allow you to specify timeout milliseconds but still awaiting merge. 😅

**Comment by fzn0x** [comment]
> btw: #2142 would allow you to specify timeout milliseconds but still awaiting merge. 😅

Thank you for the update!
