### ISSUE TITLE
add MongoDB ping monitor

### ISSUE THREAD

**Issue by rmarops** [louislam/uptime-kuma#2329]
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

New Monitor

### 🔖 Feature description

PR #2328 adds a MongoDB monitor that connects to the specified database and executes a mongo db ping.

### ✔️ Solution

Based on the other database support however the Query block has been removed as (in my opinion) typical select statements are a bit tricky on mongo.  Instead I decided on the builtin ping.

The [ping](https://www.mongodb.com/docs/manual/reference/command/ping/#mongodb-dbcommand-dbcmd.ping) command is a no-op used to test whether a server is responding to commands

### ❓ Alternatives

TCP Port check on if the port is listening though I think a db check should be a bit more thorough by performing a db auth and mongo db ping (minimum).

**Comment by Amirilw** [comment]
Yes please

**Comment by Prajwal433** [comment]
Please Add It Would Be A Great Thing
