### ISSUE TITLE
Multiple Notification

### ISSUE THREAD

**Issue by My-Solu** [louislam/uptime-kuma#233]
I get an single notification when website is down can we have option to get multiple notification eg : very 5min or 30min customizable. Until the website issue is resolved

**Comment by oooowiii** [comment]
very very need

**Comment by deefdragon** [comment]
it appears GitHub missed it, but I referenced this in #478

**Comment by rwjack** [comment]
This seems like a highly requested feature. For starters, there should be an option to repeat notifications if not resolved within X time.

This feature should be quite simple to implement and can be easily further expanded with additional conditions, repeat send notification to Y notification method for X time on days M, TU, W, and on F, SA, SU, use notification method Z, etc...

**Comment by iambkramer** [comment]
any progress on this request?

**Comment by LaserKaspar** [comment]
This is a really important feature. I forgot about the notification and just realised that my service was down for like 20 days.

**Comment by rwjack** [comment]
> I forgot about the notification and just realised that my service was down for like 20 days.

lmao

Yeah I realized this feature actually exists just yesterday.

When you edit a monitor, the last option configures after how many chained fails the notification is resent.

Now we just need an option to bulk edit monitors, and set monitor groups, which can be edited in bulk as well.
