### ISSUE TITLE
It allows the user agent to be registered when monitoring HTTP

### ISSUE THREAD

**Issue by yangs1202** [louislam/uptime-kuma#2331]
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

UI Feature

### 🔖 Feature description

It is intended to verify that it is an internal check system through a user agent.

By default, you send "Uptime Kuma"
Allows the user to put the User Agent in the character set by the user.

### ✔️ Solution

UI: Allows the user to input a user agent to be used for monitoring.

Monitor: Check Health with User Agent input from UI.

**Comment by rezzorix** [comment]
You already can customize/modify the HTTP headers; and with this also the user-agent.

Syntax:
`
User-Agent: <product> / <product-version> <comment>`

**Comment by chakflying** [comment]
Closing since this should be solved.
