### ISSUE TITLE
Widget to grab the Uptime Status

### ISSUE THREAD

**Issue by 97WaterPolo** [louislam/uptime-kuma#234]
**Is it a duplicate question?**
No feature requests seem like they have this feature described

**Is your feature request related to a problem? Please describe.**
I have a landing page which has a nice overview of the information from other sources, but I would like just a small section dedicated to Uptime Kuma this way I can quickly check that it is all good and if I see any errors go into the actual Web UI

**Describe the solution you'd like**
An endpoint or widget in which I can add it to my other website and it would render the Uptime Kuma summary on the left side (see attached photo)

**Describe alternatives you've considered**
One alternative I was thinking was on my landing page load to load a screenshot of that specific div taken from Puppeteer and load that on my landing page.

**Additional context**
It would be nice just to have it hit http://my-uptime-kuma/widget and return HTML that would generate the left side summary (see attached)
![image](https://user-images.githubusercontent.com/6467276/130318305-16e4172b-1db8-403c-b46d-30131f50729e.png)
![asdasd](https://user-images.githubusercontent.com/6467276/130318376-d2c8de38-1e6b-45a2-a0b3-a404fad35351.png)

**Comment by 97WaterPolo** [comment]
![asdasd](https://user-images.githubusercontent.com/6467276/130318376-d2c8de38-1e6b-45a2-a0b3-a404fad35351.png)

**Comment by louislam** [comment]
```html
<iframe src="http://<your_domain>/list" width="500" height="600"></iframe>
```

maybe a workaround for this.



![image](https://user-images.githubusercontent.com/1336778/130346204-907b0c2a-6a02-4e97-964a-754ebefd209d.png)

**Comment by 97WaterPolo** [comment]
So navigating to **http://192.168.68.114:3001/list** nothing is displayed. Where do you go to find the valid endpoint urls for Uptime Kuma? It is the same background color as the rest of the style but nothing is rendered, almost like a default page for any endpoint that is invalid. Is there another location for it to be?

**Comment by EclipseOfficeTech** [comment]
> So navigating to **http://192.168.68.114:3001/list** nothing is displayed. Where do you go to find the valid endpoint urls for Uptime Kuma? It is the same background color as the rest of the style but nothing is rendered, almost like a default page for any endpoint that is invalid. Is there another location for it to be?

Update to latest 1.3.2 and /list will be available

**Comment by eSeR1805** [comment]
http://my-uptime-kuma/dashboard/list or now you can make status pages http://my-uptime-kuma/status/my-status-page

**Comment by CommanderStorm** [comment]
@97WaterPolo
Could you please check if this issue is still an active issue?
This seems like it is resolved.

**Comment by chakflying** [comment]
Closing as resolved.
