### ISSUE TITLE
Aggregated entities

### ISSUE THREAD

**Issue by derekoharrow** [louislam/uptime-kuma#2340]
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

Other

### 🔖 Feature description

It would be great to have "aggregated entities" which comprise multiple other entities.

As an example, I may have 3 different monitors for the same thing - e.g. a Docker container, a TCP port, and an HTTP gui.

### ✔️ Solution

It would be great to be able to group these under one entity which assumes the state of the sub-devices.

This could be set to "any" or "all" status, which "any" being that it is down when any of the sub-entities are down and "all" being that it is down when all sub-entities are down (with the possibility of inverting it as you can already with other types).

This could make status pages, etc. much simpler too as you could use the aggregate entity instead of individual ones.

Thanks!

**Comment by CommanderStorm** [comment]
@derekoharrow 
Monitoring groups ("any") were implemented in https://github.com/louislam/uptime-kuma/pull/2693 and merged into `1.22.x`
"all" is tracked in https://github.com/louislam/uptime-kuma/issues/1089 or https://github.com/louislam/uptime-kuma/issues/2487

=> closing as resolved
