### ISSUE TITLE
Possible to monitor IPs on the LAN using Mac ?

### ISSUE THREAD

**Issue by gchattha** [louislam/uptime-kuma#2347]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

Hi, I'm running Docker on an M1 Mac and as far as I can tell you can't use host networking on it which i think is required to see hosts on the main LAN network. I want to use Uptime Kuma to ping devices on my home network, not other docker container IPs or anything on the Internet but devices on my wired and wireless network. Is there a way to do this while running under Docker on Mac? Thanks.

### 🐻 Uptime-Kuma Version

1.18.5

### 💻 Operating System and Arch

macOS Ventura

### 🌐 Browser

Edge

### 🐋 Docker Version

20.10.17

**Comment by louislam** [comment]
It's a docker question, you can run in host mode or bridge mode

https://stackoverflow.com/questions/56825258/difference-between-docker-bridge-and-host-driver

**Comment by gchattha** [comment]
Thanks, dug into it a bit further and host mode is only supported in Linux - not Mac or Windows so this software won't work in my environment to monitor devices on the same network as my host using Mac :( - https://docs.docker.com/network/host/

**Comment by 404invalid-user** [comment]
You could host it natively
