### ISSUE TITLE
Dependent entities

### ISSUE THREAD

**Issue by derekoharrow** [louislam/uptime-kuma#2348]
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

Other

### 🔖 Feature description

In some situations, you may have a service that is dependent upon another service being available.

For example, you may wish to do an HTTP GET on a URL to check if a website is up. But that HTTP GET request may be dependent on your DNS server working.

So, you may have multiple related monitors - one for DNS and one for HTTP in this example.

It would be great to be able to list/tag the monitors that a monitor is dependent on. In this case, the HTTP monitor is dependent upon the DNS monitor.

There is no point checking the HTTP monitor if the DNS monitor is down, and the HTTP monitor state can be assumed as down if the dependent DNS service is down too (optional).

### ✔️ Solution

Add a multi-select to each Monitor that allows you to select which other monitors it is dependent upon.

If any of those dependent monitors are down, then there is no point monitoring the parent monitor and it's state can be assumed as down.

**Comment by mabed-fr** [comment]
Like https://github.com/louislam/uptime-kuma/issues/2261 ?

**Comment by CommanderStorm** [comment]
@derekoharrow   
We are consolidating duplicate issues a bit to make issue management easier.
I think, we should track this issue in https://github.com/louislam/uptime-kuma/issues/1089 as there is no functional difference (maybe just small naming differences, but nothing that would require a different issue imo)
=> I am going to close this as a duplicate
