### ISSUE TITLE
v1.3.0 - High CPU/Memory usage

### ISSUE THREAD

**Issue by R0GGER** [louislam/uptime-kuma#235]
**Is it a duplicate question?**
No.

**Describe the bug**
Uptime Kuma v1.3.0     
Very high CPU and memory usage with 20 or more active monitors with a 60s interval.    
CPU is constantly on 40% and system is running out off memory.     
 
![tXzFGA](https://user-images.githubusercontent.com/8298741/130321617-fed51a01-eb32-43ec-9daa-1f2524968f2a.png)

Downgraded back to 1.2.0, problem solved. :confused:      

**Info**
- Uptime Kuma Version: 1.3.0
- System: VPS - 2 CPU cores, 35GB HDD, 1024MB RAM
- Using Docker?: Yes
- OS: Debian 10
- Browser: Chrome, Firefox

**Comment by R0GGER** [comment]
I guess what happens is... If you have two (2) or  more uptime-kuma containers running within the same server socket.io is already in use. 

My setup:    

port: 3001    
docker-compose -f uptime-1.yml -p uptime-1 up -d    
    
port: 3002    
docker-compose -f uptime-2.yml -p uptime-2 up -d

**Comment by R0GGER** [comment]
**Error:**
```
uptime         | terminate called after throwing an instance of 'std::bad_alloc'
uptime         |   what():  std::bad_alloc
```

**Comment by louislam** [comment]
Thanks for the report, can confirm that 1.3.0 uses more RAM than 1.2.0. Will try to find out.

**Comment by louislam** [comment]
Should be fixed in 1.3.1

The main reason is node-sqlite3 uses more RAM unexpectedly if I disabled the knex.js pool. So I re-enable back the pool with max 5, hope it can balance between the performance and the memory usage.

![image](https://user-images.githubusercontent.com/1336778/130331296-a8cac5f5-68ee-4e81-b37c-28f9878595d3.png)

**Comment by R0GGER** [comment]
Thanks! Yup... problem solved.

**Comment by louislam** [comment]
> Thanks! Yup... problem solved.

Sadly, 1.3.1 still have problem over time. 1.3.2 should be fixed.

**Comment by R0GGER** [comment]
> > Thanks! Yup... problem solved.
> 
> Sadly, 1.3.1 still have problem over time. 1.3.2 should be fixed.

Thanks! This is a SQLite problem... 

> This connection pool has a default setting of a min: 2, max: 10 for the MySQL and PG libraries, and a single connection for sqlite3 (due to issues with utilizing multiple connections on a single file).

Source: https://knexjs.org/#Installation-pooling
