### ISSUE TITLE
Monitor blackout period

### ISSUE THREAD

**Issue by AckItsMe** [louislam/uptime-kuma#2355]
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

Other

### 🔖 Feature description

Would it be possible for you to add a feature to set blackout periods for a particular monitor?   For example, I have a server that goes offline for 5 minutes once a week to pull a backup.   I get alerts when the services are unavailable and all clears when it is back up.  I would like to instead put in a blackout period so it would halt monitoring, or at least halt reporting, during that time.

Thank you.   I have found your tool to work really well.

### ✔️ Solution

Add a blackout period field to enter a day/time range when the monitor would either not monitor or not report outages.

**Comment by koen20** [comment]
A maintenance planning system was added in the latest beta which I think does what you describe. It is possible to schedule weekly maintenance and stop monitoring during that time.
https://github.com/louislam/uptime-kuma/releases/tag/1.19.0-beta.0
