### ISSUE TITLE
Support monitoring HTTP servers by their IP addresses

### ISSUE THREAD

**Issue by RuijieYu** [louislam/uptime-kuma#2356]
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

New Monitor

### 🔖 Feature description

Allow:
```markdown
- Monitor Type: 
  - HTTP(s)
- Friendly Name
  - name
- URL
  - http://1.2.3.4:5678/
```

Currently it complains that the format is incorrect. 

### ✔️ Solution

See description. 

### ❓ Alternatives

Alternatively I could use TCP ping, but HTTP using raw IP addresses should be allowed.  

### 📝 Additional Context

None

**Comment by mtelgkamp** [comment]
I do not have any problem creating a monitor with a valid IP address and also the check did work for me.

Screenshot from demo instance:
![screenshot of monitor using IP Address](https://user-images.githubusercontent.com/33117529/204810670-f2455be1-8683-40c8-8287-caa63bd87a92.png)

**Comment by RuijieYu** [comment]
Thanks for taking a look. I am no longer able to reproduce the issue on my docker instance, even with my original IP-port pair, so I guess I should close as invalid issue, and sorry for the noise. 

For reference, the image I am using is this:
```console
$ docker images
REPOSITORY               TAG       IMAGE ID       CREATED         SIZE
louislam/uptime-kuma     1         930a7e08142f   7 weeks ago     350MB
...
```
