### ISSUE TITLE
WHAT DO?

### ISSUE THREAD

**Issue by mksir12** [louislam/uptime-kuma#2357]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

Bro i run it, it showing  this
![Screenshot_20221127_170805](https://user-images.githubusercontent.com/116490353/204133235-ec11e6c8-a2b5-4bf8-9765-ecf651b4b9b2.jpg)

Please reply me 😥

### 🐻 Uptime-Kuma Version

In replit 

### 💻 Operating System and Arch

replit in mobile

### 🌐 Browser

Internet browser

### 🐋 Docker Version

I dont know

### 🟩 NodeJS Version

In replit

**Comment by TheFrenchGhosty** [comment]
I feel sorry for the dev...

**Comment by mksir12** [comment]
> 

Ok

**Comment by ShadowGaming100** [comment]
> ### ⚠️ Please verify that this bug has NOT been raised before.
> * [x]  I checked and didn't find similar issue
> 
> ### 🛡️ Security Policy
> * [x]  I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)
> 
> ### 📝 Describe your problem
> Bro i run it, it showing this ![Screenshot_20221127_170805](https://user-images.githubusercontent.com/116490353/204133235-ec11e6c8-a2b5-4bf8-9765-ecf651b4b9b2.jpg)
> 
> Please reply me 😥
> 
> ### 🐻 Uptime-Kuma Version
> In replit
> 
> ### 💻 Operating System and Arch
> replit in mobile
> 
> ### 🌐 Browser
> Internet browser
> 
> ### 🐋 Docker Version
> I dont know
> 
> ### 🟩 NodeJS Version
> In replit

Hi I can give you the project already installed

**Comment by ShadowGaming100** [comment]
But need setup
