### ISSUE TITLE
Display server timezone in notifications in general.

### ISSUE THREAD

**Issue by TheBakaBandit** [louislam/uptime-kuma#2360]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### Description

Timezone is still wrong in release in push notifications as reported in issue [40](https://github.com/louislam/uptime-kuma/issues/40).

This is the notification:

![image](https://user-images.githubusercontent.com/105791865/204861887-e9beebd3-2bec-42fe-9045-7a2572448665.png)

This is the settings page:

![image](https://user-images.githubusercontent.com/105791865/204862093-42e1cc40-88f4-42be-9f56-491e4c8ebf81.png)

### 👟 Reproduction steps

Set server and display timezone in settings, trigger a notification on a monitor.

### 👀 Expected behavior

The Time Zone and time in the notification would be as set in the settings.

### 😓 Actual Behavior

The Time Zone and time in the notification remain UTC

### 🐻 Uptime-Kuma Version

1.19.0-beta.0

### 💻 Operating System and Arch

Rocky Linux 8.6 (Green Obsidian)

### 🌐 Browser

Version 107.0.5304.108 (Official Build) (64-bit)

### 🐋 Docker Version

Docker version 20.10.2

**Comment by migtarx** [comment]
I would say this issue is not just in discord notifications. It also happends in pushover as well.

**Comment by TheBakaBandit** [comment]
Yes, we have tested in mattermost too and the same thing occurs.

**Comment by befantasy** [comment]
same problem with slack

**Comment by EdyDeveloper** [comment]
Does anyone know if this will be fixed?

**Comment by runchunzhang** [comment]
Does anyone know if this will be fixed?
![image](https://user-images.githubusercontent.com/18542704/215370571-92209b79-e40b-43e2-96c1-e1c9bd6c134b.png)

**Comment by radiohead-lab** [comment]
Hi Everyone,
Issue is still there with Discord notifications! Any plan to fix it?
Thx in advance.

**Comment by Skyfay** [comment]
I would also be happy if the time is displayed correctly in the Discord notifications. Is that so complicated to implement?

**Comment by jtxnn678** [comment]
Same Timezone issue.

Received notification Email contents:
[Nextcloud] [✅ Up] 200 - OK
Time (UTC): 2023-06-10 12:35:25.844

Actual local time is 20:35 (UTC +08:00)

**Comment by CommanderStorm** [comment]
@TheBakaBandit I accidentally did not tag this issue in #3203

Could you close this issue?
This will be included in the next release [(it is just around the corner)](https://github.com/louislam/uptime-kuma/milestone/31)
