### ISSUE TITLE
Add how long was down, when sending up notification.

### ISSUE THREAD

**Issue by ForceConstant** [louislam/uptime-kuma#2362]
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

New Notification

### 🔖 Feature description

It would be useful for me that when a service goes down, and then comes back up, that the notification says how long it was down for. 

### ✔️ Solution

Notification would look like:
[Service] [Up] Was down for 3:12 minutes.

**Comment by ramymoh** [comment]
I really need this and will be very helpful

**Comment by honestlai** [comment]
Bump
Would love to have this as well, it's the only reason I haven't moved off of UpTimeRobot

**Comment by CommanderStorm** [comment]
@ramymoh @honestlai 
Please refrain from posting `+1` / requests for updates things on issues, as this makes issue-management harder.
Issues are for discussing what needs to be done how by whom.
[We use 👍🏻 on issues to prioritise work](https://github.com/louislam/uptime-kuma/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).

**Comment by CommanderStorm** [comment]
Duplicate of #177 => closing and continuing to track there
