### ISSUE TITLE
Version as a sensor in HA

### ISSUE THREAD

**Issue by Coolie1101** [louislam/uptime-kuma#2364]
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

Other

### 🔖 Feature description

Get Uptime Kuma Server Version as a Sensor in HA.

### ✔️ Solution

Get Uptime Kuma Server Version as a Sensor in HA.

### ❓ Alternatives

Don't know of any.

**Comment by dannymertens** [comment]
https://github.com/meichthys/uptime_kuma/blob/main/README.md

Something like this?

**Comment by Coolie1101** [comment]
No, a sensor that shows the version currently installed, and if possible, an update is available.
![image](https://github.com/louislam/uptime-kuma/assets/28989417/67f5980d-7df3-4223-84a9-ace18c9ba103)

**Comment by CommanderStorm** [comment]
We currently don't maintain a home assistant add-on.

You are likely referring to https://github.com/hassio-addons/addon-uptime-kuma from our https://github.com/louislam/uptime-kuma/wiki/%F0%9F%94%A7-How-to-Install#home-assistant-add-on-unofficial 
Please raise the issue at the correct repository

**Comment by Coolie1101** [comment]
Oops, sorry about that.
