### ISSUE TITLE
Status page: Custom Links in Footer and Description

### ISSUE THREAD

**Issue by codedust** [louislam/uptime-kuma#2365]
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

UI Feature

### 🔖 Feature description

I would like to link to an imprint / legal notices in the status page footer. Currently, the footer is text-only.

### ✔️ Solution

It would be nice to be able to include an imprint using Markdown or html:

```markdown
[Imprint](https://example.org/imprint)
```

```html
<a href="https://example.org/imprint">Imprint</a>
```

### ❓ Alternatives

An alternative would be to add custom fields for links with imprint and privacy policies:

Mockup of the config sidebar:

![grafik](https://user-images.githubusercontent.com/7175914/205633571-b06620c9-ec93-4aec-a4a5-86f3c5dde498.png)

**Comment by Kinuseka** [comment]
This is needed

**Comment by fabbaum** [comment]
Would be very helpful. Looking for the exact same possibility.

**Comment by Computroniks** [comment]
I will have a look into this this week
