### ISSUE TITLE
Agent for Microsoft Windows 

### ISSUE THREAD

**Issue by kristianrl** [louislam/uptime-kuma#2368]
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

New Monitor

### 🔖 Feature description

I would like a Windows agent/monitor that supplies information such as
- disk space for each disk (total/free)
- memory (total/free)
- cpu utilization (%)

The agent sends its data every X minutes to uptime-kuma.

Later on
- List and state of all running services

### ✔️ Solution

I could code the agent myself if you're interested. However, I will need some additional documentation for delivering the data, and that you prepare uptime-kuma to handle this data.

**Comment by manhmz** [comment]
I suppose this would be security risk and won't be added

**Comment by jeff0485** [comment]
As a suggestion for basic functionality, you could use a PUSH monitor with your basic status messages encoded into the GET request.
Example: http://uptime:3001/api/push/6ujknb9OpL?status=up&msg=this%20is%20my%status&ping=

**Comment by kristianrl** [comment]
@jeff0485, yes, that was basically my concept.
I have decided to use [Site24x7](https://www.site24x7.eu/) as it has all the features I need.
