### ISSUE TITLE
Sql Server Monitor Failing

### ISSUE THREAD

**Issue by bfreeman-RN** [louislam/uptime-kuma#2370]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

I'm trying to cerate a monitor for an Amazon RDS Sql Server instance.  I'm running Uptime Kuma through Docker on an Ubuntu 22.04 VM in EC2.  I have other monitors configured and working fine.  I have the sql server monitor configured to use an account that only has SELECT rights to a [Country] table.  I've been able to telnet to the db server in question from inside of the container on port 1433, so there is no firewall/port issue.

Connection String: Server=[server].[something].[region].rds.amazonaws.com,1433;Database=[db name];User ID=[user];Password=[pass]

Query:
SELECT TOP 1 [ISOCode2] FROM [dbo].[Country]
GO

Everything else is default.

Have I done something wrong?  Is there a log file that I can check in order to determine the reason for the failure?

### 🐻 Uptime-Kuma Version

1.18.5

### 💻 Operating System and Arch

Ubuntu 22.04 w/ Docker 64-bit

### 🌐 Browser

Chrome Version 107.0.5304.122 (Official Build) (64-bit)

### 🐋 Docker Version

20.10.21, build baeda1f

### 🟩 NodeJS Version

v16.17.0

**Comment by louislam** [comment]
what is the error?

**Comment by bfreeman-RN** [comment]
> what is the error?

Failed to connect to [server].[something].[region].rds.amazonaws.com:1433 in 15000ms

**Comment by louislam** [comment]
Try `TrustServerCertificate=Yes` or `Encrypt=false` to your connection string.

Reference: https://github.com/louislam/uptime-kuma/pull/1636#issuecomment-1152928494

**Comment by bfreeman-RN** [comment]
TrustServerCertificate=True did the trick!

Is there a location where I can see log information about this sort of thing?

**Comment by louislam** [comment]
> TrustServerCertificate=True did the trick!
> 
> Is there a location where I can see log information about this sort of thing?

Sometimes it is just a guess, because SQL Server or the library doesn't return a meaningful error message.

**Comment by Nick390** [comment]
Wouldn't it be better to put a wiki explaining how to connect and all the arguments.

**Comment by Nick390** [comment]
Wouldn't it be better to put a wiki explaining how to connect and all the argument's
