### ISSUE TITLE
Custom DNS hostname check 

### ISSUE THREAD

**Issue by elatedmind** [louislam/uptime-kuma#2378]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

if i want to add random host name, like (_s2198943734jddfjjkdf923823.example.com) to check if TXT record exists I get an error: that my host name is invalid, but if I do simple www.example.com - then everything is OK. Is there some kind of validation in input field?

### 🐻 Uptime-Kuma Version

Version: 1.18.5

### 💻 Operating System and Arch

Ubuntu 20.04.5 LTS

### 🌐 Browser

Firefox 107.0.1

### 🐋 Docker Version

Docker version 20.10.12, build 20.10.12-0ubuntu2~20.04.1

**Comment by niuhuheyi** [comment]
is too hard i can,t help you

**Comment by louislam** [comment]
It is not possible currently. It cannot compare the result.

**Comment by simplify123** [comment]
i meet the same problem. i use bind9(192.168.1.111) as my dns server ➡ www.mydomain.test   192.168.1.130，when i set my computer primary dns server to 192.168.1.111，i can directly open www.mydomain.test，but uptime-kuma always tell me error. then i set url in uptime-kuma to 192.168.1.130, its work well,how to fix it?
