### ISSUE TITLE
HTTP(S) Keyword - Upside Down does not evaluate the keyword

### ISSUE THREAD

**Issue by begna112** [louislam/uptime-kuma#2380]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### Description

I'm trying to use Uptime Kuma to monitor (among other things) if my internet cuts over to my backup LTE connection from my fiber line. 

I can accomplish monitoring of the fiber line with a static IP  just fine by using an ip api service for example:
```
https://api.ipify.org?format=json
keyword: W.X.Y.Z
```

but LTE will get whatever IP the carrier decides to give it, with no static option. 

So for that condition, I'd want to check if it *didn't* match the same keyword as above. 

I would assume that "upside down" mode would complete full validation of the success criteria and then reverse it. Instead it seems to revert back to only if there's a response without the keyword criteria.

I *think* this qualifies as a bug? But I could easily see it being a question or a feature request. But my first instinct is that it's not working how it should, so filing it as a bug.

### 👟 Reproduction steps

1. Set an HTTP(S) Keyword check with a keyword you know won't be in the response.
2. Set the "upside down" field.

### 👀 Expected behavior

Expect the service to be UP, because it's receiving a response, but the keyword isn't found.

### 😓 Actual Behavior

The service is DOWN, because it received any response at all.

### 🐻 Uptime-Kuma Version

1.18.5

### 💻 Operating System and Arch

docker

### 🌐 Browser

any

### 🐋 Docker Version

any

**Comment by louislam** [comment]
I don't quite understand your use case, but I followed your reproduce steps and cannot reproduce the issue.

URL: https://api.ipify.org?format=json
Keyword: 255.255.255.255
Upside Down Mode: Enable

It's UP in my side.

![image](https://user-images.githubusercontent.com/1336778/206658641-e0816897-6ea8-46c1-97d5-1ab61e87474d.png)

**Comment by begna112** [comment]
I think the service was caching my IP or something. Looks like this is a non-issue, my bad.
