### ISSUE TITLE
SQL Server without certificate

### ISSUE THREAD

**Issue by AndrewSpec** [louislam/uptime-kuma#2384]
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

Other

### 🔖 Feature description

I'd like to have an option to ignore SQL Server connection errors when the server uses only self signed certificate..

### ✔️ Solution

Checkbox on the edit SQL Server settings to ignore certificate errors.

**Comment by louislam** [comment]
You can do it by connection string

https://github.com/louislam/uptime-kuma/pull/1636#issuecomment-1155175745

**Comment by AndrewSpec** [comment]
Ok, got it working.
