### ISSUE TITLE
Cloudflared showing as not installed even though it is

### ISSUE THREAD

**Issue by cleverActon0126** [louislam/uptime-kuma#2385]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

So I run Uptime Kuma ("**UK**) with Node.js and PM2, and I am trying to reverse proxy it to my domain. But when I finished installing cloudflared UK shows that I had not installed cloudflared although I have. I am not sure if there's something wrong with cloudflared or UK but one thing that was weird to me was that the installation file (.exe) was not able to install cloudflared (was cmd with no logs for like 30 minutes straight) and I have installed it with the MSI file. Is there something wrong here?

### 🐻 Uptime-Kuma Version

1.18.5

### 💻 Operating System and Arch

Windows 10 22621.900 x64

### 🌐 Browser

Google Chrome 109.0.5414.36

### 🟩 NodeJS Version

19.1.0

**Comment by cleverActon0126** [comment]
Yup, I have restarted Uptime Kuma and it still won't work. I've just tried the portable method and it gives me "Unable to locate config file" when I try `cloudflared --verison`. Not sure what I can do for the next step now.

**Comment by Kraleemil** [comment]
Have you any updates, i am trying to get it to work too

**Comment by cleverActon0126** [comment]
nope, still not working

**Comment by Kraleemil** [comment]
> nope, still not working

Let me know if theres any fix

**Comment by questgugou** [comment]
sorry i don't know

**Comment by rezzorix** [comment]
> Yup, I have restarted Uptime Kuma and it still won't work. I've just tried the portable method and it gives me "Unable to locate config file" when I try `cloudflared --verison`. Not sure what I can do for the next step now.

Have you completely uninstalled the regular version before trying the portable version?

**Comment by cleverActon0126** [comment]
Yep.
Sadly both didn't work
