### ISSUE TITLE
Show last time a service was monitored

### ISSUE THREAD

**Issue by vespino** [louislam/uptime-kuma#2386]
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

UI Feature

### 🔖 Feature description

The dashboard now shows that date a monitor was added. Is this useful and wouldn’t it be better to show the latest uptime check?

### ✔️ Solution

Show the last time the monitor was executed.

**Comment by QuikBolte** [comment]
A must have!

**Comment by vespino** [comment]
@dmkjr I would say the last time the uptime check was performed no matter the outcome. Another way of handling this would be 3 columns: added (the current column), last success, last error

**Comment by louislam** [comment]
![image](https://user-images.githubusercontent.com/1336778/207013579-13a92c30-6818-493a-a042-9b96eaf64efa.png)

You can hover to the last beat.
