### ISSUE TITLE
How to add new user?

### ISSUE THREAD

**Issue by guillermodep** [louislam/uptime-kuma#2388]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

I would like to add diferents users to login in Kuma, how can I do it? 

### 🐻 Uptime-Kuma Version

louislam/uptime-kuma:1

### 💻 Operating System and Arch

Ubuntu 20.04.5 LTS

### 🌐 Browser

Chrome 

### 🐋 Docker Version

20.10.12

### 🟩 NodeJS Version

Node.js version: 16

**Comment by dmkjr** [comment]
This is currently not available.
