### ISSUE TITLE
Email notifications

### ISSUE THREAD

**Issue by adm2k** [louislam/uptime-kuma#2396]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

I have created a HTTP(s) monitor with a keyword. I first have to login to the site (NTLM authentication works fine) and then look for the keyword.

The question is, how do I get an email notification when just the keyword is found and **no email** when it is not found. For example, if the keyword "new" is found send email and if not found **do not** send email.

Thanks...

### 🐻 Uptime-Kuma Version

1.18.5

### 💻 Operating System and Arch

Ubunto Server 22.04

### 🌐 Browser

Version 108.0.5359.75 (Official Build) (64-bit)

### 🐋 Docker Version

Docker version 20.10.17, build 100c70180f

**Comment by rezzorix** [comment]
Just switch on the option “Upside Down Mode”. 
It will turn the logic for notifications around.

**Comment by adm2k** [comment]
Flipped to "Upside Down Mode" and it still sent me an email

**Comment by rezzorix** [comment]
Sorry, of course... it will send the notification whenever the status changes - my bad I didnt think that through.

Good point also maybe at @louislam to actually change this here into a feature-request: 

"Choose notification trigger" 

Could/should be 3 options:
- notification when status changes to up only
- notification when status changes to down only
- notification on any status change

**Comment by adm2k** [comment]
Having notification options would be of great help. I have a couple of sites where I just need to log on, check for "keyword" and if found send an alert - otherwise do nothing. 

The "keyword" is not always there and in that case there should be no alert.

Hope that makes sense!
