### ISSUE TITLE
follow the step to use Cloudflare Tunnel but error

### ISSUE THREAD

**Issue by 8ty** [louislam/uptime-kuma#2398]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

![image](https://user-images.githubusercontent.com/92656899/207293825-f48ece5d-e48c-4d49-a038-cfbcc0f99e7d.png)

### 🐻 Uptime-Kuma Version

1.18.5

### 💻 Operating System and Arch

ubuntu 20

### 🌐 Browser

edge 108

**Comment by 8ty** [comment]
help needed!

**Comment by louislam** [comment]
You should provide more info. No one can help with just 403 message.
