### ISSUE TITLE
Getting notification in the middle of the night

### ISSUE THREAD

**Issue by Kraleemil** [louislam/uptime-kuma#2400]
### ⚠️ Please verify that this bug has NOT been raised before.

- [x] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

I am getting a notification for all the things i monitor at 5 am that they are all up, is that normal

### 🐻 Uptime-Kuma Version

Not sure installed it yesterday 

### 💻 Operating System and Arch

Windows 10 Pro

### 🌐 Browser

Brave

**Comment by louislam** [comment]
You can set `Retries` to 2 or more to avoid the notifications sent immediately for a small downtime.

**Comment by Kraleemil** [comment]
> You can set `Retries` to 2 or more to avoid the notifications sent immediately for a small downtime.

I am going to try that. But it was local services so its kinda werid

**Comment by louislam** [comment]
Usually because your Uptime Kuma's network was down, Uptime Kuma could not send out the down message.

**Comment by Kraleemil** [comment]
Thx but can you help in #2385 ?

**Comment by rezzorix** [comment]
You are selfhosting at home?
Could be that your provider resets the connection at that time and you (dynamic) IP changes. 

As louislam already wrote; you can adjust this by setting a retry interval.

**Comment by Kraleemil** [comment]
> You are selfhosting at home?
> Could be that your provider resets the connection at that time and you (dynamic) IP changes. 
> 
> As louislam already wrote; you can adjust this by setting a retry interval. 

It's self hosted and it's not changing IP i have a static and i adjusted and it seems like it works fine
