### ISSUE TITLE
Use regex for MQTT Success Message

### ISSUE THREAD

**Issue by philverghese** [louislam/uptime-kuma#2405]
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

Other

### 🔖 Feature description

**Feature Description:** Allow the user to specify a regex to match a MQTT message to check for success. Currently only an exact match of the entire message is supported.

**Motivation:**
The [Mosquitto MQTT Broker](https://mosquitto.org/) publishes the topic `$SYS/broker/uptime` with a message like `3861 seconds` and that value is updated about every 10 seconds. This value would be ideal for uptime monitoring. 

I found that I'm unable to monitor this topic because the in Uptime Kuma's MQTT monitoring, the message is compared using an exact string match against the "MQTT Success Message". This means I can't even use `seconds` as a success message for this topic that's literally meant to be used to monitor uptime.

I have not used other MQTT brokers, but I suspect the idea of matching a message with a regex would be useful for anyone who wants to monitor a service via MQTT.

### ✔️ Solution

I'm willing to send a PR to do this if you are open to this change. Here's what I think the work would be (and I'm sure I'm missing things)

- [ ] Change [`mqttAsync()` in `util-server.js` (around line 179)](https://github.com/louislam/uptime-kuma/blob/master/server/util-server.js#L179) to use a regex test instead of an exact string match.
- [ ] Update the UI to make it clear that a regex can be used for the "MQTT Success Message"
- [ ] Testing with normal strings, valid regex strings, invalid regex strings

### ❓ Alternatives

For now I'm monitoring a different topic: `$SYS/broker/version` which has a static message with the version number.

### 📝 Additional Context

FYI, the recommended setup for Home Assistant is to use the [Mosquitto MQTT broker add-on](https://github.com/home-assistant/addons/blob/master/mosquitto/DOCS.md), so this is probably a very common broker for home users.

**Comment by netwpl** [comment]
any news on this? i want to use regexp for the "success message".
thanks!

**Comment by wsw70** [comment]
This would be an awesome upgrade of the MQTT sensor.

It would be best if the result could also be checked against something dynamic. Typically I use a "last something" in MQTT messages that represent the heartbeats of an application /service. If this is a timestamp, I would love to check it against "now" and see if the difference is smaller than a threshold.

This would require a way to process the message (a regex or JSON unmarshalling) and a function (TS?) that could take the output as a parameter and return an OK or FAILED message. This would be, I believe, the most flexible way.

**Comment by HolgerAusB** [comment]
Full agreement. That would be very helpful.

In addition to this:

- match if topic has a non-empty message.
- match if topic has an empty/zero-lenght/null message, which is possible and not uncommon. See `mosquitto_pub -n`

**Comment by BenniBenassi** [comment]
Fantastic Idea. I support this

**Comment by mauriceatkinson** [comment]
same here

**Comment by CommanderStorm** [comment]
@BenniBenassi @mauriceatkinson @AwadYoo @netwpl 

Please refrain from posting `+1` / requests for updates things on issues, as this makes issue-management harder.
Issues are for discussing **what needs to be done how by whom**.
[We use 👍🏻 on issues to prioritise work](https://github.com/louislam/uptime-kuma/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc), as always: [Pull Requests](https://github.com/louislam/uptime-kuma/blob/master/CONTRIBUTING.md) welcome.

**Comment by Noschvie** [comment]
Another example: [IOTstack ](https://github.com/SensorsIot/IOTstack) provides heartbeats from the Mosquitto service like this:

```
$ mosquitto_sub -v -h localhost -p 1883 -t "iotstack/mosquitto/healthcheck"
iotstack/mosquitto/healthcheck Mon Oct  9 14:45:22 CEST 2023
iotstack/mosquitto/healthcheck Mon Oct  9 14:45:52 CEST 2023
iotstack/mosquitto/healthcheck Mon Oct  9 14:46:22 CEST 2023
iotstack/mosquitto/healthcheck Mon Oct  9 14:46:53 CEST 2023
iotstack/mosquitto/healthcheck Mon Oct  9 14:47:23 CEST 2023
iotstack/mosquitto/healthcheck Mon Oct  9 14:47:53 CEST 2023
iotstack/mosquitto/healthcheck Mon Oct  9 14:48:23 CEST 2023
iotstack/mosquitto/healthcheck Mon Oct  9 14:48:54 CEST 2023

```
Would be great to evaluate this timestamp. Thanks!
