### ISSUE TITLE
Network Map

### ISSUE THREAD

**Issue by TRristan** [louislam/uptime-kuma#2410]
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

UI Feature

### 🔖 Feature description

a simple network map in which you can put devices with icons and that shows you in color if it is down

### ✔️ Solution

this is an example of a program (the dude), something similar but with the style of interface that the program has now
![Captura de pantalla 2022-11-03 100923](https://user-images.githubusercontent.com/116945812/207605515-676b0593-b514-495c-98f9-9d6d7c900591.png)

**Comment by CommanderStorm** [comment]
I am going to classify this as out of scope/ https://github.com/louislam/uptime-kuma/labels/wontfix.

We are a simple uptime management software => You can model your relationships via groups, but I don't think that adding a network map is something that we can do while sticking to our core UX.

(If you have different ideas or examples we can talk about them)
