### ISSUE TITLE
After exporting the louislam/uptime-kuma container then importing to new server, i get errors.

### ISSUE THREAD

**Issue by thrdgeek** [louislam/uptime-kuma#2411]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

cat mykuma_export.tar.gz | docker import --message "Imported from Mike's laptop" - louislam/uptime-kuma:1

sha256:ceda731d0e13fe6fb434372dc66f2644272ad52792c523dd684549fbbe00d936
root@DCWVM20UBU08043:/home/user/mykuma# 
root@DCWVM20UBU08043:/home/user/mykuma# docker images
REPOSITORY             TAG       IMAGE ID       CREATED         SIZE
louislam/uptime-kuma   1         ceda731d0e13   8 seconds ago   345MB
root@DCWVM20UBU08043:/home/user/mykuma# docker-compose up -d
Creating uptime-kuma ... error

ERROR: for uptime-kuma  Cannot create container for service uptime-kuma: No command specified

ERROR: for uptime-kuma  Cannot create container for service uptime-kuma: No command specified
ERROR: Encountered errors while bringing up the project.
root@DCWVM20UBU08043:/home/user/mykuma# ^C
root@DCWVM20UBU08043:/home/user/mykuma# docker-compose down
Removing network mykuma_default
root@DCWVM20UBU08043:/home/user/mykuma# docker-compose up -d
Creating network "mykuma_default" with the default driver
Creating uptime-kuma ... error

ERROR: for uptime-kuma  Cannot create container for service uptime-kuma: No command specified

ERROR: for uptime-kuma  Cannot create container for service uptime-kuma: No command specified
ERROR: Encountered errors while bringing up the project.
root@DCWVM20UBU08043:/home/user/mykuma# docker-compose up
Creating uptime-kuma ... error

ERROR: for uptime-kuma  Cannot create container for service uptime-kuma: No command specified

ERROR: for uptime-kuma  Cannot create container for service uptime-kuma: No command specified
ERROR: Encountered errors while bringing up the project.
root@DCWVM20UBU08043:/home/user/mykuma# docker-compose down
Removing network mykuma_default
root@DCWVM20UBU08043:/home/user/mykuma# docker-compose up
Creating network "mykuma_default" with the default driver
Creating uptime-kuma ... error

ERROR: for uptime-kuma  Cannot create container for service uptime-kuma: No command specified

ERROR: for uptime-kuma  Cannot create container for service uptime-kuma: No command specified
ERROR: Encountered errors while bringing up the project.
root@DCWVM20UBU08043:/home/user/mykuma# docker run -d --restart=always -p 3001:3001 -v uptime-kuma:/app/data --name uptime-kuma louislam/uptime-kuma:1
docker: Error response from daemon: No command specified.

### 🐻 Uptime-Kuma Version

1.18.5

### 💻 Operating System and Arch

Ubuntu 20.04 x64

### 🌐 Browser

Microsoft Edge Version 106.0.1370.52 (Official build) (64-bit)

### 🐋 Docker Version

Docker version 20.10.12, build 20.10.12-0ubuntu2~20.04.1

**Comment by rezzorix** [comment]
3 things I would think of from start:

Permission problems?
File paths of the imported compose file not correct set?
Other conflicts caused by settings?

Aside from that, why not just copying the data folder (or just the database) to the new computer?

**Comment by thrdgeek** [comment]
The permissions are the same as the working server.
I have copied the data.  My problem is importing the container then starting it up.  Since I don't have internet access, I had to export it from my test server.

**Comment by Jamie-** [comment]
Not sure why it would be needed, but could try adding `command` in the docker compose to the same command that's set in the dockerfile.
