### ISSUE TITLE
How to use custom port when using pm2?

### ISSUE THREAD

**Issue by ReactiveSlime** [louislam/uptime-kuma#2412]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

How can I run using pm2 and a custom port

### 🐻 Uptime-Kuma Version

1.18.5

### 💻 Operating System and Arch

ubuntu server 22.04 64 bit

### 🌐 Browser

Google Chrome 108.0.5359.124 

### 🟩 NodeJS Version

14.21.1

**Comment by rezzorix** [comment]
2 ways:

1) Before installation via npm run setup you can adjust the default port in the file install.sh

2) pm2 start server/server.js --name uptime-kuma -- --port=$port

Change the $port to whatever you want it to be.

**Comment by ReactiveSlime** [comment]
Cool. Thanks
