### ISSUE TITLE
Rocket Chat 5.4.0 does not show content of the alert anymore

### ISSUE THREAD

**Issue by TimmiORG** [louislam/uptime-kuma#2414]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### Description

Rocket Chat 5.4.0 does not show the content of the alert any more.
But I can see the full message in the log.

```
Dec 14 20:32:14 rocket RocketChat[997]:  text: 'Uptime Kuma Alert',
Dec 14 20:32:14 rocket RocketChat[997]:  username: 'HealthCheck',
Dec 14 20:32:14 rocket RocketChat[997]:  icon_emoji: '',
Dec 14 20:32:14 rocket RocketChat[997]:  attachments: [
Dec 14 20:32:14 rocket RocketChat[997]:    {
Dec 14 20:32:14 rocket RocketChat[997]:      title: 'Uptime Kuma Alert *Time (UTC)*\n2022-12-14 19:32:14.388',
Dec 14 20:32:14 rocket RocketChat[997]:      text: '*Message*\n' +
Dec 14 20:32:14 rocket RocketChat[997]:        '[test] [🔴 Down] connect ECONNREFUSED 192.168.xxx.xxx:443',
Dec 14 20:32:14 rocket RocketChat[997]:      color: '#ff0000',
Dec 14 20:32:14 rocket RocketChat[997]:      title_link: 'https://health.example.com/dashboard/5'
Dec 14 20:32:14 rocket RocketChat[997]:    }
Dec 14 20:32:14 rocket RocketChat[997]:  ]
Dec 14 20:32:14 rocket RocketChat[997]: }
```

![grafik](https://user-images.githubusercontent.com/979342/207699269-add50caa-3483-48bc-9acd-d18ce2ee08c2.png)

### 👟 Reproduction steps

Use Rocket Chat 5.4.0 server and send uptime kuma alert through the webhook

### 👀 Expected behavior

Full details of the message should be visible

### 😓 Actual Behavior

See description and logs.

### 🐻 Uptime-Kuma Version

1.18.5

### 💻 Operating System and Arch

Fedora

### 🌐 Browser

Firefox 107

### 🐋 Docker Version

Docker

**Comment by louislam** [comment]
Cc: @antiseptikk 
Related or: #264

**Comment by TimmiORG** [comment]
Hi,
this was caused by my to have a special script inside the webhook. 
Sorry my fault.
