### ISSUE TITLE
[uptime-kuma on Docker]Where is the certificate info? 

### ISSUE THREAD

**Issue by xx10n31y** [louislam/uptime-kuma#2415]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

```shell
# first use
docker run -d --restart=always -p 3002:3001 -v uptime-kuma:/app/data --name uptime-kuma louislam/uptime-kuma:1
# second use
docker run -d --restart=always -p 3002:3001 -v uptime-kuma:/app/data --name uptime-kuma louislam/uptime-kuma:latest
# third use
docker run -d --restart=always -p 3002:3001 -v uptime-kuma:/app/data --name uptime-kuma louislam/uptime-kuma:beta
```
![image](https://user-images.githubusercontent.com/57975788/207816279-c0ba81f9-c5a2-4ac1-8f13-a9fc94868fa8.png)

TLS Certificate Expiry not working
![image](https://user-images.githubusercontent.com/57975788/207808270-956f02a2-e02b-484f-a2d4-3aa8898b05d0.png)

### 🐻 Uptime-Kuma Version

1.19.0-beta.2

### 💻 Operating System and Arch

Ubuntu 22.04.1 LTS x86_64

### 🌐 Browser

Google Chrome 108.0.5359.100

### 🐋 Docker Version

Docker version 20.10.21, build baeda1f

**Comment by solracsf** [comment]
Did you activated it on individual monitor?
![image](https://user-images.githubusercontent.com/12234510/207810439-32f9befb-b023-4d49-9b2b-3e725f6362f7.png)

**Comment by xx10n31y** [comment]
> Did you activated it on individual monitor? 

of course.

![image](https://user-images.githubusercontent.com/57975788/207811509-b7262c80-0d80-414a-a903-0354c49ef232.png)

**Comment by solracsf** [comment]
Can't say, in my case, it appears on a 5th column.
Wait for someone who can help you.

![image](https://user-images.githubusercontent.com/12234510/207813092-0071afd4-07fc-4c0b-92a2-ae92b938e10b.png)

**Comment by xx10n31y** [comment]
> Can't say, in my case, it appears on a 5th column. Wait for someone who can help you.
what is your uptime-kuma version? Do you run it on docker?

**Comment by solracsf** [comment]
Yes, docker with Caddy as reverse proxy. v.1.18.5
I've tried your site.

![image](https://user-images.githubusercontent.com/12234510/207813537-374a84ff-f92e-47ba-adac-861754035474.png)

**Comment by xx10n31y** [comment]
> 1.18.5
> Yes, docker with Caddy as reverse proxy. v.1.18.5 I've tried your site.

I tried this version, but still no have the cert exp tab.
![image](https://user-images.githubusercontent.com/57975788/207814643-a9ede0c9-f379-426b-aad2-3eeeef85adbc.png)

**Comment by xx10n31y** [comment]
> Yes, docker with Caddy as reverse proxy. v.1.18.5 I've tried your site.

Can you remove this picture from the issue or put the mosaic on domain, thanks

**Comment by louislam** [comment]
2 possible situations that the grid is not shown:
- Uptime Kuma fail to retrieve the cert details (Maybe you can some error log)
- URL not start with https://

**Comment by xx10n31y** [comment]
> 

Yes! docker logs show the message like 
```shell
2022-12-15T09:22:43.656Z [MONITOR] INFO: Get Monitor: 1 User ID: 1
2022-12-15T09:22:54.419Z [MANAGE] INFO: Resume Monitor: 1 User ID: 1
2022-12-15T09:22:54.426Z [MONITOR] INFO: Get Monitor: 1 User ID: 1
2022-12-15T09:22:54.773Z [MONITOR] WARN: Monitor #1 'tt.onevat.cn': Failing: Request failed with status code 400 | Interval: 20 seconds | Type: http | Down Count: 0 | Resend Interval: 0
2022-12-15T09:23:10.296Z [MANAGE] INFO: Resume Monitor: 1 User ID: 1
2022-12-15T09:23:10.303Z [MONITOR] INFO: Get Monitor: 1 User ID: 1
2022-12-15T09:23:10.458Z [MONITOR] ERROR: Caught error
2022-12-15T09:23:10.458Z [MONITOR] ERROR: res.request.res.socket.getPeerCertificate is not a function
2022-12-15T09:23:30.919Z [MONITOR] ERROR: Caught error
2022-12-15T09:23:30.919Z [MONITOR] ERROR: res.request.res.socket.getPeerCertificate is not a function
2022-12-15T09:23:51.123Z [MONITOR] ERROR: Caught error
2022-12-15T09:23:51.123Z [MONITOR] ERROR: res.request.res.socket.getPeerCertificate is not a function
```

**Comment by louislam** [comment]
Did you try other https like https://github.com

**Comment by xx10n31y** [comment]
> Did you try other https website like https://github.com

![image](https://user-images.githubusercontent.com/57975788/207823799-d865d026-01be-47df-b8dc-bf5cc0480a2f.png)

**Comment by xx10n31y** [comment]
> Did you try other https website like https://github.com

![image](https://user-images.githubusercontent.com/57975788/207828091-d1d207de-0461-4035-8aa0-93526b7c37cd.png)

I ran the below commands, but still no have certificate info.
```shell
docker rm -f uptime-kuma && docker rmi louislam/uptime-kuma
docker volume rm uptime-kuma
mkdir /tmp/uptime-kuma
docker run -d --restart=always -p 3002:3001 -v /tmp/uptime-kuma:/app/data --name uptime-kuma louislam/uptime-kuma:beta
```

**Comment by xx10n31y** [comment]
> Did you try other https website like https://github.com

Run the application on non China mainland VPS is working.

**Comment by louislam** [comment]
It is a known issue, probably related to your server, but I can't tell what is the exact problem, because it is hard to reproduce.

**Comment by xx10n31y** [comment]
> It is a known issue, probably related to your server, but I can't tell what is the exact problem, because it is hard to reproduce.

Yes, Please delete this issue
