### ISSUE TITLE
Maintenance mode shows wrong Effective Date Range

### ISSUE THREAD

**Issue by x86dev** [louislam/uptime-kuma#2416]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### Description

Using the new maintenance mode with 1.19 Beta 2 shows the wrong Effective Date Range when UTC plus an offset is being used and the installation uses a 24 hour scheme. See attached screenshot.

### 👟 Reproduction steps

Set the Maintenance Window with UTC+1 and a 24 hour scheme, e.g. Europe/Berlin.

### 👀 Expected behavior

A clarification what exactly the Effective Date Range is and how to interpret this would be helpful on that site.

### 😓 Actual Behavior

See above.

### 🐻 Uptime-Kuma Version

1.19 Beta 2

### 💻 Operating System and Arch

Ubuntu 20.04

### 🌐 Browser

Firefox

### 🐋 Docker Version

Docker CE 20

![Screenshot_20221215-095004](https://user-images.githubusercontent.com/3184951/207816434-b2e7b35b-aa17-4107-aca7-e3364b6a4fcd.png)

**Comment by louislam** [comment]
`Maintenance Time Window` only activate if the current date is within the `Effective Date Range`

![image](https://user-images.githubusercontent.com/1336778/207850004-3356df45-c9ff-40ff-9d2e-52f3e4791754.png)

**Comment by kmz27** [comment]
maybe add a option to set the effective date to always? so it never runs out

**Comment by x86dev** [comment]
Yes, that would be a good idea ... Maybe making this a default also should be considered.

**Comment by kimberlyeet** [comment]
Looks like 1.21.2 fixes this.
> Effective Date Range is no longer required, it is now optional
