### ISSUE TITLE
Clear data button has CSS alignment/block issues

### ISSUE THREAD

**Issue by solracsf** [louislam/uptime-kuma#2419]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### Description

See screenshot

![image](https://user-images.githubusercontent.com/12234510/207896845-a799a6cd-301f-4987-b82e-f0467b4357c5.png)

### 👟 Reproduction steps

See screenshot

### 👀 Expected behavior

Better alignment or link that fill the entire block in width.

### 😓 Actual Behavior

See screenshot

### 🐻 Uptime-Kuma Version

1.18.5

### 💻 Operating System and Arch

Ubutnu 22.0.4

### 🌐 Browser

Brave

**Comment by solracsf** [comment]
Why is this a feature request? 😄

**Comment by Computroniks** [comment]
I will create a PR for this
