### ISSUE TITLE
[SMTP] Cannot send notification to ....

### ISSUE THREAD

**Issue by Salamafet** [louislam/uptime-kuma#242]
**Info**
Uptime Kuma Version: 1.3.2
Using Docker?: Yes

Hi, thanks for this fantastic software.

When service goes down, I don't receive the mail notification and I got the following error in the console :
`Cannot send notification to myaddress@example.com` _(not my real mail address, of course)_

When I make the SMTP configuration test or when a service is back UP, I receive the mail.

I use the `docker logs` command to see the logs.
Is there a way to see more verbose logs ?

**Comment by louislam** [comment]
> **Info**
> Uptime Kuma Version: 1.3.2
> Using Docker?: Yes
> 
> Hi, thanks for this fantastic software.
> 
> When service goes down, I don't receive the mail notification and I got the following error in the console :
> `Cannot send notification to myaddress@example.com` _(not my real mail address, of course)_
> 
> When I make the SMTP configuration test or when a service is back UP, I receive the mail.
> 
> I use the `docker logs` command to see the logs.
> Is there a way to see more verbose logs ?

It looked like due to the network problem of the server where you are hosting Uptime Kuma, because it cannot connect to your SMTP server and your monitoring service.

**Comment by Salamafet** [comment]
But why this error only for down status alert ?

I have simulated down situation with one host (local web container). My network works perfectly.

**Comment by louislam** [comment]
Since I did not log the detail of error in current latest stable version, I just update the nightly version which log the error.

> louislam/uptime-kuma:nightly-amd64

**Comment by Salamafet** [comment]
Apparently, my mail provider doesn't like when service goes down 😑
`response: '550 5.2.0 Spam message rejected'`

I will contact them

Thanks a lot for your help.

**Comment by louislam** [comment]
> Apparently, my mail provider doesn't like when service goes down 😑
> `response: '550 5.2.0 Spam message rejected'`
> 
> I will contact them
> 
> Thanks a lot for your help.

lol, funny. Maybe they don't like "DOWN"
