### ISSUE TITLE
APCUPSD support

### ISSUE THREAD

**Issue by 00ihsan** [louislam/uptime-kuma#2421]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

I want to monitor my ups with uptime-kuma icw apcupsd. 

Apcupsd has a onbattery script in case of failure. And an offbattery script when power is restored. I want Uptime-kume to say offline on battery and online when power is back. How can i achieve this?

### 🐻 Uptime-Kuma Version

1.18.5

### 💻 Operating System and Arch

Synology x86

### 🌐 Browser

Safari

### 🐋 Docker Version

Docker 20.10.3

**Comment by rezzorix** [comment]
You could create a push monitor and write a script that calls this monitor depending on what the battery status is.
