### ISSUE TITLE
Monitoring websites with expired SSL certificates

### ISSUE THREAD

**Issue by AndreKotze** [louislam/uptime-kuma#2424]
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

UI Feature

### 🔖 Feature description

When monitoring https websites with expired SSL certificates the monitor will show DOWN even though the website is working.  When selecting the "Ignore TLS/SSL error for HTTPS websites" option the monitor will then show as UP but then there is no way of knowing which monitors have expired SSL certificates unless you individually select the monitors on the dashboard page.

### ✔️ Solution

When a https monitor is UP but it has an expired SSL certificate is must maybe go into an "ALARMED" or "CAUTION" state with an orange colour to easily identify it on the main dashboard page.

**Comment by CommanderStorm** [comment]
Given that modern browsers don't let you visit sites with expired certs except if you click the advanced button, I think this issue should be closed with a `wontfix`.
Users of sites will expirience an expired cert as if the site were down.

(I am open to a discussion if you have a reason for this FR)
