### ISSUE TITLE
Cannot connect to the socket server

### ISSUE THREAD

**Issue by Kraleemil** [louislam/uptime-kuma#2425]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

It says "Cannot connect to the socket server. [Error: websocket error] Reconnecting..." but i don't have reverse proxy setup

### 🐻 Uptime-Kuma Version

Not sure installed it 3 days ago

### 💻 Operating System and Arch

Windows 10 Pro

### 🌐 Browser

Brave

**Comment by dVVilly** [comment]
I'm seeing the same problem and am also NOT using a reverse proxy.

Docker Version: 20.10.22, build 3a2c30b
Docker Compose: v2.14.1
Host OS: Ubuntu 20.04 LTS
Uptime-Kuma Version: "latest" tag as of 6 days ago.

docker logs -f uptime-kuma produces no additional output when I attempt to access the dashboard.

In my case, the Uptime Kuma host is not internet connected. I don't believe this should be problematic, but thought it worth noting.

**Comment by dVVilly** [comment]
Can anyone advise how I can go about extracting more log information? I even entered a bash environment within the uptime-kuma container and ran `node server/server.js --verbose` but I'm neither seeing anything relevant to the error in the web interface, nor indeed any log activity when I reload the page.

**Comment by LightningRhino** [comment]
I am experiencing the same problem.
"Cannot connect to the socket server."
I do not use a reverse proxy.
