### ISSUE TITLE
Setting to keep X alerts for each monitor

### ISSUE THREAD

**Issue by numbermonkey** [louislam/uptime-kuma#243]
**Is it a duplicate question?**
I dont think so.

**Is your feature request related to a problem? Please describe.**
I notice the number of messages is only going up. I dont care about the history and I worry that unchecked, the storage of the history will cause an issue.

**Describe the solution you'd like**
For each monitor, a setting to only keep X number of messages. 

**Describe alternatives you've considered**
A "Clear All" button to remove all the historic messages.

**Additional context**
Showing 1 to 25 of 470 records

**Comment by aramlakhan** [comment]
**Nothing on the Inky Screen**
the check works great **sudo pihole-dashboard-inky-draw**, everything passed but still nothing on the screen. Can you please help with this?"

This is what is get from the test

[✓] dns1: 10.2%  dns2: 10.2%
[✓] Status dns1:[✓] dns2:[✓]
[✓] GDB dns1:0d15h dns2:0d15h
[✓] Warm 42.8
[✗] WRKN:0.72 at CPU:51.1%
dns1 version is v5.3.1    @ 15:11

But nothing on the Inky screen.
Any advice?

**Comment by CommanderStorm** [comment]
@numbermonkey I think this is resolved, given that these options exist:
![image](https://github.com/louislam/uptime-kuma/assets/26258709/a9d2d4c7-723b-46e0-ad2d-f5d90803b5d8)

**Comment by CommanderStorm** [comment]
Resolved via the retention setting
