### ISSUE TITLE
No email notification

### ISSUE THREAD

**Issue by adm2k** [louislam/uptime-kuma#2432]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

When a site I am monitoring is down I get an email notification on subsequent checks and the site is still down I get no email notification. Should I not get an email notification every time the monitor runs and the site is marked down?

What am I missing?

Thanks in advance!

### 🐻 Uptime-Kuma Version

1.18.5

### 💻 Operating System and Arch

Ubuntu server 22.04

### 🌐 Browser

Chrome 108.0.5359.111

### 🟩 NodeJS Version

20.10.17

**Comment by AndreKotze** [comment]
Did you change the "Resend Notification if Down X times consequently" value for the monitor?

**Comment by adm2k** [comment]
No I did not. What value should it be? Most of the time when the job runs
it will fail since the keyword may only be there once a day and at random
times.

Basically what I am needing is for the job to send an email when the
keyword is found and do nothing when the keyword is not found.

Hope that makes sense...

**Comment by AndreKotze** [comment]
I'm not too sure because I've only stumbled across Uptime Kuma a few days ago but try 1 and see what it does.

**Comment by louislam** [comment]
@AndreKotze's answer is correct, you have to set it. 

But 1 is not recommended for short interval, it will send a lot of emails in a short period.

**Comment by adm2k** [comment]
OK, I have set it to a large number, will see how it works. Also, the
monitor seems to be inconsistent in that sometimes it says the keyword is
found and other is says it is not when it is in fact actually there.

**Comment by adm2k** [comment]
Example is the keyword "items" - as you can see it is there
[image: image.png]

**Comment by louislam** [comment]
Cannot see the image, but Uptime Kuma is eventually not a real browser, it can check html only.

**Comment by adm2k** [comment]
Is this not HTML? The keyword being "have"...

<span id="ctl00_MasterPlaceHolder_dashboardControl_lblTotal"
class="red-label-msg"><a
href='FieldRep_Inventory.aspx?page=FieldRep_Search&dynamic=1'>You *have* 5
total items.</a></span>
