### ISSUE TITLE
help

### ISSUE THREAD

**Issue by ramez121** [louislam/uptime-kuma#2435]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

i get this error when i run on replit 
![image](https://user-images.githubusercontent.com/86024913/208320178-8e489928-7131-4943-b4d2-f7eef130a351.png)

### 🐻 Uptime-Kuma Version

1.18.5

### 💻 Operating System and Arch

windows

### 🌐 Browser

chrome

### 🐋 Docker Version

no

### 🟩 NodeJS Version

16

**Comment by louislam** [comment]
Dont support replit, please search old issues.
