### ISSUE TITLE
More flexible script monitoring types

### ISSUE THREAD

**Issue by danger-dream** [louislam/uptime-kuma#2439]
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

Other

### 🔖 Feature description

Can JavaScript type monitoring be provided?

This function is mainly provided for people who are more professional or have more complex needs

### ✔️ Solution

* Can use node:vm to achieve this function

* Most of the existing functions are encapsulated and injected into the vm context, and the maintainer writes a script to customize the functions they want to achieve in more detail, such as:

* More flexible http requests..
```javascript
async function event(m: Monitor): Promise<{ status: boolean, time?: number, msg?: string } | boolean | number> {
	if (!m.params) {
		throw new MonitorError('Invalid parameter')
	}
	// try....
	const { url } = JSON.parse(m.params)
	const res = await utils.axios.get(url)
	if (res.status === 200){
		if (res.data.xxx === 'success') {
			return true
		}
		return { status: false, msg: 'data.xxx is not "success"' }	
	}
	return { status: false, msg: 'status code error..' }
}
```

* Sensitive to ping time
```javascript
async function event(m: Monitor): Promise<{ status: boolean, time?: number, msg?: string } | boolean | number> {
	if (!m.params) {
		throw new MonitorError('Invalid parameter')
	}
	// try....
	const { host } = JSON.parse(m.params)
	const ms = await utils.ping(host)
	if (ms > 60) {
		throw new MonitorError('access too slow')
	}
	return ms
}
```

* More interested in something in the result set
```javascript
async function event(m: Monitor): Promise<{ status: boolean, time?: number, msg?: string } | boolean | number> {
	const st = Date.now()
	if (!m.params) {
		throw new MonitorError('Invalid parameter')
	}
	// try....
	const { databaseConnectionString, databaseQuery } = JSON.parse(m.params)
	const res = await utils.mysqlQuery(this.databaseConnectionString, this.databaseQuery)
	if (res?.length > 0 && res.filter(x => x.user !== 'xxx' && x.age > 10).length > 0) {
		return { status: true, time: Date.now() - st }
	}
	return return { status: false, time: Date.now() - st, msg: 'the desired data was not found' }
}
```

**Comment by alexmaurer-madis** [comment]
Is your proposal in the same spirit of mine but even more integrated ?

Have a look at [FR #2431](https://github.com/louislam/uptime-kuma/issues/2431)

**Comment by hlxxzt** [comment]
Yes, our suggestion is similar, but the workload of modifying the existing monitoring code part is a bit heavy, so my suggestion is to add script type monitoring

**Comment by CommanderStorm** [comment]
@danger-dream
given that jsonata based `json-query` is merged, is this issue resolved?
Note that generalising these response checks is tracked in #3919

**Comment by CommanderStorm** [comment]
> is this issue resolved?

Given that @danger-dream did not respond, I consider this issue resolved
