### ISSUE TITLE
No support for Firefox browser?

### ISSUE THREAD

**Issue by zell-mbc** [louislam/uptime-kuma#244]
**Describe the bug**
None of the menu items work with Firefox. When connecting for the first time I get redirected to my mydomain.de/dashboard
After a while the browser will show a "Cannot connect to the socket server. [Error: timeout] Reconnecting..."

**To Reproduce**
1. Go to 'status.mydomain.com via Firefox browser
2. Click on any menu item, no screen will load, instead the error above will appear after a few seconds
3. Open the same page via Chromium
4. Got immediately redirected to setup page, was able to add a test entry which shows in the dashboard, everything as expected
5. Go back to Firefox, same error remains 

**Expected behavior**
Firefox show the same behaviour as Chromium

**Info**
- Uptime Kuma Version: 1.3.2
- Using Docker?: Yes
- Reverse Proxy: nginx
- OS: Server Arch / Client Arch
- Browser: Firefox and Chromium

**Screenshots**
![image](https://user-images.githubusercontent.com/29018767/130452138-a0bdcaed-fd2f-41f6-903e-74ad25c54bd9.png)

**Error Log**
It is easier for us to find out the problem.

**Comment by louislam** [comment]
Cannot reproduce. It is ok in my Firefox.

Feel free to try my testing env: https://test-status.louislam.net in your Firefox.

![image](https://user-images.githubusercontent.com/1336778/130454465-0227335f-100d-4c01-8146-6ad12f606a0a.png)

**Comment by zell-mbc** [comment]
Interesting yours works here as well.
Does mine work for you? https://status.zell-mbc.com

**Comment by Ponkhy** [comment]
I also cannot reproduce the issue.
On your URL it stays connected for me.

**Comment by louislam** [comment]
> Interesting yours works here as well.
> Does mine work for you? https://status.zell-mbc.com

Working fine, no connection error alert in the header.

![image](https://user-images.githubusercontent.com/1336778/130455382-a90e4af7-2663-40d2-a7dc-b560bcae9ba3.png)

**Comment by zell-mbc** [comment]
Now, this is interesting, something to do with my Firefox in that case? Maybe my Add block settings but then again, why isn't yours blocked too in that case? Anyway, clearly this is an issue at my end. Thanks for responding so quickly.

**Comment by louislam** [comment]
You can press F12 to view the error in Firefox console.

Also, try private mode and new firefox profile

**Comment by zell-mbc** [comment]
Looking at the Network tab in private mode I get this error right after the refresh
![image](https://user-images.githubusercontent.com/29018767/130457349-b046d4d7-7784-43c0-85b4-cd62d3200931.png)

Which is replaced with this one once the "Cannot connect …" error message appears.
![image](https://user-images.githubusercontent.com/29018767/130457385-00f58a93-f486-4167-bbf3-2506f33760d7.png)

A connection to your server in another tab doesn't show the string error...

**Comment by Ponkhy** [comment]
Which version of Firefox do you use?

**Comment by zell-mbc** [comment]
91.0.1 (64-bit)

And I just noticed the string error shows with https://test-status.louislam.net as well, it just gets overwritten quickly so I didn't notice right away.

**Comment by Ponkhy** [comment]
Unfortunately i cannot confirm the issue with that version on my end either.

**Comment by zell-mbc** [comment]
No worries, let me poke around a little more. Now that I know this is working for everyone but me, I can narrow down my tests. I will update this thread if I find out what's going on. Maybe it's something as stupid than a missing reboot after a recent update.

**Comment by Ponkhy** [comment]
> No worries, let me poke around a little more. Now that I know this is working for everyone but me, I can narrow down my tests. I will update this thread if I find out what's going on. Maybe it's something as stupid as a missing reboot after a recent update.

Maybe try a portable version of this firefox version and see how it goes.

**Comment by louislam** [comment]
Which Arch Linux version are you using?

**Comment by zell-mbc** [comment]
Arch doesn't have versions, it's a rolling distribution and both my server and PC are up to date as of today.
Or did you mean architecture? It's x64 at both ends. I have a few more machines in reach which I can test with later this evening to hopefully narrow down where things break.

**Comment by zell-mbc** [comment]
A reboot did indeed fix the problem. I don't quite understand how this affected only my local instance, but hey, things work and I will look into switching over from Statping tomorrow.

Sorry for boiling the ocean for no reason.

**Comment by Ponkhy** [comment]
Good to hear it's fixed! No worries at all

**Comment by DX37** [comment]
I don't get it. I had the same issue - it's working slow in Firefox and flies like rocket in Chrome, but if I reboot host with Kuma - it's working in both browsers without issue.
