### ISSUE TITLE
No down notifications for http and port monitors

### ISSUE THREAD

**Issue by mickyt71** [louislam/uptime-kuma#2442]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

First of all I love what has been done so far.  I have used Systems Management monitoring tools before and what you have come up with is awesome so Kudos.

I have been able to test ping monitor and it works well and I get down and back up notifications via SMTP.

No matter how much I test however with port or http(s) monitors I only get the UP status.   In the portal it shows they are status down but no email event DOWN sent, however when I bring them back up I get a UP event status.

I haven't been able to see any logging to tell me if there is an attempt for the SMTP or not so unable to diagnose further.

### 🐻 Uptime-Kuma Version

1.18.5

### 💻 Operating System and Arch

Linux CentOS 7.6.1810

### 🌐 Browser

Google Chrome 107.0.5304.107

### 🐋 Docker Version

Docker 19.03.1

**Comment by mickyt71** [comment]
Interestingly now I have set notifications on all my monitors to both email and discord, and I get the notifications of DOWN on discord, but not via SMTP.

**Comment by louislam** [comment]
I remember someone asked before, but i cannot find the issue.

As I remember, the down email was unexpectedly rejected by email vendor for unknown reason.

**Comment by mickyt71** [comment]
Is there some logging I can refer to see what might be the issue? As it works for down status on ping just not port or http down status?

**Comment by philw95** [comment]
I have the same issue.

i use Gotify for Nortifications.
the test Masseges and the Up Messages works fine.
Down messages not sending to Gotify.

**Comment by philw95** [comment]
soo I have found my mistake.

I found it here:
https://github.com/louislam/uptime-kuma/issues/1148#issuecomment-1058529517

I use MariaDB as database.
The charset in the database was set correctly with "utf8mb4_unicode_ci" but in the variable "GOTIFY_DATABASE_CONNECTION" I had only "utf8".
I simply replaced this with "utf8mb4" and now it works without problems.


**I think this is a different problem than the Author has.**
**Sorry for Posting this here.**
