### ISSUE TITLE
Organizr integration via HTML? 

### ISSUE THREAD

**Issue by BackedUpBooty** [louislam/uptime-kuma#245]
This is such a neat tool. I love it. 

**Describe the solution you'd like**
A way to have Kuma integrated into the Organizr homepage. Organizr offers up to two custom HTML injections if that's something that you could consider. 

**Describe alternatives you've considered**
Monitorr has this ability, however Kuma is a lot more aesthetically pleasing with a more robust and intuitive UI

**Comment by louislam** [comment]
Similar request? https://github.com/louislam/uptime-kuma/issues/234

**Comment by BackedUpBooty** [comment]
Oh, I missed this when I was searching for previous posts. Yes that works, thanks. 

I put it in between <p> tags with an align center. Both embed and iframe work, though I prefer having the dashboard image immediately visible rather than the list so have changed it to that. Now I just need to decide if I want to have a larger or smaller initial view:

![image](https://user-images.githubusercontent.com/53868636/130647921-8b3dbc25-2957-4d76-9b28-11e300fe4add.png)

<br> 

![image](https://user-images.githubusercontent.com/53868636/130649073-9a9931b5-a479-43e1-8cf4-2d4c9086670d.png)

**Comment by louislam** [comment]
continue discussion in #234
