### ISSUE TITLE
Certificate expiry on the status page

### ISSUE THREAD

**Issue by Takenfal** [louislam/uptime-kuma#2451]
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

UI Feature

### 🔖 Feature description

It would be nice to have the ability to choose if a entry on the status page should show the certificate expiry (if enabled on the dashboard add monitor settings) underneath it, for example, and highlight the monitor on light red when it's going to expire.

### ✔️ Solution

The certificate expiry is already on the dashboard. It should be easy to add it on the status page

### ❓ Alternatives

No alternatives I can think about.

**Comment by luisxiaomai** [comment]
+1

**Comment by candrews67** [comment]
+1

**Comment by tarun7singh** [comment]
I've started work on it, i will push my changes to the branch.

**Comment by candrews67** [comment]
Thanks!

**Comment by sk3pp3r** [comment]
1+

**Comment by CommanderStorm** [comment]
@sk3pp3r @candrews67 @luisxiaomai 
Please refrain from posting `+1` / requests for updates things on issues, as this makes issue-management harder.
Issues are for discussing what needs to be done how by whom.
[We use 👍🏻 on issues to prioritise work](https://github.com/louislam/uptime-kuma/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).

**Comment by tarun7singh** [comment]
Completed the PR for closing this issue.
