### ISSUE TITLE
Repeat Alerts

### ISSUE THREAD

**Issue by heffneil** [louislam/uptime-kuma#2461]
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

New Notification

### 🔖 Feature description

We really need a way to test every X seconds and get an alert for each one.

### ✔️ Solution

Allow a monitor to be repeatedly monitored and alerted when it is still down.

### ❓ Alternatives

Other tools - one alert can be missed or ignored.

**Comment by rwjack** [comment]
This option is confusingly hard to find, but it exists.

![image](https://user-images.githubusercontent.com/59068073/209443362-770591f1-db32-4cc5-b4ca-faf7a4385e20.png)

**Comment by heffneil** [comment]
Well I don't have that Resend option at all.  Am I using an older version or did you enable that somehow? Thanks!

**Comment by rwjack** [comment]
I'm using the latest version. No idea when it was enabled, but I think it's been here for quite some time.

**Comment by heffneil** [comment]
Thanks - newest version has it! Would be nice to see a release notes on this thing, perhaps there is one on this github I'm just too dumb to find it

**Comment by cyril59310** [comment]
Hi, this option is available since 1.18.0 you can find the release note that indicates it here https://github.com/louislam/uptime-kuma/releases/tag/1.18.0
![chrome_GCQAWWroUo](https://user-images.githubusercontent.com/70776486/209444848-4184b3eb-ee0b-4b33-b9ac-4f1b798f3579.png)

**Comment by heffneil** [comment]
Im confused - just tell me how to get a repeating alert if something remains down.  Because putting 100 in there does nothing.

**Comment by heffneil** [comment]
nevermind changing it to 1 seems to work
