### ISSUE TITLE
Alpine image deprecated

### ISSUE THREAD

**Issue by ksurl** [louislam/uptime-kuma#2463]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

Why is the alpine version marked as deprecated in the wiki under the docker install instructions? it mentions dns cache issues, but I can't find any reference to it in the github issues. Should current alpine users move to the latest debian based version?

### 🐻 Uptime-Kuma Version

1.19

### 💻 Operating System and Arch

Debian 11 x86

### 🌐 Browser

Firefox 108

### 🐋 Docker Version

20.10.22

**Comment by louislam** [comment]
https://github.com/louislam/uptime-kuma/issues/295

Error: EAI_AGAIN

I would recommend Debian based, because it also got more features such as Cloudflare tunnel and high performance health check (no cpu spike for slow devices)

**Comment by ksurl** [comment]
Ah that makes sense. I never had any issues and it looks like it only affected hosts with kernel older than 5.x.

Will alpine be abandoned in the future and only debian build maintained? Or is it just not supported and use at your own risk?

**Comment by louislam** [comment]
For 1.X.X, I won't update Alpine dockerfile anymore, but I still build image for it.

Alpine based will be dropped completely in 2.0 in my plan.
