### ISSUE TITLE
Certificate expiry message syntax in rocket.chat

### ISSUE THREAD

**Issue by mhkarimi1383** [louislam/uptime-kuma#2466]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### Description

Hi
In rocket chat the notification for certificate expiry (the link to health check section) does not have the correct markdown syntax

### 👟 Reproduction steps

Nothing 

### 👀 Expected behavior

()[]
Instead of [][]

### 😓 Actual Behavior

[][]

### 🐻 Uptime-Kuma Version

1.19.0

### 💻 Operating System and Arch

Debian (docker)

### 🌐 Browser

Everything 

### 🐋 Docker Version

20.10

**Comment by louislam** [comment]
Understood this issue because of #2563, it is not markdown.
