### ISSUE TITLE
Failed to install uptime kuma

### ISSUE THREAD

**Issue by andryrukandifauzy** [louislam/uptime-kuma#2471]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

![image](https://user-images.githubusercontent.com/42363553/209467896-2fc84ff1-4675-49b2-b508-af7f0cbd9c1d.png)

### 🐻 Uptime-Kuma Version

latest

### 💻 Operating System and Arch

centos 7

### 🌐 Browser

chorme

### 🐋 Docker Version

no

### 🟩 NodeJS Version

14

**Comment by louislam** [comment]
Fresh install? Please delete files and try to clone the repo again.

If you are trying to update, please read `How to Update` in the wiki.

**Comment by mathiash98** [comment]
Seems like you have not run `npm install`
