### ISSUE TITLE
The /bin/ping problem on your system is not detected

### ISSUE THREAD

**Issue by Pinkyou1** [louislam/uptime-kuma#2473]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

Could not detect /bin/ping on your system

Is it possible to provide a hosted version on replit
https://replit.com/

### 🐻 Uptime-Kuma Version

1.19.0

### 💻 Operating System and Arch

replit

### 🌐 Browser

Chrome 108.0.5359.124

**Comment by louislam** [comment]
No plan to support on Replit
