### ISSUE TITLE
Dependencies, silence alerts if spefic host is offline

### ISSUE THREAD

**Issue by ithakaa** [louislam/uptime-kuma#2474]
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

Other

### 🔖 Feature description

It would be a good idea to include a dependency feature that will silence hosts notification if a specific host is offline

As an example, I am monitoring my modem from a remote location, if my modem is offline, don't send notifications for other hosts inside my network, these notifications are not required

Thanks

### ✔️ Solution

host dependency

**Comment by skaempfe** [comment]
Please see #1236

**Comment by CommanderStorm** [comment]
@ithakaa
We are consolidating duplicate issues a bit to make issue management easier.
I think, we should track this issue in https://github.com/louislam/uptime-kuma/issues/1089 https://github.com/louislam/uptime-kuma/issues/2487 #3387 as there is no functional difference (the approach here is slightly different, but can still be covered by the linked issus)
⇒ I am going to close this as a duplicate.
