### ISSUE TITLE
Strange Down time

### ISSUE THREAD

**Issue by charleslcso** [louislam/uptime-kuma#2479]
I am experiencing strange Down time notification in version 1.16 and 1.18.5.

Uptime Kuma is monitoring a number of websites locally on various servers. All are on the same network. No UFW, nor firewalls.

Monitor type is HTTPS.

Not sure why, I'll get notified about various sites are down because there are no response in 48seconds. But all the sites are accessible, and don't seem to be down at all.

I've checked my database server, web server, application servers, network and everything. Nothing strange can be found during the times marked DOWN.

I'm out of my wit to why this is happening. Does anyone experience something similar? 

![Screenshot 2022-12-27 at 6 55 17 PM](https://user-images.githubusercontent.com/520537/209656699-d6dbfcb1-4f3a-42c5-ae60-be8c6b8f01d5.jpeg)

**Comment by louislam** [comment]
Try 1.19.2

**Comment by charleslcso** [comment]
Thank you Louislam. 

Followed the guide in https://github.com/louislam/uptime-kuma/wiki/%F0%9F%86%99-How-to-Update (this time is the second time updating the code).

It finished updating. Please see screen capture.

![Screen Shot 2022-12-27 at 8 53 16 PM](https://user-images.githubusercontent.com/520537/209669650-b6071bb8-6254-4000-8e32-3eaa2d796178.png)

It seems to be running. But web browser shows a blank page.

![Screen Shot 2022-12-27 at 8 54 59 PM](https://user-images.githubusercontent.com/520537/209669814-a47436fb-4024-4731-a97d-57b0a38754fa.png)

It seems that the 3 files (.js and .css) are not in /public. 

How should I proceed?

**Comment by charleslcso** [comment]
Oh. The node process before the update was still running. 

I killed them all, and now it works.

**Comment by charleslcso** [comment]
I'm afraid the problem still exists. 

How can I get some logs and post them?
