### ISSUE TITLE
View status for unlogged person

### ISSUE THREAD

**Issue by Minvinea** [louislam/uptime-kuma#248]
Hi @louislam

I seen and test your project. It's like to Uptime Robot, very great job.
My suggest is to add a button in general admin settings.
This radio button as function to enable or disable the dashboard of status. This board can be view for unlogged and no admin person, for juste seen the status with basic informations.

It's an idea like this :
![Screenshot_74](https://user-images.githubusercontent.com/29579830/130514188-fa85bdb3-f38b-4ffb-9ae9-bcb650136fe4.png)

**Comment by louislam** [comment]
Did you mean public dashboard like #4?

**Comment by Minvinea** [comment]
Yes, it's that. Good luck pour implemant him.
