### ISSUE TITLE
gRPC check throws errors

### ISSUE THREAD

**Issue by otbutz** [louislam/uptime-kuma#2480]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### Description

The gRPC check fails but i get the expected output in bloomrpc.

### 👟 Reproduction steps

URL: `routing.ot-hosting.de:443`

Keyword: `version`

Enable TLS: :heavy_check_mark: 

Proto Service Name:
```
service.v1.RoutingService
```

Proto Method:

```
Info
```

Proto Content:
```proto
syntax = "proto3";

package service.v1;

message Envelope {
    double min_longitude = 1;
    double max_longitude = 2;
    double min_latitude = 3;
    double max_latitude = 4;
}

message InfoRequest {
}

message InfoResponse {
  string version = 1;
  string gh_version = 2;
  int64 data_timestamp = 3;
  Envelope bounding_box = 4;
  map<string,string> configuration = 5;
}

service RoutingService {
    rpc Info (InfoRequest) returns (InfoResponse);
}
```

Body:

```
{}
```

### 👀 Expected behavior

![image](https://user-images.githubusercontent.com/22315436/209657257-93235079-89ad-4f75-b799-4b02078c5a1c.png)

### 😓 Actual Behavior

Depending on the case of the method `Info`/`info` i get the following errors:

```
WARN: Monitor #67 'routing': Failing: response.substring is not a function | Interval: 60 seconds | Type: grpc-keyword | Down Count: 0 | Resend Interval: 0
```

```
WARN: Monitor #67 'routing': Failing: grpcService[grpcMethod] is not a function | Interval: 60 seconds | Type: grpc-keyword | Down Count: 0 | Resend Interval: 0
```

### 🐻 Uptime-Kuma Version

1.19.2

### 💻 Operating System and Arch

Ubuntu 22.04

### 🌐 Browser

Firefox

### 🐋 Docker Version

20.10.22

**Comment by otbutz** [comment]
@minhhoangvn

**Comment by minhhoangvn** [comment]
Could you please share your configuration options for the uptime with gRPC. You can refer to the guideline for testing on this PR https://github.com/louislam/uptime-kuma/pull/1964

**Comment by otbutz** [comment]
Same settings as noted above in the "reproduction steps" section.

![grafik](https://user-images.githubusercontent.com/22315436/209785342-9f073003-901f-4584-86b9-2d7822a136c3.png)

**Comment by minhhoangvn** [comment]
Can you try to edit the service name without the package value, in your case is “RoutingService”

**Comment by otbutz** [comment]
Funny. I'm unable to remove the package. Clicking the save button automatically restores the old value.

**Comment by otbutz** [comment]
Recreated the monitor without the package prefix. Same error.

`Info` -> `grpcService[grpcMethod] is not a function`
`info` -> `response.substring is not a function`

Entering a dummy value for proto method will also trigger `grpcService[grpcMethod] is not a function` so I assume that `info` is in fact the correct value. This should be replaced with a more understandable error message IMHO.

**Comment by minhhoangvn** [comment]
Can you share your proto data, I will double check it😅

**Comment by otbutz** [comment]
```proto
syntax = "proto3";

package service.v1;

message Envelope {
    double min_longitude = 1;
    double max_longitude = 2;
    double min_latitude = 3;
    double max_latitude = 4;
}

message InfoRequest {
}

message InfoResponse {
  string version = 1;
  string gh_version = 2;
  int64 data_timestamp = 3;
  Envelope bounding_box = 4;
  map<string,string> configuration = 5;
}

service RoutingService {
    rpc Info (InfoRequest) returns (InfoResponse);
}
```

**Comment by minhhoangvn** [comment]
@otbutz, below is the correct configuration for your proto file. I will add the accurate log information and fix the issue when we can't update the service name 😥 The logic for updating the gRPC monitor configuration is missed with the service name value.
<img width="1262" alt="image" src="https://user-images.githubusercontent.com/17515250/209819437-106e1f70-298d-4a36-9326-d919cfd35817.png">

**Comment by otbutz** [comment]
Feel free to use my endpoint for testing. `routing.ot-hosting.de:443` with TLS enabled. This is currently not working:

![grafik](https://user-images.githubusercontent.com/22315436/209822195-faf15999-c557-4fda-8f24-9c75bed2da23.png)

**Comment by minhhoangvn** [comment]
@otbutz, thank you for your help in investigating the issue. The root cause is logic to truncate the response data for displaying in monitor info
<img width="1358" alt="image" src="https://user-images.githubusercontent.com/17515250/209835392-193c14c4-9698-41a5-b8b3-db3968a5a2b4.png">

https://github.com/louislam/uptime-kuma/blob/8c684e92936b5860139b09e50917d55c0b041891/server/model/monitor.js#L551

I have created a new PR to fix those issues (can't update service name and error when truncating response data)

**Comment by otbutz** [comment]
Thanks!
