### ISSUE TITLE
Never Expiring Maintenance Window option

### ISSUE THREAD

**Issue by cbaksa** [louislam/uptime-kuma#2484]
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

UI Feature

### 🔖 Feature description

The new Maintenance feature is really nice.  Kudo's
It would be nice to have an option for a never expiring maintenance window.
Either buy leaving the box empty (currently you must select a date) or by tick box for "Never Ending Schedule"

![image](https://user-images.githubusercontent.com/47068006/209695728-4f095184-0624-415e-8813-22bbe28c41c5.png)

### ✔️ Solution

It would be nice to have the option for a never expiring Date Range.  A.K.A - this schedule never expires.
I see two possible ways to implent this.

1 - Leave the the box empty (currently you must select a date) and noting that on the screen
2 - A tick box for "This Maintenance Schedule Never Expires"

### ❓ Alternatives

At the moment I have scheduled the window out a year.

### 📝 Additional Context

N/A

**Comment by CommanderStorm** [comment]
Never ending maintenence periods have been added sometime in the past:
![image](https://github.com/louislam/uptime-kuma/assets/26258709/88506fc6-bc0c-484b-a60b-7fc75a4db8bb)

=> closing as resolved
