### ISSUE TITLE
yaml.scanner.ScannerError: mapping values are not allowed here

### ISSUE THREAD

**Issue by derks-wesley** [louislam/uptime-kuma#2488]
I can't get the yml right...

https://github.com/louislam/uptime-kuma/blob/f6ea1fe9a57bac4e3c7b55a3200753ee54899592/docker/docker-compose.yml#L6

![image](https://user-images.githubusercontent.com/90984101/209723925-455ad090-cafe-4e10-981e-2a3363813720.png)

**Comment by louislam** [comment]
You should download the raw file. Don't copy if from GitHub.
