### ISSUE TITLE
Add Notifications to Atlassian OpsGenie

### ISSUE THREAD

**Issue by ezequielbarros** [louislam/uptime-kuma#2498]
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

New Notification

### 🔖 Feature description

I want kuma to send notifications to Atlassian OpsGenie: https://docs.opsgenie.com/docs/alert-api

### ✔️ Solution

I use OpsGenie for alert notification and would like uptime kuma to send notifications there.

Many teams use OpsGenie for alert notification so it would be very useful to have this feature.

### ❓ Alternatives

I haven't tested it yet but possibly an alternative would be to use WebHook while the feature is not implemented.

### 📝 Additional Context

I'm testing uptime kuma to implement a statuspage for the services I administer and I noticed that this support for opsgenie is missing.

**Comment by Computroniks** [comment]
This should be supported using apprise https://github.com/caronc/apprise

**Comment by HenkAJV** [comment]
@Computroniks , thank you for this. I did not know it was all built-in. I tested it and it works perfectly. 
Appreciate you pointing this out to us.

**Comment by mmadoo** [comment]
Does the pull request https://github.com/louislam/uptime-kuma/pull/2956 released in https://github.com/louislam/uptime-kuma/releases/tag/1.21.1 does not add this feature ?

**Comment by XtremeOwnageDotCom** [comment]
> Does the pull request #2956 released in https://github.com/louislam/uptime-kuma/releases/tag/1.21.1 does not add this feature ?

Looking at my current instance-

![image](https://github.com/louislam/uptime-kuma/assets/5262735/a276cd91-3595-46e8-aa1c-9997743edc77)

I'd say this issue has been completed.

**Comment by CommanderStorm** [comment]
Closing as resolved in https://github.com/louislam/uptime-kuma/pull/2956 and relesed in `1.21.1`
