### ISSUE TITLE
Installation not possible with docker and non docker version

### ISSUE THREAD

**Issue by NiceKype** [louislam/uptime-kuma#2499]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

I tried both ways to install uptime kuma.
I first tried to install with pm2, that didnt worked, but without any errors. Its simply not available with the domain and the port.
And the docker version worked too, but its not working too. And there again no errors except the port is used. But the pm2 version is stopped and deleted, so i dont know where the port is used. But i tried a second port and that didnt work too.

I have no clue what i can do anymore.

### 🐻 Uptime-Kuma Version

1.19.2

### 💻 Operating System and Arch

Ubuntu 18.04

### 🌐 Browser

Firefox

### 🐋 Docker Version

Docker 20.10.19

### 🟩 NodeJS Version

14.20.1

**Comment by louislam** [comment]
Please the console log.

**Comment by NiceKype** [comment]
Which console log? No errors for that in the console as i said. I dont know which log u mean

**Comment by louislam** [comment]
You should see the log like:
Welcome to Uptime Kuma
...
Listening on 3001

Did you see this?

**Comment by Computroniks** [comment]
For pm2, use the command `pm2 logs` to check the logs.
