### ISSUE TITLE
Improve database migration for development?

### ISSUE THREAD

**Issue by chakflying** [louislam/uptime-kuma#250]
With the project steadily growing in scope, often changes would require modification to the database. While the current method of manually writing migration script works, it is prone to human error and increase difficulty for code review. I think changing to a generated migration approach would have all-around benefits.

I'm not familiar with how the database interacts with knex and the ORM, but is it possible to use the migration system provided by knex? Or can we use a separate migration management tool?

**Comment by louislam** [comment]
In my opinion, everyone should use `ALTER` to add a column rather than drop-create a table.

```sql
ALTER TABLE person
ADD field VARCHAR(255) DEFAULT 'N' NOT NULL
```

**Comment by Saibamen** [comment]
Maybe `sequelize`?
https://sequelize.org/master/manual/migrations.html
