### ISSUE TITLE
Force Ping/Check to test monitor now

### ISSUE THREAD

**Issue by Taylor-Hinote** [louislam/uptime-kuma#2509]
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

UI Feature, Other

### 🔖 Feature description

An extra button on the end of "Pause, Edit, Delete" forces a ping of service without needing to wait for "auto check" or to pause and unpause the service.

### ✔️ Solution

Add a button to the end of the button group that says "Force Check" or something similar, that forces a ping to the service.

### ❓ Alternatives

Continue pausing and unpausing the service to force a ping.

### 📝 Additional Context

Something like this maybe?
![example](https://user-images.githubusercontent.com/117930865/210100537-b1bfc0b3-ad25-4874-80ad-99fb70680fe8.png)

**Comment by megosugit** [comment]
I was looking for this feature too, I was under the impression it had to be already available, but apparently no.

I believe this would be a great addition for everyone. I have some devices which I poll once per day (just to monitor SSL certificate expiration date), it would be great to be able to trigger a polling to check the certificate is seen as renewed.

Fingers crossed for this feature :) 🤞

**Comment by megosugit** [comment]
on a side note, I'm a new user and I'm glad I found this jewel :)

I have been browsing the next milestone and I see this FR is not receiving a lot of ❤, is there a chance to get your feedback about this ? Would you be happy to add it ?

I see several users gave a thumb up, so there is hope ^^

**Comment by CommanderStorm** [comment]
> I have been browsing the next milestones and I see this FR is not receiving a lot of ❤, is there a chance to get your feedback about this ? Would you be happy to add it ?

Given that this is a community driven project, that is mostly dependant on if a dev wants to contribute such a feature. See our contribution guide: https://github.com/louislam/uptime-kuma/blob/5b6522a54edad9737fccf195f9eaa25c6fb9d0f6/CONTRIBUTING.md

**Comment by megosugit** [comment]
yes, I'm willing to think someone else is deeply missing this feature and will find how to add this 💪.

**Comment by CommanderStorm** [comment]
@chakflying
Do you think this can be merged into #2725

**Comment by chakflying** [comment]
Closing this in favor of #2725.

Note that you can currently achieve the same thing by going into Edit Monitor, then press "Save" without changing anything.
