### ISSUE TITLE
Dashboard takes ages to load the monitors on 1.3.2

### ISSUE THREAD

**Issue by raspberrycoulis** [louislam/uptime-kuma#251]
**Describe the bug**
The dashboard page partially loads, but my monitors do not show - sometimes they do after a long wait (c. 30-60 seconds), and sometimes not at all.

I'm running two separate instances of UK - one on Synology NAS via Docker with the correct proxy headers set for websocket connections, and one on Raspberry Pi (4 with 8GB and running via SSD) with Traefik 2 - both are accessible via my own sub-domains, and the Synology version also is accessible via the container's IP address too.

**To Reproduce**
1. Go to the dashboard - wait.
2. The Uptime Kuma headers appear, as well as the settings / dashboard buttons, but nothing else
3. After a long wait (c. 30-60 seconds) the monitors eventually appear, but not always

**Expected behavior**
The dashboard should load, including the monitors.

**Info**
- Uptime Kuma Version: 1.3.2
- Using Docker?: Yes
- OS: Synology NAS DSM 6.2.4-25556 and Raspberry Pi OS (64bit)
- Browser: Brave and Chrome

**Screenshots**

**Error Log**
````
Trace: KnexTimeoutError: Knex: Timeout acquiring a connection. The pool is probably full. Are you missing a .transacting(trx) call?

    at Client_SQLite3.acquireConnection (/app/node_modules/knex/lib/client.js:348:26)
    at async RedBeanNode.normalizeRaw (/app/node_modules/redbean-node/dist/redbean-node.js:548:22)
    at async Function.sendUptime (/app/server/model/monitor.js:361:29)
    at async Function.sendStats (/app/server/model/monitor.js:315:9) {
  sql: '\n' +
    '            SELECT duration, time, status\n' +
    '            FROM heartbeat\n' +
    "            WHERE time > DATETIME('now', ? || ' hours')\n" +
    '            AND monitor_id = ? ',
  bindings: [ -720, '20' ]
}

    at process.<anonymous> (/app/server/server.js:836:13)
    at process.emit (events.js:400:28)
    at processPromiseRejections (internal/process/promises.js:245:33)
    at processTicksAndRejections (internal/process/task_queues.js:96:32)

If you keep encountering errors, please report to https://github.com/louislam/uptime-kuma/issues
````

**Comment by louislam** [comment]
Duplicate https://github.com/louislam/uptime-kuma/issues/218

**Comment by louislam** [comment]
I improved in nightly build, you can give it a try.

`
louislam/uptime-kuma:nightly
`

Also I want to know the load average and the process cpu usage.

Command:
`
top
`

**Comment by Saibamen** [comment]
> I improved in nightly build, you can give it a try.

Which commit?
