### ISSUE TITLE
Setting up configuration in Docker file

### ISSUE THREAD

**Issue by hakrishi** [louislam/uptime-kuma#2510]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

Hi there,

Is it possible to add all the hosts I would like to monitor (i.e servers, domains, ports) within my Docker Compose file rather than setting it up manually on the web UI? 

Many thanks

Rishi

### 🐻 Uptime-Kuma Version

1.19.2

### 💻 Operating System and Arch

Ubuntu 20.04

### 🌐 Browser

N/A

### 🐋 Docker Version

20.10.22

### 🟩 NodeJS Version

16.9.0

**Comment by louislam** [comment]
Cannot
