### ISSUE TITLE
[1.9.2] Rocket Chat notification - only clear messages arriving

### ISSUE THREAD

**Issue by TimmiORG** [louislam/uptime-kuma#2512]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### Description

Hi,
I'm not receiving the alarm trigger notification via rocket.chat since the update from 1.8.0 to 1.9.2.
The cleared message is still coming.

### 👟 Reproduction steps

Trigger a alarm via rocket.chat notification

### 👀 Expected behavior

Alarm trigger and cleared message should be received.

### 😓 Actual Behavior

Only cleared message received.

### 🐻 Uptime-Kuma Version

1.9.2

### 💻 Operating System and Arch

Rocky Linux 9

### 🌐 Browser

Firefox 108

### 🐋 Docker Version

Docker

**Comment by MarcHagen** [comment]
Im not seeing this personally so i would like to help you :)
Can you share your service ?

What are you monitoring, what are the settings. (screenshot or just text)
what are your rocket.chat settings? (without sharing the webhook link)

**Comment by TimmiORG** [comment]
@MarcHagen 
thank you for your offer.
I tested the alert with a different machine today and I received both the alert and the clear message.
So this should be related to my environment. Guess the message could not be delivered for from reason. So will check further.
Will close the ticket for now.
Best regards and happy new year.
