### ISSUE TITLE
Maintenance generates multiple alerts on status pages

### ISSUE THREAD

**Issue by SEOAlexRamon** [louislam/uptime-kuma#2516]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### Description

I have noticed that during the active period of a maintenance, the maintenance alert is displayed for each heartbeat. Thus causing an infinity of repeated alerts.

**Maintenance configuration**
![uptime-kuma-2](https://user-images.githubusercontent.com/37023161/210208807-95042421-26a6-4739-a870-7de5091908c0.png)

**Error**
![uptime-kuma](https://user-images.githubusercontent.com/37023161/210208803-663292e6-e504-43e3-86ab-e2609c4dd3f2.png)

### 👟 Reproduction steps

1. Create a maintenance
2. Be in the maintenance interval
3. Check the status page and there you will see a notification for each maintenance heartbeat

### 👀 Expected behavior

That only one alert was to appear during active maintenance

### 😓 Actual Behavior

An alert appears for each maintenance heartbeat

### 🐻 Uptime-Kuma Version

1.19.2

### 💻 Operating System and Arch

Ubuntu 20.04.5 LTS

### 🌐 Browser

Google Chrome 108.0.5359.125

### 🐋 Docker Version

Docker version 20.10.22, build 3a2c30b

### 🟩 NodeJS Version

v16.13.2

**Comment by MrMysterius** [comment]
Happening to me as well on a recurring monthly monitor.
