### ISSUE TITLE
Use HTTP OPTIONS when monitor is HTTP(s)?

### ISSUE THREAD

**Issue by Oaktribe** [louislam/uptime-kuma#252]
**Is it a duplicate question?**
No

**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
I think the monitoring request could be optimized a bit. For example when monitor type is **HTTP(s)** only, wouldn't a HTTP OPTIONS request be sufficient here? Instead of a HTTP GET since we don't need the response body, only the headers?
https://github.com/louislam/uptime-kuma/blob/master/server/model/monitor.js#L116

If the monitor type is **HTTP(s) - Keyword** then it could work as does right now since you need the body to check for the keyboard.

**Describe alternatives you've considered**
All is described in the paragraph above.

**Additional context**
None.

**Comment by louislam** [comment]
Uptime Kuma also checks the http status code, I think it is not possible with OPTIONS request.

**Comment by Oaktribe** [comment]
I did a little test and it does return the status code.
```js
const axios = require("axios");
const dayjs = require("dayjs");
const https = require("https");

let startTime = dayjs().valueOf();

async function test()
{
    let res = await axios.options('https://www.reddit.com/', {
        timeout: 5 * 1000 * 0.8,
        
        headers: {
            "Accept": "*/*",
            "User-Agent": "Uptime-Test/" + 1,
        },
        httpsAgent: new https.Agent({
            maxCachedSessions: 0,      // Use Custom agent to disable session reuse (https://github.com/nodejs/node/issues/3940)
            rejectUnauthorized: false,
        }),
        maxRedirects: 5,
        validateStatus: (status) =>
        {
            return status >= 200 && status <= 299;
        },
    });

    const bean = {
        msg: `${res.status} - ${res.statusText}`,
        ping: dayjs().valueOf() - startTime
    };

    console.log(bean);
}

test();
```

The result:
```
{ msg: '204 - No Content', ping: 271 }
```

However some sites do block the HTTP OPTIONS request, so maybe a setting for the monitor when the type is HTTP(s)? 
Like a checkbox saying "Use HTTP OPTION instead of HTTP GET".

**Comment by louislam** [comment]
I think it cannot check error codes like 500 or 403 that are throwing from the actual endpoint. The response code is completely different. And as you said some sites do block the HTTP OPTIONS request. Implementing this feature could be confusing for users.

I think TCP Ping with 443/80 should be enough if you don't care about the response http code.
