### ISSUE TITLE
Status Page to include Cert Expiry Date/days to Expiry and ability to be sorted based on Expiry Date/days to Expiry

### ISSUE THREAD

**Issue by declanrafferty** [louislam/uptime-kuma#2522]
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

UI Feature

### 🔖 Feature description

Have the ability to include the Cert Expiry date and/or Days to Cert Expiry on Status Pages with the option to sort the rows on the Status Page by Cert Expiry

### ✔️ Solution

I would like to be able to determine which sites have upcoming expiring certs so having a status page that can be sorted to show which sites have certs that are expiring first would be very useful.

**Comment by luisxiaomai** [comment]
+1

**Comment by luisxiaomai** [comment]
+1
