### ISSUE TITLE
uptime-kuma/data Folder is full of Backups from one Day. 

### ISSUE THREAD

**Issue by lenusch** [louislam/uptime-kuma#2524]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### Description

My Kuma Instance / disk is full. 
I found out, that the folder .../uptime-kuma/data/... has many Backups vom DB: 

```
...
-rw-r--r--  1 root root 420773888 Dec 21 09:55 kuma.db.bak20221221095513
-rw-r--r--  1 root root 420773888 Dec 21 09:55 kuma.db.bak20221221095515
-rw-r--r--  1 root root 420773888 Dec 21 09:55 kuma.db.bak20221221095518
-rw-r--r--  1 root root 420773888 Dec 21 09:55 kuma.db.bak20221221095521
-rw-r--r--  1 root root 420773888 Dec 21 09:55 kuma.db.bak20221221095523
-rw-r--r--  1 root root 420773888 Dec 21 09:55 kuma.db.bak20221221095526
-rw-r--r--  1 root root 420773888 Dec 21 09:55 kuma.db.bak20221221095529
-rw-r--r--  1 root root 420773888 Dec 21 09:55 kuma.db.bak20221221095532
-rw-r--r--  1 root root 420773888 Dec 21 09:55 kuma.db.bak20221221095534
-rw-r--r--  1 root root 420773888 Dec 21 09:55 kuma.db.bak20221221095537
-rw-r--r--  1 root root 420773888 Dec 21 09:55 kuma.db.bak20221221095540
-rw-r--r--  1 root root 420773888 Dec 21 09:55 kuma.db.bak20221221095543
-rw-r--r--  1 root root 420773888 Dec 21 09:55 kuma.db.bak20221221095545
-rw-r--r--  1 root root 420773888 Dec 21 09:55 kuma.db.bak20221221095548
-rw-r--r--  1 root root 420773888 Dec 21 09:55 kuma.db.bak20221221095551
-rw-r--r--  1 root root 420773888 Dec 21 09:55 kuma.db.bak20221221095554
-rw-r--r--  1 root root 420773888 Dec 21 09:55 kuma.db.bak20221221095556
-rw-r--r--  1 root root 420773888 Dec 21 09:56 kuma.db.bak20221221095559
-rw-r--r--  1 root root 420773888 Dec 21 09:56 kuma.db.bak20221221095602
-rw-r--r--  1 root root 420773888 Dec 21 09:56 kuma.db.bak20221221095605
-rw-r--r--  1 root root 420773888 Dec 21 09:56 kuma.db.bak20221221095608
-rw-r--r--  1 root root 420773888 Dec 21 09:56 kuma.db.bak20221221095610
-rw-r--r--  1 root root 420773888 Dec 21 09:56 kuma.db.bak20221221095613
-rw-r--r--  1 root root 420773888 Dec 21 09:56 kuma.db.bak20221221095616
-rw-r--r--  1 root root 420773888 Dec 21 09:56 kuma.db.bak20221221095619
-rw-r--r--  1 root root 420773888 Dec 21 09:56 kuma.db.bak20221221095621
-rw-r--r--  1 root root 420773888 Dec 21 09:56 kuma.db.bak20221221095624
-rw-r--r--  1 root root 420773888 Dec 21 09:56 kuma.db.bak20221221095627
-rw-r--r--  1 root root 420773888 Dec 21 09:56 kuma.db.bak20221221095630
-rw-r--r--  1 root root 420773888 Dec 21 09:56 kuma.db.bak20221221095632
-rw-r--r--  1 root root 420773888 Dec 21 09:56 kuma.db.bak20221221095635
-rw-r--r--  1 root root 420773888 Dec 21 09:56 kuma.db.bak20221221095638
-rw-r--r--  1 root root 420773888 Dec 21 09:56 kuma.db.bak20221221095641
-rw-r--r--  1 root root 420773888 Dec 21 09:56 kuma.db.bak20221221095644
-rw-r--r--  1 root root 420773888 Dec 21 09:56 kuma.db.bak20221221095646
-rw-r--r--  1 root root 420773888 Dec 21 09:56 kuma.db.bak20221221095649
-rw-r--r--  1 root root 420773888 Dec 21 09:56 kuma.db.bak20221221095652
-rw-r--r--  1 root root 420773888 Dec 21 09:56 kuma.db.bak20221221095655
-rw-r--r--  1 root root 420773888 Dec 21 09:56 kuma.db.bak20221221095657
....

```
I have nearly 40GB full of that. 
I think its the Date, where i installed kuma new on Docker, but not sure. 
Can i just delete them? How to prevent, that they are comming back? 

Kuma Version: 1.18.5
Frontend Version: 1.18.5
Linux Ubuntu 20.04.4 LTS (Focal Fossa)

### 👟 Reproduction steps

Can't edit or create monitorings

### 👀 Expected behavior

...

### 😓 Actual Behavior

...

### 🐻 Uptime-Kuma Version

1.18.5

### 💻 Operating System and Arch

Ubuntu 20

### 🌐 Browser

Chrome Version 107.0.5304.110

### 🟩 NodeJS Version

v16.14.0

**Comment by louislam** [comment]
You can delete `bak` files.

It looks like it kept restating. Please also check `error.log` for the log.

**Comment by lenusch** [comment]
`[2022-12-21 09:57:33] Error [ERR_SERVER_NOT_RUNNING]: Server is not running.
    at new NodeError (node:internal/errors:371:5)
    at Server.close (node:net:1624:12)
    at Object.onceWrapper (node:events:639:28)
    at Server.emit (node:events:532:35)
    at Server.<anonymous> (/usr/local/lib/node_modules/pm2/node_modules/@pm2/io/build/main/metrics/httpMetrics.js:152:37)
    at emitCloseNT (node:net:1677:8)
    at processTicksAndRejections (node:internal/process/task_queues:82:21) {
  code: 'ERR_SERVER_NOT_RUNNING'
}
[2022-12-21 09:57:36] Error [ERR_SERVER_NOT_RUNNING]: Server is not running.
    at new NodeError (node:internal/errors:371:5)
    at Server.close (node:net:1624:12)
    at Object.onceWrapper (node:events:639:28)
    at Server.emit (node:events:532:35)
    at Server.<anonymous> (/usr/local/lib/node_modules/pm2/node_modules/@pm2/io/build/main/metrics/httpMetrics.js:152:37)
    at emitCloseNT (node:net:1677:8)
    at processTicksAndRejections (node:internal/process/task_queues:82:21) {
  code: 'ERR_SERVER_NOT_RUNNING'
}
[2022-12-21 09:57:39] Error [ERR_SERVER_NOT_RUNNING]: Server is not running.
    at new NodeError (node:internal/errors:371:5)
    at Server.close (node:net:1624:12)
    at Object.onceWrapper (node:events:639:28)
    at Server.emit (node:events:532:35)
    at Server.<anonymous> (/usr/local/lib/node_modules/pm2/node_modules/@pm2/io/build/main/metrics/httpMetrics.js:152:37)
    at emitCloseNT (node:net:1677:8)
    at processTicksAndRejections (node:internal/process/task_queues:82:21) {
  code: 'ERR_SERVER_NOT_RUNNING'
}`

thx, deleted. 
these Logs at same time, but today old logs.

**Comment by lenusch** [comment]
Oh i remeber that i made an backup, then update and then refreshed the Frontend in order to see if everything was working. It was not working. Service was down / some error Message from Apache or NGINX but maybe pressing refresh 10-20 times made the initial/last command "create Backup" new. 

So pressing refresh, it shows nothing because server issues but he got that command right and created hidden backup in background.... Hmmm

**Comment by louislam** [comment]
Not sure how to reproduce. The `*.bak` file(s) only be created if Uptime Kuma is trying to update.

**Comment by chakflying** [comment]
Closing as obsolete, as the database backup during migration was dropped in 17ae47d091e60268fe4814c87153e9e03f077ec4.
