### ISSUE TITLE
Data Backup

### ISSUE THREAD

**Issue by adm2k** [louislam/uptime-kuma#2529]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

Since the backup process in the app has been deprecated it says to backup the data volume instead. My question is what files? Here is what I see at /var/snap/docker/common/var-lib-docker/volumes/uptime-kuma/_data

kuma.db
kuma.db.bak20221231182940
kuma.db-shm
kuma.db-shm.bak0
kuma.db-shm.bak20221231182940
kuma.db-wal
kuma.db-wal.bak0
kuma.db-wal.bak20221231182940
upload

Thanks in advance!

### 🐻 Uptime-Kuma Version

1.19.2

### 💻 Operating System and Arch

Ubuntu Server 22.04

### 🌐 Browser

Version 108.0.5359.111 (Official Build) (64-bit)

### 🐋 Docker Version

20.10.17, build 100c70180f

**Comment by Computroniks** [comment]
kuma.db is the currently working database that contains configuration data as well as results so this should be backed up. Upload is, I assume a set up user uploaded assets used to customize the status page so that should also be backed up.

**Comment by adm2k** [comment]
Many thanks, I appreciate it!
