### ISSUE TITLE
Failed install uptime-kuma on Ubuntu jammy

### ISSUE THREAD

**Issue by Iliya5digital** [louislam/uptime-kuma#2533]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

I tried to install uptime-kuma on Ubuntu jammy with desktop experience.
Finishes with errors and not opened on Firefox writes "server not found".
![IMG_20230104_150918](https://user-images.githubusercontent.com/115736491/210553396-bff115ff-f10d-467a-be1b-ff7594d93729.jpg)
![IMG_20230104_150853](https://user-images.githubusercontent.com/115736491/210553403-065f5d48-3a72-4de8-813b-e7318da34f5f.jpg)
![IMG_20230104_150829](https://user-images.githubusercontent.com/115736491/210553404-57e9a17a-7eeb-481a-b472-c88df5f58aa3.jpg)
![IMG_20230104_150803](https://user-images.githubusercontent.com/115736491/210553406-fa5f96e7-aa6d-4e72-8581-fae153cb6a4c.jpg)
![IMG_20230104_150746](https://user-images.githubusercontent.com/115736491/210553411-32158b2b-9710-4c66-b1e6-2884e7cc9aae.jpg)

### 🐻 Uptime-Kuma Version

Lastest

### 💻 Operating System and Arch

Ubuntu jammy

### 🌐 Browser

Firefox 108.0.1

### 🐋 Docker Version

None

### 🟩 NodeJS Version

Lastest

**Comment by louislam** [comment]
> Required Tools:
>  [Node.js](https://nodejs.org/en/download/) >= 14
