### ISSUE TITLE
Where is the configuration file?

### ISSUE THREAD

**Issue by dminca** [louislam/uptime-kuma#2539]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

Hi guys,
just stumbled upon this yesterday, I've had a look in the repo and wiki and couldn't find the configuration file.

Is it possible to configure the endpoints in a configuration file? Or it's only available in the UI

### 🐻 Uptime-Kuma Version

latest

### 💻 Operating System and Arch

Linux

### 🌐 Browser

Safari

**Comment by Computroniks** [comment]
Currently configuration is done through the web interface and stored in the sqlite database. There is a request for an API #118 but this has not yet been implemented.
