### ISSUE TITLE
PromoSMS: Cannot send message/notification if too long

### ISSUE THREAD

**Issue by Krismm** [louislam/uptime-kuma#2544]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

Hi
I have a problem with PromoSMS notifications
PromoSMS does not send Down notifications (sends only Up)

I have additionally configured Email(SMTP) and sends Down and Up there.

Can anything be configured?

### 🐻 Uptime-Kuma Version

1.9.2

### 💻 Operating System and Arch

louislam/uptime-kuma:1.9.2-debian-data-2

### 🌐 Browser

Microsoft Edge Wersja 108.0.1462.54 

### 🐋 Docker Version

louislam/uptime-kuma:1.9.2-debian-data-2

**Comment by louislam** [comment]
https://github.com/louislam/uptime-kuma/blob/bc7271b99c1962ad4820178418527e3d88b132d1/server/notification-providers/promosms.js#L22

Just have a quick look, both up/down notifications sent thought the same function. 

@PopcornPanda any idea?

**Comment by Krismm** [comment]
During the Down event, the following message appears in the console:

`Cannot send notification to XXX-Powiadomienie
Error: Error: Error: Error: Something gone wrong. Api returned 204.  
    at PromoSMS.throwGeneralAxiosError (/app/server/notification-providers/notification-provider.js:32:15)
    at PromoSMS.send (/app/server/notification-providers/promosms.js:36:18)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async Function.sendNotification (/app/server/model/monitor.js:595:21)
    at async Timeout.beat [as _onTimeout] (/app/server/model/monitor.js:353:17)
Monitor #5 'TerminalXX - XX': Failing: PING 192.168.3.166 (192.168.3.166) 56(84) bytes of data.

--- 192.168.3.166 ping statistics ---
10 packets transmitted, 0 received, 100% packet loss, time 14ms`

That is, the values of the transferred data are incorrect

How can I see what is sent by the API?

**Comment by louislam** [comment]
Checked PromoSMS API
> 204 	Wiadomość jest dłuższa niż 1 sms

Google Translate:
> 204 The message is longer than 1 sms

I marked it as bug, see if anyone could fix it.

**Comment by Krismm** [comment]
Okay, I've got something (debug promosms.js)

when the UP status is sent the date field looks like:

```
Start Send SMS2 : -----
{
  recipients: [ '+48XXXXXXXX' ],
  text: '[Terminal02 - 3.166] [ Up] ',
  type: 3,
  sender: 'MTM-Kuma'
}
```

but when Down is sent the date field looks like this

```
Start Send SMS2 : -----
{
  recipients: [ '+48XXXXXXX' ],
  text: '[Terminal02 - 3.166] [ Down] PING 192.168.3.166 (192.168.3.166) 56(84) bytes of data.\n' +
    '\n' +
    '--- 192.168.3.166 ping statistics ---\n' +
    '10 packets transmitted, 0 received, 100% packet loss, time 13ms\n' +
    '\n',
  type: 3,
  sender: 'MTM-Kuma'
}
```

**Comment by PopcornPanda** [comment]
Sorry for long response time. I've to test changes for allowing long messages to be sent.
By default, PromoSMS allows sending 160 characters or 70 if special characters are used.

Fix should be ready today.
