### ISSUE TITLE
Twillio Sms - Missing ? 

### ISSUE THREAD

**Issue by WaffleBoyQc** [louislam/uptime-kuma#2545]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

Hi , 
I want to know if Twillio Sms is removed cause i run Version: 1.19.3
and i dont have it on my list

### 🐻 Uptime-Kuma Version

1.19.3

### 💻 Operating System and Arch

Ubuntu 22.04

### 🌐 Browser

Chrome

**Comment by louislam** [comment]
> Twillio Sms is removed

What do you mean, how did you set Twillio Sms previously? Via Apprise?
