### ISSUE TITLE
Status Pages Backup/Location??

### ISSUE THREAD

**Issue by josh-lexisnexis** [louislam/uptime-kuma#2548]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

Where are the Status Page connections stored? or how do you backup the Status Pages? 

When I created a new docker Uptime-Kuma setup and attempted to restore from the backup json file, I did not get any of the Status Pages. I checked the json backup file and see anything about the Status Pages. 

Additional Places I checked:
   I did check the kuma.db file and saw the status_page table which contains the slug and basic information about the Status Page, but did not find anything which links the monitors to the Status Pages. A bit of insight will be helpful. 

### 🐻 Uptime-Kuma Version

1.19.3

### 💻 Operating System and Arch

Centos 7

### 🌐 Browser

Firefox

### 🐋 Docker Version

Docker 1.13.1

**Comment by louislam** [comment]
The backup feature is currently not actively maintained, so it is deprecated. (There are a warning message in the backup page)

Just copy and paste the whole `./data` directory

**Comment by alimahjoub** [comment]
Hi I'm on  uptime  root/uptime I installed it with Docker Compose, where is the data path now?

**Comment by CommanderStorm** [comment]
Where is the volume in the docker compose file pointing?
If your mount is to a local volume => there
If it is pointing to a named volume => `docker volume inspect NAMED_VOLUME`

**Comment by alimahjoub** [comment]
Hi
![Uploading Screenshot_20240823_180217_Termius.jpg…]()

**Comment by CommanderStorm** [comment]
Hi
The screenshot is not uploaded

**Comment by alimahjoub** [comment]
OK 
![Screenshot_20240823_180217_Termius](https://github.com/user-attachments/assets/e7cdada7-b082-4514-8652-111552dc59cd)

**Comment by CommanderStorm** [comment]
Instead of giving you the answer, lets help you fix this the next time yourself.
=> what have you configured here?

![image](https://github.com/user-attachments/assets/5c262ca5-c7e0-43ec-8e1a-8e2637ac22ac)

> [!TIP]
> the docker compose docs for `volume` are [here](https://docs.docker.com/reference/compose-file/volumes/).

**Comment by alimahjoub** [comment]
/srv/uptime/
Should I backup the whole uptime folder to transfer to the new server?

**Comment by CommanderStorm** [comment]
Yes, that is the most likely what you want.
But make sure that 
- the app is shut down before starting to transfer data
- check file integrity after transfering data

**Comment by alimahjoub** [comment]
Tanks bro
