### ISSUE TITLE
Kuma local install

### ISSUE THREAD

**Issue by drifter75** [louislam/uptime-kuma#255]
**Info**
Uptime Kuma Version: 1.3.2
Using Docker?: **No**
OS: Debian 10

Getting below error after running 

vite v2.4.4 building for production...
transforming (567) node_modules/vue-chart-3/node_modules/lodash/_assocIndexOf.jsKilled
npm ERR! code ELIFECYCLE
npm ERR! errno 137
npm ERR! uptime-kuma@1.3.2 build: `vite build`
npm ERR! Exit status 137
npm ERR!
npm ERR! Failed at the uptime-kuma@1.3.2 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-08-25T07_32_50_555Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 137
npm ERR! uptime-kuma@1.3.2 setup: `git checkout 1.3.2 && npm install && npm run build`
npm ERR! Exit status 137
npm ERR!
npm ERR! Failed at the uptime-kuma@1.3.2 setup script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-08-25T07_32_50_679Z-debug.log
[PM2] Starting /usr/bin/npm in fork_mode (1 instance)
[PM2] Done.
┌─────┬────────────────┬─────────────┬─────────┬─────────┬──────────┬────────┬──────┬───────────┬──────────┬──────────┬──────────┬──────────┐
│ id  │ name           │ namespace   │ version │ mode    │ pid      │ uptime │ ↺    │ status    │ cpu      │ mem      │ user     │ watching │
├─────┼────────────────┼─────────────┼─────────┼─────────┼──────────┼────────┼──────┼───────────┼──────────┼──────────┼──────────┼──────────┤
│ 0   │ uptime-kuma    │ default     │ N/A     │ fork    │ 26361    │ 4m     │ 210  │ online    │ 0%       │ 21.6mb   │ root     │ disabled │

**Comment by louislam** [comment]
Your system killed the install process, make sure your system have enough free RAM to do the task.

Delete the pm2 task by `pm2 delete uptime-kuma` and try to run again.
