### ISSUE TITLE
1.19.3 only listening on IPv6

### ISSUE THREAD

**Issue by Justinzobel** [louislam/uptime-kuma#2551]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

Fresh install on Ubuntu Jammy 22.04

```
sudo netstat -tunlp | grep 3001
tcp6       0      0 :::3001                 :::*                    LISTEN      38261/node          
```

I have started it and it's only listening on IPv6 which I don't want, I want it to at least also listen on IPv4

### 🐻 Uptime-Kuma Version

1.19.3

### 💻 Operating System and Arch

Ubunt 22.04

### 🌐 Browser

Firefox 108

### 🟩 NodeJS Version

19.3.0

**Comment by louislam** [comment]
Did you try to connect via ipv4? I think netstat is inaccurate.

`curl 127.0.0.1:3001`
