### ISSUE TITLE
Add a hyperlink option in Status page to the service/website it monitors

### ISSUE THREAD

**Issue by SebastianGwizdala** [louislam/uptime-kuma#2554]
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

UI Feature

### 🔖 Feature description

Option to add a hyperlink to an item in Status page

### ✔️ Solution

On click it opens in new tab(window) specified link to the service/website it monitors. Fuctionality of Heimdall/Homer dashboard.

**Comment by Computroniks** [comment]
This has already been implemented
