### ISSUE TITLE
weekly maintenance window

### ISSUE THREAD

**Issue by robkooper** [louislam/uptime-kuma#2559]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

I have a server that is shutdown on Friday 6pm and brought back on Sunday 6pm. I tried to figure out how to set this up. The only thing that seemed to work is this: 
<img width="608" alt="image" src="https://user-images.githubusercontent.com/1580696/211129654-e2127c65-bcc2-4923-af8b-72e30a175745.png">

If I set it to be from 6pm to 6pm (either of the two times) it will not go into maintenance mode.

### 🐻 Uptime-Kuma Version

1.19.3

### 💻 Operating System and Arch

Docker container amd64

### 🌐 Browser

Chrome

### 🐋 Docker Version

20.10.21

**Comment by spali** [comment]
Not tested, but maybe you can do it with 3 separate maintenance windows, one for each day?
With that you can control the time for each day separately.
At least in theory it should work 😉  Let us know.
