### ISSUE TITLE
Restart containers that not respond

### ISSUE THREAD

**Issue by Ansem93** [louislam/uptime-kuma#256]
It would be cool if Kuma could restart the containers that won't respond.
I have multiple containers using an other one as network, sometimes that container doesn't respond and so everything will stop working.

**Describe the solution you'd like**
Add a way to restart one or more containers if one goes down.

**Describe alternatives you've considered**
Since it support Kubernetes, that is some kind of automation tool as far as I know, maybe add to the wiki some way to have Uptime Kuma tells to Kubernetes to start a script to restart the containers.

**Comment by srgvg** [comment]
Kubernetes has probes (liveness, readiness, ...) to be configured in the container, for that.
I think such a feature in uptime-kuma would be an anti-pattern.
At most, perhaps a way to trigger a generic action, script, or so, in the same way and at the same time a notification is triggered, could be interesting. IMHO.

**Comment by louislam** [comment]
Zero knowledge of K8s. 
Currently, there are healthcheck in Docker image and healthcheck js script. Does K8s skip this?  

https://github.com/louislam/uptime-kuma/blob/4c1f2f85f8ae22b632cc22ba873a5279c7ff0ba9/dockerfile#L24

**Comment by srgvg** [comment]
That is for the health check of the uptime-kuma container itself; Kubernetes deployments has this health check redefined here https://github.com/louislam/uptime-kuma/blob/4c1f2f85f8ae22b632cc22ba873a5279c7ff0ba9/kubernetes/uptime-kuma/deployment.yml#L28-L32

OP is AFAICS asking for possibility to restart containers of the applications it monitors.

**Comment by Ansem93** [comment]
> At most, perhaps a way to trigger a generic action, script, or so, in the same way and at the same time a notification is triggered, could be interesting. IMHO.

This is what I was thinking. Sorry for the bad exposure :(

> Zero knowledge of K8s.
> Currently, there are healthcheck in Docker image and healthcheck js script. Does K8s skip this?
> 
> https://github.com/louislam/uptime-kuma/blob/4c1f2f85f8ae22b632cc22ba873a5279c7ff0ba9/dockerfile#L24
The containers are not unhealty, from docker point of view they're fine so the unhealthy check doesn't work :/

**Comment by srgvg** [comment]
> The containers are not unhealty, from docker point of view they're fine so the unhealthy check doesn't work :/

Then you need to improve the container healthcheck.

**Comment by louislam** [comment]
> That is for the health check of the uptime-kuma container itself; Kubernetes deployments has this health check redefined here
> 
> https://github.com/louislam/uptime-kuma/blob/4c1f2f85f8ae22b632cc22ba873a5279c7ff0ba9/kubernetes/uptime-kuma/deployment.yml#L28-L32
> 
> OP is AFAICS asking for possibility to restart containers of the applications it monitors.

Understand. I suggest that op could make use of webhook notification to your own "restart api", do something if you see the status is "down".
