### ISSUE TITLE
Domain Name in Kuma docker

### ISSUE THREAD

**Issue by megasmorf** [louislam/uptime-kuma#2561]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

I have Kuma with docker installation so my format now is http://serverip/kumasetup/xxx my question is how can i have domain with https:// in kuma for example kuma.mydomain.xxx

### 🐻 Uptime-Kuma Version

1.19.3

### 💻 Operating System and Arch

Ubuntu 20.04.5 LTS

### 🌐 Browser

Google Chrome

### 🐋 Docker Version

Docker version 20.10.22, build 3a2c30b

**Comment by DimitriDR** [comment]
You can. You need a reverse proxy or you can also use Cloudflare tunnels.
However, It is not a bug linked to Uptime Kuma.

**Comment by megasmorf** [comment]
how can i do that with reverse proxy can you help me?

**Comment by louislam** [comment]
Many methods, but I recommend Cloudflare Tunnel.

https://github.com/louislam/uptime-kuma/wiki/Reverse-Proxy-with-Cloudflare-Tunnel

**Comment by megasmorf** [comment]
i tried with my apache but dont work  can you see where is the errror

apache file


<ifModule mod_ssl.c>
<VirtualHost *:4443>
  ServerName status.xxx.xxx
  SSLEngine On
  SSLCertificateFile /etc/letsencrypt/live/status.xxx.xxx/fullchain.pem
  SSLCertificateKeyFile /etc/letsencrypt/live/status.xxx.xxx/privkey.pem
  # Protocol 'h2' is only supported on Apache 2.4.17 or newer.
  Protocols h2 http/1.1

  ProxyPass / http://localhost:3001/
  RewriteEngine on
  RewriteCond %{HTTP:Upgrade} =websocket
  RewriteRule /(.*) ws://localhost:3001/$1 [P,L]
  RewriteCond %{HTTP:Upgrade} !=websocket
  RewriteRule /(.*) http://localhost:3001/$1 [P,L]
</VirtualHost>
</ifModule>

and composer file


# Simple docker-compose.yml
# You can change your port or volume location

version: '3.3'

services:
  https-portal:
    image: steveltn/https-portal:1
    ports:
      - '8087:8087'
      - '4443:4443'
    links:
      - uptime-kuma
    restart: always
    environment:
      DOMAINS: 'status.xxx.xxx -> http://status.xxx.xxx:3001'
      STAGE: 'production' # Don't use production until staging works
      # FORCE_RENEW: 'true'
      WEBSOCKET: 'true'
    volumes:
      - https-portal-data:/var/lib/https-portal

  uptime-kuma:
    image: louislam/uptime-kuma:1
    container_name: uptime-kuma
    volumes:
      - ./uptime-kuma:/app/data
    ports:
      - 3001:3001

volumes:
  https-portal-data:

**Comment by yehudaTiram** [comment]
I followed this 
https://www.wpdoze.com/install-uptime-kuma/
And it worked smoothly. See if it helps.
