### ISSUE TITLE
using uptime kuma without installing it

### ISSUE THREAD

**Issue by Mohammadnyc** [louislam/uptime-kuma#2562]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

is there any site that has installed uptime kuma in its server and we create account on it and add our ip or domain to check it?

### 🐻 Uptime-Kuma Version

1.19.3

### 💻 Operating System and Arch

20.4

### 🌐 Browser

chrome 107

### 🐋 Docker Version

docker 20.10

### 🟩 NodeJS Version

14.18.0

**Comment by louislam** [comment]
No, Uptime Kuma currently is just an open source application. Not a service provider.

**Comment by tobiasReichel** [comment]
you could use a poster like linode they have a one klick installer cheapest plan is 5€

**Comment by tobiasReichel** [comment]
or you could use https://www.pikapods.com/ 

really cheap managed hosting
