### ISSUE TITLE
Hyperlink on Certificate expiring not Working Discord Webhook

### ISSUE THREAD

**Issue by RappyTV** [louislam/uptime-kuma#2563]
### ⚠️ Please verify that this bug has NOT been raised before.

- [x] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### Description

I have a configured a Discord Webhook that informs me, when my certificate expires. It's not that important and just a litte typo bug, but the Hyperlink is not working.
Discord hyperlinks work like this: `[LABEL](URL)` but the webhook sends it like this: `[LABEL][URL]`

### 👟 Reproduction steps

Use a discord webhook on the certificate checker

### 👀 Expected behavior

It should send `[Main Page](url) Certificate will be expired in 7 days` (so the second curly brackets should be parenthesis)

### 😓 Actual Behavior

It sends `[Main Page][url] Certificate will be expired in 7 days`

### 🐻 Uptime-Kuma Version

1.18.5

### 💻 Operating System and Arch

Ubuntu 22.04 x64

### 🌐 Browser

Opera GX 93.0.4585.84

### 🟩 NodeJS Version

18.12.1

**Comment by louislam** [comment]
It is not markdown.
