### ISSUE TITLE
Localization of the status page

### ISSUE THREAD

**Issue by whonion** [louislam/uptime-kuma#2564]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### Description

When you change the default language element to another and then back to English, the element with the class "data-v-7d4a7f28" does not change its value.

### 👟 Reproduction steps

1. You need to change the default language, for example, to your native language.
2. Set the status page, add "Services".
3. Go back to the settings and set the default language (English)
4. Go to the status page.
The Services header element will still be in your native language:
spaneditable="false" data-v-7d4a7f28="" data-v-c15243e4="">Services</span>

### 👀 Expected behavior

Change the language of the elements, according to the general settings

### 😓 Actual Behavior

The language change does not occur on all elements

### 🐻 Uptime-Kuma Version

1.19.3

### 💻 Operating System and Arch

20.04

### 🌐 Browser

Chromium 108.0.5359.99

### 🐋 Docker Version

20.10.22

### 📝 Relevant log output

```shell
<span contenteditable="false" data-v-7d4a7f28="" data-v-c15243e4="">Services</span>
```

**Comment by louislam** [comment]
Yes, work as expected. It is free text, not an fixed name. You can rename it.

**Comment by whonion** [comment]
That's right, how could I not see it.
But it turns out when I change the language, this text is translated into my native language, but when I change it back it remains the same.
Thanks!
But if I can edit it doesn't matter anymore

**Comment by goncalopolido** [comment]
I don't think you really understood... Having the same "issue" right now. @louislam

**Comment by goncalopolido** [comment]
I don't think you really understood @louislam ... Having the same "issue" right now, I can be more specific if you want.

**Comment by MDjaa** [comment]
The issue is when during setup lets say I picked up Arabic, then went back to English , it does not update. 
it will need me to re-install in-order to change that .. if there is another way please tell me.

**Comment by CommanderStorm** [comment]
If it is reproducible, a new issue with a reproduction would be nice.
This way, I could mark it as a good first issue.

This issue remains resolved as what OP was raising as a bug is free text, not a fixed name
