### ISSUE TITLE
Allow save date of negative number

### ISSUE THREAD

**Issue by epicseven-cup** [louislam/uptime-kuma#2565]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### Description

go to Setting -> Monitor History -> fill in -1 or any negative number for [Keep monitor history data for 365 days.] and kuma will accept the value as save date.

![image](https://user-images.githubusercontent.com/59263116/211182335-0fa54508-ce9c-42e8-8539-5494076804cc.png)

### 👟 Reproduction steps

go to Setting -> Monitor History -> fill in -1 or any negative number for [Keep monitor history data for 365 days.] and kuma will accept the value as save date.

### 👀 Expected behavior

when putting in negative number in keep monitor history data will return an error. For infinite date I think maybe it can be a button next to the input box and grey out the input box for keep monitor history data once its clicked

### 😓 Actual Behavior

it accept the negative number

### 🐻 Uptime-Kuma Version

1.19.3

### 💻 Operating System and Arch

Arch Linux x86_64

### 🌐 Browser

firefox

### 🐋 Docker Version

Docker version 20.10.22

### 🟩 NodeJS Version

N/A

**Comment by Computroniks** [comment]
I will have a look at this tonight.

**Comment by Computroniks** [comment]
This should have been addressed by #2569
