### ISSUE TITLE
Cant open after installation

### ISSUE THREAD

**Issue by papahausa** [louislam/uptime-kuma#2568]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

Hi, who can help?
Already installed. https://prnt.sc/LBEdvEgB6rfU
but when i try open page i got error: 
https://uptime.your-services.online:3001/ - cant open
https://uptime.your-services.online - white page

### 🐻 Uptime-Kuma Version

1.19

### 💻 Operating System and Arch

Almalinux 8.x

### 🌐 Browser

Firefox, Chrome, safari

### 🟩 NodeJS Version

14.21

**Comment by papahausa** [comment]
Port is opened now. all works. 
How to setup letsencrypt ssl?

**Comment by louislam** [comment]
Check Reverse Proxy: https://github.com/louislam/uptime-kuma/wiki/Reverse-Proxy

I recommend Cloudflare Tunnel if your domain hosted on Cloudflare. Caddy is the second choice.
