### ISSUE TITLE
Some questions about "Retries" 

### ISSUE THREAD

**Issue by syouko** [louislam/uptime-kuma#257]
**Is it a duplicate question?**
Please search in Issues without filters: https://github.com/louislam/uptime-kuma/issues?q=

**Info**
Uptime Kuma Version:
Using Docker?:  Yes
OS: Debian 10.2
Browser: Chrome Latest

Just a little doubt about "Retries"

If I set "Heartbeat Interval" = 60s
And
"Retries" = 10

It is means From the first down until it notify me will cost 60s x 10 =600s?

What if I set "Heartbeat Interval" = 600s? Will it cost 6000s?

**Comment by louislam** [comment]
Correct.

**Comment by syouko** [comment]
> Correct.

Thanks~
