### ISSUE TITLE
Make page public

### ISSUE THREAD

**Issue by mfnalex** [louislam/uptime-kuma#2571]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

Hello, is it possible to make the status page public? Currently it only shows the login screen when I'm not logged in, however I'd like to make the status page public for everyone.

### 🐻 Uptime-Kuma Version

1.19.3

### 💻 Operating System and Arch

Ubuntu 20.04 amd64

### 🌐 Browser

Safari Version 16.2 (18614.3.7.1.5)

### 🐋 Docker Version

Docker version 20.10.22, build 3a2c30b

**Comment by louislam** [comment]
Status page is already public. You may need to change the entry page or use the dedicated url `http://example.com/status/<slug>`.

**Comment by Loughty** [comment]
> Status page is already public. You may need to change the entry page or use the dedicated url `http://example.com/status/<slug>`.
> 
> Check wiki for more info: https://github.com/louislam/uptime-kuma/wiki/Status-Page

Using `http://[host]:3001/status` or `http://[host]:3001/status/default` just give me a blank page.

The port 80 isn’t blocked, but using `http://[host]` return nothing, so, I don't know what do you refer by _"expose your Uptime Kuma in port 80"_, I don't find anything in the configuration that let me choose if the public status page is enabled or not.

**Comment by louislam** [comment]
> Using `http://[host]:3001/status` or `http://[host]:3001/status/default` just give me a blank page.

You have to create a status page first in the dashboard.



> The port 80 isn’t blocked, but using http://[host]

Reverse proxy is recommended, because port 80 is not encrypted.

You can choose your favorite one:
https://github.com/louislam/uptime-kuma/wiki/Reverse-Proxy
