### ISSUE TITLE
UTC Timezone in email alerts

### ISSUE THREAD

**Issue by attinderdhillon** [louislam/uptime-kuma#2573]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 👟 Reproduction steps

I am on latest docker image 1.19.3 on ubuntu sever. Both display timezone and server timezone are set to Asia/Kolkata.  Alerts still have UTC time.

I thought the issue have been resolved in latest releases. 

### 👀 Expected behavior

Alert time as server timezone.

### 😓 Actual Behavior

Alert timezone UTC. 

### 🐻 Uptime-Kuma Version

1.19.3

### 💻 Operating System and Arch

Ubuntu Server 22.04 x64

### 🌐 Browser

Google Chrome

**Comment by louislam** [comment]
Duplicate of #2360
