### ISSUE TITLE
Uptime counts over 100%

### ISSUE THREAD

**Issue by stuzer05** [louislam/uptime-kuma#258]
**Describe the bug**
After a poweroff and restart kuma reported
```
[example.com] [🔴 Down] getaddrinfo EAI_AGAIN example.com
[example.com] [✅ Up] 200 - OK
```
and uptime started showing 100.58%

**To Reproduce**
1. Add domain
2. Unplug power cable from server
3. Restart server

**Expected behavior**
I expect `getaddrinfo EAI_AGAIN` to be logged, now it's clearly not

**Info**
- Uptime Kuma Version: 1.3.2
- Using Docker?: Yes
- OS: Linux 5.10.60-v7l+ armv7l GNU/Linux
- Browser: Firefox

**Screenshots**
![image_2021-08-25_13-28-03](https://user-images.githubusercontent.com/23124682/130774626-ad13e368-93f1-42fa-aec2-43ab1ffac615.png)

**Comment by louislam** [comment]
> Unplug power cable from server

Does your server have cmos battery? My guess is that unplugging power cable affects your system.

**Comment by stuzer05** [comment]
No, I'm running raspberry pi. It doesn't have cmos battery.

**Comment by louislam** [comment]
Just re-check the calculation, if uptime > 100%, that means downtime is a negative number.

https://github.com/louislam/uptime-kuma/blob/a7cd70f7de807533cfc7f9b5ff2b55b3145a036b/server/model/monitor.js#L407

If it is a negative number, that means the second beat's time is earlier than the first beat. It is impossible if the system time is correct.

https://github.com/louislam/uptime-kuma/blob/a7cd70f7de807533cfc7f9b5ff2b55b3145a036b/server/model/monitor.js#L106

And there is no way for Uptime Kuma to determine whether the time is correct or not. 

My suggestion is you should shutdown gradually and you need to confirm the time is synced on boot before starting Uptime Kuma.

**Comment by stuzer05** [comment]
> If it is a negative number, that means the second beat's time is earlier than the first beat. It is impossible if the system time is correct.

Will look into it, thanks.

**Comment by stuzer05** [comment]
Maybe skip disordered entries or sort somehow?
