### ISSUE TITLE
Cant install from local - Debain 11

### ISSUE THREAD

**Issue by deanfourie1** [louislam/uptime-kuma#2583]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### Description

![Capture2](https://user-images.githubusercontent.com/71812804/211676869-29290fc2-3b4f-4fc5-93c3-5bdd4554d89c.PNG)

Getting this error when attempting to install using the local option rather then docker.

### 👟 Reproduction steps

Everything is from scratch, new install of Debain 11

### 👀 Expected behavior

Install

### 😓 Actual Behavior

Doesnt Install

### 🐻 Uptime-Kuma Version

latest release

### 💻 Operating System and Arch

Debain 11

### 🌐 Browser

none

### 🐋 Docker Version

none

**Comment by cyril59310** [comment]
hi, your version of node js does not seem to be the right version you need Node.js >= 14

![image](https://user-images.githubusercontent.com/70776486/211680245-691bfd8f-9349-44dc-a455-76b3ab1438fa.png)

**Comment by deanfourie1** [comment]
Yea sorry I saw that just before and installed latest version. All working now.

Sorry
