### ISSUE TITLE
Add a possibility to make groups and priority's 

### ISSUE THREAD

**Issue by vslinuxdotnet** [louislam/uptime-kuma#2585]
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

Other

### 🔖 Feature description

Create groups names and priority number by machine, if a  machine in a group fails first, don't try others in same group because all will be down. Example: 100 alerts will be send at the moment in one gateway fails...

### ✔️ Solution

If one machine with priority 0 in same group fails don't try to check if others with priority 1,2,3 are alive.
Only one alert is send inform that groups name, machine is down.

**Comment by chakflying** [comment]
#1236 will basically meet your needs.

**Comment by CommanderStorm** [comment]
@vslinuxdotnet https://github.com/louislam/uptime-kuma/pull/2693 has been merged and is avaliable in `1.22`.
I think this issue is resolved. Could you close this issue?

**Comment by CommanderStorm** [comment]
@
We are consolidating duplicate issues a bit to make issue management easier.
I think, we should track this issue in https://github.com/louislam/uptime-kuma/pull/2693 https://github.com/louislam/uptime-kuma/issues/1089 https://github.com/louislam/uptime-kuma/issues/2487 as there is no functional difference (maybe just small naming differences, but nothing that would require a different issue imo)
⇒ I am going to close this as a duplicate.
