### ISSUE TITLE
Defaults for interval/retry or bulk edit

### ISSUE THREAD

**Issue by luckman212** [louislam/uptime-kuma#2590]
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

Other

### 🔖 Feature description

It would be awesome if:

- defaults could be set somewhere so new monitors default to 60-3-20 (for example)
- we could select multiple monitors (of same type) and change the parameters en masse

### ✔️ Solution

After setting up 40 or so ICMP monitors, I started getting false alarms with 1 dropped ping packet. I realized the defaults of 60-0-60 are not ideal for me. I prefer 60-3-20. But now I have to manually edit each monitor and re-save it.

### ❓ Alternatives

I think I could execute some SQL directly on the db to do the bulk update of these parameters, but I am not sure if that is safe.

**Comment by luckman212** [comment]
For now, I poked around the SQLite db and figured out how to do it manually.

List all monitors with some detail
```
# sqlite3 -header /app/data/kuma.db 'select id,type,name,hostname,interval,maxretries,retry_interval from monitor'
```

Update all ICMP monitors that don't have retries==3 and interval==20:
```
# sqlite3 /app/data/kuma.db 'UPDATE monitor SET maxretries = 3, retry_interval = 20 WHERE type = "ping" AND (maxretries != 3 OR retry_interval != 20)'
```

**Comment by CommanderStorm** [comment]
@luckman212 
I think this is a partial duplicate of https://github.com/louislam/uptime-kuma/issues/455
Duplicates only create immortal zombies and are really hard to issue-manage.
Could you edit your issue (description + title) to make this unique? ^^

**Comment by luckman212** [comment]
@CommanderStorm You are correct, this appears to be a duplicate of #455. I will close this one, thank you.
