### ISSUE TITLE
Clear Event Data

### ISSUE THREAD

**Issue by erencylk** [louislam/uptime-kuma#2591]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### Description

Clear event data and system is down. Not clear event data

### 👟 Reproduction steps

Clear event data

### 👀 Expected behavior

Clear event data

### 😓 Actual Behavior

system down

### 🐻 Uptime-Kuma Version

1.19.4

### 💻 Operating System and Arch

Ubuntu 20.04

### 🌐 Browser

Chrome

**Comment by Computroniks** [comment]
Hi @erencylk 

Could you provide some more information so we can help diagnose the issue

* Are you running on docker or using nodejs
* What is your docker version / nodejs version
* Logs from docker / console
* Any error messages from the web interface
* Detailed reproduction steps, i.e add this monitor with these settings, then click this button and this will happen. One line doesn't really help us when we attempt to reproduce the error.

**Comment by CommanderStorm** [comment]
Given that this issue does not include the minimum required information to debug on, I am going to close this as `no repro`. Clearing events does work for me.

If this was a case of the db blocking for too long and the helthcheck terminating the container, this will be resolvd in `v2.0` via the introduction of an external db
