### ISSUE TITLE
False positive?

### ISSUE THREAD

**Issue by vespino** [louislam/uptime-kuma#2598]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

I have the following url on which I’m looking for “on sale soon”: https://www.cedarpoint.com/vip-experiences. It’s clearly there, but I’m getting an error: 200 - , but keyword is not in [ (function(w,d,s,l,i){w[l]=w...]

### 🐻 Uptime-Kuma Version

1.19.4

### 💻 Operating System and Arch

Docker

### 🌐 Browser

Firefox 108.2

**Comment by vespino** [comment]
I looked at the source code of the page and close to the top it shows “function(w,d,s,l,i)”. I’m also able to download the page’s source using cURL which then contains the keyword I want to monitor.

**Comment by d3xter** [comment]
You are searching for lower case "on sale soon", but the web page contains upper case "On Sale Soon", 
thats why the keyword is not found
