### ISSUE TITLE
Allow SMTP notification without user/password

### ISSUE THREAD

**Issue by FuzzyMistborn** [louislam/uptime-kuma#26]
I'm running Mailrise (https://github.com/YoRyan/mailrise) for my SMTP relay to then use any Apprise notifier.  It works fine when I test it, but I can't save my settings as I don't have a username/password set.  Any chance to remove that restriction?

**Comment by louislam** [comment]
1.0.2 updated for this

**Comment by NeuralMiner** [comment]
It appears this still might be an issue; though the requirement for a UID/PW was removed when setting up the alert, it'll fail with `Missing credentials for "PLAIN"` when attempting to send SMTP without credentials.
It looks like this project had the same issue: https://github.com/directus/directus/issues/5652
I was able to get it working by manually setting the following line to `auth: false,`: https://github.com/louislam/uptime-kuma/blob/2461f5084e2ef58f3ecfd6f1ece8ade7faa4cb8e/server/notification.js#L376-L379
So I assume a check just has to be made first to check if a UID/PW is set, and if not, set auth to false?

**Comment by louislam** [comment]
> It appears this still might be an issue; though the requirement for a UID/PW was removed when setting up the alert, it'll fail with `Missing credentials for "PLAIN"` when attempting to send SMTP without credentials.
> It looks like this project had the same issue: [directus/directus#5652](https://github.com/directus/directus/issues/5652)
> I was able to get it working by manually setting the following line to `auth: false,`:
> 
> https://github.com/louislam/uptime-kuma/blob/2461f5084e2ef58f3ecfd6f1ece8ade7faa4cb8e/server/notification.js#L376-L379
> 
> 
> So I assume a check just has to be made first to check if a UID/PW is set, and if not, set auth to false?

Should be fixed in 1.3.0
