### ISSUE TITLE
HTTP/HTTPS Global Keyword

### ISSUE THREAD

**Issue by manoeuvrelawliet** [louislam/uptime-kuma#2602]
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

Other

### 🔖 Feature description

We used to monitor multiple Websites using HTTP/HTTPS Keyword, but the Keyword can changes, therefore we need to edit them individually 

### ✔️ Solution

Please provide global keyword for HTTP/HTTPS keyword monitoring.

**Comment by CommanderStorm** [comment]
From my perspecitive a somewhat weird feature-request.
What are you trying to monitor?

I think this is better handled via other feature requests asking for more (imo generally usefull ^^) features:
- #455
- and #1323 

=> I am going to close this as a duplicate.
