### ISSUE TITLE
Hello and im from skylinegg and we want to help your open source project

### ISSUE THREAD

**Issue by RjManhas** [louislam/uptime-kuma#2607]
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

Other

### 🔖 Feature description

We will provide a another demo website that is hosted in the uk, since we like your open source project.
if you want to check our status page status.skylinegg.com.

### ✔️ Solution

faster speeds

**Comment by papahausa** [comment]
can u help me with installation?

**Comment by RjManhas** [comment]
Hello, i might be able to help if you can contact me at rjmanhas@skylinegg.com

**Comment by Justinzobel** [comment]
> Hello, i might be able to help if you can contact me at [rjmanhas@skylinegg.com](mailto:rjmanhas@skylinegg.com)

Please don't direct users away from the Github Issues. This removes potential solutions from the publicly viewable spaces.

**Comment by RjManhas** [comment]
well he asked us for help and i dont check github for this and, first of all he should not be asking in random issue threads.

**Comment by Justinzobel** [comment]
Agreed, so maybe direct them to a new thread instead of your inbox.

**Comment by papahausa** [comment]
> Hello, i might be able to help if you can contact me at [rjmanhas@skylinegg.com](mailto:rjmanhas@skylinegg.com)

check email.

**Comment by papahausa** [comment]
Ok. close this topic pls.

**Comment by RjManhas** [comment]
why would i close this topic?

**Comment by papahausa** [comment]
> why would i close this topic?

check email pls

**Comment by louislam** [comment]
The current demo is using this to manage demo sessions, but it is not perfect.
https://github.com/louislam/demo-kuma

**Comment by CommanderStorm** [comment]
@RjManhas is this issue resolved?

**Comment by Roomiiaan** [comment]
I think this issue can be closed. The page is no longer available
