### ISSUE TITLE
Monitors in Maintenance Mode incorrectly shown in Monitor count

### ISSUE THREAD

**Issue by Justinzobel** [louislam/uptime-kuma#2608]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### Description

I have several monitors in maintenance as per the screenshot attached but they are showing in the Unknown count instead of Maintenance

![image](https://user-images.githubusercontent.com/1370117/212436108-78dc1cd8-7b2f-469e-ba39-5a736b95ac44.png)

### 👟 Reproduction steps

Unknown

### 👀 Expected behavior

Monitors shown in Maintenance count

### 😓 Actual Behavior

Monitors shown in Unknown count

### 🐻 Uptime-Kuma Version

1.19.4

### 💻 Operating System and Arch

Ubuntu 22.04.1 x86_64

### 🌐 Browser

Firefox

### 🐋 Docker Version

N/A

### 🟩 NodeJS Version

19.3.0

**Comment by chakflying** [comment]
Cannot reproduce. What are the monitor types? Is there anything special about your setup?

**Comment by Justinzobel** [comment]
Standard HTTPS monitors. Install is done as per the wiki non-docker instructions.

**Comment by chintan-golakiya** [comment]
I am able to reproduce.
when scheduled maintenance starts for monitor and monitor status changes from up or down to maintenance, value of unknown is increased instead of value of maintenance
