### ISSUE TITLE
Maintenance isn't working

### ISSUE THREAD

**Issue by Nollknolle** [louislam/uptime-kuma#2615]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### Description

If I want to store a time period for a maintenance, it does not accept it.

Screenshots:
https://i.nlmyr.de/DkNV (Maintenance Dashboard)
https://i.nlmyr.de/xxVg (Date Time Section Maintenance)
https://i.nlmyr.de/5JIV (Date Time Picker Maintenance)

### 👟 Reproduction steps

Create maintenance and specify period.

### 👀 Expected behavior

Period is saved and works.

### 😓 Actual Behavior

Period is not saved and all maintenance is finished immediately.

### 🐻 Uptime-Kuma Version

1.19.4

### 💻 Operating System and Arch

Raspbian Arch64

### 🌐 Browser

Firefox 108.0.2

### 🐋 Docker Version

Docker 20.10.5+dfsg1

**Comment by Nollknolle** [comment]
https://user-images.githubusercontent.com/62543404/212680484-b23bbfbe-df65-4cb2-ac1a-52394807a57e.mp4

**Comment by sfxn** [comment]
had the same issue as @Nollknolle today but have just fonbd out how to do it the correct way.
It is not necessarily a bug but an unexpected behaviour as it is not totally intuitive.

If a mainenance windows is planned only for one day (start and end on same day) you still have to click the date *twice* as the first click sets the start date and the second click sets the end date.

When I tried it today, I only clicked once for the date, then switched to the time dialog where two times could be set.
<img width="275" alt="Screenshot 2023-01-17 at 00 05 25" src="https://user-images.githubusercontent.com/27781756/212777894-9f2f87b6-ec55-401c-863a-199dbd237267.png">

The result is accepted by the frontend but only the start date & time is shown. no end date & time.
<img width="275" alt="Screenshot 2023-01-17 at 00 05 25" src="https://user-images.githubusercontent.com/27781756/212777940-a9762c39-29bd-491b-b1b8-c378a6dfebc3.png">

The maintenance entry is then shown as "ended".

Now that I know how to use the workflow I can create correct time ranges but maybe it is possible to use the end date as star tdate when the user switches to the time setting or clicks on "Select".

**Comment by Nollknolle** [comment]
Thank you, @sfxn that worked. I had not known that you have to double-click the tag then. Maybe you can write that to it.

Greetings from Germany.

**Comment by louislam** [comment]
Yes, I think it may be an excepted behavior. 

I agree that this date picker is a bit confusing. Let me know if anyone find a better date picker.

**Comment by JacksonChen666** [comment]
> I agree that this date picker is a bit confusing. Let me know if anyone find a better date picker.

99% of the time it's better to use something already in HTML. https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/datetime-local
