### ISSUE TITLE
accidentally space in Hostname field

### ISSUE THREAD

**Issue by Scan4u** [louislam/uptime-kuma#2616]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### Description

Hello! Want to inform U concerning a small bug which cost me a little of time :)
Yesterday I add a new host, and during a copy of its ip address to the Hostname field i missed the space at the beginning of ip.
Instead of getting any warning, the entered ip was accepted and this new Monitor got the status "Down". So I spent some time before realise this extra space at the beginning of entered ip address.
Is it possible to add the additional checking of the data, entered to the Hostname field? At least for the extra spaces :)
![зображення](https://user-images.githubusercontent.com/16424225/212676440-55b6502e-a11c-430d-a959-8b11511d8d73.png)

### 👟 Reproduction steps

-

### 👀 Expected behavior

 Warning - check the entered data, entered to the Hostname field!

### 😓 Actual Behavior

No warning. Monitor is always Down.

### 🐻 Uptime-Kuma Version

1.19.4

### 💻 Operating System and Arch

Ubuntu 20.04

### 🌐 Browser

Firefox

### 🐋 Docker Version

Docker 20.10.22

### 🟩 NodeJS Version

-

### 📝 Relevant log output

```shell
-
```

**Comment by twiggotronix** [comment]
Hi,
There is an auto test for this function you could update here : https://github.com/louislam/uptime-kuma/blob/master/test/cypress/unit/util-frontend.spec.js

Just a thought, but couldn't we add a trim when we submt?
