### ISSUE TITLE
How to Set Minimum packet transmited on Ping Monitoring?

### ISSUE THREAD

**Issue by I-Fun** [louislam/uptime-kuma#2619]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem
hello there..

please kindly answer this question:

I installed Uptime Kuma Ver. 1.15.1 and when our network down it showing this :
![Screenshot 2023-01-16 223030](https://user-images.githubusercontent.com/7077766/212715035-dde48c8b-9573-47d1-9f54-0f43726eeb8b.png)

but when i upgrade Uptime kuma to the latest version (1.19.4) it showing this :
![Screenshot 2023-01-16 223045](https://user-images.githubusercontent.com/7077766/212715296-9c5c8a44-5150-489c-bf13-c4dcacbb700e.png)

it means down monitoring is way too sensitive, how to adjust that packet transmited? atleast i need more than 1 packet transmited.
i try to look on Sqlite file but i can't see that value or string similiar to that

anyone can answer this?
thanks for noticing this question 🥇 

### 🐻 Uptime-Kuma Version

1.19.4

### 💻 Operating System and Arch

Ubuntu 20.04 x86_64

### 🌐 Browser

Edge 108

**Comment by Computroniks** [comment]
Yeah, it is being looked into. It is to do with a change in ping module
