### ISSUE TITLE
Email body text

### ISSUE THREAD

**Issue by xserv-ag** [louislam/uptime-kuma#262]
Great app!

I am testing your app and i have made some display changes for discord notifications. 

Discord bot [notification:] 
![discord notification](https://user-images.githubusercontent.com/79256494/130799771-93f109e5-c481-484c-a357-8020f7a6424d.PNG)

I want to ask you if its possible to do the same this for email/smtp notifications.

**Comment by tgxn** [comment]
Hey @xserv-ag ;
I'm (potentially) going to make content changes for #232 and was looking for notification content feedback:

What changes have you made to the discord notifications?
