### ISSUE TITLE
Ability to set i.e. 2nd Tuesday for Day of Month maintenance strategy

### ISSUE THREAD

**Issue by Pingumania** [louislam/uptime-kuma#2621]
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

Other

### 🔖 Feature description

In the maintenance strategy 'Day of Month' I want the ability to select a day by name and it's number of occurrence.
Example: Every 2nd Wednesday

### ✔️ Solution

I patch my windows servers after each Microsoft patchday which is every 2nd Tuesday each month.

### ❓ Alternatives

The current workaround is to schedule the maintenance every week.

**Comment by jsexton-rahr** [comment]
We do something similar, with dev/stage the 2nd Wed and prod the 3rd Wed of the month (allow for testing of updates before they hit prod.

**Comment by CommanderStorm** [comment]
Related #3186

**Comment by CommanderStorm** [comment]
@Pingumania 
I noticed that #3186 is a good approach. Could you close this issue?

**Comment by Pingumania** [comment]
Closed in favor of https://github.com/louislam/uptime-kuma/issues/3186
