### ISSUE TITLE
Add badges maintenance label

### ISSUE THREAD

**Issue by Tealk** [louislam/uptime-kuma#2625]
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

UI Feature

### 🔖 Feature description

The [badges](https://github.com/louislam/uptime-kuma/pull/1119) should also show the maintenance mode, currently it is shown as Down

### ✔️ Solution

Add a maintenanceLabel=<maintenanceLabel>

**Comment by markusobi0** [comment]
There is already a bug report for this behavior: #2456
