### ISSUE TITLE
API to programmatically add and remove a maintenance window for a service

### ISSUE THREAD

**Issue by miguelarios** [louislam/uptime-kuma#2627]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

I have nightly Restic backups that set my Nextcloud instance to maintenance mode which causes an 503 error and notifies me via pushover as a critical notification since my Nextcloud instance is very important to me to keep up. I have set a recurring maintenance window during the backups but would be nice to have an api endpoint that I could curl as part of my bash script in my backup to add a maintenance for my Nextcloud instance to pause notifications. 

### 🐻 Uptime-Kuma Version

1.19.3

### 💻 Operating System and Arch

Debian 5.10.149-2

### 🌐 Browser

Firefox 108.1

### 🐋 Docker Version

Docker 20.10.22

**Comment by miguelarios** [comment]
Out the wrong label on this. It needs to be a feature request. Sorry!

**Comment by Computroniks** [comment]
Duplicate #118
