### ISSUE TITLE
uptime value exceeds 100%

### ISSUE THREAD

**Issue by spac3monkey** [louislam/uptime-kuma#2628]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### Description

![image](https://user-images.githubusercontent.com/97247944/213014602-4fa2c5a5-a30a-4da2-a085-c0dbfbc6a052.png)

### 👟 Reproduction steps

I don't know.

### 👀 Expected behavior

The max. uptime value should be 100%.

### 😓 Actual Behavior

The max. uptime value is over 100%.

### 🐻 Uptime-Kuma Version

1.19.3

### 💻 Operating System and Arch

Raspbian bullseye

### 🌐 Browser

Google Chrome, Safari, Mozilla Firefox

### 🐋 Docker Version

2.14.1

**Comment by Computroniks** [comment]
I think we just need a sanity check when displaying the uptime. I will look into implementing this tomorrow.

**Comment by chakflying** [comment]
I think this most likely is because of inaccurate system clock (common for raspberry pis), and the time went backwards. The question is, is hiding the real problem by e.g. clamping the value to 100% a better solution?

**Comment by louislam** [comment]
I cant find the old issue, but as @chakflying said, it is common issue for pi users.

Capping at 100% visually is good, but it will be hard to identify issues if we have make the calculation wrong in the future. I prefer to keep it as is for now.

**Comment by Computroniks** [comment]
Not sure if this affects both the status page and the dashboard, I assume it would. I would suggest only capping it on the status page, the thing that is shown to the public. This way we don't have obvious public facing errors whilst still having the ability to check if we broke the calculations but the bug isn't visible to the public.

**Comment by Computroniks** [comment]
This should have been fixed in #2635
