### ISSUE TITLE
Notification Configuration Settings

### ISSUE THREAD

**Issue by asyba** [louislam/uptime-kuma#2631]
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

UI Feature

### 🔖 Feature description

I want to have a different notification providers setup with the respective credentials.

Then on each Monitor I can use that already prefilled credentials and setup a custom notification for that monitor url.

Every time that I create a new monitor url I have to over and over and over again the credentials.

I can't  reuse the same one, because each one has a different message to send in that notification.

### ✔️ Solution

Create a configuration page for notification providers setup with the respective credentials and urls.

### ❓ Alternatives

Wasting time of my life, copying and pasting.

**Comment by CommanderStorm** [comment]
@asyba 
We are consolidating duplicate issues a bit to make issue management easier.
I think, we should track this issue in #954 as there is no difference
⇒ I am going to close this as a duplicate.
