### ISSUE TITLE
Ping error: There is no deadline option on windows

### ISSUE THREAD

**Issue by simone80an** [louislam/uptime-kuma#2636]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### Description

Using PING in latest version of uptime-kuma gives the following error: There is no deadline option on windows

### 👟 Reproduction steps

Updated uptime-kuma to latest version 1.19.5 when performing a PING to an host it's marked as DOWN with the following error: There is no deadline option on windows.
I have no error using version 1.19.4.

### 👀 Expected behavior

Have the PING command work.

### 😓 Actual Behavior

error: There is no deadline option on windows

### 🐻 Uptime-Kuma Version

1.19.5

### 💻 Operating System and Arch

Windows Server 2019

### 🌐 Browser

Google Chrome 108.0.5359.125

### 🟩 NodeJS Version

16.14.2

**Comment by louislam** [comment]
Omg, I can't believe that there are so many traps by switching to `node-ping`

**Comment by louislam** [comment]
Should be fixed in 1.19.6. Thanks for the report.

**Comment by simone80an** [comment]
I confirm that with version 1.19.6 it works again. Thanks for the quick fix!
