### ISSUE TITLE
High number of false positives

### ISSUE THREAD

**Issue by Vanderscycle** [louislam/uptime-kuma#2637]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

Hi, 

First of all thank you for your work. My question is as follow: I can't seem to have a retry/delay parameter so that should `uptime-kuma` is unable to ping the service X amount of times, then throw an error. 

For example: sometimes uptime-kuma gets a 503 one minute yet the next minute is valid (200) while no processes went down. 
![image](https://user-images.githubusercontent.com/52706578/213312848-8a114c3d-d30d-4104-b774-0146eae851d3.png)

Main issue is that I am getting plenty of false positives. `Uptime-kuma` is running in kubernetes using the example provided in the repo.

Thank you for any help.

### 🐻 Uptime-Kuma Version

1.19.6

### 💻 Operating System and Arch

Linux 6.1.2

### 🌐 Browser

firefox 108.0.1

**Comment by spali** [comment]
You can configure the monitor to retry a specified amount of time until it marks the monitor as DOWN.
![image](https://user-images.githubusercontent.com/1839708/213670693-1a4b8d90-9176-4a9c-88e2-f57b09b7d256.png)

But I would say a retry would only mask the real problem.
If 503 is returned, then if may be a a problem on the monitored service side. I would think the service has a reason to return 503. Maybe overloaded or anything else.
I would only use the retry feature if you can't control the service on your own and consciously accept some instability of it.

**Comment by louislam** [comment]
Yes, it is a bad signal of your service, you should not ignore it in my opinion.

**Comment by spali** [comment]
Not as I know, except hacking the db file. But I would rather go the manual way to update the existing monitors.

**Comment by Vanderscycle** [comment]
Sounds good, I am closing the help request.
