### ISSUE TITLE
Move uptime-kuma to new folder

### ISSUE THREAD

**Issue by jl-678** [louislam/uptime-kuma#2639]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

I am trying to reorganize all my docker data into a common location to simplify management.  I originally ran uptime-kuma with the following:

sudo docker run -d --restart=always -p 3001:3001 -v uptime-kuma:/app/data --name uptime-kuma louislam/uptime-kuma:1

And as a result, the data lives in /var/lib/docker/volumes/uptime-kuma, and I want to move it to /opt/uptime-kuma.

To accomplish the above, I copied all files in /var/lib/docker/volumes/uptime-kuma to /opt/uptime-kuma and then stop and remove the container and then run the following:

sudo docker run -d --restart=always -p 3001:3001 -v /opt/uptime-kuma:/app/data --name uptime-kuma louislam/uptime-kuma:1

This should work in theory, but Uptime Kuma never recognizes the copied files and upon first run, it asks me to create a user versus bringing the old user over.

What am I doing wrong?

### 🐻 Uptime-Kuma Version

1.19.6

### 💻 Operating System and Arch

Debian Bullseye

### 🌐 Browser

Chrome

### 🐋 Docker Version

20.10.22

**Comment by chakflying** [comment]
Did you open a shell in the container to check if all the files are copied correctly?

**Comment by jl-678** [comment]
So all this happens inside the shell.  I have tried a couple of options including:

1. Moving the original directory over (e.g. mv /var/lib/docker/volumes/uptime-kuma /opt)
2. Copy the files inside /var/lib/.... to /opt/uptime-kuma

I had the same problem in each case. It is perplexing to me as I am not sure why the files are not being recognized.

**Comment by spali** [comment]
Did you check owership and permissions of the folder and files to be the same?

**Comment by jl-678** [comment]
I am highly confused about this as it just does not make sense. It feels like I am doing something wrong, but I cannot for the life of me figure out what.  (FYI, I verified the appropriate updated path in Portainer and so it should be picking up the moved files.)  To answer other questions:

1. Have I checked permissions? Yes, original ownership is root and so is the new directory
2. Stop the container first... -> Correct. I do the following - docker stop, docker rm and then docker run with the new path
3. Copy the data folder --> I go to the original path (/var/lib/docker/volumes/uptime-kuma) and did a cp -RT this AM. Same problem.

I was poking around the sqllite database in the new location moments ago and everything looks fine.  I just cannot figure out why u-k is not using it. To the extent it matters, I have been playing around with the new u-k location to be /opt/uptime. I don't think that the name should matter.

**Comment by rezzorix** [comment]
> 2\. Stop the container first... -> Correct. I do the following - docker stop, docker rm and then docker run with the new path

Not what I wrote.

As per what you have written so far it is understood that you copied the data folder while docker was running.

So again, please verify that you do/did the following steps:

1. Stop the container
2. Copy the data folder (including contents; so make sure you `cp -R -p /folder/old/ /folder/new/`
(-R = recursive, so includes all content in the folder, -p = preserve, and preserves permissions)
4. then restart the container with new path

Maybe it is helpful for you working with docker compose... 
docker-compose.yml files are not just single line in shell, therefore better structured and less confusing.

**Comment by jl-678** [comment]
My apologies for not being clear.  I did what you stated above in each test.  I did it again today with the same result.

You raise a good idea about docker-compse as I am familiar with that approach too and so tried that out this AM. It had exactly the same problem.  In fact, it would not even recognize the existing data even if I put in the full original path in the [docker compose](https://github.com/louislam/uptime-kuma/blob/master/docker/docker-compose.yml) file. (e.g. - /var/lib/docker/volumes/uptime-kuma:/app/data

While I first thought that this might be user error, I am now wondering if there is a problem with how u-k interprets the volume path and whether it is hardcoded in the database or app somewhere.

**Comment by jl-678** [comment]
As an update, I captured the logs from running Uptime-Kuma with the new director setting, and you can find it in [Pastebin here](https://pastebin.com/R3L6xTVq).

One curiosity is line 18, where it says: 

`Data Dir: ./data`

That path is curious because it matches neither the internal path from docker run (/app/data) or the external path (/var/lib/docker/volumes/).

**Comment by louislam** [comment]
I guess you was trapped by the volume directory structure, be careful of `_data` directory.

It should look like this:

![image](https://user-images.githubusercontent.com/1336778/213882676-762c2fe7-575e-45f5-848b-08dd2f4ea6c4.png)

**Comment by jl-678** [comment]
That was 100% it.  Thank you!  I really appreciate your jumping in to help @louislam.
