### ISSUE TITLE
EKS v1.23 compatibility

### ISSUE THREAD

**Issue by divlaks** [louislam/uptime-kuma#2643]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

Hi,

We are going to upgrade our eks version to 1.23. We have deployed 1.19.3 version of uptime-kuma via helm in 1.21v of eks. We would like to know if this version is compatible with 1.23 version of eks.

### 🐻 Uptime-Kuma Version

1.19.3

### 💻 Operating System and Arch

Amazon Linux

### 🌐 Browser

Chrome

### 🐋 Docker Version

k8s 1.21

**Comment by louislam** [comment]
I think you used an unofficial installation method, you should ask them.
