### ISSUE TITLE
Can I verify the response data

### ISSUE THREAD

**Issue by weizhoujie** [louislam/uptime-kuma#2644]
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

Other

### 🔖 Feature description

The response data can be verified, not only the status code

### ✔️ Solution

The response data can be verified

**Comment by Genc** [comment]
This already exists.

![Capture](https://user-images.githubusercontent.com/18603640/213530273-746aa965-354d-4fc3-a8ac-5430f4f05c19.JPG)



Could I not have understood correctly?

**Comment by CommanderStorm** [comment]
closing as resolved by the json-query or keyword monitor
