### ISSUE TITLE
New monitor type - Execute process

### ISSUE THREAD

**Issue by vslinuxdotnet** [louislam/uptime-kuma#2645]
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

Other

### 🔖 Feature description

Execute a process in current host

### ✔️ Solution

 return stdout and stderr and compare the strings to alert or not.
 Also a timeout to execute it.

**Comment by Computroniks** [comment]
The push monitor should satisfy this role

**Comment by vslinuxdotnet** [comment]
> The push monitor should already satisfy this role

The push monitor only accepts urls....
The command must be executed in server machine.

**Comment by Computroniks** [comment]
Yes ,you write a script that runs on the target machine and calls the push url

**Comment by vslinuxdotnet** [comment]
OK, don't that way. The idea is to be transparent to the user, don't run any on target machine.
Example: Get free space disk on other server by SMB. Execute it and returns the data, compare and send notification or not.

**Comment by spali** [comment]
related to #2609, but with some different features (compare output and timeout).

**Comment by vslinuxdotnet** [comment]
> related to #2609, but with some different features (compare output and timeout).

Yes that's it, but the idea of return 0 or 1 is also good.
If add some parameters to send in command line will be great!
Thank You

**Comment by johntdyer** [comment]
this would be amazing add

**Comment by CommanderStorm** [comment]
I am going to close this issue in favour of https://github.com/louislam/uptime-kuma/issues/1117 as from the description they are identical.
