### ISSUE TITLE
If the placeholder is a long string it can't be read entirely

### ISSUE THREAD

**Issue by simone80an** [louislam/uptime-kuma#2646]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### Description

When adding a monitor if have a long string as placeholder (eg. Microsoft SQL Server) it cannot be scrolled until the end.
To read all the placeholder i must zoom out in the browser.

### 👟 Reproduction steps

Add new monitor -> Microsoft SQL Server

### 👀 Expected behavior

Use left and right arrow keys to scroll all the placeholder text.

### 😓 Actual Behavior

Using left/right arrow keys do nothing.

### 🐻 Uptime-Kuma Version

1.19.4

### 💻 Operating System and Arch

Windows Server 2019

### 🌐 Browser

Firefox 109.0

### 🟩 NodeJS Version

16.14.2

**Comment by louislam** [comment]
Yes, I think all database types are having this issue. Change to a description will be better.

**Comment by gitstart** [comment]
Hello @louislam, pushed a workaround to this problem, you can check it out.

**Comment by CommanderStorm** [comment]
Resolved by https://github.com/louislam/uptime-kuma/commit/22f730499f6e83c4eae048763654322bc8a5caf4
