### ISSUE TITLE
Certificate Expiry Notification is sent multiple times

### ISSUE THREAD

**Issue by edwardchenchen** [louislam/uptime-kuma#2648]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### Description

Certificate Expiry Notification is sent multiple times
previously the notification is sent only once on 14 days, and once on 7 days

my setting is check every 30s, so the notifications seems is not sent everytime, but maybe every other time?
![image](https://user-images.githubusercontent.com/6397192/213594604-b37a0084-f512-4fdd-b448-8aa1bc0a1dd7.png)

### 👟 Reproduction steps
my setting is HTTPS keyword monitor, every 30s
...

### 👀 Expected behavior

the notification is sent only once on 14 days, and once on 7 days

### 😓 Actual Behavior

the notification is sent everytime the check is run

### 🐻 Uptime-Kuma Version

1.19.6

### 💻 Operating System and Arch

docker

### 🌐 Browser

Chrome

### 🐋 Docker Version

20.10.22

**Comment by rezzorix** [comment]
What is your setting in the respective monitor here:

“Resend Notification if Down X times consequently”

**Comment by edwardchenchen** [comment]
> What is your setting in the respective monitor here:
> 
> “Resend Notification if Down X times consequently”

0

![image](https://user-images.githubusercontent.com/6397192/213835671-479edc25-5a46-4279-8738-6021ec5495bc.png)

**Comment by edwardchenchen** [comment]
I am closing this issue,
it was something with apache2,
it is serving old certificate and the new certificate the same time after certbot replace the file.
![image](https://user-images.githubusercontent.com/6397192/213837515-3b16f5e6-be63-416f-9929-f569e3be9570.png)
![image](https://user-images.githubusercontent.com/6397192/213837522-bb23cc95-a35c-43f8-87dd-63aadd3a5750.png)
