### ISSUE TITLE
Save button can't be found while edit and add in Mobile version

### ISSUE THREAD

**Issue by Hasan-Uddin** [louislam/uptime-kuma#2655]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### Description

Save button can't be found while edit and add in Mobile version

### 👟 Reproduction steps

Save button can't be found while edit and add in Mobile version

### 👀 Expected behavior

Expected save button while edit and add new monitor

### 😓 Actual Behavior

missing button to save changes and add new monitor

### 🐻 Uptime-Kuma Version

most latest version

### 💻 Operating System and Arch

ubt 18.04 lts

### 🌐 Browser

Google chrome latest android

### 🐋 Docker Version

it’s replit

**Comment by louislam** [comment]
Screenshot?

**Comment by chakflying** [comment]
![image](https://user-images.githubusercontent.com/3271800/213901636-dd1cb746-43e3-4921-b1cb-9b83eae724f0.png)

Looks like the button is stuck in the first column.

**Comment by louislam** [comment]
Bad UI. Maybe I will change it to sticky at the bottom.

**Comment by gitstart** [comment]
@louislam Hello, hope you are doing great, implemented something that fixes the issue you can check it out.
