### ISSUE TITLE
ENOENT error when testing Docker hosts

### ISSUE THREAD

**Issue by tassilomoedl** [louislam/uptime-kuma#2656]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

Whenever I enter the socket of my Docker Host and click on "Test", I get an ENOENT error.

### 🐻 Uptime-Kuma Version

1.19.6

### 💻 Operating System and Arch

Debian 11 x64

### 🌐 Browser

Firefox 109.0

### 🐋 Docker Version

Docker 20.10.22

**Comment by maotou316** [comment]
me too
![image](https://user-images.githubusercontent.com/28297458/214082779-ed17dcbe-1e4c-4a4a-9867-ae12896d8862.png)

**Comment by spali** [comment]
Did you mount/bind the socket `/var/run/docker.sock` into the uptime-kuma container itself?

**Comment by tassilomoedl** [comment]
Oh, I forgot this. Now it works!
