### ISSUE TITLE
Email -  Format 

### ISSUE THREAD

**Issue by GalacticAust** [louislam/uptime-kuma#2661]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

Hi All 

have seen updates on this in other posts but it has not solved my issue 

I want to format the body of the email

can anyone advise how to edit the body template

### 🐻 Uptime-Kuma Version

1.19.6

### 💻 Operating System and Arch

Ubuntu 

### 🌐 Browser

Firefox

**Comment by rezzorix** [comment]
You look at the following file:

`/app/src/components/notifications/SMTP.vue`

Adjust between lines 93 - 101 as required.

Note; depending on how and where you make changes, they wont be persistent and will be lost if e.g. you update or re-create the container.

**Comment by GalacticAust** [comment]
Hi there 

Just looking at line 93-103 isnt this just for the subject line?

 <div class="mb-3">
            <label for="subject-email" class="form-label">{{ $t("emailCustomSubject") }}</label>
            <input id="subject-email" v-model="$parent.notification.customSubject" type="text" class="form-control" autocomplete="false" placeholder="">
            <div v-pre class="form-text">
                (leave blank for default one)<br />
                {{NAME}}: Service Name<br />
                {{HOSTNAME_OR_URL}}: Hostname or URL<br />
                {{URL}}: URL<br />
                {{STATUS}}: Status<br />
            </div>
        </div>
    </div>

**Comment by GalacticAust** [comment]
<div class="mb-3">
            <label for="subject-email" class="form-label">{{ $t("emailCustomSubject") }}</label>
            <input id="subject-email" v-model="$parent.notification.customSubject" type="text" class="form-control" autocomplete="false" placeholder="">
            <div v-pre class="form-text">
                (leave blank for default one)<br />
                {{NAME}}: Service Name<br />
                {{HOSTNAME_OR_URL}}: Hostname or URL<br />
                {{URL}}: URL<br />
                {{STATUS}}: Status<br />
            </div>
        </div>
    </div>
</template>

**Comment by GalacticAust** [comment]
any update on how we edit the body? as it all seems to be subject line only

**Comment by CommanderStorm** [comment]
Related #1529
