### ISSUE TITLE
Edit monitor page doesn`t redirect after clicking save button

### ISSUE THREAD

**Issue by WajihaNiazi** [louislam/uptime-kuma#2665]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### Description

When I edited the monitor I considered that after clicking the save button not able to redirect to the monitor page.

### 👟 Reproduction steps

1. Go to the dashboard page and click the monitor form the monitor list.
![image](https://user-images.githubusercontent.com/42426067/214305821-1280e9bf-f4a5-4741-a00b-8ccc754f2d2b.png)

2. And click the edit button
![image](https://user-images.githubusercontent.com/42426067/214306557-dc11a3eb-249a-4dc6-bca0-eb38a64ad29c.png)

3. And click the save button.
![image](https://user-images.githubusercontent.com/42426067/214306761-de9e50b9-23f2-4e48-af91-a0ce86b98a51.png)

### 👀 Expected behavior

Expected to redirect to the monitor page after clicking the save button on the edit page.

### 😓 Actual Behavior

The edit monitor page doesn`t redirect after clicking the save button.

### 🐻 Uptime-Kuma Version

most latest version

### 💻 Operating System and Arch

Ubuntu 22.04.1 LTS

### 🌐 Browser

Google chrome latest

### 🟩 NodeJS Version

16.10.0

**Comment by louislam** [comment]
Yes, it is.
