### ISSUE TITLE
Creation of Multiple login and link individual host to it.

### ISSUE THREAD

**Issue by Gururaj08** [louislam/uptime-kuma#2669]
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

UI Feature

### 🔖 Feature description

Can we get to create multiple login access.
Admin account can map individual host to users. 

### ✔️ Solution

Can we get to create multiple login access.
Admin account can map individual host to users

**Comment by CommanderStorm** [comment]
@Gururaj08 
We are consolidating duplicate issues a bit to make issue management easier.
I think, we should track this issue in #128 as there is no difference
⇒ I am going to close this as a duplicate.
