### ISSUE TITLE
Can delay alarm monitoring be added

### ISSUE THREAD

**Issue by suk1da** [louislam/uptime-kuma#2671]
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

New Notification

### 🔖 Feature description

If the normal delay is 30ms ，when become 3s，it can send alarm

### ✔️ Solution

If the normal delay is 30ms ，when become 3s，it can send alarm

**Comment by koen20** [comment]
Duplicate of https://github.com/louislam/uptime-kuma/issues/459
