### ISSUE TITLE
Status Badge shows wrong message text when label is set

### ISSUE THREAD

**Issue by shukon** [louislam/uptime-kuma#2673]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### Description

When setting a custom label for a *status*-badge, such as `https://status.example.org/api/badge/47/status?label=foobar` and the status is DOWN, this results in:
![grafik](https://user-images.githubusercontent.com/9417378/214554853-db6007a9-3ee8-4899-9f7f-fcbd3d2c65ad.png)
This even overrides the `&downLabel=example` property, so `https://status.example.org/api/badge/47/status?label=foobar&downLabel=Down` is not a workaround. The `&upLabel=example` works just fine though.

This only affects *status*-badges, not duration-badges.

The reason for this is [this line](https://github.com/louislam/uptime-kuma/blob/8816be24d86c04886cb05fa877c64971f1c3acb8/server/routers/api-router.js#L146) - my suggestion would be to instead use `badgeValues.message = state ? upLabel : downLabel;`.

<details>
  <summary>Explanation</summary>
The "?? state ? upLabel : downLabel" part of the line is called the "null coalescing operator" and the ternary operator.

The null coalescing operator (??) checks if the variable "label" is null or undefined, and if so, it assigns the value of "state" to "label".

Then, the ternary operator (?:) checks if the value of "label" is truthy or falsy, and assigns the value of "upLabel" if truthy, and "downLabel" if falsy.

So, if "label" is truthy, "message" will be set to "upLabel" and if "label" is falsy, "message" will be set to "downLabel". 

This results in status being always overwritten as "truthy" or "up" when a label is set. This does not hold for the color, which is correctly assigned only based on status (`badgeValues.color = state ? upColor : downColor;`).
</details>

Happy to do a PR if it's welcome.

### 👟 Reproduction steps

Check the `https://status.example.org/api/badge/47/status?label=foobar` on your favorite Uptime-Kuma instance. Remember that you need to add the monitor (in this case e.g. 47) to a [public status page](https://github.com/louislam/uptime-kuma/pull/1119#issuecomment-1114355650) in order for badges to work.

### 👀 Expected behavior

Passing the label in the URL should only modify the label on the left-side, not the message. I'd expect this:
`https://status.example.org/api/badge/47/status?label=foobar`
->
![grafik](https://user-images.githubusercontent.com/9417378/214557528-12ff38db-f5a5-4e99-9124-eb90f152e327.png)

### 😓 Actual Behavior

Passing the label in the URL modifies the label on the left-side and also sets the message, ignoring the status:
`https://status.example.org/api/badge/47/status?label=foobar`
->
![grafik](https://user-images.githubusercontent.com/9417378/214554853-db6007a9-3ee8-4899-9f7f-fcbd3d2c65ad.png)

### 🐻 Uptime-Kuma Version

1.19.6

### 💻 Operating System and Arch

Debian 11 x64

### 🌐 Browser

Firefox 109.0

**Comment by chakflying** [comment]
Fixed as part of #2525.
