### ISSUE TITLE
Don't give the webuser secrets.

### ISSUE THREAD

**Issue by jtagcat** [louislam/uptime-kuma#268]
**Describe the bug**
Came back to edit the Telegram notification:

![image](https://user-images.githubusercontent.com/38327267/130880022-1650df1b-d203-4f0e-a9a2-af295bcfa6b9.png)

The bot token should _not_ be shown or even sent to the web client. Accessing (failure could be user-side as well, 'disable auth' for example) uptime-kama gives full control to the Telegram bot.

**Expected behavior**
Editing notifications doesn't show the secret. Instead, use type=password, and `****************` as the content. If on submit, the token/secret is different from `****************`, use that as the new value.

**Info**
- Uptime Kuma Version: 1.3.2
- Using Docker?: Yes

**Comment by Saibamen** [comment]
PR was merged: https://github.com/louislam/uptime-kuma/pull/344

**Comment by jtagcat** [comment]
This is different #344 (hiding visibly). The point here is to make it inaccessible to the webuser at all. There is no 'unhide/show' button. It might be a multi-user installation, do you really need to give 10 people various (sometimes privileged) bot tokens?

**Comment by louislam** [comment]
> This is different #344 (hiding visibly). The point here is to make it inaccessible to the webuser at all. There is no 'unhide/show' button. It might be a multi-user installation, do you really need to give 10 people various (sometimes privileged) bot tokens?

No multi users currently, you should not share your account info.
