### ISSUE TITLE
Badge value : number of decimals

### ISSUE THREAD

**Issue by melvinlemoine** [louislam/uptime-kuma#2687]
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

API

### 🔖 Feature description

Limit the number of decimals for badges value, because actually it's too much.
![illustration](https://i.imgur.com/teWRjTA.png)

### ✔️ Solution

Limit the number of decimals for badges value.
![illustration](https://i.imgur.com/teWRjTA.png)

**Comment by lionep** [comment]
Reproduced here with value 99.929999999999.
