### ISSUE TITLE
Ping loss on DHCP renew, Unifi AP, different devices

### ISSUE THREAD

**Issue by thehijacker** [louislam/uptime-kuma#2688]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

Ever since I have setup Uptime Kuma and enabled Telegram notifications I get "false" positives that devices are offline (ping check) and after a minute that they came back. Devices worked fine during this alert. Today I checked my Mikrotik logs and saw that at that exact same time DHCP lease expired and devices renewed it.

For example my Google Nest Hub today at 4:37:

![image](https://user-images.githubusercontent.com/13857043/215100509-e0285a43-bb36-477f-9f10-783a5091aa8f.png)

In telegram I got:

![image](https://user-images.githubusercontent.com/13857043/215100607-2bc9ee19-8da4-4015-a909-17cd7eec2735.png)

![image](https://user-images.githubusercontent.com/13857043/215101309-22da1497-8716-4063-ab9c-fce3779d0efe.png)

Every single show device downtime was recorded if ping check was done during DHCP renew. I am using Ubiquiti LR AP all connected to my Mikrotik router.

Any idea what could be wrong? Why is ping failing at the time of DHCP renew?

### 🐻 Uptime-Kuma Version

1.19.0-beta.2

### 💻 Operating System and Arch

Proxmox LXC container with Ubuntu 20.10 OS and Docker inside

### 🌐 Browser

Does not matter as it is monitoring question

### 🐋 Docker Version

20.10.23

**Comment by louislam** [comment]
I am not a networking expert. But according to my experience, I have never seen such DHCP connection reset issue in my life. I also checked my home ISP's DHCP lease time is very short (30mins), I have never felt anything get disconnected. Previously, I even set a 24x7 game server at home and let my friend joining, also got no problem.

So my conclusion is that normally, DHCP renewal will not reset connections.

My guessing:
- Maybe your Google Nest Hub forget to renew before expired.
- Maybe Mikrotik's DHCP implementation is not perfect.

But anything, you can set `Retries` to 1 or 2 in your monitor to avoid it.

![image](https://user-images.githubusercontent.com/1336778/215107299-75a23a04-4b0b-409c-a16c-9f7bb26530aa.png)
