### ISSUE TITLE
question on weblate

### ISSUE THREAD

**Issue by cyril59310** [louislam/uptime-kuma#2690]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

hello, in your last commit the "Custom Monitor Type" is missing in the en.json translation file, I would like to know if it is necessary to make a committee to add the key or if there was a way to add it via weblate

### 🐻 Uptime-Kuma Version

1.19.6

### 💻 Operating System and Arch

debian

### 🌐 Browser

Chrome

**Comment by louislam** [comment]
Thanks, I just added this key in Weblet, I think only admin can add new keys. Or you can make a pull request here, in case I forgot to make them in en.json.

**Comment by cyril59310** [comment]
OK thank you for your answer

**Comment by louislam** [comment]
I guess the French one is by yours? #2676

As it didn't show your profile in the comment. If you want to show your contribution on GitHub, maybe you have to match the email address, I guess.

![image](https://user-images.githubusercontent.com/1336778/215123483-c3d858a4-1332-4df2-8396-0e74e7105397.png)

**Comment by cyril59310** [comment]
surely yes, I will put the right address for the comit. thank you
