### ISSUE TITLE
collecting monitors into groups

### ISSUE THREAD

**Issue by qristo76** [louislam/uptime-kuma#2692]
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

UI Feature

### 🔖 Feature description

It would be nice to have a function to combine monitors into groups. I know there are tags, but it's a slightly different function.

### ✔️ Solution

Creating groups to which monitors would be added. After clicking +, a list of monitors in a given group would expand.

**Comment by a1git** [comment]
+1 for this request.. For operators who have thousands of objects to monitor, it will be a very nice feature to have. 
Also if possible, ability to move existing objects into groups when this feature is added

**Comment by julian-piehl** [comment]
> +1 for this request.. For operators who have thousands of objects to monitor, it will be a very nice feature to have. 
> Also if possible, ability to move existing objects into groups when this feature is added 

Take a look at my pr. I think exactly what you both want ;)

https://github.com/louislam/uptime-kuma/pull/2693

**Comment by CommanderStorm** [comment]
@qristo76  a very similar feature has been implemented+merged.
Any version after [`1.22.0-beta.0`](https://github.com/louislam/uptime-kuma/releases/tag/1.22.0-beta.0) supports this.
![image](https://github.com/louislam/uptime-kuma/assets/26258709/2b8673a3-214f-449f-a7fd-675c6dacc8db)
![image](https://github.com/louislam/uptime-kuma/assets/26258709/2a188e08-0774-402e-92e7-c18da04c0026)

Could you close this Issue, if this has been resolved? (ony you or Louis can close issues)

**Comment by ErebusBat** [comment]
How do you create a group?  I only have this option, but it isn't clear exactly how to create a new group.

![image](https://github.com/louislam/uptime-kuma/assets/93973/6823f0af-0ea9-462b-b2fc-4339c910bca7)

**Comment by julian-piehl** [comment]
> How do you create a group?  I only have this option, but it isn't clear exactly how to create a new group.
> 
> ![image](https://github.com/louislam/uptime-kuma/assets/93973/6823f0af-0ea9-462b-b2fc-4339c910bca7)
> 

Just create a new monitor and select "Group" in the type drop-down ;)

**Comment by mirivlad** [comment]
> > How do you create a group?  I only have this option, but it isn't clear exactly how to create a new group.
> > ![image](https://user-images.githubusercontent.com/93973/251300551-6823f0af-0ea9-462b-b2fc-4339c910bca7.png)
> 
> Just select "Group" in the type drop-down when creating a new monitor ;)

Dropdown menu not avaliable when creating new monitor
![изображение](https://github.com/louislam/uptime-kuma/assets/742619/8115690f-330f-41dc-84e7-2314bd4a7105)

**Comment by mirivlad** [comment]
Oh, i see. Thanks!
![изображение](https://github.com/louislam/uptime-kuma/assets/742619/2b4361c3-1e07-4a13-8d3e-57497910ebca)

**Comment by ErebusBat** [comment]
I don't know how I missed this, thank you.

For completeness:
![image](https://github.com/louislam/uptime-kuma/assets/93973/2450928d-111f-40e8-8ce2-9a59531108d2)
