### ISSUE TITLE
Docker Installation Error -Windows 2019

### ISSUE THREAD

**Issue by benoymichael100** [louislam/uptime-kuma#2696]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

I tried to install uptime-Kuma with following docker command 

docker volume create uptime-kuma2
docker run  --platform linux/amd64  -d --restart=always -p 6001:3001 -v uptime-kuma2:/app/data --name uptime-kuma louislam/uptime-kuma:1

We are getting following error from the log 

[Error: SELECT `value` FROM setting WHERE `key` = 'database_version'  limit 1 - SQLITE_IOERR: disk I/O error] {
  errno: 10,
  code: 'SQLITE_IOERR'
}

Any support to resolve this issue will be appreciated 

### 🐻 Uptime-Kuma Version

latest

### 💻 Operating System and Arch

Windows server  2019

### 🌐 Browser

Google Chrome

### 🐋 Docker Version

20.10.9

**Comment by louislam** [comment]
What is your disk type? NTFS?

**Comment by benoymichael100** [comment]
Thank you for the response @louislam 
it  is NTFS

**Comment by louislam** [comment]
Not quite sure the issue.

Try to start without a volume:
> docker run --rm -it --pull=always -p 3001:3001 louislam/uptime-kuma:1

**Comment by benoymichael100** [comment]
Same error 
![image](https://user-images.githubusercontent.com/123850265/215348812-d87120ed-e94c-4f04-9f42-4561a9248d41.png)

**Comment by guiheb** [comment]
same issue here, any update on this?

Thanks for your help.

**Comment by chakflying** [comment]
IIRC Windows server doesn't support WSL2, so all Linux containers must be run under the old LCOW kernel or the Hyper-V backend in Docker Desktop. How are you guys running this?

**Comment by brasil1983** [comment]
hi, i have same issue. Running docker on Server 2022 + wsl2. All other linux containers are running fine.

PS C:\WINDOWS\system32> docker info
Client:
 Debug Mode: false
 Plugins:
  cluster: Manage Docker clusters (Docker Inc., v1.2.0)

Server:
 Containers: 9
  Running: 4
  Paused: 0
  Stopped: 5
 Images: 11
 Server Version: 19.03.5
 Storage Driver: windowsfilter (windows) lcow (linux)
  Windows:
  LCOW:
 Logging Driver: json-file
 Plugins:
  Volume: local
  Network: ics internal l2bridge l2tunnel nat null overlay private transparent
  Log: awslogs etwlogs fluentd gcplogs gelf json-file local logentries splunk syslog
 Swarm: inactive
 Default Isolation: process
 Kernel Version: 10.0 20348 (20348.1.amd64fre.fe_release.210507-1500)
 Operating System: Windows Server 2022 Standard Version 2009 (OS Build 20348.1547)
 OSType: windows
 Architecture: x86_64
 CPUs: 8
 Total Memory: 16GiB
 Name: Server01
 ID: WBJU:IZGS:HCFM:PTTS:JMM6:CBYG:ZEVJ:DGAN:UL5B:VLIC:O74I:76HX
 Docker Root Dir: C:\ProgramData\docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: true
 I
