### ISSUE TITLE
Tambahkan Bot Minecraft.

### ISSUE THREAD

**Issue by Bintangp02** [louislam/uptime-kuma#2697]
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

New Monitor

### 🔖 Feature description

This feature is assigned to bedrock mcpe servers and also added to pc user servers or Minecraft windows servers.

with a crack option to join the server and with a non-crack option for original and fake Minecraft not original

### ✔️ Solution

if I want to use the server for free so that it stays on with the bot feature that enters our server automatically, whether it's an Android server or on a computer / PC

### ❓ Alternatives

saya belum mencoba alternatif lain yang mungkin sangat jarang bahkan tidak ada

### 📝 Additional Context

![Screenshot_20230129_130631](https://user-images.githubusercontent.com/80300921/215308347-acce9d82-90fd-4762-a376-5dbbc977fca9.jpg)

**Comment by 401U** [comment]
So what you mean a bot program that would join mc server with set interval? That's a bit of out of scope. UptimeKuma is designed as monitor your service status, not as bot program.

**Comment by CommanderStorm** [comment]
> [!TIP]
> `minecraft` can be monitored for uptime via [gamedig](https://github.com/gamedig/node-gamedig/blob/HEAD/GAMES_LIST.md)

> if I want to use the server for free so that it stays on with the bot feature that enters our server automatically, whether it's an Android server or on a computer / PC

I don't get how this is a monitor.
You want to join a server periodically to monitor what?
what is a "Tambahkan Bot"?

I think given that gamedig can monitor minecraft servers, this issue can be safely closed as resolved
