### ISSUE TITLE
[Suggestion] Use something like Apprise for notifications

### ISSUE THREAD

**Issue by FuzzyMistborn** [louislam/uptime-kuma#27]
Instead of adding all the functionality of notifications, why not bake something in like Apprise (https://github.com/caronc/apprise) so it's already done for you?  Not sure if that's possible but might save a bunch of trouble.

**Comment by louislam** [comment]
I am implementing apprise integration. I added apprise to the docker. But apprise is not working even via cli.
Am I do anything wrong?

```
FROM louislam/uptime-kuma:nightly
RUN apprise -vv -t 'my title' -b 'my notification body' 'tgram://{my bot token}/{chat_id}'
```

Result:
```
ERROR: Unparseable URL
```

**Comment by martadinata666** [comment]
Did you read the detailed description in here https://github.com/caronc/apprise/wiki/Notify_telegram ?

**Comment by louislam** [comment]
added apprise in 1.0.6
