### ISSUE TITLE
Define services form file.

### ISSUE THREAD

**Issue by jtagcat** [louislam/uptime-kuma#270]
Allow to define monitoring from a file, likely yaml. Ideally, multiple files.  
This makes it compatible with CI / infra from file.

Files could be represented as (read-only, no-login) users (#128).

As a 3rd party, it could be implemented via the API (#118) by requesting current state, and adding/modifying/removing services, reaching the defined state.

### GitHub Etiquette

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

**Comment by nicolas-g** [comment]
👍 
supporting everything through configuration files instead of point and click on the UI is crucial in order to have automation and is also Git-friendly so you can have it in version control.

**Comment by gaby** [comment]
I would love this feature, we currently have over 300 services to monitor :-)

**Comment by jtagcat** [comment]
gonna wholesomely place it here~ :)

### GitHub Etiquette

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

**Comment by louislam** [comment]
Although it got a lot of thumbs up, it againsts my project styles. 

https://github.com/louislam/uptime-kuma/blob/master/CONTRIBUTING.md#project-styles

If you love to config via yaml, I would suggest Gatus https://github.com/TwiN/gatus

**Comment by Xplouder** [comment]
@louislam Please reconsider this feature request, as said earlier this is not a replacement but another way to configure the monitors, alerts, etc. This would allow a declarative way to automate what already exists, so its a complement.

**Comment by nicolas-g** [comment]
So disappointed to see this issue closed.. this is a great product but not being able to automate or have the config in version control will be impossible to scale so this is a no go for me now.

**Comment by pauldevlin-smarsh** [comment]
Uptime-kuma is amazing, it's a shame it doesn't have the ability to pre-configure the endpoints on start-up. I'm awful with Javascript but it looks as though it could be achieved by updating the server.js after login to simply check for a backup json file (maybe in the data/uploads folder) then use the functionality already provided by Importing a Backup in the Settings.

It would probably look like this - 
- After login is successful possibly at the end of this call  socket.on("login", async (data, callback)
- Then check for backup.json in ../data/upload
- If exists run socket.on("uploadBackup", async (uploadedJSON, importHandle, callback)

Again, I'm terrible at JS so do point out if I'm being ridiculous.

**Comment by pauldevlin-smarsh** [comment]
Just an update on this. You could get around this (sort of) by spinning up a container locally, adding all healthchecks. Once happy with all healthchecks you can then run a `docker cp uptime-kuma:/app/data ./`. You now have the data folder with your setup. 

The next part is a bit fun (and could probably be done a better way) When you are spinning up a new instance/container of uptime-kuma you can run a `docker cp data uptime-kuma:/app` after you have brought it up. This will overwrite the data file with what you have already configured. restart the service and visit the /login page. Login with the credentials you had set before backup and you should see all your services ready as they were.

**Comment by LCerebo** [comment]
It's a pity that this feature was abandoned. As @Xplouder said it will be a second way to define checks, this will enable the definition of checks as "configuration as code". 
As a second bonus it could be very easy to backup and restore the configuration (not the history) using the same format (for example a yaml descriptor).
Personally I use ansible to deploy every service both at work and at home, and configuration as code is almost everywhere supported and welcome.
Reading your project styles guidelines I don't find this request contradicting any of them.
Hope that @louislam can reconsider to include the feature in a future release!

**Comment by CommanderStorm** [comment]
> I would like to be able to configure monitors from code

Currently, we don't support an API, but you can look into the community-maintained https://uptime-kuma-api.readthedocs.io/en/latest/
See #118 for further details

**Comment by tylerlittlefield** [comment]
Such a shame

**Comment by dorkamotorka** [comment]
+1

**Comment by vanhoutenbos** [comment]
> Such a shame. Has anyone made a fork that allows configuration files?

Since IAC was a hard-requirement from my client I moved to https://github.com/TwiN/gatus/
I love the kuma UI and its so easy on the eyes, but IAC was a must-have and UI was a nice to have

**Comment by terminator891** [comment]
Its just a shame that this feature was never impleneted I'm forced to move to other solution despite loving uptime-kuma gui

**Comment by Yatharth0045** [comment]
Can we reconsider this. As @Xplouder  said, this is just an alternative and will not be the only approach to add monitors/status pages. Would love to have this feature in place. @louislam

**Comment by CommanderStorm** [comment]
> Can we reconsider this

Has something fundamentally changed?
I think this feature is kind of resonable, but would need a larger review slot, tests and someone who is willing to maintain this.
At the minimum, this would need a refactoring of the monitoring type interface and help moving all monitors to this new interface.

Currently, I don't see this slot even if implmemented.
I don't have the capacity to maintain this.
-> I won't reconsider when already so heavily under water. (this month there were [152 Active pull requests
144 Active issues
](https://github.com/louislam/uptime-kuma/pulse). And this includes the christmas/december low).

See these issues, if you want to help:
- https://github.com/louislam/uptime-kuma/issues/6260
- https://github.com/louislam/uptime-kuma/issues/6673

As said, there is a number of projects already focused on IAC, so if you need this I think choosing them is a better fit.

**Comment by merura** [comment]
> Its just a shame that this feature was never impleneted I'm forced to move to other solution despite loving uptime-kuma gui

@terminator891, which other solution are you using?

**Comment by Yatharth0045** [comment]
@merura , you can try out [Gatus](https://github.com/TwiN/gatus)
