### ISSUE TITLE
Host timestamp log's export feature..

### ISSUE THREAD

**Issue by Gururaj08** [louislam/uptime-kuma#2703]
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

UI Feature

### 🔖 Feature description

Host up/Dowd logs need to export with a timestamp of weekly / Monthly. 

### ✔️ Solution

Host up/Dowd logs need to export with a timestamp of weekly / Monthly. 

### ❓ Alternatives

Host up/Dowd logs need to export with a timestamp of weekly / Monthly. 

### 📝 Additional Context

Host up/Dowd logs need to export with a timestamp of weekly / Monthly.

**Comment by CommanderStorm** [comment]
@Gururaj08 I think this can be better tracked in https://github.com/louislam/uptime-kuma/issues/2733

If you agree, could you please close this Issue, as duplicates only create immortal zombies and are really hard to issue-manage?
If not, what makes this issue unique enough to require an additional issue? (Could this be integrated into the issue linked above?) ^^
