### ISSUE TITLE
Can't register on Webplate

### ISSUE THREAD

**Issue by DimitriDR** [louislam/uptime-kuma#2704]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

I have an error message saying registrations are disabled.

Could you enable them? Thanks :)

### 🐻 Uptime-Kuma Version

N/A

### 💻 Operating System and Arch

N/A

### 🌐 Browser

N/A

### 🐋 Docker Version

N/A

### 🟩 NodeJS Version

N/A

**Comment by louislam** [comment]
Ops, that is weird, let me see why.

**Comment by louislam** [comment]
@YehowahLiu Any ideas?

I should have not touched anything these days.

This env var is always 1
> WEBLATE_REGISTRATION_OPEN=1

Restarted container still is not working.

**Comment by YehowahLiu** [comment]
Have no idea, but it seems like you have fixed it

**Comment by louislam** [comment]
I don't how to fix it, but it is working now after several restarts and reordering env vars, lol.

**Comment by louislam** [comment]
https://status.kuma.pet/

![image](https://user-images.githubusercontent.com/1336778/215736917-0475d34a-968b-48bb-9afe-b7cc6e79bdb4.png)

Also, added a keyword monitor for this, if the registration is closed again, I will know it immediately.

**Comment by louislam** [comment]
> @louislam It works, thanks.
> 
> Is it possible to promote me proofreader? Thanks :~)

I think all registered user could do that?

**Comment by DimitriDR** [comment]
Indeed, and if one day you want to migrate to Crowdin, they have free plans for OSS =)
