### ISSUE TITLE
running uptimekuma on synologynas

### ISSUE THREAD

**Issue by regchanuk** [louislam/uptime-kuma#2707]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

Cannot connect to the socket server. [Error: websocket error] Reconnecting...
Using a Reverse Proxy? [Check how to config it for WebSocket](https://github.com/louislam/uptime-kuma/wiki/Reverse-Proxy)

its a fresh install and cant seem to get it working 
ive tried to follow the instructions as bests as i can it allows me to add  the service to the web station but still goves me this error and adding the reverse proxy still does not work for synologynas  too any help would be greatful thank you 

### 🐻 Uptime-Kuma Version

latest from docker 

### 💻 Operating System and Arch

windows 11

### 🌐 Browser

chrome

### 🐋 Docker Version

synologynas 

### 🟩 NodeJS Version

synologynas

**Comment by rezzorix** [comment]
What NAS and what DSM version are you using?

**Comment by regchanuk** [comment]
ds1821+ identical to the ds1819+ running dsm DSM 7.1.1-42962 Update 1 current version

**Comment by rezzorix** [comment]
Ok, I suggest what I suggested in other topics here regarding Synology, too.

You got a great machine, my recommendation is to run a VM (Debian or Ubuntu) and start uptime-kuma and other dockers in there.
You will have less headache, and for Debian/Ubuntu also a lot of support.

The docker implementation in DSM is just to buggy / complicated in my experience.
You can get things up and running but it is just a pita (_pain in the a**_).

If you decide to try things in DSM only, this guy here has mastered it; but unfortunately not for uptime-kuma. https://mariushosting.com/docker/

**Comment by IIIdefconIII** [comment]
nothing wrong, alls exacpt for the widget in homepage is working here:
![image](https://user-images.githubusercontent.com/9917659/216454988-3ae4035d-baea-45a1-8227-04f7513d9a65.png)

**Comment by mariushosting** [comment]
No issue on Synology, Everything works as expected.

**Comment by rezzorix** [comment]
Ha! The legend himself showed up - keep up the great work / tutorials you do @mariushosting 👍

**Comment by regchanuk** [comment]
thank you all sorted it just would not start weird

**Comment by regchanuk** [comment]
> No issue on Synology, Everything works as expected. https://mariushosting.com/how-to-install-uptime-kuma-on-your-synology-nas/

thank you again
