### ISSUE TITLE
Install self signed SSL certificate Node.Js 

### ISSUE THREAD

**Issue by benoymichael100** [louislam/uptime-kuma#2708]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

On Node.Js port 3001, I have uptime-Kuma running.
How can I set up a certificate that is self-signed?

### 🐻 Uptime-Kuma Version

latest

### 💻 Operating System and Arch

Windows server  2019

### 🌐 Browser

Google Chrome

**Comment by louislam** [comment]
Use a reverse proxy or set using arguments.

https://github.com/louislam/uptime-kuma/wiki/Environment-Variables

```
node server/server.js --ssl-key=   --ssl-cert=
```

**Comment by benoymichael100** [comment]
Thank you for the response 
It is picking the certificate with arguments  But not using the environment variables . 

Created a  .env file in the root folder with following 
UPTIME_KUMA_SSL_KEY=./data/certs/key.pem
UPTIME_KUMA_SSL_CERT=./data/certs/cert.pem
But not picking up the cert . Any thoughts?

**Comment by louislam** [comment]
> Thank you for the response It is picking the certificate with arguments But not using the environment variables .
> 
> Created a .env file in the root folder with following UPTIME_KUMA_SSL_KEY=./data/certs/key.pem UPTIME_KUMA_SSL_CERT=./data/certs/cert.pem But not picking up the cert . Any thoughts?

The .env file is not supported yet in 1.19.6. You need to use arguments in Windows or if you are using pm2, you can set environment variables via pm2.
