### ISSUE TITLE
Change name of Website name

### ISSUE THREAD

**Issue by eroxunn** [louislam/uptime-kuma#2711]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

hello,

I'm wondering how to build a docker image, renamed from Uptime Kuma to, for example, Monitoring

![obraz](https://user-images.githubusercontent.com/24457722/216191294-3e841da9-7a94-4c63-b522-169b1d25529b.png)

can u help? i see the index.html have that 

### 🐻 Uptime-Kuma Version

1.19.6

### 💻 Operating System and Arch

Debian Docker

### 🌐 Browser

Firefox

### 🐋 Docker Version

Docker version 20.10.21

**Comment by julian-piehl** [comment]
Currently, there doesn't exist a setting to change this name.
If you want to change it directly in source code, you can do this here:
https://github.com/louislam/uptime-kuma/blob/master/src/layouts/Layout.vue#L16

But maybe it would be a good idea to add the functionality to change the name using the settings page or an env.

**Comment by matthiasbaldi** [comment]
I think just after the following line
https://github.com/louislam/uptime-kuma/blob/master/docker/dockerfile#LL30C22-L30C22
and then something like
````
RUN sed -i 's/Uptime Kuma/Monitoring/g' /app/src/layouts/Layout.vue
```

the path for the Layout file is a guess... check that out.
