### ISSUE TITLE
Change Tag Colour

### ISSUE THREAD

**Issue by jonnymccullagh** [louislam/uptime-kuma#2717]
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

UI Feature

### 🔖 Feature description

I could not find anywhere in the UI to change the color of a tag.

### ✔️ Solution

Tags should be editable from the Settings screen with the ability to rename them or change the tag colour.

**Comment by chakflying** [comment]
Did you try version [1.20.0-beta.0](https://github.com/louislam/uptime-kuma/releases/tag/1.20.0-beta.0)?
