### ISSUE TITLE
Where to buy you a coffee @LouisLam?

### ISSUE THREAD

**Issue by rezzorix** [louislam/uptime-kuma#272]
Well thread subject tells it all.
I am here since the very start, very pleased how the project develops, and Louis: you are doing a great job 😃 

Any way to buy you a coffee online - just as a way to show appreciation?

**Comment by louislam** [comment]
> Well thread subject tells it all.
> I am here since the very start, very pleased how the project develops, and Louis: you are doing a great job 😃
> 
> Any way to buy you a coffee online - just as a way to show appreciation?

Added Sponsor Button, thank you for your support!

**Comment by rezzorix** [comment]
Hehe great! Glad to see you didnt use "onlyfans" 🤣 👍🏻
