### ISSUE TITLE
Pause check/notification for a period of time

### ISSUE THREAD

**Issue by andreapx** [louislam/uptime-kuma#2721]
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

UI Feature, Other

### 🔖 Feature description

It would be nice to have the possibility to pause a check/notification of a device for a custom amount of time.
This would be useful when here is a problem on a device and you don't want to forget to enable the check when the device is back online.

### ✔️ Solution

There should be a new "pause for" button and in the popup the user can insert for how many minutes/hours/days the check/notification should be paused.

**Comment by Schwoby** [comment]
I have successfully created a custom maintenance window using the Single Maintenance Window option. select the date you want it to start, select a date you want it to end (could be the same date), then click the clock icon and pick your start and end times (relative to the start/end dates).
![image](https://user-images.githubusercontent.com/65581397/224639013-40f31ab1-da12-41ee-9e33-42b3ac4911e2.png)
![image](https://user-images.githubusercontent.com/65581397/224639408-5bb7d7df-384f-43eb-8118-dc7db2e9a16d.png)

**Comment by andreapx** [comment]
Oh, dammit! I was looking for the maintenance option in the single monitor, I haven0t noticed the _maintenance_ voice in the top right menu.
Thanks!
