### ISSUE TITLE
Multiple Incidents

### ISSUE THREAD

**Issue by wnconnor** [louislam/uptime-kuma#2726]
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

UI Feature

### 🔖 Feature description

The ability to create multiple incidents for a status page. This would be good to have an Info incident and an incident if we needed to put an alert or warning up.

### ✔️ Solution

When you create an incident it currently removes the previous incident which was set. It would be great to have the ability to create another incident and unpin the ones we don't want.

### ❓ Alternatives

An alternative could be to save previous incidents and have the ability to insert them after they've been unpinned. 

### 📝 Additional Context

N/A

**Comment by chakflying** [comment]
Tracked in #1253

**Comment by CommanderStorm** [comment]
@wnconnor 
We are consolidating duplicate issues a bit to make issue management easier.
I think, we should track this issue in #862 as there is no functional difference (maybe just small naming differences, but nothing that would require a different issue imo)
⇒ I am going to close this as a duplicate.
