### ISSUE TITLE
Discord Webhook Display Empty Service URL (MYSQL/MariaDB Check)

### ISSUE THREAD

**Issue by BlackYuzia** [louislam/uptime-kuma#2727]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 👟 Reproduction steps

1. Create service (MYSQL/MariaDB)
![image](https://user-images.githubusercontent.com/25010528/217066104-a5c68a3f-6057-4a14-a912-58c5205b0896.png)
2. Create Discord Webhook and setup alert
3. Get down your service

### 👀 Expected behavior

You didn't get any service URL or should get right address (like IP:PORT)

### 😓 Actual Behavior

You get discord embed message with empty (`https://`) **Service URL**
![image](https://user-images.githubusercontent.com/25010528/217065653-03f0374b-c6ef-4ed4-a98d-d578c04770bc.png)

### 🐻 Uptime-Kuma Version

1.19.4

### 💻 Operating System and Arch

<Not Required>

### 🌐 Browser

<Not Required>

### 🐋 Docker Version

<Not Required>

### 🟩 NodeJS Version

<Not Required>

**Comment by chakflying** [comment]
This would require `includeSensitiveData` if I want to extract the host from the connection string during sending the notification. Or I guess we could save the host separately during `EditMonitor`.

**Comment by BlackYuzia** [comment]
> This would require `includeSensitiveData`

I don't mean what I always want get valid service URL. I just say if URL is empty (why `https://` has been saved idk) then this shouldn't be sent to discord webhook.

**Comment by TheSavageCoder** [comment]
This also occurs with the GameDig servers we are monitoring.

![image](https://user-images.githubusercontent.com/67223323/223020633-16d07c26-d276-4709-9548-bfa7ddb83b28.png)

**Comment by MsVoxxie** [comment]
Same thing happens from GameDig notices, empty service url when it should be omitted.

**Comment by chakflying** [comment]
Closing this in favor of #2727, since that one has more details.

Duplicate of #2727.
