### ISSUE TITLE
Weblate alert of too many outgoing commits

### ISSUE THREAD

**Issue by 401U** [louislam/uptime-kuma#2732]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### **Problem**

Just recived an alert email saying

> The VCS repository has many changes compared to the upstream. Please merge the changes manually or set up push to automate this.

Also ⚠️ appears on the Component and on all the language in it, which is so annoying.

As I checked that there are no conflict, I did a manully push, and the alert disappered.

### **Reason**
After searching [weblate docs](https://docs.weblate.org/en/latest/devel/alerts.html), I figured out that alert emails would be send when outgoing (or missing) commits is great than set value([REPOSITORY_ALERT_THRESHOLD](https://docs.weblate.org/en/latest/admin/config.html#repository-alert-threshold), default to 25). Which make sence as #2713 has 29 commits.

### **Solutions**
Following method may solve the problem.
1. merge language file changes frequently on github
2. improve the [REPOSITORY_ALERT_THRESHOLD](https://docs.weblate.org/en/latest/admin/config.html#repository-alert-threshold)
3. change the `Merge style` of vcs to `merge` (I personally dislike that, as rebase give us a clean commit tree)
4. set smaller push interval, but `Merge style` required to be `merge`, as `rebase` will lead to force-push
5. other solutions? idk

### 🐻 Uptime-Kuma Version

latest

### 💻 Operating System and Arch

latest

### 🌐 Browser

latest

### 🐋 Docker Version

latest

### 🟩 NodeJS Version

latest

**Comment by YehowahLiu** [comment]
> But as our previous experience, those env vars are not working for Docker?

I except `REPOSITORY_ALERT_THRESHOLD` to work with docker, as there is no related settings of it in [docker setting code](https://github.com/WeblateOrg/weblate/blob/main/weblate/settings_docker.py). Just search in that file for REPOSITORY_ALERT_THRESHOLD with no result.

**Comment by YehowahLiu** [comment]
> But as our previous experience, those env vars are not working for Docker?

I except `REPOSITORY_ALERT_THRESHOLD` to work with docker, as there is no related settings of it in [docker setting code](https://github.com/WeblateOrg/weblate/blob/main/weblate/settings_docker.py). Just search in that file for REPOSITORY_ALERT_THRESHOLD with no result.

**Comment by louislam** [comment]
Have set a large number, hope this works.

**Comment by YehowahLiu** [comment]
> Have set a large number, hope this works.

Oh no, it alert me again🤔

**Comment by YehowahLiu** [comment]
Not have so much free time recently to learn about weblate's code logic, so not sure the reason why it doesn't work.
To save our time, just change the `Merge style` to `merge` on weblate vcs setting would be an easy solution.
Though I have the permission on weblate, I expect your approval of doing such operation, or you can just do it yourself.

**Comment by louislam** [comment]
> > Have set a large number, hope this works.
> 
> Oh no, it alert me again🤔

Yes... those env vars are not usable in the docker container, just like the `GITHUB_CREDENTIALS`. Only env vars listed here could be used: https://docs.weblate.org/en/latest/admin/install/docker.html

Will try to use `merge` method

**Comment by 401U** [comment]
> Yes... those env vars are not usable in the docker container, just like the `GITHUB_CREDENTIALS`. Only env vars listed here could be used: https://docs.weblate.org/en/latest/admin/install/docker.html

It's possible to [edit configuration beyond environment variables](https://docs.weblate.org/en/latest/admin/install/docker.html#configuration-beyond-environment-variables) by [overriding settings from the data volume](https://docs.weblate.org/en/latest/admin/install/docker.html#overriding-settings-from-the-data-volume)

**Comment by 401U** [comment]
> It's possible to [edit configuration beyond environment variables](https://docs.weblate.org/en/latest/admin/install/docker.html#configuration-beyond-environment-variables) by [overriding settings from the data volume](https://docs.weblate.org/en/latest/admin/install/docker.html#overriding-settings-from-the-data-volume)

Have you tried this method to setup `REPOSITORY_ALERT_THRESHOLD`? I receive those alert email  basically everyday, which is so annoying.
