### ISSUE TITLE
Export UP/DOWN Log's of the Host.

### ISSUE THREAD

**Issue by Gururaj08** [louislam/uptime-kuma#2733]
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

New Monitor, UI Feature

### 🔖 Feature description

All the UP/DOWN logs need to be exported or Downloaded. 
![Log](https://user-images.githubusercontent.com/41589151/217254705-0b8c3204-2534-4e64-ad9b-eabf3cc2e339.JPG)

### ✔️ Solution

All the UP/DOWN logs need to be exported or Downloaded. 

### ❓ Alternatives

All the UP/DOWN logs need to be exported or Downloaded. 

### 📝 Additional Context

All the UP/DOWN logs need to be exported or Downloaded. 
![Log's](https://user-images.githubusercontent.com/41589151/217255180-372190a0-32d5-46ec-b60b-2fac370503d2.JPG)

**Comment by Gururaj08** [comment]
const logs = [
  { timestamp: '2022-01-01T00:00:00.000Z', message: 'Log message 1' },
  { timestamp: '2022-01-01T00:01:00.000Z', message: 'Log message 2' },
  { timestamp: '2022-01-01T00:02:00.000Z', message: 'Log message 3' },
];

const exportLogs = (logs) => {
  let csvContent = 'data:text/csv;charset=utf-8,';
  csvContent += 'timestamp,message\n';

  logs.forEach(function(log) {
    csvContent += `${log.timestamp},${log.message}\n`;
  });

  const encodedUri = encodeURI(csvContent);
  const link = document.createElement('a');
  link.setAttribute('href', encodedUri);
  link.setAttribute('download', 'logs.csv');
  document.body.appendChild(link);

  link.click();
};

exportLogs(logs);

**Comment by FaridGitStart** [comment]
@louislam I want to contribute on this feature-request and the feature for exporting logs. Just wanted to inform you before working on the feature.

**Comment by githubliuyang777** [comment]
@louislam in our teams, we need to count all the up/down times of the host every month, is there any plans to add some api for users dump up/down times log

**Comment by CommanderStorm** [comment]
@FaridGitStart 
> I want to contribute on this feature-request and add the feature for exporting logs. Just wanted to inform you before working on the feature.

Please read the contribution guide at https://github.com/louislam/uptime-kuma/blob/master/CONTRIBUTING.md
I think a good way to implement this is to add a checkbox here:
![image](https://github.com/louislam/uptime-kuma/assets/26258709/61295b9d-3d15-4544-869b-d9157da7a0e3)

=> adding a checkbox here if logs should be included should be an okay design decision.
If you think another option is better or notice other problems with this approach, please feel free to reach out

**Comment by CommanderStorm** [comment]
@githubliuyang777 
> in our teams, we need to count all the up/down times of the host every month, is there any plans to add some api for users dump up/down times log

We use 👍🏻 to gauge interest in features.
Please see #118 and #2693  

Also see https://pypi.org/project/uptime-kuma-api/ => this should be eazy to implement.
Note: This is an external Tool => no guarantees in any way.
