### ISSUE TITLE
resend alerts every 5 min to remember 

### ISSUE THREAD

**Issue by MohamedHassan84** [louislam/uptime-kuma#2737]
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

New Notification

### 🔖 Feature description

resend alerts every 5 min or period of time to remind user about alerts 

### ✔️ Solution

resend alerts every 5 min

**Comment by cyril59310** [comment]
This is already possible
![813825DC-A768-410F-AD29-99C5E41CE6F2](https://user-images.githubusercontent.com/70776486/217514247-77d71966-25af-4864-81bd-e58627045b30.jpeg)
