### ISSUE TITLE
Show tags on the dropdown list when adding a new monitor to a status page

### ISSUE THREAD

**Issue by khanh96le** [louislam/uptime-kuma#2739]
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

UI Feature

### 🔖 Feature description

I have 3 status pages, each reflecting an environment: TEST, UAT, and LIVE.

![Screen Shot 2023-02-08 at 16 57 46](https://user-images.githubusercontent.com/19431276/217497045-c2b11c93-0edb-4a37-9f14-f9fcbcb38598.png)

Whenever I want to monitor a service, I must add 3 different monitors for each environment. 
![Screen Shot 2023-02-08 at 17 02 41](https://user-images.githubusercontent.com/19431276/217498348-48102b72-bf64-48ea-afc6-136025a22532.png)

Then, let's say, I want to add my service to the Live Status Page, I need to choose the right one from the dropdown list. But you can see the problem here, I don't know which one has LIVE tag.
![Screen Shot 2023-02-08 at 17 08 08](https://user-images.githubusercontent.com/19431276/217499628-72d4170a-48b1-4717-a321-71ce5847ea8d.png)

### ✔️ Solution

Of course, one simple workaround is to change the monitor name to something like `[LIVE] Fraud Management API`.

But for the complete solution, I think It should show the tags in the dropdown list as well. Sorry for the ugly mock design, but that's my idea.

![Screen Shot 2023-02-08 at 17 16 17](https://user-images.githubusercontent.com/19431276/217501314-9338378e-4213-4c4f-b667-4e309f4c0f41.png)

**Comment by titanventura** [comment]
Please review https://github.com/louislam/uptime-kuma/pull/2752

**Comment by khanh96le** [comment]
Thank @titanventura for mentioning

**Comment by titanventura** [comment]
ping @khanh96le

**Comment by titanventura** [comment]
@khanh96le , can we close this issue ?

**Comment by CommanderStorm** [comment]
Closing as resolved by #2752 and released in `1.22.0`
