### ISSUE TITLE
Migrate from Non-Docker to Docker

### ISSUE THREAD

**Issue by ReneDyhr** [louislam/uptime-kuma#2740]
### ⚠️ Please verify that this bug has NOT been raised before.

- [x] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

I'm running on the non-docker version of UptimeKuma and I'm running into issues updating to the newest version (currently using 1.17.1).

Since npm install is failing, I wanted to move to the better solution, docker. Though, I'm facing issues now having any documentation on how to migrate over.

I thought it would be easy, just start the docker container with the kuma.db file from the non-docker version. Though, when I start it up with the old kuma.db, it's just sending me to the setup page, not registering that it's an existing instance.

How would I successfully move from non-docker to docker with my current data?

### 🐻 Uptime-Kuma Version

1.17.1

### 💻 Operating System and Arch

Ubuntu 22.04

### 🌐 Browser

Google Chrome

**Comment by cyril59310** [comment]
Did you find out the path of the data file to docker? For example, if your kuma.db file is in /home/kuma/data

docker run -d --restart=always -p 3001:3001 -v /home/kuma/data:/app/data --name uptime-kuma louislam/uptime-kuma:1

**Comment by ReneDyhr** [comment]
I did find that out. I started it first to make it generate all the files but after I've changed out the kuma.db to my own, it's still sending me to the setup page.

**Comment by ReneDyhr** [comment]
Ah, I think I found the problem. There's 2 kuma.db, one in data/ and one in db/
I choose the wrong one.
