### ISSUE TITLE
upgrade to last version causes a lost of data

### ISSUE THREAD

**Issue by daouddajani** [louislam/uptime-kuma#2741]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

i upgraded to the latest version today using the docker default steps. but unfortunately all the monitor configured where lost
and i was asked to create a new account and the monitor page is empty

is there a way to restore them?
i have no backup 

### 🐻 Uptime-Kuma Version

1.19.6

### 💻 Operating System and Arch

mint

### 🌐 Browser

chrome

**Comment by cyril59310** [comment]
uptime kuma make backups of the kuma.db in the data folder, example:
kuma.db.bak20221214181334

remove .back***** (here in the example .bak20221214181334) to recover your kuma.db file

**Comment by Nesci28** [comment]
Same thing happened here.  Will try to rename the kuma.db backup

**Comment by Pjstolas** [comment]
Hi, i did update to the newest version which led to data erase. Does docker installation use different volume path? i'm trying to recover old data but i'm having trouble.

**Comment by louislam** [comment]
> Hi, i did update to the newest version which led to data erase. Does docker installation use different volume path? i'm trying to recover old data but i'm having trouble.

You should provide more info. Maybe you installed Uptime Kuma using different tutorial that was using different volume path.

**Comment by Pjstolas** [comment]
I don't know which version i was using. Installed uptime kuma like a year ago and forgot about it. Few days ago decided to update through docker, not docker compose. But its ok. I have other question, can i check an ipv6 and when it changes, notifies me?
