### ISSUE TITLE
High CPU usage for Uptime-Kuma process

### ISSUE THREAD

**Issue by AndreKotze** [louislam/uptime-kuma#2751]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### Description

Recently my Uptime-Kuma started getting really sluggish to the point where the dashboard and status pages would not load or only load partially.  When running TOP on my server I noticed that the uptime-kuma process was constantly running at 100%.

![image](https://user-images.githubusercontent.com/4725308/217820179-9ca413e2-3d29-4961-b321-e05d547e9ff4.png)

### 👟 Reproduction steps

.

### 👀 Expected behavior

.

### 😓 Actual Behavior

.

### 🐻 Uptime-Kuma Version

1.19.6

### 💻 Operating System and Arch

Ubuntu 22.04.1 LTS

### 🌐 Browser

Google Chrome 109.0.5414.120

### 🟩 NodeJS Version

14.21.2

**Comment by rezzorix** [comment]
Before labelling this as a bug; can you give more information:

- how many monitors are you running
- what type of monitors
- what are the system specs

**Comment by AndreKotze** [comment]
I'm running roughly 100 monitors which are a mix of HTTP and PING.  My server is a 4 core VM with 8GB of RAM.

On the same server I'm also running an instance of Observium which is monitoring 100+ devices through SNMP and it has no issues with performance.

**Comment by AndreKotze** [comment]
Here is another screenshot from htop:

![image](https://user-images.githubusercontent.com/4725308/218011256-75f2d83f-30b2-4bb1-a2f0-4be0eb94189d.png)

**Comment by rezzorix** [comment]
System shouldnt be a problem for 100 monitors. 
Whats the frequency of your monitors?

**Comment by AndreKotze** [comment]
20 seconds.

**Comment by AndreKotze** [comment]
I'm not sure if this could be a contributing factor but I'm getting some weird graphs for my HTTP monitors.

![image](https://user-images.githubusercontent.com/4725308/218059587-6afaf1a5-df87-4054-b6df-dd3370acf3c6.png)

![image](https://user-images.githubusercontent.com/4725308/218059697-5db15517-854e-4886-bb4b-30c1fb635e8c.png)

![image](https://user-images.githubusercontent.com/4725308/218059845-e8ed8f59-2fad-49b8-abf4-0b201ca4710c.png)

![image](https://user-images.githubusercontent.com/4725308/218060144-3f8c5334-9793-495f-97d1-e640f946075e.png)

**Comment by rezzorix** [comment]
You running it on a VM...? Then thats probably the issue?

**Comment by louislam** [comment]
> 20 seconds.

It maybe too low for 100 monitors, try to increase it to 60 or higher.

**Comment by AndreKotze** [comment]
I've just finished changing them all to 60 seconds but it made no difference.  I'm now going to clear the heartbeats and events as well.

**Comment by AndreKotze** [comment]
After clearing all the historical data the CPU usage has come right down and will occasional peak above 10%.

![image](https://user-images.githubusercontent.com/4725308/218100009-6b136923-1dfd-4a8b-be7c-26aaeeec0826.png)

**Comment by AndreKotze** [comment]
My system seems to be stable again so I'm going to close this issue now...

**Comment by souzaalexgh** [comment]
@AndreKotze I understand it became stable after cleaning the historical data, but seems pretty weird. How did it behave after a few months?

**Comment by souzaalexgh** [comment]
> My system seems to be stable again so I'm going to close this issue now...

I understand it became stable after cleaning the historical data, but that seems pretty weird. How did it behave after a few months? I'm having the same issue all of a sudden, but I didn't try cleaning anything yet.

**Comment by CommanderStorm** [comment]
In v1, reducing either retention/ping-rate/.. or moving to a faster storage solution is the only option to get around this problem.
In v2, we have likely resolved this problem. See https://github.com/louislam/uptime-kuma/issues/4500 for further details of what needs to happen before we can release this version.
