### ISSUE TITLE
Content policy violation

### ISSUE THREAD

**Issue by davidmartib** [louislam/uptime-kuma#2753]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

Dear support users,

I'm trying to install kuma behind nginx reverse proxy, using the wiki configuration, but when I try to open the application, browser shows error:

```
Cannot connect to the socket server. [Error: websocket error] Reconnecting...
Using a Reverse Proxy? [Check how to config it for WebSocket](https://github.com/louislam/uptime-kuma/wiki/Reverse-Proxy)
```

If I open the browser's console I can read this message:

`Refused to connect to 'wss://<mydomain>/socket.io/?EIO=4&transport=websocket' because it violates the following Content Security Policy directive: "default-src https: data: 'unsafe-inline' 'unsafe-eval'". Note that 'connect-src' was not explicitly set, so 'default-src' is used as a fallback.`

Nginx is configured using ssl, I if I try to connect directly to kuma on port 3001 using HTTP all works succesfully.

Thanks for your time.

### 🐻 Uptime-Kuma Version

Latest released

### 💻 Operating System and Arch

Ubuntu 20.04 x64

### 🌐 Browser

Chrome latest version

**Comment by davidmartib** [comment]
I resolved this issue adding a Cache-Control header to my Nginx config file:
(I don't understand why, but it works)

```
location / {
      **add_header Cache-Control no-store;**
      proxy_set_header   X-Real-IP $remote_addr;
      proxy_set_header   X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header   Host $host;
      proxy_pass         http://update-kuma;
      proxy_http_version 1.1;
      proxy_set_header   Upgrade $http_upgrade;
      proxy_set_header   Connection "upgrade";
    }
```

**Comment by davidmartib** [comment]
I've changed the _Primary Base URL_ to my https://<domain>, perhaps this is the reason.

**Comment by RedBoardDev** [comment]
For me, I've always this error on chrome with your fix
