### ISSUE TITLE
Ping Threshold

### ISSUE THREAD

**Issue by Appoxo** [louislam/uptime-kuma#2754]
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

UI Feature, Other

### 🔖 Feature description

Additional option for the ping threshold.
Add an option to enable notifications if the ping is too high
-> Threshold is 120ms
If ping exceeds 120ms it will send a message with the configured notification system

### ✔️ Solution

Add an option to set ping threshold

**Comment by louislam** [comment]
Duplicate of #1813
