### ISSUE TITLE
Integrate with teams

### ISSUE THREAD

**Issue by Kbvz** [louislam/uptime-kuma#2755]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

Hello, I saw that it was possible to integrate alerts in teams.  I wish I had some info on how to integrate this
Thks

### 🐻 Uptime-Kuma Version

Dt know

### 💻 Operating System and Arch

Ubuntu 

### 🌐 Browser

Chrome 

### 🐋 Docker Version

Dt Know

**Comment by JoelMiller74** [comment]
**Process:**
Open Teams
Find the Channel that you want alerts to go to.
Click the ellipse [...] next to the channel name and select Connectors
Find the **Incoming Webhook** and click **Add**
Provide a name for the webhook like 'Uptime-Kuma'
Click **Create**
A webhook URL will be provided. Copy this for later.
Open Uptime-Kuma and choose the dropdown in the top-right of the page and select Settings.
Choose **Notifications**
Click **Setup Notification**
Change Type to **Microsoft Teams**
Give it a **Friendly Name**
Enter the **Webhook URL** that you copied.
Decide if you want it to de **enabled by defaul**t and if you want to **apply it to all existing monitors**.
Click **Test** and then **Save** it if it works.
Then make something go down and see if the alert triggers and sends a Teams message to that Channel.
