### ISSUE TITLE
Uptime History

### ISSUE THREAD

**Issue by czsquizer** [louislam/uptime-kuma#2756]
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

UI Feature

### 🔖 Feature description

You should add possibility to view ping status and more history interval in the status page.

### ✔️ Solution

Allow user to select which timescale they want to see. For example, if I choose 1 month interval, we could view daily, if there were any outages.

### ❓ Alternatives

Alternatively allow admins to set the timescale that could be seen in the status page.

### 📝 Additional Context

I think it would be be considered by many of people using this beautiful webpage monitoring system. :)

Thank you -_-

**Comment by tkbstudios** [comment]
@louislam 
Do it please it'll be so amazing!
It'll be so cool to have one like roblox (Accident history, down time, etc..)
[Roblox status page](https://status.roblox.com/)

**Comment by czsquizer** [comment]
I thought more like better uptime, or uptime robot ... That each "green vertical line" would represent 1 day ...

**Comment by tkbstudios** [comment]
Yes and that you could also click these green dots to see detailed for each hour and that there's also an incident history like these on Atlassian Status Pages

**Comment by CommanderStorm** [comment]
@czsquizer 
I think this is a duplciate of https://github.com/louislam/uptime-kuma/issues/1984 
If you agree, please close this issue (duplicates only create immortal zombies).
If you disagree, could you comment why this is a different issue?
