### ISSUE TITLE
Steam Game Servers not responding

### ISSUE THREAD

**Issue by disclearing** [louislam/uptime-kuma#2758]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

It will not detect any game server I have running any fixes ?

### 🐻 Uptime-Kuma Version

1.19.6

### 💻 Operating System and Arch

Ubuntu 22.04.1

### 🌐 Browser

Google Chrome

### 🐋 Docker Version

Docker version 23.0.1, build a5ee5b1

**Comment by rezzorix** [comment]
Please provide more specific information.

**Comment by Computroniks** [comment]
@disclearing  Before we can start to diagnose any issues, we need the following information.

- Details of the error messages sent in the web interface
- Logs from the docker container
- The steps we can use to reproduce the issue
- What you have tried so far to fix the issue

**Comment by disclearing** [comment]
Brother it just does not work i input api key and it no work

**Comment by rezzorix** [comment]
Ok, you put in the steam api key.

Then you need to 

1. "+ Add New Monitor" -> "Steam Game Server"
2. enter all details
3. save

Have you followed this steps?

**Comment by disclearing** [comment]
I have it just dont see it

**Comment by rezzorix** [comment]
Nobody will be able to help you if you do not communicate properly.

**Comment by disclearing** [comment]
I clearly fucking am I deployed it through docker i signed up entered multple steam api keys neither one finds either one of my game servers are you fucking retarded I don't know what planet you are fucking on there is no errors no nothing it doesnt fucking find the server on the steam api even doe its fucking live and i can join them all

**Comment by disclearing** [comment]
!!
