### ISSUE TITLE
SMTP Notifications not working. "Self Signed Certificate" error

### ISSUE THREAD

**Issue by Trembler34** [louislam/uptime-kuma#276]
I get this error no matter the deployment. unraid with postfix as smtp server and ubuntu using exchange as smtp, both in different sites keep giving me this error. I can't setup SMTP notifications. Any idea how to get around it? Both sites have certificates. 

![Screenshot 2021-08-26 100623](https://user-images.githubusercontent.com/37017861/130988101-b56f3ad3-283b-4804-ba65-aeb2720bea25.png)

**Comment by louislam** [comment]
Implemented, ignore tls error will be available in the next version.

https://github.com/louislam/uptime-kuma/commit/dd283423ab230862e2e3ee2514265c063b34e349

![image](https://user-images.githubusercontent.com/1336778/132554731-f4dfef21-b73b-49d0-a1b7-443aea3f0a7d.png)
