### ISSUE TITLE
I got this

### ISSUE THREAD

**Issue by MarshmelloMusicerXD** [louislam/uptime-kuma#2761]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

![image](https://user-images.githubusercontent.com/68960255/218318431-3145969a-2849-4308-936b-25c4c482c425.png)
Can you help me?

### 🐻 Uptime-Kuma Version

idk

### 💻 Operating System and Arch

Windows

### 🌐 Browser

Google Chrome

### 🟩 NodeJS Version

Latest

**Comment by louislam** [comment]
What, what did you run before showing this?
