### ISSUE TITLE
Kuma On Site Agent

### ISSUE THREAD

**Issue by stodo94** [louislam/uptime-kuma#2766]
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

Other

### 🔖 Feature description

Hi,

it would be great to have an agent functionality in Kuma.

### ✔️ Solution

For example that one instance can report ping and all the requests to a main instance.

Big advantage would be to not make all ips and ports available for the main instance.

**Comment by Computroniks** [comment]
Is this something not handled by the push monitor type?

**Comment by stodo94** [comment]
No I would like to have a agent module for example:
Kuma Uptime Master instance and a kuma slave instance on site which is probing ping, https, etc. for all the hosts

**Comment by Computroniks** [comment]
Feels like a duplicate of #1259

**Comment by stodo94** [comment]
Thanks, seems like a duplicate. Didn't found it with my search keywords
