### ISSUE TITLE
[Latest] Docker container stays in "starting" state

### ISSUE THREAD

**Issue by tweek11** [louislam/uptime-kuma#2774]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### Description

[Latest] Docker container stays in "starting" state eventually changing to "unhealthy" state after recent update on Feb 13th 2023 - Container however is up and running and accessable via web gui

![image](https://user-images.githubusercontent.com/91363983/218620262-7f2b433c-7f2e-45f5-af2c-947c586269d8.png)

### 👟 Reproduction steps

Recreated / pulled image again and it replicates itself.

### 👀 Expected behavior

Recent update as of earlier this morning has caused the issue to occur.

### 😓 Actual Behavior

docker image update created issue at hand.

### 🐻 Uptime-Kuma Version

Version: 1.20.0

### 💻 Operating System and Arch

Ubuntu 22.04.1 LTS Server

### 🌐 Browser

Chrome Version 110.0.5481.97 (Official Build) (64-bit) & Firefox Version 109.0.1 (64-bit)

### 🐋 Docker Version

Docker version 20.10.14, build a224086

### 🟩 NodeJS Version

NodeJS Version 16

### 📝 Relevant log output

```shell
Container Logs:

==> Performing startup jobs and maintenance tasks
==> Starting application with user 0 group 0
Welcome to Uptime Kuma
Your Node.js version: 16
2023-02-13T23:31:46Z [SERVER] INFO: Welcome to Uptime Kuma
2023-02-13T23:31:46Z [SERVER] INFO: Node Env: production
2023-02-13T23:31:46Z [SERVER] INFO: Importing Node libraries
2023-02-13T23:31:46Z [SERVER] INFO: Importing 3rd-party libraries
2023-02-13T23:31:47Z [SERVER] INFO: Creating express and socket.io instance
2023-02-13T23:31:47Z [SERVER] INFO: Server Type: HTTP
2023-02-13T23:31:47Z [SERVER] INFO: Importing this project modules
2023-02-13T23:31:47Z [NOTIFICATION] INFO: Prepare Notification Providers
2023-02-13T23:31:47Z [SERVER] INFO: Version: 1.20.0
2023-02-13T23:31:48Z [DB] INFO: Data Dir: ./data/
2023-02-13T23:31:48Z [SERVER] INFO: Connecting to the Database
2023-02-13T23:31:48Z [DB] INFO: SQLite config:
[ { journal_mode: 'wal' } ]
[ { cache_size: -12000 } ]
2023-02-13T23:31:48Z [DB] INFO: SQLite Version: 3.39.4
2023-02-13T23:31:48Z [SERVER] INFO: Connected
2023-02-13T23:31:48Z [DB] INFO: Your database version: 10
2023-02-13T23:31:48Z [DB] INFO: Latest database version: 10
2023-02-13T23:31:48Z [DB] INFO: Database patch not needed
2023-02-13T23:31:48Z [DB] INFO: Database Patch 2.0 Process
2023-02-13T23:31:48Z [SERVER] INFO: Load JWT secret from database.
2023-02-13T18:31:48-05:00 [SERVER] INFO: Adding route
2023-02-13T18:31:48-05:00 [SERVER] INFO: Adding socket handler
2023-02-13T18:31:48-05:00 [SERVER] INFO: Init the server
2023-02-13T18:31:48-05:00 [SERVER] INFO: Listening on 3001


Healthcheck Logs:

docker inspect --format "{{json .State.Health }}" uptime-kuma | jq
{
  "Status": "unhealthy",
  "FailingStreak": 130,
  "Log": [
    {
      "Start": "2023-02-13T20:44:35.345603713-05:00",
      "End": "2023-02-13T20:44:36.627348244-05:00",
      "ExitCode": 1,
      "Output": "Health Check ERROR\n"
    },
    {
      "Start": "2023-02-13T20:45:36.635919004-05:00",
      "End": "2023-02-13T20:45:37.90540917-05:00",
      "ExitCode": 1,
      "Output": "Health Check ERROR\n"
    },
    {
      "Start": "2023-02-13T20:46:37.915300586-05:00",
      "End": "2023-02-13T20:46:39.224146218-05:00",
      "ExitCode": 1,
      "Output": "Health Check ERROR\n"
    },
    {
      "Start": "2023-02-13T20:47:39.237531979-05:00",
      "End": "2023-02-13T20:47:40.599444254-05:00",
      "ExitCode": 1,
      "Output": "Health Check ERROR\n"
    },
    {
      "Start": "2023-02-13T20:48:40.607842167-05:00",
      "End": "2023-02-13T20:48:41.892513961-05:00",
      "ExitCode": 1,
      "Output": "Health Check ERROR\n"
    }
  ]
}
```

**Comment by chakflying** [comment]
Is your server `x86` or `arm64`?

**Comment by tweek11** [comment]
Arm64

**Comment by louislam** [comment]
I suspected that it is a portainer bug, because it is still using the old healthcheck script, as ``Health Check ERROR` is coming from the old script. 

But I will try to rebuild the debian image.

**Comment by louislam** [comment]
I just rebuilt the debian image too, you could try now.

**Comment by tweek11** [comment]
It appears to be working properly again after recreating/puling the image again. 

Do you still feel this is a Portainer glitch? If so i can log a ticket with them for the Portainer Business Edition. 

If so - should i just reference the above statement of " it is still using the old healthcheck script, as ``Health Check ERROR` is coming from the old script. " Or is there something more specific i should refer to?

**Comment by louislam** [comment]
I think so. I can reproduce it.

If I directly create a container with `louislam/uptime-kuma:1.20.0`, the healthcheck script is correct. (`extra/healthcheck`) (no `.js`) 

![image](https://user-images.githubusercontent.com/1336778/218643558-a7a0713e-2487-4f83-8ebf-08fa107195c2.png)



If I first create a container with `louislam/uptime-kuma:1.18.0`.
![image](https://user-images.githubusercontent.com/1336778/218646054-77371c96-c0ec-440c-8676-766c729f8615.png)

And then update to 1.20.0, it used the wrong healthcheck script (with .js)
![image](https://user-images.githubusercontent.com/1336778/218646168-f86efc9f-aa09-4bfa-84e2-54118ace6ea1.png)

**Comment by louislam** [comment]
You could also check your current healthcheck script by going into `Inspect > Config > Healthcheck > Test`.

**Comment by tweek11** [comment]
Interesting it still reflects the healthcheck,js on my side with using the "latest" tag
![image](https://user-images.githubusercontent.com/91363983/218647839-2869e6a5-b95b-4c46-bb81-5a10ea57973b.png)

Makes me wonder if it would be more prudent to just backup the monitors, prune the existing and redeploy from scratch entirely.

**Comment by carsten-re** [comment]
After pulling the image again, the container comes up.
However, the healthcheck is in my environment still the old, I guess... (healthcheck.js)

**Comment by tweek11** [comment]
I just backed up my config from the interface, stopped the container, did a "docker system prune", redeployed in a different directory, and imported config . Upon double checking it now reports as just healthcheck. Took all of two mins.

**Comment by carsten-re** [comment]
@tweek11 - It was quicker for me :-) Just stopped & started the container and the healthcheck is now "extra/healthcheck".
I'm happy, that this issue was solved so quickly...

**Comment by DerHerrGammler** [comment]
for me a simple repull and recreate of the image solved this too. thanks for all comments

**Comment by louislam** [comment]
> Interesting it still reflects the healthcheck,js on my side with using the "latest" tag ![image](https://user-images.githubusercontent.com/91363983/218647839-2869e6a5-b95b-4c46-bb81-5a10ea57973b.png)
> 
> Makes me wonder if it would be more prudent to just backup the monitors, prune the existing and redeploy from scratch entirely.

Yes, so that is why I think it is a Portainer bug.  

> If so i can log a ticket with them for the Portainer Business Edition.

I think you should do that, thanks.
