### ISSUE TITLE
Q: Change notification title

### ISSUE THREAD

**Issue by stomko11** [louislam/uptime-kuma#2775]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

Hello. I am looking for a way how to change notification title to something custom defined. I found few merges regarding ability to change hostname, but I run UK in docker, so I was wondering if there is any extra parameter or env variable that I could use?
I am using pushbullet for my notifications, across multiple devices. Notification title is "Uptime Kuma Alert" but I would like to change it so that I can instantly tell, when I get notification, which instance of UK sent it.

### 🐻 Uptime-Kuma Version

1.20

### 💻 Operating System and Arch

docker

### 🌐 Browser

NA

### 🐋 Docker Version

Docker service on Unraid

**Comment by Computroniks** [comment]
I am not sure if this is currently supported. I know there was some discussions with templating for notifications but I don't think these have been acted upon yet.

**Comment by stomko11** [comment]
Thanks. I have switched to use Pushover instead of Pushbullet for notifications. It allows creating multiple API keys and name them accordingly. That way I can assign each instance its own key and when I get notification, I see a title who sent it.
