### ISSUE TITLE
Config on Docker

### ISSUE THREAD

**Issue by BijSvenNL** [louislam/uptime-kuma#2782]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue
- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

Hi! i want to edit the Discord Message but on /home/uptime-kuma i get these files: `kuma.db  kuma.db.bak0  kuma.db-shm  kuma.db-shm.bak0  kuma.db-wal  kuma.db-wal.bak0  upload`

Does anyone know how to find these?

### 🐻 Uptime-Kuma Version

1.19.6

### 💻 Operating System and Arch

Ubuntu Server 22.04 LTS

### 🌐 Browser

Firefox 109.0.1 (64-bits)

### 🐋 Docker Version

Docker version 20.10.12, build 20.10.12-0ubuntu2~20.04.1

### 🟩 NodeJS Version

unable to find

**Comment by Computroniks** [comment]
If you are using docker, you cannot edit the files. You would have to edit the files by first cloning the repository and then rebuild the docker container, something which is not currently supported.

**Comment by CodebySven** [comment]
Oh
