### ISSUE TITLE
Sort tags in dashboard list view

### ISSUE THREAD

**Issue by luckman212** [louislam/uptime-kuma#2785]
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

UI Feature

### 🔖 Feature description

It would be really nice if the tags were sorted so that monitors that have the same tag set would appear identical.

![screenshot_wmJuEjxU](https://user-images.githubusercontent.com/1992842/219125508-2b9be221-436d-4c59-adf7-263a53b2cdf7.png)

### ✔️ Solution

I quickly glanced at the code and it seemed like a simple `ORDER BY tag.name` would do here

https://github.com/louislam/uptime-kuma/blob/fdc3b2d57a9037c4415d18fe01762e7960a7fd43/server/model/monitor.js#LL146C19-L146C19

```js
async getTags() {
    return await R.getAll("SELECT mt.*, tag.name, tag.color FROM monitor_tag mt JOIN tag ON mt.tag_id = tag.id WHERE mt.monitor_id = ? ORDER BY tag.name", [ this.id ]);
}
```
I manually patched my 1.20.1 install and ... it worked! 

![screenshot_IemXTUCb](https://user-images.githubusercontent.com/1992842/219127540-1844b8f3-e987-40f8-be1e-223d6349a63a.png)

So this could be a quick PR if accepted.

**Comment by luckman212** [comment]
made a quick PR

https://github.com/luckman212/uptime-kuma/pull/1

**Comment by Computroniks** [comment]
PRs should be made against this repo, not your own, that way we can merge them here and see the changes easier

**Comment by luckman212** [comment]
Sorry- fat fingered mistake. Fixing now

**Comment by CommanderStorm** [comment]
@luckman212 given that the associated PR has been merged, can you close this issue or edit it to make clear what still needs to be done?

**Comment by CommanderStorm** [comment]
Thanks ❤️
