### ISSUE TITLE
Push-based monitoring

### ISSUE THREAD

**Issue by ben-z** [louislam/uptime-kuma#279]
**Is it a duplicate question?**
Not that I'm aware (after searching "push", "push-based", and "healthchecks).

**Is your feature request related to a problem? Please describe.**
Nope

**Describe the solution you'd like**
A push-based system where computers (potentially behind NATs) can ping uptime-kuma to indicate that it's up. This allows for arbitrary checks (can run any command and report its status). One project that implements this is [healthchecks.io](https://github.com/healthchecks/healthchecks). It would be awesome if we can have integration with Healthchecks.io.

**Describe alternatives you've considered**
[healthchecks.io](https://github.com/healthchecks/healthchecks). Though there's no readily available dashboard implementations that show historical uptime.

**Additional context**
N/A

**Comment by oezh** [comment]
+1 for this request. In statping, this is called "check-in" feature (currently not working by the way). The heartbeat is checked in reverse. For example, instead of "Uptime Kuma" to ping (or check) the host, the host (inside a NAT or not publicly exposed) is the one that checks-in to "Uptime Kuma" server.  

Hey bro @louislam thanks for this software, Uptime Kuma is awesome. Already have 88 monitors and is working flawlessly with PushOver notifications. Let me buy you a beer. Please DM your paypal.

**Comment by louislam** [comment]
I set this to the next next milestone.

**Comment by sbehrends** [comment]
This is in fact an interesting feature.

I was reviewing a bit the source code. I would imagine exposing a public endpoint (maybe `/monitor/:monitorID/checkin`) which would add a `hearbeat` row recording time of last checkin.

Then the second piece is the Monitor function which runs in the "timeout" interval that would turn the monitoring DOWN if the last heartbeat was missed.

**Comment by rossedlin** [comment]
+1 for this feature.

In the past, I usually have some sort of curl script running which sends out a pulse to a server listening (kuma).
The listening server (kuma) would basically say it's online if it got a pulse from the curl script every 1 minute.

If this feature was implemented I would appreciate so much!
I would even donate if you did this!

**Comment by gaby** [comment]
👍🏻 for this feature, it would really help when running networks behind VLANS, NATS, Proxies.

**Comment by user592965** [comment]
If uptime-kuma also integrates the "grace period" and the /start option in the url which allows to monitor the execution time of a script like healthchecks.io, it would be very interesting.

**Comment by gaby** [comment]
@louislam Found another small bug, If you:

- Add a "Push" monitor
- Create a backup
- Import backup in a freshly installed Uptime-Kuma instance.
- The "Push" monitor `/api/push/token` url no longer works. When sending curl requests to the URL I get a "Monitor Not Found" error.

To fix this, I had to delete the monitor completely and re-create it. An enhancement could be to add a "Refresh" icon next to the `/api/push/token` generated URL, so that when clicked it generates a New URL.

**Comment by yuriw** [comment]
And then what ?

I get this URL http://cuz:3001/api/push/7lvIsblXoX?msg=OK&ping=

How do I ping/push say from the external server or other countries?

**Comment by louislam** [comment]
@yuriw 

Sorry, but in the other hand, I dont know what is uncleared here.

> http://cuz:3001/api/push/7lvIsblXoX?msg=OK&ping=

The answer is straight forward to me. You have to setup "something" to keep calling this url from your external server. 

What is "something"? 

There are thousands methods. How to call this url is really up to you. Try the url first on your browser first, I think you will have an idea of it.

If you want to call it from linux and wget, here is another discussion here.
https://github.com/louislam/uptime-kuma/issues/679

**Comment by xpufx** [comment]
@yuriw 
> Now more about my personal expectation of this feature. The push monitor practically tests the` uptime-kuma` instance itself AFAIK (correct me of this wrong) and it's somewhat useful. Than you.

I think you were confused here a bit. Uptime Kuma itself has to be up and running. That's a given (and the weak link in a monitoring setup. If it's not up itself, it can't send you alerts.).

However, what you're doing is you're sending a heartbeat from another host basically telling the monitoring software "I AM UP!". This is how uptime kuma knows your originating service is up. You can put a straight curl call into crontab and call the uptime kuma url they provided in this link. If you need to monitor something more complicated you either create a script or use the error notification of the software you want to monitor and have it somehow call that url. For example if you want to know if a backup job ran, you can have your backup script on the originating host push a notification to uptime kuma with the status of the backup job etc. etc.

That said I don't get why @louislam and others are figthing against providing help to you or good documentation. You can check Alerta for a project with a good api for this kind of setup. It supports a method similar to that of uptime kuma's in addition to client software you can use on the originating host. The concepts would mostly translate to uptime kuma as well.

When you figure this out. Consider donating documentation.

**Comment by jniggemann** [comment]
> That said I don't get why @louislam and others are figthing against providing help to you or good documentation.

Please indice where in this thread you find @louislam or anyone else "_figthing against providing help to you or good documentation_".

**Comment by MarvinJWendt** [comment]
Hi, is there a way to report a `down` service? `http://status.example.com/api/push/xxxxxx?msg=DOWN` does still result in a `UP` point. 

My issue with this is, I am using a middleware to check my service, and I'd like to strictly report if it's up or not. Currently, I don't know if the middleware **or** the service is down, as both scenarios would result in "not pushing" to the API. A possible parameter could be `ok` which accepts a boolean, and is true by default (so that the change is non-breaking).

**Comment by markdesilva** [comment]
I wasn't aware that there was a 'msg' parameter, but then I haven't kept up with UK as I've been busy with other stuff for quite a while now.

In any case, you can use the reverse feature so that if a service is connected it registers as down. Your middle ware would need to push to UK only if it _cannot_ detect your service. You would then need your middle ware have an second push to UK periodically (eg: every second - see my example posts above using ping to Yuri).

Perhaps you could share how the middle ware determines if your service is up or down and then how do you get the middle ware to push to UK. Also why the service can't push directly to UK -  is it on a private LAN and your middle ware is a bridge?

Cheers!

> Hi, is there a way to report a `down` service? `http://status.example.com/api/push/xxxxxx?msg=DOWN` does still result in a `UP` point.
> 
> My issue with this is, I am using a middleware to check my service, and I'd like to strictly report if it's up or not. Currently, I don't know if the middleware **or** the service is down, as both scenarios would result in "not pushing" to the API. A possible parameter could be `ok` which accepts a boolean, and is true by default (so that the change is non-breaking).
> 
> A workaround would be to also include a monitor for the middleware, that always reports. That way, I could figure out if the middleware or the service is down. This seems a little bloated to me tho, and would double my monitor count, probably.

**Comment by markdesilva** [comment]
DB queries? If so, I did something similar for one of the projects I was working on a couple of months back. What I did was to write a simple php script (on the db server itself) to do the queries and based on the return values, the script would call the push URL via curl or wget to UK. If your docker stack has no internet connectivity out then it will be a problem but if allows traffic out (but not in), it is still possible and hence you could do away with the middle ware. 

But if the reverse option works with your current set up and you're happy with it, then simplest option is always best!

Cheers!

**Comment by t3cneo** [comment]
> For those interested in a remote probe, I wrote one in .Net6. Only Ping is available so far.
> 
> Not documented yet. Adjust appsettings.json accordingly to your settings.
> 
> https://github.com/zimbres/UptimeKumaRemoteProbe

Installed your app on a Windows Host as a service with NSSM( the non-Sucking Service Manager ) : works like a charm !

**Comment by ovizii** [comment]
Here is a related question. uptimekuma says:
![image](https://user-images.githubusercontent.com/837902/176478120-e2a5b0f6-ab54-4518-9f25-fbae3fd9886c.png)

Would somebody please enlighten me about the usage of these optional parameters?

**Comment by wechsler42** [comment]
Hi there,
I am also looking for some enlightenment on the usage of the optional parameters "status", "msg" and especially "ping" with regards to a passive monitoring ( probing).

**Comment by ovizii** [comment]
> Hi there, I am also looking for some enlightenment on the usage of the optional parameters "status", "msg" and especially "ping" with regards to a passive monitoring ( probing).

It looks like you can pass the actual ping time through via the ping parameter, but I haven't done any further tests.

**Comment by shiny** [comment]
> Here is a related question. uptimekuma says: ![image](https://user-images.githubusercontent.com/837902/176478120-e2a5b0f6-ab54-4518-9f25-fbae3fd9886c.png)
> 
> Would somebody please enlighten me about the usage of these optional parameters?

I'm looking for the description of those parameters too. can't find doc.

**Comment by frorayz** [comment]
Can anyone help me out here? The website I am trying to monitor is behind a SSO. Not sure how to make sure its up?

**Comment by markdesilva** [comment]
> Can anyone help me out here? The website I am trying to monitor is behind a SSO. Not sure how to make sure its up?

I'm assuming you have the SSO credentials to pass to the site? If so, you use the Authorization header as detailed here:

https://github.com/louislam/uptime-kuma/issues/768

If you need to encode the userid:password you can do so here:

https://www.base64encode.org/

**Comment by markdesilva** [comment]
> Can anyone help me out here? The website I am trying to monitor is behind a SSO. Not sure how to make sure its up?

I thought you could use the Authentication header but I tested and it didn't work. Looks like you need a proxy.

See this:

https://goauthentik.io/integrations/services/uptime-kuma/

**Comment by markdesilva** [comment]
Mis understood your question completely. Sorry about that, deleted my comments.

> Can anyone help me out here? The website I am trying to monitor is behind a SSO. Not sure how to make sure its up?

**Comment by frorayz** [comment]
> Mis understood your question completely. Sorry about that, deleted my comments.
> 
> > Can anyone help me out here? The website I am trying to monitor is behind a SSO. Not sure how to make sure its up?

Ah damn, thanks for trying to help. Would be very grateful if someone guides me in the right direction tho.

**Comment by louislam** [comment]
> > Here is a related question. uptimekuma says: ![image](https://user-images.githubusercontent.com/837902/176478120-e2a5b0f6-ab54-4518-9f25-fbae3fd9886c.png)
> > Would somebody please enlighten me about the usage of these optional parameters?
> 
> I'm looking for the description of those parameters too. can't find doc.

- status={up|down}
- msg={string} up or down message
- ping={integer} you have to measure it in your application. e.g. measure the ping of Uptime Kuma

**Comment by louislam** [comment]
> Mis understood your question completely. Sorry about that, deleted my comments.
> 
> > Can anyone help me out here? The website I am trying to monitor is behind a SSO. Not sure how to make sure its up?

Method 1: Use overlay network such as Tailscale, put Uptime Kuma and your website together into a same network. Uptime Kuma can access your website like they are in a same Lan.
Method 2: With http(s) monitor, some SSO let you bypass the login page using Auth header.
Method 3: With push monitor, you need to write a simple script to call the push url periodically.

**Comment by frorayz** [comment]
> > Mis understood your question completely. Sorry about that, deleted my comments.
> > > Can anyone help me out here? The website I am trying to monitor is behind a SSO. Not sure how to make sure its up?
> 
> Method 1: Use overlay network such as Tailscale, put Uptime Kuma and your website together into a same network. Uptime Kuma can access your website like they are in a same Lan. Method 2: With http(s) monitor, some SSO let you bypass the login page using Auth header. Method 3: With push monitor, you need to write a simple script to call the push url periodically.

Thank you for the suggestions. How would I access [this SSO](https://cunyfirst.cuny.edu/) which is behind a oracle 12c server using method 3? I have only user level access to that site. Nothing admin.

**Comment by pythonmandev** [comment]
Would you like to use the agents to monitor the servers/urls ,and push(upload) the result to the kuma ?
