### ISSUE TITLE
can only login on chrome android 

### ISSUE THREAD

**Issue by damo901** [louislam/uptime-kuma#2794]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

installed uptime-kuma on docker on kubuntu and i cant even login on from my desktop or server. only chrome from android. when try to login using other browser from any other device i get password incorrect but if i type the same password into chrome on android it work no problem . tried reinstalling it and changing the password but still nothing will work 

### 🐻 Uptime-Kuma Version

1.20.1

### 💻 Operating System and Arch

kubuntu

### 🌐 Browser

firefox

### 🐋 Docker Version

23.0.1

**Comment by cyril59310** [comment]
doesn't your android automatically add a capital letter to the beginning of your password?

otherwise try changing the password temporarily to see if the problem persists
docker exec -it <container name> bash
 and
 npm run reset-password

**Comment by damo901** [comment]
> doesn't your android automatically add a capital letter to the beginning of your password?
> 
> otherwise try changing the password temporarily to see if the problem persists docker exec -it container-name bash and npm run reset-password

i tried changing the password on both pc, server and android but only android chrome will login and not any other browser. iv tried the password on firefox on android still wont login
