### ISSUE TITLE
How to move data from local installation to docker installation?

### ISSUE THREAD

**Issue by apoorv569** [louislam/uptime-kuma#2798]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

I want to move my local installation from local install to `docker` install as it is much easier to maintain and update for me. How can I move my existing data from the local installation to `docker` installation. I'm using `docker-compose.yml` file in the `docker` directory.

### 🐻 Uptime-Kuma Version

1.20.1

### 💻 Operating System and Arch

Debian 11 bullseye

### 🌐 Browser

Firefox

### 🐋 Docker Version

23.0.1

### 🟩 NodeJS Version

16.19.1

**Comment by Computroniks** [comment]
All data is stored in the /data directory. So long as this is copied over all data should be kept

**Comment by apoorv569** [comment]
> All data is stored in the /data directory. So long as this is copied over all data should be kept

I  moved all data from `/data` to my `docker` `appdata` directory. I do see the login page but it says invalid username password. I use a password manager so it can't really be wrong.

**Comment by louislam** [comment]
Usually moved to an incorrect location. Please provide absolute paths or screenshots, so that people can actually understand your situation.

**Comment by apoorv569** [comment]
> Usually moved to an incorrect location. Please provide absolute paths or screenshots, so that people can actually understand your situation.

I moved all the data from this directory,
![2023-02-25_09-56](https://user-images.githubusercontent.com/53279454/221338109-74c3210f-4e04-4e3d-9de1-c29a19446a52.png)

to here,
![2023-02-25_09-57_1](https://user-images.githubusercontent.com/53279454/221338119-4545f8c3-797f-4c24-b17f-35a632acf1bb.png)

and here is `docker-compose.yml`.
![2023-02-25_09-57](https://user-images.githubusercontent.com/53279454/221338138-769c2d4f-fee8-4517-8234-a61d1ce74a8f.png)

**Comment by apoorv569** [comment]
> Usually moved to an incorrect location. Please provide absolute paths or screenshots, so that people can actually understand your situation.

OK, I managed to fix it. I found this page https://github.com/louislam/uptime-kuma/wiki/Reset-Password-via-CLI

and I ran this command to reset the password.
```
docker exec -it <container name> bash
npm run reset-password
```

It worked.
