### ISSUE TITLE
Monitor Type push gives no Notification if it down

### ISSUE THREAD

**Issue by Zwixx** [louislam/uptime-kuma#2801]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

I tried to monitor a daily crontab with uptime cuma. So I added a push notification and set a timeout of 90000 Seconds (25 hours). But nothing happens. The url is not visited for more than three days and the check says "up" and no notification is send.

If I add a push service with 60 seconds, it works. Is there a problem with times over one day?

### 🐻 Uptime-Kuma Version

1.20.1

### 💻 Operating System and Arch

Raspbian

### 🌐 Browser

Firefox

### 🐋 Docker Version

20.10.22

**Comment by scr4tchy** [comment]
Could be related to https://github.com/louislam/uptime-kuma/issues/922 too. I am only getting `DOWN` notifications but not `UP` notifications on a 60sec interval.
