### ISSUE TITLE
CVE request for security advisories

### ISSUE THREAD

**Issue by manuel-sommer** [louislam/uptime-kuma#2802]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

Hi @louislam ,
could you please request a CVE number for both:

https://github.com/louislam/uptime-kuma/security/advisories/GHSA-553g-fcpf-m3wp
https://github.com/louislam/uptime-kuma/security/advisories/GHSA-wh8j-xr66-f296

I don't have the rights to do that.

### 🐻 Uptime-Kuma Version

1.20.0

### 💻 Operating System and Arch

Ubuntu

### 🌐 Browser

Chrome

**Comment by louislam** [comment]
I am not familiar with this process. 

As this xxs issue could be performed by admin only, no other remote users could do this. I think the risk in reality is very low, as there is no admins would put a phishing script on their own status page.

**Comment by manuel-sommer** [comment]
Hi @louislam,
yes, you are right. Still, if an application gets more and more features (e.g. user management) or has another vulnerability, then this could potentially also be injected differently. Thus, XSS issues should always be remediated. 

You can directly request a CVE number here. Github will take care of the rest: https://github.com/louislam/uptime-kuma/security/advisories 

"_Under the repository name, click Security. In the left sidebar, under "Reporting", click Advisories. In the "Security Advisories" list, click the security advisory you'd like to request a CVE identification number for. Use the Publish advisory drop-down menu, and click Request CVE._"
