### ISSUE TITLE
Code Injection Vulnerabilities in kuma

### ISSUE THREAD

**Issue by Thewhiteevil** [louislam/uptime-kuma#2803]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### Description

Hey Kuma team,

I have created code injection vulnerability report in huntr.dev which is found in kuma webapp.

https://huntr.dev/bounties/da381d16-842e-4bc1-9b64-d664e7c0ce3b/

https://huntr.dev/bounties/232d4b4a-710d-40d7-9c5e-57ea26fef269/

These are private reports you need repository level access to validate this report.

It was created 10 days ago, hope you may received notification from the huntr.dev?

Check it and resolve soon.

### 👟 Reproduction steps

xcv

### 👀 Expected behavior

xcv

### 😓 Actual Behavior

cxv

### 🐻 Uptime-Kuma Version

1.19.6

### 💻 Operating System and Arch

vxc

### 🌐 Browser

xvxc

### 🐋 Docker Version

xcv

### 🟩 NodeJS Version

xcvcx

### 📝 Relevant log output

```shell
xcvcxvx
```

**Comment by louislam** [comment]
Please report via GitHub Advisories, it won't login to 3rd party platform with my GitHub email at this moment:
https://github.com/louislam/uptime-kuma/blob/master/SECURITY.md

And make sure it is not duplicate with existing xss issues from previous versions.
https://github.com/louislam/uptime-kuma/security/advisories?state=published

**Comment by CommanderStorm** [comment]
@Thewhiteevil is this resolved?

**Comment by CommanderStorm** [comment]
Closing as not reproducible anymore => resolved
