### ISSUE TITLE
Problem error healthcheck. on k8s  

### ISSUE THREAD

**Issue by PrasinMike** [louislam/uptime-kuma#2805]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

I found error healthcheck    on k8s   
`         livenessProbe:
            exec:
              command:
                - node
                - extra/healthcheck`
this error
<img width="683" alt="image" src="https://user-images.githubusercontent.com/108521875/220087220-ef10e24c-4bdb-4720-8aac-63cdf6646da9.png">

### 🐻 Uptime-Kuma Version

louislam/uptime-kuma:1.20.0

### 💻 Operating System and Arch

-

### 🌐 Browser

-

### 🐋 Docker Version

K8S

**Comment by louislam** [comment]
`extra/healthcheck` is not a javascript file, it is an executable file.

**Comment by PrasinMike** [comment]
> `extra/healthcheck` is not a javascript file, it is an executable file.


1. I can use healthcheck or healthcheck.go    ?
2. What should I change? exec command

`     livenessProbe:
            exec:
              command:
                - node`

**Comment by PrasinMike** [comment]
I fix it command  and use health check  I found error this image
<img width="702" alt="image" src="https://user-images.githubusercontent.com/108521875/220177389-aa506100-4cf6-434a-b3df-b84f6bcdcb1f.png">

**Comment by louislam** [comment]
Are you using `extra/healthcheck`?

PS: `extra/healthcheck.js` is not working in k8s due to the collision of `UPTIME_KUMA_PORT` env vars

**Comment by PrasinMike** [comment]
> Are you using `extra/healthcheck`?

yes I use healthcheck

**Comment by louislam** [comment]
Just realize that I forget to re-compile `extra/healthcheck` it in the latest docker image.

Workaround:
Try to set `UPTIME_KUMA_PORT=3001`

**Comment by PrasinMike** [comment]
> Just realize that I forget to re-compile `extra/healthcheck` it in the latest docker image.
> 
> Workaround: Try to set `UPTIME_KUMA_PORT=3001`

Thanks you this work

**Comment by CommanderStorm** [comment]
@PrasinMike
There don't seem to remain any open issues in this issue, am I correct?
If yes, don't forget to close it.

(Only you or Louis can do so. Otherwise, this will become a zombie that never dies)
