### ISSUE TITLE
Ping a service without revealing the target IP address when service is down 

### ISSUE THREAD

**Issue by yixingchin** [louislam/uptime-kuma#2807]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

I'm looking for a way to mask the IP address (for security concerns) when the monitored service is down. 
Currently for Ping monitoring, the standard output error message sent to my telegram is as such:
`[Service] [🔴 Down] PING HOSTNAME ([10.1.2.3](http://10.1.2.3/)) 56(84) bytes of data.`

I have used hostAliases to map custom hostname to target IP but the IP is still shown together with the custom hostname.

HTTPs monitoring have the same issue of disclosing the FQDN.

Is there any way to mask the IP/FQDN and only show the friendly name of my monitored service?

### 🐻 Uptime-Kuma Version

1.20.1

### 💻 Operating System and Arch

Ubuntu 20.04 x86

### 🌐 Browser

Google Chrome 110.0.5481.104

### 🐋 Docker Version

K8S

**Comment by louislam** [comment]
No straightforward way to do that. You need to write your own program.

Uptime Kuma setup a webhook notification => Your program receive the webhook notification and mask it => Telegram
