### ISSUE TITLE
How to add additional cookies to monitors

### ISSUE THREAD

**Issue by ReneDyhr** [louislam/uptime-kuma#2809]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

At the moment I have a monitor checking our production servers, but they are behind a loadbalancer.
I can force the loadbalancer choosing with a cookie, but I can't find any documentation on this topic, if it's even possible?

### 🐻 Uptime-Kuma Version

1.20.0

### 💻 Operating System and Arch

Ubuntu 22.04

### 🌐 Browser

Google Chrome

**Comment by IDN-YN** [comment]
I am also interested in this feature

**Comment by IDN-YN** [comment]
This is still needed

**Comment by CommanderStorm** [comment]
@ReneDyhr this is being closed as this is a `help` issue and not a `feature-request`. 
Please close this issue and re-open this as a feature reuqest (I can't edit tags, only Louis can)
In addition, please be more specific why adding cookies to which monitor is needed.

For the moment:
Create a proxy (f.ex. nginx) which adds a cookie in a proxy pass
