### ISSUE TITLE
Status Pages - Add Monitors by Tags

### ISSUE THREAD

**Issue by ImperatorTheo** [louislam/uptime-kuma#2810]
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

UI Feature

### 🔖 Feature description

When I add a group to the Status Page, I want to automatically play all monitors with a certain tag.

### ✔️ Solution

My suggestion would be that under the "Add a Monitor" where I can only select individual monitors, an "Add Monitors by Tag" is added where I can then select all my tags including Tag: Value.

**Comment by chris-gibson** [comment]
Just set up uptime kuma and this was immediately something that I wished the status pages had.

**Comment by CommanderStorm** [comment]
@PopcornPanda  a very similar feature has been implemented+merged.
Any version after [`1.22.0-beta.0`](https://github.com/louislam/uptime-kuma/releases/tag/1.22.0-beta.0) supports this.
![image](https://github.com/louislam/uptime-kuma/assets/26258709/2b8673a3-214f-449f-a7fd-675c6dacc8db)
![image](https://github.com/louislam/uptime-kuma/assets/26258709/2a188e08-0774-402e-92e7-c18da04c0026)
![image](https://github.com/louislam/uptime-kuma/assets/26258709/3a19abac-fd44-430b-84e0-8be09d9e6031)

Could you close this Issue if this has been resolved?

**Comment by CommanderStorm** [comment]
@ImperatorTheo I think this a duplice of https://github.com/louislam/uptime-kuma/issues/1726 or https://github.com/louislam/uptime-kuma/issues/651 could you recheck that this is not the case?


A very similar feature has been implemented+merged.
Any version after [`1.22.0-beta.0`](https://github.com/louislam/uptime-kuma/releases/tag/1.22.0-beta.0) supports this.
![image](https://github.com/louislam/uptime-kuma/assets/26258709/2b8673a3-214f-449f-a7fd-675c6dacc8db)
![image](https://github.com/louislam/uptime-kuma/assets/26258709/2a188e08-0774-402e-92e7-c18da04c0026)
![image](https://github.com/louislam/uptime-kuma/assets/26258709/3a19abac-fd44-430b-84e0-8be09d9e6031)

Could you close this Issue if this has been resolved?
