### ISSUE TITLE
MySQL/MariaDB Monitoring Setup

### ISSUE THREAD

**Issue by moneydontbuyclass** [louislam/uptime-kuma#2811]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

I realize that the monitoring feature for DB is new and that it will take some time to get proper documentation. Still, I wondered if anyone got this feature to work with MariaDB in a container on dockers. I use Uptime Kuma for monitoring all my containers, Their TCP ports, and their HTTPs uptime on my domain. I have two containers that use MariaDB, and I would love to monitor them in Kuma. I am struggling to get this to work and would love to see what someone else has done to get this working. Maybe the inputs I enter are incorrect, or I am missing out on a step. Any help would be greatly appreciated. 

### 🐻 Uptime-Kuma Version

1.20.1

### 💻 Operating System and Arch

Debian Raspberry pi OS 64bit 

### 🌐 Browser

Google Chrome

### 🐋 Docker Version

Docker 23.0.1 Build a5ee4b1

**Comment by Computroniks** [comment]
Can you give us an indication of what you have tried already?

**Comment by moneydontbuyclass** [comment]
I created a new monitoring with the monitoring type: MySQL/MariaDB
Then I entered the name: **nextcloud_db**
for the connection string: I used the following syntax. 
**mysql://username:password@host:port/database**
My Nextcloud container is a stack with a MariaDB container as its database. **Nextcloud** runs on **port 8443**, and there is no port for MariaDB. 

Lets say my database username is: **admin**
The password is: **admin123**
The database name and hostname are: **nextcloud_db**

Any suggestions on how I should adequately write this within the correct syntax? I apologize in advance if this question is simple and Im just too much of a noob to realize it.

**Comment by Computroniks** [comment]
Mariadb normally listens on port 3306. You will have to make sure that the firewall on the nextcloud server allows external access to this port. Although do note, opening up firewall ports does increase the attack surface of a machine, especially if weak passwords are used.

**Comment by moneydontbuyclass** [comment]
Yes, Mariadb is listening on port 3306. what I meant to say was I do not have any port mapping on the MariaDB container. The nextcloud stack is working correctly, the nextcloud container is listening to the mariadb container, and the DB is connected. I can try the external port allowance from the nextcloud server to see if that will help. Would my syntax be something like this? I want to confirm I am entering the connection string correctly. 

**mariadb://admin:admin123@nextcloud:3306/nextcloud_db**

**Comment by Computroniks** [comment]
Yeah, that syntax looks about right. I am not sure if the mariadb:// bit will work, but if you just replace that with mysql:// it should (I know you are using mariadb but they are very similar / one a fork of the other)

**Comment by louislam** [comment]
> what I meant to say was I do not have any port mapping on the MariaDB container. 

As your MariaDB is not exposing the port, it is completely normal that Uptime Kuma cannot access your MariaDB.

You have 3 options:

Option 1. 
(Easiest) 
Expose your MariaDB port to the host.

Option 2. 
(Lazy ugly way) 
Also add Uptime Kuma into your nextcloud stack (docker-compose?).

Option 3.
(A bit harder, you need to learn what is docker network) 
Create a new docker network, both MariaDB and Uptime Kuma join this network. Now Uptime Kuma should able to see your MariaDB.

It is easier to create a docker network using Portainer GUI.

If you don't have Portainer, you have to learn these commands.
https://docs.docker.com/engine/reference/commandline/network_create/
