### ISSUE TITLE
Webhook payload querystring for Synology Chat Integration 

### ISSUE THREAD

**Issue by lmacknicki** [louislam/uptime-kuma#2813]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

I am trying to post an automated notification to Synology Chat using the Webhook notification type.  Synology chat expects a payload querystring parameter formatted like this:

<Webhook URL>?payload= {"text": "Uptime Kuma alert: {{check.name}} is {{check.status}}"}

I got that format from asking ChatGPT.  Not sure where it got the "{{check.name}}" format because it doesn't work.  What gets posted to the chat channel on Synology Chat is:

![image](https://user-images.githubusercontent.com/120367192/220473408-6e11200a-a621-413a-b59d-8b1bc49d261b.png)

So the integration is working but the variable names don't get translated by Uptime Kuma.  Again, I don't know where ChatGPT got the syntax, since I can't find an example that uses that syntax.  

So my question is, is there a correct syntax that can be put in the querystring that will translate those variables into the actual values or do I need to put in an enhancement request to either allow that functionality or to add a new Notification Type for Synology Chat? 

Thanks in advance for your help!

### 🐻 Uptime-Kuma Version

1.20.1

### 💻 Operating System and Arch

Ubuntu 20.04

### 🌐 Browser

Firefox 110.0

**Comment by GymNut** [comment]
I have created a docker container to take care of this integration.
https://hub.docker.com/r/timblack/webhookrelay
will be nice once it's fully added natively into uptime-kuma :)

**Comment by Gentsar** [comment]
> ### ⚠️ Please verify that this bug has NOT been raised before.
> * [x]  I checked and didn't find similar issue
> 
> ### 🛡️ Security Policy
> * [x]  I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)
> 
> ### 📝 Describe your problem
> I am trying to post an automated notification to Synology Chat using the Webhook notification type. Synology chat expects a payload querystring parameter formatted like this:
> 
> ?payload= {"text": "Uptime Kuma alert: {{check.name}} is {{check.status}}"}
> 
> I got that format from asking ChatGPT. Not sure where it got the "{{check.name}}" format because it doesn't work. What gets posted to the chat channel on Synology Chat is:
> 
> ![image](https://user-images.githubusercontent.com/120367192/220473408-6e11200a-a621-413a-b59d-8b1bc49d261b.png)
> 
> So the integration is working but the variable names don't get translated by Uptime Kuma. Again, I don't know where ChatGPT got the syntax, since I can't find an example that uses that syntax.
> 
> So my question is, is there a correct syntax that can be put in the querystring that will translate those variables into the actual values or do I need to put in an enhancement request to either allow that functionality or to add a new Notification Type for Synology Chat?
> 
> Thanks in advance for your help!
> 
> ### 🐻 Uptime-Kuma Version
> 1.20.1
> 
> ### 💻 Operating System and Arch
> Ubuntu 20.04
> 
> ### 🌐 Browser
> Firefox 110.0
> 
> ### 🐋 Docker Version
> _No response_
> 
> ### 🟩 NodeJS Version
> _No response_

To correctly format the payload for the Synology Chat webhook notification, you should modify the "Request Body" section in your Uptime Kuma settings as follows:

- Set "Notification Type" to "Webhook."
- In the "Friendly Name" field, you can provide any name you prefer.
- In the "Post URL" field, make sure it follows this format: `https://<DS_IP>/webapi/entry.cgi?api=SYNO.Chat.External&method=incoming&version=2&token=%22<YourToken>%22&`

- For the "Request Body," choose "Custom Body" and set the payload as:

```json
payload={"text": "{{ msg }}"
```

Please note that it's essential to include `&` at the end of the "Post URL" after `%22`.

These settings should ensure that the payload is correctly formatted for Synology Chat. 

1. Uptime Kuma:
![1](https://github.com/louislam/uptime-kuma/assets/47820340/290de40f-7d2d-4401-9279-e94325a46da5)

2. Synology Chat:
![2](https://github.com/louislam/uptime-kuma/assets/47820340/5c917f4d-6f00-4bb7-8c4c-c9c3137a2f98)

**Comment by michelde** [comment]
Just if someone else want to use this cool new notification... Here is one correction.

> ```text
> payload={"text": "{{ msg }}"
> ```

In this line a `}` at the end is missing. So the correct line should be:
```text
payload={"text": "{{ msg }}"}
```

Thanks for getting this working.

**Comment by maxXx1** [comment]
My UptimeKuma says:

`Error: Additional Headrers is not valid JSON` :(

**Comment by CommanderStorm** [comment]
What did you put into the `Additional Headrers` field?

**Comment by maxXx1** [comment]
> What did you put into the `Additional Headrers` field?

`?payload= {"text": "Uptime Kuma alert: {{check.name}} is {{check.status}}"}`

**Comment by CommanderStorm** [comment]
That is supposed to go into the `Request Body`>`Custom Body` field instead according to the post above
