### ISSUE TITLE
Possible memory leaks

### ISSUE THREAD

**Issue by Lanhild** [louislam/uptime-kuma#2820]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### Description

Often more than not, I have to restart my Uptime Kuma because of an exponentially increasing memory usage. Searched through the logs but I haven't found anything relevant. I have about ~60 HTTP monitors.
![image](https://user-images.githubusercontent.com/73610779/220718270-c22cdbc5-7b50-4b98-9d12-5259c477741f.png)

### 👟 Reproduction steps

Have an uptime kuma container on Docker.

### 👀 Expected behavior

No memory leaks

### 😓 Actual Behavior

Huge memory leaks over time.

### 🐻 Uptime-Kuma Version

1.20.1

### 💻 Operating System and Arch

Ubuntu 22.04

### 🌐 Browser

Irrelevant

**Comment by louislam** [comment]
Similar issue: #2344 

It is hard to fix as I cannot reproduce the issue. It will be great if you could provide more info on how to reproduce.

**Comment by Lanhild** [comment]
Seems like using a MongoDB monitor causes a very high memory usage/fluctuations. I had enabled a MongoDB monitor, and that's when the memory usage spikes started. I disabled it and now my memory usage seems to have come back to normal.

**Comment by milindpatel63** [comment]
I am also having a similar issue...
I am running uptime kuma on fly.io free plan...with 1GB disk space and 232MB of memory...it has been running fine for a year, but after the latest update, I had 2 crashes in the past week due to out of memory

![image](https://user-images.githubusercontent.com/11052427/221324447-4bc981a8-ce38-413f-a694-4259f4f7d68e.png)

**Comment by louislam** [comment]
> I am also having a similar issue... I am running uptime kuma on fly.io free plan...with 1GB disk space and 232MB of memory...it has been running fine for a year, but after the latest update, I had 2 crashes in the past week due to out of memory
> 
> ![image](https://user-images.githubusercontent.com/11052427/221324447-4bc981a8-ce38-413f-a694-4259f4f7d68e.png)

Using mongodb too?

**Comment by PeterCxy** [comment]
I have the same issue running uptime kuma on fly.io after updating to 1.20.1, and I am not using the MongoDB monitor. I am only using monitors of type HTTP, PING, DNS, or PUSH.

**Comment by chakflying** [comment]
Interesting that there is mention of a memory leak in MongoDB's [JIRA](https://jira.mongodb.org/browse/NODE-5024) which was fixed in the latest version.

**Comment by louislam** [comment]
> Interesting that there is mention of a memory leak in MongoDB's [JIRA](https://jira.mongodb.org/browse/NODE-5024) which was fixed in the latest version.

Thanks, it should have a quick release for this.

**Comment by PeterCxy** [comment]
But the issue is also present for me **without** using the MongoDB monitor type. Is it triggered regardless of whether the MongoDB driver is actually used?

**Comment by louislam** [comment]
> But the issue is also present for me **without** using the MongoDB monitor type. Is it triggered regardless of whether the MongoDB driver is actually used?

Probably not, would be appreciated if you could find the root cause of your issue.
