### ISSUE TITLE
Best way to Upgrade?

### ISSUE THREAD

**Issue by Mighty33** [louislam/uptime-kuma#2821]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

Hi Support or anyone...  Whats the best way for me to upgrade this to the new version?

-Andrew

### 🐻 Uptime-Kuma Version

previous version

### 💻 Operating System and Arch

Ubuntu 20

### 🌐 Browser

edge, chrome

### 🐋 Docker Version

standalone

**Comment by rezzorix** [comment]
Here is the link to the wiki:
https://github.com/louislam/uptime-kuma/wiki/%F0%9F%86%99-How-to-Update
