### ISSUE TITLE
Lavalink Status Support

### ISSUE THREAD

**Issue by NOXITB** [louislam/uptime-kuma#2822]
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

API, New Monitor, UI Feature, Other

### 🔖 Feature description

The abaility to check wither a lavalink server is up and running 

### ✔️ Solution

The abaility to check wither a lavalink server is up and running 

### ❓ Alternatives

i have tried to make my own but it does not work

**Comment by CommanderStorm** [comment]
Going by their API, you can just call [`GET /version`](https://lavalink.dev/api/rest#get-lavalink-version) or other equivalent endpoints.
No change in Uptime Kuma is necessary.

=> closing as resolved
