### ISSUE TITLE
Docker monitoring ping n/a

### ISSUE THREAD

**Issue by hugomickael** [louislam/uptime-kuma#2826]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

Hi, is it normal that when using docker host connected directly to the socket, the ping always shows n/a? Thanks.

### 🐻 Uptime-Kuma Version

1.20.1

### 💻 Operating System and Arch

Ubuntu 22.03 LTS, Docker

### 🌐 Browser

Chrome

### 🐋 Docker Version

23.0.1

**Comment by hugomickael** [comment]
hum ok, so maybe it is an issue. What can I do to try to solve it?

**Comment by chakflying** [comment]
There is no response time metric provided by the docker API.

**Comment by hugomickael** [comment]
So, I must use a ping monitor type for that?

**Comment by chakflying** [comment]
Ping might not work depending on your docker networking setup. But in general most other monitor types provide a response time and you can try and see which one fits your needs.

**Comment by hugomickael** [comment]
ok thanks for the help.
