### ISSUE TITLE
Help with maintenance window 

### ISSUE THREAD

**Issue by adm2k** [louislam/uptime-kuma#2828]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

I am trying to define a daily maintenance window to begin at 8pm and end at 5am daily. I am unable to leave the Effective Date Range empty during Save. If I try to put in a start and end date it also adds a time which does not work. What am I doing wrong? Is a beginning and ending date required? If so, how do I enter dates without a time being inserted?

See picture attached.

![image](https://user-images.githubusercontent.com/120423301/220899243-51da5cb5-6f8e-4cbe-835d-62fa11b040f8.png)

Many thanks!

### 🐻 Uptime-Kuma Version

1.19.6

### 💻 Operating System and Arch

Ubuntu 22.04 server

### 🌐 Browser

Version 110.0.5481.112 (Official Build) (64-bit)

**Comment by adm2k** [comment]
And how do I enter that date range? It attempts to put time in  there as well and I already a time window defined.

![image](https://user-images.githubusercontent.com/120423301/220917299-e8f6bd46-6d43-42ce-bf8f-fa590e8f2eed.png)

**Comment by adm2k** [comment]
I apologize if I do not understand. I looked at the image and don't understand. All I am trying to do is this:

Enable maintenance mode from 20:00 to 05:00 daily regardless of date

**Comment by chakflying** [comment]
Meaning the time in the "Effective Date Range" does not matter as long as you set it large enough to cover the age of the universe.

**Comment by louislam** [comment]
No, for `Effective Date Range`, you haven't set a end date. As I said before, set it from 2023 to 2028, like this:

![image](https://user-images.githubusercontent.com/1336778/221000839-5ea6ee80-6c6a-4cf1-b741-0d4190ac089d.png)
