### ISSUE TITLE
hi want to link back to login page from status page is it possible 

### ISSUE THREAD

**Issue by regchanuk** [louislam/uptime-kuma#2829]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

hi all
is there a way to create a short cut link to the dashboard on the status page if landing page is status page is it possible to create a link to the login page /dashboard but making it discreate

### 🐻 Uptime-Kuma Version

latest  will give details on request

### 💻 Operating System and Arch

synologynas linux

### 🌐 Browser

Chrome

### 🐋 Docker Version

unknown

### 🟩 NodeJS Version

cant tell

**Comment by chakflying** [comment]
See discussion in #544.

**Comment by regchanuk** [comment]
<a href="https://uptime.your domain.com">Service page</a>
