### ISSUE TITLE
Monitor-Type GameDig and Badges

### ISSUE THREAD

**Issue by Maximilian1021** [louislam/uptime-kuma#2833]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### Description

I have selected Game-Dig as the monitor type. But no games are shown in the next drop down menu! See screenshot.
![grafik](https://user-images.githubusercontent.com/13157092/221109212-c2bfef40-3496-4309-844f-9ff5e05caa74.png)

Then I tried to create a badage for a monitor (Ping) which is accessible. But it only gives me N/A.
![grafik](https://user-images.githubusercontent.com/13157092/221109343-27edb0da-cdf5-49cd-8c81-80f8c5afbf52.png)

I have installed the latest version. (see screenshot)
![grafik](https://user-images.githubusercontent.com/13157092/221109486-6640e88b-b571-4dba-960a-4985146a1455.png)

### 👟 Reproduction steps

**Game-Dig**
Wähle als Monitor-Type Game-Dig
Klicke auf das nächste Drop-Down Menü

**badge**
Verwende das badge bei einem Server welcher über den Port überwachtung 
Rufe die API Seite für das Badge auf

### 👀 Expected behavior

What happened I can not say. Only that it does not work for me!

### 😓 Actual Behavior

What happened I can not say. Only that it does not work for me!

### 🐻 Uptime-Kuma Version

1.20.1

### 💻 Operating System and Arch

Ubuntu 20.04.5 LTS \n \l

### 🌐 Browser

Firefox V110

### 🐋 Docker Version

Docker version 20.10.12, build 20.10.12-0ubuntu2~20.04.1

### 🟩 NodeJS Version

-/-

**Comment by chakflying** [comment]
Posting your container logs would be helpful.

**Comment by louislam** [comment]
The issue has been fixed by @chakflying

Workaround at this moment: Refresh the page, the list should be shown now.
