### ISSUE TITLE
Full List of Supported Notifications

### ISSUE THREAD

**Issue by louislam** [louislam/uptime-kuma#284]
Just for someone who have never heard of Apprise. Thanks to Apprise, Uptime Kuma is supporting so many notification services!

Please check the list before asking for enhancement.

**Built-in:**

- Telegram
- Webhook (Only for developer who know how to handle http post request)
- SMTP
- Discord
- Signal
- Gotify 
- Slack
- Rocket.chat
- Pushover
- Pushy
- Octopush
- LunaSea
- Pushbullet
- Line Messenger
- Mattermost
- Apprise (Docker built-in, need to install apprise if you installed Uptime Kuma without Docker)

**Via Apprise (Docker built-in) (2021-08-28)**

1. AWS SNS :calling:
3. Boxcar
4. ClickSend :calling:
5. DingTalk :calling:
6. Discord :books:
7. D7 Networks :calling:
8. E-Mail :books:
9. Emby
10. Enigma2 Devices
11. Faast
12. FCM - (Google) Firebase Cloud Messaging
13. Flock
14. Gitter
15. Google Chat
16. Gotify
17. Growl
18. Home Assistant
19. IFTTT
20. Join
21. Kavenegar :calling:
22. KODI
23. Kumulos
24. LaMetric Time/Clock
25. Mailgun :books:
26. Matrix
27. Mattermost
28. MessageBird :calling:
29. Microsoft Teams
30. MSG91 :calling:
31. Nexmo :calling:
32. Nextcloud
33. Notica
34. Notifico
35. Office 365
36. OneSignal
37. Opsgenie
38. Parse Platform
39. Popcorn Notify
40. Prowl
41. PushBullet :books:
42. Pushed
43. Pushjet
44. Pushover :books:
45. PushSafer :books:
46. Reddit
47. Rocket.Chat
48. Ryver
49. SendGrid
50. SimplePush
51. Sinch
52. Slack :books:
53. SMTP2Go :books:
54. SparkPost :books:
55. Spontit
56. Syslog
57. Techulus Push
58. Telegram :books:
59. Twilio :calling:
60. Twist
61. Twitter
62. XBMC
63. XMPP
64. Webex Teams
65. Zulip
67. Custom Notification Services
    - JSON
    - XML
70. Desktop Notification Services
    - Linux Notifications:
         - Gnome
         - Qt
         - DBus
    - MacOS X Notifications
    - Windows Notifications

Source: https://github.com/caronc/apprise/wiki

**Comment by tgxn** [comment]
Could we flesh out the wiki a bit to have information like this?

**Comment by louislam** [comment]
> Could we flesh out the wiki a bit to have information like this; or a .md part of `docs/` perhaps?
> 
> Edit:
> I created [this document](https://github.com/louislam/uptime-kuma/wiki/Notification-Methods), but we should add the Apprise list _(I can't copy the markdown from your comment)_

Using h2 as a list is a bit weired, I removed all h2 and just keep the link there.

And I dont want to maintain two lists in the future, I perfer to just keep one list here.

**Comment by sam7oo** [comment]
When I try to monitor an IPV6 IP not able to monitor, please help me out

**Comment by louislam** [comment]
> When I try to monitor an IPV6 IP not able to monitor, please help me out

Please create a post with more details via this link:
https://github.com/louislam/uptime-kuma/issues/new?assignees=&labels=help&template=ask-for-help.md&title=

**Comment by armandofcom** [comment]
Add multiple alert providers, such as Slack and PagerDuty, and with configurable thresholds and descriptions.
You can take a look at the project https://github.com/TwiN/gatus
and get feedback from several of the proven providers

**Comment by thomas-mc-work** [comment]
I'd vote for putting either the list or the direct link into the docs. Then this ticket can also be unpinned.

**Comment by HolgerHuo** [comment]
Hi! What about adding support for using using custom Telegram Backend (https://core.telegram.org/bots/api#using-a-local-bot-api-server )? Should this be handled by apprise or use the inbuilt notification method?

**Comment by Computroniks** [comment]
A note for those using Office 365 as an SMTP server. From the 1st of October 2022, Microsoft have announced that they are going to start disabling basic authentication on all Office 365 mail servers. As a result, users will no longer be able to use the SMTP notification type as this only supports basic authentication. Instead they should use the [Office 365](https://github.com/caronc/apprise/wiki/Notify_office365) notification provider from Apprise

**Comment by Christoph-Wagner** [comment]
XMPP should be removed from the supported list, the comments make it sound as if it never properly worked, and recently it has been completely removed from apprise: https://github.com/caronc/apprise/pull/619

**Comment by louislam** [comment]
Close as this list has been updated for a while.

Please refer to https://github.com/louislam/uptime-kuma/tree/master/server/notification-providers

**Comment by lwertugrul** [comment]
Hello, will an alert be added to the system for xmpp?
