### ISSUE TITLE
Check if DNS record matches a specified one

### ISSUE THREAD

**Issue by gggxbbb** [louislam/uptime-kuma#2844]
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

New Monitor

### 🔖 Feature description

You should a new type of monitor that not only monitor the DNS record but also check if the DNS record matches a specified one.

### ✔️ Solution

In some cases, I need to make sure that the DNS record matches a specified one and get alarm when it becomes mismatched.

### 📝 Additional Context

 I know this might be a request that seems to be abnormal, but it happens sometimes that one of my friends' domain has been set to some unexpected records accidently. So it might be helpful for some people.

**Comment by istenrot** [comment]
This would be a neat feature for monitoring DNS blacklists. Was this feature implemented already?

**Comment by tamal-sen** [comment]
Please consider adding this feature. We'd love to use it to monitor DNS A record changes.

**Comment by CommanderStorm** [comment]
@tamal-sen 
Please see the screenshots from https://github.com/louislam/uptime-kuma/pull/5048
