### ISSUE TITLE
Option to add custom data to webhook body.

### ISSUE THREAD

**Issue by zimbres** [louislam/uptime-kuma#2845]
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

Other

### 🔖 Feature description

A box like "Additional Headers" to add data to webhook body.

### ✔️ Solution

Customize the webhook body, so the server that will be called can receive additional data.

**Comment by william-aqn** [comment]
This is a really needed addition.

+ It would also be great to change the request type "GET/POST/PUT/PATCH/DELETE/..."

**Comment by d19dotca** [comment]
Yes, this would be fantastic. Specifically in my case I'm looking to use webhooks with the Instatus webhook which requires a certain body: https://instatus.com/help/monitoring/custom-service-webhook

**Comment by CommanderStorm** [comment]
@zimbres 
I think this was resolved by https://github.com/louislam/uptime-kuma/pull/3088 which was merged into the upcoming [`1.23` release](https://github.com/louislam/uptime-kuma/milestone/34)
=> Could you close this issue?
