### ISSUE TITLE
Multi Theft Auto Not working at GameDig.

### ISSUE THREAD

**Issue by djalmasi** [louislam/uptime-kuma#2849]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

At first I thought there was a problem with the server I was running,but I tried to add other servers as well. I cannot add any MTA server. I always get the same failed to 1 attempt error. 
![image](https://user-images.githubusercontent.com/46577572/221451922-d8e13763-65ae-4866-bd25-3419f3fec3a2.png)

### 🐻 Uptime-Kuma Version

1.20.2

### 💻 Operating System and Arch

Debian GNU/Linux 10 

### 🌐 Browser

Brave v1.48.171 

### 🐋 Docker Version

version 23.0.0, build e92dd87

**Comment by louislam** [comment]
Just tested it is not working in my side too. I think you should report to gamedig's repo.
https://github.com/gamedig/node-gamedig/issues

**Comment by djalmasi** [comment]
Update: The monitor works, the documentation is misleading. The monitor requires the server list port (more precisely 22126) and works with it. When you try to add it, 22003 is entered by default. (I think because many websites/systems use this by default).
