### ISSUE TITLE
Incorrectly Connected Response Time Graph

### ISSUE THREAD

**Issue by quexten** [louislam/uptime-kuma#285]
**Is it a duplicate question?**
I haven't found this in the issues.

**Describe the bug**
The response time graph connects points in the wrong order, leading to a weird overlap.

**To Reproduce**
I'm not sure what happened to reproduce this, but the incorrectly connected graph starts when I turned off uptime kuma for a while.

**Expected behavior**
The graph should be connected in the correct order.

**Info**
- Uptime Kuma Version: 1.3.2
- Using Docker: Yes
- OS: Linux
- Browser: Google Chrome

**Screenshots**
[https://i.imgur.com/dExShzf.png](https://i.imgur.com/dExShzf.png)

**Error Log**
Not relevant.

**Comment by chakflying** [comment]
Will investigate when I have time, I have seen it once or twice, but nothing in my code should affect how the dots connect chronologically, so it might be a chart.js bug.

**Comment by CommanderStorm** [comment]
@quexten could you close this issue? It seems that https://github.com/louislam/uptime-kuma/issues/843 is a better description of the underlying issue

**Comment by quexten** [comment]
I don't know whether it's actually the same bug as I have multiple overlaps (visible on the right on the screenshot) which doesn't speak for a time zone issue. Regardless, I haven't encountered the bug again in the last 2 years so I'm closing for now.
