### ISSUE TITLE
Badge not working

### ISSUE THREAD

**Issue by RedBoardDev** [louislam/uptime-kuma#2850]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

Hello !
I wanted to use badge on github to see if my service is up or down. But actually I've an error icon, and when I click on the image, I can see this error: Error Fetching Resource
Here my repository test: [https://github.com/RedBoardDev/test-repository](url)
I use docker compose, and I'm always at the latest update for every thing.
I don't know where is the problem

### 🐻 Uptime-Kuma Version

latest

### 💻 Operating System and Arch

Raspbian lite

### 🌐 Browser

Chrome

### 🐋 Docker Version

Docker version 20.10.22, build 3a2c30b

### 🟩 NodeJS Version

v19.3.0

**Comment by chakflying** [comment]
You might have configured your nginx proxy to somehow block CORS access.

**Comment by RedBoardDev** [comment]
> You might have configured your nginx proxy to somehow block CORS access.

I've configure my nginx proxy like that:
`server {
  listen 443 ssl http2;
  # Remove '#' in the next line to enable IPv6
  # listen [::]:443 ssl http2;
  server_name uptime.redboard.fr;
  ssl_certificate /etc/letsencrypt/live/uptime.redboard.fr/cert.pem;
  ssl_certificate_key /etc/letsencrypt/live/uptime.redboard.fr/privkey.pem;

  location / {
    add_header Cache-Control no-store;
    proxy_set_header   X-Real-IP $remote_addr;
    proxy_set_header   X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header   Host $host;
    proxy_pass         http://localhost:3001/;
    proxy_http_version 1.1;
    proxy_set_header   Upgrade $http_upgrade;
    proxy_set_header   Connection "upgrade";
  }
}
`

**Comment by louislam** [comment]
> https://uptime.redboard.fr/api/badge/3/status?v2

![](https://uptime.redboard.fr/api/badge/3/status?v2)

**Comment by RedBoardDev** [comment]
@louislam Nop, it's not good :(
look https://github.com/RedBoardDev/test-repository
I've try with this on the readme:
```<img src="https://uptime.redboard.fr/api/badge/3/status?v2" />```
![image](https://user-images.githubusercontent.com/66514178/221895142-c72b6a5d-7f2c-4b6a-afd3-74f1c8a58ac9.png)

**Comment by louislam** [comment]
> https://status.kuma.pet/api/badge/63/status

<img src="https://status.kuma.pet/api/badge/63/status" />

**Comment by RedBoardDev** [comment]
> > https://status.kuma.pet/api/badge/63/status
> 
> ![](https://camo.githubusercontent.com/8d32de9adce2d823c6a9e01645ac78e887896b2f93252ea7268d811e22055c4d/68747470733a2f2f7374617475732e6b756d612e7065742f6170692f62616467652f36332f737461747573)

Your work but not mine..
https://github.com/RedBoardDev/test-repository/blob/main/README.md

**Comment by RedBoardDev** [comment]
mmh yes, how can I resolve that ? Do you have some idea what can I check/try to solve that ?

**Comment by louislam** [comment]
Test again with [icon.png](https://uptime.redboard.fr/icon.png)

![](https://uptime.redboard.fr/icon.png)

**Comment by RedBoardDev** [comment]
nop... I think it's my configuration or idk
