### ISSUE TITLE
Non-Docker Upgrade from 1.20.1 to 1.20.2 Problem

### ISSUE THREAD

**Issue by cybero2912** [louislam/uptime-kuma#2853]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

Hello,
I tried to upgrade from 1.20.1 to 1.20.2 following the wiki article for the Non-Docker Upgrade but failed

`cd <uptime-kuma-directory>

# Update from git
git fetch --all
git checkout 1.20.2 --force

# Install dependencies and prebuilt
npm install --production
npm run download-dist

# Restart
pm2 restart uptime-kuma`

### 🐻 Uptime-Kuma Version

1.20.1

### 💻 Operating System and Arch

Ubuntu 22.04.2 LTS

### 🌐 Browser

FF

### 🐋 Docker Version

NA

### 🟩 NodeJS Version

14.21.3

**Comment by louislam** [comment]
Error message?

**Comment by cybero2912** [comment]
seems there was a permission problem running 
'sudo npm install --production'
after entering 'sudo su' before and running 'npm install --production' at a root prompt upgrade finished successfully

but now I see under about:
Frontend Version do not match backend version!
