### ISSUE TITLE
Certificate Expiration does not display on custom ports

### ISSUE THREAD

**Issue by crouthamela** [louislam/uptime-kuma#2854]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### Description

When monitoring an HTTPS URL, the Certificate Expiration countdown does not display if a custom port was specified in the URL. For example, monitoring https://myurl.com:4433 will not show the expiration date on the monitor page, but https://myurl.com will.

### 👟 Reproduction steps

1. Create an HTTP(s) Monitor Type
2. Enter a URL with a custom port at the end (https://myurl.com:4433)
3. Check Certificate Expiry Notification

### 👀 Expected behavior

Certificate Expiration date would display on the monitor page.

### 😓 Actual Behavior

Certificate Expiration date does not display on the monitor page.

### 🐻 Uptime-Kuma Version

1.20.2

### 💻 Operating System and Arch

Debian 11

### 🌐 Browser

Google Chrome 110.0.5481.105

**Comment by crouthamela** [comment]
Interesting. I'm having the issue with port 4433.

**Comment by CommanderStorm** [comment]
Closing as `cannot-reproduce`

**Comment by CommanderStorm** [comment]
A likely duplicate issue was triaged in https://github.com/louislam/uptime-kuma/issues/3551 and #4281 was proposed and will be reviewed in one of the upcoming releases.
