### ISSUE TITLE
Any way to exclude certain redirect URL or headers?

### ISSUE THREAD

**Issue by amberflag48** [louislam/uptime-kuma#2862]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

Hello all,

I have nginx setup on my other services with an error_page parameter to redirect to my status page in case the service is not available. 

This works flawlessly, except that Uptime-Kuma does not realise the service is done because of that, since the last redirect status code is 200.

The way around that I found is to disable redirect and use the full URLs of my services, but it's not very practical since it's hard to maintain.

Is there any other way to accomplish what I'm trying to do here?

Thanks!

### 🐻 Uptime-Kuma Version

1.20.2

### 💻 Operating System and Arch

Debian 11

### 🌐 Browser

N/A

### 🐋 Docker Version

23.0.1

**Comment by rezzorix** [comment]
In http(s) monitors you have the option to set the maximum number of redirects. This is set to 10 by default. Change it to 0 and you should be fine.

**Comment by amberflag48** [comment]
> In http(s) monitors you have the option to set the maximum number of redirects. This is set to 10 by default. Change it to 0 and you should be fine. 

As mentioned in the post, this is what I already do, but it's not practical since I need the complete URL of the app and update it everytime it changes. Eg: Emby will redirect you to the login page, so I need to use the complete URL with redirect set to 0.

I was looking at another solution, but if there's none I'd stick to that.

**Comment by rezzorix** [comment]
Ah I understood that you have the nginx setup that way, not uptime kuma. 

But if thats not the case, how about then changing the status codes that nginx posts upon redirect?

**Comment by amberflag48** [comment]
> Ah I understood that you have the nginx setup that way, not uptime kuma. 
> 
> But if thats not the case, how about then changing the status codes that nginx posts upon redirect?
> 
> 

Yeah sorry my post was not very clear. 

To my understanding, there is no way to change the status code nginx uses unless I use a PHP script in front of my uptime-kuma page.

What it does is it uses the error_page parameter in nginx to redirect to uptime kuma on specific error code.

Once it reaches uptime Kuma, it gives me a 200 status code, because the uptime Kuma page is found and exists.

**Comment by chakflying** [comment]
Using the keyword monitor to check for something static in your actual page would probably be an easier solution.
