### ISSUE TITLE
SSL Error?

### ISSUE THREAD

**Issue by GammaPotato** [louislam/uptime-kuma#2872]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### Description

keep getting this error. After that everything goes on as normal. after 2 to 3 hours he comes back

write EPROTO 140343779805120:error:14094438:SSL routines:ssl3_read_bytes:tlsv1 alert internal error:../deps/openssl/openssl/ssl/record/rec_layer_s3.c:1558:SSL alert number 80

Sorry cant 

### 👟 Reproduction steps

comes during a check whether the service is online

### 👀 Expected behavior

idk?

### 😓 Actual Behavior

idk?

### 🐻 Uptime-Kuma Version

1.20.2

### 💻 Operating System and Arch

Ubuntu docker Server by ionos

### 🌐 Browser

Version 110.0.5481.178

**Comment by hafx** [comment]
Hi, 

I have the same issue on with my raspberry using docker (Uptimekuma Version: 1.21.0)

Any idea how to fix that ?

**Comment by coderunway** [comment]
write EPROTO 139739003946944:error:14094438:SSL routines:ssl3_read_bytes:tlsv1 alert internal error:../deps/openssl/openssl/ssl/record/rec_layer_s3.c:1565:SSL alert number 80

I have the same issue running with the latest tag docker container. My VM is Debian
 `Linux debian-dev 5.10.0-21-amd64 #1 SMP Debian 5.10.162-1 (2023-01-21) x86_64 GNU/Linux
`

**Comment by Miggets7** [comment]
Having the same issue in a docker swarm environment. The SSL error occurs randomly. The server it's checking against is Caddy Server. Not sure if I can provide more info?

**Comment by Deathproof76** [comment]
same here on docker

**Comment by d-vorobyov** [comment]
same here

**Comment by CommanderStorm** [comment]
@d-vorobyov 

Please open another issue witha all the context.
Currently, I could not replicate this issue.
Can you provide us a [Minimal, Reproducible Example](https://stackoverflow.com/help/minimal-reproducible-example)?

**Comment by alexander-potemkin** [comment]
Same here. nginx -> Node.JS process in Docker. Randomly occurs, don't know how to reproduce.

**Comment by CommanderStorm** [comment]
@alexander-potemkin 

See the message above:

> Please open another issue witha all the context.
Currently, I could not replicate this issue.
Can you provide us a [Minimal, Reproducible Example](https://stackoverflow.com/help/minimal-reproducible-example)?

**Comment by alexander-potemkin** [comment]
@CommanderStorm , I've noticed it. That's why added that I don't know how to reproduce. It's happening sporadically, when nothing changes.
Thought it make sense to leave a note here - please, correct me if I'm wrong.

**Comment by alexander-potemkin** [comment]
In my case it turned out that a DNS rotation was an issue: the host had two entries, one of which was incorrect, so SSL error was caused by an attempt to connect to the wrong server.
Hope that will be of help.

**Comment by wreidlinger** [comment]
Thanks @alexander-potemkin for the hint. Also in my case it turned out that it was an DNS issue.
I used DNS names which are existing on my local DNS server. But at the same time I also have DNS name which resolev to public IP addresses with the same DNS names. The **uptime-kuma** docker runs on the LAN. So if the **uptime-kuma** resolves the local DNS addresses it works without a problem.... but when **uptime-kuma** resolves the public DNS addresses it would gets this SSL Error.
FYI, I use such a setup to be able to have Lets Encrypt Certificates run without browser errors for internal services.

This was the error:
```[<friendly name>] [DOWN] write EPROTO 00A8B797C17F0000:error:0A000438:SSL routines:ssl3_read_bytes:tlsv1 alert internal error:../deps/openssl/openssl/ssl/record/rec_layer_s3.c:1586:SSL alert number 80```

I was able to fix this DNS resolve issue with *hard-coded* IP / DNS entries inside my `docker-compose.yaml` file.
```bash
---
version: '3.3'
services:
  uptime-kuma:
    image: louislam/uptime-kuma:latest
    container_name: uptime-kuma
    volumes:
      - data:/app/data
    ports:
      - 127.0.0.1:3001:3001
    environment:
     - TZ=Europe/Vienna
    restart: always
    dns:
      - 10.0.0.20
      - 10.0.0.1
      - 8.8.8.8
      - 4.4.4.4
    extra_hosts:
      - "host1.publicdomain.org:10.0.0.10"
      - "host2.publicdomain.org:10.0.0.11"
      - "host3.publicdomain.org:10.0.0.12"
      - "host4.publicdomain.org:10.0.0.13"
volumes:
    data:
```
