### ISSUE TITLE
Add support for XML body to HTTP Monitor

### ISSUE THREAD

**Issue by pysiak** [louislam/uptime-kuma#2875]
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

Other

### 🔖 Feature description

You should add support for XML as body type, not just json.

### ✔️ Solution

I can send JSONs, but when I paste a SOAP XML it fails. In my use case I need to be able to monitor a SOAP webservice which are XML and uptime kuma fails because it expects JSON.

**Comment by chakflying** [comment]
Implemented in #2610.

**Comment by pysiak** [comment]
Nice, thanks, didn't see that
