### ISSUE TITLE
There is no monitoring

### ISSUE THREAD

**Issue by yanXiaoi** [louislam/uptime-kuma#2879]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### Description

![image](https://user-images.githubusercontent.com/120445129/222665724-0c751776-5584-4541-ab98-01aa66f2ed13.png)
When it has been running normally for a while, it does not check the item and no data appears
![image](https://user-images.githubusercontent.com/120445129/222666041-048834d2-c0d3-4c7b-82ba-cf3f644c25e5.png)
And it is normal in the state
![image](https://user-images.githubusercontent.com/120445129/222666900-6ef142ca-375e-4454-9e06-0143e451a2b0.png)
As shown in the picture, it stopped checking on the 27th
![image](https://user-images.githubusercontent.com/120445129/222667828-0fd1ac51-c353-4623-9a47-cc2d18e73476.png)

### 👟 Reproduction steps

A large number of monitoring cases, occasionally stopping one or two monitoring

### 👀 Expected behavior

Normal monitoring

### 😓 Actual Behavior

There is no monitoring

### 🐻 Uptime-Kuma Version

1.19.6

### 💻 Operating System and Arch

Centos 7.9

### 🌐 Browser

Edge 110.0.1587.41

**Comment by chenshaoju** [comment]
Sorry for my English.

I have the same issue with specific monitoring items.

here is a screen recording of this issue:

https://github.com/louislam/uptime-kuma/assets/515763/911b8dbc-3c2b-4245-85ee-237bad4df6b7

here are uptime-kuma logs from docker:
[_uptime-kuma_logs.txt](https://github.com/louislam/uptime-kuma/files/12328900/_uptime-kuma_logs.txt)

This issue may have the same at: https://github.com/louislam/uptime-kuma/issues/736

If need any more information, please don't hesitate to ask.👏

**Comment by CommanderStorm** [comment]
@yanXiaoi @chenshaoju 
How many monitors do you have, what type are they, and what storage are you running on?
Could you try [`1.23.0-beta.1`](https://github.com/louislam/uptime-kuma/releases/tag/1.23.0-beta.1)?
A few performance/stability fixes (https://github.com/louislam/uptime-kuma/pull/2800 https://github.com/louislam/uptime-kuma/pull/3380 https://github.com/louislam/uptime-kuma/pull/3174) have gone into this release making higher numbers of monitors more feasible, more are planned for the [`v2.0`-release](https://github.com/louislam/uptime-kuma/pull/2720).

**Comment by chenshaoju** [comment]
Thanks for the reply, I have 53 items running.

I try using the beta version, but I don't know how to upgrade in docker, I'm a docker noob, sorry. :/

I can be waiting for the 1.23.0 to release and upgrade in docker later.

If this issue is fixed, I will update the post. 👏

**Comment by chenshaoju** [comment]
@CommanderStorm After update to 1.23.0, this issue looks has been fixed.

Thanks! 🍻

![image](https://github.com/louislam/uptime-kuma/assets/515763/69aab85b-9a09-4e88-9958-bf2eacb812bf)

**Comment by medram** [comment]
Having the same issue.

**Comment by CommanderStorm** [comment]
@medram there currently is not enough content in this issue to debug on

Large deployments (think above 300-400 monitors, less if using more demanding monitors like "real browser") are not supported in the v1 of uptime kuma.

The upcoming v2 release does include a number of performance updates, which should™️ resolve a bunch of perfomance issue with large deployments.
See https://github.com/louislam/uptime-kuma/milestone/24 for the progress

**Comment by chakflying** [comment]
Fixed by #3952.
