### ISSUE TITLE
IPv6 Not working

### ISSUE THREAD

**Issue by DedBash** [louislam/uptime-kuma#2883]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### Description

I know there are similar bugs but I can't get it to ping IPv6 but I noticed that not even the demo page can do it at the moment.
![Screenshot 2023-03-03 234020](https://user-images.githubusercontent.com/79027536/222845242-3d9a934c-5e80-4cc1-a4c4-f2368026b8bf.png)
![Screenshot 2023-03-03 234149](https://user-images.githubusercontent.com/79027536/222845309-8ad511a0-f20f-4a6c-b8de-a2dcadd1d69c.png)
My docker container also has an IPv6 and it doesn't even seem to be in beta anymore.
![Screenshot 2023-03-03 234515](https://user-images.githubusercontent.com/79027536/222846065-1ae25b44-f23e-414d-8124-2771d25a89ba.png)

### 👟 Reproduction steps

create your own instance or use the demo from https://demo.uptime.kuma.pet/

### 👀 Expected behavior

Ping a IPv6

### 😓 Actual Behavior

Timout

### 🐻 Uptime-Kuma Version

1.20.2

### 💻 Operating System and Arch

Debian GNU/Linux 11 (bullseye) x86_64

### 🌐 Browser

Happens everywhere

### 🐋 Docker Version

Docker version 20.10.5+dfsg1, build 55c4c88

**Comment by DedBash** [comment]
beta = demo version

**Comment by louislam** [comment]
Maybe due to: https://github.com/louislam/uptime-kuma/pull/2223

**Comment by louislam** [comment]
7ec09d01185bbf35ff9fa2543167376aa0f2d44b Should be fixed.

**Comment by Astry-l** [comment]
hi ,i got the same problem,how to solved?  

my uptime kunma version is 1.21.2
