### ISSUE TITLE
Change DNS Server for Uptime Kuma

### ISSUE THREAD

**Issue by XHyperDEVX** [louislam/uptime-kuma#2893]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

Hello, I have seen that some users here would like to have a DNS function. The possibility to set DNS servers for the monitors.

I really need this feature, so I would like to ask how far you plan to implement this feature, if and when.

The feature is that you can set a DNS server for Uptime Kuma or each individual monitor to check if a website is also accessible from other networks or, as in my case, I want to stop the flood of calls in my PiHole which is running on the same system. To do this, I would have to get Uptime Kuma to make the calls via a different DNS server than the one specified by the Linux system.

I [and probably many other users] would be happy to see this feature in the next update. :)

### 🐻 Uptime-Kuma Version

1.20.2

### 💻 Operating System and Arch

Debian 11

### 🌐 Browser

Microsoft Edge

### 🐋 Docker Version

-

### 🟩 NodeJS Version

v18.14.2

**Comment by sargonas** [comment]
You can do this in your docker compose file actually. You can configure custom DNS servers for a docker container by using the `dns:` entry under `services:`.

Example:
```
version: 2
  services:
    dns:
      - 1.1.1.1
      - 8.8.8.8
```

**Comment by XHyperDEVX** [comment]
That is the problem. I don't use Docker. Is there another way for non-Docker?

**Comment by sargonas** [comment]
Ooooh yeah that will be an issue then. Sadly DNS is typically managed at the OS level so I don't really have an alternative suggestion.

**Comment by XHyperDEVX** [comment]
That's a real shame. Then I'll have to find another way, I thought it would be easier. But simple would be too easy
