### ISSUE TITLE
server/util-server.js: [Down] PING 1.1.1.1 (1.1.1.1): 56 data bytes

### ISSUE THREAD

**Issue by wonderfulShrineMaidenOfParadise** [louislam/uptime-kuma#2895]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### Description

Ping will fail if the system uses busybox version of  `ping`.

### 👟 Reproduction steps

1. Use a distro using busybox by default.
2. Or remove `iputils`
3. Add a ping monitor

### 👀 Expected behavior

It pings without root permission or `iputils`?

### 😓 Actual Behavior

[Down] PING 1.1.1.1 (1.1.1.1): 56 data bytes

### 🐻 Uptime-Kuma Version

1.20.2

### 💻 Operating System and Arch

Alpine 3.17 armv7

### 🌐 Browser

-

### 🟩 NodeJS Version

18.14.2

### 📝 Relevant log output

```shell
sudo -u uptime-kuma busybox ping 1.1.1.1
PING 1.1.1.1 (1.1.1.1): 56 data bytes
ping: permission denied (are you root?)
```
```

**Comment by louislam** [comment]
See https://serverfault.com/questions/1001174/cant-ping-permission-denied

**Comment by wonderfulShrineMaidenOfParadise** [comment]
Should we add some docs about this or expand the error message? I don't think it's easy to figure out what actually happens without more clues than `[Down] PING 1.1.1.1 (1.1.1.1): 56 data bytes`

**Comment by wonderfulShrineMaidenOfParadise** [comment]
Especially when `ping: permission denied (are you root?)` is not visible in logs or the web ui.
