### ISSUE TITLE
Don't Resolve Language

### ISSUE THREAD

**Issue by BlackYuzia** [louislam/uptime-kuma#2897]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

Hi there.
Suppose browsers have a few formats to display language.
I have next languages inside `navigator`
![image](https://user-images.githubusercontent.com/25010528/223643707-63c30837-9420-4cf8-815f-901ed6337a91.png)

Suppose, `uk` that's `Ukraine`.
In code we only check full code:
https://github.com/louislam/uptime-kuma/blob/2dedc1cfbd2eab61ebcc5793ee4a949532d19405/src/i18n.js#L59-L62 

You check `Ukraine` language by `uk-UA` by that reason I always get `en` language instead.
https://github.com/louislam/uptime-kuma/blob/2dedc1cfbd2eab61ebcc5793ee4a949532d19405/src/i18n.js#L39
You also could check a few languages (by check `navigator.languages` after / instead of `navigator.language`)

Should we change a bit this check to partial compare instead of full compare or add select language?

### 🐻 Uptime-Kuma Version

1.20.0

### 💻 Operating System and Arch

Ubuntu 20.04

### 🌐 Browser

Google Chrome 110.0.5481.178

### 🟩 NodeJS Version

18.x.x

**Comment by louislam** [comment]
Yes, I think it is better to use `navigator.languages`.

It seems that `uk-UA` cannot match anyway, it is good to rename it to `uk`?

**Comment by BlackYuzia** [comment]
> It seems that uk-UA cannot match anyway, it is good to rename it to uk?

Don't sure. But you could use both of them? What if that depends on browser and some of them set `uk` some `uk-UA`. Then we get the same result.
