### ISSUE TITLE
[Feature Request] Service Grouping

### ISSUE THREAD

**Issue by lenaxia** [louislam/uptime-kuma#29]
Requesting having service grouping. Something simple but that can provide visual separation between different groups of services, Examples include "Infrastructure", "Media", "Storage", "External".

Suggestion is to base this off of tags. A single "Group" tag can be assigned to each service which will determine how it is displayed and what other services are displayed with it. Tags/Groups should be orderable. Services should be broadly orderable, and the order they show up in the larger list, should be how they show up within a group. 

Another implementation would be enabling a "Add a new group" on the main page, which creates a group in the service list on the left, and enable drag and drop to move things around.

**Comment by LeviSnoot** [comment]
Agreed, I suggested this in #21 but your explanation is a bit clearer than mine.

**Comment by louislam** [comment]
dup with #12
