### ISSUE TITLE
⚠️ Friendly Reminder for Oracle Cloud free tier users, check if Uptime Kuma is still running

### ISSUE THREAD

**Issue by louislam** [louislam/uptime-kuma#2901]
One of my Uptime Kuma (arm64) testing instance hosted on Oracle Cloud was just turned off by them recently, due to their new idle policy.

Oracle Cloud free tier is no longer a good option to host Uptime Kuma in my opinion. You should move away eventually. 

https://docs.oracle.com/en-us/iaas/Content/FreeTier/freetier_topic-Always_Free_Resources.htm#compute__idleinstances

**Comment by xwsdgsdgs** [comment]
I AM USING REPLIT ITS GOOD

**Comment by fate8383** [comment]
I have got the same email and changed to PAYG, still free and I got to keep my instance. Your system is idle is not true basically, they are just forcing all to move to PAYG. I am heavily using it and it is not idle ever.

**Comment by louislam** [comment]
Yes, I agree. Mine instances also got several containers running too.

For my experience of GCP/AWS/Azure, the bandwidth cost in payg model is unpredictable. Not sure how is Oracle Cloud though.

**Comment by fate8383** [comment]
> Yes, I agree. Mine instances also got several containers running too.
> 
> 
> 
> For my experience of GCP/AWS/Azure, the bandwidth cost in payg model is unpredictable. Not sure how is Oracle Cloud though.

It is clear in their statement whatever is free in the free tier will remain free in PAYG. So I took their word :) but I still set up some budget cost alerts in their OCI cost
Management section for like $1 to let me know if I ever get there.

**Comment by rezzorix** [comment]
So... running more software to be above the 10% rule would prevent an instance to be seen as "idle"?

**Comment by rezzorix** [comment]
Just bringing this here to the game would help? https://linux.die.net/man/1/stress

**Comment by rezzorix** [comment]
Now I was a bit curious and was looking a bit more into it; the below applies for instances with 2 CPUs.
Adjust for more CPUs or different timings.

1. on Linux install `stress`

2. create a script which runs `stress` with 1 cpu at full 100% for a random time up to 5 minutes.
`sudo stress -c 1 -t $(( RANDOM % 300 ))`

Make sure the script is executable.

3. set a cronjob for runs this script randomly within the first 50 minutes of every hour:
`0 * * * * sleep $(( RANDOM \% 3000 )); /path/to/script.sh`

With this more or less random pattern of random CPU usage throughout the day it should surpass the required "[CPU utilization for the 95th percentile is less than 10%](https://pitstop.manageengine.com/portal/en/kb/articles/95th-percentile)" over 7 days.

Am I am right with all this?
Anyone else can / wants to do the exact maths on it and improve my humble approach above? :wink:

**Comment by Windows200000** [comment]
> I have got the same email and changed to PAYG, still free and I got to keep my instance. Your system is idle is not true basically, they are just forcing all to move to PAYG. I am heavily using it and it is not idle ever.

Would be lovely if they didn't have issues with not accepting credit cards. Also, all of [these](https://docs.oracle.com/en-us/iaas/Content/FreeTier/freetier_topic-Always_Free_Resources.htm) have to be satisfied, so you might have just not used enough bandwidth or similar.

**Comment by matthewharrington** [comment]
Just a comment for anyone wanting add some load to their free Oracle instance:

I installed stress-ng:

`dnf install stress-ng`

and then set up stress-ng to run periodically:

`sudo crontab -e`

Cron:
*/10 * * * * stress-ng --matrix 0 -t 1m

and then saved the crontab.

Cheers, Matt.

**Comment by rezzorix** [comment]
> Just a comment for anyone wanting add some load to their free Oracle instance:
> 
> I installed stress-ng:
> 
> `dnf install stress-ng`
> 
> and then set up stress-ng to run periodically:
> 
> `sudo crontab -e`
> 
> Cron: */10 * * * * stress-ng --matrix 0 -t 1m
> 
> and then saved the crontab.
> 
> Cheers, Matt.

That doesnt work because idle is considered when "[CPU utilization for the 95th percentile is less than 20%](https://docs.oracle.com/en-us/iaas/Content/FreeTier/freetier_topic-Always_Free_Resources.htm#compute__idleinstances)".

So unless stress-ng does that go with a random approach as posted by me earlier.
