### ISSUE TITLE
Dropdown List in MonitorList

### ISSUE THREAD

**Issue by Chronos093** [louislam/uptime-kuma#2909]
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

UI Feature

### 🔖 Feature description

I'm using Kuma to monitor my servers, and I noticed that as I add items to monitor the MonitorList starts to get polluted.
It wouldn't be interesting to put a drop-down list in the MonitorList, for example, separated by the first tag.

### ✔️ Solution

I believe that performing a separation by tag, considering the first tag and making it clear in the settings that the first tag would be used for the drop-down list.

**Comment by CommanderStorm** [comment]
@Chronos093 
I think this got resolved in `1.23.0`
![image](https://github.com/louislam/uptime-kuma/assets/26258709/9e030112-3f42-4e3c-a987-407d036d47f9)

If this is not resolved, could you add screenshots what you are refering to?
