### ISSUE TITLE
JWT Authentication

### ISSUE THREAD

**Issue by kemalunel** [louislam/uptime-kuma#2912]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

Hello Everyone,
I'm looking for an authentication with JWT. How can I provide that to get token then use the APIs to monitor that.
Thanks.

### 🐻 Uptime-Kuma Version

1.20.2

### 💻 Operating System and Arch

Ubuntu 20.04 LTS

### 🌐 Browser

Google Chrome

### 🟩 NodeJS Version

16

**Comment by luckman212** [comment]
https://github.com/louislam/uptime-kuma/issues/2095
