### ISSUE TITLE
The UTC time of the alarm notification is formatted as the local time

### ISSUE THREAD

**Issue by 919927181** [louislam/uptime-kuma#2914]
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

Other

### 🔖 Feature description

The UTC time of the alarm notification is formatted as the local time。

### ✔️ Solution

The UTC time of the alarm notification is formatted as the local time

### ❓ Alternatives

  Now we can only modify the notification template
  /**
     * Convert UTC to LocalDate
     * Use: For example ${heartbeatJSON["time"]} Modify to ${this.UTCToLocalDate(heartbeatJSON["time"])}
     * @param {dateTimeStr} Utc time in string format. For example  2023-03-10 03:04:35.876
     * @returns {newDateTimeStr} localDateTime in string format
     */
	UTCToLocalDate(dateTimeStr) {
        if (dateTimeStr.indexOf('T') == -1) {
            dateTimeStr = dateTimeStr.replace(' ', 'T');
            dateTimeStr += 'Z'
        }
        const dateTime = new Date(dateTimeStr);
        const newDateStr = dateTime.getFullYear() + '-' + this.addZero(dateTime.getMonth() + 1) + '-' + this.addZero(dateTime.getDate());
        const newTimeStr = dateTime.getHours() + ':' + this.addZero(dateTime.getMinutes()) + ':' + this.addZero(dateTime.getSeconds());
        const newDateTimeStr = newDateStr + ' ' + newTimeStr;
        return newDateTimeStr;
    }
    /**
     * month or date zero fill 
     */
    addZero(val) {
        if (val < 10) {
            val = '0' + val;
        }
        return val;
    }

**Comment by chakflying** [comment]
This should be closed with #3203.

**Comment by CommanderStorm** [comment]
A bit clearer message:

@919927181 
Could you close this issue? (only you or Louis can do so)
This feature has been released in the `1.22`-Release and is currently available.

**Comment by 919927181** [comment]
thank
