### ISSUE TITLE
Run script on service failure

### ISSUE THREAD

**Issue by Fernando-Checa** [louislam/uptime-kuma#2918]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

Is it possible ro run a script or ssh command on service failure?

I want to monitor my router because sometines it hangs and can't send notifications.
But I could run a script to reboot it.

Thanks in advance

### 🐻 Uptime-Kuma Version

1.20.2

### 💻 Operating System and Arch

ubuntu 21.04

### 🌐 Browser

Brave

**Comment by danielthedifficult** [comment]
Came here looking for this exact feature :)

**Comment by louislam** [comment]
You can use Webhook Notification + Writing a simple Node.js/Python http server to do that.

**Comment by william-aqn** [comment]
Idea! Need add curl executor with command line format
Example - need send PUT/DELETE/GET request into my endpoint with specific body and headers

**Comment by yomono** [comment]
The issue it's a little bit old but just use https://github.com/adnanh/webhook/, it's exactly what you're asking for
Good luck!

**Comment by mfide** [comment]
Any update here? I need to execute a python script when failure a detected.

**Comment by CommanderStorm** [comment]
There are a number of solutions mentioned above.
From Writing a simple Node.js/Python http server to something like https://github.com/adnanh/webhook/

This feature falls under the same category as the following security wise
- #1117 

I am unsure if this would be a good idea, in any case I don't want to deal with the security flaws.
