### ISSUE TITLE
monitor server load and cpu/ram/disk usage 

### ISSUE THREAD

**Issue by tcpzix** [louislam/uptime-kuma#2921]
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

New Monitor

### 🔖 Feature description

it will be amazing if we can monitor server load and resource with kuma! :)

### ✔️ Solution

monitor disk cpu ram server load

**Comment by cal97g** [comment]
This would be great.

**Comment by Prajwal433** [comment]
please do it requesting

**Comment by kokofixcomputers** [comment]
That would be great.

**Comment by jondycz** [comment]
This is the only reason I haven't switched yet

**Comment by kokofixcomputers** [comment]
> This is the only reason I haven't switched yet

What is the reason?

**Comment by CommanderStorm** [comment]
@tcpzix 
Is this a duplicate of #819?

**Comment by tcpzix** [comment]
yes you right this is a duplicate of #819 and i'm sorry about that
thanks

**Comment by CommanderStorm** [comment]
@tcpzix could you close this issue then? ^^

**Comment by tcpzix** [comment]
Yes, it's done.
