### ISSUE TITLE
Slow to add/remove hosts

### ISSUE THREAD

**Issue by franciscopaniskaseker** [louislam/uptime-kuma#2922]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

Server parameters:

- 4 vcpus (hetzner vps, that is very fast besides shared)
- 4gb of ram (3gb free)
- 121 active hosts
- server load is 0.5
- 50% of one cpu is being used by kuma nodejs (basically the reason of 0.5 load value)
- 0.0 of WA
- we are using the official docker setup
- we tested with last stable version and now with last beta version.

To add a host, when I click in save, it takes  almost 10 seconds to save. Same thing for delete.

In the same server we have zabbix monitoring setup and zabbix has no performance issues (with local storage or external resources).

We are observing that for a months, but it's getting worse.

1. Is some kind of nodejs limitation?
2. or maybe the database is very fragmented?
3. any suggestions to troubleshoot that?

thank you for your time and, by the way, one more time: congratulations for this excellent open source solution!

### 🐻 Uptime-Kuma Version

1.21.0-beta.1 or last stable

### 💻 Operating System and Arch

ubuntu 20.04 x64

### 🌐 Browser

chrome last stable version

### 🐋 Docker Version

23.0.1-1

### 🟩 NodeJS Version

v16.19.1

**Comment by chakflying** [comment]
Maybe you can help testing this PR: #2800
Tell us the types of monitors used would also be helpful to debug possible issues with a monitor type.

**Comment by franciscopaniskaseker** [comment]
I will test.

WA is the mount of time that the CPU is spending waiting for I/O operations to complete. If the value is too high, means that the I/O operations are too low to finish or th I/O demand is too high for the system.

Usually the WA value goes high when storage is being too low to read or write, mainly write.

**Comment by franciscopaniskaseker** [comment]
@chakflying by the way, how do you recommend to test this in my docker image?

**Comment by chakflying** [comment]
https://github.com/louislam/uptime-kuma/wiki/Test-Pull-Requests

This should help.
