### ISSUE TITLE
Different notifications for monitor states.

### ISSUE THREAD

**Issue by Schwoby** [louislam/uptime-kuma#2925]
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

New Notification, Other

### 🔖 Feature description

ability to select different notifications based on monitor status changes.

basically, if the monitor/service is changed to DOWN, send notification1 and if the if the monitor/service is changed to UP, send notification2.

### ✔️ Solution

i would like there to be a notification potion for each of the different monitor states, or at the very least the UP and DOWN states. beside each of these state options, the current notification options exist. in this way, notification1 (such as an 'urgent' notice that could wake people up) can be used for the monitor when it goes DOWN and notification2 (such as an 'all clear' notice that would not wake people up) can be used for the monitor when it changes into the UP state.

### ❓ Alternatives

keep the urgent notice as the only notice. after receiving the notice, enable maintenance on the affected monitor, fix the issue(s) that triggered the notice, wait for a monitoring cycle after the fix was finished and disable maintenance.

issue1: this method requires additional steps (and time) to be taken and can give the appearance of a false-positive if the steps for maintenance are missed.

issue2: there are times that notification cannot reach their destination to alert for DOWN, but the issue is able to resolve itself, and then the urgent notice gets sent for the UP status, this gives a false-positive as he monitor no longer needing an urgent level of care.

### 📝 Additional Context

Uptime Kuma is an absolutely great product. this project has reduced manual logging and checking down to miniscule levels. keep up the great work, one and all!

**Comment by ameador1** [comment]
Exactly - I want the same thing. UK can already let you select multiple Notifications. If the Notifications had a Status attribute for Up or Down - then the setting for sound played and such could be set accordingly and only the proper Notification (based on Status) would be sent. As is it - if it goes up or down - I get the obnoxious notification I need so I WILL get the notice when systems are down - I don't want this same sound and volume used when the system comes back up. I am using Pushover, and this COULD work great with this feature being added.

**Comment by CommanderStorm** [comment]
@Schwoby 
We are consolidating duplicate issues a bit to make issue management easier.
I think, we should track this issue in https://github.com/louislam/uptime-kuma/issues/1233 as this can be implemented by the mechanism proposed there
⇒ I am going to close this as a duplicate.
