### ISSUE TITLE
Not able to setup the SMTP connection from Gmail. Getting connection timeout. How to find the log path for any failure

### ISSUE THREAD

**Issue by sureshkumar-skc** [louislam/uptime-kuma#2928]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

I'm setting up the SMTP Email notification for the locally hosted server, and I am getting connection timeout whereas with the same credentials it is working on the hosted server 

### 🐻 Uptime-Kuma Version

1.20.2

### 💻 Operating System and Arch

Ubuntu

### 🌐 Browser

Chrome

**Comment by drewlsvern** [comment]
@sureshkumar-skc Are you running in docker? 

If you are you can view the logs like this `docker logs <replace-with-container-name-here>`
