### ISSUE TITLE
Have a global setting for notifications

### ISSUE THREAD

**Issue by IronicBadger** [louislam/uptime-kuma#293]
An env var to select a default enabled notification (by name or some other identifier) please.

![image](https://user-images.githubusercontent.com/2773080/131382267-ec60b626-eb8c-4811-97cd-f82f7319c838.png)

Having to select this per notification is tedious. Thanks!!

**Comment by Saibamen** [comment]
Merged PR: https://github.com/louislam/uptime-kuma/pull/340
You can check it in current `master` branch
