### ISSUE TITLE
How to extract Logs

### ISSUE THREAD

**Issue by Kbvz** [louislam/uptime-kuma#2930]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

Hello,

I use uptime kuma but i don't know how to extract logs. i had notifications but i want logs in basic form. perhaps txt file ? I can copy and paste since web interface. 
i think theses logs are stored somewhere but i don't know where ;)

thks for help

### 🐻 Uptime-Kuma Version

1.19.6

### 💻 Operating System and Arch

**

### 🌐 Browser

firefox

### 🐋 Docker Version

***

### 🟩 NodeJS Version

**

**Comment by drewlsvern** [comment]
@Kbvz From a brief look at the logging code in `src/util.ts` it appears it just logs to the console which just writes to std out.

Are you running in a docker?

**Comment by Kbvz** [comment]
Hello, Yes in docker. I wrote docker log ls yesterday (or same) ans i saw logs but i cant export 

Cordialement,
Stéphane/kbvz  
 
  Le jeu., mars 16, 2023 à 5:33, Joel ***@***.***> a écrit:   


@Kbvz From a brief look at the logging code in src/util.ts it appears it just logs to the console which just writes to std out.

Are you running in a docker?

**Comment by drewlsvern** [comment]
@Kbvz You can just send anything from docker logs command to a file like this:
`docker logs <name-of-container> > myLogOutput.txt`

**Comment by Kbvz** [comment]
i tried docker container ls 
docker logs [containerid] 
docker logs [containerid]  >>file.txt
docker logs [containerid]  1> file.txt

and dont have logs in file..

**Comment by drewlsvern** [comment]
@Kbvz So when you run the docker logs command with the container id do you see any log out?

**Comment by CommanderStorm** [comment]
> i tried 
> docker logs [containerid]
> docker logs [containerid] >>file.txt
> docker logs [containerid] 1> file.txt
> 
> and dont have logs in file..

You want just one `>` for piping input in linux. Piping is actually [more powerfull than this](https://linuxhint.com/linux-pipe-command-examples/) if you are curious.

For examle
![image](https://github.com/louislam/uptime-kuma/assets/26258709/499d9183-14d4-4cef-bb55-6d45b2ab146d)
