### ISSUE TITLE
How to update

### ISSUE THREAD

**Issue by nafeasonto** [louislam/uptime-kuma#2936]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

I read the instructions on how to update, but I am getting errors it already exists. I am pretty new to Linux so can someone tell me step by step please?

Version: 1.20.2

### 🐻 Uptime-Kuma Version

Version: 1.20.2

### 💻 Operating System and Arch

Debian 11

### 🌐 Browser

Chrome

**Comment by adm2k** [comment]
Maybe this will help:

https://github.com/louislam/uptime-kuma/wiki/%F0%9F%86%99-How-to-Update

**Comment by rezzorix** [comment]
> Maybe this will help:
> 
> https://github.com/louislam/uptime-kuma/wiki/%F0%9F%86%99-How-to-Update

@adm2k @nafeasonto wrote that he read the instructions but still getting errors:

> I read the instructions on how to update, but I am getting errors it already exists. I am pretty new to Linux so can someone tell me step by step please?
> 

@nafeasonto can you be more precise on the error message?
Can you explain which steps you followed exactly?
