### ISSUE TITLE
Weird response time spikes

### ISSUE THREAD

**Issue by Nuklon** [louislam/uptime-kuma#2937]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### Description

My monitors all have the same odd response time spikes at 2520 ms:
![image](https://user-images.githubusercontent.com/23340481/225708590-ae50778e-f481-46cb-878b-bea34291184e.png)
![image](https://user-images.githubusercontent.com/23340481/225708686-48c46f12-e60e-45fc-9be1-1ad7ba3583a8.png)

They're not happening at the same time, but they are happening for each monitor. It's almost always 2520/2521ms. I've checked the sites at times it's happening and they are responding OK, both from OS as Docker.

### 👟 Reproduction steps

Add HTTPS monitor

### 👀 Expected behavior

No spikes

### 😓 Actual Behavior

Spikes

### 🐻 Uptime-Kuma Version

1.20.2

### 💻 Operating System and Arch

Ubuntu 22.04.2 LTS

### 🌐 Browser

Firefox

### 🐋 Docker Version

23.0.1, build a5ee5b1

### 📝 Relevant log output

```shell
There's nothing in the logs that's relevant I think.
```

**Comment by chakflying** [comment]
This is probably something specific to your environment. The thread could be locked up doing something for a determined time.

**Comment by louislam** [comment]
https://github.com/louislam/uptime-kuma/blob/61506b1af23061efe30c9d687f50d71f197de7e6/server/model/monitor.js#L356

I checked the code, it is calculated by `endTime - startTime` and there is no code for sleeping 2500ms in between.

I think it is your network or the server issues, but really hard to tell. For example, it could be your DNS rate limit, slow down your dns query on purpose.

**Comment by Nuklon** [comment]
I thought it was DNS as well so I tried to enable the DNS cache option in Kuma, but that didn't do anything 🤔. The servers I'm monitoring are all working, I checked from within Docker as Ubuntu.

**Comment by Nuklon** [comment]
It's a largely idle server that's of course not connected to Wi-Fi. However, I've been trying out some different DNS servers and it seems more stable with 1.1.1.1. I'll close it for now. Will reopen if needed.
