### ISSUE TITLE
Support Plausible and other Analytics Platforms

### ISSUE THREAD

**Issue by johnmarksilly** [louislam/uptime-kuma#2938]
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

UI Feature, Other

### 🔖 Feature description

Add the ability to add an arbitrary script tag to track analytics using alternate providers.

Plausible analytics uses the following script tag to initialize it's analytics:
<script defer="defer" data-domain="domain.com" src="https://anaytics.domain.com/js/plausible.js"></script>

### ✔️ Solution

In my use-case, I use the self-hosted privacy oriented Plausible analytics instead of Google.

It would be nice to add it. I'll create a PR if I have time this weekend.

**Comment by BluDood** [comment]
I would also love this to be a feature

**Comment by RapidCompiler** [comment]
I did an exec into the uptime kuma docker container and stumbled upon an index.html file. I tried inserting this plausible snippet in the header of that file, but it doesn't seem to work. I also tried changing the title of the web page, which didn't work. So I'm unsure as to how to implement this. Can anyone help?

I did an exec into my homer dashboard container and inserted this snippet in the header of the main HTML file. This seemed to work just fine for homer, and the analytics are coming up on my plausible dashboard. I tried using this same technique for uptime kuma, but didn't work.

**Comment by chakflying** [comment]
Did you try to restart the container after modifying?

**Comment by CommanderStorm** [comment]
@johnmarksilly 
We are consolidating duplicate issues a bit to make issue management easier.
I think, we should track this issue in https://github.com/louislam/uptime-kuma/issues/2818 as there is no functional difference that I can see ^^
=> I am going to close this as a duplicate

**Comment by CommanderStorm** [comment]
The follwing PR is avaliable, but needs testing if this works properly with plausible
- https://github.com/louislam/uptime-kuma/pull/5608/

here is how to test PRs:
https://github.com/louislam/uptime-kuma/wiki/Test-Pull-Requests
