### ISSUE TITLE
Custom subjects not replacing {{code}} with actual content

### ISSUE THREAD

**Issue by douglerner** [louislam/uptime-kuma#2941]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### Description

In email notifications, for a custom subject, {{NAME}} works but everything else like {{URL}} is literally sending the text {{URL}} instead of the actual value.

### 👟 Reproduction steps

1. I set a custom header for a notification. 
2. I then tested the notification and looked at the resulting email.
3. I also saved the notification and triggered it by flipping the monitor to cause it to send a notification.
4. I also tried various combinations of of custom items, but only {{NAME}} of the monitor came through.

### 👀 Expected behavior

I expected to see {{URL}} and other items replaced by their actual value.

### 😓 Actual Behavior

{{URL}} and others appear literally rather than with their values.

### 🐻 Uptime-Kuma Version

1.20.02

### 💻 Operating System and Arch

It's running on PikaPods - whatever they are using

### 🌐 Browser

Google Chrome 109.0.5414.87 (Official Build) (arm64)

**Comment by 401U** [comment]
I have just tested, the only thing doesn't work is {{URL}}

with custom subject set to `1.{{NAME}}2.{{HOSTNAME_OR_URL}}3.{{URL}}:4.{{STATUS}}:`, I got `1.Test2.testing.hostname3.{{URL}}4.⚠️ Test` as the real subject.

Yes the {{URL}} is not working, and the reason is that `{{URL}}` has been removed in [Server Side](https://github.com/louislam/uptime-kuma/blob/61506b1af23061efe30c9d687f50d71f197de7e6/server/notification-providers/smtp.js) and still remaining in [Client Side](https://github.com/louislam/uptime-kuma/blob/61506b1af23061efe30c9d687f50d71f197de7e6/src/components/notifications/SMTP.vue#L99)

**Comment by douglerner** [comment]
I wonder how the monitoring can be used if there isn’t way of conveying the URL being checked. The body of the email can’t be customized either, right?Doug Sent from my iPhone   On Mar 19, 2023, at 21:06, 401Unauthorized ***@***.***> wrote:﻿
I have just tested, the only thing doesn't work is {{URL}}
with custom subject set to 1.{{NAME}}2.{{HOSTNAME_OR_URL}}3.{{URL}}:4.{{STATUS}}:, I got 1.Test2.testing.hostname3.{{URL}}4.⚠️ Test as the real subject.
Yes the {{URL}} is not working, and the reason is that {{URL}} has been removed in Server Side and still remaining in Client Side

**Comment by 401U** [comment]
> I wonder how the monitoring can be used if there isn’t way of conveying the URL being checked. The body of the email can’t be customized either, right?

Just use {{HOSTNAME_OR_URL}} in your custom email subject, it works for me.

**Comment by douglerner** [comment]
I tested with {{HOSTNAME_OR_URL}} and that works. But there don't seems to be variables for keywords being checked - or even if it is a keyword check. Is there no way to get that in kuma alerts?

**Comment by 401U** [comment]
> I tested with {{HOSTNAME_OR_URL}} and that works. But there don't seems to be variables for keywords being checked - or even if it is a keyword check. Is there no way to get that in kuma alerts?

You mean check your custom subject, e.g. when you try to use `{{URL}}` or something invalid it will tell you it's invalid?

**Comment by douglerner** [comment]
I was just asking, while we were here, if there was something that can be added to mention that the alert was about a failed keyword check. I didn't see that in the variables. But as suggested I opened a question/help issue on that. https://github.com/louislam/uptime-kuma/issues/2948 Thanks.
