### ISSUE TITLE
Customizing the body of email notifications (or at least providing more info by default)

### ISSUE THREAD

**Issue by douglerner** [louislam/uptime-kuma#2942]
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

New Notification

### 🔖 Feature description

The body of a notification reports that a site being monitored is down, or restored to up. But it doesn't give any details about the site such as the URL that was checked and possibly any keywords that were being looked for.

It would be nice if we could customize the body of notifications to include things like that. Or at least include some basic useful info in the body so we can click on the URLs in received notification and see what the results are.

### ✔️ Solution

If I get a notification from a monitor, it's about a site. A URL was checked. I would like to be able to click on the URL so I can see the result. It will also help me locate the server in question so I can fix the problem.

### ❓ Alternatives

I couldn't think of any alternative solutions.

**Comment by Mighty33** [comment]
I would love this... I would love to have a way to add the link to web status page in the body of email.

**Comment by CommanderStorm** [comment]
@Mighty33 
Please refrain from posting `+1` / requests for updates things on issues, as this makes issue-management harder.
[We use 👍🏻 on issues to prioritise work](https://github.com/louislam/uptime-kuma/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).

**Comment by bbarman4u** [comment]
I would like to see this feature as well. Looks like today MS Teams notification has this information, so would make sense for other notification targets like SMTP email in this case can use it.
