### ISSUE TITLE
Docker swarm services & labels for selector

### ISSUE THREAD

**Issue by ralphschuler** [louislam/uptime-kuma#2945]
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

New Monitor

### 🔖 Feature description

Additionally to the containers i would like to monitor swarm services.

And then to change the Selector (Container id) to container or service labels.

### ✔️ Solution

Instead of using the Container ID the check would use labels either attached to a container or a service.

### 📝 Additional Context

Im honestly not sure what i should add to it.

its "quite simple".

I looked into it and could maybe be able to implement it myself.
the question is how to start so i dont messup everything.

**Comment by Chirishman** [comment]
> likely depends on #957 Related #882

Not actually dependent on anything else. If you point at a management node's IP it will answer about the service availability for the whole swarm.

See this workaround: https://github.com/louislam/uptime-kuma/issues/3069#issuecomment-1712935178

**Comment by CommanderStorm** [comment]
I think this is better tracked in https://github.com/louislam/uptime-kuma/issues/4233, as docker-compose and docker swarm are likely not as different.
=> merging these issuses via closing this one as a duplicate.

> [!TIP]
> If you have a look at the dependency linked in https://github.com/louislam/uptime-kuma/issues/957, `@BigBoot` has shared https://github.com/BigBoot/AutoKuma, which claims to solve this usecase.
**We have not tested if it works as advertised, nor audited said software.**
