### ISSUE TITLE
Is there a way for an alert email to mention that the check was for a keyword?

### ISSUE THREAD

**Issue by douglerner** [louislam/uptime-kuma#2948]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

In an email alert I can return {{HOSTNAME_OR_URL}} to tell me what site was checked. But some sites are not just checks of whether they can be reached. That's why there is a keyword setting.

That's useful because some checks may be of an API. Or reaching a status page that indicates whether the site is in proper synch.

With Uptime Robot alerts like that will give the URL in the body and say "keyword not found."

Is there a way for Uptime Kuma to report, in email alerts, that the check was for a keyword (and maybe what the keyword was)?

Otherwise with multiple monitors it's hard to tell in alerts what the check was for.

### 🐻 Uptime-Kuma Version

1.20.2

### 💻 Operating System and Arch

Whatever PikaPods is running on

### 🌐 Browser

Google Chrome

**Comment by 401U** [comment]
Currently, it only say `keyworld is not in ...`. Not able to see the real keyworld now.

example email notification with default subject as bellow:
![Y0320_113221](https://user-images.githubusercontent.com/52659312/226240478-aac03702-58c1-465f-8cc4-d06fa33fee2f.png)

You can keep this issue open as a feature request, maybe oneday someone would impl it.

**Comment by douglerner** [comment]
That's interesting. Even if the real keyword is not shown that's no worse than Uptime Robot which also just says keyword not found. In your example, is that the default notification? If you customize it so you can include {{HOSTNAME_OR_URL}} (so you know which site was checked) how would that fit in?

Thanks.
