### ISSUE TITLE
how to generate  report and status Pages

### ISSUE THREAD

**Issue by JatenJ** [louislam/uptime-kuma#2950]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

1. How can i generate report from Dashboard if available with excl or any format.
 2. How to create view only user.  we can setup status page but i cant find quick status up, Down, Maintenance, unknown and pause 

### 🐻 Uptime-Kuma Version

1.19.6

### 💻 Operating System and Arch

redhat 

### 🌐 Browser

Firefox 

### 🟩 NodeJS Version

14

**Comment by rezzorix** [comment]
1. to work with the data outside of uptime kuma you need additional software like e.g. Prometheus
https://github.com/louislam/uptime-kuma/wiki/Prometheus-Integration

2. at this moment you cannot. you can however create status pages that are “view only”
