### ISSUE TITLE
Monitor API Requests

### ISSUE THREAD

**Issue by tigaszzz** [louislam/uptime-kuma#2951]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

Hi,

is it possible to monitor a external API  not just its uptime on its endpoint but also simulate a request so it can retrieve real data ? 
 If so, how those it handles sessions with access tokens and multiple request?

regards

### 🐻 Uptime-Kuma Version

1.21

### 💻 Operating System and Arch

Ubuntu 20.

### 🌐 Browser

Chorme latest

### 🐋 Docker Version

no 

### 🟩 NodeJS Version

19.4.0

**Comment by louislam** [comment]
Duplicate of #118
