### ISSUE TITLE
Unclear documentation

### ISSUE THREAD

**Issue by VNRARA** [louislam/uptime-kuma#2957]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

"Note: whilst basic authentication will continue to work after you update, you will be unable to use basic authentication as soon as you add your first API key. After you have added your first API key, basic authentication for endpoints will be permanently disabled."

So if I want to go back to normal auth, I'd have to delete the whole docker instance and start over?

### 🐻 Uptime-Kuma Version

latest

### 💻 Operating System and Arch

docker

### 🌐 Browser

*

**Comment by chakflying** [comment]
Disabled basic auth. is stored as a setting in the database, and there is no process to reset this flag (unless you manually edit the database). Which means you need to delete the database and start over.

**Comment by Computroniks** [comment]
Yes, as soon as you add your first API key, basic authentication will be permanently disabled. If you really want to reenable it (not recommended, it is a bad idea to use normal user credentials for API access, especially if the credentials are stored in a file), you can manually edit the database using and sqlite editor to remove the key in the settings table.
