### ISSUE TITLE
Copy button doesn't work

### ISSUE THREAD

**Issue by VNRARA** [louislam/uptime-kuma#2958]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### Description

Copy button doesn't work when creating API keys. 

### 👟 Reproduction steps

Create copy, press copy button

### 👀 Expected behavior

copy key

### 😓 Actual Behavior

no copy

### 🐻 Uptime-Kuma Version

1.21.1

### 💻 Operating System and Arch

DSM 7.1 (Docker)

### 🌐 Browser

Version 111.0.5563.65 (Official Build) (64-bit)

**Comment by chakflying** [comment]
Reproduced this. Here is the summary:

|  | HTTP | HTTPS |
|--|------|-------|
|localhost|working|not tested|
non-localhost|not working|working|

Both the development build and release build, and firefox / edge the failure case exist.
There is too much magic in `CopyableInput` and I don't really want to figure out what's going on 😅

**Comment by louislam** [comment]
Weird, I re-checked the code, it is basically getting a monitor data from server and fill in the data.

https://github.com/louislam/uptime-kuma/pull/2489/files

**Comment by chakflying** [comment]
I think according to [this StackOverflow](https://stackoverflow.com/questions/48122221/working-copy-to-clipboard-function-doesnt-work-when-called-in-bootstrap-modal) being in a modal triggers some enhanced security from the browser. I think since our `CopyableInput` is an actual textfield, we can just use the existing one instead of creating a hidden one.

**Comment by louislam** [comment]
> I think according to [this StackOverflow](https://stackoverflow.com/questions/48122221/working-copy-to-clipboard-function-doesnt-work-when-called-in-bootstrap-modal) being in a modal triggers some enhanced security from the browser. Since our `CopyableInput` is an actual textfield, maybe we can just use the existing one instead of creating a hidden input to copy from.

It is only working with textarea, so I move the hidden textarea to the same level instead of creating in the top level of document.
