### ISSUE TITLE
Alert repeats despite repeat being 0

### ISSUE THREAD

**Issue by TheLastProject** [louislam/uptime-kuma#2959]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### Description

When setting "Resend Notification if Down X times consecutively (Resend disabled)" to 0, Uptime Kuma still sends multiple notifications.

Here is a screenshot of 2 monitors both having resend set to 0 (it was resent every 30 minutes):

![image](https://user-images.githubusercontent.com/1885159/226737803-dc353b19-be67-4c9c-905d-e599518e224c.png)

![image](https://user-images.githubusercontent.com/1885159/226730449-67f9b4cc-92a7-4d38-b7a9-c77edfb9efa2.png)

### 👟 Reproduction steps

1. Create a notification service (we used Matrix)
2. Set up monitoring for a non-working service with resend set to 0
3. Wait for notifications

### 👀 Expected behavior

Only 1 notification that the service is down

### 😓 Actual Behavior

Notification repeats constantly (in our case every 30 minutes)

### 🐻 Uptime-Kuma Version

1.21.0

### 💻 Operating System and Arch

Debian 11

### 🌐 Browser

Firefox 110.0

### 🐋 Docker Version

Docker version 20.10.5+dfsg1, build 55c4c88

**Comment by TheLastProject** [comment]
My apologies, a misconfiguration caused the Docker container to restart every 30 minutes. Somehow I completely missed that (the Uptime Kuma UI deals very well with backend disconnects)

**Comment by gh3597** [comment]
I was going to delete the above but I have just updated and after a quick test it seems that it isn't exhibiting this behaviour despite me checking the release notes. Maybe I misunderstood one of the fixes or it was fixed with another issue. Either way, I think this is no longer an issue.
