### ISSUE TITLE
Feature: Reset statistics without having to remove checks

### ISSUE THREAD

**Issue by agrider** [louislam/uptime-kuma#296]
**Is it a duplicate question?**
Not that I can see...

**Is your feature request related to a problem? Please describe.**
Thanks to the issues outlined in #295, my response times have been being reported as being in the 20-40s range and my uptimes have been reported as down quite often. Now that I've resolved the issue, my aggregate statistics are skewed wildly by the historical data and I can't find an easy way to reset them without removing and re-adding the watch. 

**Describe the solution you'd like**
I would like to be able to reset the aggregate statistics (avg response, uptime(s)) easily, like with a single "clear statistics" button in the settings page of each watch. It would be ideal to also put a "clear all statistics" button under the main settings page as well for cases like this one where all watches historical statistics are corrupt/invalid/undesirable. 

**Describe alternatives you've considered**

**Additional context**

**Comment by Ponkhy** [comment]
Hey, there i already made a PR #290 according to that topic and i'll be hopefully implemented in version 1.6.0.

**Comment by Ponkhy** [comment]
This issue can be closed i think, since the PR was merged.

**Comment by agrider** [comment]
I usually wait until changes are actually released but I can close it now if others would prefer. Just let me know if folks want it closed now, otherwise I'll close at the next release.
