### ISSUE TITLE
Zoom webhook

### ISSUE THREAD

**Issue by jinpy666** [louislam/uptime-kuma#2960]
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

New Notification

### 🔖 Feature description

Zoom is a global enterprise IM.
Refer to the access document: https://support.zoom.us/hc/en-us/articles/4418193782029

### ✔️ Solution

.

**Comment by rezzorix** [comment]
You can already use webhooks with uptime kuma.

**Comment by jinpy666** [comment]
> 

Thanks for your comment.
Zoom Webhook have their own API format, and uptime Webhook are not compatible.

**Comment by Genc** [comment]
Hi @jinpy666  , Are you sure webhook is not compatible? When I reviewed the document, i saw that you can provide all of these. If you can tell me with examples, I can make improvements for this.

![image](https://github.com/louislam/uptime-kuma/assets/18603640/64904d56-65e1-4568-bc8b-d409fcc4899c)

**Comment by CommanderStorm** [comment]
> Zoom Webhook have their own API format, and uptime Webhook are not compatible.

@jinpy666 
I think this was resolved by https://github.com/louislam/uptime-kuma/pull/3088 which was merged into the upcoming [`1.23` release](https://github.com/louislam/uptime-kuma/milestone/34)
=> Could you close this issue?

**Comment by jinpy666** [comment]
Thanks, it looks like custom Webhooks will solve this problem, but this feature is not yet available in 1.22.1.

**Comment by CommanderStorm** [comment]
Could you close this issue then? (Otherwise this will become one of the zombie-issues even after `1.23`)

**Comment by jinpy666** [comment]
Thank you, everyone.
