### ISSUE TITLE
Zammad ticket integration

### ISSUE THREAD

**Issue by DavKiller** [louislam/uptime-kuma#2965]
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

New Notification

### 🔖 Feature description

I would like to propose that through the Zammad API automated tickets can be created to inform users of crashes.

### ✔️ Solution

When using this type of notification, what should happen is the following:
- When giving an error, a monitor would have to create a ticket (with the priority previously configured in the add notification panel)
- When reestablishing the connection with the monitor, the ticket should be closed automatically.

### ❓ Alternatives

The existing alternative is email notification.

**Comment by Kastello1** [comment]
Unsure why this has been closed, it hasn't been added as far as I can see and such an integration would be really helpful :)

**Comment by DavKiller** [comment]
I close it because you can use mail to create a ticket in zamad, its true one think : Surely it is more efficient using the api and not mail but if you want I'll open the issue again

**Comment by Kastello1** [comment]
Thats true!
Would still be neat if it's get integrated via API at some point, doesn't need to be highly prioritised tho as E-Mail still works ofc.
