### ISSUE TITLE
Status Badge label gets always displayed

### ISSUE THREAD

**Issue by markusobi0** [louislam/uptime-kuma#2974]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### Description

For the status badges there is a query input "label", without this the label "Status" is always set since the last update, even if no query input was passed. There is no way to not show the label

### 👟 Reproduction steps

Compare the output of `/api/badge/<id>/status` in the Versions of <=1.19.x and >=1.20.x

### 👀 Expected behavior

![image](https://user-images.githubusercontent.com/36815683/227601246-1034922f-52c9-4edf-9d16-e7abf7e3930c.png)

### 😓 Actual Behavior

![image](https://user-images.githubusercontent.com/36815683/227601477-493fd02a-60e6-46fa-bf93-3522688eb0d5.png)

### 🐻 Uptime-Kuma Version

1.21.0

### 💻 Operating System and Arch

Ubuntu 20.04

### 🌐 Browser

Vivaldi 5.7.2921.63

### 🐋 Docker Version

Docker 20.10.19

**Comment by chakflying** [comment]
#2211 Added "Status" as the default. I guess currently we don't have a way to distinguish between not setting the label and setting an empty one.

**Comment by markusobi0** [comment]
Good that I noticed the flaw before the update. 

Would it be possible to reintegrate a function for it, the current situation I would personally call a "breaking change with workaround". But the current workaround is not a nice one
