### ISSUE TITLE
Monitor using cached IPv6 address even after restarting container

### ISSUE THREAD

**Issue by luckman212** [louislam/uptime-kuma#2977]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### Description

I think maybe related to https://github.com/louislam/uptime-kuma/pull/2632, I am seeing a problem since updating to 1.21.0

IPv6 HTTPS monitor is using an old stale cached IP. I checked DNS lookup on Docker host as well as `docker exec -it uptime-kuma bash` and then `ping6 my-ipv6-host.foo` which does also return the correct IPv6 address. 

But uptime-kuma still says `connect ETIMEDOUT 2607:fb90:xxxx... (old adress)`

I already had DNS Cache disabled in Uptime Kuma settings. But, I tried enabling and disabling it again just to be sure. No effect.

### 🐻 Uptime-Kuma Version

1.21.0

### 💻 Operating System and Arch

Ubuntu 22.04.1

### 🌐 Browser

Chrome 111

### 🐋 Docker Version

Docker 20.10.17

**Comment by chakflying** [comment]
Are you using the HTTPS monitor or the Docker monitor?

**Comment by luckman212** [comment]
HTTPS

**Comment by luckman212** [comment]
This started working again suddenly. Strange. I'll close the issue for now.

I think there might still be a bug lurking somewhere related to DNS caching. Is there a way to inspect and/or flush nodejs' internal DNS cache?
