### ISSUE TITLE
Docker Desktop - All HTTP(S) Monitors Only Show As Down 

### ISSUE THREAD

**Issue by dbowles1975** [louislam/uptime-kuma#2979]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

After running for several days weeks, all HTTP(S) monitors show down. All ping monitors show as up. All services can still be accessed and pinged. Restarting the Docker Desktop service resolves the problem for a few days. I assume the answer will be to not use Docker Desktop, but I figured I'd ask anyway in case someone else had a similar issue and was able to resolve it. 

### 🐻 Uptime-Kuma Version

1.21.0

### 💻 Operating System and Arch

Windows 10 Pro - Docker Desktop

### 🌐 Browser

Version 111.0.5563.111 (Official Build) (64-bit)

### 🐋 Docker Version

4.4.17.1

**Comment by hafx** [comment]
Hi, 

I have exactly the same issue with docker on a raspberry PI (raspbian buster).

**Comment by louislam** [comment]
Error message?

**Comment by dbowles1975** [comment]
> 

I'll let you know the next time it fails. It happens every few days or so.

**Comment by dbowles1975** [comment]
> Error message?

The error message is "timeout of 48000ms exceeded"

It happens with every HTTP(S) monitor and each of them can still be accessed by clicking the URL in the monitor. Does not affect any ping monitors. Affects monitors running inside and outside of Docker. There's a bunch of these in the error log at the exact time the monitors go down:

`[2023-04-01 03:41:47] KnexTimeoutError: Knex: Timeout acquiring a connection. The pool is probably full. Are you missing a .transacting(trx) call?`

**Comment by chakflying** [comment]
How many monitors are you running?

**Comment by louislam** [comment]
#2346 It's a quite common issue of Uptime Kuma, usually due to the disk I/O and SQLite's limitation.

Make sure your docker disk image is putting in a SSD, it will be faster.
![image](https://user-images.githubusercontent.com/1336778/229293431-e12d7e2f-d70b-4f5c-bd74-5a08d209db13.png)

Also Uptime Kuma 2.0 will support MySQL/MariaDB database, which probably solve this issue, but no ETA yet.

**Comment by dbowles1975** [comment]
> How many monitors are you running?

26. About half are HTTP(S).

**Comment by dbowles1975** [comment]
> #2346 It's a quite common issue of Uptime Kuma, usually due to the disk I/O and SQLite's limitation.
> 
> Make sure your docker disk image is putting in a SSD, it will be faster. ![image](https://user-images.githubusercontent.com/1336778/229293431-e12d7e2f-d70b-4f5c-bd74-5a08d209db13.png)
> 
> Also Uptime Kuma 2.0 will support MySQL/MariaDB database, which probably solve this issue, but no ETA yet.

It's currently in an SSD.

**Comment by hafx** [comment]
> I had the same problem but solved it with a proxy.

Hi, 
What is the link between error (timeout of 48000ms exceeded) and a proxy ?
