### ISSUE TITLE
Monitor fails due to self signed cert only when using socks5 proxy

### ISSUE THREAD

**Issue by clintkev251** [louislam/uptime-kuma#2981]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### Description

I have a single monitor in my Uptime Kuma instance which checks a server which is using a self-signed cert (a PiKVM). This was working fine when I was not using any proxy and had "Ignore TLS/SSL error for HTTPS websites" checked. However after adding the proxy (which is a socks5 (+DNS) proxy), the monitor fails due to this self signed certificate. 

### 👟 Reproduction steps

Create an HTTP or HTTP keyword monitor which makes requests to a server with a self signed certificate and check "Ignore TLS/SSL error for HTTPS websites". Then create a Socks5 (+DNS) proxy and apply it to the monitor.

### 👀 Expected behavior

The server continues to be registered as ok

### 😓 Actual Behavior

The monitor registers the server as down due to the self-signed certificate.

### 🐻 Uptime-Kuma Version

1.21.0

### 💻 Operating System and Arch

Debian 5.10.162-1 (2023-01-21) x86_64

### 🌐 Browser

N/A

### 🐋 Docker Version

Docker 23.0.1

### 📝 Relevant log output

```shell
2023-03-25T20:38:44-04:00 [MONITOR] WARN: Monitor #55 'PiKVM': Failing: self signed certificate | Interval: 120 seconds | Type: keyword | Down Count: 0 | Resend Interval: 0
```

**Comment by CommanderStorm** [comment]
Yes, the fix only applies to `socks`, `socks5`, `socks5h`, `socks4`.

Given that I don't have an HTTP Squid proxy configured, could you test if adding the respective option to `HttpProxyAgent`/`HttpProxyAgent` above works?

⇒ Could you provide a PR via https://github.com/louislam/uptime-kuma/blob/bbaba29222eccdcda0a5a1e1e6355b8b0da057b9/CONTRIBUTING.md

**Comment by chakflying** [comment]
I did a cursory search and it seems like there are a lot of complications with passing `rejectUnauthorized` to the proxy library that we are using, and just adding the parameter won't work. (https://github.com/TooTallNate/proxy-agents/issues/89) 

I would advice against creating such a PR unless you can test and verify that it works.
