### ISSUE TITLE
Which permissions come with API keys?

### ISSUE THREAD

**Issue by codedust** [louislam/uptime-kuma#2986]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

When reading the [API keys wiki page](https://github.com/louislam/uptime-kuma/wiki/API-Keys) it is unclear which permissions are associated with an API key. Specifically: Is it possible to modify uptime kuma's config using an API key or is it only possible to read the Prometheus metrics endpoint?

### 🐻 Uptime-Kuma Version

1.21.1

### 💻 Operating System and Arch

-

### 🌐 Browser

-

**Comment by killsometimebe4timekillsu** [comment]
https://github.com/louislam/uptime-kuma/issues/1685 API Keys Management (Currently, it is used for Prometheus metrics API only) (Thansk @Computroniks)

**Comment by codedust** [comment]
Thanks for the confirmation!
