### ISSUE TITLE
Maintenance Window only working once

### ISSUE THREAD

**Issue by CryPt00n** [louislam/uptime-kuma#2987]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### Description

The Maintenance window is only working once, no matter how schedule is configured. Tried Interval, DoW & DoM, no difference.

![grafik](https://user-images.githubusercontent.com/38314677/228063859-d9d9d4e3-0e16-4079-ae51-8b81d9487db5.png)
![grafik](https://user-images.githubusercontent.com/38314677/228064005-7b9d30c9-cd84-4ac5-9f87-cb555194be16.png)
![grafik](https://user-images.githubusercontent.com/38314677/228064059-3f6d63c7-5177-4a13-9c34-d3f09c3f3987.png)
![grafik](https://user-images.githubusercontent.com/38314677/228063947-d0657d9b-da8f-4f2b-9756-7e873b2fc6dd.png)
![grafik](https://user-images.githubusercontent.com/38314677/228065051-b6f12f18-a1c0-41b4-b4a2-3c61e1719b8e.png)

### 👟 Reproduction steps

Create maintenance schedule with Interval, DoW or DoM Strategy.

### 👀 Expected behavior

Configured Strategy is used, not just a single maintenance window.

### 😓 Actual Behavior

Just a single maintenance window is created.

### 🐻 Uptime-Kuma Version

1.21.1

### 💻 Operating System and Arch

Unraid 6.11.5

### 🌐 Browser

Firefox 111.0.1 (64-Bit)

### 🐋 Docker Version

20.10.21

**Comment by bfqrst** [comment]
I am able to confirm this! Coincidentally (or not) in _Europe/Berlin_ timezone too. On a similar note I noticed that last weekend when the change to summer time happened, the start and end times got shifted by an hour. I had to pull each timeslot back one hour. Obviously this is not what you want when you set a specific time in a specific timezone. Happy to raise a dedicated issue if wanted...

**Comment by jirsbek** [comment]
I can also confirm this. No matter how maintenance window is set up, every second day I have to manually set and save the settings again.

**Comment by niawag** [comment]
Confirming both too: 
- I have two uptime kuma instances with maintenance schedule and it's working only once. Here are my settings:
![image](https://user-images.githubusercontent.com/5684014/228482256-3e14a567-3ad0-4542-ba65-fac4cee62850.png)
- Shifting to summer time (+1h) messed up the schedule by 2h if I recall correctly.

I'll test it with 1.21 (and prior if needed) to see what version broke this feature.

**Comment by sittikornsuw** [comment]
can confirm this as well , now I need to re-activate maintenance schedule everyday

test with 1.21 

<img width="720" alt="Screenshot 2566-03-29 at 16 07 27" src="https://user-images.githubusercontent.com/126160968/228485095-2f28593b-8784-4aa3-9c8b-0938aad59018.png">

**Comment by louislam** [comment]
Can reproduce with UTC+8 too. Will try to find out what causes the issue in 1.21.X.

But I think the daylight saving problem in Europe is unrelated here. 
And by current design, Uptime Kuma eventually stores the start/end time in absolute UTC time only. If the timezone is changed, the start/end time will be shifted accordingly by design. 

Since I am not a guy who lives in a country with DST, feel free to open a new `feature-request` and tell me normally how DST is usually handled in software/apps.

**Comment by louislam** [comment]
1.21.2-beta.0 has been released. Mainly fix this issue, feel free to try.

Release notes:
https://github.com/louislam/uptime-kuma/releases/tag/1.21.2-beta.0

**Comment by MiranoVerhoef** [comment]
> Going back to 1.20.2 solves this issue so it appeared in 1.21. I guess it have to do with this solved issue: #2776

i feel responsible for this not working xD.

@louislam  testing that beta version as we speak!

**Comment by niawag** [comment]
Hi, I can confirm that it's now working! And with great improvement: TZ consideration + no need for an end date, GREAT!

**Comment by TimoHocker** [comment]
The beta looks great.
I have noticed one small issue. When the end date is already set, it can't be cleared. With the clear button on the date picker or by deleting all date parts, after saving it just returns to the previous value.

**Comment by louislam** [comment]
> The beta looks great. I have noticed one small issue. When the end date is already set, it can't be cleared. With the clear button on the date picker or by deleting all date parts, after saving it just returns to the previous value.

Thanks, fixed. https://github.com/louislam/uptime-kuma/commit/45ef7b2f69d5091e7d391406780378730f9fd025

**Comment by SunnyDoraemon** [comment]
it's not work for me ,in version 1.22.1

**Comment by SunnyDoraemon** [comment]
cron or recurring-interval will not work after one day

**Comment by SunnyDoraemon** [comment]
is there any way to fixed this in 1.22.1 @louislam
