### ISSUE TITLE
Issue updating to latest 1.5.0 build

### ISSUE THREAD

**Issue by hansenc0705** [louislam/uptime-kuma#299]
npm ERR! code 1
npm ERR! path /root/uptime-kuma/node_modules/@louislam/better-sqlite3-with-prebuilds
npm ERR! command failed
npm ERR! command sh -c prebuild-install || npm run build-release
npm ERR! > @louislam/better-sqlite3-with-prebuilds@7.4.3 build-release
npm ERR! > node-gyp rebuild --release
npm ERR! prebuild-install WARN install /lib64/libm.so.6: version `GLIBC_2.29' not found (required by /root/uptime-kuma/node_modules/@louislam/better-sqlite3-with-prebuilds/build/Release/better_sqlite3.node)
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@7.1.2
npm ERR! gyp info using node@14.17.3 | linux | x64
npm ERR! gyp ERR! find Python
npm ERR! gyp ERR! find Python checking Python explicitly set from command line or npm configuration
npm ERR! gyp ERR! find Python - "--python=" or "npm config get python" is "/usr/bin/python3"
npm ERR! gyp ERR! find Python - "/usr/bin/python3" is not in PATH or produced an error
npm ERR! gyp ERR! find Python Python is not set from environment variable PYTHON
npm ERR! gyp ERR! find Python checking if "python3" can be used
npm ERR! gyp ERR! find Python - "python3" is not in PATH or produced an error
npm ERR! gyp ERR! find Python checking if "python" can be used
npm ERR! gyp ERR! find Python - "python" is not in PATH or produced an error
npm ERR! gyp ERR! find Python checking if "python2" can be used
npm ERR! gyp ERR! find Python - "python2" is not in PATH or produced an error
npm ERR! gyp ERR! find Python
npm ERR! gyp ERR! find Python **********************************************************
npm ERR! gyp ERR! find Python You need to install the latest version of Python.
npm ERR! gyp ERR! find Python Node-gyp should be able to find and use Python. If not,
npm ERR! gyp ERR! find Python you can try one of the following options:
npm ERR! gyp ERR! find Python - Use the switch --python="/path/to/pythonexecutable"
npm ERR! gyp ERR! find Python   (accepted by both node-gyp and npm)
npm ERR! gyp ERR! find Python - Set the environment variable PYTHON
npm ERR! gyp ERR! find Python - Set the npm configuration variable python:
npm ERR! gyp ERR! find Python   npm config set python "/path/to/pythonexecutable"
npm ERR! gyp ERR! find Python For more information consult the documentation at:
npm ERR! gyp ERR! find Python https://github.com/nodejs/node-gyp#installation
npm ERR! gyp ERR! find Python **********************************************************
npm ERR! gyp ERR! find Python
npm ERR! gyp ERR! configure error
npm ERR! gyp ERR! stack Error: Could not find any Python installation to use
npm ERR! gyp ERR! stack     at PythonFinder.fail (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/find-python.js:302:47)
npm ERR! gyp ERR! stack     at PythonFinder.runChecks (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/find-python.js:136:21)
npm ERR! gyp ERR! stack     at PythonFinder.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/find-python.js:179:16)
npm ERR! gyp ERR! stack     at PythonFinder.execFileCallback (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/find-python.js:266:16)
npm ERR! gyp ERR! stack     at exithandler (child_process.js:326:5)
npm ERR! gyp ERR! stack     at ChildProcess.errorhandler (child_process.js:338:5)
npm ERR! gyp ERR! stack     at ChildProcess.emit (events.js:375:28)
npm ERR! gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
npm ERR! gyp ERR! stack     at onErrorNT (internal/child_process.js:467:16)
npm ERR! gyp ERR! stack     at processTicksAndRejections (internal/process/task_queues.js:82:21)
npm ERR! gyp ERR! System Linux 4.18.0-326.el8.x86_64
npm ERR! gyp ERR! command "/usr/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--release"
npm ERR! gyp ERR! cwd /root/uptime-kuma/node_modules/@louislam/better-sqlite3-with-prebuilds
npm ERR! gyp ERR! node -v v14.17.3
npm ERR! gyp ERR! node-gyp -v v7.1.2
npm ERR! gyp ERR! not ok

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-08-31T21_34_58_775Z-debug.log

**Info**
Uptime Kuma Version: 1.3.2
Using Docker?: No
OS: CentOS Stream release 8
Browser: Chrome Version 92.0.4515.159 (Official Build) (x86_64)

**Comment by louislam** [comment]
I just found out that, I used too recent version to build better-sqlite3. I will try to rebuild it.

Related issue:
https://github.com/JoshuaWise/better-sqlite3/issues/403#issuecomment-817278393

**Comment by louislam** [comment]
Rebuilt with old Ubuntu, solved GLIBC_2.29 error, another error come up.

I plan to revert back to node-sqlite3 in the version, since better-sqlite3 is hard to be installed.

You can switch back to 1.3.2 at this moment.

```
git checkout 1.3.2 --force
```

**Comment by louislam** [comment]
Just released 1.5.2, should be solved your problem.

**Comment by martadinata666** [comment]
let me bump, which ubuntu version? I can build version 1.5.0 in buster and bullseye correctly, nodejs come from nodesource repo itself.

**Comment by hansenc0705** [comment]
thanks, 1.5.2 fixed the issue i had and was able to install the latest update. thanks!

**Comment by louislam** [comment]
> let me join, pretty curious abt this, which ubuntu version? I can build version 1.5.0 in buster and bullseye correctly, nodejs come from nodesource repo itself.

I rebuilt the prebuilt with Ubuntu 16.04. 

I gave up better-sqlite3 already, so no need to fix.

The dockerfile
https://github.com/louislam/better-sqlite3-with-prebuilds/blob/master/dockerfile_linux
