### ISSUE TITLE
Dashboard Display on vertical 4K screen

### ISSUE THREAD

**Issue by LA4XLA** [louislam/uptime-kuma#2993]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### Description

Maybe not bug, but rather suggestion of improvement in design. When displaying Dashboard on a vertical 4K screen the quick stats list view does not utilize the hight of the monitor. Only fills half monitor and display pagination buttons. Would be nice with button "all" in adition to < 1, 2 >. 
Version: 1.21.1

### 👟 Reproduction steps

See Description

### 👀 Expected behavior

See Description

### 😓 Actual Behavior

See Description

### 🐻 Uptime-Kuma Version

Version: 1.21.1

### 💻 Operating System and Arch

Ubuntu 22.10

### 🌐 Browser

Edge V112 Dev

**Comment by CommanderStorm** [comment]
#3451 was merged into `v1.23.X` resolving this issue
=> closing as resolved
