### ISSUE TITLE
Any way to connect some uptime-kuma installations to one server with uptime-luma

### ISSUE THREAD

**Issue by iNaiks** [louislam/uptime-kuma#2995]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

Hi,
Very good service to check the aviability of a lot of services!!! Amazing !!!!!

I've started to do a mini-server to check a lot of thing of my house and from internet.
But the quiestion is, there is any way that I can install a small uptime-kuma and configure for check some services, and send the info (online/offline, time of ping...) to the mini-server with uptime-kuma.

Is for check devices that are not in my network with ping and no need to use the TCP port check with port forwarding.

Very thanks.
Nico 

### 🐻 Uptime-Kuma Version

1.21.1

### 💻 Operating System and Arch

Docker with Synology

### 🌐 Browser

Safari 16.2

### 🐋 Docker Version

20.10.3-1308

### 🟩 NodeJS Version

12.22.12-2031 // 10.20.1-1012 // 16.17.1-1010

**Comment by Computroniks** [comment]
See #84
