### ISSUE TITLE
Is there a way to duplicate an existing notification so I don't have to start from scratch with a different monitor?

### ISSUE THREAD

**Issue by douglerner** [louislam/uptime-kuma#2997]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

I'm creating a new monitor and the people to be alerted are a different set of people than the ones in a previous notification I created for a different monitor.

But the base is the same: it's and SMTP (Email) notification, using the same host mail server, sender name, etc. And I'd like to use most of the same settings. But I'd like it to be a different friendly name, and a different set of recipients.

When creating a new monitor I see I can create a new notification. But is there a way of duplicating an existing notification so I can select and modify that? 

Or maybe I'm missing a basic concept where I can already use an existing notification and modify it on a per-monitor basis?

Thanks.

### 🐻 Uptime-Kuma Version

1.20.12

### 💻 Operating System and Arch

Whatever PikaPod sis using

### 🌐 Browser

Chrome

**Comment by louislam** [comment]
It is not possible currently.

**Comment by douglerner** [comment]
OK, thanks.
