### ISSUE TITLE
Is there an API?

### ISSUE THREAD

**Issue by Swalhamdan** [louislam/uptime-kuma#2998]
### ⚠️ Please verify that this bug has NOT been raised before.

- [x] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

I want an existing system of mine to interact with the Uptime Kuma service. Is there an API I can use for the systems to interact with eachother? If there is another alternative to this please let me know.

### 🐻 Uptime-Kuma Version

1.21.1

### 💻 Operating System and Arch

Ubuntu 20.04

### 🌐 Browser

Chrome

**Comment by Computroniks** [comment]
Currently there is no public API. See #118 for updates

**Comment by CommanderStorm** [comment]
@Swalhamdan Is there a something that is not covered by #118? Is this issue resolved?
