### ISSUE TITLE
NGINX Reverse Proxy: disallowed MIME type & blocked due to MIME type

### ISSUE THREAD

**Issue by haywardgb** [louislam/uptime-kuma#3005]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

I'm trying to use status.server.name to connect to localhost:3001 with NGINX reverse proxy for a specific status page.

The DNS settings are working fine with Cloudflare, the page loads but it's blank. If I look at the source I can see the html content. But in the browser console I get the following errors. Can anyone help me out? 

I can connect fine to the main localhost:3001 through another.domainname using Cloudflare tunnels. So Kuma is fine.

CONSOLE ERRORS:

Loading module from “https://server/assets/index.cc8bee17.js” was blocked because of a disallowed MIME type (“text/html”).
Loading failed for the module with source “https://server/assets/index.cc8bee17.js”. status.server:12:1
The resource from “https://server/assets/index.12012ccc.css” was blocked due to MIME type (“text/html”) mismatch (X-Content-Type-Options: nosniff). status.server

NGINX SERVER CONFIG:

server {
 listen 443 ssl http2;
    ssl_certificate /var/www/certs/server_certificate.pem;
    ssl_certificate_key /var/www/certs/server_key.pem;
    server_name status.server;
    charset UTF-8;
    location ~* \.(js|json|css)$ {
    access_log off; log_not_found off; expires 30d; }

 location / {
    proxy_set_header   X-Real-IP $remote_addr;
    proxy_set_header   X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header   Host $host;
    proxy_pass         http://localhost:3001/;
    proxy_http_version 1.1;
    proxy_set_header   Upgrade $http_upgrade;
    proxy_set_header   Connection "upgrade";
  }
}

### 🐻 Uptime-Kuma Version

1.21.1

### 💻 Operating System and Arch

Ubuntu 20

### 🌐 Browser

Firefox

**Comment by haywardgb** [comment]
I finally found where the option to add a domain was for this: https://github.com/louislam/uptime-kuma/wiki/Status-Page

But it's still giving me the same issue. I've changed proxy_pass http://localhost:3001/status/server to default.

**Comment by louislam** [comment]
I think it is not correct

> proxy_pass http://localhost:3001/status/server;

Please follow:
https://github.com/louislam/uptime-kuma/wiki/Reverse-Proxy#nginx

**Comment by haywardgb** [comment]
> I think it is not correct
> 
> > proxy_pass http://localhost:3001/status/server;
> 
> Please follow: https://github.com/louislam/uptime-kuma/wiki/Reverse-Proxy#nginx

I've tried with and without. I tried with the official version , which gives me the same issue :(

The reason I added /status/StatusPage is because I thought that might work, but no :(

**Comment by haywardgb** [comment]
To be clear. 

I have followed the information here: https://github.com/louislam/uptime-kuma/wiki/Status-Page for adding status pages as domain names. I added my status.servername.tld as instructed. 

I then followed this guide to add my subdomain to Nginx: https://github.com/louislam/uptime-kuma/wiki/Reverse-Proxy#nginx

I then added my.servername.tld to my cloudflare DNS ... 

When I access the page, it's blank and I look in console to find the errors listed in the original post.

**Comment by louislam** [comment]
Not quite sure, can you try to view the icon?

> https://your-server/icon.png

Reference: https://status.kuma.pet/icon.png

**Comment by haywardgb** [comment]
I gave up trying to do it the NGINX Reverse Proxy way and went the Cloudflare Tunnel route.

It works a charm using Cloudflare Tunnels. Should have just done it that way to start with.

Sorry for wasting your time Louislam. Thank you though and much appreciated :)
