### ISSUE TITLE
Scheduled Maintenance does not repeat

### ISSUE THREAD

**Issue by TimoHocker** [louislam/uptime-kuma#3012]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### Description

Maintenances with Recurring Strategy will only run once and never repeat.

### 👟 Reproduction steps

I created a new maintenance, set it to 'Recurring - Interval' and Interval 1. Time window 02:30 - 03:00 and Effective Date Range from Today to a random date in 2100 (This should not be required, I want it to repeat forever). I also tried using 'Recurring - Day of Week' as seen in the screenshot, but both result in the same problem.

![Screenshot](https://i.imgur.com/9PIGnE5.png)

### 👀 Expected behavior

The maintenance should be active from 02:30 to 03:00 every day.

### 😓 Actual Behavior

The maintenance works properly on the next day, but then remains in status 'Ended' and never repeats.

### 🐻 Uptime-Kuma Version

1.21.0

### 💻 Operating System and Arch

Debian bullseye x86

### 🌐 Browser

Firefox Developer Edition

### 🐋 Docker Version

Docker 23.0.1

### 📝 Relevant log output

```shell
# On the first day it shows the maintenance being planned
uptime-kuma  | 2023-04-01T02:30:01+02:00 [MAINTENANCE] INFO: Generate Timeslot for maintenance id: 1

# On the second day and any further days it logs nothing related to the maintenance, just the monitors that are now generating alerts.
```

**Comment by louislam** [comment]
Please check 1.21.2-beta.0

Duplicate of #2987
