### ISSUE TITLE
Working time

### ISSUE THREAD

**Issue by Filoz** [louislam/uptime-kuma#3014]
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

Other

### 🔖 Feature description

Hello everyone
I have an url that I have to monitor which, every night from 2 am to 3 am, performs maintenance and then goes down or about 1 hour.

It would be really great to be able to define at what time intervals the monitor should take place (be active).

This feature also allows different monitors to be set up for the same url  to run at different times.

### ✔️ Solution

Being able to set time intervals for each monitor during the day when it should or should not be active.
In my case I would set the control to take place all day except from 2 to 3 am so I will not receive """false""" notifications in the mid of the night :D.

**Comment by louislam** [comment]
There is a feature called `Maintenance` for this purpose.

Unfortunately, it is bugged in `1.21.1`, please use the beta version for now.

https://github.com/louislam/uptime-kuma/releases/tag/1.21.2-beta.0
