### ISSUE TITLE
Checking Status of app behind Vouch Proxy

### ISSUE THREAD

**Issue by nevetS-718** [louislam/uptime-kuma#3018]
### ⚠️ Please verify that this bug has NOT been raised before.

- [x] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

I am trying to check the uptime of an static page being served by nginx, but behind [Vouch proxy](https://github.com/vouch/vouch-proxy). The issue I am faced with is Uptime Kuma marking the app as up regardless as long as it can reach Vouch and my OAuth provider. The closes existing issue I could find is #1744 , however that was written off as "If you can get to the login page it should be reachable" but in my situation isn't the case. The following is the network section from Firefox devtools:

![redirs](https://user-images.githubusercontent.com/70534545/229559567-8ddf0042-f012-4090-a89b-13cf7737abd5.PNG)

My current idea on how to make this work is to figure out how to pass SSO credentials through to my OAuth provider. If I can't figure anything like this out, my last ditch solution would be to create an internal app that checks the internal app's uptime, then passes that through to Uptime Kuma, but that wouldn't fix the issue with static pages.

This may be something I need to ask the Vouch devs about, but I figured I would leave a paper trail here in case anyone else has this issue. I'll link the issue from the Vouch repo when I make it as well.

Any ideas would be greatly appreciated!

### 🐻 Uptime-Kuma Version

1.12.1

### 💻 Operating System and Arch

Debian 11 x64 on Nanode 1G

### 🌐 Browser

Mozilla Firefox 102.9.0esr

### 🐋 Docker Version

N/A

### 🟩 NodeJS Version

18.15.0

**Comment by CommanderStorm** [comment]
A solution of your usecase could be `push`-based monitoring.
i.e. you have push monitores set up inside the proxy that tell uptime-kuma (presumably outside of kuma, right?) that the service is still up.

This does not monitor for Vouch being up+working (for this you could set up another monotor)

Would this be a solution to your usecase?
