### ISSUE TITLE
MariaDB aborts KUMA db connection.

### ISSUE THREAD

**Issue by Kevinsky86** [louislam/uptime-kuma#3020]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### Description

Since enabling database monitoring. 
Server logs aborted connections from kuma user.

Client (KUMA) appears to not properly close connections.

(Edit: To clarify, even though the database logs the aborted connection, KUMA monitoring seems to work just fine.)

### 👟 Reproduction steps

Enable monitor using select query.

In my case: 
select * from heartbeat where id = 1;

### 👀 Expected behavior

Should not generate noise in database logs.

### 😓 Actual Behavior

Generates noise in database server logs.

### 🐻 Uptime-Kuma Version

1.21.1

### 💻 Operating System and Arch

Almalinux 8

### 🌐 Browser

Chrome 111.0.5563.147

### 🟩 NodeJS Version

v18.12.1

### 📝 Relevant log output

```shell
Aborted connection ### to db: 'kumadb' user: 'kumauser' host: 'kuma.ip.address' (Got an error reading communication packets)
```

**Comment by louislam** [comment]
My guess: your query result is too big

> https://dba.stackexchange.com/questions/19135/mysql-error-reading-communication-packets

**Comment by Kevinsky86** [comment]
> My guess: your query result is too big
> 
> > https://dba.stackexchange.com/questions/19135/mysql-error-reading-communication-packets

Yeah found this result also.

But I've changed it to select count(id) which returns "1" instead of the one row that is in this table and subsequently litterally used "select 1" as the whole query, but issue persists.

I don't think it's a configuration issue on the DB end, it processes a couple hundred queries per second from various systems without logging anything similiar.

The query also works as far as KUMA is concerned.

**Comment by lenisko** [comment]
https://github.com/louislam/uptime-kuma/blob/eb9c74807188008b1a98c237108849c57fef0f7c/server/util-server.js#L345

Shouldn't `connection.end` be used there? 

https://github.com/mysqljs/mysql#terminating-connections

**Comment by chakflying** [comment]
This was because of #2729. The ideal solution would be to check if connection was established, and call `end` or `destroy` accordingly. But I have not worked on it yet.

**Comment by lenisko** [comment]
```js
.finally(() => {
    try {
      connection.end();
    } catch (e) {
      log.warn("mysq", "can't end connection, using destroy");
      connection.destroy();
    }
});
```

@chakflying how about simple `try..catch` in this case?
