### ISSUE TITLE
Monitor can't deleted

### ISSUE THREAD

**Issue by prohand** [louislam/uptime-kuma#3025]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### Description

After delete monitor and refresh page I have this page : 

![image](https://user-images.githubusercontent.com/20227162/229888762-55c5080d-a1f4-4c88-8faa-cd257c285faa.png)

And monitor can't deleted

### 👟 Reproduction steps

Delete monitor and refresh page

### 👀 Expected behavior

Monitor must be removed

### 😓 Actual Behavior

Monitor not be removed

### 🐻 Uptime-Kuma Version

1.21.2

### 💻 Operating System and Arch

Ubuntu 22.04 

### 🌐 Browser

Brave 1.49.132

### 🟩 NodeJS Version

14.20.1

**Comment by chakflying** [comment]
Please see #1661

**Comment by prohand** [comment]
Good evening,

Thank you, it's ok while waiting longer.
Sorry to bother you

THANKS
