### ISSUE TITLE
CloudFlare pages support (severless)?

### ISSUE THREAD

**Issue by bbigras** [louislam/uptime-kuma#3026]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

Is it possible to run a lightweight frontend on CloudFlare pages?

It could be nice to do something like:

- run worker on my own server (or maybe cloudflare workers) and push results to a highly available database like cockroach cloud (not sure if neon is replicated).
- have a read-only front-end on cloudflare pages that connects to cockroach
- profits

The advantages would be to kinda self host (the worker) but still have the status page up if my host is down

### 🐻 Uptime-Kuma Version

none 

### 💻 Operating System and Arch

none

### 🌐 Browser

Firefox

**Comment by CommanderStorm** [comment]
I am doubtful that running `uptime-kuma` serverless works good.

To be frank, I am not convinced, that going serverless is a good use case for an uptime monitor.
My reasoning behind this is that for uptime-monitoring, you have a repetitive stream of pings going out.
If serverless, this would drive up the cost fast.

If the pings dont come from the serverless functions, you have a server somewhere.
Why not run uptime-kuma there?

Why do you think serverless+external db is a good choice?

Note:
There are efforts underway to migrate to a different database, but I don't think a relatively niche database which you have to pay for like Cockroach is a good fit.
Decoupling the frontend and the pings may be something that can be looked into if the migration to a different database has completed.
