### ISSUE TITLE
Decouple SSL expiry alerts from Up/Down alerts

### ISSUE THREAD

**Issue by ligouras** [louislam/uptime-kuma#3028]
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

Other

### 🔖 Feature description

It would be extremely helpful to be able to configure a notification ONLY for certificate expiration alerts, either per monitor, or as a global.

### ✔️ Solution

Add an option in Settings > Notifications for configuring a notification specifically for certification expiry alerts.

### 📝 Additional Context

Right now we have a single Slack channel which receives all alerts, and it is hard to detect certificate-related alerts among all up/down events.

**Comment by CommanderStorm** [comment]
@ligouras @ass
We are consolidating duplicate issues a bit to make issue management easier.
I think, we should track this issue in https://github.com/louislam/uptime-kuma/issues/508 as this is included there
⇒ I am going to close this as a duplicate.
