### ISSUE TITLE
Add a queue system

### ISSUE THREAD

**Issue by AwesomeKalin** [louislam/uptime-kuma#3036]
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

New Monitor

### 🔖 Feature description

Some people (like me) host uptime kuma on ultra-low end hardware (eg. Replit). As a result, the server could get overloaded due too many monitors.

### ✔️ Solution

I would like to see a queue system. The user will specify how many monitors can be checked concurrently and if this number is reached, other monitors wait until another monitor finishes.

**Comment by HammyHavoc** [comment]
Disappointed that this isn't planned; avoiding rate-limiting when checking certain hosting providers would be nice.

**Comment by HammyHavoc** [comment]
> > Disappointed that this isn't planned; avoiding rate-limiting when checking certain hosting providers would be nice.
> 
> Don't know where you got that information from. Please see
> 
>     * [Change the monitor "scheduler" from setTimeout to Croner + Queue  #3447](https://github.com/louislam/uptime-kuma/pull/3447)
> 
> 
> That PR still needs some work though. V2.0 has resolved a lot of performance issues (you are unlikely to be bottlenecked by monitors).
> 
> Replit won't be supported due to the number of bugs raisedby its users being too high for us to handle

Wow! Extremely excited by this! Amazing!!
