### ISSUE TITLE
Importing Digicert's new G2 Certificates

### ISSUE THREAD

**Issue by Dakotuhh** [louislam/uptime-kuma#3038]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

We've recently been issued a new certificate from DigiCert, using their Intermediate Certificate Authority "DigiCert Global G2 TLS RSA SHA256 2020 CA1." You can read about this change here:

https://knowledge.digicert.com/generalinformation/digicert-root-and-intermediate-ca-certificate-updates-2023.html

Due to this, our HTTPS monitoring fails unless the "Ignore TLS/SSL error for HTTPS websites" is checked.  I do not have any issues with the certificate when browsing to the site on my desktop or phone.

Is there a way I can manually add this ICA to my trusted certificates? Will this ICA certificate be added to Uptime-Kuma in the future?

For my own privacy and the privacy of my employer, I cannot provide the website for testing, but I'm open to try anything suggested. 

### 🐻 Uptime-Kuma Version

1.21.2

### 💻 Operating System and Arch

CentOS Stream 8 x64

### 🌐 Browser

Google Chrome Version 112.0.5615.49

### 🐋 Docker Version

23.0.3, build 3e7cbfd

**Comment by chakflying** [comment]
According to [this](https://metadata.ftp-master.debian.org/changelogs/main/c/ca-certificates/stable_changelog) Changelog, the "DigiCert Global Root G2" was already added to debian back in 2014. I also tested the docker version works with [Digicert's demo website](https://global-root-g2.chain-demos.digicert.com/). 

I think the more likely scenario is that you didn't include the full certificate chain on your server / website.

**Comment by Dakotuhh** [comment]
Hmm... You're right, thanks for finding test site. The ICA and CA certs are both in the correct stores on the web server, although the ICA cert did have to be added manually... I'll take another look at it.

**Comment by Dakotuhh** [comment]
Not super relevant to Uptime-Kuma, but for those who see this, DigiCert has a diagnostics tool that can help, and even provides some troubleshooting steps:  https://www.digicert.com/help/

I did not restart the site when I installed the new certs, and it turns out that was my issue.
