### ISSUE TITLE
Highly inconsistent memory usage

### ISSUE THREAD

**Issue by Lanhild** [louislam/uptime-kuma#3039]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### Description

![image](https://user-images.githubusercontent.com/73610779/230488043-97e42c8b-88a6-454d-adc5-dbd067050ee3.png)
![image](https://user-images.githubusercontent.com/73610779/230488065-3f68536b-0b82-4169-aa6b-e10c048e9c8c.png)

### 👟 Reproduction steps

Start uptime kuma using docker compose, and observe. Memory usage spikes happen even though I'm doing nothing in my instance, it's just reporting as usual.

### 👀 Expected behavior

No such inconsistent memory usage spikes

### 😓 Actual Behavior

Memory usage spikes.

### 🐻 Uptime-Kuma Version

1.21.2

### 💻 Operating System and Arch

Ubuntu 22.04

### 🌐 Browser

Irrelevant

### 🟩 NodeJS Version

n/a

### 📝 Relevant log output

```shell
No relevant logs
```

**Comment by stefandesu** [comment]
I've had my Uptime Kuma instance on Fly.io crash a few times randomly due to memory spikes (free apps have a 232 MB memory limit). Since it's back without seconds and there seem to be no issues with monitoring, I didn't look further into it, but I thought it might be relevant for this issue. Unfortunately, the logs already got cleared from the Fly.io console, although I don't think there were any log entries that could help pinpoint the leak.

**Comment by chakflying** [comment]
I did some profiling and found that downloading the response body from monitored websites can be a big memory contributor. The response body gets parsed to a string with `toString`, which allocates a block of memory that doesn't seem to get freed automatically (in my 15 minutes profiling). But maybe it's already garbage collected and it's just not freeing it back to the OS unless some condition is met? This is deep inside node.js so I'm not sure how to fix.

**Comment by stefandesu** [comment]
I've had some crashes again and I've noticed that for my instances on Fly.io, the out of memory crashes are related to the nightly "clear-old-data" task. In a success scenario, the logs look like this:

```
2023-04-25T01:14:02.517 app[______________] ams [info] Worker for job "clear-old-data" online undefined
2023-04-25T01:14:04.903 app[______________] ams [info] 2023-04-25T03:14:04+02:00 [PLUGIN] WARN: Warning: In order to enable plugin feature, you need to use the default data directory: ./data/
2023-04-25T01:14:04.904 app[______________] ams [info] 2023-04-25T03:14:04+02:00 [DB] INFO: Data Dir: data/
2023-04-25T01:14:05.621 app[______________] ams [info] 2023-04-25T03:14:05+02:00 [DB] INFO: SQLite config:
2023-04-25T01:14:05.628 app[______________] ams [info] [ { journal_mode: 'wal' } ]
2023-04-25T01:14:05.631 app[______________] ams [info] [ { cache_size: -12000 } ]
2023-04-25T01:14:05.634 app[______________] ams [info] 2023-04-25T03:14:05+02:00 [DB] INFO: SQLite Version: 3.39.4
2023-04-25T01:14:05.664 app[______________] ams [info] {
2023-04-25T01:14:05.664 app[______________] ams [info] name: 'clear-old-data',
2023-04-25T01:14:05.664 app[______________] ams [info] message: 'Clearing Data older than 180 days...'
2023-04-25T01:14:05.664 app[______________] ams [info] }
2023-04-25T01:14:05.935 app[______________] ams [info] { name: 'clear-old-data', message: 'done' } 
```

When it fails, it already stops after the first line:

```
2023-04-26T01:14:02.621 app[______________] ams [info] Worker for job "clear-old-data" online undefined
2023-04-26T01:15:34.847 app[______________] ams [info] [172851.821740] Out of memory: Killed process 526 (node) total-vm:1076864kB, anon-rss:182500kB, file-rss:0kB, shmem-rss:0kB, UID:0 pgtables:3948kB oom_score_adj:0 
```

Also note that there's a 1.5 minute delay between starting the job and it being out of memory, while in the success scenario, the whole job runs in a few seconds. Maybe there's a bug with a memory leak in that job's code?

**Comment by chakflying** [comment]
Just for clarity, it did print 'Clearing Data older than 180 days...' before going out of memory?

**Comment by stefandesu** [comment]
@chakflying Nope, it's just what I posted above, so it's only the 'Worker for job "clear-old-data" online undefined' line before it runs out of memory 1 1/2 minutes later.

**Comment by chakflying** [comment]
Well that's very weird, because the logging calls are basically the first things that gets run, if no logs were printed it indicates the jobs didn't start.

Is the instance already running close to out of memory, and starting the job just pushed it over?

**Comment by stefandesu** [comment]
Memory usage does seem to be increasing over time the longer it is up. Here's my instance's memory usage over the past 7 days:

<img width="703" alt="Screen Shot 2023-04-29 at 09 32 23" src="https://user-images.githubusercontent.com/3275148/235290177-5c6008c8-ea63-477f-970b-be069cccdbd8.png">

Those big spikes were the out-of-memory crashes, but many of the jumps in memory usage before that seem to be caused during the nightly job as well (but not all of them).

Here's a closer look at one of the spikes where it crashed:

<img width="654" alt="Screen Shot 2023-04-29 at 09 34 54" src="https://user-images.githubusercontent.com/3275148/235290227-9a67cef7-8018-4aad-a52d-f5ec8dee693f.png">

It might be a weird Fly.io thing, but at the start of the job, memory usage jumps close to the limit, stays there for that 1 1/2 minutes (where there seems to be no logging), and only then it crashes. Seems very weird to me.

In any case, there seem to be one or more things that cause memory usage to go up (often in jumps), but not go down again, and at a certain point, the jump is too big and it runs out of memory.

Hope this helps!

**Comment by stefandesu** [comment]
> The job currently runs on worker threads, which seems to start a new V8 instance with independent memory management.

This seems to prevent the `max_old_space_size` CLI arg to work as expected. I experimented with different values for my instance on Fly.io, but it still gets OOM killed every 2-3 days. I assume, as you expect, that not all the memory is returned to the OS after the `clear-old-data` job and so even if the main thread stays under the `max_old_space_size`, total memory consumption still rises like before. At least the graphs don't seem to have changed much.

> Regardless rewriting this job to not use worker threads would probably eliminate this.

At the very least, it should then be possible to use `max_old_space_size` to force garbage collection before it gets OOM killed.

**Comment by Saibamen** [comment]
Will be fixed with 1.22.0

This issue started with [version 1.9.0](https://github.com/louislam/uptime-kuma/releases/tag/1.9.0)

**Comment by jaskeerat789** [comment]
I have been running uptime-kuma 1.21.3 on k8s and 1.21.2 on an ec2(t3a.small) using docker. Both the environments show an upward trend for memory utilization. Metrics are collected using node-exporter for both environment.

k8s has request set to 200Mi and limit set to 400Mi.
![image](https://github.com/louislam/uptime-kuma/assets/38110126/0a07d0a5-1942-4395-98c3-555068017bab)

There are no limits set for container on ec2
![image](https://github.com/louislam/uptime-kuma/assets/38110126/b7dccae1-6b77-4338-9e71-e622362680a0)

```bash
$ docker stats uptime-kuma
CONTAINER ID   NAME          CPU %     MEM USAGE / LIMIT  
52a02f328b12   uptime-kuma   15.57%    1.034GiB
```

Is it related to the issue discussed here?

**Comment by chakflying** [comment]
What monitors do you have setup and are you sending HTTP request to endpoints with a large response size?

**Comment by chakflying** [comment]
Research and explanation was already written above. If you care about the memory used, update to `1.22` and set a memory limit for the container. (cli argument `--memory=`) It should run fine with around ~256MB.

**Comment by luckman212** [comment]
@jaskeerat789 What tool did you use to generate those graphs?

**Comment by CommanderStorm** [comment]
@luckman212 See [grafana](https://grafana.com/)

https://github.com/louislam/uptime-kuma/assets/26258709/4b4da9d4-8704-4278-b770-c6cdceeb4a14
