### ISSUE TITLE
Raise maintenance page against tag group

### ISSUE THREAD

**Issue by disappointingsupernova** [louislam/uptime-kuma#3041]
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

Other

### 🔖 Feature description

When on 'Schedule Maintenance' rather than having to select each host individually, being able to assign maintenance to all hosts with a tag would be useful.

For example, I have a tag called 'PowerDNS' - I would like to be able to add all of those hosts to the affected hosts list for a scheduled maintenance

### ✔️ Solution

On 'Schedule Maintenance' select affected hosts based on the tag that they have.

**Comment by CommanderStorm** [comment]
@disappointingsupernova  a very similar feature has been implemented+merged.
Any version after [`1.22.0-beta.0`](https://github.com/louislam/uptime-kuma/releases/tag/1.22.0-beta.0) supports this.
![image](https://github.com/louislam/uptime-kuma/assets/26258709/2b8673a3-214f-449f-a7fd-675c6dacc8db)
![image](https://github.com/louislam/uptime-kuma/assets/26258709/2a188e08-0774-402e-92e7-c18da04c0026)
![image](https://github.com/louislam/uptime-kuma/assets/26258709/3a19abac-fd44-430b-84e0-8be09d9e6031)

Could you close this Issue, if this has been resolved?

**Comment by disappointingsupernova** [comment]
Thanks All. This is great!
