### ISSUE TITLE
Having startup errors

### ISSUE THREAD

**Issue by ARR4NN** [louislam/uptime-kuma#3043]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

https://logs.ronanplugins.com/emamexukil.swift

### 📝 Error Message(s) or Log

https://logs.ronanplugins.com/emamexukil.swift

### 🐻 Uptime-Kuma Version

it auto pulls from github

### 💻 Operating System and Arch

Ubuntu 20.04

### 🌐 Browser

Chrome

**Comment by louislam** [comment]
> npm ERR! Error: ENOSPC: no space left on device, write

And you didn't seem to follow the instruction of installation.

**Comment by ARR4NN** [comment]
> > npm ERR! Error: ENOSPC: no space left on device, write
> 
> 
> 
> And you didn't seem to follow the instruction of installation.

Well it has been working fine for months and a restart caused it to go all crazy

**Comment by louislam** [comment]
I think you can focus on the error msg first.

`no space left on device` = no more disk space

Try to check your disk space first.
