### ISSUE TITLE
Allow shorter interval ping after monitor is down

### ISSUE THREAD

**Issue by binarydad** [louislam/uptime-kuma#305]
I have an interval of 5 minutes (300 secs) for most of my monitors. However, when one goes down, it still waits 5 minutes to ping again (as expected). 

It would be nice if there's an option to have a shorter ping for when a monitor is down so that I can be alerted more quickly that it is back up, instead of waiting (in my case) 5 minutes. 

For example, if my default ping internal is 300 secs, I'd like to define a "when monitor is down" interval of something like 30 seconds, until the monitor is back up. 

Thank you. BTW I absolutely love UK. I've completely ditched uptimerobot.

**Comment by engineeringsys** [comment]
@binarydad 

can you output any logging information from the container when this happens?  i could take a stab at this.  if you like this project definitely encourage sponsoring the author.

**Comment by trogper** [comment]
does retry interval solve your issue?

**Comment by chakflying** [comment]
Should be closed since retry interval is supported.

**Comment by chakflying** [comment]
Closing as we now have configurable retry interval. 

Note outstanding issue tracked in #4025.
