### ISSUE TITLE
Documentation Enhancement Request - Process to Backup Uptime Kuma (Upgrade Process)

### ISSUE THREAD

**Issue by techmanities** [louislam/uptime-kuma#3050]
The Release Documentation States to Make a Backup of your Installation before upgrading.

However, I could not find any documentation on GitHub on what that requires.

Is it simply a copy of the installation director, or are their specific files/configurations/databases in other locations that need to be backed up before the upgrade. 

(An "Export All Data" process would be helpful also).

**Comment by louislam** [comment]
You can stop the container and just copy the data directory or volume.
