### ISSUE TITLE
Run Playwright Tests

### ISSUE THREAD

**Issue by jonnymccullagh** [louislam/uptime-kuma#3056]
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

New Monitor

### 🔖 Feature description

I haven't seen this raised before but wondering if it would be possible to have a check type that allows pasting a [playwright](https://playwright.dev/) test.
This could allow for multi-steps, form completion & element selection.

### ✔️ Solution

Maybe being able to paste some javascript into a text box and choosing Playright as the monitor type. The javascript would then need to be run via `playwright test`.
```test.describe("myapp", () => {
  const baseDomain = 'myapp.mydomain.com';
  test('login', async ({ page }) => {
    await page.goto(`https://${baseDomain}/auth/login`);
    await page.locator('input[type="text"]').click();
    await page.locator('input[type="text"]').fill('myname@mydomain.com');
    await page.locator('input[type="text"]').press('Tab');
    await page.locator('input[type="password"]').fill('somethingsecret');
    await Promise.all([
      page.waitForNavigation(),
      page.locator('button:has-text("Log in")').click()
    ]);
  });```

### ❓ Alternatives

_No response_

### 📝 Additional Context

_No response_

**Comment by CommanderStorm** [comment]
I don't quite get what you are requesting.
Is running tests not what continuous integration (on-push or on-schedule) is for? What would be the advantage to running this in an uptime monitor?

If you are referring to this projects tests:
What is the advantage compared to the [current way to test this project](https://github.com/louislam/uptime-kuma/blob/master/test/cypress/e2e/setup.cy.js)?

I agree that test coverage is not great, PRs in this area would be appreciated.

**Comment by jonnymccullagh** [comment]
I suppose @CommanderStorm I am asking for synthetics checks. We have these checks in other tools such as Datadog, Elastic and I would like to be able to do the same here. Other tools have browser tools built in that allow for using a UI to generate the synthetics test but I think a first step would be to be able to create a synthetics test script manually (or using the Elastic Recorder) but to run that code as part of an uptime-kuma check.

**Comment by CommanderStorm** [comment]
Traditionally, I would say that this would be better located in a CI.
Said CI can push to uptime-kuma using the `push`-monitor

**Comment by jonnymccullagh** [comment]
That is how I am currently running it. But I do think there is a place for synthetics checks in montioring tools as is the case in other tools DD, Elastic, Grafana.

**Comment by CommanderStorm** [comment]
> But I do think there is a place for synthetics checks in montioring tools

Why is this better in monitoring tools than in CI?

**Comment by jonnymccullagh** [comment]
I really don't want an argument. If you don't agree it is fine to close this issue. 
But to answer the question: to keep monitoring stats in one place, to manage retries, downtimes and notifications in one place and to have it included on a status page.
I agree all of this can be done in other tools or pipelines. But so too could http pings for uptime.

**Comment by lorenzulrich** [comment]
Even though this is already closed I'd like to second @jonnymccullagh here. This is a very useful feature of e.g. BetterUptime that allows for uptime tests that are a little more complex than just HTTP tests, e.g. if you're waiting for some external content to load or want to test stuff behind a login.

https://betterstack.com/docs/uptime/playwright-monitor/
