### ISSUE TITLE
Time axes are not aligned

### ISSUE THREAD

**Issue by waclaw66** [louislam/uptime-kuma#3058]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### Description

When the same service is checked by different monitor types - ping and http, there is misalignment on time axis.

![obrazek](https://user-images.githubusercontent.com/15554561/231674012-0d3eb4a0-c440-43ff-8e3e-cf3460e77b29.png)

### 👟 Reproduction steps

Create ping and http monitors for the same service.

### 👀 Expected behavior

Time axes of service monitors have to be aligned.

### 😓 Actual Behavior

Time axes are misaligned. Outage times of services cannot be compared.

### 🐻 Uptime-Kuma Version

1.21.2

### 💻 Operating System and Arch

?

### 🌐 Browser

Firefox 113

### 🐋 Docker Version

?

### 🟩 NodeJS Version

?

**Comment by louislam** [comment]
It's not representing a time range.

**Comment by chakflying** [comment]
More specifically, every beat represents a "heartbeat interval". If your monitors have the same check interval, their timescale should be the same.

**Comment by waclaw66** [comment]
I've observed that the heartbeat interval doesn't take into account timeout of a monitor. It's 48s for http and 10s for ping checks monitoring not responding service.
Timeout shouldn't affect heartbeat interval, checks shall be executed peridically like cron.
That explains my previous complaints about time range.

**Comment by chakflying** [comment]
Yup I also just tested to confirm this. It's 21s for http and 5s for ping on Windows, although I guess for http it also depends on the manner of failure/timeout. The response time also gets added to the interval on successful beats, which leads to a slower website checking on larger intervals than a faster website. I think we can reopen this to think about a solution.
