### ISSUE TITLE
Remote docker monitoring with TLS

### ISSUE THREAD

**Issue by Galmior** [louislam/uptime-kuma#3061]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

I am trying to monitor docker remotely.  i did follow this procedure : [https://github.com/louislam/uptime-kuma/pull/2852].
I did test the remote connexion from portainer and it was working. It was the same from a curl request : 
`curl https://docker1.home.bsfi.local:2376/containers/json?all=true \
  --cert cert.pem \
  --key key.pem \
  --cacert ca.pem
[{"Id":"e567e73fbaff1dd76f4691e32f42d9a4ad67f299eb07f8b4aa5e41c8bc7b3c49","Names":["/blissful_kirch"],"Image":"hello-world","ImageID":"sha256:feb5d9fea6a5e9606aa995e879d862b825965ba48de054caab5ef356dc6b3412","Command":"/hello","Created":1681130301,"Ports":[],"Labels":{},"State":"exited","Status":"Exited (0) 3 days ago","HostConfig":{"NetworkMode":"default"},"NetworkSettings":{"Networks":{"bridge":{"IPAMConfig":null,"Links":null,"Aliases":null,"NetworkID":"b1993881205cae972485dbddf3b4c104956bf62036d2b1f7862d9e22f28ca218","EndpointID":"","Gateway":"","IPAddress":"","IPPrefixLen":0,"IPv6Gateway":"","GlobalIPv6Address":"","GlobalIPv6PrefixLen":0,"MacAddress":"","DriverOpts":null}}},"Mounts":[]}]
`
When i try fom uptime GUI i got : socket hang up as error

i did setup the directory : data/docker-tls/docker1.home.bsfi.local/
cert|key|ca are within this directory

I do not understand what i did wrong :( Can someone help me?

### 📝 Error Message(s) or Log

`AxiosError: socket hang up
    at connResetException (node:internal/errors:705:14)
    at TLSSocket.socketOnEnd (node:_http_client:518:23)
    at TLSSocket.emit (node:events:525:35)
    at endReadableNT (node:internal/streams/readable:1358:12)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) {
  code: 'ECONNRESET',
  config: {
    transitional: {
      silentJSONParsing: true,
      forcedJSONParsing: true,
      clarifyTimeoutError: false
    },
    adapter: [Function: httpAdapter],
    transformRequest: [ [Function: transformRequest] ],
    transformResponse: [ [Function: transformResponse] ],
    timeout: 0,
    xsrfCookieName: 'XSRF-TOKEN',
    xsrfHeaderName: 'X-XSRF-TOKEN',
    maxContentLength: -1,
    maxBodyLength: -1,
    env: { FormData: [Function] },
    validateStatus: [Function: validateStatus],
    headers: { Accept: '*/*', 'User-Agent': 'Uptime-Kuma/1.21.2' },
    url: '/containers/json?all=true',
    httpsAgent: Agent {
      _events: [Object: null prototype],
      _eventsCount: 2,
      _maxListeners: undefined,
      defaultPort: 443,
      protocol: 'https:',
      options: [Object: null prototype],
      requests: [Object: null prototype] {},
      sockets: [Object: null prototype],
      freeSockets: [Object: null prototype] {},
      keepAliveMsecs: 1000,
      keepAlive: false,
      maxSockets: Infinity,
      maxFreeSockets: 256,
      scheduling: 'lifo',
      maxTotalSockets: Infinity,
      totalSocketCount: 1,
      maxCachedSessions: 0,
      _sessionCache: [Object],
      [Symbol(kCapture)]: false
    },
    baseURL: 'https://docker1.home.bsfi.local:2376',
    method: 'get',
    data: undefined
  },
  request: <ref *1> Writable {
    _writableState: WritableState {
      objectMode: false,
      highWaterMark: 16384,
      finalCalled: false,
      needDrain: false,
      ending: false,
      ended: false,
      finished: false,
      destroyed: false,
      decodeStrings: true,
      defaultEncoding: 'utf8',
      length: 0,
      writing: false,
      corked: 0,
      sync: true,
      bufferProcessing: false,
      onwrite: [Function: bound onwrite],
      writecb: null,
      writelen: 0,
      afterWriteTickInfo: null,
      buffered: [],
      bufferedIndex: 0,
      allBuffers: true,
      allNoop: true,
      pendingcb: 0,
      constructed: true,
      prefinished: false,
      errorEmitted: false,
      emitClose: true,
      autoDestroy: true,
      errored: null,
      closed: false,
      closeEmitted: false,
      [Symbol(kOnFinished)]: []
    },
    _events: [Object: null prototype] {
      response: [Function: handleResponse],
      error: [Function: handleRequestError],
      socket: [Function: handleRequestSocket]
    },
    _eventsCount: 3,
    _maxListeners: undefined,
    _options: {
      maxRedirects: 21,
      maxBodyLength: 10485760,
      protocol: 'https:',
      path: '/containers/json?all=true',
      method: 'GET',
      headers: [Object],
      agent: [Agent],
      agents: [Object],
      auth: undefined,
      hostname: 'docker1.home.bsfi.local',
      port: '2376',
      nativeProtocols: [Object],
      pathname: '/containers/json',
      search: '?all=true'
    },
    _ended: true,
    _ending: true,
    _redirectCount: 0,
    _redirects: [],
    _requestBodyLength: 0,
    _requestBodyBuffers: [],
    _onNativeResponse: [Function (anonymous)],
    _currentRequest: ClientRequest {
      _events: [Object: null prototype],
      _eventsCount: 7,
      _maxListeners: undefined,
      outputData: [],
      outputSize: 0,
      writable: true,
      destroyed: false,
      _last: true,
      chunkedEncoding: false,
      shouldKeepAlive: false,
      maxRequestsOnConnectionReached: false,
      _defaultKeepAlive: true,
      useChunkedEncodingByDefault: false,
      sendDate: false,
      _removedConnection: false,
      _removedContLen: false,
      _removedTE: false,
      strictContentLength: false,
      _contentLength: 0,
      _hasBody: true,
      _trailer: '',
      finished: true,
      _headerSent: true,
      _closed: false,
      socket: [TLSSocket],
      _header: 'GET /containers/json?all=true HTTP/1.1\r\n' +
        'Accept: */*\r\n' +
        'User-Agent: Uptime-Kuma/1.21.2\r\n' +
        'Host: docker1.home.bsfi.local:2376\r\n' +
        'Connection: close\r\n' +
        '\r\n',
      _keepAliveTimeout: 0,
      _onPendingData: [Function: nop],
      agent: [Agent],
      socketPath: undefined,
      method: 'GET',
      maxHeaderSize: undefined,
      insecureHTTPParser: undefined,
      path: '/containers/json?all=true',
      _ended: false,
      res: null,
      aborted: false,
      timeoutCb: null,
      upgradeOrConnect: false,
      parser: null,
      maxHeadersCount: null,
      reusedSocket: false,
      host: 'docker1.home.bsfi.local',
      protocol: 'https:',
      _redirectable: [Circular *1],
      [Symbol(kCapture)]: false,
      [Symbol(kBytesWritten)]: 0,
      [Symbol(kEndCalled)]: true,
      [Symbol(kNeedDrain)]: false,
      [Symbol(corked)]: 0,
      [Symbol(kOutHeaders)]: [Object: null prototype],
      [Symbol(kUniqueHeaders)]: null
    },
    _currentUrl: 'https://docker1.home.bsfi.local:2376/containers/json?all=true',
    [Symbol(kCapture)]: false
  }
}
`

### 🐻 Uptime-Kuma Version

1.21.2

### 💻 Operating System and Arch

Debian on AArch64

### 🌐 Browser

Google chrome 112.0.5615.86

### 🐋 Docker Version

Docker 23.0.1

**Comment by chakflying** [comment]
If you are just running the docker version, this pull request has not been merged yet and this feature is not available.

**Comment by Galmior** [comment]
ok thanks a lot. I will check from time to time to see if it has been merged or not. I love this project and thks for eveything that has been created
