### ISSUE TITLE
adding support for ELASTICSEARCH monitoring

### ISSUE THREAD

**Issue by macaty** [louislam/uptime-kuma#3064]
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

New Monitor

### 🔖 Feature description

Uptime-kuma is an amazing project, and after my initial experience using it, I deeply appreciate its beauty. I would love to contribute some great ideas to this project and hope they can be accepted to make kuma even more perfect.

### ✔️ Solution

adding support for ELASTICSEARCH monitoring item types, which would make your system monitoring more comprehensive.

**Comment by CommanderStorm** [comment]
Please separate this issue into multiple issues. (supplying multiple issues in one issue is unmaintanable, sorry)

Please supply more details about what you would like to be monitored how.
Also include why the existing offerings (for example pings, ...) don't cover this usecase.

**Comment by CommanderStorm** [comment]
Note that Postgres is already supported:
![image](https://github.com/louislam/uptime-kuma/assets/26258709/a94bd91b-bc00-45c3-8c20-03acc51ba68e)

**Comment by CommanderStorm** [comment]
LDAP is now tracked in https://github.com/louislam/uptime-kuma/issues/4504

Given that elasticsearch offers a [cluster health api](https://www.elastic.co/guide/en/elasticsearch/reference/current/cluster-health.html), I think the current tooling such as the `json-query` monitor are sufficient without additional context as requested above
=> closing as resolved
