### ISSUE TITLE
Renaming UptimeKuma to UptimeRobot in all titles, names, notifications, etc. 

### ISSUE THREAD

**Issue by arebacollins** [louislam/uptime-kuma#3067]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

Hello all,
 
First, I love the application, and am willing to even dedicate time and resource towards bettering it. I have a somewhat embarrassing situation with the name though. you see, "Kuma" in Swahili is derogatory slang for the female sex organ. 

Is there a language file, or an easy way to change a local installation to reflect a different name, I am totally OK with literally any other name, but would obviously not mind doing uptime robot. 

Really appreciate. 
Collins. 

### 🐻 Uptime-Kuma Version

1.10.0

### 💻 Operating System and Arch

ubuntu 21.04

### 🌐 Browser

chrome

**Comment by CommanderStorm** [comment]
From the [wiki](https://github.com/louislam/uptime-kuma/wiki):
> Kuma (クマ/熊) means 🐻🐻 in Japanese.
A little bear is watching your website. 🐻🐻🐻 

⇒ I don't think changing the name of this project is feasible.

On the name you suggested:
[UptimeRobot](https://uptimerobot.com/) is another company. Impersonating other companies is not a use case for this project. 

Currently, [we don't support Swahili as a Translation](https://weblate.kuma.pet/projects/uptime-kuma/uptime-kuma/). This may change. (given that this is a community-driven project)
Using another name in a translation could be possible, but might require a PR to add the required translation strings.

Our current strategy is:
![image](https://github.com/louislam/uptime-kuma/assets/26258709/d33d6f4a-6ce2-414e-84ec-d9f17253c666)

I can't think of any suitable solutions with which we could replace the lower term for Swahili.
Do you have any good ideas/Suggestions which are close to our current brand?

**Comment by CommanderStorm** [comment]
Edit: you can disable the Powered By with this button:
![image](https://github.com/louislam/uptime-kuma/assets/26258709/1858108f-6ed0-4c97-8c6a-acbf24355268)
