### ISSUE TITLE
Agent and client setup tutorial?

### ISSUE THREAD

**Issue by rhuanpk** [louislam/uptime-kuma#3071]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

Hello everybody,

I really apologize if my question is redundant, but I really searched a lot here in the issues and didn't find exactly what I need.

I wanted to know first if it is possible, if so, could someone point me to an updated tutorial on how to install and configure an Uptime Kuma agent on a server to monitor it and its services (mainly the Docker containers on that server) that communicate with the Uptime Kuma client that is on another server?

How do I install this agent? Your config files? Which ports on the firewall should I allow?

And on the client side, how do I configure the Dashboard to receive information from this agent, and from the Docker containers it is monitoring?

PS: I didn't put the Uptime Kuma version because I didn't know how to check it, since I installed the client by command:

```bash
docker run -d --restart=always -p 3001:3001 -v uptime-kuma:/app/data --name uptime-kuma louislam/uptime-kuma:1
```

Suggested at: <https://uptime.kuma.pet/>

---

I'm really grateful for any help!

### 🐻 Uptime-Kuma Version

0.0.0

### 💻 Operating System and Arch

Ubuntu 20.04 x86

### 🌐 Browser

Google Chrome 112.0.5615.49

### 🐋 Docker Version

Docker 23.0.3

**Comment by louislam** [comment]
It is not possible unfortunately.

**Comment by rhuanpk** [comment]
Oh, ok :/
Anyway thank you!

**Comment by minster586** [comment]
so I just made a small program for Windows That's basically what it does is you select a running program it then allows you as the user to select a port and how often the program checks if that other program is running and gives you HTTP code 200 if the program's running or 4O4 if it's not to which uptime kuma can actually check
