### ISSUE TITLE
What is the normal number of monitors for Uptime Kuma instance?

### ISSUE THREAD

**Issue by dlackovic** [louislam/uptime-kuma#3075]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

What is normal number of monitors per instance? How man monitors you have in one instance?

### 🐻 Uptime-Kuma Version

latest

### 💻 Operating System and Arch

Osx

### 🌐 Browser

Firefox

**Comment by sonuame** [comment]
I am using it with 124 numbers. I can see delay in few alerts already

**Comment by rezzorix** [comment]
It pretty much depends on your system and connection you run uptime-kuma on. 

Some people reach a limit at 100… some others at 124… but you will also find people here that have uptime-kuma running with several
hundred monitors.
