### ISSUE TITLE
Telegram reports about sites, that was removed

### ISSUE THREAD

**Issue by lustmordtheblackpost** [louislam/uptime-kuma#3077]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### Description

Uptime_Bot, [17.04.2023 15:27]
[svet24.ru] [🔴 Down] connect EHOSTUNREACH 193.187.96.199:443
Uptime_Bot, [17.04.2023 15:28]
[svet24.ru] [✅ Up] 200 - OK

But these projects are removed from Uptime Kuma long ago. Looks like some issues in database

### 👟 Reproduction steps

getting notifications about deleted sites

### 👀 Expected behavior

 Looks like some issues in database

### 😓 Actual Behavior

notificatins 

### 🐻 Uptime-Kuma Version

1.21.2

### 💻 Operating System and Arch

Ubuntu 20.04 ч64

### 🌐 Browser

Chrome lastest

**Comment by prabhsharan36** [comment]
@louislam should I work on this? could you please assign this bug to me?

**Comment by louislam** [comment]
> @louislam should I work on this? could you please assign this bug to me?

Yes, of course, thank you. However, it is hard to be confirmed as there is no reproduce steps.

**Comment by prabhsharan36** [comment]
@lustmordtheblackpost checked in every possible way. But, in database the notification linked with the monitor we delete also gets deleted due to the "CASCADE ON DELETE" constraint. Could you provide the way how I could reproduce this issue?

**Comment by lustmordtheblackpost** [comment]
By the last update I can't reproduce too. I'll monitor it too.

**Comment by CommanderStorm** [comment]
Closing as `cannot-reproduce`
