### ISSUE TITLE
Change default Slug

### ISSUE THREAD

**Issue by SnowBerryZ** [louislam/uptime-kuma#3082]
Hallo, sorry for my Bad English, i have an Question its possible to change the Standard Slug "status" but my Subdomain have the Name "status" and this is very ugly to read ^_^

I have tested to change server.js entryPages... Have no effects :-( 

Have an nice Day.

**Comment by chakflying** [comment]
You can point the home page to your Status Page by going into Settings -> General -> Entry Page.

**Comment by SnowBerryZ** [comment]
This is not what i mean ...
My Problem are i have an subdomain with status.domain.com ... And the finaly Result:
status.domain.com/status/xyz are not very great :D

**Comment by chakflying** [comment]
I get what you mean now. It's a limitation of the current usage of the vue-router. You are welcome to open an issue using the issue template to track this properly.
