### ISSUE TITLE
Run as non-root user?

### ISSUE THREAD

**Issue by bestrocker221** [louislam/uptime-kuma#3083]
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

Other

### 🔖 Feature description

Hi, thanks for the project!

It would be nice to give the user the possibility to specify the user that runs the container so that we do not need to run it as root.

Thanks in advance for all of your work.

### ✔️ Solution

Maybe create a new user (1000:1000) in the dockerfile?
This way it would be possible to specify the same uid as the host user and properly share volumes

**Comment by netr0m** [comment]
See https://github.com/louislam/uptime-kuma/pull/2086

It's a WIP, for release 2.x - see https://github.com/users/louislam/projects/4?query=is%3Aopen+sort%3Aupdated-desc

There's https://github.com/louislam/uptime-kuma/pull/1286 as well

**Comment by CommanderStorm** [comment]
@bestrocker221 given that https://github.com/louislam/uptime-kuma/pull/2086 is merged into the v2 branch, could you close this issue?

(this will be in v2 and this way we are not risking this issue becoming an immortal zombie, given that only you or louis can close issues...)

**Comment by fede843** [comment]
waiting for this too. Thanks!
