### ISSUE TITLE
What's the best way to update Kuma? Updating Kuma to the latest version from 19.6

### ISSUE THREAD

**Issue by Mighty33** [louislam/uptime-kuma#3085]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

What's the best way to update Kuma? Updating Kuma to the latest version from 19.6

### 🐻 Uptime-Kuma Version

19.6

### 💻 Operating System and Arch

Ubuntu 20

### 🌐 Browser

edge, chrome

**Comment by chakflying** [comment]
You can follow the instructions in the [Wiki](https://github.com/louislam/uptime-kuma/wiki/%F0%9F%86%99-How-to-Update).
