### ISSUE TITLE
Ping not working but able to use CMD (windows) to ping an IP. **Help?

### ISSUE THREAD

**Issue by Mighty33** [louislam/uptime-kuma#3086]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

I wanted to monitor a modem...But no ports specifically are opened. Wanted to use just a simple ping (ICMP) to monitor this device...  In the command prompt CMD works and able to ping... But in Kuma, not able to ping. Is there a way to monitor this via ICMP (like in cmd prompt ping)??

### 🐻 Uptime-Kuma Version

19.6

### 💻 Operating System and Arch

Ubuntu 20

### 🌐 Browser

edge, chrome

**Comment by Mighty33** [comment]
Needed to install the ping command on Ubuntu 20.4

**Comment by hemrajani-Code** [comment]
I am facing the same issue. is there a recommendation or a solution to this?

**Comment by bendcloud** [comment]
Same here. Any update?

**Comment by CommanderStorm** [comment]
you can install ping or use our container.

Alternatively, we can change the code path for windows, but this requires someone who uses wondwos to develop and test. I don't.
