### ISSUE TITLE
DNS failures mean that notifications are not delivered

### ISSUE THREAD

**Issue by JunTsao** [louislam/uptime-kuma#3090]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### Description

I have set up a DNS monitoring project to monitor wx.mail.qq.com through port 53, and configured notifications through WeCom. Today, my DNS server had a failure, but I did not receive any failure notifications from Uptime Kuma until I manually restarted the DNS service and then Uptime Kuma sent me a notification that the service had been restored.

![image](https://user-images.githubusercontent.com/9066570/233287194-00e64e68-818d-4758-924e-fbfb5276a477.png)
![image](https://user-images.githubusercontent.com/9066570/233284586-832509f6-00f3-481b-9723-d2c6c955ecf2.png)

In addition, I have configured several HTTP GET monitoring items in Uptime Kuma. After I restarted the DNS service, I received notifications that these monitoring items had been restored. However, on the dashboard, these monitoring items are displayed as normal together.
![image](https://user-images.githubusercontent.com/9066570/233284986-fd8c1217-dcac-43f6-8a14-5982af440558.png)

So,  never received any DNS failure notifications throughout the incident.

### 👟 Reproduction steps

1、Stop DNS service in Windows Server 2019.
2、The Uptime Kuma dashboard shows a failure.
3、WeCom did not receive any notifications.
4、Start Windows Server 2019 DNS service.
5、Received HTTP GET monitoring item recovery notification in WeCom.
6、In addition, I only configured one WeCom notification.

### 👀 Expected behavior

Received DNS failure notification in WeCom.

### 😓 Actual Behavior

WeCom did not receive DNS failure notification.

### 🐻 Uptime-Kuma Version

1.21.2

### 💻 Operating System and Arch

Windows Server 2019

### 🌐 Browser

edge 114

### 🐋 Docker Version

Docker 20.10.22

**Comment by louislam** [comment]
>1、Stop DNS service in Windows Server 2019.
2、The Uptime Kuma dashboard shows a failure.

Is Uptime Kuma also using that DNS service to resolve domain names?

If yes, it was completely normal that Uptime Kuma could not send a notification, because it needed to make a request to `https://qyapi.weixin.qq.com`, but your DNS was down which is impossible.

**Comment by chakflying** [comment]
We could probably add the DNS cache to the notification providers to mitigate this, but yeah this shouldn't be a "supported failure mode", if the DNS server uptime-kuma depends on goes down, your data becomes unreliable anyway.

**Comment by CommanderStorm** [comment]
I am going to close this issue as wotfix.
If a user wants to run a custom dns server, they should not run the monitoring of said dns serve via said server...
I don't see a good fix to this on our side..

In docker, a reliable dns server can be specified such as `1.1.1.1` via the `--dns` flag
