### ISSUE TITLE
Being able to show result of mysql query in tags

### ISSUE THREAD

**Issue by szymontex** [louislam/uptime-kuma#3095]
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

UI Feature

### 🔖 Feature description

This should be pretty straight forward. Uptimekuma is performing mysql querry to check if service (mysql/mariadb( is up. It could bring result of that query and be able to show it in tags. 

### ✔️ Solution

I'm having values of current user logged in in particular system in database. Uptime Kuma is able of mysql query, I would love to see result of that query and show it in tag value.

**Comment by CommanderStorm** [comment]
@szymontex What do you mean by showing it in a tag value? Seems like a sort of weird feature to me.

**Comment by CommanderStorm** [comment]
given that @szymontex did not reppond what they really mean or what their usecase is, I am going to close this issue as not planned.

Currently, I think custom behaviour can be implmented via the api, but is not nessesarily something that all users would understand or like to have.
=> closing as not planned

If you thnk we are missing some context, we would love to discuss the original usecase that made you like this feature in the first place.
