### ISSUE TITLE
Why is the project running in index.html in dist and I want to modify the source file what should I do？

### ISSUE THREAD

**Issue by czkground** [louislam/uptime-kuma#3096]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

Why is the project running in index.html in dist and I want to modify the source file what should I do？

### 🐻 Uptime-Kuma Version

no

### 💻 Operating System and Arch

windows11

### 🌐 Browser

edge

### 🟩 NodeJS Version

18.16.0

**Comment by louislam** [comment]
You have to understand and setup the dev environment first: 
https://github.com/louislam/uptime-kuma/blob/master/CONTRIBUTING.md

**Comment by czkground** [comment]
> 您必须先了解并设置开发环境：https://github.com/louislam/uptime-kuma/blob/master/CONTRIBUTING.md
抱歉！我不是学前端对这方面知识很欠缺，我看了还不是很懂，感谢回答
