### ISSUE TITLE
Monitor site for specific keyword

### ISSUE THREAD

**Issue by adm2k** [louislam/uptime-kuma#3099]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

I would like to be able to monitor this website, https://webapps.jacksonemc.com/nisc/maps/MemberOutageMap/
and have UptimeKuma notify me if the "#Out" value is 0 or greater for Barrow County.

### 🐻 Uptime-Kuma Version

Version: 1.21.2

### 💻 Operating System and Arch

Ubuntu server 22.04

### 🌐 Browser

Version 112.0.5615.134 (Official Build) (64-bit)

**Comment by sprior** [comment]
The web page you listed doesn't work in that straightforward way.  Your browser goes to the address you gave which returns the general page and some Javascript code, and then that Javascript is executed by your browser to fetch the actual outage data and then the display is updated by your browser to fill in that information.   That site appears to protect itself from exactly the kind of automated data retrieval that you are asking for, so I think you're out of luck.
