### ISSUE TITLE
add insecure SMTP (protonmail)

### ISSUE THREAD

**Issue by gitcatpeter** [louislam/uptime-kuma#31]
Currently sending a test email via protonmail- bridge fails (and consequently email does not work), because kuma uses self-signed certificates.
Please allow additional options in SMTP settings to turn off SSL.
Depending on email client usually these settings need to be considered:
SYMFONY__ENV__MAILER_ENCRYPTION=null
or
DIUN_NOTIF_MAIL_SSL=false
DIUN_NOTIF_MAIL_INSECURESKIPVERIFY=true

Is proxy in front an answer too?

**Comment by louislam** [comment]
#19 is it related to your issue?

**Comment by gitcatpeter** [comment]
Commented in #19.
Yes, this takes care of it. Thanks.
