### ISSUE TITLE
Microsoft Teams not sending down alert

### ISSUE THREAD

**Issue by dinbhar** [louislam/uptime-kuma#3105]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

I am monitoring 40 hosts. The down alert never comes on MS Team, the Up alert comes. Down and up alert work if I try to send it to Telegram. Is anyone facing a similar issue?

Thanks,

### 🐻 Uptime-Kuma Version

1.21.2

### 💻 Operating System and Arch

Ubuntu 20.04

### 🌐 Browser

Edge

### 🐋 Docker Version

23.0.3

### 🟩 NodeJS Version

0

**Comment by Woahai321** [comment]
ME 2

**Comment by chakflying** [comment]
I did a quick check and there should be nothing different between up and down notifications except the message. Did you manually check by setting up a Push monitor and adding the Teams notification?

**Comment by Po3idon** [comment]
Same issue. I monitor round about 40-50 monitors. Only up messages, no down messages.

**Comment by dinbhar** [comment]
I did the following.
1. Created SMTP notification and kept the MS Team notification running too.
2. Waited for a host to go down
3. When the host went down I received notifications on both email and Teams
4. Disabled the SMTP and down alerts are working fine for MS Team (tested with push monitor)
5. Will test more and update

**Comment by NeuralMiner** [comment]
> 

We also did this and it seemed to have resolved it for us.
