### ISSUE TITLE
Impossible to login to websocket with API token

### ISSUE THREAD

**Issue by Vinalti** [louislam/uptime-kuma#3107]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### Description

When trying to use the SocketIO endpoint of Kuma (which i didn't find documentation for btw) the login function seem to provide only support for username, password and token (cookie i guess). 

### 👟 Reproduction steps

use the `login` feature of the SocketIO endpoint with no username and the api_key as password. That doesn't work. 

### 👀 Expected behavior

We should be able to use an API token to connect to the SocketIO ? Or is ther another proper API endpoint ?

### 😓 Actual Behavior

Nothing. "Bad username or password."

### 🐻 Uptime-Kuma Version

1.21.1

### 💻 Operating System and Arch

N/A

### 🌐 Browser

Chrome

**Comment by chakflying** [comment]
Not a bug, API keys are currently only used for the Prometheus metrics endpoint. https://github.com/louislam/uptime-kuma/pull/2558

**Comment by Vinalti** [comment]
Ok... and how should we parse the prometheus endpoint?
would it be possible to have a similar endpoint returning JSON? `/metrics.json` or `status.json` for instance.

this would be very appreciated as there is no API usable by a normal script at the moment...😅  
In reality we don't need much, an "is_up" (bool) , and "average_up"(percentage) values for each monitored endpoint would be very nice already.

**Comment by simonmicro** [comment]
@Vinalti I would recommend you to utilize one of the [Prometheus client libraries](https://prometheus.io/docs/instrumenting/clientlibs/) (also available for Python) to parse the response by Uptime-Kuma, as it is a standardized format already.
