### ISSUE TITLE
Avoiding down notification for keyword search because the SSL cert altnames don't match?

### ISSUE THREAD

**Issue by douglerner** [louislam/uptime-kuma#3109]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

I'm using an HTTPS check with keyword. The site is a cluster of 4 nodes and a source. Only the source (www) has an SSL cert. But the other nodes(node1.www, node2.www, etc.) all have DNS entries so I can go to the separate nodes as needed. I want to do checks of whether the nodes are in synch by checking keywords.

With Uptime Robot this works, but with Uptime Kuma I get a down message:

Hostname/IP does not match certificate's altnames: Host: [node1.www.thedomain.net](http://node1.www.thedomain.net/). is not in the cert's altnames.

Is there a way I can allow Uptime Kuma to do the keyword check and not worry about the fact that node1 is not in the cert's altnames?

Thanks.

### 🐻 Uptime-Kuma Version

1.21.2

### 💻 Operating System and Arch

Whatever PikaPods uses

### 🌐 Browser

Whatever PikaPods uses

**Comment by chakflying** [comment]
Have you tried the "Ignore TLS/SSL error for HTTPS websites" option?

**Comment by douglerner** [comment]
Thank you. I overlooked that setting and/or didn't catch what it meant. It seems to be ok now. Thanks!
