### ISSUE TITLE
IPv6-only does not work in some environments

### ISSUE THREAD

**Issue by solick** [louislam/uptime-kuma#3113]
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

Other

### 🔖 Feature description

Currently it is not possible to monitor server which has only an ipv6 address. I tested with a virtual machine which has only an ipv6 address with ping monitoring and the server is down as inactive. Tested the same machine with uptimerobot and the server is shown as up and running.

Because Ipv6 is the future and Ipv4 is legacy, uptime-duma should support ipv6 monitoring.

### ✔️ Solution

Either enable ping monitoring to test v4 and v6 or add a new ping6 monitoring.

**Comment by n-thumann** [comment]
Is this still the case? I am currently running Uptime Kuma on a IPv6-only server and monitoring `ipv6.google.com` (doesn't have an A record) with no issues :v:

**Comment by solick** [comment]
It was only the case using the docker variant. I installed uptime kuma now plain on a vm and now it works.

**Comment by benniju** [comment]
Hi, I can only run Uptime Kuma in docker, because I use Home Assistant OS. Would it be possible to add IPv6 support to the Docker images?

**Comment by benniju** [comment]
I am running v1.23.13 in Home Assistant OS using the following addon: https://github.com/hassio-addons/addon-uptime-kuma
I have tried adding a ping monitor for an Hostname which only has an AAAA (IPv6) record and no A (IPv4) record and IP address. 
When I save the monitor I get the message that it is down with the error `ping: connect: Address not available`. When I try to add the IP Address itself with braces, I can't even save the monitor.

This is the output when I try to use ping in the docker container using docker exec:
```
root@a0d7b954-uptime-kuma:/opt$ ping google.de
PING google.de (142.250.186.35) 56(84) bytes of data.
64 bytes from fra24s04-in-f3.1e100.net (142.250.186.35): icmp_seq=1 ttl=114 time=19.9 ms
^C
--- google.de ping statistics ---
1 packets transmitted, 1 received, 0% packet loss, time 0ms
rtt min/avg/max/mdev = 19.858/19.858/19.858/0.000 ms
root@a0d7b954-uptime-kuma:/opt$ ping -6 google.de
ping: connect: Address not available
root@a0d7b954-uptime-kuma:/opt$ ping6 google.de
ping6: connect: Address not available
```

So it seems that the container does not have any IPv6 support at all. This is not the case for other Home Assistant Containers. 
Although I have noticed that the hass docker image is not based on this docker image, so maybe I should open the issue there?

**Comment by CommanderStorm** [comment]
The current regex is here:

https://github.com/louislam/uptime-kuma/blob/11007823e7207531da4d82cab0b774ee8ace6f57/src/util-frontend.js#L111-L126

**Comment by benniju** [comment]
> Is the URL publicly routable? If yes, could you provide the URL you are testing against?

Yes, but I do not want to publish the URL. But the same problem also occurs when adding ipv6.google.com.
> Is this reproducible on uptime.kuma.pet ? (I am trying to rule out bad docker networking, which is somewhat of a common occurrence)

Yes, the ping also does not work there with the error `connect: Network is unreachable` 
> Alternatively (idk how to do that via your deployment variant, we don't maintain that and I don't use it) you can try our troubleshooting steps here and see if it is a docker network is configured correctly: https://github.com/louislam/uptime-kuma/wiki/Troubleshooting
```
root@a0d7b954-uptime-kuma:/opt$ curl https://ipv6.google.com
curl: (7) Failed to connect to ipv6.google.com port 443 after 4 ms: Couldn't connect to server
root@a0d7b954-uptime-kuma:/opt$ ping ipv6.google.com
ping: connect: Address not available
```
So as I also noted before it does seem that the container does not have any IPv6 Support at all, so it is likely a docker network problem. Should I open an issue in the addons repo instead? I find it interesting though, that the IPv6 ping also fails on the demo, but with a different error.

**Comment by CommanderStorm** [comment]
ipv6 networking in docker (docs at https://docs.docker.com/config/daemon/ipv6/) needs to be enabled.
By default only IPv4 is available.

For home assistant this is tracked/discussed here:
https://github.com/home-assistant/supervisor/issues/2133

Closing as nothing we can do. Upstream support needs to be enabled manually.
If there is something that we are missing, please comment and we can reopen the issue ^^
