### ISSUE TITLE
Add support for custom html script embedding

### ISSUE THREAD

**Issue by djedu** [louislam/uptime-kuma#3115]
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

UI Feature

### 🔖 Feature description

Add an option to embed custom javascript for the status pages.

This will allow the use of other analytics tools instead of Google for example. 

### ✔️ Solution

An option in settings to embed html in the head and/or body of the page would be great.

**Comment by chakflying** [comment]
Previously script tag insertion was reported as [XSS](https://github.com/louislam/uptime-kuma/security/advisories/GHSA-wh8j-xr66-f296). We have not had a discussion around here for the ideal security boundaries of this application, I honestly think it's a reasonable request, it's a fact that the admin has full control over the content of the status pages.

**Comment by CommanderStorm** [comment]
@djedu 
We are consolidating duplicate issues a bit to make issue management eazier.
I think, we should track this issue in https://github.com/louislam/uptime-kuma/issues/2818 as there is no functional difference ^^
=> I am going to close this as a duplicate
