### ISSUE TITLE
says no auth mode when stoping cloudflared

### ISSUE THREAD

**Issue by kokofixcomputers** [louislam/uptime-kuma#3118]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### Description

When i press stop cloudflared it says you are in no auth mode a password is not required but i am in auth mode

images:

When stopping cloudflared:

<img width="524" alt="SCR-20230502-kp3" src="https://user-images.githubusercontent.com/113046561/235794436-8dc43f1e-6bea-40b0-a20b-7fca65ba192b.png">

When logging in:

<img width="473" alt="SCR-20230502-kq5" src="https://user-images.githubusercontent.com/113046561/235794529-f0e6ffc2-888c-433c-a30c-4655b8ee2b95.png">

### 👟 Reproduction steps

It says that you are in no auth mode a password is not required when you stop cloudflared in settings in uptime kuma but i am in auth mode

### 👀 Expected behavior

It should not show the text a password is not required you are in no auth mode.

### 😓 Actual Behavior

It showed that a password is not required you are in no auth mode in cloudflared

### 🐻 Uptime-Kuma Version

1.21.2

### 💻 Operating System and Arch

Linux (Replit)

### 🌐 Browser

Firefox

### 📝 Relevant log output

```shell
There is no relevant log in consle or terminal
```

**Comment by louislam** [comment]
Uptime Kuma do not support on Replit. There are a lot of weird issues on Replit which had been reported by other users already.
