### ISSUE TITLE
Telegram notification not working

### ISSUE THREAD

**Issue by maxicasa** [louislam/uptime-kuma#3122]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### Description

I have created a `Telegram` notification but when I click on `Test` button an error occurs:

`Cannot read properties of undefined (reading 'data')`

See the screenshot:
![image](https://user-images.githubusercontent.com/2181924/235964464-50dbcc08-cb8a-4095-9e77-60ac141aeaae.png)

### 👟 Reproduction steps

Insert `Bot token`;
Insert `Chat ID`;

Click on `Test` button.

### 👀 Expected behavior

Send a notification without errors.

### 😓 Actual Behavior

Nothing is sent and an error occurs:

`Cannot read properties of undefined (reading 'data')`

### 🐻 Uptime-Kuma Version

1.21.2

### 💻 Operating System and Arch

Debian GNU/Linux 11 (bullseye)

### 🌐 Browser

Brave Version 1.50.121 Chromium: 112.0.5615.138

### 🐋 Docker Version

Docker version 23.0.5

**Comment by maxicasa** [comment]
There was a problem with the dns configuration in my docker configuration.
Modifying the `docker-compose.yml` with `network_mode: host` solves the problem.

Issue closed.

**Comment by chakflying** [comment]
Incorrect error parsing fixed in 0eaaa8b6fab88d75c8a7211001b6194b191706cf.
