### ISSUE TITLE
Cant monitor my own (sub)domain(s)

### ISSUE THREAD

**Issue by Nilex** [louislam/uptime-kuma#3125]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

Hi guys,

Ive tested Uptime Kuma a couple of months ago with docker on my Synology NAS.
Recently, Ive started a couple of services, eg, plex, a public minecraft server. I would like to know if these services ever go down, so I have decided to install and use Uptime Kuma.
I can ping my devices fine but unfortunately my Uptime Kuma times out when I try to monitor them by URL.
Ive tested it on another device, same issue.. I also tested it on the demo from git, where it seems to work just fine.. so it must be something on my own network.. The network config in docker is bridged
Does any1 have any idea why i cant contact my own subdomains to monitor them, Id appreciate any help 

Thank you

### 📝 Error Message(s) or Log

Just timeouts

### 🐻 Uptime-Kuma Version

1.21.2

### 💻 Operating System and Arch

Synology DSM7

### 🌐 Browser

Google Chrome

### 🐋 Docker Version

20.10.3-1308

### 🟩 NodeJS Version

14.20.1-1012

**Comment by seigieu** [comment]
Login into docker container and check `tracert` to these services. By IP and by domain.
Also check ping to domains and see if IP addresses are translated properly.

**Comment by rezzorix** [comment]
Could be that you cannot loopback to your own ip address. Search for “hairpin NAT” - depending on your router it can just a simple setting, or it isnt possible at all.
