### ISSUE TITLE
Notifications

### ISSUE THREAD

**Issue by Bigguy3** [louislam/uptime-kuma#3126]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

The Uptime Kuma Notifications send me only "down" and not "Up" to the mail

### 🐻 Uptime-Kuma Version

1.21.2

### 💻 Operating System and Arch

Ubuntu 20.04.6

### 🌐 Browser

Google chrome

**Comment by kokofixcomputers** [comment]
Which notification type are you using? (Email, Instagram, etc.)

**Comment by Bigguy3** [comment]
EMAIL

**Comment by CommanderStorm** [comment]
What is the template for the monitor? is this a duplicate of #3184 ?
