### ISSUE TITLE
Load time issue

### ISSUE THREAD

**Issue by Disthene** [louislam/uptime-kuma#3127]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

Hello,

I have more than 100 urls now in uptime, and I'm facing issues to retrieve the information. Interface is working smoothly, I can access different pages and menu without any problem.
But I have to wait many minutes, sometime more than 15 to be able to retrieve the different monitors/logs and maintenances windows.
Any idea why this is happening ? Even when I restart the server I face the same issue. I installed it directly on a linux server with pm2. Any help is welcome.
![image](https://user-images.githubusercontent.com/44158442/236473097-7fb42347-ec45-4f93-8639-824a27933972.png)

Regards,

### 🐻 Uptime-Kuma Version

1.20.1

### 💻 Operating System and Arch

Ubuntu 20.04 x64

### 🌐 Browser

Google Chrome

### 🐋 Docker Version

/

**Comment by Disthene** [comment]
Seems to be related to the size of the database, it seems it doesn't like keeping the datas for a year and a 2GB size is way too big.
Any solution on a way to keep datas in a readable way for a year would be awesome. Any proposale ?

Regards,

**Comment by CommanderStorm** [comment]
Just to make shure:
- Given that the "New Update" button is showing. Have you tried this on the most up to date version of Uptime Kuma?
- Have you tried to Vacuum your database? When was your Database created?
  ![image](https://github.com/louislam/uptime-kuma/assets/26258709/5d9b0827-1f83-4d58-94b8-13470b1cfe1f)
