### ISSUE TITLE
Trigger notification based on db query output 

### ISSUE THREAD

**Issue by Remy541** [louislam/uptime-kuma#3128]
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

New Monitor, UI Feature

### 🔖 Feature description

I'd like to monitor a process that ultimately puts new data in a database. Sometimes new information is not provided by a 3rd party, and thus this process is not able to insert new data into a certain database. 

### ✔️ Solution

The ability to be notified if a certain sql query has a certain outcome. 
Something like the following:
```sql
SELECT DATEDIFF(NOW(), latest_insert_timestamp) <= 1 AS is_recent
FROM (
  SELECT MAX(inserttimestamp) AS latest_insert_timestamp
  FROM my_table
) latest_entry;
```

**Comment by CommanderStorm** [comment]
@Remy541 
I think this is a duplicate of https://github.com/louislam/uptime-kuma/issues/2342
If you agree, could you please close this Issue, as duplicates only create immortal zombies and are really hard to issue-manage?
If not, what makes this issue unique enough to require an additional issue? (Could this be integrated into the issue linked above?) ^^

**Comment by Remy541** [comment]
@CommanderStorm Although I searched for similar issues, I hadn't found the one you linked, but I think you are right. The issues are quite similar, so I will close this one. Thanks for the heads up.

**Comment by CommanderStorm** [comment]
Thanks ^^
