### ISSUE TITLE
Cannot verify 2fa token

### ISSUE THREAD

**Issue by kokofixcomputers** [louislam/uptime-kuma#3129]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### Description

When i backup the data folder and moved it to another place with 2fa enabled the 2fa does not work. It just asks for 2fa token but when type it in it says wrong token. But when i type the token in the original one (Which is the one that i copied the data folder from) It works. The only way i could sign in is to run the remove 2fa tool.

### 👟 Reproduction steps

When i backup the data folder and moved it to another place with 2fa enabled the 2fa does not work. It just asks for 2fa token but when type it in it says wrong token. But when i type the token in the original one (Which is the one that i copied the data folder from) It works.

### 👀 Expected behavior

It should let me in to the dashboard

### 😓 Actual Behavior

It says wrong token.

### 🐻 Uptime-Kuma Version

1.21.2

### 💻 Operating System and Arch

Linux (Replit)

### 🌐 Browser

Chrome

**Comment by chakflying** [comment]
Are the clocks running accurate and in-sync?

**Comment by kokofixcomputers** [comment]
Yes

**Comment by kokofixcomputers** [comment]
They are in sync i just synced it with a time server

**Comment by louislam** [comment]
Uptime Kuma do not support on Replit. There are a lot of weird issues on Replit which had been reported by other users already.
