### ISSUE TITLE
Cannot connect to uptime kuma in brave

### ISSUE THREAD

**Issue by kokofixcomputers** [louislam/uptime-kuma#3131]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### Description

When i go to uptime kuma in brave it works perfectly. After a few minutes of requests sending to uptime kuma server it stops working.

Screenshots:

Message:

<img width="693" alt="Screen Shot 2023-05-06 at 2 58 39 PM" src="https://user-images.githubusercontent.com/113046561/236648130-ccd6671a-64b3-447e-8182-2d0c3dde88c0.png">

Browser console:

<img width="2240" alt="Screen Shot 2023-05-06 at 3 01 17 PM" src="https://user-images.githubusercontent.com/113046561/236648183-142f9ba7-1203-43d4-b1b5-a12836c0a6cd.png">

Piesocket testing connection:

<img width="2240" alt="Screen Shot 2023-05-06 at 3 03 27 PM" src="https://user-images.githubusercontent.com/113046561/236648250-f269d5bc-906e-4071-a871-eae586c0cb11.png">

And Piesocket connecting to other websocket servers:

<img width="2240" alt="Screen Shot 2023-05-06 at 3 04 37 PM" src="https://user-images.githubusercontent.com/113046561/236648279-0f576fa8-b364-44d4-80b8-780e9979e4f0.png">

In other browsers like firefox or chrome it works perfectly.

The error api key thing is not related to this.

### 👟 Reproduction steps

When i go to uptime kuma in brave it works perfectly. After a few minutes of requests sending to uptime kuma server it stops working.

### 👀 Expected behavior

It should connect and let me use uptime kuma

### 😓 Actual Behavior

It could not connect to uptime kuma

### 🐻 Uptime-Kuma Version

1.21.2

### 💻 Operating System and Arch

Linux (Replit)

### 🌐 Browser

Brave

**Comment by rezzorix** [comment]
Not a bug.

If I am not wrong then this has to do with Brave Shield.
Websocket connections in Brave are limited to 10 or 30(?); more than that will be blocked.

You may disable shield to see if it works afterwards:
https://community.brave.com/t/disable-brave-shield-for-good/400791

**Comment by kokofixcomputers** [comment]
No disabling brave shields did not work.

**Comment by louislam** [comment]
Uptime Kuma do not support on Replit. There are a lot of weird issues on Replit which had been reported by other users already.
