### ISSUE TITLE
How to update docker after installing from Linode Marketplace

### ISSUE THREAD

**Issue by freakytoad1** [louislam/uptime-kuma#3133]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

The Linode marketplace install has been great for getting up and going but I can't find any documentation on how to update the installed version past the initial install. I'm weary to run the [general update steps on the wiki here](https://github.com/louislam/uptime-kuma/wiki/%F0%9F%86%99-How-to-Update) in case they don't match the paths that Linode used to set it up.

Any suggestions?

### 🐻 Uptime-Kuma Version

1.19.4

### 💻 Operating System and Arch

Ubuntu 20.04

### 🌐 Browser

Firefox

### 🐋 Docker Version

Docker version 23.0.5, build bc4487a

**Comment by freakytoad1** [comment]
Specifically referring to this guide on the Linode Marketplace https://www.linode.com/docs/products/tools/marketplace/guides/uptime-kuma/

Near the bottom it states. But I'm not sure how it installed, what parameters it used for Docker, or where the local directories are mapped.

```
Note
Currently, Linode does not manage software and systems updates for Marketplace Apps. 
It is up to the user to perform routine maintenance on software deployed in this fashion.
```

**Comment by louislam** [comment]
Some commands could assist you to find some clues:
- docker container ls
- pm2 monit
- node -v

Some paths:
- /opt
- /home
- /root
- /var/lib/docker/volumes

**Comment by Obereigwe1** [comment]
Send an email to ***@***.***

**Comment by klecka** [comment]
I'd like to know as well.

**Comment by CommanderStorm** [comment]
As Louis stated, you can get these parameters from docker or look at your disk.
If you have problems with the steps, more context is nessesary, as we don't maintain the linode marketplace and [I can't find where the concrete app is configured](https://github.com/linode/Marketplace-Apps)

**Comment by muhubi** [comment]
Thank you @freakytoad1
