### ISSUE TITLE
Windows in uptime kuma

### ISSUE THREAD

**Issue by kokofixcomputers** [louislam/uptime-kuma#3136]
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

UI Feature

### 🔖 Feature description

It would be nice to make something like windows in uptime kuma on the same website so when you press help it opens a window not a browser window or pop up.

### ✔️ Solution

It would make a pop up not a browser pop up window or browser window or tab

**Comment by CommanderStorm** [comment]
What? Could you please explain what you would like more clearly?
I don't understand what you mean by `window not a browser window or pop up`?
The solution you stated is also contradictory with the feature you want (at least that is how I parse this request)

Please provide examples of what you mean.

**Comment by CommanderStorm** [comment]
I am going to close this given that I have good idea what this issue is refering to and @kokofixcomputers has not responded for the request for clarification
