### ISSUE TITLE
How I Reset Uptime-Kuma

### ISSUE THREAD

**Issue by JohanChungus** [louislam/uptime-kuma#3137]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

I Forgor Username And Password

### 🐻 Uptime-Kuma Version

1.11.3

### 💻 Operating System and Arch

Debian

### 🌐 Browser

Chrome Android

**Comment by cyril59310** [comment]
hi, to reset the password you can follow the step indicated here
https://github.com/louislam/uptime-kuma/wiki/Reset-Password-via-CLI

**Comment by JohanChungus** [comment]
What about username?

**Comment by cyril59310** [comment]
the user name is indicated when resetting the password

**Comment by cyril59310** [comment]
The only way to change the username is by editing the db file, but it is not recommended.

**Comment by JohanChungus** [comment]
Hmm ok I will close the comment

**Comment by pointout** [comment]
I would like to reopen this: 
I have changed the data-directory by env-variable. If I run the password-reset, the script does not find the data directory:
```
== Uptime Kuma Reset Password Tool ==
Connecting the database
2024-09-10T08:14:11+00:00 [SERVER] INFO: Data Dir: ./data/
2024-09-10T08:14:11+00:00 [DB] WARN: ENOENT: no such file or directory, open 'data/db-config.json'
2024-09-10T08:14:11+00:00 [DB] INFO: Database Type: sqlite
2024-09-10T08:14:11+00:00 [SERVER] INFO: Copying Database
Error: user not found, have you installed?
2024-09-10T08:14:11+00:00 [DB] INFO: Closing the database
2024-09-10T08:14:13+00:00 [DB] INFO: Database closed
Finished.
```
The data directory is one level up (`../data`) and I am using mariadb.

How can I address the right data directory?

**Comment by pointout** [comment]
I ran `npm run reset-password`. How to specify the data directory?

**Comment by CommanderStorm** [comment]
On Linux terminals, this is done via 
```bash
DATA_DIR=whatever npm run whatever
````
