### ISSUE TITLE
Uptime Kuma causes system unstable on Windows

### ISSUE THREAD

**Issue by louislam** [louislam/uptime-kuma#3138]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### Description

During the development of Uptime Kuma, at some point, my PC's network is becoming unstable. All monitors went down and notifications could not be sent out. Firefox/Chrome cannot load any web page. 

- Firefox: no response
- Chrome: ERR_CONNECTION_FAILED

After kill the process, everything is back to normal. 

Since recently I updated several things such as Reltek Lan driver, Windows update, Intellij IDEA, Node.js to 20. So I am not sure which part causes the issue.

But if you have such symptom, please let me know here. 

![](https://github.com/louislam/uptime-kuma/assets/1336778/0ddee832-ec31-44ad-b9a7-6d004fd4e24d)

![image](https://github.com/louislam/uptime-kuma/assets/1336778/e8aa3544-cb17-4347-b729-07992e8bc43b)

### 👟 Reproduction steps

TBC

### 👀 Expected behavior

No such issue

### 😓 Actual Behavior

Network unstable

### 🐻 Uptime-Kuma Version

dev

### 💻 Operating System and Arch

Windows 11 Version 22H2 (22621.1635)

### 🌐 Browser

Firefox or Chrome

### 🟩 NodeJS Version

20.1.0

**Comment by louislam** [comment]
It seems that it is currently having issue on Node.js 20.

After uninstalled Node.js 20 and install Node.js 18, the issue is gone.

**Comment by kokofixcomputers** [comment]
I sent a issue to node!

**Comment by louislam** [comment]
Actually, I am still trying to find which part causes the issue. I tested HTTP monitors only and cannot reproduce the issue.

So it could be other monitor types' issue.

**Comment by kokofixcomputers** [comment]
Node said there is simply no way that node is responsible for the behavior described in that issue. Maybe node triggers a bug in the operating system but you should report that to your OS vendor, not here.

**Comment by louislam** [comment]
Yes, it is quite normal they closed it, as there is no clue to prove and reproduce yet. 
Let me find the root cause first.

**Comment by louislam** [comment]
Previously, I was facing this issue with both my Windows PCs. 

I have tested again with Node.js 20.4.0 and Uptime Kuma 1.22.1 today. I haven't encountered that issue again, so perhaps it has been fixed. However, I'm still unsure which part was causing the problem.
