### ISSUE TITLE
MySQL/MariaDB driver: Check is a variable is specific value

### ISSUE THREAD

**Issue by ilgrandetia** [louislam/uptime-kuma#3140]
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

New Monitor

### 🔖 Feature description

I would like a check on the value of a variable to be implemented.

### ✔️ Solution

There should be the ability to set a specific value into uptime kuma interface (e.g., ON, OFF, 1, 0, etc..) for checking if that variable, normally searched with a select (e.g., SELECT @@global.read_only; the result can be 0 or 1), is egual to that field.
In that case it sends the notification if the value is equal to the set variable (or not if configured in "inverted mode".

### ❓ Alternatives

Actually the driver works only with time check on execute of SQL command.
Alternative is monitor the service is up with TCP port check.

**Comment by titanventura** [comment]
Would like to work on this !

**Comment by CommanderStorm** [comment]
@ilgrandetia
We are consolidating duplicate issues a bit to make issue management easier.
I think, we should track this issue in #2342 as there is no difference
⇒ I am going to close this as a duplicate.
