### ISSUE TITLE
Windows exe error

### ISSUE THREAD

**Issue by Zaid-maker** [louislam/uptime-kuma#3142]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### Description

I download the Windows exe from README and when i extract it and open it it gives an error.

![image](https://github.com/louislam/uptime-kuma/assets/53424436/6c3f2e5a-f1a8-4b3c-803b-283bf2b6a5c8)

### 👟 Reproduction steps

I didn't know

### 👀 Expected behavior

Nope

### 😓 Actual Behavior

It should work i guesss

### 🐻 Uptime-Kuma Version

1.21.0

### 💻 Operating System and Arch

Windows 11

### 🌐 Browser

Desktop exe

### 🟩 NodeJS Version

v 16

**Comment by louislam** [comment]
It seems that your antivirus blocked it. Which antivirus are you using?

I think it is false positive. The source code is here:
https://github.com/louislam/uptime-kuma/tree/master/extra/exe-builder

**Comment by Zaid-maker** [comment]
> It seems that your antivirus blocked it. Which antivirus are you using?
> 
> I think it is false positive. The source code is here: https://github.com/louislam/uptime-kuma/tree/master/extra/exe-builder

Regular windows Anti virus Windows Defender

**Comment by louislam** [comment]
Strange, it is OK in my side. Can you check the log of Windows Defender?

![image](https://github.com/louislam/uptime-kuma/assets/1336778/524260f0-0eb9-4894-a7ef-351ff9cfa20f)

**Comment by Zaid-maker** [comment]
> Strange, it is OK in my side. Can you check the log of Windows Defender?
> 
> ![image](https://user-images.githubusercontent.com/1336778/237448672-524260f0-0eb9-4894-a7ef-351ff9cfa20f.png)

you were the antivirus blocking it and this time got thread found notifications, its works with disabling the antivirus.

![image](https://github.com/louislam/uptime-kuma/assets/53424436/fe94545a-c93c-4bcb-9a8a-502504190211)

**Comment by chakflying** [comment]
Unfortunately a self-unpacking .exe fits the signature of a virus too well.
![image](https://github.com/louislam/uptime-kuma/assets/3271800/c30da929-4a17-4cde-a91f-ab67f1f47c09)

**Comment by Zaid-maker** [comment]
> Unfortunately a self-unpacking .exe fits the signature of a trojan too well.
> 
> ![image](https://github.com/louislam/uptime-kuma/assets/3271800/c30da929-4a17-4cde-a91f-ab67f1f47c09)
> 

So is this fixable?

**Comment by louislam** [comment]
Portable 1.0.1

https://github.com/louislam/uptime-kuma/files/11886108/uptime-kuma-win64-portable-1.0.1.zip

It should be better.

**Comment by rallisf1** [comment]
> Portable 1.0.1
> 
> https://github.com/louislam/uptime-kuma/files/11886108/uptime-kuma-win64-portable-1.0.1.zip
> 
> It should be better.

The AV no longer complaints, but the installation script has an issue:
![error](https://github.com/louislam/uptime-kuma/assets/8031572/01aeec22-7090-420a-9792-d32f0de5a4ad)

That was on a Win 10 x64 machine with no nodejs installed. I added the ./node folder to the PATH variable and it worked.

**Comment by Zaid-maker** [comment]
> > Portable 1.0.1
> > 
> > https://github.com/louislam/uptime-kuma/files/11886108/uptime-kuma-win64-portable-1.0.1.zip
> > 
> > It should be better.
> 
> The AV no longer complaints, but the installation script has an issue:
> ![kuma-error](https://github.com/louislam/uptime-kuma/assets/8031572/042eea91-9150-4c92-9b12-64bbac719d43)
> 
> 
> That was on a Win 10 x64 machine with no nodejs installed. I added the ./node folder to the PATH variable and it worked. 

I don't think you have to manually add nodejs to Path it's automatically add it.

**Comment by louislam** [comment]
> > Portable 1.0.1
> > https://github.com/louislam/uptime-kuma/files/11886108/uptime-kuma-win64-portable-1.0.1.zip
> > It should be better.
> 
> The AV no longer complaints, but the installation script has an issue: ![kuma-error](https://user-images.githubusercontent.com/8031572/259077911-042eea91-9150-4c92-9b12-64bbac719d43.png)
> 
> That was on a Win 10 x64 machine with no nodejs installed. I added the ./node folder to the PATH variable and it worked.

#2606

**Comment by lonnylippold** [comment]
Just had my infosec say Uptime-Kuma (windows) came up as malwae/trojan in Crowdstrike and I am not allowed to run it unless I can prove it is a false positive
