### ISSUE TITLE
RSS Feed not working

### ISSUE THREAD

**Issue by adm2k** [louislam/uptime-kuma#3147]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

This feed is failing - it has been working until a few hours ago:
https://openrss.org/github.com/louislam/uptime-kuma/issues

![image](https://github.com/louislam/uptime-kuma/assets/120423301/955baefa-9975-447e-b5e3-1da4eb549121)

### 🐻 Uptime-Kuma Version

Version: 1.21.2

### 💻 Operating System and Arch

Ubuntu 22.04

### 🌐 Browser

Version 113.0.5672.114 (Official Build) (64-bit)

**Comment by CommanderStorm** [comment]
The link you provided works. Could you elaborate on what exactly is not working?
![image](https://github.com/louislam/uptime-kuma/assets/26258709/f8145ea7-856f-4203-97ae-85451eab96c5)

**Comment by adm2k** [comment]
You are correct, that is working now. I have no idea why it was failing validation as I showed in the original screen shot.

**Comment by CommanderStorm** [comment]
Likely an issue with the RSS feed provided by GitHub or an issue with openrss.com
⇒ Unless this is connected with `uptime-kuma`, please close this issue 😉

**Comment by adm2k** [comment]
Issue appears to have resolved itself. RSS feed is now validating. I am closing this issue.
