### ISSUE TITLE
Monitor display EHOSTUNREACH and DOWN when is UP

### ISSUE THREAD

**Issue by DavKiller** [louislam/uptime-kuma#3151]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

Hi:
I have a problem with a a few monitors, For a few days, an error appears (and marking the monitor as down) but it is incorrect, the machine is up.
The monitors are monitoring some printers, but it seems strange to me that being on the same network, some printers (of the same model) work and it is clearly seen when they are active and when they are not, and these cannot.

Sorry if my English is bad :(

### 📝 Error Message(s) or Log

![imagen](https://github.com/louislam/uptime-kuma/assets/65242580/ea82409a-47e8-42a9-b3d9-01796eac4daf)

### 🐻 Uptime-Kuma Version

1.21.2

### 💻 Operating System and Arch

Docker

### 🌐 Browser

Firefox 112.0.2

### 🐋 Docker Version

Portainer

### 🟩 NodeJS Version

16.19.1

**Comment by DavKiller** [comment]
I have tried, I have it in 9 trys if I don't remember bad, and i can confirm you is not the cable/software because I have the same model in other site and it's works perfectly.

**Comment by iamalexblue** [comment]
Got same error
![IMG_4868](https://github.com/louislam/uptime-kuma/assets/41639269/2ac351d0-af41-485a-a2ff-a0e82d619d38)
 It will Intermittently up and down, even through sites didn't down

**Comment by CommanderStorm** [comment]
> i can confirm you is not the cable/software because I have the same model in other site and it's works perfectly.

Why are you shure about this?
Have you exchanged printers? Does the problem stay with the printer/ the line? 

@iamalexblue from your screenshot some of these sites are via a DDNS. Have you checked that this is the case? Heisenbugs dropouts can be hard to debug remotely, please open another issue with full context (linking this issue), to keep this managable :)

**Comment by iamalexblue** [comment]
Sorry for my rude reply. I just saw some issues that looks familiar then commented on it.

And thanks for ur reply. Yes some of my sites are mapped through DDNS, but actually they work fine at most time. Eventually, after testing I found that it might be related to the monitoring configuration and the hardware size allocated to Docker（Free Hosting platform always has many limit,so I decide to migrate uptime_kuma to azure container apps)


> > i can confirm you is not the cable/software because I have the same model in other site and it's works perfectly.
> 
> 
> 
> Why are you shure about this?
> 
> Have you exchanged printers? Does the problem stay with the printer/ the line? 
> 
> 
> 
> @iamalexblue from your screenshot some of these sites are via a DDNS. Have you checked that this is not the issue? Heisenbugs can be really hard to debug remotely, please open another issue with full context (linking this issue), to keep this managable :)

**Comment by CommanderStorm** [comment]
> Sorry for my rude reply. I just saw some issues that looks familiar then commented on it.

No worries, was not percieved that way.

> And thanks for ur reply. Yes some of my sites are mapped through DDNS, but actually they work fine at most time. Eventually, after testing I found that it might be related to the monitoring configuration and the hardware size allocated to Docker（Free Hosting platform such as Pikapods always has many limits but miss some features, so I decide to migrate uptime_kuma to azure container apps)

Interesting. What kind of error messages did you get? Could this be the underlying issue in this Thread too?

**Comment by DavKiller** [comment]
> > i can confirm you is not the cable/software because I have the same model in other site and it's works perfectly.
> 
> Why are you shure about this?
> Have you exchanged printers? Does the problem stay with the printer/ the line? 
> 
> @iamalexblue from your screenshot some of these sites are via a DDNS. Have you checked that this is not the issue? Heisenbugs can be really hard to debug remotely, please open another issue with full context (linking this issue), to keep this managable :)

**_Sorry in advance if my English is bad_**

I am sure of it because from the computer I can do a ping and it does it without returning an error.

I'm waiting tomorrow to change the printer for another device and test if it really is the cable, but I highly doubt it.
 
PS: I just remembered that the printers were always located in the same place and from x day the error started. I'll try to do tests on Monday and I'll ask here again.

**Comment by DavKiller** [comment]
I think the problem is the firewall of the Docker container...?
I tried to do a ping in the container terminal but it doesn't work, I don't understand why those specific IPs cannot ping from one day to the next, because when the container was raised, all the monitors were working.

_That's all the info i have for now for this error, probably i will try to re-install or install it directly in a virtual machine if the problem persist_
