### ISSUE TITLE
How I Can config Time Zone of Time in Line Notifications Message ?

### ISSUE THREAD

**Issue by banpot408** [louislam/uptime-kuma#3153]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

How I Can config Time Zone of Time in Line Notifications Message ?
Now can't change still show only UTC Time

### 🐻 Uptime-Kuma Version

Version: 1.21.3

### 💻 Operating System and Arch

Ubuntu 20.04 x86

### 🌐 Browser

Chrome

**Comment by CommanderStorm** [comment]
What is your deployment?
How have you tried setting the timezone? (what are the steps you tried to solve this? What were the results?)

**Comment by Roomiiaan** [comment]
How can I set the time zone in notifications? Only showing UTC 😥

**Comment by CommanderStorm** [comment]
Please answer the question I asked, otherwise helping you is really difficult.

>What is your deployment? (Docker/Nodejs/...?)
>How have you tried setting the timezone? (what are the steps you tried to solve this? What were the results?)

![image](https://github.com/louislam/uptime-kuma/assets/26258709/a06b9910-783c-4473-bd3d-5232bda5101b)

**Comment by Roomiiaan** [comment]
I run kuma on my docker! I tried set the time zone in settings of kuma and on the hostsystem (debian 10)Am 29.05.2023 um 13:48 schrieb Frank Elsinga ***@***.***>:﻿
Please answer the question I asked, otherwise helping you is really difficult.

What is your deployment? (Docker/Nodejs/...?)
How have you tried setting the timezone? (what are the steps you tried to solve this? What were the results?)

**Comment by CommanderStorm** [comment]
What notification provider are you using? (where exactly are you seeing the wrong timezone? Please provide screenshots)
Can you also provide a screenshot of the settings panel?

What happens when you run with timezone+localtime mounted?

```bash
docker run -p 3001:3001 -v /etc/timezone:/etc/timezone -v /etc/localtime:/etc/localtime louislam/uptime-kuma:latest
```

**Comment by Roomiiaan** [comment]
> ```shell
> /etc/timezone:/etc/timezone
> ```

I also tried to mount the time zone... Without success :( 
![grafik](https://github.com/louislam/uptime-kuma/assets/31469387/09bb3aad-9f35-4d09-a6c8-88538f77283a)
Still showing UTC time (time zone is utc+2 Europe/Berlin)

**Comment by CommanderStorm** [comment]
@banpot408 @Roomiiaan 
This is something, that is hardcoded in the Notification template (example of Line):
https://github.com/louislam/uptime-kuma/blob/0735f12d19f3e0caa88284ea4eb1de88456441b6/server/notification-providers/linenotify.js#L25-L35

Opinions if this should to be changed? 
I would argue that knowing when (in UTC) the post was made could be useful. The time in your local time is written at the bottom.
CC: @chakflying

**Comment by Roomiiaan** [comment]
I understand what you mean @CommanderStorm I do think, however, that misunderstandings can arise. In Germany we are far away from UTC and didn't need this information at all.
Maybe you can add a button when creating notifications: "Use configured time zone from settings"

**Comment by banpot408** [comment]
> I understand what you mean @CommanderStorm I do think, however, that misunderstandings can arise. In Germany we are far away from UTC and didn't need this information at all. Maybe you can add a button when creating notifications: "Use configured time zone from settings"

i am agree with @Roomiiaan

**Comment by louislam** [comment]
You cannot config currently. Since the server timezone was added after most notifications, they are hardcoded UTC. They need to be updated in order to display the server timezone, like this: https://github.com/louislam/uptime-kuma/pull/3152/files
