### ISSUE TITLE
Exit status dependent push monitors

### ISSUE THREAD

**Issue by kzshantonu** [louislam/uptime-kuma#3155]
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

Other

### 🔖 Feature description

URL parameter under the push monitor type to indicate a Cron job failed or exit successfully 

### ✔️ Solution

Hoping healthchecks-type 0 success and any other number to mark monitor as down. Like `cronjob-script; curl https://kuma.url/uuid/$?` 

### ❓ Alternatives

The default 'OK' message type could accept a numerical exit code

**Comment by CommanderStorm** [comment]
Why don't you conditionally `push`  status at the end of the script to kuma?

```python
if success:
  push_to_uptime_kuma()
```

Reasoning:
- if a cronjob fails, this has the same effect as it never running
- If you use the `push` status, this warn you of both faliours.
- This way you have more controll about what you consider a faliour and a success

**Comment by GitHubQueenn** [comment]
> Why don't you conditionally `push` status at the end of the script to kuma?
> 
> if success:
>   push_to_uptime_kuma()
> 
> Reasoning:
> 
>     * if a cronjob fails, this has the same effect as it never running
> 
>     * If you use the `push` status, this warn you of both faliours.
> 
>     * This way you have more controll about what you consider a faliour and a success

So, if I want to monitor if a cronjob ran (or even failed), would I add that code to the bottom of my script randomly, or?

**Comment by CommanderStorm** [comment]
> would I add that code to the bottom of my script randomly

What do you mean by randomly?

You can monitor if recurring external events via push monitors yes if that is waht you are asking.
