### ISSUE TITLE
 [RATE-LIMIT] INFO: remaining requests: 20

### ISSUE THREAD

**Issue by ARR4NN** [louislam/uptime-kuma#3157]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

 [RATE-LIMIT] INFO: remaining requests: 20

### 📝 Error Message(s) or Log

 [RATE-LIMIT] INFO: remaining requests: 20

### 🐻 Uptime-Kuma Version

it auto pulls from github

### 💻 Operating System and Arch

Ubuntu 20.04

### 🌐 Browser

Chrome

### 🐋 Docker Version

latest

### 🟩 NodeJS Version

16

**Comment by ARR4NN** [comment]
and my page is solid white 
![image](https://github.com/louislam/uptime-kuma/assets/70060472/5e2f14c9-8c33-4caf-b811-6155d0f1118f)

**Comment by unitrade** [comment]
Did you solve the problem?

**Comment by oprey123** [comment]
I am having the same issue, any input would be helpful.

**Comment by CommanderStorm** [comment]
With the context that exists in this issue all of you are likely experiencing different issues. (there is not enough context given to match)

Remember that if no good context is given, expecting good help is unlikely.
Remarks like `it auto pulls from github` as a version or a quite generic logging message with no additional context definitively not enough to say what has happened and if this is a problem on our side/...

**Comment by tokar86a** [comment]
I have notes the same thing here. What is it all about?

**Comment by CommanderStorm** [comment]
Please refer to my comment from above:

> if no good context is given, expecting good help is unlikely

A generic answer:

The log message indicates that an action has been performed against a rate-limited endpoint.
This is nothing to be conceared about, unless you are actually spamming a rate limited endpoint.

See
https://github.com/louislam/uptime-kuma/blob/b25ac55a2f0702bbbd8b7d7fba736e962ea10d97/server/rate-limiter.js#L27

> [!NOTE]
> An enhancement might be to not warn on the first rate-limited request.
Our contribution guide is here: https://github.com/louislam/uptime-kuma/blob/master/CONTRIBUTING.md

**Comment by stigglitch** [comment]
Run this one-liner inside the container to disable the flood, survives reboots. Your system might explode, be warned!

sed -i '/log.info("rate-limit", "remaining requests: " + remainingRequests);/s#^#//#' /app/server/rate-limiter.js
