### ISSUE TITLE
Remote docke host with TLS

### ISSUE THREAD

**Issue by awptechnologies** [louislam/uptime-kuma#3158]
I'm trying to use uptime kuma to monitor my docker host using tls.  When connecting portainer to docker socket with tls there is a drop down to add the ca.pem, cert.pem, and key.pem.  how would I go about connecting uptime kuma to docker in the same way.

**Comment by kzshantonu** [comment]
Hi I have the same question

**Comment by CommanderStorm** [comment]
@kzshantonu please refrain from necroposting on issues which violated the community guidelines.
Please also search for related issues (like #2675) in the future 😉 
Managing hundreds of issues is just unmanageable otherwise.

**Comment by kzshantonu** [comment]
@CommanderStorm my bad, I searched and commented
