### ISSUE TITLE
Subcategories

### ISSUE THREAD

**Issue by MaximilianGT500** [louislam/uptime-kuma#3159]
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

UI Feature

### 🔖 Feature description

A way to make for a group on the status page subgroups, I have the problem that I have many APIs and proxies to a group and this looks very messy.

### ✔️ Solution

Create a drop-down menu where you can add the service

**Comment by CommanderStorm** [comment]
Is this the same issue as the one that will be adressed in #2693 (i.e. a duplicate of the other issues mentioned there?)
This reads very similar, please elaborate on the difference or close this issue 😉
