### ISSUE TITLE
Status code 403

### ISSUE THREAD

**Issue by picarda** [louislam/uptime-kuma#3165]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

Hello,

1. I can browse all my websites with all my devices. (https://alainpicard.ca)
2. However, I get for all of them a 403 in the panel. 
3. They are on AWS EC2
4. CloudFlare as CDN

### 📝 Error Message(s) or Log

Request failed with status code 403

### 🐻 Uptime-Kuma Version

1.21.3

### 💻 Operating System and Arch

Debian 11

### 🌐 Browser

Chrome 113.0.5672.93

### 🐋 Docker Version

20.10.5+dfsg1

**Comment by louislam** [comment]
OK in my side, but it is usually caused by Cloudflare's `Browser Integrity Check`.

![image](https://github.com/louislam/uptime-kuma/assets/1336778/68809e24-de9a-453a-8ef6-23a15628b5cf)

**Comment by picarda** [comment]
Hi, thank you for this.
What did the trick was to turn off this options:
Security/Bots/Bot Fight Mode  ---> Off.

Best!

**Comment by Leonetienne** [comment]
> Hi, thank you for this. What did the trick was to turn off this options: Security/Bots/Bot Fight Mode ---> Off.
> 
> Best!

thanks kinda dumb, that's in most cases the main point in using cloudflare

**Comment by ebkalderon** [comment]
Here's a better option that is _far_ less drastic: add a specific [IP Access Rule](https://developers.cloudflare.com/waf/tools/ip-access-rules/) allowing the source IP address of your Uptime Kuma instance. This bypasses the Bot Fight Mode rules of the Cloudflare WAF for that IP specifically, and that did the trick for me.
