### ISSUE TITLE
nginx: [warn] conflicting server name on 0.0.0.0:443, ignored

### ISSUE THREAD

**Issue by ShieldCoreLLC** [louislam/uptime-kuma#3166]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

Hello,
Recently i tried adding SSL to uptime kuma as i've had it on non ssl with a subdomain.
After i did everything, i got an error saying "nginx: [warn] conflicting server name on 0.0.0.0:443, ignored"
Nothing is running on 443 port, and it doesn't work for some reason.
Any fix? I'll put a picture of the configuration file.

### 📝 Error Message(s) or Log

![Screenshot_1](https://github.com/louislam/uptime-kuma/assets/133788067/ededb7a7-a1e7-41fc-bb48-3558a33f5a50)
![Screenshot_2](https://github.com/louislam/uptime-kuma/assets/133788067/a3206104-ae31-4942-97f4-e4b12803b778)

### 🐻 Uptime-Kuma Version

1.21.3

### 💻 Operating System and Arch

Debian 11

### 🌐 Browser

Google Chrome

### 🐋 Docker Version

Docker 23.0.6

**Comment by chakflying** [comment]
Do you have other files in `nginx/conf.d`? Maybe you have a duplicate configuration with the same server_name by accident.

**Comment by ShieldCoreLLC** [comment]
I fixed that issue, but now SSL is still not working, and i have to include ":3001" in order to access the uptime kuma.
What could it then?
![Screenshot_3](https://github.com/louislam/uptime-kuma/assets/133788067/59268172-958d-44cd-8051-b958db8a5b97)
![Uploading Screenshot_4.png…]()

**Comment by louislam** [comment]
Did you just fix it? I think it is fine now.

![image](https://github.com/louislam/uptime-kuma/assets/1336778/7359a4aa-7a56-4e1f-b6d7-1ac054999d76)

**Comment by ShieldCoreLLC** [comment]
Fixed the issue, it works now.
