### ISSUE TITLE
TypeError: l is null

### ISSUE THREAD

**Issue by Justman10000** [louislam/uptime-kuma#3168]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 👟 Reproduction steps

Installing via GitHub repository

### 👀 Expected behavior

Normales Verhalten

### 😓 Actual Behavior

No reacting and partially blackscreens

![grafik](https://github.com/louislam/uptime-kuma/assets/49990629/16163e3c-b0d9-40de-aad8-975a5bfbe25d)

### 🐻 Uptime-Kuma Version

SNAPSHOT (Using GitHub Repository)

### 💻 Operating System and Arch

Microsoft Windows 11

### 🌐 Browser

Mozilla Firefox 112.0.2

### 🟩 NodeJS Version

18.16.0

### 📝 Relevant log output

```shell
TypeError: l is null
    gh https://uptime.justman10000.de/assets/index.8134fe00.js:5
    v https://uptime.justman10000.de/assets/index.8134fe00.js:5
    ae https://uptime.justman10000.de/assets/index.8134fe00.js:5
    run https://uptime.justman10000.de/assets/index.8134fe00.js:5
    update https://uptime.justman10000.de/assets/index.8134fe00.js:5
    C https://uptime.justman10000.de/assets/index.8134fe00.js:5
    P https://uptime.justman10000.de/assets/index.8134fe00.js:5
    L https://uptime.justman10000.de/assets/index.8134fe00.js:5
    v https://uptime.justman10000.de/assets/index.8134fe00.js:5
    E https://uptime.justman10000.de/assets/index.8134fe00.js:5
    $ https://uptime.justman10000.de/assets/index.8134fe00.js:5
    k https://uptime.justman10000.de/assets/index.8134fe00.js:5
    v https://uptime.justman10000.de/assets/index.8134fe00.js:5
    E https://uptime.justman10000.de/assets/index.8134fe00.js:5
    $ https://uptime.justman10000.de/assets/index.8134fe00.js:5
    k https://uptime.justman10000.de/assets/index.8134fe00.js:5
    v https://uptime.justman10000.de/assets/index.8134fe00.js:5
    E https://uptime.justman10000.de/assets/index.8134fe00.js:5
    $ https://uptime.justman10000.de/assets/index.8134fe00.js:5
    k https://uptime.justman10000.de/assets/index.8134fe00.js:5
    v https://uptime.justman10000.de/assets/index.8134fe00.js:5
    ae https://uptime.justman10000.de/assets/index.8134fe00.js:5
    run https://uptime.justman10000.de/assets/index.8134fe00.js:5
    update https://uptime.justman10000.de/assets/index.8134fe00.js:5
    Ji https://uptime.justman10000.de/assets/index.8134fe00.js:5
    CM https://uptime.justman10000.de/assets/index.8134fe00.js:5
```

**Comment by Mikzas** [comment]
Same problem

**Comment by CommanderStorm** [comment]
What kind of installation did you do? (`Installing via GitHub repository` is not very specific 😅)

Given that there is an "Aktualisierung verfügbar" on the screen: Have you tried this in the latest version of uptime-kuma?

**Comment by Justman10000** [comment]
> What kind of installation did you do? (`Installing via GitHub repository` is not very specific 😅)

Well, I cloned the repo and installed the NPM packages via yarn.

> Given that there is an "Aktualisierung verfügbar" on the screen: Have you tried this in the latest version of uptime-kuma?

I have the latest! It's directly from the source code! You can't get more up to date than that

**Comment by louislam** [comment]
If you meant the latest source of this repo, you have to build the frontend manually first, since it is usually for development/testing only.

```
npm ci
npm run build
```

More info:
https://github.com/louislam/uptime-kuma/blob/master/CONTRIBUTING.md#build-the-frontend

**Comment by kokofixcomputers** [comment]
It's not the latest i see the update available blue button on the top.

**Comment by Justman10000** [comment]
> It's not the latest i see the update available blue button on the top.

It is also not the latest, but the Snapshot! but that is even newer! Kuma recognizes the Snapshot probably as outdated version, therefore the button

**Comment by Justman10000** [comment]
@louislam

**Comment by chakflying** [comment]
I find it strange that you expected to be offered assistance when you are unwilling to follow the official installation steps in the README or the development procedure in the contributing guide.

I think this issue should be closed.
