### ISSUE TITLE
Maintenance Webhook Updates

### ISSUE THREAD

**Issue by lohan136** [louislam/uptime-kuma#3170]
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

New Notification

### 🔖 Feature description

It would be nice if there were a feature where you could enable another webhook for any of the services it has and send a webhook when maintenance is coming up or is happening so users/clients could be updated about maintenance coming up or happening.

### ✔️ Solution

Making a way to add another webhook to be able to send maintenance notifications when maintenance is happening or maintenance is going on

**Comment by YukiInu** [comment]
Was also looking for this feature.

**Comment by CommanderStorm** [comment]
@YukiInu 
please show your support by adding tumb-ups to the issue and not commenting +1 or similar, as this makes issue management way harder.

I will be a bit harsh: This is the GitHub version of grafittis

**Comment by CommanderStorm** [comment]
@lohan136
We are consolidating duplicate issues a bit to make issue management easier.
I think, we should track this issue in #2462 as the webhook notification can be used in this way
⇒ I am going to close this as a duplicate.
