### ISSUE TITLE
SSH Tunneling

### ISSUE THREAD

**Issue by WisdomSky** [louislam/uptime-kuma#3172]
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

API

### 🔖 Feature description

Is there an option to use SSH Tunneling so we can access services which are not publicly accessible (from a remote server)?

We have mysql and mongodb services from other servers that are not externally accessible and I want to monitor it from an uptime kuma instance from different server.

### ✔️ Solution

none

**Comment by CommanderStorm** [comment]
I am assuming your environment is 

| internal | public |
|--------|--------|
| `database` | `backend`, `uptime-kuma` | 

And the `backend` also has an uptime monitor.

Would it not be better to include the status of the underlying infrastructure in the `backend` status?
Reasoning:
- This would alert you in case one of the infrastructure pieces goes down
- Databases are build like tanks nowadays.
- The logs from the backend will tell you clearly that the database is not healthy.
  => not a big downside to include this here
- Adding such a tunnel adds extra complexity which you will have to maintain.

Another option is to use the `push` monitor, i.e. the `database` tells `uptime-kuma` periodically that it is healthy. see #279

**Comment by WisdomSky** [comment]
Oh I did not know about this. I think this would be a great alternative to ssh tunneling.  Thanks for recommending me this option (push monitor).
 I think I missed this while browsing the list of monitors.
