### ISSUE TITLE
apprise

### ISSUE THREAD

**Issue by mxtthiasss** [louislam/uptime-kuma#3175]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [x] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

I setuped a notification with apprise for nextcloudtalk ( the nctalks://.. is working tested it on my local Maschine and the Maschine where uptime kuma is running ) 
Then I pressed the test notification button. It says the test notification was send but it never showed up in nextcloud talk 

### 📝 Error Message(s) or Log

there is no error in the logs. Uptime Kuma said it worked totally fine but it wasn't 

### 🐻 Uptime-Kuma Version

 1.21.3

### 💻 Operating System and Arch

Debain 11 x86

### 🌐 Browser

Firefox latest 

### 🐋 Docker Version

Docker 23.0.6

### 🟩 NodeJS Version

18.0.0

**Comment by CommanderStorm** [comment]
What do the logs of `apprise` say?

Can you be more specific about your setup? (how is it deployed)
What steps have you taken to try to debug this until this point? (what do you mean with `the nctalks://.. is working tested`?)

**Comment by mxtthiasss** [comment]
its deploy with docker on debain 11 . the riseapp got a pip package and with that I can test with it is working and it is working. and there are no logs from uptime Kuma it says it was successfully but it wasn't

**Comment by CommanderStorm** [comment]
Before I try to reproduce this:
Are you certain that the URLs in the `Apprise CLI` and uptime kuma match entirely? (no copy paste error, accidental tab/witespace, ...)

Can you screenshot the output (painting over the confidential areas in snipping tool/ ...)
- where `apprise` is defined in uptime kuma
- of the CLI with debug flags
- of the CLI without debug flags

**Comment by louislam** [comment]
Since Uptime Kuma is technically that calls the `apprise` command with your url `nctalks://..`, it should be identical.

I guess it could be some escaped characters in the CLI command which may not be necessary in the Uptime Kuma's input.

**Comment by mxtthiasss** [comment]
The url is to 100% the same i copied both from my text editor.
 
![image](https://github.com/louislam/uptime-kuma/assets/67516707/e82fd8c7-f099-49ac-bcae-70ccb64c10f0)
![image](https://github.com/louislam/uptime-kuma/assets/67516707/e26643e9-b968-484d-9078-b417df1df0f7)

**Comment by mxtthiasss** [comment]
> Since Uptime Kuma is technically that calls the `apprise` command with your url `nctalks://..`, it should be identical.
> 
> I guess there could be some escaped characters in the CLI command which may not be necessary in the Uptime Kuma's input.

my command looks like this
`nctalks://user:pw@server/roomid`

**Comment by mxtthiasss** [comment]
Hey, thank your for your help i found the problem. The Name resolution in the Docker Conntainer don't work
