### ISSUE TITLE
SMTP Setup Error

### ISSUE THREAD

**Issue by PaPaTheGMan** [louislam/uptime-kuma#318]
Having issue setting up SMTP notifications.  Error message is:
![image](https://user-images.githubusercontent.com/57098412/131920121-38713f60-bf42-4e1d-a630-fb828be27d64.png)

**To Reproduce**
1. Go to 'Settings, Setup Notification, Choose Email'
2. Fill in parameters - note using smtp-mail.outlook.com on port 587 & checking 'Secure''
3. Scroll down to 'Test'

**Expected behavior**
Successful 'test' email sent from server and received on client.

**Info**
- Uptime Kuma Version: 1.5.2
- Using Docker?: **Yes**/No
- OS: 'Armbian focal (21.08.1) aarch64'
- Browser: MS Edge

**Screenshots**

**Error Log**
snippet from log:

[Error: 281473420979768:error:1408F10B:SSL routines:ssl3_get_record:wrong version number:../deps/openssl/openssl/ssl/record/ssl3_record.c:331:
] {
  library: 'SSL routines',
  function: 'ssl3_get_record',
  reason: 'wrong version number',
  code: 'ESOCKET',
  command: 'CONN'
}

**Comment by louislam** [comment]
Secure have to be false according to nodmailer doc.

> secure: false, // true for 465, false for other ports

**Comment by PaPaTheGMan** [comment]
Thank you.  I saw the note about 465, but thought 587 was also a secure connection for smtp.  Unchecking the box fixed the issue.  Thanks again.
