### ISSUE TITLE
Signal Notification on Synology Docker

### ISSUE THREAD

**Issue by DominArsen** [louislam/uptime-kuma#3181]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

Hi,

I recently installed Uptime Kuma via Docker on a Synology server. I managed to configure the email notifications and they work perfectly.
However, I'm trying to set up "Signal Notification" but I'm having a problem. While configuring, I get the following error: "Error: Error: getaddrinfo ENOTFOUND signal-api".
I have already tried several solutions but without success. I'm not sure I understand the origin of this error.
Could you help me to solve this problem? I would be happy to provide additional information if needed.
Thank you in advance for your help and I look forward to your response.
[Photo Problem](https://github.com/louislam/uptime-kuma/assets/25647586/2b8ad4bc-4ef3-4b5f-842a-c408e6eb5828)

### 📝 Error Message(s) or Log

Uptime kuma : "Error: Error: getaddrinfo ENOTFOUND signal-api"

### 🐻 Uptime-Kuma Version

1.21.3

### 💻 Operating System and Arch

Synology DSM 7.1.1-42962 Update 5

### 🌐 Browser

Google Chrome 113.0.5672.127 (Build officiel) (64 bits)

### 🐋 Docker Version

Docker 20.10.3-1308

**Comment by CommanderStorm** [comment]
From your screenshot, I cannot infer where you are getting the name `signal-api` from. I can only read names which are slightly different.
Could you please describe your environment more?

Please also describe the solutions you tried:
Are the [two containers in the same network](https://docs.docker.com/network/)?
Can they communicate?

**Comment by DominArsen** [comment]
Yes the two containers communicate..
How can I know what to put in Uptime Kuma's address bar?
