### ISSUE TITLE
Email notification titles are confusing

### ISSUE THREAD

**Issue by rwjack** [louislam/uptime-kuma#3184]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 👟 Reproduction steps

The notification email title shouldn't really contain the status of the check.

At the very least it should contain the ACTUAL status of the check, because the way it is right now is just confusing.

![ima_0df683b](https://github.com/louislam/uptime-kuma/assets/59068073/d9ab3761-adb5-4eb3-8779-ac72cc8d9301)

![ima_879f2f6](https://github.com/louislam/uptime-kuma/assets/59068073/71938307-9560-4da4-b187-b397dcc1a243)

### 👀 Expected behavior

Email notification subject should match the actual status of the check.

### 😓 Actual Behavior

Explained in screenshot.

### 🐻 Uptime-Kuma Version

1.21.3

### 💻 Operating System and Arch

Docker

### 🌐 Browser

Irellevant

**Comment by CommanderStorm** [comment]
what is the content of this field:
![image](https://github.com/louislam/uptime-kuma/assets/26258709/d68ba43e-61c0-457b-93b5-2e61900625f5)

**Comment by rwjack** [comment]
Well, this is embarrassing.

![image](https://github.com/louislam/uptime-kuma/assets/59068073/77513839-18e5-4a23-9cf9-66ca0b4006fe)

I honestly don't remember ever filling up that field, nor does it make sense that I would hardcode it to the name of a single check.

Guess that should solve it then.
