### ISSUE TITLE
Email Notifications

### ISSUE THREAD

**Issue by evdev** [louislam/uptime-kuma#3191]
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

UI Feature

### 🔖 Feature description

Can you please enhance the email notification option to allow customizing the body of the email?
Would it be possible to add a variable for email addresses for each monitor and to send a notification to the email addresses in the variable? This way I won't need to configure a notification type for each email address I would like to send to and it can instead send the email automatically to the listed email addresses in the local variable of the monitored entity. 

### ✔️ Solution

add a customization field for the body
add variable to each monitor and allow the variable to be used for the monitor's notifications

**Comment by prohand** [comment]
Hello, great feature :)
hope it is implemented

**Comment by CommanderStorm** [comment]
@evdev 
Customising the body of mails is tracked in #1529, please don't post duplicate issues, as this makes issue management harder.

Handling emails like this would be very messy. Not everybody wants email notifications.
=> I don't think Uptime Kuma should modify the Notification system like this.
If you really need this feature, you could achieve this with other email filtering tools like Sieve.

Please go into detail about your intended use case, if you really need this.

**Comment by CommanderStorm** [comment]
@prohand 
Please refrain from posting `+1` / requests for updates things on issues, as this makes issue-management harder.
Issues are for discussing what needs to be done how by whom.
[We use 👍🏻 on issues to prioritise work](https://github.com/louislam/uptime-kuma/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).
