### ISSUE TITLE
using wrong interface to ping

### ISSUE THREAD

**Issue by copenhaus** [louislam/uptime-kuma#3194]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### Description

Hi, I've deployed this as a docker on a Synology NAS.  The NIC has a Local Port on 3444, bound to Synology IP address.  The Container Port is on port 3001 and has an IP address of 172.17.0.5 (according to Portainer)

The problem is when I tried to ping different offices via BOVPN, one of them happened to be "172.17.0.254" and Kuma fails, because it tries to ping from 172.17.0.5.

I created another "bridge-uptime" network and added Kuma to it, but it still can't reach 172.17.0.254.

Thoughts?  suggestions?

Thanks in advnace

### 👟 Reproduction steps

described above.

### 👀 Expected behavior

it should've been able to reach 172.22.0.254 and reported it as healthy.

### 😓 Actual Behavior

PING 172.17.0.254 (172.17.0.254) 56(84) bytes of data. --- 172.17.0.254 ping statistics --- 11 packets transmitted, 0 received, 100% packet loss, time 1009ms

### 🐻 Uptime-Kuma Version

1.21.3

### 💻 Operating System and Arch

Synology DSM 7.0.1-42218 Update 3

### 🌐 Browser

Cheom 113.0.5672.127

### 🐋 Docker Version

Docker 20.10.3-1239

**Comment by louislam** [comment]
Usually it is your specific network issue, if you go into Uptime Kuma's bash and execute the `ping 172.17.0.254` command, I believe it won't work either.

More info:
https://github.com/louislam/uptime-kuma/wiki/Troubleshooting

**Comment by chakflying** [comment]
From your description, sounds like you have an overlapping subnet. The IP layer of the network is literally unable to route packets to where you want to go because it is masked by the docker network. [This blogpost](https://medium.com/codebrace/understanding-docker-networks-and-resolving-conflict-with-docker-subnet-ip-range-bfaad092a7ea) has a pretty good explanation.

**Comment by copenhaus** [comment]
That's exactly what I did...I think...

There's no such file (/etc/docker/daemon.json), so I modified it via Synology GUI instead.

![image](https://github.com/louislam/uptime-kuma/assets/25488700/a0c9e01a-09dc-4f89-b835-e0f26c8adc2f)

confirmed with Portainer.

![image](https://github.com/louislam/uptime-kuma/assets/25488700/63c63718-f14f-4815-80bf-b990a3ffa465)

But this is what I got:
![image](https://github.com/louislam/uptime-kuma/assets/25488700/1b48cb5a-6316-43c3-86bb-ff00012fb0b6)

I entered the shell and tried to ping 172.17.0.254, but it didn't go anywhere:
![image](https://github.com/louislam/uptime-kuma/assets/25488700/421ba545-c3cc-4be9-940f-cdc44c7a122f)

**Comment by chakflying** [comment]
Maybe you can check if the original bridge is still masking your network by adding a monitor with `172.17.0.3` to see if it's going to your other container.

**Comment by copenhaus** [comment]
![image](https://github.com/louislam/uptime-kuma/assets/25488700/0140afff-ff36-4732-a375-52ddbfcf391b)
