### ISSUE TITLE
Multiple services per server / aggregated "health" status, perhaps via tags?

### ISSUE THREAD

**Issue by Jzsiba** [louislam/uptime-kuma#3195]
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

New Monitor, UI Feature, Other

### 🔖 Feature description

At the moment, you can add a monitor, give it a name and that's pretty much it. There's no way to relate it to other monitors, and no way to aggregate the "health" of a system. 

### ✔️ Solution

The tag system is already in place and could offer a perfect way to capture an aggregate score. A binary up/down for each monitor tagged could produce a more useful "at a glance" idea of what's going on with a system. 

Let's say I have a system running Apache, MariaDB, Redis & some application that responds via HTTP/s on some given port other that the one Apache is answering on.

That's 4 services on a single machine, all that could be tagged with the name of the machine. 25% each, gives me the ultimate health of the system. If I could then monitor the status of that Tag, instead of individual monitors on a status page. I could compress the amount of information displayed on the monitor page, while increasing the amount of actual information I can glean from the status page itself.

Bonus if I can click on the tag and expand it to show the individual monitors within that tag. 

### ❓ Alternatives

Separate status pages per server. Not an idea solution.

### 📝 Additional Context

I would also love to see the ability to add multiple columns on status pages but that's something I can do myself via custom css. It'd just be a nice built in feature!

**Comment by CommanderStorm** [comment]
Is this one of the duplicates of #2693?
If not, could you edit this issue to be more distinctive/build on this PR?

**Comment by CommanderStorm** [comment]
Could you close this issue?

**Comment by CommanderStorm** [comment]
Thank you ❤️
