### ISSUE TITLE
 improve status page

### ISSUE THREAD

**Issue by enzofoucaud** [louislam/uptime-kuma#3197]
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

UI Feature

### 🔖 Feature description

It would be nice to improve the status page to look something like this.

Example: 
https://status.multiversx.com/
https://status.multiversx.com/uptime

### ✔️ Solution

Improved UX + added API info?

**Comment by enzofoucaud** [comment]
Yes, sorry, I could have been more specific in my request.

What I like about Atlassian is the little extra details, such as uptime over the last X days, info on why you've lost connections by moving your mouse over the various points, see past incidents at the bottom of the page, add a uptime page, etc

**Comment by CommanderStorm** [comment]
Please open one feature request per feature request and do a duplication search for each of them. (for example for the detialed incidents, see the duplicates mentioned in #1253)
Like you wrote the issue, this is not manageable, given the number of issues.

Furthermore, please be more specific about why you want this feature and why this information would be important for you.

**Comment by shdf2** [comment]
Sorry to hijack this request :) 

in the status page, what about displaying a detailed view **when we click on a monitor**. Actualy when we click on a monitor nothing happens, so we could have the detailed view like in the dahsboard, when we are logged in.

**Comment by CommanderStorm** [comment]
> Sorry to hijack this request

@shdf2
Please open another issue. Like this, this is indeed unmanagable.
Also, please run a duplication search, there may be issues which are very close.

**Comment by CommanderStorm** [comment]
@enzofoucaud
Like you wrote the issue, submitting non-detailed `feature-requests` this is not manageable, given the number of issues.
Could you close this issue and reopen single-issue `feature-reuqests` instead? (only you or Louis can close this issue)
