### ISSUE TITLE
Add `application/xml` to webhook option

### ISSUE THREAD

**Issue by woj-tek** [louislam/uptime-kuma#3198]
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

API, New Notification

### 🔖 Feature description

It would be great to add `application/xml` to content-type option, in addition to existing `application/json`

### ✔️ Solution

Add another entry to the list of content types.

### ❓ Alternatives

If the endpoint only supports `application/xml` there aren't many alternatives. There could be a middleman handling `application/json` and transforming it to XML, but it doesn't seem sensible.

**Comment by chakflying** [comment]
Should be solved with #3088

**Comment by woj-tek** [comment]
@chakflying indeed #3088 should fix this.
