### ISSUE TITLE
Possibility to add a link to the image and name of each status page.

### ISSUE THREAD

**Issue by ldev-coder** [louislam/uptime-kuma#3199]
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

UI Feature, Other

### 🔖 Feature description

Possibility to add a link to the image and name of each status page.

### ✔️ Solution

Add to the database where the status page fields are defined two varchar(255) fields, one for the image url and one for the link in the page name.
Then add the tag to the image and status page name.
Both fields to be defined in the definitions of each status page.

**Comment by CommanderStorm** [comment]
What do you mean by image? Docker/actual image? 

Do you mean this feature?
![image](https://github.com/louislam/uptime-kuma/assets/26258709/3fd53765-3f02-45ac-9583-53fedc50a4df)

Do you mean this component?
![image](https://github.com/louislam/uptime-kuma/assets/26258709/fb0b2ed0-dc32-4eb9-ba08-b6d81bd85e77)

**Comment by ldev-coder** [comment]
> O que você entende por imagem? Docker/imagem real?
> 
> Você quer dizer esse recurso? ![imagem](https://user-images.githubusercontent.com/26258709/241586013-3fd53765-3f02-45ac-9583-53fedc50a4df.png)
> 
> Você quer dizer este componente? ![imagem](https://user-images.githubusercontent.com/26258709/241586216-fb0b2ed0-dc32-4eb9-ba08-b6d81bd85e77.png)

![image](https://github.com/louislam/uptime-kuma/assets/69407012/0942e655-51c5-49bb-a944-c594f244adba)

**Comment by ldev-coder** [comment]
@louislam Pls add this to version 1.22.0

**Comment by CommanderStorm** [comment]
> @ louislam Pls add this to version 1.22.0

Given that there [has not been a PR raised for the version](https://github.com/louislam/uptime-kuma/milestone/31), that would likely delay the release ⇒ should not be done in 1.22.0.
If you want to write a PR, please see https://github.com/louislam/uptime-kuma/blob/master/CONTRIBUTING.md

Please also answer all the questions:
What do you mean by image? (Where should the image you mentioned go? Why do you need another image?)

I also have some additional questions:
- Would adding a description not be the better version of what you are requesting?
- Would linking via the monitors not be a better version? What is your usecase?

**Comment by hmhackmaster** [comment]
@ldev-coder To be clear, you are wanting to add a picture and custom text to the top of the status page, just like you can see the custom picture and text on the `https://status.skyhost.pt` page?

**Comment by CommanderStorm** [comment]
Closing as it is unclear what @ldev-coder meant and he is not responding to clarification-requests
