### ISSUE TITLE
Ping monitor: "Platform |openbsd| is not support"

### ISSUE THREAD

**Issue by h3artbl33d** [louislam/uptime-kuma#3201]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### Description

First and foremost: thank you so much for creating `uptime-kuma` - have been using it for quite some time and am completely happy with it. I do run it on OpenBSD with some monitors. Most are TCP Pings and some HTTPS.  However, a 'Ping' monitor throws the following error:

```
Platform |openbsd| is not support
```

I am not versed in NodeJS - so the following might be complete nonsense: it seems to be caused by `cypress`, which is listed as a devDependency. The [🔧 How to Install](https://github.com/louislam/uptime-kuma/wiki/%F0%9F%94%A7-How-to-Install#-without-docker-recommended-for-x86x64-only) instructs to execute `npm run setup`.  The [`package.json:42`](https://github.com/louislam/uptime-kuma/blob/master/package.json#L42) shows that `npm ci --production` is ran, which should omit devDependencies.

If I run `npm i @louislam/ping` I get the following output:

```
npm ERR! code 1
npm ERR! path /var/www/status/app/node_modules/cypress
npm ERR! command failed
npm ERR! command sh -c node index.js --exec install
npm ERR! Platform: "openbsd" is not supported.

npm ERR! A complete log of this run can be found in:
npm ERR!     /var/www/status/.npm/_logs/2023-05-29T10_35_00_736Z-debug-0.log
```

However, running `npm i @louislam/ping --production` seems to work:

```
npm WARN config production Use `--omit=dev` instead.

removed 1 package, and audited 657 packages in 57s

90 packages are looking for funding
  run `npm fund` for details

3 vulnerabilities (2 moderate, 1 high)

To address issues that do not require attention, run:
  npm audit fix

To address all issues, run:
  npm audit fix --force

Run `npm audit` for details.
```

It fix the issue - still getting the same error adding a Ping monitor (even after restarting `uptime-kuma`) - but this might be due to my incompetence with NodeJS / npm.

### 👟 Reproduction steps

1. Follow  [🔧 How to Install](https://github.com/louislam/uptime-kuma/wiki/%F0%9F%94%A7-How-to-Install#-without-docker-recommended-for-x86x64-only) on an OpenBSD machine.
2. Add a Ping monitor.
3. The error pops up.

### 👀 Expected behavior

1. Follow  [🔧 How to Install](https://github.com/louislam/uptime-kuma/wiki/%F0%9F%94%A7-How-to-Install#-without-docker-recommended-for-x86x64-only) on an OpenBSD machine.
2. Add a Ping monitor.
3. The monitor starts pinging the host at the set interval.

### 😓 Actual Behavior

1. Follow  [🔧 How to Install](https://github.com/louislam/uptime-kuma/wiki/%F0%9F%94%A7-How-to-Install#-without-docker-recommended-for-x86x64-only) on an OpenBSD machine.
2. Add a Ping monitor.
3. The error pops up.

### 🐻 Uptime-Kuma Version

1.21.3

### 💻 Operating System and Arch

OpenBSD 7.3

### 🌐 Browser

Chromium 113.0.5672.126

### 🟩 NodeJS Version

18.15.0

**Comment by h3artbl33d** [comment]
**To be clear:** Uptime Kuma works, TCP Ping, HTTPS monitors work - so do the notifications. This issue only occurs with a (ICMP) Ping monitor.

**Comment by louislam** [comment]
Unfortunately, we switched the ping library to [node-ping](https://github.com/danielzzz/node-ping) which is not support for OpenBSD. 

node-ping should need to be modified in order to support it.

Current workaround: 
You can use an older version of Uptime Kuma that haven't switched to node-ping, but I can't remember start from which version.

**Comment by rezzorix** [comment]
I believe the switch to node-ping was made with uptime-kuma 1.19.4

See also here: https://github.com/louislam/uptime-kuma/pull/2223

**Comment by CyberTailor** [comment]
As of version 1.23.16, it doesn't even start on OpenBSD:

```
sysrq-bsd$ node server/server.js
Welcome to Uptime Kuma
Your Node.js version: 22.12.0
2024-12-22T00:42:08+01:00 [SERVER] INFO: Welcome to Uptime Kuma
2024-12-22T00:42:08+01:00 [SERVER] INFO: Node Env: production
2024-12-22T00:42:08+01:00 [SERVER] INFO: Inside Container: false
2024-12-22T00:42:08+01:00 [SERVER] INFO: Importing Node libraries
2024-12-22T00:42:08+01:00 [SERVER] INFO: Importing 3rd-party libraries
/home/www/uptime-kuma/node_modules/playwright-core/lib/server/registry/index.js:258
    if (process.platform === 'linux') cacheDirectory = process.env.XDG_CACHE_HOME || _path.default.join(os.homedir(), '.cache');else if (process.platform === 'darwin') cacheDirectory = _path.default.join(os.homedir(), 'Library', 'Caches');else if (process.platform === 'win32') cacheDirectory = process.env.LOCALAPPDATA || _path.default.join(os.homedir(), 'AppData', 'Local');else throw new Error('Unsupported platform: ' + process.platform);
                                                                                                                                                                                                                                                                                                                                                                                             ^

Error: Unsupported platform: openbsd
    at /home/www/uptime-kuma/node_modules/playwright-core/lib/server/registry/index.js:258:388
    at Object.<anonymous> (/home/www/uptime-kuma/node_modules/playwright-core/lib/server/registry/index.js:270:3)
    at Module._compile (node:internal/modules/cjs/loader:1565:14)
    at Object..js (node:internal/modules/cjs/loader:1708:10)
    at Module.load (node:internal/modules/cjs/loader:1318:32)
    at Function._load (node:internal/modules/cjs/loader:1128:12)
    at TracingChannel.traceSync (node:diagnostics_channel:322:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:219:24)
    at Module.require (node:internal/modules/cjs/loader:1340:12)
    at require (node:internal/modules/helpers:138:16)

Node.js v22.12.0
```

**Comment by CyberTailor** [comment]
See also https://github.com/louislam/uptime-kuma/issues/3642

**Comment by louislam** [comment]
In current state, Uptime Kuma cannot be run on FreeBSD anymore due to upstream dependencies.

As said @rezzorix said, you can try older versions like 1.19.4.

**Comment by tschettervictor** [comment]
Or try this helpful install script.

https://github.com/tschettervictor/bsd-apps/tree/main/uptime-kuma
