### ISSUE TITLE
Run a bash script when a monitor is down

### ISSUE THREAD

**Issue by pigate-eu** [louislam/uptime-kuma#3206]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

I want every time that a monitor is down to execute a bash script located on the same server with Uptime Kuma. On Setup Notification I did't find this option so let me know if exist a trick or this feature.

### 🐻 Uptime-Kuma Version

1.21.3

### 💻 Operating System and Arch

Debian

### 🌐 Browser

Google Chrome

**Comment by kmcbride3** [comment]
I had the same use case, which I've solved by running an instance of Webhookd (https://github.com/ncarlier/webhookd), and then using the webhook notification option within Uptime Kuma to trigger the call to execute the script (via Webhookd) when the monitor detects that the service is down. In my case, both Uptime Kuma and Webhookd are running in separate docker containers, but this solution would work even if they're running on separate servers, as long as Uptime Kuma can reach the Webhookd instance.

Within the bash script, I've put in some checks at the beginning to check whether the docker container I'm attempting to self-heal is already running (e.g., the script was already previously triggered, and is still running) before doing anything else. Works pretty well, for the most part.

**Comment by pigate-eu** [comment]
Really Thank You! Works like a charm!!!

I use the image "ncarlier/webhookd:edge-distrib" because I need curl to run some scripts on webhookd container after kuma detects that the monitors are down, so with this docker image tag all works perfect!! I have static IP to webhookd container for kuma to detect every time the correct conainer and use it as webhook trigger.

**Comment by spupuz** [comment]
i'm trying to use this with uptime kuma but i got permission denied.
i need to restart docker container if i do use webhookd command line to test the script all is fine but then when i try execute command from my pc:

curl -v -XPOST --header "X-Hook-Mode: chunked" http://192.168.1.xxx:8383/restart_vpn_containers

i got this error

time=2024-09-20T21:52:03.149Z level=ERROR msg="hook executed" hook=restart_vpn_containers.sh id=2 status=error exitCode=0 err="open /tmp/restart_vpn_containers.sh_2_20240920_2152.txt: permission denied" took=0

time=2024-09-20T22:00:38.830Z level=INFO msg="executing hook..." hook=restart_vpn_containers id=3

if i make a test from uptimekuma it says connection error.

i use both uptimekuma and webhood container in bridged mode.
