### ISSUE TITLE
HTTP(s) - Keyword not working correctly

### ISSUE THREAD

**Issue by mitsuo-makuda** [louislam/uptime-kuma#3213]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 👟 Reproduction steps

1. Create a new monitor.
2. Set it to HTTPS(s) - Keyword
3. Set the URL to https://discord.com/invite/TzN5rCrhZU
4. Set the keyword to Invite Invalid
5. Save the new monitor.

### 👀 Expected behavior

200 - OK, but keyword is not in [...]

### 😓 Actual Behavior

200 - OK, keyword is found

### 🐻 Uptime-Kuma Version

1.20.2

### 💻 Operating System and Arch

YunoHost 11.1.18

### 🌐 Browser

Mozilla Firefox 113.0b8 (64-bit)

**Comment by rezzorix** [comment]
Not a bug. 

Related answer from a similar previous issue:

              The website is most likely an SPA, meaning content is loaded by JavaScript after initial page load. Currently you cannot check the content of such a website.

_Originally posted by @chakflying in https://github.com/louislam/uptime-kuma/issues/2935#issuecomment-1471627620_
