### ISSUE TITLE
Uptime kuma monitor is gone

### ISSUE THREAD

**Issue by kokofixcomputers** [louislam/uptime-kuma#3216]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### Description

i had 5 monitors in uptime-kuma and 2 status pages when i add 2 more monitors and 1 more status page it works perfectly but after a few minutes the monitor and the status page is gone i don't see any related logs i only see weird resuming log that should not be there.

### 👟 Reproduction steps

1. Have 5 monitors and 2 status pages
2. Add 2 more monitors. and add 1 more status page
3. Link the ones you created to the status page you created
4. Now wait

### 👀 Expected behavior

It should not delete my monitors. It also should not have the weird resuming logs.

### 😓 Actual Behavior

it has those weird resuming logs and my monitors is deleted without having the delete log.

### 🐻 Uptime-Kuma Version

1.21.3

### 💻 Operating System and Arch

Linux (Replit)

### 🌐 Browser

Google Chrome

### 🟩 NodeJS Version

18.15.0

**Comment by kokofixcomputers** [comment]
Also i don't seem to have this problem when i delete 2 other monitors before creating the two monitors.

**Comment by louislam** [comment]
Uptime Kuma do not support on Replit. There are a lot of weird issues on Replit which had been reported by other users already.
