### ISSUE TITLE
access to 3001 from outside

### ISSUE THREAD

**Issue by kuhytitusdlz** [louislam/uptime-kuma#3217]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

Hi there,
I have installed uptime-kuma from docker, and I can get http://192.168.100.10:3001 from local machine. But from outside (192.168.100.2) it's unreachable, port don't answer. Another docker app is work fine. What can I do?

### 🐻 Uptime-Kuma Version

1.21.3

### 💻 Operating System and Arch

Ubuntu 20.04.5 LTS

### 🌐 Browser

curl

### 🐋 Docker Version

20.10.21

**Comment by VuurwerkFan** [comment]
Hello, 192.168.100.2 is a private IP. Did u portforward it? 
Otherwise it only is avaible in your home network and not from the outside.

**Comment by louislam** [comment]
Firewall usually, try to turn it off and test it first.

**Comment by kuhytitusdlz** [comment]
update ubuntu to 22.04, docker, it's work now, thanks!
