### ISSUE TITLE
How can a push-based monitor be both "Up" and "Down" simultaneously?

### ISSUE THREAD

**Issue by luckman212** [louislam/uptime-kuma#3218]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

I'm trying to understand this, maybe I'm doing it wrong, but...

I read https://github.com/louislam/uptime-kuma/issues/279 and still don't quite understand the `status` parameter for push monitors.

I've got a monitoring script that pushes every **hour** to my kuma instance. 

It sends the params as, e.g.

Something's wrong...
```
https://my.kuma/api/push/f4h2di3sfz?status=down&msg=3%20devices%20offline
```
All good...
```
https://my.kuma/api/push/f4h2di3sfz?status=up&msg=All%20devices%20online
```

For the monitor itself, I set it to have a heartbeat of 7200 (to allow for some slack on the script timing).

### The actual question

So, how can the last "Status update" be **Down**:

![CleanShot 2023-06-03 at 21 47 52](https://github.com/louislam/uptime-kuma/assets/1992842/774cff33-91d6-4718-8bda-25533d2dcb87)

<img width="815" alt="image" src="https://github.com/louislam/uptime-kuma/assets/1992842/8294f038-2d46-408f-bc08-aac88bd49579">

### 🐻 Uptime-Kuma Version

 1.21.3

### 💻 Operating System and Arch

Ubuntu/docker

### 🌐 Browser

Chrome 114.0.5735.90 

### 🐋 Docker Version

Docker version 20.10.24, build 297e128

**Comment by luckman212** [comment]
anyone have any ideas? should I try the beta version?

**Comment by ww7** [comment]
Also wondering if possible to control status programmatically.
It would be great to `Push` statuses `Up` and `Down` via curl (with disabled Heartbeat)
