### ISSUE TITLE
No SSL notification

### ISSUE THREAD

**Issue by klecka** [louislam/uptime-kuma#3224]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [x] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

I set up a website monitoring and configured notifications through MS Teams and it works great.
But I checked the box 'Certificate expiry notification' and don't get these. When I'm in the app settings and try to add a day to the cert expiry field it is empty again after saving the settings.

### 🐻 Uptime-Kuma Version

1.21.3

### 💻 Operating System and Arch

Ubuntu 20.04 LTS (Linode Nanode 1 GB)

### 🌐 Browser

Chrome & Firefox latest

**Comment by chakflying** [comment]
Assuming you installed manually instead of using Docker, what version of node.js are you using?
