### ISSUE TITLE
How to contribute to Uptime Kuma Grafana Dashboard

### ISSUE THREAD

**Issue by mamayadi** [louislam/uptime-kuma#3225]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

I want to contribute to [Uptime Kuma Dashboard](https://grafana.com/grafana/dashboards/14847-uptime-kuma/), but I didn't find how, any one can help ?

### 🐻 Uptime-Kuma Version

1.21.3

### 💻 Operating System and Arch

Ubuntu 22.04.2 LTS

### 🌐 Browser

Google Chrome 113.0.5672.92

**Comment by CommanderStorm** [comment]
See https://github.com/louislam/uptime-kuma/wiki/%F0%9F%94%A7-How-to-Install#unofficial--experimental
i.e. add a PR [here](https://github.com/louislam/uptime-kuma-wiki)
Please also add more screenshots to the dashboards page.

I think that currently this stands against merging this into the docs (I am not a maintainer, but think that addressing these is still an important concern):
![image](https://github.com/louislam/uptime-kuma/assets/26258709/a1fb173e-faff-4c9e-b4c3-9e5ba2f3625c)

**Comment by proffalken** [comment]
@mamayadi I don't believe I ever got around to creating a Github repo for that one.

You can update the existing one to do what you need it to and then just export it from Grafana and upload it to the Grafana dashboards site yourself.

I'm not running Uptime Kuma at the moment so I can't do that myself.

**Comment by mamayadi** [comment]
@proffalken, thank you for your response
