### ISSUE TITLE
[slack] Remove previews

### ISSUE THREAD

**Issue by icsy7867** [louislam/uptime-kuma#3226]
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

UI Feature, Other

### 🔖 Feature description

![image](https://github.com/louislam/uptime-kuma/assets/3788162/0bc6bf11-a589-41ba-a3fa-1b5fa7ab2924)

I had someone ask me for this, and I am not sure if it is possible.  But the slack integration adds a preview with what looks like very similar information from the message.  This appears a bit superfluous and it would be nice to be able to disable this.

### ✔️ Solution

Add an option to the web gui to disable link and media unfurling.
https://api.slack.com/reference/messaging/link-unfurling#no_unfurling_please

Not really sure where the preview is coming from, it's not really media and not really a link.  But this should prevent this from happening in the slack API/Webhook call:

```json
{
    "text": "Check out the <https://api.slack.com|Slack API>",
    "unfurl_links": false,
    "unfurl_media": false
}
```

So a simple slider for "Disable Preview", "Disable Link Unfurling" in the slack integration edit menu with the other sliders should be functional and still look aesthetically pleasing.  You could also do a single slider "No previews" or something instead.

![image](https://github.com/louislam/uptime-kuma/assets/3788162/d128d4a4-23e8-4b88-860b-8d8b47cf48c8)

### ❓ Alternatives

Not sure of any.

**Comment by DaanMeijer** [comment]
I would be willing to fix this issue with a pull request, once my pull request for 3351 gets merged :)

**Comment by falkoschindler** [comment]
I would also love to hide these redundant previews!
@DaanMeijer Are you still up for a pull request? 🙂

**Comment by septemberservices** [comment]
> I would also love to hide these redundant previews! @DaanMeijer Are you still up for a pull request? 🙂

Absolutely! I hope to get to it sometime this week.

**Comment by DaanMeijer** [comment]
> I would also love to hide these redundant previews! @DaanMeijer Are you still up for a pull request? 🙂

Absolutely! I hope to get to it sometime this week.
