### ISSUE TITLE
Notifications are sent on US time.

### ISSUE THREAD

**Issue by HYDeath** [louislam/uptime-kuma#3230]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

I have tried changing the display time zone and server time zone in the settings and changing the docker container time, but the time is still US time. I really can not solve, modify the source code is only valid for email, Ali SMS failed to change over.![image](https://github.com/louislam/uptime-kuma/assets/65531310/c8016aa4-7722-4250-b4b0-4371063183ab)

### 📝 Error Message(s) or Log

None

### 🐻 Uptime-Kuma Version

1.21.3

### 💻 Operating System and Arch

centos 7.9

### 🌐 Browser

Google Chrome 114.0.5735.91

### 🐋 Docker Version

Docker 24.0.2

**Comment by louislam** [comment]
It will be fixed in the upcoming version.

**Comment by HYDeath** [comment]
> 它将在即将发布的版本中修复。

Ok, thanks, looking forward to the new version.

**Comment by CommanderStorm** [comment]
@HYDeath given that has been resolved by #3203, could you close this issue?
The next version will be released soon-ish see https://github.com/louislam/uptime-kuma/milestone/31 for further details

**Comment by HYDeath** [comment]
> @HYDeath given that has been resolved by #3203, could you close this issue? The next version will be released soon-ish see https://github.com/louislam/uptime-kuma/milestone/31 for further details

OK
