### ISSUE TITLE
I need to add a timeout for when the alert generated by uptime kuma is "DOWN" it disappears after 20 seconds

### ISSUE THREAD

**Issue by aroldo2** [louislam/uptime-kuma#3233]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

I need the pop up when the server is "DOWN" to close automatically, would there be any simple way to make this happen????

### 🐻 Uptime-Kuma Version

1.21.3

### 💻 Operating System and Arch

ubuntu 22.04

### 🌐 Browser

Firefox

**Comment by I-Fun** [comment]
+1

**Comment by CommanderStorm** [comment]
@I-Fun 
Please refrain from posting `+1` / requests for updates things on issues, as this makes issue-management harder.
Issues are for discussing **what needs to be done how by whom**.
[We use 👍🏻 on issues to prioritise work](https://github.com/louislam/uptime-kuma/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc), as always: [Pull Requests](https://github.com/louislam/uptime-kuma/blob/master/CONTRIBUTING.md) welcome.

**Comment by Substancia** [comment]
Hey @aroldo2 , looks like this feature already exists? In Settings -> Notifications, we can set the error toast timeout in seconds (which by default is set to -1 for never disappear).

Please check if this is what you were looking for?

**Comment by m00ner** [comment]
For the life of me, I can not locate this and i feel like an idiot...   I see a button that says setup notifications but there is nothing in there about toast or timeout. 


> Hey @aroldo2 , looks like this feature already exists? In Settings -> Notifications, we can set the error toast timeout in seconds (which by default is set to -1 for never disappear).

**Comment by chakflying** [comment]
Reference #3441, it was merged to the `2.0.0` release, so it's not available on current versions yet.

**Comment by CommanderStorm** [comment]
Closing as resolved by https://github.com/louislam/uptime-kuma/pull/3441 and will be released in the upcoming [`v2.0`-release](https://github.com/louislam/uptime-kuma/milestone/24)
