### ISSUE TITLE
Is demo really hosting? 

### ISSUE THREAD

**Issue by Nipatsu** [louislam/uptime-kuma#3236]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

Is demo version really hosting anything if I put my link to it. If its not do you know then any websites which will use uptime kuma and I can use them. My computer dont support node.js 14 so I cant install it

### 🐻 Uptime-Kuma Version

Idk

### 💻 Operating System and Arch

Ubuntu? 

### 🌐 Browser

Firefox

**Comment by CommanderStorm** [comment]
What do you mean by

> Is demo version really hosting anything if I put my link to it

I think there is a language barrier. Could you translate your request with deepl.com and include more details about your setup and
- why node is a requirement
- why node 14 is not supported on your device

**Comment by rihards-simanovics** [comment]
@Nipatsu Demo site for Uptime Kuma is technically going to work just like a normal installation, however demo will be reset after 10 min removing all data you place in it. If you want to host one yourself you will need a NodeJS. If you want to you can also host it with Docker.
