### ISSUE TITLE
Installation question

### ISSUE THREAD

**Issue by Reyah9999** [louislam/uptime-kuma#3237]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

How to install uptime-kuma on a regular website hosting by type timeweb.com ?

### 📝 Error Message(s) or Log

-

### 🐻 Uptime-Kuma Version

idk

### 💻 Operating System and Arch

-

### 🌐 Browser

Yandex

### 🐋 Docker Version

-

### 🟩 NodeJS Version

-

**Comment by CommanderStorm** [comment]
You choose the VPS by the provider of your choice, in your case probably
![image](https://github.com/louislam/uptime-kuma/assets/26258709/027c1602-d67b-4b53-b2c5-44d3837fa2cc)
(given that the website is only available in russian, which I dont speak I cannot help you with this provider other than what google translate can do)

And follow the [installation path](https://github.com/louislam/uptime-kuma/wiki/%F0%9F%94%A7-How-to-Install) of your choice.

I don't understand what you mean by 
> This is file hosting

**Comment by Reyah9999** [comment]
.
