### ISSUE TITLE
[groups] Monitor critical flag to replace 'Partially Degraded Service' with 'Full Service Outage'

### ISSUE THREAD

**Issue by kub3let** [louislam/uptime-kuma#3238]
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

UI Feature

### 🔖 Feature description

The Status Page on top shows `All Systems Operational` or `Partially Degraded Service` but there is never really a `Degraded Service` or `Full Service Outage` message, since that requires all Monitors to be down ?

I have a bunch of Monitors and some like `Router` or `Firewall` can be interpreted as if they are down nothing works. There are still other Monitors like redundancy or offsite services that will always be up though.

I think it would be great if we had a `Critical Service` checkbox (or dropdown with levels?) on the Monitor.

### ✔️ Solution

Adding a checkbox `Critical Service` on Monitors.

If this is checked and the Monitor is on the Status Page with Status `down` the heading message changes to `Full Service Outage` with red error symbol.

Actual message e.g. `Full Service Outage` to be defined.

**Comment by CommanderStorm** [comment]
Related #2487 #2474

Imo #2693 blocks #1236 which blocks such a change

**Comment by CommanderStorm** [comment]
I would argue against adding such a checkbox (additional clutter), but rather change the message to `Degraded Service` if all monitors in a status page are down.
(this would also not be blocked by grouping)

**Comment by kub3let** [comment]
Seems reasonable, I will wait for the pr's to be merged and then see if I can implement this feature.

**Comment by CommanderStorm** [comment]
@kub3let 
I think, we should track this issue in https://github.com/louislam/uptime-kuma/issues/1089
Oppinions?

**Comment by CommanderStorm** [comment]
Continuing to track this in https://github.com/louislam/uptime-kuma/issues/1089 and related issues tagged with `[groups]`

=> closing as a duplicate
