### ISSUE TITLE
Group notifications

### ISSUE THREAD

**Issue by Lars-** [louislam/uptime-kuma#324]
**Is it a duplicate question?**
Not exactly

**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
A way to add groups (already another question) but also being able to get a notification when the whole or a port of that group goes down.
For example, I have 3 servers with the same website. It would be great to create a group with all 3 servers. When all (or maybe 2 of the 3) are down, I get a notification instead of when a single server goes down. This would make it much easier to deploy a website which will result in a small downtime on that server.

**Comment by jtagcat** [comment]
Unsure if this issue is about the same thing as this:
***
Ah yes, 50 notifications!
![image](https://user-images.githubusercontent.com/38327267/134779543-6524a228-df84-4e51-ba6b-9b43795ca1b3.png)
***
All those were on the same host, 'if host goes down, suppress individual notifications'.

**Comment by CommanderStorm** [comment]
@Lars- This should be resolved given that https://github.com/louislam/uptime-kuma/pull/2693 is merged.
Could you close this issue?

**Comment by arshadmech** [comment]
Hi There,

i want to send an email like group (devops@example.com) notification, so that, who are available in that group . all of them will get email alert. 
i tried that one but i am unable to see email . can any one guide me on this.

**Comment by CommanderStorm** [comment]
This is not the right place to debug this, could you open a [`help` issue](https://github.com/louislam/uptime-kuma/issues/new?assignees=&labels=help&projects=&template=ask-for-help.yaml) with all the context?
(Currently, this is necroposting on a resolved, unrelated issue)

It is also not clear what you tried concretely from your description.
