### ISSUE TITLE
Auto end maintenance window when back online

### ISSUE THREAD

**Issue by ojsef39** [louislam/uptime-kuma#3240]
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

UI Feature

### 🔖 Feature description

So my problem is that i don’t know exactly when the maintenance window is over because the backup time varies heavily.

so it would be really great if there is an option to start a maintenance window at a specific time and it stops automatically when it’s back online

### ✔️ Solution

Option to start maintenance windows at specific time, but no end time. instead let the user set specific status codes that are the trigger for ending maintenance.

for example maintenance windows starts at 2 am -> server goes offline -> server comes back online with code 200 -> end maintenance window

### ❓ Alternatives

Implement Maintenance Window in API.
(to start and end maintenance window via update script)

**Comment by chakflying** [comment]
I think you would still want to be notified if your backup failed and it never came back online, so a timeout is necessary which the current feature already provides?

**Comment by ojsef39** [comment]
> I think you would still want to be notified if your backup failed and it never came back online, so a timeout is necessary which the current feature already provides?

Yeah, i get notified from the backup server itself if it fails.
And never came back online just means the maintenance windows is still open. and that’s exactly what i want. as long the server is offline as long i want the maintenance window to be open, because there is still work to do.

You see now where i come from with this idea?

**Comment by ojsef39** [comment]
found this, this fixes my issue:

https://github.com/lucasheld/uptime-kuma-api
