### ISSUE TITLE
Add translations

### ISSUE THREAD

**Issue by DevItq** [louislam/uptime-kuma#3244]
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

Other

### 🔖 Feature description

You should add translations for "Edit maintenance" on Edit maintenance page and for all alerts. Also, I translated almost all of the words into Russian, so could you merge them?

### ✔️ Solution

i don't know :)

**Comment by DevItq** [comment]
Also need to translate Loss connection on server.. and Cannot connect to the socket server...

**Comment by CommanderStorm** [comment]
> Also, I translated almost all of the words into Russian, so could you merge them?

Are you sure that you have provided them to web blade and that your submissions are not already in https://github.com/louislam/uptime-kuma/releases/tag/1.22.0-beta.0?
I dont see them here: https://github.com/louislam/uptime-kuma/pull/3242
Also note that due to timing issues, this might have to be pushed one relese down the road, as `beta.0`  has just hit.

**Comment by DevItq** [comment]
@CommanderStorm Thank you for your answer, but I don't see my changes in ru-RU.js in the release or elsewhere also alerts are still not translated

**Comment by louislam** [comment]
@DevItq

https://github.com/louislam/uptime-kuma/pull/3242

Those changes are in this pr, it will be merge when the next release.

**Comment by DevItq** [comment]
@louislam Thank you!

**Comment by DevItq** [comment]
And what about alerts?

**Comment by louislam** [comment]
If you have translated those words on Weblate, it will sync back to #3242 later. So don't worry.

**Comment by DevItq** [comment]
@louislam No, that's not what I meant. I'm about adding translations for alerts using $t ("...") or something like that.

**Comment by CommanderStorm** [comment]
What do you mean concretely with translations for alerts?
https://github.com/louislam/uptime-kuma/pull/3249 has been merged, and the 3 extra keys should be available for translation ^^

If we are missing more keys, just let me know. I can prepare another PR

**Comment by DevItq** [comment]
@CommanderStorm Should i create bug for this:
>Also there is a UI bug(home and >create a button in the mobile >version selected at the same time, >can get when choosing add button)

**Comment by DevItq** [comment]
@CommanderStorm Also, I realized that we can't translate alerts (toasts) because their logic is in the backend.

**Comment by CommanderStorm** [comment]
> But perhaps there is a way to translate not only the frontend, but also the backend.

This seems like a non-trivial thing to fix after looking into it a bit.
Could you open a `feature-request` to `Add localisation (i18n) to the backend alerts and responses`

**Comment by DevItq** [comment]
@CommanderStorm Ok
