### ISSUE TITLE
Cloudflare Tunnel ssl issue

### ISSUE THREAD

**Issue by Gavyz** [louislam/uptime-kuma#3245]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [x] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### Description

![image](https://github.com/louislam/uptime-kuma/assets/88584060/0023aedf-1b7c-4ead-ad52-0c68c8430d80)
![image](https://github.com/louislam/uptime-kuma/assets/88584060/b9a171e2-2681-4d1e-a99b-1a82f37cea1d)

### 👟 Reproduction steps

I followed the steps on the wiki for cloudflared.

### 👀 Expected behavior

It is supposed to give the website a ssl.

### 😓 Actual Behavior

I got no ssl for the website

### 🐻 Uptime-Kuma Version

1.21.3

### 💻 Operating System and Arch

Ubuntu 22.04 (docker)

### 🌐 Browser

Brave 1.52.122 (Chromium 114.0.5735.110)

### 🐋 Docker Version

24.0.2

**Comment by louislam** [comment]
Have you added https:// manually at the beginning of url?

**Comment by Gavyz** [comment]
@louislam That works but how can i make it automatically make it into https?

**Comment by louislam** [comment]
This may help:
https://developers.cloudflare.com/ssl/edge-certificates/additional-options/always-use-https/

**Comment by Gavyz** [comment]
/\ This helped
