### ISSUE TITLE
port forwarding- /metrics safe?

### ISSUE THREAD

**Issue by kenhoppla** [louislam/uptime-kuma#3247]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

I'm fairly new to this topic, so please excuse me if I ask any naive questions.

I recently set up uptime-kuma with NGINX on my DuckDNS domain. Everything seems to be functioning properly. However, I noticed that I can view my statistics, such as tested URLs and servers, at domain.example/metrics without having to log in. Is this considered safe, or is there a way to disable it?

Thanks for your help!

### 🐻 Uptime-Kuma Version

0.7.4

### 💻 Operating System and Arch

HomeAssistantOS

### 🌐 Browser

Brave

**Comment by louislam** [comment]
https://status.kuma.pet/metrics

It is supposed to be private.


![image](https://github.com/louislam/uptime-kuma/assets/1336778/b9de0764-f3cc-46e9-8ecf-b66f35ddcf2b)

**Comment by kenhoppla** [comment]
Can I configure this in the uptime-kuma settings?

**Comment by kenhoppla** [comment]
> There is no specific configuration for the Prometheus metrics endpoint.
> 
> * At the start when you have completed setup, the `/metrics` endpoint is protected by your username & password.
> * If you added an API key in Settings -> API Keys, the `/metrics` endpoint is protected by the API keys in the Settings page.
> * If you disabled authentication in Security -> Disable Auth, the `/metrics` endpoint is also publicly available.
> 
> You can reach your desired state by configuring these settings. If you did not do these things, open new Browser Private Window, go to `/metics` and see that it's available without login, you have found a bug.

Reinstalled AdGuard and now everything is working as expected. Thanks for your help!
