### ISSUE TITLE
Hostname/IP does not match certificate's altnames: Host: api.telegram.org

### ISSUE THREAD

**Issue by walkercz** [louislam/uptime-kuma#3250]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### Description

when try to test telegram notification error occures

Error: Hostname/IP does not match certificate's altnames: Host: api.telegram.org. is not in the cert's altnames: DNS:*.internalll.synology.me, DNS:internalll.synology.me
    at Telegram.send (/app/server/notification-providers/telegram.js:31:23)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Socket.<anonymous> (/app/server/server.js:1209:27)

### 👟 Reproduction steps

deployed docker container
set up telegram notification
test
error

### 👀 Expected behavior

test should go ok and telegram notification should work

### 😓 Actual Behavior

when tried to test the telegram notification via the test button, app throws an error

Error: Hostname/IP does not match certificate's altnames: Host: api.telegram.org. is not in the cert's altnames: DNS:*.internalll.synology.me, DNS:internalll.synology.me

### 🐻 Uptime-Kuma Version

Version: 1.21.3

### 💻 Operating System and Arch

proxmox lxc container ubuntu 20.04.6 LTS louislam/uptime-kuma:1

### 🌐 Browser

google chrome 

### 🐋 Docker Version

docker 24.0.2

### 📝 Relevant log output

```shell
Error: Hostname/IP does not match certificate's altnames: Host: api.telegram.org. is not in the cert's altnames: DNS:*.internalll.synology.me, DNS:internalll.synology.me
    at Telegram.send (/app/server/notification-providers/telegram.js:31:23)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Socket.<anonymous> (/app/server/server.js:1209:27)
```

**Comment by CommanderStorm** [comment]
I cannot reproduce this in my local docker environment
![image](https://github.com/louislam/uptime-kuma/assets/26258709/44d44e1b-ef0a-4368-becd-627484059b01)

Given that you are getting a selfsighend certificate from synology, can this be an issue?

**Comment by walkercz** [comment]
ahh closed, blocked by synology safe access .. really sorry for bothering you
