### ISSUE TITLE
"performance" issue

### ISSUE THREAD

**Issue by KxmischerLasse** [louislam/uptime-kuma#3252]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

The CPU Usage is very hight when a user is on the status page

https://prnt.sc/FsaC0mIRN4Y6

Red Arrow -> When a User is on the Status Page
Green Arrow -> When no User is on the Status Page

Server is running on a intel core i9 9900k
![Screenshot_1](https://github.com/louislam/uptime-kuma/assets/67797390/745cfeef-8714-4eec-bd31-7fe5ea51e22c)

### 🐻 Uptime-Kuma Version

Latest Release

### 💻 Operating System and Arch

Debian 11

### 🌐 Browser

Brave (Google Chrome)

### 🐋 Docker Version

Latest

### 🟩 NodeJS Version

Latest version installed by uptime kuma

**Comment by CommanderStorm** [comment]
That the CPU usage is higher when we are rendering the status page for a user and delviering realtime updates (especially if you have many monitors in the status page) to the user is to be expected imo..
Am I missing the question?
