### ISSUE TITLE
Every notification is sent double.

### ISSUE THREAD

**Issue by HellStorm666** [louislam/uptime-kuma#3255]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### Description

Notifications from uptime-kuma are sent twice instead of just one time.
I've setup a notification to Teams and to Gotify.
Both applications receive 2 messages (so 4 in total) if some service went down or up.

This happens on my uptime-kuma setup in LXC, at the office setup in Docker and in our Oracle cloud setup in Docker.

### 👟 Reproduction steps

configure a service to monitor with default settings.
configure teams and/or gotify for notifications with default settings.
Bring service down.

### 👀 Expected behavior

Get 1 message on Teams and 1 message on Gotify that service is down.

### 😓 Actual Behavior

I get 2 messages in Teams and 2 messages on Gotify that the service is down.

### 🐻 Uptime-Kuma Version

1.21.3

### 💻 Operating System and Arch

Docker and LXC

### 🌐 Browser

Latest stable Edge

### 🐋 Docker Version

23.0.6

**Comment by CommanderStorm** [comment]
This seems strange.

Are you shure that you have:
- only one instance of uptime-kuma running?
- only two notification providers configured
- Gotify and Teams dont sync messages between each other (i.e. gotify forwards to teams)

**Comment by HellStorm666** [comment]
> This seems strange.
> 
> Are you shure that you have:
> 
> * only one instance of uptime-kuma running?
> * only two notification providers configured
> * Gotify and Teams dont sync messages between each other (i.e. gotify forwards to teams)

`:)
So, seemed that uptime-kuma had a second docker container spanned... Shutdown the second container and now I get only 1 message :)
