### ISSUE TITLE
Question about the update

### ISSUE THREAD

**Issue by Reyah9999** [louislam/uptime-kuma#3258]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

How to update uptime kuma? I write these commands:

docker pull louislam/uptime-kuma:1
docker stop uptime-kuma
docker rm uptime-kuma
docker run -d --restart=always -p 3001:3001 -v uptime-kuma:/app/data --name uptime-kuma louislam/uptime-kuma:1

But nothing happens

### 🐻 Uptime-Kuma Version

1.21.3

### 💻 Operating System and Arch

Ubuntu 22.04

### 🌐 Browser

Yandex 23.5.2.625 (64-bit)

**Comment by Reyah9999** [comment]
🐳 Docker

**Comment by louislam** [comment]
You meant you are using 1.21.3, but you want to try the beta version?

If yes, you have to change the image to `louislam/uptime-kuma:beta`

**Comment by Reyah9999** [comment]
> You meant you are using 1.21.3, but you want to try the beta version?
> 
> If yes, you have to change the image to `louislam/uptime-kuma:beta`

How to do it? What commands should I enter?

**Comment by louislam** [comment]
> > You meant you are using 1.21.3, but you want to try the beta version?
> > If yes, you have to change the image to `louislam/uptime-kuma:beta`
> 
> How to do it? What commands should I enter?

Just need to modify your commend:
```
docker stop uptime-kuma
docker rm uptime-kuma
docker run -d --restart=always -p 3001:3001 -v uptime-kuma:/app/data --name uptime-kuma louislam/uptime-kuma:beta
```

**Comment by Reyah9999** [comment]
> > > You meant you are using 1.21.3, but you want to try the beta version?
> > > If yes, you have to change the image to `louislam/uptime-kuma:beta`
> > 
> > 
> > How to do it? What commands should I enter?
> 
> Just need to modify your commend (Please noted that the beta version is relatively not stable):
> 
> ```
> docker stop uptime-kuma
> docker rm uptime-kuma
> docker run -d --restart=always -p 3001:3001 -v uptime-kuma:/app/data --name uptime-kuma louislam/uptime-kuma:beta
> ```

thx

**Comment by jhowbhz** [comment]
> > > > You meant you are using 1.21.3, but you want to try the beta version?
> > > > If yes, you have to change the image to `louislam/uptime-kuma:beta`
> > > 
> > > 
> > > How to do it? What commands should I enter?
> > 
> > 
> > Just need to modify your commend (Please noted that the beta version is relatively not stable):
> > ```
> > docker stop uptime-kuma
> > docker rm uptime-kuma
> > docker run -d --restart=always -p 3001:3001 -v uptime-kuma:/app/data --name uptime-kuma louislam/uptime-kuma:beta
> > ```
> 
> thx

Work for me, thanks!
