### ISSUE TITLE
Dashboard empty as if no data was input, extremely large history database

### ISSUE THREAD

**Issue by michalb314** [louislam/uptime-kuma#3261]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### Description

After installing Kuma through a docker install, after a while there's a bug when after editing a monitor, everything will disappear - all monitors, settings, etc. It's as if Kuma has been reset to a post-install state.

This has happened on an install that has around 300 monitors checking every minute. I think it has something to do with the database, since when i checked, the database size reported to be 1400mb (in options). When i deleted the whole history, dtabase history dropped to 5mb and Kuma started showing my monitors and all options have been loaded to their previous values. Since then everything is working fine.

### 👟 Reproduction steps

- Install kuma through docker
- Add a lot of monitors (300 in my case)
- Wait until the database history is around 1,4gb
- Edit a monitor

### 👀 Expected behavior

Monitor succesfully edits, application continues work.

### 😓 Actual Behavior

Every monitor and setting disappears.

### 🐻 Uptime-Kuma Version

1.21.3

### 💻 Operating System and Arch

Debian GNU/Linux 9 (stretch)

### 🌐 Browser

Firefox 113.0.2 (also other browsers)

### 🐋 Docker Version

19.03.15, build 99e3ed8919

**Comment by chakflying** [comment]
Likely to be another duplicate of #2346

**Comment by CommanderStorm** [comment]
@michalb314 does the log show similar output as #2346?
What hardware are you letting your instance run on? (slower SSD?)

**Comment by michalb314** [comment]
@CommanderStorm Yes, the log shows pretty much the exact same error message:  
KnexTimeoutError: Knex: Timeout acquiring a connection. The pool is probably full. Are you missing a .transacting(trx) call? at Client_SQLite3.acquireConnection (/app/node_modules/knex/lib/client.js:312:26)
There's a few different SQL queries where this fails, but i feel like it's not the query that's an issue, but the database size/performance itself.

Unfortunately i'm not able to debug as per your request, lack of time.

I don't really have exact hardware specs, it's an OVH VPS with a nvme SSD. 

I feel like the issue related enough to warrant closing this issue, so please go ahead if you feel like it's a preferable course of action.

**Comment by michalb314** [comment]
Right, i did not know that, thank you.

Closed as per above. Related to #2346
