### ISSUE TITLE
Bug when editing monitor(type group)

### ISSUE THREAD

**Issue by DevItq** [louislam/uptime-kuma#3262]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 👟 Reproduction steps

Need to create monitor(type: group), then link some monitors to it, then change type(group to other type)

### 👀 Expected behavior

...

### 😓 Actual Behavior

All monitors which was linked are still linked after changing type and we can't unlink them

### 🐻 Uptime-Kuma Version

1.22.0-beta.0

### 💻 Operating System and Arch

Replit

### 🌐 Browser

Google Chrome

**Comment by DevItq** [comment]
I suggest just to unlink monitors(which was linked to group) when changing type of group

**Comment by louislam** [comment]
Thank you for testing it, I didn't notice this.

**Comment by tarun7singh** [comment]
@DevItq @louislam Added a fix for this.
