### ISSUE TITLE
[Request] Status page: Customize the time period for the status ticks 

### ISSUE THREAD

**Issue by JamesMenetrey** [louislam/uptime-kuma#3264]
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

UI Feature

### 🔖 Feature description

Currently, status pages display ticks representing an interval of one minute. Consequently, users of status pages cannot see more than a period of time going above one hour.

This is quite limited when hosting services where we would like to build trust with our users and have a more holistic view of the uptime of our services.

### ✔️ Solution

Introduce a setting on the status page that would allow you to specify a time period covered by the ticks.

### ❓ Alternatives

An alternative setting would be to specify the duration of a tick (1 minute, 1 hour, 4 hour, 1 day, etc.).

**Comment by ra-coder** [comment]
Also would like to have this feature

**Comment by CommanderStorm** [comment]
@ra-coder 

Please refrain from posting `+1` / requests for updates things on issues, as this makes issue-management harder.
Issues are for discussing what needs to be done how by whom.
[We use 👍🏻 on issues to prioritise work](https://github.com/louislam/uptime-kuma/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).

**Comment by CommanderStorm** [comment]
@JamesMenetrey 
I think this is a duplicate of #1888
If you agree, could you please close this Issue, as duplicates only create immortal zombies and are really hard to issue-manage?
If not, what makes this issue unique enough to require an additional issue? (Could this be integrated into the issue linked above?) ^^

**Comment by JamesMenetrey** [comment]
After reviewing #1888, this issue would satisfy this one if implemented. I cross my fingers it gets worked on soon! :)

**Comment by plgonzalezrx8** [comment]
Was this ever implemented? I cannot find this feature and want to create an issue but found this one, so I was wondering if there's a solution to this.

**Comment by CommanderStorm** [comment]
@plgonzalezrx8 

From https://github.com/louislam/uptime-kuma/issues/1888#issuecomment-2068191172:

> No it has not. In v1 the performance simply was not good enough to support this.
> 
> In v2, this should be possible.
See https://github.com/louislam/uptime-kuma/pull/4264 for further context on the PR that would enable configuring such a feature on the dashboard.
The status page does not have such a dependency, but needs somebody to implement it.
Our contribution guide is here: https://github.com/louislam/uptime-kuma/blob/master/CONTRIBUTING.md
> 
> A synthetic benchmark which spawns some monitors and looks how the server handles it would likely be needed. See https://github.com/louislam/uptime-kuma/issues/4500 for how to get involved.
