### ISSUE TITLE
Push Monitor Retries Not Work

### ISSUE THREAD

**Issue by erencylk** [louislam/uptime-kuma#3266]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### Description

I have a push monitor. While it should check 3 times, it goes down without doing this.

### 👟 Reproduction steps

Push Monitor 3 Retries

### 👀 Expected behavior

Wait 3 Push

### 😓 Actual Behavior

Not Wait 3 Push
![image](https://github.com/louislam/uptime-kuma/assets/24528547/2680df58-048d-4092-9c20-80618d337a28)

### 🐻 Uptime-Kuma Version

1.21.3

### 💻 Operating System and Arch

Ubuntu 20.04

### 🌐 Browser

Chrome

**Comment by chakflying** [comment]
Duplicate of #3208 and #1863
