### ISSUE TITLE
Unable to clone any monitors

### ISSUE THREAD

**Issue by ScottJohansen** [louislam/uptime-kuma#3269]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### Description

![image](https://github.com/louislam/uptime-kuma/assets/136326947/c53f90a8-7799-45a8-84ad-831156deb362)
This error shows up whenever i click save when trying to clone any monitor. Error shows a column is missing. Only just migrated from 1.21.3 and error has only shown since.

### 👟 Reproduction steps

Anytime i try to save a cloned monitor

### 👀 Expected behavior

It would clone the monitor.

### 😓 Actual Behavior

It throws this error and does not clone the monitor

### 🐻 Uptime-Kuma Version

1.22.0-beta.0

### 💻 Operating System and Arch

Alma Linux / Docker Container

### 🌐 Browser

Google Chrome

### 🐋 Docker Version

24.0.2

### 📝 Relevant log output

```shell
insert into `monitor` (`accepted_statuscodes_json`, `active`, `auth_domain`, `auth_method`, `auth_workstation`, `basic_auth_pass`, `basic_auth_user`, `body`, `children_i_ds`, `database_connection_string`, `database_query`, `description`, `dns_last_result`, `dns_resolve_server`, `dns_resolve_type`, `docker_container`, `docker_host`, `expiry_notification`, `force_inactive`, `game`, `grpc_body`, `grpc_enable_tls`, `grpc_metadata`, `grpc_method`, `grpc_protobuf`, `grpc_service_name`, `grpc_url`, `headers`, `hostname`, `http_body_encoding`, `ignore_tls`, `interval`, `keyword`, `maxredirects`, `maxretries`, `method`, `mqtt_password`, `mqtt_success_message`, `mqtt_topic`, `mqtt_username`, `name`, `packet_size`, `parent`, `path_name`, `proxy_id`, `push_token`, `radius_called_station_id`, `radius_calling_station_id`, `radius_password`, `radius_secret`, `radius_username`, `resend_interval`, `retry_interval`, `tls_ca`, `tls_cert`, `tls_key`, `type`, `upside_down`, `url`, `user_id`, `weight`) values ('["200-299"]', true, NULL, NULL, NULL, NULL, NULL, NULL, , NULL, NULL, NULL, NULL, '1.1.1.1', 'A', NULL, NULL, true, false, NULL, NULL, false, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, false, 60, NULL, 10, 0, 'GET', NULL, NULL, NULL, NULL, 'Clone of Brunelhealth CRM', 56, NULL, 'Brunelhealth CRM', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, 60, NULL, NULL, NULL, 'http', false, 'https://crm.brunelhealth.com', 1, 2000) - SQLITE_ERROR: table monitor has no column named children_i_ds
```

**Comment by kokofixcomputers** [comment]
In the relevant log it seems like there is something wrong with groups try switching back to version: 1.21.3
