### ISSUE TITLE
High Ping Times

### ISSUE THREAD

**Issue by rdavey228** [louislam/uptime-kuma#327]
I'm noticing incorrect high ping times reported in Kuma.

Pings to google are displaying as over 300ms and even internal services on my network are over 100ms!

If I run a ping command from my docker host I get ping times of under 1ms. I also run the same ping test inside the Kuma container from the command line and get the same 1ms result.

Why are ping times displayed so high on the Kuma dashboard?

**Comment by louislam** [comment]
> I also run the same ping test inside the Kuma container from the command line and get the same 1ms result.

Actually Uptime Kuma is using the same `ping` command to get the ping time.

You can try with the exact command manually in the container.
```
ping -n -w 2 -c 1 <hostname>
```

So, what is the monitor type? 

If it is a HTTP type, it is normal, because it is a HTTP response time, not a ping time.

**Comment by rdavey228** [comment]
> > I also run the same ping test inside the Kuma container from the command line and get the same 1ms result.
> 
> Actually Uptime Kuma is using the same `ping` command to get the ping time.
> 
> You can try with the exact command manually in the container.
> 
> ```
> ping -n -w 2 -c 1 <hostname>
> ```
> 
> So, what is the monitor type?
> 
> If it is a HTTP type, it is normal, because it is a HTTP response time, not a ping time.

Ah ok, that makes sense then!  I changed the monitor type to ping rather than HTTP and I see 1ms now as expected.

Its confusing as if the sensor type is HTTP it displays the response time under ping when its technically not a ping. You should have a ping stat and then another section that says HTTP response time and put the stat under there. Or have the heading dynamic so that when its a HTTP sensor it says HTTP response time rather than ping response as the heading title.

Just a suggestion.
