### ISSUE TITLE
Teams - Priority / urgent notifications. 

### ISSUE THREAD

**Issue by DarrenRainey** [louislam/uptime-kuma#3271]
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

New Notification

### 🔖 Feature description

For teams notifications it would be nice to be able to set the priority e.g Important or Urgent (Everyone in the teams group will be notified every 2 minutes for 20 minutes) as currently alerts are just sent as regular messages they may be missed.
![image](https://github.com/louislam/uptime-kuma/assets/6136439/8c5aa0b9-108c-47c2-97c6-892a4b5aad06)

### ✔️ Solution

Add an option to the teams notification provider to set the priority of the message e.g. normal, important or urgent.

### ❓ Alternatives

I guess you could setup email notifications since teams allows you to setup an email address that will automatically post messages and will display the importance level if set in the email however I haven't looked into this option much as we are restricted to what accounts we can generate e.g. no email access for the bot.

**Comment by tarun7singh** [comment]
@DarrenRainey Looked at this and seems like this option is not available for webhooks.

**Comment by DarrenRainey** [comment]
Closed as currently not possible from application side.
