### ISSUE TITLE
[Ntfy] Action link should only be included if url is defined

### ISSUE THREAD

**Issue by cfouche3005** [louislam/uptime-kuma#3274]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### Description

When using the ntfy notification, uptime-kuma create an action button to go to the uptime-kuma page on the ntfy notification but the actual link is not completed. The main URL is setup on uptime-kuma

### 👟 Reproduction steps

Create an ntfy notification
Receive a down or up notification
Click on the action button on ntfy
See the result

### 👀 Expected behavior

the action button take you to the uptime-kuma page

### 😓 Actual Behavior

the action button take you to a about:blank page

![image](https://github.com/louislam/uptime-kuma/assets/51720655/ea758a08-ff64-4980-aed0-745daed2a139)

### 🐻 Uptime-Kuma Version

1.22.0-beta.0

### 💻 Operating System and Arch

Fly.io 

### 🌐 Browser

Not browser related

### 🐋 Docker Version

Fly.io

**Comment by CommanderStorm** [comment]
Relavant Code:
https://github.com/louislam/uptime-kuma/blob/master/server/notification-providers/ntfy.js#L58

**Comment by clesmian** [comment]
This seems to happen for those cases where no URL is available, e.g. when monitoring a docker container. Could this also be the issue in your case @cfouche3005 ?

**Comment by cfouche3005** [comment]
Yes, I can confirm (when I create an http monitor, the button on the notification redirect me to the monitored website), I was thinking that the button redirected to the probe on uptime-kuma, not the monitored website (but it make sense)

**Comment by CommanderStorm** [comment]
> This seems to happen for those cases where no URL is available

@cfouche3005
What is the expected case and what is currently implemented?
Is this resolved?
I am confused

**Comment by cfouche3005** [comment]
@CommanderStorm Sorry if it wasn't clear (English is not my first language), the issue is just a "normal" behavior : Uptime-Kuma set the action button web link with the monitored website but for Groups (or docker container), witch doesn't have a web link, it just set a blank link. The rest of the issue was just a misunderstanding of the actual behavior.
This issue might be a non issue.

**Comment by clesmian** [comment]
Actually in case there is no URL, I think it should either set the field to something meaningful (e.g. the URL of the monitor) or not enable the button at all. Setting the button to an empty action is just confusing and not helpful to a user.
