### ISSUE TITLE
Windows portable has malware according to windows defender & fortinet

### ISSUE THREAD

**Issue by vanhoutenbos** [louislam/uptime-kuma#3275]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

I tried to download and install the .zip version of uptime-kuma but I get warnings from microsoft and fortinet that it is not safe to download this zip.
Could you please investigate and repack if needed?

https://www.virustotal.com/gui/url/428902b85893f7e3a4773e5eedcec733e98065eea289b477ce05d9a3a96614ad/detection

### 📝 Error Message(s) or Log

1 security vendor flagged this URL as malicious

### 🐻 Uptime-Kuma Version

1.21.0

### 💻 Operating System and Arch

Windows 11

### 🌐 Browser

Google Chrome latest

**Comment by chakflying** [comment]
Duplicate of #3142
