### ISSUE TITLE
How to improve performance of uptime kuma

### ISSUE THREAD

**Issue by mabed-fr** [louislam/uptime-kuma#3279]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

My problem is not a very important problem, but i constate for print chart is too slow, i see a external SQL integration feature for 2.0 is in progress.

After a lot of reviews of type of database a NoSQL database is not more adapted ? the write and read is very very more performant is NoSQL, and Nosql can manage internal data of uptime kuma and result of check. 

Other idea is to use SQL for the part of authentification and internal data for uptime kuma and TSDB for register heath check result  , this solution is more complicated but more performant also.

Enjoy discute with you !

### 🐻 Uptime-Kuma Version

2.0.0

### 💻 Operating System and Arch

Debian 11

### 🌐 Browser

Chrome

### 🐋 Docker Version

Docker

**Comment by CommanderStorm** [comment]
See https://github.com/louislam/uptime-kuma/pull/3017
See https://github.com/louislam/uptime-kuma/pull/2750
