### ISSUE TITLE
incident report

### ISSUE THREAD

**Issue by regchanuk** [louislam/uptime-kuma#3282]
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

New Notification, UI Feature

### 🔖 Feature description

when updating incident report i would like this to be also added to the notifications sent out by the system to all platforms is this possiblly able to be done 

### ✔️ Solution

i like to notify people with in telegram group 

### ❓ Alternatives

inseting message again in to the group 

### 📝 Additional Context

![image](https://github.com/louislam/uptime-kuma/assets/46360316/16a10bdd-51ae-453f-b076-5b5aec44d3ec)

![image](https://github.com/louislam/uptime-kuma/assets/46360316/42f254d1-c5e8-4add-b211-be1fc20f8415)

images are provided for some context

**Comment by CommanderStorm** [comment]
This seems like a duplicate of https://github.com/louislam/uptime-kuma/issues/718
**If it is, please close this issue (duplicates only hurt feature discoverability)**
If it is not, please make this more distinct.
Note that subscription is tracked in https://github.com/louislam/uptime-kuma/issues/916 (duplicates: https://github.com/louislam/uptime-kuma/issues/3022 or https://github.com/louislam/uptime-kuma/issues/2462)

Current implementation has stalled: https://github.com/louislam/uptime-kuma/pull/725#issuecomment-1557659075
Contributions in this department would likely be accepted, as Louis has already indicated aproval in https://github.com/louislam/uptime-kuma/pull/725#issuecomment-949317992.

**Comment by regchanuk** [comment]
this can be claosed sorry for any inconvenience this has already been requested
