### ISSUE TITLE
Error 404, on Docker Installation for 2 known working Dockers (out of 20)

### ISSUE THREAD

**Issue by bmpreston** [louislam/uptime-kuma#3284]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

I've only been using Uptime Kuma for about 12 hours.  I believe I have done searches for this, and found errors pertaining to a slash // at the end of a website/domain name.  My Uptime functioned throughout the night at began throwing error 404 offlines for 2 Docker instances.  Unknown source.  I have restarted the 2 dockers in question.  Both were functioning, both are functioning now.  I have since completely stopped and restarted Docker on my Unraid installation, error persists.  Logs have been pulled, I don't see any source of these errors, it just started...

### 📝 Error Message(s) or Log

{"log":"2023-06-19T00:01:23-04:00 [AUTH] INFO: Successfully logged in user brian@prestons.family. IP=**SCRUBBED**\n","stream":"stdout","time":"2023-06-19T04:01:23.894943905Z"}
{"log":"2023-06-19T03:01:15-04:00 [MONITOR] WARN: Monitor #4 'DDNS Updater': Pending: Request failed with status code 404 | Max retries: 1 | Retry: 1 | Retry Interval: 60 seconds | Type: docker\n","stream":"stderr","time":"2023-06-19T07:01:15.438854446Z"}
{"log":"2023-06-19T03:01:16-04:00 [MONITOR] WARN: Monitor #11 'Radarr': Pending: Request failed with status code 404 | Max retries: 1 | Retry: 1 | Retry Interval: 60 seconds | Type: docker\n","stream":"stderr","time":"2023-06-19T07:01:16.887466769Z"}
{"log":"2023-06-19T03:02:16-04:00 [MONITOR] WARN: Monitor #4 'DDNS Updater': Failing: Request failed with status code 404 | Interval: 60 seconds | Type: docker | Down Count: 0 | Resend Interval: 0\n","stream":"stderr","time":"2023-06-19T07:02:16.159794725Z"}
{"log":"2023-06-19T03:02:17-04:00 [MONITOR] WARN: Monitor #11 'Radarr': Failing: Request failed with status code 404 | Interval: 60 seconds | Type: docker | Down Count: 0 | Resend Interval: 0\n","stream":"stderr","time":"2023-06-19T07:02:17.232571774Z"}
{"log":"2023-06-19T03:03:16-04:00 [MONITOR] WARN: Monitor #4 'DDNS Updater': Failing: Request failed with status code 404 | Interval: 60 seconds | Type: docker | Down Count: 0 | Resend Interval: 0\n","stream":"stderr","time":"2023-06-19T07:03:16.201994348Z"}
{"log":"2023-06-19T03:03:17-04:00 [MONITOR] WARN: Monitor #11 'Radarr': Failing: Request failed with status code 404 | Interval: 60 seconds | Type: docker | Down Count: 0 | Resend Interval: 0\n","stream":"stderr","time":"2023-06-19T07:03:17.324420224Z"}
{"log":"2023-06-19T03:04:16-04:00 [MONITOR] WARN: Monitor #4 'DDNS Updater': Failing: Request failed with status code 404 | Interval: 60 seconds | Type: docker | Down Count: 0 | Resend Interval: 0\n","stream":"stderr","time":"2023-06-19T07:04:16.258745908Z"}
{"log":"2023-06-19T03:04:17-04:00 [MONITOR] WARN: Monitor #11 'Radarr': Failing: Request failed with status code 404 | Interval: 60 seconds | Type: docker | Down Count: 0 | Resend Interval: 0\n","stream":"stderr","time":"2023-06-19T07:04:17.384971272Z"}
{"log":"2023-06-19T03:05:16-04:00 [MONITOR] WARN: Monitor #4 'DDNS Updater': Failing: Request failed with status code 404 | Interval: 60 seconds | Type: docker | Down Count: 0 | Resend Interval: 0\n","stream":"stderr","time":"2023-06-19T07:05:16.298362511Z"}
{"log":"2023-06-19T03:05:17-04:00 [MONITOR] WARN: Monitor #11 'Radarr': Failing: Request failed with status code 404 | Interval: 60 seconds | Type: docker | Down Count: 0 | Resend Interval: 0\n","stream":"stderr","time":"2023-06-19T07:05:17.448586584Z"}
{"log":"2023-06-19T03:06:16-04:00 [MONITOR] WARN: Monitor #4 'DDNS Updater': Failing: Request failed with status code 404 | Interval: 60 seconds | Type: docker | Down Count: 0 | Resend Interval: 0\n","stream":"stderr","time":"2023-06-19T07:06:16.347383994Z"}
{"log":"2023-06-19T03:06:17-04:00 [MONITOR] WARN: Monitor #11 'Radarr': Failing: Request failed with status code 404 | Interval: 60 seconds | Type: docker | Down Count: 0 | Resend Interval: 0\n","stream":"stderr","time":"2023-06-19T07:06:17.49067831Z"}
{"log":"2023-06-19T03:07:16-04:00 [MONITOR] WARN: Monitor #4 'DDNS Updater': Failing: Request failed with status code 404 | Interval: 60 seconds | Type: docker | Down Count: 0 | Resend Interval: 0\n","stream":"stderr","time":"2023-06-19T07:07:16.397953359Z"}
{"log":"2023-06-19T03:07:17-04:00 [MONITOR] WARN: Monitor #11 'Radarr': Failing: Request failed with status code 404 | Interval: 60 seconds | Type: docker | Down Count: 0 | Resend Interval: 0\n","stream":"stderr","time":"2023-06-19T07:07:17.546805414Z"}

### 🐻 Uptime-Kuma Version

1.21.3

### 💻 Operating System and Arch

Unraid 6.12.0

### 🌐 Browser

Google Chrome on Version 114.0.5735.133

### 🐋 Docker Version

23.0.6

### 🟩 NodeJS Version

null

**Comment by CommanderStorm** [comment]
Is there something that is different for these tow docker insances? Are they in a different docker-network/...
What do these tow instances have in common?

Longshot: What is the amount of pings you have set up and is your storage slow?

**Comment by bmpreston** [comment]
> Is there something that is different for these tow docker insances? Are they in a different docker-network/... ? What do these two instances have in common?

So I figured it out.  These are set for Docker, and both were updated at 0300.  They must have a new container ID.  (Confirming now). Confirmed.  They pulled new images and the container ID is not the same.  How might I set this up for Docker and not worry about continuously changing IDs.

> 
> What do you mean by
> 
> > I believe I have done searches for this, and found errors pertaining to a slash // at the end of a website/domain name.
> 
> (slashes at the end of URLs are different URLs)
> 

The questions asked when submitted a ticket is 'have you searched for this issue before.'

> Longshot: What is the amount of pings you have set up and is your storage slow?

**Comment by CommanderStorm** [comment]
> The questions asked when submitted a ticket is 'have you searched for this issue before.'

Cannot reproduce:
![image](https://github.com/louislam/uptime-kuma/assets/26258709/eecfc305-b3ba-4354-9663-31a853e727da)

**Comment by bmpreston** [comment]
It is not resolved.  I'm wondering how to keep the Docker sock from
creating new IDs on each upgrade.

**Comment by bmpreston** [comment]
> > The questions asked when submitted a ticket is 'have you searched for this issue before.'
> 
> Cannot reproduce: ![image](https://user-images.githubusercontent.com/26258709/246884551-eecfc305-b3ba-4354-9663-31a853e727da.png)

I'm confused.  My text wasn't to the quote, but the question was asked, 'I checked and didn't find similar issue'. I then typed "I believe I have done searches for this, and found errors pertaining to a slash // at the end of a website/domain name."

I was answering the question of the form...
