### ISSUE TITLE
Improve sqlite handling

### ISSUE THREAD

**Issue by otbutz** [louislam/uptime-kuma#3286]
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

Other

### 🔖 Feature description

uptime-kuma should run `PRAGMA optimize` on a regular basis as recommended by the sqlite devs:

> To achieve the best long-term query performance without the need to do a detailed engineering analysis of the application schema and SQL, it is recommended that applications run "PRAGMA optimize" (with no arguments) just before closing each [database connection](https://www.sqlite.org/c3ref/sqlite3.html). **Long-running applications might also benefit from setting a timer to run "PRAGMA optimize" every few hours.**

https://www.sqlite.org/pragma.html#pragma_optimize

We should also shift the temp_store into memory:

> When temp_store is MEMORY (2) [temporary tables](https://www.sqlite.org/inmemorydb.html#temp_db) and indices are kept as if they were in pure [in-memory databases](https://www.sqlite.org/inmemorydb.html).

https://www.sqlite.org/pragma.html#pragma_temp_store

While uptime-kuma doesn't use temporary tables, sqlite might create transient indices for some queries.

https://www.sqlite.org/tempfiles.html#transient_indices

### ✔️ Solution

* timer for `PRAGMA optimize;`
* execute `PRAGMA temp_store = MEMORY;` during DB setup

**Comment by otbutz** [comment]
It my also be worth to experiment with MMAP:

https://www.sqlite.org/pragma.html#pragma_mmap_size

**Comment by CommanderStorm** [comment]
Interesting.
We should probably develop benchmarks to test what impact these Pragmas have first.
CC @chakflying : What do you think would be a good benchmark? Is such a benchmark needed in your opinion?

## Ideas for load-generation:
- Creating 100 Ping monitors and ping big, public websites?
- Create 5 status sites with 10 Monitors each
- simulate 1 User which are logged into the main UI
- simulate 5 Users requesting each of the status sites each once a second

## Measurement:
Idk, what metrics could be good indicators.  
I woud tend to argue, that these could be good indicators, but maybe we need to introduce a histogram for database request latency:
```
# HELP nodejs_eventloop_lag_seconds Lag of event loop in seconds.
# TYPE nodejs_eventloop_lag_seconds gauge
nodejs_eventloop_lag_seconds 0

# HELP nodejs_eventloop_lag_min_seconds The minimum recorded event loop delay.
# TYPE nodejs_eventloop_lag_min_seconds gauge
nodejs_eventloop_lag_min_seconds 0.000010752

# HELP nodejs_eventloop_lag_max_seconds The maximum recorded event loop delay.
# TYPE nodejs_eventloop_lag_max_seconds gauge
nodejs_eventloop_lag_max_seconds 4.341104639

# HELP nodejs_eventloop_lag_mean_seconds The mean of the recorded event loop delays.
# TYPE nodejs_eventloop_lag_mean_seconds gauge
nodejs_eventloop_lag_mean_seconds 0.010128117050246792

# HELP nodejs_eventloop_lag_stddev_seconds The standard deviation of the recorded event loop delays.
# TYPE nodejs_eventloop_lag_stddev_seconds gauge
nodejs_eventloop_lag_stddev_seconds 0.0005632039789133666

# HELP nodejs_eventloop_lag_p50_seconds The 50th percentile of the recorded event loop delays.
# TYPE nodejs_eventloop_lag_p50_seconds gauge
nodejs_eventloop_lag_p50_seconds 0.010108927

# HELP nodejs_eventloop_lag_p90_seconds The 90th percentile of the recorded event loop delays.
# TYPE nodejs_eventloop_lag_p90_seconds gauge
nodejs_eventloop_lag_p90_seconds 0.010158079

# HELP nodejs_eventloop_lag_p99_seconds The 99th percentile of the recorded event loop delays.
# TYPE nodejs_eventloop_lag_p99_seconds gauge
nodejs_eventloop_lag_p99_seconds 0.010780671
```

**Comment by otbutz** [comment]
We should also look into our usage of autovacuum full. Do we really want to suffer from the potential performance impact on each commit?

https://blogs.gnome.org/jnelson/2015/01/06/sqlite-vacuum-and-auto_vacuum/ (a bit dated but most of is still relevant)

https://www.sqlite.org/pragma.html#pragma_auto_vacuum

The database isn't going to shrink unless a monitor is deleted. Without an explizit `PRAGMA vacuum;` once in a while we'll suffer from fragmentation either way.

**Comment by otbutz** [comment]
As we're using `journalmode=WAL` the pragma `synchronous=FULL` is an overkill. The documentation states that `synchronous=NORMAL` is good enough while using the WAL.

> [WAL mode](https://www.sqlite.org/wal.html) is safe from corruption with synchronous=NORMAL, and probably DELETE mode is safe too on modern filesystems. [WAL mode](https://www.sqlite.org/wal.html) is always consistent with synchronous=NORMAL, but WAL mode does lose durability. A transaction committed in WAL mode with synchronous=NORMAL might roll back following a power loss or system crash. Transactions are durable across application crashes regardless of the synchronous setting or journal mode. The synchronous=NORMAL setting is a good choice for most applications running in WAL mode.

https://www.sqlite.org/pragma.html#pragma_synchronous

**Comment by CommanderStorm** [comment]
> We should also look into our usage of autovacuum full

Related discussion #2800

**Comment by otbutz** [comment]
> > We should also look into our usage of autovacuum full
> 
> Related discussion #2800

I agree with @chakflying on this one. We need to figure out a maintenance/vacuum plan that fits our needs. Constantly truncating the database file on every commit is bad idea.

To be honest, I'd skip autovacuum entirely for the reason pointed out in #2800:

> Currently the server deletes heartbeat data older than the retention period every night. I think theoretically auto_vacuum = FULL also has no use here. Assuming the monitor config is not changed, the server will produce the same amount of data each day. If we cleanup the database every night, all the freelist pages can be reused the next day.

We're basically playing page ping-pong which ultimately risks fragmentation at the filesystem level.

At the same time we should aim to run a full vacuum once in while to fight fragmentation at the database level. Once we do this, I see no point to stick with autovacuum.

**Comment by louislam** [comment]
Yes, I will merge #2800 into the next version.

**Comment by otbutz** [comment]
![image](https://github.com/louislam/uptime-kuma/assets/22315436/c51f7763-3153-4b2f-a857-6fb7f221c269)

A full vacuum currently generates pseudo errors because the database is locked. We should pause checks while this task is running.

**Comment by chakflying** [comment]
I will reply here instead of #2800.

**On the use of incremental_vacuum:**
My plan was to call `incremental_vacuum(N)` during the nightly clean-up, but I can't figure out what should N be. My understanding is if N is not big enough, the database will again grow in size indefinitely. Thinking about this, calling just `incremental_vacuum` to clear the whole freelist is probably the only sensible choice.

**On abandoning auto_vacuum:**
I think there are reasons against using vacuum on a timer. [Vacuum](https://www.sqlite.org/lang_vacuum.html) will create a temporary database file to overwrite the original, meaning that it needs disk space **twice** the current database size to complete. This will create huge disk IO for those with big databases, and will lock up the server for a substantial amount of time.

Vacuum will help with fragmentation, but it's also unclear if fragmentation is really an issue for nightly clean-up. We are just truncating old heartbeats past the required number of days, it should theoretically be a contiguous chunk of pages ready for use again.

**On pausing monitors during vacuum:**
If deleting a monitor will lock up the database due to vacuum, then it's no better than the current situation. Say we pause monitors before vacuum, we will need an application side logic to make sure the current heartbeats are done, then stop queuing the next `setTimeout()`. But even if there are no writes, there can still be reads coming in, like loading the dashboard, status pages, etc. Do we need to stop those as well? Regardless I think there is a non-trivial amount of engineering effort required, and it will be up to louislam if he is interested in taking this on.

**Comment by otbutz** [comment]
> My understanding is if N is not big enough, the database will again grow in size indefinitely.

Why would it? sqlite is reusing free pages within the database file. Citing the sqlite docs:

> Unused database file pages are added to a "[freelist](https://www.sqlite.org/fileformat2.html#freelist)" and reused for subsequent inserts. **So no database file space is lost. However, the database file does not shrink.**

Worst case scenario would be a database file which is too large for the actual number of monitor events in it. As long as we don't intend to reduce the amount of logged events by deleting a monitor or by reducing the retention period, I'd expect the database to stay at a certain size.

> **On abandoning auto_vacuum:** I think there are reasons against using vacuum on a timer. [Vacuum](https://www.sqlite.org/lang_vacuum.html) will create a temporary database file to overwrite the original, meaning that it needs disk space **twice** the current database size to complete. This will create huge disk IO for those with big databases, and will lock up the server for a substantial amount of time.
> 
> Vacuum will help with fragmentation, but it's also unclear if fragmentation is really an issue for nightly clean-up. We are just truncating old heartbeats past the required number of days, it should theoretically be a contiguous chunk of pages ready for use again.

Solid assessment. Maybe we can stick with autovacuum=incremental and use `PRAGMA incremental_vacuum(N);` to handle the shrink functionality on demand. There are only 3 cases where it makes sense to shrink the database:

* deleting a monitor
* choosing a *lower* retention period
* shrink database action in the settings page

In any other case I'd expect the database to grow or keep it's size by recycling free pages.

> **On pausing monitors during vacuum:** If deleting a monitor will lock up the database due to vacuum, then it's no better than the current situation. Say we pause monitors before vacuum, we will need an application side logic to make sure the current heartbeats are done, then stop queuing the next `setTimeout()`. But even if there are no writes, there can still be reads coming in, like loading the dashboard, status pages, etc. Do we need to stop those as well? Regardless I think there is a non-trivial amount of engineering effort required, and it will be up to louislam if he is interested in taking this on.

The main benefit of `incremental_vacuum(N)` would be that we can run this in a loop with a limited amount of pages in order to avoid blocking the UI and monitors for far too long.

**Comment by chakflying** [comment]
I think this issue can be closed since the relevant optimizations have been merged.
