### ISSUE TITLE
Display on the uptime status pages for 30 days

### ISSUE THREAD

**Issue by Shandeika** [louislam/uptime-kuma#3287]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

Why does the status pages display uptime for a day, and not for 30 days? And why can't it be configured?
Dashboard:
![image](https://github.com/louislam/uptime-kuma/assets/43181505/a2fa30ce-fc52-46c2-a2f5-289957b971a9)
Status page:
![image](https://github.com/louislam/uptime-kuma/assets/43181505/c9c81aef-79af-49ba-8879-a56ebb92ffd6)

In my understanding, the status page should display uptime in 30 days. Please write if I can configure it somehow, because I haven't found it.

### 🐻 Uptime-Kuma Version

1.21.3

### 💻 Operating System and Arch

Ubuntu 20.04.6 LTS (GNU/Linux 5.4.0-149-generic x86_64)

### 🌐 Browser

Yandex Browser 23.5.2.625 (64-bit)

### 🐋 Docker Version

Docker 24.0.1

**Comment by CommanderStorm** [comment]
@Shandeika
This is open-source software manned by volunteer maintainers ⇒ it is provided `as is`.
I sense some passive-agressive hostility in your comment, which I will ignore.

Currently there is no configuration option for this. This is a duplicate of #3264 and others like it => please close this issue, as duplicates only hurt issue manageability

**Comment by Shandeika** [comment]
> @Shandeika This is open-source software manned by volunteer maintainers ⇒ it is provided `as is`. I sense some passive-agressive hostility in your comment, which I will ignore.
> 
> Currently there is no configuration option for this. This is a duplicate of #3264 and others like it => please close this issue, as duplicates only hurt issue manageability

No aggression, you have a great open project. I'm glad it exists.
I just wondered if it was possible to configure it. After uptimerobot, it's a little unusual.
I'm sorry that I didn't see similar queries, apparently I was looking badly :(
