### ISSUE TITLE
Running Uptime Kuma on a different server

### ISSUE THREAD

**Issue by Khizar-Akhtar** [louislam/uptime-kuma#3288]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

Is it possible to run Uptime Kuma on a different server instead of localhost?
Actually i want to setup this Uptime kuma on a comopany server  

### 🐻 Uptime-Kuma Version

1.22.0-beta.0

### 💻 Operating System and Arch

FullPage OS Nightly

### 🌐 Browser

Chromium

### 🐋 Docker Version

24.0.2

**Comment by CoderYiXin** [comment]
这是来自QQ邮箱的假期自动回复邮件。你好，我有忙，无法亲自回复你的邮件。我将稍候给你回复。

**Comment by louislam** [comment]
Why not? https://status.kuma.pet

**Comment by CommanderStorm** [comment]
You can refer to https://github.com/louislam/uptime-kuma/wiki/%F0%9F%94%A7-How-to-Install and install it on the VPS/VM/Kubernetes/... of your choice

**Comment by Khizar-Akhtar** [comment]
Ok thanks for the help
