### ISSUE TITLE
Sentry Integration Support

### ISSUE THREAD

**Issue by WilliamDavidHarrison** [louislam/uptime-kuma#3290]
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

Other

### 🔖 Feature description

You should add a feature so when an issue is created on [Sentry](https://sentry.io), an incident is created on Uptime Kuma.

### ✔️ Solution

In my use-case, basically if an issue is opened on Sentry and it is marked as `regression`, it should automatically create an incident on a status page with some basic info about the issue, and basically saying stuff like this issue is known.

### ❓ Alternatives

None

### 📝 Additional Context

None

**Comment by CommanderStorm** [comment]
Given how many false-positives there are in sentry (web extention xyz triggering some obscure error on a privacy focused browser/...) which you likely don't want to show to the public.

How would such an integration work? How complex would it be to develop?

**Comment by WilliamDavidHarrison** [comment]
Maybe if an issue has a manually assigned label such as "incident" or something, it will create the the incident on Uptime Kuma. I'm not very familiar with the Sentry API, but the user would just need to create an integration on Sentry and copy the token. Then on Uptime Kuma, in settings, maybe an option for Sentry where they put the token and enter the specific label for issues to have to create an incident.

**Comment by WilliamDavidHarrison** [comment]
I'm going to close this as I feel like it is not really easy to implement and wouldn't really be that useful.
