### ISSUE TITLE
Error on long reponse time

### ISSUE THREAD

**Issue by christopherpickering** [louislam/uptime-kuma#3292]
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

Other

### 🔖 Feature description

It would be nice to be able to fail monitors based on response time. Like if the page takes longer than 5 secs than fail.

### ✔️ Solution

Fail monitors that take longer than x seconds to reply.

**Comment by CommanderStorm** [comment]
I think this is a duplicate of #2140, #2077, #877 which will be resolved by #2142
If it is, please close this issue. Duplicates dont help in issue discoverability.
If it is distinct enough to warrant another issue, please make it more unique.

**Comment by christopherpickering** [comment]
Just saw that and came to close lol thanks! I searched for the wrong words.

**Comment by CommanderStorm** [comment]
Thanks ^^
