### ISSUE TITLE
Status page - Auto theme does not work on custom domains

### ISSUE THREAD

**Issue by crystalcommunication** [louislam/uptime-kuma#3294]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### Description

If you select the "Auto" theme for a status page and the page has a custom domain, the light theme is always used for the custom domain. The theme works as expected when accessing the status page through the main domain using the `/status/example` URI.

### 👟 Reproduction steps

1. Make sure your browser is set to dark mode
2. Configure a status page to use Auto theme and a custom domain
3. View the status page using the custom domain

### 👀 Expected behavior

When the status page loads, it should be using the dark theme

### 😓 Actual Behavior

The status page uses the light theme

### 🐻 Uptime-Kuma Version

1.22.0-beta.0

### 💻 Operating System and Arch

Debian 11 x86_64

### 🌐 Browser

Firefox 102.11.0esr

### 🟩 NodeJS Version

18.14.2

**Comment by chakflying** [comment]
I have not tested this exact case (custom domain) and I don't have one setup right now. Feel free to help investigate.

**Comment by CommanderStorm** [comment]
A possible cause is, that the default value is 
https://github.com/chakflying/uptime-kuma/blame/596402e71ff9851feb63d3cf2c227bf047182aec/server/socket-handlers/status-page-socket-handler.js#L279
