### ISSUE TITLE
Trigger action when host is down

### ISSUE THREAD

**Issue by tlee-atmosic** [louislam/uptime-kuma#3297]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

I'm running this on Docker and I would like to know if there is a way to trigger an action like a script when the monitoring host goes down.

### 🐻 Uptime-Kuma Version

1.21.3

### 💻 Operating System and Arch

Rocky Linux 8

### 🌐 Browser

Chrome 114.0.5735

### 🐋 Docker Version

Docker version 23.0.1, build a5ee5b1

**Comment by solracsf** [comment]
Yes, send a Webhook notification somewhere where your script can be executed.

![image](https://github.com/louislam/uptime-kuma/assets/12234510/0d165d53-cf01-40f3-81f0-a2b2b08b50ec)
