### ISSUE TITLE
Question for a new feature

### ISSUE THREAD

**Issue by Ponkhy** [louislam/uptime-kuma#330]
So i was thinking about to add global/default notifications according to #293.
I have two ideas in mind to realise it and wanted to ask what you guys think or would choose/prefer.

**Idea 1:**
Alter table notifications and add a new column "is_default" as boolean. Every notification with a "1" gets send every time even if it wasn't enabled in a monitor.

**Idea 2:**
Add a new row in the settings table with the "key" "default_notifications". In the row is one array with every notification id in it which should get triggered.

**Comment by chakflying** [comment]
I was think instead add a "defaultEnabled" column in the notifications table, then when the user creates a new monitor, automatically enable these notification items, and the user can optionally turn it off. This would be consistent with the current UI and we only need to add a checkbox in the notification settings page. Only downside is existing monitors will not be affected.

**Comment by louislam** [comment]
> This would be consistent with the current UI and we only need to add a checkbox in the notification settings page.

Agree with @chakflying.

And for idea 2, this approach is not suggested for any relational databases, it may causes trouble if a notification is deleted.

My idea would be:

**UI - Notification Dialog**
Add Checkbox `Default enabled`
Add Checkbox  `Also apply to existing monitors`

**SQLite**
`notification table` - add a  `is_default` column.

**When loading the page "Add New Monitor"**
Get a list of default notifications, and enable them in the notification list.
`SELECT id FROM notification WHERE is_default = 1`

**When clicked "Save" in the Notification Dialog**
- Checkbox `Default enabled` store into `is_default`
- If Checkbox  `Also apply to existing monitors` is checked, add relationship to all existing monitor in `monitor_notification` table.

**Comment by Ponkhy** [comment]
> If Checkbox `Also apply to existing monitors` is checked, add relationship to all existing monitor in `monitor_notification` table.

Yea i wanted to same some space in the database, but you both are right it wouldn't really be consistent.

Alright, thanks for the input!

**Comment by Ponkhy** [comment]
Should the `Also apply to existing monitors` only apply to monitors which are owned by the user or every monitor?
I'm asking in case for the future of possible multi user support.

**Comment by louislam** [comment]
> Should the `Also apply to existing monitors` only apply to monitors which are owned by the user or every monitor?
> I'm asking in case for the future of possible multi user support.

Yes, should be the current user.

**Comment by Ponkhy** [comment]
> Get a list of default notifications, and enable them in the notification list.

So it sounds like you want rather have a separate list of notifications where only the defaults are in?

**Comment by louislam** [comment]
> > Get a list of default notifications, and enable them in the notification list.
> 
> So it sounds like you want rather have a separate list of notifications where only the default ones are in?

I forgot there is a notification list in $root while i was thinking this idea. So no need to fetch again actually. Just need to switch on if is_default is true

**Comment by Ponkhy** [comment]
Okay i need help because i'm a little stuck and maybe to one sided with my thoughts.
How would you automatically get a notification `checked` and pushed to `notificationIDList` if `isDefault` is `true`?
