### ISSUE TITLE
Using Uptime Kuma for WordPress maintenance site?

### ISSUE THREAD

**Issue by paaljoachim** [louislam/uptime-kuma#3304]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

I am helping Glow a WordPress maintenance service find a good monitoring service they can integrate into their service.
https://getglow.io/

It would be helpful with some feedback to if this is possible and how to do so.

Thanks.

### 🐻 Uptime-Kuma Version

1

### 💻 Operating System and Arch

1

### 🌐 Browser

all

**Comment by CommanderStorm** [comment]
Depends on your monitoring needs and what you mean by interation

**Comment by rezzorix** [comment]
> Depends on your monitoring needs and what you mean by interation

Honestly I think this link-dropping is just spam.
The question is so unspecific and then for a commercial service; topic should just be closed.

**Comment by paaljoachim** [comment]
Hey

I do not work at Glow. I use their service. I am trying to figure out if I should suggest Uptime Kuma for the maintenance service or not. 

> Depends on your monitoring needs and what you mean by interation.

I do not know.

Thank you for the reply!
I can do this through email instead.

**Comment by louislam** [comment]
I think Uptime Kuma is pretty straightforward. Just try it and you will find the answer yourself.
