### ISSUE TITLE
Error: PRAGMA journal_mode = WAL - SQLITE_NOTADB: file is not a database

### ISSUE THREAD

**Issue by Sumit0789** [louislam/uptime-kuma#3305]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### Description

<img width="712" alt="Screenshot 2023-06-24 at 9 54 56 AM" src="https://github.com/louislam/uptime-kuma/assets/111736044/56bc9089-6f29-43cb-a1d6-e218300cab49">

### 👟 Reproduction steps

NA

### 👀 Expected behavior

it was running earlier without any issue.

### 😓 Actual Behavior

It should run.

### 🐻 Uptime-Kuma Version

1.22.0-beta.0

### 💻 Operating System and Arch

5.4.226-129.415.amzn2.x86_64

### 🌐 Browser

114.0.5735.133

### 🐋 Docker Version

20.10.17

**Comment by louislam** [comment]
Your sqlite database may be inaccessible or corrupted. Please check the data volume.

**Comment by Sumit0789** [comment]
why it got corrupted ? how can we fix this.

**Comment by rezzorix** [comment]
Check if there are backup db files in the folder that can be used (there might be even if you didnt actively backup)
If there arent and you didnt actively create a backup then theres not much you can do.

**Comment by chakflying** [comment]
Since you mentioned Amazon Linux, what is your system setup? How is the data stored?

**Comment by Sumit0789** [comment]
I am running this on eks with efs volume mount in pod.

**Comment by chakflying** [comment]
Did you read in the README that "NFS are not supported"? Also, thanks to your report we can now say even though EFS provides file locking, it does not provide the guarantees necessary for SQLite.

**Comment by Sumit0789** [comment]
can we use any database like mysql, postgresql or mongodb instead of sqlite ?

**Comment by CommanderStorm** [comment]
Currently, external databases are not supported.

This will be one of the [headline-features](https://github.com/louislam/uptime-kuma/milestone/24) (next to subdirectory deployments) in v2.0
See #3017 and the tracking PR #2720
