### ISSUE TITLE
Strange 401 return on http check

### ISSUE THREAD

**Issue by Volkor3-16** [louislam/uptime-kuma#3309]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

I'm getting a strange result when I run a monitor on one of my servers, it's being flagged as down with a 401 result.
However, when I curl the page from the same box (both inside and outside of the docker container) I get the valid HTML from the server.
As a temporary solution, I have marked 401 errors as "up" to bypass the issue, but it doesn't feel right to ignore the problem completely. 
I have already checked other services running on the same nginx box, and they are functioning correctly. I have a strong suspicion that the issue lies either with my poorly written Rust program or with uptime-kuma.

If anyone is willing to assist me in testing and reproducing the issue, the site in question is https://cz0.au.

Are there any other troubleshooting steps I can do?

Additionally, is there a matrix room available? If not, is there any reason we don't have one?

### 📝 Error Message(s) or Log

Request failed with status code 401

### 🐻 Uptime-Kuma Version

1.21.3

### 💻 Operating System and Arch

Ubuntu 22.04.2 LTS on Oracle Cloud

### 🌐 Browser

-

### 🐋 Docker Version

Docker communiyu, 24.0.2

### 🟩 NodeJS Version

-

**Comment by CommanderStorm** [comment]
Cannot reproduce the site working:
![image](https://github.com/louislam/uptime-kuma/assets/26258709/b3f9dbd4-97bb-4a5c-8b86-afb371e0f036)

**Comment by CommanderStorm** [comment]
> Additionally, is there a matrix room available? If not, is there any reason we don't have one?

Why should we? For tech-discussions, issues are a better place.
I agree with the sentiment that issues are not ideal for `help`, I would like the discussions tab to be enabled for this.
I am not convinced that moving `help` to a non-publicly available and especially a non-searchable thing is a good idea.
(I am not the bdfl, only Louis could make such decisions. See https://github.com/louislam/uptime-kuma/pull/1349 for a discussion of such topics)

**Comment by Volkor3-16** [comment]
> Note that web browsers kommonly ignore the status codes, and render the content anyway.

Dammit, time to fix up my awful rust code. :/

> I agree with the sentiment that issues are not ideal for help, I would like the discussions tab to be enabled for this.
I am not convinced that moving help to a non-publicly available and especially a non-searchable thing is a good idea.

Didn't know github discussions were a thing, I imagine that would work too.

I'm a IRC/Matrix user, so I'm used to real-time chats for that. I'd imagine we'd have a room for announcements for updates and security notices which would be incredibly handy

On the issue of logging, matrix recently made a bot that logs and allows for search engine indexing of messages, I'm not sure on it's progress, or how well it works, but assuming it's all good I don't think we need to worry about it :)

Anyway, thanks for the help, I'll close the issue :)

**Comment by CommanderStorm** [comment]
> I'd imagine we'd have a room for announcements for updates and security notices which would be incredibly handy

Releases are listed here: https://github.com/louislam/uptime-kuma/releases you can subscribe on the main page here:
![image](https://github.com/louislam/uptime-kuma/assets/26258709/ab7d02c5-1876-4858-8e41-3113cf9420fe)
