### ISSUE TITLE
Pause Before Checking HTTP Keyword

### ISSUE THREAD

**Issue by SimoHDK** [louislam/uptime-kuma#331]
**Is it a duplicate question?**
No

**Is your feature request related to a problem? Please describe.**
Keyword checker is unable to check sites with delayed javascript (I think)

**Describe the solution you'd like**
Essentially I am trying to monitor specific sites for keywords, however if the words are loaded in javascript, it will always error (Can't be found). Would it be simple enough to 'wait' a given time for the page to fully load, _then_ check for keywords? Is this possible?

**Comment by louislam** [comment]
Likely impossible without Puppeteer (a.k.a. Chrome Headless), because it need to parse the frontend JS code. And this library will use a lot of RAM, I probably will not implement it.

**Comment by SimoHDK** [comment]
Thanks for the reply. No worries!
