### ISSUE TITLE
only notify for more than N times down

### ISSUE THREAD

**Issue by musnows** [louislam/uptime-kuma#3315]
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

Other

### 🔖 Feature description

我希望能提供一个通知选项，当一个监控有超过N次down了之后，再发送通知，而不是一次down就发送通知。有时候一些down是由于网络timeout引起的，并不是服务真的停止了；
当连续N次down了之后，就能确定确实是出现了一些问题，此时再发送通知。

I would like to provide a notification option to send notifications after a monitor has been down more than N times, instead of sending notifications in one down. Sometimes some downtimes are caused by a network timeout, rather than the service actually stopping;

After N consecutive downtimes, it can be determined that there is indeed some problem, and then a notification will be sent

### ✔️ Solution

在监控中提供一个选项，当down的次数大于N的时候就发送通知，默认值设置为0代表只要down就一定通知
Provide an option in monitoring to send notifications when the number of downtimes is greater than N. The default value is set to 0, which means that notifications will be sent whenever the down occurs

**Comment by CommanderStorm** [comment]
Is this not already offered by the `Retry` option?

**Comment by musnows** [comment]
> Is this not already offered by the `Retry` option? If yes, could you please close this issue, if no, could you make this differentiation more clear?


Indeed, I didn't notice this. sorry for that 😶‍🌫️
