### ISSUE TITLE
Bad count of monitors since 1.22.0 (groups)

### ISSUE THREAD

**Issue by mikolajek-fr** [louislam/uptime-kuma#3317]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### Description

Thanks for adding group monitors :)

But there's a small problem : the group is counted as monitor - it isn't !

### 👟 Reproduction steps

- Create 3 monitors : total is 3.
- Create group monitor, put all the 3 monitors inside it : total is 4.

### 👀 Expected behavior

Group monitors should not be counted as monitors.

### 😓 Actual Behavior

Actually, group monitors are counted as monitors.

### 🐻 Uptime-Kuma Version

1.22.0

### 💻 Operating System and Arch

AlmaLinux 9.2

### 🌐 Browser

Firefox 114

**Comment by CommanderStorm** [comment]
Given that the group monitor is also just a monitor (you can notify upon it and everything) I don't know if this counting is really incorrect.

**Comment by astroking362** [comment]
> Given that the group monitor is also just a monitor (you can notify upon it and everything) I don't know if this counting is really incorrect.

Agree. It is a Monitor of a set of Monitor statuses. You can also invert behaviour, change frequency of checks, etc.

**Comment by louislam** [comment]
Actually, I don't know to handle this. Programmatically it is correct, but I know it is a bit weird at the same time.

@julian-piehl Since you are the author, any ideas on this?

**Comment by julian-piehl** [comment]
I understand the confusion there. But like you yourself said:

> group monitors are counted as monitors.

Group **monitors** are monitors too. You are creating them like any other monitor, and they have all features other monitors have.
It's only a kind of monitor that has other monitors as children.
So I would say it is correct counting them as individual monitors.

Talking from a UI perspective, I see the problem, but I don't have a solution for this either.
I think just ignoring group monitors wouldn't be right.

**Comment by mikolajek-fr** [comment]
Sorry for being late.

OK for closing the bug, because it's not really a bug. But I think some people don't need to have group monitors as monitors, they just need a group to put some monitors inside it. When I see "2 monitors down", for me, I have 2 services/servers down ; now I have to think for myself "maybe it's just 1 service/server and his group".

**Comment by mikolajek-fr** [comment]
Not a bug / just a different point of view.
