### ISSUE TITLE
replace node-radius-client

### ISSUE THREAD

**Issue by kolbma** [louislam/uptime-kuma#3319]
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

Other

### 🔖 Feature description

__node-radius-client__ has unsupported and duplicating dependencies.  
Seems also that __node-radius-client__ is not maintained. The github links doesn't work.

### ✔️ Solution

Replace code using node-radius-client.

**Comment by CommanderStorm** [comment]
I don't see maintaining a radius client ourselves as a viable strategy.
Currently, there is no viable alternative.
Unless vulnerabilities are found in `node-radius-client`, I would tend to stick to it.

The only alternative out there seems to be https://github.com/retailnext/node-radius, which has
- a GitHub page
- but hasn't had a meaningful commit in the past 5 years

**Comment by louislam** [comment]
Yes, I don't see any better replacements on npm too at this moment. Feel free to open a new feature-request in the future if someone make a new and better library for this.
