### ISSUE TITLE
Push type minitor can't deal with ping value with decimals in 1.22.0

### ISSUE THREAD

**Issue by Potat0000** [louislam/uptime-kuma#3320]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### Description

Push type minitor can't deal with ping value with decimals.

The issue didn't exist in 1.21.3 . It first appear in 1.22.0

### 👟 Reproduction steps

1. Create a monitor with push type.
2. Call https://domain.tld/api/push/xxxxxxxx?status=up&msg=OK&ping=12.345
3. Shows "12" as ping value.

### 👀 Expected behavior

Shows "12.345" as ping value.

### 😓 Actual Behavior

Shows "12" as ping value.

### 🐻 Uptime-Kuma Version

1.22.0

### 💻 Operating System and Arch

Debian 12

### 🌐 Browser

Edge 114.0.1823.58

### 🐋 Docker Version

24.0.2

**Comment by CommanderStorm** [comment]
@Potat0000
I would suggest we continue this issue in https://github.com/louislam/uptime-kuma/issues/3343, as this is a more generic issue.
Could you close this issue?

**Comment by CommanderStorm** [comment]
See https://github.com/louislam/uptime-kuma/issues/3343#issuecomment-1616730611
=> This is not a bug, but rather intended behaviour.

Out of curiosity: Why would you need sub-1ms `ping`?
