### ISSUE TITLE
Prefiled tag value

### ISSUE THREAD

**Issue by mabed-fr** [louislam/uptime-kuma#3331]
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

API, UI Feature, Other

### 🔖 Feature description

Hello

I'm continuing my prometheus grafana integration with uptime kuma and I'm very happy with it.

I see that the export of tags is in progress here https://github.com/louislam/uptime-kuma/pull/898

Would it be possible to be able to select tags with a prefilled value like

datacenter = ILIAD and applies it to several probes ?

WHAT DO YOU THINK?

### ✔️ Solution

 NC

### ❓ Alternatives

  NC

### 📝 Additional Context

  NC

**Comment by CommanderStorm** [comment]
Is adding labels like this not more commonly done in the `ServiceMonitor`?

**Comment by mabed-fr** [comment]
Hello

For my part, I don't think so.

For example, I have two labels with the location of my servers

DATACENTER= EQUINIX
DATACENTER= ILIAD

I have a lot of probes to add and the dropdown with pre-populated values ​​would be a plus.

What do you think?

**Comment by CommanderStorm** [comment]
What is wrong about using the `labels` option in your scraping configuration?
See https://stackoverflow.com/questions/49829423/prometheus-add-target-specific-label-in-static-configs

Given that we don't support multiple instances directly, I think this is out of scope and handling this in the metrics-collector/relabeling configuration is a better fit

**Comment by CommanderStorm** [comment]
What do you mean by 
> This would avoid entering into the probe directly in my opinion

I don't understand why an additonal tag is required and why this is not better handled by existing tooling outside our scope.

Either
- you want to tag the instance => I would argue that this should be handled outsie of our scope
- you want to tag monitors => https://github.com/louislam/uptime-kuma/pull/898

**Comment by mabed-fr** [comment]
I only wish to have the possibility of having labels in the uptime kuma interface but labels with value before the assignment.
