### ISSUE TITLE
Add SMSC (СМСЦентр) provider notification 

### ISSUE THREAD

**Issue by FlatronBuda** [louislam/uptime-kuma#3334]
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

New Notification

### 🔖 Feature description

Add new notification service https://smsc.kz/.
I took the ClickSendSMS code as a base and added additional parameters.
This service allows you to send not only SMS, but I needed to send SMS

### ✔️ Solution

File src/components/notifications/index.js 
after the line `import ClickSendSMS from "./ClickSendSMS.vue";` added `import SMSC from "./SMSC.vue";`
after the line `clicksendsms": ClickSendSMS,` added `"smsc": SMSC,`

File server/notification.js
after the line `const ClickSendSMS = require("./notification-providers/clicksendsms");` added `const SMSC = require("./notification-providers/smsc");`
after the line `new ClickSendSMS(),` added `new SMSC(),`

File src/components/NotificationDialog.vue
after the line `"clicksendsms": "ClickSend SMS",` added `"smsc": "SMSC",`

And new created files server/notification-providers/smsc.js and src/components/notifications/SMSC.vue[smsc.zip](https://github.com/louislam/uptime-kuma/files/11907037/smsc.zip)

Full files in provider
[fullfiles.zip](https://github.com/louislam/uptime-kuma/files/11907084/fullfiles.zip)

### 📝 Additional Context

With git fork I did not understand the instructions, so I posted them as files

![image](https://github.com/louislam/uptime-kuma/assets/8991450/a599c03b-aa8e-4604-b84d-668e5cdc265f)

**Comment by louislam** [comment]
I opened the pull request for you, you could check the code there: https://github.com/louislam/uptime-kuma/pull/3335/files

**Comment by Zaid-maker** [comment]
Why dude cannot make a PR by himseld? lol

**Comment by CommanderStorm** [comment]
@Zaid-maker Please stay respectful of other people's work.
This is a productive issue which is clearly stating what needs to be fixed how and why.

The author also clearly stated 
> With git fork I did not understand the instructions, so I posted them as files

@FlatronBuda
What part did you get stuck on? (Where do we need to improve our documentation?)

**Comment by Zaid-maker** [comment]
> @Zaid-maker Please stay respectful of other people's work. This is a productive issue which is clearly stating what needs to be fixed how and why. This Issue also includes all the necessary information to get this notification provider merged.
> 
> The author also clearly stated
> 
> > With git fork I did not understand the instructions, so I posted them as files
> 
> @FlatronBuda What part did you get stuck on? (Where do we need to improve our documentation?)

You have any problem with me? please mind ur own business!

**Comment by louislam** [comment]
Please focus on the feature-request.
