### ISSUE TITLE
Merge Http probe

### ISSUE THREAD

**Issue by mabed-fr** [louislam/uptime-kuma#3336]
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

API, New Monitor, UI Feature

### 🔖 Feature description

Today we have 2 http probes and a third one being prepared https://github.com/louislam/uptime-kuma/pull/1878

It is quite possible to merge into one.

### ✔️ Solution

Combine 3 probes in one

HTTP with
- keyword field (empty by default)
- response time field (10s by default)
- return status code field (default return code already present 200-299)

### 📝 Additional Context

This would make it possible not to multiply the probes to cover all the functionalities

**Comment by CommanderStorm** [comment]
I think this work is better tracked in #3919 and I don't really see the point of having another issue open for this refactoring ^^
=> closing as a "duplicate"
