### ISSUE TITLE
checkbox for pause or delete multiple probe

### ISSUE THREAD

**Issue by mabed-fr** [louislam/uptime-kuma#3337]
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

UI Feature

### 🔖 Feature description

checkbox for pause or delete multiple probe

### ✔️ Solution

NC

**Comment by chakflying** [comment]
Duplicate of #1886

**Comment by CommanderStorm** [comment]
@mabed-fr Given that this is a duplicate of another issue with an open PR, please close this issue ^^

**Comment by mabed-fr** [comment]
Yes sorry

**Comment by CommanderStorm** [comment]
Thanks ❤️
