### ISSUE TITLE
How to include the change into the notification email?

### ISSUE THREAD

**Issue by bimg21** [louislam/uptime-kuma#3339]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

I am looking for a way for the notification email to include the change that happened on the website. Let's say my target keyword "2023" appeared in new row that says "Join us on a concert in Atlanta in 2023" and I want the exact change quoted in the email.

### 🐻 Uptime-Kuma Version

1.22.0

### 💻 Operating System and Arch

Ubuntu 22.04

### 🌐 Browser

Firefox 113

**Comment by CommanderStorm** [comment]
What do you mean by "the change that happened on the website"?
Keyword monitoring only checks for the existence of a keyword.

**Comment by rezzorix** [comment]
For your needs changedetection.io is the better choice. 

Github: https://github.com/dgtlmoon/changedetection.io

**Comment by bimg21** [comment]
> [CommanderStorm]
When one of keywords is added, I want to be notified with quote thereof and a link

> [rezzorix]
I did try changedetection, but I am not able to configure email notification.

**Comment by CommanderStorm** [comment]
> I want to be notified with quote thereof and a link

How would finding the context work?
The monitor just knows that a keyword is missing...
=> how would we figure out what to quote in an email?
=> Just send the entire webpage as html?

I am not convinced that this would be a good addition.

> I did try changedetection, but I am not able to configure email notification.

changedetection.io offers [smtp via apprise](https://github.com/caronc/apprise#email-notifications)

**Comment by CommanderStorm** [comment]
> I was not able to get it to work.

That is not something that we can help you with.
Please open an issue in the correct repositry: https://github.com/dgtlmoon/changedetection.io/issues/new/choose
