### ISSUE TITLE
Tab icon includes group

### ISSUE THREAD

**Issue by kokofixcomputers** [louislam/uptime-kuma#3341]
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

UI Feature, Other

### 🔖 Feature description

So when there is a monitor down in a group the tab icon shows a 2 like this:

<img width="105" alt="louislam:uptime-kuma2 " src="https://github.com/louislam/uptime-kuma/assets/113046561/d42b5c1f-bb80-456e-8e29-9ebd1972d2ad">

In the dashboard:

<img width="716" alt="louislam:uptime-kuma " src="https://github.com/louislam/uptime-kuma/assets/113046561/b1f61481-88b3-4672-b61c-77c0842f824b">

In the screenshow there is a monitor in a group does but in the tab icon screenshot it shows 2 so could it just say the number of monitors down like 1 because it confuses me

### ✔️ Solution

If there is a monitor in a group that is down the tab icon says 2 but i want it to say 1 instead just show to number of monitors down and not include the group

**Comment by CommanderStorm** [comment]
I think this is a duplicate of https://github.com/louislam/uptime-kuma/issues/3317
Could you recheck that this is not the same issue? (Duplicates only make issue management harder and create zombies)

**Comment by CommanderStorm** [comment]
@kokofixcomputers 
I think that Julian made a solid argument why this is intended behaviour and not a bug in https://github.com/louislam/uptime-kuma/issues/3317#issuecomment-1616755399
Could you close this issue?
