### ISSUE TITLE
Change HTML of Status page

### ISSUE THREAD

**Issue by luisdelavegadj** [louislam/uptime-kuma#3342]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

Hi all, I wanted to know if it is possible to change some HTML tags inside the status page.

If yes, in which path is the file to be modified?

### 🐻 Uptime-Kuma Version

1.22.0

### 💻 Operating System and Arch

Ubuntu 20.04.6 LTS

### 🌐 Browser

Opera GX

### 🐋 Docker Version

20.10.21

### 🟩 NodeJS Version

10.19.0

**Comment by CommanderStorm** [comment]
What tags would you like to inject?
CSS can be injected here:
![image](https://github.com/louislam/uptime-kuma/assets/26258709/a7b85ad3-2f85-4b6e-ad34-9fdd05aa7d9a)

For other tags, you will have to modify this file:
https://github.com/louislam/uptime-kuma/blob/master/index.html
Note that this will be added to every page of uptime-kuma and not only the status page.

If you need to modify just the status page, you will have to write logic in 
https://github.com/louislam/uptime-kuma/blob/master/server/model/status_page.js

**Comment by luisdelavegadj** [comment]
Hi @CommanderStorm 
I would like to change the background and center the logo and writing at the top but I can't find the file where to change the css/html

**Comment by CommanderStorm** [comment]
The things you want can be achieved as following:

- change background:  Use the `Custom CSS` field
- center the logo: Use the `Custom CSS` field
- writing at the Top: Use the `Title` field

=> no need to edit any files

**Comment by luisdelavegadj** [comment]
Thank you. To do the rebuild? how you do it? so the changes will be effective

**Comment by CommanderStorm** [comment]
On the status page click `Edit`
![image](https://github.com/louislam/uptime-kuma/assets/26258709/8644a749-c29c-42b8-a5b8-9d4cea73262e)

Changes are effective after clicking "Save"

**Comment by luisdelavegadj** [comment]
I tried to do this, but it doesn't apply the change
![Cattura](https://github.com/louislam/uptime-kuma/assets/45440611/021cb8eb-0054-4d23-9d29-98016f04e253)

**Comment by luisdelavegadj** [comment]
sorry, i fixed it. I forgot the "**.**" in the title-flex end mb-4

**Comment by CommanderStorm** [comment]
Nice.
If it is resolved, could you close this issue then? ^^

**Comment by luisdelavegadj** [comment]
is it possible to add html to the status page? @CommanderStorm

**Comment by CommanderStorm** [comment]
Yes, see https://github.com/louislam/uptime-kuma/issues/3342#issuecomment-1616103879

**Comment by luisdelavegadj** [comment]
ok, but how do I add "<p> Example </p>" in center page? in page edit, i can only add css

**Comment by CommanderStorm** [comment]
Are you maybe referring to adding a title or adding a description?
Could you make annotated screenshot?

**Comment by luisdelavegadj** [comment]
![Cattura](https://github.com/louislam/uptime-kuma/assets/45440611/571e39ca-f26e-4c69-8997-45a3592ef362)

**Comment by CommanderStorm** [comment]
If adding a description right here is fine, use the `Description`
![image](https://github.com/louislam/uptime-kuma/assets/26258709/26b7e0bf-c3a2-4602-8fb9-113c6bbac19c)

**Comment by luisdelavegadj** [comment]
I would like to add text under the title and not the description. it's possible?

**Comment by CommanderStorm** [comment]
Directly no.
You might be able to get this to work via css-pseudo selectors and `content`, but I cannot guarantee.

Here is the link to the file if the first does not work:
https://github.com/louislam/uptime-kuma/blob/8c60e902e1c76ecbbd1b0423b07ce615341cb850/src/pages/StatusPage.vue#L137
