### ISSUE TITLE
PUSH only display N/A with ping in set

### ISSUE THREAD

**Issue by musnows** [louislam/uptime-kuma#3343]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### Description

I use push task url with `ping=rainy` and put it to my python code, the status code return 200, but in uptime-kuma, it still display N/A

![image](https://github.com/louislam/uptime-kuma/assets/87506951/2bcec820-8f5e-486e-b995-2060506a2cf7)

![image](https://github.com/louislam/uptime-kuma/assets/87506951/c8862dab-19b6-48a2-a3a9-8c0d64b1e94e)

I also try in the monitor with `ping=test`, it still display N/A

![image](https://github.com/louislam/uptime-kuma/assets/87506951/5020aa38-5a7c-41ae-8a79-309e6b562608)

----

The  `1.21.3` version I deployed in replit can display correctly

![image](https://github.com/louislam/uptime-kuma/assets/87506951/5d51a0f2-2d27-490b-ba5a-95b7668f681c)

### 👟 Reproduction steps

using push task and set `ping=xxx`

### 👀 Expected behavior

display ping xxx in window

### 😓 Actual Behavior

display N/A in window

### 🐻 Uptime-Kuma Version

1.22.0

### 💻 Operating System and Arch

openwrt

### 🌐 Browser

edge 

### 🐋 Docker Version

docker 20.10.16

**Comment by musnows** [comment]
I try to use `1.21.1` in docker at same machine, it can display ping xxx correctly

![image](https://github.com/louislam/uptime-kuma/assets/87506951/facee41d-53ac-4d43-8544-fa6a651d0863)

**Comment by CommanderStorm** [comment]
Commit causing the issue: https://github.com/louislam/uptime-kuma/commit/71f00b369055b36110d854e0399344a8157dc9d6
Related PR: https://github.com/louislam/uptime-kuma/pull/2491

**Comment by CommanderStorm** [comment]
I think it is reasonable to expect that a `ping` is something which is either an integer/float and can thus be rounded to an integer.
What are you using the `ping` field for?

**Comment by CommanderStorm** [comment]
@louislam
Could you [edit the changelog](https://github.com/louislam/uptime-kuma/releases/tag/1.22.0) to communicate this breaking bugfix to our users?

⚠️ For the `ping` parameter of the `Push-Monitor`, submitted values are now being parsed as integers.

**Comment by louislam** [comment]
> @louislam Could you [edit the changelog](https://github.com/louislam/uptime-kuma/releases/tag/1.22.0) to communicate this breaking bugfix to our users?
> 
> > ⚠️ For the `ping` parameter of the `Push-Monitor`, submitted values are now being parsed as integer

**Comment by Potat0000** [comment]
> @musnows @Potat0000 I think it is reasonable to expect that a `ping` is something which is either an integer/float and can thus be rounded to an integer. What are you using the `ping` field for?

I am using the ping field to record the latency to the gateway. Obviously a float type data is very necessary in this case because all the latency data is between 1ms and 2ms.

I don't see any problem with supporting float type data, because in version 1.21 and earlier, the graph below can also display the float type graph very well.

**Comment by Potat0000** [comment]
Or maybe I should open another Feature Request issue for supporting float ping value again?

**Comment by musnows** [comment]
> @musnows @Potat0000 I think it is reasonable to expect that a `ping` is something which is either an integer/float and can thus be rounded to an integer. What are you using the `ping` field for?

I use it to make where the push request from，such as `ping=uptimerobot`🤣I never thought of using  integer/float to try it out
