### ISSUE TITLE
Security Issue

### ISSUE THREAD

**Issue by n-thumann** [louislam/uptime-kuma#3344]
DO NOT PROVIDE ANY DETAILS HERE. Please privately report to https://github.com/louislam/uptime-kuma/security/advisories/new.

Why need this issue? It is because GitHub Advisory do not send a notification to @louislam, it is a workaround to do so.

Your GitHub Advisory URL:
https://github.com/louislam/uptime-kuma/security/advisories/GHSA-7grx-f945-mj96
https://github.com/louislam/uptime-kuma/security/advisories/GHSA-vr8x-74pm-6vj7

**Comment by louislam** [comment]
Closed as fixed. Thanks.
