### ISSUE TITLE
Support float ping value

### ISSUE THREAD

**Issue by Potat0000** [louislam/uptime-kuma#3345]
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

Other

### 🔖 Feature description

In #3343 and #3320 , I said that I'm using the ping field to record the latency to the gateway. Obviously a float type data is very necessary in this case because all the latency data is between 1ms and 2ms. This feature may have been implemented by mistake since in version 1.21 and earlier, it could record ping values with float type and the graph below can also display the float type graph very well.

### ✔️ Solution

Supporting float ping value for push type and even for other type (for Response field).

**Comment by CommanderStorm** [comment]
Why is the difference between 1..2ms important to you?
At such latency, are other metrics (99p/...) not more import for you?

**Comment by Nuklon** [comment]
> The value for the ping is an integer globally ⇒ changing this in one corner would change this for every monitor => Nelsons assessment is correct, this is a duplicate
> 
> Why do you need to differentiate between 10.3 and 10ms?

I monitor sites on the same server as UK is running on, so it's not 10ms but 1-2ms. This is not useful to differentiate and creates a very jagged graph.

**Comment by Potat0000** [comment]
> This is not fixed, I'm using 1.23.7 and HTTP is still rounded to int.

Thank you to all of you who are still following this issue.

It can be confirmed that in 1.23.7 push type can store float value again. Since my original request is to support float ping value for push type, I think this issue could close as completed. You can open another issue to ask for float values for other types like HTTP.
