### ISSUE TITLE
Use notification as a hook

### ISSUE THREAD

**Issue by mabed-fr** [louislam/uptime-kuma#3349]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

Can i use notification as a hook ? 

I want triger the request when one of my probe is down:

curl -X POST -H 'Api-Key: API_xxxxxxxxx' -H 'Client-Key: CK_xxxxxxxxxxxxxxxxxx' "https://api.oneprovider.com/server/action" -d "server_id=xxxx" -d "action=reboot" -d "reason=Uptime-Kuma"

But i can't pass a data (-d) in webhook notification

![image](https://github.com/louislam/uptime-kuma/assets/25350431/111ce78d-e7f1-4d0d-9898-aa9565d4c9b8)

I must open feature request for hook ? or you have a tricks ?

### 🐻 Uptime-Kuma Version

1.22.0

### 💻 Operating System and Arch

Debian 12

### 🌐 Browser

Chrome

### 🐋 Docker Version

24.0.2

**Comment by CommanderStorm** [comment]
currently the body cannot be modified. See https://github.com/louislam/uptime-kuma/issues/2845 and the associated pull request: https://github.com/louislam/uptime-kuma/pull/3088

This is currently on the [roadmap for `1.23`](https://github.com/louislam/uptime-kuma/milestone/34)

**Comment by mabed-fr** [comment]
Perfect
