### ISSUE TITLE
[Feature request] Add HTTP incoming requests pings

### ISSUE THREAD

**Issue by nbvcxz** [louislam/uptime-kuma#335]
First, thank you for great work. Considering it's quite young application - it's very impressive.

I like Uptime Kuma not only for its pretty design, but also KISS architecture: no agents, one server with UI, easy to use. But it has few small disadvantages: E.g. all monitored hosts and services must be "directly" available. You cannot test your network infrastructure (in separate networks) unless Uptime Kuma is VPN connected.

The solution could be to add HTTP incoming requests pings, just like in [healthchecks.io](https://healthchecks.io/). I know it's just an idea and not easy to introduce - it would require also some cron mechanism implementation, but could make Uptime Kuma even more flexible without need of using remote agents.

**Comment by timoschwarzer** [comment]
Duplicate of #279

**Comment by nbvcxz** [comment]
True, thx, I'm closing it.
