### ISSUE TITLE
Please add an Environment Variable for Port selection

### ISSUE THREAD

**Issue by MekayelAnik** [louislam/uptime-kuma#3356]
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

Other

### 🔖 Feature description

I use macvlan to give my containers their own Local IP addresses. Since macvlan does not support port mapping (port mapping is allowed in bridged networks), I can't map the webUI port to my port of choice i.e. 80 or 443.

If you add an Environment variable which will set the desired port to the uptime-kuma "internally", then this problem can be solved.
Keep Up the great work.
Regards

### ✔️ Solution

suppose, There will be a env variable named "WEBUI_PORT".
If WEBUI_PORT=1000 then for webUI the uptime-kuma will be listening on port 1000 and if WEBUI_PORT=80, uptime-kuma webUI will be listening on port 80

**Comment by CommanderStorm** [comment]
Is this not already done with these two environment variables:
https://github.com/louislam/uptime-kuma/blob/c583037dff32641455b60bf1faa6c5e2973ee719/server/server.js#L112

**Comment by MekayelAnik** [comment]
Yes, 
Setting up  either UPTIME_KUMA_PORT or PORT does the work which I wanted.
Thanks.
