### ISSUE TITLE
mediaType in manifest

### ISSUE THREAD

**Issue by lechovicz** [louislam/uptime-kuma#3362]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

Hi! I'm trying to pull docker container following the instructions. Running:
> docker pull louislam/uptime-kuma:1
Returns:
> Pulling from louislam/uptime-kuma
> mediaType in manifest should be 'application/vnd.docker.distribution.manifest.v2+json' not 'application/vnd.oci.image.manifest.v1+json'

Is there any workaround for this? I'm running this on Debian 10 and  Docker version 19.03.3

### 🐻 Uptime-Kuma Version

N/A

### 💻 Operating System and Arch

Debian 10

### 🌐 Browser

N/A

### 🐋 Docker Version

19.03.3

**Comment by chakflying** [comment]
Have you tried updating Docker to the latest version?

**Comment by CommanderStorm** [comment]
Updating your OS might also be a good opportunity:
https://docs.docker.com/engine/install/debian/ lists only debian stable as supported targets

Security releases for your OS were stopped on 30. june 2022
