### ISSUE TITLE
Uptime Kuma vs. Uptime Robot: Seeing large difference in load time recorded for same site (images attached)

### ISSUE THREAD

**Issue by ReessKennedy** [louislam/uptime-kuma#3363]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

Loving Kuma! But I am getting large differences for load time logged for the same time while running HTTP calls. On free version of Robot that pings every 5 minutes and Kuma pings each minute but I am not sure this should make a difference. See images below. Robot is showing lower times at around 270ms and Kuma is averaging around 580ms. Any help is appreciated. 

## Uptime Robot
<img width="580" alt="Screen Shot 2023-07-05 at 10 44 06 AM" src="https://github.com/louislam/uptime-kuma/assets/3970267/0fbf1180-ec74-406a-b419-89b78de905f2">

## UptimeKuma
<img width="903" alt="Screen Shot 2023-07-05 at 10 43 45 AM" src="https://github.com/louislam/uptime-kuma/assets/3970267/fe2ed0d9-4351-459d-87fb-11c549f4f34c">

### 🐻 Uptime-Kuma Version

.22.1

### 💻 Operating System and Arch

Ubuntu 22.04LTS

### 🌐 Browser

Google Chrome

**Comment by CommanderStorm** [comment]
It could be on multiple factors.
- You are looking at different times of the day (!)
- Your instance of kuma and uptime robot probably are hosted in a different datacenter
  => different base-latency
  => differing amounts of network-goblins knawing at packets, sending them in loops and making your live miserable.
- Your app is unpredictable (Robot has the average of 535ms, kuma seems similar)

**Comment by ReessKennedy** [comment]
Thanks, yeah, some of these I thought of. It's just that I changed web servers for this app that is being monitored and Robot shows that app is now loading faster (the drop down in load shown) but Kuma is showing slower. I should have been more clear that this is what is happening.

I have also set up some Keyword searches for keyword that live in the footer of the page of the app with the thought that this will be a better read on actual load time since it will need to wait until this part of the page loads. I am wondering if there is a setting in Kuma that produces a more honest analysis of load time if I am trying to partially use Kuma as a tool to check in on and improve page load speed. I test on dev tools and GTMetrix and Pingdom but it's nice to just set a monitor to check speeds over time. 

Thanks for your help @CommanderStorm ! Appreciate the input.

**Comment by louislam** [comment]
> I have also set up some Keyword searches for keyword that live in the footer of the page of the app with the thought that this will be a better read on actual load time since it will need to wait until this part of the page loads

Not really, because Uptime Kuma downloads a complete html and check the keyword. The load times are basically the same. 


> I am wondering if there is a setting in Kuma that produces a more honest analysis of load time

The current ping is just the download time of your page html page. In reality, there are a lot of things such as images/javascript files that also need to be downloaded.

I am working on adding a headless browser Chromium as the engine. As it is basically a real browser, the load time will be more meaningful.
https://github.com/louislam/uptime-kuma/pull/3308#issuecomment-1606157226

**Comment by ReessKennedy** [comment]
@louislam: Awesome work on this. Chromium addition would be cool. I find having to check load times via Pingdom or PageDev tools annoying.
