### ISSUE TITLE
Error response from daemon: manifest for louislam/uptime-kuma:1 not found

### ISSUE THREAD

**Issue by joerich** [louislam/uptime-kuma#3369]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

Error response from daemon: manifest for louislam/uptime-kuma:1 not found

### 📝 Error Message(s) or Log

Error response from daemon: manifest for louislam/uptime-kuma:1 not found

### 🐻 Uptime-Kuma Version

Version: 1.22.0

### 💻 Operating System and Arch

Terramaster NAS

### 🌐 Browser

Chrome 114.0.5735.199

**Comment by CommanderStorm** [comment]
Could not reproduce:
![image](https://github.com/louislam/uptime-kuma/assets/26258709/0b9462f0-e6fc-403a-9425-f37a2e861584)


what docker version are you running?

**Comment by joerich** [comment]
Docker Version 17.05.6

**Comment by joerich** [comment]
BUMP

**Comment by chakflying** [comment]
- Your docker version is released 6 years ago. You should try to update to the latest available version.
- You can check your connection to docker hub by running `docker search uptime-kuma`.

**Comment by CommanderStorm** [comment]
> BUMP

Please refrain from posting `+1` / requests for updates things on issues, as this makes issue-management harder.
Issues are for discussing what needs to be done how by whom.
[We use 👍🏻 on issues to prioritise work](https://github.com/louislam/uptime-kuma/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).

**Comment by mfsiat** [comment]
i also found this error, i was trying with version 2. I changed it to latest from 2
![image](https://github.com/louislam/uptime-kuma/assets/12368038/28ed70b5-21af-48ba-b764-49e3a4766188)

**Comment by CommanderStorm** [comment]
@mfsiat 
The tag you are referring to does not exist, as v2 is not ready for public testing yet. See this milestone for further context: https://github.com/louislam/uptime-kuma/milestone/24
Once we release our first beta of v2, this will show up on our releases page: https://github.com/louislam/uptime-kuma/releases.
Once there is the first beta there will be ample time to test the breaking changes and fix other bugs.

See for https://github.com/louislam/uptime-kuma/issues/3695#issuecomment-1706348752 for a duplicate of your question.

**Comment by louislam** [comment]
> i also found this error, i was trying with version 2. I changed it to latest from 2 ![image](https://user-images.githubusercontent.com/12368038/266103882-28ed70b5-21af-48ba-b764-49e3a4766188.png)

I accidentally updated the docker-compose.yml to v2, just fix, you can download again:

https://github.com/louislam/uptime-kuma/blob/master/docker/docker-compose.yml

**Comment by mfsiat** [comment]
Thanks @CommanderStorm & @louislam
