### ISSUE TITLE
Use a timer feature to pause alerts for a specific period of time.

### ISSUE THREAD

**Issue by lifeinhd22** [louislam/uptime-kuma#3372]
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

UI Feature

### 🔖 Feature description

Allow users to temporarily mute notifications for a certain duration. This would be different from simply pausing them, which requires another action to resume them.

### ✔️ Solution

Set date/time when to resume on it's own.

**Comment by CommanderStorm** [comment]
Are you referring to `maintanence windows`? If not, what is the difference?

**Comment by lifeinhd22** [comment]
It would be same. Just another button near pause.

**Comment by lifeinhd22** [comment]
You have a valid point about the feature, but it is not essential. It would allow you to select the device directly, instead of browsing a list of devices in the menu.  

![image](https://github.com/louislam/uptime-kuma/assets/125096383/e058c9ff-0186-4655-9261-6fbde7aee4a7)

**Comment by YunchaoZheng** [comment]
Notifications are important marks of DOWN status, thus needed to be recorded on time. 
So, we can't simply enter maintenance mode when we want to mute notifications.
It would be better to set mute notification on your end point rather than on Kuma. Just like mail system.

**Comment by dansullivan86** [comment]
I think pausing notifications could be really useful and separate to maintenance.  For example today DigitalOcean is going up and down, I don't need a notification for every service coming and going, but I would like to be able to view the current status in Uptime kuma.

**Comment by CommanderStorm** [comment]
@lifeinhd22 
We are consolidating duplicate issues a bit to make issue management easier.
I think, we should track this issue in: 
- for recurring time based notification-muting: #3375
- easier maintenance windows addition: #2984
- easier maintenance window closing: #3768

⇒ I am going to close this as a duplicate.

**Comment by CommanderStorm** [comment]
@lifeinhd22 
We are consolidating duplicate issues a bit to make issue management easier.
I think, we should track this issue in: 
- for recurring time based notification-muting: #3375
- easier maintenance windows addition: #2984
- easier maintenance window closing: #3768

⇒ I am going to close this as a duplicate.
