### ISSUE TITLE
Security Issue

### ISSUE THREAD

**Issue by kokofixcomputers** [louislam/uptime-kuma#3374]
All right some more issues

Your GitHub Advisory URL: https://github.com/louislam/uptime-kuma/security/advisories/GHSA-m68c-5hqg-jwh6

**Comment by CommanderStorm** [comment]
You removed the ping ^^
 
> Why need this issue? It is because GitHub Advisory do not send a notification to @louislam, it is a workaround to do so.

**Comment by kokofixcomputers** [comment]
As long as louislam understands it, it's fine.

**Comment by louislam** [comment]
Maybe I reveal some details here, it is related to the 1.23.0-beta.1's changelog.

> ⬆️ Security Fixes
    https://github.com/louislam/uptime-kuma/pull/3421 Hardening: Avoid exposing the Uptime Kuma version to the public

Since a lot of web apps like Apache or php are also exposing their version to the public, so I think I would say it is a hardening rather than a vulnerability, I will not request a CVE number in this case.
