### ISSUE TITLE
How do i use Monitor Group on the add monitor as i cant find a way to create a group 

### ISSUE THREAD

**Issue by NOXITB** [louislam/uptime-kuma#3376]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

How do i use Monitor Group on the add monitor as i cant find a way to create a group if someone could tell me where i can create this that would be great 

### 📝 Error Message(s) or Log

![image](https://github.com/louislam/uptime-kuma/assets/77712352/a5717893-2de3-42ee-9bbd-6fdc48676d7b)

### 🐻 Uptime-Kuma Version

Latest

### 💻 Operating System and Arch

Ubuntu 20.04LTS

### 🌐 Browser

Brave latest

### 🐋 Docker Version

Latest Portainer

**Comment by CommanderStorm** [comment]
monitor groups can be created here:
![image](https://github.com/louislam/uptime-kuma/assets/26258709/afa93c91-1950-41ea-8a20-23a5bebeb94a)

**Comment by nsarakas** [comment]
As @CommanderStorm screenshoted, you will need to click on +Add New Monitor and then under Monitor Type, select Group (which is under General Monitor Type).
<img width="316" alt="image" src="https://github.com/louislam/uptime-kuma/assets/2875949/94187360-a590-49fe-aef5-06f5688c9ff4">

**Comment by NOXITB** [comment]
Thanks
