### ISSUE TITLE
Can groups of IPs be monitored with a Boolean OR operand?

### ISSUE THREAD

**Issue by ChrissoChrisso** [louislam/uptime-kuma#3382]
### ⚠️ Please verify that this bug has NOT been raised before.

- [x] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

Please let me start by saying thank you for this awesome software.  I really like it :-)

Now on to my question:
I would like to monitor groups of IP addresses following the OR operand, where as long as at least one of the IPs in a specific group is up, that group reports as up.  I only want the group to report as down while all IPs in that group are down.  Is that possible to do?  If so I haven’t figured out how to configure it and would greatly appreciate configuration tips.  Thank you in advance.

If it is not currently possible to do this, an implementation idea that maybe could work? is to split the single "Group" option here:
![image](https://github.com/louislam/uptime-kuma/assets/46985781/7fa5ba69-0029-47da-95db-c5dab56ad421)

into 2 options: "Group (Boolean AND)" and "Group (Boolean OR)".
"Group (Boolean AND)" would match the current functionality which appears to follow the AND operator.
"Group (Boolean OR)" would match the desired functionality of using the OR operator.

Again, many thanks for your help, and I appreciate this cool software.

### 🐻 Uptime-Kuma Version

1.22.1

### 💻 Operating System and Arch

Ubuntu 22.04 x64

### 🌐 Browser

Firefox 114

### 🐋 Docker Version

n/a

### 🟩 NodeJS Version

20.4.0

**Comment by CommanderStorm** [comment]
No, this is not a feature we currently offerer.
You can open a `feature-request` (I can't change tags and help gets autostale'ed => leaving this issue as is is not ideal)

**Comment by zimbres** [comment]
Similar: https://github.com/louislam/uptime-kuma/issues/2487

**Comment by CommanderStorm** [comment]
@ChrissoChrisso 
could you close this issue? (duplicates only lead to zombies)

**Comment by ChrissoChrisso** [comment]
Feature request https://github.com/louislam/uptime-kuma/issues/3387 created.

**Comment by ChrissoChrisso** [comment]
Feature request https://github.com/louislam/uptime-kuma/issues/3387 created.
