### ISSUE TITLE
Upgrade vom 1.21.3 to 1.22.1 results in empty dashboard page

### ISSUE THREAD

**Issue by solick** [louislam/uptime-kuma#3389]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### Description

I upgrade from 1.21.3 to 1.22.1 and after that the page call results in an empty dashboard page. I can reproduce that by switching back to 1.21.3 which then works fine again.

Any ideas what could be the root cause?

Tested with current Safari and Chrome browser

As I can see in the systemd logs the program itself is running and performing the checks normally. It seems just to be a problem with the frontend.

### 👟 Reproduction steps

Install 1.21.3, upgrade than to 1.22.1 and call the page.

### 👀 Expected behavior

1.22.1 should show the dashboard page

### 😓 Actual Behavior

Shows empty dashboard page

### 🐻 Uptime-Kuma Version

1.22.1

### 💻 Operating System and Arch

debian 11

### 🌐 Browser

Safari, Chrome

### 🐋 Docker Version

none, native Installation

### 🟩 NodeJS Version

15 LTS

**Comment by louislam** [comment]
Just tested, cannot reproduce.

You may need to show the full update log.

Make sure you have run `npm run download-dist`.

Please note that Node.js 15 is not LTS and reached end of life

**Comment by CommanderStorm** [comment]
When you are refering to `Safari, Chrome` are both of those running on iOS?
[Apple has restrictions that anything on iOS has to use webkit](https://apple.stackexchange.com/questions/350671/does-safari-and-google-chrome-for-macos-use-the-same-rendering-engine)

**Comment by solick** [comment]
Ok sorry. First I am using node 18 which is LTS at the moment as far as I know.
Second: Yes it was the missing command, now it is working again. Thanks
