### ISSUE TITLE
Is it possible to show the main status of a status page on an external website?

### ISSUE THREAD

**Issue by veitorg** [louislam/uptime-kuma#3390]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

Hey,
I use Uptime Kuma for monitoring my network. On my main website (HTML), I would like to show the status of an entire status page in the footer. It should look like "all services operational" or something like that as it states on the top of an uptime puma status page.
Im am not to experienced with APIs, but is there a way (maybe using the API) to let my main website pull the status of a status page and display it in the footer?

I would be very grateful for any solution

### 📝 Error Message(s) or Log

No error, just help with implementation

### 🐻 Uptime-Kuma Version

latest

### 💻 Operating System and Arch

Ubuntu 20.04

### 🌐 Browser

All Browsers

### 🐋 Docker Version

latest

**Comment by pistasjis** [comment]
Look at ``https://status.yourdomain.xyz/api/status-page/your-status-page-name``. It returns a JSON of all the added status monitors, but if you need heartbeat, look at ``https://status.yourdomain.xyz/api/status-page/heartbeat/your-status-page-name``.

**Comment by veitorg** [comment]
> Look at `https://status.yourdomain.xyz/api/status-page/your-status-page-name`. It returns a JSON of all the added status monitors, but if you need heartbeat, look at `https://status.yourdomain.xyz/api/status-page/heartbeat/your-status-page-name`.

Can you please tell me what I kind of need to implement in HTML to get this into the footer just stating of all systems are operational or not. (Like large providers have it like IONOS oder so)

**Comment by CommanderStorm** [comment]
> Can you please tell me what I kind of need to implement in HTML

Depends on what you want to implement exactly and the language you are doing it in (vue, react, svelte, vanila-js, ...)
