### ISSUE TITLE
How to display statistics on other sites!?

### ISSUE THREAD

**Issue by sepahna** [louislam/uptime-kuma#3391]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

Hello I have entered many domains, how can I display them in one tab on a WordPress site?

### 🐻 Uptime-Kuma Version

1

### 💻 Operating System and Arch

Ubuntu 

### 🌐 Browser

Chrome

### 🟩 NodeJS Version

14

**Comment by CommanderStorm** [comment]
displaying custom statistics is possible via the [prometheus integration](https://github.com/louislam/uptime-kuma/wiki/Prometheus-Integration).
You can also embed a uptime-kuma dashboard into your site via an iframe, but likely this is either not going to look as nice or require some css modificaiton.

Sidenote: Please update your Node.js version v14 was releases quite a while ago. Security Support for this platform has ended on 30 Apr 2023 as by https://endoflife.date/nodejs
