### ISSUE TITLE
uptime kuma don't send noification with a large attempts

### ISSUE THREAD

**Issue by ale82x** [louislam/uptime-kuma#3392]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### Description

i use uptime kuma to monitor my servers and works fine.

but i use it also for monitor outdated script.
so i add a monitor
https keyword
url = https://api.github.com/repos/roundcube/roundcubemail/releases/latest
keyword = 1.6.0
interval = 60 seconds
attempts = 7200
retry = 60 seconds

so i want to email me when script is outdated after 5 days (60sec 120 hours) = 7200

but when the value is very large monitor don't work ... it never becomes "down" and don't send email...

i try with my website and if i use attemps = 10 (ten minutes) works fine.

thank you

### 👟 Reproduction steps

create a monitor with keyword with large attemps and wait...

### 👀 Expected behavior

send email after 5 days

### 😓 Actual Behavior

don't send notification

### 🐻 Uptime-Kuma Version

1.22.1

### 💻 Operating System and Arch

almalinux and docker compose

### 🌐 Browser

all

### 🐋 Docker Version

Docker 24.0.4

**Comment by CommanderStorm** [comment]
For your concrete use case:
Would this not be easier+more reliable? (why do you want to get notifications after 5 days? 🤔)
![image](https://github.com/louislam/uptime-kuma/assets/26258709/29a00cd3-9846-4b25-b9ab-5480175debb4)

Are you using the inverted mode? If so, have you read the discussion for https://github.com/louislam/uptime-kuma/pull/3040 (avaliable in 1.23)

What do you mean by `attempts`?
![image](https://github.com/louislam/uptime-kuma/assets/26258709/4d446d4e-44ee-47ba-8939-c4bccc4c7c87)

Have you tried a higher value for the heartbeat interval? 60s seems quite agressive imo. (might it be that you are being rate limited?)

**Comment by ale82x** [comment]
hello,
thank you for reply...

url of github is a test, i monitor also other website in search of specific keyword.
5 days is because, i wouldnt update as soon as the update comes out.
so i wait 5 days and then update...

thank you , I did not think about it...
now i setup:
hearthbeat interval = 86400 (1 day)
retries = 5

thank you

**Comment by ale82x** [comment]
sorry, i'm wiriting again because not work...

i setup
hearthbeat interval = 86400 (1 day)
retries = 5

but this id "down" from 11 times...

![immagine](https://github.com/louislam/uptime-kuma/assets/40036611/926b3f1b-1e6a-4d03-bbf2-3e01f412ebca)

and is NOT down but "pending"

thank you

**Comment by CommanderStorm** [comment]
Did you restart your server by any chance? in this time interval?
=> See https://github.com/louislam/uptime-kuma/issues/3504

**Comment by ale82x** [comment]
ok, my is an active monitor (not PUSH/PASSIVE) but ok,
i try to set retries = 0

thank you
