### ISSUE TITLE
Ability to mirror two Kuma instances

### ISSUE THREAD

**Issue by ImAARIX** [louislam/uptime-kuma#3393]
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

Other

### 🔖 Feature description

It would be interesting to have the ability to mirror a Kuma instance data to other Kuma instances, have the same data (monitors, labels, maintenances, etc..)
It can help to track uptime from multiple instances, if the main instance is down, other instances would still track all uptimes

### ✔️ Solution

Add a settings section with:
  - a radio button that is not enabled by default, that'll enable mirroring
  - an URL input
  - a token of the main Kuma instance
  - a time input (CRON or standard "every x minutes/hours" input).

Once it's launched, it'll gather data and prevent user from changing other settings section than this one.

### ❓ Alternatives

For now, I backup every tables with Sqlite3 CLI (except the "heartbeat" one that contains uptime data) and I import it to other instances.

**Comment by CommanderStorm** [comment]
I think this is a duplicate of https://github.com/louislam/uptime-kuma/issues/84 https://github.com/louislam/uptime-kuma/issues/528 or the other HA-issues.
If you agree, could you please close this Issue, as duplicates only create immortal zombies and are really hard to issue-manage?
If not, what makes this issue unique enough to require an additional issue? ^^

**Comment by ImAARIX** [comment]
This could be really useful to share only specific tables content between two instances (api_key, docker_host, incident maintenance, maintenance_status_page, monitor, monitor_group, monitor_maintenance, monitor_notification, monitor_tag, monitor_tls_info, proxy, setting, status_page, status_page_cname, tag, user, notification, notification_sent_history)

**Comment by CommanderStorm** [comment]
Please contribute this alternate approach in the issues I mentioned.
Like this, this will not get the attention you want it to get.

I have concerns about this security of this approach.
Syncing databases is also prone to the entire slew of distributed systems shenanigans concerning to Consistency and Partition tolerance.

**Comment by ImAARIX** [comment]
Okay, so I'll close this issue and contribute to one of these.

But regarding the security issues that this approach could create, keep in mind that it's more like an "advanced user functionnality", and that it's up to each user to deal with security problems and keep their system as secured as they can.
Regarding the last part of your comment, I went to take information about Consistency and Partition tolerance, and I agree that it'll be complicated to sync databases as is, but we're here only talking about transferring few objects, and I think it can be done easily with API endpoints.
