### ISSUE TITLE
Show timeline for a period of days

### ISSUE THREAD

**Issue by dsvinovacaogp** [louislam/uptime-kuma#3397]
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

UI Feature

### 🔖 Feature description

When adding a new "status page" or modifying it, give the option to show the timeline for a specific period, like 24 hours, 7 days, 15, 30 or even 90 days as the atlassian status feature provides. The status page pattern has shown a short period per minute or hours and in many cases for us it is bad. It could include an option to leave this configuration optional and customize the timeline by period.

Example:

Openai status for a period of 90 days.

[Status OpenAi](https://status.openai.com)

### ✔️ Solution

Have an option in the configuration menu of a status page to configure the visualization of a timeline for periods of hours or days of up to 90 days.

### ❓ Alternatives

Last case, is there a way to set it to a minimum of 24 hours?

**Comment by CommanderStorm** [comment]
I think this is a duplicate of https://github.com/louislam/uptime-kuma/issues/3264
If you agree, could you please close this Issue, as duplicates only create immortal zombies and are really hard to issue-manage?
If not, what makes this issue unique enough to require an additional issue? ^^

**Comment by dsvinovacaogp** [comment]
No problem, I haven't really encountered this feature before. Closing. Grateful.
