### ISSUE TITLE
No alert via OpsGenie when service is back online

### ISSUE THREAD

**Issue by tomsteenbakkers** [louislam/uptime-kuma#3398]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

I have setup 2 notification providers in Uptime Kuma: OpsGenie and Pushover.

When a monitor detects a service being unavailable I get an alert with both services.

When I bring the service back online, Pushover generates a new alert, saying the service is UP. The OpsGenie doesn’t alert me. Is this by design?

I would expect a P4 or P5 alert in OpsGenie.

### 🐻 Uptime-Kuma Version

1.22.1

### 💻 Operating System and Arch

TrueNAS-SCALE-22.12.3.1

### 🌐 Browser

Safari on iPadOs 16

### 🐋 Docker Version

K8S

**Comment by louislam** [comment]
https://github.com/louislam/uptime-kuma/blob/master/server/notification-providers/opsgenie.js

I suspected that the implementation is indeed not quite correct. It just calls `/close` for the `UP` status.

**Comment by louislam** [comment]
cc: @wwniclask25

**Comment by tomsteenbakkers** [comment]
I just created an new API key to check if it's related to the API. This is the result:
- When the services is down I get a notification and an alert is registered in OpsGenie
- When the services is Up I get **no** notification but the alert is closed in OpsGenie

**Comment by CommanderStorm** [comment]
So not a bug, right? 
If this is not a bug, could you close this issue?

**Comment by tomsteenbakkers** [comment]
It started as a question. I’m using also PagerDuty which works a little bit different, hence the question. 

I will close it. Thanks for the support.

**Comment by tomsteenbakkers** [comment]
I have removed all integrations and created a new one specific for Uptime Kuma. 

Now I get notifications when an Alert is raised and Closed. And the Alert is also closed automatically!

Thanks for the support.

**Comment by emmahsax** [comment]
Note for anybody that is still seeing this type of thing:

I was running Uptime Kuma 1.17.x using Apprise as the alerting system. This was giving me an "Up" message when the alert came back online.

Since updating to the latest version of Uptime Kuma, version 1.23.10, there's a new Opsgenie-specific Notification Type, and that works as expected. The Apprise alerting type still gives duplicate alerts (shown below)

![image](https://github.com/louislam/uptime-kuma/assets/7562793/b110e413-10f4-424c-a552-f57347cde37b)

**Comment by brad1121** [comment]
Just in case anyone else has similar issues. 

We are using this for Jira ticket creation, in our case the test notifications were not working as they did not include the description field in the data. Real alerts worked as expected. Wasted a fair bit of time trying to work out why we got 202 responses when testing but no tickets..
