### ISSUE TITLE
Add multiple hosts

### ISSUE THREAD

**Issue by qq8554650** [louislam/uptime-kuma#3399]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

Many hosts need to be added, just monitor ping.Notification only to me
Now only add one by one，Can change hostname to hostname(S)?
ths ^^

### 🐻 Uptime-Kuma Version

1.22.1

### 💻 Operating System and Arch

CentOS Linux release 7.9.2009 (Core)

### 🌐 Browser

Microsoft Edge 114.0.1823.67

### 🐋 Docker Version

Docker version 20.10.7, build f0df350

**Comment by rezzorix** [comment]
Only a work around at the moment. 

Create 1 ping monitor and save. 

Go to settings, backup and export this 1 monitor. 

Manually duplicate and add within the same file with adusted hostnames. 

Import this adjusted file and all your monitors should be there. 

Not a clean solution but still quicker than creating all manually or copy a monitor in the current interface.

**Comment by qq8554650** [comment]
> Only a work around at the moment.
> 
> Create 1 ping monitor and save.
> 
> Go to settings, backup and export this 1 monitor.
> 
> Manually duplicate and add within the same file with adusted hostnames.
> 
> Import this adjusted file and all your monitors should be there.
> 
> Not a clean solution but still quicker than creating all manually or copy a monitor in the current interface.

Will this feature be added in a future version? ths

**Comment by rezzorix** [comment]
I believe there are a number of people who would welcome this.
