### ISSUE TITLE
Add a PNG icon?

### ISSUE THREAD

**Issue by mkono87** [louislam/uptime-kuma#34]
Could you add a png version of the icon so I or we can link the icon to our container in Unraid please?

**Comment by louislam** [comment]
Just added a png icon

https://github.com/louislam/uptime-kuma/blob/master/public/icon.png

**Comment by mkono87** [comment]
> 
> 
> Just added a png icon
> 
> https://github.com/louislam/uptime-kuma/blob/master/public/icon.png

Thanks so much
