### ISSUE TITLE
Deleting a host & Vague Alerts

### ISSUE THREAD

**Issue by Termex69** [louislam/uptime-kuma#3400]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### Description

I know in previous versions after you tap Delete and confirm with Yes, it supposed to be removed and go back to the main page within seconds. 
When I try to delete a host from monitoring, it appears that nothing was done.
I tried refreshing the page and it takes about 1 to 2 minutes to show me the update.

I have monitoring groups setup and devices added to that group. If a devices is down in the group the alert says "Child Inaccessible", but does not state exactly which child id down.
I think the group alert should be [Group name] : Child Inaccessible > Device hostname is down.

### 👟 Reproduction steps

Click "List" > click the hostname you want to delete > click "Delete" > click "Yes" to confirm.

### 👀 Expected behavior

Expected behavior is that the host should be deleted after confirmation after some seconds.

### 😓 Actual Behavior

It remains on the device page after "Yes" to confirm was clicked.

### 🐻 Uptime-Kuma Version

1.22.1

### 💻 Operating System and Arch

Debian 11

### 🌐 Browser

Chrome, Edge and Firefox

### 🐋 Docker Version

20.10.5

### 🟩 NodeJS Version

12.22.12

**Comment by chakflying** [comment]
First part is a duplicate of #1661
Second part is a duplicate of #3278
