### ISSUE TITLE
Avg Respons time

### ISSUE THREAD

**Issue by phifuh** [louislam/uptime-kuma#3401]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

Hello, I just found this project and tried to play with it local. 
I added a few websites but I noticed that all of them have a respons time of 5000-15000ms. Even google has 10000ms. 
Any idea why the container has such a huge delay when each website loads within 200ms in a browser?

### 🐻 Uptime-Kuma Version

1.22.1

### 💻 Operating System and Arch

Windows 10

### 🌐 Browser

Google Chrome

### 🐋 Docker Version

Podman 4.5.1

**Comment by louislam** [comment]
https://demo.uptime.kuma.pet

Can you reproduce the issue on our demo site?

**Comment by phifuh** [comment]
I tried the demosite, google is down to ~200ms which seems fine and another test site is down from ~10000ms to ~1200ms

**Comment by louislam** [comment]
I also tested Podman 4.5.1 + Podman Desktop 1.1.0. Looks good to me.

If you eventually deploy on a server, I would suggest you should directly test on your server rather local.

![image](https://github.com/louislam/uptime-kuma/assets/1336778/492fbc63-0d98-442a-a7b5-7ee9e15e9d7f)

**Comment by CommanderStorm** [comment]
> I saw that rootless container is planned for v2.0.0 but is there any ETA?

See https://github.com/louislam/uptime-kuma/pull/2720#issuecomment-1615101427
