### ISSUE TITLE
Api Usage 

### ISSUE THREAD

**Issue by lastsamurai26** [louislam/uptime-kuma#3402]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

Is there a possibility to create the badges automatically via the sensor ID ? 
I have 20 sensors for monitoring and want to get all up/down statuses automatically without having to use the generator, is this possible? 

### 🐻 Uptime-Kuma Version

1.22.1

### 💻 Operating System and Arch

Debian 12

### 🌐 Browser

Chrome  114.0.5735.199

### 🐋 Docker Version

Docker 24.0.4

**Comment by chakflying** [comment]
Badges are always available as long as you add the monitor to a Status Page.

**Comment by lastsamurai26** [comment]
That means I have to read the badge for each sensor manually in the StatusPage ?
is there a possibility to query the sensors via Api which there are ?

**Comment by CommanderStorm** [comment]
See https://github.com/louislam/uptime-kuma/issues/118

**Comment by CommanderStorm** [comment]
See also https://github.com/louislam/uptime-kuma/issues/3390#issuecomment-1627675868

**Comment by lastsamurai26** [comment]
thx :-)
