### ISSUE TITLE
Harmonogram/calendar of monitoring?

### ISSUE THREAD

**Issue by koles142** [louislam/uptime-kuma#3404]
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

UI Feature

### 🔖 Feature description

Hi, I solid like to ask about harmonogram/calendar of monitoring. My case: I have a business and use a lot of mobile devices. I would like monitor it, because any failure in opening hours generate cost for me. After opening hours these devices are turned off. In this case every day I will have a lot of notifications, which are false for me.

### ✔️ Solution

Calendar in gui where I can define (per host)  which monitored host can send me pushes eg.: Tablet in opening hours 8:00-16:00 can send me the push when has problem or is offline, but after this time not. Game changer will be possibilites check free days, holidays, christmas etc. with disabled norifications.

**Comment by CommanderStorm** [comment]
What is the difference to the schedulable maintenance mode currently implemented?

**Comment by koles142** [comment]
In currently schedulable maintenance I can’t set repeat every year, have only option every day and month. In this case I can’t set maintenance eg. every christmas or free days.

**Comment by CommanderStorm** [comment]
You can schedule it via cron:
- 
![image](https://github.com/louislam/uptime-kuma/assets/26258709/c220432b-57f1-4e35-bbb9-62bd3d055815)

- https://crontab.guru/#*_*_24-26_12_*

**Comment by CommanderStorm** [comment]
@koles142
I think the feature you are requesting is already implemented.
If you agree, could you please close this issue, as duplicates only create immortal zombies and are really hard to issue-manage.
If not, what makes this issue different from already implemented functionality?

**Comment by CommanderStorm** [comment]
@koles142 
We are consolidating duplicate issues a bit to make issue management easier.
I think, we should track this issue in #1984 as there is no functional difference (maybe just small naming differences, but nothing that would require a different issue imo)
⇒ I am going to close this as a duplicate.
