### ISSUE TITLE
Postgres Monitor SSL/TLS Issue

### ISSUE THREAD

**Issue by jayKeegan** [louislam/uptime-kuma#3405]
### ⚠️ Please verify that this bug has NOT been raised before.

- [x] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

I am using Digital Ocean Managed Databases service to host my PostgreSQL server. When trying to monitor it through Uptime Kuma, but I am getting errors related to self signed certificates.

I appreciate any help.

### 📝 Error Message(s) or Log

```
self signed certificate in certificate chain
```

### 🐻 Uptime-Kuma Version

1.22.0

### 💻 Operating System and Arch

Debian 10

### 🌐 Browser

Chrome 114 on macOS (Ventura)

**Comment by CommanderStorm** [comment]
You can
- add the certificate as a trusted certificate to your system
- disable certificate checking for said monitor

**Comment by ancashoria** [comment]
Hey, how can I disable certificate checking for said monitor?
I'm using monitor type: PostgreSQL and the option is not there

> You can
> 
>     * add the certificate as a trusted certificate to your system
> 
>     * disable certificate checking for said monitor

**Comment by ancashoria** [comment]
> Hey, how can I disable certificate checking for said monitor? I'm using monitor type: PostgreSQL with a connection string and the option is not there
> 
it's done with `sslmode=no-verify` at the end of the connection string

https://github.com/louislam/uptime-kuma/issues/4100#issuecomment-1825761733
