### ISSUE TITLE
How to change how long page refresh takes in footer?

### ISSUE THREAD

**Issue by FosterG4** [louislam/uptime-kuma#3407]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

How do I change how long the page refreshes in the footer?

I want to change how long the status page refreshes in from 05:05 to 30 seconds or something like that.

example screenshot:
![Screenshot 2023-07-12 131141](https://github.com/louislam/uptime-kuma/assets/30888372/34ecf59b-ad51-4583-9401-843081f04020)

### 🐻 Uptime-Kuma Version

1.22.1

### 💻 Operating System and Arch

CentOS Linux 7 (Core)

### 🌐 Browser

Version 114.0.5735.199 (Official Build) (64-bit)

### 🟩 NodeJS Version

v14.21.2

**Comment by CommanderStorm** [comment]
Currently, this is not configurable. See https://github.com/louislam/uptime-kuma/commit/193a273557ea8f5d713029d500500cc3b8df496e for a PR which shows pretty clearly what parts of the code are responsible for reloading the new heartbeats.

If you like, you could contribute a PR adding such a configuration option…
