### ISSUE TITLE
Down Event not showing

### ISSUE THREAD

**Issue by devzeroo** [louislam/uptime-kuma#341]
**Is it a duplicate question?**
Not that i can find.

I have a HTTPs monitor and the SLA is at 99.96 as shown on image below, but the time/date and duration of the incident its not shown on the records/events list.

Is this a bug ?

![screenshot-uptimer com br-2021 09 06-11_29_43](https://user-images.githubusercontent.com/13603669/132232208-0559acc6-05e2-433a-af3a-4b0255d82770.png)

**Info**
Uptime Kuma Version: dockerhub:latest
Using Docker?: Yes on AWS Lightsail
OS:
Browser:

**Comment by louislam** [comment]
Possibly a bug. 

Do you how to query the sqlite3 db? It should contain the downtime log.

Assume that you are using Windows. You can copy the `kuma.db` in `/app/data/kuma.db` to your desktop, and run the sql in SQLite Expert Personal.

```sql
SELECT * FROM heartbeat WHERE status = 0
```
