### ISSUE TITLE
Set Custom Subject {{STATUS}} in upper case CAPS

### ISSUE THREAD

**Issue by rhbkweb** [louislam/uptime-kuma#3411]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

Hi,

I tried to integrate UPTIME KUMA, email (SMTP) integration with the very popular and free https://instatus.com/ status page service, but it does not work.

It’s because INSTATUS only accepts, email status notifications with the word “UP” and “DOWN” all-in upper-case CAPS and UPTIME KUMA sends “Up” and “Down” with just the first letter in upper case CAPS.

On UPTIME KUMA I set the smtp email notification CUSTOM subject to be: {{STATUS}}.
It would be great if on UPTIME KUMA, can in the future have a way to set this.

In the meantime, does anyone has an advice or suggestion on how can I solve this, in order to send the {{STATUS}} in upper case caps? Maybe by manual changing/editing some file, in a way that setting is not lost in future UPTIME KUMA updates?

Thanks!

### 🐻 Uptime-Kuma Version

1.22.1

### 💻 Operating System and Arch

UBUNTU 22.04 with Cloudron.io control panel

### 🌐 Browser

Google Chrome

**Comment by CommanderStorm** [comment]
Currently, we don't support this.
The SMTP notification provider currently does "templating" like this:
https://github.com/louislam/uptime-kuma/blob/ac68a35d3a43c9e1abce0790080507040cc14302/server/notification-providers/smtp.js#L58-L60

Ideally, this would be handled via liquid as well (is an ongoing migration, but slow given the amount of notification providers):
https://github.com/louislam/uptime-kuma/blob/ac68a35d3a43c9e1abce0790080507040cc14302/server/notification-providers/webhook.js#L29-L39

Liquidjs would include a [capitalisation-filter](https://liquidjs.com/filters/capitalize.html)
Pull requests welcome

**Comment by rhbkweb** [comment]
@CommanderStorm 

Thanks for the response.
But since I'm not a developer/web dev, I do not "understand" your response. I'm a sysadmin.

Maybe try to explain to me in a more "simple" way. My konowledge goes so far as editing files in SSH... :(

Thanks!

**Comment by CommanderStorm** [comment]
I have opened this [Pull request](https://github.com/louislam/uptime-kuma/pull/3414).
Could you test if the change breaks any functionality and provide Screenshots that it does not?
(you seem to have `smtp` configured, and I should really get back to my exam studying 😉)

As in, send provque mails and have the template set to these two cases:
- `{{STATUS}} {{NAME}} {{HOSTNAME_OR_URL}}` (simple)
- `{{NAME}} {{NAME}} {{STATUS}} {{status}}` (duplicate + caseness)

**Comment by rhbkweb** [comment]
Hi @CommanderStorm 

Thanks a lot for the help and code. I have not yet had the time to test.

Anyway I also contacted INSTATUS support team about this issue and they already updated their system to accept "Up" and "Down" email subject notifications. 

So now UPTIME KUMA works perfectly with INSTATUS using SMTP email notifications.
