### ISSUE TITLE
IPv6 does not work in HTTPS PING mode....

### ISSUE THREAD

**Issue by J-P1** [louislam/uptime-kuma#3415]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

Good morning,
I installed it on a VirtualBox Ubuntu virtual machine and everything works perfectly both in ipv4 and ipv6 (Local Mode).
On the other hand for the certificate I had to switch to VPS as indicated and it was impossible to ping on IPv6.
Maybe something in iptables to open, but there I dry, I would need help.

I don't have a solution to solve this problem, do you have any idea what can block IPv6?

VPS OS / Ubuntu 22.04 Distribution
Installation : Coolify

### 📝 Error Message(s) or Log

.

### 🐻 Uptime-Kuma Version

1.21.2

### 💻 Operating System and Arch

Ubuntu 22.04 Distribution

### 🌐 Browser

Google Chrome Version 114.0.5735.199 (Build officiel) (64 bits)

### 🐋 Docker Version

Docker version 24.0.4, build 3713ee1

**Comment by chakflying** [comment]
What service provider is the VPS hosted on?

**Comment by J-P1** [comment]
OVH supplier

**Comment by louislam** [comment]
I think you need to config ipv6. You better ask the OVH support. 

https://help.ovhcloud.com/csm/en-gb-vps-configuring-ipv6?id=kb_article_view&sysparm_article=KB0047569

**Comment by J-P1** [comment]
IPv6 is configured and when I ping the interface I get good feedback.
 ping6 google.com
PING google.com(par21s17-in-x0e.1e100.net (2a00:1450:4007:808::200e)) 56 data bytes
64 bytes from par21s17-in-x0e.1e100.net (2a00:1450:4007:808::200e): icmp_seq=1 ttl=112 time=5.10 ms
64 bytes from par21s17-in-x0e.1e100.net (2a00:1450:4007:808::200e): icmp_seq=2 ttl=112 time=4.78 ms
64 bytes from par21s17-in-x0e.1e100.net (2a00:1450:4007:808::200e): icmp_seq=3 ttl=112 time=4.88 ms
64 bytes from par21s17-in-x0e.1e100.net (2a00:1450:4007:808::200e): icmp_seq=4 ttl=112 time=4.85 ms
64 bytes from par21s17-in-x0e.1e100.net (2a00:1450:4007:808::200e): icmp_seq=5 ttl=112 time=4.82 ms
64 bytes from par21s17-in-x0e.1e100.net (2a00:1450:4007:808::200e): icmp_seq=6 ttl=112 time=4.78 ms
64 bytes from par21s17-in-x0e.1e100.net (2a00:1450:4007:808::200e): icmp_seq=7 ttl=112 time=4.87 ms
64 bytes from par21s17-in-x0e.1e100.net (2a00:1450:4007:808::200e): icmp_seq=8 ttl=112 time=4.88 ms
^C
--- google.com ping statistics ---
8 packets transmitted, 8 received, 0% packet loss, time 7009ms
rtt min/avg/max/mdev = 4.777/4.867/5.095/0.094 ms

on the other hand with uptime kuma it does not work?
![Capture](https://github.com/louislam/uptime-kuma/assets/124814422/f56bde7f-ce13-4007-9f7b-25531b3e54a0)

**Comment by louislam** [comment]
Docker enabled IPv6?

**Comment by J-P1** [comment]
this is what i have now does that mean it is activated???

**Comment by J-P1** [comment]
/etc/docker/daemon.json


{
    "log-driver": "json-file",
    "log-opts": {
      "max-size": "100m",
      "max-file": "5"
    },
    "features": {
        "buildkit": true
    },
    "live-restore": true,
    "default-address-pools" : [
    {
      "base" : "172.17.0.0/12",
      "size" : 20
    },
    {
      "base" : "192.168.0.0/16",
      "size" : 24
    }
  ]
}

**Comment by louislam** [comment]
Type `how to enable docker ipv6` in Google and you will find the answer, trust me.
