### ISSUE TITLE
Are there any checks if uptime kuma is down itself?

### ISSUE THREAD

**Issue by ghost** [louislam/uptime-kuma#3417]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

Does Uptime Kuma have a built-in mechanism to determine if it itself is offline when it detects that a service is down or unreachable?

E.g. by setting "northstars" hosts like 1.1.1.1 or 8.8.8.8, and if a certain percentage of those northstars if unreachable, UK assumes the connection issue is on its side.

### 🐻 Uptime-Kuma Version

N/A

### 💻 Operating System and Arch

N/A

### 🌐 Browser

N/A

**Comment by CommanderStorm** [comment]
No such a mechanism is not supported.

**Comment by CommanderStorm** [comment]
I think this is a duplicate of https://github.com/louislam/uptime-kuma/issues/774
If you agree, could you please close this Issue, as duplicates only create immortal zombies and are really hard to issue-manage?
If not, what makes this issue unique enough to require an additional issue? ^^
