### ISSUE TITLE
steam monitoring not working correctly 

### ISSUE THREAD

**Issue by regchanuk** [louislam/uptime-kuma#3418]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### Description

running some steam games like csgo and creativerse monitoring issue Not showing the green bar chart
![image](https://github.com/louislam/uptime-kuma/assets/46360316/63bfff62-6536-4612-9c11-aa0478961bac)

im thinking steam might have chane somthing 

ptime Kuma
Version: 1.22.1
Frontend Version: 1.22.1

### 👟 Reproduction steps

recreated monitor twice and still happening also happening on other server that i run uptime kuma

and  tried on other server running the same thing 

### 👀 Expected behavior

i was hoping it would show the bar like minecraft 
![image](https://github.com/louislam/uptime-kuma/assets/46360316/d2b05e1f-6147-4e52-9d49-43104a28ac2c)

### 😓 Actual Behavior

not showing bar graph properly and should show properly it was working a few days ago not sure whats happened 

### 🐻 Uptime-Kuma Version

1.22.1

### 💻 Operating System and Arch

debian 12

### 🌐 Browser

114.0.5735.199 Google

### 🐋 Docker Version

latest as of july

### 🟩 NodeJS Version

latest as of july

**Comment by CommanderStorm** [comment]
We rely on the `ping`'s from gamedig in the case of the monitor you specified:
https://github.com/louislam/uptime-kuma/blob/6bece8796e3d7cdb1642a1dc0a90603afb6c6f21/server/model/monitor.js#L619-L628

The following example shows that ping was being delivered:
https://github.com/gamedig/node-gamedig/issues/339

Have you updated the CSGO-Server to a newer version, for which Gamedig is currently not providing support for `ping`?

Could you test against your server what gamedig outputs and raise an issue over at gamedig if it does not contain the `ping` parameter?

**Comment by regchanuk** [comment]
im using steam info                                From                         Reginald Chan                             PUBLIC *******************************************************************This e-mail is confidential. It may also be legally privileged. If you are not the addressee you may not copy, forward, disclose or use any part of it. If you have received this message in error, please delete it and all copies from your system and notify the sender immediately by return e-mail.Internet communications cannot be guaranteed to be timely, secure, error or virus-free. The sender does not accept liability for any errors or omissions.*******************************************************************"SAVE PAPER - THINK BEFORE YOU PRINT!"On 13 Jul 2023, at 23:07, Frank Elsinga ***@***.***> wrote:﻿
We rely on the ping's from gamedig in the case of the monitor you specified:
https://github.com/louislam/uptime-kuma/blob/6bece8796e3d7cdb1642a1dc0a90603afb6c6f21/server/model/monitor.js#L619-L628
The following example shows that ping was being delivered:
gamedig/node-gamedig#339
Have you updated the CSGO-Server to a newer version, for which Gamedig is currently not providing support for ping?
Could you test against your server what gamedig outputs and raise an issue over at gamedig if it does not contain the ping parameter?

**Comment by louislam** [comment]
Double checked the steam api, it doesn't provide ping value. Closed due to impossible.

![image](https://github.com/louislam/uptime-kuma/assets/1336778/d3486660-f442-48c3-a747-fcc4ae2224b0)
