### ISSUE TITLE
Where the PING response from？

### ISSUE THREAD

**Issue by anniextra** [louislam/uptime-kuma#342]
i have setup the uptime-kuma, but i found the ping response time is NOT same as i ping from my pc.

in the uptime-kuma, i setup a SITE-A it said the responese is 433ms, but i open a terminal windows, it only 130ms

i just want to know, where is the ping response from SITE-A?

[https://imaxic.com/view.png](url)

**Comment by louislam** [comment]
Please read #327

**Comment by anniextra** [comment]
Thanks for reply...
