### ISSUE TITLE
Automatic Dependencies Updates

### ISSUE THREAD

**Issue by Zaid-maker** [louislam/uptime-kuma#3422]
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

Other

### 🔖 Feature description

It would cool to have a automatic dependencies update for this repo, it will allows to keep dependencies up to date. I have testing the automatic dependencies update on my fork.

### ✔️ Solution

There are many tools out there like Dependabot, Depfu & Renovatebot(using this on the fork). it would be cool if this feature got added <3

**Comment by louislam** [comment]
https://github.com/louislam/uptime-kuma/pull/388

I will run `npm update` before release, so no problem.

**Comment by Zaid-maker** [comment]
> #388
> 
> I will run `npm update` before release, so no problem.

hmm, but honestly i love the automatic update it makes life easier

**Comment by Zaid-maker** [comment]
There are so many deps so i dont think you can run npm update on every dep

**Comment by Zaid-maker** [comment]
Speaking of Dependabot its much faster and simpler nowadays you can give it a try!

**Comment by louislam** [comment]
`npm update` definitely could update all dependencies with just one command, but with dependabot, I have to click `Merge` everyday.

See this
https://github.com/louislam/uptime-kuma/commit/a9d691a6a81c9f776a0734b989961583a68a59d4

And read more about `npm update`
https://docs.npmjs.com/cli/v8/commands/npm-update

**Comment by Zaid-maker** [comment]
> `npm update` definitely could update all dependencies with just one command, but with dependabot, I have to click `Merge` everyday.
> 
> See this [a9d691a](https://github.com/louislam/uptime-kuma/commit/a9d691a6a81c9f776a0734b989961583a68a59d4)
> 
> And read more about `npm update` https://docs.npmjs.com/cli/v8/commands/npm-update

ohh that's something i didn't knew but still renovatebot has a automerge option

**Comment by Zaid-maker** [comment]
[Auto Merge](https://docs.renovatebot.com/configuration-options/#automerge)
