### ISSUE TITLE
ERROR: Error: Cannot find 'dist/index.html', did you install correctly?

### ISSUE THREAD

**Issue by xwsdgsdgs** [louislam/uptime-kuma#3426]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

i just run in and got issue 

### 📝 Error Message(s) or Log

 npm run start

> uptime-kuma@1.22.1 start
> npm run start-server

> uptime-kuma@1.22.1start-server
> node server/server.js

Welcome to Uptime Kuma
Your Node.js version: 18
2023-07-16T00:00:46Z [SERVER] INFO: Welcome to Uptime Kuma
2023-07-16T00:00:46Z [SERVER] INFO: Node Env: production
2023-07-16T00:00:46Z [SERVER] INFO: Importing Node libraries
2023-07-16T00:00:46Z [SERVER] INFO: Importing 3rd-party libraries
2023-07-16T00:00:48Z [SERVER] INFO: Creating express and socket.io instance
2023-07-16T00:00:48Z [SERVER] INFO: Server Type: HTTP
2023-07-16T00:00:48Z [SERVER] ERROR: Error: Cannot find 'dist/index.html', did you install correctly?
exit status 1
 

### 🐻 Uptime-Kuma Version

1.22.1

### 💻 Operating System and Arch

REPLIT

### 🌐 Browser

REPLIT

**Comment by CommanderStorm** [comment]
Replit was declared an unsupported platform given the amount of weird unreproducible issues on Replit which had been reported by other users already.
The main issue is, that the issues are not reproducible on other development platforms we support.
=> please develop using a normal (linux/windows/macos) device.

See https://github.com/louislam/uptime-kuma/issues/3131#issuecomment-1574770405

**Comment by louislam** [comment]
> Requirements:
Platform
✅ Major Linux distros such as Debian, Ubuntu, CentOS, Fedora and ArchLinux etc.
✅ Windows 10 (x64), Windows Server 2012 R2 (x64) or higher
❌ Replit / Heroku
