### ISSUE TITLE
Using some system languages, the content is garbled

### ISSUE THREAD

**Issue by visualczm** [louislam/uptime-kuma#3427]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

The content is garbled
![image](https://github.com/louislam/uptime-kuma/assets/22953065/fe0943e6-2c60-4ca1-b9bb-8cbf2b2307e0)
![image](https://github.com/louislam/uptime-kuma/assets/22953065/bdf2a859-f9ae-4bee-bd19-c16513c803af)

### 🐻 Uptime-Kuma Version

1.0.0

### 💻 Operating System and Arch

windows server 2016

### 🌐 Browser

Edge 113.0.1774.57

### 🟩 NodeJS Version

v18.14.1

**Comment by CommanderStorm** [comment]
What site were you pinging and what was the problem?
Could you provide a [Minimal, Reproducible Example](https://stackoverflow.com/help/minimal-reproducible-example)?

**Comment by chakflying** [comment]
This is likely a variant of #570. I think it's a difficult issue to support if `chardet` and `iconv` cannot handle the encoding.

**Comment by visualczm** [comment]
@chakflying @CommanderStorm 
thank you for your help ~
it's install windows 11 chinese version
yep，i think so like to #570  
system info:
![image](https://github.com/louislam/uptime-kuma/assets/22953065/2060d4b2-c05e-4a41-8d03-bcd6ce2ceb33)

uptime kuma setting:
![image](https://github.com/louislam/uptime-kuma/assets/22953065/66a7b590-9063-4955-a7cf-6002a0dbc46b)
![image](https://github.com/louislam/uptime-kuma/assets/22953065/644c256f-e346-4cc5-8681-ece710139a2c)
![image](https://github.com/louislam/uptime-kuma/assets/22953065/5d509a53-1880-4330-8009-6f5f22d4bd21)


problem ie:
![image](https://github.com/louislam/uptime-kuma/assets/22953065/0cf5240d-a81b-4521-90c0-2238af2298e1)

**Comment by visualczm** [comment]
@chakflying @louislam @CommanderStorm 
I have an idea, Is it possible to add a switch without displaying the details to avoid garbled characters,
maybe I just need to know that the server is offline.

**Comment by wc7086** [comment]
Tips that may help:
The default encoding for Chinese Windows is `GBK`
Code pages: 936
https://learn.microsoft.com/en-us/windows/win32/intl/code-pages
