### ISSUE TITLE
Notification-PushDeer: unavailable

### ISSUE THREAD

**Issue by kiddyyang** [louislam/uptime-kuma#3433]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### Description

When I test with Configure PushDeer, the error is reported as in the following screenshot.
[image](https://github.com/louislam/uptime-kuma/assets/11471064/349767bf-4057-4336-a47f-aa18cab8c60c)
My key is correct and has been tested successfully on other platforms. 

### 👟 Reproduction steps

Configure PushDeer and click the Test button

### 👀 Expected behavior

It looks like the PushDeer server is unavailable, I'm not sure what the program's default PushDeer API URL is, now the official default one should be: https://api2.pushdeer.com.
At the same time, I hope to add a custom API URL, because PushDeer supports setting up the user's own server, not using the official server, which is what I did. The official API also provides this parameter, the name of which should be API_BASE.

### 😓 Actual Behavior

The screenshot of the reported error is in the description.

### 🐻 Uptime-Kuma Version

1.22.1

### 💻 Operating System and Arch

Official Docker latest version

### 🌐 Browser

Google Chrome 114.0.5735.199

### 🐋 Docker Version

Docker 24.0.2

**Comment by CommanderStorm** [comment]
https://pushdeer.com/ seems to be down, but https://www.pushdeer.com/ seems not.
According to https://www.pushdeer.com/dev.html we are using their API correctly

See:

https://github.com/louislam/uptime-kuma/blob/8e72d6f5341a6c916408fc40bf81cf04173dffe6/server/notification-providers/pushdeer.js#L11-L29

**Comment by CommanderStorm** [comment]
Okay, so not a `bug`, right?

In this case:
Could you recreate this issue with the different fields in the [`feature_request`](https://github.com/louislam/uptime-kuma/issues/new?assignees=&labels=feature-request&projects=&template=feature_request.yaml) template?
Rationale: 
- only louis can change tags
- This removes the `Server Error` confusion

Alternative:
If you want to provide a PR for this, this would be appreciated. Such a PR should include screenshots that the notification provider works using `https://api2.pushdeer.com/` before and after making this parameter configurable.

**Comment by kiddyyang** [comment]
> [`feature_request`](https://github.com/louislam/uptime-kuma/issues/new?assignees=&labels=feature-request&projects=&template=feature_request.yaml)

Yes, sure, this is not a bug, I'll close this issue and re-submit a feature request, Thank you very much for your kind help.
But I'm sorry I don't have the development capacity to provide this PR.
