### ISSUE TITLE
Password reset completes but unable to use new or old password to log into Uptime Kuma

### ISSUE THREAD

**Issue by girhame** [louislam/uptime-kuma#3446]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### Description

I was unable to log into Uptime Kuma with the old password. I went through the steps to reset the password. It shows that it completed successfully, but I am still unable to log into Uptime Kuma with the new password. 
![image](https://github.com/louislam/uptime-kuma/assets/139905235/24cbbdd2-8682-4c3d-8c45-6b4b240e70e6)

### 👟 Reproduction steps

I went through the steps to reset the password. It stated it was successful but still not able to log in.

### 👀 Expected behavior

The new password should have worked.

### 😓 Actual Behavior

The new password does not work

### 🐻 Uptime-Kuma Version

1.22.1

### 💻 Operating System and Arch

Ubuntu 22.04.2 LTS

### 🌐 Browser

Google Chrome 114.0.5735.199

### 🐋 Docker Version

24.0.4

**Comment by CommanderStorm** [comment]
Have you set up 2FA?

**Comment by CommanderStorm** [comment]
Currently, I could not replicate this issue.
Can you provide us a [Minimal, Reproducible Example](https://stackoverflow.com/help/minimal-reproducible-example)?

The reproduction steps I took:
```bash
sudo docker run -p 3001:3001 louislam/uptime-kuma:1
```
go to http://localhost:3001 and add u:`admin` pw:`adminadmin1`
```bash
sudo docker ps -q
sudo docker exec -it 6ff58c500920 bash
npm run reset-password
```

changing the password to pw:`adminadmin2` works and is persistent after re-login.

**Comment by CommanderStorm** [comment]
Given that we cannot reproduce this issue (and the user is not responding), I am going to close this as `can't repro`
