### ISSUE TITLE
Optimize CERT info monitor，and integration it into other monitor type

### ISSUE THREAD

**Issue by anniextra** [louislam/uptime-kuma#345]
CERT Info only need update in 12/24hr, i mean there are no need to check them 1min，

so i think it can optimize CERT info in 2 type, 
1. manual，
2. 4/8/12/24hrs

i just need a heartrate monitor for my site and i also need CERT info, and need for the CERT update alert mails.

**Comment by CommanderStorm** [comment]
@anniextra
checking these certificates is very cheap.
What was the original reason/need for this feature request?

**Comment by CommanderStorm** [comment]
> @anniextra
> checking these certificates is very cheap.
> What was the original reason/need for this feature request?

I am going to close this issue as not planned because I don't see a usecase for this.
Feel free to reopen or comment on this issue if I am missing something.
