### ISSUE TITLE
Can the ssl certificate expiration time of all websites be displayed on one page?

### ISSUE THREAD

**Issue by gdtv** [louislam/uptime-kuma#3456]
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

UI Feature

### 🔖 Feature description

Now I have to click on each site individually to see the ssl expiration time for that domain

### ✔️ Solution

the ssl certificate expiration time of all websites be displayed on one page

**Comment by chakflying** [comment]
Can be solved with #3357.
