### ISSUE TITLE
Wiki installer command wrong

### ISSUE THREAD

**Issue by ruhrscholz** [louislam/uptime-kuma#3462]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### Description

In the wiki, under "How to Install" (https://github.com/louislam/uptime-kuma/wiki/%F0%9F%94%A7-How-to-Install), it says to run `curl -o kuma_install.sh http://git.kuma.pet/install.sh && sudo bash kuma_install.sh`.

This does not work, as http://git.kuma.pet/install.sh is a HTTP 301 redirect to the real script:

```
curl http://git.kuma.pet/install.sh
<html>
<head><title>301 Moved Permanently</title></head>
<body>
<center><h1>301 Moved Permanently</h1></center>
<hr><center>nginx</center>
</body>
</html>
```

The solution is to add curl's `-L` flag, which allows curl to follow redirects:

```
curl -Lo kuma_install.sh http://git.kuma.pet/install.sh && sudo bash kuma_install.sh
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   162  100   162    0     0    541      0 --:--:-- --:--:-- --:--:--   543
100  6013  100  6013    0     0  13220      0 --:--:-- --:--:-- --:--:-- 13220
=====================
Uptime Kuma Installer
=====================
Supported OS: CentOS 7/8, Ubuntu >= 16.04 and Debian
---------------------------------------
This script is designed for Linux and basic usage.
For advanced usage, please go to https://github.com/louislam/uptime-kuma/wiki/Installation
---------------------------------------

Local - Install Uptime Kuma in your current machine with git, Node.js 14 and pm2
Docker - Install Uptime Kuma Docker container

Which installation method do you prefer? [DOCKER/local]: ^C
```

### 👟 Reproduction steps

Run the command as specified in https://github.com/louislam/uptime-kuma/wiki/%F0%9F%94%A7-How-to-Install:

```
curl -o kuma_install.sh http://git.kuma.pet/install.sh && sudo bash kuma_install.sh
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   162  100   162    0     0    264      0 --:--:-- --:--:-- --:--:--   264
kuma_install.sh: line 1: html: No such file or directory
kuma_install.sh: line 2: syntax error near unexpected token `<'
'uma_install.sh: line 2: `<head><title>301 Moved Permanently</title></head>
```

### 👀 Expected behavior

It should execute the installer

### 😓 Actual Behavior

It tries to execute the redirect HTML page as if it were bash

### 🐻 Uptime-Kuma Version

1.22.1

### 💻 Operating System and Arch

Debian Bookworm

### 🌐 Browser

curl 7.88.1

**Comment by louislam** [comment]
Thanks, fixed.
