### ISSUE TITLE
MSSQL Connection Error

### ISSUE THREAD

**Issue by thumDer** [louislam/uptime-kuma#3468]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

I am not able to connect to an MSSQL DB Instance. The connection string should be ok, I can connect to the db with MSSMS using the same credentials. I receive the error message provided below

### 📝 Error Message(s) or Log

Cannot read properties of null (reading '0')

### 🐻 Uptime-Kuma Version

1.22.1

### 💻 Operating System and Arch

Synology DSM 7.2-64570

### 🌐 Browser

Firefox 115.0.2

### 🐋 Docker Version

20.10.3-1308

**Comment by chakflying** [comment]
What query are you running for the monitor?

**Comment by thumDer** [comment]
The following:
`Server=172.20.1.35,1433;Database=Company;User Id=guest;Password=pass;Encrypt=true;TrustServerCertificate=Yes;Connection Timeout=15`

**Comment by CommanderStorm** [comment]
If there are things in your db which indicate invalid states => check these, otherwise this example works well for most users:
![image](https://github.com/louislam/uptime-kuma/assets/26258709/15704655-6a01-44a5-926b-438b41711300)

**Comment by thumDer** [comment]
ah thanks, it is working now that way, it wasn't obvious enough for me.

**Comment by CommanderStorm** [comment]
> it wasn't obvious enough for me

I have added a PR which schould make this more obvious. Do you think a description what should be in this field would be nessesary?

**Comment by thumDer** [comment]
The example you provided in the PR should be enough, thanks!
