### ISSUE TITLE
IIS Reverse Proxy - 502.3 Bad Gateway

### ISSUE THREAD

**Issue by TekkGuy** [louislam/uptime-kuma#3470]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

OS: Windows 10 Pro
Web Server Installed: Yes (IIS)
Platform Usage: Docker

First, let me say that I am new to Docker and installed it specifically to run this application. After installing it, I saw that this application runs on port 3001. Now, for my own education, I wanted to know if it was possible to change the hostname and port that this application responded to. I happen to be also hosting some local use websites on IIS.

I read that I could use IIS to act as a reverse proxy, so I researched and following the directions found, I set up that ARR module and the URL Rewrite module. 

I activated the proxy, created a "Website Placeholder" (ie: blank site w/ correct hostname and SSL), added a reverse proxy rule to the website, and pointed it to localhost:3001. I selected the option to "Enable SSL Offloading" so that IIS handles the SSL but communicates to the application over regular HTTP. I also added two "Server Variables" (ie: which convert to headers): HTTP_Upgrade and HTTP_Connection, with the values of "websocket" and "upgrade", respectively.

Now when I navigate to my hostname, I get a page indicating a HTTP Error 502.3 - Bad Gateway.

Help!

### 📝 Error Message(s) or Log

HTTP Error 502.3 - Bad Gateway.

### 🐻 Uptime-Kuma Version

1.22.1

### 💻 Operating System and Arch

Windows 10 Pro

### 🌐 Browser

Google Chrome 114.0.5735.199

### 🐋 Docker Version

4.21.1

**Comment by CommanderStorm** [comment]
Have you googled the error message? => is an IIS issue

**Comment by zimbres** [comment]
You need:

URL Rewrite: https://www.iis.net/downloads/microsoft/url-rewrite
ARR: https://www.iis.net/downloads/microsoft/application-request-routing

Also you need to enable websocket support for IIS, on Windows Server this is under Server Manager - Roles and Features - Web Server - Application Development

Then:
https://www.youtube.com/watch?v=oIRjkPucQ9k

**Comment by TekkGuy** [comment]
@CommanderStorm Yes, I did Google it. I always do my best to find my own answers before I ask. But I could not get a clear answer, so I thought that perhaps I could ask here and there might be some kind soul that would be able to help me. I know that IIS is not spoken about in the Reverse Proxy information found here, which is again, why I asked. I thought maybe someone might have tried doing this and could have some advice. I understand that this is ultimately an IIS issue, however, it does seem to stem around the fact that the return response from the Kuma website is somehow causing an issue.

@zimbres Thank you for the information, however, as I explain in my OP, I already installed and setup ARR, as well as URL Rewrite. Unfortunately the video didn't show anything other than the setup items I already completed. However, you mentioned something about websocket support, so I will look into that. Thanks.

**Comment by zimbres** [comment]
@TekkGuy Did it worke for you?

**Comment by louislam** [comment]
Maybe it is not a Websocket issue, because normally, with a proper Websocket config, you can still see the first page.

Or you can try to request the logo.

https://hostname/icon.svg

https://status.kuma.pet/icon.svg

**Comment by kongxiangyiren** [comment]
use iisnode
https://github.com/kongxiangyiren/iis-twikoo

**Comment by kongxiangyiren** [comment]
use iisnode,
https://github.com/kongxiangyiren/uptime-kuma
and You need it
![image](https://github.com/louislam/uptime-kuma/assets/72970235/3f86a747-62ea-454d-84db-89d52798e684)
