### ISSUE TITLE
Cache Buster - does the cache buster function exist?

### ISSUE THREAD

**Issue by tallesairan** [louislam/uptime-kuma#3479]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### CacheBuster

I have a question, I would like to know if a feature exists in **uptime kuma**

I use many layers of cache in some applications, which often do not even respect the cache header, I would like to know if there is any way to pass some parameter "nocache=current_timestamp" in the url dynamically? 
I use this in the uptime robot, I believe that if I don't have this functionality I will develop it.

###  example from [uptime robot](https://uptimerobot.com/blog/cachebuster-a-pro-tip-for-bypassing-cache/)

> Uptime Robot will auto-replace the string:
> 
> *cachebuster*
> in the querystring with a unique timestamp every time so that each request is unique.
> 
> As an example, if the website to be monitored is:
> 
> https://mywebsitetomonitor.com
> We can use the URL as:
> 
> https://mywebsitetomonitor.com/?*cachebuster*
> and the request will have a different querystring each time.
> 
> Hope this helps for a better uptime.

### 📝 Error Message(s) or Log

Not Error

### 🐻 Uptime-Kuma Version

latest

### 💻 Operating System and Arch

Ubuntu 20.04

### 🌐 Browser

Google Chrome 95

**Comment by CommanderStorm** [comment]
No, this is currently not supported
See #575 for the issue which tracks this behaviour

**Comment by tallesairan** [comment]
Thanks 👍🏼
