### ISSUE TITLE
Notification enable toggle for each service is hard to see

### ISSUE THREAD

**Issue by karmanyaahm** [louislam/uptime-kuma#348]
**Describe the bug**
As shown in the screenshot below, when disabled, this toggle is very hard to see at it's small size. 

**To Reproduce**

**Expected behavior**
Due to my experiences with other software, I had assumed all notification sources would automatically be notified for all services, but that isn't the case and I spent a lot of time debugging why I wasn't receiving any notifications, when all I had to do was enable these toggles.

**Info**
- Uptime Kuma Version: 1.5.3
- Using Docker?: Yes
- OS: Ubuntu 20.04 
- Browser: Firefox 92.0b9-1

**Screenshots**
![image](https://user-images.githubusercontent.com/32671690/132285344-25cedb9a-3776-4fca-928d-c54735ab3206.png)

**Error Log**
N/A

p.s. thx for this cool app

**Comment by louislam** [comment]
Yes, it will be enabled automatically after added for the next version.

https://github.com/louislam/uptime-kuma/projects/1#card-68179722

**Comment by Ponkhy** [comment]
> Yes, it will be enabled automatically after added for the next version.
> 
> https://github.com/louislam/uptime-kuma/projects/1#card-68179722

Isn't it technically already in #340, or what do you mean by "add in" and "auto enable"?

**Comment by karmanyaahm** [comment]
Sorry if this was unclear, but I'm just asking for color changes which would make this toggle easier to see. Perhaps a lighter shade of gray in the background of the button, or a red outline could do it.

**Comment by louislam** [comment]
Better in https://github.com/louislam/uptime-kuma/commit/7a4432de1e7834d2ccd33336d0b29568ac923c2b

![image](https://user-images.githubusercontent.com/1336778/132688375-846bc09b-0159-4199-a315-05dfa8b66bd4.png)

**Comment by karmanyaahm** [comment]
Thanks!
