### ISSUE TITLE
[BUG] "Retries" option don't work for Radius monitor.

### ISSUE THREAD

**Issue by dnl4** [louislam/uptime-kuma#3486]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### Description

I trying to set Kuma to notify me only after 3 retries when radius e down. But it keep notifying me after the first "Access-Reject" response.

![image](https://github.com/louislam/uptime-kuma/assets/23690346/d8980c47-885c-451a-981b-d1cc278b354a)

![image](https://github.com/louislam/uptime-kuma/assets/23690346/df2246c7-1c27-4bc9-a251-62871fd56937)

### 👟 Reproduction steps

1. create a radius monitor
2. Heartbeat Interval = 60s, Retries = 3

### 👀 Expected behavior

Notify me after 3 failed attempts

### 😓 Actual Behavior

Notify me after the first failed attempt

### 🐻 Uptime-Kuma Version

1.22.1

### 💻 Operating System and Arch

CentOS 7

### 🌐 Browser

Safari 16.5.1 (18615.2.9.11.7)

### 🐋 Docker Version

Docker version 20.10.8, build 3967b7d

**Comment by CommanderStorm** [comment]
The code for the monitor is available at

https://github.com/louislam/uptime-kuma/blob/6413d4cbdfff4c20d7024548d701d46e91d35659/server/model/monitor.js#L749-L786

Even though this monitor is one of the monitors which still need extraction like https://github.com/louislam/uptime-kuma/pull/3413, I don't see an obvious defect

Could you retry with a higher "Retries" option (like 10) to rule out user-error?

**Comment by dnl4** [comment]
I will make tests and record a video to make sure.

I just realized that it only considers the "retry" in case of server  timeout. But not in case of user not found ("Access-Reject").
![image](https://github.com/louislam/uptime-kuma/assets/23690346/bfc568b1-11ec-4008-9265-cbb526c87abc)
