### ISSUE TITLE
RTL Status page

### ISSUE THREAD

**Issue by ahmadta721** [louislam/uptime-kuma#3487]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

Hello
I'm having trouble displaying the status page. If the descriptions and names of the monitors are written in right-to-left languages ​​(RTL). The status page is defined from left to right.
It will be displayed correctly only if the admin is logged in and the Uptime-Kuma language is defined as (right to left).
In fact, the status page is supposed to be displayed to others, which is not displayed correctly.

### 🐻 Uptime-Kuma Version

1.22.1

### 💻 Operating System and Arch

Ubuntu 22.04.2

### 🌐 Browser

Google Chrome 115.0.5790.110

**Comment by CommanderStorm** [comment]
Could you provide a screenshot of said difference?

**Comment by CommanderStorm** [comment]
Ah now I see.
Currently, it is not possible to select the language of a specific status page
See https://github.com/louislam/uptime-kuma/issues/2196 https://github.com/louislam/uptime-kuma/issues/1643 and https://github.com/louislam/uptime-kuma/issues/2784 for further details

The status page will always try to mach the language of the system it is running on from my experiments

you can set `localStorage.locale` to `fa` which makes the webpage right-aligned:
![image](https://github.com/louislam/uptime-kuma/assets/26258709/2d32668d-bc55-47fc-acd4-7778ec765786)

**Comment by CommanderStorm** [comment]
PRs for the other issues mentioned above always welcome, here is our contribution guide: https://github.com/louislam/uptime-kuma/blob/master/CONTRIBUTING.md

=> this issue can be closed as having more duplicates for these features only creates the risk of creating immortal zombies ^^
