### ISSUE TITLE
增加application/x-www-form-urlencoded请求类型

### ISSUE THREAD

**Issue by gaye746560359** [louislam/uptime-kuma#3488]
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

UI Feature

### 🔖 Feature description

application/x-www-form-urlencoded

### ✔️ Solution

application/x-www-form-urlencoded

**Comment by chakflying** [comment]
Duplicate of #1332
