### ISSUE TITLE
In browser push / notification

### ISSUE THREAD

**Issue by FLX-0x00** [louislam/uptime-kuma#3489]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

I am completely overwhelmed with the issues and its hard to find if there is any duplicate. I would like to ask if there is any possibility to set up (maybe in the main settings tab) a boolean switch that will globally enable the web notifications service of the browser itself, so you can keep the uptime kuma tab open and get browser notifications (if permissions are requested correctly). This allows you to run and monitor services in networks where there is no internet connection and you just need to "ping" => hey, this service is down. I think this should not be a new "provider", but a global settings => Notifications that can be turned on and off as needed. I hope everyone understands what I am trying to say. I did not find any hints for this feature, but it can be really helpful in some situations.

### 🐻 Uptime-Kuma Version

beta

### 💻 Operating System and Arch

docker

### 🌐 Browser

Google Chrome

**Comment by chakflying** [comment]
Currently there is no integration with browser notifications. Feature request is a duplicate of #2792.
