### ISSUE TITLE
Monitoring expired domain when deleted

### ISSUE THREAD

**Issue by tobsowo** [louislam/uptime-kuma#3492]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

I'll like to monitor a domain that is expired but forgot to renew and has passed redemption period. Is it possible to monitor such domain when it's available to the public?

### 🐻 Uptime-Kuma Version

1.21.3

### 💻 Operating System and Arch

Ubuntu 222.04

### 🌐 Browser

Brave

**Comment by CommanderStorm** [comment]
Certificate monitoring is available if this is what you are referring to.

If you are literally referring to domain expiry monitors:
I think this is a duplicate of https://github.com/louislam/uptime-kuma/issues/944
If you agree, could you please close this Issue, as duplicates only create immortal zombies and are really hard to issue-manage?
If not, what makes this issue unique enough to require an additional issue? (Could this be integrated into the issue linked above?) ^^

**Comment by Computroniks** [comment]
@tobsowo Currently this is not supported, and to be honest I don't think it is really something that will ever be supported as it seems quite out of scope for this project and it seems like quite a niche requirement.

@CommanderStorm not a duplicate of #944 as the domain has already expired and we are looking for if the domain has been released back to public sale yet.

**Comment by CommanderStorm** [comment]
> @CommanderStorm not a duplicate of #944 as the domain has already expired and we are looking for if the domain has been released back to public sale yet. 

If you monitor for domain expiry = 1 day (or smaller) that is a really good indicator of the domain expiring tomorrow 
=> This can/schould be handled via the domain monitor proposed in the mentioned issue imo

**Comment by CommanderStorm** [comment]
@tobsowo 
Only you or Louis can close this issue ^^
(ping, given that you gave a 👍🏻 on my last comment)

> If you agree, could you please close this Issue, as duplicates only create immortal zombies and are really hard to issue-manage?

**Comment by CommanderStorm** [comment]
Thanks ❤️
