### ISSUE TITLE
New event if the message of a push notification changes?

### ISSUE THREAD

**Issue by manelrodero** [louislam/uptime-kuma#3493]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

When monitoring every 1 minute via URL push, a new event does not appear if the status has not changed.

For example, if I use a URL like this https://my.kuma/api/push/r35ZHhZ43F?status=up&msg=Idle&ping=0 to indicate that the server is Up but not working (Idle) using the message I get the following event:

![image](https://github.com/louislam/uptime-kuma/assets/26098260/3cab402c-3609-4b44-85fb-8b3a14648079)

But when I send a status change with a new message https://my.kuma/api/push/r35ZHhZ43F?status=up&msg=Running&ping=1, no event appears because the server is still Up.

**Is there a way to log this "state change" of the service?**

### 🐻 Uptime-Kuma Version

1.22.1

### 💻 Operating System and Arch

Ubuntu 18.04.6 LTS

### 🌐 Browser

Microsoft Edge Versión 115.0.1901.183

### 🐋 Docker Version

ocker version 24.0.2, build cb74dfc

**Comment by CommanderStorm** [comment]
One possiblitly would be changing your up/down definition:
- Idle => Down
- Running => Up

Your usage of the push monitor is possibly out of scope for an uptime monitor

**Comment by manelrodero** [comment]
You're right, I don't just want to know if the service works (up) or doesn't work (down) but the last state of the same in the style of what can be done with Nagios.

If I do it as you indicate I will see a color change from green to red which is not entirely true ;-)

Let's imagine that you want to monitor a print queue. It can be up and running with 0 jobs in the queue or with 10 jobs in the queue.

You could solve this by sending the number of jobs in the Ping parameter. But I have seen that if the ping is 0, the current value is reported as N/A.

I'm going to rethink how we implement monitoring for these types of services.

Thanks for the help.

**Comment by CommanderStorm** [comment]
See https://github.com/louislam/uptime-kuma/issues/2790#issuecomment-1433707641
See https://github.com/louislam/uptime-kuma/issues/1675#issuecomment-1142259645

Also see the issues requesting custom vales for push monitors
A ping of 0ms does not make sense => N/A

**Comment by manelrodero** [comment]
Thanks for the information.

They are interesting monitoring proposals because not every time a service responds to a ping or an HTTPS request it can be considered to be "Up". For example, a web application can respond but if the database behind it is down, there is no data. Any improvements to be able to know if something works or doesn't work in this broader sense will be welcome.

An option to activate the generation of a new event if the message changes, even if the status does not, can serve to include useful information when solving problems.

And you're right that a ping of 0 doesn't make sense, hehe, but since I was using it to pass the number of jobs in the print queue I found it curious that it said N/A when a 0 had been passed. I would understand if it was N /A if no value was passed to you ;-)

I said, thank you very much for the help and for this fantastic project.
