### ISSUE TITLE
api requests to Uptime Kuma

### ISSUE THREAD

**Issue by JK-Effects** [louislam/uptime-kuma#3496]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

Is there a way to address the Uptime Api to get maintenance windows and offline/online status?
This would allow to display information as a shoutout on other web pages or on a frontend when the backend is offline / in maintenance.

### 🐻 Uptime-Kuma Version

Version: 1.22.1

### 💻 Operating System and Arch

Debian GNU/Linux 11 (bullseye)

### 🌐 Browser

Microsoft Edge Version 115.0.1901.183 

### 🐋 Docker Version

Docker version 20.10.22

**Comment by CommanderStorm** [comment]
There currently is no api, see #118 and other duplicates like https://github.com/louislam/uptime-kuma/pull/1927

If you want to contribute (this is a community-driven project), our [contribution guide](https://github.com/louislam/uptime-kuma/blob/master/CONTRIBUTING.md) and splitting https://github.com/louislam/uptime-kuma/pull/1834 would be starting points.

What we do offer however is the ability to get metrics via prometheus, which likely is sufficient for your usecase.
See the [wiki-entry](https://github.com/louislam/uptime-kuma/wiki/Prometheus-Integration)
