### ISSUE TITLE
Dashboard monitors take long time to appear

### ISSUE THREAD

**Issue by Zandor300** [louislam/uptime-kuma#3497]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### Description

When opening the dashboard on my Uptime Kuma instance, it takes a long time before the monitors appear on my screen. When looking at the messages being sent through Socket.io, I see that the `monitorList` message takes around 10 seconds to 2 minutes to be sent after I load the page.

Note that while waiting for this `monitorList` message to show up, a bunch of uptime and heartbeat messages do come through. When the `monitorList` message shows up, the monitor list in the browser instantly appears.

While waiting, the page looks like this:

![image](https://github.com/louislam/uptime-kuma/assets/6069593/54b97602-d747-457c-8b30-8641e347a3ea)

Same goes for `importantHeartbeatList` taking a long time to show up.

Currently running 1.22.1 but this has been a problem for the past +5 minor versions.

Not using the new groups feature.

Startup script:
```sh
#!/bin/bash

VERSION="1.22.1"

docker pull louislam/uptime-kuma:$VERSION

docker stop uptime-kuma || true && docker rm uptime-kuma || true

docker run -d \
  --restart=always \
  -p 3001:3001 \
  -v uptime-kuma:/app/data \
  --name uptime-kuma louislam/uptime-kuma:$VERSION
```

### 👟 Reproduction steps

Uptime Kuma instance running on DigitalOcean:
- Basic
- 2 vCPUs
- 2 GB RAM
- 60 GB of storage

Avg RAM usage: ~500MB  
Avg CPU usage: 1 vCPU at ~75%, the other doing almost nothing  
Disk usage: 47% of 60 GB in use

Just over 100 monitors.  
Only using Ping, HTTP(s) and Push monitor types.

Nothing else running on this VPS next to Docker running Uptime Kuma.

![image](https://github.com/louislam/uptime-kuma/assets/6069593/6637fb7a-f8e7-4526-825f-204015493fcd)

### 👀 Expected behavior

Monitors show up within 1-2 seconds.

### 😓 Actual Behavior

Page loads instantly, but monitors show up after +10 seconds, sometimes 20s or even multiple minutes.

### 🐻 Uptime-Kuma Version

1.22.1

### 💻 Operating System and Arch

Ubuntu 20.04 x64

### 🌐 Browser

Google Chome 115.0.5790.110 (64 bit)

### 🐋 Docker Version

20.10.10, build b485636

### 🟩 NodeJS Version

N/a

### 📝 Relevant log output

Tell me what you need to solve this issue.

**Comment by CommanderStorm** [comment]
I think this is one of the duplicates of https://github.com/louislam/uptime-kuma/pull/3463
Until we have improved the performance in this area, you can do these steps: https://github.com/louislam/uptime-kuma/issues/3494#issuecomment-1654178713
If you agree, could you please close this Issue, as duplicates only create immortal zombies and are really hard to issue-manage?
If not, what makes this issue unique enough to require an additional issue? (Could this be integrated into the issue linked above?) ^^
