### ISSUE TITLE
Cloudflare Tunnel Failing to connect

### ISSUE THREAD

**Issue by HollowCyberSec** [louislam/uptime-kuma#3505]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### Description

I followed the provided guide to connect cloudflare tunnel to Uptime Kuma but it will not work as show.
I'm shown this log: 
2023-07-30T20:44:41Z ERR  error="Unable to reach the origin service. The service may be down or it may not be responding to traffic from cloudflared: dial tcp <myip>:3001: i/o timeout" cfRay=7ef07029ca03da2f-MIA event=1 ingressRule=0 originService=http://<myip>:3001
2023-07-30T20:44:41Z ERR Request failed error="Unable to reach the origin service. The service may be down or it may not be responding to traffic from cloudflared: dial tcp <myip>:3001: i/o timeout" connIndex=0 dest=https://upmon.mydomain.com/favicon.ico event=0 ip=<ip> type=http

I have installed 3 Kuma instances and none have worked correctly. Is there something missing that is not described in the guide?

Thanks

### 👟 Reproduction steps

Install Kuma, create tunnel, insert token ID, start cloudflare tunnel, status installed and running, inserted VPS information into cloudflare tunnel, no access to website.

### 👀 Expected behavior

connection to uptime kuma instance

### 😓 Actual Behavior

no connection, error 502

### 🐻 Uptime-Kuma Version

1.22.1

### 💻 Operating System and Arch

Ubuntu 20.04 LTS

### 🌐 Browser

Microsoft Edge

### 🐋 Docker Version

20.10.21

**Comment by CommanderStorm** [comment]
> The service may be down or it may not be responding to traffic from cloudflared: dial tcp :3001: i/o timeout

- What are you getting if you do `curl localhost:3001` on the VPS?
- What are you getting if you run `sudo docker ps`?


> I have installed 3 Kuma instances and none have worked correctly

- What exactly are you referring to when you mean 3 instances?
- What is your networking diagram on the VPS?
- Have you installed `cloudflared` and are not using the path provided inside uptime-kuma?  (see https://github.com/louislam/uptime-kuma-wiki/pull/46/files why I am questioning this in particular)

**Comment by louislam** [comment]
My instance is working.

https://status.kuma.pet

**Comment by HollowCyberSec** [comment]
I thought the issue was with uptime kuma, but found the issue is with cloudflare. I have 2 more apps that are not working with tunnels either. Will close issue for now.
