### ISSUE TITLE
Trusting a local private CA

### ISSUE THREAD

**Issue by ChrisThePCGeek** [louislam/uptime-kuma#3506]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

I want to bind mount in my internal trusted CA cert so kuma can tell me when my local services certs are expiring. Right now I run it in kubernetes and I just mapped in the crt file to /usr/share/local/ca-certificates/myCA.crt inside the container.  then i added a post execute command to run `update-ca-certificates` which seems to have worked. i can see the cert in the /etc/ssl/certs but its still saying cant get local certificate and keeping my service marked as down.

What I wonder is does Uptime-Kuma not use the alpine system trusted cert store and if so where or how could I do the above to accomplish adding my local CA to make it trusted?

Thank you so much!!

### 🐻 Uptime-Kuma Version

1.22.1

### 💻 Operating System and Arch

debian k3s cluster

### 🌐 Browser

chrome

### 🐋 Docker Version

k3s 1.24.10

**Comment by joe-eklund** [comment]
I believe this is because it is actually using Node to execute the checks. Are you able to try setting the `NODE_EXTRA_CA_CERTS={you_cert_file}` environment variable to where you mapped the cert file?

**Comment by selloween** [comment]
I'm having the same issue using the latest Docker image (DIGEST:sha256:14c918a95df0813c6004073ad6ac7254784aa56196918b89eca101017627027b) 

@joe-eklund  I tried adding the environment variable NODE_EXTRA_CA_CERTS, but it didn't fix the problem.
In the logs I get following error:

` WARN: Monitor #4 'example.localnet': Pending: unable to get issuer certificate | Max retries: 1 | Retry: 1 | Retry Interval: 60 seconds | Type: http`

Thanks for your help.

**Comment by spezd** [comment]
Had the same issue, performed the following using version `1.23.1`
1. Copied the Smallstep CA to `/usr/local/share/ca-certificates/mycert.crt`
2. Add `NODE_EXTRA_CA_CERTS=/usr/local/share/ca-certificates/mycert.crt` to my stack, all works.

**Comment by jaknz** [comment]
I can confirm that setting the `NODE_EXTRA_CA_CERTS` variable resolved this for me. Stashed mine in /app/data/certs/ so will survive updates as well.
