### ISSUE TITLE
weblate has reported merge conflicts

### ISSUE THREAD

**Issue by AnnAngela** [louislam/uptime-kuma#3507]
See <https://weblate.kuma.pet/projects/uptime-kuma/uptime-kuma/#alerts>, it blocks us from updating translations.

@louislam Please take a look at it, and sorry if you knew it already.

**Comment by louislam** [comment]
Got it, try to fix it.

**Comment by louislam** [comment]
Ops, I don't why this time why it still cannot be merged even though I fix the conflict.

I checked the latest translation (yesterday) is in the #3318. So I completely reset the branch on Weblate to resolve this problem.

I hope it did not deleted anything. :/

![image](https://github.com/louislam/uptime-kuma/assets/1336778/9f8acf4a-5ae4-4d89-80c4-dd3fcbf4918d)

**Comment by AnnAngela** [comment]
> I think I should not allow anyone to touch language files (except en.json) in the pull requests, regardless of the situation.

@louislam I agreed it, maybe you can use [`CODEOWNER`](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-code-owners) to protect these files.
