### ISSUE TITLE
Send further notification (optionally by a different method, like text) if still down after longer time

### ISSUE THREAD

**Issue by mlncn** [louislam/uptime-kuma#3516]
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

New Notification, New Monitor

### 🔖 Feature description

Allow the creation of a "follow-up" notification for sites that remain down past a configurable amount of time.

### ✔️ Solution

If a site has been down one minute, send an e-mail notification.

If a site has been down one hour, send a text message notification.

### ❓ Alternatives

Building a separate service that tries to use the Kuma API, or to hook that up with something like IFTT or Zapier, but not finding anything obvious or easy.

### 📝 Additional Context

There can be a lot of noise with uptime monitoring at the 48 second level, and want to ensure we don't miss a much bigger problem within that.  An additional notification, ideally on a different medium, would completely alleviate that!

**Comment by CommanderStorm** [comment]
What you are referring to is already implemented via Resend
![image](https://github.com/louislam/uptime-kuma/assets/26258709/27278312-78a1-4149-a1b8-803a8cefae20)

This may also be a duplicate of #1323 or other issues.

**Comment by wolcen** [comment]
It isn't so much a re-send of the notification as it is an escalation.

To meet this use case, one could also have an additional monitor that uses a non-zero retry value, and set it to use the escalation-level notification settings.

**Comment by CommanderStorm** [comment]
I think this should be handled in a dedicated App like https://github.com/louislam/uptime-kuma/pull/2783

Anyway
I think this is a duplicate of https://github.com/louislam/uptime-kuma/issues/1315
If you agree, could you please close this Issue, as duplicates only create immortal zombies and are really hard to issue-manage?
If not, what makes this issue unique enough to require an additional issue? (Could this be integrated into the issue linked above?) ^^

**Comment by mlncn** [comment]
Ah yes, thanks!  Sorry i did not find #1315— some more keywords for the next person: backup notifications, follow-up alerts, extra ping for extended downtime, all that is in #1315 !
