### ISSUE TITLE
Seemingly Random "Cannot connect to the socket server. [Error: websocket error] Reconnecting..."

### ISSUE THREAD

**Issue by viasux** [louislam/uptime-kuma#3519]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### Description

I'm getting this popup when I go to example.com/dashboard

<img width="592" alt="image" src="https://github.com/louislam/uptime-kuma/assets/47131867/b9e04ff9-eb44-421a-a955-30af679fb645">

I don't exactly know what could have caused this, as it's worked in the past and it was working before I updated uptime kuma. (I updated to see if it would fix this) - I'm using caddy and my caddyfile was reverse_proxy -ing `localhost:3001` but I changed it to `127.0.0.1:3001`, as per the docs after seeing the error, nothing changed.

I'm not sure how this could be an issue with caddy, because if it wasn't being proxied correctly, I wouldn't even be able to see this page in my browser.

### 👟 Reproduction steps

Not exactly sure, I came across it after updating my system, but I haven't checked the dashboard in a long while.

### 👀 Expected behavior

This error should not show, and the dashboard should work.

### 😓 Actual Behavior

silly error

### 🐻 Uptime-Kuma Version

Should be 1.22.1, as it says last updated today, 2023-08-02

### 💻 Operating System and Arch

Debian 11 Bullseye

### 🌐 Browser

Brave

### 🐋 Docker Version

Docker version 24.0.5, build ced0996

**Comment by chakflying** [comment]
What types of monitor and how many are you running? What is the monitor history period set to?

**Comment by viasux** [comment]
> What types of monitor and how many are you running? What is the monitor history period set to?

Well I can't see the dashboard so I can't check any of my configs, but I'm running 8 of them right now. I have one game server and at least 5 of the others are websites, checking with text. No clue what the monitor history period is set to

**Comment by chakflying** [comment]
Since you are running docker, have you checked the container logs for any errors?

**Comment by viasux** [comment]
> Since you are running docker, have you checked the container logs for any errors?

docker logs [containerid] doesn't seem to return any errors

**Comment by CommanderStorm** [comment]
How have you configured the websocket in caddy?
Have you followed https://github.com/louislam/uptime-kuma/wiki/Reverse-Proxy#caddy ?

**Comment by louislam** [comment]
Try to access Uptime Kuma via 127.0.0.1:3001 and make sure that Uptime Kuma is running.

If you don't have a desktop env on your server, you can ssh and tunnel 3001 via putty on Windows.
![image](https://github.com/louislam/uptime-kuma/assets/1336778/e474ffce-3f63-4a9b-8ce1-9ca873c6d622)

**Comment by viasux** [comment]
> How have you configured the websocket in caddy? Have you followed https://github.com/louislam/uptime-kuma/wiki/Reverse-Proxy#caddy ?

I followed the reverse proxy documentation

what websocket?

**Comment by viasux** [comment]
> Try to access Uptime Kuma via 127.0.0.1:3001 and make sure that Uptime Kuma is running.
> 
> If you don't have a desktop env on your server, you can ssh and tunnel 3001 via putty on Windows. ![image](https://user-images.githubusercontent.com/1336778/258319414-e474ffce-3f63-4a9b-8ce1-9ca873c6d622.png)

no de, no access to a windows machine, i just do everything over ssh

i have discord notis set up for when things crash and they still work, everything except for the dashboard works as i said
