### ISSUE TITLE
Expose tags in Prometheus metrics

### ISSUE THREAD

**Issue by mateuszdrab** [louislam/uptime-kuma#3524]
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

API

### 🔖 Feature description

As the tags feature is very useful in storing additional data about monitors, I have realized that it would provide extra value if those tags were exposed to the Prometheus compatible metrics endpoint at `/metrics`. 
In my case, the use case would be to provide a severity label on the monitors so that it could then be used to alter the severity of the Prometheus alert. There are some monitors I'd like Prometheus to alert on at lower than critical severity which is the default.
It could also be useful in other scenarios

### ✔️ Solution

Expose tags as labels or meta-labels with the __ prefix so that users could use the relabeling process to keep/rename/drop tags as needed. 
I think the meta-metric approach would be best and is something that various native service discovery mechanisms already provide in Prometheus.

### ❓ Alternatives

Perhaps meta labels could also be exposed for enabled notification channels, which for some users could be useful in deciding which alerts are critical or not. For example, if the monitor notification channel A is enabled, then it would also mean the Prometheus alert needs to have a higher severity (which can be achieved through relabels).

**Comment by mateuszdrab** [comment]
Nevermind, as I posted I checked for PRs instead of issues and here it goes 😂
https://github.com/louislam/uptime-kuma/pull/898

**Comment by amrap030** [comment]
Unfortunately, it seems this feature is removed. For me it is a much needed feature and I would be thankful if this could be added again as soon as possible. Why was this removed? I also checked in v2 if it is available, but unfortunately not.

**Comment by dandanx** [comment]
@amrap030 had the same issue, checked the Code, labels are included, checked the logs, found errors from the Prometheus-Exporter complaining about labels not defined on initialization. If someone has the same issue after creating new tags, just restart Uptime-Kuma after the creation.
