### ISSUE TITLE
Another bug with filtering and group monitors

### ISSUE THREAD

**Issue by chakflying** [louislam/uptime-kuma#3533]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### Description

![image](https://github.com/louislam/uptime-kuma/assets/3271800/08d6013d-ef69-4149-b75d-16250bc67064)

### 👟 Reproduction steps

1. Add Group monitor A
2. Add monitor B, placed in group A
3. Click on monitor B to open its details page
4. Select a filter that applies to monitor B, e.g. "Running"
5. Observe that monitor B is shown twice

### 👀 Expected behavior

Group should stay collapsed if filtering is active, and the child is already shown in the root list

### 😓 Actual Behavior

Group is expanded and monitor is shown twice

### 🐻 Uptime-Kuma Version

master

### 💻 Operating System and Arch

Windows 11 x64

### 🌐 Browser

Mozilla Firefox

**Comment by derekoharrow** [comment]
Also, when filtered the monitors in the list include the full hierarchy - in the image above it shows "Test Group / Test Radius" under "Test Group". When you have lots of monitors this becomes messy as they all begin with "Test Group /" and you can't see which is which.

When filtered, it should not show the hierarchy on the monitor line, only the monitor name itself.

**Comment by chakflying** [comment]
But there are also people who have monitors with the same name, but under a different hierarchy:

- sever 1
  - redis
- server 2
  - redis

The pathname feature was designed for this use case.

**Comment by derekoharrow** [comment]
> But there are also people who have monitors with the same name, but under a different hierarchy:
> 
> * sever 1
>   
>   * redis
> * server 2
>   
>   * redis
> 
> The pathname feature was designed for this use case.

Then those should be grouped under the groups - e.g.

server 1
    redis
server 2
    redis

The same way as it works for unfiltered monitors.

**Comment by derekoharrow** [comment]
Here's an example to illustrate:

Unfiltered:

![image](https://github.com/louislam/uptime-kuma/assets/38404530/75a76f36-08d3-4c45-8f38-63c04f5caf62)


Filtered:

![image](https://github.com/louislam/uptime-kuma/assets/38404530/eb3d2c40-903f-4e58-8769-90a0b657aeb9)

As you can see in the filtered example, you can no longer see which monitor is what.
