### ISSUE TITLE
钉钉通知不支持中文通知吗？

### ISSUE THREAD

**Issue by ivanmissu** [louislam/uptime-kuma#3535]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

钉钉通知不支持中文通知吗？

### 🐻 Uptime-Kuma Version

1.22.1

### 💻 Operating System and Arch

CentOS 7.9 x86

### 🌐 Browser

Chrome 115.0.5790.102

### 🐋 Docker Version

K8S

**Comment by CommanderStorm** [comment]
Commenting in Chinese on a repo which is primarily in English is not recommended for obvious reasons (I and other people helping with issue-management cannot read/speak chinese) => please stick to english in the future

Translation by Google Translate:
> Doesn't pinned notifications support Chinese notifications?

Could you please attach a screenshot of what notification you are refering to?
Some Server-messages will be translatable by https://github.com/louislam/uptime-kuma/pull/3263
For full-templating of notifications please read
- these PRs: https://github.com/louislam/uptime-kuma/pull/760 https://github.com/louislam/uptime-kuma/pull/751
- and these issues: https://github.com/louislam/uptime-kuma/issues?q=is%3Aissue+is%3Aopen+notification+template, most notable https://github.com/louislam/uptime-kuma/issues/975

**Comment by PangKingTing** [comment]
I found that after integrating DingTalk notifications, the update-kuma platform was unable to push fault notifications to DingTalk. I don't know where the problem lies.
