### ISSUE TITLE
Some way to stop all alerts for X period of time? (part of backups)

### ISSUE THREAD

**Issue by jaxjexjox** [louislam/uptime-kuma#3537]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

I would love to 'pause' notifications.

I know about the docker exec command to reset my password, would love something like

```
docker exec -it <container name> bash
npm run pause 10m
```

Currently I do the following on my server.

sudo docker stop kuma
sudo docker rm kuma
sudo cp /kumadatafolder/  /backups/kumadatabackup/
sudo docker run (etc etc etc)

In doing this - it will go and spam out a whole heap of emails again, if anything is out of action.
Be nice to stop that, for the duration of the backup process somehow

It might be possible, I'm not aware (apologies)

### 🐻 Uptime-Kuma Version

All

### 💻 Operating System and Arch

22.04 - docker (latest, always)

### 🌐 Browser

NA

### 🐋 Docker Version

Docker version 24.0.5, build ced0996

**Comment by CommanderStorm** [comment]
What you are refering to is the maintance mode:
![image](https://github.com/louislam/uptime-kuma/assets/26258709/c34849d4-6982-4087-86db-043c93f70d15)

**Comment by jaxjexjox** [comment]
Can I "inject" maintenance mode into my instance via cli, before stopping my container, and then cancel it again via cli ?

**Comment by CommanderStorm** [comment]
You can, but not via first-party tooling, as ahead of time configuration would be against the ["project-style"](https://github.com/louislam/uptime-kuma/blob/master/CONTRIBUTING.md#project-styles) and the API is currently in this state #118 

See https://github.com/lucasheld/uptime-kuma-api for further details on the third party I was referring to
