### ISSUE TITLE
[Notification] Add group placeholder for title

### ISSUE THREAD

**Issue by felixschndr** [louislam/uptime-kuma#3538]
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

Other

### 🔖 Feature description

I love the integration of Groups and use them a lot. For this I'd like to be able to include the Group in the Notification.
-----
Example:
I have the following setup:
![image](https://github.com/louislam/uptime-kuma/assets/45742226/e7f6b798-4280-4400-9962-48dcb488fa37)
I have monitors for two nextcloud instances. So there is 
- a group for nextcloud
  - a group for instance 1
    - a monitor for the service itself
    - a monitor for the logviewer of the website
  - a group for instance 2
    - a monitor for the service itself 
    - a monitor for the logviewer of the website
-------
Now, when I get a notification I only get the title of the monitor that has changed. So to be able to identify which monitor (in this case instance 1 or 2?) changed I have to include the whole title in the service name. However as a consequence the name of the monitors are long and duplicate what the group names already describe.

### ✔️ Solution

Add a new placeholder for the group name
![image](https://github.com/louislam/uptime-kuma/assets/45742226/ad26d01c-fa2c-4633-a5f2-888a10a8e582)
This is for email. I am unsure about other notification services, something to discuss...

**Comment by CommanderStorm** [comment]
Should I mark it as resolved by https://github.com/louislam/uptime-kuma/pull/3414? (said PR gives you the ability to access this template-variable)

**Comment by felixschndr** [comment]
Yes, thank you. I didn't see that PR
