### ISSUE TITLE
Intermittent Issue, monitoring appear DOWN but Server Isnot DOWN

### ISSUE THREAD

**Issue by okamah** [louislam/uptime-kuma#3547]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### Description

Hi,

Iam using uptime-kuma since some months ago.

There is problem especially when I monitor some server, not all my server appear intermitten monitoring.

the problem intermitten is
Server dont have problem to remote. But uptime kuma appear status down. then not more than 1 minute appear UP. Like this:

<html>
<body>

Name | Status | DateTime | Message
-- | -- | -- | --
XX.XX.XX.XX Server | Up | 2023-08-09 11:58:51 |  
XX.XX.XX.XX Server | Down | 2023-08-09 11:57:46 | Request timeout
XX.XX.XX.XX Server | Up | 2023-08-09 07:35:31 |  
XX.XX.XX.XX Server | Down | 2023-08-09 07:34:26 | Request timeout

</body>
</html>

That status very often, and annoying when we use webhook notification, we got many report down and up but there is no internet problem in the server.

I have trying update and now using uptime kuma version 1.22.1.
More case is happend to Singapore server.
So I have migrate uptime-kuma server from german to singapore server. BUT STILL SAME.

any advice for us to solve this?

### 👟 Reproduction steps

-

### 👀 Expected behavior

-

### 😓 Actual Behavior

Intermitten status down/up, but no problem with server we are monitored.

### 🐻 Uptime-Kuma Version

1.22.1

### 💻 Operating System and Arch

Ubuntu 20.04.6 LTS

### 🌐 Browser

115.0.5790.171 

### 🐋 Docker Version

20.10.25, build 20.10.25-0ubuntu1~20.04.1

### 🟩 NodeJS Version

v16.20.1

**Comment by Computroniks** [comment]
Do you experience this issue consistently? I.e. 1 minute down, 1 minute up for the entire day or is it more the monitor will randomly go down? Timeouts can occur during network operations. It does not necessarily mean that the server being monitored is down as it could be something else on the path between Uptime Kuma and the server, especially if the two are a long way apart. It might be worth increasing the number of retries the monitor does before it marks it's self as down to reduce the notifications.

**Comment by okamah** [comment]
Yes, its consistency until now giving me notification. But there is no problem with the server.

We can make sure that path betwen uptime kuma server and the server is OK, we added some IP with same datacenter. But it is randomly and only for below 1 minute down then up again....continously.

How many retries thay you recommend?
I have tried increased this but not solve to reduce many notification

**Comment by Computroniks** [comment]
> How many retries thay you recommend?

Normally 2-3 would be OK. Just out of interest, what is the load on your server running Uptime Kuma, and what are it's specs (RAM, number of cores, HDD space)? How many monitors are you running? Are you running any other services on the Uptime Kuma server? If the server is under heavy load, it could possibly cause issues with monitoring. Which monitoring type are you using? It might be worth temporarily switching over to the `ping` monitor type to help rule out any networking issues.

**Comment by okamah** [comment]
We are using hetzner, 2GB and 2core with usage currently for 60 servers, with load still below 50%.

Server only use for uptime kuma task only.
And also I have using both port and ping method. 
The problem still same.

Now Iam also trying with second uptime kuma server with vultr. With same specs, but problem is random. Intermitten notification as problem we mention is got random. And different between both servers.

Thank you

**Comment by Computroniks** [comment]
What interval are the monitors set at? Does this issue affect all monitors or just a few?

**Comment by louislam** [comment]
You should also add https://google.com or https://uptime.kuma.pet for comparison.

**Comment by okamah** [comment]
I have added these...will update soon

**Comment by okamah** [comment]
Hi, do you have sample server with singapore datacenter that we can added to compare with....
As we mention in the first, most case randomize come from singapore server.

I am just now got random again about 6 singapore server in different provider and all notif up below 1 minute.

Current still using port 3389. Same case if we are using ping monitoring.

Thank you

**Comment by PenNotes** [comment]
Did this ever get fixed because I am running into the same issue. One Server keeps pinging back that it is offline then a couple minutes later it comes back onlin e. Meanwhile the server has never been down but in my asumption that application is having issues. Current version, Version: 1.23.13

**Comment by CommanderStorm** [comment]
The issue you are commenting on was orriginally just the regular networking troubles.
If you increase your retries or fix your network issues, you won't get notified.. 

It is unlikely to be related to uptime kuma.
