### ISSUE TITLE
Set a primary monitor for a monitor group

### ISSUE THREAD

**Issue by JackBailey** [louislam/uptime-kuma#3548]
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

UI Feature

### 🔖 Feature description

A monitor group should have a "primary" monitor as a child.

### ✔️ Solution

Have a checkbox for each monitor which is in a group, when checked it'll be set as the primary monitor for the group.

### 📝 Additional Context

This means you can have a group per server, with primary monitor set which monitors the state of the server (Such as a PUSH). If that monitor goes down, the whole group is down and a notification is sent, no notifications are sent for the individual monitors. (So you don't get a bunch of notifications if the server itself goes down).

When the primary monitor is working again, it'll send a notification, if other monitors in the group don't come back up within their heartbeat interval + retries period, send notifications for each monitor (So if the server restarts but some services don't automatically restart, you'll get a notification).

I understand this would probably be pretty complex to implement but It'd be a really useful feature.

**Comment by CommanderStorm** [comment]
I think this is a duplicate of the issues linked by https://github.com/louislam/uptime-kuma/pull/1236
If you agree, could you please close this Issue, as duplicates only create immortal zombies and are really hard to issue-manage?
If not, what makes this issue unique enough to require an additional issue? (Could this be integrated into the issue linked above?) ^^

**Comment by JackBailey** [comment]
Yes, that PR would resolve this enough for me. Wouldn't get the notifications if the primary monitor is up and its dependants are not but that's not a massive issue.

**Comment by bernarddt** [comment]
I just want to mention here that a similar result can be achieved by adding a "Group" monitor (basically it groups monitors together) and then just disabling the notifications of the individual monitors inside the group and enabling the notifications of the group itself. The group will report when one or many children are failing, and you only get a notification for the group, and not each monitor.

**Comment by ezaratemx** [comment]
Has someone figured out how to send a notification only if the full group fails or for example, when you have 3 monitors in a group and 2 of those fail, then only notify?
