### ISSUE TITLE
How to create an account?

### ISSUE THREAD

**Issue by Khangb1234** [louislam/uptime-kuma#3550]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

I need create account 

### 🐻 Uptime-Kuma Version

Xxxx

### 💻 Operating System and Arch

Xxxxx

### 🌐 Browser

Xxxx

**Comment by CommanderStorm** [comment]
Currently, multiple users are not possible.
See https://github.com/louislam/uptime-kuma/issues/128 for futher details

**Comment by jaxjexjox** [comment]
@Khangb1234  You may note, there's a 'dashboard' status view, which lets people view things, without edit ability, this may be useful for your needs?
