### ISSUE TITLE
Cert Exp not shown in overview, but service marked as down when expired

### ISSUE THREAD

**Issue by liquidat** [louislam/uptime-kuma#3551]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### Description

One out of my many tests does show the "Cert Exp." in the monitor overview - although it showed the service as DOWN when the certificate expired!

Screenshot of the service (my local FritzBox):
![image](https://github.com/louislam/uptime-kuma/assets/1998084/94d21594-3fe9-4ee0-afe6-7ed9926a8c04)
Screenshot of the same configuration, for my local Grafana, as comparison:
![image](https://github.com/louislam/uptime-kuma/assets/1998084/b238eb40-69c6-4ec9-8a54-85e1977ef8b9)

Monitor configuration:
![image](https://github.com/louislam/uptime-kuma/assets/1998084/58263a29-1d1f-418f-aed1-92c87b9f3bf4)

Logs in UI, showing that the monitor was down:
![image](https://github.com/louislam/uptime-kuma/assets/1998084/4180f047-88a8-4a1a-8d18-f73920126b33)

Logs indicating that the expiry date was correctly identified, see below.

### 👟 Reproduction steps

1. Set up Kuma
2. Set up FritzBox with certificate (let's encrypt, domain based)
3. Set up Kuma monitor on FritzBox, activate "Certificate Expiry Notification"

### 👀 Expected behavior

The cert expiry should be shown in the monitor overview.

### 😓 Actual Behavior

The cert expiry is not shown.

Note that in the backed everything is working fine: when we reached the expiry date, the service was shown as down in Kuma!

### 🐻 Uptime-Kuma Version

1.22.1

### 💻 Operating System and Arch

Raspbian GNU/Linux 11 (bullseye), ARM

### 🌐 Browser

Chrome, Firefox

### 🐋 Docker Version

Docker version 20.10.5+dfsg1, build 55c4c88

### 🟩 NodeJS Version

16

### 📝 Relevant log output

```shell
uptime-kuma     | 2023-08-09T13:09:12+02:00 [MONITOR] WARN: Monitor #14 'FritzBox': Failing: certificate has expired | Interval: 60 seconds | Type: http | Down Count: 0 | Resend Interval: 0
uptime-kuma     | 2023-08-09T13:10:12+02:00 [MONITOR] WARN: Monitor #14 'FritzBox': Failing: certificate has expired | Interval: 60 seconds | Type: http | Down Count: 0 | Resend Interval: 0
uptime-kuma     | 2023-08-09T13:11:12+02:00 [MONITOR] WARN: Monitor #14 'FritzBox': Failing: certificate has expired | Interval: 60 seconds | Type: http | Down Count: 0 | Resend Interval: 0
```

**Comment by zappityzap** [comment]
I've seen this with one of my monitors too, but haven't been able to figure out why.

**Comment by xifengzhu** [comment]
I've seen this with one of my monitors too.

**Comment by chakflying** [comment]
Would be great if someone can share a url where this is reproducible so we can test and debug this.

**Comment by xifengzhu** [comment]
> Would be great if someone can share a url where this is reproducible so we can test and debug this.

https://wordmind.ai

**Comment by CommanderStorm** [comment]
Cannot reproduce; The cert is valid and is displayed as such.
The cert expiry is also displayed.
Am I misssing something?

![image](https://github.com/louislam/uptime-kuma/assets/26258709/f87e9081-dd34-4a38-811e-7bcf3a9b9ace)

**Comment by xifengzhu** [comment]
> @xifengzhu Cannot reproduce; The cert is valid and is displayed as such. The cert expiry @liquidat reported is also displayed. Am I misssing something?
> 
> ![image](https://private-user-images.githubusercontent.com/26258709/292789510-f87e9081-dd34-4a38-811e-7bcf3a9b9ace.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM1NTY5MTAsIm5iZiI6MTcwMzU1NjYxMCwicGF0aCI6Ii8yNjI1ODcwOS8yOTI3ODk1MTAtZjg3ZTkwODEtZGQzNC00YTM4LTgxMWUtN2JjZjNhOWI5YWNlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjI2VDAyMTAxMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUzMjY3ZmFkMTViY2U4M2IyZDIyYjFmMDg5OTk0NmQ5OGVjYTVmYTMyNDEwNzkwYzBkNmZhMTQ5Y2UyNDFkZGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.zM6WRB6lmTeZCqkRIZaUxMoS7eLEDRNguLdb1Mvm7Iw)

I found that https://wordmind.ai can recognize the certificate, but if it is https://wordmind.ai/health_check, it cannot recognize the certificate.

**Comment by Niemand2006** [comment]
This error is when the Port from https is not 443.

**Comment by ihcops** [comment]
> Would be great if someone can share a url where this is reproducible so we can test and debug this.

https://bill.vps1.net/ 

![20240309174i308](https://github.com/louislam/uptime-kuma/assets/30463397/9802cfcd-0a98-4d0d-aa9d-d0fdd578579b)

**Comment by CommanderStorm** [comment]
Tested https://github.com/louislam/uptime-kuma/pull/4281 as working and fixing this example too
<details><summary>Details</summary>
<p>

![image](https://github.com/louislam/uptime-kuma/assets/26258709/2ccf5cd5-102f-4794-982e-56858521921e)

</p>
</details>

**Comment by CommanderStorm** [comment]
Resolved in next patch release
