### ISSUE TITLE
For Ping (Or HTTPs) Add a minimum response time - After that, warn, then service alert

### ISSUE THREAD

**Issue by francismiles1** [louislam/uptime-kuma#3552]
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

New Monitor

### 🔖 Feature description

there are people suggesting Ping TTL etc, but what I am suggesting is setting a minimum and maximum bar on response times.
For some failing services, their response times go through the roof, but still work. Its useful to know this before the inevitable crash.

### ✔️ Solution

Add a minimum and maximum response time capability.
If response times (averaged over the number of times this happens - set by the user) fall within these bounds, alert with a WARNING
If response times fall outside of the Maximum, or service Fails, Alert with FAIL

**Comment by Computroniks** [comment]
Is this a duplicate of #459 and #1813? If it is, could you please close this issue to try and avoid cluttering the issue list too much.

**Comment by francismiles1** [comment]
Oops, sorry, didn't see those. Yes, will close.
