### ISSUE TITLE
We can't able to integrate the uptime-kuma with mail for notification

### ISSUE THREAD

**Issue by axit678** [louislam/uptime-kuma#3557]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

We can't able to integrate the uptime-Kuma with mail notification

For username, password and hostname we have created a SES(AWS) service.

### 📝 Error Message(s) or Log

While testing the notification we are receiving the mails but not while the monitor is down.

### 🐻 Uptime-Kuma Version

1.22.1

### 💻 Operating System and Arch

Ubuntu

### 🌐 Browser

Edge

**Comment by CommanderStorm** [comment]
I have a few thoughts, where this might come from:
- have you loooked in the spam folder
- is there a ratelimit / other filter configured in SES which might block this notification
- have you made shure that the notification is actually enabled on the monitor

**Comment by axit678** [comment]
> I have a few thoughts, where this might come from:
> 
> * have you loooked in the spam folder
> * is there a ratelimit / other filter configured in SES which might block this notification
> * have you made shure that the notification is actually enabled on the monitor

Thanks @CommanderStorm 
We have found that the issue is with the domain.

**Comment by axit678** [comment]
Closing the issue
