### ISSUE TITLE
Persistence of data

### ISSUE THREAD

**Issue by vasanthkumar97** [louislam/uptime-kuma#3558]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

Hi, I'm trying to setup a self managed uptime monitoring , and found this product built just for my usecase, 

Im able to build this using docker and monitor services . Im confused how do i persist my data , Is there any support for a mysql or postgres database to persist data or is file system an only option. 

Thanks  

### 🐻 Uptime-Kuma Version

1.22.1

### 💻 Operating System and Arch

ubunu 20 

### 🌐 Browser

Chrome

**Comment by CommanderStorm** [comment]
- mariadb will be a feature in [`v2.0`](https://github.com/louislam/uptime-kuma/pull/2720)
- We are currently using sqlite => persistence is something we already offer. No need to wait for mariadb support

**Comment by vasanthkumar97** [comment]
Is it in memory of file system?

**Comment by louislam** [comment]
I think it is a Docker question. I assume that you were starting a Uptime Kuma using the `docker run` command.

```
-d 
--restart=always 
-p 3001:3001 
-v uptime-kuma:/app/data 
--name uptime-kuma
```

You should learn these arguments: https://docs.docker.com/engine/reference/commandline/run/

And let me ask you back a question, what is the usage of `-v`?

**Comment by vasanthkumar97** [comment]
I understand its mounted volume to docker container, Im trying to find out if there is any other alternate

**Comment by CommanderStorm** [comment]
No, there is currently no other way to be more persistent than the filesystem, as we need a database.
Out of curiosity: What are your requirements / why were you confused? Can we improve the docs somewhere?

PS: If this resolves your question, don't forget to close this issue.
