### ISSUE TITLE
Support corporate https_proxy

### ISSUE THREAD

**Issue by pronyma2097** [louislam/uptime-kuma#356]
**Is it a duplicate question?**
no

**Describe the bug**
I'm using docker image (1.5.3 version) and I'm trying to poll a simple https website.
First, I had a "getaddrinfo ENOTFOUND" error, fixed it by setting ENV HTTPS_PROXY variable in a local dockerfile.
This was because i'm working under a corporate proxy.
But now I'm experiencing "Request failed with status code 501" error, I don't know why...
Just in case, this is not a reverse proxy problem, this is going through proxy problem.

**To Reproduce**
1. Go to 'Add New Monitor'
2. Set 'Monitor Type' to 'HTTP(s)'
3. Set 'Friendly Name' to 'test'
4. Set 'URL' to 'https://www.google.fr/' or any other website
5. Click on 'Save'
6. See error 'Request failed with status code 501'

**Expected behavior**
Website to be UP

**Info**
- Uptime Kuma Version: 1.5.3
- Using Docker?: Yes
- OS: Ubuntu 20.04
- Browser: Firefox 91

**Error Log**
Where ?

**Comment by louislam** [comment]
Nothing to do in our side. Uptime Kuma is just a normal application that make http requests. Should be your docker network or proxy server problems.

You can test the network inside the container with this cmd.
```
docker exec -ti uptime-kuma sh
```

**Comment by pronyma2097** [comment]
Network seems to be fine, I'm able to curl any websites inside uptime-kuma container.

**Comment by pronyma2097** [comment]
I have the same problem with non-docker installation.
I set the npm proxy config for the setup instruction ---> OK.
Then I tried both commands :
- https_proxy=http://10.xxx.xxx.xxx:3128 node server/server.js ---> Set a monitor --> Request failed with status code 501.
- HTTPS_PROXY=http://10.xxx.xxx.xxx:3128 node server/server.js ---> Set a monitor --> Request failed with status code 501.

I googled proxy problem with node apps, it seems it has to be handled inside the application code to work.

**Comment by louislam** [comment]
It may be a bug of axios.
https://github.com/axios/axios/issues/3384

And Uptime Kuma is also using Socket (TCP/UDP) and call system's ping command. I think these connections will not go through http proxy.

**Comment by louislam** [comment]
Someone said, add `proxy: false` can fix the problem. 

You could try to add this in line 120.

https://github.com/louislam/uptime-kuma/blob/331ae5ec20623cc3290385267ebadc6d008ba2a2/server/model/monitor.js#L119-L124

**Comment by louislam** [comment]
```
HTTPS_PROXY=http://10.xxx.xxx.xxx:3128
```

I never use these proxy env vars before, `HTTPS` with `http://` is correct?

If yes, I would say Uptime Kuma is not supported http proxy officially.

**Comment by pronyma2097** [comment]
Yes this is correct, https request are going through a http corporate proxy...
I will try to find answers on axios side.

**Comment by pronyma2097** [comment]
I was able to solve my problem by doing this :
```
axios = require('axios');
const HttpsProxyAgent = require('https-proxy-agent');

const agent = new HttpsProxyAgent({host: '10.xxx.xxx.xxx', port: '3128'});

axios = axios.create({
    httpsAgent: agent
});

axios.get('https://www.google.fr/')
.then((response) => {
  console.log('response: ' + JSON.stringify(response.data));
}, (error) => {
  console.log('error: ' + error);
  process.exit(1);
});
```
But I'm not sure how it could be done in uptime-kuma, because we already have an httpsAgent (line 126), and users still want to user uptime-kuma without proxy.

**Comment by louislam** [comment]
I think it is impossible to add another https agent, as it is used already.

If you don't need the check certificate feature and ignore tls feature. You can build your fork with httpsproxyagent. 

https://github.com/louislam/uptime-kuma/blob/331ae5ec20623cc3290385267ebadc6d008ba2a2/server/model/monitor.js#L125-L128

**Comment by pronyma2097** [comment]
I'll do that, I'll fork later when i have the time.

Thank you.

**Comment by majorgear** [comment]
> variable https_proxy.

Can you explain how to do this when running UK in a docker container? Do create environment variable "https_proxy" and set it to false? 

i.e. in docker compose file
```
environment : 
  - https_proxy='false'
``` 
?
