### ISSUE TITLE
DNS - timeout A,CNAME,TXT,PTR queries

### ISSUE THREAD

**Issue by xzivzs** [louislam/uptime-kuma#3572]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

Hey there,

Configuration :
--------------------------
I have a bind9 docker DNS servers on 2 different hosts machine :

ns1.mydomain.com - 192.168.20.21
ns2.mydomain.com - 192.168.20.22

I also have a ubuntu server for testing purposes
ubnt-srv-test.mydomain.com - 192.168.20.23

uptime-kuma is installed as a docker container on the same host as ns2.mydomain.com.
--------------------------

I first setup uptime-kuma on my ubuntu test servers before deploying to my production env. Everything was working fine, I created 2 monitors for DNS A queries from 192.168.20.21 and 192.168.20.22.

Now I did deploy uptime-kuma as a docker container on the same ubuntu server as "ns2.mydomain.com ; 192.158.20.22", I can do a DNS monitor for ns1.mydomain.com (192.168.20.21) just fine but when I create a DNS monitor for ns2.mydomain.com so to the same host machine ( 192.168.20.22 ) Im getting "Failing: queryA ETIMEOUT ns2.home.vsl-it.net | Interval: 60 seconds | Type: dns | Down Count: 0 | Resend Interval: 0" . 

For testing I did move the docker container of uptime-kuma to the same host server as "ns1.mydomain.com" and now the problem is the opposite, I can now query ns2.mydomain.com just fine but ns1.mydomain.com ( so the same server now as uptime-kuma) , gives me "Failing queryA TIMEOUT". 

Finally, I move uptime-kuma back to my ubuntu TEST server ( 192.168.20.23 )  and now both ns1.mydomain.com and ns2.mydomain.com DNS monitors are being queried  properly.

What am I missing here ? it looks like uptime-kuma cannot monitor DNS when the DNS server is on the same host as uptime-kuma .

Cheers,

### 🐻 Uptime-Kuma Version

1.22.1

### 💻 Operating System and Arch

docker

### 🌐 Browser

chrome and firefox

### 🐋 Docker Version

24.0.5

**Comment by chakflying** [comment]
Not sure how you are running your DNS server but have you checked this?

https://forums.docker.com/t/dns-issues-with-local-resolver-and-containers-on-the-same-host/102319/9

**Comment by xzivzs** [comment]
both dns servers ns1.mydomain.com and ns2.mydomain.com are working fine in my environment. I can query internal / external with both ns1 and ns2, I also setup a reverse lookup dns on both. I also use "docker exec" to get inside uptime-kuma container and there I could ping and dig internal / external dns queries from both ns1 and ns2 so I don't think the issue is from my dns servers. 
I'm wondering why I can monitor DNS on both ns1 and ns2 when uptime-kuma container is setup on an other host machine whereas as soon as uptime-kuma container is setup on the same host as ns2 then it can't monitor it but can do with ns1 and also, if uptime-kuma is setup on the same host as ns1, so then it can monitor ns2 but not ns1 anymore ?
