### ISSUE TITLE
PAUSED Sensor will not been shown in /metrics page

### ISSUE THREAD

**Issue by RK62** [louislam/uptime-kuma#3579]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### Description

Sensors that are on PAUSE are not listed on the /metrics page under "monitor_status".
States MAINTENANCE, UP and DOWN are always complete. 
The sensor type does not matter.
The number on the "QuickStats" page is also correct.

If you set a group to pause, QuickStats will show the correct number including the underlying sensors, but the /metrics page will show them as UP.

### 👟 Reproduction steps

Set sensors to State PAUSE and call /metrics page
The call of the /metric page was authorised by API-KEY.

### 👀 Expected behavior

The State / Counter of QuickStats und /Metrices page should be the same.

### 😓 Actual Behavior

The Information of sensors and /metric page differs.

### 🐻 Uptime-Kuma Version

1.22.1

### 💻 Operating System and Arch

Docker: louislam/uptime-kuma:1.22.1

### 🌐 Browser

Edge

### 🐋 Docker Version

20.10.25

**Comment by chakflying** [comment]
I believe it's by design, metrics is not supposed to show stale data.

https://serverfault.com/questions/1005300/do-prometheus-metrics-have-some-sort-of-freshness-lifetime

**Comment by RK62** [comment]
After prolonged observation, this is probably not a mistake:

1. PENDING describes a coming error and not paused sensors. PAUSED sensors are not in the output.

2. UP sensors with type PUSH will only be shown when a push message has been received for the first time after a restart/reboot of Uptime Kuma.

It would be very useful to be able to retrieve a JSON with all current monitor values.
Please switch to "feature-request".

**Comment by CommanderStorm** [comment]
We already have the following APIs. Do they solve your usecase?

- `https://status.yourdomain.xyz/api/status-page/your-status-page-name`
- `https://status.yourdomain.xyz/api/status-page/heartbeat/your-status-page-name`

**Comment by CommanderStorm** [comment]
@RK62 
Also note that depending on what you are requesting (your `feature-request` is not clear)  this is likely a duplicate of https://github.com/louislam/uptime-kuma/issues/1928
If you agree, could you please close this Issue, as duplicates only create immortal zombies and are really hard to issue-manage?
If not, what makes this issue unique enough to require an additional issue? (Could this be integrated into the issue linked above?) ^^

**Comment by RK62** [comment]
Continued in [#1928](https://github.com/louislam/uptime-kuma/issues/1928)
