### ISSUE TITLE
The sizes of these beats look different

### ISSUE THREAD

**Issue by Eronana** [louislam/uptime-kuma#358]
**Describe the bug**
The sizes of these beats look different, it's so weird.
![image](https://user-images.githubusercontent.com/9164153/132500451-d7c68085-f6f0-4102-875d-95255b118dc7.png)

**Expected behavior**
They should have the same size.

**Info**
- Uptime Kuma Version: latest
- Using Docker?: Yes
- OS: MacOS
- Browser: Chrome and Safari

**Comment by louislam** [comment]
Duplicate of #326
