### ISSUE TITLE
Make StatusPageList Public

### ISSUE THREAD

**Issue by fr4nc1stein** [louislam/uptime-kuma#3580]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

Im editing the code and redesigning the Status Page, id like to put another status page under the status page.

In the following image below, I edit the code but its static button
Id like to ask a help on how I can reproduce the list of status pages and put it on the active status page.

<img width="1369" alt="Screenshot 2023-08-16 at 6 34 36 AM" src="https://github.com/louislam/uptime-kuma/assets/13563755/90bd2873-1eaf-40ac-b075-0226a9c90bb1">

I  saw the statusPageList in the code however its available on authenticated users.

### 🐻 Uptime-Kuma Version

1.23.0-beta.1

### 💻 Operating System and Arch

Mac M2 2022

### 🌐 Browser

Google Chrome

**Comment by CommanderStorm** [comment]
> Id like to ask a help on how I can reproduce the list of status pages and put it on the active status page

I don't quite understand what you mean. What do you need help reproducing?

I would currently suggest that these links could be put in the description of the status page or all status pages being merged into one.
⇒ Currently, the feature to list other status pages from one status page does not exist.

**Comment by fr4nc1stein** [comment]
Yes, the feature to list other status pages from one page does not exist.

Id like to edit the code, do we have a feature request on this?

**Comment by CommanderStorm** [comment]
> do we have a feature request on this

I was unable to find such an issue.
Please run a duplication search too: https://github.com/louislam/uptime-kuma/issues?q=is%3Aissue+is%3Aopen+status+page+

> Id like to edit the code

Here is our contribution/development guide: https://github.com/louislam/uptime-kuma/blob/master/CONTRIBUTING.md
