### ISSUE TITLE
Import monitors via CSV file

### ISSUE THREAD

**Issue by kayvanaarssen** [louislam/uptime-kuma#3581]
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

UI Feature

### 🔖 Feature description

Make an option to import monitors via an CSV file.
Also provide an example.csv file for all the fields that can be used or a help page. With more information.
When moving from another service this will be very helpfull.
And also if you have multiple local things or things you want monitor. And import can save a lot of time / clicking around.

### ✔️ Solution

Import monitors from CSV file

### 📝 Additional Context

There are multiple requests on this, mostly to import from other services.

**Comment by CommanderStorm** [comment]
I think this is a duplicate of https://github.com/louislam/uptime-kuma/issues/1190 https://github.com/louislam/uptime-kuma/issues/2297
If you agree, could you please close this Issue, as duplicates only create immortal zombies and are really hard to issue-manage?
If not, what makes this issue unique enough to require an additional issue? (Could this be integrated into the issue linked above?) ^^

**Comment by kayvanaarssen** [comment]
Well, yes and no. It specifies the import from UptimeRobot.
And more specified to bulk add. But what we need is import via .csv and a demo file.
So i'll let you be the judge of it.
Think its a really needed / missing feature.

**Comment by CommanderStorm** [comment]
I don't see a difference between importing a CSV file and importing a CSV file.

**Comment by kayvanaarssen** [comment]
> #2297

Right, sorry i overlooked the details in: https://github.com/louislam/uptime-kuma/issues/1190 hope this feature will make it into uptime-kuma soon. Closing the issue!

**Comment by gshershov** [comment]
up, it is actual in 2+ releases of Uptime Kuma
