### ISSUE TITLE
Option to click on the Down nodes and list them separately

### ISSUE THREAD

**Issue by petercharleston** [louislam/uptime-kuma#3584]
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

Other

### 🔖 Feature description

Hi everyone,

when we have a node or nodes down, these are listed in the Dashboard page under the heading Down.
To then located the nodes down we need to scroll through the left hand side of page to find the monitor in Red.
Can there be a feautre to click on the 'Down' list and view all the down nodes separately?
![image](https://github.com/louislam/uptime-kuma/assets/44698386/6b716c2e-79e8-47db-8f9b-15ed99eec0fb)

### ✔️ Solution

Hi everyone,

when we have a node or nodes down, these are listed in the Dashboard page under the heading Down.
To then located the nodes down we need to scroll through the left hand side of page to find the monitor in Red.
Can there be a feautre to click on the 'Down' list and view all the down nodes separately?
![image](https://github.com/louislam/uptime-kuma/assets/44698386/6b716c2e-79e8-47db-8f9b-15ed99eec0fb)

**Comment by CommanderStorm** [comment]
Have you tried the filtering menu added by #3312 into [`1.23`](https://github.com/louislam/uptime-kuma/releases)?
I think the filtering menu already allows for this functionality
⇒ Is this issue resolved?

**Comment by CommanderStorm** [comment]
> Thanks, 3312 looks good

Closing as resolved
