### ISSUE TITLE
Grace Time Period for the Push monitor?

### ISSUE THREAD

**Issue by NoLooseEnds** [louislam/uptime-kuma#3590]
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

Other

### 🔖 Feature description

Add the possibility of a Grace Time Period for the Push monitor – also prefferable to be able to add hours/days – and not only seconds.

### ✔️ Solution

Same as healthchecks.io?

<img width="648" alt="image" src="https://github.com/louislam/uptime-kuma/assets/4103531/9bd3b6e0-2be9-4fcb-89ca-b29335066bea">

**Comment by chakflying** [comment]
I have not used healthchecks.io, but from the screenshot I can say that the push monitor here works a bit differently. We don't have a concept of "expected period". Instead you can just set the monitor interval to "expected period + grace period" and it should work the same way.

**Comment by NoLooseEnds** [comment]
Oh, okay. So if I want it to check in once a week (ie. a backup script running once a week) I set the monitor intervall seconds to `604800`?

**Comment by NoLooseEnds** [comment]
But the timer "resets" when it checks in (i.e when you visit the URL)?

**Comment by chakflying** [comment]
Timer is reset when url is visited.

**Comment by NoLooseEnds** [comment]
Great! Appreciate the help! :)
