### ISSUE TITLE
Filtered dashboard lists monitors multiple times.

### ISSUE THREAD

**Issue by derekoharrow** [louislam/uptime-kuma#3592]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### Description

I have a monitor that is down, and this is under a nested group ("the lounge" under "Everything->Media")

If I have the view unfiltered, the default, then everything shows as expected.

If I filter for "down" monitors, then it seems to list everything multiple times. In this case, under "Everything", under "Everything / Media" and under "Everything / Media / thelounge".

Also, when filtered, instead of showing the monitor name on its own, it shows all the groups above it - e.g. instead of "the lounge" it says "Everything / Media / thelounge" which makes it very difficult to read.

Originally posted by @derekoharrow in https://github.com/louislam/uptime-kuma/pull/3312#issuecomment-1682481029

### 👟 Reproduction steps

Put monitors into groups and sub-groups. "Down" one of the monitors and then filter on Down monitors.

### 👀 Expected behavior

Should only list each monitor once.
Should only list individual monitor name, not hierarcy.

### 😓 Actual Behavior

Lists monitors multiple times when filtered by status.
When filtered, shows full hierarchy for monitors instead of just monitor name.

### 🐻 Uptime-Kuma Version

1.23.0

### 💻 Operating System and Arch

Ubuntu 22.04.2 LTS

### 🌐 Browser

Chrome, Edge

### 🐋 Docker Version

Docker version 20.10.18, build b40c2f6

**Comment by CommanderStorm** [comment]
@derekoharrow 
I think this is a duplicate of https://github.com/louislam/uptime-kuma/issues/3533
If you agree, could you please close this Issue, as duplicates only create immortal zombies and are really hard to issue-manage?
If not, what makes this issue unique enough to require an additional issue? (Could this be integrated into the issue linked above?) ^^
