### ISSUE TITLE
How can I figure out the monitorID

### ISSUE THREAD

**Issue by gs97ahn** [louislam/uptime-kuma#3597]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

As featured in [PR#1119](https://github.com/louislam/uptime-kuma/pull/1119), uptime badge became available.

However, I'm not sure how I can figure out the `monitorID` for an ongoing monitoring.

### 🐻 Uptime-Kuma Version

1.23.0

### 💻 Operating System and Arch

Ubuntu 22.04

### 🌐 Browser

Google Chorme 115.0.5790.170

### 🐋 Docker Version

20.10.24

**Comment by CommanderStorm** [comment]
The id you are searching for is this one:
![image](https://github.com/louislam/uptime-kuma/assets/26258709/53b67bf2-402c-4cc5-9a54-46d3a7e8d3bf)

Note that there also is a badge-generator hidden here on the status page:
![image](https://github.com/louislam/uptime-kuma/assets/26258709/a87a4e5a-e51e-43d0-b0a9-a6117df01275)
![image](https://github.com/louislam/uptime-kuma/assets/26258709/ffc5a9a6-5fd3-4640-ba45-a615cabe59ed)

**Comment by gs97ahn** [comment]
Thank you for the answer
