### ISSUE TITLE
AWS SES (smtp) not working 

### ISSUE THREAD

**Issue by shardharma** [louislam/uptime-kuma#360]
Hi,

We have configured the AWS SES (Smtp) for email notification it's not working, tried with port 587, 465, 25 but no luck. 

Any input here.  
![smpt_587](https://user-images.githubusercontent.com/59441855/132633003-3ed12cd3-3a28-40e0-93c0-15e6fd2b56ab.PNG)
![smtp_465](https://user-images.githubusercontent.com/59441855/132633013-e72cac6c-29c8-4cf0-800a-801684a1a5d0.PNG)

**Comment by chakflying** [comment]
Did you try with "Secure" unchecked?

**Comment by shardharma** [comment]
yes, but no luck

**Comment by louislam** [comment]
any error msg?

**Comment by shardharma** [comment]
I can't see any error in AWS ECS we have hosted the tool in AWS Farget.  only monitoring log on ping and URL reporting to CloudWatch log groups.

**Comment by louislam** [comment]
After clicked the "Test" button, there should be a error msg in bottom right.

![image](https://user-images.githubusercontent.com/1336778/132647598-41cda81d-8de6-4ebb-afec-469b10860d24.png)

**Comment by shardharma** [comment]
Hi louislam,

Here is the test screenshot for your reference. 
![New](https://user-images.githubusercontent.com/59441855/132648718-5d781ddd-6378-4122-a53e-bfac697a8ced.JPG)

Just for your update, we have tested slack integration it's working fine.

**Comment by louislam** [comment]
So there is no error msg in the bottom right corner?  The red box.

**Comment by shardharma** [comment]
No error

**Comment by louislam** [comment]
Um, should be something show up whether is success or not.

After clicked "Test" button, did you see "Sent Successfully"?

If nothing show up, try smtppro.zoho.com 465 with random username/password

![image](https://user-images.githubusercontent.com/1336778/132650280-98e4d63d-48b1-4b99-b29c-8dce83cdc9e9.png)

**Comment by shardharma** [comment]
Thank louislam,

I can see the connection time out error in SMTP configuration, it looks like the issues with the network level. 

<img width="875" alt="new error" src="https://user-images.githubusercontent.com/59441855/132659533-208796c0-4606-4a2b-8c9a-511b4247f87a.png">

**Comment by shardharma** [comment]
We have tried Gmail but still, it is blocked somewhere,
The same tool I have set up inside the windows desktop docker is running fine, tested the AWS SES, and Gmail working fine.  Will check this with our network team.
