### ISSUE TITLE
install.sh gives error on install option

### ISSUE THREAD

**Issue by ajnadox** [louislam/uptime-kuma#3600]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

https://github.com/louislam/uptime-kuma/wiki/%F0%9F%94%A7-How-to-Install
say use: curl -Lo kuma_install.sh https://git.kuma.pet/install.sh && sudo bash kuma_install.sh
but when selecting dock by just Enter or typing docker it throws you an error

### 📝 Error Message(s) or Log

Which installation method do you prefer? [DOCKER/local]: 
kuma_install.sh: line 192: docker: command not found
Error: docker is not found!

### 🐻 Uptime-Kuma Version

1.23.0

### 💻 Operating System and Arch

Ubuntu 22.04 x64

### 🌐 Browser

Chrome

**Comment by CommanderStorm** [comment]
Do you have docker installed?
If you don't, this installation path will fail for obvious reasons.
Installing docker is kind of out of scope for this installer imo, but maybe we can check if docker is installed and give a better error message.

**Comment by ajnadox** [comment]
yes sorry for my misstake in the error reporting, i was thinking that we could add like:
```
if [[ $(which docker) && $(docker --version) ]]; then
    echo "Update docker"
    docker update
  else
    echo "Install docker"
    #prerequisite
        sudo apt update && sudo apt install apt-transport-https ca-certificates curl software-properties-common -y
    #GPG key
        curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /usr/share/keyrings/docker-archive-    keyring.gpg
    #Docker repository to APT
        echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
    #install from the Docker repo
        sudo apt update && apt-cache policy docker-ce && sudo apt install docker-ce
fi
```
