### ISSUE TITLE
Please help me to disable this change that was a recent pull request via css

### ISSUE THREAD

**Issue by pallebone** [louislam/uptime-kuma#3602]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

This recent pull request:

https://github.com/louislam/uptime-kuma/pull/3219

has altered how my status page looks and added a time value like ‘12 minutes ago’ to the page. Unfortunately this is not compatible with a screen size of a monitoring device I use and while I am sure I am in the minority of who would like to turn it off, and dont have anything against it, would appreciate anyone can tell me in the css what to add to remove it. 

Many thabks in advance :)

kind regards
Peter

### 🐻 Uptime-Kuma Version

1.23.0

### 💻 Operating System and Arch

Docker

### 🌐 Browser

Safari

**Comment by CommanderStorm** [comment]
What you want is this setting (no custom css needed):
![image](https://github.com/louislam/uptime-kuma/assets/26258709/599878bc-9562-4b0f-8205-712cda07c989)

**Comment by CommanderStorm** [comment]
This issue is tracked in https://github.com/louislam/uptime-kuma/issues/3596
=> could you close this issue?

**Comment by pallebone** [comment]
Ok thank you. I guess I also have the same issue then where it still shows for me :)
