### ISSUE TITLE
1.23 - filter dropdown menus don't work on iOS

### ISSUE THREAD

**Issue by luckman212** [louislam/uptime-kuma#3618]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### Description

I know all attention is on 2.0.0 now, so it's ok if this is not applicable anymore...

Just wanted to note that the new status/tag filter dropdown menus are non-functional on iOS (Safari) as far as I can tell. I cannot tap/click/activate them at all.

### 👟 Reproduction steps

open kuma on mobile Safari

try to click e.g. the Status filter bubble.

### 👀 Expected behavior

menu opens

### 😓 Actual Behavior

nothing happens

### 🐻 Uptime-Kuma Version

1.23.0

### 💻 Operating System and Arch

ubuntu 20 / Docker

### 🌐 Browser

Mobile Safari - iOS 16

**Comment by rezzorix** [comment]
Can confirm the same for ios 16.6 with mobile firefox (which technically is safari, too)

**Comment by CommanderStorm** [comment]
What do you mean exactly by don't work?
Do you by any chance mean https://github.com/louislam/uptime-kuma/pull/3607?

Is there something written in the log? (if you/somebody else has a mac)

**Comment by CommanderStorm** [comment]
I forgot to comment on this:

> I know all attention is on 2.0.0 now, so it's ok if this is not applicable anymore...

There still will be a patch-release as always (see the [`1.23.1`-milestone](https://github.com/louislam/uptime-kuma/milestone/36)), before https://github.com/louislam/uptime-kuma/pull/2720 can be merged into master
=> work shifts to the [´2.0.0´-milestone](https://github.com/louislam/uptime-kuma/milestone/24) 😉

PRs from those with Apple devices welcome. I don't know if this is testable any other way.

**Comment by louislam** [comment]
Yes, I just update the changelog a bit:

> Update: The last minor version (`1.23.x`) means that there won't be any new features introduced in v1. However, bug fixes will still be provided. You can expect to see `1.23.1`, `1.23.2` and so on.

**Comment by luckman212** [comment]
> What do you mean exactly by don't work? (what button can't you click?)

These:

![image](https://github.com/louislam/uptime-kuma/assets/1992842/f53d7131-0cd0-404b-bca6-b82e91d60359)

> Do you by any chance mean https://github.com/louislam/uptime-kuma/pull/3607?

No - not related to that issue

> Is there something written in the log?

You mean the log of the uptime kuma instance? No. Mobile browser log? Maybe- I don't know how to access/view that. Maybe I have to browse it while my phone is in some kind of debug mode? I'll check.

**Comment by louislam** [comment]
Can reproduce on BrowserStack's iPhone device.

![image](https://github.com/louislam/uptime-kuma/assets/1336778/893a7793-f8a4-4c67-9a71-9681e96dbfdc)

**Comment by CommanderStorm** [comment]
using ios (BrowserStack):
the console  => no relevant errors.

macos ventura - firefox 115:
![image](https://github.com/louislam/uptime-kuma/assets/26258709/cb7a37d6-290f-4aa5-ac2f-3220d2143147)

**Comment by CommanderStorm** [comment]
Seems to be a "feature" of safari ios: https://itnext.io/fixing-focus-for-safari-b5916fef1064

**Comment by luckman212** [comment]
I have no idea but I searched a little and found a simple playground on MDN, I added some logging to it and a button, seems to work on my phone...

https://developer.mozilla.org/en-US/play?id=tDaotaNvwKc33Vt8CDIuJb4fHLbgP57V1C4Lq2rpXUqN09I7fORDXtCdduhIKjW%2BnV32mnArodGEGyJW

**Comment by CommanderStorm** [comment]
Idk, about your example. The following does not work:

https://play.vuejs.org/#eNqNkk1PAjEQhv/KpBcgQThwI2D8CCZ6EKPerAdYBijutk07Rcxm/7uz7YIfIehptzPP++btTEtxaW1vG1AMxchnTlkCjxTsudSqsMYRlA6XFSydKaDFYEtqqTOjPYFxC3QwBgbaL68dqUf9ZMFiPhAWNp8R8glgVDvyZ6G2cLE0WfBKj6WIFj0b/LrdaqpnjLQ6UjSYCXSM4/IejMZsPQ9ERgN9WGRFOh26ADe1DBgoEJQGFje6fkJTvj7X019j90fYOen/hd2Dx+P9Ctd0Y6Af6dIUp3Hwyg+hLJstVFU9/sPIRVeQ5y0t1aq38UbzestaKUVmCqtydFNLircoBZukDFLM8ty838UauYDdfT1bY/Z2pL7xu7omxYNDj26LUhx6NHMrpNSePN3jjv8PzcIsQs70ieYjepOHOmPCroJecOxvXEx7Gx+p0qtnP9kRar+/VB20JqvIS8FP9/rE1b/iDnqDqJO6EtUnuoQLmw==

**Comment by luckman212** [comment]
I monkeyed around with the playground with some help from chatGPT. This version works on my iPhone, not sure if it can be adapted to Kuma

[source](https://play.vuejs.org/#eNqFkk1PAjEQhv/KpBc0UTDxZsD4EUz0IEa9WQ+wO0Bxt23aKWI2+9+dtoBoCJ7amXne6dtOG3FtbXcZUFyIvi+csgQeKdhLqVVtjSNowOEUWpg6U0OH0Y7UUhdGewLjSnQwiMTR2/ux1P1ebsJyDghrW40JOQLox568lGoJNJ4oXeJqIMWZFHA1NUXwHKR+XRv8/KiTckqfMt85jtCkCm4fYwJtoHQCnzEJREYDfVlkRY62VYC7KAMGagSlgcVrXS+j2WiP83m3bnfQ5oT0/zY30H5jf2ytq8nKL1/5IUfp7ZW/gKZZD6Jt4wR2Xl2cCPI8qqmadRfeaJ5yE7VSFKa2qkI3sqR4lFJwm+xCinFVmc+HlCMX8GSTL+ZYfOzJL/wq5qR4cujRLVGKbY3GboaUy8OXR1zxflusTRkqpg8Un9GbKkSPGbsJumTbO1xye5/+qtKzVz9cEWq/uVQ0Gsk28VLw/709cPUfu+fd86STuhXtN/jmDEk=)

```typescript
<script setup>
import { ref } from 'vue'

const order = ref([])
</script>

<template>
  <p>
  <div tabindex="0" @focus="order.push('focusin-div')" @blur="order.push('focusout-div')">
    <button type="button">
      Focus on me in div
    </button>
  </div>
  <button @focus="order.push('focusin-btn')" @blur="order.push('focusout-btn')" type="button">
    Focus on me in button
  </button>
  </p>
  Order is: {{ order }}
</template>
```

**Comment by CommanderStorm** [comment]
That is pretty trippy: The above button works on IOS and the below button works on chrome-linux

**Comment by CommanderStorm** [comment]
Should we add both `v-on`'s to the div and the button?
(That sounds like a horrible plan, but I don't have better ideas)

as in [this code](https://play.vuejs.org/#eNqtkk1vwjAMhv+KlQtDYjCJG4JpH2LSdhjTttuyA7QuhLVJlDisU9X/PqeljAPitJ5q+4n9+k0qcWvtcBdQTMTUJ05ZAo8U7LXUqrDGEVTgMIMaMmcK6DHak1rqxGhPYFyKDmaRuPj47Es9HbVN+DgHhIXNl4QcAUxjT+Bvmqod0HKldIrlTIorKeAmM0nwHDQdhzb4zUWvySl9uSLd60dolQd3ijGBOmg/g6esApHR/9cZ6MciM23fo0kADxEFHlYgKA17ohMyauNu+xGv3xoyah1ZNCYqP4Gq2jta19HKI/vEQJBnzzO1Hm690XxdVTwrRWIKq3J0C0uK70QKbtNOkmKZ5+b7qcmRCzjo8skGk68T+a0vY06KF4ce3Q6lONRo6dZIbXn+9owl/x+KhUlDzvSZ4it6k4eoscXugk5Z9hHXqH1sHp3S63c/Lwm175aKQiNZN7wU/BDvz6z+J3c8HDfnpK5F/QtYZvfD)?

**Comment by zluckytraveler** [comment]
> macos ventura - firefox 115 (I don't have macos-safari avalibale anymore. If somebody can verify safari as well, that would be appreciated)

@CommanderStorm 
I can confirm on MacOS Safari v16.5.2 that those dropdown menu filters are not working for me either.

https://github.com/louislam/uptime-kuma/assets/97180817/202d75f5-6f56-41e7-9eef-2d6c7cf959b9

**Comment by chakflying** [comment]
The reason `@focusin` and `@focusout` are on the `div` element is that we want the drop-down to be kept open when the user clicks on the drop-down items. In this case the toggle button itself may lose focus, but the `div` is still in focus.

As for how to fix this bug, I have no idea. I'll learn to use browserstack when I get some free time soon.
