### ISSUE TITLE
Can I support a custom status code or code returned by the interface

### ISSUE THREAD

**Issue by xiangshen123** [louislam/uptime-kuma#3621]
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

API

### 🔖 Feature description

Can I support a custom status code or code returned by the interface

### ✔️ Solution

Can I support a custom status code or code returned by the interface

**Comment by CommanderStorm** [comment]
What do you mean by 
> Can I support a custom status code or code returned by the interface

I think you wanted to choose the `help`-template.

**Comment by xiangshen123** [comment]
List as I visit a URL,He returns the following values，However, our service only supports returning status codes of 1-999
![image](https://github.com/louislam/uptime-kuma/assets/124766156/338e74f9-8e0a-47d7-8462-3002f2b7386b)

Can I customize the return value for the URL shown in the figure?

**Comment by CommanderStorm** [comment]
"0000" is [not a valid status code according to RFC 9110](https://httpwg.org/specs/rfc9110.html#status.code.extensibility) if you are refering to the actual status code.

However, your screenshot does NOT show an HTTP status code, instead you are showing `json`. If this is indeed valid `json`, please consider using the `json-query` monitor instead. If this is not valid `json`, please consider using the `keyword` monitor instead.


> Can I customize the return value for the URL shown in the figure?

I am unshure if you can customise the returned content of the url you are monitoring. (something might have been lost in translation, I don't understand what you mean)
