### ISSUE TITLE
Hi there, is the "Http(s) keyword" of the monitor type does not support Chinese?

### ISSUE THREAD

**Issue by Jim2757** [louislam/uptime-kuma#3622]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

Hi Team, I try to use the "Http(s) keyword" of the monitor type to monitor my website but some issue have arisen, is the program does not support Chinese？
![1](https://github.com/louislam/uptime-kuma/assets/112788102/04bae99d-b7c7-4d7b-95a2-a0114c018375)

### 🐻 Uptime-Kuma Version

lasted

### 💻 Operating System and Arch

docker in Ununtu 22.04

### 🌐 Browser

Chrome  116.0.5845.96

### 🐋 Docker Version

Docker version 24.0.4, build 3713ee1

**Comment by chakflying** [comment]
I'm guessing the target website is not encoded in UTF-8? We don't support encoding conversions currently.

**Comment by CommanderStorm** [comment]
This might be what the user in https://github.com/louislam/uptime-kuma/issues/3535 was refering to.

This might also be a duplicate of https://github.com/louislam/uptime-kuma/issues/3427

**Comment by Jim2757** [comment]
Yes@chakflying thanks,  it has been solved

**Comment by CommanderStorm** [comment]
> it has been solved

@Jim2757 If the issue is resolved, could you close it? ^^
(only you or Louis can close issues which are resolved)

**Comment by visualczm** [comment]
@Jim2757  你好,你是怎么做的。我的ping乱码
