### ISSUE TITLE
API keys and creating a monitor

### ISSUE THREAD

**Issue by anthonyra** [louislam/uptime-kuma#3625]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

It appears that the socket.io API can be used to create monitors. Based on the wrapper here <https://github.com/lucasheld/uptime-kuma-api/tree/master> however I'm not sure if this falls under the scope of what the API keys can authorize?

Since I'm not sure if the socket.io API is considered  one of the "secured HTTP APIs" as described in <https://github.com/louislam/uptime-kuma/wiki/API-Keys> or not...

I'm currently trying to install monitors with `ansible-pull` so the credentials could in theory be accessible on local storage of the host. I'd much rather it be the API key vs the admin user:password or JWT representing that same user.

### 🐻 Uptime-Kuma Version

1.23.0

### 💻 Operating System and Arch

Ubuntu 22.04.2 LTS

### 🌐 Browser

Mozilla Firefox 116.0.3 (64-bit)

### 🐋 Docker Version

not using docker

### 🟩 NodeJS Version

18.17.1

**Comment by Computroniks** [comment]
API keys currently only cover the Prometheus /metrics endpoint

**Comment by anthonyra** [comment]
Ahh is there a chance for there to be support on the socket.io side?
