### ISSUE TITLE
Maintenance mode and time zones problem

### ISSUE THREAD

**Issue by AndrewSpec** [louislam/uptime-kuma#3626]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### Description

There's a problem with maintanance mode and time zones (I think). After a fresh startup it's working fine. Next day it's ignoring the maintanance window.

![image](https://github.com/louislam/uptime-kuma/assets/274712/1559391c-6491-43bf-aa6f-2608eabc8d55)
When I'm posting this issue it should be in maintanance mode but it's not.

### 👟 Reproduction steps

Add a new maintanance task with UTC+2
Wait for that time.

### 👀 Expected behavior

In maintanance mode it should stop sending me notifications. But it's not entering maintanance mode.

### 😓 Actual Behavior

While it's time to fire the maintanance mode it's not doing it.

### 🐻 Uptime-Kuma Version

1.23.0

### 💻 Operating System and Arch

Debian 10

### 🌐 Browser

Brave 

### 🐋 Docker Version

Docker 24.0.2

**Comment by CommanderStorm** [comment]
- What is the maintenance window set to exactly? (what options are you using?)
- What exactly do you mean by `Add a new maintanance task with UTC+2` (How did you add a maintanance period with a timezone? what is the timezone of the server, uptime-kuma and the maintanance period)
- why do you think this is a timezone issue? (what timezone are you running in?)

**Comment by AndrewSpec** [comment]
> * What is the maintenance window set to exactly? (what options are you using?)
![image](https://github.com/louislam/uptime-kuma/assets/274712/32daa6a9-0983-4d5f-b01b-f134f75bcb24)

> * What exactly do you mean by `Add a new maintanance task with UTC+2` (How did you add a maintanance period with a timezone? what is the timezone of the server, uptime-kuma and the maintanance period)
> * why do you think this is a timezone issue? (what timezone are you running in?)
![image](https://github.com/louislam/uptime-kuma/assets/274712/6f93c7f7-909f-4574-bcb7-daba544f8758)
It was working fine from the beginning but after some time I changed the time zone to my real time zone and then it stopped working. In the changelog I noticed that there was some fixes for the time zone so I thought that this could solve my problem but not.

**Comment by louislam** [comment]
Cannot reproduce with 16:00 to 18:00. 

![image](https://github.com/louislam/uptime-kuma/assets/1336778/828ff479-90ef-4fe5-90ec-65a16c9e2de9)

**Comment by Besstheone** [comment]
Hello @louislam ,
I tested it with :
![image](https://github.com/louislam/uptime-kuma/assets/39663221/9caa76b1-65f2-44a2-b7bf-de26a33a6959)

and it started /stopped in less than 1 sec
![image](https://github.com/louislam/uptime-kuma/assets/39663221/3801fc3a-af9f-470a-acf5-21ea894f242e)
![image](https://github.com/louislam/uptime-kuma/assets/39663221/db53d8b0-bc44-49e5-9363-993499c4c73e)
![image](https://github.com/louislam/uptime-kuma/assets/39663221/576e5533-d594-4fd3-97ad-8e9497cd8bc8)

server time is the same as the last screenshot

**Comment by CommanderStorm** [comment]
https://github.com/louislam/uptime-kuma/issues/4634 does cover the same issue and has a deeper reproduction why this issue happens => closing as a "duplicate" (despite this beig first)
