### ISSUE TITLE
Solução para a de Status

### ISSUE THREAD

**Issue by gildasio719** [louislam/uptime-kuma#3627]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

In projects involving hundreds of monitors, it's crucial to recognize that monitoring efficiency is greatly enhanced by focusing solely on assets that have experienced downtime. Therefore, the optimal approach would be to place status 0, or rather the 'down' status, at the top of the status page.

### 🐻 Uptime-Kuma Version

1.23.0

### 💻 Operating System and Arch

Windows, linux

### 🌐 Browser

Google Chrome

**Comment by CommanderStorm** [comment]
No, this is currently not a feature.
I don't see the question in this issue. Did you mean to open a [`feature-request`](https://github.com/louislam/uptime-kuma/issues/new?assignees=&labels=feature-request&projects=&template=feature_request.yaml) for this?


If yes, please close this issue (editing tags is something only Louis can do) and include:
-  an english title which is descriptive of the issue
- why you need hundreds of monitors on a status page (more out ouf curiosity)
- references to the issues that implemented this feature for the dashboard view and how you think this should work on the status page side (what is controlled by the admin/public user, what is a rough layout of the UI).
  See https://github.com/louislam/uptime-kuma/issues/1585 and the PR implementing this feature https://github.com/louislam/uptime-kuma/pull/3312

⇒ how do you think this feature should work?

**Comment by chakflying** [comment]
Duplicate of #1936

**Comment by CommanderStorm** [comment]
@gildasio719 
If you agree, could you please close this Issue, as duplicates only create immortal zombies and are really hard to issue-manage?
If not, what makes this issue unique enough to require an additional issue? (Could this be integrated into the issue linked above?) ^^

**Comment by gildasio719** [comment]
Ok Thanks
