### ISSUE TITLE
The update to 1.23.0 has prevented effective monitoring of 630 hosts

### ISSUE THREAD

**Issue by szyszc** [louislam/uptime-kuma#3630]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

I'm monitoring around 630 hosts using Uptime Kuma, mostly with a frequency of 3600 seconds. Uptime Kuma is installed in a Ubuntu 22.04.2 CT container on ProxMox. Despite having so many hosts, it runs stably and is fairly responsive. I don't have any issues with configuring individual host settings, alerts, or analyzing their performance.

After updating to the latest version 1.23.0, I can't set any parameters for existing hosts. The configuration opens, but the fields appear empty. Additionally, I'm unable to add any new hosts for monitoring because some fields in the add-form don't seem to respond.

Is there any chance for a solution?

### 🐻 Uptime-Kuma Version

1.23.0

### 💻 Operating System and Arch

Ubuntu 22.04.2 LTS on CT container ProxMox

### 🌐 Browser

Firefox, MS Edge

**Comment by CommanderStorm** [comment]
- > I'm monitoring around 630 hosts 
  
  what monitor(s) are you using?
- >  I can't set any parameters
  
  You mean that you can't use the edit button, correct?
- What is your hardware setup? (slow IO?, NFS?)
- Are there any clues in the `Error Message(s) or Log` (both browser + container)
