### ISSUE TITLE
openssl TLS Certificate Expiry - custom protocol check - STUN / TURN server

### ISSUE THREAD

**Issue by ebricca** [louislam/uptime-kuma#3631]
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

New Monitor

### 🔖 Feature description

implement a monitor that does just an openssl TLS Certificate Expiry check - for custom protocols / on custom ports

### ✔️ Solution

openssl s_client $starttls $starttls_proto -servername "$domain" -verify_hostname "$domain" -connect "$host":"$port" $tls_version $s_client_options 

### ❓ Alternatives

more complex - fully monitor STUN / TURN 
https://icetest.info

### 📝 Additional Context

We have been monitoring the certificate expiry of our STUN / TURN server - via:
https://github.com/selivan/https-ssl-cert-check-zabbix/blob/master/ssl_cert_check.sh

https://ourcodeworld.com/articles/read/1526/how-to-test-online-whether-a-stun-turn-server-is-working-properly-or-not

**Comment by CommanderStorm** [comment]
I think this is a duplicate of https://github.com/louislam/uptime-kuma/issues/1079
If you agree, could you please close this Issue, as duplicates only create immortal zombies and are really hard to issue-manage or rewrite the description+title it to make distinct:
- For example reducing this to a `STUN / TURN (VOIP) server monitor`
- including what makes this different from #1079 => why this cannot be integrated there

**Comment by ebricca** [comment]
thanks - you are right - i must have been blind 
- full stun/turn monitoring is possibly better done with a script via push / out of scope
custom port tls check as proposed in #1979 would fit .. thus closing
