### ISSUE TITLE
Custom Body Webhooks does not fill template variables

### ISSUE THREAD

**Issue by Blumlaut** [louislam/uptime-kuma#3635]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### Description

Hi, i'm attempting to use the "Custom Body" feature to send a custom Discord Webhook, however it seems like the template variables (except for `msg`) are not filled properly and instead come out empty

### 👟 Reproduction steps

Create a new Notification and select > Webhook > Custom Body and enter the following minimal repro:

```json
{
    "username": "Uptime Kuma",
    "content": "test {{ monitorJSON['name'] }}",
    "embeds": [{
        "title": "Service {{ monitorJSON['name'] }} is {{heartbeatJSON['status']}}!",
        "color": 5174599,
        "footer": {
          "text": "test"
        },
        "fields": [
          {
            "name": "Field Name",
            "value": "Field Value"
          }
        ]
    }]
}
```

Toggle on `Additional headers` and fill it with:
```json
{ "Content-Type": "application/json" }
```

Then click "Test".
Result:
![grafik](https://github.com/louislam/uptime-kuma/assets/13604413/85fa79c6-f2b3-492d-9a93-b6cbfa67a9bd)

### 👀 Expected behavior

Template Variables should be filled properly.

### 😓 Actual Behavior

Template Variables are not filled and instead come out empty.

### 🐻 Uptime-Kuma Version

1.23.0

### 💻 Operating System and Arch

Debian Bullseye x64

### 🌐 Browser

Firefox 116.0.3

### 🐋 Docker Version

N/A

### 🟩 NodeJS Version

v18.17.0

### 📝 Relevant log output

```shell
N/A, Nothing is logged.
```

**Comment by CommanderStorm** [comment]
Are you maybe using a fork?
Note, I don't see any templating or custom Body in either https://github.com/louislam/uptime-kuma/blob/eee9a1f004c67c850b6d9b3342124f61c3ba0d4e/server/notification-providers/discord.js#L73-#L75 or https://github.com/louislam/uptime-kuma/blob/eee9a1f004c67c850b6d9b3342124f61c3ba0d4e/server/notification-providers/discord.js#L108-#L110

⇒ what we allow is a prefix, but that is not templated.

If this filed were templated: `monitorJSON` and `heartbeatJSON` are not available for certificate expiry or testing messages (they are `null`)

**Comment by Blumlaut** [comment]
> Edit: I noticed you wrote you are using the webhook

Sorry for the confusion, yes, i'm using "Webhook" and am writing the request body myself.

**Comment by CommanderStorm** [comment]
Note that you have the full potential of https://liquidjs.com/index.html at your disposal
⇒ you can write templates that work for both `UP`/`DOWN` and cert-expiry/testing.

To test this, you can monitor, for example https://thiswebsitedowsnotexist.com/. Saving a notification triggers a heartbeat and the accompanying notification.

**Comment by Blumlaut** [comment]
Thanks! i'm looking at liquidjs' docs already and what i originally had in mind does work, closing this issue as not a bug.

**Comment by CommanderStorm** [comment]
Could you look if https://github.com/louislam/uptime-kuma/pull/3636 is clear in the messaging/ if the wording can be improved?
