### ISSUE TITLE
Modify message of an event or healthcheck

### ISSUE THREAD

**Issue by luisxkimo** [louislam/uptime-kuma#3639]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

Its possible modify the message of an event or healtcheck?

![image](https://github.com/louislam/uptime-kuma/assets/6990299/1a117d19-e652-4765-9390-54a70c89eb8c)

Case of use: add a link to an incident page stored on a git repository or a wiki

### 🐻 Uptime-Kuma Version

1.22.1

### 💻 Operating System and Arch

Debian 10.13

### 🌐 Browser

Edge Version 116.0.1938.54

### 🐋 Docker Version

1.7.1

### 🟩 NodeJS Version

16.20.2

**Comment by CommanderStorm** [comment]
> Its possible modify the message of an event or healtcheck

Currently, there is no Eazy way to modify this message.

You can
- build a custom image with a fix for this message installed or
- contribute a customisation option for this. See our contibution guide: https://github.com/louislam/uptime-kuma/blob/master/CONTRIBUTING.md
  I am uncertain if adding a link to an external page is generally usefull. Storing issues in a git repo seems kind of nieche, and not fully usefull given that the people wo can see this part of the UI are admins already...

PS: Docker 1.7 is absolutely ancient. My system has `24.0.5` installed. Please upgrade this part of your infrastucture ^^

**Comment by luisxkimo** [comment]
Hi @CommanderStorm ,

Thanks for you quick reply. I will investigate to add a PR to the project.

About docker engine, is the engine on the AKS cluster, so the container engine version is something managed by the service (containerd://1.7.1)

**Comment by CommanderStorm** [comment]
Note that docker and containerd are not the same thing. While differences are likely rare, if asked for a docker version, please state that you are using containerd
