### ISSUE TITLE
Discord + Email notification help

### ISSUE THREAD

**Issue by ImMaxUK** [louislam/uptime-kuma#364]
**Is it a duplicate question?**
Please search in Issues without filters: https://github.com/louislam/uptime-kuma/issues?q=

**Info**
Uptime Kuma Version: 1.5.3
Using Docker?: No
OS: Ubuntu 18.04
Browser: Firefox

Hello,
I have set up Discord webhook notifications, but for some reason, I don't seem to get them. I have the Retries set to 0, and once a monitor is offline, no notifications seem to be sent.
Does anyone know why this might be? (I also have emails setup, still no notification)

**Comment by xhweng-yy** [comment]
when save time ,can recieve notification,but other time ,cant
