### ISSUE TITLE
1.23.0 DNS record issues

### ISSUE THREAD

**Issue by awptechnologies** [louislam/uptime-kuma#3640]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### Description

After installing the latest version (1.23.0) Ping monitors where asking for reply from AAAA records. I use Pihole as my authoritive DNS server and i use dasmaq on opnsense as my internal DNS. Before with 1.22.1 i had no issues the query stayed on local dns and did not try to forward AAAA records to pihole.

### 👟 Reproduction steps

Just install 1.23.0

### 👀 Expected behavior

I expect the dns query for pings to stay local and not forward AAAA records to my edge DNS

### 😓 Actual Behavior

With 1.23.0 DNS records are forwarded to my edge DNS server with AAAA records. This is confusing because ipv6 is actually disabled through grub on my docker host.

### 🐻 Uptime-Kuma Version

1.23.0 Is the Problem. I downgraded to 1.22.1 to get rid of issue.

### 💻 Operating System and Arch

Debian 12

### 🌐 Browser

Edge

### 🐋 Docker Version

Docker version 24.0.5, build ced0996

**Comment by CommanderStorm** [comment]
- What do you mean exacty by `did not try to forward AAAA records`?
  What are the settings of both DNS-Servers respective records?
  Could you make this into a [Minimal, Reproducible Example](https://stackoverflow.com/help/minimal-reproducible-example)?
- You are using regular pings, right? (not `Tailscale ping`)?
- In 1.23 we added a different dns-caching layer. See https://github.com/louislam/uptime-kuma/issues/3371 Could that be the culprit of whatever difference you are seing?

**Comment by louislam** [comment]
I think it is related to `nscd`, you can disable it in the next version.

**Comment by awptechnologies** [comment]
This fixed it thank you! no longer forwarding AAAA records for ping with this setting off.
