### ISSUE TITLE
Enable status page certificate expiry badge for all HTTP(s) monitors

### ISSUE THREAD

**Issue by marvinruder** [louislam/uptime-kuma#3648]
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

UI Feature, Other

### 🔖 Feature description

For the monitor type “HTTP(s)”, a badge showing SSL certificate expiry information can be shown (added in #3357). Although the monitor types “HTTP(s) – Keyword” and “HTTP(s) – JSON Query” offer all the other features related to Certificate Expiry (e.g. notification, showing info on dashboard), the status page badge cannot be enabled for them at the moment.

### ✔️ Solution

Certificate Expiry badge can be added to status page for monitors of type “HTTP(s) – Keyword” and “HTTP(s) – JSON Query”.

**Comment by CommanderStorm** [comment]
https://github.com/louislam/uptime-kuma/pull/3649 was merged and is avaliable since the `1.23.3` release.
I think this issue was mistakenly left open
=> closing as resolved
