### ISSUE TITLE
how to customize notifiction

### ISSUE THREAD

**Issue by kugimiya530** [louislam/uptime-kuma#3653]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

fow now the if monitor the https or ping function

when server down the result will be

【XXXXXX】 
[🔴 Down]
Name:  Servername 
connect ETIMEDOUT 191.xx.xx.xx
Time (Asia/Taipei): 2023-08-28 09:40:02

how can i hide the ip address

i don't want to show that

### 📝 Error Message(s) or Log

none

### 🐻 Uptime-Kuma Version

1.23.0

### 💻 Operating System and Arch

Debian12

### 🌐 Browser

Doesn't matter

**Comment by lihexin88** [comment]
+1
I hope can customize the notifiction to add more server info

**Comment by CommanderStorm** [comment]
@lihexin88 
Please refrain from posting `+1` / requests for updates things on issues, as this makes issue-management harder.
Issues are for discussing **what needs to be done how by whom**.
[We use 👍🏻 on issues to prioritise work](https://github.com/louislam/uptime-kuma/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc), as always: [Pull Requests](https://github.com/louislam/uptime-kuma/blob/master/CONTRIBUTING.md) welcome.
