### ISSUE TITLE
Qnap Installation 

### ISSUE THREAD

**Issue by preynolds2** [louislam/uptime-kuma#3654]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

Can someone point me to a guide to install this on qnap?

Thanks 

### 🐻 Uptime-Kuma Version

Latest

### 💻 Operating System and Arch

Qnap

### 🌐 Browser

Qnap

**Comment by louislam** [comment]
You should be able to install Docker on your Qnap. After installed Docker, come back this repo and follow the README.md.

**Comment by preynolds2** [comment]
Thanks
