### ISSUE TITLE
Grouping view like in the settings page for the status pages.

### ISSUE THREAD

**Issue by gsg-git** [louislam/uptime-kuma#3656]
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

UI Feature

### 🔖 Feature description

Grouping view like in the settings page for the status pages.

### ✔️ Solution

![grafik](https://github.com/louislam/uptime-kuma/assets/92863111/ddea6c05-06d7-4593-b424-e2653bc98817)
made an illustration

**Comment by CommanderStorm** [comment]
@gsg-git 
I think this is a duplicate of https://github.com/louislam/uptime-kuma/issues/3324 or (https://github.com/louislam/uptime-kuma/issues/2596 / https://github.com/louislam/uptime-kuma/issues/2597 )
If you agree, could you please close this Issue, as duplicates only create immortal zombies and are really hard to issue-manage?
If not, what makes this issue unique enough to require an additional issue? (Could this be integrated into the issue linked above?) ^^

**Comment by CommanderStorm** [comment]
@gsg-git ?

**Comment by gsg-git** [comment]
Yeah its okay - i think the demand of grouping view has aleready been communicated.

**Comment by baxenko** [comment]
I installed Kuma today and I don't see the option to display groupings in the status bar either. Is it possible to make a tree-like view like in the dashboard?

**Comment by CommanderStorm** [comment]
No, this is currently not possible, please refer to duplicates of this issue https://github.com/louislam/uptime-kuma/issues/3324 or (https://github.com/louislam/uptime-kuma/issues/2596 / https://github.com/louislam/uptime-kuma/issues/2597)

If you'd like to contribute such a feature, here is our [contribution guide](https://github.com/louislam/uptime-kuma/blob/master/CONTRIBUTING.md) ^^
