### ISSUE TITLE
How to create a docker image by using source code?

### ISSUE THREAD

**Issue by TomNewChao** [louislam/uptime-kuma#3658]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

How to create a docker image by using source code? Is there any relevant guidance document here?

### 🐻 Uptime-Kuma Version

master

### 💻 Operating System and Arch

centos8

### 🌐 Browser

google chrome

**Comment by louislam** [comment]
See https://github.com/louislam/uptime-kuma/blob/master/CONTRIBUTING.md

**Comment by TomNewChao** [comment]
When i see the package.json.  "npm run build && node ./extra/env2arg.js docker buildx build -f docker/dockerfile --platform linux/amd64 -t louislam/uptime-kuma1 --target release . --load" is work for me

**Comment by TomNewChao** [comment]
> See https://github.com/louislam/uptime-kuma/blob/master/CONTRIBUTING.md

Thanks

**Comment by Aj7Ay** [comment]
<img width="2048" alt="Screenshot 2024-04-03 at 11 53 20 AM" src="https://github.com/louislam/uptime-kuma/assets/110721907/a1774df7-09f6-4396-b050-386d59c6b01f">
while building the image 
facing the above issue from last two days 
container exited state after starting

**Comment by CommanderStorm** [comment]
@Aj7Ay I already answered you in https://github.com/louislam/uptime-kuma/issues/4645
Duplicate posts mean duplicate support effort..
