### ISSUE TITLE
NTFY notification garbled

### ISSUE THREAD

**Issue by ae5960e8-a6fc-491f-b252-898ecf59af95** [louislam/uptime-kuma#3662]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### Description

I've been using Uptime Kuma for years, and the NTFY notification has always been garbled and hard to read.

### 👟 Reproduction steps

Set up NTFY as standard

### 👀 Expected behavior

Uptime Kuma as on the NTFY website:
![image](https://github.com/louislam/uptime-kuma/assets/76442625/43db8776-4ef3-455c-a6ba-cfbdc7d271be)

### 😓 Actual Behavior

![0yrmy3v1mj1ucke9](https://github.com/louislam/uptime-kuma/assets/76442625/b9890703-7aec-4ae4-bbf1-9019d350dac9)

### 🐻 Uptime-Kuma Version

1.23.1

### 💻 Operating System and Arch

Alpinr Linux

### 🌐 Browser

Firefox 116.0.3-1

### 🐋 Docker Version

20.10.24

**Comment by louislam** [comment]
#3476

**Comment by CommanderStorm** [comment]
@ae5960e8-a6fc-491f-b252-898ecf59af95 do we have to improve the helptext further?
If yes, do you have any suggestions?
