### ISSUE TITLE
Uptime Kuma Windows Portable is recognized as a trojan virus by Avast

### ISSUE THREAD

**Issue by fedir-indutnyi** [louislam/uptime-kuma#3664]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### Description

I know this seems as a duplicate, but another antivirus - Avast is also reporting Uptime Kuma as a trojan

### 👟 Reproduction steps

Windows with Avast. Unzip Uptime Kuma Portable.

### 👀 Expected behavior

n/a

### 😓 Actual Behavior

Immediately alerting as a trojan by Avast

### 🐻 Uptime-Kuma Version

1.23.1

### 💻 Operating System and Arch

Windows

### 🌐 Browser

Chrome

### 🐋 Docker Version

n/a

### 🟩 NodeJS Version

portable inside bundle

**Comment by CommanderStorm** [comment]
There really is no way to fix this, as far as we know.
If you know how, we would be open to suggestions, but currently we are kind out of ideas.

See https://github.com/louislam/uptime-kuma/pull/3143

**Comment by fedir-indutnyi** [comment]
Thank you for fast reply. I think in this case solution would be to clone repo and use node installed locally - to play around with an application. Best Regards, Fedir

**Comment by louislam** [comment]
It seems that antivirus don't like Costura.Fody which is used for embedding all `dll` files into a single exe. After removed it, at least Avast don't complaint about this. But for `Gen:Variant.Tedy.411495`, I have no idea why.

https://github.com/louislam/uptime-kuma/commit/38f5f16dc7676427266c9be8971b870634868aa6

![](https://github.com/louislam/uptime-kuma/assets/1336778/5ce6244a-4b87-4d50-bc5d-23f5fa28634e)




Download:
https://github.com/louislam/uptime-kuma/releases/download/1.23.1/uptime-kuma-windows-x64-portable-1.23.1-2.zip
