### ISSUE TITLE
Field Request Timeout missing in "HTTP(s) - Json Query" type Monitor.

### ISSUE THREAD

**Issue by victorperez2911** [louislam/uptime-kuma#3666]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### Description

In a recent release, functionality to set a Request Timeout for Http monitoring was added.

Another newly added feature was the ability to create monitoring of the "Https JSON Query" type, and in this case, the TimeOut field of the Request is hidden.

I classified it as a bug, because I don't think it was a decision by design, it would be a bit annoying to have to duplicate a monitoring in order to have feedback both on the data returned by the request and the performance of the request simultaneously.

### 👟 Reproduction steps

1. Create New Monitoring on Uptime Kuma Main Page
2. Select the value "Http(s)" in the Monitor Type field.
3. Note that the "Request Timeout" field will be displayed for completion.
4. Without saving, change the value of the "Monitor Type" field to the "Http(s) JSON Query" option.
5. Note that the "Request Timeout" field disappears.

### 👀 Expected behavior

The expected behavior is that the "Request Timeout" field remains available even in a "HTTP(s) Json Query" type monitoring

### 😓 Actual Behavior

The current behavior is the impossibility of using in a monitoring "Http(s) JSON Query" the functionality of configuring a "Request TimeOut"

### 🐻 Uptime-Kuma Version

1.23.1

### 💻 Operating System and Arch

Docker Version

### 🌐 Browser

Edge

### 🐋 Docker Version

Docker

### 🟩 NodeJS Version

14

**Comment by CommanderStorm** [comment]
@victorperez2911 I think this issue is resolved and closing this has been forgotten, given that https://github.com/louislam/uptime-kuma/pull/3751 is merged.
Could you close this issue?
