### ISSUE TITLE
Questions regarding SSL Certificate chain validation.

### ISSUE THREAD

**Issue by robcarvaj** [louislam/uptime-kuma#3667]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

I've been looking at uptime kuma documentation and have not found an answer for this yet. Sorry if this is already answered, if it is please let me know where.

I'm looking to move from statuscake to uptime kuma and one of the key things I need to use it for is to monitor SSL certificates. I'm trying to find what checks Kuma does to confirm that the certificate chain is valid or not, but I have not found it. From the UI all that you can see is whether the certificate chain is valid or not and the expiration date, however, there's no explanation on how the cert chain is validated.

Below is a checklist of what statuscake offers in terms of SSL certificate validation. I need to understand which of these capabilities if any are already in Kuma or if any of this is planned to be added in the future.

- Certificate must not be expired: SSL Certificates expire after a certain length of time. An expired certificate will not be trusted and will show warnings to your visitors.

- Certificate must not be revoked: Certificates may be revoked by their authority if it has been compromised, the authority has been compromised, or a newer certificate was generated. Visitors will receive warnings if this is the case.

- Certificate must not be broken: Certificates may be broken for a variety of reasons: They have expired, they are not served on the correct domain, ….

- Certificate must have a proper cipher suite: The cipher suite contains information on how communication will be encrypted. The better the cipher, the harder it is for a third party to decode it. Weak ciphers should be replaced, especially if passwords or financial transactions are involved.

- A current protocol must be used: A certificate is only as strong as its protocol. TLS1.2 is the current standard. TLS1.0 will be deprecated in 2018 and anything older should no longer be used.

- Perfect Forward Secrecy (PFS) should be enabled: PFS prevents encrypted traffic from being stored by a third party to be decrypted at a later stage. When this is enabled, a new random secret key gets generated with each sesssion.

- Page must not serve Mixed Content (MC): In order to display the padlock, the website must not load any content from an insecure source. This could be local, but could also be from external sources, such as CDN, video providers and more.

### 🐻 Uptime-Kuma Version

Version: 1.23.0

### 💻 Operating System and Arch

Linode

### 🌐 Browser

Chrome

**Comment by CommanderStorm** [comment]
Note that there are multiple features that handle this:
- cert notifications monitor the expiry aproaching a limit
   => they warn if a threshold is reached
- certificate expiry is based on the certificate being valid:
  - the CA of any cert in the chain is valid (i.e. not selfsigned/forged, unless the CA is manually registered)
  - not revoked
  - not broken

For all these things, we are using the build-in cert-validy mechanism in node.
See
- https://github.com/louislam/uptime-kuma/blob/64b97c0f29123ea7c23846b3acca94fe524dfc1c/server/util-server.js#L711
- https://axios-http.com/docs/res_schema
- https://nodejs.org/docs/latest-v14.x/api/tls.html (search for `tlsSocket.authorized`)

You can verify what is considered OK/Not ok by utilising https://badssl.com/ if you have concearns.


Note that improving this system is partially tracked in https://github.com/louislam/uptime-kuma/issues/3570 
⇒ If you want to implement this feature, here is our [contribution guide](https://github.com/louislam/uptime-kuma/blob/master/CONTRIBUTING.md)
Please note that for this feature, a discussion of the planned architecture would be recommended (Reason: certs are a security-critical part)

**Comment by chakflying** [comment]
Note that I think certificate revocation is not implemented by default in node.js. I think it would be nice to have but I have no experience in implementing this.

**Comment by CommanderStorm** [comment]
Ups. I was tripped up by there being an error message for this.

Yes, one would need to implement this, but I think the consensus in the community is that currently CRL is not useful/… https://github.com/nodejs/node/issues/16338
