### ISSUE TITLE
Econnfrefused for Signal Notification

### ISSUE THREAD

**Issue by skwzrd** [louislam/uptime-kuma#3669]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

- I have the latest `uptime-kuma` and `signal-cli-rest-api` versions both installed with docker.
- I successfully linked my signal device by scanning the qr code from `curl http://localhost:8080/v1/qrcodelink?device_name=signal-api --output $HOME/signal/signal_qr_code.png`
- I get a successful response from running `curl -X POST -H "Content-Type: application/json" 'http://localhost:8080/v2/send' -d '{"message": "Test via Signal API!", "number": "+NUMBER", "recipients": [ "+NUMBER" ]}'` amd I even get the message on my signal app.
- However, in the Uptime-Kuma interface, when I add the Signal notification with POST URL `http://localhost:8080/v2/send` I get a pop-up saying `Error: Error: connect ECONNREFUSED 127.0.0.1:8080`

![image](https://github.com/louislam/uptime-kuma/assets/39067332/592b24ea-ff0a-49ac-9d6b-c43c019aaf6e)

The uptime-kuma instance runs on the same server as the site. I did this in the past, on the same VPS, and it worked. So if running curl from the VPS works, it's strange that uptime-kuma does not.

### 📝 Error Message(s) or Log

Error: Error: connect ECONNREFUSED 127.0.0.1:8080

### 🐻 Uptime-Kuma Version

1.23.1

### 💻 Operating System and Arch

Ubuntu 22.04

### 🌐 Browser

LibreWolf

### 🐋 Docker Version

Docker version 24.0.5, build 24.0.5-0ubuntu1~22.04.1

### 🟩 NodeJS Version

n/a

**Comment by louislam** [comment]
You need to put both containers into a same network.

https://stackoverflow.com/questions/42385977/accessing-a-docker-container-from-another-container

**Comment by skwzrd** [comment]
@louislam

I don't recall doing that on the previous install I did 6 months ago, but I just gave that a shot. I have run,
```
sudo docker network create uptime_kuma_network
sudo docker network connect uptime_kuma_network e77588d929bc
sudo docker network connect uptime_kuma_network c0a70ce03240
sudo docker container restart e77588d929bc c0a70ce03240
```
, then refreshed the webpage, and I get the same error.

**Comment by chakflying** [comment]
I think using `localhost` would only work if you are using the `host` networking mode in docker. Have you tried using `<IP of the Signal container>:8080` instead?

**Comment by skwzrd** [comment]
@chakflying 

Thanks a ton!

I replaced the POST URL with the signal-api container's IPv4 address, `172.X.X.X,` gotten from `sudo docker network inspect uptime_kuma_network` and it works!

**Comment by kfeina** [comment]
Hello, 

You could use your docker container name 

http://signal-cli-rest-api:8080/v2/send
