### ISSUE TITLE
Link (URL parameter) to go to status page with filter preselected e.g. "Status=Down"

### ISSUE THREAD

**Issue by luckman212** [louislam/uptime-kuma#3671]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

Usually when I go to UptimeKuma it's to check on down monitors. So I end up clicking the little filter bubble, status -> down. It would be very handy to be able to "bookmark" that filter setting directly e.g. something like:

```
https://my-uptime-kuma?filter=true&status=down
```

I am sorry if there is already a request or PR for this functionality. I did some basic searching and couldn't find it, although it is somewhat a little bit similar to https://github.com/louislam/uptime-kuma/issues/2787.

Thank you 🙏 

### 🐻 Uptime-Kuma Version

1.23.1

### 💻 Operating System and Arch

Ubuntu 20

### 🌐 Browser

Chrome

**Comment by CommanderStorm** [comment]
I am unsure what your question is.
This functionality does not currently exist/ there are no open PRs/ issues as far as I know.

If you'd like to improve `uptime-kuma` in this area, here is our [contribution guide](https://github.com/louislam/uptime-kuma/blob/master/CONTRIBUTING.md).

Did you mean to choose `feature-request`? 
If yes: could you close this issue and open the correct template?
Rationale:
- `help` is autoclosed after a certain time
- only louis can change tags
- there are extra fields in the feature-request ^^

**Comment by luckman212** [comment]
Ok sorry I guess I opened w. the wrong template. I will close and re-open under FR

**Comment by luckman212** [comment]
https://github.com/louislam/uptime-kuma/issues/3672
