### ISSUE TITLE
gamedig update

### ISSUE THREAD

**Issue by sahara101** [louislam/uptime-kuma#3673]
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

New Monitor

### 🔖 Feature description

Add sonsostheforest to gamedig 

### ✔️ Solution

gamedig server missing game

### 📝 Additional Context

Hi, gamedig added sonsoftheforest, would love to have it as option in kuma as well.

Thanks!

**Comment by louislam** [comment]
Uptime Kuma always updates gamedig in the next release, but this game isn't released in their side yet, you have to wait.

https://github.com/gamedig/node-gamedig/blob/master/CHANGELOG.md

> To Be Released...
    Sons Of The Forest - Added support
    Red Dead Redemption 2 - RedM (2018) - Added support
