### ISSUE TITLE
Entries get duplicated when save button is clicked more than once

### ISSUE THREAD

**Issue by gi-yt** [louislam/uptime-kuma#3677]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### Description

Sometimes when save button is clicked more than once, large parts of the service list get duplicated as such:
![image](https://github.com/louislam/uptime-kuma/assets/73596856/d093c114-c764-40c5-a52e-bf95ad5bdca0)

### 👟 Reproduction steps

1) Add a service/incident to the status page
2) Click save button more than once
3) The entries are duplicated

### 👀 Expected behavior

Save button should not duplicate entries

### 😓 Actual Behavior

Save button duplicates entries

### 🐻 Uptime-Kuma Version

1.22.1

### 💻 Operating System and Arch

Debian 12/Docker

### 🌐 Browser

Firefox 116

**Comment by louislam** [comment]
How could you do that? Because the save button will be disabled after first click.

**Comment by Jaluanda** [comment]
I had similar issue, maybe because I monitored too much (about 150+ active monitor and front page items). The website or service kinda laggy so I pressed save button 2nd time and it got duplicated. Like this:
![image](https://github.com/louislam/uptime-kuma/assets/11334082/461b41cf-e3bf-4f17-998a-4775a30d5c64)

**Comment by gi-yt** [comment]
yeah I also have a lot of services and it basically only happens with that case
