### ISSUE TITLE
如何修改后台的默认路径，大家都是/dashboard，想修改这个路径如何修改

### ISSUE THREAD

**Issue by aigcpro** [louislam/uptime-kuma#3678]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

如何修改后台的默认路径，大家都是/dashboard，想修改这个路径如何修改

### 📝 Error Message(s) or Log

如何修改后台的默认路径，大家都是/dashboard，想修改这个路径如何修改

### 🐻 Uptime-Kuma Version

16.9.1

### 💻 Operating System and Arch

16.9.1

### 🌐 Browser

16.9.1

### 🐋 Docker Version

16.9.1

### 🟩 NodeJS Version

16.9.1

**Comment by Zaid-maker** [comment]
How is your every version is 16.9.1? You must have copy paste on every field.

**Comment by louislam** [comment]
You can't change the dashboard path.
