### ISSUE TITLE
[SETUP-DATABASE] db-config.json is not found or invalid

### ISSUE THREAD

**Issue by Zaid-maker** [louislam/uptime-kuma#3679]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### Description

Start getting this error on local device which is a fork repo and has all upstream commits but when i pull these changes and run neccessary commands and start the server with `node server/server.js` and get this Database warning.

### 👟 Reproduction steps

didn't find yet...

### 👀 Expected behavior

it should work i guess

### 😓 Actual Behavior

pulling changes from upstream repo(this one) and when try to start the server got this warning.

### 🐻 Uptime-Kuma Version

1.23.1

### 💻 Operating System and Arch

Windows 11 x64

### 🌐 Browser

Brave Browser Version 1.57.57 Chromium: 116.0.5845.163 (Official Build) (64-bit)

### 🟩 NodeJS Version

18.17.1

### 📝 Relevant log output

```shell
2023-09-02T22:56:00+05:00 [SETUP-DATABASE] INFO: db-config.json is not found or invalid: ENOENT: no such file or directory, open 'data\db-config.json'
2023-09-02T22:56:00+05:00 [SERVER] INFO: Connecting to the Database
2023-09-02T22:56:00+05:00 [DB] WARN: ENOENT: no such file or directory, open 'data\db-config.json'
```

**Comment by CommanderStorm** [comment]
- Why did you start the server using `node server/server.js`?
- I think you skipped the step. Have you made sure that all commands have been run?   
  see https://github.com/louislam/uptime-kuma/blob/master/CONTRIBUTING.md#install-dependencies-for-development

**Comment by louislam** [comment]
No negative effect.

`db-config.json` is used for determining MySQL or SQLite, it will pick up your sqlite database if there is no `db-config.json` but `kuma.db` exists.

Maybe I can generate `db-config.json` for such case, so you won't see such message next time.

**Comment by Zaid-maker** [comment]
> * Why did you start the server using `node server/server.js`?
> * I think you skipped the step. Have you made sure that all commands have been run?
>   see https://github.com/louislam/uptime-kuma/blob/master/CONTRIBUTING.md#install-dependencies-for-development

I always start the local dev server like that and never got any issue before!

**Comment by Zaid-maker** [comment]
> No negative effect.
> 
> `db-config.json` is used for determining MySQL or SQLite, it will pick up your sqlite database if there is no `db-config.json` but `kuma.db` exists.
> 
> Maybe I can generate `db-config.json` for such case, so you won't see such message next time.

Yeah that will help to not see the message

**Comment by Zaid-maker** [comment]
> * I think you skipped the step. Have you made sure that all commands have been run?
>   see https://github.com/louislam/uptime-kuma/blob/master/CONTRIBUTING.md#install-dependencies-for-development

I did that too still same message!

**Comment by Zaid-maker** [comment]
```bash
2023-09-03T22:20:35+05:00 [SETUP-DATABASE] INFO: db-config.json is not found or invalid: ENOENT: no such file or directory, open 'data\db-config.json'
2023-09-03T22:20:35+05:00 [SERVER] INFO: Connecting to the Database
2023-09-03T22:20:35+05:00 [DB] WARN: ENOENT: no such file or directory, open 'data\db-config.json'
2023-09-03T22:20:35+05:00 [DB] INFO: Database Type: sqlite
```

**Comment by kokofixcomputers** [comment]
> ```shell
> 2023-09-03T22:20:35+05:00 [SETUP-DATABASE] INFO: db-config.json is not found or invalid: ENOENT: no such file or directory, open 'data\db-config.json'
> 2023-09-03T22:20:35+05:00 [SERVER] INFO: Connecting to the Database
> 2023-09-03T22:20:35+05:00 [DB] WARN: ENOENT: no such file or directory, open 'data\db-config.json'
> 2023-09-03T22:20:35+05:00 [DB] INFO: Database Type: sqlite
> ```

What directory are you in when running node server/server.js?
What directory is Uptime Kuma in?

**Comment by Zaid-maker** [comment]
> > ```shell
> > 2023-09-03T22:20:35+05:00 [SETUP-DATABASE] INFO: db-config.json is not found or invalid: ENOENT: no such file or directory, open 'data\db-config.json'
> > 2023-09-03T22:20:35+05:00 [SERVER] INFO: Connecting to the Database
> > 2023-09-03T22:20:35+05:00 [DB] WARN: ENOENT: no such file or directory, open 'data\db-config.json'
> > 2023-09-03T22:20:35+05:00 [DB] INFO: Database Type: sqlite
> > ```
> 
> What directory are you in when running node server/server.js? What directory is Uptime Kuma in?

The root dir ofc!

**Comment by Zaid-maker** [comment]
Thank you so much! its fixed and working as intended

**Comment by fimo-roe** [comment]
please explain how it was fixed in the end.
