### ISSUE TITLE
webhook why once time ?Why cannot alarms be sent all the time in Down state

### ISSUE THREAD

**Issue by xhweng-yy** [louislam/uptime-kuma#368]
**Is it a duplicate question?**
Please search in Issues without filters: https://github.com/louislam/uptime-kuma/issues?q=

**Info**
Uptime Kuma Version:
Using Docker?: Yes/No
OS:
Browser:
webhook why once time ?Why cannot alarms be sent all the time in Down state

**Comment by chakflying** [comment]
Duplicate of #233
