### ISSUE TITLE
How to set up the status page

### ISSUE THREAD

**Issue by erukim** [louislam/uptime-kuma#3681]
### ⚠️ Please verify that this bug has NOT been raised before.

- [x] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

I'm using Uptime using Kuma.
And I'm using 2 domains and I did all the domains for the status page using the domain.com/status/ document, but it still comes out in the same format as github.com/louislam/uptime-kuma/wiki/Status-Page .
What can I do to solve this problem?

### 🐻 Uptime-Kuma Version

1.23.1

### 💻 Operating System and Arch

Ubuntu 22.04 live-server

### 🌐 Browser

Chrome

**Comment by CommanderStorm** [comment]
What do you mean by `but it still comes out in the same format as`?

**Comment by erukim** [comment]
I created the entire status page with domain 1, which in this case only works the same way as the first domain, so that the status page can be accessed directly by referring to the https://github.com/louislam/uptime-kuma/wiki/Status corresponding wiki, but the second domain works the same way as the first one.

**Comment by kokofixcomputers** [comment]
> I created the entire status page with domain 1, which in this case only works the same way as the first domain, so that the status page can be accessed directly by referring to the https://github.com/louislam/uptime-kuma/wiki/Status corresponding wiki, but the second domain works the same way as the first one.

What do you mean by "works the same way as the first one"? Can you provide more information?
