### ISSUE TITLE
getaddrinfo EAI_AGAIN xxxxxxxx.com

### ISSUE THREAD

**Issue by klsdfjo** [louislam/uptime-kuma#3682]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

getaddrinfo EAI_AGAIN xxxxxxxx.com

### 📝 Error Message(s) or Log

getaddrinfo EAI_AGAIN xxxxxxxx.com

### 🐻 Uptime-Kuma Version

版本: 1.23.1

### 💻 Operating System and Arch

dibian

### 🌐 Browser

safari

### 🐋 Docker Version

leasts

**Comment by CommanderStorm** [comment]
Providing so little information is unlikely to get the help you wanted. (garbage-in ⇒ garbage-out)

- What steps have you tried?
- what DNS-caching are you using?
- what monitor are you using?

Have you searched through the other issues? https://github.com/louislam/uptime-kuma/issues?q=is%3Aissue+EAI_AGAIN
