### ISSUE TITLE
how to change username or add a new user?

### ISSUE THREAD

**Issue by xaswq** [louislam/uptime-kuma#3683]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

I've set up the software but can't find an option to change the username or add a new user. Is there a way to do this?

Thanks!

### 🐻 Uptime-Kuma Version

1.23.1

### 💻 Operating System and Arch

ubuntu 20

### 🌐 Browser

chrome

### 🐋 Docker Version

Docker

**Comment by CommanderStorm** [comment]
- The ability to add users is tracked in this issue: https://github.com/louislam/uptime-kuma/issues/128
- With database access the username can be changed. Currently there is not a simple way to do so as far as I know

**Comment by kokofixcomputers** [comment]
Right now, There is no way to add a new user as @CommanderStorm has said, There is also no way to change the username directly in the UI/UX you can only change it by modifying the database file.

**Comment by ww7** [comment]
How to change username for docker based setup:
```
docker exec -it uptime-kuma bash
sqlite3
.open data/kuma.db
UPDATE user SET username = 'new-username' WHERE username = 'old-username';
.quit
exit
```

**Comment by Sam-Pryor** [comment]
Thanks @ww7 
If you don't use docker you can:
`cd uptime-kuma/
sudo apt update && sudo apt install sqlite3
sqlite3
.open data/kuma.db
UPDATE user SET username = 'new-username' WHERE username = 'old-username';
.quit`

**Comment by wvogel** [comment]
It might become handy for someone wishing to ad multiple users:
As written above, connect to the container and open sqlite3. then proceed:
select * from user;
Now remember the first and the third column. First one is the ID - add 1 in the line below (let's say this is then **2**), the third is the **hash** of a password you know. Might as well reuse that one to be able to log in for the first time and then change it.
insert a record:
`insert into user values (2,'mynewlogin','the-hash-from-above',1,null,null,0,null);`
press ctrl+d twice and you are ready to log in with the newly created account.

**Comment by CommanderStorm** [comment]
@wvogel that does not work on multiple ways.
Multi-User support requires adjustments (see the PR linked to the issue I noted above)
