### ISSUE TITLE
Join as notification type

### ISSUE THREAD

**Issue by WatskeBart** [louislam/uptime-kuma#3689]
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

New Notification

### 🔖 Feature description

You should add [Join](https://joaoapps.com/join/) as a extra notification type which is compatible with Tasker.

### ✔️ Solution

[Join](https://joaoapps.com/join/) is for me a free and versatile notification platform.

### ❓ Alternatives

I've used Pushbullet in the past but didn't like the lack of features which [Join](https://joaoapps.com/join/) has.

**Comment by CommanderStorm** [comment]
This is kind of niche/uncommon notification provider.
If you/someone else would like to contribute such a provider, here is the Contribution guide:
https://github.com/louislam/uptime-kuma/blob/master/CONTRIBUTING.md 

If you do decide to do this, please not these two suggestions, which often push PRs back by a review-cycle:
- Ensure that the PR includes screenshots of the `DOWN`/`UP` and `testing`/`cert-expiry` events.
- All keys that can/should be translated are in `en.json` (⇒ our translators can translate this and no merge-confilicts between weblate and master can arise)

**Comment by WatskeBart** [comment]
> This is kind of niche/uncommon notification provider. If you/someone else would like to contribute such a provider, here is the Contribution guide: https://github.com/louislam/uptime-kuma/blob/master/CONTRIBUTING.md
> 
> If you do decide to do this, please not these two suggestions, which often push PRs back by a review-cycle:
> 
> * Ensure that the PR includes screenshots of the `DOWN`/`UP` and `testing`/`cert-expiry` events.
> * All keys that can/should be translated are in `en.json` (⇒ our translators can translate this and no merge-confilicts between weblate and master can arise)

That's a to big of a task for me. I will use the generic Webhook option in combination with Join for now.
Thanks for the quick response and kudos for this great application.
