### ISSUE TITLE
http/dns request response matching

### ISSUE THREAD

**Issue by pythonmandev** [louislam/uptime-kuma#3692]
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

Other

### 🔖 Feature description

When it monitor the http server,it can monitor the response of the http request with matching the contain of the website,and the same as dns monitoring.

### ✔️ Solution

collect the respone of http/dns request ,and matching the contain.

**Comment by mabed-fr** [comment]
http + keyword exist and dnsexist.

**Comment by AngryNorseMan** [comment]
http + keyword exists but dns check does not give any kind of pattern matching capabilities that I can see, just if a particular hostname resolves on a particular NS server.  It would be a very nice to have that once could add a string to monitor a specific response to a NS record for instance to validate that name servers on a particular domain remain the same.

This is something I'm looking for, and it looks like uptime.com is capable of it but I very much prefer this tool and would love to see that feature added, which seems to be what the original poster was wanting as well if I understand the initial issue correctly.
