### ISSUE TITLE
base2-slim not work

### ISSUE THREAD

**Issue by mabed-fr** [louislam/uptime-kuma#3695]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### Description

base2-slim not work

uptime-kuma-2 exited with code 0

### 👟 Reproduction steps

services:
  uptime-kuma-2:
    image: louislam/uptime-kuma:base2-slim
    container_name: uptime-kuma-2
    ports:
      - 127.0.0.1:3002:3001
    volumes:
      - uptime-kuma-2-0-emb:/app/data
    environment:
      - "UPTIME_KUMA_DB_TYPE=mariadb" 
      - "UPTIME_KUMA_DB_HOST=bdd-kuma"
      - "UPTIME_KUMA_DB_PORT=3306"
      - "UPTIME_KUMA_DB_NAME=uptime"
      - "UPTIME_KUMA_DB_USERNAME=kuma"
      - "UPTIME_KUMA_DB_PASSWORD=uptimekuma"
      - "UPTIME_KUMA_SETUP_ADMIN_USERNAME=admin"
      - "UPTIME_KUMA_SETUP_ADMIN_PASSWORD=azerty"
    restart: always

  bdd-kuma:
    image: mariadb:latest
    container_name: bdd-kuma
    environment:
      MARIADB_ROOT_PASSWORD: "ahphocoh8Iev"
      MARIADB_DATABASE: "uptime"
      MARIADB_USER: "kuma"
      MARIADB_PASSWORD: "uptimekuma"
    restart: always

### 👀 Expected behavior

start and work

### 😓 Actual Behavior

not work

### 🐻 Uptime-Kuma Version

base2-slim

### 💻 Operating System and Arch

Debian 12

### 🌐 Browser

Google chrome

### 🐋 Docker Version

Docker version 24.0.5, build ced0996

### 📝 Relevant log output

```shell
docker compose logs

uptime-kuma-2 exited with code 0
```

**Comment by louislam** [comment]
WIP, please wait until release.
