### ISSUE TITLE
Bandwidth (network traffic) usage of each services

### ISSUE THREAD

**Issue by mfide** [louislam/uptime-kuma#3698]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

Hello,

I just installed Uptime Kuma to my Linux server using docker compose, already started monitoring all my services. I found it very vivid and to the point.

I wonder now if it is also possible to monitor my server's cpu temperature and especially network traffic consumed by each of docker services on my server?

I do similar thing on my server using node-exported-prometheus-graphana triplet but wonder if similar thing would be possible just using Uptime kuma?

Thank you.

### 📝 Error Message(s) or Log

-

### 🐻 Uptime-Kuma Version

1.23.1

### 💻 Operating System and Arch

Ubuntu 22.04 x86_64

### 🌐 Browser

Google Chrome 116.0.5845.141

### 🐋 Docker Version

24.0.5

**Comment by mabed-fr** [comment]
I think this comes out of the uptime-kuma philosophy which aims to be the open source alternative to uptime robot.

If you want to monitor your servers use netdata to collect the prometheus metrics to store them and grafana to display them...

Enjoy

**Comment by CommanderStorm** [comment]
I think this is a duplicate of https://github.com/louislam/uptime-kuma/issues/2603 https://github.com/louislam/uptime-kuma/issues/2231 https://github.com/louislam/uptime-kuma/issues/819
If you agree, could you please close this Issue, as duplicates only create immortal zombies and are really hard to issue-manage?
If not, what makes this issue unique enough to require an additional issue? (Could this be integrated into the issue linked above?) ^^
