### ISSUE TITLE
[Question](05-09-2023) Can We Host Uptime Kuma in Shared Server with NodeJS? 

### ISSUE THREAD

**Issue by theinternetguy** [louislam/uptime-kuma#3699]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

Hi,

Can We Host Uptime Kuma in Shared Server with NodeJS? 

Thanks

### 🐻 Uptime-Kuma Version

Latest

### 💻 Operating System and Arch

Linux

### 🌐 Browser

Chrome

### 🟩 NodeJS Version

Yes

**Comment by CommanderStorm** [comment]
Depends on your requirements.
- Some features (ncst DNS caching, Chrome) might not be available if you can't install programs
- Security wise this also depends on your requirements (what is really shared? What isolation guarantees do I have/need?)

Here is our documentation: https://github.com/louislam/uptime-kuma/wiki/%F0%9F%94%A7-How-to-Install
