### ISSUE TITLE
Cant update to 1.0.3

### ISSUE THREAD

**Issue by rezzorix** [louislam/uptime-kuma#37]
Is it only me? 

I tried on 2 different machines, 1 which had the 1.0.1 version and another that has never seen uptime-kuma.

However and wherever ever i pull / run with or without latest tag, I cant get the 1.0.3 running on my systems...

Any advise?

**Comment by philippdormann** [comment]
@louislam does not always release on dockerhub, latest version is 1.0.1 😉

see https://hub.docker.com/r/louislam/uptime-kuma/tags?page=1&ordering=last_updated

**Comment by louislam** [comment]
1.0.3 docker image is on the way. The docker buildx progress is extreme slow now, due to compiling sqlite3 binary file for arm64 and arm/v7.

**Comment by antoine2tt** [comment]
@louislam thanks for your update !

**Comment by louislam** [comment]
Finally done!
If anyone know how to extract files in /app/node_modules/sqlite3/lib/binding in arm docker image. I do not want to build it every time, it is painful, lol.

**Comment by louislam** [comment]
> Finally done!
> If anyone know how to extract files in /app/node_modules/sqlite3/lib/binding in arm docker image, please let me know. I do not want to build it every time, it is painful, lol.
