### ISSUE TITLE
[K8s] 1.6.0: Container crashes after trying to update the sql scheme

### ISSUE THREAD

**Issue by srgvg** [louislam/uptime-kuma#370]
**Describe the bug**

**To Reproduce**

Upgrade from 1.5.3 to 1.6.0.
This runs with the docker image, in Kubernetes.
Container starts, logs the following, crashes, and restarts, with the same log again.
Reverting back to 1.5.3, container starts properly again (see second log)

**Expected behavior**
DB Upgrades suscceed and application starts.

**Info**
- Uptime Kuma Version: 1.6.0
- Using Docker?: Yes
- OS: Linux, Kubernetes (K3OS)
- Browser: n/a

**Error Log**

With 1.6.0:
```
Welcome to Uptime Kuma
Node Env: undefined
Importing Node libraries
Importing 3rd-party libraries
Importing this project modules
Prepare Notification Providers
Version: 1.6.0
Data Dir: ./data/
Creating express and socket.io instance
Server Type: HTTP
Connecting to Database
SQLite config:
[ { journal_mode: 'wal' } ]
[ { cache_size: -12000 } ]
Connected
Your database version: 9
Latest database version: 9
Database no need to patch
Database Patch 2.0 Process
patch-setting-value-type.sql is not patched
Backup the db
patch-setting-value-type.sql is patching
Shutdown requested
Called signal: SIGTERM
Stopping all monitors
Trace: Error [ERR_SERVER_NOT_RUNNING]: Server is not running.
    at Server.close (net.js:1608:12)
    at Object.onceWrapper (events.js:519:28)
    at Server.emit (events.js:412:35)
    at emitCloseNT (net.js:1661:8)
    at processTicksAndRejections (internal/process/task_queues.js:81:21) {
  code: 'ERR_SERVER_NOT_RUNNING'
}
    at process.<anonymous> (/app/server/server.js:973:13)
    at process.emit (events.js:400:28)
    at processPromiseRejections (internal/process/promises.js:245:33)
    at processTicksAndRejections (internal/process/task_queues.js:96:32)
If you keep encountering errors, please report to https://github.com/louislam/uptime-kuma/issues
patch-setting-value-type.sql is patched successfully
patch-improve-performance.sql is not patched
patch-improve-performance.sql is patching
Closing DB
```

Reverting back to 1.5.3
```
Welcome to Uptime Kuma
Node Env: undefined
Importing Node libraries
Importing 3rd-party libraries
Importing this project modules
Version: 1.5.3
Data Dir: ./data/
Creating express and socket.io instance
Server Type: HTTP
Connecting to Database
[ { journal_mode: 'wal' } ]
Connected
Your database version: 9
Latest database version: 8
Warning: Database version is newer than expected
Load JWT secret from database.
Adding route
Adding socket handler
Init the server
Listening on 3001
Latest Version: 1.6.0
Monitor #3 ....
```

**Comment by louislam** [comment]
May not related to patch db, it is actually successfully
 
```
patch-setting-value-type.sql is patched successfully
```

The main problem is, something close the Uptime Kuma.
```
Shutdown requested
Called signal: SIGTERM
```

**Comment by louislam** [comment]
> May not related to patch db, it is actually successfully
> 
> ```
> patch-setting-value-type.sql is patched successfully
> ```
> 
> The main problem is, something close the Uptime Kuma process.
> 
> ```
> Shutdown requested
> Called signal: SIGTERM
> ```

**Comment by louislam** [comment]
My guess is k8s healthcheck send this shutdown signal?

I am reading this, there is no `start-period` like dockerfile
https://github.com/louislam/uptime-kuma/blob/31b4a5c33e872395b22c121bdb2fcab4189bccaa/kubernetes/uptime-kuma/deployment.yml#L28-L32

https://github.com/louislam/uptime-kuma/blob/31b4a5c33e872395b22c121bdb2fcab4189bccaa/dockerfile#L27

**Comment by gaby** [comment]
@louislam To get `start-period` in kubernetes it would need to be the following way: 

```
livenessProbe:
  exec:
    command:
    - node
    - extra/healthcheck.js
  initialDelaySeconds: 180
  periodSeconds: 60
  timeoutSeconds: 30
```

Source: https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/

**Comment by gaby** [comment]
There's a note about exec probes: 

```
Note:
Before Kubernetes 1.20, the field timeoutSeconds was not respected for exec probes: probes continued running indefinitely, even past their configured deadline, until a result was returned.
```

**Comment by srgvg** [comment]
Thx @gaby adding that to the liveness probe solves it indeed.

**Comment by gaby** [comment]
@louislam Looks good to me! Future update would be to add configuration to the Readiness Probe. I can take a look at it this weekend.

**Comment by louislam** [comment]
> @louislam Looks good to me! Future update would be to add configuration to the Readiness Probe. I can take a look at it this weekend.

I have no experience with K8s. Any K8s changes need one more reviewer to test, verify and confirm before merge.
