### ISSUE TITLE
Where can I find the uptime kuma logs?

### ISSUE THREAD

**Issue by alef1603** [louislam/uptime-kuma#3700]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

Fisrt of all, thanks for this amazing tool... I have just started using it and it seems to fit exactly to my needs. 

I running the docker image provided to run uptime kuma, however, I did not find any logs to check a strange behavior after I added 2 different notifications (2 webhook, 1 fro MS Teams and another for JIRA Service) to all of my monitoring checks (all of them are TCP Port).

Can you please help me on these 2 questions?
1- does it work fine with more than 1 notification alert?
2- where can I find the uptime logs to check what is going on?

Thanks!!

### 📝 Error Message(s) or Log

it is what I am looking for.

### 🐻 Uptime-Kuma Version

1.23.1

### 💻 Operating System and Arch

Ubuntu 22.04.2 LTS

### 🌐 Browser

Microsoft Edge 116.0.1938.69

### 🐋 Docker Version

Docker  20.10.21

**Comment by CommanderStorm** [comment]
You can access the log via 

`docker logs <id-of-the-contaiener>`
You can find this id via `docker ps`

Alerting to multiple proviers simultaneosly is supported.

**Comment by alef1603** [comment]
Thanks a lot.
