### ISSUE TITLE
Notifications ignore self-signed SSL certificates button

### ISSUE THREAD

**Issue by mtimani** [louislam/uptime-kuma#3705]
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

New Notification

### 🔖 Feature description

The RocketChat Notifications does not have an ignore self-signed SSL certificates button. Thus, rendering it impossible to configure a webhook on a self-hosted RocketChat server.

### ✔️ Solution

Add a button (like for the Monitors) to ignore SSL certificates of RocketChat servers

**Comment by CommanderStorm** [comment]
Doing so (ignoring certs for notifications) could mean that an attacker intercepts these notifiations as they are no longer  as MITM attacks are possible in this case.

Wouldn't it be better to either
- register the CA used by the RocketChat server you host
- or provide said server with a valid cert (letsencrypt/...)

**Comment by mtimani** [comment]
100%
Nevertheless, you provide the same feature as an option (tick box) for monitoring. Why not add the same button to ignore (in case the person wants it) the SSL certificate.
Leaving by default the secure option (validating the certificate)

**Comment by Alex11381** [comment]
Same problem with Matrix

**Comment by CommanderStorm** [comment]
Closing as https://github.com/louislam/uptime-kuma/labels/wontfix.

Doing so (ignoring certs for notifications) could mean that an attacker intercepts these notifiations as they are no longer as MITM attacks are possible in this case.

Users seeking this should either
- register the CA used by the `$Notificationprovider` server you host
- or provide said `$Notificationprovider` server with a valid cert (letsencrypt/...)

Notifications are very different from monitors, where this is handy.
For notifications, you don't want them going to a potentially different server.
