### ISSUE TITLE
[Python] Error while experimenting with Socket.io

### ISSUE THREAD

**Issue by mawoka-myblock** [louislam/uptime-kuma#371]
I'm trying to get data in Python over the socket.io-connection.
This is my code:
```python
import asyncio
import socketio
sio = socketio.AsyncClient()
@sio.event
async def connect():
    print('connection established')
    await get_data()
async def get_data():
    await sio.emit("login", {"username": "test", "password": "testtest"})
async def main():
    await sio.connect("http://localhost:3001/")
    await sio.wait()
if __name__ == "__main__":
    asyncio.run(main())
```
The problem: In the Server-log, I get this error: 
```
Trace: TypeError: callback is not a function
    at Socket.<anonymous> (/app/server/server.js:222:17)
    at process.<anonymous> (/app/server/server.js:973:13)
    at process.emit (events.js:400:28)
    at processPromiseRejections (internal/process/promises.js:245:33)
    at processTicksAndRejections (internal/process/task_queues.js:96:32)
If you keep encountering errors, please report to https://github.com/louislam/uptime-kuma/issues
```

**Info**
Uptime Kuma Version: 1.6.0
Using Docker?: Yes
OS: Docker
Browser: -

**Comment by louislam** [comment]
Just follow Uptime-Kuma's frontend js code, you are missing the last parameter `callback`.

https://github.com/louislam/uptime-kuma/blob/31b4a5c33e872395b22c121bdb2fcab4189bccaa/src/mixins/socket.js#L205-L219

And just a remind, it is not an API, the call will be changed in the future.

**Comment by mawoka-myblock** [comment]
Ok, thank you very much for your quick help!

**Comment by mawoka-myblock** [comment]
I asked for help, because I made this: https://github.com/mawoka-myblock/uptime-kuma-static
