### ISSUE TITLE
"No certificate" badge is shown for http monitors

### ISSUE THREAD

**Issue by mueller-ma** [louislam/uptime-kuma#3712]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 👟 Reproduction steps

1. Create a monitor with http url
2. Add the monitor to a status page
3. Enable "Show Certificate Expiry" for that status page

### 👀 Expected behavior

No badge is shown for http monitors.

### 😓 Actual Behavior

A red badge with the text "Cert Exp.: No/Bad Certificate" is shown for a monitor with an http address. This looks like there's an error, but it's expected to have no certificate when it's http only.

### 🐻 Uptime-Kuma Version

1.23.1

### 💻 Operating System and Arch

Docker

### 🌐 Browser

Firefox

**Comment by CommanderStorm** [comment]
I think this is a duplicate of https://github.com/louislam/uptime-kuma/issues/3615
If you agree, could you please close this Issue, as duplicates only create immortal zombies and are really hard to issue-manage?
If not, what makes this issue unique enough to require an additional issue? (Could this be integrated into the issue linked above?) ^^

**Comment by louislam** [comment]
I think it is not a duplicate, as op said it is related to a "non-https" url.

**Comment by louislam** [comment]
Fixed: https://github.com/louislam/uptime-kuma/pull/3710/commits/ff51704cdfcc7853076a62e67b8fc33cfd04c17a
