### ISSUE TITLE
[k8s] Lost DB during update

### ISSUE THREAD

**Issue by chevdor** [louislam/uptime-kuma#3714]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### Description

There are similar issues but close and I just ran into the problem.
Similar issue: https://github.com/louislam/uptime-kuma/issues/2778

I would have preferred the app to stock and ask than reset everything.

This also leads to a dead end for the user since:
- backup does not work (`Deprecated: Since a lot of features were added and this backup feature is a bit unmaintained, it cannot generate or restore a complete backup.`)
- Saving data is useless since it gets overwritten

### 👟 Reproduction steps

Stop old version
Start new version

### 👀 Expected behavior

The DB is not wiped

### 😓 Actual Behavior

The DB is wiped/reset

### 🐻 Uptime-Kuma Version

1.23.1

### 💻 Operating System and Arch

K8S

### 🌐 Browser

brave

### 🐋 Docker Version

K8S 1.27.2

### 🟩 NodeJS Version

n/a

**Comment by louislam** [comment]
K8s is not official supported and most likely you are not pointing to the same volume after update.

**Comment by chevdor** [comment]
This is not a K8S issue. K8S is just how I run it.
I am pointing 100% to the same folder, my config did not change.
I am also seeing the db in the config location I defined.

I was greeted after the update by the "Let's set your admin password" flow.

**Comment by chakflying** [comment]
You can post the container logs to help troubleshooting.

**Comment by chevdor** [comment]
Unfortunately I no longer have logs as I killed the pod to force the update.
I just tried however to kill my current pod, a new one started and did pick everything nicely.

That confirms that my storage config should be fine.
It also points toward the issue being potenitially around upgrades/migrations ?

**Comment by chevdor** [comment]
noteas that may be helpful: 
- I am using only stable release (ie no beta) 
- I did jump from 1.22.1 to 1.23.1 without passing thru 1.23.0

**Comment by CommanderStorm** [comment]
I cannot reproduce this with docker:
- `docker stop $(docker ps -qa) && docker rm $(docker ps -qa) &&  docker volume rm $(docker volume ls -q)` (to reset everything, dangerous ^^)
- `docker run -it -p 3001:3001 -v uptime-kuma:/app/data louislam/uptime-kuma:1.22.1`
- stop said container
- `docker run -it -p 3001:3001 -v uptime-kuma:/app/data louislam/uptime-kuma:1.23.1`

This leads me to believe that there is something else going on.
How are you running the container exactly (storage-wise, helmchart-wise, k8s-version-wise, ...)

**Comment by CommanderStorm** [comment]
Another note: How did you upgrade the apps version exactly?

**Comment by chevdor** [comment]
Using k8s, if you kill a pod (that was made in a deployment), a new pod gets created as replacement.
Since I am using `imagePullPolicy: Always`, the freshest image gets pulled in.

So to upgrade, I simply killed the older pod. Storage is handled by k8s and as long as you have storage outside of the container (ie a mounted volume), k8s makes sure the old pod is down before the new one takes over storage.

> Could it be that you are deploying another verison of the app and tearing down the old version thus deleting the persistant volume you defined?

This is a fair question but this is not the case and the test I made confirms it is not what is happening. Killing my current pod, does trigger the same process I described, it pulled the latest image (which is still the same version) and starts again.
When I killed the v1.23.1 pod, it was replaced with a new pod and all the data was still available.

**Comment by louislam** [comment]
Some directions:

1. Use a sqlite gui tool such as SQLite Expert Personal to see what is inside the database `kuma.db`.
2. Go into the container's terminal and check the size of kuma.db at /app/data.

**Comment by chevdor** [comment]
Here the sizes already:
```
[  519050676]  .
├── [    3155380]  sub
│   ├── [      16384]  docker-tls
│   ├── [       3164]  error.log
│   ├── [    1945600]  kuma.db
│   ├── [      32768]  kuma.db-shm
│   ├── [    1108312]  kuma.db-wal
│   ├── [      16384]  screenshots
│   └── [      16384]  upload
├── [  515862528]  subkuma.db
└── [      16384]  subupload
```

**Comment by louislam** [comment]
You should be using `DATA_DIR`

> Fixed the data directory issue if you specified a path in DATA_DIR without tailing slash
    In case you did this, you may need to manually correct the path like /home/userkuma_data/kuma.db to /home/user/kuma_data/kuma.db)

https://github.com/louislam/uptime-kuma/releases/tag/1.23.0


In your case, you should:
1. rename `sub` to `sub_bak`
2. rename subkuma.db to sub/kuma.db
3. rename subupload to sub/upload
4. start the container

**Comment by chevdor** [comment]
Thanks @louislam, this does explain my issue and thanks to your explanation, I could restore all my previous data.
I was indeed using a `DATA_DIR` without trailing `/` and that explains the whole issue.

After adding the trailing `/`, fixing the folders as mentioned above and killing the pod (which made a new one start), I could get back on track with all the probes I had defined earlier.

❤️

**Comment by girhame** [comment]
It is possible I did not set up the yml correctly when reinstalled. Can you review and let me know. Should it specify the db file or just the volume?
![uptime](https://github.com/louislam/uptime-kuma/assets/139905235/26e29dfa-33aa-42a6-bf8e-0d7b0a48b758)

**Comment by thorr972** [comment]
Hello,

I inform you of a strange behavior.. but which allowed me to restore my database from a JSON backup.

I am currently using version Version: 1.23.16 (Frontend version: 1.23) under Docker (version 20.10.5+dfsg1, build 55c4c88).

Here is a procedure that has worked several times (I don't know why).

But I would invite you to make a copy of the "/app/data" folder anyway.

1) Delete all the contents of the "/app/data" folder.

2) Restart your container
3) On the authentication page, recreate your usual logins.

4) After authentication, go to Settings and make an export that you save wherever you want.

5) Try to import your JSON backup.

You will get an error "SQLITE_CONSTRAINT: FOREIGN KEY constraint failed" the first time and then try again.
The second time, everything will be fine.

If someone can explain why it works.... I'm interested.
