### ISSUE TITLE
Please support The Lark webhooks

### ISSUE THREAD

**Issue by Just2co** [louislam/uptime-kuma#3715]
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

New Notification

### 🔖 Feature description

Feishu's webhook notifications have been supported for a long time. Please  support  Lark webhooks, which is the international version of Feishu.

### ✔️ Solution

请添加Lark 的webhook 支持

### ❓ Alternatives

I tested and found that directly adding the webhook link of the notification robot from a Lark group into the URL section under Feishu notifications does result in receiving notifications. However, there were compatibility issues where the notification details were not displayed. Please add support for this, it would be greatly appreciated!

### 📝 Additional Context

把Lark 的webhook 填入飞书通知的URL 下面，可以收到通知，但是会出现适配问题，不显示通知详情，所以请添加Lark 的通告支持，非常感谢！

I tested and found that directly adding the webhook link of the notification robot from a Lark group into the URL section under Feishu notifications does result in receiving notifications. However, there were compatibility issues where the notification details were not displayed. Please add support for this, it would be greatly appreciated!

**Comment by CommanderStorm** [comment]
This is kind of niche/uncommon notification provider.
If you/someone else would like to contribute such a provider, here is the Contribution guide:
https://github.com/louislam/uptime-kuma/blob/master/CONTRIBUTING.md 

If you do decide to do this, please not these two suggestions, which often push PRs back by a review-cycle:
- Ensure that the PR includes screenshots of the `DOWN`/`UP` and `testing`/`cert-expiry` events.
- All keys that can/should be translated are in `en.json` (⇒ our translators can translate this and no merge-confilicts between weblate and master can arise)

**Comment by Just2co** [comment]
This issue has been resolved. You can directly add a bot in a Lark group, choose custom bot, then fill in the webhook link in uptime-kuma's settings - notifications, and select Feishu as the notification type.
