### ISSUE TITLE
How to add additional cookies to monitors

### ISSUE THREAD

**Issue by IDN-YN** [louislam/uptime-kuma#3716]
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

Other

### 🔖 Feature description

At the moment I have a monitor checking our production servers, but they are behind a loadbalancer.
I can force the loadbalancer choosing with a cookie, but I can't find any documentation on this topic, if it's even possible?

### ✔️ Solution

Being able to add a cookie to a monitor

**Comment by chakflying** [comment]
If you only need to add a static cookie, you should be able to use the "Headers" option and add `"Cookie": "your-value"`. Dynamic cookies is currently not supported.
