### ISSUE TITLE
Better Status Page And Report / Issues

### ISSUE THREAD

**Issue by NOXITB** [louislam/uptime-kuma#3718]
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

UI Feature

### 🔖 Feature description

Make it easier for you to have issues and show your customers like https://discordstatus.com/

### ✔️ Solution

https://discordstatus.com/

**Comment by CommanderStorm** [comment]
Your feature request does not really go into details what you mean by "easier".
Could you screenshot what you are refering to?

Is this a duplicate of the ones tracked in https://github.com/louislam/uptime-kuma/pull/1253 ?

**Comment by NOXITB** [comment]
> Your feature request does not really go into details what you mean by "easier". Could you screenshot what you are refering to?
> 
> Is this a duplicate of the ones tracked in #1253 ?

that would be it wasent searching hard enough at 2 am sorry about that this one is been closed
