### ISSUE TITLE
Timezone Issue Causes Incorrect Monitor Time Display

### ISSUE THREAD

**Issue by olewaldo** [louislam/uptime-kuma#3723]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

Environment:
Uptime Kuma Version: 1.23.1
OS: Ubuntu 22.04
Database: MariaDB

Issue:
I've encountered an issue where the monitor time displayed in Uptime Kuma is incorrect. The time initially appears correct but later jumps forward by 2 hours. I've confirmed that the server's timezone and MariaDB's timezone are both correctly set to 'Europe/Berlin'.

Logs:
The following warning appears in the logs:

`Ignoring invalid timezone passed to Connection: UTC. This is currently a warning, but in future versions of MySQL2, an error will be thrown if you pass an invalid configuration option t>`

This log entry coincides with the time jump in the Uptime Kuma interface.

Steps to Reproduce:

- Install Uptime Kuma on a server with the 'Europe/Berlin' timezone.
- Set up a monitor.
- Observe the time displayed for the monitor.

Expected Behavior:
The monitor time should be consistent with the server's timezone setting.

Actual Behavior:
The monitor time jumps forward by 2 hours after a short period.

Additional Information:
I've tried modifying the MariaDB configuration to set the global timezone, but the issue persists. 

### 🐻 Uptime-Kuma Version

1.23.1

### 💻 Operating System and Arch

Ubuntu 22.04

### 🌐 Browser

Chrome 116.0.5845.142

### 🟩 NodeJS Version

16.20.2

**Comment by louislam** [comment]
MariaDB support is not released yet in 1.23.1. And it is not stable yet.

Please follow README.md to install Uptime Kuma 1.23.1 correctly.

**Comment by olewaldo** [comment]
Thank you for the quick response. Is MariaDB not supported at all, or is it just the mentioned version that is not supported? Since I had the option to choose MariaDB during the setup after installation, I assumed that it is also supported. I have looked at the README, but unfortunately, I can't find any information on the supported databases there; maybe I have overlooked it.

**Comment by rezzorix** [comment]
Wait for the next (major) update and you get mariadb. 
For now it is not supported.

**Comment by louislam** [comment]
> Thank you for the quick response. Is MariaDB not supported at all, or is it just the mentioned version that is not supported? Since I had the option to choose MariaDB during the setup after installation, I assumed that it is also supported. I have looked at the README, but unfortunately, I can't find any information on the supported databases there; maybe I have overlooked it.

I think you somehow installed the development build (2.0.0) (which is support MariaDB, but still buggy and work in progress).

You should follow the installation guide to install 1.23.1 correctly.

**Comment by olewaldo** [comment]
No, I have version 1.23.1 installed. When I look at the "About" section, it shows me version 1.23.1 for both the backend and frontend.

But that's fine, now I know it's not yet supported and I'm looking forward to the next major release!
