### ISSUE TITLE
serve status page using sub-domain

### ISSUE THREAD

**Issue by 7zx** [louislam/uptime-kuma#3728]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

How can i make the status page accesible through a sub-domain like: status.mydomain.com (no paths, just a direct sub-domain)

### 🐻 Uptime-Kuma Version

this doesn't really matter

### 💻 Operating System and Arch

Raspian aka Debian

### 🌐 Browser

this doesn't really matter

**Comment by louislam** [comment]
See: https://github.com/louislam/uptime-kuma/wiki/Status-Page
