### ISSUE TITLE
Trying to be able to monitor my Docker

### ISSUE THREAD

**Issue by 60Jordangaming** [louislam/uptime-kuma#3732]
### ⚠️ Please verify that this bug has NOT been raised before.

- [x] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

I been trying to run -v /var/run/docker.sock:/var/run/docker.sock 
Then later found out my Docker.sock is in /run/docker.sock So I did -v /run/docker.sock:/run/docker.sock 
I still had not got it to work I been searching all over and Can not found Nothing  

### 📝 Error Message(s) or Log

bash: -v: command not found

### 🐻 Uptime-Kuma Version

Version: 1.23.1

### 💻 Operating System and Arch

Ubuntu 22.04.3 LTS

### 🌐 Browser

opera

### 🐋 Docker Version

Docker version 24.0.6, build ed223bc

**Comment by CommanderStorm** [comment]
> So I did -v /run/docker.sock:/run/docker.sock

- have you tried `-v /run/docker.sock:/var/run/docker.sock` ?

Please also attach this information:
- What method are you using? https://github.com/louislam/uptime-kuma/wiki/How-to-Monitor-Docker-Containers
- How is docker installed
- have you made sure that your `deamon.json` contains the required lines? Could you post the content of said file?
