### ISSUE TITLE
[QUESTION] Validity duration of the frontend socket's authentication tokens.

### ISSUE THREAD

**Issue by MarlBurroW** [louislam/uptime-kuma#3733]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

I'm currently implementing two-factor authentication for my[ Streamdeck plugin](https://github.com/MarlBurroW/Streamdeck-Uptime-Kuma). 
Before, I used to store user credentials in the settings of my plugin, but the support for two-factor authentication forces me to save the authentication token returned by the[ login method](https://github.com/louislam/uptime-kuma/blob/9c24cd397302b16c1d9be04e4d8278cd4eecaea7/server/server.js#L365), then use the [loginByToken ](https://github.com/louislam/uptime-kuma/blob/9c24cd397302b16c1d9be04e4d8278cd4eecaea7/server/server.js#L320)method to authenticate in all subsequent connections,
For this reason, I'd like to know if the authentication tokens returned by the[ login method](https://github.com/louislam/uptime-kuma/blob/9c24cd397302b16c1d9be04e4d8278cd4eecaea7/server/server.js#L365) of the websocket have an expiration duration. If they do, is it possible to add an option to get non-expiring tokens or ones with a very long duration ?

Note: I know there's an official API in development, but in the meantime, I have to use the frontend's websocket which might not be intended for third-party applications.

Thanks

Related issue on my repo: https://github.com/MarlBurroW/Streamdeck-Uptime-Kuma/issues/7

### 🐻 Uptime-Kuma Version

1.23.1

### 💻 Operating System and Arch

Docker image tag 1.23.1

### 🌐 Browser

Chrome

**Comment by louislam** [comment]
The token will not expire. As long as it keeps in a private place, it should be safe.

**Comment by MarlBurroW** [comment]
Good news, thank you @louislam.
