### ISSUE TITLE
Is there any way to retrieve historical data from each dashboard?

### ISSUE THREAD

**Issue by alejandromiller21** [louislam/uptime-kuma#3734]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

I need to retrieve historical data from each dashboard in text plane or json format. Can you tell me how to do it?
![image](https://github.com/louislam/uptime-kuma/assets/89926156/e099b707-0fc0-4b4a-b6cc-2629e6f3669f)

### 🐻 Uptime-Kuma Version

1.23.1

### 💻 Operating System and Arch

Kubernetes

### 🌐 Browser

Google Chrome 

### 🐋 Docker Version

louislam/uptime-kuma:1.23.1

**Comment by CommanderStorm** [comment]
Currently, such a functionality does not exist. 
For the moment, you can use external (unofficial) tools like https://uptime-kuma-api.readthedocs.io/en/latest/ to export data or directly access the database.
If you'd like to add address this feature, here is our contributing guide: https://github.com/louislam/uptime-kuma/blob/master/CONTRIBUTING.md

I think this is a duplicate of https://github.com/louislam/uptime-kuma/issues/1093 (and its duplicates like https://github.com/louislam/uptime-kuma/issues/1101)
If you agree, could you please close this Issue, as duplicates only create immortal zombies and are really hard to issue-manage?
If not, what makes this issue unique enough to require an additional issue? (Could this be integrated into the issue linked above?) ^^
