### ISSUE TITLE
Changing Duration of Monitor

### ISSUE THREAD

**Issue by privacytime101** [louislam/uptime-kuma#3738]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

Is there any way to change the duration that the uptime percentage checks in? Currently the percentage seems to show how much it was up in the past 24 hours, but it'd be nice if it could be longer.

### 🐻 Uptime-Kuma Version

1.23.1

### 💻 Operating System and Arch

Ubuntu 22.04 x86

### 🌐 Browser

Brave (Chromium 116.0.5845.188)

**Comment by mariogarridopt** [comment]
In the current version, there is no way to change the timespan used to calculate the percentage of uptime
