### ISSUE TITLE
Accessing via IPv6 address results in socket server connect timeout

### ISSUE THREAD

**Issue by samip5** [louislam/uptime-kuma#374]
**Is it a duplicate question?**
No

**Describe the bug**
If you access standalone install via IPv6 address like `http://[2001:DB8::1]`, you will find that the application is unable to connect to backend.

**To Reproduce**
1. Install standalone, without Docker and start via pm2.
2. Go to the URL via IPv6.
3. See it will not load fully
4. See error about socket server timeout

**Expected behavior**
It would work properly

**Info**
- Uptime Kuma Version: 1.6.0
- Using Docker?: No
- OS: Ubuntu Server 20.04 ARM64
- Browser: Edge and Firefox tried

**Screenshots**
![unknown](https://user-images.githubusercontent.com/1703002/132906265-4621dab3-35e2-47b3-9bfe-65554ca89fab.png)
![unknown2](https://user-images.githubusercontent.com/1703002/132906271-d3d9d094-3abb-4e0c-bef6-91949a005425.png)
![unknown3](https://user-images.githubusercontent.com/1703002/132906272-845c6c09-7f84-455f-8539-9305406fa02e.png)
![unknown4](https://user-images.githubusercontent.com/1703002/132906277-a76f1e42-c8f9-4df4-8b60-08f69f39551e.png)

**Error Log**
N/A

**Comment by louislam** [comment]
Will look into it tomorrow.

**Comment by louislam** [comment]
Fixed in 2da77d84489e133b895a2a4a6b494013346e8d25

You can checkout master and try.

**Comment by samip5** [comment]
> Fixed in [2da77d8](https://github.com/louislam/uptime-kuma/commit/2da77d84489e133b895a2a4a6b494013346e8d25)
> 
> You can checkout master and try.

Verified as working. :)
