### ISSUE TITLE
Should node 14 really be supported?

### ISSUE THREAD

**Issue by harryzcy** [louislam/uptime-kuma#3746]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### Description

Node.js 14, 16 reached end-of-life already. Should they really be supported? They use OpenSSL 1.1.1 which is EOL as well.

I think it's better to force node>=18 in `package.json` and drop related tests.

### 👟 Reproduction steps

Use node 14

### 👀 Expected behavior

Exit

### 😓 Actual Behavior

It works

### 🐻 Uptime-Kuma Version

master branch

### 💻 Operating System and Arch

All

### 🌐 Browser

All

**Comment by CommanderStorm** [comment]
I am going to close this issue as the discussion in #3747 has not shown an immediate need to upgrade this part.

If there are (security/other) reasons which we are missing, we would love to hear them either in this issue (we can reopen in such a case) (if not security related) or as a security advisory if it is.
