### ISSUE TITLE
stuck monitor after read ETIMEDOUT

### ISSUE THREAD

**Issue by obfusk** [louislam/uptime-kuma#3752]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### Description

We had a monitor get stuck after two consecutive `read ETIMEDOUT`s. Pausing and resuming didn't help. Neither did restarting the docker container. We had to delete and recreate the monitor.

As you can see in the screenshot, it simply didn't do anything for 13 hours after two failed checks (HTTP monitor, check interval 60s, 5 retries, retry interval 60s, nothing unusual). It just got completely stuck on both our production and staging servers.

![kuma-stuck](https://github.com/louislam/uptime-kuma/assets/1260687/4d3efeaa-2b7a-48c0-93e4-a6e3be7a0f06)

### 👟 Reproduction steps

(Un)fortunately, it hasn't happened since, so I'm not sure how to reproduce. The server was indeed unreachable and monitoring correctly showed it as down after recreating the monitor.

### 👀 Expected behavior

For the monitor to fail as a result of the failed checks.

### 😓 Actual Behavior

The monitor got stuck and did nothing.

### 🐻 Uptime-Kuma Version

1.23.1

### 💻 Operating System and Arch

Debian GNU/Linux 11

### 🌐 Browser

Firefox

### 📝 Relevant log output

The two read ETIMEDOUT failures show up in the log, but nothing else does afterwards for hours (for that monitor):

```
[MONITOR] WARN: Monitor #73 'Link': Pending: read ETIMEDOUT | Max retries: 5 | Retry: 1 | Retry Interval: 60 seconds | Type: http
[MONITOR] WARN: Monitor #73 'Link': Pending: read ETIMEDOUT | Max retries: 5 | Retry: 2 | Retry Interval: 60 seconds | Type: http
```

After recreating the monitor it fails as expected:

```
[MONITOR] WARN: Monitor #99 'Link': Pending: timeout of 48000ms exceeded | Max retries: 5 | Retry: 1 | Retry Interval: 60 seconds | Type: http
[MONITOR] WARN: Monitor #99 'Link': Pending: timeout of 48000ms exceeded | Max retries: 5 | Retry: 2 | Retry Interval: 60 seconds | Type: http
[MONITOR] WARN: Monitor #99 'Link': Pending: timeout of 48000ms exceeded | Max retries: 5 | Retry: 3 | Retry Interval: 60 seconds | Type: http
[MONITOR] WARN: Monitor #99 'Link': Pending: timeout of 48000ms exceeded | Max retries: 5 | Retry: 4 | Retry Interval: 60 seconds | Type: http
[MONITOR] WARN: Monitor #99 'Link': Pending: timeout of 48000ms exceeded | Max retries: 5 | Retry: 5 | Retry Interval: 60 seconds | Type: http
```

**Comment by louislam** [comment]
No reproduce steps usually means it is cannot be fixed.

**Comment by obfusk** [comment]
> No reproduce steps usually means it is cannot be fixed.

Yeah, I expected that. Just wanted to report it, also in case anyone else runs into it. Will report back if it happens again of course.

**Comment by Jamira40** [comment]
We had similar issue with one of our instances. It was running on 1.21.3. Happened to two checks. There was no data in graphs whatsoever. Pausing and Unpausing restarted checks. Right now its updated to latest release 1.23.2

Checked logs didn't see anything suspicious.

**Comment by CommanderStorm** [comment]
We have no clue where this is coming from nor a clue how to debug or fix this => closing as no-repro
