### ISSUE TITLE
Custom notifications

### ISSUE THREAD

**Issue by WilliamDavidHarrison** [louislam/uptime-kuma#3753]
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

New Notification

### 🔖 Feature description

Allow us to setup a notification with a URL that we set and when a monitor goes up or down a data payload gets sent to it.

### ✔️ Solution

1. Set up custom webhook URL
2. When a monitor goes up/down a payload gets sent to that URL

**Comment by harryzcy** [comment]
How is it different from "Webhook"?

**Comment by WilliamDavidHarrison** [comment]
I completely forgot about that, my bad.
