### ISSUE TITLE
Login Logfile? [fail2ban] 

### ISSUE THREAD

**Issue by XHyperDEVX** [louislam/uptime-kuma#3754]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

Hello,

is there a log file that automatically stores failed logins on the login screen with IP?

If no, is there another way to protect the login with fail2ban?

### 🐻 Uptime-Kuma Version

1.23.1

### 💻 Operating System and Arch

Debian 11

### 🌐 Browser

Not important

### 🐋 Docker Version

No Docker

### 🟩 NodeJS Version

18.14.2

**Comment by CommanderStorm** [comment]
Yes, login attempts should be logged like this:
![image](https://github.com/louislam/uptime-kuma/assets/26258709/33e61a85-91d4-414f-89a1-1e467cf4f7be)

No, we currently don't use fail2ban, but instead use rate-limiting

**Comment by XHyperDEVX** [comment]
> Yes, login attempts should be logged like this: ![image](https://user-images.githubusercontent.com/26258709/268490074-33e61a85-91d4-414f-89a1-1e467cf4f7be.png)
> 
> No, we currently don't use fail2ban, but instead use rate-limiting. I have not heard of other software usting this to protect non-ssh logins

I want to protect the login with fail2ban itself, for which I need a file where uptime-kuma stores all failed logins with ip.
the accesses on your screenshot, where do i find them? are they in a file?

**Comment by chakflying** [comment]
If you are not using docker, you can pipe the stdout of the server to a file to make it available.

**Comment by XHyperDEVX** [comment]
> If you are not using docker, you can pipe the stdout of the server to a file to make it available.

How?

**Comment by CommanderStorm** [comment]
https://docs.docker.com/engine/reference/commandline/logs/

**Comment by XHyperDEVX** [comment]
> You can access the logs via the normal mechanism https://docs.docker.com/engine/reference/commandline/logs/
> 
> Note that fail2ban is not better than our currently implmented rate limiting as far as I understand it.

i use fail2ban for my whole system. i do not only host uptime-kuma [logical for an uptime service].

currently i have it configured so that for all logins fails, even for other services, the ip is blocked for EVERYTHING.

it's good that uptime-kuma blocks itself on failed logins, but unfortunately i need to make it compatible with fail2ban to make it work server wide.

**Comment by XHyperDEVX** [comment]
> You can access the logs via the normal mechanism https://docs.docker.com/engine/reference/commandline/logs/
> 
> Note that fail2ban is not better than our currently implmented rate limiting as far as I understand it.

This doesn't work, I don't use Docker, as also mentioned.

**Comment by rezzorix** [comment]
> You can access the logs via the normal mechanism https://docs.docker.com/engine/reference/commandline/logs/
> 
> Note that fail2ban is not better than our currently implmented rate limiting as far as I understand it.

Well fail2ban essentially blocks the IP in question for everything; you can also log it separately and have generally more flexibility of how to handle bans. 

The current “rate limiting” in uptime-kuma cannot be configured and if an IP is “rate-limited” then only for this specific instance; while at the same time you could have a viable interest to block this IP for everything. 

fail2ban is a neat tool, versatile and I can only recommend you to look into it a bit (independently from uptime-kuma; there is no real coding required to hook fail2ban and uptime-kuma up)

**Comment by rezzorix** [comment]
@XHyperDEVX 
Mount the uptime-kuma log path to where your fail2ban can access it and then you should be able to get data and fail2ban working.

**Comment by XHyperDEVX** [comment]
> @XHyperDEVX Mount the uptime-kuma log path to where your fail2ban can access it and then you should be able to get data and fail2ban working.

again, HOW? How do I mount the path in a text file?

**Comment by CommanderStorm** [comment]
Sorry, I missed that.
What platform are you using? Node just logged to stdout, for pm2 see https://pm2.keymetrics.io/docs/usage/log-management/

**Comment by XHyperDEVX** [comment]
> Sorry, I missed that. What platform are you using? Node just logged to stdout (=> you need to pipe that to a file), for pm2 see https://pm2.keymetrics.io/docs/usage/log-management/

i use pm2.

when i look into the pm2 logs i just found, there are failed logins displayed, but unfortunately only with "IP=::1", why?

**Comment by chakflying** [comment]
There is nothing wrong with not understanding something. But maybe recognize that this is a community driven project, and instead of throwing every question you have out there expecting an answer, treat this as a learning opportunity and use the abundance of tools available online to search for answers first?

Why would the client IP address be localhost(::1)? Where are you accessing the server from? Maybe you are using a reverse proxy? If so, you can take a look at the Settings page -> Reverse Proxy -> the Trust Proxy setting.

**Comment by XHyperDEVX** [comment]
> There is nothing wrong with not understanding something. But maybe recognize that this is a community driven project, and instead of throwing every question you have out there expecting an answer, treat this as a learning opportunity and use the abundance of tools available online to search for answers first?
> 
> Why would the client IP address be localhost(::1)? Where are you accessing the server from? Maybe you are using a reverse proxy? If so, you can take a look at the Settings page -> Reverse Proxy -> the Trust Proxy setting.

i know this is a project that lives on its community. and i love it. uptime-kuma is awesome! i have been using it for a long time, and now i just need some help with this thing
nothing is meant to be demanding or nasty here :)

Yes, I use a reverse proxy. I run apache. the trust proxy setting is on off.

I do not know if you have a clue about apache, but this is the relevant part of my Apache VHost code for uptime-kuma:

```
ProxyPass / http://localhost:3001/
RewriteEngine on
RewriteCond %{HTTP:Upgrade} websocket [NC]
RewriteCond %{HTTP:Connection} upgrade [NC]
RewriteRule ^/?(.*) "ws://localhost:3001/$1" [P,L]
```

**Comment by XHyperDEVX** [comment]
i just found out that pm2 stores the logs in the root directory. at least for me. there i find the output of `pm2 logs` in an "uptime-kuma-out.log".

perfect, exactly what i need!

Now I just need to fix the IP problem, as a message above this one mentions.

**Comment by knightcott-paul** [comment]
> Problem solved

How?

**Comment by XHyperDEVX** [comment]
@knightcott-paul

I'm honest, I don't know anymore. A lot has happened in the meantime. I've moved my entire system to Docker and for security reasons I've made the login page for Uptimekuma only accessible locally, so it's not open to the outside world. That's why it's no longer an issue for me anyway.



Sorry about that.

**Comment by GAS85** [comment]
> I have not heard of other software usting this to protect non-ssh logins

Sure it is used for such kind of use cases. E.g. https://docs.nextcloud.com/server/latest/admin_manual/installation/harden_server.html#setup-fail2ban

I have all services that are exposed to internet protected with fail2ban regardless of own protection features.
