### ISSUE TITLE
Hide "Edit status page" and "Go to dashboard" when authentication is disabled.

### ISSUE THREAD

**Issue by aHalliday13** [louislam/uptime-kuma#3755]
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [x] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

UI Feature

### 🔖 Feature description

Currently when you are logged in and viewing a status page, you see two buttons to edit the page and go to the dashboard. This is fine, because for normal users, they can't see the buttons because they aren't logged in. However, when you disable the built in authentication to use your own, these buttons appear for everyone who sees the page. This is less than ideal, as preferably, I could protect the sensitive dashboard pages behind HTTP authentication, and then allow anyone to access the status pages. However, in this case non-authenticated users will now see two buttons which they have no use for. As such I suggest a way to be able to hide these buttons.

### ✔️ Solution

I think the easiest way to do it would be to just hide the buttons if authentication is disabled, but it might also make sense to implement it as a settings switch to hide and show the buttons.

### ❓ Alternatives

Just dealing with the buttons. This is a less than ideal situation as users who shouldn't be able to edit the dashboard have to look at two buttons that are useless to them and obstruct the flow of the status page.

**Comment by 2003Aditya** [comment]
Hey! please assign me this issue.

**Comment by Rai-Sahil** [comment]
Can I work on this?

**Comment by CommanderStorm** [comment]
You can work on this.
We don't assign people to issues ^^

See our contribution guide: https://github.com/louislam/uptime-kuma/blob/master/CONTRIBUTING.md

**Comment by homeautomaton** [comment]
Here's a css work-around for you:

```
.btn { display: none }
.btn-success { display: block }
```

**Comment by ericwooley** [comment]
If your here because you followed this [Authentik](https://goauthentik.io/integrations/services/uptime-kuma/) guide, you don't need to worry about this after all.

These buttons don't appear unless you have been on the dashboard of uptime kuma, even with auth disabled. 

If you start an incognito window, and go to your status page and login, you will not see buttons. Then if you login with authentik, and hit the dashboard, then go to the status page, you will see the buttons.

**Comment by aHalliday13** [comment]
Good to know, thanks! I'll close this issue.
