### ISSUE TITLE
Speedtest tracker

### ISSUE THREAD

**Issue by DeadSledge989** [louislam/uptime-kuma#3758]
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

New Monitor

### 🔖 Feature description

add a speedtest tool that tracks ur network speed over time and alert if something is wrong

### ✔️ Solution

add speedtest tracker

**Comment by CommanderStorm** [comment]
@DeadSledge989 
I think this is a duplicate of https://github.com/louislam/uptime-kuma/issues/744 (and its duplicates #3097 #1161)
If you agree, could you please close this Issue, as duplicates only create immortal zombies and are really hard to issue-manage?
If not, what makes this issue unique enough to require an additional issue? (Could this be integrated into the issue linked above?) ^^
