### ISSUE TITLE
weblate alerts again

### ISSUE THREAD

**Issue by AnnAngela** [louislam/uptime-kuma#3759]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### Description

https://weblate.kuma.pet/projects/uptime-kuma/uptime-kuma/#alerts

weblate alerts again, the i18n files cannot be updated. @louislam

**Comment by louislam** [comment]
Fixed. Weird, this time no conflicts, but the alert ask me to merge manually, because there are too many new commits.
