### ISSUE TITLE
Monitor Kafka Producer Enable Kafka SSL disabled after checking box and saving

### ISSUE THREAD

**Issue by dnltech2020** [louislam/uptime-kuma#3760]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### Description

when adding a new monitor type for kafka producer, there is an option to enable kafka ssl,  when checking the box to enable kafka ssl when I click on save the check box is unchecked.

### 👟 Reproduction steps

add new monitor fill out following

friendly name
kafka brokers
kafka topic anme
kafka producer message
check enable kafka SSL
leave the Kafka SASL option to none

then save and the enable kafka SSL check box is unchecked

### 👀 Expected behavior

when checking the enable kafka ssl that the check box stays checked no matter what

### 😓 Actual Behavior

when checking the enable kafka ssl and saving the check box becomes unchecked after saving.

### 🐻 Uptime-Kuma Version

1.23.1

### 💻 Operating System and Arch

docker

### 🌐 Browser

MS Edge 110.1587.41

### 🐋 Docker Version

k8s 1.27

**Comment by mhkarimi1383** [comment]
@louislam
@dnltech2020 

#3771 should address this issue

**Comment by mhkarimi1383** [comment]
CC: @louislam

I have no idea where is the problem, I have fixed some issues in ui/worker codes but problem persist :/

**Comment by mhkarimi1383** [comment]
@louislam 
The problem was more than this, I was not fully familiar with the ORM that used in uptime kuma

**Comment by CommanderStorm** [comment]
https://github.com/louislam/uptime-kuma/pull/3984 was merged and is available since `1.23.4` but did not get closed properly
=> closing it as completed. If this is a mistake, feel free to comment ^^
