### ISSUE TITLE
SQLITE_CONSTRAINT: FOREIGN KEY constraint failed

### ISSUE THREAD

**Issue by MisterCT42** [louislam/uptime-kuma#3761]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### Description

I saw that there was a new version so I did the described steps: https://github.com/louislam/uptime-kuma/wiki/%F0%9F%86%99-How-to-Update

But after updating everything was gone.. thankfully I made a backup right before updating. But the restore is showing this error:
![2023-09-18 16_14_16-Uptime Kuma and 12 more pages - Work - Microsoft​ Edge](https://github.com/louislam/uptime-kuma/assets/136058506/110ac6ed-025b-411b-8a13-8cf7b817410d)

### 👟 Reproduction steps

Restore backup after updating to latest version.

### 👀 Expected behavior

Restore the backup with all my monitors

### 😓 Actual Behavior

Error popup message that show: insert into `monitor_notification` (`monitor_id`, `notification_id`) values (11, '7') - SQLITE_CONSTRAINT: FOREIGN KEY constraint failed

### 🐻 Uptime-Kuma Version

1.23.2

### 💻 Operating System and Arch

Portainer

### 🌐 Browser

Chrome

### 🐋 Docker Version

Latest

### 🟩 NodeJS Version

Latest

**Comment by louislam** [comment]
Change to `help` as the backup feature is unmaintained and deprecated already.

**Comment by CommanderStorm** [comment]
> was trying to backup restore with override option and got all my monitors deleted. Are there any ways to restore them?

What did you do precicely?

**Comment by hvspa** [comment]
what i did is i exported the config, copy pasted one of the monitors' json, replaced the ID-s (+1 to the highest ID) and imported back with override option selected. then it started to complain about foreign keys. tried to import the original json, still same complaint, then wiped the databases, still same complaint about foreign keys

**Comment by hvspa** [comment]
what i did now, i deleted the `kuma.db` file, and then restarted the deployment, then imported the json again, and monitors appeared, but
1. they are not in groups, grouping them manually
2. my grpc monitors are down and UI does not allow me to edit them, when i click on them, nothing happen in the right frame of UI

**Comment by CommanderStorm** [comment]
Sorry to say, but the backup functionality is deprecated for a reason.
We recomend you to just backup the database instead in the UI.

Given that you deleted the db, there is nothing that can be fixed.

Things like groups, status pages, maintenances or the grpc monitor never got fully adopted into that feature.
The feature has been dropped in `v2.0` (#4500)

If you want to import existing data sources of monitors, please use a **third party tooling** like [AutoKuma](https://github.com/BigBoot/AutoKuma) or https://uptime-kuma-api.readthedocs.io/ instead

**Comment by hvspa** [comment]
> Sorry to say, but the backup functionality is deprecated for a reason. We recomend you to just backup the database instead in the UI.
> 
> Given that you deleted the db, there is nothing that can be fixed.
> 
> Things like groups, status pages, maintenances or the grpc monitor never got fully adopted into that feature. The feature has been dropped in `v2.0` (#4500)
> 
> If you want to import existing data sources of monitors, please use a **third party tooling** like [AutoKuma](https://github.com/BigBoot/AutoKuma) or https://uptime-kuma-api.readthedocs.io/ instead

thanks for the links, this will be indeed useful. ended up re-creating some kafka monitors, manually adding the grpc monitors' proto-s, some postgres connection strings, but the main monitors got recovered on a blank database, which was a day saver.
thanks again!

**Comment by thorr972** [comment]
Hello,

I inform you of a strange behavior.. but which allowed me to restore my database from a JSON backup.

I am currently using version Version: 1.23.16 (Frontend version: 1.23) under Docker (version 20.10.5+dfsg1, build 55c4c88).

Here is a procedure that has worked several times (I don't know why).

But I would invite you to make a copy of the "/app/data" folder anyway.

1) Delete all the contents of the "/app/data" folder.

2) Restart your container
3) On the authentication page, recreate your usual logins.

4) After authentication, go to Settings and make an export that you save wherever you want.

5) Try to import your JSON backup.

You will get an error ""insert into `monitor_notification` (`monitor_id`, `notification_id`) values (20, '2') - SQLITE_CONSTRAINT: FOREIGN KEY constraint failed"" the first time and then try again.

The second time, everything will be fine.

If someone can explain why it works.... I'm interested.

Best Regards
