### ISSUE TITLE
CacheableLookup was never used for http monitors

### ISSUE THREAD

**Issue by chakflying** [louislam/uptime-kuma#3762]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### Description

Adding a logging function to the `CacheableDnsHttpAgent`

```js
// cacheable-dns-http-agent.js#40
        setInterval(() => {
            console.log("Cache entries: ", this.cacheable._cache.size);
            console.log(this.cacheable._cache.entries());
        }, 10000);
```

reveals that no entries were ever added for the urls visited by http monitors. I suspect this is because even though the agent is installed in `http.globalAgent`, the monitors use their own agent, which is not affected by this. 

Monitor types `steam` and `docker` explicitly uses the `CacheableDnsHttpAgent` so I assume it's working there, but I did not test to confirm.

Given that `cacheable-lookup` caused issues with IPv6 previously, and we now have `nscd` for containers, I think it would be better to just completely remove it in `2.0.0`.

### 👟 Reproduction steps

1. Enable DNS Cache for HTTP(s) monitors in Settings
1. Add logging function to `CacheableDnsHttpAgent`
2. Create an http monitor visiting an internet url
3. Observe that the specified domain does not appear in the cache

### 👀 Expected behavior

http monitors should have their DNS entries cached when

### 😓 Actual Behavior

http monitors DNS entries are not cached

### 🐻 Uptime-Kuma Version

master

### 💻 Operating System and Arch

Windows 11 x64

### 🌐 Browser

Mozilla Firefox

### 🟩 NodeJS Version

18.17.1

**Comment by CommanderStorm** [comment]
Good catch!
