### ISSUE TITLE
Email body and subject does not match

### ISSUE THREAD

**Issue by theme1256** [louislam/uptime-kuma#3766]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### Description

The header/subject of the email and the body reference two different monitors.
The body contains the correct reference.
![image](https://github.com/louislam/uptime-kuma/assets/9347753/17234ae3-b49e-4917-9ddc-bbf8872bcd91)
We only use email notifications, so I don't know if others might be experiencing the same issue.

### 👟 Reproduction steps

No idea, the only thing the monitors have in common is the notification.

### 👀 Expected behavior

The header/subject of the email should reference the correct monitor.

### 😓 Actual Behavior

The header/subject of the email references another monitor.

### 🐻 Uptime-Kuma Version

1.23.0

### 💻 Operating System and Arch

AMI2, Docker and Debian 11, Docker

### 🌐 Browser

Chrome 116.0.5845.188

**Comment by chakflying** [comment]
This was reported before and is likely because the Gmail client incorrectly groups emails with different subjects together.

**Comment by theme1256** [comment]
Nope.
The screenshot is a single email with the wrong subject.
I've never seen gmail group emails with seperate subjects, only if the subject starts with eg. "Re:" or "Fwd:".
gmail never groups emails from uptimerobot, also when they are send with seconds between them.

**Comment by CommanderStorm** [comment]
The issue Nelson is refering to is https://github.com/louislam/uptime-kuma/issues/3660
Please make sure that this is not the case by clicking the option to view the original as mentioned in said issue.

Debugging this further:
- Could you share how you configured your templating?
 => I want to make sure, that this is not a duplicate of https://github.com/louislam/uptime-kuma/issues/3184
- How are these monitors related? Are they groups/... ?

**Comment by theme1256** [comment]
Inspecting the original content of the email, ok, the subject is correct.
But WFT? I've never seen this behavior from gmail, it normally never groups messages, unless the subjects are basically equal.
I've changes the subjects to be "{{NAME}} is now {{STATUS}}!" and now it seams to work fine, so I guess because all the text was in brackets gmail thought it was related?

**Comment by isradelatorre** [comment]
The same thing happened to me when receiving notifications in gmail and I was able to fix it by editing the subject and adding {{NAME}} is now {{STATUS}} as suggested by @theme1256
