### ISSUE TITLE
WebSocket Error with Uptime-Kuma

### ISSUE THREAD

**Issue by redat00** [louislam/uptime-kuma#3769]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

Hello ! 

I'm trying to deploy uptime-kuma using a .deb package, unfortunately I'm not successful at it and I'm encountering some errors. 

Everything goes well until I start the application, it start well, but I'm redirect to the `/setup-database` URL and getting a Not Found error. When opening the Console I can see a whole lot of errors related to websocket : 

```
Failed to connect to the backend. Socket.io connect_error: timeout index-919ccbd7.js:20:13827
The connection to wss://[url]/socket.io/?EIO=4&transport=websocket was interrupted while the page was loading.
```
The same error happens either I'm running being nginx as reverse-proxy, or not, so it's not the reverse proxy.

While I know building a .deb it not really a conventional, neither a recommended way to do it, I would just like some help to understand what might be causing this error. 

I'm setuping uptime-kuma the same way in both cases : 
```
npm ci --production && npm run download-dist
```

Perhaps some packages are installed globally when doing `npm ci --production` and so they're not present on the end machine ? 

Thanks in advance for any help ! 

### 🐻 Uptime-Kuma Version

1.23.1

### 💻 Operating System and Arch

Debian Bullseye

### 🌐 Browser

FIrefox 117.0.1

### 🟩 NodeJS Version

16.20.2

**Comment by CommanderStorm** [comment]
Why would you like to install it as a `.deb` package? Where are you getting said package from? (we are not publishing to apt afaik)

Have you read through https://github.com/louislam/uptime-kuma/wiki/Reverse-Proxy ?

**Comment by louislam** [comment]
>Where are you getting said package from? (we are not publishing to apt afaik)

> While I know building a .deb it not really a conventional

It seems that he is building the .deb.

If you see `/setup-database`, it is wrong, it is unreleased feature. 

Please follow the installation guide in the README.md carefully. 

I don't know why you need to make .deb, I would recommend that you should make a `.sh` script instead, in case you want to one-click-install on multiple machines.

**Comment by redat00** [comment]
Heyy! 

I'm building a .deb package because it's easier for us to deploy, or at least make it available to multiples hosts in our environment. I was able to get it working, turns out the `git checkout v[version]` IS needed. So this is entirely my fault. 

Now I have a nice working `.deb` package of uptime_kuma ! 

Thanks for your help though !

Btw if you wanted to build one for the project, I could give a hand, but it's not related to this issue.

**Comment by 250king** [comment]
Will, I have a special usage, because my CDN provider isn't support websocket (In fact it is support but the connection will be broken after about 15 seconds. The CDN provider requeire you use other service for websocket that common HTTP service isn't support but it is too expensize), so can Uptime-Kuma use other method such as Event Source?

![Image](https://github.com/user-attachments/assets/7ed42287-dabb-4f10-a947-da505f0aab86)

**Comment by 250king** [comment]
huh? you means that my website should be naked? i don't want because i afraid someone know my website IP and attack it (

**Comment by louislam** [comment]
Uptime Kuma is using socket.io which supports polling if WebSocket is not available in the first place.

> In fact it is support but the connection will be broken after about 15 seconds.
 
I think you have to completely disable WebSocket in your CDN.

Or if you have an ability to modify Uptime Kuma, you can force the transport to `polling`:

https://socket.io/docs/v3/client-initialization/#transports

**Comment by 250king** [comment]
The main problem is that client side try to connect to my server by websocket. The CDN will return 400 in normal but the client side still continue to connect by websocket instead of polling? 🤔

**Comment by 250king** [comment]
Oh, I get the detail

![Image](https://github.com/user-attachments/assets/d4b6d4e9-aa14-43da-949c-ec40e2a10344)

![Image](https://github.com/user-attachments/assets/0bf70bce-ff3c-44ad-a631-8f6a06fb485d)
