### ISSUE TITLE
Make a discord server?

### ISSUE THREAD

**Issue by Pranjal-SB** [louislam/uptime-kuma#3770]
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

Other

### 🔖 Feature description

any plans on making a discord server for this awesome af project?

### ✔️ Solution

best case would be that you guys make a discord server for this project.

**Comment by CommanderStorm** [comment]
Why do you think making a discord server would benefit the project?
We already have GitHub Issues/PRs and a Subreddit.

**Comment by louislam** [comment]
Regardless of Uptime Kuma, I am personally against these non-indexable platforms like Discord server and Telegram group for sharing information to the public, despite there are already a lot of people using it.

At least I think searchable in the search engine is very important for software projects. It is the usual way and easiest for people to find the information.

Don't get me wrong, Discord is a good tool for gaming or chatting, I use it too. It is just not really suitable for the case.

If you need helps or questions, just do it here.

**Comment by rezzorix** [comment]
> Regardless of Uptime Kuma, I am personally against these non-indexable platforms like Discord server and Telegram group for sharing information to the public, despite there are already a lot of people using it.
> 
> At least I think searchable in search engines is very important for software projects. It is the usual way and the easiest way for people to find the information.
> 
> Don't get me wrong, Discord is a good tool for gaming or chatting, I use it too. It is just not really suitable for the case.
> 
> If you need helps or questions, just do it here.

This!
People underestimate the damage discord and this kind of non-indexable platforms do to an open and collaborative internet. 

So NO to Discord is the best answer a developer and/or community can give.

**Comment by Pranjal-SB** [comment]
> Regardless of Uptime Kuma, I am personally against these non-indexable platforms like Discord server and Telegram group for sharing information to the public, despite there are already a lot of people using it.
> 
> At least I think searchable in search engines is very important for software projects. It is the usual way and the easiest way for people to find the information.
> 
> Don't get me wrong, Discord is a good tool for gaming or chatting, I use it too. It is just not really suitable for the case.
> 
> If you need helps or questions, just do it here.

ohk np and now that I think about it you are right.
sry for this dumb issue 😅.
