### ISSUE TITLE
Is it possible to read Kuma.db data using any manager?

### ISSUE THREAD

**Issue by alejandromiller21** [louislam/uptime-kuma#3772]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

Would cloudbeaver or dbveaber be able to read Kuma.db data?

### 🐻 Uptime-Kuma Version

1.23.2

### 💻 Operating System and Arch

Ubuntu

### 🌐 Browser

Google Chrome 

### 🐋 Docker Version

K8S

**Comment by CommanderStorm** [comment]
The v1 version of `uptime-kuma` does offer `SQLite` as a database.
The v1 version of `uptime-kuma` does offer `SQLite`, `embedded-mariadb` (as in: running in the same container) and external `mariadb` as a database.

Any software compatible with said databases will allow you to access/modify the content of said database.
If you have a look at https://github.com/louislam/uptime-kuma/blob/master/CONTRIBUTING.md#tools, we have even linked [`DBeaver Community`](https://dbeaver.io/download/) under "SQLite GUI tool"

**Comment by kokofixcomputers** [comment]
You can use SQLite tool (download here: https://www.sqlite.org/download.html use the Precompiled Binaries) and run the commands.

**Comment by alejandromiller21** [comment]
Thanks!!
