### ISSUE TITLE
Kuma server-side link status monitoring

### ISSUE THREAD

**Issue by jaclas** [louislam/uptime-kuma#3773]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

I have Kuma installed on my home server, it monitors many external servers where my applications are running. Unfortunately, my home connection is unreliable and often Kuma signals problems with no response from the configured servers, but not because they are offline, but that offline is the Kuma server. 

Is it possible to solve this somehow? Can Kuma check the status of the global connection, e.g. by pinging to the DNS servers?

### 🐻 Uptime-Kuma Version

1.23.2

### 💻 Operating System and Arch

Ubuntu 22.04

### 🌐 Browser

Chrome

### 🐋 Docker Version

20.10.14

**Comment by mabed-fr** [comment]
Hello, You are experiencing the concerns of many people. One of the solutions that can help you out will be the implementation of:

https://github.com/louislam/uptime-kuma/pull/1236

You create a "parent" monitor (ping google) and if this monitor is down the other services will not be defined as down

**Comment by jaclas** [comment]
Thx, but why is this hanging around so long and not merged? This is a very useful feature, I don't understand why there is resistance to implementing it.

**Comment by CommanderStorm** [comment]
See https://github.com/louislam/uptime-kuma/pull/2693#issuecomment-1413794719 for further context

Said feature would need a heavy rebase to make it shippable.
It for example does not use the new monitor syntax (not piling everything into `monitor.js`) or the new db-independent migrations.
