### ISSUE TITLE
End user notification

### ISSUE THREAD

**Issue by TargetCrafter** [louislam/uptime-kuma#3775]
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

New Notification, UI Feature

### 🔖 Feature description

Atlasian statuspage allows for end users to subscribe to a page, it would be nice if this was possible in Uptime-Kuma too.

### ✔️ Solution

I would like to see a "Subscribe" button that can be enabled for status pages. When a user clicks on the button, checkboxes appear in front of the monitors so that the user can select for what monitors they would like to be notified. After this the click a confirm button after which they are asked for their email. After submitting this they get added to a list with their notification preference.

Whenever a monitor goes offline the users that have selected to be notified will get a customized email or trough another notification channel that contains what monitor is down and extra information if available.
The users can unsubscribe by clicking a link in the email which leads them to their notification preferences.

### ❓ Alternatives

If the update notification preferences (selecting what monitors send notifications) is too much the users could also subscribe to an entire page which would be easier to implement, but i think that the preferences would add a lot of value.

### 📝 Additional Context

Examples:
[Atlasian](https://jira-software.status.atlassian.com/#)
[NinjaOne](https://status.ninjaone.com/)

**Comment by CommanderStorm** [comment]
@TargetCrafter 
I think this is a duplicate of https://github.com/louislam/uptime-kuma/issues/916 and its duplicates like https://github.com/louislam/uptime-kuma/issues/3022
If you agree, could you please close this Issue, as duplicates only create immortal zombies and are really hard to issue-manage?
If not, what makes this issue unique enough to require an additional issue? (Could this be integrated into the issue linked above?) ^^

**Comment by TargetCrafter** [comment]
You're right, i didn't find those before. I'll add my requests to [#916](https://github.com/louislam/uptime-kuma/issues/916).
[#3022](https://github.com/louislam/uptime-kuma/issues/3022) seems to be stale since june, so i think that one should be closed as it is basically the same as [#916](https://github.com/louislam/uptime-kuma/issues/916).
