### ISSUE TITLE
Missing signature key - Docker

### ISSUE THREAD

**Issue by RayneYoruka** [louislam/uptime-kuma#3777]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

Trying to update or simply trying to pull the image from the docker hub gives missing signature key error.

### 📝 Error Message(s) or Log

[root@Server /]# docker pull louislam/uptime-kuma:1
Trying to pull repository docker.io/louislam/uptime-kuma ...
missing signature key

### 🐻 Uptime-Kuma Version

1.17.1

### 💻 Operating System and Arch

CentOS7 - amd64

### 🌐 Browser

Firefox 117.0.1

### 🐋 Docker Version

 1.13.1 / Api 1.26

**Comment by CommanderStorm** [comment]
Cannot reproduce:
![image](https://github.com/louislam/uptime-kuma/assets/26258709/c0b6ecbb-98b1-4a57-a926-db732cd5d264)

Docker 1.13.1 is quite old. An update to your runtime is ikely to fix this issue

**Comment by CommanderStorm** [comment]
see https://github.com/ansible/ansible-runner/issues/1095 which is reporting the same fix

**Comment by RayneYoruka** [comment]
It seems that I will have to completely remove docker and then use a different repo to upgrade it. What a mess

**Comment by CommanderStorm** [comment]
Yes, and that is likely a good thing, given the improvements that have been made like buildx/...

Could you close this issue, as this is very likely not caused by us (you an reopen issues in the future if it turns out we did something wrong)

**Comment by RayneYoruka** [comment]
I'll do that, thank you.

**Comment by louislam** [comment]
> It seems that I will have to completely remove docker and then use a different repo to upgrade it. What a mess

It is a typical Linux experience, I would say. That is why Docker exists to make you less painful. I bundled everything you need in a single Docker image, so you don't need to.

**Comment by ZhiboWong** [comment]
> Cannot reproduce: ![image](https://private-user-images.githubusercontent.com/26258709/269425397-c0b6ecbb-98b1-4a57-a926-db732cd5d264.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkyMTQ4NjksIm5iZiI6MTcxOTIxNDU2OSwicGF0aCI6Ii8yNjI1ODcwOS8yNjk0MjUzOTctYzBiNmVjYmItOThiMS00YTU3LWE5MjYtZGI3MzJjZDVkMjY0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI0VDA3MzYwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk2YTY0MWY0MmQ0NTU5YTY3ODkyMjY4ODhiNGVhMzI5MjY5N2FmOTRlMWJiOWY3OWY1NGZiY2ZiZDQzZTg5MDUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.al6idX20ZIUY-mRuMp2NL-Z-__5FG3VpGOk0MpydfRQ) ![image](https://private-user-images.githubusercontent.com/26258709/269425868-fc80cb90-1e7c-4118-b4ba-cc85010036b0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkyMTQ4NjksIm5iZiI6MTcxOTIxNDU2OSwicGF0aCI6Ii8yNjI1ODcwOS8yNjk0MjU4NjgtZmM4MGNiOTAtMWU3Yy00MTE4LWI0YmEtY2M4NTAxMDAzNmIwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI0VDA3MzYwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNiNWQyOTQ5NTZiN2RmYzNmZWYwMTg4MGQzNWYyZjk5ZjllODc3M2YwZjE1NzFlZjdjYzI5NTU5MDA3MzcxOTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ca3rXi0w4vvgYQi-0_k6V95_G-BaSIWsv7EUL3aaifY)
> 
> Docker 1.13.1 is quite old. An update to your runtime is ikely to fix this issue

How to update runtime?

**Comment by CommanderStorm** [comment]
@ZhiboWong 
this depends on your installation path and is quite google-able.
Please try to resolve issues yourself first before asking for help and provide more context about what you tried and what your environment is if that does not work.

**Comment by ZhiboWong** [comment]
> @ZhiboWong this depends on your installation path and is quite google-able. Please try to resolve issues yourself first before asking for help and provide more context about what you tried and what your environment is if that does not work.

I have searched "How to update docker runtime" but nothing worthy. My OS is CentOS 7.

```shell
[root@iZ2ze0adjult3m3h0zfmg4Z ~]# yum update docker
Loaded plugins: fastestmirror, product-id, search-disabled-repos, subscription-manager

This system is not registered with an entitlement server. You can use subscription-manager to register.

Loading mirror speeds from cached hostfile
base                                                                                                                                                                               | 3.6 kB  00:00:00     
epel                                                                                                                                                                               | 4.3 kB  00:00:00     
extras                                                                                                                                                                             | 2.9 kB  00:00:00     
updates                                                                                                                                                                            | 2.9 kB  00:00:00     
No packages marked for update
[root@iZ2ze0adjult3m3h0zfmg4Z ~]# docker -v
Docker version 1.13.1, build 7d71120/1.13.1
```

**Comment by louislam** [comment]
> My OS is CentOS 7.

CentOS 7 comes with a very old version of Docker, you should uninstall `docker` and then install `docker-ce`.

You should follow the official guide.

https://docs.docker.com/engine/install/centos/


Side note:
CentOS 7 will reach its end of life on June 30, 2024, which is 5 days from now. I would recommend you to start with a newer OS, like Debian or Ubuntu, if possible.

**Comment by ZhiboWong** [comment]
> > My OS is CentOS 7.
> 
> @ZhiboWong
> 
> CentOS 7 comes with a very old version of Docker, you should uninstall `docker` and then install `docker-ce`.
> 
> You should follow the official guide.
> 
> https://docs.docker.com/engine/install/centos/
> 
> Side note: CentOS 7 will reach its end of life on June 30, 2024, which is 5 days from now. I would recommend you to start with a newer OS, like Debian or Ubuntu, if possible.

Thx for your sugggestion. Now I face a new problem.
```shell
[root@iZ2ze0adjult3m3h0zfmg4Z ~]# yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo

Loaded plugins: fastestmirror, product-id, subscription-manager

This system is not registered with an entitlement server. You can use subscription-manager to register.

adding repo from: https://download.docker.com/linux/centos/docker-ce.repo
grabbing file https://download.docker.com/linux/centos/docker-ce.repo to /etc/yum.repos.d/docker-ce.repo
Could not fetch/save url https://download.docker.com/linux/centos/docker-ce.repo to file /etc/yum.repos.d/docker-ce.repo: [Errno 14] curl#7 - "Failed to connect to 2a03:2880:f111:83:face:b00c:0:25de: Network is unreachable"
```
I am sure this problem caused by Chinese FW. Although facing problem either , I continue establishing proxy for using oversea repo.  Can you give me repo which I can use in China ?
