### ISSUE TITLE
Monitor Item Duplicate Checker

### ISSUE THREAD

**Issue by tim1014** [louislam/uptime-kuma#378]
**Is it a duplicate question?**
Not in sight.

**Is your feature request related to a problem? Please describe.**
After adding the JSON import/export function. It becomes an issue.

**Describe the solution you'd like**
Add function to check if the monitor exists. Warn the user that the monitor is already created.

At JSON import/export, let the user to choose to keep or discard all the existing monitors.
Also, checks duplicated monitors when importing JSON config.

**Comment by Ponkhy** [comment]
Thanks, i gonna try to make a PR about it this weekend.

**Comment by Saibamen** [comment]
Resolved by https://github.com/louislam/uptime-kuma/pull/382?

**Comment by deefdragon** [comment]
> Resolved by #382?

Somewhat, but checking for duplicate named monitors, or monitors with the same endpoints would also be nice during creation/as a button from settings.
