### ISSUE TITLE
X-Forwarded-Host Problem [Reverse Proxy, Apache]

### ISSUE THREAD

**Issue by XHyperDEVX** [louislam/uptime-kuma#3782]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

I have a status page with its own domain name. status.url.tld.
my apache configuration also works, so status.url.tld is forwarded with X-Forwarded host and everything works.

EXCEPT I enable "Trusted Proxy" in the Uptime Kuma settings. [I need this function for something else].
Now the whole thing doesn't work, status.url.tld just redirects me to the dashboard.

Why?

This is my status.url.tld Apache code:

```
ProxyPass / http://localhost:3001/ 

ProxyPreserveHost On
RequestHeader set X-Forwarded-Host: status.url.tld

RewriteEngine on
RewriteCond %{HTTP:Upgrade} websocket [NC]
RewriteCond %{HTTP:Connection} upgrade [NC]
RewriteRule ^/?(.*) "ws://localhost:3001/$1" [P,L
```

Other than that, everything is set up as it should be:
![image](https://github.com/louislam/uptime-kuma/assets/68189420/72eb70c6-eb63-4927-b422-e6c1fe840577)
[here of course with the correct domain]

![image](https://github.com/louislam/uptime-kuma/assets/68189420/3faa9b9e-9e7f-45e9-ab86-c53e3c810944)

### 📝 Error Message(s) or Log

-

### 🐻 Uptime-Kuma Version

1.23.2

### 💻 Operating System and Arch

Debian 11

### 🌐 Browser

Edge

### 🐋 Docker Version

No Docker

### 🟩 NodeJS Version

v18.14.2

**Comment by louislam** [comment]
Maybe it is a related pr: #3726

**Comment by XHyperDEVX** [comment]
Yea, that solved my problem. Thanks a lot!
