### ISSUE TITLE
Is there support for webhook notifications to send different REST API methods?

### ISSUE THREAD

**Issue by roltairtheprotogen** [louislam/uptime-kuma#3783]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

I'm working on setting up Uptime Kuma to work with Atlassian Statuspage (I know Kuma has a statuspage itself but this fits my situation better) to relay uptime/downtime. To do this I was going to use the webhook notification method however I noticed by the looks of it that Kuma only supports the POST method, is there a way to send in a different method like PATCH which is what Atlassian requires?

Any help is much appreciated!

### 🐻 Uptime-Kuma Version

1.23.2

### 💻 Operating System and Arch

Ubuntu 22.04.3 LTS

### 🌐 Browser

Opera GX

### 🐋 Docker Version

Docker 22.04.6

**Comment by CommanderStorm** [comment]
No, this is currently not possible. See https://github.com/louislam/uptime-kuma/issues/2413 for a possible solution.
As always: [Pull Requests](https://github.com/louislam/uptime-kuma/blob/master/CONTRIBUTING.md) welcome.

I think this is a can be integrated into this feature request https://github.com/louislam/uptime-kuma/issues/2413
If you agree, could you please close this Issue, as duplicates only create immortal zombies and are really hard to issue-manage.

**Comment by roltairtheprotogen** [comment]
I agree and have left a comment on there, thanks!
