### ISSUE TITLE
Push Monitor reporting duplicate "down" state

### ISSUE THREAD

**Issue by iTerminate** [louislam/uptime-kuma#3787]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### Description

When reporting a "down" state using push monitor URL it will report down once for the push and once more for the monitor timeout. 

### 👟 Reproduction steps

1. Create a push monitor with a timeout of 30 seconds for example. 
1. Run the push url for the monitor to report an up state. 
1. Run the push url again but change the status parameter https://uk-url/api/push/pushKEY?status=down&msg=issue&ping=
1. Wait 30 seconds or monitor timeout time. 
1. Another down state will show up. 

### 👀 Expected behavior

Once `down` is reported by push monitor, the push monitor no longer needs to report a duplicate `down` state until the next `up` state is pushed. 

### 😓 Actual Behavior

Duplicate down state of monitor resulting in duplicate notifications. 

### 🐻 Uptime-Kuma Version

1.23.1

### 💻 Operating System and Arch

Linux/Centos

### 🌐 Browser

Google Chrome

### 🟩 NodeJS Version

v18.12.1

**Comment by louislam** [comment]
It is by our design, change to `feature-request`

**Comment by iTerminate** [comment]
Since this is now a feature request, what would be the best approach to implement this? 
Here are some potential approaches I thought of:
1. All push monitors would have the new behavior.
2. An attribute of a push monitor monitor would determine the behavior. 
3. System wide setting would determine behavior of all push monitors.

**Comment by chakflying** [comment]
Maybe you can explain your use case and why you think it should behave this way.

**Comment by iTerminate** [comment]
Yes the problem is two notifications per down state and a false additional down state in the monitor log.

**Comment by louislam** [comment]
As I said it is by design, because `Retries` and `Resend Notification if Down X times consecutively` all depend on this design. They are core features available for all monitor types. If only one down, it is unable to resend the notifications.

Changing the existing push monitor to your logic, I would say it is impossible. However, if you have a very strong reason, maybe it can be another new push monitor type, but so far I cannot see a strong reason.
