### ISSUE TITLE
Clickable link monitors aren't underlined when editing status page

### ISSUE THREAD

**Issue by BBaoVanC** [louislam/uptime-kuma#3795]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### Description

After enabling clickable link on a monitor, it shows as underlined on the status page to hint that it is a link. However, in the edit status page menu, it doesn't show any as underlined. This combined with #3794 makes it hard to tell if a monitor is clickable before saving.

### 👟 Reproduction steps

1. Have a monitor where clickable link is enabled (make sure you press Save on the entire page too)
   1. Go to "Edit Status Page"
   2. Press the settings cog next to the bbaovanc.com monitor
   3. Tick "Show Clickable Link"
      ![image](https://github.com/louislam/uptime-kuma/assets/17971474/ad196a22-e06c-4e2c-8b5a-8c68a1569bb1)
   4. Press Save in the bottom left of the entire page
3. View that it is underlined on the actual status page
   ![image](https://github.com/louislam/uptime-kuma/assets/17971474/1df7703b-4e45-4fc3-9d13-7b42b7efb518)
4. Click "Edit Status Page"
5. View that it is not underlined
   ![image](https://github.com/louislam/uptime-kuma/assets/17971474/543212d8-8467-4e47-8184-8f0a8eaf70f5)

### 👀 Expected behavior

Monitors with clickable link should be underlined in edit page

### 😓 Actual Behavior

They are not underlined in edit page

### 🐻 Uptime-Kuma Version

1.23.2

### 💻 Operating System and Arch

Debian 11

### 🌐 Browser

Firefox 117.0.1

### 🐋 Docker Version

Docker 24.0.6

**Comment by BBaoVanC** [comment]
> Hi, @BBaoVanC are you talking about this page? On this page, the underline is not present below the website name. Can you please help me by telling me that I am going in right way? I am new to open source and I want to solve this issue.

1. Go to "Edit Status Page"
2. Press the settings cog next to the bbaovanc.com monitor
3. Tick "Show Clickable Link"
   ![image](https://github.com/louislam/uptime-kuma/assets/17971474/ad196a22-e06c-4e2c-8b5a-8c68a1569bb1)
4. Press Save in the bottom left of the entire page

Now it should show the monitor as underlined, and you should be able to click it too. If you go back to "Edit Status Page", it's no longer underlined.

**Comment by nayangoyal** [comment]
I got that "Show Clickable Link" and I want to work on this issue can you assign this issue to me?

**Comment by BBaoVanC** [comment]
> I got that "Show Clickable Link" and I want to work on this issue can you assign this issue to me?

Only maintainers can assign an issue, but you can work on the issue yourself and make a pull request without being assigned to it.

**Comment by louislam** [comment]
> I got that "Show Clickable Link" and I want to work on this issue can you assign this issue to me?

Bug fix is always welcome.

Don't forget to read https://github.com/louislam/uptime-kuma/blob/master/CONTRIBUTING.md
