### ISSUE TITLE
Compatibility with  EKS version

### ISSUE THREAD

**Issue by rohith1312** [louislam/uptime-kuma#3804]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

Hello,

Good Day.
Our current version of Uptime Kuma is App Version 1.19.3 and Chart Version 2.4.3. Due to security vulnerabilities, we want to upgrade it to the latest version. App version: 1.23.1 and
chart version: 2.14.1, so I just want to know if the latest uptime Kuma version is compatible with our current EKS version: 1.23 and EKS version: 1.25 (which we are going to upgrade).

### 🐻 Uptime-Kuma Version

1.19.3

### 💻 Operating System and Arch

AWS amazon linux 2

### 🌐 Browser

Google Chrome

**Comment by CommanderStorm** [comment]
Instead of opening an issue, I would suggest you to try upgrading.
See https://github.com/louislam/uptime-kuma/wiki/%F0%9F%86%99-How-to-Update
