### ISSUE TITLE
Incorrect link to Windows Portable release

### ISSUE THREAD

**Issue by jaknz** [louislam/uptime-kuma#3807]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### Description

README.md has a direct link to download the Windows Portable release, but the link is invalid. Looks like it's been replaced and removed, maybe?

https://github.com/louislam/uptime-kuma#windows-portable-x64

### 👟 Reproduction steps

Click the download link for Windows Portable

### 👀 Expected behavior

Download a file

### 😓 Actual Behavior

Github 404 file not found error

### 🐻 Uptime-Kuma Version

1.23.1

### 💻 Operating System and Arch

Windows 11

### 🌐 Browser

N/A

### 🐋 Docker Version

N/A

### 🟩 NodeJS Version

N/A

**Comment by CommanderStorm** [comment]
See https://github.com/louislam/uptime-kuma/releases/download/1.23.1/uptime-kuma-windows-x64-portable-1.23.1-2.zip instad (difference is the `-2`)
