### ISSUE TITLE
Remote workers

### ISSUE THREAD

**Issue by samip5** [louislam/uptime-kuma#381]
**Is it a duplicate question?**
No

**Is your feature request related to a problem? Please describe.**
I'm frustrated when I want to be able to monitor my endpoints from different networks.

**Describe the solution you'd like**
I would like to see an worker approach where I could deploy an remote worker on those different networks and then get information on the monitor from each worker. If it fails from one worker, I should be able to get a notification about it even if it works from others.

**Describe alternatives you've considered**
None

**Comment by Ponkhy** [comment]
Duplicate of #279

**Comment by samip5** [comment]
Oh, it seems that I didin't know what to search for properly.
