### ISSUE TITLE
Unable to set maintenance mode - Invalid time value

### ISSUE THREAD

**Issue by AzureInformatique** [louislam/uptime-kuma#3811]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

Hi,

When I try to add maintenance to the system regardless of the value inserted I get an Invalid time value error, do you have a solution?

Thanks a lot

### 📝 Error Message(s) or Log

![Error](https://github.com/louislam/uptime-kuma/assets/124894927/d463f610-0b3f-4bee-9b95-2ea7fce8bbce)

### 🐻 Uptime-Kuma Version

1.23.2

### 💻 Operating System and Arch

Docker

### 🌐 Browser

Chrome

### 🐋 Docker Version

Latest

**Comment by JulienAubert9** [comment]
Hello,

We have same issue to create a new maintenance window (error with time value).

But on our side, we don't see the previous configured maintenance anymore, and they are working fine we can see them in the history. Strange...

**Comment by sysadminafterdark** [comment]
I can confirm that I am having this issue as well with status.sysadminafterdark.com. I'm running Amazon Linux 2023 with the latest Docker-CE and UptimeKuma release. I can confirm both the host and container time is correct and the timezone is defined as an environmental variable. It is also correct in Settings > General > Timezone. No matter which timezone I select, I receive the error "Invalid Time Value". I'm certain this may be a bug. Any news relating to this? Thanks!

**Comment by AzureInformatique** [comment]
Bonjour louislam/uptime-kuma,

NOUS VOUS REMERCIONS D'AVOIR CONTACTÉ AZURE INFORMATIQUE !
Notre équipe dédiée examine actuellement votre requête, et nous
nous engageons à vous fournir une réponse complète dans les
meilleurs délais.

Si vous souhaitez fournir des informations supplémentaires,
n'hésitez pas à répondre directement à ce message.

Cordialement,
Le service client d'AZURE INFORMATIQUE

**Comment by sysadminafterdark** [comment]
> We have not been able to reproduce this in any development setting. That you have set an enviornment variable might be a clue. What have you set there? Looking at the environment variables we offer, I don't see one that interacts with time https://github.com/louislam/uptime-kuma/wiki/Environment-Variables

Heya! Thanks for your reply! I have my entire launch script here with instructions to reproduce my environment: https://gitlab.sysadminafterdark.com/sysadminafterdark/afterdark-uptimekuma-launch-script

Can you spin up a quick instance and try to reproduce? I can also grab logs for you if need be, just let me know. Thanks!

**Comment by sysadminafterdark** [comment]
Whoops! You’re right. I forgot to push my changes to git last night while fiddling with things. I added 

environment:
   - TZ=America/Detroit 
To both containers in my docker compose file because it WAS incorrect. If that is not the correct course of action, I can remove it once home and try again. 

I can confirm the configuration hosted currently on my git still exhibits this issue - I was just trying to troubleshoot on my own before posting here. Thanks!

**Comment by CommanderStorm** [comment]
Sorry, but really cannot reproduce..

![image](https://github.com/louislam/uptime-kuma/assets/26258709/55d7a5b5-186d-4d96-a669-58747d53a6d9)
![image](https://github.com/louislam/uptime-kuma/assets/26258709/bbaba68f-7524-45d1-8fb7-e8ba56dfb643)

**Comment by CommanderStorm** [comment]
unrelated note regarding these very spammy `[Snyk] Security upgrade` mentions above:

@ITSecOps-404 @djtms @souuuf @GTVolk @rossedlin @BuloZB @Blue-Gamer48

Please configure Snyk in a way which is not so spammy and, most importantly, does not spam random issues. **This is making reading comments on them worse.**

@lili2311 @PeterSchafer (@snyk/cli is codeowner and there are no issues for https://github.com/snyk/actions => no good way to contact you people for this)
**Please disable this spam**. I don't even know why this spam exists (the constant mentioning comes from seemingly random, out of date/abandoned forks).
Do you have a whitelist, where we can apply to be not mentioned anymore?

**Comment by sysadminafterdark** [comment]
> Sorry, but really cannot reproduce..
> 
> Without `TZ=America/Detroit`
> With `TZ=America/Detroit`

Let me bang on this a bit once I get home. Worst case, I’ll blow away the server and try anew. Since I did a bit of automation, this should only take me a few minutes to rebuild. Please stand by.

**Comment by sysadminafterdark** [comment]
> Sorry, but really cannot reproduce..
> Without `TZ=America/Detroit`
> With `TZ=America/Detroit`

I just finished blowing away my instance and resetting things up. Everything now works as expected. That is VERY weird. I ran my git script as is without any TZ modification. @AzureInformatique and @JulienAubert9 - if you are still experiencing this issue, perhaps a fresh install is on the books. Please feel free to use my script located above if you need a jumpstart getting back online. I wonder what the common denominator between the three of us was that resulted in that popup.

**Comment by CodeMeZone** [comment]
I have this issue, using the unRAID template.

**Comment by CommanderStorm** [comment]
Without being able to reproduce this issue, we can't relally help here..
I don't know where this is coming from or how to get into this state..

Maybe (kind of doubt it, but anyway) related (because of timezone handling): https://github.com/Hexagon/croner/releases/tag/8.0.0

If somebody can somewhat-regularly reproduce this, please record a screencapture via https://gifcap.dev/ and post how you want to add a maintenance in this thread. ^^
Please also include:
- what the timezone + time is inside/on the docker contaienr/host
- what the timezone is set to inside the settings

**Comment by Hexagon** [comment]
Older versions of croner has a bug related to time zones AKDT/AKST and AST. Could this be it? Fixed in croner 7.x and 8.x.  

7.x is for node versions prior to 18.

**Comment by CommanderStorm** [comment]
@Hexagon
None of the reports have mentioned using `AKDT`/`AKST`/`AST`, only timezones like `America/Detroit` which are not affected by said cange

=> This is the reason I stated above that I am not quite convinced that this is the case…
=> recording a [screen capture](https://gifcap.dev/) as mentioned above is the best way we can see possible differences in reproduction
=> hopefully making this reproducible

**Comment by sassanix** [comment]
How were you able to fix this? 

I too am getting invalid time data.

![image](https://github.com/louislam/uptime-kuma/assets/39465071/6bbce580-0254-4a4b-bae4-3867cdc2f028)


I don't have any environments set in docker compose.

**Comment by sassanix** [comment]
I made post here which I belive is the same issue:  https://github.com/louislam/uptime-kuma/issues/4930
