### ISSUE TITLE
startpage.com failing with `incorrect header check` using plain HTTP(s) monitor

### ISSUE THREAD

**Issue by vincejv** [louislam/uptime-kuma#3816]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### Description

Host https://www.startpage.com never goes online and fails with the error `incorrect header check`, however when using Chromium as the Monitor type, it no longer has this issue.
Reported earlier on a closed issue (host not specified on the issue) that was supposed to be fixed: https://github.com/louislam/uptime-kuma/issues/2475

### 👟 Reproduction steps

1. Create an HTTP Monitor
2. Set the url to https://www.startpage.com
3. Monitor reports the website as `incorrect header check` despite being online

### 👀 Expected behavior

Should say `200 - OK` if the website is online

### 😓 Actual Behavior

Keeps on reporting website is down even if it's accessible

### 🐻 Uptime-Kuma Version

1.23.2

### 💻 Operating System and Arch

OpenWrt 22.03.5 r20134-5f15225c1e

### 🌐 Browser

Chrome 117.0.0.0

### 🐋 Docker Version

Docker version 20.10.22, build 3a2c30b

### 🟩 NodeJS Version

v16.20.2

### 📝 Relevant log output

```shell
2023-09-29T11:51:12+08:00 [MONITOR] WARN: Monitor #14 'Startpage': Failing: incorrect header check | Interval: 60 seconds | Type: http | Down Count: 0 | Resend Interval: 0
2023-09-29T11:52:13+08:00 [MONITOR] WARN: Monitor #14 'Startpage': Failing: incorrect header check | Interval: 60 seconds | Type: http | Down Count: 0 | Resend Interval: 0
2023-09-29T11:53:15+08:00 [MONITOR] WARN: Monitor #14 'Startpage': Failing: incorrect header check | Interval: 60 seconds | Type: http | Down Count: 0 | Resend Interval: 0
```

**Comment by chakflying** [comment]
Most likely the target website is not compressing the body correctly, which led to decompression fail in `axios` (see https://github.com/axios/axios/issues/2406)

You can work around this by adding a custom header for your monitor:
```json
{
    "Accept-Encoding": "identity"
}
```

**Comment by vincejv** [comment]
@chakflying Thanks for the quick reply, this solved the issue!
