### ISSUE TITLE
Clarification on Recommended System Resources

### ISSUE THREAD

**Issue by kiarafbickers** [louislam/uptime-kuma#3817]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

I'm planning to use Uptime Kuma, and I wanted to get a better understanding of the recommended system resources. I've gone through the documentation, but I couldn't find specific recommendations on CPU, RAM, and other system requirements.

**Q:** What are the recommended system specifications (CPU, RAM) for running Uptime Kuma in a production environment?

Any insights or links to relevant documentation would be greatly appreciated. 

### 📝 Error Message(s) or Log

N/A

### 🐻 Uptime-Kuma Version

latest stable 

### 💻 Operating System and Arch

debian

### 🌐 Browser

Chrome 

### 🐋 Docker Version

latest stable

**Comment by vincejv** [comment]
My docker container uses 800mb of RAM with just 19 probes, 2 of which run chromium, given how memory hungry browsers are, this is to be expected, YMMV will always vary depending on the number of hosts and type of checks you have.

What I'm not sure is if Uptime-Kuma uses multiple chromium instances for each probe, that'd be really a huge waste of ram if the chromium instance isn't being recycled

**Comment by kiarafbickers** [comment]
@vincejv Any indication how much CPU usage I should go with? I'm seeing a few tickets related to CPU issues.

**Comment by CommanderStorm** [comment]
As Vince said: this entierely depends on the number of hosts and type of checks you are going to do.

A save bet would be to keep it below 200 monitors for the v1, while v2 will be able to handle much more.
If you are concearned: use docker to deploy the instance on your local machine, set it up, look at the CPU/RAM usage and order the correct VPS/VM
