### ISSUE TITLE
Email notifications only sending up notifications but not down

### ISSUE THREAD

**Issue by JoshMout** [louislam/uptime-kuma#3821]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

I setup uptime kuma on a fresh install of Ubuntu server on an Oracle OCI instance and setup email notifications.  It works great other than the fact I only get the UP notifications and not the DOWN ones.  Not sure what I did wrong here.

![Screenshot_20230930_192944_Messages](https://github.com/louislam/uptime-kuma/assets/22785444/ca552f82-1378-4714-b0fe-ead56fa08b8c)

### 🐻 Uptime-Kuma Version

1.23.2

### 💻 Operating System and Arch

Ubuntu 22.04 x64

### 🌐 Browser

Google Chrome

### 🐋 Docker Version

Docker 20.10.22

**Comment by TheOjasSingh** [comment]
Hi I want to work on this issue if you can assign it to me, Na can you help setting my uptime-kurma on my local machine

**Comment by CommanderStorm** [comment]
We don't assgin people to issues, you can work on this.
See https://github.com/louislam/uptime-kuma/blob/master/CONTRIBUTING.md for our contribtion guide and how to set up a develpment environment

**Comment by bjinthahouse** [comment]
I've had a similar issue, because of the icons that are send the "Down" icons lead to the mail being declared as Spam by Microsoft. We had to specifically whitelist the email address which uptime uses to send it's notifications.

**Comment by JoshMout** [comment]
Does any one know if there's a way to disable the down emoji so it doesn't get blocked?

**Comment by CommanderStorm** [comment]
SMTP subject and body will be fully templatable after v2.0 given that https://github.com/louislam/uptime-kuma/pull/3414 was merged

=> closing as resolved
