### ISSUE TITLE
Logo Update for Status Page?

### ISSUE THREAD

**Issue by TejaswaniShanker** [louislam/uptime-kuma#3822]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

I'd like to change the logo on the status page. Could you guide me on how to do this efficiently?

### 🐻 Uptime-Kuma Version

1.23.2

### 💻 Operating System and Arch

Ubuntu 22.04

### 🌐 Browser

Brave v1.58.135

### 🐋 Docker Version

24.0.6

**Comment by CommanderStorm** [comment]
![image](https://github.com/louislam/uptime-kuma/assets/26258709/caf4a2fa-36b2-4920-81b6-92faf8169bfd)
![image](https://github.com/louislam/uptime-kuma/assets/26258709/c81fcafc-a7d5-4aec-bc24-5bea5d202b1e)

**Comment by TejaswaniShanker** [comment]
@CommanderStorm Thanks, man! Just missed it.

I have a question; Why does it always say 21-22 minutes here? What does that mean?

![brave_mJRgIUlQNA](https://github.com/louislam/uptime-kuma/assets/145736101/0542a3af-b288-4255-95ee-db92240bdaa8)

**Comment by CommanderStorm** [comment]
21minutes  is how long the left side of said bar is in the past. Pings get added from the right and push items to the left
