### ISSUE TITLE
Not Able to make change in Local

### ISSUE THREAD

**Issue by Hemnendra** [louislam/uptime-kuma#3823]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

I download this project and running in my local but if i make some change in vue file and then running again its not reflecting i tried after deleting cache also please suppport 

### 📝 Error Message(s) or Log

NO error

### 🐻 Uptime-Kuma Version

1.23.2

### 💻 Operating System and Arch

LInux

### 🌐 Browser

chrome

### 🟩 NodeJS Version

v18.17.0

**Comment by louislam** [comment]
See https://github.com/louislam/uptime-kuma/blob/master/CONTRIBUTING.md to understand the project.
