### ISSUE TITLE
Is it possible to extract Monitors from an Docker image of Uptime Kuma?

### ISSUE THREAD

**Issue by akolar123** [louislam/uptime-kuma#3833]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

Is it possible to extract Monitors from an Docker image of Uptime Kuma?

In what directory are the Monitors stored in and is it possible to migrate them to a different Uptime Kuma server (I have switcehd from Docker to Windows Portable version)?

I'm not able to create a backup as I can not access the previous instance of Uptime Kuma, but I have created an Docker Image before my server crashed.

### 🐻 Uptime-Kuma Version

1.23.1

### 💻 Operating System and Arch

Windows Portable

### 🌐 Browser

Brave

**Comment by Zaid-maker** [comment]
You can copy the `./data/` folder and paste it into your new Uptime Kuma and u are good to go!

**Comment by devunderslash** [comment]
You could also export the monitor json via the settings -> Backup -> Export Backup which allows you could use to also Import for Disaster Recovery purposes.

**Comment by CommanderStorm** [comment]
@devunderslash as warned on the site you mentioned, the backup feature has been left unmaintained for quite some time.
Please make a backup of the database instead  by shutting down uptime-kuma and copying the `data` folder.

See 
![image](https://github.com/louislam/uptime-kuma/assets/26258709/8f20eabc-9c84-4524-b251-6b5594a2efa2)

**Comment by regchanuk** [comment]
Will back up be updated  or removed from the system instead or revamped updated again

**Comment by CommanderStorm** [comment]
See https://github.com/louislam/uptime-kuma/pull/2667

**Comment by CommanderStorm** [comment]
Closing as backup has been dropped lacking maintenance in v2.0
A new attempt must be developed with the native backup feature of the db used (sqlite/mariadb) in mind instead.
