### ISSUE TITLE
Restart All Monitors at once after succesfull restore

### ISSUE THREAD

**Issue by tismofied** [louislam/uptime-kuma#3837]
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

UI Feature

### 🔖 Feature description

I'd like an option of hitting start all monitors after doing a restore

### ✔️ Solution

I'd like an option of hitting start all monitors after doing a restore

**Comment by CommanderStorm** [comment]
Are you refering to this button?
![image](https://github.com/louislam/uptime-kuma/assets/26258709/53a533e9-013f-4618-a6b3-0bdf69da0a6e)

**Comment by chakflying** [comment]
Sounds like you are using the json backup/restore feature. Please avoid it unless absolutely necessary, as it has been unmaintained for so long you will only run into more issues like this.

**Comment by tismofied** [comment]
How would I back up?

**Comment by CommanderStorm** [comment]
You can perform backups by simply copying the `data` folder, as this contains the database and any auxiliary files.
