### ISSUE TITLE
health check for MongoDB

### ISSUE THREAD

**Issue by arsalanses** [louislam/uptime-kuma#384]
Hi,
is there a solution to health check service (like: MongoDB, PostgreSQL, TOR, ...) inside "uptime kuma"?

Example:
with this command, I can ping my MongoDB database
if I could place it inside "uptime kuma" it would be fantastic
`mongo --eval 'db.runCommand("ping").ok' localhost:27017/test --quiet`

**Comment by gaby** [comment]
@arsalanses Monitoring mondodb is already supported. Just created a "TCP Ping", and set the port to `27017`. For PostgreSQL use port `5432`.
