### ISSUE TITLE
The grey box in this page can be adjusted and developed for better ui experience

### ISSUE THREAD

**Issue by devagya-rattan** [louislam/uptime-kuma#3841]
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

UI Feature

### 🔖 Feature description

![Screenshot (72)](https://github.com/louislam/uptime-kuma/assets/112056749/d7049606-fdfd-4621-9153-7e33d0c19155)

### ✔️ Solution

Css can be used

### ❓ Alternatives

css

**Comment by CommanderStorm** [comment]
What do you mean by the folliwing?

> The grey box in this page can be adjusted and developed for better ui experience

**Comment by Harshvar25** [comment]
can i work on this ?

**Comment by CommanderStorm** [comment]
You can. We don't assign people to ussues in this Repository.
See our contribution guide: https://github.com/louislam/uptime-kuma/blob/master/CONTRIBUTING.md

**Comment by devagya-rattan** [comment]
i mean to say about the content below the two green boxes

**Comment by debarkamondal** [comment]
Does this look good? If it does I would go ahead and refactor the code and create a PR. This is my first time so please guide me if I did some mistake.

![image](https://github.com/louislam/uptime-kuma/assets/37607719/47add6db-16f3-4900-9d1d-f9ebd2eb699e)
![image](https://github.com/louislam/uptime-kuma/assets/37607719/7cbabc78-de61-4221-a878-7c075486d443)

**Comment by debarkamondal** [comment]
Also noticed another thing:
Why is the second heading called `A self-hosted monitoring tool` doesn't use margin to create spacing instead two `<br>` tags. Also the spacing is is inconsistent and not pleasing to eye.

**Comment by CommanderStorm** [comment]
@debarkamondal I think you forgot to create a PR

**Comment by CommanderStorm** [comment]
This issue revolves around these lines

https://github.com/louislam/uptime-kuma-website/blob/110ca0153f4d2d9bb980d65081602ecd2af49be4/views/main.php#L31-L33

**Comment by karandhanwani16** [comment]
Hello, I have raised an PR based on thei issue, Please let me know if there is anything I can do.

**Comment by CommanderStorm** [comment]
lets continue this in https://github.com/louislam/uptime-kuma-website/pull/4/
