### ISSUE TITLE
Microsoft Teams Notification throwing Aggregate Error

### ISSUE THREAD

**Issue by sreeharichalla82** [louislam/uptime-kuma#3842]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

Microsoft Teams Notification throwing Aggregate Error

### 🐻 Uptime-Kuma Version

1.21.3

### 💻 Operating System and Arch

Windows  10

### 🌐 Browser

Chrome 117.0

### 🟩 NodeJS Version

1.8.13

**Comment by sreeharichalla82** [comment]
@CommanderStorm, I have set the Microsoft Team Notification and when I click on Test it throws AggregateError

Log:

Error: Error: AggregateError
at Teams.throwGeneralAxiosError (/home/vcap/app/server/notification-providers/notification-provider.js:38:15)
at Teams.send (/home/vcap/app/server/notification-providers/teams.js:153:18)
at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
at async Socket.<anonymous> (/home/vcap/app/server/server.js:1209:27)

**Comment by CommanderStorm** [comment]
I think the likely culprit is the same as in https://github.com/louislam/uptime-kuma/issues/4457#issuecomment-1933842651
=> tracking it there
