### ISSUE TITLE
UI: `No fil...ected.`

### ISSUE THREAD

**Issue by jtagcat** [louislam/uptime-kuma#385]
![image](https://user-images.githubusercontent.com/38327267/132962321-dcc78183-b6ad-406e-8e29-4c6d3513d95a.png)

100% zoom on HD display.

**Comment by Saibamen** [comment]
This is because of two columns in Settings page.
I don't see a quick solution here. Even if we add `width: 100%` to this element, this IMO looks bad:
![image](https://user-images.githubusercontent.com/905878/132989152-09b942e4-3dde-4db7-bc41-ed452607ed52.png)

**Comment by jtagcat** [comment]
What about having it on it's own line, and import below, align-right.

Export may get it's own section even. Tieing it with upload file to export doesn't make sense.

I think a tabbed design (default select export tab(?)), where you may select import at the top.  
This may also result in hiding text, reducing bomb-overwhelm factor for the settings page.

On mobile, can't sketch atm.

**Comment by Ponkhy** [comment]
I'll think about something tomorrow, thank you!

**Comment by Saibamen** [comment]
## v1:
![image](https://user-images.githubusercontent.com/905878/132999036-0049611f-7003-491d-97cd-1dbfad4542dd.png)
### v1 mobile:
![image](https://user-images.githubusercontent.com/905878/132999472-e0586d12-2657-44ec-bd41-bbdafb9b8bba.png)

## v2:
![image](https://user-images.githubusercontent.com/905878/132999383-ae560c2d-b0fb-46f6-b239-167d7123fdc4.png)
### v2 mobile:
![image](https://user-images.githubusercontent.com/905878/132999406-c2926466-e13e-4bda-b987-d753a85cd23b.png)

**Comment by Ponkhy** [comment]
Or you just already do it xD
I think we should go with v2 and also put the Import Options from #382 when it's in the master branch on the left, in the same line as the import button.
Or you could submit a commit on the PR.

**Comment by jtagcat** [comment]
It seems I'm late to the party :)

**Comment by jtagcat** [comment]
meant something along the lines of https://www.w3schools.com/w3css/w3css_tabulators.asp

**Comment by jtagcat** [comment]
Closing for now, reopen if wanted (◕‿◕✿)

**Comment by Saibamen** [comment]
@jtagcat:
No! This is not how we should use issues and PRs...

This issue is not fixed yet, because PRs was not merged to `master` branch...

**Comment by jtagcat** [comment]
Ah, well, that what's happens when you try to make use of free time, partial reading, thought the second PR merge was enough.

come play splatoon 1

**Comment by Neer171** [comment]
How about adding CSV format to import and export option because json is not too much user friendly in order to import/export.

**Comment by Saibamen** [comment]
CSV requires more code for save and read. JSON is more universal. And you cannot create hierarchical and related data in CSV. No

**Comment by Neer171** [comment]
how can a normal user create json file for their domains if they have 100 domains.

**Comment by chakflying** [comment]
@Neer171 This issue is about the import dialog design. Please open a new issue if you think another format of import should be added.
