### ISSUE TITLE
Regroup HTTP(s) - Keyword probe to HTTP(s) but optional

### ISSUE THREAD

**Issue by mabed-fr** [louislam/uptime-kuma#3850]
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

API, New Notification, New Monitor, UI Feature

### 🔖 Feature description

Regroup HTTP(s) - Keyword probe to HTTP(s) but optional like as it will be https://github.com/louislam/uptime-kuma/pull/1878

Advantage:

* Possibility of having a single monitor which alerts on several element events (keyword, status code, slow response time, ssl ...)

* Eliminate duplicate monitors

### ✔️ Solution

like https://github.com/louislam/uptime-kuma/pull/1878

**Comment by CommanderStorm** [comment]
Closing in favor of your earlier issue #3336 as a duplicate
