### ISSUE TITLE
Build docker locally

### ISSUE THREAD

**Issue by DanielRDias** [louislam/uptime-kuma#3852]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

I'm trying to build and run the docker locally. i.e. based on the GitHub Code, not using the DockerHub image directly.
I couldn't find in the documentation how to do this, so I tried the following.

The reason why I'm doing this is because when I try to host it on AWS using "AWS Fargate" to run the docker container and "AWS EFS" for the volume, I get permission errors when modifying the permissions of /app/data to the node user.

So, I would like to build and modify it to debug/fix the issue.

### 📝 Error Message(s) or Log

I tried the following to build the docker image and got the following errors:

1. `docker build ./docker` fails with the following error:
```
COPY failed: file not found in build context or excluded by .dockerignore: stat .npmrc: file does not exist
```
2. `docker build . -f ./docker/dockerfile` fails with the following error:
```
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: '@azure/msal-node@1.17.3',
npm WARN EBADENGINE   required: { node: '10 || 12 || 14 || 16 || 18' },
npm WARN EBADENGINE   current: { node: 'v20.5.1', npm: '9.8.0' }
npm WARN EBADENGINE }
npm ERR! code EACCES
npm ERR! syscall mkdir
npm ERR! path /app/node_modules
npm ERR! errno -13
npm ERR! Error: EACCES: permission denied, mkdir '/app/node_modules'
npm ERR!  [Error: EACCES: permission denied, mkdir '/app/node_modules'] {
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'mkdir',
npm ERR!   path: '/app/node_modules'
npm ERR! }
npm ERR! 
npm ERR! The operation was rejected by your operating system.
npm ERR! It is likely you do not have the permissions to access this file as the current user
npm ERR! 
npm ERR! If you believe this might be a permissions issue, please double-check the
npm ERR! permissions of the file and its containing directories, or try running
npm ERR! the command again as root/Administrator.

npm ERR! A complete log of this run can be found in: /home/node/.npm/_logs/2023-10-06T13_56_18_510Z-debug-0.log
```
3. Changed the docker file line 13 from `USER node` to `USER root` I'm able to build the image, but when I run it nothing is loading.

### 🐻 Uptime-Kuma Version

1.23.2

### 💻 Operating System and Arch

Amazon Linux 2023

### 🌐 Browser

Google Chrome 117.0.5938.149

### 🐋 Docker Version

Docker version 20.10.17, build 100c701

### 🟩 NodeJS Version

v18.16.0

**Comment by chakflying** [comment]
Please be aware that using EFS volume is not supported. There was previous report that database corruption occurred while using EFS. (#3305)

**Comment by CommanderStorm** [comment]
See
https://github.com/louislam/uptime-kuma/blob/156614b3034b72f56cc6b0a8ee71562959f3b252/package.json#L35-L44

**Comment by louislam** [comment]
Also there are a lot of breaking changes in the latest v2 dev branch which is definitely not production ready. The docker image is also becoming rootless, permission issues are a little bit tricky to deal with.

Therefore, use the 1.23.X branch is better: https://github.com/louislam/uptime-kuma/tree/1.23.X

**Comment by DanielRDias** [comment]
> Please be aware that using EFS volume is not supported. There was previous report that database corruption occurred while using EFS. (#3305)

Thank you for the feedback.
Do you have any alternative to EFS so that we can set this up on the cloud in a "serverless" way so that I don't need to manage the machine where the docker is running?
If not, I might need to take the risk and setup a backup policy.
Alternatively, is it possible to set things via API or programmatically, so that I could keep everything versioned on GitHub for example so that I can easily restore in case something happens?

**Comment by chakflying** [comment]
The current application is not serverless-friendly as data is only stored locally in SQLite. I'm not experienced with this but I think you can consider running the container on an EC2 instance using bind mount or Docker volume, or possibly using an EBS volume.

But since all data is stored in an SQLite file, backup is as simple as saving a copy of the file. (by exporting the mounted volume or copying the data directory).
