### ISSUE TITLE
Hide `Also apply to existing monitors`, if parent not enabled.

### ISSUE THREAD

**Issue by jtagcat** [louislam/uptime-kuma#386]
![image](https://user-images.githubusercontent.com/38327267/132962374-7cdebe02-a863-42ff-9ac9-29343e46c199.png)

**Comment by Ponkhy** [comment]
Heyo, that's not a bug, it's still there in case someone wants to apply this notification on every monitor afterwards.

**Comment by jtagcat** [comment]
It should read `Enable on` or `Attach to` `existing monitors' instead then.
