### ISSUE TITLE
[Bug] Cannot read properties of null (reading '_dockerType')

### ISSUE THREAD

**Issue by jamess60** [louislam/uptime-kuma#3861]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### Description

When creating a monitor with type docker container (polls the docker.sock file) and entering the container name, the monitor turns from green to yellow and this notification is sent via telegram:

Cannot read properties of null (reading '_dockerType')

This is in the uptimekuma container log
2023-10-09T15:21:57+02:00 [MONITOR] WARN: Monitor #30 'Overseer (Plex requests)': Failing: Cannot read properties of null (reading '_dockerType') | Interval: 60 seconds | Type: docker | Down Count: 0 | Resend Interval: 0

The only reference I can find is in #2141 but this was linked to a deprecated feature and marked wontfix.

### 👟 Reproduction steps

1) Start an uptimekuma:latest container with the docker.sock volume mapped
2) create a monitor for a container on that host using container name instead of ID 

### 👀 Expected behavior

Monitor should be green as the service is up

### 😓 Actual Behavior

Service is yellow and error is sent to log

### 🐻 Uptime-Kuma Version

1.21.3

### 💻 Operating System and Arch

Debian 12 x64

### 🌐 Browser

Firefox NA

### 🐋 Docker Version

Docker 24.0.5

**Comment by chakflying** [comment]
For the "Docker Host" option in the monitor settings, can you try to select the host again and test that it is working?

![image](https://github.com/louislam/uptime-kuma/assets/3271800/cbf62624-ebcb-46f6-977f-05cdcafd0d4c)

Test available when you click on "Edit" under the "Docker Host" option:
![image](https://github.com/louislam/uptime-kuma/assets/3271800/99773994-237e-42bc-9def-dc4c9d4ae5fe)

**Comment by jamess60** [comment]
Testing the host works but the issue persists
