### ISSUE TITLE
Cannot connect to the socket server. [Error: websocket error] - Cloudflare

### ISSUE THREAD

**Issue by jm-rizkallah** [louislam/uptime-kuma#3866]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### Description

I noticided that if i enable cloudflare under attack mode is to show visitors a challenge when they visite the domain i get a socket server error.

Once disabled i can access my uptime kuma page

![image](https://github.com/louislam/uptime-kuma/assets/92910078/53fe101d-5306-49bb-b0a8-4c85af9b97e1)

### 👟 Reproduction steps

Enable under attack mode on the domain in cloudflare

### 👀 Expected behavior

The page should be displayed normally

### 😓 Actual Behavior

Cannot connect to the socket server. [Error: websocket error]

### 🐻 Uptime-Kuma Version

1.23.3

### 💻 Operating System and Arch

Ubuntu

### 🌐 Browser

Edge Version 117.0.2045.47 

### 🐋 Docker Version

Docker version 20.10.18, build b40c2f6

**Comment by louislam** [comment]
Change to `help` as it is a 3rd party issue.
