### ISSUE TITLE
Uptime can be over 100%

### ISSUE THREAD

**Issue by chrisreeves-** [louislam/uptime-kuma#3870]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### Description

One of my endpoints is reporting over 100% uptime, I have approx 20 endpoints being checked, there is only one over 100%

![image](https://github.com/louislam/uptime-kuma/assets/9957942/9fc087e3-e7b3-4a66-8317-64ac18d23d44)

I know the cause is from a system time change/imbalance so the root cause is that issue.

The uptime seems to be increasing and not decreasing

### 👟 Reproduction steps

Cause yourself headaches by having the wrong system time on the physical host

### 👀 Expected behavior

Uptime not greater than 100% regardless of system time change.

### 😓 Actual Behavior

![image](https://github.com/louislam/uptime-kuma/assets/9957942/a337ed5b-823e-43f4-b63e-1b0bea0aa2e9)

### 🐻 Uptime-Kuma Version

1.23.3

### 💻 Operating System and Arch

Slackware

### 🌐 Browser

Chrome 117.0.5938.149

### 🐋 Docker Version

Docker  20.10.24

### 🟩 NodeJS Version

8.19.4

**Comment by louislam** [comment]
Duplicate of https://github.com/louislam/uptime-kuma/issues/2628
