### ISSUE TITLE
[redis] Ignore TLS/SSL error

### ISSUE THREAD

**Issue by HdroguettA** [louislam/uptime-kuma#3871]
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

UI Feature, Other

### 🔖 Feature description

Provide the capability to ignore the TLS/SSL error that is returned by a Redis service.  
`self-signed certificate in certificate chain`

Heroku recommends this as a way to connect in Node.js https://devcenter.heroku.com/articles/connecting-heroku-redis#connecting-in-node-js.

### ✔️ Solution

The `redis` package allows us to set `rejectUnauthorized: false` through the `socket` [createClient configuration property](https://github.com/redis/node-redis/blob/master/docs/client-configuration.md#create-a-ssl-client-using-a-self-signed-certificate).

We can utilise the existing monitor `ignoreTls` variable to include the same input that is part of the Additional section when the `monitor.type` is `http | keyword | json-query`. It can then be utilised by the `redisPingAsync` method.

Consideration will have to be taken as the current `ignoreTLSError` translations refer specifically to 'HTTPS websites'

**Comment by CommanderStorm** [comment]
PR welcome. Here is our contribution guide: https://github.com/louislam/uptime-kuma/blob/master/CODE_OF_CONDUCT.md
