### ISSUE TITLE
Monitor https 200 website with error message in content/body

### ISSUE THREAD

**Issue by bjoerrrn** [louislam/uptime-kuma#3872]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

I want to monitor a website, which is delivering a 200 http(s) status code, but it's content might be a technical error or not. I have searched for a while, but for sure I am searching for the wrong keywords... For now, I do not know, how to setup this monitor. 

In case of an error, the https website has a DIV element with class "refusal-header-box" and the content of the DIV element is "technical error". 

### 🐻 Uptime-Kuma Version

1.23.3

### 💻 Operating System and Arch

Debian

### 🌐 Browser

Edge, Safari

### 🐋 Docker Version

24.0.6

### 🟩 NodeJS Version

18.16.0

**Comment by louislam** [comment]
Try this.

![image](https://github.com/louislam/uptime-kuma/assets/1336778/aac1da2c-dabb-47c2-83dd-455e28ac2bb5)

**Comment by louislam** [comment]
Try this.

![image](https://github.com/louislam/uptime-kuma/assets/1336778/0f044e57-9749-4b03-b949-98af3193deb6)

**Comment by bjoerrrn** [comment]
Thank you @louislam
