### ISSUE TITLE
Allow response data to be used as tag values

### ISSUE THREAD

**Issue by george-dadeboe** [louislam/uptime-kuma#3873]
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

UI Feature

### 🔖 Feature description

I was hoping, if there was a way, to allow the repose of a request to be parsed and then turned in tags or even tag values. For instance, I have a simple Python application that returns the status of all/one of my access points using the router's API (Synology SRM API if you were wondering). A sample response looks like this 
```json
{
  "node": {
    "name": "Office AP",
    "is_re": true,
    "model": "MR2200ac",
    "uptime": "18h 13m 41s",
    "uplink": {
      "is_ethernet_connected": true,
      "wireless_uplinks": []
    },
    "wifi_radios": [
      {
        "band": "2.4G",
        "current_channel": 7,
        "current_frame_rate_rx": 0,
        "current_frame_rate_tx": 20,
        "current_rate_rx": 0,
        "current_rate_tx": 4909
      },
      {
        "band": "5G-1",
        "current_channel": 132,
        "current_frame_rate_rx": 34,
        "current_frame_rate_tx": 245,
        "current_rate_rx": 6019,
        "current_rate_tx": 299481
      },
      {
        "band": "5G-2",
        "current_channel": 36,
        "current_frame_rate_rx": 7,
        "current_frame_rate_tx": 30,
        "current_rate_rx": 542,
        "current_rate_tx": 5756
      }
    ],
    "network_status": "online",
    "node_status": "good",
    "node_status_msg": "good"
  }
}
```

### ✔️ Solution

I would like below on my dashboard
![image](https://github.com/louislam/uptime-kuma/assets/56259461/88957c79-674e-4877-9d75-602d4c2dd539)
where the values of the fields are being populated from the response data.

**Comment by george-dadeboe** [comment]
If there's a way to achieve this via Push monitor type I would be really appreciative if you could me in the right direction 😄

**Comment by CommanderStorm** [comment]
@george-dadeboe 
I think this is a duplicate of https://github.com/louislam/uptime-kuma/issues/686
If you agree, could you please close this Issue, as duplicates only create immortal zombies and are really hard to issue-manage?
If not, what makes this issue unique enough to require an additional issue? (Could this be integrated into the issue linked above?) ^^

**Comment by george-dadeboe** [comment]
@CommanderStorm I believe you are right. will close this issue.
