### ISSUE TITLE
Uptime Kuma Storage Error

### ISSUE THREAD

**Issue by kokofixcomputers** [louislam/uptime-kuma#3879]
### ⚠️ Please verify that this bug has NOT been raised before.

- [x] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

I run uptime kuma on a server that does not have much space but now i ran out of space it says:

Trace: [Error: PRAGMA journal_mode = WAL - SQLITE_IOERR: disk I/O error] {
  errno: 10,
  code: 'SQLITE_IOERR'
}

when booting up and it does not let me in to the uptime kuma dashboard because it does not host a webserver. What should i do now? i don't want to lose my monitors and notifications.

### 📝 Error Message(s) or Log

Trace: [Error: PRAGMA journal_mode = WAL - SQLITE_IOERR: disk I/O error] {
  errno: 10,
  code: 'SQLITE_IOERR'
}

### 🐻 Uptime-Kuma Version

Either 1.23.2 or 1.23.1

### 💻 Operating System and Arch

Linux

### 🌐 Browser

Google Chrome

### 🟩 NodeJS Version

Not sure it is installed a long time ago.

**Comment by louislam** [comment]
Can you access the Linux?  Backup the data folder to your local machine via SFTP first.

And try to start the Uptime Kuma from your local machine.

If it is able to start, try to remove all heartbeat data and set a shorter days. Shrink the database size finally.

![image](https://github.com/louislam/uptime-kuma/assets/1336778/9863cb17-9579-4b8d-a871-2c3314a2ccfd)

**Comment by kokofixcomputers** [comment]
> Can you access the Linux? Backup the data folder to your local machine via SFTP first.
> 
> And try to start the Uptime Kuma from your local machine.
> 
> If it is able to start, try to remove all heartbeat data and set a shorter days. Shrink the database size finally.
> 
> ![image](https://user-images.githubusercontent.com/1336778/274471870-9863cb17-9579-4b8d-a871-2c3314a2ccfd.png)

I cannot start the uptime kuma. It just won't start the webserver

**Comment by louislam** [comment]
Even if with enough disk space?

**Comment by kokofixcomputers** [comment]
> Even if with enough disk space?
> 
> If yes, I would suggest that you should use a SQLite tool such as SQLite Expert to view the kuma.db, see if it is accessible.

Oh... I thought that you said that in the server without enough disk space... I'm trying to do that know thanks.

**Comment by louislam** [comment]
Yes, my first comment meant you should setup your uptime kuma in your desktop machine, because I believe your desktop should have more free disk space. Re-upload the database to the server when the database size is reduced. That was what I meant.
