### ISSUE TITLE
Notifications : add selected tag or ALL tags with the notification message. 

### ISSUE THREAD

**Issue by bengivre** [louislam/uptime-kuma#3882]
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

New Notification

### 🔖 Feature description

Add the option to have the tags (key:value) attached to a monitor in the notification message. 
Either selected tags from the notification configuration or just a check box to mention all the tags. 

Maybe just under the time , we could have 

`Time (UTC): 2023-08-09 04:01:48.868`

`Monitor Tags:  key1:value2 | key2:value2 | key3:value3 | etc.. `

 

### ✔️ Solution

When you get a notification, you can see the tags attached to a monitor.

**Comment by CommanderStorm** [comment]
I think this is a duplicate of https://github.com/louislam/uptime-kuma/issues/2730
If you agree, could you please close this Issue, as duplicates only create immortal zombies and are really hard to issue-manage?
If not, what makes this issue unique enough to require an additional issue? (Could this be integrated into the issue linked above?) ^^

**Comment by bengivre** [comment]
it's a duplicate indeed. I was not able to find it earlier . 
Closing that one

**Comment by CommanderStorm** [comment]
Thanks
