### ISSUE TITLE
Change favicon

### ISSUE THREAD

**Issue by XHyperDEVX** [louislam/uptime-kuma#3888]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

I would like to change the favicon of my Uptime Kuma page. how do I do that? best so that it is not reset after an update....

### 🐻 Uptime-Kuma Version

1.23.2

### 💻 Operating System and Arch

Debian 11

### 🌐 Browser

Edge

### 🐋 Docker Version

standalone, no docker

### 🟩 NodeJS Version

v18.14.2

**Comment by CommanderStorm** [comment]
The favicon of status pages is the logo you uploaded.
See https://nav-monitoring.mm.rbg.tum.de/status/navigatum for an example of his in usage.

Changing the favicon for other pages is currently not possible, but here is our contribution guide:
https://github.com/louislam/uptime-kuma/blob/03e43ab3643e0f8b610d0ed86b1857675e4e7233/CONTRIBUTING.md

**Comment by XHyperDEVX** [comment]
but that's exactly what i want. i know how to change the favicon from the status page, but i want to change the favicon from the dashboard.

is there a workaround?

**Comment by CommanderStorm** [comment]
As noted above, you can contribute further appearance setting.

There is no workaround except for building a custom docker image with the favicon overridden or maintaining a slightly custom branch with just the favicon changed.

Note that if you want this as a feature-request, please fill out [this form](https://github.com/louislam/uptime-kuma/issues/new?assignees=&labels=feature-request&projects=&template=feature_request.yaml) instead, as we have auto-closing on `help`-issues

**Comment by XHyperDEVX** [comment]
I am not able to write javascript, so I can't contribute anything.

**Comment by XHyperDEVX** [comment]
-> #3890
