### ISSUE TITLE
Changing Favicon

### ISSUE THREAD

**Issue by XHyperDEVX** [louislam/uptime-kuma#3890]
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

UI Feature

### 🔖 Feature description

The ability to change the [Fav]icon, as with status pages.

### ✔️ Solution

An upload button to upload an image file which will be used as favicon for the dashboard and all other pages and as icon in the dashboard itself.

### 📝 Additional Context

this is what i mean by "icon in the dashboard itself":
![image](https://github.com/louislam/uptime-kuma/assets/68189420/047b71ae-1ec7-4d6a-9352-9fcbb512ceb3)

**Comment by Ankitchaudharyy** [comment]
I am interested in solving this issue. Would u please assign it to me?

**Comment by XHyperDEVX** [comment]
@Ankitchaudharyy 
I would like to, but I don't have enough rights. I think that would have to do @louislam.

Thanks that you dedicate yourself to my proposal :)

**Comment by louislam** [comment]
You can change the logo in your status page, but for dashboard, the answer is no.

Just like you won't ask for Jellyfin, Portainer, Google, Facebook or something else to let you change the application logo.

**Comment by XHyperDEVX** [comment]
we are not allowed to change the favicon? that's a shame....
