### ISSUE TITLE
Password with # character in MySQL/MariaDB Monitor

### ISSUE THREAD

**Issue by Finallf** [louislam/uptime-kuma#3894]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### Description

I have a stack with nginx proxy manager, mariadb, Adminer, phpmyadmin and uptime-kuma.
In mariadb this configures root with its own password, and an nginx user also with its own password.
Everything works correctly between NPM, mariadb, Adminer and phpmyadmin.
In both Adminer and phpmyadmin, I can connect to mariadb as root or as nginx user, using their respective passwords.

But I can't connect by creating a MySQL/MariaDB monitor through uptime-kuma, because it gives a connection error, after searching so much I discovered that it's the password I'm using.

Both passwords have 13 characters, and the last character is #

For some reason, uptime-kuma cannot correctly pass the password to access mariadb.

I tested by creating another user, with the same password with just the first 12 characters, and it connects normally.

Why do npn, adminer and phpmyadmin connect normally and uptime-kuma does not, using the # character?

Password that works: 123456789012
Password that doesn't work: 123456789012#

Remembering that I tried to pass the password using ASCII encoding: # = %23
But it doesn't work either.

Could it be a connection string bug?

### 👟 Reproduction steps

Use a password with the # character in the MySQL/MariaDB user that you will monitor in Uptime-kuma

Try monitoring the MySQL/MariaDB service with this user.

### 👀 Expected behavior

Connect to the database even using the # character

### 😓 Actual Behavior

Do not connect to the database using the # character

### 🐻 Uptime-Kuma Version

1.23.3

### 💻 Operating System and Arch

Debian 12

### 🌐 Browser

Chrome 118.0.5993.70

### 🐋 Docker Version

Docker version 24.0.6, build ed223bc

### 📝 Relevant log output

```shell
2023-10-14 23:24:31 305 [Warning] Access denied for user 'teste1'@'172.18.0.12' (using password: YES)
```

**Comment by Finallf** [comment]
From what I saw, it's an error/bug in node-mysql2 used by uptime-kuma.
Is there a possibility of getting around this problem?
It seems that the people at node-mysql2 are not very excited about fixing this problem at the moment.

https://github.com/louislam/uptime-kuma/issues/3221
https://github.com/sidorares/node-mysql2/pull/1621

**Comment by louislam** [comment]
I actually want to split password into a standalone input field. Let me fix it.
