### ISSUE TITLE
indentation hostnames is off

### ISSUE THREAD

**Issue by Stvn21** [louislam/uptime-kuma#39]
Might not a big deal, but maybe it can be easily corrected.

<img width="447" alt="Screenshot 2021-07-13 at 22 50 33" src="https://user-images.githubusercontent.com/54367657/125523092-d21f2037-8811-4cb4-85bc-7a5385622b63.png">

Edit: This issue persist on my macbook using safari/chrome/brave, but not on Windows using Chrome.

**Comment by louislam** [comment]
Improved by #145

**Comment by chakflying** [comment]
I'm pretty sure this is not the same pill (`.badge` in Dashboard.vue), also I don't have a mac to test so you might have to check again.

**Comment by louislam** [comment]
> I'm pretty sure this is not the same pill (`.badge` in Dashboard.vue), also I don't have a mac to test so you might have to check again.

Oh, I messed up with test.
