### ISSUE TITLE
[Feature request] SSH sensors (monitoring via remotely executable scripts)

### ISSUE THREAD

**Issue by nbvcxz** [louislam/uptime-kuma#390]
**Is it a duplicate question?**
Seems nobody has asked about it.

**Is your feature request related to a problem? Please describe.**
It's just a low priority idea for the future to improve monitoring and make it more flexible and accurate.

**Describe the solution you'd like**
A new type of sensors: Monitoring with remotely executed ssh command. Similarly to already existing HTTP sensors, the exitcode (range) can trigger up or down.

**Describe alternatives you've considered**
Somehow, the alternative is the already planned ["Push based monitoring"](https://github.com/louislam/uptime-kuma/projects/1#card-67956435). Generally it's going to be the same, but triggered in the different way.

**Comment by rmnijgh** [comment]
Hi, I was wondering if this FR has been considered yet? Monitoring checks over SSH opens a lot of possibilities for uptime-kuma.

**Comment by qroac** [comment]
I'd love to see this for monitoring our application servers behind reverseproxy and firewall

**Comment by CommanderStorm** [comment]
Because of the extremely similar scope and because the other issue allows ssh'ing into other boxes, I am going to close this issue as a duplicate in favour of #1117 (despite being the earlier issue)
