### ISSUE TITLE
OAuthToken Expiry Refresh Will Never Occur Where ‘Expires_at’ Is Not Provided

### ISSUE THREAD

**Issue by HdroguettA** [louislam/uptime-kuma#3902]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### Description

Info:
The expires_at key is only labelled as 'recommended' and will not be provided in every openid-client response
https://datatracker.ietf.org/doc/html/rfc6749#section-4.2.2

For Salesforce, it is not provided.
https://help.salesforce.com/s/articleView?id=sf.remoteaccess_oauth_client_credentials_flow.htm&type=5

----

I began to notice many OAuth2 failures (401) which occurred on endpoints being monitored. They seemed to line up with the session expiry for the platform being monitored. I found that editing and hitting save on the monitor without actually changing anything resolved the issue (seemingly forced a refresh).

Looking into the `getOidcTokenClientCredentials` method from `util-server.js`, we never seem to refresh the OAuthToken. This is primarily due to no `expires_at` object key being provided. This is relied upon by monitor.js within the `this.auth_method === "oauth2-cc"` condition.

As a result of the above the following condition which allows a refresh is ONLY ever entered when `this.oauthAccessToken` is undefined, which happens to occur on save. This results in a failure until saving. (`monitor.js`)

![image](https://github.com/louislam/uptime-kuma/assets/48663306/cb020cda-8d2b-4716-b148-1b84a4f7572e)

### 👟 Reproduction steps

I found this to apply to Salesforce OAuth2 Client Credentials.

As all salesforce organisations are different, you can replicate this by first creating your Connected App in salesforce by following the recommended steps here https://help.salesforce.com/s/articleView?id=sf.connected_app_client_credentials_setup.htm&type=5.

1. Create a monitor for HTTP(s) [This can also be any of the extended HTTP(s) types]
2. Include your endpoint such as https://{your_domain}.my.salesforce.com/services/data/v57.0/limits
3. Configure the Authentication Method to OAuth2: Client Credentials
4. Here you can include debug logs for `this.oauthAccessToken` after it is set by `getOidcTokenClientCredentials` to see the `expires_at` missing OR wait for the session to expire (based on your organisation settings. 

### 👀 Expected behavior

The OAuth2 token is refreshed.

I believe we can handle this in a few ways:

- Call `getOidcTokenClientCredentials` after 401 when `this.auth_method === "oauth2-cc"`
- Set `this.oauthAccessToken` to undefined after 401 when `this.auth_method === "oauth2-cc"`
- Include a new session expiry time related field for the user to manually input the expected session life to be used for refreshing
- Hardcode some small number so it's refreshed for every request (if we really have to...)

### 😓 Actual Behavior

I received a down alert

### 🐻 Uptime-Kuma Version

1.23.3

### 💻 Operating System and Arch

Windows 11 x64

### 🌐 Browser

Google Chrome 118.0.5993.70

### 🟩 NodeJS Version

18.17.1

**Comment by HdroguettA** [comment]
Happy to make a pull request for any solution

**Comment by CommanderStorm** [comment]
PRs appreciated, see our contribution guide: https://github.com/louislam/uptime-kuma/blob/579d7232c92621fab7da3e5765de7ea9eb6a9e3b/CONTRIBUTING.md

Call `getOidcTokenClientCredentials` after `401` when `this.auth_method === "oauth2-cc"` seems like the most logical choice.

To preemt this:
Have you made shure that there is really no expiry-related field present? (I can't imagine tokens expiring without telling people when they will expire)

**Comment by HdroguettA** [comment]
@CommanderStorm 

I'll look at creating a PR for this. 


In regards to the value not being provided.
I have yes. I was also surprised so I logged the `this.oauthAccessToken` response (below) and double checked with [the documentation](https://help.salesforce.com/s/articleView?id=sf.remoteaccess_oauth_client_credentials_flow.htm&type=5).

![image](https://github.com/louislam/uptime-kuma/assets/48663306/1f19b8ba-2ed3-46ab-aa97-d716651ff72c)

**Comment by louislam** [comment]
cc: @hegerdes May need your assistance on this issue.

**Comment by hegerdes** [comment]
Typical OAuth hell. Salesforce and Atlassian do a lot of stuff _their own way_ 🙄

I am also in favor of the first solution you provided. But let me ask you one thing first. Is the access code you get form the oauth provider a JWT and can we always assume that it is a JWT? (I'm not sure right now if the spec requires it to be a JWT)

If so, JWTs always have expiry-time. We could use this as an alternative  expiry-time to the native expiry-time form the oauth 
 token provider response. This would avoid doing unneeded http check requests that could pollute (system/access) logs

**Comment by HdroguettA** [comment]
The access token from Salesforce is not always a JWT and is defaulted to 'opaque'. JWT has to be configured in the app connection settings to be enabled.

Are we looking to implement a JWT Authorization flow? We'll have to create the ability for users to import and store certificates for signing the assertion.

**Comment by hegerdes** [comment]
I think I caused some confusion - I do not want to create and sign own JWTs. I just thought about using the JWTs (accsess codes) expiry that we get form the OAuth/OIDC provider. 
All the implementation I've seen so far provide an JWT that is valid for about 1 hour and can be used to access the protected resource (using methods like Bearer Token).  Sorry if I wasn't clear enough.

But when you say not all Oauth/OIDC providers issue JWTs than my idea is stupid and you definitely should presume your initial solution. The spec definitely does not require the access token to be a JWT - it just happens to be that it is for most providers. Just make sure to prevent infinite loops of always requesting a new token when the HealthCheck happens to fail.

**Comment by HdroguettA** [comment]
@hegerdes Ah! My apologies, I see what you were going for now. Unfortunately not the case :(

Great foresight, I made sure to include a reattempt check within [the pull request](https://github.com/louislam/uptime-kuma/pull/3903/commits/35fdf2e49dd08ad7a56cc9270de19f3cdfd3027f#:~:text=if%20(this.auth_method%20%3D%3D%3D%20%22oauth2%2Dcc%22%20%26%26%20error.response.status%20%3D%3D%3D%20401%20%26%26%20!options.isReattempt)%20%7B) to prevent the infinite loops after I encountered it during testing.
