### ISSUE TITLE
Set how far back uptime history is shown on status page

### ISSUE THREAD

**Issue by nexy7574** [louislam/uptime-kuma#3907]
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

UI Feature

### 🔖 Feature description

On the status page, the length of uptime history appears to be determined by how frequently the uptime checks are made. For instance, monitors with 60 second intervals will show up to 45 minutes in history
![image](https://github.com/louislam/uptime-kuma/assets/53234499/efea6b7e-8eee-417f-b5e0-9073463644a4)

This isn't great as that period can be really short, and is (as far as im aware) entirely non-configurable.
It would be nice to have a setting that would say "Show uptime history for: 30m/1h/2h/3h/6h/12h/24h/48h/7d/1mo" and so on, rather than calculating it as it is currently.

### ✔️ Solution

Currently, the only way to extend history is to decrease how often your monitor probes. This comes at a cost of realtime/frequent monitoring, in that you would now have to wait even longer for a probe to go out before being notified of downtime.

As mentioned, a great solution would simply to be able to choose how much uptime history is shown in the status page.

### 📝 Additional Context

![image](https://github.com/louislam/uptime-kuma/assets/53234499/2a62871f-98bf-4f9e-9744-87e70e983898)
This monitor is only checked every 5 minutes, and as such shows up to 4 hours of history (I assume due to less probes and data). Since this is a low priority service, I'm not too concerned about being notified of downtime within a matter of minutes of it going down.

![image](https://github.com/louislam/uptime-kuma/assets/53234499/4462cbcf-d035-436d-9549-985973dcd1ff)
These monitors are checked every 60 seconds as they're critical infrastructure and I need to be notified of unexpected downtime asap. However, on the status page, only <45 minutes are shown in the history. I'd like to be able to make this show the past hour.

This seems like a request that would make sense as the uptime badges (![badge](https://status.nexy7574.co.uk/api/badge/21/uptime/168)) can display an arbitrary number of hours in the past, so I don't see why the status page itself is limited to 45 minutes for 60 second intervals.

**Comment by CommanderStorm** [comment]
I think this is a duplicate of https://github.com/louislam/uptime-kuma/issues/1888
If you agree, could you please close this Issue, as duplicates only create immortal zombies and are really hard to issue-manage?
If not, what makes this issue unique enough to require an additional issue? (Could this be integrated into the issue linked above?) ^^

Note that [our contribution guide can be found here](https://github.com/louislam/uptime-kuma/blob/master/CONTRIBUTING.md)

**Comment by nexy7574** [comment]
Ah, I didn't see that, my bad. This is a duplicate though, thank you :)
