### ISSUE TITLE
ZFS zpool status check

### ISSUE THREAD

**Issue by curiousercreative** [louislam/uptime-kuma#3908]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

Hello, I'm new to Uptime Kuma and I'm trying to determine if the app supports checking the status of a ZFS zpool. I've got a DIY offsite backup server that has a zpool that occasionally becomes unavailable. Maybe some sort of bash/SSH command with something I expect to find (or inverse) via grep? In bash, it'd be something like `ssh 192.168.100.100 'zpool status POOL_NAME' | grep 'state: ONLINE'`

### 🐻 Uptime-Kuma Version

N/A

### 💻 Operating System and Arch

Ubuntu 22.04

### 🌐 Browser

N/A

**Comment by CommanderStorm** [comment]
Currently, this is not possible using the build in monitors.
Running scripts is tracked in #1117 but the security aspect of said monitor has not been fully explored.
However, you can build your own custom monitor and call the Push-montor's url with the result.

**Comment by CommanderStorm** [comment]
Closing in favor of https://github.com/louislam/uptime-kuma/issues/1117
