### ISSUE TITLE
Status page has no auto-theme button

### ISSUE THREAD

**Issue by wc7086** [louislam/uptime-kuma#3909]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### Description

![image](https://github.com/louislam/uptime-kuma/assets/74053663/b08698b8-6640-414f-afa9-b16bdd1eb762)

### 👟 Reproduction steps

Edit status page

### 👀 Expected behavior

Allows the status page to automatically select a theme

### 😓 Actual Behavior

Status page has no auto-theme button

### 🐻 Uptime-Kuma Version

1.23.3

### 💻 Operating System and Arch

Windows Server 2012 x64

### 🌐 Browser

EDGE 118.0.2088.46

### 🟩 NodeJS Version

18.18.2

**Comment by chakflying** [comment]
Please check if you are actually running the latest version.

![image](https://github.com/louislam/uptime-kuma/assets/3271800/01647da1-1472-4766-92a6-338d6233b207)

**Comment by wc7086** [comment]
![image](https://github.com/louislam/uptime-kuma/assets/74053663/56ac7271-38ca-4f6d-952c-ff1275d6051f)
Sorry, I typed the wrong system, I am using `Windows Server 2012`

**Comment by chakflying** [comment]
The page should also show your Frontend version if installed correctly.

![image](https://github.com/louislam/uptime-kuma/assets/3271800/acab4b75-7f24-4b13-8251-beb7193b8b97)

You have most likely updated incorrectly, and the frontend is stuck in an old version. Please follow the instructions in the [wiki](https://github.com/louislam/uptime-kuma/wiki/%F0%9F%86%99-How-to-Update) carefully, make sure there are no errors during the `download-dist` step before restarting the server.

**Comment by wc7086** [comment]
When I repeated the upgrade process and cleared the browser cache, the front-end version showed up correctly. This could be a caching issue. I will revise the content of this issue later.
