### ISSUE TITLE
SSL Certificate Expiry Date Monitoring for HTTP(s) - Keyword Mode

### ISSUE THREAD

**Issue by shivesh96** [louislam/uptime-kuma#3926]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### Problem:
Current HTTP monitoring system missing SSL certificate expiry date tracking, which is essential for maintaining the security and reliability of our services. To address this issue, we propose implementing SSL certificate expiry date monitoring with a focus on a HTTP(s) - Keyword mode.

### Add New Monitor
- In GENERAL settings > Monitor Type
- Select HTTP(s) - Keyword
- Fill all remain required Field with "Certificate Expiry Notification" checkbox.
- This will start monitoring.

### Create a status page
- Now On Right Top corder
- click "Status Page"
- Click New Status Page
- Fill Name and Slug
- Click Next
- Now Add Previously created monitor.
- Make sure tick "Show Certificate Expiry" just above save button on Bottom Left corner.
- Click Save Button.

### 👀 Expected behavior

It Should be shown Certificate Expiry Date too on status page.

### 😓 Actual Behavior

Currently not showing Certificate Expiry Date on HTTP(s) - Keyword mode.

### 🐻 Uptime-Kuma Version

1.23.2

### 💻 Operating System and Arch

Ubuntu Docker Environment

### 🌐 Browser

Google Chrome

### 🐋 Docker Version

Docker 20.10.21

![Screenshot 2023-10-21 at 9 22 48 PM](https://github.com/louislam/uptime-kuma/assets/905995/6bc2f750-bf7b-4dc5-bba5-c5ac6c2efcfc)

**Comment by CommanderStorm** [comment]
Cannot confirm.
Could you provide a reproducible example via <https://badssl.com>?

![image](https://github.com/louislam/uptime-kuma/assets/26258709/ceae7929-8933-4c60-bed5-9a08c30fd730)
![image](https://github.com/louislam/uptime-kuma/assets/26258709/318a0ded-6d7c-49e9-aee4-c514f3567e41)

**Comment by CommanderStorm** [comment]
Closing as unreproducible.
@shivesh96 If you find a way to reproduce this in the future, we can reopen this issue ^^
