### ISSUE TITLE
hosting uptime kuma instance

### ISSUE THREAD

**Issue by 7zx** [louislam/uptime-kuma#3927]
Should I host my Uptime Kuma instance on a VPS or outside my network if I want to monitor self-hosted services using their local IPv4 addresses? My concern is that if there's an outage or a brief Wi-Fi disruption at my location, the Uptime Kuma instance, which is hosted on the same network, won't be able to accurately detect downtime for these services. 

Furthermore, I'm hosting my services using Cloudflare tunnels to avoid opening ports in my router for security reasons. Given this setup, I'd like to monitor the local IPv4 addresses of these services, and it seems my only option is to host the Uptime Kuma instance inside my own network (server). What would you recommend for such monitoring scenarios, especially with the use of Cloudflare tunnels for added security?

**Comment by 7zx** [comment]
And could I effectively monitor my self-hosted services using their local IPv4 addresses when hosting Uptime Kuma outside my network or on a VPS?

**Comment by 7zx** [comment]
I should note that monitoring the services through their domains (each service it’s being hosted via a subdomain) is not an option for me; I prefer monitoring them via their local IPv4 addresses.

**Comment by CommanderStorm** [comment]
So first of all, if the wifi is down and `uptime-kuma` is hosted behind the wifi you will not get notified (depending on what notification provider, but most require internet access)

=> if you want to monitor for this case the notification system needs to live on an vps and you need to use `push`-monitors
=> if this case does not matter to you, setting uptime-kuma up inside your local network (i.e. behind the potential network partition) is fine.

**Comment by 7zx** [comment]
With push-monitors i can monitor my services through their local ipv4 with uptime kuma instance hosted on a VPS right?

**Comment by CommanderStorm** [comment]
Yes, the push monitor will notify you of failed check-ins
![image](https://github.com/louislam/uptime-kuma/assets/26258709/b47d1780-d1bf-46b4-b77d-61e75a1d6514)

**Comment by louislam** [comment]
Or use Tailscale, can join all your machines into a new private network.

**Comment by 7zx** [comment]
what method should i use to call the URL every 20 seconds (in my case its 20 seconds)? im on debian 11

**Comment by 7zx** [comment]
what method should i use to call the URL every 20 seconds (in my case its 20 seconds)? This is to monitor my Debian server.

should i use a bash script and run it in the background like:

```
#!/bin/bash

while true; do
  curl -s "https://status.polido.pt/api/push/EXAMPLE?status=up&msg=OK&ping=" > /dev/null 2>&1

  sleep 20
done
```
or is there a better method?

**Comment by 7zx** [comment]
Which approach should I employ to periodically request the URL every 20 seconds, specifically for monitoring my Debian server? Is utilizing a background-running bash script, such as the one below:
```
#!/bin/bash

while true; do
  curl -s "https://status.polido.pt/api/push/EXAMPLE?status=up&msg=OK&ping=" > /dev/null 2>&1
  sleep 20
done
```

Or alternatively, are there more effective methods to achieve this?

**Comment by chakflying** [comment]
Running a bash script is fine. The things you need to think about is:

- how to keep the script running automatically. You can setup a cron job or a systemd timer.
- Whether you want additional logic in your script. For example you can visit the local url of the service you are monitoring to make sure it's running fine before calling the push url.
