### ISSUE TITLE
Website Operational, Monitor Indicates DOWN

### ISSUE THREAD

**Issue by 7zx** [louislam/uptime-kuma#3933]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

My websites, which are using Cloudflare DNS, appear as 'DOWN' on Uptime Kuma with a 'Request failed with status code 403' error, despite their operational status.

### 📝 Error Message(s) or Log

`Request failed with status code 403`

### 🐻 Uptime-Kuma Version

1.23.3

### 💻 Operating System and Arch

Debian 12

### 🌐 Browser

Google Chrome

### 🐋 Docker Version

Docker version 20.10.24+dfsg1, build 297e128

**Comment by 7zx** [comment]
**Uptime Kuma Instance:** https://status.polido.pt/status/services

**Comment by 7zx** [comment]
I am using HTTPS monitors.

**Comment by 7zx** [comment]
If it's relevant, all the websites under monitoring utilize Cloudflare Tunnels, so does the Uptime Kuma instance mentioned here: https://status.polido.pt/status/services

**Comment by 7zx** [comment]
To address the issue, I resolved it by taking the following steps:

**Identified the Issue:** I noticed that the websites were showing as 'DOWN' due to **Bot Fight Mode** being enabled in Cloudflare. I found evidence of this in the firewall events, which indicated that the monitoring agent was being challenged.

**Filtered User Agent and IP Address:** To resolve the problem, I filtered the user agent 'Uptime-Kuma/1.23.3' and the IP address 54.93.204.118 in Cloudflare's firewall settings. This effectively whitelisted the monitoring agent, allowing it to access the websites without interference.

With the IP address and user agent filtered, I can now keep **Bot Fight Mode** enabled without any issues.

By implementing these changes, I successfully resolved the issue, and the websites now report their operational status accurately.

**Firewall Events Activity logs:**

![image](https://github.com/louislam/uptime-kuma/assets/83615960/0bfe40c1-c207-4aa2-8635-e89429bb291e)

**Comment by 7zx** [comment]
I temporarily disabled Bot Fight Mode, which resolved the issue. However, I prefer to have it enabled for security reasons.
So i checked out my firewall logs and saw this:

![image](https://github.com/louislam/uptime-kuma/assets/83615960/5b51ab84-9cb6-40ee-ad4f-2462961d71b0)

I have created custom rules to allow the specific User-Agent and IP Address associated with Uptime Kuma, and re-enabled Bot Fight Mode. Oddly, the websites are once again inaccessible for monitoring purposes.

Am I missing something in my custom rule configuration? Are there additional User-Agents or IP addresses associated with Uptime Kuma that need to be whitelisted for successful monitoring without disabling Bot Fight Mode?

**Comment by 7zx** [comment]
![image](https://github.com/louislam/uptime-kuma/assets/83615960/f96ec8e2-efd4-4f6c-b00c-fd7f9b0f16ad)

![image](https://github.com/louislam/uptime-kuma/assets/83615960/1740ac4a-08c6-444a-bc94-16413c40b292)

**Comment by 7zx** [comment]
I temporarily disabled Bot Fight Mode, which resolved the issue. However, I prefer to have it enabled for security reasons. So what can i do to be able to use Uptime Kuma and have Bot Fight Mode enabled?

**Comment by 7zx** [comment]
i already allowed my vps ip which my uptime kuma instance is behing hosted, but with Bot Fight Mode enabled, the monitors still show the `Request failed with status code 403` error:

![image](https://github.com/louislam/uptime-kuma/assets/83615960/8eebb900-95cc-42cf-a3ad-4c60951dbb10)

**Comment by mabed-fr** [comment]
> i already allowed my vps ip which my uptime kuma instance is behing hosted, but with Bot Fight Mode enabled, the monitors still show the `Request failed with status code 403` error:
> 
> ![image](https://user-images.githubusercontent.com/83615960/277497851-8eebb900-95cc-42cf-a3ad-4c60951dbb10.png)

Skip all not only custom rules

**Comment by 7zx** [comment]
same results

**Comment by mabed-fr** [comment]
look at the rule that blocks uptime kuma requests in waf events, you may have other rules

**Comment by CommanderStorm** [comment]
> which resolved the issue

I am going to close this issue as likely resolved
