### ISSUE TITLE
Groups show as completely down, when any one child monitor is down.

### ISSUE THREAD

**Issue by kristiandg** [louislam/uptime-kuma#3937]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### Description

In the attached pic, I have a handful of monitors nested into a group, but when any one of them is down, the entire group shows as down, rather than some variation of "degraded".
<img width="440" alt="Screenshot 2023-10-25 at 11 34 08 AM" src="https://github.com/louislam/uptime-kuma/assets/33264300/f1f9656c-61b6-4e87-9718-be4423defef9">

In an ideal world, the group's badge should show as partially degraded (instead of fully down), and mathematically, maybe even it's percentage take into account the child nodes (as in, for the pic above, the group, which consists of 3 items, one of which is down, would show 66.67%). Since you can nest groups into other groups, the logic needs to also calculate that based on that nesting. I had expected it to do this, and not show the whole group as completely down.

I'm not sure if there's a use-case for showing all down in a group, when any one item is impacted, but if so, maybe groups could have a toggle that allows it to calculate it either way.

### 👟 Reproduction steps

Create a group of monitors, and force one monitor into a failed state. You should see the group show as completely failed as well, rather than a degraded state.

### 👀 Expected behavior

When a monitor group has some items operational and some items down, I'd expect the group's statistics to show partially degraded and mathematically calculate the down percentage (such as, 3 items and 1 down calculates to 66.67%). Equally, nested groups should calculate that way too (same 3/1 group is 66.67% operational, but that group is nested with 9 other groups that are fully up, inside of a parent group, so mathematically, the parent group is really only 3% down (I hope I did that math right).

### 😓 Actual Behavior

Groups with any one monitor down, are showing 0% operational.

### 🐻 Uptime-Kuma Version

1.23.3

### 💻 Operating System and Arch

Ubuntu 23.10

### 🌐 Browser

Safari 17.0 (Mac)

### 🐋 Docker Version

n/a

### 🟩 NodeJS Version

18.13.0

### 📝 Relevant log output

```shell
N/A
```

**Comment by chakflying** [comment]
Duplicate of #3562

**Comment by kristiandg** [comment]
I guess that's fine. My take on that was that it was more of a feature request, and I was considering this a mathematic bug.  Maybe the other one can be re-classified as bug because literally, things nested in a group, clearly aren't 100% down when there's still 1 item functional.  That 3562 also didn't account for double-nesting groups and how to handle that math.  

Thoughts?

**Comment by chakflying** [comment]
Currently the group monitor is only up if all the child monitors are up in the given time period. This is calculated on every interval individually. This is not a bug.

**Comment by kristiandg** [comment]
Ah, ok then. I'll close this and upvote the FR.  Thanks.
