### ISSUE TITLE
Certificate says "Unable to verify" for valid wildcard cert

### ISSUE THREAD

**Issue by kristiandg** [louislam/uptime-kuma#3939]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### Description

I have a LetsEncrypt wildcard cert that is showing valid in a regular browser, but Kuma says "Unable to verify the first certificate" (which I don't fully understand that statement - "first" cert?).  Below are pics of the valid cert and the monitor status log.

<img width="498" alt="Screenshot 2023-10-25 at 3 54 21 PM" src="https://github.com/louislam/uptime-kuma/assets/33264300/05c09405-532b-4d3a-92e0-5ffec95c223e">
<img width="480" alt="Screenshot 2023-10-25 at 3 53 33 PM" src="https://github.com/louislam/uptime-kuma/assets/33264300/b15ca231-98ed-40e1-a8cd-29f7b6356103">
<img width="551" alt="Screenshot 2023-10-25 at 3 54 48 PM" src="https://github.com/louislam/uptime-kuma/assets/33264300/114b73da-aeea-4190-a64f-2dd25bdcab67">

I also have a second LetsEncrypt cert that is expired, and that one properly shows as expired, but I'm not sure why the valid one is showing as unable to verify.

### 👟 Reproduction steps

I can DM you the URL to test with, if you like (would prefer not to put it in a public forum). 

### 👀 Expected behavior

On the valid cert, I expected it to show as green and valid, then also monitoring the expiration date.

### 😓 Actual Behavior

Upon creation of the monitor, it shows as PENDING for 24 hours, then switches to DOWN with the events "unable to verify first cert".as the reasoning.

### 🐻 Uptime-Kuma Version

1.23.3

### 💻 Operating System and Arch

Ubuntu 23.10

### 🌐 Browser

Safari 17.0 (Mac)

### 🐋 Docker Version

n/a

### 🟩 NodeJS Version

18.13.0

**Comment by adamhancock** [comment]
@kristiandg If you want to send me your URL I can test this. I suspect the server is not providing the intermediary certificate in its response. I've seen this before where its fine in a browser but not with other clients. 

How is Lets Encrypt setup on your server you're checking with Uptime Kuma? Do you have a LE client creating the certificate and then you've manually added it into apache configuration?

**Comment by kristiandg** [comment]
@adamhancock ok, this is silly, but how do I send that to just you :)

And, to answer your question, the server being monitored, it's the LetsEncrypt agent spinning the cert and then I manually place it and bounce apache.

**Comment by adamhancock** [comment]
@kristiandg Ah sorry - email it to this throwaway: rimethohil@mywrld.top

Is it an old version of Apache? Can you check the config against https://ssl-config.mozilla.org with the right apache version.

**Comment by kristiandg** [comment]
@adamhancock Emailing you now, but it's an appliance, essentially, and I can't really modify the config of Apache except to add certs for specific hosts.  But it's version 2.4.48 (Ubuntu).

**Comment by kristiandg** [comment]
@adamhancock Did you see anything notable in what I sent?

**Comment by war59312** [comment]
Having a similar issue with Gotify.

Gotify is also using a wildcard cert, from ZeroSSL.

Gotify is behind an nginx proxy: https://gotify.net/docs/nginx

Uptime-kuma is also behind an nginx proxy: https://github.com/louislam/uptime-kuma/wiki/Reverse-Proxy

**Comment by j-hudecek** [comment]
Hi, I'm seeing the same issue with a wildcard certificate. Perhaps it's too soon to close it as stale
