### ISSUE TITLE
Setup Uptime Kuma with Docker and Plesk

### ISSUE THREAD

**Issue by creperozelot** [louislam/uptime-kuma#3943]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

Try to connect Uptime-Kuma-Docker in Plesk with a domain. Getting error on page load: `Cannot connect to the socket server. [Error: websocket error]...`. I tried many ways, editing nginx / Apache. Added .htaccess file and tried to deploy on Node.js. How can i fix this issue?

Referring to https://github.com/louislam/uptime-kuma/issues/1264#issuecomment-1531401026 (Didn't Work) Some Node errors...

### 📝 Error Message(s) or Log

Original: `Cannot connect to the socket server. [Error: websocket error] Die Verbindung wird wiederhergestellt...
Wird ein Reverse Proxy genutzt? [Prüfen, wie er für die Nutzung mit WebSocket konfiguriert wird](https://github.com/louislam/uptime-kuma/wiki/Reverse-Proxy)`

Translated: `Cannot connect to the socket server. [Error: websocket error] Reconnecting... Using a Reverse-Proxy? [Check, how to setup with WebSocket](https://github.com/louislam/uptime-kuma/wiki/Reverse-Proxy)`

### 🐻 Uptime-Kuma Version

1.23.3

### 💻 Operating System and Arch

Debian 11

### 🌐 Browser

Google Chrome 116.0.5845.110

### 🐋 Docker Version

Docker version 24.0.6, build ed223bc, Integrated in Plesk

### 🟩 NodeJS Version

null

**Comment by rezzorix** [comment]
Docker is not integrated in Plesk. 

Docker runs on your server; Plesk has a module to manage Docker containers (similar to Portainer, but very primitive).

Could you give some more information?

Are you hosting the server?
Or are you just a user using the Plesk Panel?

What type of server?
What Plesk licence?

Since I see you are German; you may also let me know your Server Provider & Package, then I can advise even further. Some Providers restrict usage, sometimes you have to request more permissions… sometimes its not possible.

**Comment by creperozelot** [comment]
> Docker is not integrated in Plesk.
> 
> Docker runs on your server; Plesk has a module to manage Docker containers (similar to Portainer, but very primitive).
> 
> Could you give some more information?
> 
> Are you hosting the server? Or are you just a user using the Plesk Panel?
> 
> What type of server? What Plesk licence?
> 
> Since I see you are German; you may also let me know your Server Provider & Package, then I can advise even further. Some Providers restrict usage, sometimes you have to request more permissions… sometimes its not possible.

1. Yeah, I'm hosting the Server
2. Currently, it's a V-Server on Strato running with Plesk Web Admin Edition

**Comment by creperozelot** [comment]
Any Suggestions
