### ISSUE TITLE
Service was down but in Uptime Kuma it was stuck as "Pending"

### ISSUE THREAD

**Issue by siimots** [louislam/uptime-kuma#3946]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### Description

I did docker update in one of my servers (services, not Uptime Kuma server) and after reboot it stopped working after 5 minutes.

![image](https://github.com/louislam/uptime-kuma/assets/7014925/282debaa-9eff-42e6-8b63-00f7792297bb)

Another server (Uptime Kuma) monitors it  and all those crashed docker services in Uptime Kuma were stuck in "Pending" state for 12 hours before I noticed.

All those services have similar settings:
HTTP GET or JSON keyword montitor

![image](https://github.com/louislam/uptime-kuma/assets/7014925/231ea1fe-6440-489e-9f35-cb4368cbf9cc)

All those services show similar "Pending" graph

### 👟 Reproduction steps

1. Make services you monitor offline
2. Let Reverse proxy keep working (Caddy)
3. Reverse proxy shows Error 502 in browser

### 👀 Expected behavior

If service is "Pending" for 12 hours it should be marked as down.
I guess 60 minutes is maximum to stay pending.

### 😓 Actual Behavior

Uptime Kuma stays in pending state for unlimited time (at least 12hours in my case)

### 🐻 Uptime-Kuma Version

1.23.3

### 💻 Operating System and Arch

Ubuntu 22.04.3 LTS (GNU/Linux 5.15.0-1046-oracle x86_64)

### 🌐 Browser

Edge

### 🐋 Docker Version

Docker version 24.0.6, build ed223bc

**Comment by siimots** [comment]
Actual service went down around 23:35 and around 11:15 I started restart servers & debug docker failure.

<img width="556" alt="Screenshot 2023-10-26 at 19 11 07" src="https://github.com/louislam/uptime-kuma/assets/7014925/e454f09b-1ed1-443d-85d6-229aa63a416e">

Another strange graph where there is maintenace period (6-9AM) (... Websocket in Telegram notification)
![image](https://github.com/louislam/uptime-kuma/assets/7014925/e15ec7c2-10ea-4b23-a8ff-c4759deb0072)

**Comment by CommanderStorm** [comment]
Closing as resolved by #3952 and released in `1.23.4`
