### ISSUE TITLE
Added new Uzbek language

### ISSUE THREAD

**Issue by golibnarzullayev** [louislam/uptime-kuma#3954]
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [x] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

UI Feature

### 🔖 Feature description

Adding the Uzbek language to make it easier for Uzbek users

### ✔️ Solution

I will translate every word to be translated into Uzbek

### ❓ Alternatives

There is no alternative

**Comment by louislam** [comment]
Welcome. You could follow this guide: https://github.com/louislam/uptime-kuma/blob/master/src/lang/README.md

However, in case you don't know how to create a pull request or add the language into the dropdown menu. I could prepare it for you, but there are two uz code: `uz` and `uz_Latn`, which one do you use?
![image](https://github.com/louislam/uptime-kuma/assets/1336778/a5127ff4-9f32-4b7d-b458-69ae4a3adda4)

**Comment by golibnarzullayev** [comment]
> Welcome. You could follow this guide: https://github.com/louislam/uptime-kuma/blob/master/src/lang/README.md
> 
> However, in case you don't know how to create a pull request or add the language into the dropdown menu. I could prepare it for you, but there are two uz code: `uz` and `uz_Latn`, which one do you use? ![image](https://user-images.githubusercontent.com/1336778/278797478-a5127ff4-9f32-4b7d-b458-69ae4a3adda4.png)

I choose uz code

**Comment by louislam** [comment]
You can translate on Weblate now, thanks.
https://weblate.kuma.pet/translate/uptime-kuma/uptime-kuma/uz/?q=state%3A%3Ctranslated&offset=1

Is `Ўзбек тили` correct?

https://github.com/louislam/uptime-kuma/blob/12cc2f15076df61cb404545058ed54be4ad1c14f/src/i18n.js#L46

**Comment by golibnarzullayev** [comment]
> You can translate on Weblate now, thanks. https://weblate.kuma.pet/translate/uptime-kuma/uptime-kuma/uz/?q=state%3A%3Ctranslated&offset=1
> 
> Is `Ўзбек тили` correct?
> 
> https://github.com/louislam/uptime-kuma/blob/12cc2f15076df61cb404545058ed54be4ad1c14f/src/i18n.js#L46

`O'zbek tili`
