### ISSUE TITLE
Bearer token not available in 0.9.1

### ISSUE THREAD

**Issue by vdiogo** [louislam/uptime-kuma#3960]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### Description

According to https://github.com/louislam/uptime-kuma/issues/3033 the feature supporting bearer token was meant to be available in a previous version of uptime-kuma but I cannot find it:
![image](https://github.com/louislam/uptime-kuma/assets/24878195/2821a787-410e-44af-a1ae-049b5895c8ba)

### 👟 Reproduction steps

Add a new monitor and select authentication method

### 👀 Expected behavior

Expected Bearer token support

### 😓 Actual Behavior

Bearer token not available

### 🐻 Uptime-Kuma Version

0.9.1

### 💻 Operating System and Arch

Linux 6.1.21-v8

### 🌐 Browser

Google Chrome 118.0.5993.117

### 🐋 Docker Version

24.0.6

**Comment by louislam** [comment]
#3033 is for NTFY notification.

You can set a custom header.
