### ISSUE TITLE
Only View

### ISSUE THREAD

**Issue by volkankoc** [louislam/uptime-kuma#3962]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

How can I show "Uptime Kuma" only in watch mode? I will make the settings myself and I do not want anyone to intervene on the computer where it is displayed.

### 🐻 Uptime-Kuma Version

1.23.3

### 💻 Operating System and Arch

Macos

### 🌐 Browser

Chrome

**Comment by chakflying** [comment]
You can create a status page, button available top-right of the dashboard.
