### ISSUE TITLE
Hundreds of SSL certificate expiry emails

### ISSUE THREAD

**Issue by SkwalExe** [louislam/uptime-kuma#3964]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

I enabled the SSL certificate expiry notification feature because I want to receive an email when my certificates only have one week of validity left.

But it seems to send an email every hour, how can I disable that? I already received 200+ emails and its really annoying 

### 🐻 Uptime-Kuma Version

1.23.3

### 💻 Operating System and Arch

Ubuntu Server 22.04

### 🌐 Browser

Doesn't matter

### 🐋 Docker Version

Not using docker

### 🟩 NodeJS Version

16

**Comment by louislam** [comment]
It shouldn't be like this. It may be a bug.

You can try to lower the days here.
![image](https://github.com/louislam/uptime-kuma/assets/1336778/ec5c3d10-d41e-4c74-943e-17958a6591eb)

**Comment by SkwalExe** [comment]
Thank you for your answer. If I lower the days, for example to 2 days, I will continue to receive a lot of emails when the certificate's validity lifetime passes below 2 days. It doesn't look like a 'bug' since I receive an email precisely every hour. I think there should be a checkbox to enable/disable those 'repeated' emails.

**Comment by CommanderStorm** [comment]
I cannot reproduce this behaviour on my side (https monitor)
=> I get notified only once at the next check after the deadline of tls cert expiry has elapsed

What monitor are you using?

**Comment by SkwalExe** [comment]
I have the problem with multiple monitor. Each hour I get one notification for every monitor.

**Comment by CommanderStorm** [comment]
as asked above:
what monitor are you using?
If the domain is publicly accessible: what is the domain?

**Comment by SkwalExe** [comment]
![image](https://github.com/louislam/uptime-kuma/assets/69600456/abd1c136-8b38-4e2b-be31-bd7e6318116e)

**Comment by CommanderStorm** [comment]
Currently, I could not replicate this issue.
Can you provide us a [Minimal, Reproducible Example](https://stackoverflow.com/help/minimal-reproducible-example)?

Are you shure that these are the same monitor? (do you maybe have a duplicate monitor?)

We have a demo site avaliable at https://demo.uptime.kuma.pet/
Could you test your exact configuration on there?

![image](https://github.com/louislam/uptime-kuma/assets/26258709/faf08170-aaba-4ef0-9779-fec3d262a2b3)
Note that if it were to notify every time, there would be more than one instance of the message

**Comment by SkwalExe** [comment]
I dont have any duplicate monitors, and even if I had duplicate monitors, why would I receive hundreds of notifications ? I would just receive 2 right?

I think you can't reproduce the issue because you don't have the same nodejs version as me. In your screenshot, it shows 89 days remaining because it uses IPv6 so its the certificate of the hosting srever. Nodejs 16 prioritizes IPv4, which makes the requests pass through a reverse proxy (certificate of the reverse proxy => 7 days left).


Also, I think the demo site has a problem, 
![image](https://github.com/louislam/uptime-kuma/assets/69600456/a08b8337-61cb-4593-b34d-8bd6b82b8ce0)

I will try to make a minimal reproducible example. Thank you for your help!

**Comment by SkwalExe** [comment]
I tried everything but I couldn't reproduce the issue with another Uptime K instance. I think I'll just disable ssl notifications for now and see if the issue persists after the next major release. Thanks a lot for your help.
