### ISSUE TITLE
New Software Update Status - Broken

### ISSUE THREAD

**Issue by EVIL-Teken** [louislam/uptime-kuma#3965]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### Description

Noticed there was no update notification banner on the dashboard while running v.1.23.2. Perhaps this bug is fixed in the latest general release v.1.23.3 which I'm running now?!? 

### 👟 Reproduction steps

NA

### 👀 Expected behavior

Upon general release of new software the dashboard should indicate a new release at the top. This was not seen at all while using various workstations running Windows 7, 10, 11 viewing with Chrome web browser.

### 😓 Actual Behavior

No new software notification at the top of the Dashboard.

### 🐻 Uptime-Kuma Version

1.23.2

### 💻 Operating System and Arch

Linux 5.10.103-v7l+ (Raspbian)

### 🌐 Browser

Version 103.0.5060.132 (Official Build) (64-bit)

### 🐋 Docker Version

Docker version 23.0.1, build a5ee5b1

**Comment by cyril59310** [comment]
Hello, it's not a bug. The version is retrieved from this URL https://uptime.kuma.pet/version, which is manually updated by louislam, but it has not been updated for 1.23.3."

**Comment by louislam** [comment]
Updated. It is indeed not a bug and I usually update this json file slowly, but this time I actually forgot. Thanks for let me know.
