### ISSUE TITLE
Gaps shown in heartbeat graph for ping less than 1ms

### ISSUE THREAD

**Issue by supermarkert** [louislam/uptime-kuma#3966]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### Description

When using a Push Monitor on my LAN and using the optional Ping paramenter, my pings are often (but not always) less than 1ms.  So this results in a Push URL such as: 
`http://uptimekuma.lan:3001/api/push/[code]?status=up&msg=OK&ping=0.982`

Which works great (I can confirm UptimeKuma has received the Push), except the Heartbeat graph on the Y-axis only seems to go down to 1.0 ms, and all pings less than 1ms are not indicated and show up as blank on the X-axis.

![Node ping](https://github.com/louislam/uptime-kuma/assets/15205204/e27ae6f4-065e-4619-85ca-35f97c30fc65)

### 👟 Reproduction steps

Create a Push monitor, and send the URL with an optional Ping parameter of < 1.0

### 👀 Expected behavior

I would expect the heartbeat graph to resolve all the way down to zero, and include all pings. I would be fine if the ping on the graph would simply round up to 1ms.

### 😓 Actual Behavior

If I hover over the ping location, I can see on the graph that the hearbeat is registered and rounded up to 1ms (this is fine), but otherwise pings < 1ms do not appear and show up as gaps in the graph, and Y-axis of the graph only goes down to 1.0 ms. 

### 🐻 Uptime-Kuma Version

1.23.3

### 💻 Operating System and Arch

Debian 12 x64

### 🌐 Browser

Google Chrome 118.0.5993.117

**Comment by chakflying** [comment]
Fixed by #3987.

**Comment by supermarkert** [comment]
Works perfect. Thanks!
