### ISSUE TITLE
Updating without losing data

### ISSUE THREAD

**Issue by aciducen1995** [louislam/uptime-kuma#3968]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [x] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

May i know what is the appropriate way to update uptime-kuma without losing any data? The steps i always do are as below but sometime its working sometimes its not working.

- docker pull louislam/uptime-kuma:1
- docker volume create uptime-kuma-v1.23.3
- docker run -d --restart=always -p 3001:3001 -v uptime-kuma-v1.23.3:/app/data --name uptime-kuma-v1.23.3 louislam/uptime-kuma:1
- Transfer all the database tables except heartbeat to this newly created container using Heidi SQL

FYI, i have 800+ monitoring with already have 9GB for kuma.db. 

### 📝 Error Message(s) or Log

This is the error i get when i do docker logs --details containerID

at consoleCall (<anonymous>)
     at Timeout.safeBeat [as _onTimeout] (/app/server/model/monitor.js:987:25)
 2023-10-31T04:11:50+08:00 [MONITOR] ERROR: Please report to https://github.com/louislam/uptime-kuma/issues
 2023-10-31T04:11:50+08:00 [MONITOR] INFO: Try to restart the monitor
 Trace: [Error: select * from `heartbeat` where  monitor_id = 614 ORDER BY time DESC limit 1 - SQLITE_CORRUPT: database disk image is malformed] {
   errno: 11,
   code: 'SQLITE_CORRUPT'
 }

Sometimes it works maybe depending on the updated version. but for this latest v.1.23.3, I always failed to update. once transfer the db, uptime kuma reconnects every 1 minute

### 🐻 Uptime-Kuma Version

1.23.3

### 💻 Operating System and Arch

Oracle Linux 8.5

### 🌐 Browser

Google Chrome

### 🐋 Docker Version

20.10.17

**Comment by louislam** [comment]
First thing first, make a backup of your old volume first.

You don't need to create a new volume. You can use the same volume all the time.

You should follow:
https://github.com/louislam/uptime-kuma/wiki/%F0%9F%86%99-How-to-Update

Transferring data using HeidiSQL is not recommended, because Uptime Kuma has its own database migration process.

**Comment by aciducen1995** [comment]
Thank you for your time to reply. I have seen that wiki but never knew it has its own database migration. I assume it uninstall old container since its has "rm" command.

**Comment by CommanderStorm** [comment]
See
https://docs.docker.com/engine/reference/run/#clean-up---rm

The local file system of the container indeed gets deleted and the container also gets deleted.
What does not get deleted though is the volume, as it lives "outside" (not correct, but close enough) of docker

**Comment by aciducen1995** [comment]
@louislam sorry if its out of context, is their a way to change uptime percentage in status page? as far as i know, the uptime is only 24h. any plan for this?

**Comment by CommanderStorm** [comment]
Inital requirements for such a feature were added by https://github.com/louislam/uptime-kuma/pull/2750
See issues like https://github.com/louislam/uptime-kuma/issues/2477 (and all the issues linked to it)

Here is our contribution guide: https://github.com/louislam/uptime-kuma/blob/b534fde26512bb4e6ae674aa92d5447c11e15b2c/CONTRIBUTING.md
