### ISSUE TITLE
Notification type "OPSGenie" - Unable to send notifications via a proxy

### ISSUE THREAD

**Issue by JulienAubert9** [louislam/uptime-kuma#3969]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### Description

Hello,

With the notification integration type "OPSGenie", it's impossible to transmite notification through a proxy because the integration is not able to talk correctly to http proxy.

We see direct requests "POST https://api.eu.opsgenie.com/v2/alerts" in the logs, this is not supported.
The integration has to first open a tunnel using CONNECT method: e.g.: "CONNECT api.eu.opsgenie.com:443 HTTP/1.0"

A "curl" command is automatically do this, for example.
Please, could you add this possibility ? We use Kuma behind a proxy

Thank you in advance

### 👟 Reproduction steps

Configure the notification integration "OPSGenie" and use is through a proxy

### 👀 Expected behavior

The notification integration "OPSGenie" should be able to send notification through a proxy.

### 😓 Actual Behavior

Error 503 when we test to send a notification because the proxy refuse the connection

### 🐻 Uptime-Kuma Version

1.23.3

### 💻 Operating System and Arch

Portainer integration

### 🌐 Browser

Not relevant

**Comment by CommanderStorm** [comment]
Not a bug, but a feature request.
None of the notification providers use the proxy settings

If you'd like to contribute such a feature see our [contribution guide](https://github.com/louislam/uptime-kuma/blob/df832f15fe21c5afc2d3e1d040bced79790962f2/CONTRIBUTING.md)

**Comment by CommanderStorm** [comment]
Duplicate of #616
