### ISSUE TITLE
Export not working

### ISSUE THREAD

**Issue by R0GGER** [louislam/uptime-kuma#397]
**Is it a duplicate question?**
No.

**Describe the bug**
Export doesn't work, it only exports my default notifications.
I started over in a clean database with the same monitors and notifications, but also in this new container and database I had the problem.

Screenshot monitors and notifications:
The first two (2) notifications are set as default and apply to existing monitors.
![oBY6ve](https://user-images.githubusercontent.com/8298741/133003557-62acbd72-401a-4523-b912-acf9053dd7de.png)

Export output:
`{"version":"1.6.0","notificationList":[{"id":1,"name":"Uptime ALERT!","config":"{\"name\":\"Uptime ALERT!\",\"type\":\"telegram\",\"isDefault\":true,\"gotifyPriority\":8,\"smtpSecure\":false,\"telegramBotToken\":\"11111111111111111111111111111\",\"telegramChatID\":\"-1111111111111\",\"applyExisting\":true}","active":1,"userId":1,"isDefault":1},{"id":2,"name":"Uptime ALERT!","config":"{\"name\":\"Uptime ALERT!\",\"type\":\"smtp\",\"isDefault\":true,\"gotifyPriority\":8,\"smtpSecure\":true,\"smtpHost\":\"mail.mydomain.tld\",\"smtpPort\":465,\"smtpUsername\":\"notification@mydomain.tld\",\"smtpPassword\":\"*****`

**Info**
Uptime Kuma Version: 1.6.0
Using Docker?: Yes
Docker Version:  Docker version 20.10.8, build 3967b7d
OS: Debian 10
Browser: Google Chrome

**Comment by R0GGER** [comment]
Found it... My generated SMTP password was ending on a exclamation mark **!**. Somehow this **!** stops exporting the whole file...

**Comment by Saibamen** [comment]
FYI: @Ponkhy

**Comment by Ponkhy** [comment]
Thank you! I'll look into that later when i've more time

**Comment by Ponkhy** [comment]
nvm. i've already found the issue. It looks like the browser has some kind of problem with a "#" in the `href`.
I'll do a PR to fix the issue in a bit.

**Comment by louislam** [comment]
I just found the problem and fixed.

**Comment by Ponkhy** [comment]
Ahaha, was about to make my PR and was wondering why it looked different xD
