### ISSUE TITLE
Minecraft server service query

### ISSUE THREAD

**Issue by dev-Blaze** [louislam/uptime-kuma#3973]
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

New Monitor

### 🔖 Feature description

Ability to monitor uptime of minecraft servers. 

The TCP port monitor does not work for this. 

### ✔️ Solution

Minecraft server status api 
https://api.mcsrvstat.us/

the api pulls the server icon as well. It would be nice if the monitor can pull the icon for the status page as well.

**Comment by CommanderStorm** [comment]
see the gamedig monitor: minecraft uptime monitoring is already supported
Is there something I am missing?


Favicons on the statuspage would be a nice touch. This is tracked in #443 
Here is our contribution guide: https://github.com/louislam/uptime-kuma/blob/fdfb572e09bc6d4c4c0e80bde779cba0dad54ad1/CONTRIBUTING.md
