### ISSUE TITLE
Uptime Kuma on Netlify

### ISSUE THREAD

**Issue by koo1140** [louislam/uptime-kuma#3974]
### ⚠️ Please verify that this bug has NOT been raised before.

- [x] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

how to do it? give me a tutorial

if it isn't possible tell me

### 🐻 Uptime-Kuma Version

i dont think its necesary

### 💻 Operating System and Arch

i dont think its necesary

### 🌐 Browser

google chrome

### 🐋 Docker Version

i dont think its necesary

### 🟩 NodeJS Version

i dont think its necesary

**Comment by CommanderStorm** [comment]
You can find our installation guide (and video tutorials) here: https://github.com/louislam/uptime-kuma/wiki/%F0%9F%94%A7-How-to-Install

**Comment by CommanderStorm** [comment]
closing as currently impossible given our and netlifys archtecutre
