### ISSUE TITLE
Question about API and Group creation (and monitor assignment)

### ISSUE THREAD

**Issue by kristiandg** [louislam/uptime-kuma#3977]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

Good morning.  We're trying to set something up where, when a new project is spun up, the collection of monitors for that project are all created via API, and placed in a group for the project name. That way, when the project is spun down, or anyone working on the project needs to view those monitors, they can find their collection of monitors in the same place.

However, in the API documentation, I don't see the option for creating/editing a monitor type of "group" (which I would have expected). Additionally, when creating an actual monitor (such as, a ping), I don't see a key for "group membership" or something like that to place the monitor in the group.

Can someone shed some light on this, by chance?

Thank you.

### 📝 Error Message(s) or Log

n/a - API question, not a bug

### 🐻 Uptime-Kuma Version

1.23.1

### 💻 Operating System and Arch

n/a - API question, not reporting a bug

### 🌐 Browser

Various

### 🐋 Docker Version

n/a - API question, not a bug

### 🟩 NodeJS Version

n/a - API question, not a bug

**Comment by CommanderStorm** [comment]
To answer your question (if future people come across this issue):

- we currently don't offfer an api, see https://github.com/louislam/uptime-kuma/issues/118
- Current planned approach to resolve this is https://github.com/louislam/uptime-kuma/pull/3854

**Comment by kristiandg** [comment]
Thanks. I was confused because I saw within Kuma the API Key section, and on badges (the base URL including "/api/", which threw me.
