### ISSUE TITLE
Knex: Timeout acquiring a connection. The pool is probably full. Are you missing a .transacting(trx) call?

### ISSUE THREAD

**Issue by hmortensen2** [louislam/uptime-kuma#3978]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### Description

Get this error on some of my devices. Seems to be a problem with the ping call from uptime kuma. Please investigate.

### 👟 Reproduction steps

Occurs in my running of uptime kuma

### 👀 Expected behavior

successful ping

### 😓 Actual Behavior

error message as above

### 🐻 Uptime-Kuma Version

Version: 1.19.6

### 💻 Operating System and Arch

docker

### 🌐 Browser

 Version 118.0.5993.120

### 🐋 Docker Version

dont know

### 🟩 NodeJS Version

don't know

### 📝 Relevant log output

```shell
AP Third FLoor New	Down	2023-11-04 14:10:29	Knex: Timeout acquiring a connection. The pool is probably full. Are you missing a .transacting(trx) call?
ovif ip camera	Down	2023-11-04 14:10:29	Knex: Timeout acquiring a connection. The pool is probably full. Are you missing a .transacting(trx) call?
pfsense	Down	2023-11-04 14:10:22	Knex: Timeout acquiring a connection. The pool is probably full. Are you missing a .transacting(trx) call?
nas 1	Down	2023-11-04 14:10:21	Knex: Timeout acquiring a connection. The pool is probably full. Are you missing a .transacting(trx) call?
AP Third FLoor New	Up	2023-11-04 14:02:28	
AP Third FLoor New	Down	2023-11-04 13:59:12	Knex: Timeout acquiring a connection. The pool is probably full. Are you missing a .transacting(trx) call?
ovif ip camera	Up	2023-11-04 13:56:52	
ovif ip camera	Down	2023-11-04 13:53:29	Knex: Timeout acquiring a connection. The pool is probably full. Are you missing a .transacting(trx) call?
ovif ip camera	Up	2023-11-04 13:21:46	
ovif ip camera	Down	2023-11-04 13:18:34	Knex: Timeout acquiring a connection. The pool is probably full. Are you missing a .transacting(trx) call?
```

**Comment by CommanderStorm** [comment]
There may be multiple reasons for this behaviour.

- How many monitors do you have
- what is their composition
- what does your storage system under uptime-kuma look like
- how much cpu has your server and are there any noisy neighbours

v2 does fix most of these issues by allowing for `mariadb` as another storage option (plus a few misc. performance optimisations, like https://github.com/louislam/uptime-kuma/pull/2750 or https://github.com/louislam/uptime-kuma/pull/3515)

**Comment by CommanderStorm** [comment]
Potential Duplicates: https://github.com/louislam/uptime-kuma/issues/2324 https://github.com/louislam/uptime-kuma/issues/1219
