### ISSUE TITLE
/metrics page unreachable

### ISSUE THREAD

**Issue by sanerspace** [louislam/uptime-kuma#3983]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### Description

An integration requires the "http:[host]/metrics" page to be reachable. However the integration fails and when I try to visit that address manually I get asked to login, then it rejects my login.
I am able to reach the /dashboard and secure pages. I tried changing my password, as well as using an API key, and cannot log in with either one.
I am on version 0.9.1 running as an add-on to Home Assistant.
The integration is https://github.com/meichthys/uptime_kuma/blob/main/README.md.

### 👟 Reproduction steps

Attempt to visit "http://[hostname]/metrics", input login credentials

### 👀 Expected behavior

Expected to be admitted to a valid page.

### 😓 Actual Behavior

My login is rejected over and over. The login is via the browser popup, rather than via the usual Kuma login screen.

### 🐻 Uptime-Kuma Version

0.9.0

### 💻 Operating System and Arch

Hassio (version of Linux) running on Raspberry Pi 4.

### 🌐 Browser

Google Chrome 119.0.6045.105

**Comment by CommanderStorm** [comment]
see https://github.com/louislam/uptime-kuma/wiki/API-Keys

> API keys can be enabled to manage access to the Prometheus metrics endpoint.
>
> By default, HTTP basic authentication is used to secure access to the Prometheus metrics endpoint. As soon as you add your first API key, the use of basic authentication for the endpoint will be permanently disabled.

Note that this could likely be communicated more clearly in the frontend.
Here is our contribution guide, if you'd like to improve the software in this regard:
https://github.com/louislam/uptime-kuma/blob/b534fde26512bb4e6ae674aa92d5447c11e15b2c/CONTRIBUTING.md

**Comment by sanerspace** [comment]
Oh I missed that document somehow. Sounds like I need to take this as an issue with the integration developer, as this is expected behavior from the Kuma code but the integration still fails.
I can also attempt to help with the docs.
Would it help anything to modify the behavior to give a 403 error once http access is disabled? Just a thought. Thanks

**Comment by chakflying** [comment]
The thing is, technically it should still work in API key only mode if you input the API key in the browser login dialog's password field.

**Comment by kokofixcomputers** [comment]
> ### ⚠️ Please verify that this bug has NOT been raised before.
> * [x]  I checked and didn't find similar issue
> 
> ### 🛡️ Security Policy
> * [x]  I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)
> 
> ### Description
> An integration requires the "http:[host]/metrics" page to be reachable. However the integration fails and when I try to visit that address manually I get asked to login, then it rejects my login. I am able to reach the /dashboard and secure pages. I tried changing my password, as well as using an API key, and cannot log in with either one. I am on version 0.9.1 running as an add-on to Home Assistant. The integration is https://github.com/meichthys/uptime_kuma/blob/main/README.md.
> 
> ### 👟 Reproduction steps
> Attempt to visit "http://[hostname]/metrics", input login credentials
> 
> ### 👀 Expected behavior
> Expected to be admitted to a valid page.
> 
> ### 😓 Actual Behavior
> My login is rejected over and over. The login is via the browser popup, rather than via the usual Kuma login screen.
> 
> ### 🐻 Uptime-Kuma Version
> 0.9.0
> 
> ### 💻 Operating System and Arch
> Hassio (version of Linux) running on Raspberry Pi 4.
> 
> ### 🌐 Browser
> Google Chrome 119.0.6045.105
> 
> ### 🐋 Docker Version
> _No response_
> 
> ### 🟩 NodeJS Version
> _No response_
> 
> ### 📝 Relevant log output
> _No response_

Maybe updating to the latest version will fix your problem? Just sure to make a backup of kuma.db

**Comment by sanerspace** [comment]
Thankfully I was able to get the integration to connect to the /metrics page by inputting the API key as the password, with no username. It still took a little fiddling, so I will seek to improve the documentation for the integration as well. But we can mark this as resolved in light of the expected behavior.

**Comment by sanerspace** [comment]
Thanks for all the help!
