### ISSUE TITLE
Unable to see email (SMTP) notification

### ISSUE THREAD

**Issue by arshadmech** [louislam/uptime-kuma#3985]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

Hi There,

Greetings for the Day,

1. I configured uptime kuma using docker image and i got web UI also,
2. Next i configure my application url, so that i will get notification when status of my application changes.
3. I am able to get notification when i added notification for a single user like, arshad@example.com (this is my email addrss)
4. When i added group email address( there are 5 users ,email ID are available in this group mailid/alias) dev@example.com, and click on test, i got a pop sent successfully, but i am unable to any notifications/email in my email box. 
Can you guide how to setup this.

### 📝 Error Message(s) or Log

I checked the logs, i am not getting anything.

### 🐻 Uptime-Kuma Version

YARN_VERSION=1.22.19   NODE_VERSION=16.20.2 

### 💻 Operating System and Arch

ubuntu 20.04

### 🌐 Browser

Google chrome: Version 116.0.5845.187

### 🐋 Docker Version

Docker version 20.10.21

**Comment by CommanderStorm** [comment]
Given that the first mail worked, I strongly susspect your mailinglist to be at fault.
Some hints:
- Is the message maybe held for moderation?
- Have you double checked that you are subscribed to the list
- what do the logs of the mailinglist say
