### ISSUE TITLE
HTTP Keyword - dynamic value in XML/JSON request body

### ISSUE THREAD

**Issue by marcolonghitano** [louislam/uptime-kuma#3986]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

I would like to add a dynamic value in the body request.
I know it's possible to check the response with JSONata, I need something similar to create a dynamic JSON/XML body with the current timestamp. For instance:
```
{
  "parameter": $now()
}
```

### 🐻 Uptime-Kuma Version

1.23.3

### 💻 Operating System and Arch

Ubuntu 18.04.1

### 🌐 Browser

Chrome

**Comment by CommanderStorm** [comment]
Reassigned as feature-request instead of a help issue.

Unsure how to implement this 
- without being too bad for maintenance
- without being backwards-breaking

**Comment by chakflying** [comment]
We can basically group this together with #4383 by providing a template language (liquid.js) for the request body input.

**Comment by CommanderStorm** [comment]
Agree, merging into #4383 and making said issue a bit more generic.
=> closing as a "duplicate"
