### ISSUE TITLE
Custom cloudflare tunnel version

### ISSUE THREAD

**Issue by Farmeurimmo** [louislam/uptime-kuma#3993]
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

UI Feature, Other

### 🔖 Feature description

You should add the possibility to change the cloudflare tunnel version because with new tunnels version (post quantum etc..) a lot of things are broken and my uptime kuma page have a huge downtime compared to other of my services. (like 40% of uptime in 7 days but my service provider have an uptime of 99.2%) 

I'm currently having problems with cloudflare tunnels with version > 2022.9.0.

After looking at the error, I try to downgrade with my other tunnel to like 2022.8.0 and I didn't have any problem of connection crashing and errors 1033. So I think this will help me to resolve the problem.

### ✔️ Solution

Give us the possibility to change tunnel version if possible, I don't want to downgrade and sacrifice security updates etc of kuma for this.

**Comment by Farmeurimmo** [comment]
I didn't know. Where is it in the code ?
I think I can build my own image of it with the modification.

**Comment by chakflying** [comment]
You can check `docker/debian-base.dockerfile#30`.

**Comment by louislam** [comment]
https://community.cloudflare.com/t/can-i-use-cloudflared-in-a-docker-compose-yml/407168/2

I think you should use a standalone cloudflared container. It should be easier than rebuilding the uptime kuma image.

Don't forget to turn off Uptime Kuma's cloudflared.

**Comment by Farmeurimmo** [comment]
Thanks for your suggestions, I think I’ll use an external cloudflare tunnel.
