### ISSUE TITLE
Updating to 1.23.3 gives white screen and doesnt load

### ISSUE THREAD

**Issue by rai68** [louislam/uptime-kuma#3995]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

Upgraded to 1.23.3, and page does not load.

There are no errors in any server side logs.
Server starts fine, just has the chrome/Firefox errors

Cleared Caches, reinstall browsers

### 📝 Error Message(s) or Log

Chrome

![image](https://github.com/louislam/uptime-kuma/assets/58925163/95e29c05-2bfc-4d17-a18d-9465b8e05b48)
![image](https://github.com/louislam/uptime-kuma/assets/58925163/65314bf4-98a0-491e-8d92-ccf16db4131b)

Firefox

![image](https://github.com/louislam/uptime-kuma/assets/58925163/d75a2a17-adcc-4af0-8144-6e64d357cb62)

### 🐻 Uptime-Kuma Version

1.23.3

### 💻 Operating System and Arch

Debian

### 🌐 Browser

Chrome 119.0.6045.106 (Official Build) (64-bit), Firefox 119.0 

### 🟩 NodeJS Version

18.14.2, 18.17.1

**Comment by chakflying** [comment]
Have you followed the steps from the wiki when updating to make sure the front-end files are installed correctly?

**Comment by rai68** [comment]
Yes i did all the update commands in order

```
# Update from git
git fetch --all
git checkout 1.23.3 --force

# Install dependencies and prebuilt
npm install --production
npm run download-dist

# Restart
pm2 restart uptime-kuma
```

**Comment by rai68** [comment]
Not sure why i didnt think of this, but a reboot of OS fixed the problem
