### ISSUE TITLE
Telegram notification

### ISSUE THREAD

**Issue by f0r7y** [louislam/uptime-kuma#3996]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

When I test to send a telegram notification i see this error:
self signed certificate in certificate chain

### 🐻 Uptime-Kuma Version

1.23.3

### 💻 Operating System and Arch

Ubuntu 22

### 🌐 Browser

All

### 🐋 Docker Version

20.10.24

**Comment by CommanderStorm** [comment]
- What network layers are between your uptime-kuma instance and the telegram api? Wifi access page/ other effects spoofing on the route. 
- Do you have a proxy enabled?

**Comment by CommanderStorm** [comment]
Closing as unreproducible and the user did not respond to questions
