### ISSUE TITLE
Only Alert when a website comes online

### ISSUE THREAD

**Issue by madereddy** [louislam/uptime-kuma#3997]
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

Other

### 🔖 Feature description

I am working with an application and with storms lately it has been brought offline for a variety of reasons. Uptime is able to alert saying the application is down and using ncarlier/webhookd:edge-distrib it allows uptime to launch a DR version of the application. The DR application is being routed through a different URL.  I would like the ability to alert when a website comes online, but do not alert if its offline.

### ✔️ Solution

The best option I can think of is only alert when a monitor turns active and do not report when its not active.

### ❓ Alternatives

I tried using upside down mode, but it will send an alert that the DR application is down when it is actually online.

### 📝 Additional Context

Not able to switch DNS which makes this more challenging. Also have to manually sync the data between DR and the main site when it comes back online.

**Comment by CommanderStorm** [comment]
I think this is a duplicate of https://github.com/louislam/uptime-kuma/issues/3585
If you agree, could you please close this Issue, as duplicates only create immortal zombies and are really hard to issue-manage?
If not, what makes this issue unique enough to require an additional issue? (Could this be integrated into the issue linked above?) ^^

Note that [our contribution guide can be found here](https://github.com/louislam/uptime-kuma/blob/master/CONTRIBUTING.md) and that we are open to contributions if you adhere to this

**Comment by madereddy** [comment]
@CommanderStorm https://github.com/louislam/uptime-kuma/issues/3585 would solve my issue as well. Closing this issue
