### ISSUE TITLE
SQLITE_CORRUPT

### ISSUE THREAD

**Issue by techisgreat** [louislam/uptime-kuma#3998]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

```raw
2023-11-08T21:11:43Z [SERVER] INFO: Connecting to the Database
Trace: [Error: PRAGMA journal_mode = WAL - SQLITE_CORRUPT: database disk image is malformed] {

  errno: 11,
  code: 'SQLITE_CORRUPT'
}
    at process.<anonymous> (/app/server/server.js:1886:13)
    at process.emit (node:events:513:28)
    at emit (node:internal/process/promises:140:20)
    at processPromiseRejections (node:internal/process/promises:274:27)
    at processTicksAndRejections (node:internal/process/task_queues:97:32)
```

### 🐻 Uptime-Kuma Version

1.23.2

### 💻 Operating System and Arch

Ubuntu 20.04.3

### 🌐 Browser

Google Chrome

**Comment by CommanderStorm** [comment]
Could you provide additional details (we rely on good quality reports, please remember that we are volunteers doing stuff in their spare time)?

- What is your setup? (are you for example using NFS?)
- what did you do before the error?
- Have you searched trough [the other issues for related issues](https://github.com/louislam/uptime-kuma/issues?q=is%3Aissue+SQLITE_CORRUPT) and what was the result?
- Have you tried any measures, for example the one suggested by @modem7 in https://github.com/louislam/uptime-kuma/issues/3958 or https://github.com/louislam/uptime-kuma/issues/1994 to fix the issue?

**Comment by MarcAroni81** [comment]
Hi, I had this as well and did the following: 
`docker exec -it Uptime-Kuma /bin/bash
sqlite3 /app/data/kuma.db ".dump" | sqlite3 /app/data/new.db
sqlite3 /app/data/new.db "PRAGMA integrity_check"
rm /app/data/kuma.db
mv /app/data/new.db /app/data/kuma.db
`
After that I restarted my Container an it worked well.

**Comment by CommanderStorm** [comment]
@kokofixcomputers but @techisgreat has not responded to the question. How/why do you know that?

**Comment by kokofixcomputers** [comment]
> @kokofixcomputers but @techisgreat has not responded to the question. How/why do you know that?

It's been a month, and many people (including me sometimes because I'm kind of lazy) just leave issues alone after resolved.
