### ISSUE TITLE
Minecraft Monitor with Gamedig

### ISSUE THREAD

**Issue by FireTryx** [louislam/uptime-kuma#3999]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

Hey, can you help me with my monitor because there is Pending, i tried to use TCP Port but in other issue, i wrote "Use Gamedig' (Sorry for the crappy English I'm French)

![image](https://github.com/louislam/uptime-kuma/assets/96184599/74dd8c41-7f7e-45cd-ac68-64f799bd6810)

I use FlameCord because I've a Proxy and the monitor works fine (For the proxy, I use TCP Port):

![image](https://github.com/louislam/uptime-kuma/assets/96184599/5450b34c-1045-4e79-874e-57a35b0e683a)

Help me please

### 🐻 Uptime-Kuma Version

1.23.3

### 💻 Operating System and Arch

Ubuntu Server 22.04.3 LTS

### 🌐 Browser

119.0.6045.124 (Official build)

### 🟩 NodeJS Version

v18.18.2

**Comment by FireTryx** [comment]
@louislam

**Comment by FireTryx** [comment]
@CommanderStorm 

Since yesterday, the monitor has not worked

![image](https://github.com/louislam/uptime-kuma/assets/96184599/d1d47ec2-847c-4715-96d8-d5211b165412)

**Comment by FireTryx** [comment]
I’ve reset all evenements and all verifications but this is bot work

**Comment by louislam** [comment]
Did you read upstream issues provided by @CommanderStorm? I would suggest that you should try the command first.

```
# Install gamedig globally
npm install gamedig -g

# Test 
gamedig --type minecraft --host mc.hypixel.net --port 25565 --socketTimeout 10000 --attemptTimeout 10000
```

If it is not working, it may be a gamedig's issue, you may

**Comment by FireTryx** [comment]
@louislam i do this command on my VPS ?

**Comment by FireTryx** [comment]
@louislam @CommanderStorm thank you very much, really

**Comment by CommanderStorm** [comment]
> louislam CommanderStorm thank you very much, really

Do you mean that this issue is resolved?
If yes: could you close this issue?
If no: could you respond to the questions in https://github.com/louislam/uptime-kuma/issues/3999#issuecomment-1803444139

**Comment by FireTryx** [comment]
Yes, thanks you
