### ISSUE TITLE
[Request] Allow public access to dashboard

### ISSUE THREAD

**Issue by zmiguel** [louislam/uptime-kuma#4]
First of all, this project looks awesome, with statping being unmaintained this is an amazing replacement!

I would like to request the addition of some sort of public dashboard like other services have (statping, etc).
I use these apps to monitor the status of a few services I run and I would like for my users to be able to check the service's status (like I currently do with tinystatus, but also like statping)

Thank you.

**Comment by racoon-one** [comment]
Totally agree on this one!
 I am hosting Game Servers for my friends and we used Uptime Robot to inform them that the server is down before it got paywalled.
So this would be pretty handy.

**Comment by 12nick12** [comment]
I second that would be great. Thanks for the awesome project. I used to run CheckMK (worked great), but I didn't need all the info it provided.

**Comment by KdnAhUh2ZALZJXqP7z** [comment]
For simplicity sake, I would suggest following Statping's structure and just have a "public" or "private" flag instead of any ideas regarding multiple dashboards. Public are always displayed out front, and private are only displayed once logged in.

**Comment by lenaxia** [comment]
For simplicity sake, I would suggest following Statping's structure and just have a "public" or "private" flag instead of any ideas regarding multiple dashboards. Public are always displayed out front, and private are only displayed once logged in.

**Comment by John-S4** [comment]
Agreed. 

When I saw this project suggested as a statping replacement, this is what I presumed it would do, and just installed it and had a play expecting something that could be used a public status page. 

It looks good so far, but this feature would make it far more useful and appeal to a lot more people.

**Comment by nre-ableton** [comment]
Ditto, this project seems nice, but the lack of a public dashboard is a dealbreaker for me.

**Comment by lsultana98** [comment]
Yeah I agree, this dashboard is great, A public display would be fantastic.

**Comment by atridadl** [comment]
Yeah +1 for the dash.

**Comment by IronicBadger** [comment]
+1 for public dash please

**Comment by Aterfax** [comment]
A +1 from me - but I'd like the ability to make this public on a randomised alphanumeric URL so only those with the link can view and / or restricting to users with a view capability / group.

**Comment by jemand771** [comment]
Nice idea @Aterfax, although I think it would be smarter to do that externally via something like a reverse proxy. Just map /dash/123456789 to the public dashboard (once it exists) and you're good.
Depending on your needs I'd recommand traefik or nginx as a reverse proxy

**Comment by Aterfax** [comment]
> 
> 
> Nice idea @Aterfax, although I think it would be smarter to do that externally via something like a reverse proxy. Just map /dash/123456789 to the public dashboard (once it exists) and you're good.
> Depending on your needs I'd recommand traefik or nginx as a reverse proxy

True,  it should be simple enough to do with nginx reverse proxy. I suppose it depends on your security posture on the LAN but you can cover that with a bit of faff with docker and `--net=container:myreverseproxycontainer`.

Probably worth documenting using the type of reverse proxy configuration available once a public dashboard bit exists given the availability of nginx, traefik and authelia.

**Comment by Anubis18** [comment]
I'm use this for private now and it's awesome. Big thanks for developer uptime kuma.

I hope in the future there will be a public dashboard feature

**Comment by luisxiaomai** [comment]
+1, hope this feature

**Comment by luisxiaomai** [comment]
+1, hope this feature

**Comment by DillFrescott** [comment]
This is def a deal-breaker for me not having this.

**Comment by Kavenci** [comment]
+1, A public dashboard is what this really needs

**Comment by douglasjunior** [comment]
I don't think a public dashboard would be very useful, but creating individual public links per monitor would be awesome!

**Comment by gaby** [comment]
> I don't think a public dashboard would be very useful, but creating individual public links per monitor would be awesome!

Our team has hundreds of users, having a public dashboard is useful. Specially for core/infrastructure services.

**Comment by John-S4** [comment]
> I don't think a public dashboard would be very useful, but creating individual public links per monitor would be awesome!

Why do you think it would not be useful? 

There are a lot of use cases where you want site/service/app users to be able to see the status of the services.

**Comment by douglasjunior** [comment]
By "Dashboard" I mean visualization of ALL registered projects, right?

Imagine a company that has a hundred projects, but only one or two are of interest to certain teams.

Why should the team have access to ALL projects if they are only interested in one?

**Comment by Saibamen** [comment]
> By "Dashboard" I mean visualization of ALL registered projects, right?

No, only those that have their status set to public.

**Comment by douglasjunior** [comment]
> No, only those that have their status set to public.

Even so, in my previous example, you would have a Dashboard with hundreds of public projects. 🤷‍♂️

**Comment by gaby** [comment]
> > No, only those that have their status set to public.
> 
> Even so, in my previous example, you would have a Dashboard with hundreds of public projects. 🤷‍♂️

Only projects set to `Public` will show up in the Public dashboard.

**Comment by beornf** [comment]
This is getting into semantics the superset of a "Dashboard" feature would be N dashboards either public or private each with M public or private assigned monitors.

**Comment by louislam** [comment]
> > No, only those that have their status set to public.
> 
> Even so, in my previous example, you would have a Dashboard with hundreds of public projects. 🤷‍♂️

I know what you mean. You want something like one status page per one monitor or multiple status pages.  

I also noticed this situation while I try to use this feature to my real services, since those services are under different brands. 

May plan to add multiple status pages and separating them by CNAME/Domain name, but will not be implement in the upcoming version.

**Comment by douglasjunior** [comment]
That's right @louislam! Thanks for understanding, and congratulations for this amazing job.

**Comment by Aterfax** [comment]
Hi @louislam great work! I was wondering if we could get the incidents to support markdown?

I also wanted to check if there were any updated instructions for reverse proxying only the public status page (looks like you need to reverse proxy /api/status-page and /status /assets /upload and icon.svg).

Cheers.

**Comment by Twisterado** [comment]
@Aterfax what reverse proxy are you using? Caddy 2 allows pretty easy adjustments on what to expose and what to keep private.

**Comment by Aterfax** [comment]
nginx - it's not that I can't do it knowing the above (writing and testing the config is easy enough.) I just that I want to check what is needed only to make the public status page (not full login) work.

Then update the documentation for this in the wiki area.

**Comment by louislam** [comment]
Maybe there is no beautiful way to achieve this, as most routes are actually just a vue-router (frontend routes).

Status page is not required WebSocket, but the dashboard is required it.

Since you need two more headers "Upgrade" and "Connection" in order to do a reverse proxy for WebSocket, in the other words, you can just ignore these two headers to block the dashboard access.

https://github.com/louislam/uptime-kuma/wiki/Reverse-Proxy

**Comment by fv3rdugo** [comment]
Your access to the public dashboard must be like to https://hostname/status/YourDashboard that's all.

**Comment by neldonado** [comment]
Is there any progress happening on this?

**Comment by zmiguel** [comment]
> Is there any progress happening on this?

This has been a feature for a long time now. What exactly do you mean?

**Comment by neldonado** [comment]
> > Is there any progress happening on this?
> 
> 
> 
> This has been a feature for a long time now. What exactly do you mean?

How do I enable this? When I go to the dashboard it asks me to enter my password

**Comment by zmiguel** [comment]
> > > Is there any progress happening on this?
> > 
> > 
> > This has been a feature for a long time now. What exactly do you mean?
> 
> How do I enable this? When I go to the dashboard it asks me to enter my password

It's the 3rd option in general settings. "Entry page"

**Comment by neldonado** [comment]
> > > > Is there any progress happening on this?
> > > 
> > > 
> > > This has been a feature for a long time now. What exactly do you mean?
> > 
> > 
> > How do I enable this? When I go to the dashboard it asks me to enter my password
> 
> It's the 3rd option in general settings. "Entry page"

Right, I see this here, and it requires a password when I go to the URL I have designated.  

![image](https://user-images.githubusercontent.com/46225185/193117797-0f7ec6b4-a6c6-49ea-8057-d9b6017c72db.png)

![image](https://user-images.githubusercontent.com/46225185/193118015-dbc47bbf-0fae-48df-a12c-9234e3c416c8.png)

**Comment by neldonado** [comment]
Just realized I hadn't created a status page yet. :) Problem solved.
