### ISSUE TITLE
Support timezone

### ISSUE THREAD

**Issue by ksurl** [louislam/uptime-kuma#40]
`apk add tzdata` to docker image and support `TZ` environment variable to set the timezone. alpine is pretty straightforward. you just add this to the start up before running the app

`cp -f "/usr/share/zoneinfo/${TZ}" /etc/localtime && echo "${TZ}" > /etc/timezone`. 

I would suggest a script to run the cp and the npm startup and set the script as the entrypoint

**Comment by louislam** [comment]
Timezone is already handled in the frontend and you can change in the "Settings" page. 
All dates stored in SQLite are in UTC.

**Comment by ksurl** [comment]
The discord notification uses utc time

![image](https://user-images.githubusercontent.com/1371562/125555484-ff45947f-a306-4f7c-81ce-eea3d1616b22.jpeg)

**Comment by rezzorix** [comment]
Interesting.

Just realized that for Discord notifications the time of incident is sent.
In Telegram notifications just give information on that status - without any time...

@louislam 
maybe would be good to either streamline notification texts on backend for each service 
OR (maybe even better)
let users customise the notification text (including setting a timezone for this notifications)

_I really would contribute more than only  writing enhancements and testing builds but my coding skill are far too limited ... :pensive:_

**Comment by Simon-Peham** [comment]
The same is in the Slack notifications it is also in UTC

**Comment by tgxn** [comment]
Same for all the notifications I think; they are all UTC. I'd like for them to follow the instance timezone, _if configured_ _(if it's "Auto" or not configured we can consider it to be UTC, as we can't infer the client data from the server)_

**Comment by kamilmirza** [comment]
same problem with Pushover notifications
configured desired UTC but no go in Settings
![Screenshot_20210920-204404535](https://user-images.githubusercontent.com/6561475/134032490-4fbe3198-6777-488a-9781-b699717a4d26.jpg)

**Comment by chris-socialtap** [comment]
Yeah, having the same issue over Slack. Loving Uptime Kuma so far - awesome polish. However, for us to use in production the timezone really needs to be considered in the message (or have it customizable).

For example, we have clients in US, parts of EU, and Australia. The timestamp from Slack takes a lot of figuring out because it will only show us time here. It's also bit confusing as well that it doesn't match relative to the time within slack.

**Comment by MostHated** [comment]
It would definitely be nice to have all times used within the system to use the proper timezone. While the interface has the right time by setting the timezone, that doesn't really do anything for me, as I don't often look at the interface. I am attempting to pull the data from "api/status-page/heartbeat" to use in various automations.

**Comment by windware-ono** [comment]
Hello. I'd like the fix implemented. This should be a quick fix.

**Comment by FrancisHG** [comment]
++ Same, I am using Slack and it is using UTC for text notification, not the configured timezone in UptimeKuma.

**Comment by pbunluesin** [comment]
I got this issue with Line Notification. it's effect with production which need accurate time.

**Comment by BlackScreen** [comment]
Same problem here with mails. Would be great if this is fixed.

**Comment by robotter112** [comment]
I have the same problem that in the email UTC time is displayed. 
Although the server is UTC +02:00 and in the web interface the same is set.

**Comment by stavros-k** [comment]
I don't think +1 ing this does not provide any help. Since it's still open, it's an issue. Use the "reactions" on the top post to show you "want" this implemented. Keeps the chat clean and will be easier for contributors to discuss how that would be implemented.

**Comment by mbacicc** [comment]
I'm also having timezone problems with email notification.

It would be easily solved by installing tzdata in the base image (both debian and alpine have this package) and passing the TZ env var in the docker container.

**Comment by yyahari** [comment]
Como solucion a este error en particular con respecto a smtp
hicimos uunas modificaciones,
1.apt update && apt install tzdata -y
2.dpkg-reconfigure tzdata 
3.Seleccione mi time zone correspondiente
4.corri "date" dandome la fecha y hora de mi zona horaria
5.edite el archivo /app/server/notification-providers/smtp.js
6.comente el campo:
//if (heartbeatJSON) {
        //  bodyTextContent = `${msg}\nTime (UTC): ${heartbeatJSON["time"]}`;
     // }

   
8.  agregue;
        let fecha = new Date();
        let fechayhora=fecha.toLocaleString();

        if (heartbeatJSON) {
            bodyTextContent = `${msg}\nTime: ${fechayhora}`;
        }
10. con eso me muestra la hora correcta con respecto a mi pais en los correos
11.Saludos

**Comment by Dr0id1** [comment]
Do we have an update on that ?

**Comment by BlackScreen** [comment]
> Do we have an update on that ?

Don't think so. Would be nice to have this feature soon. :)

**Comment by louislam** [comment]
I recently added server side timezone along with the maintenance pull request. It is configurable in the Settings page.

![LOUIS-AORUS-15P  006095](https://user-images.githubusercontent.com/1336778/195107535-6bb57242-b059-462a-ba17-76414fd982b1.png)

**Comment by roughnecks** [comment]
Sorry if I'm posting here, but I think this issue is still current with webhooks notifications.

![image](https://github.com/user-attachments/assets/83a61b3a-89f3-4af7-a09c-4a241bbbfa79)

![image](https://github.com/user-attachments/assets/a12081f1-ce7d-40ca-b39f-4a5b34887f89)

**Comment by CommanderStorm** [comment]
What is your notification template?

**Comment by roughnecks** [comment]
`"template": "${heartbeat.time}\r\n${msg}"`

**Comment by CommanderStorm** [comment]
`time` is in UTC.
If you want the local time, please use `localDateTime` instead.
If you want the Timezone in addition, you can use `timezone`

**Comment by roughnecks** [comment]
I see, will make the change. Thanks
