### ISSUE TITLE
Problem with self-signed certificate

### ISSUE THREAD

**Issue by TIexplorer** [louislam/uptime-kuma#4000]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

Hello, I run Kuma with the server parameters to download the certificate, it starts, but the verification still fails.
I tried creating a .env file, adding environment variables, but it only got worse, now Kuma won't start at all.

Can you help?

### 🐻 Uptime-Kuma Version

1.23.3

### 💻 Operating System and Arch

 Debian GNU/Linux 10 

### 🌐 Browser

Google chome

**Comment by chakflying** [comment]
- Are you running uptime-kuma using docker, or natively?

- What steps have you tried? Are you using the `NODE_EXTRA_CA_CERTS` environment variable?

**Comment by TIexplorer** [comment]
I'm running kuma without docker using Node.js

Here is my .env file in the root directory (uptime-kuma)

UPTIME_KUMA_HOST=::
UPTIME_KUMA_PORT=3001
UPTIME_KUMA_SSL_CERT=sertificate.eng.crt
DATA_DIR=./data/
UPTIME_KUMA_DISABLE_FRAME_SAMEORIGIN=false
UPTIME_KUMA_ALLOW_ALL_CHROME_EXEC=0
NODE_TLS_REJECT_UNAUTHORIZED=0


I run Kuma and specify the parameter

sudo node server/server.js --ssl-cert=sertificate.eng.crt

**Comment by nicedevil007** [comment]
Heya guys, I run my uptime-kuma instance inside a LXC container on my proxmox hypervisor. So not a "standard" docker installation. Is there a file where I can set those arguments?

I already have added my local CA cert to the trusted certificate store of my debian OS, but that didn't change anything.
