### ISSUE TITLE
twilio voice notification

### ISSUE THREAD

**Issue by wzrdtales** [louislam/uptime-kuma#4003]
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

New Notification

### 🔖 Feature description

twilio voice notification, for more agressive notifications. 

### ✔️ Solution

twilio has a voice api https://www.twilio.com/docs/voice

### ❓ Alternatives

pagertree

### 📝 Additional Context

this removes the need for tools like pagertree

**Comment by CommanderStorm** [comment]
I think this is a duplicate of https://github.com/louislam/uptime-kuma/issues/3295 or https://github.com/louislam/uptime-kuma/issues/3812
If you agree, could you please close this Issue, as duplicates only create immortal zombies and are really hard to issue-manage?
If not, what makes this issue unique enough to require an additional issue? (Could this be integrated into the issue linked above?) ^^

Note that [our contribution guide can be found here](https://github.com/louislam/uptime-kuma/blob/master/CONTRIBUTING.md) and that we are open to contributions if you adhere to this

**Comment by wzrdtales** [comment]
ah yeah they're duplicate, didn't find it as I explicitly search for voice notification and nothing came back
