### ISSUE TITLE
Enable Dark Mode by Default

### ISSUE THREAD

**Issue by drtech981** [louislam/uptime-kuma#4007]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

Is there a way to enable dark mode by default for all new users and new logins ?

### 🐻 Uptime-Kuma Version

1.23.3

### 💻 Operating System and Arch

Ubuntu 22.04 LTS x64

### 🌐 Browser

Google Chrome v119

**Comment by CommanderStorm** [comment]
> enable dark mode by default for all new users

Currently, there is no such functionality.
Please see #128 for further details

> enable dark mode by default for new logins

If you visit the website from a system set to dark mode, this is the default
