### ISSUE TITLE
make Uptime kuma API easier to use

### ISSUE THREAD

**Issue by kokofixcomputers** [louislam/uptime-kuma#4008]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

I'm trying to intergrate uptime kuma api with something else but i just could not figure it out since i'm coding in python and can't quite figure out how to turn my python app into a Prometheus compatible code. Would anyone mind helping make the api easier to use? like `https://<uptimekumaurl>:<uptimekumaport>/api/monitors` then it will return a json list of monitors same with create delete and pause/resume monitors or something like that

### 🐻 Uptime-Kuma Version

1.23.3

### 💻 Operating System and Arch

Linux

### 🌐 Browser

Google Chrome

**Comment by CommanderStorm** [comment]
> can't quite figure out how to turn my python app into a Prometheus compatible code

Just to be sure: have you looked at https://github.com/louislam/uptime-kuma/wiki/Prometheus-Integration ?

> like `https://<uptimekumaurl>:<uptimekumaport>/api/monitors` then it will return a json list of monitors same with create delete and pause/resume monitors or something like that

Currently, we don't offer an api. See #118 for further details.
The current attempt at adding such a functionality is https://github.com/louislam/uptime-kuma/pull/3854 and might be merged into `v2.1` if all goes well.

You can find external tooling which does wrap around our internal web socket endpoints, see https://uptime-kuma-api.readthedocs.io/en/latest/

**Comment by kokofixcomputers** [comment]
I did.
