### ISSUE TITLE
Security Issue

### ISSUE THREAD

**Issue by gtg2619** [louislam/uptime-kuma#4014]
DO NOT PROVIDE ANY DETAILS HERE. Please privately report to https://github.com/louislam/uptime-kuma/security/advisories/new.

Why need this issue? It is because GitHub Advisory do not send a notification to @louislam, it is a workaround to do so.

Your GitHub Advisory URL:https://github.com/louislam/uptime-kuma/security/advisories/GHSA-v4v2-8h88-65qj

**Comment by gtg2619** [comment]
@louislam sorry for bothering. I don't know if you noticed this issue. In the private report I added a comment with a possible fix suggestion, hope you can see it. Also I'm not familiar with any of this, so I'd appreciate any feedback on what I'm not doing well, or anything else in the advisory.

**Comment by louislam** [comment]
Fixed, will be available in 1.23.7
