### ISSUE TITLE
Some problems with certificat

### ISSUE THREAD

**Issue by Psykozo51** [louislam/uptime-kuma#4015]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

After a docker installation, i select to monitor some local url on a domain.

We have a lot of service with in exemple myservice.localdomaine.fr, I confirm we have a local domain with a .fr extention
I had on my server the CaRoot certificat in the folder /usr/local/share/ca-certificates/CaRacine.cer
After this a send this commandlet 
NODE_EXTRA_CA_CERTS=/usr/local/share/ca-certificates/CaRacine.cer
After this a restart the container, but i have this issue: unable to get local issuer certificate
I do something wrong ?
Thanks for your helps !

### 📝 Error Message(s) or Log

unable to get local issuer certificate

### 🐻 Uptime-Kuma Version

1.23.3

### 💻 Operating System and Arch

Debian 10

### 🌐 Browser

Opera One(version : 104.0.4944.36

### 🐋 Docker Version

24.0.7

### 🟩 NodeJS Version

no

**Comment by louislam** [comment]
Uptime Kuma's container cannot access your host's file, you have to bind it first.

Example:
```
-v /usr/local/share/ca-certificates/CaRacine.cer:/usr/local/share/ca-certificates/CaRacine.cer
```

Or you can copy the file to uptime kuma's data folder and set it:

```
NODE_EXTRA_CA_CERTS=/app/data/CaRacine.cer
```

Depends on your preference.

**Comment by Psykozo51** [comment]
> Uptime Kuma's container cannot access your host's file, you have to bind it first.
> 
> Example:
> 
> ```
> -v /usr/local/share/ca-certificates/CaRacine.cer:/usr/local/share/ca-certificates/CaRacine.cer
> ```
> 
> Or you can copy the file to uptime kuma's data folder and set it:
> 
> ```
> NODE_EXTRA_CA_CERTS=/app/data/CaRacine.cer
> ```
> 
> Depends on your preference.

thanks for your respons, if i understand your reply, in my compose file I must add this line ?
-v /usr/local/share/ca-certificates/CaRacine.cer:/usr/local/share/ca-certificates/CaRacine.cer

**Comment by louislam** [comment]
It is for docker run command.

For compose file, you should add under `volumes` section like:

```yaml
volumes:
   - /usr/local/share/ca-certificates/CaRacine.cer:/usr/local/share/ca-certificates/CaRacine.cer
```

**Comment by Psykozo51** [comment]
> ```yaml
> volumes:
>    - /usr/local/share/ca-certificates/CaRacine.cer:/usr/local/share/ca-certificates/CaRacine.cer
> ```

same result :(

2023-11-11 20:09:37	unable to get local issuer certificate

You can find the compose files:
`version: '3.7'

services:
  uptime-kuma:
    image: louislam/uptime-kuma:latest
    container_name: uptime-kuma
    restart: always
    ports:
      - 3001:3001
    dns:
      - 128.1.133.2
    environment:
      - TZ=UTC # Vous pouvez ajuster le fuseau horaire selon votre localisation
    volumes:
      - ./uptime-kuma-data:/app/data
      - /usr/local/share/ca-certificates/CaRacine.cer:/usr/local/share/ca-certificates/CaRacine.cer

**Comment by louislam** [comment]
`NODE_EXTRA_CA_CERTS=/usr/local/share/ca-certificates/CaRacine.cer`

You still need this environment variable

**Comment by Psykozo51** [comment]
> `NODE_EXTRA_CA_CERTS=/usr/local/share/ca-certificates/CaRacine.cer`
> 
> You still need this environment variable

ok ok 

with you reply I had the certificat on the good folder
![image](https://github.com/louislam/uptime-kuma/assets/127778316/72987c25-cd71-4c04-b495-47e136d3e65e)

Send the cli 
NODE_EXTRA_CA_CERTS=/usr/local/share/ca-certificates/CaRacine.cer

And restart the container, but not better

**Comment by louislam** [comment]
I think you might have misunderstood, you should add it in your compose file like:

```yaml
   environment:
      - TZ=UTC
      - NODE_EXTRA_CA_CERTS=/usr/local/share/ca-certificates/CaRacine.cer
```

**Comment by Psykozo51** [comment]
> ```yaml
> - NODE_EXTRA_CA_CERTS=/usr/local/share/ca-certificates/CaRacine.cer
> ```

ok, i'm sorry, I had this argument in the compose file
![image](https://github.com/louislam/uptime-kuma/assets/127778316/4b9a2c9e-422d-45ae-b8f4-b9b3281eefa4)

But same result, but if on the web ui I select the option : ignore error certificat SSL/TLS, i didn't have problems with url

**Comment by chakflying** [comment]
Can you check if your .cer file is in PEM format? Looks like node.js only accepts extra certs in PEM format.

**Comment by Psykozo51** [comment]
> Can you check if your .cer file is in PEM format? Looks like node.js only accepts extra certs in PEM format.

Thx for your reply, how can i check that ?

**Comment by CommanderStorm** [comment]
There are a lot of tools online or offline for this. I am sure you can find one of them 
See https://stackoverflow.com/questions/5215771/how-can-i-check-if-the-certificate-file-i-have-is-in-pem-format

**Comment by Psykozo51** [comment]
> There are a lot of tools online or offline for this. I am sure you can find one of them See https://stackoverflow.com/questions/5215771/how-can-i-check-if-the-certificate-file-i-have-is-in-pem-format

from what I've been able to find on the various sites, my cer is a PEM format certificate.
I've imported it into the usr folder as notified above

**Comment by steled** [comment]
I had a similar problem and I needed to add all issuer (sub issuer and also root issuer) into one pem file.
I than needed to mount the file into the container and used the env var `NODE_EXTRA_CA_CERTS` to point to the file `/usr/local/share/ca-certificates/ca.pem`

You can find a list of all certificate from the overview of the monitor when you check the certificate info:

![Image](https://github.com/user-attachments/assets/7bc9b5ae-6ffa-44aa-a746-2e15ab116c1a)

I hope this can help also others.
