### ISSUE TITLE
Top / Sum Status for a Status Page as API endpoint?

### ISSUE THREAD

**Issue by Noschvie** [louislam/uptime-kuma#4023]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

Hello,
how can I get the top or sum status of a configured status page as API endpoint? Want to display this sum status inside a smart home visualisation.
Like this `<kuma-url>/api/badgePage/:statusPageName/status`
Thanks!

### 🐻 Uptime-Kuma Version

1.23.4

### 💻 Operating System and Arch

Debian 12, amd64

### 🌐 Browser

Firefox, latest

### 🐋 Docker Version

Docker version 24.0.6

**Comment by CommanderStorm** [comment]
Currently, we don't offer an api. See #118 for further details.
The current attempt at adding such a functionality is https://github.com/louislam/uptime-kuma/pull/3854 and might be merged into `v2.1` if all goes well.

You can find external tooling which does wrap around our internal web socket endpoints, see https://uptime-kuma-api.readthedocs.io/en/latest/

**Comment by Noschvie** [comment]
Planned for `v2.1`
