### ISSUE TITLE
Lot of ECONNRESET errors. Is it possible to ignore them ?

### ISSUE THREAD

**Issue by Vincent-HD** [louislam/uptime-kuma#4024]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

Hi,
I'm having lot of ECONNRESET error, which I'm unsure why. My connection is fine, everything is working properly but Uptime Kuma seems to have trouble to reach websites sometimes. The real problem is that it's false positive, and it hides other websites that can potentially be really down.

Do someone has the same problem ?
![image](https://github.com/louislam/uptime-kuma/assets/61592570/18a471d1-9bc6-4a3e-951c-2cfbc884b61b)

### 🐻 Uptime-Kuma Version

1.23.1

### 💻 Operating System and Arch

Ubuntu 20.04.5

### 🌐 Browser

Vivaldi 6.4.3160.42

### 🐋 Docker Version

23.0.0

**Comment by CommanderStorm** [comment]
Could you have a look at these two resources:
- https://github.com/louislam/uptime-kuma/wiki/Troubleshooting
- https://stackoverflow.com/questions/17245881/how-do-i-debug-error-econnreset-in-node-js

Could you also go into detail what the service you are monitoring is?

**Comment by Vincent-HD** [comment]
Hi,
I will look into them yes, I'll keep you updated. For the debug econnreset, it seems that's it's not very straightforward and hard to find the cause

I'm monitoring Wordpress websites, basic Apache/Nginx server. I have ~50 websites monitored, and I have the problem with few of them, so keeping track of which website is actually down is not that easy

**Comment by neven-savanovic** [comment]
Is there a solution for the ECONNRESET error? I encounter it randomly on some sites. I've attempted to debug the issue, but the logs aren't providing useful information.

**Comment by Vincent-HD** [comment]
If I remember correctly, I got way less ECONNRESET now that I've increased the retry intervals, it was like 10 seconds between each retry, by increasing it now ECONNRESET is way less common

**Comment by Vincent-HD** [comment]
> Is there a solution for the ECONNRESET error? I encounter it randomly on some sites. I've attempted to debug the issue, but the logs aren't providing useful information.

If I remember correctly, I got way less ECONNRESET now that I've increased the retry intervals, it was like 10 seconds between each retry, by increasing it now ECONNRESET is way less common
