### ISSUE TITLE
Paused monitors are automatically resumed

### ISSUE THREAD

**Issue by olgagerassimova** [louislam/uptime-kuma#4028]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### Description

The bug was revealed with the latest version 1.23.4. 
Every time I put a monitor on pause, it will be resumed after a while.

### 👟 Reproduction steps

create a monitor, put it on pause, click "yes" button in the confirmation form, wait 3-5 minutes, and check the results. The paused monitor will be resumed automatically.

### 👀 Expected behavior

The paused monitor would remain in paused status.

### 😓 Actual Behavior

The monitor is resumed from paused status to active automatically.

### 🐻 Uptime-Kuma Version

1.23.4

### 💻 Operating System and Arch

SMP PREEMPT_DYNAMIC Debian 6.0.12-1~bpo11+1 (2022-12-19) x86_64 GNU/Linux

### 🌐 Browser

Chrome Version 118.0.5993.117 (Official Build) (arm64)

### 🐋 Docker Version

k8s

**Comment by louislam** [comment]
1.23.5 should be fixed this issue.
