### ISSUE TITLE
`Certificate Expiry Notification`  should be disabled if `Ignore TLS/SSL error for HTTPS websites` is on

### ISSUE THREAD

**Issue by vrenjith** [louislam/uptime-kuma#4029]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

In summary the Certificate alert notifications are not happening. This is the situation.

- We have setup the Slack notifications for Uptime Kuma and we are receiving down / up notifications correctly.
- Certificate alert option is checked for the sites
- Notification settings appear normal.

Could you please help what can we look for here? (all screenshots are given below)

| ![](https://github.com/louislam/uptime-kuma/assets/2093241/1127a2cd-1111-4519-a9bb-3fdcbdb432ac) | ![](https://github.com/louislam/uptime-kuma/assets/2093241/293a4cb4-45f8-4e89-8d53-7423cb375bc2) |
|--------|--------|
| ![](https://github.com/louislam/uptime-kuma/assets/2093241/20cf5ea6-90b4-4c39-a2e0-6ccf418ca2b2) |  |

### 🐻 Uptime-Kuma Version

1.23.3

### 💻 Operating System and Arch

Running as Docker Container

### 🌐 Browser

Version 119.0.6045.105 (Official Build) (arm64)

**Comment by CommanderStorm** [comment]
Is this checkmark set?
![image](https://github.com/louislam/uptime-kuma/assets/26258709/142959af-eb37-45e8-bb26-c34e18ec14a3)

**Comment by vrenjith** [comment]
Yes, it  is. See the screenshot below

<img width="965" alt="image" src="https://github.com/louislam/uptime-kuma/assets/2093241/c269bc01-2112-4306-9024-28eb1b72d98f">

**Comment by CommanderStorm** [comment]
Could you please attach the `📝 Error Message(s) or Log` you ommitted above?

**Comment by vrenjith** [comment]
@CommanderStorm Thank you for responding.
There are no error messages or logs that I am able to locate related to this. Do you mean the container logs or are there any other way to check for logs?

**Comment by CommanderStorm** [comment]
Yes I mean the container logs.

**Comment by CommanderStorm** [comment]
> There are no error messages or logs that I am able to locate related to this

I don't think that we are going to be able to debug this one without the logs or this being reproducible via https://badssl.com/

=> closing as no-repro as there really is nothing that can be done in this issue from my point of view.

**Comment by vrenjith** [comment]
@CommanderStorm  there are no logs that I can see related to certificate or expiry. Anyway last 30 days logs are attached. Could you please check? We definitely had a certificate that expired on 14-May-2024
[downloaded-logs-20240514-235337.csv.zip](https://github.com/louislam/uptime-kuma/files/15312495/downloaded-logs-20240514-235337.csv.zip)

**Comment by vrenjith** [comment]
@CommanderStorm 
One doubt. We have enabled `Ignore TLS/SSL error for HTTPS websites` for all the monitors as the certs are signed by our internal CA which is not trusted by the Uptime kuma container. 

Is that affecting the cert expiry check? (I assume it shouldn't as the expiry check is independent of if the chain is trusted)

**Comment by CommanderStorm** [comment]
> [!TIP]
> You can register your internal CA with Uptime Kuma and enable certificate warnings:
> - Copy the XYZ CA to `/usr/local/share/ca-certificates/mycert.crt`
>  - Add `NODE_EXTRA_CA_CERTS=/usr/local/share/ca-certificates/mycert.crt` to the stack

> enabled `Ignore TLS/SSL error for HTTPS websites`

You are ignoring the certificate expirys if you have enabled this setting.
Certificate expiry is a `TLS/SSL error`.

Good observation that the checkmarks are somewhat counterintuitive.
=> ignoring errors should ideally disable the other checkmark with a helptext.
