### ISSUE TITLE
Refused to display 'mydomain.com' in a frame because it set 'X-Frame-Options' to 'sameorigin'.

### ISSUE THREAD

**Issue by gamer50082** [louislam/uptime-kuma#4034]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 👟 Reproduction steps

iframe uptime-kuma status

### 👀 Expected behavior

shows the webpage

### 😓 Actual Behavior

shows error in devtools console

### 🐻 Uptime-Kuma Version

1.23.3

### 💻 Operating System and Arch

unknown

### 🌐 Browser

brave Version 1.60.114 Chromium: 119.0.6045.124 (Official Build) (64-bit)

### 🟩 NodeJS Version

nodejs 20

**Comment by louislam** [comment]
See UPTIME_KUMA_DISABLE_FRAME_SAMEORIGIN
https://github.com/louislam/uptime-kuma/wiki/Environment-Variables

**Comment by gamer50082** [comment]
doesnt work still give same error

.env

```
UPTIME_KUMA_HOST=0.0.0.0
UPTIME_KUMA_PORT=4364
UPTIME_KUMA_DISABLE_FRAME_SAMEORIGIN=true
```

**Comment by louislam** [comment]
Set it to false

**Comment by gamer50082** [comment]
tried with

```
true
TRUE
false
FALSE
```
