### ISSUE TITLE
Windows Portable and Environment Variables

### ISSUE THREAD

**Issue by M-APatel1** [louislam/uptime-kuma#4038]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

Does the Windows Portable version of Uptime Kuma support Environment Variables yet? If so - should the .env file be placed in the "exe directory" / core?

### 🐻 Uptime-Kuma Version

Windows Runtime v1.0.0

### 💻 Operating System and Arch

Windows 11

### 🌐 Browser

N/A

**Comment by chakflying** [comment]
You can try putting it in the `/core` folder.

Be aware that the windows portable version is deprecated and will not be maintained. (#3935)

**Comment by CommanderStorm** [comment]
Closing as we have decided that the [pain of supporting the windows PE version of our sofware is too much of a pain for us to shoulder.](https://github.com/louislam/uptime-kuma/issues/3935#issuecomment-1778922822)
We recommend switching to switch to the methods from our installation guide: https://github.com/louislam/uptime-kuma/wiki/%F0%9F%94%A7-How-to-Install
