### ISSUE TITLE
Possible bug with uptime calculation and missing event

### ISSUE THREAD

**Issue by megosugit** [louislam/uptime-kuma#4040]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### Description

Hello,

not sure if it is a bug or if I'm missing something (sorry if I did 🙏), but I have some monitors (not all) showing slightly below 100%.
I was expecting to see an event giving the reason and the date/time when the device was not seen, but there is none.

While displaying the last 24hrs pings, I can see 2 vertical yellow bars, but I have no detail and I would have expected to be able to see the corresponding events in the lower pane.

See screenshot for example:

![image](https://github.com/louislam/uptime-kuma/assets/63979420/e22ccb27-caf4-42c4-89c7-bf170c05718e)

### 👟 Reproduction steps

not sure exactly how it happened. The devices were allegedly up.

### 👀 Expected behavior

I would expect to see events details in the lower pane.

### 😓 Actual Behavior

no detail is given.

### 🐻 Uptime-Kuma Version

1.23.4

### 💻 Operating System and Arch

linux x86_64 DiskStation

### 🌐 Browser

119.0.6045.160

### 🐋 Docker Version

20.10.23 (API: 1.41)

### 🟩 NodeJS Version

16.20.2

**Comment by louislam** [comment]
I would say the current design is like this. The yellow is "Pending" status. You can change the "Retries" value to 0, if you don't want to have "Pending" status and show them as "Down" status.

**Comment by megosugit** [comment]
Thank you.

If I understand correctly:
if the monitor doesn't get a reply, it changes the device status to Pending and wait for the next number of retries to either mark it as Down or Up. But whatever happens, Pending decreases uptime.

I was thinking of another type of behavior:
Pending doesn't count as Down and doesn't decrease Uptime unless all retries (as defined in the Retries value) have been exhausted.
There would be 2 cases:
1/ if the device replies before the end of all retries, then it was a false positive and it wouldn't count.
2/ if the device does not reply after all specified retries, it is marked as Down, a notification is sent, and Pending status decreases uptime value.

But apparently, Pending is considered as "Down" currently.
I see both sides and they all have pros and cons.

If you confirm the first behavior is the one currently in place (considered not Up when Pending), is there a possibility to list the Pending events in the event list ?
We would be able to see how often this happens and we could be able to understand why Uptime is not 100% even though there was no clear Down event.

**Comment by louislam** [comment]
Yes, you are right.

> is there a possibility to list the Pending events in the event list ?

Cannot list them in the UI currently. But if you know some SQL knowledge. SQLite could be a workaround.

`SELECT * FROM heartbeat WHERE status = 2`

**Comment by chakflying** [comment]
Duplicate of #688
