### ISSUE TITLE
Not able to  Ping 172.20.x.x network after installing Uptime Kuma docker image. able to ping everything else but not a class B network

### ISSUE THREAD

**Issue by JimmyJake234** [louislam/uptime-kuma#4049]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

Not able to  Ping 172.20.x.x network after installing Uptime Kuma docker image. able to ping everything else but not a class B network. no issues before the install,, Ubuntu had no issues before the install but not able to connect to any of the devices in the 172.x.x.x networks after the install

### 📝 Error Message(s) or Log

from 172.20.0.1 icmp_seq=6 Destination host Unreachable
which means UPT-Kuma can not monitor none of the printers or any other devices in the 172.x.x.x networks

### 🐻 Uptime-Kuma Version

 1.23.2

### 💻 Operating System and Arch

ubuntu 22.04.3 desktop

### 🌐 Browser

Firefox 

### 🐋 Docker Version

Docker Version 24.05

### 🟩 NodeJS Version

20.9.0

**Comment by CommanderStorm** [comment]
Could you have a look at these links:
- https://github.com/louislam/uptime-kuma/wiki/Troubleshooting
- https://www.youtube.com/watch?v=bKFMS5C4CG0
- Possibly related: https://github.com/louislam/uptime-kuma/issues/3956

**Comment by cschlesselmann** [comment]
Sounds like a possible network range overlap, did you check which network ranges docker is using for the internal networks?
