### ISSUE TITLE
Cannot read properties of undefined (reading 'SSL_OP_LEGACY_SERVER_CONNECT')

### ISSUE THREAD

**Issue by RomelSan** [louislam/uptime-kuma#4051]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### Description

Monitoring a HTTPS email server service now does not work on 1.23.5

Got the error: Cannot read properties of undefined (reading 'SSL_OP_LEGACY_SERVER_CONNECT')

![image](https://github.com/louislam/uptime-kuma/assets/11341002/15773a46-1c9e-49ff-9a36-5e47ff452d69)

### 👟 Reproduction steps

Just upgrade to the version 1.23.5
Must have an old server with a https service to monitor.

### 👀 Expected behavior

Should work.

### 😓 Actual Behavior

It reports the service as down when actually it is UP

### 🐻 Uptime-Kuma Version

1.23.5

### 💻 Operating System and Arch

Ubuntu 22.04 LTS

### 🌐 Browser

Google Chrome

**Comment by louislam** [comment]
Should be fixed in 1.23.6
