### ISSUE TITLE
Cant Update ( no docker )

### ISSUE THREAD

**Issue by lxnunorodrigues** [louislam/uptime-kuma#4055]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

Hi cant update .
I try this but still on version : 1.23.2

i use this to force : 

# Update from git
git fetch --all
git checkout 1.23.6 --force

# Install dependencies and prebuilt
npm install --production
npm run download-dist

# Restart
pm2 restart uptime-kuma

### 🐻 Uptime-Kuma Version

1.23.2

### 💻 Operating System and Arch

proxmox container

### 🌐 Browser

edge / chrome

### 🐋 Docker Version

0

### 🟩 NodeJS Version

0

**Comment by chakflying** [comment]
So you have a machine with Proxmox installed. How did you install uptime-kuma? Did you create an LXC container by searching for the uptime-kuma image? Or did you create another Linux VM, then installed the application inside manually?

**Comment by lxnunorodrigues** [comment]
Hi
I installed on this website : https://tteck.github.io/Proxmox/

today i see update on webgui and cant update it on my ssh commands , still on version 1.23.2

**Comment by lxnunorodrigues** [comment]
if i put "git fetch --all" i see only Fetching origin , its ok ????

**Comment by lxnunorodrigues** [comment]
if i put : git checkout 1.23.6 --force ,    i see : HEAD is now at c1aaad0d Update to 1.23.6

**Comment by chakflying** [comment]
I'm not familiar with how LXC works, but looks like it does not uses pm2 to run uptime-kuma, and instead uses a systemd service. Have you tried restarting it?
```
sudo systemctl restart uptime-kuma
```

**Comment by lxnunorodrigues** [comment]
Hi same problem , cant update , same version ...

**Comment by chakflying** [comment]
Can't really help as the install method is non-standard.

I guess you can also try the update script provided by them.

```
bash -c "$(wget -qLO - https://github.com/tteck/Proxmox/raw/main/ct/uptimekuma.sh)"
```

**Comment by lxnunorodrigues** [comment]
Thanks its ok now , i have lasted version ( 1.23.6 ) 

 ✓ Stopped Uptime Kuma
 ✓ Pulled Uptime Kuma 1.23.6
 ✓ Updated Uptime Kuma
 ✓ Started Uptime Kuma
 ✓ Updated Successfully

**Comment by chakflying** [comment]
If the problem is solved, feel free to close this issue.
