### ISSUE TITLE
Paused monitor still be monitored

### ISSUE THREAD

**Issue by solracsf** [louislam/uptime-kuma#4057]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### Description

When a monitor is paused it still be monitored. It shouldn't.

### 👟 Reproduction steps

1. Pause a HTTP monitor (attached to a group, don't know if this is important)
2. Stop the Webserver
3. Monitor will be reported as down 

### 👀 Expected behavior

Paused monitor should be...paused.

### 😓 Actual Behavior

Paused monitor is monitored.

![image](https://github.com/louislam/uptime-kuma/assets/12234510/8d428e82-d02f-4fb9-b660-b2c86b2b7708)

### 🐻 Uptime-Kuma Version

1.23.4

### 💻 Operating System and Arch

Ubutnu 22.0.4

### 🌐 Browser

Brave

**Comment by chakflying** [comment]
Duplicate of #4028, fixed in #4032, please check version `1.23.6`.

**Comment by solracsf** [comment]
Thanks, but as here, monitor is not resumed, I thought it was not the same issue.

**Comment by chakflying** [comment]
When I reproduced this, the UI is indeed paused, but the heartbeats continues to get updated, and a refresh of the browser would show the correct status, which is running.

I believe it's related to the way `checkMonitors` resumes monitors where the status does not get sent to clients.

**Comment by chakflying** [comment]
Fixed by #4088.
