### ISSUE TITLE
MySQL for scalability 

### ISSUE THREAD

**Issue by CINOAdam** [louislam/uptime-kuma#406]
Hi there, I was wondering if there is an example using MySQL for the DB.

Thank You!

**Comment by Ponkhy** [comment]
Not yet unfortunately, but far as i know the thought for it is definitely there.
I already tried out a bit stuff but it's nothing fixed.

**Comment by CINOAdam** [comment]
> Not yet unfortunately, but far as i know the thought for it is definitely there.
> I already tried out a bit stuff but it's nothing fixed.

Did you get it to work at all?

**Comment by louislam** [comment]
MySQL is not supported in current version.

**Comment by gaby** [comment]
> Hi there, I was wondering if there is an example using MySQL for the DB.
> 
> Thank You!

What kind of scalability issues are you having with sqlite? My team is currently monitoring around 250 hosts with in one VM with 2vCPU/2GB RAM, with no performance issues. We are also running NGINX in front to add TLS support.
