### ISSUE TITLE
Planned maintenance display

### ISSUE THREAD

**Issue by lougedada** [louislam/uptime-kuma#4060]
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

Other

### 🔖 Feature description

Currently, the plans added in planned maintenance will not be displayed on the status page in advance. I hope that the added planned maintenance can appear on the status page in advance to remind users.

### ✔️ Solution

The status page displays planned maintenance content in advance

**Comment by CommanderStorm** [comment]
Related: https://github.com/louislam/uptime-kuma/issues/3792 https://github.com/louislam/uptime-kuma/issues/1984 https://github.com/louislam/uptime-kuma/issues/916

**Comment by lougedada** [comment]
> 相关新闻： #[3792](https://github.com/louislam/uptime-kuma/issues/3792) #[1984 #](https://github.com/louislam/uptime-kuma/issues/1984)[916](https://github.com/louislam/uptime-kuma/issues/916)

I didn't see the solution in the previous question

**Comment by CommanderStorm** [comment]
Yes, linking related issues is just a convenience to make sure that if a PR lands all related issues can be found simpler ^^

**Comment by CommanderStorm** [comment]
@lougedada
We are consolidating duplicate issues a bit to make issue management easier.
I think, we should track this issue in #2389 as there is no functional difference (maybe just small naming differences, but nothing that would require a different issue imo)
⇒ I am going to close this as a duplicate.
