### ISSUE TITLE
Would like to be emailed the current IP for machines that come up in email

### ISSUE THREAD

**Issue by jaxjexjox** [louislam/uptime-kuma#4063]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

Hello,

I tried googling and playing with the notification options before creating this issue, but I couldn't for the life of me figure it out.

I can have uptime kuma report the IP address which is no longer responding but I'd love for it to tell me the new IP for a device when it comes up.

See screenshot.
![image](https://github.com/louislam/uptime-kuma/assets/26258709/daa1c78c-d042-4bc4-8e1c-753f7bffd04c)

Is this actually possible and I just need to adjust syntax in the notification configuration or it doesn't work this way?

### 📝 Error Message(s) or Log

Nothing precisely

### 🐻 Uptime-Kuma Version

all

### 💻 Operating System and Arch

Ubuntu, linux, docker, all

### 🌐 Browser

NA

### 🐋 Docker Version

NA

### 🟩 NodeJS Version

NA

**Comment by chakflying** [comment]
This information is currently not available as we assume you would most likely use a static IP address for the Ping monitor type.

**Comment by jaxjexjox** [comment]
Oh look I'd definitely prefer a static IP but some of the devices I monitor are dynamic, so I simply monitor

hostname.blah.blahblah

etc.  It'd be nice to know that it came up (obviously working already) and what IP it came up, with.
