### ISSUE TITLE
Maintenance start/end time input incorrectly uses system timezone

### ISSUE THREAD

**Issue by lougedada** [louislam/uptime-kuma#4066]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### Description

![image](https://github.com/louislam/uptime-kuma/assets/56870521/30ddd5ee-fbfb-44ae-b125-19a554c1799f)
![image](https://github.com/louislam/uptime-kuma/assets/56870521/5ec67895-c413-4b59-82f5-5f8b6ff6f533)
I set the Chinese time, but after exiting, the time displayed was 1 hour later than the set time, but the actual execution time was correct.

### 👟 Reproduction steps

Select the time zone as Shanghai and set up planned maintenance

### 👀 Expected behavior

Time display leading to status page errors

### 😓 Actual Behavior

Status page error time display

### 🐻 Uptime-Kuma Version

1.23.6

### 💻 Operating System and Arch

Ubuntu 22.04.3 LTS

### 🌐 Browser

edge

### 🐋 Docker Version

Docker version 24.0.5, build 24.0.5-0ubuntu1~22.04.1

**Comment by CommanderStorm** [comment]
Could you try restarting your instance as noted in https://github.com/louislam/uptime-kuma/issues/3626

**Comment by imlonghao** [comment]
I'm able to reproduce this issue. IT IS RELATED TO YOUR BROWSER/SYSTEM TIMEZONE.

Let's say we have a planned maintenance on 2023-11-30 10:00-11:00 (UTC+8), aka 2023-11-30 11:00-12:00 (UTC+9)

How to reproduce:
1. Change your system timezone to Asia/Tokyo (UTC+9)
2. Go to https://demo.uptime.kuma.pet/ and create a demo instance
3. Create a `New Monitor`, whatever target is ok
4. Go to `Schedule Maintenance` and create a maintenance as the screenshot
![image](https://github.com/louislam/uptime-kuma/assets/4951333/f512edbb-2f98-4902-a8f9-550d5b96b8d8)
5. Now you can see from the list, the maintenance is shown as `2023-11-30 09:00 - 2023-11-30 10:00
UTC+08:00 Asia/Shanghai`, which is an hour earlier than expected.
![image](https://github.com/louislam/uptime-kuma/assets/4951333/63a8d30d-addc-43c1-a269-dada2b54c16b)

**Comment by jaybhanushali3166** [comment]
Hi @chakflying / @CommanderStorm,
I'd be interested to work on this bug. May you please assign it to me?

**Comment by chakflying** [comment]
I don't think this issue is complicated enough to require assignment, and we don't assign issues here in general. If you have a solution you can open a pull request following the guidelines.
