### ISSUE TITLE
Bug on new Browser engine

### ISSUE THREAD

**Issue by AlexandreVig** [louislam/uptime-kuma#4069]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### Description

I get this error with the new browser engine: - browser.newContext: Target page, context or browser has been closed.
When I'm connected in SSH, it works great and as soon i disconnect from SSh connexion it starts to return this error : browser.newContext: Target page, context or browser has been closed.
After trying to reconnect in SSH, it doesn't work anymore.

### 👟 Reproduction steps

Connect in SSH to your ubuntu server where uptime kuma is installed.
I am running Kuma without docker
Configure your new Browser Engine monitor:
- Install chromium with this command : ```sudo apt install chromium-browser```
- The chromium version is Chromium 119.0.6045.159
- Add the chromium executable path in parameter
- Configure the monitor with the right url

It works fine and when you disconnect from your SSH connection it starts to bug and return the error.

### 👀 Expected behavior

Just work fine

### 😓 Actual Behavior

return the error : browser.newContext: Target page, context or browser has been closed

### 🐻 Uptime-Kuma Version

1.23.6

### 💻 Operating System and Arch

Ubuntu 20.04.6 LTS

### 🌐 Browser

Brave v. 1.60.118

### 🐋 Docker Version

Non-Docker

### 🟩 NodeJS Version

16.13.1

### 📝 Relevant log output

```shell
browser.newContext: Target page, context or browser has been closed
```

**Comment by louislam** [comment]
Should be due to #4079, let's focus on #4079
