### ISSUE TITLE
The 'push' type of monitoring is like freezing

### ISSUE THREAD

**Issue by irtec** [louislam/uptime-kuma#4078]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### Description

Thank you for creating this project; it has been immensely helpful. I attempted to build the latest version, 1.23.6, using MariaDB mode with MySQL version 5.7. However, I encountered an issue with the 'push' monitoring type, which seems to be frozen and not checking at the specified intervals. It appears that the heartbeat isn't functioning correctly. Additionally, when the heartbeat time is exceeded, it does not indicate a 'down' status. As in this picture, it has been more than 20 seconds without pushing data, but the status is still UP, which should be DOWN

<img width="810" alt="Screenshot 2023-11-22 at 03 20 43" src="https://github.com/louislam/uptime-kuma/assets/34168344/0553292c-1f3a-45f0-8c72-20128558c77d">

### 👟 Reproduction steps

...

### 👀 Expected behavior

...

### 😓 Actual Behavior

...

### 🐻 Uptime-Kuma Version

1.23.6

### 💻 Operating System and Arch

Macos 14.1.1

### 🌐 Browser

...

### 🐋 Docker Version

...

### 🟩 NodeJS Version

v18.15.0

### 📝 Relevant log output

```shell
...
```

**Comment by CommanderStorm** [comment]
> using MariaDB mode with MySQL version 5.7.

What do you mean by this statement?
using `mariadb` as a database is not yet released, this is only in the [v2 milestone release](https://github.com/louislam/uptime-kuma/milestone/24)
Are you sure that you are using `1.23.6` and not the master branch (v2 development happens here, bugs are expected)

To better narrow this issue down:
- please fill out all fields (including what is written in the log)
- what have you set as `Heartbeat Interval (Check every ... seconds)`, `Retry` and `Heartbeat Retry Interval`?

**Comment by irtec** [comment]
I'll try to make sure to clone the current master repo again. Maybe I did something wrong when building the repo.

<img width="868" alt="Screenshot 2023-11-22 at 16 26 04" src="https://github.com/louislam/uptime-kuma/assets/34168344/bd85ed49-1c69-44bb-b7cd-b74acab274d3">

`git clone https://github.com/louislam/uptime-kuma.git && \
cd uptime-kuma && \
npm install && \
npm ci --production && \
npm install vite --save-dev && \
npm run build`

<img width="516" alt="Screenshot 2023-11-22 at 16 27 19" src="https://github.com/louislam/uptime-kuma/assets/34168344/34ff6bf4-dc6f-4fad-9040-8f691d662f85">

**Comment by chakflying** [comment]
This is a known bug that will be fixed by #3756.

@louislam we should set the version on master branch to `2.0.0-dev` or something to prevent confusion.

**Comment by CommanderStorm** [comment]
> I'll try to make sure to clone the current master repo again. Maybe I did something wrong when building the repo.

Please see https://github.com/louislam/uptime-kuma/wiki/%F0%9F%94%A7-How-to-Install

**Comment by irtec** [comment]
> This is a known bug that will be fixed by #3756.
> 
> @louislam we should set the version on master branch to `2.0.0-dev` or something to prevent confusion.

Ok thank you

**Comment by chakflying** [comment]
Duplicate of #3723
