### ISSUE TITLE
Chromium on Ubuntu 22.04 LTS not recognized

### ISSUE THREAD

**Issue by gerbilOFdoom** [louislam/uptime-kuma#4079]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### Description

Uptime Kuma doesn't recognize `/snap/bin/chromium` as a valid path for chromium. This path is the default install path for Ubuntu 22.04 LTS when using canonical repositories and should probably be considered valid.

I believe getting it allowed is as simple as adding `/snap/bin/chromium` and `/snap/bin/chromium-browser` to server/monitor-types/real-browser-monitor-type.js at line 45. The only other step is ensuring this path is auto-detected properly.

### 👟 Reproduction steps

1. Install Uptime Kuma on a fresh Ubuntu 22.04 LTS install using the Manual method
2. Install chromium-browser via `apt install chromium-browser`
3. Notice that apt redirected to snap, so chromium is located at `/snap/bin/chromium`
4. Attempt to set the chrome executable to this snap location

### 👀 Expected behavior

Expected /snap/bin to be an acceptable location for Uptime Kuma

### 😓 Actual Behavior

Was prompted to set the environment variable to allow chrome to exist anywhere

### 🐻 Uptime-Kuma Version

1.23.6

### 💻 Operating System and Arch

Ubuntu 22.04 LTS

### 🌐 Browser

N/A

### 🐋 Docker Version

N/A

### 🟩 NodeJS Version

20.8.0

### 📝 Relevant log output

```shell
Location of log output other than docker is not documented
```

**Comment by CommanderStorm** [comment]
Given that you already have debugged [where this needs to be added](https://github.com/louislam/uptime-kuma/blob/master/server/monitor-types/real-browser-monitor-type.js#L38), I think this would be a prime target for a first PR. ^^

Here is our contribution guide: https://github.com/louislam/uptime-kuma/blob/1550a5f79270f39007086d8d23c180ba9f63096b/CONTRIBUTING.md

**Comment by gerbilOFdoom** [comment]
Well, that's the fun part. I've already tested adding the path to that array. Trouble is, the chromium path is supposed to be autodetected using paths in that array. Typing `/snap/bin/chromium` manually does work, but something is still broken here. 

The command-exists dependency correctly checks a given path and the findChrome function _looks_ like it iterates over the array and either returns the path correctly or some other function has a bug. The text of the error in the browser comes from browserType.launch, a function that probably exists in a dependency that I can't see at the moment.

Further travel down this rabbit hole would be detrimental to my class work, so I have to return to that - thus, this issue instead of a pull request.

**Comment by louislam** [comment]
I always thought Ubuntu and Debian are using the same chromium package, but they are not.

Will try to add `/snap/bin/chromium`
