### ISSUE TITLE
[WeCom] Add ability to notify specific user

### ISSUE THREAD

**Issue by NC-Cj** [louislam/uptime-kuma#4081]
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

New Notification, New Monitor

### 🔖 Feature description

Notification systems can only send text, and in some OA systems, websocket bots can push messages to specified users

### ✔️ Solution

I want to fill in the user's account id and it can send the message @ to the person specified

### ❓ Alternatives

Add a line to select input

### 📝 Additional Context

![image](https://github.com/louislam/uptime-kuma/assets/63846405/002c3759-4a69-43b4-a88e-6a40ca4b9687)

**Comment by CommanderStorm** [comment]
It is unclear what you mean by `New Notification, New Monitor`.

> Notification systems can only send text, and in some OA systems, websocket bots can push messages to specified users

Have you tried using the websocket notification type? (at least that is what I think you are requesting)

> I want to fill in the user's account id and it can send the message @ to the person specified

I could not test if such a change would work due to not having access to wechat.
Here is our contribution guide: https://github.com/louislam/uptime-kuma/blob/d810a74d707325eaba714c4f52e2ff46733aeb65/CONTRIBUTING.md

**Comment by nianhua99** [comment]
i'm willing to try @CommanderStorm

**Comment by CommanderStorm** [comment]
@nianhua99 Please make sure to base the contribution on top of https://github.com/louislam/uptime-kuma/pull/4516 to not cause a huge merge conflict once the discussion there is resolved + merged.

**Comment by NC-Cj** [comment]
我没有具体关注源码文件，你可以指出配置监控通知的源码在那个路径下吗？我想了解下项目代码结构 @nianhua99

**Comment by nianhua99** [comment]
> @nianhua99 Please make sure to base the contribution on top of #4516 to not cause a huge merge conflict once the discussion there is resolved + merged.

Sorry, I checked the docs and found out that the template_card mode doesn't support reminder members, so I'm giving up on that

**Comment by nianhua99** [comment]
> 我没有具体关注源码文件，你可以指出配置监控通知的源码在那个路径下吗？我想了解下项目代码结构 @nianhua99

你可以尝试 <@userid> 这样的语法

**Comment by CommanderStorm** [comment]
> found out that the `template_card` mode doesn't support reminder members

I am going to close this issue as not planned then.

I don't know what you mean regarding `<@userid>`, but if this won't work with `template_card`, I don't see this worthwhile.

Feel free to reopen if I misunderstood something.
