### ISSUE TITLE
Not used variables in a documentation

### ISSUE THREAD

**Issue by Feriman22** [louislam/uptime-kuma#4086]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### Description

[The Docker Hub repository](https://hub.docker.com/r/elestio/uptime-kuma) description contains these below variables:

ADMIN_EMAIL
ADMIN_PASSWORD

However it's not working even if I set them in the Docker Compose.

### 👟 Reproduction steps

1. Define these variables in the docker compose: ADMIN_EMAIL and ADMIN_PASSWORD
2. Start the container with an empty volume
3. Open the Uptime Kuma WebUI
4. It will ask for username and password

### 👀 Expected behavior

It shouldn't ask for a signup

### 😓 Actual Behavior

It asks for a signup (username and password)

### 🐻 Uptime-Kuma Version

1.23.6

### 💻 Operating System and Arch

Debian 10.12

### 🌐 Browser

Google Chrome 119.0.6045.160 (Official Build) (64-bit)

### 🐋 Docker Version

Docker version 20.10.14, build a224086

### 📝 Relevant log output

```shell
version: '3'

services:
  uptime-kuma:
    image: elestio/uptime-kuma:latest
    container_name: ${CONTAINER_NAME:-uptime-kuma}
    hostname: ${HOST_NAME:-uptkuma}
    restart: always
    environment:
      TZ: Europe/Budapest
      ADMIN_EMAIL: ${ADMIN_EMAIL:-my@email.com}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD:-mypassword}
    networks:
      - home
    volumes:
      - uptime-kuma:/app/data
      - /var/run/docker.sock:/var/run/docker.sock
volumes:
  uptime-kuma:

networks:
  home:
    external: true
```

**Comment by louislam** [comment]
Be careful, elestio/uptime-kuma is not official one. And I dont know how they can be the top of result on Docker Hub.

The real one:
https://hub.docker.com/r/louislam/uptime-kuma


Of course, please read this repo's readme for how to install.

**Comment by Feriman22** [comment]
Hi @louislam,
Okay, I got it. So the "Verified Publisher" is not the official one. Good to know, thanks!
