### ISSUE TITLE
SQLITE ERROR after Updating

### ISSUE THREAD

**Issue by Phyroks** [louislam/uptime-kuma#4091]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

After updating my uptime kuma, the server wont start again.

### 📝 Error Message(s) or Log

Welcome to Uptime Kuma
Your Node.js version: 18.18.2
2023-11-23T20:35:56Z [SERVER] INFO: Env: production
2023-11-23T20:35:56Z [SERVER] INFO: Uptime Kuma Version: 1.23.6
2023-11-23T20:35:56Z [SERVER] INFO: Loading modules
2023-11-23T20:35:56Z [SERVER] INFO: Creating express and socket.io instance
2023-11-23T20:35:56Z [SERVER] INFO: Server Type: HTTP
2023-11-23T20:35:57Z [SERVER] INFO: Data Dir: ./data/
2023-11-23T20:35:57Z [DB] INFO: Database Type: sqlite
2023-11-23T20:35:57Z [SERVER] INFO: Connected to the database
migration file "2023-10-11-1915-push-token-to-32.js" failed
migration failed with error: DROP TABLE "monitor" - SQLITE_FULL: database or disk is full
2023-11-23T20:35:57Z [DB] ERROR: Database migration failed
2023-11-23T20:35:57Z [SERVER] ERROR: Failed to prepare your database: ROLLBACK - SQLITE_ERROR: cannot rollback - no transaction is active
container@pterodactyl~ Server marked as offline...
[Pterodactyl Daemon]: ---------- Detected server process in a crashed state! ----------
[Pterodactyl Daemon]: Exit code: 1
[Pterodactyl Daemon]: Out of memory: false
[Pterodactyl Daemon]: Aborting automatic restart, last crash occurred less than 60 seconds ago.

### 🐻 Uptime-Kuma Version

1.23.6

### 💻 Operating System and Arch

Ubuntu 22.04 x68

### 🌐 Browser

Firefox

### 🟩 NodeJS Version

18.18.2

**Comment by Phyroks** [comment]
The Server has enough Disk Space

**Comment by Phyroks** [comment]
I was on Version 1.23.3.
I tried to update to 1.23.6 direclty from 1.23.3

After updating step by step from 1.23.3->1.23.4->1.23.5->1.23.6 
Everything worked fine.

**Comment by CommanderStorm** [comment]
> After updating step by step from 1.23.3->1.23.4->1.23.5->1.23.6
> Everything worked fine

Should not be nessesary.

Given that we have had some (irreproducible) reports of migration failures (with other error messages, so maybe unrelated):
On what version were you before that, as far back as you remember? (as detailed as possible, may help in reproducing this)

The problem with the migrations is that I cannot reproduce any errors on my side.
```bash
docker volume rm uptime-kuma
docker run -it -p 3001:3001 -v uptime-kuma:/app/data louislam/uptime-kuma:1.23.3
```

Wait for stabilising and then kill+run another instance
```bash
docker run -it -p 3001:3001 -v uptime-kuma:/app/data louislam/uptime-kuma:1.23.6
```

**Comment by Phyroks** [comment]
I run my uptime kuma in pterodactyl
