### ISSUE TITLE
Building a local image

### ISSUE THREAD

**Issue by DubovskoySergey** [louislam/uptime-kuma#4092]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

Hello! 
I am trying to build a local image, but when starting the container I get the error:
/usr/bin/env: 'sh\r': No such file or directory
I used the original dockerfiles.
Help please

My dockerfile
```
FROM louislam/uptime-kuma:builder-go AS build_healthcheck
FROM louislam/uptime-kuma:base-debian AS build
WORKDIR /app

ENV PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=1
COPY .npmrc .npmrc
COPY package.json package.json
COPY package-lock.json package-lock.json
RUN npm ci --omit=dev
COPY . .
COPY --from=build_healthcheck /app/extra/healthcheck /app/extra/healthcheck
RUN chmod +x /app/extra/entrypoint.sh

FROM louislam/uptime-kuma:base-debian AS release
WORKDIR /app

ENV UPTIME_KUMA_IS_CONTAINER=1

# Copy app files from build layer
COPY --from=build /app /app


EXPOSE 3001
VOLUME ["/app/data"]
HEALTHCHECK --interval=60s --timeout=30s --start-period=180s --retries=5 CMD extra/healthcheck
ENTRYPOINT ["/usr/bin/dumb-init", "--", "extra/entrypoint.sh"]
CMD ["node", "server/server.js"]
```
### 📝 Error Message(s) or Log

/usr/bin/env: 'sh\r': No such file or directory

### 🐻 Uptime-Kuma Version

1.26.3

### 💻 Operating System and Arch

Windows 11

### 🌐 Browser

Google Chrome

### 🐋 Docker Version

Docker Desctop 4.22.1

**Comment by CommanderStorm** [comment]
- > I am trying to build a local image
   
  out of curiosity: why are you trying to do that?
  Could your usecases (?) not be better covered by extending our docker files `FROM louslam/...`
- General note of caution:
  (The warning is not for you, the Dockerfile you linked is from the `v1.23.X` branch, more for future readers)
  > We are currently on our path from `v1.x` -> `v2.x` This includes many changes to how our docker files look/work. See https://github.com/louislam/uptime-kuma/milestone/24 for the progress.
  The master branch is `2.0.0-dev` and as such not ready for production. For development please refer to our [Contribution guide](https://github.com/louislam/uptime-kuma/blob/master/CONTRIBUTING.md). The current production ready version [can be seen here](https://github.com/louislam/uptime-kuma/releases).
- local images can be build using the `npm run <scripts>`  with scripts of `build-docker...` [See the v1.23.x branch for further details](https://github.com/louislam/uptime-kuma/blob/1.23.X/package.json).
- For me, building the `VERSION=abc npm run build-docker` command works on both `main` and `1.23.X` and the with the `Dockerfile` provided by you works in the `1.23.X` branch.
- Could you please go into your setup further (docker/npm version/...)

**Comment by CommanderStorm** [comment]
One thing that might have happened, is that you have produced a local image which is not working.

Please run ´docker pull louislam/uptime-kuma:...´ with all the images you depend on.

**Comment by DubovskoySergey** [comment]
> out of curiosity: why are you trying to do that?

I have made some changes to the code, which will allow you to receive more informative messages when sending notifications. Therefore, I want to build a project and check if my add-on works

Thank you, I will try to use your suggestion now
