### ISSUE TITLE
[discord] Add support for forums

### ISSUE THREAD

**Issue by TheDanniCraft** [louislam/uptime-kuma#4096]
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

New Notification

### 🔖 Feature description

Currently the webhooks only support posting into normal channels.
When selecting a webhook that leads to a forum channel the POST request fails:
```
Error: AxiosError: Request failed with status code 400 {"message":"Webhooks posted to forum channels must have a thread_name or thread_id","code":220001}
```
[Discord Docs about webhooks in forum channels](https://discord.com/developers/docs/resources/webhook#execute-webhook)

### ✔️ Solution

Add a checkbox so the user can set if its a forum channel or not, if it is the case maybe show a textbox where you can set the thread name.

Then if the box is checked, add `thread_name` to the json payload.

**Comment by CommanderStorm** [comment]
PRs welcome, here is our [contribution guide](https://github.com/louislam/uptime-kuma/blob/ac452bbcb944a69b946c132df688fd32409e839b/CONTRIBUTING.md) and there is the [discord notification provider](https://github.com/louislam/uptime-kuma/blob/master/server/notification-providers/discord.js)

**Comment by TheDanniCraft** [comment]
> PRs welcome, here is our [contribution guide](https://github.com/louislam/uptime-kuma/blob/ac452bbcb944a69b946c132df688fd32409e839b/CONTRIBUTING.md) and there is the [discord notification provider](https://github.com/louislam/uptime-kuma/blob/master/server/notification-providers/discord.js)

I'll give it a try
