### ISSUE TITLE
Docker 1.0.3 restarting / error (ARMv7 only)

### ISSUE THREAD

**Issue by rezzorix** [louislam/uptime-kuma#41]
After pulling the latest docker build, the docker instance wont start and is stuck in a constant restarting loop.

The following command to see whats going on:
`sudo docker logs --tail 20 --follow --timestamps containername`

Results in:
```2021-07-14T07:06:53.133535605Z #
2021-07-14T07:06:53.133558809Z #FailureMessage Object: 0xbeb5c24c
2021-07-14T07:07:54.433098117Z
2021-07-14T07:07:54.433180876Z
2021-07-14T07:07:54.433206784Z #
2021-07-14T07:07:54.433230784Z # Fatal error in , line 0
2021-07-14T07:07:54.433253876Z # unreachable code
2021-07-14T07:07:54.433276913Z #
2021-07-14T07:07:54.433299580Z #
2021-07-14T07:07:54.433322394Z #
2021-07-14T07:07:54.433345006Z #FailureMessage Object: 0xbeb3424c
2021-07-14T07:08:55.696356724Z
2021-07-14T07:08:55.696458391Z
2021-07-14T07:08:55.696482409Z #
2021-07-14T07:08:55.696504279Z # Fatal error in , line 0
2021-07-14T07:08:55.696525650Z # unreachable code
2021-07-14T07:08:55.696546816Z #
2021-07-14T07:08:55.696567557Z #
2021-07-14T07:08:55.696588168Z #
2021-07-14T07:08:55.696608686Z #FailureMessage Object: 0xbe9a224c
```

**Comment by Panja0** [comment]
Just FYI:
I just upgraded my Docker instance from v1.0.1 to v1.0.3 without any problems.
Docker running on a Synology.

**Comment by louislam** [comment]
I personally tested on x64 and arm64. It is working.

Which platform are you using?

**Comment by rezzorix** [comment]
I tried on 4 machines:

[color=red]Not working:
Raspberry pi 3B+ | armv7l | Raspbian GNU/Linux 10 (buster) 
Raspberry pi 4 | armv7l | Raspbian GNU/Linux 10 (buster)[/color}

Working:
Lattepanda v1 | x86_64 | 20.04.2 LTS (Focal Fossa)
VM | x86_64 | 20.04.2 LTS (Focal Fossa)

So the x86_64 seems to have no issue.
The arm has problems...

**Comment by louislam** [comment]
The big difference between 1.0.1 and 1.0.3 is that I change the base image to Apline Linux in order to reduce the container size.

I don't have arm v7 on hand, could you please try this two commands:

```
docker run node:14-alpine3.14 npm
```

It should print the npm usage

```
docker run node:14-alpine3.14 -e "console.log('hello-world')"
```

It should echo hello-world.

**Comment by rezzorix** [comment]
And there we got the error.. alpine linux is the culprit ;)

```
docker run node:14-alpine3.14 npm
Unable to find image 'node:14-alpine3.14' locally
14-alpine3.14: Pulling from library/node
136482bf81d1: Already exists
bdd119b32a78: Already exists
8bf68b515250: Already exists
2f0693970941: Already exists
Digest: sha256:07640af2829bf356db3b995f64043e3cd58a53af5703c48a51f3e07eb645e946
Status: Downloaded newer image for node:14-alpine3.14


#
# Fatal error in , line 0
# unreachable code
#
#
#
#FailureMessage Object: 0x7ec4526c
```

**Comment by rezzorix** [comment]
Adding this for further reading:
_NPM crashes on Raspberry Pi 3 B+ in the latest Docker image 
https://www.gitmemory.com/issue/Koenkk/zigbee2mqtt/7662/852985841_

**Comment by louislam** [comment]
> And there we got the error.. alpine linux is the culprit ;)
> 
> ```
> docker run node:14-alpine3.14 npm
> Unable to find image 'node:14-alpine3.14' locally
> 14-alpine3.14: Pulling from library/node
> 136482bf81d1: Already exists
> bdd119b32a78: Already exists
> 8bf68b515250: Already exists
> 2f0693970941: Already exists
> Digest: sha256:07640af2829bf356db3b995f64043e3cd58a53af5703c48a51f3e07eb645e946
> Status: Downloaded newer image for node:14-alpine3.14
> 
> 
> #
> # Fatal error in , line 0
> # unreachable code
> #
> #
> #
> #FailureMessage Object: 0x7ec4526c
> ```

So bad..... I can't believe the base image on arm/v7 is not working at all.🙈
Please use 1.0.1 at this moment, I need to find a way to test on arm/v7 to fight with the problem.

**Comment by rezzorix** [comment]
> So bad..... I can't believe the base image on arm/v7 is not working at all.🙈
> Please use 1.0.1 at this moment, I need to find a way to test on arm/v7 to fight with the problem.

While you are at it... maybe wanna see if armv6 is also possible?
Would love to run this on my Raspberry Pi Zero :D

**Comment by louislam** [comment]
> > So bad..... I can't believe the base image on arm/v7 is not working at all.🙈
> > Please use 1.0.1 at this moment, I need to find a way to test on arm/v7 to fight with the problem.
> 
> While you are at it... maybe wanna see if armv6 is also possible?
> Would love to run this on my Raspberry Pi Zero :D

with docker is not possible, base nodejs image do not provide armv6.
without docker maybe possible.

**Comment by mkono87** [comment]
Yep same issue on rpi3. No worky work :(

**Comment by louislam** [comment]
> Adding this for further reading:
> _NPM crashes on Raspberry Pi 3 B+ in the latest Docker image https://www.gitmemory.com/issue/Koenkk/zigbee2mqtt/7662/852985841_

Based on their discussion, the problem is related to 3.13

So, would you mind to try 3.12 on your pi, thank you.
```
docker run node:14-alpine3.12 npm
```

**Comment by rezzorix** [comment]
3.12 returns `hello-world`

So you can use 3.12 :smiley:

**Comment by louislam** [comment]
> 3.12 returns `hello-world`
> 
> So you can use 3.12 😃

So great, will change to 3.12 for next release

**Comment by louislam** [comment]
> @louislam FYI this issue isn't going to go away unless someone updates libseccomp2 in the main repo for Debian armv7 (it can also be caused by people running old versions of the Docker engine).
> 
> The "fix" is client-side - update libseccomp from the [Buster Backports repo](https://docs.linuxserver.io/faq#libseccomp) and make sure the docker engine is up to date from their repos rather than the distro repos which are frequently way behind. Alpine 3.13 (and indeed 3.14) based build of your image works fine on a patched armv7 Rasbian/Pi OS host.

Thank you so much! Hope they update the libseccomp2 before Alpine 3.12 reaches end of life.

**Comment by Edgarruiz856** [comment]
edgarplasticos3@hotmail.com

**Comment by Edgarruiz856** [comment]
- [x] edgarplasticos3@hotmail.com> I tried on 4 machines:
> Not working:
> Raspberry pi 3B+ | armv7l | Raspbian GNU/Linux 10 (buster) 
> Raspberry pi 4 | armv7l | Raspbian GNU/Linux 10 (buster)
> 
> Working:
> Lattepanda v1 | x86_64 | 20.04.2 LTS (Focal Fossa)
> VM | x86_64 | 20.04.2 LTS (Focal Fossa)
> 
> So the x86_64 seems to have no issue.
> The arm has problems... 
> 
> The arm versions were working before for me... nothing changed.
> I just sudo docker stop container, sudo docker rm container, sudo docker rm image and then docker run again.
