### ISSUE TITLE
Managed PostgreSQL database need self-signed certificate in certificate chain

### ISSUE THREAD

**Issue by acarlomagno** [louislam/uptime-kuma#4100]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

I have a managed PostgreSQL database on DigitalOcean... the server needs a mandatory SSL connection
I get this error when I try to connect to the "self-signed certificate in certificate chain"
I created a self-signed certificate and tried to set an environment var path... but when I start the container I get an error and it won't start

I used these variables: UPTIME_KUMA_SSL_KEY and UPTIME_KUMA_SSL_CERT...
I copied the .key and .crt files to the Ubuntu server folder... but the container can't seem to find them.

Should I copy them into the container?

 ...or did I go the wrong way?

### 📝 Error Message(s) or Log

self-signed certificate in certificate chain

### 🐻 Uptime-Kuma Version

1.23.6

### 💻 Operating System and Arch

Ubuntu 22.04.2

### 🌐 Browser

Chrome

**Comment by chakflying** [comment]
The environment variables are not used for connecting monitor targets, but for enabling TLS when accessing Uptime Kuma.

Have you tried adding `sslmode=no-verify` as a parameter in your connection string?

**Comment by acarlomagno** [comment]
> The environment variables are not used for connecting monitor targets, but for enabling TLS when accessing Uptime Kuma.
> 
> Have you tried adding `sslmode=no-verify` as a parameter in your connection string?

wow works! ... but it's strange because sslmode=required was a mandatory parameter about the documentation.

**Comment by chakflying** [comment]
If you don't want to disable certificate verification, you can try using the environment variable `NODE_EXTRA_CA_CERTS=<path to your .crt>`. The file needs to be inside the container.

**Comment by acarlomagno** [comment]
thanks @chakflying  I will try also this way
