### ISSUE TITLE
Keep getting a request failed with a status 302

### ISSUE THREAD

**Issue by combatistor** [louislam/uptime-kuma#4103]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### Description

Hi everyone, I was playing with my docker swag reverse proxy and at some point I added a
`rewrite ^/(.*)$ http://domain.com/$1 permanent;` to my domain.
Since then I modified it to a 301 redirect but in order to mitigate the 'permament' I had to clear the caches of my browsers.
The problem is I keep getting an error 302 for the http monitoring 1 of my services, wether I access it via the IP:PORT or with the domain name. This service is hosted on a different machine than my docker setup.
I tried to check if there is a way to clear the cache of something in uptime kuma, recreating the container, cleaning the docker network but I can't get rid of the issue.
I also tried to call curl from within the container to IP:PORT or domain name and it works, I can't understand why it doesn't work from the application.

I'm testing more and I complitely removed my internal dns and reverse proxy, and tested using the IP:PORT and I was still getting the error.

### 👟 Reproduction steps

I added this
`rewrite ^/(.*)$ http://domain.com/$1 permanent;` at some point in my reverse proxy and replaced it afterwards by a
`return 301`

### 👀 Expected behavior

I should get a 200 OK

### 😓 Actual Behavior

I'm getting a 302

### 🐻 Uptime-Kuma Version

1.23.7

### 💻 Operating System and Arch

docker on ubuntu 20

### 🌐 Browser

MS Edge Version 119.0.2151.72

**Comment by louislam** [comment]
Cannot reproduce and there is no cache mechanism. 


You can try my simple test. Basically it will result 200 or 302 randomly.
https://louislam.net/test-random-302.php 

```php
<?php
// Random 302 redirect
$random = rand(1, 2);
if ($random == 1) {
    header("Location: https://uptime.kuma.pet", true, 302);
} else {
    echo "200 OK";
}

```

![image](https://github.com/louislam/uptime-kuma/assets/1336778/75c888b0-1e14-4d54-a929-b5c8aef3a331)

**Comment by combatistor** [comment]
I could get it working by changing the port of the service I was trying to reach on the other machine. That's a strange issue and I have no idea why or where it was making a trouble, I hope it can be useful for others.

After re-checking my setup, I have an internal dns (adguard home), a reverse proxy (swag) on the same docker host. I could configure docker to share my local dns with the containers, but now uptime kuma is unable to monitor http, I'm getting a timeout by abort signal. when I check nslookup inside the container, I can resolve the names, but it seems kuma can't

**Comment by combatistor** [comment]
My bad, sorry I forgot about the max redirects

**Comment by louislam** [comment]
Also `curl` maybe helps.

https://github.com/louislam/uptime-kuma/wiki/Troubleshooting

**Comment by combatistor** [comment]
mmmhhh resolution doesn't work with curl

**Comment by combatistor** [comment]
I think the problem was that my service stirling pdf was redirecting automatically to /login page, and I wasn't aware of that.
Now I fixed the problem, so be careful if the service you try to monitor automatically redirects you to a different page, I thought at first it was coming from my reverse proxy but it wasn't.

Thank you for the help !
