### ISSUE TITLE
Apprise / Nextcloud - URL Prefix support

### ISSUE THREAD

**Issue by idominiki** [louislam/uptime-kuma#4119]
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

Other

### 🔖 Feature description

Would be great if 'url_prefix' is also working in Uptime Kuma Setting as referenced here https://github.com/caronc/apprise/issues/974

### ✔️ Solution

As our Nextcloud is running in subdir /nextcloud we can't use Nextcloud Talk in Apprise actually.

**Comment by louislam** [comment]
Should be able to resolve by upgrading to Apprise 1.6.0. Will try to update it.
