### ISSUE TITLE
How to change port 3001 to some other port WITHOUT docker

### ISSUE THREAD

**Issue by gl-yziquel** [louislam/uptime-kuma#4125]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

My problem is simple. 1. I checked out the repo with git/gix. 2. I did `pnpm install`. 3. I did `npm run dev` 4. As I have many services running on my computer, port 3001 is busy and server can't start up.

```console
2023-11-30T12:01:24+01:00 [SERVER] DEBUG: Init the server
2023-11-30T12:01:24+01:00 [SERVER] ERROR: Cannot listen: listen EADDRINUSE: address already in use :::3001
2023-11-30T12:01:24+01:00 [SERVER] INFO: Shutdown requested
```

I did not see instruction to change the port in the doc, and I'm not on docker, but running it on metal. Ideally, I'd like `npm run dev` to work with alternate ports.

Where do I set such a configuration for uptime-kuma ?

### 🐻 Uptime-Kuma Version

1708b67949ca183b2ee86ef70e9e51c5f721a73e

### 💻 Operating System and Arch

Ubuntu

### 🌐 Browser

None. elinks most of the time. Falkon. Anyhow, not applicable here.

### 🐋 Docker Version

Not applicable here.

### 🟩 NodeJS Version

v20.5.1

**Comment by gl-yziquel** [comment]
Ah...

Hard-coded in `server/server.js`:

```javascript
const port = [ args.port, process.env.UPTIME_KUMA_PORT, process.env.PORT, 3001 ]
```

OK. I'll try this environment variable or argument.

**Comment by louislam** [comment]
> Ah...
> 
> Hard-coded in `server/server.js`:
> 
> ```js
> const port = [ args.port, process.env.UPTIME_KUMA_PORT, process.env.PORT, 3001 ]
> ```
> 
> OK. I'll try this environment variable or argument.

If you can change the port by the environment variable or argument, then logically it is not hard-coded.

Close as you find the answer by yourself.

**Comment by gl-yziquel** [comment]
ok. sorry.

**Comment by gl-yziquel** [comment]
Thank you so much !
