### ISSUE TITLE
Use iframe to mimic subdirectory deployment

### ISSUE THREAD

**Issue by jinghuashang** [louislam/uptime-kuma#4128]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

I want to reverse proxy Uptime kuma through nginx to a secondary directory, for example, I deploy uptime kuma to status.abc.com, but I want to proxy it to abc.com/status.

### 🐻 Uptime-Kuma Version

1.23.7

### 💻 Operating System and Arch

ubutu 20.04

### 🌐 Browser

Google Chrome

**Comment by jinghuashang** [comment]
Refer to this [website](https://moeyy.cn/status/)

**Comment by CommanderStorm** [comment]
Currently, subdirectory deployments are not possible. Please refer ot https://github.com/louislam/uptime-kuma/pull/1092 for additional details

**Comment by chakflying** [comment]
I think this is the only viable solution in the foreseeable future, so it's actually quite reasonable to recommend. We might need to mention the environment variable `UPTIME_KUMA_DISABLE_FRAME_SAMEORIGIN`.
