### ISSUE TITLE
How to add/update/delete monitor programatically

### ISSUE THREAD

**Issue by nreddipalle** [louislam/uptime-kuma#4138]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

I want to add/update/delete monitors as part of our infrastructure provisioning pipeline. Is it possible to perform these actions programmatically instead of manual action.

### 🐻 Uptime-Kuma Version

1.23.7

### 💻 Operating System and Arch

Linux Container

### 🌐 Browser

Google Chrome

**Comment by CommanderStorm** [comment]
Currently, this is not possible. Please see #118 https://github.com/louislam/uptime-kuma/issues/1940 https://github.com/louislam/uptime-kuma/issues/4026 https://github.com/louislam/uptime-kuma/issues/210
=> current draft is sheduled to be reviewed in the v2.1 release https://github.com/louislam/uptime-kuma/pull/3854

There are external tools such as https://uptime-kuma-api.readthedocs.io/en/latest/ available, but there may be interop issues

**Comment by fede843** [comment]
it would have been nice to be able to provision configuration
