### ISSUE TITLE
Received Alert from "DatasourceNoData"

### ISSUE THREAD

**Issue by Konano** [louislam/uptime-kuma#4148]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### Description

All services are running, but I always get an "server down" alert from the source named "DatasourceNoData".

![image](https://github.com/louislam/uptime-kuma/assets/22500116/9e6288cb-6af8-4e9e-a9ba-6d5c9405f211)

![image](https://github.com/louislam/uptime-kuma/assets/22500116/dce2cb72-236d-400f-9f38-12adc924ce7a)

Is this a bug? How can I debug?

### 👟 Reproduction steps

Do not know how to reproduct.

### 👀 Expected behavior

Display the correct source.

### 😓 Actual Behavior

Display the wrong source named "DatasourceNoData"

### 🐻 Uptime-Kuma Version

1.23.7

### 💻 Operating System and Arch

Docker amd64

### 🌐 Browser

Unimportance

### 🐋 Docker Version

Docker 24.0.4

### 🟩 NodeJS Version

Unimportance

**Comment by CommanderStorm** [comment]
What are your monitors names and monitor types?

**Comment by louislam** [comment]
Is it Telegram?

There is no hard coded string `DatasourceNoData`, I guess you have another Uptime Kuma instance or your Telegram API key leaked.

Try to reset the Telegram API key.

**Comment by Konano** [comment]
> There is no hard coded string DatasourceNoData

Yes, that's why I feel so wierd.

> Try to reset the Telegram API key.

I will use another Telegram Chat ID to receive alerts. If `DatasourceNoData` is sent from another Uptime Kuma instance, it should not change.

**Comment by Konano** [comment]
Found that the alert is from Grafana lol
