### ISSUE TITLE
E-Mail notification does not work

### ISSUE THREAD

**Issue by XHyperDEVX** [louislam/uptime-kuma#4151]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

I have transferred the e-mail data from an old instance 1:1 to my new one, but I get a timeout.
The old instance works perfectly. The only difference between the two instances is that the old one is standalone and the new one is in docker.

### 📝 Error Message(s) or Log

-

### 🐻 Uptime-Kuma Version

1.23.7

### 💻 Operating System and Arch

Debian 12 with Docker

### 🌐 Browser

Edge

### 🐋 Docker Version

20.10.24

### 🟩 NodeJS Version

no idea, just docker

**Comment by CommanderStorm** [comment]
Where is your email server located? Is it on the server itsself or remote?
Could you try these steps: https://github.com/louislam/uptime-kuma/wiki/Troubleshooting

**Comment by XHyperDEVX** [comment]
problem fixed, was due to docker itself.
