### ISSUE TITLE
Check Now button

### ISSUE THREAD

**Issue by Stevelolp** [louislam/uptime-kuma#4152]
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

UI Feature

### 🔖 Feature description

A Checknow button for a selected Monitor in the Dashboard would be cool. 

### ✔️ Solution

Create a Check Now Button that skips the wait time and checks the Monitor immediately and add it to the top list of buttons together with the pause, delete and edit button.

**Comment by chakflying** [comment]
Duplicate of #3800
