### ISSUE TITLE
Hide monitor in maintenance on status page if the monitor is not list in the status page

### ISSUE THREAD

**Issue by Lurikbolding** [louislam/uptime-kuma#4173]
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

UI Feature

### 🔖 Feature description

I use 3 monitors. (M1 M2 M3).
I create 2 status page (SP1 and SP2)

I add the M1 monitor on the SP1 status page (for customer 1)
I add all monitor on the SP2 page (for me, admin user)

When i put the M2 monitor in maintenance, there is a blue caption on the Status page SP2 with the text of the maintenance.

But on the SP1 page, the maintenance caption is still visible.
The customer 1 did not understand why he see maintenance information about monitor which are not list on the SP1 page

### ✔️ Solution

I think the maintenance caption should be visible only if the monitor in maintenance is to be show on the status page.

**Comment by NihadBadalov** [comment]
@Lurikbolding I tried to reproduce your issue. However, I didn't get the same results. Here are some pictures of the way I set the stuff up:

Can you make sure you have the same settings? If it still doesn't work, could you provide more detailed steps to reproduce?

<details>
<summary>Pictures</summary>

<details>
<summary>Maintenance Settings (IMPORTANT)</summary>
<img width="896" alt="image" src="https://github.com/louislam/uptime-kuma/assets/32594553/6bffe6c7-3345-42e6-a918-cee2dfcf1080">
</details>

<details>
<summary>Monitors</summary>
<img width="431" alt="image" src="https://github.com/louislam/uptime-kuma/assets/32594553/bcf5e4bd-1400-44b9-9571-0f0e6f5ba704">
</details>

<details>
<summary>SP1</summary>
<img width="1163" alt="image" src="https://github.com/louislam/uptime-kuma/assets/32594553/225d6778-7076-475b-a973-d2bb5b5c9d42">
</details>

<details>
<summary>SP2</summary>
<img width="1150" alt="image" src="https://github.com/louislam/uptime-kuma/assets/32594553/2bb4eaaf-449c-4329-a9a1-2832b712422b">
</details>

</details>

**Comment by Lurikbolding** [comment]
Hello
Sorry i did not see your first message.

I don't success to reproduce the issue. So i think i made a mistake the first time.
