### ISSUE TITLE
[ntfy] priority level is not clearly communicated to the user

### ISSUE THREAD

**Issue by tdavis6** [louislam/uptime-kuma#4174]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### Description

When a notification is triggered, it sends to ntfy with a priority of 5. This is the incorrect behavior because it is set to send with a priority of 4. The double chevron indicates a priority of 4, while the triple chevron indicates a priority of 5.

![image](https://github.com/louislam/uptime-kuma/assets/53464194/e26704d8-de5f-45de-9cc3-05c62839ef90)
![image](https://github.com/louislam/uptime-kuma/assets/53464194/5b684576-a966-4096-8bc1-037959759c2d)

Thank you so much for such an awesome app!

### 👟 Reproduction steps

This is triggered by setting a notification to use ntfy, with a priority of 4. Then, if a monitor goes down, the notification is sent with a priority of 5.

### 👀 Expected behavior

It would be expected that the notification is sent with a priority of 4. 

### 😓 Actual Behavior

The notification was sent with a priority of 5.

### 🐻 Uptime-Kuma Version

1.23.8

### 💻 Operating System and Arch

Synology DSM 7.2.1-69057 Update 3

### 🌐 Browser

Firefox 120.0.1

### 🐋 Docker Version

20.10.23

**Comment by tdavis6** [comment]
So sorry, just read the ntfy.js file and this appears to be the intended behavior. This is based on lines 44-45.

**Comment by CommanderStorm** [comment]
The behaviour is this way since https://github.com/louislam/uptime-kuma/pull/2863

https://github.com/louislam/uptime-kuma/blob/ad4629cb038c5b47fb04053f48c6fa905644e386/server/notification-providers/ntfy.js#L44-L45

=> down monitors have n+1 `priority`

**Comment by tdavis6** [comment]
Thank you so much for the quick reply!

**Comment by CommanderStorm** [comment]
@tdavis6 
What do you think about such a helptext ?
I am struggling to find a formulation which does not include `max(5, priority + 1)`. Do you have any good ideas?

![image](https://github.com/louislam/uptime-kuma/assets/26258709/956f8189-1d04-45a7-89c7-19a6c65ae860)

**Comment by CommanderStorm** [comment]
Okay.
I think I found a way which does not include a formula. Oppinions?

![image](https://github.com/louislam/uptime-kuma/assets/26258709/e1bd99a4-0b47-401f-8dd4-2c0188ec7a55)
![image](https://github.com/louislam/uptime-kuma/assets/26258709/70d7c56a-4e0b-4876-99bf-3fb444718732)

**Comment by tdavis6** [comment]
I think that looks good! However, if the set priority is 3 and it bumps it to 4 that might not be clear. I'm trying to think of something that would make that behavior clear, without being too long to put there.

**Comment by tdavis6** [comment]
Perhaps "All events are sent with this priority, except DOWN-events, which have a priority one above this, with a maximum of 5"

**Comment by tdavis6** [comment]
Thank you so much for helping me!

**Comment by sevmonster** [comment]
I wasn't aware of this functionality. Would it be too much to have a separate priority for down alerts?

**Comment by CommanderStorm** [comment]
Resolved by https://github.com/louislam/uptime-kuma/pull/4175
