### ISSUE TITLE
Backup and restore issues

### ISSUE THREAD

**Issue by leochen12-rgb** [louislam/uptime-kuma#4177]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 👟 Reproduction steps

When using the backup function, restore the docker mapped data directory using the web interface after the backup is complete. These two restoration methods have bugs, can not restore the group information, all the hosts are restored together

### 👀 Expected behavior

Restore a backup

### 😓 Actual Behavior

Grouping disappears, hosts are all put together

### 🐻 Uptime-Kuma Version

1.23.8

### 💻 Operating System and Arch

centos stream 9

### 🌐 Browser

Google Chrome 119.0.6045.200

### 🐋 Docker Version

Docker 20.10.21

**Comment by rezzorix** [comment]
There is a big warning written on the backup page:

```
Deprecated: Since a lot of features were added and this backup feature is a bit unmaintained, it cannot generate or restore a complete backup.
Please backup the volume or the data folder (./data/ directly instead.
```
