### ISSUE TITLE
Uptime Stats reset everytime i login

### ISSUE THREAD

**Issue by awptechnologies** [louislam/uptime-kuma#4182]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

When logging into uptime all history is gone. It like it starts over everytime i login. This happen after flushing database from GUI.

### 🐻 Uptime-Kuma Version

Latest

### 💻 Operating System and Arch

Debian 12

### 🌐 Browser

Firefox

### 🐋 Docker Version

Latest

### 🟩 NodeJS Version

Latest

**Comment by CommanderStorm** [comment]
- what do you mean by starting over?
- how did you deploy your instance?
- What option do you mean by "flushing database"? ![image](https://github.com/louislam/uptime-kuma/assets/26258709/bddd71cb-cc66-4789-aae0-4b8466649620)
- Digging into a performance hypothesis:
  - How many montiors/... do you have?
  - How big is the db on disk?
  - what disk are you running on?
  - what was your rentention previous to flushing the db?

**Comment by CommanderStorm** [comment]
Closing as @awptechnologies did not respond to the questions and without additional information debugging is impossible
=> closing as stale
