### ISSUE TITLE
If Resend Interval is set to 0, no alerts are ever sent

### ISSUE THREAD

**Issue by sevmonster** [louislam/uptime-kuma#4184]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### Description

Using Ntfy notification backend, if I set the *Resend Notification if Down X times consecutively* to zero, I do not get notifications at all from that monitor. I would prefer to not receive more than one alert for each outage, but this seems not possible at the moment. Maybe related to #3365?

### 👟 Reproduction steps

1. Set up notifications
2. Create a monitor
3. Set *Resend Notification if Down X times consecutively* to zero
4. Enable notifications
5. Let the monitor go down

### 👀 Expected behavior

I get a notification

### 😓 Actual Behavior

I get no notification

### 🐻 Uptime-Kuma Version

1.23.8

### 💻 Operating System and Arch

Alpine Linux edge

### 🌐 Browser

any

### 🐋 Docker Version

Docker 24.0.7, Compose v2.23.3

### 🟩 NodeJS Version

16.13.1

### 📝 Relevant log output

```shell
Logs look identical to monitors with Resend Interval set above 0
```

**Comment by sevmonster** [comment]
And you set the *notification* resend interval to 0, not the uptime check retries? Just making sure since that is all you took a screenshot of.

This always happens with all monitors for me. After changing all monitors to use a larger integer notifications magically started working. There is nothing particularly interesting about my setup that might make it different.

I can do some testing if you like.

**Comment by CommanderStorm** [comment]
Yes, can still reproduce this.

![image](https://github.com/louislam/uptime-kuma/assets/26258709/6f36b749-416d-4968-9238-e86a85b3e7c0)
![image](https://github.com/louislam/uptime-kuma/assets/26258709/adff9168-abb0-4dda-b67d-f72d9eb2abf2)

**Comment by sevmonster** [comment]
I also can no longer reproduce this with the existing monitors that were experiencing this. Maybe by setting the value higher than 0 it got them out of whatever state they were stuck in. I will reopen if it re-emerges.
