### ISSUE TITLE
Status from local side via local DNS & CNAME at TCP port

### ISSUE THREAD

**Issue by XHyperDEVX** [louislam/uptime-kuma#4187]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

I have two questions:

I have a local DNS server that forwards "home.local" to a local ip. i want to monitor the access from "home.local". Unfortunately, uptime-kuma can't connect to this local url because it uses external DNS servers, in my case Cloudflare [1.1.1.1].
How can I tell it to query the url at the local DNS server ONLY FOR THIS ONE CONNECTION?

And my second question:

Can I somehow specify a CNAME in the TCP port option? I would like to monitor the HTTP access from outside, i.e. whether one comes into my network from outside via port 80. As I unfortunately do not have a static IP, I have set up a DynDNS service. Unfortunately, I can only enter IPs for the TCP port, not a CNAME. Is there any way to do this?

### 📝 Error Message(s) or Log

-

### 🐻 Uptime-Kuma Version

1.23.7

### 💻 Operating System and Arch

Debian 12 [..as host system, i use the Uptime-Kuma Docker Image]

### 🌐 Browser

Edge

### 🐋 Docker Version

20.10.24

### 🟩 NodeJS Version

i dont know

**Comment by CommanderStorm** [comment]
Note that if you need dns resolution, you are likely monitoring a website => the https monitor is be better suited for this.
