### ISSUE TITLE
How to monitor API？

### ISSUE THREAD

**Issue by junyangfan** [louislam/uptime-kuma#4190]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

I have created a proxy API interface now, and I want to listen to this API interface. How should I configure it?

This API interface returns a 403 status，But this status code is the result I expected

### 🐻 Uptime-Kuma Version

1.23.8

### 💻 Operating System and Arch

Debian 10 x86

### 🌐 Browser

Google Chrome

**Comment by CommanderStorm** [comment]
>  I want to listen to this API interface

It may be able to call the API via the monitors included.
This entirely depends on what type (gRPC, http/JSON/XML, MQTT, ...) your API is.
The only clue you gave is that it reurns a status of 403 which likely implies that you want to monitor an http endpoint. (=> use one of the https monitors depending on what you want to monitor)
What your definition of up is not something you have specified. (does a 403 already mean up or do you need to auth agains your API first?)
Currently, this issue does not hold enough details to help you in any meaningful way.
