### ISSUE TITLE
Notify When Page takes more than  x ms to load

### ISSUE THREAD

**Issue by riteshsonawane1372** [louislam/uptime-kuma#4192]
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

New Notification

### 🔖 Feature description

I want to get notified when my website take more than 4500ms to load. 

### ✔️ Solution

We can check every 60 sec if page takes more than 4500ms to load and then send notification. 

### ❓ Alternatives

None

**Comment by CommanderStorm** [comment]
Closing as a duplicate of https://github.com/louislam/uptime-kuma/issues/1813
