### ISSUE TITLE
Build Error (Termux)

### ISSUE THREAD

**Issue by Toserk1024** [louislam/uptime-kuma#4198]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

When I tried to deploy this program on an Android phone using termux, a build error occurred after running for some time after using the npm run setup command. When I looked at the console log, I found that it had requested a file that didn't exist, causing subsequent builds to fail. The following is the error log output at the time of the request:

    ERR! install response status 404 Not Found on https://github.com/louislam/node-sqlite3/releases/download/v15.1.6/napi-v6-android-arm-unknown.tar.gz
    node-pre-gyp WARN Pre-built binaries not installable for @louislam/sqlite3@15.1.6 and node@20.2.0 (node-v115 ABI, unknown) (falling back to source compile with node-gyp)
    node-pre-gyp WARN Hit error response status 404 Not Found on https://github.com/louislam/node-sqlite3/releases/download/v15.1.6/napi-v6-android-arm-unknown.tar.gz

In order to avoid inaccurate expression in the translation process, the following is the original Chinese text:
当我在使用termux在安卓手机上尝试部署此程序时，使用npm run setup命令之后，运行一段时间之后发生构建错误。我在查看控制台日志时，发现它请求了一个不存在的文件，导致后续的构建出错。

### 📝 Error Message(s) or Log

[This is the full log](https://file.toserk.tk/other/2023-12-09T14_03_56_992Z-debug-0.log)

### 🐻 Uptime-Kuma Version

latest

### 💻 Operating System and Arch

Android10 Termux

### 🌐 Browser

No need to provide

### 🟩 NodeJS Version

v20.2.0

**Comment by louislam** [comment]
It is not official supported.

It is just for fun.

You can read this: https://github.com/louislam/uptime-kuma/issues/423

**Comment by Toserk1024** [comment]
Thanks for your help, now it can run successfully.![IMG_20231210_085705.jpg](https://github.com/louislam/uptime-kuma/assets/89717167/bfbcfed1-b553-44ac-adfe-11f36708fbaa)

**Comment by Murchik0v** [comment]
![Screenshot_20240305-100733](https://github.com/louislam/uptime-kuma/assets/67903447/58ff12fd-bb00-49af-9d3f-885b8e219362) and? It's not working

**Comment by CommanderStorm** [comment]
@Murchik0v Termux is an experiment and might not be working correctly.
It is not official supported, It is just for fun.

You should read this: https://github.com/louislam/uptime-kuma/issues/423
