### ISSUE TITLE
Feature request: SNMP 

### ISSUE THREAD

**Issue by jterpstra1** [louislam/uptime-kuma#420]
**Is it a duplicate question?**
No

**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
SNMP as a monitoring option, would like to use this in combination with monitoring via SNMP

**Describe alternatives you've considered**
Have googled for some solutions but this one seems the best if possible

**Additional context**
-

**Comment by BCsabaEngine** [comment]
SNMP is a metric system with variables that means number, percents and strings. Uptimekuma is an uptime system with bool status info. How to display ex. printer cartridge level percent?

**Comment by stephen304** [comment]
I would love to be able to have uptime kuma listen to the snmpv3 notifications from my APC ups so that I can get alerts and monitoring of power outages in uptime kuma.

**Comment by c-zolotko** [comment]
SNMP would be nice for our Extron devices and Projectors.

**Comment by CommanderStorm** [comment]
@jterpstra1 I would like to track this issue in https://github.com/louislam/uptime-kuma/issues/1675, given that the other issue has more likes ([Some mainteiners use 👍🏻 on issues to prioritise work](https://github.com/louislam/uptime-kuma/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc))
Could you close this issue?
