### ISSUE TITLE
 New notification method: Request URL

### ISSUE THREAD

**Issue by Toserk1024** [louislam/uptime-kuma#4201]
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

New Notification

### 🔖 Feature description

Add a new notification method: Request URL,This can facilitate access to some PHP scripts to achieve DNS switching and other functions.

### ✔️ Solution

Sends a request to a URL when the status of a monitored item changes, The request content can be escaped using some variables,For example, when the test monitoring item is down, the notification is set as "https://example.com/?name={{name}}&status={{status}}"The real URL of the request at this point is "https://example.com/?name=test&status=down"

**Comment by CommanderStorm** [comment]
See the Webhook monitor instead:

![image](https://github.com/louislam/uptime-kuma/assets/26258709/86d862a7-da6f-4a8f-b4d8-db4207aab002)

Note that templating the request url is tracked in #1734

=> closing as a duplicate
