### ISSUE TITLE
Please make security CVEs public 

### ISSUE THREAD

**Issue by ntimo** [louislam/uptime-kuma#4207]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

Hello the release https://github.com/louislam/uptime-kuma/releases/tag/1.23.9 contains two CVEs but they are not public yet. Could you please make them public so people can read them to know what the security vulnerabilities are about.

### 🐻 Uptime-Kuma Version

1.23.9

### 💻 Operating System and Arch

None

### 🌐 Browser

None

**Comment by louislam** [comment]
Done
