### ISSUE TITLE
Make a dockerfile

### ISSUE THREAD

**Issue by ganjakha** [louislam/uptime-kuma#4209]
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

Other

### 🔖 Feature description

Make a dockerfile so we can deploy this awesome project in one click.

### ✔️ Solution

Make a dockerfile so we can deploy this awesome project in one click.

**Comment by CommanderStorm** [comment]
Please refer to our Readme:
https://github.com/louislam/uptime-kuma?tab=readme-ov-file#-docker

Or our installation instructions:
https://github.com/louislam/uptime-kuma/wiki/%F0%9F%94%A7-How-to-Install#-docker

**Comment by ganjakha** [comment]
I know it.
I want one click solution for deploying in render/heroku/clevet cloud or
other docker hosting that doesn't support manual deploying (at least not
free)..

A dockerfile will do it.🥹

**Comment by CommanderStorm** [comment]
Our dockerfiles for the `1.23.X` release train (`master` is for `v2.0-dev´) is located here: https://github.com/louislam/uptime-kuma/blob/1.23.X/docker/dockerfile

Please refer to https://github.com/louislam/uptime-kuma/wiki/%F0%9F%94%A7-How-to-Install#unofficial--experimental for the currently reported one-click options.
If you have found more options, opening a PR agianst our wiki would be appreciated ^^

**Comment by ganjakha** [comment]
Thanks, I'll check them out.
