### ISSUE TITLE
 SyntaxError: Unexpected token '.'

### ISSUE THREAD

**Issue by reconftw010101** [louislam/uptime-kuma#421]
**Is it a duplicate question?**
Please search in Issues without filters: https://github.com/louislam/uptime-kuma/issues?q=

**Info**
Uptime Kuma Version: Latest
Using Docker?: No
Docker Version:
Node.js Version (Without Docker only):  v12.16.3
OS: Ubuntu
Browser: Firefox

I'm facing the syntax error in model name monitor.js here is the log

2|uptime-kuma  | Welcome to Uptime Kuma
2|uptime-kuma  | Node Env: undefined
2|uptime-kuma  | Importing Node libraries
2|uptime-kuma  | Importing 3rd-party libraries
2|uptime-kuma  | Importing this project modules
2|uptime-kuma  | /root/UpTimeChecker/server/model/monitor.js:139
2|uptime-kuma  |                     if (this.getUrl()?.protocol === "https:") {
2|uptime-kuma  |                                       ^
2|uptime-kuma  | SyntaxError: Unexpected token '.'
2|uptime-kuma  |     at wrapSafe (internal/modules/cjs/loader.js:1047:16)
2|uptime-kuma  |     at Module._compile (internal/modules/cjs/loader.js:1097:27)
2|uptime-kuma  |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1153:10)
2|uptime-kuma  |     at Module.load (internal/modules/cjs/loader.js:977:32)
2|uptime-kuma  |     at Function.Module._load (internal/modules/cjs/loader.js:877:14)
2|uptime-kuma  |     at Module.require (internal/modules/cjs/loader.js:1019:19)
2|uptime-kuma  |     at Module.Hook._require.Module.require (/usr/local/lib/node_modules/pm2/node_modules/require-in-the-middle/index.js:80:39)
2|uptime-kuma  |     at require (internal/modules/cjs/helpers.js:77:18)
2|uptime-kuma  |     at Object.<anonymous> (/root/UpTimeChecker/server/server.js:27:17)
2|uptime-kuma  |     at Module._compile (internal/modules/cjs/loader.js:1133:30)
PM2            | App [uptime-kuma:2] exited with code [1] via signal [SIGINT]
PM2            | App [uptime-kuma:2] starting in -fork mode-
PM2            | App [uptime-kuma:2] online

![image](https://user-images.githubusercontent.com/89736003/133603998-16cb3205-e923-4115-b8d1-c604252be550.png)

**Comment by louislam** [comment]
Required Tools: Node.js >= 14, git and pm2.
