### ISSUE TITLE
Notification for folder is not correct

### ISSUE THREAD

**Issue by hoangpbc** [louislam/uptime-kuma#4212]
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

New Notification, UI Feature

### 🔖 Feature description

A Folder name 'A' has a subfolder named 'B', when I add some monitor channel on folder B, if one of these channels is down, 
for examples: if one channel down, the whole folder B has status 'DOWN' and the whole folder A carry status DOWN too. And the number of down host is: 1 host actually down + 1 folder B down + 1 Folder A down = 3 host down

### ✔️ Solution

just readjust so that the folder can not have a status down or something like that

**Comment by CommanderStorm** [comment]
Currently, groups are down if any member is down.
Alternative handling approaches are tracked in https://github.com/louislam/uptime-kuma/issues/1089 https://github.com/louislam/uptime-kuma/issues/2487 #2668 #3387
=> closing as a duplicate
