### ISSUE TITLE
Monitoring HTTP(S) service that is sitting behind an Identity Provider (Authentik).

### ISSUE THREAD

**Issue by Jas-SinghFSU** [louislam/uptime-kuma#4220]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

When I attempt to monitor a domain using the HTTP(S) monitor for a service that sits behind an Identity Provider like Authentik, I get a success even though the service is down. This is because upon visiting the Domain I want to monitor, you must pass Authentik first. Since Authentik is always up and the first thing that responds, Uptime Kuma thinks that 200 response is from the actual application.

Flow goes: Request App URL > Authentik (Identity Provider) > Actual Application

How can I check the status of the Actual Application and bypass Authentik. I know that Uptime Kuma has OAuth credentials where it takes the Token URL and ID+Secret, but I don't think Authentik can provide these.

Any suggestions would be appreciated, thank you.

### 🐻 Uptime-Kuma Version

1.23.9

### 💻 Operating System and Arch

Ubuntu 22.04 x86

### 🌐 Browser

Microsoft Edge

**Comment by CommanderStorm** [comment]
If you get a response back from your auth provider, what is in the content of said message?
Can you use keyword/json-query to determine uptime with that?

**Comment by Jas-SinghFSU** [comment]
@CommanderStorm The response for the original request is a 302 code which redirects to the auth subdomain. The content when I run a curl on it is the following:
```
<html>
  <head><title>301 Moved Permanently</title></head>
  <body>
    <center><h1>301 Moved Permanently</h1></center>
    <hr><center>openresty</center>
  </body>
</html>
```

I doesn't seem like I can use a keyword/json-query because Uptime Kuma would somehow have to go past the authentication (assuming it passed) to check the true status. And it doesn't seem like it can.

**Comment by CommanderStorm** [comment]
So basically, you get redirected to their website, have to log in and only then the website of your auth-provider shows (proxies) you the content?
This likely sets a cookie (?) / JWT / oAuth token for your session. Depending on how long this session time is + how much access you have, it might be possible to either create a never expiring session to use a session.

It seems like you likely can circumvent this by either:
- utilising authentic's oauth support (as far as I glanced at their docs, they seem to support this, am I missing something?)
- utilising a combination of "does the app redirect to authentic" and internal checks using the push monitor (=skipping auth)

**Comment by Jas-SinghFSU** [comment]
Yes, since Authentik is an Identity Provider middleware that sits in the proxy. It checks if authentication is passed and it'll then pass that information onto the proxy (NGINX) to go ahead and redirect to the appropriate web service. 

It does have OAuth support but using the oauth credentials provided by Authentik doesn't seem to work. I think the OAuth credentials are meant to integrate with the authentication strategy of apps since it relies on redirect urls and various other parameters. Maybe I'm missing something though.

I'm not sure I'm following the 2nd point, if you could expand on that please.

**Comment by CommanderStorm** [comment]
Well you monitor if authentic is returing a 301 with the expected content => assume auth flow is working
You also monitor your app by sending heartbeats to the url specified in the push monitor => assume your app is healthy

Given that there appears to be no simple way to circumvent authentic (at least that I can see from glancing at their docs) this is the simplest way.

**Comment by Jas-SinghFSU** [comment]
Ah, I see what you're saying now. I'm going to save this approach because like you said, there's no simple way to circumvent Authentik.

I ended up finding a solution in the meantime; most (not all) of the apps that I host have a health-check endpoint and I added an exception to that Authentik. That way authorization can be bypassed for those health-check specific endpoints.
