### ISSUE TITLE
After refreshing a status page in Safari, data does not load

### ISSUE THREAD

**Issue by gridsystem** [louislam/uptime-kuma#4222]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### Description

After refreshing a status page in Safari, data does not load correctly, all graphics go blank and there is an axios error in console.

### 👟 Reproduction steps

- Create a status page and add multiple HTTP monitors to it.
- Visit the status page
- Verify that monitor data is loading correctly
- Make sure developer tools -> network -> disable caches is not enabled, we want caching to work as it would for normal users
- Press refresh

### 👀 Expected behavior

The page should load as it did the first time, with all data present

### 😓 Actual Behavior

- The monitors go blank
- Errors are visible in console
  - `Failed to load resource: The network connection was lost`
  - `Unhandled Promise Rejection: AxiosError: Network Error`

### 🐻 Uptime-Kuma Version

1.23.9

### 💻 Operating System and Arch

MacOS Sonoma 14.1.1

### 🌐 Browser

Safari 17.1

### 🐋 Docker Version

Unsure, via fly.io

### 🟩 NodeJS Version

Unsure, via louislam/uptime-kuma:1.23.9 image

**Comment by louislam** [comment]
Have you tried Chrome or Firefox?

**Comment by louislam** [comment]
Could you test my instance on your Safari: https://status.kuma.pet

**Comment by louislam** [comment]
> Failed to load resource: The network connection was lost

No idea, but it is a connection error unlikely related to Uptime Kuma. Could be fly.io, or your network.

And I always recommend to host Uptime Kuma on a pure VPS or Linux machine.

These platforms usually cause some weird issues. Similar to Replit.

**Comment by CommanderStorm** [comment]
Yes, communication between client-server is done via web sockets

**Comment by chakflying** [comment]
I remembered running it on fly.io and it worked fine, unfortunately I did not keep the config file around. Have you tried switching between the different connection handlers available?

**Comment by louislam** [comment]
The status page is not Websocket, it is just a normal http request, as you can see the axios error which is a http client error.

I said fly.io just because I have no idea. As the issue is pretty weird, it could be everything actually.

Your instance:
- Chrome / Firefox = ok
- Safari = not ok

My instance:
- all ok

**Comment by CommanderStorm** [comment]
Given that this is likely a problem with fly and not with us (you said it works on the demo site) I would suggest you contact the fly support for these issues you are seeing instead.
They are much more likely to be able to help you on how to get a service running on their infrastructure.

**Comment by CommanderStorm** [comment]
If I had to guess, this might be because of some misconfiguration of scale-to-zero (we don't support that)

**Comment by CommanderStorm** [comment]
For anybody wondering, scale to zero can be controlled via `auto_stop_machines = false` and `auto_start_machines = true` as written here: https://community.fly.io/t/hosting-uptime-kuma-on-fly-io/14352

I am going to consider this issue resolved. If this is not, we can reopen

**Comment by CommanderStorm** [comment]
The latest stable release. (No significant difference other than the demo timer)

**Comment by CommanderStorm** [comment]
docker, but that is not likely to be the culprit.
See https://github.com/louislam/demo-kuma for further details on said site

**Comment by louislam** [comment]
https://stackoverflow.com/questions/18811286/nodejs-express-cache-and-304-status-code

I just randomly saw a question on stackoverflow which may be or may not be related to this issue.
