### ISSUE TITLE
Tailscale Bug

### ISSUE THREAD

**Issue by Panic135** [louislam/uptime-kuma#4228]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### Description

During the recent Tailscale re-write fix, it appears to have broken my setup - I run Ubuntu 22.04, Tailscale (latest) and Uptime Kuma and nothing else - Tailscale Ping working fine as of 1.23.6 - when upgraded to 1.23.9 the Tailscale Ping stopped working and started responding on the UI "no output from ping", when I rolled uptime kuma back, worked absolutely fine. 

### 👟 Reproduction steps

Add a tailscale ping monitor on Uptime Kuma 1.23.9 or newer. 

### 👀 Expected behavior

It would ping and show as up. 

### 😓 Actual Behavior

It came up with large red box on the right hand side of the screen saying no output from ping. 

### 🐻 Uptime-Kuma Version

1.23.9

### 💻 Operating System and Arch

Ubuntu 22.04, x86

### 🌐 Browser

Google Chrome

### 🐋 Docker Version

NA

### 🟩 NodeJS Version

Tried with both 18.19.0 and 20.10 - Both working on Kuma 1.23.6 but not as of 1.23.9

### 📝 Relevant log output

```shell
Not sure where to generate the log.
```

**Comment by CommanderStorm** [comment]
Only change to https://github.com/louislam/uptime-kuma/blob/1.23.X/server/monitor-types/tailscale-ping.js was https://github.com/louislam/uptime-kuma/pull/4123/files

=> sync to async
=> limiting to 1 ping per ping

Unsure what could be causing problems here

**Comment by Panic135** [comment]
Any estimated time for a release to resolve this? -Thanks!

**Comment by CommanderStorm** [comment]
#4231 was merged and will be [included in `1.23.11`](https://github.com/louislam/uptime-kuma/milestone/47). As any self-respecting, volunteer run engineering project, we live by [#NoEstimates](https://www.youtube.com/watch?v=QVBlnCTu9Ms).

Said release will be made once ready.
