### ISSUE TITLE
Browser Engine monitors causes out of memory over time.

### ISSUE THREAD

**Issue by itrankolov** [louislam/uptime-kuma#4232]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### Description

When I configure the montor types to be Browser engine (Chrome/Chromium), after some time I get a lot of chromium processes in the container. After a few days this causes out of memory condition. In my opinion for some reason the chromium processes are not cleaned up after a check is being done.  I have 4 monitors using Browser Engine and after a few hours there are like 100s of chromium processes running.

### 👟 Reproduction steps

Normal installation with some monitors using Browser Engine monitor type.

### 👀 Expected behavior

Cleanup of (stalled?) chromium processes after a check is executed. 

### 😓 Actual Behavior

A lot of chromium processes pile up after a few hours. 

### 🐻 Uptime-Kuma Version

1.23.10, but was the same on 1.23.9

### 💻 Operating System and Arch

Docker on Debian 12.4

### 🌐 Browser

N/A

### 🐋 Docker Version

20.10.24+dfsg1, build 297e128

### 🟩 NodeJS Version

v18.18.2

**Comment by CommanderStorm** [comment]
Duplicate of #3788
