### ISSUE TITLE
How to set up ping monitor to Sonarr

### ISSUE THREAD

**Issue by EricHupp** [louislam/uptime-kuma#4235]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

I have a strange issue.  I have the arr stack installed and UK is monitoring it fine through Cloudflare tunnels, but in Sonarr and only Sonarr I keep getting log spam of this line every 30 seconds (which is my heartbeat interval)
2023-12-13 14:35:22.8|Info|Auth|Auth-Unauthorized ip 192.9.xxx.xxx  url 'http://sonarr.foo.org'
I looked in the docs to try and use a ping monitor but when I enter my URL it tells me pop up of "Please match the requested format."

If I turn off auth on the app General page it goes away, but I don't want to do that as it's a secondary layer to my server. 
I guess my question is, what is the format I'm supposed to use to set up a monitor for Sonarr that doesn't access the auth page? 
Both Ping and Health are referenced in the docs and I don't think I'm using them correctly. 

### 📝 Error Message(s) or Log

2023-12-13 14:58:34.7|Info|Auth|Auth-Unauthorized ip 192.9.xxx.xxx url 'http://sonarr.foo.org'

### 🐻 Uptime-Kuma Version

1.23.10

### 💻 Operating System and Arch

Ubuntu 22.04.3 LTS

### 🌐 Browser

Google Chrome Version 120.0.6099.71

### 🐋 Docker Version

Docker version 20.10.24, build 297e128

### 🟩 NodeJS Version

na

**Comment by CommanderStorm** [comment]
I think this issue might resolve your question https://github.com/Sonarr/Sonarr/issues/5396

from reading the error message:
In case you want to use the health check endpoint, you might have to allow said IP to auth

**Comment by EricHupp** [comment]
Thanks for the reply.  I read through that thread before opening this and it's not making sense to me.   I'm pretty new to this and have a real basic understanding of linux.   When I try and add https://myurl.org/ping it tells me it's not the correct format. 
I don't understand what that format should be.  
I looked in Sonarr's settings and don't see anything (including advanced) that references how to add an IP to auth
>In case you want to use the health check endpoint, you might have to allow said IP to auth

Sorry to be a bother on this but I'm kinda lost.

**Comment by CommanderStorm** [comment]
> When I try and add ... it tells me it's not the correct format.

Please go step by step.
What did you add where?
What system is telling you what error message exactly?

Could you attach a screenshot of your configuration with the api key redacted?

**Comment by CommanderStorm** [comment]
Also important: are you using the `v3` or `v4` api of sonarr?

**Comment by EricHupp** [comment]
Sonarr is v3.

Currently this is what I have for my monitor
![image](https://github.com/louislam/uptime-kuma/assets/29580743/b840a9a1-8772-42fd-bfa3-7da58a94b70d)

Since I'm using CF Tunnels that has basic auth I have this included.

![image](https://github.com/louislam/uptime-kuma/assets/29580743/00cd747a-9d12-4468-8810-c31d58648fb4)


When I try and change the monitor type to PING I get this error. 
![image](https://github.com/louislam/uptime-kuma/assets/29580743/af41d50f-b3a1-4f4d-85d2-dab71582ddad)

I also tried changing to this url and still get the auth spam in my log. 
2023-12-13 15:57:24.5|Info|Auth|Auth-Unauthorized ip 192.9.136.251 url 'http://sonarr.xxxxxxx.org/api/v3/health'
![image](https://github.com/louislam/uptime-kuma/assets/29580743/28a365d0-6638-4265-9a88-b98ffc7fab0a)

**Comment by CommanderStorm** [comment]
What you are trying to monitor is a https-api => use the https monitor.

You are missing the auth fields entirely => rejected auth is too be expected.

From the sonarr docs (https://sonarr.tv/docs/api/) I get this field:

> [!NOTE]
> The v3 API docs apply to both v3 and v4 versions of Sonarr. Some functionality may only be available in v4 of the Sonarr application
![image](https://github.com/louislam/uptime-kuma/assets/26258709/60a1a806-5c44-4784-bbab-26ba6c1ed24c)

**Comment by EricHupp** [comment]
I tried using the Authentication section with the username/password for the auth page on Sonarr and that didn't change anything. 

![image](https://github.com/louislam/uptime-kuma/assets/29580743/8ee81d30-d359-4048-8bd2-a33b9c73244d)

**Comment by CommanderStorm** [comment]
According to their api that is not a supported auth mechanism.
Please use the apiKey as I wrote above

**Comment by EricHupp** [comment]
>Please use the apiKey as I wrote above


I followed https://sonarr.tv/docs/api/ and entered the ip address that needs auth

![image](https://github.com/louislam/uptime-kuma/assets/29580743/ce6f4d84-b057-41f1-8189-e9ba75a8555e)



Which opened this window.  I generated an API key in UP and entered it in both of these fields.  I still get the same log entries.  

![image](https://github.com/louislam/uptime-kuma/assets/29580743/a7d5474b-c453-4407-8a5b-7ec4132b9d92)

I have this as my entry in UP

![image](https://github.com/louislam/uptime-kuma/assets/29580743/6233dae6-e8f1-4c74-9440-c5dc209058b0)

**Comment by CommanderStorm** [comment]
> I generated an API key in UP and entered it in both of these fields.

Have you added the correct header to the request?
Please be more specific in what software you have added fields? (Uptime Kuma won't know if you add something to the swagger editor UI)
Could you re-check that you have added the `X-Api-Key`-Header or include the `apikey` query parameter.

Please attach a screenshot of your full configuration (including headers, as they are the relevant part)

> I have this as my entry in Uptime Kuma

Please use the `ping` or `health check`-routes as specified in the sonarr api. It is unclear to me if other routes require more auth.

**Comment by EricHupp** [comment]
Please remember that I'm somewhat new to this. 
I am completely guessing at what to do. 

>Have you added the correct header to the request?
I have this in my headers section

{
    "CF-Access-Client-Id": "efxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx.access",
    "CF-Access-Client-Secret": "74382c889975xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
}

>Please use the ping or health check-routes as specified in the sonarr api. 
I still have no idea what I'm supposed to add in either of these entries. 

>According to their api that is not a supported auth mechanism.
>Please use the apiKey as I wrote above

You stated earlier to do this.   Do what with the API key?  What entry am I supposed to put in it? 
Am I supposed to create a key in uptimekuma?  I did and I have no idea what I'm supposed to do with it. 

You posted this address  https://sonarr.tv/docs/api/ but that doesn't tell me what I'm supposed to do with it. 
I followed the link and guessing that it is looking for the address to authorize I entered the address that is showing 
in my logs and clicked authorize.  I then entered the API key that I generated in uptimekuma, but that didn't work.

**Comment by EricHupp** [comment]
Success!!!

This was the part I needed. 
https://example.com/ping?apikey=INSERT_API_KEY_HERE

I added the API key from Sonarr into the URL you gave and the log spam stopped.  

Thank you so much for being patient with me.  I greatly appreciate it.

**Comment by EricHupp** [comment]
Issue closed.
