### ISSUE TITLE
Status Page High Density Display

### ISSUE THREAD

**Issue by brooksvb** [louislam/uptime-kuma#4236]
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

UI Feature

### 🔖 Feature description

The default status page display wastes a ton of screen real estate on anything larger than mobile. I think there should be an option to enable higher density styling on a status page.	

We plan to display a status page on a large wall-mounted TV, so we would like to see much more information using that screen real-estate.

### ✔️ Solution

A checkbox option in the edit sidebar for a status to enable high-density display, reducing empty space on the page and displaying many more items in more than a single column. Enabling this option should not break styling for smaller screens and mobile.

### ❓ Alternatives

I solved this by writing some custom CSS. I was pleased with the results and wanted to share my work, so I created a [Reddit post](https://www.reddit.com/r/UptimeKuma/comments/18hv05l/sharing_my_high_density_status_page_css/).

The CSS can be viewed in [this Gist](https://gist.github.com/brooksvb/78a54355151a18477e33c224177dc5fa).

I tested at typical computer monitor sizes and made sure mobile size still looked fine. I still need to see how it looks on 4K screen sizes and will likely need to add a couple additional tweaks, which I will update in the Gist.

I figured my CSS could be a good reference for implementing this as a feature, but as things currently stand, we are satisfied with our custom CSS.

Here are before and after pictures for comparison:
![kuma-before](https://github.com/louislam/uptime-kuma/assets/14019044/9b87bf8f-d5c2-4cf2-b7fe-11ac55e76d20)
![kuma-after](https://github.com/louislam/uptime-kuma/assets/14019044/303b23f5-1797-40a3-a01e-861a8383aead)

Here is a list of the changes my CSS makes:

- Removed large gutters on the sides of content to use more of full screen width
- Dynamic grid layout with min and max width for each item; will try to fit as many columns appropriate for the screen size
- Changed item layout to a stacked layout for compactness
- Moved uptime percentage on items to empty space to allow more width for display name
- Added border around items for slightly improved readability
- Compacted header by moving Uptime Status side-by-side with the main Status Page Title
- Compacted footer
- Overrides for various margins and padding for compactness
- Tweaked the blue color used for maintenance message because original was harsh on the eyes
- Consideration for not applying certain changes that don't look good on mobile

**Comment by CommanderStorm** [comment]
Multi column displays for the status page are tracked in #3934 and #1844
I don't see a real difference between this and the other issues
=> closing as a duplicate

**Comment by brooksvb** [comment]
My bad, I tried searching a few terms but didn't find those issues. Thanks.

**Comment by CommanderStorm** [comment]
Yea, GitHub's search is not great. Fully agree on that one

**Comment by ShadowWhisperer** [comment]
For reference, both above issues are closed. All of the issues they reference are closed, except this [#592](592
).

**Comment by pacholoamit** [comment]
Just wanting to say I referenced this here: https://github.com/pacholoamit/uptime-kuma-themes
