### ISSUE TITLE
After installation, the page does not open

### ISSUE THREAD

**Issue by IVAN96H** [louislam/uptime-kuma#4237]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

After installing monitoring using the Non-Docker method, the control panel page simply does not open.
During the installation, I used snap to install NodeJS v18.18.0
I also installed npm v9.9.2
I also installed Git (v2.34.1) and PM2 (v5.3.0).

### 🐻 Uptime-Kuma Version

1.23.10

### 💻 Operating System and Arch

Ubuntu 22.04.3 LTS

### 🌐 Browser

N/A

### 🐋 Docker Version

N/A

### 🟩 NodeJS Version

18.18.0

**Comment by CommanderStorm** [comment]
> simply does not open

What do you mean by this?
Could you attach screenshots, error messages or logs?
