### ISSUE TITLE
Server in the status pages not clickable unless I log into dashboard

### ISSUE THREAD

**Issue by treemlt** [louislam/uptime-kuma#4239]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

I am self hosting Uptime-Kuma and I have succesfully added servers but I cannot click them to view the full info unless I log into the dashboard. Is there a way i can enable this? I have looked in all the settings and found nothing.

### 🐻 Uptime-Kuma Version

Latest

### 💻 Operating System and Arch

Linux

### 🌐 Browser

Google Chrome

### 🐋 Docker Version

Contianer Manager Synology

**Comment by CommanderStorm** [comment]
You can disable auth, but this will also disable any form of authentication. If your system is only internally available, this might be fine for you from a security perspective, but for anything public DON'T

The full information might contain secrets and is therefore never publicly available.

**Comment by sevmonster** [comment]
You can click them? What is that supposed to do? I click them and nothing happens.

**Comment by CommanderStorm** [comment]
Ah, sorry, I misread your question and thought it was about how to disable the having to log in part.

Currently, no such feature exists, this is tracked in the following (you can subscribe there for progress info):
- group titles: #4072
- monitor link to dashboard: #2787
- login button on dashboard: #544
- status page-url ⇋ monitoring url difference: #2507

If you want to help with this, here is our [contribution guide](https://github.com/louislam/uptime-kuma/blob/master/CONTRIBUTING.md)

I think this should resolve the question
