### ISSUE TITLE
Use `navigator.languages` instead of `navigator.language` for language detection

### ISSUE THREAD

**Issue by cyberbellum96** [louislam/uptime-kuma#4243]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem (edited by @chaflying)

Language key `uk` is not recognized by the front-end, and the displayed language defaults back to `en`.

### 🐻 Uptime-Kuma Version

1.23.10

### 💻 Operating System and Arch

Ubuntu 22.04.3 LTS

### 🌐 Browser

N/A

### 🐋 Docker Version

24.0.7

### 🟩 NodeJS Version

N/A

**Comment by IVAN96H** [comment]
> What do you mean by "for editing"? you have found the correct folder for editing the database

I need to change some status page data, but I can't find its source code. I already asked a question about changing the language on the status page. Now I need to find a file where I can edit the default language for site visitors.

**Comment by CommanderStorm** [comment]
First of all, it seems like you are using docker.
Note that modifications to this part would be temporary and revert at the next reboot.

A default language and locale switcher is included in #3523 and said PR will be reviewed in the [v2.1 release train](https://github.com/louislam/uptime-kuma/milestone/40).

See https://github.com/louislam/uptime-kuma/issues/1643 
=> there is no "default language" for site visitors, this is dependent on which language the OS is set to.

Localising the footer/.. is tracked here: https://github.com/louislam/uptime-kuma/issues/2784

Our contibution guide (including how to get a dev environment set up) is here: https://github.com/louislam/uptime-kuma/blob/master/CONTRIBUTING.md

**Comment by cyberbellum96** [comment]
> First of all, it seems like you are using docker. Note that modifications to this part would be temporary and revert at the next reboot.
> 
> A default language and locale switcher is included in #3523 and said PR will be reviewed in the [v2.1 release train](https://github.com/louislam/uptime-kuma/milestone/40).
> 
> See #1643 => there is no "default language" for site visitors, this is dependent on which language the OS is set to.
> 
> Localising the footer/.. is tracked here: #2784
> 
> Our contibution guide (including how to get a dev environment set up) is here: https://github.com/louislam/uptime-kuma/blob/master/CONTRIBUTING.md

I have "Ukrainian" in my OS settings, but by default it displays in English.

**Comment by CommanderStorm** [comment]
The default language is determined like this: https://github.com/louislam/uptime-kuma/blob/8151ac0e2546467d7f75ed7403b4229372d515a8/src/i18n.js#L60-L63

Could you run the following commands in the console with uptime open?

```js
localStorage.locale
```
```js
navigator.language
```

**Comment by cyberbellum96** [comment]
> uptime-kuma/src/i18n.js



> The default language is determined like this:
> 
> https://github.com/louislam/uptime-kuma/blob/8151ac0e2546467d7f75ed7403b4229372d515a8/src/i18n.js#L60-L63
> 
> Could you run the following commands in the console with uptime open?
> 
> ```js
> localStorage.locale
> ```
> 
> ```js
> navigator.language
> ```

The problem is that I can't find where this file is located: uptime-kuma/src/i18n.js

How exactly should I execute these commands through the console?

**Comment by cyberbellum96** [comment]
I managed to find 3 i18n.js files at the following address: var/lib/docker/overlay2/<many numbers and letters>/diff/app/src

**Comment by CommanderStorm** [comment]
> How exactly should I execute these commands through the console?

The console is integrated into your browser (assuming you use chrome given that you did not fill out that field). Open the the inspector via right-clicking 

![image](https://github.com/louislam/uptime-kuma/assets/26258709/62e21045-303c-416c-9a2a-b6f9699ca4b8)

![image](https://github.com/louislam/uptime-kuma/assets/26258709/bde00790-16bb-4a99-af4d-b57033a672c8)

**Comment by CommanderStorm** [comment]
The reason for this is that we currently only support the `uk-UA` locale and not `uk`

I think a better approach compared to the current one would be to use 
![image](https://github.com/louislam/uptime-kuma/assets/26258709/c587a30f-1128-4a13-869f-1f3b13e91512)

instead.
Docs: https://developer.mozilla.org/en-US/docs/Web/API/Navigator/languages

**Comment by cyberbellum96** [comment]
> The reason for this is that we currently only support the `uk-UA` locale and not `uk`
> 
> I think a better approach compared to the current one would be to use ![image](https://private-user-images.githubusercontent.com/26258709/290847886-c587a30f-1128-4a13-869f-1f3b13e91512.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI2NTA0NTMsIm5iZiI6MTcwMjY1MDE1MywicGF0aCI6Ii8yNjI1ODcwOS8yOTA4NDc4ODYtYzU4N2EzMGYtMTEyOC00YTEzLTg2OWYtMWYzYjEzZTkxNTEyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE1VDE0MjIzM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUxY2ZhM2M3ODQyNmQ5MmM0NmM2MmFhMTNhMmJjODVkMGYyYThlZjUyNDQxYTUxMjQxZmM1YzdkNGM3ZTFmN2UmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.pB8a7giiQ2JEEWLsioquJgTQMsih0Vv67nPQf4HQ9jg)
> 
> instead. Docs: https://developer.mozilla.org/en-US/docs/Web/API/Navigator/languages

Okay, I understand what the problem is. Thank you very much!

**Comment by CommanderStorm** [comment]
Closing as #4244 was merged
