### ISSUE TITLE
Tags on Status Page

### ISSUE THREAD

**Issue by XHyperDEVX** [louislam/uptime-kuma#4248]
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

UI Feature

### 🔖 Feature description

It would be great if you could display the Montitor tags on the status pages, for example like this:
![image](https://github.com/louislam/uptime-kuma/assets/68189420/71336323-2232-4fd7-bf3e-2aea452fb334)

### ✔️ Solution

Integrate it lol

### ❓ Alternatives

-

**Comment by chakflying** [comment]
There's already a setting for this.

![image](https://github.com/louislam/uptime-kuma/assets/3271800/efd4be3d-1d7d-47ff-9a3c-f998239b4ff4)
