### ISSUE TITLE
All HTTP Monitors show Down Status

### ISSUE THREAD

**Issue by zluckytraveler** [louislam/uptime-kuma#4249]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

Whenever I use the the HTTP(s) monitor and use any url with just `HTTP` the status is down, however if I use `HTTPS` it is up. I have confirmed that it can any URL and it will report a down status for `timeout exceeded`

I have tried using multiple different versions of Uptime Kuma and using a different machine with a separate instance of Uptime Kuma and the result is still the same.

I have tried using the Demo and it works as expected.

### 🐻 Uptime-Kuma Version

1.23.10

### 💻 Operating System and Arch

MacOS (Ventura 13.0.1)

### 🌐 Browser

Safari

### 🐋 Docker Version

4.21.1

**Comment by chakflying** [comment]
If the demo works but not on your machine, then it's most likely a problem with your network configuration. Maybe plain HTTP requests are getting blocked or redirected.

**Comment by PikuZheng** [comment]
Same problem. It features dual-stack domain names and runs in containers.

 I suspect it is related to curl, when testing using curl inside the container, curl looped

**Comment by CommanderStorm** [comment]
You can single in one one of the stacks via specifing
```
curl -6 -v google.com
```
or
```
curl -4 -v google.com
```

**Comment by PikuZheng** [comment]
not resolved

**Comment by CommanderStorm** [comment]
Yes, but not debuggable without further details.
See my comment above asking for the `curl` output using different ip-familys...

please refer to our troubleshooting guide: how to execute curl in the contaienr https://github.com/louislam/uptime-kuma/wiki/Troubleshooting

**Comment by PikuZheng** [comment]
Due to some subsequent upgrades, I think this issue no longer exists.
