### ISSUE TITLE
ping for ip:port not working after last update

### ISSUE THREAD

**Issue by gpopesc** [louislam/uptime-kuma#425]
**Describe the bug**
After last update I had few containers checked in Kuma by monitor type: ping ip:port and I get down status for all containers with this type of checking.
It used to work before last update.
I changed to http(s) status check and it works ok

![image](https://user-images.githubusercontent.com/11590919/133684508-084844d4-f3b1-4ac6-970e-2fdb566a5a46.png)

**Expected behavior**
the server checked by monitor type: ping is up and running for selected IP.

**Info**
Uptime Kuma Version: 1.6.2
Using Docker?: Yes
Docker Version: 20.10
OS: Synology

**Comment by louislam** [comment]
Your screenshot is shown that it is "ping" type, which is icmp ping and cannot ping with port.

Please try "TCP Ping" type.

**Comment by gpopesc** [comment]
thank you for your confirmation
