### ISSUE TITLE
Can I use Uptime Kuma to ping private IPs from multiple locations?

### ISSUE THREAD

**Issue by djxcee** [louislam/uptime-kuma#4252]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

I am trying to see if I can use Uptime Kuma to do a basic ping on devices to private IPs from multiple locations.  I can setup containers at each location but not sure how I would accomplish this, without a VPN setup.

Any suggestions would be appreciated!

### 🐻 Uptime-Kuma Version

1..23.10

### 💻 Operating System and Arch

Ubuntu 22.04.3

### 🌐 Browser

Google Chrome 120.

**Comment by chakflying** [comment]
If you have devices in a private network, but you expect to be able to access them outside, there must be some mechanism for you to bridge the networks together. It would only make sense to run monitoring over the same method you access them. So I don't see why you would want to do this without a VPN.

You can use something like tailscale to avoid the complications of setting up a VPN yourself.

**Comment by CommanderStorm** [comment]
> do a basic ping on devices to private IPs from multiple locations

The reverse is possible:
You set up push monitors on your central instance and push heartbeats there.

**Comment by djxcee** [comment]
Hi @CommanderStorm, I was thinking the same without the need to setup a VPN/Bridge.

However, I look at Monitor Types and I only see ping without additional Types to perform per device.  Trying to see how I would do a Ping then notifify a Push to our primary Uptime Kuma instance.

**Comment by CommanderStorm** [comment]
Push monitors require you to do arbitrary checks. The other monitoring types are not avaliable for remote execution. See #84 for further discussion.
=> you write a small shell/python/... script that defines what is up and pushes a heartbeat to the url defined by the push monitor in Uptime Kuma if it is.
