### ISSUE TITLE
Update Debian to bullseye+

### ISSUE THREAD

**Issue by thatsgolden** [louislam/uptime-kuma#4253]
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

Other

### 🔖 Feature description

Upgrade the based Docker Image, so we can use Chromium v120, right now debian buster only has a Chromium v90 package.

(well, I found I was using a bookworm apt source, so I got the errors below, solved via chenge source to buster)
~Right now uptime-kuma use `node:18-buster` which based on Debian 10 (Buster), but debian 10 does not have a `libcrypt1` package.~

> https://packages.debian.org/search?suite=buster&arch=any&searchon=names&keywords=libcrypt1

~So when you install Chromium 120.0.6099.109-1~deb12u1, you will get an error:~

### ✔️ Solution

build the docker version of uptim-kuma based on [node:18-bullseye](https://github.com/nodejs/docker-node/blob/f416b53801a9d49d6ce6b2c038c8bc9ed93625dd/18/bullseye/Dockerfile) at lease

**Comment by louislam** [comment]
Will be in 2.0.0.

https://github.com/louislam/uptime-kuma/blob/c9fe6b5d0166f66a9837f489aa453fb128ce53db/docker/debian-base.dockerfile#L2
