### ISSUE TITLE
Kuma Layout Change

### ISSUE THREAD

**Issue by Chronos093** [louislam/uptime-kuma#4255]
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

Other

### 🔖 Feature description

Hello, 
I would like to request a change in the current layout of Kuma, if possible, to improve the visualisation on panels / TV. The current layout is very strange and not practical when you have in mind to put on a TV to monitor all day, especially if there are several items to monitor.

### ✔️ Solution

I believe that a layout that highlights the column that is currently on the left and that has cards for each monitor, with a cleaner designer focusing only on displaying whether it is on/off, if you want more information click on the card and a modal will be displayed, which would be the current right column.

### 📝 Additional Context

I display kuma on a 32" tv where I monitor my services and servers, but the current layout of kuma makes it very difficult and impractical to visualise the information on this screen.

**Comment by CommanderStorm** [comment]
@Chronos093 Please report issues in english. Nobody on our team can read portugese.
I have ran deepl over this issue.

**Comment by CommanderStorm** [comment]
Multi column displays for the status page are tracked in #3934, #1844 and #592
I don't see a real difference between this and the other issues
=> closing as a duplicate
