### ISSUE TITLE
[docker] `exec /usr/bin/dumb-init: input/output error`

### ISSUE THREAD

**Issue by miselve** [louislam/uptime-kuma#4259]
### ⚠️ Please verify that this bug has NOT been raised before.

- [x] I checked and didn't find a similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

I was using Uptime Kuma on docker for sometime now. After I updated to 1.23.10 It refused to start stating `exec /usr/bin/dumb-init: input/output error` . Some system details: Raspberry Pi 5 4GB running Raspbian. If I leave it running it crashes my whole Raspberry.

I use the following command to run the container: (as suggested in the documentation)
`docker run -d --restart=always -p 3001:3001 -v uptime-kuma:/app/data --name uptime-kuma louislam/uptime-kuma:1`

PS. I am using portainer to manage all my containers. 

### 📝 Error Message(s) or Log

exec /usr/bin/dumb-init: input/output error
exec /usr/bin/dumb-init: input/output error
exec /usr/bin/dumb-init: input/output error
exec /usr/bin/dumb-init: input/output error
exec /usr/bin/dumb-init: input/output error
exec /usr/bin/dumb-init: input/output error
exec /usr/bin/dumb-init: input/output error
exec /usr/bin/dumb-init: input/output error
exec /usr/bin/dumb-init: input/output error
exec /usr/bin/dumb-init: input/output error
exec /usr/bin/dumb-init: input/output error
exec /usr/bin/dumb-init: input/output error
exec /usr/bin/dumb-init: input/output error
exec /usr/bin/dumb-init: input/output error
And it keeps going...

### 🐻 Uptime-Kuma Version

1.23.10

### 💻 Operating System and Arch

Raspbian ARM64

### 🌐 Browser

Chrome 120.0.6099.72

### 🐋 Docker Version

24.0.7

**Comment by louislam** [comment]
According to this, you are using a image of wrong arch for some reason.

https://github.com/apache/airflow/discussions/30925

How did you update the image?

**Comment by miselve** [comment]
> According to this, you are using a image of wrong arch for some reason.
> 
> [apache/airflow#30925](https://github.com/apache/airflow/discussions/30925)
> 
> How did you update the image?

I rm'ed the old container and pulled the :latest again. I kept the persistent storage and the new container was executed with `docker run -d --restart=always -p 3001:3001 -v uptime-kuma:/app/data --name uptime-kuma louislam/uptime-kuma:1`

Any suggestions?

**Comment by louislam** [comment]
Check the image hash first, see if it is using the correct arch.

**Comment by miselve** [comment]
> Check the image hash first, see if it is using the correct arch.

The image is`sha256:ac6ddd03f1217030c36fc06c0894ceb840ffb9fa1414104db7b6941010714506`
<img width="1376" alt="image" src="https://github.com/louislam/uptime-kuma/assets/94703285/b58a7628-37c3-4a00-bfa7-38db07dda136">

**Comment by louislam** [comment]
> > Check the image hash first, see if it is using the correct arch.
> 
> The image is`sha256:ac6ddd03f1217030c36fc06c0894ceb840ffb9fa1414104db7b6941010714506` <img alt="image" width="1376" src="https://private-user-images.githubusercontent.com/94703285/292010234-b58a7628-37c3-4a00-bfa7-38db07dda136.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMxNTYzMzAsIm5iZiI6MTcwMzE1NjAzMCwicGF0aCI6Ii85NDcwMzI4NS8yOTIwMTAyMzQtYjU4YTc2MjgtMzdjMy00YTAwLWJmYTctMzhkYjA3ZGRhMTM2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjIxVDEwNTM1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY0YmRiMjg1YjE1MWZhNWExNjA3ZTc2MWE1ZDUxZGQ0MWM1ZDI4YzRiOTlmMjRmOWUwMjgzZTQwNmQ5MzAwMTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.mH885p7F_wEFektmvFlP5odN69RlyR5GDEk0GahRwvk">

It's a correct image. I have no idea actually and cannot reproduce.

My instance https://uptime.kuma.pet is working fine and it is also on arm64.

**Comment by chakflying** [comment]
With how little information is related to this error, I think it's more likely a disk corruption issue:

https://unix.stackexchange.com/questions/39905/input-output-error-when-accessing-a-directory

The fact that your whole OS crashes also support this theory. Are you using an old SD card for storage? Maybe you should check the linux logs for disk errors.

**Comment by prljav** [comment]
pretty sure, for some reason(???) uptime kuma does a lotttttt of mostly writes probably and reads which either damages your sd card or does something weird to the controller, just happened to me as well.

**Comment by CommanderStorm** [comment]
> uptime kuma does mostly writes

In v1 the heartbeats are stored in an unaggregated fassion.
=> one heartbeat = one column in the heatbeat table

In v2 we changed this to be agregated. See #4500 for futrther details

Generally, you would not use a SD-Card to run a production project on...

**Comment by prljav** [comment]
> > uptime kuma does mostly writes
> 
> In v1 the heartbeats are stored in an unaggregated fassion. => one heartbeat = one column in the heatbeat table
> 
> In v2 we changed this to be agregated. See #4500 for futrther details
> 
> Generally, I would not use a SD-Card to run a production project on if it includes persistent IO. The reliability of SD cards is just too low imo and the price of cheap name/.. ssds too good

yea... tell that to rpi foundation

**Comment by CommanderStorm** [comment]
> tell that to rpi foundation

They offer a hat which integrates with their case and everything.
See `@geerlingguy`'s video on this topic https://youtu.be/GYN3ub8Qb_I

There are also many boards that build ontop of the compute module offer ssd as a first classs citizen.
