### ISSUE TITLE
Will not install

### ISSUE THREAD

**Issue by Grumpypjs08** [louislam/uptime-kuma#426]
Uptime Kuma Version: 1.6.0
Using Docker?: No
Docker Version: N/A
Node.js Version (Without Docker only): 16.9.1
OS: Linux
Browser: Chrome

I am trying to host it on dreamhost but can not get it to display anything with eather command.

**Comment by gaby** [comment]
Can you provide the commands used and logs?

**Comment by louislam** [comment]
Tested with Node.js 16.9.1 on Ubuntu without any issues. 

Please show the error log.

**Comment by Panja0** [comment]
I had some problems as well installing on a fresh Ubuntu 20.04.3 due to dependencies
Please use the following command for installing:
`sudo npm install --legacy-peer-deps && node node_modules/esbuild/install.js && npm run build && npm prune`
