### ISSUE TITLE
Push monitor doesn't record "msg" parameter unless "status" is different than current

### ISSUE THREAD

**Issue by supermarkert** [louislam/uptime-kuma#4261]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### Description

The "Push" monitor allows for several parameters to be sent with the Push url, including "status" and "msg".  But the Event doesn't update or record a new event and "msg" parameter unless the status is changing from the current state.  If it was DOWN and I send a push url with "status=up&msg=message1", then the status changes and the Message is recorded. But if I send another Push while it is UP, Kuma will receive the heardbeat and keep it UP, but not record the new message event.

### 👟 Reproduction steps

1. Create a "Push" monitor
2. Set an appropriate heartbeat interval for testing.
3. Allow monitor to go DOWN
4. Call URL, with appropriate status and msg (e.g. http://uptimekuma.lan:3001/api/push/########?status=up&msg=message1)
5. (Note that monitor is now UP and "message1" is received as an event)
6. before monitor goes Down, call URL again, with different message (e.g. http://uptimekuma.lan:3001/api/push/########?status=up&msg=message2

### 👀 Expected behavior

I would expect that the Event data would be recorded for every URL call, regardless of the Up/Down status of the monitor. This would allow me to update the monitor at regular intervals and record a relevant status message, any time.  
Otherwise, I'm not sure of the benefit of the "msg" parameter if it can only be set when changing between Up/Down.  

### 😓 Actual Behavior

After step 6 above, the monitor heartbeat is reset, however the Event data and "message2" is not recorded.  Only after waiting for the monitor to be DOWN and then repeating Step 6 would it record the event with "message2".

### 🐻 Uptime-Kuma Version

1.23.10

### 💻 Operating System and Arch

Debian GNU/Linux 12 

### 🌐 Browser

Google Chrome Version 120.0.6099.110 (64-bit)

**Comment by chakflying** [comment]
You can check the latest message by hovering over the last heartbeat. The events list only shows important heartbeats (up/down transitions) by design.

![image](https://github.com/louislam/uptime-kuma/assets/3271800/dea02b16-da20-448a-9d04-cf9ac55dc867)

**Comment by supermarkert** [comment]
OK, thanks. I wasn't aware.  I'll work around it. Just testing a new workflow and seeing if this will work.  
Maybe it's more of a Feature Request then? A configurable option in the monitor (log all events, vs just changes)? Push monitors are kind of an oddball, and I know it would be useful to me if I could look at the monitor and get a complete list of all the status messages I've sent to it (without having to hover over each heartbeat).

**Comment by chakflying** [comment]
For the feature request see #3461.
