### ISSUE TITLE
Update with Docker failed, service not starting.

### ISSUE THREAD

**Issue by hanserasmus** [louislam/uptime-kuma#4269]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### Description

I have tried updating my Docker instance via Portainer, but it fails with the message:

```
2023-12-23T06:00:50Z [DB] INFO: Your database version: 1

2023-12-23T06:00:50Z [DB] INFO: Latest database version: 10

2023-12-23T06:00:50Z [DB] INFO: Database patch is needed

2023-12-23T06:00:50Z [DB] INFO: Patching ./db/patch2.sql

2023-12-23T06:00:50Z [DB] INFO: Closing the database

2023-12-23T06:00:52Z [DB] INFO: SQLite closed

[Error: CREATE TABLE monitor_tls_info (

	id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,

	monitor_id INTEGER NOT NULL,

	info_json TEXT

) - SQLITE_ERROR: table monitor_tls_info already exists] {

  errno: 1,

  code: 'SQLITE_ERROR'

}

2023-12-23T06:00:52Z [DB] ERROR: Start Uptime-Kuma failed due to issue patching the database

2023-12-23T06:00:52Z [DB] ERROR: Please submit a bug report if you still encounter the problem after restart: https://github.com/louislam/uptime-kuma/issues
```

### 👟 Reproduction steps

Update docker instance to latest version

### 👀 Expected behavior

New instance should come up like it did in the past

### 😓 Actual Behavior

Service fails to start. Portainer keeps trying

### 🐻 Uptime-Kuma Version

Version: 1.23.10

### 💻 Operating System and Arch

Docker Swarm

### 🌐 Browser

Firefox

### 🐋 Docker Version

Docker version 24.0.5, build ced0996

### 🟩 NodeJS Version

18.18.2

**Comment by chakflying** [comment]
Please see discussion in #4077.

**Comment by hanserasmus** [comment]
Thank you. Will follow discussion there, but there does not seem to be any fix yet? Or am I missing something?

**Comment by chakflying** [comment]
The user reported that restoring a previous database backup fixed the issue. The last comment also provided the commands for restoring using the SQL dump method.

**Comment by hanserasmus** [comment]
Yeah OK thanks. Not really going to help in my instance. Pity I will have to rebuild everything.
