### ISSUE TITLE
bean.validate - Pterodactyl

### ISSUE THREAD

**Issue by Strongboost** [louislam/uptime-kuma#4271]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

Hey, Im using Pterodactyl and tried to install Uptime Kuma on a nodejs Server (nodejs version 20). I already tried installing everything 3 times. I always get „bean.validate is not a function“. I get this error in the console: „[MONITOR] ERROR: Error adding Monitor: undefined User ID: 1“. I have no clue what Im doing wrong.

### 📝 Error Message(s) or Log

Website: bean.validate is not a function
Console: [MONITOR] ERROR: Error adding Monitor: undefined User ID: 1

### 🐻 Uptime-Kuma Version

Latest

### 💻 Operating System and Arch

22.04

### 🌐 Browser

Latest Safari

### 🐋 Docker Version

24.0.7

### 🟩 NodeJS Version

20.8.0

**Comment by chakflying** [comment]
"Latest" is not a version number. Please provide the actual version number. Also, what steps did you follow to install the application?

**Comment by Strongboost** [comment]
17.2 and I installed a nginx server, downloaded the installer and installed it. Until the everything worked perfectly. But if I try to create a monitor the error appears. 

I rented a vps and I dont have to problem anymore, looks like a pterodactyl error to me (ptero isnt made for webserver so its prob. My fault)

**Comment by CommanderStorm** [comment]
> 17.2

We released no such version.

> downloaded the installer and installed it

It is also not clear what you mean by installer. I would not consider any of our options a installer:
https://github.com/louislam/uptime-kuma/wiki/%F0%9F%94%A7-How-to-Install
