### ISSUE TITLE
Expect to reduce the size of the Docker image.

### ISSUE THREAD

**Issue by CaoMeiYouRen** [louislam/uptime-kuma#4272]
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

Other

### 🔖 Feature description

Expect to reduce the size of the Docker image.

### ✔️ Solution

Use dependency analysis tools like "@vercel/nft" to ensure that only the necessary dependencies are retained and unnecessary dependencies are removed, thereby reducing the size of the Docker image.
Based on personal testing, the size can be reduced from the current 300+MB to 100+MB before compression, resulting in a reduction of approximately 200MB. The compressed size is expected to be around 50MB, which is half the size of the current Alpine-based image.
While the significant reduction in the size of the Docker image is appealing, removing unnecessary dependencies may introduce certain risks. Therefore, thorough testing and gathering feedback from users are necessary to ensure stability before implementation.
The purpose of proposing this feature is to encourage maintainers to include reducing the size of the Docker image in future plans. It may not be feasible to make immediate changes, but I hope to see optimizations in this area in the future.

### 📝 Additional Context

refer to [minify-docker.js](https://github.com/DIYgod/RSSHub/blob/master/scripts/docker/minify-docker.js)

```dockerfile
# minify
FROM base as docker-minifier

WORKDIR /app

RUN npm add @vercel/nft@0.24.4 fs-extra@11.2.0 --save-prod

COPY --from=builder /app /app
COPY ./scripts/minify-docker.js /app/scripts/

RUN export PROJECT_ROOT=/app/ && \
    node /app/scripts/minify-docker.js && \
    rm -rf /app/node_modules /app/scripts && \
    mv /app/app-minimal/node_modules /app/ && \
    rm -rf /app/app-minimal
```

**Comment by CommanderStorm** [comment]
If you have any concrete suggestions on how our binary size can be reduced, a PR is appreciated.
The Dockerfile for v2 can be found at https://github.com/louislam/uptime-kuma/blob/master/docker/dockerfile

Note that if you require a slimmer variant, there will be the `2-slim-rootless` and `2-slim` tag available which does not include some heavy dependencies like mariadb.

**Comment by louislam** [comment]
Not worth to add in the current stage, because there are a lot of notifications cannot be tested by myself, especially for those notifications from China or other specific countries. Also we are not fully understand how node_modules works. Saving this 200 MB is too risky.

And I actually tried to use `vercel/pkg` to make a single binary before but failed. I believe `pkg` was doing similar things to shrink down the node_modules into a single file.

**Comment by CaoMeiYouRen** [comment]
> Not worth to add in the current stage, because there are a lot of notifications cannot be tested by myself, especially for those notifications from China or other specific countries. Also we are not fully understand how node_modules works. Saving this 200 MB is too risky.
> 
> And I actually tried to use `vercel/pkg` to make a single binary before but failed. I believe `pkg` was doing similar things to shrink down the node_modules into a single file.

I fully understand your concerns, so I just hope to see improvements in this area in the future. 

In practical use, `@vercel/nft` may have missing dependency issues because it is necessary to ensure that all dependencies are analyzed, and dynamically imported dependencies cannot be analyzed. 

I noticed that you mentioned `vercel/pkg`, but what I want to say is [@vercel/nft](https://github.com/vercel/nft), which are two separate projects.

**Comment by CommanderStorm** [comment]
> dynamically imported dependencies cannot be analyzed

Depending on how smart this is, we will have serious problems, as we sometimes have conditional imports node-version.

I am going to close this as not planned (due to likely not working).
If you try it (and it works on a wide variety of our monitors), we would consider a PR (mergable at a later date once the monitors have good test coverage).
