### ISSUE TITLE
Monitor vps storage

### ISSUE THREAD

**Issue by RuanMD** [louislam/uptime-kuma#4273]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

How to monitor vps storage

### 🐻 Uptime-Kuma Version

1.23.10

### 💻 Operating System and Arch

ubunto 20.04

### 🌐 Browser

vivaldi

### 🐋 Docker Version

docker

**Comment by CommanderStorm** [comment]
You likely are refering to #819
=> currently this is not a feature we directly support, but you can use the ping montor with a script [like this](https://github.com/louislam/uptime-kuma/issues/819#issuecomment-1362698405) to get the same effect
