### ISSUE TITLE
View monitor id

### ISSUE THREAD

**Issue by RafaelSavoy** [louislam/uptime-kuma#4274]
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

API, UI Feature, Other

### 🔖 Feature description

I'm using an uptime-kuma-api made with websocket, as there isn't an "official" one yet. The problem is that I need to get the monitor's id to be able to get its result, and so far I haven't found any place in the interface where I could get this id. This would certainly be easy for me, but making a request for all monitors to find the ID would be bad for my client.

### ✔️ Solution

I propose put a id in monitor infos

![2023-12-23_14-52](https://github.com/louislam/uptime-kuma/assets/89671665/542fe111-1b03-449a-bc1b-a96ec49646a9)

**Comment by CommanderStorm** [comment]
The ID can be found in the url.
![image](https://github.com/louislam/uptime-kuma/assets/26258709/b77a2500-0989-4f11-9b7f-2aa8f077a263)

Related previous issue https://github.com/louislam/uptime-kuma/issues/2104

**Comment by CommanderStorm** [comment]
> I could make the pull request

Here is our contribution guide: https://github.com/louislam/uptime-kuma/blob/master/CONTRIBUTING.md

Note that looking like the rest of the UI is a hard requirement for us. I don't think adding it to the link column is a good idea.
I would suggest instead a smaller, less dark `#ID` appropriate spacing after/before the title.

**Comment by RafaelSavoy** [comment]
Ok, thanks for idea, i will make the pull requests

**Comment by CommanderStorm** [comment]
Reopening as FR is not completed

**Comment by RafaelSavoy** [comment]
I finally had time to do this, what did you think?

![](https://i.imgur.com/gPyOb6z.png)

**Comment by RafaelSavoy** [comment]
Now that I realized that the pull request has already been made

**Comment by CommanderStorm** [comment]
> what did you think

I think making this smaller and gray as proposed by @chakflying looks more in line with our current design language
