### ISSUE TITLE
Group Monitor shows 0% - 1/4 are offline

### ISSUE THREAD

**Issue by Thrandu** [louislam/uptime-kuma#4275]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### Description

Build a simple Monitoring Group and have some child Objects with "Ping" shows 0% instead of maybe 65% if 1 Object is down.

### 👟 Reproduction steps

Build Monitoring Group: Server-Connection
Ping Checks:
-> Ping Server1
-> Ping Server2
-> Ping Server3
-> Ping Server4

### 👀 Expected behavior

If i add 4 Objects and 1 down, i expected ~65%

### 😓 Actual Behavior

Inactive - 0% "Child inaccessible" 

### 🐻 Uptime-Kuma Version

1.23.10

### 💻 Operating System and Arch

Ubuntu 22.04

### 🌐 Browser

Google Chrome 120.0.6099.129

**Comment by chakflying** [comment]
Duplicate of #3387
