### ISSUE TITLE
How can I check whether an exe program running  ?

### ISSUE THREAD

**Issue by volkankoc** [louislam/uptime-kuma#4276]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

How can I check whether an exe program running on a Windows server is running or not with uptime-kuma?

### 🐻 Uptime-Kuma Version

1.23

### 💻 Operating System and Arch

Windows Server

### 🌐 Browser

Chrome

**Comment by CommanderStorm** [comment]
Currently, this is only possible via the push monitor.
Said monitor works by you sending heartbeats to a specified adress if the monitor should be up.

Extensions to our current functionality which are similar are tracked here:
- exec/shell monitor: #1117 
- `systemd`: https://github.com/louislam/uptime-kuma/issues/1677
