### ISSUE TITLE
Recurrent Push or Recurrent Monitor Strategy

### ISSUE THREAD

**Issue by eitchtee** [louislam/uptime-kuma#4279]
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

New Monitor, UI Feature

### 🔖 Feature description

I have a few automation scripts that aren't always running, i.e. they run at specific times, finish and move on to the next execution that could be daily, weekly, every x days and so on, meaning that a normal heartbeat monitor won't fit this type of execution.

So I'd like to propose a new monitor (or a new monitor strategy) that allows for recurrent checks given a cron expression (and a delay) or a more specific configuration using daily, weekly and monthly configurations (see _Additional Context_ for examples already on Kuma)

### ✔️ Solution

A Recurrent Push monitor, with configurable recurrence for each check.

For example, if the user has a script that runs every Monday and Friday at 1pm, it would be possible to configure a monitor that only checks for a push at these specific times, notifying any possible failure to execute.

In my mind this could take the form of a cron(-like) expression, since something similar is already implemented for maintenance mode, for the given example, something like `0 13 * * MON,FRI` would properly configure the needed monitor.

Also, a `delay` or `time-window` parameter, in seconds, would be greatly appreciated, e.g. expect a push from 1pm to 1pm + the configured delay, allowing for some margin of error for more erratic functions.

Other configurations like new tries and timeout would be kept the same.

### ❓ Alternatives

A very long heartbeat _could_ work, but it's very error prone, since the user has to calculate perfectly how many seconds between each execution without any control of when the check starts or ends, and considering Uptime-Kuma has a limit of 2073600 seconds, or 24 days, on a heartbeat, it leaves a lot of possible recurrences out of the equation.

### 📝 Additional Context

While this is a proposal for a Recurrent **Push**, as it servers my needs, perhaps, if given interest it could be extended for other/all monitors, this would give a lot of flexibility, maybe the user wants to check a website only on rush hour, or monitor a docker container that runs only on specific times (this can happen with containers for build tooling for example), and anything else imagination allows.

---

The current maintenance configuration is already a perfect example of how this could be implemented, via cron or some recurrence-specific configuration (daily, weekly and monthly)

![image](https://github.com/louislam/uptime-kuma/assets/10510126/146fdbfa-4294-4395-8344-91eb285ab6c7)
-
![image](https://github.com/louislam/uptime-kuma/assets/10510126/26e1cbad-e211-455a-a157-fe16ff45b17b)
-
![image](https://github.com/louislam/uptime-kuma/assets/10510126/fdd07d8b-eabe-4f72-8f53-7dc705cde774)
-
![image](https://github.com/louislam/uptime-kuma/assets/10510126/8b96bef7-24b0-42aa-ab98-6583671915cd)

_Sorry for the screenshots in pt_BR_

**Comment by eitchtee** [comment]
Complete brain-fart on my side. This is already possible with maintenance mode

**Comment by CommanderStorm** [comment]
@eitchtee 
See #3447 => we are working on a more elegant solution to this, but this won't be in the v2.0 release ^^
