### ISSUE TITLE
scheduled monitor pause

### ISSUE THREAD

**Issue by scottini** [louislam/uptime-kuma#4280]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

Hello,

is there a way to schedule a pause for a monitor for a chosen period of time?

My use case is that every day, some of my monitored objects reboot to install updates and for "refreshing" purpose, and are therefore unreachable for 5 to 20 minutes depending on reason of reboot. Everyone of these objects has its own reboot schedule, different from one another. My Uptime Kuma instance correctly detects the situation, but I need to compare the scheduled reboots with the detected monitors downs, to extract the true problematic situations...

### 🐻 Uptime-Kuma Version

1.23.10

### 💻 Operating System and Arch

Debian on Docker

### 🌐 Browser

Firefox 121.0

### 🐋 Docker Version

24.0.7

**Comment by CommanderStorm** [comment]
Depending on your usecase (only difference is accounting wise), this is likely already possible using the cron-maintenance mode.

See these issues for further details on this feature:
- scheduled pausing #4246
- cron based monitoring #3447
