### ISSUE TITLE
Getting Authentik to work with oauth2: client credentials

### ISSUE THREAD

**Issue by modem7** [louislam/uptime-kuma#4282]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

Currently getting the error:
```
The oauth config is invalid. invalid_grant (The provided authorization grant or refresh token is invalid, expired, revoked, does not match the redirection URI used in the authorization request, or was issued to another client)
```

<details><summary>configuration</summary>
<p>

![image](https://github.com/louislam/uptime-kuma/assets/4349962/2775cef4-14a5-48cb-8ae5-bc26bd67b14c)

```json
{
  "issuer": "https://authentik.mydomain.com/application/o/uptimekuma/",
  "authorization_endpoint": "https://authentik.mydomain.com/application/o/authorize/",
  "token_endpoint": "https://authentik.mydomain.com/application/o/token/",
  "userinfo_endpoint": "https://authentik.mydomain.com/application/o/userinfo/",
  "end_session_endpoint": "https://authentik.mydomain.com/application/o/uptimekuma/end-session/",
  "introspection_endpoint": "https://authentik.mydomain.com/application/o/introspect/",
  "revocation_endpoint": "https://authentik.mydomain.com/application/o/revoke/",
  "device_authorization_endpoint": "https://authentik.mydomain.com/application/o/device/",
  "response_types_supported": [
    "code",
    "id_token",
    "id_token token",
    "code token",
    "code id_token",
    "code id_token token"
  ],
  "response_modes_supported": [
    "query",
    "fragment",
    "form_post"
  ],
  "jwks_uri": "https://authentik.mydomain.com/application/o/uptimekuma/jwks/",
  "grant_types_supported": [
    "authorization_code",
    "refresh_token",
    "implicit",
    "client_credentials",
    "password",
    "urn:ietf:params:oauth:grant-type:device_code"
  ],
  "id_token_signing_alg_values_supported": [
    "RS256"
  ],
  "subject_types_supported": [
    "public"
  ],
  "token_endpoint_auth_methods_supported": [
    "client_secret_post",
    "client_secret_basic"
  ],
  "acr_values_supported": [
    "goauthentik.io/providers/oauth2/default"
  ],
  "scopes_supported": [
    "profile",
    "email",
    "openid"
  ],
  "request_parameter_supported": false,
  "claims_supported": [
    "sub",
    "iss",
    "aud",
    "exp",
    "iat",
    "auth_time",
    "acr",
    "amr",
    "nonce",
    "email",
    "email_verified",
    "name",
    "given_name",
    "preferred_username",
    "nickname",
    "groups"
  ],
  "claims_parameter_supported": false,
  "code_challenge_methods_supported": [
    "plain",
    "S256"
  ]
}
```

</p>
</details> 

### 📝 Error Message(s) or Log

The oauth config is invalid. invalid_grant (The provided authorization grant or refresh token is invalid, expired, revoked, does not match the redirection URI used in the authorization request, or was issued to another client

<details><summary><code>error.log</code></summary>
<p>

```console
auth_via=oauth_client_secret
event=/application/o/token/host=authentik.mydomain.com
level=info
logger=authentik.asgi
method=POST
pid=36214
remote=xxx.xxx.xxx.xxx
request_id=762d425b9c464b9ebf21b45241f65991
runtime=24
scheme=https
status=400
timestamp=2023-12-26T16:18:33.725261
user=user_agent=openid-client/5.6.1 (https://github.com/panva/node-openid-client)
add auth_via=oauth_client_secret
add event=/application/o/token/
add host=authentik.mydomain.com
add level=info
add logger=authentik.asgi
add method=POST
add pid=36214
add remote=xxx.xxx.xxx.xxx
add request_id=762d425b9c464b9ebf21b45241f65991
add runtime=24
add scheme=https
add status=400
add timestamp=2023-12-26T16:18:33.725261
add user=
add user_agent=openid-client/5.6.1 (https://github.com/panva/node-openid-client)
```

</p>
</details> 

### 🐻 Uptime-Kuma Version

1.23.10

### 💻 Operating System and Arch

Ubuntu 22.04 Docker 

### 🌐 Browser

Chrome

### 🐋 Docker Version

24.0.7

**Comment by modem7** [comment]
If I do:

`bash
curl --request POST \
  --url 'https://authentik.modem7.com/application/o/token/' \
  --header 'content-type: application/x-www-form-urlencoded' \
  --data grant_type=client_credentials \
  --data 'client_id=gWi2xdQUT5oxClSWGVZhhDIc5LvPCaNqG1uMQfVR' \
  --data 'username=UptimeKuma' \
  --data 'password=reallylongpassword'
```

I get a token that when decoded is:

```json
{
  "iss": "https://authentik.mydomain.com/application/o/uptimekuma/",
  "sub": "980c16b36164fc6a0c80287963f6bec4747b6e9c2e48a275501c20db582c1abe",
  "aud": "gWi2xdQUT5oxClSWGVZhhDIc5LvPCaNqG1uMQfVR",
  "exp": 1703610208,
  "iat": 1703609608,
  "auth_time": 1703609608,
  "acr": "goauthentik.io/providers/oauth2/default",
  "azp": "gWi2xdQUT5oxClSWGVZhhDIc5LvPCaNqG1uMQfVR",
  "uid": "KsRWZopx8tpU8jBEQDvWVEq75LJ1R4AawmKyBzzq"
}
```

**Comment by chakflying** [comment]
Have you tried changing "Authentication Method" from `Authorization Header` to `Form Data Body`?

**Comment by modem7** [comment]
Heya, Yupper! No change!

**Comment by chakflying** [comment]
I think as mentioned by @hegerdes, different providers have different implementations of OAuth and it's difficult to accomodate them all. In this case, according to [Authentik's docs](https://goauthentik.io/docs/providers/oauth2/client_credentials) they seem to mix together the use of `password` and `client_credentials` grant types.

**Comment by hegerdes** [comment]
@modem7 have you tried getting a token when using Postman's oauth functionally? I doubt that Postman supports this out of the box but I'm carious. 

Regarding Authentik: That is some weird interpretation of doing oauth. They are using `username` &`password` for authentication and not `client_id` &  `client_secret` like almost every other. If there need to be some extra info in the token request there is the `scope` parameter.  They are handling the `client_credentials` grand  like the `password` grand. But the `password` grand is lagacy and [should not be used](https://www.oauth.com/oauth2-servers/access-tokens/password-grant/).

Currently uptime-kuma does not support  `username` &`password` in oauth client_credentials grant and to be honest I would't  invest time to do. It would open the door to many other non standard ways of doing oauth - _Note:_ just my personal opinion.

**Comment by CommanderStorm** [comment]
> Currently uptime-kuma does not support `username` & `password` in oauth client_credentials grant and to be honest I would't invest time to do

Fully agree with this statement => closing as not planned.
@modem7 please open a ticket with Authentik to support the oauth standard (refering to this issue)

https://github.com/goauthentik/authentik/issues/6139 is the the correct issue, but their automation has close this issue.
@BeryJu could you re-open it?

**Comment by modem7** [comment]
> > Currently uptime-kuma does not support `username` & `password` in oauth client_credentials grant and to be honest I would't invest time to do
> 
> Fully agree with this statement => closing as not planned.
> @modem7 please open a ticket with Authentik to support the oauth standard (refering to this issue)
> 
> https://github.com/goauthentik/authentik/issues/6139 is the the correct issue, but their automation has close this issue.
> @BeryJu could you re-open it?

Cheers guys! I'm glad it wasn't me being a muppet.

I'll keep an eye on the ticket at the authentik side/create a new one if it can't/won't be reopened after Xmas, and attempt the workaround listed on it. 

Cheers!
