### ISSUE TITLE
Can the alarm content be customized？

### ISSUE THREAD

**Issue by zz950115** [louislam/uptime-kuma#4287]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

Can the alarm content be customized？

### 🐻 Uptime-Kuma Version

1.23.10

### 💻 Operating System and Arch

Centos 7

### 🌐 Browser

Edge

**Comment by chakflying** [comment]
What notification provider are you using?

**Comment by CommanderStorm** [comment]
Templating for most notfication providers has not been implemented.
See https://github.com/louislam/uptime-kuma/issues/646

The webhook and smtp notifications are support templating.

**Comment by zz950115** [comment]
> 您使用的是哪个通知提供程序？

feishu
