### ISSUE TITLE
UX: change 'Delete' button to grey instead of red

### ISSUE THREAD

**Issue by abctaylor** [louislam/uptime-kuma#4290]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### Description

Hi - on a healthy setup, you'd want to see all green/neutral colours on your screen. The 'delete' button remains red. To demonstrate, consider this perspective. The red grabs your attention for no real reason. I'd suggest it be changed to grey.

<img width="1280" alt="2023-12-27 15_33_51-Uptime Kuma" src="https://github.com/louislam/uptime-kuma/assets/30197206/364136c5-a089-4047-99aa-6077783e7bde">

### 👟 Reproduction steps

N/A

### 👀 Expected behavior

Grey button to look better

### 😓 Actual Behavior

Red button...

### 🐻 Uptime-Kuma Version

1.23.10

### 💻 Operating System and Arch

Almalinux kernel 6.6.8

### 🌐 Browser

Chrome

### 🐋 Docker Version

Kubernetes

**Comment by iamabhshk** [comment]
Is this issue resolved? If not can I take this up?

**Comment by chakflying** [comment]
I don't think the proposed solution is a good idea, since it should still be red to signify a "danger action". But maybe we can think about hiding it in an overflow menu.

**Comment by abctaylor** [comment]
That's why there is a modal that asks you to confirm to proceed. It's a good idea to keep that button red but I'd still be in favour of making this delete button grey, or if people have very strong views on red, maybe a red trash icon and a grey background to make it less intrusive.

Andrew

Sent from a mobile device

On 2 Jan 2024, at 11:58, Nelson Chan ***@***.***> wrote:

﻿

I don't think the proposed solution is a good idea, since it should still be red to signify a "danger action". But maybe we can think about hiding it in an overflow menu.

**Comment by CommanderStorm** [comment]
my design textbook has this to say about this topic:
![image](https://github.com/louislam/uptime-kuma/assets/26258709/cfef2d93-c1e4-469f-845e-ec8aa530cf5e)

**Comment by iamabhshk** [comment]
#4307

**Comment by CommanderStorm** [comment]
Resolved by #4307

@iamabhshk FYI: next time please add `Resolves #4290` to your PRs => said issue will get closed automatically ^^

**Comment by iamabhshk** [comment]
Sure, thanks
