### ISSUE TITLE
Cannot Connect to Custom Docker Network

### ISSUE THREAD

**Issue by smorgan134** [louislam/uptime-kuma#4291]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

I'm trying to connect my uptime-kuma instance to a custom ipvlan docker network, and it fails every time.  Here is my docker compose code...

<details><summary><code>docker-compose.yaml</code></summary>
<p>

```yaml
version: '3.3'

services:
  uptime-kuma:
    image: louislam/uptime-kuma:latest
    volumes:
      - "/home/mvadmin/utkuma/uptime-kuma-data:/app/data"
    networks:
      mvdocknet:
        ipv4_address: 172.16.10.7
    dns:
      - "172.16.10.2"
      - "172.16.10.3"
    restart: always

networks:
  mvdocknet:
    external: true
```

</p>
</details> 

Is it possible to even do this, or does uptime-kuma have to run on its own default network?

### 📝 Error Message(s) or Log

Here is the error I receive from Portainer when I attempt to deploy the stack...

<details><summary><code>error.log</code></summary>
<p>

```raw
failed to deploy a stack:
Container uptime-kuma-uptime-kuma-1
Creating Container uptime-kuma-uptime-kuma-1
Created Container uptime-kuma-uptime-kuma-1
Starting Error response from daemon:
failed to create task for container:
failed to create shim task:
OCI runtime create failed: runc create failed:
unable to start container process:
error during container init:
error running hook #0:
error running hook:
exit status 1, stdout, stderr:
failed to add interface veth2c782ea to sandbox:
error setting interface "veth2c782ea" IP to 172.16.10.7/24:
address already in use: unknown
```

</p>
</details> 

### 🐻 Uptime-Kuma Version

Latest

### 💻 Operating System and Arch

Ubuntu running Docker and Portainer

### 🌐 Browser

Brave

### 🐋 Docker Version

Docker 24.0.5

### 🟩 NodeJS Version

NA

**Comment by CommanderStorm** [comment]
According to the log, you are trying to assign an already used address to another container/...
Please try chaning the ip adress to one not in use.

**Comment by smorgan134** [comment]
I was able to get it to work using the next available address. I’m not sure why that address isn’t available. I don’t have any containers assigned to it.
