### ISSUE TITLE
Monitor Group hierarchy not retained after restoring backup

### ISSUE THREAD

**Issue by asif-pspc** [louislam/uptime-kuma#4295]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### Description

After taking a backup and restoring on a new instance, the monitors are created on the new instance with the restore process. However, the monitors are not assigned to the monitor groups. The monitor groups are created, however, they are all empty and all monitors are at the same level with no parent / child relationship. 

### 👟 Reproduction steps

Server 1:
Create monitor group
Create monitor and assign to monitor group
Perform backup 

Server 2:
Restore backup using json on new server

All monitors and monitor groups are imported, however, when editing the monitor, the monitor group is set to none and no parent/child relationships are reflected in the dashboard.

The json file does not contain a MonitorGroup field 

### 👀 Expected behavior

On the restored instance expect to see the parent / child relationship.  The monitor should be assigned to a monitor group as is defined in the instance where the backup was performed.

### 😓 Actual Behavior

All monitors and monitor groups are imported, however, the monitors are not assigned to any monitor groups.

### 🐻 Uptime-Kuma Version

1.23.9

### 💻 Operating System and Arch

RHEL 8.9 x86-64

### 🌐 Browser

Microsoft Edge Version 120.0.2210.91 (Official build) (64-bit)

**Comment by louislam** [comment]
#4177

**Comment by CommanderStorm** [comment]
@asif-pspc We have dropped said feture in `v2.0`
