### ISSUE TITLE
Trusted Proxies

### ISSUE THREAD

**Issue by jarqvi** [louislam/uptime-kuma#4298]
### ⚠️ Please verify that this bug has NOT been raised before.

- [ ] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

I deployed uptime-kuma using the image below:
https://hub.docker.com/r/louislam/uptime-kuma
but since my app is behind a reverse proxy, it doesn't show real IPs in the logs. How do I fix this? And that I don't have access to the reverse proxy configuration file.

### 🐻 Uptime-Kuma Version

1

### 💻 Operating System and Arch

22.04

### 🌐 Browser

Google

**Comment by CommanderStorm** [comment]
We support both the `x-forwarded-for` and the `x-real-ip` headers for this. (for the difference see #2175)
Please include them in the reverse proxy configuration.
If this is not provided to Uptime Kuma, we cannot use it.
=> contact whoever is maintaining the reverse proxy to include this header.

note that you need to enable this setting:
![image](https://github.com/louislam/uptime-kuma/assets/26258709/d4adc3cd-5c86-4c6d-97ef-9482cd55e839)
