### ISSUE TITLE
show intervals in human readable form

### ISSUE THREAD

**Issue by tomaszduda23** [louislam/uptime-kuma#4299]
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

UI Feature

### 🔖 Feature description

Display intervals in more clear form.

### ✔️ Solution

as-it: Heartbeat Interval (Check every 100800 seconds)
to-be: Heartbeat Interval (Check every 1 day, 4 hours)

**Comment by CommanderStorm** [comment]
Duplicate of #3601
