### ISSUE TITLE
Authelia with Uptime-Kuma

### ISSUE THREAD

**Issue by XHyperDEVX** [louislam/uptime-kuma#4301]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

I would like to install Authelia on my system. However, I am worried that this could affect the uptime of Kuma. So far I have protected some services with simple HTTP Auth. But this is too "insecure" and unwieldy [and ugly] for me. I think Authelia is the perfect solution. However, in Uptime Kuma you have the option of entering HTTP Auth data, which I have done in my current setup. However, with Authelia it is no longer HTTP Auth but the Authelia UI. Is there a way to let Uptime-Kuma enter the login data there?

Possibly with these options? [And if not, what are these options for anyway?]
![image](https://github.com/louislam/uptime-kuma/assets/68189420/1ce67273-a453-4b08-9580-72a2cb964feb)

### 🐻 Uptime-Kuma Version

newest stable Docker Image

### 💻 Operating System and Arch

Docker

### 🌐 Browser

Edge

### 🐋 Docker Version

Newest Docker Version

**Comment by madereddy** [comment]
I had the same problem with Authelia and protecting backend resources. The best way I found to was implement a Bypass in Authelia to allow checking certain urls like below. This allows the full website to be protected and makes sure that UptimeKuma can still monitor it properly.

```
    - domain: '*.madereddy.com'
      policy: bypass
      resources:
        - '^/icons/vtt.png'
        - '^/api/status'
        - '^/favicon.ico'
```
