### ISSUE TITLE
Self-Signed Certificate Trust?

### ISSUE THREAD

**Issue by nicedevil007** [louislam/uptime-kuma#4302]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

I have local CA that is responsible for my local certificates. I do tests again local domains that are using my local certs. I already trust my local CA on the linux machine I'm running Uptime-Kuma on (debian).
I already tried adding the option for my CA trust inside the systemd file.

Selfsigned Certificates in Chain is still there :/

```bash
[Unit]
Description=Uptime-Kuma - A free and open source uptime monitoring solution
Documentation=https://github.com/louislam/uptime-kuma
After=network.target

[Service]
Type=simple
Restart=on-failure
User=root
WorkingDirectory=/opt/uptime-kuma
ExecStart=/usr/bin/npm run start-server --ssl-cert=/usr/local/share/ca-certificates/mylocalCA.crt

[Install]
WantedBy=multi-user.target
```

### 📝 Error Message(s) or Log

[DOWN] self signed certificate in certificate chain

### 🐻 Uptime-Kuma Version

1.23.11

### 💻 Operating System and Arch

Debian 12

### 🌐 Browser

Brave

### 🐋 Docker Version

no docker, Debian installation inside a LXC

### 🟩 NodeJS Version

16.20.2

**Comment by nicedevil007** [comment]
Question is on how to setup this env variable with the systemd service => like it was done here in docker environment
https://github.com/louislam/uptime-kuma/issues/3506#issuecomment-1714933483

**Comment by chakflying** [comment]
The systemd config file allows you to set environment variables by adding `Environment=""`. ([Stack Exchange post](https://serverfault.com/questions/413397/how-to-set-environment-variable-in-systemd-service))

**Comment by nicedevil007** [comment]
> The systemd service config file allows you to set environment variables by adding `Environment=""`. ([Stack Exchange post](https://serverfault.com/questions/413397/how-to-set-environment-variable-in-systemd-service))

You are the man! Thank you very much, did the trick :)
And just in case someone else is looking for this, here the complete systemd service file.
Dont forget to do `systemd daemon-reload` after changing anything to the file.

[Unit]
Description=Uptime-Kuma - A free and open source uptime monitoring solution
Documentation=https://github.com/louislam/uptime-kuma
After=network.target

[Service]
Type=simple
Restart=on-failure
User=root
Environment="NODE_EXTRA_CA_CERTS=/usr/local/share/ca-certificates/myCAcertfile.crt"
WorkingDirectory=/opt/uptime-kuma
ExecStart=/usr/bin/npm run start-server                                                                      

[Install]
WantedBy=multi-user.target
