### ISSUE TITLE
Documentation Integration

### ISSUE THREAD

**Issue by extrafein** [louislam/uptime-kuma#4305]
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

UI Feature

### 🔖 Feature description

As a Administrator I want the possibility to get - in case of an incident - as fast es possible to the corresponding documentation, to reduce downtime as much as possible

### ✔️ Solution

In my use case a notes-section inside each monitor would be more than helpfull. This section should interpret markdown-code to enable deeper integration via hyperlinks.

### ❓ Alternatives

Add some text into the description of the monitor.
But:
- The idea of this fiel is to descripe the service and its intention in 1-2 sentences
- No Markdown / hyperlinks possible

### 📝 Additional Context

# EXAMPLE
## Typical issues and solutions
- **This is the issue**: [Typical soultion](#)
## Main Dokumentation
- [Configuration](#)

**Comment by CommanderStorm** [comment]
I think this should be is a part of #646 => closing as a duplicate

Related #3008
