### ISSUE TITLE
Ability to control the UID and GID of container user

### ISSUE THREAD

**Issue by kn100** [louislam/uptime-kuma#4310]
# Feature request

Some of us like to run our containers so that the user inside the container uses a UID and GID of a user on the host. To give a specific example:

On the host:
```
ls -alth
drwxr-xr-x 11 someuser somegroup 11 Jan  3 00:16 somedir
```

And then in the docker-compose file, you'd specify a UID and GID pair, for example on the LinuxServer images you specify it as environment variables (see PUID and PGID in this example repo: https://hub.docker.com/r/linuxserver/jellyfin).

This then has the effect of the user that does r/w operations to the mounted dirs starting with a specific UID and GID, which then match a UID and GID on the host, and therefore has the same level of access as the user on the host.

You can of course specify that the container itself runs as a specific user, but it seems that Uptime Kuma creates a user called Node, and there's no control that I can see that allows you to control its UID/GID.

It would be really nice if the container allowed for that!

### 📝 Additional Context

I'd be happy to take a look at implementing this for you, assuming you're interested :) Thank you for your time.

**Comment by kn100** [comment]
Upon some further reading, I have just discovered your rootless images. This might make this a non issue for me - but this might be worth looking into either way. The LSIO images are probably a great example to work from.

**Comment by CommanderStorm** [comment]
See https://github.com/louislam/uptime-kuma/wiki/Environment-Variables#docker-specific-environment-variables

**Comment by kn100** [comment]
@CommanderStorm does your docker entrypoint actually do anything with those env vars? I can't test this myself right now but these env vars do nothing except for exist in your container - where you can then use them however you'd wish. Docker doesn't afaik do anything with them by default.

**Comment by kn100** [comment]
As an example, in the LSIO images, they all use a base image that has the following script being executed during its build:
https://github.com/linuxserver/docker-baseimage-ubuntu/blob/jammy/root/etc/s6-overlay/s6-rc.d/init-adduser/run - in there you can see the PGID and PUID being used to create a user within the container. I could just be being blind, but I do not see anything similar for Uptime Kumas Docker image.
