### ISSUE TITLE
Why not show docker-compose.yml in wiki, I see this file exit in previous git version

### ISSUE THREAD

**Issue by mobeicanyue** [louislam/uptime-kuma#4311]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

https://github.com/louislam/uptime-kuma/blob/d286c534bd0d3cf07135d82b227e223ccc777eea/docker/docker-compose.yml

Why not show docker-compose.yml in wiki, I noticed that this file existed in a previous version of git.

I think it's more convenient to run docker server with `docker-compose up -d`

rather than `docker run -d --restart=always -p 3001:3001 -v uptime-kuma:/app/data --name uptime-kuma louislam/uptime-kuma:1`

### 🐻 Uptime-Kuma Version

1.23.11

### 💻 Operating System and Arch

Debian

### 🌐 Browser

Edge 120

**Comment by chakflying** [comment]
Please reference #4289. The file has been moved, but the wiki has not been updated yet.

**Comment by mobeicanyue** [comment]
Ok, thanks.

**Comment by mobeicanyue** [comment]
I aware that the new compose file is
```
volumes:
      - ./data:/app/data
```
but the docker run command is
```
-v uptime-kuma:/app/data
```
It's Incompatible

**Comment by CommanderStorm** [comment]
docker compose and docker being different should not matter to you.
Please consider using one and stick with it.

We will switch the docker run command when v2 gets released as discussed in https://github.com/louislam/uptime-kuma/pull/4289#issuecomment-1870999447
