### ISSUE TITLE
JSON Queries not retained after restoring backup

### ISSUE THREAD

**Issue by tayyebi** [louislam/uptime-kuma#4314]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### Description

In Json-Query monitor types, data is not retained after importing.

### 👟 Reproduction steps

Exported data on Version: 1.23.7 (with same front-end version)
Imported data on Version: 1.23.11 (with same front-end version)

### 👀 Expected behavior

It is expected to contain "Json Query" and "Expected Value" fields field with imported data.

### 😓 Actual Behavior

Both "Json Query" and "Expected Value" are empty strings.

### 🐻 Uptime-Kuma Version

1.23.11

### 💻 Operating System and Arch

Ubuntu 22.04

### 🌐 Browser

Mozilla/5.0 (X11; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/115.0

### 🐋 Docker Version

Docker version 24.0.7, build afdd53b

**Comment by chakflying** [comment]
Ref. #4177

Backup & Restore with json has been deprecated and issues will not be fixed.
