### ISSUE TITLE
Dashboard log shows no name for deleted items.

### ISSUE THREAD

**Issue by jtagcat** [louislam/uptime-kuma#433]
![image](https://user-images.githubusercontent.com/38327267/133803649-9d071c7f-0c37-4cb0-a755-fbf25f67ddd8.png)

Deleted monitors should be handled better. Either remove them from the log completely (probably?, though audit trail?), or show them in the log.

**Comment by Ponkhy** [comment]
It already should delete every heartbeat and event of a monitor when it'll be deleted.
You can also try to clear all statistics in the settings page. Keep in mind it'll also delete them for every monitor.

**Comment by jtagcat** [comment]
I don't personally mind, it's just about the polish ✿✨

**Comment by chakflying** [comment]
It's actually a bug with the frontend not getting an updated events list after `deleteMonitor`. Currently the frontend mostly rely on the server websocket part to actively sending updates when data changes, and `sendImportantHeartbeatList` only gets triggered after login.
