### ISSUE TITLE
Does Uptime Kuma has documentation on APIs? I'd like to write my own Agent functionality.

### ISSUE THREAD

**Issue by afunworm** [louislam/uptime-kuma#4330]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

It seems like one of the most requested features here is to have an agent reporting back to the main instance of Uptime Kuma. I understand it might be a little more than what Uptime Kuma intended to be, so I'd like to attempt and make this happen. To do that though, does Uptime Kuma have any APIs for taking in inputs for reporting, adding monitors, etc.?

### 🐻 Uptime-Kuma Version

1.23.11

### 💻 Operating System and Arch

Ubuntu 22.04 x86

### 🌐 Browser

Chrome

### 🐋 Docker Version

24.0.7

### 🟩 NodeJS Version

20.10.0

**Comment by louislam** [comment]
See #118

**Comment by CommanderStorm** [comment]
I think this is more likely a duplicate of #84 

You might also be requesting how to use the push monitor. In this case, v2 will ship with better examples:
![image](https://github.com/louislam/uptime-kuma/assets/26258709/b59ff9b8-04dc-4780-8b96-8c78d0752586)
