### ISSUE TITLE
When configuring AliyunSMS notifications for a monitored item, it is not possible to send SMS through the configured Aliyun SMS template variable parameter restriction.

### ISSUE THREAD

**Issue by ste0815** [louislam/uptime-kuma#4336]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

I found that when configuring AliyunSMS notifications, the interface prompts:
The SMS template must contain the following variables:
${name} ${time} ${status} ${msg}
Learn more: https://help.aliyun.com/document_detail/101414.html
All these variables must all exist, missing one of them there is no way to configure successfully, but Aliyun has official restrictions on fields, and fields must be defined according to the notification SMS template specification.
https://help.aliyun.com/zh/sms/user-guide/notification-template-specifications
There are only a limited number of fields that can be defined, and many of them are limited to 20 characters and don't support English letters, or Chinese characters, etc. I've tried to replace several variable attributes, and ${name} ${time} ${status} seems to meet the requirements, but only ${msg} doesn't meet the requirements in any configurations.
So is it possible to make a selection of the above variables, not all of them, I only need ${name} ${time} is enough, the other I will be fixed to the character on the line, thank you very much!
Or there are other solutions，pls tell me.

### 📝 Error Message(s) or Log

Error: Error: The variable msg (AliyunSMS Notification Testing) in the template does not conform to the variable specification of [User Nickname].

### 🐻 Uptime-Kuma Version

1.23.11

### 💻 Operating System and Arch

ubuntu-20.04

### 🌐 Browser

edge

**Comment by xiaoleigithub** [comment]
模版内容：应用服务：${name}，状态发生变更：${status}，时间：${time}。
字段属性：name-用户昵称；status-用户昵称；time-时间；
这是我的短信模版配置，亲测可用。
