### ISSUE TITLE
Does the ping type host name support the cidr format?

### ISSUE THREAD

**Issue by L-69** [louislam/uptime-kuma#4338]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

Does the ping type host name support the cidr format?

### 📝 Error Message(s) or Log

Does the ping type host name support the cidr format?

### 🐻 Uptime-Kuma Version

zuixin

### 💻 Operating System and Arch

demo

### 🌐 Browser

chrom

### 🐋 Docker Version

/

### 🟩 NodeJS Version

/

**Comment by chakflying** [comment]
We don't support pinging a range of hosts, if that's what you're asking.

**Comment by L-69** [comment]
Can adding a ping host be called through the API? It does not support pinging a series of hosts. Can I create them in batches?

**Comment by CommanderStorm** [comment]
> Can adding a ping host be called through the API?

Currently, this is not possible through first party tooling.
See #118 for further details.
Current attempt at implementing this is https://github.com/louislam/uptime-kuma/pull/3854 which has been added to the [`v2.1` milestone](https://github.com/louislam/uptime-kuma/milestone/40)

In the meantime, please use third party tooling like https://uptime-kuma-api.readthedocs.io/

> Can I create them in batches?

Please refer to these Issues:
- https://github.com/louislam/uptime-kuma/issues/1323
- https://github.com/louislam/uptime-kuma/issues/455
- https://github.com/louislam/uptime-kuma/issues/1190

Our contribution guide can be found here: https://github.com/louislam/uptime-kuma/blob/master/CONTRIBUTING.md

**Comment by CommanderStorm** [comment]
For port ranges, plese refer to https://github.com/louislam/uptime-kuma/issues/497
