### ISSUE TITLE
How to add monitoring items through API

### ISSUE THREAD

**Issue by L-69** [louislam/uptime-kuma#4339]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

How to add monitoring items through API

### 📝 Error Message(s) or Log

How to add monitoring items through API

### 🐻 Uptime-Kuma Version

/

### 💻 Operating System and Arch

/

### 🌐 Browser

/

### 🐋 Docker Version

/

### 🟩 NodeJS Version

/

**Comment by CommanderStorm** [comment]
Currently, this is not possible through first party tooling.
See #118 for further details.
Current attempt at implementing this is https://github.com/louislam/uptime-kuma/pull/3854 which has been added to the [`v2.1` milestone](https://github.com/louislam/uptime-kuma/milestone/40)

In the meantime, please use third party tooling like https://uptime-kuma-api.readthedocs.io/
