### ISSUE TITLE
Iptables error during running/installing kuma via docker

### ISSUE THREAD

**Issue by cmandesign** [louislam/uptime-kuma#434]
Hey Guys, 

I've encountered the following error during installation via Docker. I appreciate your assistance in this case 👍 

**Info**
Uptime Kuma Version:  louislam/uptime-kuma:1
Using Docker?: Yes
Docker Version:  Docker version 20.10.1, build 831ebea
OS: Ubuntu 20.04

Error :

```fish
root@ubuntu:~# docker run -d --restart=always -p 3001:3001 -v uptime-kuma:/app/data --name uptime-kuma louislam/uptime-kuma:1
Unable to find image 'louislam/uptime-kuma:1' locally
1: Pulling from louislam/uptime-kuma
a330b6cecb98: Pull complete
4579d311ffe3: Pull complete
be6579e48fc9: Pull complete
3f0d83228f07: Pull complete
5ea40c9713b1: Pull complete
2c81e602d06c: Pull complete
057c331472ea: Pull complete
235cac765f5e: Pull complete
Digest: sha256:c1835aad167780777421ea1ab77d7fedab214a2ad88bd8aaf8de24fc36a972b3
Status: Downloaded newer image for louislam/uptime-kuma:1
daf36813f337f9c917fe80bdb1e3be0a1034934f7c09c4913c2938a0909ecb7c
docker: Error response from daemon: driver failed programming external connectivity on endpoint uptime-kuma (4a90fec6fec5d30e8e0f462b0420835b5bcc39877c77e37cfefcd0d9d74d3ab4):  (COMMAND_FAILED: '/usr/sbin/iptables -w10 -t filter -A DOCKER ! -i docker0 -o docker0 -p tcp -d 172.17.0.2 --dport 3001 -j ACCEPT' failed: iptables: No chain/target/match by that name.
).

```

**Comment by chakflying** [comment]
According to [this](https://stackoverflow.com/questions/31667160/running-docker-container-iptables-no-chain-target-match-by-that-name), it's most likely a misconfiguration of iptables on your host machine. Have you checked that your docker is actually functioning correctly, i.e. can port forward a simple service like a nginx server?

**Comment by gaby** [comment]
@cmandesign Restarting the docker daemon will fix that, some tool in your system is modifying iptables after Docker create it's rules. 

```
systemctl restart docker
```

**Comment by cmandesign** [comment]
Thanks @chakflying & @gaby  for the quick answers. 

It has been fixed by rebooting the machine.
