### ISSUE TITLE
How to add websites in batches?

### ISSUE THREAD

**Issue by xyzzen** [louislam/uptime-kuma#4340]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

Now I have 260 domain names to monitor, but I can't seem to add them in batches?

### 🐻 Uptime-Kuma Version

1.23.11

### 💻 Operating System and Arch

centos

### 🌐 Browser

google 120.0.6099.200

### 🐋 Docker Version

docker 18.09.0

**Comment by CommanderStorm** [comment]
Please refer to these Issues:
- https://github.com/louislam/uptime-kuma/issues/1323
- https://github.com/louislam/uptime-kuma/issues/455
- https://github.com/louislam/uptime-kuma/issues/4065

Our contribution guide can be found here: https://github.com/louislam/uptime-kuma/blob/master/CONTRIBUTING.md
