### ISSUE TITLE
Why after I insert data through the database, the UI can see the inserted data, but it seems that the ping action will not be executed and the status is unknown?

### ISSUE THREAD

**Issue by L-69** [louislam/uptime-kuma#4341]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

```sql
INSERT INTO monitor (id, name, active, user_id, interval, url, type, weight, hostname, created_date, maxretries, ignore_tls, upside_down, maxredirects, accepted_statuscodes_json, dns_resolve_type, dns_resolve_server, retry_interval, method, expiry_notification, resend_interval, packet_size, kafka_producer_brokers, kafka_producer_sasl_options, oauth_auth_method, timeout, gamedig_given_port_only, kafka_producer_ssl, kafka_producer_allow_auto_topic_creation)
VALUES (11, '124.222.195.30', 1, 1, 20, 'https://', 'ping', 2000, '124.222.195.30', '2024-01-08 02:38:47', 5, 0, 1, 10, '["200-299"]', 'A', '1.1.1.1', 20, 'GET', 0, 0, 56, '[]', '{"mechanism":"None"}', 'client_secret_basic', 4, 1, 0, 0);
```

Why after I insert data through the database, the UI can see the inserted data, but it seems that the ping action will not be executed and the status is unknown?

### 📝 Error Message(s) or Log

Why after I insert data through the database, the UI can see the inserted data, but it seems that the ping action will not be executed and the status is unknown?

### 🐻 Uptime-Kuma Version

/

### 💻 Operating System and Arch

/

### 🌐 Browser

/

### 🐋 Docker Version

/

### 🟩 NodeJS Version

/

**Comment by chakflying** [comment]
Have you tried restarting the server?

**Comment by L-69** [comment]
The service data can be refreshed after restarting the service, but the service cannot be restarted every time a monitoring item is added.
I now use the API to add it, so I don’t need to insert data into the database.

**Comment by CommanderStorm** [comment]
> The service data can be refreshed after restarting the service

Closing as resolved
