### ISSUE TITLE
mqtt timeout

### ISSUE THREAD

**Issue by baitinghollow** [louislam/uptime-kuma#4342]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

Monitoring a topic in mqtt broker, payload is 'up' or 'down'.  When topic does not match, heartbeat show all red [down][timeout}. Then when the topic matches, one heartbeat shows green [up], followed by red [down][timeout].

Expected behavior is when the topic matches, each 60sec the heartbeat should be green [up]

### 🐻 Uptime-Kuma Version

1.23.11

### 💻 Operating System and Arch

debian 12 in proxmox VE

### 🌐 Browser

chrome

**Comment by CommanderStorm** [comment]
Closing as Duplicate of #3855

Note that our contribution guide can be found here: https://github.com/louislam/uptime-kuma/blob/master/CONTRIBUTING.md
