### ISSUE TITLE
Is there only one admin user? Can't create other login users?

### ISSUE THREAD

**Issue by L-69** [louislam/uptime-kuma#4345]
### ⚠️ Please verify that this question has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

Is there only one admin user? Can't create other login users?

### 📝 Error Message(s) or Log

Is there only one admin user? Can't create other login users?

### 🐻 Uptime-Kuma Version

/

### 💻 Operating System and Arch

/

### 🌐 Browser

/

### 🐋 Docker Version

/

### 🟩 NodeJS Version

/

**Comment by CommanderStorm** [comment]
Please refer to the discussion in #128
TLDR: https://github.com/louislam/uptime-kuma/pull/3571 has been proposed and will be reviewed in an upcoming (`v2.2`) milestone

=> closing as a duplicate
