### ISSUE TITLE
Request to add the "Update Events" feature on the page to enable users to be informed about all previous update events.

### ISSUE THREAD

**Issue by chettestwef** [louislam/uptime-kuma#4346]
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

New Notification, New Monitor, UI Feature

### 🔖 Feature description

Request to add the "Update Events" feature on the page to enable users to be informed about all previous update events.

### ✔️ Solution

At the top right corner of the status monitoring page, you can see a button for viewing historical updates, or you can scroll down to see the historical update times.

### ❓ Alternatives

no

### 📝 Additional Context

https://instat.us/

**Comment by CommanderStorm** [comment]
What is a "update event" precicely?

**Comment by CommanderStorm** [comment]
Given @chettestwef did not respond what they are requesting, and I don't know what is being asked here, I am going to close this issue as `not planned`

We can reopen if this changes

**Comment by chettestwef** [comment]
> Given @chettestwef did not respond what they are requesting, and I don't know what is being asked here, I am going to close this issue as `not planned`
> 
> We can reopen if this changes

Sorry for keeping you waiting. It's a page like this: 
![image](https://github.com/louislam/uptime-kuma/assets/99162086/afae5e1e-e33e-4e10-941c-dd7e6e946aa7)

**Comment by CommanderStorm** [comment]
Improving the incident system is tracked in https://github.com/louislam/uptime-kuma/issues/579
See https://github.com/louislam/uptime-kuma/pull/1253 for a more in-depth discussion.
