### ISSUE TITLE
Add an interactive tool to ping a specific node to ping TEMPORARILLLLYYYY with increased frequency, for TESTING ONLY.

### ISSUE THREAD

**Issue by homeautomaton** [louislam/uptime-kuma#4347]
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

New Monitor, UI Feature

### 🔖 Feature description

I'm frequently copying the host/IP address from the uptime kuma UI, just to use a command-line tool to do some continuous ping testing on a problematic node.

### ✔️ Solution

Provide a button on the individual monitor page, beside the pause/edit/clone/delete options to do "continuous test".

I'd be happy with just "ping," but supporting all of the other monitor types would be a plus.

**Comment by CommanderStorm** [comment]
So you mean you want to decrease the heartbeat frequency to `20`?
Why not edit the correct field directly?

**Comment by homeautomaton** [comment]
Since this concept seems, apparently, so hard to grasp, and the notion of how a command-line ping tool might work seems so foreign, let me provide a detailed use-case.

I have more than 100 devices configured in uptime kuma, and on a good day, I don't see any outages. Some days, a given node or another might become problematic and stop responding. Say that the normal setting is to ping every 5 minutes, with 30 second retries, and report an outage after 4 failures...

Now, if I go unplug and replug a cable, do I want to wait around for 5 minutes to see if that has an effect? No.

Do I want to change up all of the parameters for the monitor, just for the diagnosis and debugging, only to have to change them back once things are back to normal? No, again.

So, presently, I resort to using the command-line ping, which defaults to 1-ping-per-second. Something we can't presently do, for good reason, with the normal settings of uptime kuma.

So, what I am asking for, and what was pretty clearly described in my original unadulterated title to this enhancement request, is a simple, separate, interactive tool, accessible from uptime kuma, to do continual, pinging, like the command-line ping tool, i.e. 1-second intervals.

Next time you think about changing the title of an enhancement request, why don't you read the Feature Description and Solution sections first?

**Comment by homeautomaton** [comment]
Since this issue was terribly tainted, degraded and defiled by someone with no understanding of network diagnostic needs changing the title and muddying the water, I am closing this and reopening a new enhancement request with the original title. Hoping nobody takes a squat on the new request.
