### ISSUE TITLE
Add a websocket that will return the contents of div.monitor-list as JSON. 

### ISSUE THREAD

**Issue by Xliff** [louislam/uptime-kuma#4348]
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

API

### 🔖 Feature description

I would like the ability to return the section contained by the $('div.monitor-list') selector as a JSON response so I can export it to another webservice.

![2024-01-09_22-37](https://github.com/louislam/uptime-kuma/assets/609986/71d84ee5-85d4-4e10-b024-993b6b435d78)

### ✔️ Solution

N/A

### 📝 Additional Context

N/A

**Comment by CommanderStorm** [comment]
See `/api/status-page/heartbeat/NAME_OF_STATUS_PAGE`

Note that the current attempt at documeting this is https://github.com/louislam/uptime-kuma/pull/3854 which has been added to the [`v2.1` milestone](https://github.com/louislam/uptime-kuma/milestone/40)
This issue is tracked in #118
