### ISSUE TITLE
HTTPS proxy "unable to verify the first certificate"

### ISSUE THREAD

**Issue by gwaydust** [louislam/uptime-kuma#4352]
### ⚠️ Please verify that this question has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

I am running uptime kuma in docker in a corporate network, we need to access internet via proxy, which I have hosted on one of my VMs. When kuma access internet via proxy, it shows the error "unable to verify the first certificate". I suppose it is talking about the SSL cert (.cer) of my proxy? Should I put the file into docker container somewhere? Do I need to set env variable like NODE_EXTRA_CA_CERTS?

### 📝 Error Message(s) or Log

[DOWN] "unable to verify the first certificate"

### 🐻 Uptime-Kuma Version

1.23.11

### 💻 Operating System and Arch

SUSE 15.2 x64

### 🌐 Browser

Firefox 121

### 🐋 Docker Version

20.10.12-ce

### 🟩 NodeJS Version

v18.19.0

**Comment by chakflying** [comment]
If your corporate proxy is doing some kind of MITM, then most likely you would need to add the certificate presented by the proxy to `NODE_EXTRA_CA_CERTS`. Note that the certificate file needs to be accessible inside the container.
