### ISSUE TITLE
Cloudflare Tunnels Reports That It's Out Of Date

### ISSUE THREAD

**Issue by RyderCragie** [louislam/uptime-kuma#4353]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### Description

Cloudflare Tunnels Reports That It's Out Of Date

### 👟 Reproduction steps

Set up the Cloudflare tunnel proxy following https://github.com/louislam/uptime-kuma/wiki/Reverse-Proxy-with-Cloudflare-Tunnel and then went to the tunnels page in one.dash.cloudflare.com

### 👀 Expected behavior

Didn't expect an error.

### 😓 Actual Behavior

Got an error.

### 🐻 Uptime-Kuma Version

1.23.11

### 💻 Operating System and Arch

Synology DSM 7.2.1-69057 Update 3

### 🌐 Browser

Google Chrome

### 🐋 Docker Version

20.10.23-1437

![image](https://github.com/louislam/uptime-kuma/assets/69316364/cfbd59aa-ecde-4d36-8fad-e50f8e622379)
![image](https://github.com/louislam/uptime-kuma/assets/69316364/5729b1aa-83cf-4311-9f61-bca4349e6b6f)

**Comment by RyderCragie** [comment]
Also, not an issue so I won't submit a report, more than likely just outdated documentation, but I couldn't use http://localhost:3444, I had to use http://192.168.0.254:3444

**Comment by chakflying** [comment]
The guide assumes that you are using the built-in cloudflared, or that you are running on the same OS environment. Unfortunately in your case, depending on the Docker networking configuration it will not be accessible on localhost.

So it's more an issue of your specific configuration.

**Comment by RyderCragie** [comment]
> The guide assumes that you are using the built-in cloudflared, or that you are running it on the same OS environment. Unfortunately in your case, depending on the Docker networking configuration it will not be accessible on localhost.
> 
> So it's more an issue of your specific configuration.

Thanks. How can I update the version?

**Comment by louislam** [comment]
Use docker compose, and don't forget to search old posts.

https://github.com/louislam/uptime-kuma/issues/3993#issuecomment-1803129833

**Comment by RyderCragie** [comment]
I'll use a normal tunnel in that case. I don't know enough.
Thanks.
