### ISSUE TITLE
Issue With Reverse Proxy

### ISSUE THREAD

**Issue by RyderCragie** [louislam/uptime-kuma#4356]
### ⚠️ Please verify that this question has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

I followed this guide to install Uptime Kuma on my Synology NAS running DSM 7.

[How to Install Uptime Kuma on Your Synology NAS – Marius Hosting](https://mariushosting.com/how-to-install-uptime-kuma-on-your-synology-nas/)

![image](https://github.com/louislam/uptime-kuma/assets/69316364/03f48fdd-d453-46f2-83b7-3555abba6600)

This is what it looks like in Container Manager:

![image](https://github.com/louislam/uptime-kuma/assets/69316364/baa5b72d-2f67-431a-8b14-74d12b45a86d)

I have a Cloudflare Tunnel in Container Manager that allows me to access the webpage of any port on my NAS publically behind a protected interface, so I used that for Uptime Kuma. Only to find out that I also need to do this to stop WebSocket errors and page reloads:

[Reverse Proxy · louislam/uptime-kuma Wiki (github.com)](https://github.com/louislam/uptime-kuma/wiki/Reverse-Proxy#synology-builtin-reverse-proxy)

So I added this into Task Scheduler and let it run:

![image](https://github.com/louislam/uptime-kuma/assets/69316364/5092fb10-d065-454b-90d0-5f5819f4b505)

To which I got:

![image](https://github.com/louislam/uptime-kuma/assets/69316364/cf16c181-7515-4cd0-8fff-0606ab3232f4)

Also noticed that the port has changed here which I suspect is normal. This means I have 2 ports I can use to access the web UI now.

![image](https://github.com/louislam/uptime-kuma/assets/69316364/b84e93f9-17e3-44f0-bc3a-92f0f7de2185)

Then I tried adding the proxy and got this:

![image](https://github.com/louislam/uptime-kuma/assets/69316364/3a09d1a5-ef19-4e39-bb58-748130ec74ba)

Both ports show as:

![image](https://github.com/louislam/uptime-kuma/assets/69316364/f13a98b4-e5f2-4ba8-a370-6f237a1f56dc)

What am I doing wrong?

### 🐻 Uptime-Kuma Version

1.23.11

### 💻 Operating System and Arch

Synology DSM 7.2.1-69057 Update 3

### 🌐 Browser

Google Chrome

### 🐋 Docker Version

20.10.23-1437

**Comment by CommanderStorm** [comment]
what are you trying to do in the reverse proxy exactly?

the source port is the port you have uptime-kuma deployed at
=> reassigning this public port is not possible.

Source is in this relationship the entrypoint, destination is where this arrow points.

**Comment by RyderCragie** [comment]
I'm doing it to stop getting WebSocket errors (as explained).
I don't know what I need to do differently to get it working. I'm following the exact same procedure.

**Comment by CommanderStorm** [comment]
that is exactly where you are not clear. what precicely should the reverse proxy do?
Did you maybe intend to have forward 3445 -> 3001? in this case the fields should be exchanged for each other

**Comment by RyderCragie** [comment]
I'm not entirely sure what it's supposed to do, per say. I just know that following those steps is supposed to stop the WebSocket errors. That's where my knowledge ends with this matter.
It's still getting on my nerves though.

**Comment by RyderCragie** [comment]
Turns out I'd managed to create another container with the new port, it wasn't just one container. Every time I run that command it just creates a new container. Not sure what's going on here.

**Comment by CommanderStorm** [comment]
I am asumging this is resolved => closing as such

> Every time I run that command it just creates a new container

The command you created contains one command for creating the docker container. Unsure what you are confused about

**Comment by RyderCragie** [comment]
Why would the creator of Uptime Kuma tell you to create a 2nd instance to set up a proxy? Seems an odd thing to do.

**Comment by CommanderStorm** [comment]
Link? You are refering to https://github.com/louislam/uptime-kuma/wiki/Reverse-Proxy#synology-builtin-reverse-proxy, correct?

I cannot reproduce us telling users to create a second instance.

**Comment by RyderCragie** [comment]
> Link? You are refering to https://github.com/louislam/uptime-kuma/wiki/Reverse-Proxy#synology-builtin-reverse-proxy, correct?
> 
> 
> 
> I cannot reproduce us telling users to create a second instance.

You just said in a previous reply that the command creates a second instance. I got the command from that guide. I can't make that clearer. You said that

**Comment by CommanderStorm** [comment]
> I got the command from that guide

That guide is written by a third party, namely @mariushosting.
@mariushosting is not the creator of Uptime Kuma.
We don't maintain how to install on synology as we don't own such a device.

**Comment by RyderCragie** [comment]
It's the command in this guide that creates a 2nd instance. Not the other one. This is from the creator, right?

https://github.com/louislam/uptime-kuma/wiki/Reverse-Proxy#synology-builtin-reverse-proxy

**Comment by CommanderStorm** [comment]
Yes this is our guide, but we never talked about said guide.
Confused what you mean with 2nd instance.

Our guide does not result in 2 instances, even if executed twice:
![image](https://github.com/louislam/uptime-kuma/assets/26258709/171da4e5-0991-48a6-bfa6-c4e016ff740a)

**Comment by RyderCragie** [comment]
I don't know what I'm doing wrong.

**Comment by CommanderStorm** [comment]
Did you maybe mix and match both
- https://mariushosting.com/how-to-install-uptime-kuma-on-your-synology-nas/
- and https://github.com/louislam/uptime-kuma/wiki/Reverse-Proxy#synology-builtin-reverse-proxy?

If combined this results in 2 containers, as they neither share a `--name` containername nor `--p` port

@mariushosting please consider using the same values as us for this.
