### ISSUE TITLE
I would like to integrate the status pages into iobroker vis

### ISSUE THREAD

**Issue by chrisdu** [louislam/uptime-kuma#4357]
### ⚠️ Please verify that this question has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

uptime kuma runs on proxmox in the container.
When I integrate uptime as an iframe in vis it appears: 10.0.0.103 has refused the connection.
Create a .env file in /opt/uptime-kuma/ root folder and then add the line below in the file:
UPTIME_KUMA_DISABLE_FRAME_SAMEORIGIN=true
I've already tried that, unfortunately without success, firewall is deactivated on proxmox.
Thanks for the help

### 📝 Error Message(s) or Log

When I integrate uptime as an iframe in vis it appears: 10.0.0.103 has refused the connection.

### 🐻 Uptime-Kuma Version

1

### 💻 Operating System and Arch

debian

### 🌐 Browser

Opera, Chrome, firfox

### 🐋 Docker Version

proxmox 

### 🟩 NodeJS Version

v20.11.0

**Comment by CommanderStorm** [comment]
How did you integrate the iframe exactly?

**Comment by chakflying** [comment]
`10.0.0.103` looks like a private address. Maybe you can first check if you can access the instance with that IP from where you opened the browser.

**Comment by chrisdu** [comment]
I used the widget in iobroker that I also use to access my videos and Fronius pages and it works there too.

I can reach the address with a ping.
This is the Fronius page:
![uptimeproblem02](https://github.com/louislam/uptime-kuma/assets/4033905/5c3688b8-2ab1-4c5d-9934-caed631751fc)
this is the uptime page:
![uptimeproblem01](https://github.com/louislam/uptime-kuma/assets/4033905/66ba65c5-72cc-43fa-9c1d-392b55f6147e)

**Comment by chakflying** [comment]
Also it is unclear if you are running uptime-kuma as a Docker container or some LXC container. If you are running it as a Docker container, it's root folder should not be in `/opt/uptime-kuma/` inside the container. I recommend you modify the container start command to add the required environment variable instead.

**Comment by chrisdu** [comment]
if I integrate uptime kuma on my iobroker test system in Proxmox as an iframe, it works... ???
![uptimeproblem04](https://github.com/louislam/uptime-kuma/assets/4033905/0b52a6a1-34b2-4ca3-87c6-1bf1b6313e49)

**Comment by CommanderStorm** [comment]
> integrate uptime kuma on my iobroker  [...] it works

I am assuming you solved the issue => closing as resolved
For future readers: how did you solve it? (what was the problem)

**Comment by chrisdu** [comment]
...sorry, but the problem is that I can get uptime to work in Testiobroker on Proxmox but not on my main system on the Raspberry. The iobroker runs on Raspian.
