### ISSUE TITLE
State validation validate echo value

### ISSUE THREAD

**Issue by sanqianyanyi** [louislam/uptime-kuma#4358]
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

New Notification

### 🔖 Feature description

Thank you very much for providing me with such a useful tool, can you add a function to validate the request return value of a web page to complete the state monitoring

### ✔️ Solution

Increase the display back to calibration

**Comment by CommanderStorm** [comment]
> function to validate the request return value of a web page to complete the state monitoring

You mean the status code?
We already have something like integrated or am I misunderstanding you?

> Increase the display back to calibration

what?

**Comment by sanqianyanyi** [comment]
No, I'm sorry I misrepresented it, it's the packet information that is returned by the checksum after requesting it

> > 函数验证网页的请求返回值，完成状态监控
> 
> 你指的是状态码吗？ 我们已经有类似集成的东西了，还是我误解了你的意思？
> 
> > 将显示调回校准值
> 
> 什么？

**Comment by CommanderStorm** [comment]
> packet information that is returned by the checksum after requesting it

What checksum?
What packet information?
What are you even requesting?
I am sorry, but I really don't understand what you are requesting...

I am going to close this because I really don't know what is being requested here.
We can reopen this.
