### ISSUE TITLE
Trying to migrate from one docker host to another

### ISSUE THREAD

**Issue by sunseeker2k5** [louislam/uptime-kuma#4362]
### ⚠️ Please verify that this question has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

I am trying to migrate an instance of Uptime Kuma from one docker host to another.
1. Stopped old Kuma instance on old host 
2. Backed up var/lib/docker/volumes/uptime-kuma/_data
3. installed the new instance on new host and logged in
4. stopped the new instance and copied the backup contents to the same folder structure
5. restarted the new instance

Everything seems ok, monitors are there and they are reporting new events but when i try to update one of them the screen is empty (monitor type, friendly name, URL are all blank). If i try to edit I can, my tags and groups are there but when I am trying to save it it throws 2 errors

- ```sql
  INSERT INTO monitor_tag(tad_id,monitor_id,value) VALUES (6,NULL,") - SQLITE)_CONSTRAINT : NOT NULL  constraint failed: monitor_tag, monitor_id
  ```
- ```log
  Undefined bindings detected for keys [0] when compiling RAW query : id=?
  ```
Old and new are the same Kuma version. On old host i first recreated the container before migrating and there everything continuies to work ok on the old host. If i don't recreate the container on old host, same issues.

### 📝 Error Message(s) or Log

- ```sql
  INSERT INTO monitor_tag(tad_id,monitor_id,value) VALUES (6,NULL,") - SQLITE)_CONSTRAINT : NOT NULL  constraint failed: monitor_tag, monitor_id
  ```
- ```log
  Undefined bindings detected for keys [0] when compiling RAW query : id=?
  ```

### 🐻 Uptime-Kuma Version

1.23.11

### 💻 Operating System and Arch

Ubuntu 22.04 OS, Docker container

### 🌐 Browser

Version 120.0.6099.199 (Official Build) (64-bit) on Linux Mint 21.2

### 🐋 Docker Version

Version 120.0.6099.199 (Official Build) (64-bit)

**Comment by louislam** [comment]
Sounds no issue to me.

Maybe you should not boot the new instance first (skip the step 3).
