### ISSUE TITLE
monitor dockerized postgres db connection when using docker intalled uptime-kuma

### ISSUE THREAD

**Issue by re4388** [louislam/uptime-kuma#4364]
### ⚠️ Please verify that this question has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

The connection is always refuse.

Like below
```
2024-01-13T11:01:37+08:00 [MONITOR] WARN: Monitor #16 'eded': Failing: connect ECONNREFUSED 127.0.0.1:5433 | Interval: 60 seconds | Type: postgres | Down Count: 0 | Resend Interval: 0
```

Is there any extra setup necessary to make this work? 
like make two container in the same network? 
or something I might miss out.

### 📝 Error Message(s) or Log

```
2024-01-13T11:01:37+08:00 [MONITOR] WARN: Monitor #16 'eded': Failing: connect ECONNREFUSED 127.0.0.1:5433 | Interval: 60 seconds | Type: postgres | Down Count: 0 | Resend Interval: 0
```

_No response_

### 🐻 Uptime-Kuma Version

docker version, tag: 8c17e48b96c linux/arm64

### 💻 Operating System and Arch

Mac Air m2, OS: Ventura 13.3.1 

### 🌐 Browser

Version 120.0.6099.199 (Official Build) (arm64)

### 🐋 Docker Version

Docker Engine - Community Version:          24.0.7

### 🟩 NodeJS Version

18

**Comment by chakflying** [comment]
It depends on what docker networking mode you are using for both containers.

**Comment by re4388** [comment]
@chakflying
I add below snippet to both compose.yaml files but still not working
```
networks:
  my-network:
    driver: bridge
```

**Comment by louislam** [comment]
A special hostname: `host.docker.internal`

See how to enable this:
https://stackoverflow.com/a/43541732/1097815

**Comment by chakflying** [comment]
Using the bridge networking mode, each container has a unique IP address inside the network. You would need to configure the monitor to use this IP address instead. Docker provides a [tutorial on bridge networks](https://docs.docker.com/network/network-tutorial-standalone/#use-user-defined-bridge-networks) on their website.

**Comment by re4388** [comment]
@chakflying, @louislam  Thanks so much for all the information provided! 
My issue resolved~
I finally can check my docker-pg-db with following connection string:
`postgres://userName:password@host.docker.internal:my_db_listen_port/my_database_name`
