### ISSUE TITLE
Monitoring Remote Home Assistant

### ISSUE THREAD

**Issue by Lockie85** [louislam/uptime-kuma#4366]
### ⚠️ Please verify that this question has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

Hey,

I've tried to search and figure out the correct setup for this monitor but I can't figure it out. Help would be appreciated.

I've two remote servers. On server 1 I've Ubuntu with Docker running Uptime Kuma. On server 2 I've Home Assistant which I access via a domain e.g. https://myhassserver.uk/ (example domain not the real one)

I want to create a monitor in Uptime Kuma for the Home Assistant server via the domain but I'm failing to figure out how to do this.

What I've tried is a monitor type of HTTP(s) with the domain but I get a 403 error, Forbidden response.

Can anyone help me on how I'm meant to setup a monitor like this?

Many Thanks

### 📝 Error Message(s) or Log

403 forbidden response.

### 🐻 Uptime-Kuma Version

1.23.11

### 💻 Operating System and Arch

Ubuntu

### 🌐 Browser

Chrome

### 🐋 Docker Version

CE 2.19.4

**Comment by CommanderStorm** [comment]
403 forbidden usually means you are not allowed to access this site because the credentials you provided are not valid ,(assuming correct usage by HA)
https://en.wikipedia.org/wiki/HTTP_403

**Comment by Lockie85** [comment]
Yep that bit I get, but I'm not trying to access it/login (I'd assume). I'm only trying to check the page loads, in this case the login page. Would it need access/login to get a 200?

If I go to my domain I don't get a 403, I get the login page.

**Comment by CommanderStorm** [comment]
Please make sure that you have your ip banning configured correctly.
See https://community.home-assistant.io/t/solved-out-of-the-blue-now-i-get-403-forbidden/324107

See https://github.com/louislam/uptime-kuma/wiki/Troubleshooting#uptime-kuma-reports-down-but-the-service-can-be-accessed
=> please try to reproduce this behaviour and see what the endpoint is really responding with

> Would it need access/login to get a 200

It seems to require correct credentials.
I don't have a HA instance to test on, it also depends on what endpoint you are using.
To be on the same page: you are using ["System Health"](https://www.home-assistant.io/integrations/system_health/) to get the status?

**Comment by Lockie85** [comment]
Argh! I've found the issue. I forgot my Cloudflare setup blocked IPs which weren't based in a specific country. Which my server is NOT! So I've had to allow the IP on cloudflare and now it works. Totally forgot I did that! Oops.
