### ISSUE TITLE
Notify on specific status code

### ISSUE THREAD

**Issue by CharlotteCross1998** [louislam/uptime-kuma#4368]
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

New Notification

### 🔖 Feature description

Ability to have notifications only on selected status codes

### ✔️ Solution

I want to be able to have a notification only when selected status codes are given, instead of when the status changes. For example, I don't want any notifications about my service being up, nor a notification for a 504, but I may want a notification for a 503 or 404.  

The user may be able to select from a list of status codes they want to receive a notification about.

**Comment by vfosnar** [comment]
You can use the 'Accepted Status Codes' option

**Comment by jorgelaranjo** [comment]
![image](https://github.com/louislam/uptime-kuma/assets/1196202/1abd1aed-75b1-4b9c-bb14-d955b9529a6e)

**Comment by CharlotteCross1998** [comment]
Sorry if I'm being obtuse and not understanding the configuration properly. I've just tested and I get a notification giving me an error of 200, which is what this feature request is about. 

I want the status page to accept 200-299 as successful, but I don't want notifications about it being 200-299, or notifications about it not being 200-299 unless it's 503 or 404 specifically being true, but not false. If I tell the monitor I want to accept 503 and 404 as successful, I get a notification about 200. If I tell the monitor I want to accept 200-299, I do get a notification about 503 and 404, but I also get notifications about everything else, where my request is, is that I'd like to be able to get a notification sent when the test case for 404 and 503 are true, but not when they're false. 

So in my configuration, I want to test against 200-299 because I want to see the history of that in the interface, but I want a notification when 503 and 404 are specifically true not when they've changed from being true to false, only false to true, so the feature isn't about choosing which status codes to accept as successful, but when a specific status code is observed, notify on that. I hope that makes sense?

**Comment by jorgelaranjo** [comment]
> Sorry if I'm being obtuse and not understanding the configuration properly. I've just tested and I get a notification giving me an error of 200, which is what this feature request is about.
> 
> I want the status page to accept 200-299 as successful, but I don't want notifications about it being 200-299, or notifications about it not being 200-299 unless it's 503 or 404 specifically being true, but not false. If I tell the monitor I want to accept 503 and 404 as successful, I get a notification about 200. If I tell the monitor I want to accept 200-299, I do get a notification about 503 and 404, but I also get notifications about everything else, where my request is, is that I'd like to be able to get a notification sent when the test case for 404 and 503 are true, but not when they're false.
> 
> So in my configuration, I want to test against 200-299 because I want to see the history of that in the interface, but I want a notification when 503 and 404 are specifically true not when they've changed from being true to false, only false to true, so the feature isn't about choosing which status codes to accept as successful, but when a specific status code is observed, notify on that. I hope that makes sense?

Create a group, create several items, one for the positive 200-299 and one negative for hte 404/503 as shown
Setup notification on both for when it changes from beeing good to bad
And will work as expected.

![image](https://github.com/louislam/uptime-kuma/assets/1196202/c7569414-9ca6-46d3-88bb-7a3179a14acc)


Here's status page
![image](https://github.com/louislam/uptime-kuma/assets/1196202/b2ccbb90-9083-4afd-a637-af7a53d469b5)

**Comment by CharlotteCross1998** [comment]
I see, thank you.
