### ISSUE TITLE
Docker container EACCESS permission denied mkdir 'data/upload'

### ISSUE THREAD

**Issue by Delgerskhn** [louislam/uptime-kuma#4370]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### Description

When I build my Docker image targeting the release stage and run the container, it throws an EACCES permission denied error.

### 👟 Reproduction steps

1. Build the Docker image targeting the release stage.
2. Run the container.

### 👀 Expected behavior

The Docker container should run without any errors.

### 😓 Actual Behavior

The Docker container throws the following error:
uptime-kuma | Trace: Error: EACCES: permission denied, mkdir 'data/upload/' uptime-kuma | at Object.mkdirSync (node:fs:1414:3) 

### 🐻 Uptime-Kuma Version

2.0.0-dev

### 💻 Operating System and Arch

Ubuntu 20.04

### 🌐 Browser

Microsoft Edge

### 🐋 Docker Version

Docker version 24.0.7, build afdd53b

### 🟩 NodeJS Version

20.x

### 📝 Relevant log output

```shell
uptime-kuma | Trace: Error: EACCES: permission denied, mkdir 'data/upload/' uptime-kuma | at Object.mkdirSync (node:fs:1414:3) uptime-kuma | at Database.initDataDir (/app/server/database.js:140:16) uptime-kuma | at /app/server/server.js:172:14 uptime-kuma | at Object. (/app/server/server.js:1571:3) uptime-kuma | at Module._compile (node:internal/modules/cjs/loader:1233:14) uptime-kuma | at Module._extensions..js (node:internal/modules/cjs/loader:1287:10) uptime-kuma | at Module.load (node:internal/modules/cjs/loader:1091:32) uptime-kuma | at Module._load (node:internal/modules/cjs/loader:938:12) uptime-kuma | at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:83:12) uptime-kuma | at node:internal/main/run_main_module:23:47 { uptime-kuma | errno: -13, uptime-kuma | syscall: 'mkdir', uptime-kuma | code: 'EACCES', uptime-kuma | path: 'data/upload/' uptime-kuma | } uptime-kuma | at process.unexpectedErrorHandler (/app/server/server.js:1814:13) uptime-kuma | at process.emit (node:events:514:28) uptime-kuma | at emit (node:internal/process/promises:150:20) uptime-kuma | at processPromiseRejections (node:internal/process/promises:284:27) uptime-kuma | at process.processTicksAndRejections (node:internal/process/task_queues:96:32) uptime-kuma | If you keep encountering errors, please report to [https://github.com/louislam/uptime-kuma/issues](vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/code/electron-sandbox/workbench/workbench.html) uptime-kuma | 2024-01-15T06:57:36Z [] INFO: Cannot write to error.log uptime-kuma exited with code 0
```

**Comment by Delgerskhn** [comment]
The same src works on my local machine.

**Comment by Delgerskhn** [comment]
After I manually created the upload, screenshots, docker-tls directories in project src, and build the docker image, this error is resolved.

**Comment by CommanderStorm** [comment]
> Build the Docker image targeting the release stage

What is the release stage?

**Comment by CommanderStorm** [comment]
I just noticed that you have written that you are running against `2.0.0-dev` in the description.

Said version is not yet done (pre-beta) => not yet supported.
Please refer to #4171 for additional context
