### ISSUE TITLE
Where did the grafana dashboard go?

### ISSUE THREAD

**Issue by nmcc1212** [louislam/uptime-kuma#4374]
### ⚠️ Please verify that this question has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

The grafana dashboard referenced here [https://github.com/louislam/uptime-kuma/wiki/Prometheus-Integration](https://github.com/louislam/uptime-kuma/wiki/Prometheus-Integration#:~:text=There%20is%20also%20a%20Grafana%20Dashboard%20available%20to%20import%20into%20your%20Grafana%20installation%20to%20get%20the%20metrics%20integrated%20with%20your%20other%20monitoring%20tools.) gives me a 404 error when going to the link https://grafana.com/grafana/dashboards/14847-uptime-kuma/

### 🐻 Uptime-Kuma Version

N/A

### 💻 Operating System and Arch

N/A

### 🌐 Browser

N/A

**Comment by CommanderStorm** [comment]
Good catch. Said dashboard was not maintained/owned by us (maintainers).

Possibly related: https://github.com/louislam/uptime-kuma/issues/3225

@proffalken you added this dashboard in https://github.com/louislam/uptime-kuma-wiki/commit/e9a64eae5237632e836bfefe98c9d7b50cd24acc
Could you make it public/restore it again?

**Comment by louislam** [comment]
> https://web.archive.org/web/20220722045503/https://grafana.com/api/dashboards/14847/revisions/2/download

Found the revision 2 on Wayback machine

@proffalken If you don't mind, you could give this json file a open source license like MIT and your copyright info, so that other users can continue your work and republish it.😃

**Comment by proffalken** [comment]
Good find @louislam - yes, happy to do that, is there a "contrib" dirnor similar in the repo I can add it to so it's not lingering in a git repo owned by me somewhere?

**Comment by louislam** [comment]
https://github.com/louislam/uptime-kuma/tree/unofficial/grafana-dashboard

I just created a new branch here, feel free to create a pull request to modify the license info.
