### ISSUE TITLE
 OK, but keyword is not in []

### ISSUE THREAD

**Issue by vinznsk** [louislam/uptime-kuma#4375]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### Description

I have 80 websites in Uptime Kuma, 2 websites recently started getting issues with keywords

<img width="466" alt="2024-01-16-14-03-12" src="https://github.com/louislam/uptime-kuma/assets/702948/5e00a42c-53ea-4442-b02d-4a7879a68444">

Websites are okay, UptimeRobot for example, doesn't show any issues, only uptime kuma. Also, I can open websites manually and there are no issues as well.

This doesn't happen with all website, just a few. 

So, there are 2 issues I see:
1. Error is not relevant to the reality, websites are okay, but Uptimie Kuma displays an error
2. There are weird symbols in the response

P.S. I have Uptime Kuma installed on NAS and on a Ubuntu server, this issues happen on both of them.

### 👟 Reproduction steps

1. Create a new alert
   - Type: Https - keyword
   - Friendly name - aronlawfirm.com
   - URL: https://www.aronlawfirm.com/
   - Interval: 60 sec
   - Retries: 3
   - Method: Get
   - Body Encoding: JSON

### 👀 Expected behavior

OK, but keyword is found

### 😓 Actual Behavior

200 - OK, but keyword is not in [���Q���F�f�h�,�������}��;����Y�A���8� ;�&]...]

### 🐻 Uptime-Kuma Version

1.23.11

### 💻 Operating System and Arch

Ubuntu 20.04

### 🌐 Browser

Google Chrome 120.0.6099.217

### 🐋 Docker Version

-

### 🟩 NodeJS Version

-

**Comment by CommanderStorm** [comment]
![image](https://github.com/louislam/uptime-kuma/assets/26258709/3824f8c1-9d43-458a-86b0-345bceea1c51)

![image](https://github.com/louislam/uptime-kuma/assets/26258709/1a3d68fa-eb6d-4527-8a15-973dc15cca64)

**Comment by CommanderStorm** [comment]
Cannot really reproduce this one. I think some content for the `body` may be necessary given that you said to provide JSON encoding. (?)

**Comment by vinznsk** [comment]
403 error is because of Sucuri Firewall (there are a several websites use Sucuri, but not all of them)

There were 3 websites we saw this issue today and now all of them work fine

![image](https://github.com/louislam/uptime-kuma/assets/702948/c9f1d695-ff0c-4a31-abf8-d04f72e95371)

I'll give more info as soon as it happens again.
