### ISSUE TITLE
steam server monitor fill domain problem

### ISSUE THREAD

**Issue by billy-shang** [louislam/uptime-kuma#4378]
### ⚠️ Please verify that this question has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

steam服务器监控问题，我需要填写域名来监控，但它监测失败，如果用IP地址，是成功的，但我IP地址是动态的，每次都需要我自己去更新IP地址吗？

deepl translation:
STEAM server monitoring question, I need to fill in the domain name to monitor, but it fails to monitor, if I use the IP address, it is successful, but my IP address is dynamic, do I need to update the IP address by myself every time?

### 🐻 Uptime-Kuma Version

1.10.0

### 💻 Operating System and Arch

群辉

### 🌐 Browser

chrome

**Comment by CommanderStorm** [comment]
> do I need to update the IP address by myself every time

Currently, this is the only option offered. [PRs appreciated](https://github.com/louislam/uptime-kuma/blob/master/CONTRIBUTING.md) ^^

DNS resolution for the steam monitor has been raised in this issue: https://github.com/louislam/uptime-kuma/issues/1257

=> closing as better tracked in #1257
