### ISSUE TITLE
Use two lines for friendly name

### ISSUE THREAD

**Issue by mueller-ma** [louislam/uptime-kuma#4381]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### Description

When the friendly name is too long, it isn't shown fully on small displays like phones. The name could use multiple lines, so it's shown. Maybe limit this to two or three lines.

### 👟 Reproduction steps

Create a new monitor with "Very loooooooooooong name".

### 👀 Expected behavior

Full name is shown

### 😓 Actual Behavior

![grafik](https://github.com/louislam/uptime-kuma/assets/22525368/bef1682b-b0f1-4c18-b66e-9b8de0862c17)

### 🐻 Uptime-Kuma Version

1.23.11

### 💻 Operating System and Arch

Windows 10

### 🌐 Browser

Firefox 121.0.1

**Comment by CommanderStorm** [comment]
Idk how where new line there would fit into our UI.
Why do you wan't so long titles?

**Comment by mueller-ma** [comment]
The title doesn't have to be super long. For example from the screenshot in the Readme "Inbox by Gmail". When I use Chrome to emulate "Galaxy Fold", the title isn't fully shown: 
![grafik](https://github.com/louislam/uptime-kuma/assets/22525368/698ba5c5-5db1-466a-8f86-df224ffb7b42)

Some services require more words to describe themselves for all users. For example "Active Directory" can be hard to understand for users where "Login on Windows Systems" is longer, but better understandable.

> I don't think this should be considered a bug, since it's more of a design choice.

IMO anyone who wishes to can keep their titles short, but I personally prefer the full title to be shown.

**Comment by mueller-ma** [comment]
This setting doesn't influence the status page, but the dashboard only. And it's only for logged in user, not for every visitor: https://github.com/louislam/uptime-kuma/issues/1858

**Comment by mueller-ma** [comment]
If you agree I can create a PR for this.

**Comment by mueller-ma** [comment]
What about adding a mouse over text for the title? At least on PC users can view the full title then.

**Comment by mueller-ma** [comment]
The following custom CSS enables line wrap for long titles:

```css
.hp-bar-big {
  padding: 0; 
}
.monitor-list .item .info {
  white-space: normal;
}
```
