### ISSUE TITLE
Changing Weblate commit details

### ISSUE THREAD

**Issue by kindercat** [louislam/uptime-kuma#4382]
### ⚠️ Please verify that this question has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

I saw the Weblate commits for all languages and I'm wondering if I can edit a commit details like email address.

### 🐻 Uptime-Kuma Version

1.23.10

### 💻 Operating System and Arch

Ubuntu 22.04.3

### 🌐 Browser

Microsoft Edge latest

**Comment by CommanderStorm** [comment]
You are likely referring to this, right?
Is the email address incorrect?

https://github.com/louislam/uptime-kuma/pull/4270/commits/755c92ca4e26c1964b44b557207dc117a33834c9

We could create a [`.mailmap`](https://git-scm.com/docs/gitmailmap), but for this we need a bit more context ^^

**Comment by kindercat** [comment]
I've done some testing on Weblate in the mail section and I think it will be a good idea if the commits can be linked to the no-reply identity from github to avoid spam.

**Comment by CommanderStorm** [comment]
If you use an identity which I assume is not linked+verified to/for your account, like kindercat@users.noreply.weblate.kuma.pet, this will not be linked to your account as far as I understand

**Comment by CommanderStorm** [comment]
we can add this as an alias for `smartzen017@gmail.com` in a [`.mailmap`](https://git-scm.com/docs/gitmailmap), but I sort of doubt that this achives what you want...

Note that spam is not a real issue.
I have not seen more spam in my mailbox from contributing actively on GitHub. The only spam I receive can be traced back to stupid things I did in the past and being included in data leaks.

**Comment by kindercat** [comment]
If you can edit the commit and this issue with the weblate or github identity is ok for me :)

I really appreciate this project and I want to help more.

**Comment by CommanderStorm** [comment]
Editing commits is a medium pain and requires rebasing.
cc @louislam given that you manage weblate ^^ 

This is the mentiended commit https://github.com/louislam/uptime-kuma/pull/4270/commits/d6808582a41a32644b8dc6ef128fe3f20fbefe9b

**Comment by kindercat** [comment]
This is the commit I wanted to edit https://github.com/louislam/uptime-kuma/commit/755c92ca4e26c1964b44b557207dc117a33834c9
Also please don't forget to edit the post from above :)

Thanks!

**Comment by kindercat** [comment]
This one https://github.com/louislam/uptime-kuma/issues/4382#issuecomment-1895881428

**Comment by CommanderStorm** [comment]
So you want your weblate contributions to not be displayed on github?

**Comment by kindercat** [comment]
Yes. Only the username is ok for me.
You can use kindercat@users.noreply.weblate.kuma.pet or no-reply identity from github.

**Comment by louislam** [comment]
Unfortunately, Weblate don't let me to control the git repo either. There are only two actions I can do: `Commit` and `Push`, which do not seem to be able to change the commit message.

![image](https://github.com/louislam/uptime-kuma/assets/1336778/7e8d13a3-d943-497c-a587-a9ad0e369f9b)

**Comment by kindercat** [comment]
Maybe this is usefull https://youtu.be/BNF4le5X1Ms?si=UtLIOdp8q50plFk_
If not, it's not that bad.. just delete this issue and I'm fine.
