### ISSUE TITLE
Maintenance Still Pings just disables notification Option

### ISSUE THREAD

**Issue by Fluffy8852** [louislam/uptime-kuma#4388]
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

UI Feature, Other

### 🔖 Feature description

In my opinion, maintenance mode should have an option to keep pinging but disable notifications and show it on status page but downtime is still downtime even if you do have maintenance.

### ✔️ Solution

Have an option to keep pinging but disable notifications and show it on status page but downtime is still downtime even if you do have maintenance.

**Comment by CommanderStorm** [comment]
I think this is fully covered by #3016
=> closing as a duplicate

If you'd like to get involved, here is our contribution guide: https://github.com/louislam/uptime-kuma/blob/master/CONTRIBUTING.md
