### ISSUE TITLE
I Want to view multi uptime service

### ISSUE THREAD

**Issue by volkankoc** [louislam/uptime-kuma#4389]
### ⚠️ Please verify that this question has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

I Want to view multi uptime service. I have 10 uptime services at different addresses.  How can I watch all the images from these services on one screen?

### 🐻 Uptime-Kuma Version

1.23

### 💻 Operating System and Arch

Windows

### 🌐 Browser

Chrome

**Comment by chakflying** [comment]
We don't have a specific integration for this. You can think about building a Grafana dashboard from multiple data sources, or alternatively use iframes to combine them into 1 view.

**Comment by CommanderStorm** [comment]
Here are the relevant docs:
- https://github.com/louislam/uptime-kuma/wiki/Status-Page#custom-subdirectory--custom-html-on-status-pages
- https://github.com/louislam/uptime-kuma/wiki/Prometheus-Integration
