### ISSUE TITLE
ports check broken?

### ISSUE THREAD

**Issue by yuriw** [louislam/uptime-kuma#4390]
### ⚠️ Please verify that this question has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

I have two port check items and both don't work (8920, 8096)

I checked the ports via https://portchecker.co/check-it and it correctly reported them as open.

Maybe a regression.

### 📝 Error Message(s) or Log

none

### 🐻 Uptime-Kuma Version

1.23.11

### 💻 Operating System and Arch

Ubuntu 22.04

### 🌐 Browser

Chrome

### 🐋 Docker Version

n/a

### 🟩 NodeJS Version

n/a

**Comment by yuriw** [comment]
My URL is external and HTTPS Emby server

**Comment by CommanderStorm** [comment]
If the url is external, could you share the ip/port of said service?

**Comment by yuriw** [comment]
> If the url is external, could you share the ip/port of said service?

Let me look for a public server as an example (I'd like to avoid sharing mine publicly)

**Comment by CommanderStorm** [comment]
You can share it to me via my email adress if you'd prefer:
![image](https://github.com/louislam/uptime-kuma/assets/26258709/6092e50a-4c15-422f-9c72-4038688cdee5)

**Comment by yuriw** [comment]
Check you email 😉

**Comment by CommanderStorm** [comment]
Sorry, but I cannot reproduce said ip responding to a tcp connection.

![image](https://github.com/louislam/uptime-kuma/assets/26258709/0c3e7db8-6a9d-44ac-8a02-4feb8bd8b81f)


I think you are misunderstanding something:
- TCP port is the equivalent of `telnet IP PORT`
- https://portchecker.co/ checks for "open ports".

it is unclear to me what mechanism they use, to determine this, best I can think of is 
![image](https://github.com/louislam/uptime-kuma/assets/26258709/36e3464e-b37b-43cc-9efa-a43255be2df7)

**Comment by yuriw** [comment]
@CommanderStorm 
I am blocking non-US inbound traffic and that's why you could not telnet to it.
I disabled the block now.  Can you retry?
TIA

**Comment by yuriw** [comment]
Pls paste your setup of this ping

**Comment by CommanderStorm** [comment]
![image](https://github.com/louislam/uptime-kuma/assets/26258709/daa32e30-d3be-4a9f-8c47-e5756e1d062c)

If there is a field that needs better UX, feedback is appreciated

**Comment by yuriw** [comment]
It's odd.  It used to work fine for me and then stopped and still does not.

I guess it's some combination of odd things.

What is the next way to get more detail logs from uptime kuma to troubleshoot?

**Comment by yuriw** [comment]
> If there is a field that needs better UX, feedback is appreciated

please remove IP !

**Comment by CommanderStorm** [comment]
>  used to work fine for me and then stopped and still does not

Software normally does not stop working without external effects ("admins/users mucking with it"). => Bisect the changes you did when the changes occured.


> What is the next way to get more detail logs from uptime kuma to troubleshoot

You can exec inside the container and then progressively go outward.
We have documented how to do this partially in https://github.com/louislam/uptime-kuma/wiki/Troubleshooting#uptime-kuma-reports-down-but-the-service-can-be-accessed

It works on https://uptime.kuma.pet/ as expected.

**Comment by yuriw** [comment]
> > used to work fine for me and then stopped and still does not
> 
> Software normally does not stop working without external effects ("admins/users mucking with it"). => Bisect the changes you did when the changes occured.
> 
> > What is the next way to get more detail logs from uptime kuma to troubleshoot
> 
> You can exec inside the container and then progressively go outward. We have documented how to do this partially in https://github.com/louislam/uptime-kuma/wiki/Troubleshooting#uptime-kuma-reports-down-but-the-service-can-be-accessed
> 
> It works on https://uptime.kuma.pet/ as expected.

Not for me:

![image](https://github.com/louislam/uptime-kuma/assets/3876474/99f56af9-8da5-4762-8d58-6f4b0f55ac3d)

Tried on my network and on a different network

**Comment by yuriw** [comment]
I restored an old version of UK from last November with the hope it would work, but no it shows the same problem. 

Very interesting...

**Comment by yuriw** [comment]
@CommanderStorm how can you check the port on the same node where UK runs via the command line tool?
Cam you try it for me pls?
Thx

**Comment by CommanderStorm** [comment]
> I am blocking non-US inbound traffic

Note that you likely re-enabled this block. Remember that I am doing this from a residential, German internet access.

**Comment by yuriw** [comment]
I don't run docker 😞
Anything else you can use?

**Comment by yuriw** [comment]
Try any external port pls

**Comment by CommanderStorm** [comment]
I don't know what you mean by any external port. I tried this already as noted above:
The ip+port you specified are external to me, and they don't want to connect to me.

Here is what telnet should look like if a website wants to connect via TCP:
![image](https://github.com/louislam/uptime-kuma/assets/26258709/43b40f42-0da2-4c63-9134-6a503975fbf0)

**Comment by CommanderStorm** [comment]
> I don't run docker 😞 Anything else you can use?

You are likely searching at the wrong spot.
From my perspective, your service is either geo-locked, defective or not at said ip + port any more.

**Comment by yuriw** [comment]
> > I don't run docker 😞 Anything else you can use?
> 
> You are likely searching at the wrong spot. From my perspective, your service is either geo-locked, defective or not at said ip + port any more.

My ports are definitely open.  Yes I block all traffic from non-US.
I suspect the issue is the way UK was deployed via https://tteck.github.io/Proxmox/

Sorry for being unclear.
All I need help with is to check a port via the command line (on Debian), so I can compare.
I bet the port won't check as open from the same node as UK is installed.

By "any" port I meant it does not have to be my port :)

**Comment by yuriw** [comment]
Yup confirmed - the port is not checkable.
Why - who knows?!
Workaround - use local LAN IP address instead of an external host name
