### ISSUE TITLE
Monitors display 0.X % for the last 24 hours but it should be 100 %

### ISSUE THREAD

**Issue by Rebecca-Dieter-Teamwire** [louislam/uptime-kuma#4396]
### ⚠️ Please verify that this question has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

We are running some Jobs each night and at the end push the state to the chosen uptime-kuma Push-URL

The checks have all the same settings. As example:
![Bildschirmfoto vom 2024-01-19 08-59-33](https://github.com/louislam/uptime-kuma/assets/128380805/ef13817c-bd9c-44d5-95aa-c0c2998da830)

Overall we have 12 of those monitors but 6 of them are not displaying the correct percentage for the last 24 hours (in our eyes):
Those monitors are displaying the following percentages:
* 0.09
* 0.08
* 0.4
* 0.08
* 0.08

The Dashboard shows the following state (This is only one of them as an example):
![image](https://github.com/louislam/uptime-kuma/assets/128380805/c6ca39d7-b6f8-45dc-a60f-d8431314a74d)

The URL which gets pushed looks like this:
`https://< our server url >/api/push/< monitor id provided by uptime-kuma >?status=up&msg=Lab+succeeded`

As mentioned the jobs only run once a day and then push the information to uptime-kuma to have an easy overview. Since the job only runs once and it's succeed each time there is no possiblity to have a percentage like 0.X or anything else. It should either be 100 % or 0 %.

### 📝 Error Message(s) or Log

I did not see any errors for those monitors over the last 48 hours

### 🐻 Uptime-Kuma Version

1.23.10-debian

### 💻 Operating System and Arch

Debian 11

### 🌐 Browser

Google Chrome 120.0.6099.216-1

### 🐋 Docker Version

Docker version 23.0.1, build a5ee5b1

**Comment by CommanderStorm** [comment]
Could your instance have been offline or could a maintenance period have been in place in the time frame?
