### ISSUE TITLE
Telegram Notifications

### ISSUE THREAD

**Issue by sotoje** [louislam/uptime-kuma#44]
Could you please explain the configuration for Telegram Notifications? I does not work for me

**Comment by rezzorix** [comment]
1. have Telegram app installed on your phone
2. open this link https://t.me/BotFather
3. it will ask you to open the Telegram app
4. you now chat with BotFather
5. enter /start
6. Follow instructions written there e.g. enter /newbot 

At the end you get the bot token that you add into the "Bot Token" field in Kuma.

**Comment by sotoje** [comment]
I juat follow this steps but it does not work

**Comment by rezzorix** [comment]
> I just follow this steps but it does not work

What exactly doesnt work? 
Which steps were you able to complete?

**Comment by sotoje** [comment]
I have my telegram notification form complete, and i push the test button but nothing happends.
I try to put offline, one of my sites but I didn't receive any notification.

I have used the bot in group and in one to one chat, changing the chat id in each case

**Comment by rezzorix** [comment]
Ok... if you have the correct token & chat ID then hitting the test button should result in a testing message in your Telegram chat.

Make sure that the token & chat id are 100% correct (check for "spaces" or 0 O (zero or o) etc.)

**Comment by sotoje** [comment]
I'm pretty sure, but i will check it again because its easy i must be work....
 
Thanks for you support, i will update

**Comment by louislam** [comment]
> I just follow this steps but it does not work



> I'm pretty sure, but i will check it again because its easy i must be work....
> 
> Thanks for you support, i will update

After Pressed the "Test" button,  did you get any error message?

**Comment by sotoje** [comment]
No, i have checked it again and all seems ok.
No errors, the test button works and it said "sent successfully" but does not work.
The chat id has has a dash "-xxxxxxx"

**Comment by louislam** [comment]
You can check with the api directly, UptimeKuma using this as well

https://api.telegram.org/bot<TOKEN>/sendMessage?chat_id=<Chat ID>&text=Hello

**Comment by sotoje** [comment]
{"ok":false,"error_code":401,"description":"Unauthorized"}

**Comment by sotoje** [comment]
Working!

**Comment by rezzorix** [comment]
I still think you have wrong token and/or chat_id

Did you get the chat id from @RawDataBot from the link I posted above?

**Comment by sotoje** [comment]
Could be, i copy/paste it again and it is working now.

Thank for your support!!!!

**Comment by rezzorix** [comment]
Glad it worked. :smiley:

This thread can be closed 🔒
