### ISSUE TITLE
git.kuma.pet not working

### ISSUE THREAD

**Issue by Saibamen** [louislam/uptime-kuma#440]
http://git.kuma.pet/
![image](https://user-images.githubusercontent.com/905878/133908043-6a25da76-bbe1-4682-ab27-60fdde4cb92d.png)

This is because of `vite` version `v2.5.8`. It was fixed in `v2.5.9`: https://github.com/vitejs/vite/issues/4977 few minutes ago

**Comment by Saibamen** [comment]
@louislam: We need to add build check for every commit.

Related PRs: https://github.com/louislam/uptime-kuma/pull/53, https://github.com/louislam/uptime-kuma/pull/213

**Comment by louislam** [comment]
This is just a resource url point to this repo. Not supposed to read via a browser.
