### ISSUE TITLE
How to update cloudflared?

### ISSUE THREAD

**Issue by sasagar** [louislam/uptime-kuma#4401]
### ⚠️ Please verify that this question has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

The Uptime Kuma includes cloudflared v2023.10.0 for now.

But the latest version is v2024.1.4, is it possible to update the one?

### 🐻 Uptime-Kuma Version

1.23.11

### 💻 Operating System and Arch

Linux omv 6.1.0-rpi7-rpi-v8 #1 SMP PREEMPT Debian 1:6.1.63-1+rpt1 (2023-11-24) aarch64 GNU/Linux

### 🌐 Browser

Google Chrome v120.0.6099.234

### 🐋 Docker Version

Docker version 24.0.7, build afdd53b

**Comment by CommanderStorm** [comment]
We update these kinds of dependencys like apprise or cloudflared before every release.
We currently ship with the latest at the time of our last release: https://github.com/cloudflare/cloudflared/blob/master/RELEASE_NOTES

Is there a reason that requires a patch release for this?

**Comment by chakflying** [comment]
Please check this issue for the recommended method of running an external cloudflared with your chosen version.

https://github.com/louislam/uptime-kuma/issues/3993#issuecomment-1803129833

**Comment by sasagar** [comment]
Thanks for your help.

Maybe the best way for me to get the latest version would running cloudflared outside of the Uptime Kuma container.

I just want the notification in the CF tunnel away, because it is little noisy.

Thanks again for your informations.
