### ISSUE TITLE
An actual dashboard page, showing multiple monitored devices

### ISSUE THREAD

**Issue by aristosv** [louislam/uptime-kuma#4402]
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

UI Feature

### 🔖 Feature description

We have 160 remote devices we're monitoring with ping. Playing around with .css I was able to show around 80 of them, by creating a 10x8 grid status page. But the boxes for each device are too big, and there's a lot of wasted space on the top of the page, showing the logo, a title, the "edit status page" and "go to dashboard" buttons, and the "services" title.

### ✔️ Solution

remove all content from status page and give the option to create grids and resize boxes. Use the whole page just for the monitored devices. We also use site24x7 and this feature is critical for creating monitoring dashboards and displaying then on large screens in the NOC. Dashboards are critical for efficient monitoring, this is what IT organizations are looking for, and it will take uptime kuma to the next level.

### ❓ Alternatives

provide the .css code by creating multiple templates, or implement a template system with various options for the status pages.

**Comment by CommanderStorm** [comment]
Multi-column status pages are tracked in #592

I don't see a significant difference between these issues
If I am missing something, we can reopen this isssue ^^
 => closing as a duplicate

Note that our contribution guide is avaliable at https://github.com/louislam/uptime-kuma/blob/master/CONTRIBUTING.md
