### ISSUE TITLE
page error message“Lost connection to the socket server. Reconnecting...”

### ISSUE THREAD

**Issue by macaty** [louislam/uptime-kuma#4409]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### Description

When  click on or jump to manage-status-page 【 http://x.x.x.x:6001/manage-status-page】 from status pages【http://x.x.x.x:6001/status/monitor】 ，we got an error message ,like "Lost connection to the socket server. Reconnecting..."

The detailed error message is as follows, please help:
error url: http://x.x.x.x:6001/socket.io/?EIO=4&transport=polling&t=OqqPZ0i&sid=bdBgD95f9Dm-G10IAAGH 
404 status respone：{"code":1,"message":"Session ID unknown"}

![image](https://github.com/louislam/uptime-kuma/assets/16797633/6b7f2a1b-17af-4d22-8dd2-ab8978d30027)
![image](https://github.com/louislam/uptime-kuma/assets/16797633/67ef0b64-3b37-46e3-8abd-0f0de8337267)

### 👟 Reproduction steps

refer to Description

### 👀 Expected behavior

refer to Description

### 😓 Actual Behavior

refer to Description

### 🐻 Uptime-Kuma Version

louislam/uptime-kuma:1.23.11

### 💻 Operating System and Arch

centos 7.9

### 🌐 Browser

chrome 120.0.6099.225

**Comment by CommanderStorm** [comment]
- How have you deployed uptime kuma?
- Are you running a reverse proxy? If yes, how is it configured?
- am I reading your report correctly that every site works except `/manage-status-page`?

**Comment by macaty** [comment]
1. deploy to docker env

**Comment by CommanderStorm** [comment]
Given that the error message is stating that the `Session ID [is] unknown`, have you tried logging out + back in?
What is the Relevant log output?

**Comment by macaty** [comment]
Yes，I tried several times and got the same result.
![image](https://github.com/louislam/uptime-kuma/assets/16797633/6649f126-61d8-49a0-ba63-b76a916e14ad)
![image](https://github.com/louislam/uptime-kuma/assets/16797633/d4b5722c-0084-46d6-8e43-8b05d150b1b8)

**Comment by CommanderStorm** [comment]
just a guess (comparing #4422 and my working setup):
What is your docker version?

**Comment by baalchina** [comment]
> just a guess (comparing #4422 and my working setup): What is your docker version? Comparing your setup with his, are there any points which seem similar?

Hi, I had the same error in this  https://github.com/louislam/uptime-kuma/issues/4422, while my docker is Docker version 20.10.13, build a224086, thank you.

**Comment by CommanderStorm** [comment]
Okay, so it is not the runtime, nor the docker version.
The only think that differes is that both @baalchina and @macaty are running a version of centos.

I have never worked with said OS. Are there any firewalls on said OS that might be active?

**Comment by baalchina** [comment]
> Okay, so it is not the runtime, nor the docker version. The only think that differes is that both @baalchina and @macaty are running a version of centos.
> 
> I have never worked with said OS. Are there any firewalls on said OS that might be active?

Well, i disabled firewalld in my rocky linux, and tried to open uptime-kuma in a single pc but three browsers(firefox, edge, chrome), only firefox display the lost connection to the socket server, but soon became normal. I'll try again later.
So, should I open any other ports except 3001 ? And is there recommend os by kuma? Maybe ubuntu or debian?
Thanks.

**Comment by louislam** [comment]
Can you reproduce the issue on our demo site?

https://demo.kuma.pet/start-demo

**Comment by baalchina** [comment]
> Can you reproduce the issue on our demo site?
> 
> https://demo.kuma.pet/start-demo
er...I checked the demo site, seems the same error 400. but the error soon disappear and became normal.

![Snipaste_2024-01-29_20-09-40](https://github.com/louislam/uptime-kuma/assets/3983019/335ddbc5-8e03-4192-989a-3dd0cb33aabc)
![Snipaste_2024-01-29_20-08-39](https://github.com/louislam/uptime-kuma/assets/3983019/65636148-d158-447e-8d5d-df353ae46dc0)

**Comment by louislam** [comment]
Weird. I cannot reproduce.

2 possible directions:
- Browser (Affected by extension?), you should try Firefox or MS Edge without extensions.
- Something weird in your network, you can try different network like mobile network.

**Comment by CommanderStorm** [comment]
I can reproduce this (after the 2nd try => not really repeatable)

![image](https://github.com/louislam/uptime-kuma/assets/26258709/3fa66bce-5f4b-4964-9f74-3747dea54f58)

**Comment by CommanderStorm** [comment]
Let's find commonalities.
I am running Chrome 121.0.6167.85 => maybe connected with newer chrome versions?

@louislam what brower are you running?
Could you retry this 2x more just to be sure that this is not also happening on your end?

**Comment by louislam** [comment]
Tried several combinations and tried several times. Also Chrome 121.0.6167.85, maybe I missed some important steps to reproduce.

Test 1:

1. Refresh the status page / Or type the direct status page url `/status/monitor`
2. Click "Go to Dashboard"

Test 2 (From vue router):

1. Go to `/manage-status-page`
1. Click the status page
2. Click "Go to Dashboard"

![image](https://github.com/louislam/uptime-kuma/assets/1336778/814ac525-1975-42d7-ac2f-9c1947709f81)

**Comment by CommanderStorm** [comment]
I have tried multiple times again and cannot reproduce what I could reproduce before.
Seems rarer than I thought.
Without any sort of way of reproducing this little shit.

This bug be like:

<img src="https://media1.giphy.com/media/fXnRObM8Q0RkOmR5nf/giphy.gif"/>

Going back to basics (i.e. the docs): https://socket.io/docs/v3/troubleshooting-connection-issues/#in-the-network-monitor-of-your-browser

> The session ID (included in the sid query parameter) is unknown from the server. That may happen in a [multi-server setup](https://socket.io/docs/v3/using-multiple-nodes/).

@macaty might there be a second server somewhere or might there be something caching responses or might there be something tampering with the traffic we send out?
From the information provided and from I could gather, I really cannot debug this further.

**Comment by louislam** [comment]
https://github.com/socketio/socket.io/issues/4881

Have not look into it yet, but it seems that it is an upstream bug.

If it is true, maybe we should rollback to the previous working version.

**Comment by macaty** [comment]
> 我又尝试了多次，但无法重现我之前可以重现的内容。 似乎比我想象的要少见。 没有任何方式来重现这个小东西。
> 
> 这个错误就像：
> 
> ![](https://camo.githubusercontent.com/9bb126acda82a633fbc41984edacddc216920841c5af072336175b7eebcbbbe1/68747470733a2f2f6d65646961312e67697068792e636f6d2f6d656469612f66586e524f624d385130526b4f6d52356e662f67697068792e676966) [ ![68747470733a2f2f6d65646961312e67697068792e636f6d2f6d656469612f66586e524f624d385130526b4f6d52356e662f67697068792e676966](https://camo.githubusercontent.com/9bb126acda82a633fbc41984edacddc216920841c5af072336175b7eebcbbbe1/68747470733a2f2f6d65646961312e67697068792e636f6d2f6d656469612f66586e524f624d385130526b4f6d52356e662f67697068792e676966) ](https://camo.githubusercontent.com/9bb126acda82a633fbc41984edacddc216920841c5af072336175b7eebcbbbe1/68747470733a2f2f6d65646961312e67697068792e636f6d2f6d656469612f66586e524f624d385130526b4f6d52356e662f67697068792e676966) [ ](https://camo.githubusercontent.com/9bb126acda82a633fbc41984edacddc216920841c5af072336175b7eebcbbbe1/68747470733a2f2f6d65646961312e67697068792e636f6d2f6d656469612f66586e524f624d385130526b4f6d52356e662f67697068792e676966)
> 
> 回到基础知识（即文档）：https://socket.io/docs/v3/troubleshooting-connection-issues/#in-the-network-monitor-of-your-browser
> 
> > 服务器未知会话 ID（包含在 sid 查询参数中）。这可能发生在[多服务器设置](https://socket.io/docs/v3/using-multiple-nodes/)中。
> 
> @macaty某处是否可能有第二台服务器，或者是否存在缓存响应的内容，或者是否存在篡改我们发出的流量的内容？ 从提供的信息和我收集到的信息来看，我真的无法进一步调试。 你知道你是如何能够如此频繁地重现这一点而我却不能吗？



> 只是一个猜测（比较#4422和我的工作设置）： 你的 docker 版本是什么？你的设置和他的比较，有什么相似之处吗？

root@N1:~# docker ps|grep uptime
8f6ef13e16fc   louislam/uptime-kuma:1.23.11   "/usr/bin/dumb-init …"   6 days ago     Up 6 days (healthy)    0.0.0.0:6001->3001/tcp, :::6001->3001/tcp   uptimekuma
root@N1:~# docker version
Client:
 Version:           20.10.17
 API version:       1.41
 Go version:        go1.19.5
 Git commit:        100c701
 Built:             Sat Feb 11 17:11:34 2023
 OS/Arch:           linux/arm64
 Context:           default
 Experimental:      true

Server:
 Engine:
  Version:          20.10.17
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.19.5
  Git commit:       a89b842
  Built:            Sat Feb 11 13:33:41 2023
  OS/Arch:          linux/arm64
  Experimental:     false
 containerd:
  Version:          1.6.6
  GitCommit:        10c12954828e7c7c9b6e0ea9b0c02b01407d3ae1
 runc:
  Version:          1.1.2
  GitCommit:        a916309fff0f838eb94e928713dbc3c0d0ac7aa4
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0

**Comment by macaty** [comment]
> 好吧，所以这不是运行时，也不是 docker 版本。 唯一不同的是，两者@baalchina和@macaty正在运行 centos 版本。
> 
> 我从未使用过上述操作系统。所述操作系统上是否有可能处于活动状态的防火墙？

root@N1:~# docker ps|grep uptime
8f6ef13e16fc   louislam/uptime-kuma:1.23.11   "/usr/bin/dumb-init …"   6 days ago     Up 6 days (healthy)    0.0.0.0:6001->3001/tcp, :::6001->3001/tcp   uptimekuma
root@N1:~# docker version
Client:
 Version:           20.10.17
 API version:       1.41
 Go version:        go1.19.5
 Git commit:        100c701
 Built:             Sat Feb 11 17:11:34 2023
 OS/Arch:           linux/arm64
 Context:           default
 Experimental:      true

Server:
 Engine:
  Version:          20.10.17
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.19.5
  Git commit:       a89b842
  Built:            Sat Feb 11 13:33:41 2023
  OS/Arch:          linux/arm64
  Experimental:     false
 containerd:
  Version:          1.6.6
  GitCommit:        10c12954828e7c7c9b6e0ea9b0c02b01407d3ae1
 runc:
  Version:          1.1.2
  GitCommit:        a916309fff0f838eb94e928713dbc3c0d0ac7aa4
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
root@N1:~# docker images | grep uptime
louislam/uptime-kuma   1.23.11   d84df151f227   4 weeks ago     422MB

**Comment by macaty** [comment]
> Let's find commonalities. I am running Chrome 121.0.6167.85 => maybe connected with newer chrome versions?
> 
> @louislam what brower are you running? Could you retry this 2x more just to be sure that this is not also happening on your end?

yes, u are right.   It become normal when i disable NeatDownloadManager Extension
1.9.92

**Comment by macaty** [comment]
> Weird. I cannot reproduce.
> 
> 2 possible directions:
> 
> * Browser (Affected by extension?), you should try Firefox or MS Edge without extensions.
> * Something weird in your network, you can try different network like mobile network.

u are right.  it become normal where i disable NeatDownloadManager Extension.
![image](https://github.com/louislam/uptime-kuma/assets/16797633/3ba0b3e9-7e50-4982-ab89-a359295e8c55)

**Comment by baalchina** [comment]
> > Weird. I cannot reproduce.
> > 2 possible directions:
> > 
> > * Browser (Affected by extension?), you should try Firefox or MS Edge without extensions.
> > * Something weird in your network, you can try different network like mobile network.
> 
> u are right. it become normal where i disable NeatDownloadManager Extension. ![image](https://private-user-images.githubusercontent.com/16797633/300653195-3ba0b3e9-7e50-4982-ab89-a359295e8c55.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY2MjcyNzUsIm5iZiI6MTcwNjYyNjk3NSwicGF0aCI6Ii8xNjc5NzYzMy8zMDA2NTMxOTUtM2JhMGIzZTktN2U1MC00OTgyLWFiODktYTM1OTI5NWU4YzU1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTMwVDE1MDI1NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE2NzNiNTk0NTEzYWRjYmNhODk2OGQ4MDhjYWEwODU4NTUxODI5OGY2NjZjMjNlMWZhY2JmMzQ3YmIyZmM4NTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.vTrMwAAodlbX-EY_Xz6yu1ubHK9d1MwjSshSoX6DehM)

That's it! I am using netdownload too..when I open chrome in Incognito Window, or edge in private mode...the socket error disappeared both in my site and demo site...

**Comment by hrshv6** [comment]
In our case, the cause of this error was haproxy. To solve this problem, we needed to add the following two settings to our haproxy.cfg file:

![2024-04-02_192016](https://github.com/louislam/uptime-kuma/assets/5875821/ac245be0-b979-4a28-a7a0-84ddc2b35393)

Just wanted to comment in here for other people looking for a solution.

**Comment by CommanderStorm** [comment]
**Likely completely unrelated to the other posts.** NONe of them have stated that they are using haproxy.
Also that `timeout client-fin` is necessary if `timeout tunnel` is used is [documented in the docs](https://github.com/louislam/uptime-kuma/wiki/Reverse-Proxy#haproxy) ^^

Our knowledge of these niche reverse proxies is not the best and I know that that part of the docs is likely not the best => PRs from people who know more would be appreciated..

**Comment by kingfisher77** [comment]
Suddenly the same error occurs in the GUI: Connection to socket server lost. Restoring the connection...

- Calling uptime.ourdomain.com
- Login screen - red banner with Lost connection to the socket server. Connection is re-established...
- Login is possible, but the connection is immediately interrupted again
- Red banner appears again and again

The setup is done with docker compose. It has been running successfully for many months. Around 50 monitors. 

Docker log:

```
uptime-kuma | 2024-04-12T09:15:07+02:00 [AUTH] INFO: Login via token. IP=172.31.0.2
uptime-kuma | 2024-04-12T09:15:07+02:00 [AUTH] INFO: Username from JWT: admin
uptime-kuma | 2024-04-12T09:15:07+02:00 [AUTH] INFO: Successfully logged in user admin. IP=172.31.0.2
```
And it goes on like this.

We have reduced the monitor history to 1 day and emptied the database (it was about 1 GB in size) without anything changing. All browsers show the same behavior.

We are now somewhat at a loss. Does anyone have any ideas?

**Comment by Kerryliu** [comment]
Oddly, I'm also getting the same issue.  I'm not sure when this happened, as I don't usually visit the dashboard - unless a service goes down.  

Navigating to the IP directly (e.g. http://192.168.1.123:3001/) gives no issues.  

Using a reverse proxy (I'm using traefik) and navigating to something like https://uptime.mydomain.com, results in the behavior that @kingfisher77 described.

**Comment by kingfisher77** [comment]
Yes, missed to mention this. We are behind traefik too.

**Comment by chakflying** [comment]
Looks like you guys are affected by this? #4669

**Comment by Kerryliu** [comment]
Thank you! It looks like that was the issue.

**Comment by kingfisher77** [comment]
Fantastic! Thank you.

**Comment by cmbcbe** [comment]
For those who use Cloudflare Argo Tunnel, i have add similar issue until I enable the function "Disable chunked encoding"
![image](https://github.com/louislam/uptime-kuma/assets/21077157/edcbe45a-0683-4ffb-9c06-0fe2e04a3649)

Regards

**Comment by tarocjsu** [comment]
This error not just for domain name acess or reverse proxy access, also happen when direct use http://ip_address:3001/

**Comment by jjoterop** [comment]
I am having this error with GKE:

Current configuration:
uptime kuma with nginx as reverse proxy, also tried with caddy and I am facing the same issue:

Global Load Balancer with managedCerts-->Nginx/Caddy --> Uptime Kuma

If I just use a normal LoadBalancer Service everything works fine, but using a reverse proxy as SSL Termination proxy is not working as expected.

Thankyou!

**Comment by CommanderStorm** [comment]
@jjoterop "not working as expected" is not specific error mesage.
Please open a new issue (instead of piling onto a solved one).

Refer to our [reverse proxy documentation](https://github.com/louislam/uptime-kuma/wiki/Reverse-Proxy) for tips first.

**Comment by rthidden** [comment]
I am getting the same error: 'Lost connection to the socket server. Reconnecting...' I have tried it with Microsoft Edge and Google Chrome with no extensions and in private mode. I installed Uptime Kuma for the first time yesterday. I was getting the error locally yesterday and thought it was just my PC or my connection. But then I started using Uptime Kuma on PikaPods today and am still getting the error. 

I tried reloading the app from the PikaPods dashboard and logged out of the app. Now, I am not able to log in because of the error. 

Browser: 
Microsoft Edge: Version 128.0.2739.9 (Official Build) stable app, beta channel (64-bit)
Google Chrome: Version 127.0.6533.100 (Official Build) (64-bit)

From the developer tools, you can see the error keeps repeating. 
![image](https://github.com/user-attachments/assets/b7d0e0e1-7b74-49d3-a7d4-1091b43fe0d8)

**Comment by rafi** [comment]
For me, it was the `proxy_timeout` setting set too low that caused the socket disconnections.

**Comment by Yuri-NagaSaki** [comment]
> 这个错误不仅仅出现在域名访问或者反向代理访问时，直接使用http://ip_address:3001/也会发生。

Yes.

![Image](https://github.com/user-attachments/assets/8166be65-57c0-4203-bf81-e0c707cbae90)

![Image](https://github.com/user-attachments/assets/d911601d-9bb0-4669-8372-2391bff1a458)


```
docker version 27.3.1
images: louislam/uptime-kuma :1    542ef8cfcae2   3 months ago   440MB
```

**Comment by w-66** [comment]
me too

**Comment by CommanderStorm** [comment]
> Please open a new issue (instead of piling onto a solved one).
> 
> Refer to our [reverse proxy documentation](https://github.com/louislam/uptime-kuma/wiki/Reverse-Proxy) for tips first.

**Comment by ajinfajrian** [comment]
I'm using Nginx Proxy Manager, and increasing the proxy_read_timeout fixed it for me.


![Image](https://github.com/user-attachments/assets/558660cd-e016-4c0d-b37f-1bb9ee0d61e7)
