### ISSUE TITLE
How I can bypass cloudflare protection

### ISSUE THREAD

**Issue by dzeremov** [louislam/uptime-kuma#4412]
### ⚠️ Please verify that this question has NOT been raised before.

- [x] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

[
![2024-01-23 18_33_30](https://github.com/louislam/uptime-kuma/assets/148291813/b1e5345f-c8da-4d38-b71a-c8cec5d9e756)
](url)

Hi! I found that I can't monitor cloud flare protected websites. As a person I can press a checkbox in browser to access the site but how I can bypass this thing if I monitor HTTPS with Uptime Kuma? 

Sorry this might be a noob question but I didn't find an answer or similar topic. Thanks!

### 🐻 Uptime-Kuma Version

1.23.11

### 💻 Operating System and Arch

Ubuntu 22.04

### 🌐 Browser

Brave 1.61.121

**Comment by CommanderStorm** [comment]
Ask the service you are trying to monitor for a non-protected healthcheck website.

Bypassing cloudflare bot protection by bots is not something that should be possible and if it were possible we should not implement that.

**Comment by chakflying** [comment]
If you are the admin, you should be able to add Uptime Kuma to whitelist using a specific IP or some other criteria suitable to your networking setup.
