### ISSUE TITLE
don't alert for group. only for devices.

### ISSUE THREAD

**Issue by aristosv** [louislam/uptime-kuma#4415]
### ⚠️ Please verify that this question has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

I have 23 groups, and a total of 163 monitored devices in uptime kuma. There are currently 161 devices up and 2 devices down. The problem is that there's not actually 2 devices down. Only 1 device is down. The second device is actually the parent group of the device that's down. How can I configure the group to not appear as a device that's down?

### 🐻 Uptime-Kuma Version

1.23.11

### 💻 Operating System and Arch

Debian 12 x64

### 🌐 Browser

120.0.2210.144 (Official build) (64-bit)

### 🐋 Docker Version

Docker 24.0.7

**Comment by CommanderStorm** [comment]
You can switch this switch to not alert for this group:
![image](https://github.com/louislam/uptime-kuma/assets/26258709/fff92426-212a-475b-80a0-e7661a431b38)

**Comment by aristosv** [comment]
To the best of my understanding, that option defines if a notification will be sent or not. I have emails configured, and that option is OFF for all groups. The whole group still appears to be down, even through only one device in that group is down.

![2024-01-25 07_23_17-Uptime Kuma and 4 more pages - Work - Microsoft​ Edge](https://github.com/louislam/uptime-kuma/assets/528302/0f8a3eb5-4dde-4c46-9623-ed53521e344d)

**Comment by CommanderStorm** [comment]
I am sorry, I was mislead by the title

> don't alert for group. only for devices

customising if a group considers itsself `UP` or `UP` is tracked in
- https://github.com/louislam/uptime-kuma/issues/3387
- https://github.com/louislam/uptime-kuma/issues/2487
- https://github.com/louislam/uptime-kuma/issues/1089

Current progress is that #4395 is blocking any further development (at least for the `v2.1` release).
