### ISSUE TITLE
can't ping SMTP Skiff hostname and port

### ISSUE THREAD

**Issue by antonioraminhos** [louislam/uptime-kuma#4416]
i can't ping the Skiff Email Server which is `inbound-smtp.skiff.com:25` through my Uptime Kuma instance (hostname and port using TCP Port monitor), but it works if
- I ping the port and hostname through my PC
- or [`check-host.net`](https://check-host.net/check-tcp?host=inbound-smtp.skiff.com:25&csrf_token=f97320c835f675c341454979e93a76a6e9e4541d)

Configuration 

| monitoring results | configuration |
|--------|--------|
| ![image](https://github.com/louislam/uptime-kuma/assets/156920116/87bd045f-3681-4dd7-856b-772738638cdc) | ![image](https://github.com/louislam/uptime-kuma/assets/156920116/e350e46e-461b-49ab-a87b-9026f05e45b7) |

Edit: integrated comment into this message

**Comment by antonioraminhos** [comment]
![image](https://github.com/louislam/uptime-kuma/assets/156920116/e350e46e-461b-49ab-a87b-9026f05e45b7)

**Comment by antonioraminhos** [comment]
![image](https://github.com/louislam/uptime-kuma/assets/156920116/3d6baabd-4992-4de0-9fd2-a8f6f19ef69f)

**Comment by antonioraminhos** [comment]
BUMP

**Comment by chakflying** [comment]
What is the "down" message shown in the monitor events list?

**Comment by CommanderStorm** [comment]
![image](https://github.com/louislam/uptime-kuma/assets/26258709/625a77f1-2b7d-4d6d-b24a-8734979f5bbf)

`tcpping` is executed here and should default to `5s` according to their docs

https://github.com/louislam/uptime-kuma/blob/538f83205d75fdfc437bece61764e864ae90a5b0/server/util-server.js#L99-L118

Relevant docs: https://www.npmjs.com/package/tcp-ping#pingoptions-callback

**Comment by CommanderStorm** [comment]
@antonioraminhos any clues why a ping might take this long?

**Comment by antonioraminhos** [comment]
idk

**Comment by antonioraminhos** [comment]
can you try on your uptime kuma instance? i tried on the demo and it also didn't work

**Comment by CommanderStorm** [comment]
![image](https://github.com/louislam/uptime-kuma/assets/26258709/45ea11f4-7443-4235-81f1-2bdca175ce8c)

I tried this on a separate local instance and there is some weirdness going on.
I don't think this is weirdness on our end tbh. Have you got a firewall/fail2ban/... in your network path?

Is there a reason why the german educational network (eduroam) might be blocked but german resitential internet might not?

**Comment by antonioraminhos** [comment]
i don't know, but i just tried running a docker container for uptime kuma on my personal pc and it just works, but on my AWS EC2 VPS, it doesn't, maybe AWS don't allows pings to port 25? i just don't know at this point.
![image](https://github.com/louislam/uptime-kuma/assets/156920116/cf2f36c7-bda8-4818-b1f4-e9a2bfc16ae3)

**Comment by louislam** [comment]
If I understand it correctly, AWS is indeed not allowed that by default.

> On all instances, Amazon EC2 restricts outbound traffic to public IP addresses over port 25 by default.
https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ec2-resource-limits.html

In my opinion, I was always not happy with these "top-tier" VPSs. If your server is dedicated for Uptime Kuma only, I would recommend DigitalOcean or Linode.

**Comment by CommanderStorm** [comment]
I think with said wiki article clearing up why this is behaving so weird this issue is resolved
