### ISSUE TITLE
Uptime Kuma is not sending up/down notifications to Discord but "Test" notifications work

### ISSUE THREAD

**Issue by Honorme94** [louislam/uptime-kuma#4421]
### ⚠️ Please verify that this question has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

Uptime Kuma (Docker) is not sending up/down notifications to Discord but "Test" notifications work.

### 🐻 Uptime-Kuma Version

1.23.11

### 💻 Operating System and Arch

23.10 x86_64

### 🌐 Browser

Microsoft Edge 120.0.2210.144

### 🐋 Docker Version

Docker version 24.0.5

**Comment by Honorme94** [comment]
Resolved the issue on my own, user error.

**Comment by safiyykanjiyani** [comment]
What was your user error? Having the same issue

**Comment by CommanderStorm** [comment]
The first place where I would recomend you to look is if this is enabled here:
![image](https://github.com/louislam/uptime-kuma/assets/26258709/fce1f86d-4174-44c4-8aa6-8b4325b97f90)
