### ISSUE TITLE
Got "Lost connection to the socket server. Reconnecting..." everytime when I open kuma site, how can I check the log?

### ISSUE THREAD

**Issue by baalchina** [louislam/uptime-kuma#4422]
### ⚠️ Please verify that this question has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

Hi, I installed kuma by docker in a rocky 9.3 linux, with this command:
`docker run -d --restart=always -p 3001:3001 -v uptime-kuma:/app/data --name uptime-kuma louislam/uptime-kuma:1
`

But everytime when I tried open site(without login),  I got a "Lost connection to the socket server. Reconnecting..." error, after some time (maybe 1 or 2 min), the error disappare, everythings seems fine.

I tried using a reserve proxy(with config in here https://github.com/louislam/uptime-kuma?tab=readme-ov-file#advanced-installation ), or direct visite the ip:3001, still got the same error.

So, how can I check the error log?

Add:
I newly installed a fresh Rocky 9.3 server, with docker 25.0.1, and new uptime-kuma , visit using ip:3001, still got lost conneciton. And the docker logs shows the same like below.

### 📝 Error Message(s) or Log
![Snipaste_2024-01-25_21-26-24](https://github.com/louislam/uptime-kuma/assets/3983019/52860199-f19e-4c55-8891-1ee35012cb58)(docker logs, seems no error?) 

### 🐻 Uptime-Kuma Version

1.23.11

### 💻 Operating System and Arch

Rocky 9.3, docker

### 🌐 Browser

Chrome,edge,firefox

### 🐋 Docker Version

20.10.13

**Comment by CommanderStorm** [comment]
> So, how can I check the error log?

```sh
sudo docker logs uptime-kuma
```

> ![Uploading 1706161729257_d.png…](docker logs, seems no error?)

I think a file you tried to attach was not fully done uploading..

**Comment by baalchina** [comment]
> > So, how can I check the error log?
> 
> ```shell
> sudo docker logs uptime-kuma
> ```
> 
> > ![Uploading 1706161729257_d.png…](docker logs, seems no error?)
> 
> I think a file you tried to attach was not fully done uploading..

sorry, i update the attach in the origin post..

**Comment by chakflying** [comment]
I think this is more of a front-end issue, would be great if you also take a look if there are any browser console errors (but I think it's unlikely).

I also noticed that the polling connection method seems to behave a bit weird compared to before, but further investigation would require deeper knowledge of how socket.io works first.

**Comment by baalchina** [comment]
> I think this is more of a front-end issue, would be great if you also take a look if there are any browser console errors (but I think it's unlikely).
> 
> I also noticed that the polling connection method seems to behave a bit weird compared to before, but further investigation would require deeper knowledge of how socket.io works first.

![Snipaste_2024-01-25_22-39-31](https://github.com/louislam/uptime-kuma/assets/3983019/3384e11d-d032-4984-bbbd-e8680bce4ce4)


This is the chrome console error. In this picture I got 2 error then seems connected, and kuma works fine. In some other times will be more and more same error...

**Comment by chakflying** [comment]
400 seems connected to #4409.

**Comment by CommanderStorm** [comment]
continuing to debug this in #4409 as I think they are the same issue.
If during said process we discover that this is a different issue, we will reopen
=> closing as duplicate
