### ISSUE TITLE
Restored DB - Dashboard shows hosts are down (Ping/HTTP monitors) but they are up - doesnt update

### ISSUE THREAD

**Issue by JackieTreeh0rn** [louislam/uptime-kuma#4424]
### ⚠️ Please verify that this question has NOT been raised before.

- [x] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

I am running on docker stack using a gluster volume mapped on all swarm nodes and with zero backlog.   this allows for service to respawn on any node, it works quite well, however...

- Compose bind:
`/mnt/glustervol/uptime-kuma/data:/app/data`

-  I take down stack to make db backup (all services and monitors are up at the time of backup):
`docker stack rm uptime-kuma`

- I backup db data folder
`cp -av ./data/*  ./data_bak`

- I restore db back up
 `cp -av ./data_bak/* ./data`

- I redeploy stack (all services are monitors already up -  same state as during backup)
`docker stack deploy -c docker-compose.yml uptime-kuma`

Service starts, shows all my monitors, etc, but only a few hosts report as UP eventhough they are ALL up.   No issue reported on service log, just that hosts are down.  Tried editing monitors just to re-save, and no difference. 

what gives?

### 🐻 Uptime-Kuma Version

image: louislam/uptime-kuma:1

### 💻 Operating System and Arch

Ubuntu 23.10 / Docker latest

### 🌐 Browser

Safari

### 🖥️ Deployment Environment

- Runtime: 
- Database: 
- Filesystem used to store the database on: 
- number of monitors:

**Comment by chakflying** [comment]
What are the error messages of the monitors down as down?

**Comment by JackieTreeh0rn** [comment]
on the dashboard.  everything is restored, all my monitors etc.  bu only a handful of hosts show as being UP.  the logs for the service just show standard ouput (hosts down to ping, etc) I reboot the hosts anyway to see if it resets somehow but nothing.  I basically end up having to delete all my monitors, recreate them from scratch if that makes sense
