### ISSUE TITLE
what are the correct values for each setting in uptime kuma?

### ISSUE THREAD

**Issue by aristosv** [louislam/uptime-kuma#4428]
### ⚠️ Please verify that this question has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

I've used this command to bulk change the "Heartbeat Interval" on all the monitors, because they are too many to change one by one. (currently 671)

`sqlite3 kuma.db "UPDATE monitor SET interval = 120;"`

I also did the same with "Retries" using this command.

`sqlite3 kuma.db "UPDATE monitor SET maxretries = 3;"`

Both times it worked like a charm.

Now I want to change the "Heartbeat Retry Interval", so I exported the .json file and saw that the value for "Heartbeat Retry Interval" is "retryInterval"

So I run this command

`sqlite3 kuma.db "UPDATE monitor SET retryInterval = 3;"`

But I get this message

`Error: no such column: retryInterval`

I'm guessing that since the backup feature is deprecated, the values I'm seeing in the .json file might be incorrect.

So the question is, how can I see the correct values for each setting in uptime kuma? Or is there a better way to make bulk changes?

### 📝 Error Message(s) or Log

`Error: no such column: retryInterval`

### 🐻 Uptime-Kuma Version

Version: 1.23.11

### 💻 Operating System and Arch

Debian 12 x64

### 🌐 Browser

Edge Version 120.0.2210.144 (Official build) (64-bit)

### 🖥️ Deployment Environment

- Runtime: Docker: 24.0.7 / nodejs v18.19.0
- Database:  sqlite
- Filesystem used to store the database on:  ext4
- number of monitors: 671

**Comment by chakflying** [comment]
The column name should be `retry_interval`. In general, you can open the .db in any SQLite compatible software to see the table structure.
