### ISSUE TITLE
HTTPS Certificate Expiry Notification for host behind traefik with letsencrypt certificate

### ISSUE THREAD

**Issue by Menthe11** [louislam/uptime-kuma#4429]
### ⚠️ Please verify that this question has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

When creating a certificate expiry notification for a host behind traefik with an certificate from letsencrypt i get this error message.

### 📝 Error Message(s) or Log

write EPROTO 00C83F317A7F0000:error:0A000410:SSL routines:ssl3_read_bytes:sslv3 alert handshake failure:../deps/openssl/openssl/ssl/record/rec_layer_s3.c:1586:SSL alert number 40 

### 🐻 Uptime-Kuma Version

1.23.11

### 💻 Operating System and Arch

Rocky Linux 9.3

### 🌐 Browser

Firefox 122.0 / Edge 121.0

### 🖥️ Deployment Environment

- Runtime: Docker 24.0.7 build afdd53b

**Comment by Menthe11** [comment]
DNS resolver error...

**Comment by myrp-andre** [comment]
> DNS resolver error...

Hi, how did you resolve it?
