### ISSUE TITLE
Add multiple Docker sockets

### ISSUE THREAD

**Issue by casudo** [louislam/uptime-kuma#4431]
### ⚠️ Please verify that this question has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

How can I add multiple docker sockets? Currenty I am running Uptime Kuma on VM1, which runs Docker. I can monitor these containers just fine.

Is there a way to add the Docker socket for my VM2 and VM3 to also monitor the containers directly?

### 🐻 Uptime-Kuma Version

v1.23.11

### 💻 Operating System and Arch

Ubuntu 22.04

### 🌐 Browser

Firefox

### 🖥️ Deployment Environment

- Runtime: Docker
- Database:  sqlite
- Filesystem used to store the database on: ZFS on HDD
- number of monitors: too many

**Comment by CommanderStorm** [comment]
Exposing the sockets like this is not something that I would recomend for security reasons.

Please refer to method 2 instead: https://github.com/louislam/uptime-kuma/wiki/How-to-Monitor-Docker-Containers#method-2-tcp---bridge-mode
