### ISSUE TITLE
Is it possible to customize the time span of status history?

### ISSUE THREAD

**Issue by lwabish** [louislam/uptime-kuma#4435]
### ⚠️ Please verify that this question has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

In status pages, the time span of my service status is 36/37 min.
I wonder how is this decided? Didn't find any doc about this nor any config in settings.Also hard to decide keyword to search this problem in issue, so I have to ask here.But I think this should be a regular feature, sorry If this is duplicated.

### 🐻 Uptime-Kuma Version

1.23.11

### 💻 Operating System and Arch

ubuntu

### 🌐 Browser

edge 121.0.2277.83

### 🖥️ Deployment Environment

- Runtime: docker
- Database: 
- Filesystem used to store the database on: 
- number of monitors: 2

**Comment by CommanderStorm** [comment]
The displayed time span ins currently based around the monitoring interval.
In v2 the part of the system responsible for this has been significantly changed and adding this feature is now possible.
This feature is tracked in #1167
Our [contribution guide is here](https://github.com/louislam/uptime-kuma/blob/master/CONTRIBUTING.md)

=> closing as a duplicate

**Comment by lwabish** [comment]
Thanks for your reply.
