### ISSUE TITLE
Service stopped working, Dashboard works fine 

### ISSUE THREAD

**Issue by Ingo-Knito** [louislam/uptime-kuma#4439]
### ⚠️ Please verify that this question has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

I have installed uptime-kuma a couple of months ago and it worked perfekt.
Now, a couple of weeks later, two active monitors are not working anymore.

According to the dashboard, both are active and the url is also accessible.
But the statistics are not updated anymore and the last check was 14 days ago.
The dashboard looks ok.

### 📝 Error Message(s) or Log

![image](https://github.com/louislam/uptime-kuma/assets/39132657/917b2bc5-ea56-4dd6-99b7-31ec54409096)

### 🐻 Uptime-Kuma Version

1.23.3

### 💻 Operating System and Arch

RASPI, Debian Bookworm 

### 🌐 Browser

Chrome 

### 🖥️ Deployment Environment

- Runtime: 
- Database: 
- Filesystem used to store the database on: 
- number of monitors: 2

**Comment by CommanderStorm** [comment]
What does the log say?
What is your Deployment Environment?

**Comment by chakflying** [comment]
Please update the application to the latest version. Older versions of 1.23.X had issues were HTTP monitors could get stuck due to timeouts. (see #3952) This should be fixed in the latest version.

**Comment by CommanderStorm** [comment]
Good catch.
I am going to close this issue as resolved.
@Ingo-Knito if this issue persists on newer versions, we can reopen this issue ^^

**Comment by Ingo-Knito** [comment]
Ok, thanks for your help!

I will try (again) to update. Actual the update fails.
I'm running it as a service. It looks like the "mv" during the installation causes this problem. But this is an other issue...

**Comment by chakflying** [comment]
That's very interesting. We never found the root cause of the original issue. I wonder if the system time jumping backwards / getting too out of sync would somehow break node.js's timers.
