### ISSUE TITLE
Push Monitor in `down` not using a `&msg=` value for notification

### ISSUE THREAD

**Issue by ww7** [louislam/uptime-kuma#4440]
### 📑 I have found these related issues/pull requests

Didn't find similar feature request.

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### Description

I'm using Push Monitor with custom `&msg=somemessage` and with `&status=up` somemessage is shown at notification alert and events, but with `?status=down` it only prints `No heartbeat in the time window`

### 👟 Reproduction steps

Send POST to
`https://example.com/api/push/token/?status=up&msg=disk%20space%20${3}%25&ping=`
`https://example.com/api/push/token/?status=down&msg=disk%20space%20${3}%25&ping=`

### 👀 Expected behavior

Expected to receive custom message also with `?status=down` 

### 😓 Actual Behavior

Receiving default `No heartbeat in the time window`

### 🐻 Uptime-Kuma Version

1.23.11

### 💻 Operating System and Arch

Ubuntu 20.04 LTS

### 🌐 Browser

Google Chrome

### 🖥️ Deployment Environment

Docker version 24.0.7

**Comment by CommanderStorm** [comment]
Currently setting the status via the push monitor is not supported.
See https://github.com/louislam/uptime-kuma/issues/1386 for further details
Our contribution guide is here: https://github.com/louislam/uptime-kuma/blob/master/CONTRIBUTING.md

=> closing as a duplicate

**Comment by ww7** [comment]
@CommanderStorm 

1. it works already, we can set status `up` or `down` via Push Monitor
2. my request is about using/forwarding `&msg=` for `down` status to the event/notification

Please reopen this issue as Bug or Feature request

**Comment by CommanderStorm** [comment]
Looking into the code, indeed status is already supported:

https://github.com/louislam/uptime-kuma/blob/3cea7d4eb23eb69140a79f2eb58d1d45a98dc88e/server/routers/api-router.js#L53C13-L53C25

**Comment by CommanderStorm** [comment]
Cannot reproduce this not working though:

![image](https://github.com/louislam/uptime-kuma/assets/26258709/3e0eff66-3e97-4a8e-a76a-7275d01dd477)


- https://demo.kuma.pet/api/push/S4HVNJ6Lle?status=down&msg=abc&ping=213
- https://demo.kuma.pet/api/push/S4HVNJ6Lle?status=up&msg=abc&ping=213
- don't send a ping in this timeslot
- https://demo.kuma.pet/api/push/S4HVNJ6Lle?status=up&msg=disk%20space%20${3}%25&ping=213
- https://demo.kuma.pet/api/push/S4HVNJ6Lle?status=down&msg=disk%20space%20${3}%25&ping=213

**Comment by ww7** [comment]
@CommanderStorm 
Sorry about the mistake, it works!

**Comment by EDIflyer** [comment]
I can get up and down to work OK but msg isn't being passed through for me? On v1.23.13
Have tried `msg=sometext` and also `msg="some text"` but only get an OK regardless...
![image](https://github.com/louislam/uptime-kuma/assets/13610277/21936762-ba83-4f58-83f7-86734ad93b4e)

**Comment by CommanderStorm** [comment]
Again: cannot reproduce

https://demo.kuma.pet/api/push/bwOJKeirIF?status=up&msg=FALSE&ping=
![image](https://github.com/louislam/uptime-kuma/assets/26258709/93bde1d9-8aa5-4283-90a6-6d0a99d854e5)

Could you share your setup?
I suspect you have a second `?msg=OK` somewhere or are encoding the url wrong..

**Comment by EDIflyer** [comment]
Thanks for the quick reply and interesting!

After you said it was working OK for you I've tried again and interestingly found it I post the request in my browser it does indeed update the message, however if I just enter a straight `curl` request from the command line on my Ubuntu machine although I get a `{"ok":true}` response it doesn't seem to process the msg. So perhaps it's around how the URL is called?

Curl request I'm using is `curl https://status.ediflyer/api/push/FhlIVwTOL0?status=up&msg=testup&ping=`

**Comment by EDIflyer** [comment]
OK so turns out putting quotes around the entire string seems to have the desired effect!
