### ISSUE TITLE
Docker Container State and Status not updating when UP (only updating when Down)

### ISSUE THREAD

**Issue by n1njaznutz** [louislam/uptime-kuma#4441]
### ⚠️ Please verify that this question has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

New to Uptime Kuma. Installed via Docker on Synology NAS. Docker Host correctly configured and added some Docker Containers. Set up Notifications (via Discord and Pushover).  When I stop a Docker Container, UK is correctly reporting the Down status and notification is triggered.

However, when I Start the Container, the Status and latest Message remains as Down despite the container being back up and running.  I expected these message to update and a further notification be generated confirming the container being back up - Quick Stats does show the correct number of containers being up.

Any help appreciated.

![Screenshot 2024-01-31 162139](https://github.com/louislam/uptime-kuma/assets/150074096/5dac5c74-acaf-4f67-8056-ce24a98ecf3a)

![Screenshot 2024-01-31 162218](https://github.com/louislam/uptime-kuma/assets/150074096/a94720b5-17b0-4010-9494-d300fc29c1f0)

### 🐻 Uptime-Kuma Version

1.23.11

### 💻 Operating System and Arch

Synology DS224+

### 🌐 Browser

Chrome 121.0.6167.86 (Official Build) (64-bit)

### 🖥️ Deployment Environment

- Runtime:  Container Manager 20.10.23-1437
- Database: 
- Filesystem used to store the database on: Synology DSM 7.2.1-69057 Update 3
- number of monitors:

**Comment by CommanderStorm** [comment]
how are you starting docker containers?
Are you using `docker start` (this one re-activates the existing container) or `docker run` (this one creates a new container)?

**Comment by n1njaznutz** [comment]
> how are you starting docker containers? Are you using `docker start` (this one re-activates the existing container) or `docker run` (this one creates a new container)?

Stopping and Starting via Portainer.  Stopping works as expected. Starting does not.  As per screenshot - UK reports the container is Up but the latest status and message still show Down.

**Comment by CommanderStorm** [comment]
I am not familiar with portainer and don't know which of the two mentioned methods they use.

When you start/stop, does this change the Container Name / ID?
(also: Which of the two are you using to monitor the container?)

What is the log output?

**Comment by chakflying** [comment]
This is a limitation of the current logic. If the status transitions from pending to up, the heartbeat is not considered as "important", and will not be shown in the list.

**Comment by chetan232** [comment]
I have the same issue anyone explain to me how to do that when some site is down then Uptime Kuma say **down** and when some site up Kuma says **up** in Discord ?? please help thank you
