### ISSUE TITLE
Email Notification Not Working

### ISSUE THREAD

**Issue by denispollini** [louislam/uptime-kuma#4443]
### ⚠️ Please verify that this question has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

Can't send notication email.

### 📝 Error Message(s) or Log

```log
Error: Connection timeout
    at SMTPConnection._formatError (/app/node_modules/nodemailer/lib/smtp-connection/index.js:784:19)
    at SMTPConnection._onError (/app/node_modules/nodemailer/lib/smtp-connection/index.js:770:20)
    at Timeout.<anonymous> (/app/node_modules/nodemailer/lib/smtp-connection/index.js:229:22)
    at listOnTimeout (node:internal/timers:569:17)
    at process.processTimers (node:internal/timers:512:7) {
  code: 'ETIMEDOUT',
  command: 'CONN'
}
```

### 🐻 Uptime-Kuma Version

Versione: 1.23.11

### 💻 Operating System and Arch

Debian GNU/Linux 10 x86_64

### 🌐 Browser

Brave

### 🖥️ Deployment Environment

- Runtime: Docker version 23.0.2, build 569dd73 
- Database: 
- Filesystem used to store the database on: 
- number of monitors:

**Comment by SuperDexter23** [comment]
The version of uptime kuma is random because i don't know how to check in docker container

**Comment by apio-sys** [comment]
Probably some issue with your underlying mail system. It really depends on what you are using for sending out email. A local sendmail() or exim or postfix, an external SMTP mail relay controlled by yourself or external, etc. Without that info and some initial troubleshooting steps hard to answer or help I think.

**Comment by CommanderStorm** [comment]
Sorry, but we can't support version `1.10.0`. Said release was made a while ago and digging into said code is not maintainable for us.

> The version of uptime kuma is random because i don't know how to check in docker container

I don't quite get what you are trying to tell us here.
If you are asking for a guide on how to update, please check here: https://github.com/louislam/uptime-kuma/wiki/%F0%9F%86%99-How-to-Update

> [!NOTE]
> the deployed version is also visible here:
> ![image](https://github.com/louislam/uptime-kuma/assets/26258709/0570eda0-f732-4845-abd9-72cbafa7a995)

For your actual issue, please ensure that you are using the exact configuration as in your mail program and that said configuration works there.

These might be related (without additional context from your side, we are unable to tell more..):
- #1713
- #2793

**Comment by SuperDexter23** [comment]
> Sorry, but we can't support version `1.10.0`. Said release was made a while ago and digging into said code is not maintainable for us.
> 
> > The version of uptime kuma is random because i don't know how to check in docker container
> 
> I don't quite get what you are trying to tell us here. If you are asking for a guide on how to update, please check here: https://github.com/louislam/uptime-kuma/wiki/%F0%9F%86%99-How-to-Update
> 
> Note
> 
> the deployed version is also visible here: ![image](https://github.com/louislam/uptime-kuma/assets/26258709/0570eda0-f732-4845-abd9-72cbafa7a995)
> 
> For your actual issue, please ensure that you are using the exact configuration as in your mail program and that said configuration works there.
> 
> These might be related (without additional context from your side, we are unable to tell more..):
> 
> * [[smtp] Office 365 authentication #1713](https://github.com/louislam/uptime-kuma/issues/1713)
> * [Send mail via the systems mail subsystem #2793](https://github.com/louislam/uptime-kuma/issues/2793)

I check my uptime kuma version and modify the 1st post

**Comment by SuperDexter23** [comment]
This is my Uptime Kuma Configuration:
![image](https://github.com/louislam/uptime-kuma/assets/81813145/d47fd6d9-61a6-4d4a-8201-76d40b8195e2)

**Comment by SuperDexter23** [comment]
hi any news about it?

**Comment by jspatel** [comment]
I am running into same issue. As soon as I press test button for the SMTP mail, it throws error on docker console log. I am running 1.23.11. 

```
Error: Connection timeout
    at SMTPConnection._formatError (/app/node_modules/nodemailer/lib/smtp-connection/index.js:784:19)
    at SMTPConnection._onError (/app/node_modules/nodemailer/lib/smtp-connection/index.js:770:20)
    at Timeout.<anonymous> (/app/node_modules/nodemailer/lib/smtp-connection/index.js:229:22)
    at listOnTimeout (node:internal/timers:569:17)
    at process.processTimers (node:internal/timers:512:7) {
  code: 'ETIMEDOUT',
  command: 'CONN'
}
```

I have checked the mail server and it is working fine. I also reset the password to ensure that it is not a typo. 
I am using the hosted mail server provider and I have plenty of other emails in the same domain working fine. Uptime Kuma can't simply connect and send out the test email.

**Comment by CommanderStorm** [comment]
I think I was unclear.
Could you try via https://github.com/louislam/uptime-kuma/wiki/Troubleshooting this is a networking issue on the path to your mail server and/or give us more intel on how to reproduce this (mail provider).
Currently, I cannot reproduce the mail notifications not working…

**Comment by axiomcs78** [comment]
Mail notif. are not working here either.  Trying gmail.  What email provider(s) are you using or which ones are known to work?
After setting it up, immediately after clicking Save I get the error msg "querya etimeout".  Also happens with an MS365 email address.  (hmm, I no longer see the ability to create Email monitors)

**Comment by nicopowa** [comment]
Same error here, running Uptime Kuma and [Docker MailServer](https://docker-mailserver.github.io/docker-mailserver/latest/) running on the same machine.

Communications are blocked by ufw, which seems to be a known issue out there, lots of things to read before choosing the right conf.

`[UFW BLOCK] IN=docker0 OUT= SRC={UPTIME_KUMA_CONTAINER_IP} DST={HOST_PUBLIC_IP} ... DF PROTO=TCP SPT=36832 DPT=465`

**Comment by talaikis** [comment]
AWS S3 doesn't work too while everything works fine elsewhere.

**Comment by Matthias-Roth-SWE** [comment]
I have the same issue after moving to a new server. Same Uptime Kuma Version on both servers: 1.23.17. Same settings in Uptime Kuma: I copied the volume from the old server to the new server. 

Old server: 
- Ubuntu 20.04.6
- Docker version: 28.1.1
- containerd version: 1.7.27
- runc version: 1.2.5

New server:
- Ubuntu 24.04.3
- Docker version: 28.5.2
- containerd version:  1.7.29
- runc version: 1.3.3

docker inspect shows only 2 differences:

Old Server:
- "CgroupnsMode": "host",
- "OomKillDisable": false,

New server:
- "CgroupnsMode": "private",
- "OomKillDisable": null,
