### ISSUE TITLE
Add Cookie check / monitor

### ISSUE THREAD

**Issue by kamuffe** [louislam/uptime-kuma#4448]
### 📑 I have found these related issues/pull requests

Nothing found

### 🏷️ Feature Request Type

New monitor, Change to existing monitor

### 🔖 Feature description

It would be nice if we could add a check to verify that a certain cookie is configured the right way. e.g. add checks for a "SID" cookie that the secure flag is set to true or httpOnly is also set to true.
Background:
Due to a framework update we lost these configurations and suddenly the flags were wrong at the cookies. So it would be nice if in such a case Uptime Kuma would alert us. It's also similar to the feature "Monotor SSL Cetificates" wich is already available.

### ✔️ Solution

It is possible to add one or more cookie checks with a configurable cookie name and add 1 or more properties per cookie which are checked.

### ❓ Alternatives

Nothing found.

**Comment by CommanderStorm** [comment]
Monitoring cookies is covered in #3568 and I don't see an immediate difference in capability.
=> closing as a duplicate

In parallel, we are converting the `json-query` and `keyword` monitors into generic pieces.
This will make implementing something like #3568 a lot easier.
You can subscribe to/read these issues for further context/intel:
- https://github.com/louislam/uptime-kuma/pull/3919
- #3568
- #4445

We can reopen if you make a good argument why this cannot be covered by a `header-query` monitor.
