### ISSUE TITLE
Crontab through uptime kuma

### ISSUE THREAD

**Issue by bbenjamin-sys** [louislam/uptime-kuma#4449]
### 📑 I have found these related issues/pull requests

#1117 is the outcome that comes closest. But it doesn't specifically provide what's needed. 

### 🏷️ Feature Request Type

New monitor

### 🔖 Feature description

Hello ,

I'm an avid user of Uptime Kuma for monitoring my web services, and I've found it incredibly useful for keeping track of uptime and performance. I have a suggestion for a new feature that I believe would greatly enhance its capabilities: the monitoring of cron scripts running on Linux systems.

Many systems and applications rely on cron jobs for routine tasks and maintenance. Being able to monitor these scripts directly from Uptime Kuma would provide users with a more holistic view of their system's health and reliability.

### ✔️ Solution

 This feature could include:

- Monitoring the execution status of each cron job (success or failure).
- Tracking the execution time and alerting if a script takes longer than expected.
- Addition an history
- Add it to the alerting system
- Optionally capturing and displaying the output of the script for debugging purposes.

This feature would be particularly useful for system administrators and developers who manage backend processes that are critical to their operations.

### ❓ Alternatives
I've found tools like crontab_ui or cronicle that come close, but are no longer maintained. 

The others are tools that are not self-hosted and therefore not very trustworthy.

**Comment by CommanderStorm** [comment]
I am going to close this issue as a duplicate of #1482 which has this PR open #3447

The remaining issues should be split into actual issues. An explaination/rationale why I think the points mentioned are not worth this issue staying open (subtracting the points covered by #1482):

> - Monitoring the execution status of each cron job (success or failure).

Push monitors can report the status via the `status=down` or `status=up` query parameter

> - Tracking the execution time and alerting if a script takes longer than expected.

Push monitors can report the ping/latency/execution time via the `ping=NUMBER` or `ping=NUMBER` query parameter

> - Addition an history

Unclear what is meant, I think already implemented

> - Add it to the alerting system

Monitors are part of the alerting system. Unclear what is meant by this point.


> - Optionally capturing and displaying the output of the script for debugging purposes.

Push monitors can report the message via the `msg=MSG` query parameter

If I misunderstood one/some of your points, we are (obviously) open to a discussion and can reopen the issue ^^

**Comment by chakflying** [comment]
I think "monitoring cron jobs" and "running monitors on a cron schedule" are 2 slightly different things, with one depending on the other to work.

Whether an active solution, instead of manually configuring push monitors, would be possible, is a different problem and requires investigation.

**Comment by chakflying** [comment]
Taking a look at [croniter's guide](https://cronitor.io/guides/cron-jobs), it looks like an active solution would still need to modify the jobs to insert HTTP pings to report the job status. In that sense the Push monitor already covers this use case fairly well.

**Comment by Yohannfra** [comment]
Hi,

If anyone is interested I created [cron-kuma-pusher](https://github.com/Yohannfra/cron-kuma-pusher) it's a cron wrapper utility to push the result of the job to uptime-kuma.

It's been running fine in production for the past two weeks for me for about ten jobs.
