### ISSUE TITLE
Auto-Clear all statistics after X days

### ISSUE THREAD

**Issue by gaby** [louislam/uptime-kuma#445]
**Is it a duplicate question?**
No

**Is your feature request related to a problem? Please describe.**
Currently there's no limit to how many statistics are kept for all monitors. this can lead to disk usage issues when having too many monitors.

We currently have around 200-300 monitors, we have no need to keep data after let's say 30 days? It would be beneficial to have an options in the settings page to auto-clear statistics after X days. 

Even more useful would be to add an env variable to set a default "auto-clear" statistics.

**Describe the solution you'd like**
Ability to select an maximum amount of days to keep statistics for.

**Describe alternatives you've considered**
My current solution is to, backup my monitors, delete the database and import the backup again.

**Comment by Ponkhy** [comment]
Yea that's on my todo list pretty much on the first place, will do a PR next week about this.

**Comment by gaby** [comment]
@Ponkhy Thank you!

**Comment by chakflying** [comment]
I have been wanting to add a job scheduler for running non-critical background tasks, which would be a great foundation for this and future TLS expiry notification support. [Bree](https://jobscheduler.net/) looks promising in particular.

**Comment by Ponkhy** [comment]
Ohh yea it actually does look good. 
I haven't started yet so i could wait until you've implemented it.
