### ISSUE TITLE
Edge sinking structure adjustment

### ISSUE THREAD

**Issue by jidixuelangas** [louislam/uptime-kuma#4454]
### ⚠️ Please verify that this question has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

Hello, our network has several regions, some of which cannot be directly connected to the Internet. I want to ask whether there are plans, plans, and architecture designs that consider the edge sinking structure

### 🐻 Uptime-Kuma Version

1.23.11

### 💻 Operating System and Arch

Rocky Linux 9

### 🌐 Browser

Google 120

### 🖥️ Deployment Environment

- Runtime: 
- Database: 
- Filesystem used to store the database on: 
- number of monitors:

**Comment by CommanderStorm** [comment]
I have no clue what @jidixuelangas is asking in this issue and they are not really responding to my comment..
=> closing as not planned
