### ISSUE TITLE
Non-Collapsed Microsoft TEAMS alerts

### ISSUE THREAD

**Issue by petercharleston** [louislam/uptime-kuma#4457]
### ⚠️ Please verify that this question has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

For a month or so the UpTime Kuma alerts to TEAMS have been presented as collapsed so need to click on 'see more' to view the alert.
It is using the same Web hook as before.
So the alert could be a cert expiring issue or monitor down but this can only be determined by selecting 'see more'
![image](https://github.com/louislam/uptime-kuma/assets/44698386/f41374b1-ed99-4328-b152-2f5fd3ad4087)

### 🐻 Uptime-Kuma Version

1.23.11

### 💻 Operating System and Arch

ubuntu 22.04

### 🌐 Browser

any browser

### 🖥️ Deployment Environment

- Runtime: Docker
- Database: SQLite
- Filesystem used to store the database on: linux
- number of monitors: 320

**Comment by dierkerZebralog** [comment]
We have the same problem. I think Microsoft changed something on their side. I found this https://answers.microsoft.com/en-us/msteams/forum/all/disable-auto-collapse-of-conversation-threads/7a62f765-f272-488b-9095-9d5ea617e16f thread and this option to vote for a feature to expand all messages.

https://feedbackportal.microsoft.com/feedback/idea/51e28c2d-f795-ec11-a81c-000d3a0f04fc

**Comment by CommanderStorm** [comment]
@dierkerZebralog the page you linked is likely not relevant. Said issue was opened 1y ago and the feeedback form has likely been closed in the meantime.
![image](https://github.com/louislam/uptime-kuma/assets/26258709/d13836cd-5bcf-46b4-a927-9cee79e50ca4)

**Comment by CommanderStorm** [comment]
A more likely culprit is that the webhook they expect looks different to what we send.
Here is what they expect https://learn.microsoft.com/de-de/microsoftteams/platform/webhooks-and-connectors/how-to/add-incoming-webhook?tabs=dotnet
Here is what we send:
https://github.com/louislam/uptime-kuma/blob/56aa81e337043d4efa76c46dd7dc8320c9688398/server/notification-providers/teams.js#L74-L94

TBH, this monitor does not really fit into the coding style of the other monitors and likely needs an overhaul.
If somebody wants to do this work, here is our contribution guide: https://github.com/louislam/uptime-kuma/blob/master/CONTRIBUTING.md
Currently, the core-maintainer team is quite slim, and we have different things on our priority lists, fixing the remaining bugs in v2.0 and reviewing the other pull requests that have piled up during said merge window.
⇒ help in this area by somebody who can test this against a teams account would be appreciated.

**Comment by taschenuhr** [comment]
The issue was bugging me, too. And as you, @CommanderStorm, invited to help with this issue, I've happy to do so and prepared the PR #4538, that should solve both issues mentioned above.
