### ISSUE TITLE
Using ipv6 for the uptime-kuma web ui results in timeouts

### ISSUE THREAD

**Issue by philipwilk** [louislam/uptime-kuma#4459]
### ⚠️ Please verify that this question has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

I have two monitors running against my services and they work fine. However, the web ui constantly gave me 503s when haproxy was trying to get to uptime-kuma, and a monitor of itself shows that the web ui is almost constantly inaccessible.
I had haproxy  forwarding ipv4 and ipv6 requests to my domain to uptime-kuma, but I remembered having issues with some other node app and ipv6 in the past so I turned off routing of the domain via ipv6 to uptime-kuma and this fixed it. This is visible in the monitor (for itself) here. The blip in the green at 17:50 is when i switched the ipv6 backend in haproxy back on to verify, and then turned it back off.
![image](https://github.com/louislam/uptime-kuma/assets/50517631/23dd8d74-1070-4330-ba19-f74d1e85eef3)

**The only change i made was disable access via ipv6**, and it now works flawlessly.
This is curious, as the nextcloud and navidrome monitors I have set up are both also being routed by this same haproxy server, also for both ipv4 and ipv6, to the same ipv4 ip and ipv6 ip of this host server. Something about allowing access to the ui over ipv6 simply breaks it and I don't know why, since there's no errors in the systemd service, and the web ui just says that the websockets lost connection or i just get a haproxy 503.

I realise that I'm running an out of date version so im gonna update it and get back with the result, but I dont see anything in the patch notes between .8-.11 of something like this being resolved.

### 🐻 Uptime-Kuma Version

1.23.7

### 💻 Operating System and Arch

Nixos 23.11

### 🌐 Browser

Firefox 121

### 🖥️ Deployment Environment

- Runtime: 18.18.2 (not 100% sure which point release it's on)
- Database: sqlite
- Filesystem used to store the database on: ext4
- number of monitors: 3

**Comment by philipwilk** [comment]
> When you are saying that you are getting erros, I am assuming you are monitoring websites which don't have either ipv4 or ipv6 support, even though the DNS response says they have.
> 
> Currently, if a http monitor check is made, it is not possible to control if this check is done via ipv6 or ipv4.
> 
> This is mostly because `axios` does not have great support for ipv6.
> 
> See these issues instead:
> 
>     * [axios parsed IPv6 as hostname (through proxy) #3564](https://github.com/louislam/uptime-kuma/issues/3564)
> 
>     * [IPv6 + IPv4 switch to see if both are healty #1242](https://github.com/louislam/uptime-kuma/issues/1242)
> 
>     * [IP version switch `IPv4`/`IPv6` #1025](https://github.com/louislam/uptime-kuma/issues/1025)
> 
> 
> => closing as a duplicate If I misunderstood something, we can reopen ^^

No, this is not an issue with the monitor, this is an issue with the web gui interface for uptime-kuma. When trying to access the web gui via ipv6, it results in the entire web gui becoming inaccessible from any device for some time. I am sure this is not a config issue with my reverse proxy as the other two websites i monitor with uptime-kuma are using the same configuration (be it on different ports over haproxy) on the same server with the same ips and are both accessible via ipv6, while uptime kuma is not.

**Comment by CommanderStorm** [comment]
Could you share your full configuration? (more specific, what have you set as the [`timeout` values documented here](https://github.com/louislam/uptime-kuma/wiki/Reverse-Proxy#haproxy))

I cannot reproduce ipv6 not working via 

```bash
docker run -it -p 3001:3001 louislam/uptime-kuma:1.23.11
```

![image](https://github.com/louislam/uptime-kuma/assets/26258709/3a8909fa-8cec-4998-a9f9-5b89bff711ad)

=> I assume this is haproxy having a problem with uptime kuma.

**Comment by philipwilk** [comment]
As far as I know, they are set to the haproxy defaults;
![image](https://github.com/louislam/uptime-kuma/assets/50517631/6ab3dd2a-c731-4162-8c11-934b049dd1ae)
The backends look like they're exactly the same except for the port for me as well 
![image](https://github.com/louislam/uptime-kuma/assets/50517631/93e713c7-ca9f-47e8-be0c-f4386aa555e1)

**Comment by CommanderStorm** [comment]
Managing this level of different software is really difficult for me. I have never used haproy.
@Computroniks you added this in https://github.com/louislam/uptime-kuma-wiki/pull/4
Do you have pointers where this issue might be coming from?

This might be a case of misleading/bad docs:
Could you try the [`timeout tunnel`](https://github.com/louislam/uptime-kuma/wiki/Reverse-Proxy#haproxy) options?

**Comment by chakflying** [comment]
It seems weird to me that you are using `vaultwarden-ipv6` as the server for the ipv6 config. The port is also different, which suggest to me that you have configured that line incorrectly. Please check that you are using the correct ipv6 address and port.

**Comment by CommanderStorm** [comment]
good catch!

**Comment by philipwilk** [comment]
Oops, I must have pressed the wrong button when reenabling the backend to send a sc of the config (I undid the ipv6 config after seeing it wasnt working so I had to add it back). Before I wrote this issue, the config was like this:
![image](https://github.com/louislam/uptime-kuma/assets/50517631/f6c44d6e-9f0c-4b81-a79e-b57fae1e79d8)

Sorry but the issue still stands 😄

**Comment by CommanderStorm** [comment]
> the issue still stands

My remark about trying out a different `timeout` configuration also still stands 😄 (see https://github.com/louislam/uptime-kuma/issues/4459#issuecomment-1933208339)

<img src="https://media2.giphy.com/media/bcrOR2stk6tKIxqPOZ/giphy.gif"/>

**Comment by philipwilk** [comment]
Sorry, I  didn't have enough time at the moment to test that 😅 
I've added it do the default part of the config  (wasnt sure what time to set it to so i put it at 60s) and it doesn't seem to have made a difference (still 503s from haproxy)

I have also noticed this behaviour also occurs with vaultwarden, but not with nextcloud, grafana or navidrome. Here's my entire haproxy config in case I'm overlooking something obvious. 
Also, I am using haproxy on opnsense, while uptime-kuma is on a different nixos server.
```
#
# Automatically generated configuration.
# Do not edit this file manually.
#

global
    uid                         80
    gid                         80
    chroot                      /var/haproxy
    daemon
    stats                       socket /var/run/haproxy.socket group proxy mode 775 level admin
    nbthread                    1
    hard-stop-after             60s
    no strict-limits
    httpclient.resolvers.prefer   ipv4
    tune.ssl.default-dh-param   2048
    spread-checks               2
    tune.bufsize                16384
    tune.lua.maxmem             0
    log                         /var/run/log local0 info
    lua-prepend-path            /tmp/haproxy/lua/?.lua
    ssl-default-bind-options prefer-client-ciphers ssl-min-ver TLSv1.3
    ssl-default-bind-ciphers ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-SHA384:ECDHE-ECDSA-AES128-SHA256
    ssl-default-bind-ciphersuites TLS_AES_128_GCM_SHA256:TLS_AES_256_GCM_SHA384:TLS_CHACHA20_POLY1305_SHA256
cache opnsense-haproxy-cache
    total-max-size 512
    max-age 60
    process-vary off

defaults
    log     global
    option redispatch -1
    timeout client 30s
    timeout connect 30s
    timeout check 5s
    timeout server 60s
    retries 3
    default-server init-addr last,libc
    # WARNING: pass through options below this line
    timeout tunnel 60s
    timeout client-fin 60s

# autogenerated entries for ACLs


# autogenerated entries for config in backends/frontends

# autogenerated entries for stats




# Frontend: https (https)
frontend https
    http-response set-header Strict-Transport-Security "max-age=15768000; includeSubDomains"
    bind 0.0.0.0:443 name 0.0.0.0:443 ssl prefer-client-ciphers ssl-min-ver TLSv1.3 ciphers ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-SHA384:ECDHE-ECDSA-AES128-SHA256 ciphersuites TLS_AES_128_GCM_SHA256:TLS_AES_256_GCM_SHA384:TLS_CHACHA20_POLY1305_SHA256 alpn h2,http/1.1 crt-list /tmp/haproxy/ssl/63b46490d9adb2.01491287.certlist 
    bind ::1:443 name ::1:443 ssl prefer-client-ciphers ssl-min-ver TLSv1.3 ciphers ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-SHA384:ECDHE-ECDSA-AES128-SHA256 ciphersuites TLS_AES_128_GCM_SHA256:TLS_AES_256_GCM_SHA384:TLS_CHACHA20_POLY1305_SHA256 alpn h2,http/1.1 crt-list /tmp/haproxy/ssl/63b46490d9adb2.01491287.certlist 
    mode http
    option http-keep-alive

    # logging options
    # ACL: find_acme_challenge
    acl acl_63ae4f510c2317.09538657 path_beg -i /.well-known/acme-challenge/
    # ACL: nextcloud
    acl acl_63ae5ac28c9080.54854619 hdr(host) -i nextcloud.philipw.uk
    # ACL: navidrome
    acl acl_6543808692c5d4.34757103 hdr(host) -i navi.fogbox.uk
    # ACL: grafana
    acl acl_65b70ff3e9ab50.53190521 hdr(host) -i grafana.fogbox.uk
    # ACL: uptime-kuma
    acl acl_65c0f630093bd6.13706830 hdr(host) -i status.fogbox.uk
    # ACL: vaultwarden
    acl acl_65c3527f6a9f60.52253394 hdr(host) -i vault.fogbox.uk

    # ACTION: redirect_acme_challenges
    use_backend acme_challenge_backend if acl_63ae4f510c2317.09538657
    # ACTION: nextcloud
    use_backend nextcloud if acl_63ae5ac28c9080.54854619
    # ACTION: navidrome
    use_backend navidrome if acl_6543808692c5d4.34757103
    # ACTION: grafana
    use_backend grafana if acl_65b70ff3e9ab50.53190521
    # ACTION: uptime-kuma
    use_backend uptime-kuma if acl_65c0f630093bd6.13706830
    # ACTION: vaultwarden
    use_backend vaultwarden if acl_65c3527f6a9f60.52253394

# Frontend: http ()
frontend http
    bind 0.0.0.0:80 name 0.0.0.0:80 
    bind ::1:80 name ::1:80 
    mode http
    option http-keep-alive

    # logging options
    # ACL: find_acme_challenge
    acl acl_63ae4f510c2317.09538657 path_beg -i /.well-known/acme-challenge/
    # ACL: nextcloud
    acl acl_63ae5ac28c9080.54854619 hdr(host) -i nextcloud.philipw.uk
    # ACL: navidrome
    acl acl_6543808692c5d4.34757103 hdr(host) -i navi.fogbox.uk
    # ACL: grafana
    acl acl_65b70ff3e9ab50.53190521 hdr(host) -i grafana.fogbox.uk
    # ACL: uptime-kuma
    acl acl_65c0f630093bd6.13706830 hdr(host) -i status.fogbox.uk
    # ACL: vaultwarden
    acl acl_65c3527f6a9f60.52253394 hdr(host) -i vault.fogbox.uk

    # ACTION: redirect_acme_challenges
    use_backend acme_challenge_backend if acl_63ae4f510c2317.09538657
    # ACTION: nextcloud
    use_backend nextcloud if acl_63ae5ac28c9080.54854619
    # ACTION: navidrome
    use_backend navidrome if acl_6543808692c5d4.34757103
    # ACTION: grafana
    use_backend grafana if acl_65b70ff3e9ab50.53190521
    # ACTION: uptime-kuma
    use_backend uptime-kuma if acl_65c0f630093bd6.13706830
    # ACTION: vaultwarden
    use_backend vaultwarden if acl_65c3527f6a9f60.52253394

# Backend: acme_challenge_backend (Added by ACME Client plugin)
backend acme_challenge_backend
    # health checking is DISABLED
    mode http
    balance source
    # stickiness
    stick-table type ip size 50k expire 30m  
    stick on src
    http-reuse safe
    server acme_challenge_host 127.0.0.1:43580 

# Backend: nextcloud ()
backend nextcloud
    # health checking is DISABLED
    mode http
    balance source
    # stickiness
    stick-table type ip size 50k expire 30m  
    cookie SRVCOOKIE prefix
    http-reuse safe
    option forwarded 
    option forwardfor
    server nextcloud 192.168.1.10:80 cookie 63ae5a5fea52d872149136
    server nextcloud-ip6 2a0e:cb01:1d:1200::16a1:80 cookie 659b2f8359188021594342

# Backend: navidrome ()
backend navidrome
    # health checking is DISABLED
    mode http
    balance source
    # stickiness
    stick-table type ip size 50k expire 30m  
    cookie SRVCOOKIE prefix
    http-reuse safe
    option forwarded 
    option forwardfor
    server navidrome 192.168.1.10:4533 cookie 6543800c30d8d090046646
    server navidrome-ip6 2a0e:cb01:1d:1200::16a1:4533 cookie 659b2f95dbbd9738607875

# Backend: grafana ()
backend grafana
    # health checking is DISABLED
    mode http
    balance source
    # stickiness
    stick-table type ip size 50k expire 30m  
    cookie SRVCOOKIE prefix
    http-reuse safe
    option forwarded 
    option forwardfor
    server grafana 192.168.1.10:3000 cookie 65b7103b2c8b1672500661
    server grafana-ip6 2a0e:cb01:1d:1200::16a1:3000 cookie 65b7104d75dac032226307

# Backend: uptime-kuma ()
backend uptime-kuma
    # health checking is DISABLED
    mode http
    balance source
    # stickiness
    stick-table type ip size 50k expire 30m  
    cookie SRVCOOKIE prefix
    http-reuse safe
    option forwarded 
    option forwardfor
    server uptime-kuma 192.168.1.10:3001 cookie 65c0f56379297265132091
    server uptime-kuma-ip6 2a0e:cb01:1d:1200::16a1:3001 cookie 65c420083197e242185448

# Backend: vaultwarden ()
backend vaultwarden
    # health checking is DISABLED
    mode http
    balance source
    # stickiness
    stick-table type ip size 50k expire 30m  
    cookie SRVCOOKIE prefix
    http-reuse safe
    option forwarded 
    option forwardfor
    server vaultwarden 192.168.1.10:8222 cookie 65c351f49e566788237205
    server vaultwarden-ipv6 2a0e:cb01:1d:1200::16a1:8222 cookie 65c0f5724fec8231848795



listen local_statistics
    bind            127.0.0.1:8822
    mode            http
    stats uri       /haproxy?stats
    stats realm     HAProxy\ statistics
    stats admin     if TRUE

# remote statistics are DISABLED
```

**Comment by CommanderStorm** [comment]
The common thing between vaultwarden and us is that we both use websockets.
I have no clue which of these options conflicts with websockets via ipv6, or if there are any options set that might not work as they should.

@BlackDex, given that you have contributed the vaultwarden HAProxy configuration, is there something that you think is off with this configuration?

**Comment by BlackDex** [comment]
The first thing i see in the haproxy config from @philipwilk is that it looks like ipv4 is running on 0.0.0.0 and ipv6 is running on the ipv6 localhost version `::1`.

Now, the examples at Vaultwarden are not (yet) like below, but the binding could be like this:

```haproxy
bind [::]:80 v4v6 ssl ....
bind [::]:443 v4v6 ssl ....
```

Also, for Vaultwarden, if you want a fully IPv6 path, you need to configure `ROCKET_ADDRESS=::`.
If using Docker, then you also need to configure that to accept IPv6, which can be a pain sometimes.

Know that HAProxy can just terminate the IPv6, and forward to IPv4 and all still works.
With the correct headers the IPv6 IP's will be shown in the logs.

Also, for Uptime-Kuma, what have you configured to poll? Best would be to check the `/alive` endpoint.

**Comment by BlackDex** [comment]
Also, in regards of HAProxy, and i see you already have Grafana maybe also Prometheus, you could add this to your HAProxy.

```haproxy
frontend stats
    mode http
    bind *:8404 name prometheus-exporter
    http-request use-service prometheus-exporter if { path /metrics }
    stats enable
    stats uri /stats
    stats refresh 30s
```

And add this to your Prometheus config:
```yaml
  - job_name: haproxy
    scrape_interval: 30s
    scrape_timeout: 20s
    static_configs:
      - targets: ['192.168.1.1:8404']
```

That might provide more details.
You can also access `http://127.0.0.1:8404/stats` directly for a web-interface from HAProxy it self.

**Comment by CommanderStorm** [comment]
Thanks a ton @BlackDex 
<img src="https://media3.giphy.com/media/po3NDGWuAE33qmWqe3/giphy.gif"/>

I think this resolves this issue

**Comment by philipwilk** [comment]
I'll just use haproxy for ipv6 termination for now then, since anything else seems like it will take quite a bit more effort.
I'll also add haproxy to prometheus now that you've reminded me of it though 😄
