### ISSUE TITLE
Certificate check not displayed in UI and no alert sent

### ISSUE THREAD

**Issue by mlanner** [louislam/uptime-kuma#4461]
### ⚠️ Please verify that this question has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

I have configured a monitor for an HTTPS site, but the "Cert Exp." doesn't show up and therefore won't send a certificate expiration warning. I have many other similar sites configured, but this is the only one where the cert is not picked up. If I visit the site and check the cert manually, it shows that the cert is issued by Let's Encrypt and is valid.

What I expect to see:
![uptime-kuma-check-stats-expected](https://github.com/louislam/uptime-kuma/assets/1568794/56878074-ed0e-4cbc-807f-f7122c08067d)

What I actually see:
![uptime-kuma-check-stats-no-cert-exp](https://github.com/louislam/uptime-kuma/assets/1568794/f7c9c106-fd0f-41af-88a2-7cc37e492c7b)

As noted below from the log, it does check for the cert and it knows it has expired. Still, it's not showing in the GUI. Also, it doesn't send out the notification. This works for all my other monitors on this host.

### 📝 Error Message(s) or Log

However, the log does capture that the certificate has expired:

```
2024-02-06T19:20:37-08:00 [MONITOR] WARN: Monitor #2 'HTTPS | host.domain.com': Pending: certificate has expired | Max retries: 2 | Retry: 1 | Retry Interval: 300 seconds | Type: http
```

### 🐻 Uptime-Kuma Version

1.23.11

### 💻 Operating System and Arch

Ubuntu 22.04 w/ Docker

### 🌐 Browser

Firefox

### 🖥️ Deployment Environment

- Runtime: Docker
- Database: sqlite
- Filesystem used to store the database on: ext4
- number of monitors: 7

**Comment by chakflying** [comment]
Likely a duplicate of #3551

**Comment by mlanner** [comment]
@chakflying Agree that it does seem to behave largely the same as in the ticket you referenced. I'm using the root of my domain, though, like suggested in the example given in that ticket. I also tested this on a different Uptime Kuma instance (same version) against this particular server and FQDN, and it behaves the same. So, maybe it has something to do with the particular server/software ... ?

**Comment by CommanderStorm** [comment]
> Agree that it does seem to behave largely the same as in the ticket you referenced

I am going to close this issue as a duplicate
=> lets continue any discussion in https://github.com/louislam/uptime-kuma/issues/3551
