### ISSUE TITLE
Updating SQLite file DB

### ISSUE THREAD

**Issue by wojcikm** [louislam/uptime-kuma#4462]
### ⚠️ Please verify that this question has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

database malformed error after DB update

### 🐻 Uptime-Kuma Version

1.23.11

### 💻 Operating System and Arch

docker official image

### 🌐 Browser

brave

### 🖥️ Deployment Environment

I have several hunderds of sites and I needed to update interval check. So I decided to copy db file (`uptime-kuma-data/kuma.db`), made update to all rows with interval property and then replaced existing db. 

App was up then, but after some time I have noticed strange behaviour - history was missing, page was loading slowly, monitors werent updated. 

Maybe there is another procedure I should follow?

**Comment by CommanderStorm** [comment]
Please don't change a tire while you are driving the same car.
=> first stop the container, make the changes you need, and then start the container again.

For your concrete issue:
Please also restart the container as some things, such as which monitors exist, might not get loaded if you just changed them in the db.
See https://github.com/louislam/uptime-kuma/issues/1840 for further context.

**Comment by wojcikm** [comment]
I had stopped the container before dumping the DB ofc - that's why I am suprised it won't work.

What is more - my update was not reflected in the app - old value was still present.

**Comment by chakflying** [comment]
The application loads all monitor configs from the database on startup. The most likely explanation is that you did not update the database with new values correctly, hence they are not reflected in the application.

Maybe you can post the exact steps you took, and verify by checking the existing database that it contains the new values you entered.

**Comment by wojcikm** [comment]
I went another way - instead of dumping db file to local, I just stopped container, made changes with sqlite3 cli and we are good. Thanks for helping me.
