### ISSUE TITLE
Microsoft Teams Notification:  Error: AxiosError: Request failed with status code 404

### ISSUE THREAD

**Issue by cs-michaelc** [louislam/uptime-kuma#4464]
### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### Description

I attempted to create a new Microsoft Teams notification, but every time I test it, I encounter the error message "Error: AxiosError: Request failed with status code 404."

Please note that I'm utilizing the new version of Microsoft Teams. Interestingly, when I set up a new Incoming Webhook on the previous version of Microsoft Teams, it operates without any issues.

<img width="992" alt="Screenshot 2024-02-08 at 8 25 01 AM" src="https://github.com/louislam/uptime-kuma/assets/92838112/3a089ba9-8451-4f6c-bfbf-b08aa481fadc">

### 👟 Reproduction steps

Go to Settings
Setup Notification
Notification Type to Microsoft Teams

### 👀 Expected behavior

Test Successful

### 😓 Actual Behavior

Error: AxiosError: Request failed with status code 404

### 🐻 Uptime-Kuma Version

1.22.1

### 💻 Operating System and Arch

Ubuntu 20

### 🌐 Browser

Firefox

### 🖥️ Deployment Environment

Nodejs

**Comment by louislam** [comment]
>  I'm utilizing the new version of Microsoft Teams. Interestingly, when I set up a new Incoming Webhook on the previous version of Microsoft Teams, it operates without any issues.

I don't use Microsoft Teams, did you mean there are two versions of Teams at this moment? And they both provide a different webhook url?

**Comment by CommanderStorm** [comment]
I think the likely culprit is the same as in https://github.com/louislam/uptime-kuma/issues/4457#issuecomment-1933842651
