### ISSUE TITLE
Too long password are not accepted

### ISSUE THREAD

**Issue by ColdbloodDK** [louislam/uptime-kuma#4468]
### 📑 I have found these related issues/pull requests

No related issues

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 👟 Reproduction steps

Set a long password

### 👀 Expected behavior

The password is setted and i can login with the new one

### 😓 Actual Behavior

The password is setted but i can't login with the new one and i need to reset it trought cli with a shorter one

### 🐻 Uptime-Kuma Version

1.23.10

### 💻 Operating System and Arch

Ubuntu 22.04.3 LTS x86_64

### 🌐 Browser

Brave 1.62.162

### 🖥️ Deployment Environment

- Runtime: Docker version 25.0.1, build 29cf629
- Database: sqlite/embedded
- Filesystem used to store the database on: ext4
- number of monitors: 6

**Comment by louislam** [comment]
How long is it?

**Comment by CommanderStorm** [comment]
I tried setting a password, which is
```py
>>> "1A"+"a"*1000
'1Aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa'
```

=> cannot reproduce on https://demo.kuma.pet/

**Comment by gamer50082** [comment]
I don’t think anyone would go that far for a password

**Comment by gamer50082** [comment]
Max I would or recommend to go is 512

**Comment by CommanderStorm** [comment]
I think this issue is some form of user-errror => closing as resolved
We can reopen @ColdbloodDK  goes further into details how to reproduce this issue
