### ISSUE TITLE
Badges

### ISSUE THREAD

**Issue by louislam** [louislam/uptime-kuma#447]
I am reading gatus's readme (https://github.com/TwinProduction/gatus#badges) and found this feature.

Upvote👍 to let me know that you want this feature in Uptime Kuma too.

![image](https://user-images.githubusercontent.com/1336778/133960104-151ac8cb-2dfd-4832-9f67-b40ff411c874.png)

**Comment by gaby** [comment]
That requires an internet connection, in my case that would break since we run `Uptime-Kuma` behind a corporate proxy with no internet access.

**Comment by Saibamen** [comment]
@gaby So this will be disabled by default

Why disabled by default for all? Fewer requests ;)

**Comment by DPA-Dev** [comment]
Scoured the open enhancements to find this. Would love to see this in an update, so happy you are already thinking about it :)

**Comment by FulytheFox** [comment]
I've made a little concept of how such a badge could look like. I would really love to have badges for kuma!
![concept_kuma_badge](https://user-images.githubusercontent.com/37185496/147383252-d10887e2-08c8-4200-8260-6129bad148fa.png)

**Comment by jensneuber** [comment]
I opened a pull request for a feature like this: https://github.com/louislam/uptime-kuma/pull/1119
