### ISSUE TITLE
Notifications on maintenances/incidents

### ISSUE THREAD

**Issue by dponzone** [louislam/uptime-kuma#4474]
### 📑 I have found these related issues/pull requests

I was unable to find a related feature request.

### 🏷️ Feature Request Type

Maintenance

### 🔖 Feature description

Uptime Kuma is a great tool, also was Staytus, but the latter is almost dead.
Staytus has/had the ability to notify subscribers on incidents/maintenances.
Would it be possible to get the best of both worlds ?

### ✔️ Solution

When one creates a maintenance, or an incident in a status page, Kuma would notify all impacted services using their currently configured notification targets.
Of course, a layer of deduplication could be required somewhere to avoid receiving 1000 mails in some situations.

### ❓ Alternatives

Well, I did not find any tool doing what Kuma does and what Staytus does.

**Comment by CommanderStorm** [comment]
Email Subscribription is tracked in https://github.com/louislam/uptime-kuma/issues/916 
I think this issue is either a direct duplicate or should be tracked there.
=> closing as a dulicate
