### ISSUE TITLE
Migrate from `omsrivastava/timezones-list` to `vvo/tzdb`

### ISSUE THREAD

**Issue by chakflying** [louislam/uptime-kuma#4479]
### 📑 I have found these related issues/pull requests

none

### 🏷️ Feature Request Type

Other

### 🔖 Feature description

[omsrivastava/timezones-list](https://github.com/omsrivastava/timezones-list), the library currently used by our front-end, is rarely updated and has [inaccuracies](https://github.com/omsrivastava/timezones-list/issues/14). 

[vvo/tzdb](https://github.com/vvo/tzdb) looks much better as it is automatically kept up-to-date with authoritative sources. 

Some migration work is needed since the data format is different.

### ✔️ Solution

Migrate from `omsrivastava/timezones-list` to `vvo/tzdb`

**Comment by louislam** [comment]
It can be considered as a bug fix, because the https://github.com/omsrivastava/timezones-list/issues/14 issue you mentioned should be related to the DST issue, which `timezones-list` does not handling it at all.

https://www.zeitverschiebung.net/en/timezone/america--santiago
