### ISSUE TITLE
Connection issues using Cloudflare Tunnels

### ISSUE THREAD

**Issue by peshav** [louislam/uptime-kuma#4480]
### 📑 I have found these related issues/pull requests

 I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### Description

When trying to connect to my uptime instance over cloudflare tunnels to my host machine hosted on a vps i am sometimes getting either an 502 error or when i get past the 502 error im getting connection issues with some error messages at the top of the page.
![lost-connection](https://github.com/louislam/uptime-kuma/assets/18575962/56edbeff-2b25-44c2-b17d-63a65ffdf800)
![xhr-poll-error](https://github.com/louislam/uptime-kuma/assets/18575962/920eec6f-e2e6-43ea-8202-d5d8873241f5)
![bad-gateway](https://github.com/louislam/uptime-kuma/assets/18575962/6c95dfc8-4486-49f2-bf38-37066e1ce769)

If I keep waiting or refresh the page a few times it finally connects and seem to work, until I refresh the page or try to connect from a different device.

### 👟 Reproduction steps

I followed everything described in this wiki: [](https://github.com/louislam/uptime-kuma/wiki/Reverse-Proxy-with-Cloudflare-Tunnel)
Additionally im using the env variable to setup my cloudflare token.

### 👀 Expected behavior

Visiting the url defined in the cloudflare tunnel should connect me to the uptime kuma dashboard.

### 😓 Actual Behavior

Visiting the url results in either a 502 gateway error, waiting time until the xhr polling error gets resolved or sometimes it just works as expected.

### 🐻 Uptime-Kuma Version

1.23.11

### 💻 Operating System and Arch

Ubuntu 22.04

### 🌐 Browser

Google Chrome Version 121.0.6167.160

### 🖥️ Deployment Environment

latest install of every runtime setup on a fresh and updated ubuntu 22.04 vps. 
nr. of monitors: 5

**Comment by peshav** [comment]
Maybe this SO post is relevant to this issue: [](https://stackoverflow.com/questions/69450485/receiving-error-xhr-poll-error-socket-io-client-react)

**Comment by CommanderStorm** [comment]
When the guide was made, we indeed had `transport: ["websocket"]` as the only option.
This change was primarily a security fix and secondary a fix of how we understood long polling.
See https://github.com/louislam/uptime-kuma/releases/tag/1.23.9 and the associated PRs like https://github.com/louislam/uptime-kuma/pull/4216#issuecomment-1850362953 / or the security advisory for further context.

On the other hand https://demo.kuma.pet/ is run via cloudflare tunnels, so I don't know what you are experiencing precicely…

=> given that these are 5xx errors you are experiencing, what are the server logs?

**Comment by louislam** [comment]
Changed to help as it is running fine for all my instances and cannot reproduce.

Some directions to determine the root cause:
- Try to reproduce on https://demo.kuma.pet/
- Try different browsers
- Try different networks
- Try different server locations
