### ISSUE TITLE
Monitor on Status Page is not identical in edit mode

### ISSUE THREAD

**Issue by fabbaum** [louislam/uptime-kuma#4482]
### 📑 I have found these related issues/pull requests

I have not found a similar issue.

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### Description

The Uptime Monitor shows incorrect values while editing the Status Page. Compare the two attachments.

For a newly created monitor where the first ping fails, the uptime status is displayed as UP when the status page is being edited. These should actually be grayed out, as with a status page that is not being edited.

The time range also does not match. During editing it shows a wrong range.

![Status Page durign editing](https://github.com/louislam/uptime-kuma/assets/82809599/34ce278d-8011-4053-8aa3-fe143c70c831)
![Status Page](https://github.com/louislam/uptime-kuma/assets/82809599/dde5b705-7365-44ec-beb0-916827716796)

### 👟 Reproduction steps

Create a new monitor, add it to a status page. Compare the monitor on the Status Page with the monitor when the Status Page is being edited. 

### 👀 Expected behavior

The status bars should look the same.

### 😓 Actual Behavior

The status bars are different.

### 🐻 Uptime-Kuma Version

1.23.11

### 💻 Operating System and Arch

Ubuntu 22.04 x64

### 🌐 Browser

Microsoft Edge Version 121.0.2277.106

### 🖥️ Deployment Environment

- Runtime: Docker 25.0.2
- number of monitors: 53

**Comment by louislam** [comment]
Cannot reproduce.

Your time range gap was so big too (11m vs 30m). Do you have any caching service in front of Uptime Kuma?

**Comment by fabbaum** [comment]
I also tried to reproduce it again, but I didn't succeed either. We use nginx in front of Uptime Kuma.

**Comment by fabbaum** [comment]
I also tried to reproduce it again, but I didn't succeed either. We use nginx in front of Uptime Kuma.
