### ISSUE TITLE
How to set up Passive Push for cronjobs ?

### ISSUE THREAD

**Issue by ethicnology** [louislam/uptime-kuma#4484]
### ⚠️ Please verify that this question has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

I want to replace healthchecks.io by Kuma. 

I read different issues/PR about the new push feature that would let me using Kuma to monitor the execution of my jobs (#4449 …)

I can't find enough documentation to set up the push.

The need is simple. I have cronjobs that run once per day, when a job start it pushes `begin` and when the job ends it pushes `end`.

The job is considered failed if no END was sent for a BEGIN (after x hours if possible)

If the job is successful, I'm interested to have the execution time between the BEGIN and END

How I'm supposed so setup Kuma to address this kind of need ?

I tried to send different `msg=BEGIN`/`msg=END` to the demo, but the events are not all recorded.

Should I send a `status=up` when the job start and a `status=down` when the job end instead of using `msg` ?

### 🐻 Uptime-Kuma Version

1.23

### 💻 Operating System and Arch

Debian 12

### 🌐 Browser

Firefox

### 🖥️ Deployment Environment

- Runtime: N/A
- Database: N/A
- Filesystem used to store the database on: N/A
- number of monitors: N/A

**Comment by CommanderStorm** [comment]
> The job is considered failed if no END was sent for a BEGIN (after x hours if possible)

If you drop the first part and just monitor if the END is send (after x hours), that is directly supported.
I don't see the need to monitor for an `arming` of the monitor step.
If you really need this functionality, you can achive it via the third party api[^1] and pausing the monitor.

An alternative way of phrasing your problem would be to set the montor to `DOWN` at the BEGIN of the cronjob and let the retry mechanism keep it from notifying you. The END sets it to `UP` again. Time which it can be `DOWN`/ in the cronjob is specified via the retry-settings and monitoring inteval.

> I tried to send different msgs to the demo

Only evens considered "important" (f.ex. `UP`->`DOWN`, `DOWN`->`UP`) cause an alert and are recorded.

> execution time

You can "abuse" the `ping`-parameter (in ms) for this, but it might not look pretty.

[^1]: https://uptime-kuma-api.readthedocs.io/en/latest/
