### ISSUE TITLE
Ability to set acceptable ping value range

### ISSUE THREAD

**Issue by Potat0000** [louislam/uptime-kuma#4486]
### 📑 I have found these related issues/pull requests

None

### 🏷️ Feature Request Type

Other

### 🔖 Feature description

When using monitor types that include ping RTT value, sometimes even if the service is Up, the ping value is way too high that it's almost unusable, or is too low that something was wrong obviously.

### ✔️ Solution

Maybe it's a good idea to provide a new option for those monitors with ping values to set a range of "Acceptable Ping Value". If the ping RTT value is out of range (too high or too low), it can be treated as Down, and send notifications after retrying.

### 📝 Additional Context

Some monitor types (like HTTP) can do this by setting a low timeout time. However, for most other types, there aren't such options. It would be a good thing if there could be a universal option to finish such a job.

**Comment by chakflying** [comment]
PR for Notification specifically for slow response times open in #4005.

**Comment by Potat0000** [comment]
Sorry for not finding that PR.
