### ISSUE TITLE
Docker Browser Engine - `exited with code 100`

### ISSUE THREAD

**Issue by Bgabor997** [louislam/uptime-kuma#4488]
### ⚠️ Please verify that this question has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

Can't istall Chromium browser engine

### 📝 Error Message(s) or Log

2024-02-13T14:46:31+01:00 [CHROMIUM] INFO: Installing Chromium...
2024-02-13T14:46:31+01:00 [CHROMIUM] INFO: apt install chromium exited with code 100

### 🐻 Uptime-Kuma Version

1.23.11

### 💻 Operating System and Arch

Ubuntu 22 Docker

### 🌐 Browser

Google Chrome latest

### 🖥️ Deployment Environment

- Runtime: Docker 24.0.6
- Database: default docker one
- Filesystem used to store the database on:  ubuntu on ssd
- number of monitors: 20

**Comment by CommanderStorm** [comment]
`exited with code 100` is sadly a very non-descriptive error message..

Could you please verify, via https://github.com/louislam/uptime-kuma/wiki/Troubleshooting that you have internet inside the container?

**Comment by Bgabor997** [comment]
```
root@dc3303b1d8d4:/app# ping google.com
PING google.com (142.251.208.110) 56(84) bytes of data.
64 bytes from bud02s41-in-f14.1e100.net (142.251.208.110): icmp_seq=1 ttl=58 time=18.5 m                                                                                                                                                                     s
64 bytes from bud02s41-in-f14.1e100.net (142.251.208.110): icmp_seq=2 ttl=58 time=18.5 m                                                                                                                                                                     s
64 bytes from bud02s41-in-f14.1e100.net (142.251.208.110): icmp_seq=3 ttl=58 time=18.2 m                                                                                                                                                                     s
64 bytes from bud02s41-in-f14.1e100.net (142.251.208.110): icmp_seq=4 ttl=58 time=18.4 m                                                                                                                                                                     s
64 bytes from bud02s41-in-f14.1e100.net (142.251.208.110): icmp_seq=5 ttl=58 time=18.2 m                                                                                                                                                                     s
64 bytes from bud02s41-in-f14.1e100.net (142.251.208.110): icmp_seq=6 ttl=58 time=18.5 ms
64 bytes from bud02s41-in-f14.1e100.net (142.251.208.110): icmp_seq=7 ttl=58 time=18.6 ms
64 bytes from bud02s41-in-f14.1e100.net (142.251.208.110): icmp_seq=8 ttl=58 time=18.2 ms
^C
--- google.com ping statistics ---
8 packets transmitted, 8 received, 0% packet loss, time 17ms
rtt min/avg/max/mdev = 18.163/18.381/18.550/0.153 ms
root@dc3303b1d8d4:/app# curl https://google.com
<HTML><HEAD><meta http-equiv="content-type" content="text/html;charset=utf-8">
<TITLE>301 Moved</TITLE></HEAD><BODY>
<H1>301 Moved</H1>
The document has moved
<A HREF="https://www.google.com/">here</A>.
</BODY></HTML>
```

**Comment by CommanderStorm** [comment]
Weird.
This is what it should look like:

![image](https://github.com/louislam/uptime-kuma/assets/26258709/5a52e8c0-af1e-4000-9910-7eb9aa3a8aa8)

Could you try clicking the button agian? (maybe debian had a networking fluke or something..)
Alternatively: could you run `apt install update` and `apt install chromium`

**Comment by Bgabor997** [comment]
well if i install it manually from the container, it works perfectly, it can find it with auto detect. Strange, maybe some kind of a permission issue? o.O not sure, anyways thx for the help, its solved

**Comment by CommanderStorm** [comment]
> it can find it with auto detect

What are you refering to exactly here? (screenshot)

**Comment by CommanderStorm** [comment]
I retried and now know what you are refering to.
When said message is printed in the log, you likely have pressed the `Test` Button more than once => cromium is not done installing

![image](https://github.com/louislam/uptime-kuma/assets/26258709/9eb4e5c3-108f-4b00-bc9d-9e03a89cd16f)

**Comment by Qixuga** [comment]
Got the same error after automatic update uptime kuma docker image with watchtower to 1.23.13
I used `image-tag: louislam/uptime-kuma:1`
It seems, uptime kuma hangs inside while installing an os/chrome engine update, but i thought this will be updated, within the container-update so you don't need to install updates inside. It seems the auto-update have to be disabled in docker-image, are there a setting via ENV etc to do this?
Am i wrong?

i had internet, dns and ping works fine - all other checks working fine.

logfile from docker-container said for alle browser engine checks:

```
2024-06-10T11:22:57+02:00 [CHROMIUM] INFO: Installing Chromium...
2024-06-10T11:22:58+02:00 [CHROMIUM] INFO: Installing Chromium...
2024-06-10T11:22:58+02:00 [CHROMIUM] INFO: apt install chromium exited with code 100
2024-06-10T11:22:58+02:00 [MONITOR] WARN: Monitor #94 '<monitor-name>': Failing: Installing Chromium, please wait... | Interval: 900 seconds | Type: real-browser | Down Count: 0 | Resend Interval: 0
```

if you need any other information, let me know.
If i should create a new issue, let me also know.

Thank you for your great tool and support!

**Comment by CommanderStorm** [comment]
Could you exec into the container and run `apt install chromium` to see what the full output of said command is?
(see https://github.com/louislam/uptime-kuma/wiki/Troubleshooting how to do that)

**Comment by patsevanton** [comment]
please open issue

```
root@40719c5df98d:/app# apt update
Ign:1 http://deb.debian.org/debian buster InRelease
Ign:2 http://deb.debian.org/debian-security buster/updates InRelease
Ign:3 http://deb.debian.org/debian buster-updates InRelease
Err:4 http://deb.debian.org/debian buster Release
  404  Not Found [IP: 146.75.118.132 80]
Err:5 http://deb.debian.org/debian-security buster/updates Release
  404  Not Found [IP: 146.75.118.132 80]
Err:6 http://deb.debian.org/debian buster-updates Release
  404  Not Found [IP: 146.75.118.132 80]
Hit:7 https://pkg.cloudflare.com/cloudflared buster InRelease
Reading package lists... Done
E: The repository 'http://deb.debian.org/debian buster Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
E: The repository 'http://deb.debian.org/debian-security buster/updates Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
E: The repository 'http://deb.debian.org/debian buster-updates Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
root@40719c5df98d:/app# apt install chromium
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package chromium
```

**Comment by CommanderStorm** [comment]
@patsevanton please see the pinned issue
