### ISSUE TITLE
Allow hostname instead of IP only for ping again

### ISSUE THREAD

**Issue by Spiritreader** [louislam/uptime-kuma#449]
In recent builds (since https://github.com/louislam/uptime-kuma/commit/3a0bc80016380a5b56617e15b496d0839b9c42bb) there is a requirement to put an IP or a specific hostname into the TCP ping field.
https://github.com/louislam/uptime-kuma/blob/6aaf984f29b6bef6bb9fb8f859744aa60a97ef59/src/pages/EditMonitor.vue#L53

@Ponkhy ~~Is there any technical reason why this is done? Or is there something funky with the regex? 
Allowing only IP addresses as ping type seems a bit restrictive.~~
The host name regex seems to work fine when testing it on its own, but the validation seems to fail nonetheless when a hostname is entered.

Using `example.com` results in a failed input validation
![image](https://user-images.githubusercontent.com/18438899/134081946-895ee6be-59d8-4551-886b-c908d6b83ec5.png)

The commit ID I built my docker image with:
```
Checking out Revision 6aaf984f29b6bef6bb9fb8f859744aa60a97ef59 (refs/remotes/origin/master)
 > git config core.sparsecheckout # timeout=10
 > git checkout -f 6aaf984f29b6bef6bb9fb8f859744aa60a97ef59 # timeout=10
 > git branch -a -v --no-abbrev # timeout=10
 > git branch -D master # timeout=10
 > git checkout -b master 6aaf984f29b6bef6bb9fb8f859744aa60a97ef59 # timeout=10
Commit message: "fix retryInterval = 0 if it is an old monitor. (#380 https://github.com/louislam/uptime-kuma/pull/380#issuecomment-922618356)"
 ```

**Comment by Ponkhy** [comment]
It's a bug, it was intended to accept hostnames and ip addresses, we want to restrict it because we had a couple cases where ppl put a port in the hostname field too.

**Comment by louislam** [comment]
Have to concat two regex rules in string.

https://stackoverflow.com/questions/4947561/can-i-combine-2-regex-with-a-logic-or/4947608

But my attempt is failed, since I am not familiar with regex.
