### ISSUE TITLE
"Request failed with status code 501" on "HTTPS" URLs

### ISSUE THREAD

**Issue by dibr0006** [louislam/uptime-kuma#4499]
### ⚠️ Please verify that this question has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

I run uptime-kuma in a docker containter within ubuntu server and encounter the problem, hat every job targeting a https url fails with "Request failed with status code 501".

### 📝 Error Message(s) or Log

"Request failed with status code 501"

### 🐻 Uptime-Kuma Version

1.23.11

### 💻 Operating System and Arch

Ubuntu Server 22.04.3

### 🌐 Browser

Firefox

### 🖥️ Deployment Environment

docker run -d --restart=always -p 3001:3001 -v uptime-kuma:/app/data --name uptime-kuma louislam/uptime-kuma:1

**Comment by CommanderStorm** [comment]
- 501 usually means this is some kind of server error. Have you checked the server log
- How are you routing your network traffic? is there a common component to the things you are monitoring?
- Have you tried the troubleshooting steps listed here? what are the results locally vs inside the container?
https://github.com/louislam/uptime-kuma/wiki/Troubleshooting

**Comment by dibr0006** [comment]
hi,
server logd do not shot anything noticable.

there is a company proxy for external traffic but the site is internal and can bypass the proxy.

curl works normaly:

***@***.***:/root$ curl https://XXXX.XXXX.de/info/ping
{"status":200,"type":"OK","title":"Ping","detail":null,"instance":"/info/ping"}

any ideas how to debug the issue?

**Comment by CommanderStorm** [comment]
> server logd do not shot anything noticable

What do they show in realation to the requests you are making?

What exactly do you mean by this statement?

> but the site is internal

If this is on the same docker network: have you allowed access between these containers?

> any ideas how to debug the issue?

See above:
> - Have you tried the troubleshooting steps listed here? what are the results locally vs inside the container?
https://github.com/louislam/uptime-kuma/wiki/Troubleshooting

**Comment by dibr0006** [comment]
because I got no meaningful debug info, I tested an other tool, which gave me a hint:

2024-02-19 09:28:53.840 - error: run monitor(clssqh4qq0001mn5avw6zosoj) http error Error: unable to verify the first certificate

but, why can I not get rid of thei by ignoring cert errors?

**Comment by CommanderStorm** [comment]
Please answer the questions I asked in https://github.com/louislam/uptime-kuma/issues/4499#issuecomment-1952144695, without answering my questions remote debugging is a lot more painfull..

**Comment by dibr0006** [comment]
server logd do not shot anything noticable

What do they show in realation to the requests you are making?

>nothing, iis on windows server is not logging anything

What exactly do you mean by this statement?

    but the site is internal

> proxy is not used when accessing the website

If this is on the same docker network: have you allowed access between these containers?

    any ideas how to debug the issue?

> curl works in the container where kuma is running itself.

See above:

        Have you tried the troubleshooting steps listed here? what are the results locally vs inside the container?
        https://github.com/louislam/uptime-kuma/wiki/Troubleshooting

> it is very probable that "http error Error: unable to verify the first certificate" is the source of the problem. in another monitoring tool I simply ignore certificate errors and I'm done.

**Comment by chakflying** [comment]
501 is a HTTP response code returned by the server. Certificate verification is something that typically happens on the client. I don't see any reason they would be related to one another, unless you have some evidence to suggest otherwise.
