### ISSUE TITLE
The base URL does not apply

### ISSUE THREAD

**Issue by peterzheng98** [louislam/uptime-kuma#4501]
### ⚠️ Please verify that this question has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

I hope to access Kuma through the /uptime path. However, even though I have set the Base URL to xxx.com/uptime/ and configured Nginx to forward /uptime/ to localhost:3001, accessing /uptime still automatically redirects to /dashboard, which conflicts with other services.

### 🐻 Uptime-Kuma Version

1.23.11

### 💻 Operating System and Arch

Ubuntu 20.04 x86

### 🌐 Browser

Microsoft Edge Version 114.0.1823.41 (Official build) (x86_64)

### 🖥️ Deployment Environment

- Runtime: Docker version 25.0.3, build 4debf41
- Database: -
- Filesystem used to store the database on: ext4
- number of monitors: 0

**Comment by CommanderStorm** [comment]
That is currently not supported and not what said setting is used for.
The setting is used for setting the base path (in https://example.com/status/abc this would be https://example.com)

See this issue:
- https://github.com/louislam/uptime-kuma/issues/147

If you need just a status page under a certain subdirectory, see https://github.com/louislam/uptime-kuma/wiki/Status-Page#custom-subdirectory--custom-html-on-status-pages instead
