### ISSUE TITLE
Need to set proxy only for MS Teams notification.

### ISSUE THREAD

**Issue by virendarkmr** [louislam/uptime-kuma#4510]
### ⚠️ Please verify that this question has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

I am using the tool in our private cloud to monitor few of our APIs which are in our internal network, Email notification is working properly as we have our own internal network SMTP server.

For sending MS Teams notification we have to use corporate proxy and we are able to send test message using postman via corporate proxy.

How do we set proxy only for MS Teams notification and not for health monitoring.

I tried OS proxy configration like http_proxy and no_proxy but it is not working.

### 📝 Error Message(s) or Log

NA

### 🐻 Uptime-Kuma Version

1.23.10

### 💻 Operating System and Arch

Centos

### 🌐 Browser

chrome

### 🖥️ Deployment Environment

Centos 7.9 server

**Comment by CommanderStorm** [comment]
Currently, sending notifications via the proxy configuration is not supported. See these issues:
- #616 
- #2588
