### ISSUE TITLE
"connect ECONNREFUSED" when check HTTP on specific port

### ISSUE THREAD

**Issue by Isnubi** [louislam/uptime-kuma#4517]
### ⚠️ Please verify that this question has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

Hello,
I just got this error, when I try to monitor a HTTP service on localhost on a specific port.

But, the service is well up (can curl it).

Anyone got infos about that?

Thanks!

### 📝 Error Message(s) or Log

![image](https://github.com/louislam/uptime-kuma/assets/40593456/804e49eb-198c-45f5-b5f4-6ddc8e915fa1)
![image](https://github.com/louislam/uptime-kuma/assets/40593456/7bc1b01c-8e01-4764-ba29-eb6da3246e4e)

### 🐻 Uptime-Kuma Version

1.23.11

### 💻 Operating System and Arch

Debian 12

### 🌐 Browser

Firefox 122.0.1

### 🖥️ Deployment Environment

- Runtime: Docker 25.0.3

**Comment by CommanderStorm** [comment]
docker has more than one network type with only some of them allowing access to the local network and some not even allowing access to remote networks.
See https://youtu.be/bKFMS5C4CG0

Have you configured Uptime Kuma to have access to said containe?

**Comment by Isnubi** [comment]
Okay I understand where the problem was, thanks !
uptime-kuma run in docker so 127.0.0.1 is itself, and not the host...
