### ISSUE TITLE
`reset_password`-script should check if the database file exists

### ISSUE THREAD

**Issue by CommanderStorm** [louislam/uptime-kuma#4518]
A good possible improvement here is that the reset password script should first check if the database file exists in the specified directory before actually running the reset procedure.

<sub>

_Originally posted by @chakflying in https://github.com/louislam/uptime-kuma/issues/4507#issuecomment-1959540349_

</sub>

The reason behind this is that otherwise a new (unmigrated) database might be created leading to confused users

The script is located here:

https://github.com/louislam/uptime-kuma/blob/master/extra/reset-password.js

**Comment by huzaifaazim0** [comment]
Hello,
i want to solve this issue,
but there is one confusion, you said "script should first check if the database file exists in the specified directory"
what is the specified directory? the "/data/"?

**Comment by CommanderStorm** [comment]
The database should live in this directory:

https://github.com/louislam/uptime-kuma/blob/e61589d02e7527744cd6a28db82909451bdc02f9/server/database.js#L130-L132


If `dbConfig.type === "sqlite"` (`dbConfig` has to be loaded from `Database.readDBConfig()`) and `Database.sqlitePath` does not exist once the `reset-password` command is being issued, `reset-password` should abort with a helpful error message instead of [creating it in `Database-connect(...)`](https://github.com/louislam/uptime-kuma/blob/e61589d02e7527744cd6a28db82909451bdc02f9/server/database.js#L220).

I would need to look deeper into the code how the same logic works for the `mariadb` backend (especially: is the logic necessary for said database?)

**Comment by huzaifaazim0** [comment]
makes sense
let me know when you are done looking and ready to assign

Thanks

**Comment by CommanderStorm** [comment]
We don't assign people to issues, as we have not seen any upside to doing so.
See our contribution guide: https://github.com/louislam/uptime-kuma/blob/master/CONTRIBUTING.md

Thinking about MariaDB a bit more:
the state of not having a valid database would either lead to a connection error or (if the db were to not be configured) lead to the SQLite path being triggered.
I don't see a case in which special handling is required (people resetting the password during the setup process is I think not a real threat)

**Comment by huzaifaazim0** [comment]
Okay
Makes sense...
Not sure why that guy encountered the error but "if it occurs one time it
may occur again"

If you think it's necessary to be added
Let me know, I am open to work on it.

And if you think that its not an issue, its good to close it

Thanks

**Comment by CommanderStorm** [comment]
As nelson said, adding this check is not NESSESARY, but "a good possible improvement"
=> one less papercut one can get while using our software

> if you think that its not an issue, its good to close it

If I thought that, the issue would not have been extracted in the first place 😉

**Comment by huzaifaazim0** [comment]
Hello, so i was trying it out and found out that in readDBConfig() Database.dataDir is undefined
looks like initDataDir is not being run successfully.

here are the steps i did

1- cloned the repo
2- ran "npm ci"
3- ran "npm run dev"
4- setup a db and created account on "localhost:3000"
5- logged out
6- then tried "npm run reset-password"

it is failing with this error 
"TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined" database.js:165:51

upon checking details found out that Database.dataDir is undefined.

so in readDBConfig() if i change this line
let dbConfigString = fs.readFileSync(path.join(Database.dataDir , "db-config.json")).toString("utf-8");

to 

let dbConfigString = fs.readFileSync(path.join(Database.dataDir || "./data/" , "db-config.json")).toString("utf-8");


this works

should i change this line and add checks for sqlite in the reset-password function?

Let me know. i'll be waiting

**Comment by huzaifaazim0** [comment]
hey,
sorry about my previous response. please ignore that.
upon detailed review, i found out there was no issue.
the only thing needed is to add DB initDataDir and connect to the try catch block to show an error message in a good way

the old codebase is already testing for the database file existance

i have created a pull request with the above mentioned change
https://github.com/louislam/uptime-kuma/pull/4519
