### ISSUE TITLE
[Virus Error] in notification email

### ISSUE THREAD

**Issue by larsinka** [louislam/uptime-kuma#4522]
### 📑 I have found these related issues/pull requests

None

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### Description

I just received an email notification for a device being „up“ again in my network but this time it said „[Virus Error]“ in the header. It was the first time this occurred. Didn’t change anything in the config. 
![IMG_0048](https://github.com/louislam/uptime-kuma/assets/62347791/6fc10fa6-7232-4329-965f-166ec6a65d2d)

### 👟 Reproduction steps

Cannot reproduce 

### 👀 Expected behavior

Normal header in notification email

### 😓 Actual Behavior

Added „[Virus Error]“ in header 

### 🐻 Uptime-Kuma Version

1.23.11

### 💻 Operating System and Arch

Debian GNU/Linux 12 (bookworm) aarch64

### 🌐 Browser

Safari

### 🖥️ Deployment Environment

- Runtime: Docker 25.0.3, build 4debf41
- Database: I don’t know 
- Filesystem used to store the database on: ext4(?)
- number of monitors: 10

**Comment by CommanderStorm** [comment]
first of all, this is not a message found in our source code and we don't do virus scans (how/why would we? ^^)
Debugging this needs more information:

- What have you set as a custom subject tempalte for said notification provider?
- What smtp server are you using? Could this introduce such a subject if the virus scanner from said server failed?
