### ISSUE TITLE
Discord & Telegram give error on notification

### ISSUE THREAD

**Issue by Koenfred19** [louislam/uptime-kuma#4524]
### 📑 I have found these related issues/pull requests

none

### 🛡️ Security Policy

- [x] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### Description

Hey my uptimekuma instance doesn't push notifications via telegram and discord i get the following error: Error: Error: connect ECONNREFUSED 0.0.0.0:443  Does someone have a fix?

### 👟 Reproduction steps

I just installed it via https://tteck.github.io/Proxmox/

### 👀 Expected behavior

It should just give the notification

### 😓 Actual Behavior

I doesn't push a notification

### 🐻 Uptime-Kuma Version

1.23.11

### 💻 Operating System and Arch

Debian 12

### 🌐 Browser

Chromiumbased

### 🖥️ Deployment Environment

- Runtime: 
- Database: 
- Filesystem used to store the database on: 
- number of monitors:

**Comment by CommanderStorm** [comment]
LXC containers packaged by a third party are not a supported installation method.
Please raise issues with them first: https://github.com/tteck/Proxmox

I don't know anything about LXC containers and how they differer from docker containers.
I also don't know how networking works exactly => asking 
Here are the ways of running uptime kuma supported by us https://github.com/louislam/uptime-kuma/wiki/%F0%9F%94%A7-How-to-Install directly.

General debugging hints may still apply:
- Have you checked that you have internet connectivity inside the container?
https://github.com/louislam/uptime-kuma/wiki/Troubleshooting
- What is the networking topology?
  Could a firewall be blocking your network access?
- Is this the cause of your issues? https://github.com/tteck/Proxmox/issues/1409

**Comment by Koenfred19** [comment]
I will close the issue it was my DNS server that was blocking api.telegram.com and discord.com, sorry for stealing everyones time 😉
