### ISSUE TITLE
LINE messenger has changed their developer portal, making some helptexts outdated

### ISSUE THREAD

**Issue by Vista2003** [louislam/uptime-kuma#4526]
### ⚠️ Please verify that this question has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

I'm trying to add LINE messenger alerts into Uptime kuma but everytime I try to run a test, I get 401'ed with this error:
![image](https://github.com/louislam/uptime-kuma/assets/55105920/71cf8d94-f7b3-4465-8d0c-f876fe6e311e)

LINE's dev portal doesn't have have a Channel access token anymore but instead seems to have Channel secrets instead, does this change anything on how Uptime Kuma communicates with LINE's API?

### 🐻 Uptime-Kuma Version

1.23.11

### 💻 Operating System and Arch

UNRAID 6.12.8 - x64 (Intel)

### 🌐 Browser

Brave Version 1.63.162 Chromium: 122.0.6261.69 (Official Build) (64-bit)

### 🖥️ Deployment Environment

- Runtime: Docker (UNRAID 6.12.8)
- Database: Unknown (whatever is default)
- Filesystem used to store the database on: btrfs (in Docker)
- number of monitors: 12

**Comment by CommanderStorm** [comment]
Line was introduced in https://github.com/louislam/uptime-kuma/pull/227
Since then it has completely broken apparently. At least I can't create a channel in a provider.

![image](https://github.com/louislam/uptime-kuma/assets/26258709/f9a341c9-ac08-4aad-8bc1-3b0a8df9d1b9)
Am I doing something wrong?
Your comment indicates that you got further..

**Comment by Vista2003** [comment]
I went down the messenger API route to get to where am I.

**Comment by CommanderStorm** [comment]
What do you mean by messager API route? 🤔
Said button is grayed out for me..

**Comment by CommanderStorm** [comment]
@Ponkhy You introduced this, and I assume have more knowledge on how this should work.
Are we doing something wrong?

**Comment by Vista2003** [comment]
> What do you mean by messager API route? 🤔
> Said button is grayed out for me.. 

That's odd, I just clicked on it and managed to set it up.

**Comment by Vista2003** [comment]
![image](https://github.com/louislam/uptime-kuma/assets/55105920/dbec072d-5dc0-43de-8999-b49e8697830b)
Yep, I seem to just be able to click on Messager API

**Comment by CommanderStorm** [comment]
Kind of fed up with this notification provider (at least for today)

I thought, to be able to create a messaging chanel, one has to magically know that
- a line account has to be created not only in line.biz,
- but also in their weird mobile app (why do I have to login with google and then with a password?),
- but also in their web app line.me (Why does this need me entering a confirmation code?)
- but also linked to line.biz
  ![image](https://github.com/louislam/uptime-kuma/assets/26258709/692d6c9f-00ad-4786-afdf-2411fe36996f)
- And after moving from here to there
  ![image](https://github.com/louislam/uptime-kuma/assets/26258709/8a54092a-3a80-4173-96dc-fc49d861c625)

This still won't allow creation of anything in their interface (Why does it not just tell me what is wrong with my account? Who is this designed for?)

**Comment by CommanderStorm** [comment]
> LINE's dev portal doesn't have have a Channel access token anymore but instead seems to have Channel secrets instead, this this change anything on how Uptime Kuma communicates with LINE's API?

Their docs at least don't talk about channel secrets.
https://developers.line.biz/en/docs/basics/channel-access-token/#channel-access-token-types

We are both talking about `LINE Messanger` and not `LINE Notify`?
![image](https://github.com/louislam/uptime-kuma/assets/26258709/6e4d50c1-0657-4740-af81-e98c9b0d9971)

**Comment by Vista2003** [comment]
Yes, we are talking about LINE Messanger, not Notify.

This is what I can see when I create a Messanger API

![image](https://github.com/louislam/uptime-kuma/assets/55105920/036601a6-384f-4e8f-8d0f-cde3e69196f2)

**Comment by Vista2003** [comment]
Wait, I figured it out. The text on the Kuma webUI is outdated.

![image](https://github.com/louislam/uptime-kuma/assets/55105920/c912ce74-5a3a-4093-9945-73a2c731ba31)
Turns out there is a token but it's under messenger API and not basic settings and the User ID is the User ID shown in the basic settings

**Comment by CommanderStorm** [comment]
What text (exactly) would you put where? (said Page won't load for me due to above mentioned issues)
![image](https://github.com/louislam/uptime-kuma/assets/26258709/5db319ba-ee98-49c5-8275-bdb25b7bdafe)

If you'd like to have this as a contribution, changing helptexts is obviously also possible via pull requests.
Files:
- form [`src/components/notifications/Line.vue`](https://github.com/louislam/uptime-)kuma/blob/master/src/components/notifications/Line.vue
- translations in [`src/lang/en.json`](https://github.com/louislam/uptime-kuma/blob/master/src/lang/en.json)
