### ISSUE TITLE
warning before something is posted

### ISSUE THREAD

**Issue by LeoThies** [louislam/uptime-kuma#4529]
### 📑 I have found these related issues/pull requests

unable to find any related issues.

### 🏷️ Feature Request Type

Dashboard

### 🔖 Feature description

Should be showing something like this: "warning: everyone can see this. Are you sure you wanted to post that?". You have to press "okay" before posting.

### ✔️ Solution

For an effective and clear warning message that appears before posting, the text could be redesigned as follows:

Warning: This post will be visible to everyone. Please double-check if you really want to share this. By clicking 'OK', you confirm that you are ready to publish your post.

**Comment by LeoThies** [comment]
![image](https://github.com/louislam/uptime-kuma/assets/115998386/4a4131ef-d9d4-4692-b388-bff168103a35)
If I press "Eintrag" there should be showing something like this: "warning: everyone can see this. Are you sure you wanted to post that?"

**Comment by CommanderStorm** [comment]
I don't think this is nessesary.
If you post an incident to a public status page, you would expect that to be public, right?
![image](https://github.com/louislam/uptime-kuma/assets/26258709/55673860-5340-439c-8784-8b7e1ff4988a)

I agree that the German translation is a bit weird. See https://weblate.kuma.pet/ if you want to propose a different one.

**Comment by LeoThies** [comment]
Thanks a lot! 
It is like you said.

German translation is often weird. Would be nice if we could edit the text ourselves
