### ISSUE TITLE
Send notification every minitus ?

### ISSUE THREAD

**Issue by Rakkoc** [louislam/uptime-kuma#4531]
### 📑 I have found these related issues/pull requests

There is an online system that I follow. When an error occurs, it sends a notification via Telegram. But I don't see it when it comes while I'm sleeping. How can there be a system that will notify me every minute and force me until I wake up?

### 🏷️ Feature Request Type

Change to existing notification-provider

### 🔖 Feature description

I can be sleeping when the system gives an error. How can I make it send a notification that will wake me up so that I can intervene immediately?

### ✔️ Solution

may defrent application same critical alerts.

**Comment by CommanderStorm** [comment]
You can do so by adjusting these two values:
![image](https://github.com/louislam/uptime-kuma/assets/26258709/3ee3ea73-587f-4320-bf6c-361cee938e13)

**Comment by Rakkoc** [comment]
Thank you for help. i saw it now.
