### ISSUE TITLE
Kuma stops working after ~5 minutes

### ISSUE THREAD

**Issue by PapeThePope** [louislam/uptime-kuma#4539]
### ⚠️ Please verify that this question has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

Hi im using uptime-kuma in a docker container on a redhat system.
Unfortunately after working for around 5 Minutes uptime-kuma just stops working. The container seems to be loosing any network connectivity.
It cant Ping a local server and it cant be accessed via Browser.

### 📝 Error Message(s) or Log

On Container Restart i get the following error (only if i restart after its broken): 
```
Emulate Docker CLI using podman. Create /etc/containers/nodocker to quiet msg.
ERRO[0004] Unable to clean up network for container XXX: "tearing down network namespace configuration for container XXX: 1 error occurred:
    * plugin type=\"bridge\" failed (delete): cni plugin bridge failed: running [/sbin/iptables -t nat -D POSTROUTING -s XX.XX.XX.XX -j CNI-ABC -m comment --comment name: \"podman\" id: \"XXX\" --wait]: exit status 2: iptables v1.8.5 (nf_tables): Chain 'CNI-ABC' does not exist
Try `iptables -h' or 'iptables --help' for more information."
```

### 🐻 Uptime-Kuma Version

1.23.3

### 💻 Operating System and Arch

Red Hat Enterprise Linux release 8.9

### 🌐 Browser

Chrome Version 122

### 🖥️ Deployment Environment

- Runtime: podman version 4.6.1
- Database: SQLLITE (Container Standard Settings)
- Filesystem used to store the database on: container internal?
- number of monitors: 1

**Comment by CommanderStorm** [comment]
I think your podman installation has some defects. Have you looked here:
- https://github.com/containers/podman/issues/5335
- Given that you specified RHEL, maybe you can (I can't) access https://access.redhat.com/solutions/4859291

**Comment by PapeThePope** [comment]
I have another application on the same host in a container and this one is working fine :( 
For example it also connects the same local server.

It seems so weird that it just stops after ~5 Minutes and before everything is fine?

I looked at the first link, but cant find a good comparison to my problem, especially with the other app working in mind. And unfortunately i dont have access the redhat forums

**Comment by CommanderStorm** [comment]
have you looked into the podman logs what happes at the 5m mark?

**Comment by PapeThePope** [comment]
The only thing i see in the logs of the pod is:
2024-02-29T08:30:51+01:00 [MONITOR] WARN: Monitor #1 'XXX': Pending: PING XXX (XXX) 56(84) bytes of data.
--- XXX ping statistics ---
10 packets transmitted, 0 received, 100% packet loss, time 242ms

Which goes in line, that the pod just looses connection, as the server is reachable from the host and other container.
Time varies though. Was like 10 Minutes now.

**Comment by CommanderStorm** [comment]
I am not talking about the pod logs, I am talking about the podman logs (i.e. the logs of your runtime, not the pod being run)

**Comment by louislam** [comment]
> exit status 2: iptables v1.8.5 (nf_tables): Chain 'CNI-ABC' does not exist
Normally Podman will add some rules to the iptables (firewall) silently. I guess you have other programs which removed/overrided Podman's rules. For my experience, VestaCP's Firewall GUI did that.

**Comment by PapeThePope** [comment]
> I am NOT talking about the pod logs, I am talking about the podman logs (i.e. the logs of your runtime, not the pod being run)

Actually Podman did not log anything for that, funny stuff :(

I did **change the network mode to host**, which solved the issue in my case, as it is ok for me to run it like that.

**Comment by TechJedi51** [comment]
I am seeing the same thing in Portainer. This just started to happen after the last update.
