### ISSUE TITLE
Still alert for certificate expires, even if TLS/SSL errors for HTTPS sites are ignored

### ISSUE THREAD

**Issue by eraizi** [louislam/uptime-kuma#4540]
### ⚠️ Please verify that this question has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

When monitoring a site with a self-signed certificate over HTTPS, if you set to ignore TLS/SSL errors for HTTPS sites, you will not receive alert emails when the certificate expires.

### 🐻 Uptime-Kuma Version

1.23.7

### 💻 Operating System and Arch

windows10

### 🌐 Browser

Chrome

### 🖥️ Deployment Environment

- Runtime: 
- Database: 
- Filesystem used to store the database on: 
- number of monitors:

**Comment by CommanderStorm** [comment]
I don't quite get this question.
If you ignore TLS/SSL errors, this includes ignoring the certificate expires.

If you are asking how to register your custom CA, please consider using the `NODE_EXTRA_CA_CERTS` environment variable to add your self-signed ca certs. (e.g. `/cert/path/CAcert.pem`) [Read more](https://github.com/louislam/uptime-kuma/issues/1380)

**Comment by eraizi** [comment]
I modify the file ecosystem.config.js:
module.exports = {
    apps: [{
        name: "uptime-kuma",
        script: "./server/server.js",
		env_production: {
        NODE_ENV: "production",
        NODE_EXTRA_CA_CERTS: "./cert/test.crt"
       }
    }]
};

restart :
node server/server.js

the error still exists: Certificate chain invalid

**Comment by CommanderStorm** [comment]
`node server/server.js` does not utilise any `ecosystem.config.js`.
`ecosystem.config.js` is a file used by `pm2`, see https://pm2.keymetrics.io/docs/usage/application-declaration/

**Comment by eraizi** [comment]
when run command is  node server/server.js, how to config  NODE_EXTRA_CA_CERTS

**Comment by CommanderStorm** [comment]
How you configure environvent variables for commandline calls depends on your OS.
Given that you did leave this field (`Runtime`, `Filesystem`) empty above I can't quite help you with this.

On posix based systems, this would be 
```sh
export NODE_EXTRA_CA_CERTS=value
node server/server.js
```

**Comment by CommanderStorm** [comment]
Ok, glad to know that that worked for you
