### ISSUE TITLE
Add a custom notification

### ISSUE THREAD

**Issue by HuhuGamingTTV** [louislam/uptime-kuma#4542]
### ⚠️ Please verify that this question has NOT been raised before.

- [x] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

Hello!

I'd like to know how to add a notification, like a second Discord but with a different code. I've tried importing into the code and doing the necessary but it never shows up in the form when I create or edit a notification.

If you can help me, thank you!!

### 🐻 Uptime-Kuma Version

1.23.11

### 💻 Operating System and Arch

Ubuntu 22.04

### 🌐 Browser

Google Chrome 122.0.6261.70

### 🖥️ Deployment Environment

- Runtime: Docker 25.0.3
- Database: SQLite
- Filesystem used to store the database on: ZFS on an SSD
- number of monitors: 1 (monitor like screen?)

**Comment by CommanderStorm** [comment]
> I've tried importing into the code and doing the necessary

From this description, it is difficult to infer what precisely you did try.

Please refer to one of the merged PRs (f.ex. https://github.com/louislam/uptime-kuma/pull/2956/files) for all the files that need changing for a notification provider to be recognised.
