### ISSUE TITLE
Uptime Kuma in Pterodactyl want to use Cloudflare Tunnel help

### ISSUE THREAD

**Issue by Jauniii** [louislam/uptime-kuma#4546]
### ⚠️ Please verify that this question has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

Hello there, i have a ubuntu server with pterodactyl, i set uptime kuma up in pterodactyl but now it has a port behind it i want it to go from ip:port to subdomain.domain.tld, it wouldn´t make sense to use a nginx proxy, because it´s already hosted on a nginx server, that´s why i want to use cloudflare tunnel i already read the guide "https://github.com/louislam/uptime-kuma/wiki/Reverse-Proxy-with-Cloudflare-Tunnel" and i followed every instruction, but it´s not working

### 🐻 Uptime-Kuma Version

1.23.11

### 💻 Operating System and Arch

Ubuntu 22.04

### 🌐 Browser

Google Chrome 122.0.6261.95

### 🖥️ Deployment Environment

- Runtime: Pterodactyl/Docker
- Database: none
- Filesystem used to store the database on: 
- number of monitors:

**Comment by CommanderStorm** [comment]
> it wouldn´t make sense to use a nginx proxy, because it´s already hosted on a nginx server

What do you mean with this statement?

> it´s not working

Could you please go into details what you are meaning here? (Include logs, what you tried, ...)

**Comment by Jauniii** [comment]
yes hello thank you for replying i want to have uptime kuma in my pterodactyl panel, that´s why
> it wouldn´t make sense to use a nginx proxy
i set everything up like in the guide and i am receiving confirmations in uptime kuma and in ssh, that they are connected and also confirmation in cloudflare, but there is nothing on the domain i set up for it

**Comment by CommanderStorm** [comment]
What do you mean with "nothing on the domain"?
Are you refering to dns not resolving, white page, 404, ...

**Comment by CommanderStorm** [comment]
> > it wouldn´t make sense to use a nginx proxy, because it´s already hosted on a nginx server
> 
> I want to have uptime kuma in my pterodactyl panel, that´s why

I don't quite get this part.
So you are running an nginx server with pterodactyl and now want to use cloudflare to do what?
Wouldn't it make more sense to use the nginx server for this too?

**Comment by Jauniii** [comment]
if you visit https://uptime.lebenmc.de/ then you can see, that there isn´t anything
i get Error code 502
no because then i would have nginx two times

**Comment by Jauniii** [comment]
![image](https://github.com/louislam/uptime-kuma/assets/161231746/c36cf133-742a-4450-958a-0e6158fc1817)
look here´s my setting

**Comment by Jauniii** [comment]
> > > it wouldn´t make sense to use a nginx proxy, because it´s already hosted on a nginx server
> > 
> > 
> > I want to have uptime kuma in my pterodactyl panel, that´s why
> 
> I don't quite get this part. So you are running an nginx server with pterodactyl and now want to use cloudflare to do what? Wouldn't it make more sense to use the nginx server for this too?

i have uptime kuma in my pterodactyl panel and want it to be uptime.lebenmc.de instead of 45.90.97.161:3001

**Comment by CommanderStorm** [comment]
Have you tried `http://localhost:3001`?
What were the results with this Sevice?

![image](https://github.com/louislam/uptime-kuma/assets/26258709/df7dfdb2-fa05-4f0a-811d-027bd4d734cd)

**Comment by Jauniii** [comment]
It worked
ty so much

**Comment by Jauniii** [comment]
have a good day

**Comment by Jauniii** [comment]
do you know if i can do that with an nginx egg also in pterodactyl?
if i have 45.90.97.161:25252 but with an nginx egg, how can i do that, because nginx doesn´t have a cloudflare tunnel option

**Comment by CommanderStorm** [comment]
What are you trying to do in the first place?

If you are trying to move your site behind a cloudflare tunnel, please see https://github.com/louislam/uptime-kuma-wiki/pull/46/files

**Comment by CommanderStorm** [comment]
> It worked

Closing as resolved
