### ISSUE TITLE
Paused monitors included in uptime percentage on status page

### ISSUE THREAD

**Issue by will-knoll** [louislam/uptime-kuma#4549]
### ⚠️ Please verify that this question has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

I'm not sure if this is a bug or if this is the intended behavior, so I wanted to ask the community. I have paused 2 of the 64 monitors. All 64 monitors are included in the primary status page. At the top of the status page it says "Partially Degraded Service", I then scroll down and all active monitors are up.

My initial reaction is the two paused monitors should not be included when determining if the service is partially degraded. However, I wanted to get the community's feedback.

### 🐻 Uptime-Kuma Version

1.23.11

### 💻 Operating System and Arch

Ubuntu 22.04

### 🌐 Browser

Microsoft Edge 122.0.2365.66

### 🖥️ Deployment Environment

- Runtime: Docker 25.0.3
- Database: sqlite
- Filesystem used to store the database on: ext4 on SSD
- number of monitors: 64

**Comment by CommanderStorm** [comment]
For the current behaviour, I would classify this is intended behaviour.
If monitors are paused this means we cannot determine their status => cannot say that everything is up.

https://github.com/louislam/uptime-kuma/blob/574705a4c3041d65b752bbcffd3fb8324c74d832/src/pages/StatusPage.vue#L529-L555

**Comment by will-knoll** [comment]
Thank you, CommanderStorm. I'm not sure I agree though. The way I see it is a paused monitor is like a switchport on a Cisco network switch being administratively down- someone configured the switchport to be down, just like someone configured the monitor to be paused.

A better status message would be "Good (2 monitors paused)" with the logic added to the if statement on 541
```
if (beat.status === PAUSED) { 
   return STATUS_PAGE_WITH_PAUSED; 
} else if ...
...
```

**Comment by mininmobile** [comment]
hate stale bots, this should not have been closed..

**Comment by mininmobile** [comment]
another use case in addition to will-knoll's; i want to be able to list paused, offline servers on the status page as backup capacity

perhaps a better way to go about this is to check if a monitor has a tag with the value of `non-critical` or similar, and if so, exclude it from this total server status

maintainer pls reopen

**Comment by CommanderStorm** [comment]
> hate stale bots

Sorry, but this is the only way we can deal with the level of support `help`-requests (other requests don't have this automation) we get.

**Comment by CommanderStorm** [comment]
I have stated my opinion above that the current behavior not a bug and intended behavior.
Though, I can see that users might find the current behavior mildly confusing.

=> If someone would provide a PR changing this to be better communicated (`... (2 monitors paused)`), this would get reviewed and merged if good.
Our contribtuion guide is here: https://github.com/louislam/uptime-kuma/blob/c919d2c990beba0d5d91b28f436b43296b6992b0/CONTRIBUTING.md

The rest of your comment (listing offline servers as backup capacity, tag based status exclusion) is off-topic.
Listing offline servers as backup capacity can be achived by adding a tag to them.

**Comment by mininmobile** [comment]
yeah i have the monitors tagged, just wish they wouldn't make the service appear "degraded" when i list them on the status page >m<
