### ISSUE TITLE
How to use external DB to store the endpoints details in kuma

### ISSUE THREAD

**Issue by guru91197** [louislam/uptime-kuma#4551]
### ⚠️ Please verify that this question has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

Hi Team,

Could you please let me know is it possible us can configure an external DB to use Kuma, storing all the uptime information?..

If it is possible please share link for the configuration 

Thanks
Gulab

### 🐻 Uptime-Kuma Version

Version: 1.23.11

### 💻 Operating System and Arch

ubuntu

### 🌐 Browser

google chrome

### 🖥️ Deployment Environment

- Runtime:  Docker
- Database:  inbuilt SQL 
- Filesystem used to store the database on:  yes
- number of monitors:  100

**Comment by CommanderStorm** [comment]
`v2.0` will come with the ability to use internal or external mariadb. External postgres is tracked here: #959 
See our pinned post for the steps that need to be done to get there: https://github.com/louislam/uptime-kuma/issues/4500
