### ISSUE TITLE
Installation on Pterodactyl

### ISSUE THREAD

**Issue by dev-kinsukghosh** [louislam/uptime-kuma#4552]
### ⚠️ Please verify that this question has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

so i am using uptime karma at a hosting and i changed the port which they are giving me but when i visit that website there saying the site cant be reached and in consoul it saying db-config.json not found and i can only use code which are avable in startup am using node.js server idk what the problemcan anyone help me
that server running on linix

### 📝 Error Message(s) or Log

2024-03-05T10:52:46Z [SERVER] INFO: Env: production
2024-03-05T10:52:47Z [SERVER] INFO: Uptime Kuma Version: 2.0.0-dev
2024-03-05T10:52:47Z [SERVER] INFO: Loading modules
2024-03-05T10:52:48Z [SERVER] INFO: Creating express and socket.io instance
2024-03-05T10:52:48Z [SERVER] INFO: Server Type: HTTP
2024-03-05T10:52:48Z [SERVER] INFO: Custom hostname: 0.0.0.0
2024-03-05T10:52:48Z [SERVER] INFO: Data Dir: ./data/
2024-03-05T10:52:48Z [SETUP-DATABASE] INFO: db-config.json is not found or invalid: ENOENT: no such file or directory, open 'data/db-config.json'
2024-03-05T10:52:48Z [SETUP-DATABASE] INFO: Starting Setup Database on 35438
2024-03-05T10:52:48Z [SETUP-DATABASE] INFO: Open http://0.0.0.0:35438 in your browser
2024-03-05T10:52:48Z [SETUP-DATABASE] INFO: Waiting for user action...

### 🐻 Uptime-Kuma Version

1.23.10

### 💻 Operating System and Arch

linix

### 🌐 Browser

brave

### 🖥️ Deployment Environment

- Runtime: nodejs version 20
- Database: idk how to change
- Filesystem used to store the database on: idk
- number of monitors: 0

**Comment by dev-kinsukghosh** [comment]
@louislam

**Comment by CommanderStorm** [comment]
@dev-kinsukghosh 
You have not really presented a lot of context.
You are using `2.0.0-dev`. Is that intentional?
If yes, which [steps of our contribution guide](https://github.com/louislam/uptime-kuma/blob/master/CONTRIBUTING.md) have you followed to get there?

Note that installing stable versions can be done via our installation guide:
https://github.com/louislam/uptime-kuma/wiki/%F0%9F%94%A7-How-to-Install

**Comment by dev-kinsukghosh** [comment]
bro if you like want more info just sent me as
- info1
- info2
- info3
- etc

**Comment by dev-kinsukghosh** [comment]
and i dont have ssh acces to server as its a shered server the server runs on [Pterodactyl]

**Comment by dev-kinsukghosh** [comment]
3 here the startup commond in startup tab how server will start
``
if [[ -d .git ]] && [[ 1 == "1" ]]; then git pull; fi; if [[ ! -z ${NODE_PACKAGES} ]]; then /usr/local/bin/npm install ${NODE_PACKAGES}; fi; if [[ ! -z ${UNNODE_PACKAGES} ]]; then /usr/local/bin/npm uninstall ${UNNODE_PACKAGES}; fi; if [ -f /home/container/package.json ]; then /usr/local/bin/npm install; fi; /usr/local/bin/node /home/container/index.js
``

**Comment by dev-kinsukghosh** [comment]
oh also wait let me give few screenshot of tabs

![image](https://github.com/louislam/uptime-kuma/assets/143876955/4860e137-4c2b-4293-aea0-48b37a3b670e)
![image](https://github.com/louislam/uptime-kuma/assets/143876955/1848454f-53ec-4c5e-b4ae-a7d059f6a8b3)
![image](https://github.com/louislam/uptime-kuma/assets/143876955/e80f38fb-9006-4a4a-9e98-33c2139b45b5)
![image](https://github.com/louislam/uptime-kuma/assets/143876955/ae311c37-b29e-4c3a-a1e8-7ca7f612fadb)

**Comment by CommanderStorm** [comment]
The command you are using is not correct.
You are installing master because your command pulls master: `if [[ -d .git ]] && [[ 1 == "1" ]]; then git pull; fi`

Please refer to our installation guide instead:
https://github.com/louislam/uptime-kuma/wiki/%F0%9F%94%A7-How-to-Install#-non-docker

Note that where it states the container to use, you likely should put our docker container instead. Some features are locked behind docker (Cromium Browser, …) while only the Tailscale monitor is locked behind node.

**Comment by dev-kinsukghosh** [comment]
@CommanderStorm  like first problem fix i was stupid so but another problem arose 
the first problem was i was using the correctt url was using in but the server is of de to used de url now its fine but 2 problem
http://de-prem-01.hosts.optikservers.com:35438/setup-database its showing blank here what i do

**Comment by CommanderStorm** [comment]
`/setup-database` is a `v2.x`-family url.


<details><summary><code>v1.x</code> does not contain this URL.</summary>
<p>

![image](https://github.com/louislam/uptime-kuma/assets/26258709/8ecab712-4d55-4a29-91d7-04c5feab33c9)

</p>
</details> 


I am assuming you are still running `2.0.0-dev`. 
Note that we are outputting the uptime kuma version in the log:

**Comment by dev-kinsukghosh** [comment]
so what i do yes running 2.0

**Comment by dev-kinsukghosh** [comment]
running this version of uptimekuma
https://github.com/louislam/uptime-kuma/releases/tag/1.23.11

**Comment by CommanderStorm** [comment]
I am assuming switching from running `2.0.0-dev` to running `1.23.11` resolved your issue

**Comment by gOOvER** [comment]
> running this version of uptimekuma https://github.com/louislam/uptime-kuma/releases/tag/1.23.11

there is allready an egg for ptero, which works fine and with tha latest stable version ;)
