### ISSUE TITLE
monitoring giving socket hang up

### ISSUE THREAD

**Issue by Vanieltk** [louislam/uptime-kuma#4553]
### ⚠️ Please verify that this question has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

Hello dear ones!

I have a problem with my kuma uptime, and I can't find a solution.

Just from yesterday, monitoring started to give this socket hang up error, in a very large and frequent way, in all monitoring.
This error had been occurring for some time, but very sporadically and very little, almost imperceptibly, but yesterday it started to notify much more frequently and in all monitoring, in an interspersed way, it gives the warning, then it stays up, and then notify again.

I've done everything, changed the version, cleaned the base, stopped the container and uploaded it again, but nothing resolved it, remembering that there was no type of change on the environment side.

Please thank anyone who can help me.

### 📝 Error Message(s) or Log

![Screenshot_20240305_083723](https://github.com/louislam/uptime-kuma/assets/73503310/748b1e98-9d80-4536-a34e-62e9ba0926d8)

### 🐻 Uptime-Kuma Version

1.23.11

### 💻 Operating System and Arch

Container uptime/kuma

### 🌐 Browser

Google Chrome

### 🖥️ Deployment Environment

- Runtime: K8S, EKS 1.27
- Database: sqllite
- Filesystem used to store the database on: EBS GP2
- number of monitors: 120

**Comment by CommanderStorm** [comment]
- what is your database size and retention set to (just as a precaution, not likely related)
- Could you have a look at https://github.com/louislam/uptime-kuma/wiki/Troubleshooting and see if you can reproduce this in a shell to give more context?

**Comment by Vanieltk** [comment]
I managed to solve the problem, it really was something within our network, which we ended up discovering.

**Comment by Tscherno** [comment]
@Vanieltk Anything you could share? Having the same issue since yesterday and i am guessing something network related, but no concrete clue so far.
