### ISSUE TITLE
Dynamic Naming for Uptime Kuma Monitoring

### ISSUE THREAD

**Issue by sashkomel6** [louislam/uptime-kuma#4555]
### 📑 I have found these related issues/pull requests

I checked and didn't find similar feature request.

### 🏷️ Feature Request Type

API / automation options

### 🔖 Feature description

Uptime Kuma system has the capability to monitor dozens of different resources, each with a unique name. However, creating separate notifications for each monitor can be a cumbersome process, especially as the number of monitors grows significantly.

### ✔️ Solution

The proposed feature involves the ability to use dynamic names for monitors in the Uptime Kuma system. Instead of creating individual notifications for each monitor with different names, users can utilize the $name variable, which automatically takes the name of the monitor when sending the notification. This simplifies the notification setup process and enables efficient management of a large number of monitors.

### 📝 Additional Context

![Знімок екрана 2024-03-06 144043](https://github.com/louislam/uptime-kuma/assets/45562029/95caea74-ee8b-44de-8253-3a2db8336771)

**Comment by CommanderStorm** [comment]
So you want templating in the friendly name in the monitor setup.
Why? Said field is AFAIK not displayed to the public. It is only use to select which notification providers to send messages to.
![image](https://github.com/louislam/uptime-kuma/assets/26258709/18877292-d566-492b-b84e-529b91e1d202)
Am I missing something?

**Comment by sashkomel6** [comment]
Yes, templating friendly names of monitors is beneficial for the convenience and efficiency of managing the monitoring system, even if they are not displayed publicly. This way, I won't need 80 notifications for each monitoring, but with a general name.

**Comment by CommanderStorm** [comment]
What are you trying to achieve in the first place?

I don't we are on the same page.
If what you asked were to be implemented:
- `monitor 1`: notifications > `<template would be applied here>`
- `monitor 2`: notifications > `<template would be applied here>`

Both of which link to the same notification provider, but behave identical.
The friendly name should only be available in the frontend
=> should not affect notification you receive in telegram.

What is displayed in the notifications does not display the friendly name. 
![image](https://github.com/louislam/uptime-kuma/assets/26258709/db563e29-e07d-468f-8851-65b1fb87ffc9)

**Comment by sashkomel6** [comment]
![1](https://github.com/louislam/uptime-kuma/assets/45562029/30399a1d-cb19-4fdc-8651-ce13527cfdac)
Example: I have 2 monitors, 1 Ubuntu and 2 WIN2022, and in order for me to receive separate notifications for each with the monitor identifier, I need to create 2 separate notifications.
![2](https://github.com/louislam/uptime-kuma/assets/45562029/6808ab1b-790f-4706-84ff-61395d3764a0)
Can I make it so that when creating a notification I can choose, for example, $name, and it automatically takes the name of the monitor. 
![3](https://github.com/louislam/uptime-kuma/assets/45562029/e35223d2-6ffd-4240-b41d-697c99e1fad3)
And I would have 1 notification for each monitor, and in Telegram I would receive information for each monitor.
![4](https://github.com/louislam/uptime-kuma/assets/45562029/0e8d98bc-b350-4bfa-bafc-584c94201b47)

**Comment by CommanderStorm** [comment]
You don't actually want what you are asking for, because you don't need to configure that.
See my example above, the monitor name is already included in the notification.
It is not included for the testing notifications, as we don't have a monitor to send information about.

Aligning the testing and actual notifications would likely be a good thing, but doing such a major reworking would be a lot of effort.
Currently, the notifications subsystem is not designed to allow for this level of templating/..
The work in this area is tracked in https://github.com/louislam/uptime-kuma/issues/646

I am going to close this issue as resolved because the needed work is better tracked in https://github.com/louislam/uptime-kuma/issues/646 and because I think your underlying issue is resolved.
