### ISSUE TITLE
Using slack `Username` is missing the necessary helptext to explain what it does

### ISSUE THREAD

**Issue by ojbkxiongdei** [louislam/uptime-kuma#4560]
### 📑 I have found these related issues/pull requests

Using slack webhook and filling in the user ID or name, the @ corresponding person cannot be alerted.

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### Description

| varaint1 | varaint2 |
|--------|--------|
| ![image](https://github.com/louislam/uptime-kuma/assets/55149555/f65c6aec-f701-425a-a875-9747edef98b3) | ![image](https://github.com/louislam/uptime-kuma/assets/55149555/5d4aaa4a-9592-456d-a6a8-b67c496c8419) | 

### 👟 Reproduction steps

Refer to the 2 pictures above

### 👀 Expected behavior

I hope slack alerts will be sent to specified users

### 😓 Actual Behavior

Filling in the slack user parameters does not take effect, and the actual alarm is not sent to the user.

### 🐻 Uptime-Kuma Version

1.23.11

### 💻 Operating System and Arch

k8s

### 🌐 Browser

chrome

### 🖥️ Deployment Environment

- Runtime: k8s
- Database: local
- Filesystem used to store the database on: nfs
- number of monitors: 

### 📝 Relevant log output

```shell
no
```

**Comment by CommanderStorm** [comment]
have you tried just using `@...` or just `...` (without `<@>`)?

@NiNiyas Given that you have introduced this in
https://github.com/louislam/uptime-kuma/pull/61/
How should this field be used?

**Comment by NiNiyas** [comment]
Hey, I don't use slack anymore, but looking at https://api.slack.com/messaging/sending#impersonation, it seems that it is only for impersonation and not for tagging a user. If you want to tag, I think you need to include the username in the message text itself.

**Comment by sanjogbhalla16** [comment]
I would love to contribute in this , this is my first time , can you please guide me how to do it

**Comment by CommanderStorm** [comment]
Shure ❤️.

Here are the relevant links:
- our contributing guide on how to setup a dev environment: https://github.com/louislam/uptime-kuma/blob/e8c650797c80fe7189091afa9a81d4bad679dac1/CONTRIBUTING.md
- The file at question: https://github.com/louislam/uptime-kuma/blob/master/src/components/notifications/Slack.vue
- (if nessesary) vue-i18n's component translations for adding links: https://vue-i18n.intlify.dev/guide/advanced/component.html

**Comment by sanjogbhalla16** [comment]
Thank You @CommanderStorm, for your kind support , please assign this task to me and also label it under hacktoberfest-2024.

**Comment by CommanderStorm** [comment]
We don't assign people and that label is not necessary=> no

**Comment by R-HNF** [comment]
I'll try this!

**Comment by R-HNF** [comment]
I've submitted PR #5259!
