### ISSUE TITLE
Immediate Ad-Hoc "Single Maintenance Window" with a Time Limit from the Monitor GUI

### ISSUE THREAD

**Issue by bernarddt** [louislam/uptime-kuma#4564]
### 📑 I have found these related issues/pull requests

#3285: This user has the same type of problem but requires a change to the notification engine.
#4246: This FR needs te monitor to stay active, while my suggestion is more in line of "ignore it for 24 hours".

### 🏷️ Feature Request Type

Settings

### 🔖 Feature description

Have the ability to put a monitor into maintenance mode for a specified duration.

When I have a monitor for a service that are being taken offline for upgrade or an extended duration. I want to be able to "mute" the monitor for a period so that it doesn't continue to email me every 30 minutes that the service is down. 

### ✔️ Solution

Similar to the "Do Not Disturb" function on my phone. I want to go to the monitor that is down, and select a button to put the monitor in maintenance for x hours or days or months.

### ❓ Alternatives

This is essential what maintenance windows are for. But the difference is that the current GUI process think of maintenance windows a recurring or single period in time that you set up ahead of time to "pause" notifications during that window.

Why this doesn't work for me is because I want to rather go to the monitor itself, and then "put it in an ad-hoc maintenance window for a period of time starting now". And not go to Profile > Maintenance, then create a custom "Single Maintenance Window" figure out the start and end date and time, and then associate it with the one monitor. And repeat this for every monitor I want to "pause" for a while.

Where the current maintenance workflow is more geared towards "planned future maintenance". I'm more looking to a "mute this monitor for 24 hours" (ad-hoc maintenance) workflow.

**Comment by CommanderStorm** [comment]
You linked https://github.com/louislam/uptime-kuma/issues/4246.
I think this should be discussed there, becasue I don't see how the core feature (a button on the dashboard which enacts a maintenance window for X hours/...) is differnt. Lets not split the room on this one.

I am going to close this as a duplicate.
