### ISSUE TITLE
Multiple docker tls

### ISSUE THREAD

**Issue by Cacus3** [louislam/uptime-kuma#4569]
### ⚠️ Please verify that this question has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

I want to monitor multiple docker instances.
basing on https://github.com/louislam/uptime-kuma/wiki/How-to-Monitor-Docker-Containers i known how to connect 1 external docker but i want to connect multiple (up to 15 at this moment) :)
How can i do this i must use  certificate eq from my web page on every docker?

### 🐻 Uptime-Kuma Version

1

### 💻 Operating System and Arch

Docker

### 🌐 Browser

chrome

### 🖥️ Deployment Environment

- Runtime: 0
- Database: none
- Filesystem used to store the database on: none
- number of monitors: 0
im not using yet

**Comment by CommanderStorm** [comment]
> How can i do this i must use certificate eq from my web page on every docker?

You can put the FQDN in `DOCKER_TLS_DIR_PATH` as specified in the bottom of the wiki article.

**Comment by Cacus3** [comment]
sorry i missed this part :)
