### ISSUE TITLE
Missing notifications with PUSH monitor

### ISSUE THREAD

**Issue by dponzone** [louislam/uptime-kuma#4570]
### 📑 I have found these related issues/pull requests

I was not able to locate any related issue.

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### Description

I have quite some PUSH monitors (around 200 of them).
They have all the same parameters:
-interval: 70s
-maxretries: 0 (not sure about the importance of this one in my case)

The PUSH URLs are called every 60s with:
?status=up&msg=registered&ping=1 if the monitored service is up
?status=down&msg=unregistered&ping=0 if the monitored service is down

Once in a while, a service goes down, with the right notifications (email+slack):

[Trunk XXXXX] [🔴 Down] unregistered
Time (Europe/Paris): 2024-03-12 08:08:12

but one minute after, the service comes back up (it's not offline anymore on the dashboard) but without any notifications (no event on the dashboard, no email, no slack).

It happens approximatively once a day (one out of approximatively max 10 offline events).
It's not always the same monitors, so it seems quite random.

### 👟 Reproduction steps

It seems random (race condition ?), so I am not sure how to reproduce it.

### 👀 Expected behavior

I should have the UP notifications.

### 😓 Actual Behavior

I miss some UP notifications.

### 🐻 Uptime-Kuma Version

1.23.11

### 💻 Operating System and Arch

Debian 11.8

### 🌐 Browser

Safari

### 🖥️ Deployment Environment

- Runtime: 25.0.3
- Database: sqlite/embedded
- Filesystem used to store the database on: ext4 in VM (host is ZFS on SSD)
- number of monitors: 237

**Comment by dponzone** [comment]
Ok I prefer your maths after edit :)

I was not clear, I knew that because you're missing the issue:

The status of my service is up 1 min later (so the push went OK) but no notifications.

**Comment by CommanderStorm** [comment]
what is the log output of such an event?

**Comment by dponzone** [comment]
Not sure which log you are talking about.
On the dashboard, there is NOTHING for the UP event. Except it's up.
I can't locate any interesting log file in /var/lib/docker/volumes/uptime-kuma.

**Comment by CommanderStorm** [comment]
Logs of containers can be accessed via the [`docker logs`-command](https://docs.docker.com/reference/cli/docker/container/logs/):
```sh
docker logs uptime-kuma
```

**Comment by ifzm** [comment]
I also encountered the same problem. I didn't see the up event, but the timing data seems to have an up result later on. I don't understand why the event is missing, and I only saw the down and retry events in the Docker log

**Comment by ifzm** [comment]
> 我也遇到了同样的问题。我没有看到 up 事件，但计时数据稍后似乎有一个 up 结果。我不明白为什么事件丢失，我只在 Docker 日志中看到了 down 和 retry 事件

This problem doesn't necessarily happen every time. I have felt normal in the past week, and the down and up push are normal. This time, I noticed that the event in the monitoring panel was missing the up

**Comment by ifzm** [comment]
> I also encountered the same problem. I didn't see the up event, but the timing data seems to have an up result later on. I don't understand why the event is missing, and I only saw the down and retry events in the Docker log

This problem doesn't necessarily happen every time. I have felt normal in the past week, and the down and up push are normal. This time, I noticed that the event in the monitoring panel was missing the up 
:(
