### ISSUE TITLE
Ability to monitor Semaphore or Ansible status

### ISSUE THREAD

**Issue by powergrim** [louislam/uptime-kuma#4571]
### 📑 I have found these related issues/pull requests

I run Semaphore to automate my home-lab. So it's all self-hosted. The few playbooks that I have either have run successfully or have failed. I`d like some way to see that reflected in my Uptime Kuma dashboard.

### 🏷️ Feature Request Type

New monitor

### 🔖 Feature description

Some way of obtaining the status of an Ansible Playbook or Semaphore status. In a way that it can show failed/success easily.

### ✔️ Solution

In a way, see a dashboard that gives some sort of UP for a well-running playbook or DOWN for a failed playbook.

### ❓ Alternatives

A webhook to call the latest status would be a way. But any other way to figure this out would be to just look at my Semaphore dahboard. But I like the "One-dashboard-for-all" way of things. And I don't need comprehensive details of what went right or wrong. Just a plain OKAY/NOT-OKAY is fine :).

**Comment by CommanderStorm** [comment]
Semaphore does offer an api at https://www.semui.co/api-docs/
I would recomend you query that via the json-query monitor.

Another alternative (as noted) would be using the push-monitor.

**Comment by CommanderStorm** [comment]
I currently don't see the need for such a monitor.
We can restate this as a FR if you make a good argument why this is not already covered by the existing tooling ^^
