### ISSUE TITLE
Time-based monitoring

### ISSUE THREAD

**Issue by chengdada123** [louislam/uptime-kuma#4573]
### 📑 I have found these related issues/pull requests

no

### 🏷️ Feature Request Type

New monitor, Settings

### 🔖 Feature description

Hope it can be monitored over time. For example, I want to monitor the website from 20:00 at night to 8:00 in the morning. How can I achieve this? Thank you.

### ✔️ Solution

When adding monitoring, there is an option to monitor by time period.

### ❓ Alternatives

NO

### 📝 Additional Context

NO

**Comment by CommanderStorm** [comment]
Currently, I would recommend enacting a scheduled maintenance when you don't want to get notified for downtimes. (=> 7:55-20:05) 
In the future we plan to include more detailed scheduling, but this is tracked in numerous other issues. See https://github.com/louislam/uptime-kuma/pull/3447 and linked issues for our Plan.
