### ISSUE TITLE
domain expiry from whois 

### ISSUE THREAD

**Issue by vanurag63** [louislam/uptime-kuma#4575]
### ⚠️ Please verify that this question has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

i have found that there is no option for DNS expiry. it will be helpfull if this feature is implemented.

thanks in advance

### 🐻 Uptime-Kuma Version

latest

### 💻 Operating System and Arch

ubuntu

### 🌐 Browser

chrome

### 🖥️ Deployment Environment

- Runtime: 
- Database: 
- Filesystem used to store the database on: 
- number of monitors:

**Comment by CommanderStorm** [comment]
@vanurag63 please have a look at the discussion in #944 as stated by the last comment. This issue is a duplicate.
