### ISSUE TITLE
monitor a website with a port and path

### ISSUE THREAD

**Issue by djkingraja** [louislam/uptime-kuma#4576]
### ⚠️ Please verify that this question has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

Hello, is it possible to monitor a website in the format https://i.p.add.ress:port/path e.g. https://1.2.3.4:1045/orders

### 🐻 Uptime-Kuma Version

1.23.11

### 💻 Operating System and Arch

Debian 12

### 🌐 Browser

Google Chrome Version 122.0.6261.112 (Official Build) (64-bit)

### 🖥️ Deployment Environment

- Runtime: nodejs 18.19.0
- Database: sqlite
- Filesystem used to store the database on: ext4
- number of monitors: 3

**Comment by louislam** [comment]
Yes.
