### ISSUE TITLE
Webhook to start and stop maintenance

### ISSUE THREAD

**Issue by upamanyudas** [louislam/uptime-kuma#4578]
### 📑 I have found these related issues/pull requests

https://github.com/louislam/uptime-kuma/issues/3170

### 🏷️ Feature Request Type

API / automation options, Maintenance

### 🔖 Feature description

A webhook that can be called to start and stop a maintenance e.g. when my UnRAID server starts `appdata` backup i can easily run a `pre-backup` script and a `post-backup` script to put my hosted services under maintenance automatically.

### ✔️ Solution

An API / webhook strategy in the `Date and Time` section of `Edit Maintenance`.

**Comment by CommanderStorm** [comment]
@upamanyudas 
I don't see how this is different from the issue you linked:
- https://github.com/louislam/uptime-kuma/issues/2462

=> closing as a duplicate

**Comment by upamanyudas** [comment]
This is a tad different.
The issue I linked sends out notifications after the maintenance has started.
The feat request I'm making is for the maintenance to play or pause depending on calls from external devices / services.

**Comment by CommanderStorm** [comment]
Indeded, I misunderstood you.
So you want an api to create/edit a certain maintenance?
This is tracked in #118 instead => please see https://github.com/louislam/uptime-kuma/pull/3854 for the current status of this

**Comment by cwchristerw** [comment]
I want to activate existing maintenance with webhook.
