### ISSUE TITLE
Is that possible to pass Zenduty tokens via Environment variables 

### ISSUE THREAD

**Issue by Aj7Ay** [louislam/uptime-kuma#4579]
### ⚠️ Please verify that this question has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

we are planning to use uptime kuma for our organisation 
1. API is not supporting to create incidents (Will wait for 2.0 version)
2. Is that possible to pass the Zenduty token via Environment variables while building the project ?

### 🐻 Uptime-Kuma Version

1

### 💻 Operating System and Arch

Ubuntu 22.04

### 🌐 Browser

Google Chrome, Firefox

### 🖥️ Deployment Environment

- Runtime: 
- Database: 
- Filesystem used to store the database on: 
- number of monitors:

**Comment by CommanderStorm** [comment]
> API is not supporting to create incidents

Please see #118 for further details.
The work there is going on, but https://github.com/louislam/uptime-kuma/pull/3854 won't be done for the v2.0 release => was pushed one milestone further.
You can also use the [third party python api wrapper](https://uptime-kuma-api.readthedocs.io/en/latest/) to get this functionality sooner.

> Is that possible to pass the Zenduty token via Environment

We currently also don't offer this notification provider.
All environment variables are listed here: https://github.com/louislam/uptime-kuma/wiki/Environment-Variables

> while building the project

Build time (!= run time) would mean said token is baked into the docker image or the binary.
We don't allow for that for obvious security reasons ^^

**Comment by Aj7Ay** [comment]
I have another query
Is Twilio supporting voice call feature with uptime kuma so we can use it
Other than zenduty

**Comment by CommanderStorm** [comment]
No this is not implemented.
See https://github.com/louislam/uptime-kuma/issues/3295

**Comment by Aj7Ay** [comment]
We are trying to use Twilio sir
Right now we can integrate with Zenduty
When can we expect Twilio sir please

**Comment by CommanderStorm** [comment]
> When can we expect

This is open source.
This is not some faceless corporation with lots of stable engineering effort here.

- work happens when it happens (or not) by people mostly in their spare time.
- We don't offer timelines or deadlines or estimates [except for the nearest of terms](https://github.com/louislam/uptime-kuma/milestones).
   See [#noestimates](https://www.youtube.com/watch?v=QVBlnCTu9Ms) for further context why I don't think that that would add value.

Our contribution guidelines can be found here:
https://github.com/louislam/uptime-kuma/blob/master/CONTRIBUTING.md

**Comment by Aj7Ay** [comment]
I understand sir
Thanks for the Information, and your Time
