### ISSUE TITLE
[Feature Request] Offline messages

### ISSUE THREAD

**Issue by R0GGER** [louislam/uptime-kuma#458]
**Is it a duplicate question?**
No

**Is your feature request related to a problem? Please describe.**
When a monitor goes down you'll a message such as:
- Parse Error: Invalid major version 
- timeout of 48000ms exceeded
- connect EHOSTUNREACH 0.0.0.0:9999
- Request timeout
- Request failed with status code 522

**Describe the solution you'd like**
I prefer to get an offline message without all the technical stuff.      
Just a message when a service is down "Connection Timeout" or "Offline" is enough.

**Comment by Neer171** [comment]
Not agree with this thought, with additional technical info we can know the exact reason of website down without opening dashboard.

**Comment by SpcCw** [comment]
It would be nice to have option for that.

Sometimes monitors are intended for non-technical people, sometimes it is preferable to have them in more compact and readable form.

**Comment by chakflying** [comment]
Closing as I think this would be better tracked in #646.
