### ISSUE TITLE
ntotification delay time

### ISSUE THREAD

**Issue by rhsmart** [louislam/uptime-kuma#4580]
### 📑 I have found these related issues/pull requests

Is it possible to add notification delay time?

### 🏷️ Feature Request Type

Settings

### 🔖 Feature description

Notification delay time.

### ✔️ Solution

Delay notification send if site is down. When site back before notification delay time, notification is canceled and not send.

**Comment by CommanderStorm** [comment]
Retries are already possible.
You can configure how you are alerted in the monitor settings:

![image](https://github.com/louislam/uptime-kuma/assets/26258709/ebf93aaf-28dd-4d4e-a759-fbf73aaca05e)
