### ISSUE TITLE
error: kex_exchange_identification: Connection closed by remote host

### ISSUE THREAD

**Issue by marcolino7** [louislam/uptime-kuma#4582]
### ⚠️ Please verify that this question has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

Hi,
I running Update Kuma in a Docker Container on Raspberry PI 4. Latest Raspbian version, latest docker and latest Update Kuma container. When Update Kuma is running, I got in journalctl lots ot this error:

```
Mar 14 11:22:53 admin sshd[5137]: error: kex_exchange_identification: Connection closed by remote host
Mar 14 11:22:53 admin sshd[5137]: Connection closed by 172.17.0.3 port 35848
Mar 14 11:23:53 admin sshd[5165]: error: kex_exchange_identification: Connection closed by remote host
Mar 14 11:23:53 admin sshd[5165]: Connection closed by 172.17.0.3 port 57844
Mar 14 11:24:53 admin sshd[5194]: error: kex_exchange_identification: Connection closed by remote host
Mar 14 11:24:53 admin sshd[5194]: Connection closed by 172.17.0.3 port 48312
Mar 14 11:25:53 admin sshd[5234]: error: kex_exchange_identification: Connection closed by remote host
Mar 14 11:25:53 admin sshd[5234]: Connection closed by 172.17.0.3 port 37570
```

172.17.0.3 is the IP Address assigned by docker to Update Kuma container.
I run update kuma with this command:
`docker run -d --restart=always -p 3001:3001 -v /var/lib/docker-ext/updatekuma:/app/data --name uptime-kuma louislam/uptime-kuma:latest`

Any help would be appreciated.

Marco

### 📝 Error Message(s) or Log

```
Mar 14 11:22:53 admin sshd[5137]: error: kex_exchange_identification: Connection closed by remote host
Mar 14 11:22:53 admin sshd[5137]: Connection closed by 172.17.0.3 port 35848
Mar 14 11:23:53 admin sshd[5165]: error: kex_exchange_identification: Connection closed by remote host
Mar 14 11:23:53 admin sshd[5165]: Connection closed by 172.17.0.3 port 57844
Mar 14 11:24:53 admin sshd[5194]: error: kex_exchange_identification: Connection closed by remote host
Mar 14 11:24:53 admin sshd[5194]: Connection closed by 172.17.0.3 port 48312
Mar 14 11:25:53 admin sshd[5234]: error: kex_exchange_identification: Connection closed by remote host
Mar 14 11:25:53 admin sshd[5234]: Connection closed by 172.17.0.3 port 37570
```

### 🐻 Uptime-Kuma Version

1.23.11

### 💻 Operating System and Arch

Raspbian 12 (bookworm)

### 🌐 Browser

Chrome/Edge

### 🖥️ Deployment Environment

- Runtime: Docker 25.04
- Database: sqlite/embedded (Default on Docker)
- Filesystem used to store the database on: ext4
- number of monitors: 4

**Comment by CommanderStorm** [comment]
Seems weird.
Lets try to debug this:
Have you `Enable NSCD (Name Service Cache Daemon)` or clicked the `detect Chrome/Chromium Executable` button?

**Comment by marcolino7** [comment]
> Seems weird. Lets try to debug this: Have you `Enable NSCD (Name Service Cache Daemon)` or clicked the `detect Chrome/Chromium Executable` button?

Gi,
thanks for help. it is my mistake. I setup a TCP check on port 22, to verify that SSH is working. I deleted the check and error gone.

It would be intresting to add an SSH check, in order to check if sshd is working, and perform some check via ssh command.
Thanks

Marco
