### ISSUE TITLE
what am I doing wrong

### ISSUE THREAD

**Issue by s4mat** [louislam/uptime-kuma#4586]
### ⚠️ Please verify that this question has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

he don't start

### 📝 Error Message(s) or Log

![изображение](https://github.com/louislam/uptime-kuma/assets/80270161/65146b57-559a-4a3a-9f4f-98c7bb3ae5e7)

### 🐻 Uptime-Kuma Version

21.6.2

### 💻 Operating System and Arch

Termux

### 🌐 Browser

Firefox

### 🖥️ Deployment Environment

- Runtime: 
- Database: 
- Filesystem used to store the database on: 
- number of monitors:

**Comment by CommanderStorm** [comment]
> 21.6.2

We have not published such a version.

The error message pretty clearly states that android is not a supported platflorm. It is not clear what you are trying to do..
