### ISSUE TITLE
Incorrect Cert Expiry Time

### ISSUE THREAD

**Issue by inthenightsky** [louislam/uptime-kuma#4588]
### 📑 I have found these related issues/pull requests

N/A

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### Description

The SSL certificate for my site has renewed for a year, but this isn't reflected on the monitor.

### 👟 Reproduction steps

I'm unsure on exact reproduction steps, but:

* create a new monitor
* make a change to the SSL cert (?)
* observe the information related to the cert (expiry date, days remaining) don't update when the monitor refreshes

### 👀 Expected behavior

The correct information related to the cert should be grabbed and used instead.

### 😓 Actual Behavior

An incorrect expiry date & days remaining are displayed.

### 🐻 Uptime-Kuma Version

1.23.11

### 💻 Operating System and Arch

Ubuntu 20.04.6 LTS x64

### 🌐 Browser

Firefox 123.0.1

### 🖥️ Deployment Environment

- Runtime:  Docker version 25.0.3 
- Database: Local SQLite
- Filesystem used to store the database on: Linux ext4 on an SSD
- number of monitors: 3

**Comment by CommanderStorm** [comment]
I cannot confirm this problem on my device.

Let's debug this to find what is different:
- are you using the dashboard or the status page?
- What happens when you reload the page?

@chakflying what do you think:
Could this be related to https://github.com/louislam/uptime-kuma/pull/4281

**Comment by inthenightsky** [comment]
Thanks for the reply. I'm just using the dashboard, and behaviour is consistent through refreshes and even on another browser.

**Comment by CommanderStorm** [comment]
What happens when you click on this tab in the dashboard? (yould you post a screenshot?)

![image](https://github.com/louislam/uptime-kuma/assets/26258709/ecd57b27-d83f-43b8-9e9f-effa9907624b)

**Comment by inthenightsky** [comment]
Sure,

![image](https://github.com/louislam/uptime-kuma/assets/22177675/9fc1f3a8-669e-4d3a-b432-4935835e3de2)

I've removed the domain name & fingerprint to maintain my privacy, but I'll drop you an email directly with the domain name so you can see it's SSL info.

**Comment by CommanderStorm** [comment]
I think I have a good hint.

When was the last time a ping was executed (we don't support floats as latency => the last ping latency was 4,4 days???).
Am I reading something wrong here?

![image](https://github.com/louislam/uptime-kuma/assets/26258709/d6a39cfe-8bab-42cd-a2bb-a648179d5400)

**Comment by CommanderStorm** [comment]
What monitor are you using?

**Comment by inthenightsky** [comment]
Pings are executing every 60s.

The monitor is HTTP(s) using the Chromium browser engine.

**Comment by CommanderStorm** [comment]
What do you get when hovering over the last ping
![image](https://github.com/louislam/uptime-kuma/assets/26258709/a2e30a40-dbaf-4742-8410-c72a7dd13456)
Are there any events? (Listed below)

**Comment by inthenightsky** [comment]
![image](https://github.com/louislam/uptime-kuma/assets/22177675/a4c1d892-ffb3-4e16-a04f-c9e43507ff40)

There are events, but these relate to the previous monitor type - it was swapped from standard to the Chromium engine a while ago. These don't seem to reflect reality since there's no keyword check option with the Chromium engine type.

![image](https://github.com/louislam/uptime-kuma/assets/22177675/b12c4b54-345b-4d9f-a585-3c26bd838214)

**Comment by inthenightsky** [comment]
A small troubleshooting step I just performed was creating a new monitor again using the Chromium engine type, this time cert expiry stats aren't reported.

New Monitor:
![image](https://github.com/louislam/uptime-kuma/assets/22177675/0d5e40e8-6cd4-4910-92c5-f5efa6bd9d43)

Old Monitor:
![image](https://github.com/louislam/uptime-kuma/assets/22177675/56d9ff2d-0f73-4674-88fe-3978fcf0abf5)

I think when the monitor type was swapped something funky went down.

**Comment by CommanderStorm** [comment]
I am a bit unsure if this is caused by https://github.com/louislam/uptime-kuma/pull/4281 or if `real-browser` need investigating.

Currently, I don't think investigating the second option is worth active consideration given that #4281 is not merged + released.
=> I have changed this to an help issue, as I think looking at this next release is more productive ^^
