### ISSUE TITLE
[Feature Request] Specify maximum allowed ping/latency

### ISSUE THREAD

**Issue by ghost** [louislam/uptime-kuma#459]
Pretty simple one,
It would be nice to have a warning notification if ping/latency exceeds a specified amount, for a specified amount of subsequent checks.
Then the status could show as orange or yellow.

**Comment by lexmozli** [comment]
+1 to this

**Comment by andlil** [comment]
Yes, as of this morning I agree. I have a 4G-link that went from 100 ms to 4500 ms but the check still shows as up even though the connection is entirely unusable.

**Comment by xkx** [comment]
+1 for this.

**Comment by ppowalowski** [comment]
+1 it would help a lot to declare a service as down or mark it yellow (maybe threshold based) as soon as it doesn't respond within a reasonable time.

**Comment by mrja** [comment]
+1!
