### ISSUE TITLE
Exposing Uptime Kuma behind an Application Gateway

### ISSUE THREAD

**Issue by fabry006** [louislam/uptime-kuma#4591]
### ⚠️ Please verify that this question has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

I have been trying to expose Kuma behind an application gateway (e.g. Kong, Apegee ...) but so far I failed.
The issue is that as soon as I connect to the exposed endpoint (e.g /uptime/kuma), the application returns a redirect to /dashboards which fails since the gateway does not know this path (same happen for the /assets)

I tried as well to set the base path in Setting -> Generic to https://mydomain/uptime/kuma but it does not work as well.
I tried also to add an haproxy in front of Kuma that redirects all the calls to 127.0.0.1:3001 but still I have the same issue.

Can you please explain me what to do?
thank you

### 🐻 Uptime-Kuma Version

1.23.11

### 💻 Operating System and Arch

docker

### 🌐 Browser

Chrome, Edge

### 🖥️ Deployment Environment

- Runtime:  Docker
- Database: sqlite

**Comment by CommanderStorm** [comment]
That is currently not supported and not what said setting is used for.
The setting is used for setting the base path (in https://example.com/status/abc this would be https://example.com) used in some notification providers.

See this issue:
- https://github.com/louislam/uptime-kuma/issues/147

If you need just a status page under a certain subdirectory, see the workaround in the wiki https://github.com/louislam/uptime-kuma/wiki/Status-Page#custom-subdirectory--custom-html-on-status-pages instead
