### ISSUE TITLE
Mapping to subDomain

### ISSUE THREAD

**Issue by PaulMcF1987** [louislam/uptime-kuma#4593]
### ⚠️ Please verify that this question has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

I am hosting uptime-kuma on docker
When I run the container via `port:ip` it works fine.
I have mapped the port to a subdomain `https://my.domain.co.uk`
The page loads but there is a red banner at the top which says `Cannot connect to the socket server. [Error: websocket error] Reconnecting...
Using a Reverse Proxy? [Check how to config it for WebSocket](https://github.com/louislam/uptime-kuma/wiki/Reverse-Proxy)`

I have views this page and tried both the `caddy` and `https-portal` options, none of which work, and leave me in the same position

Any help would be much appreciated.

### 🐻 Uptime-Kuma Version

1.22.1

### 💻 Operating System and Arch

Ubuntu 20.04.6 LTS

### 🌐 Browser

Sidekick

### 🖥️ Deployment Environment

- Runtime: 
- Database: 
- Filesystem used to store the database on: 
- number of monitors:

**Comment by DuncanBennie** [comment]
I had this when I was hosting behind Cloudflare and hadn't enabled websockets. If you're using Cloudflare, make sure you enable websockets: https://developers.cloudflare.com/network/websockets/
