### ISSUE TITLE
Hebrew Language - RTL insted LTR

### ISSUE THREAD

**Issue by sharonxd1234** [louislam/uptime-kuma#4594]
### ⚠️ Please verify that this question has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

I use the system with the Hebrew language, and the system should be RTL but is still set to LTR, how can I change so that the system direction is RTL

### 🐻 Uptime-Kuma Version

1.23.11

### 💻 Operating System and Arch

WIndows

### 🌐 Browser

Chrome

### 🖥️ Deployment Environment

- Runtime: 
- Database: 
- Filesystem used to store the database on: 
- number of monitors:

**Comment by CommanderStorm** [comment]
> how can I change so that the system direction is RTL

That is not possible, but we can change the code for that.
Would you like a bugfix against the `1.23.X`-branch to be associated with your account?
https://github.com/louislam/uptime-kuma/blob/bc077cc536ee95b904f9a4a730b1fcedcf1788dd/CONTRIBUTING.md

> [!TIP]
> `Hebrew (Israel)` is `he-IL`.
> 
> The line where we define what language is RTL and what is LTR is here:
https://github.com/louislam/uptime-kuma/blob/bc077cc536ee95b904f9a4a730b1fcedcf1788dd/src/i18n.js#L60

A question as a non-expert (discussion from https://github.com/louislam/uptime-kuma/pull/4394#issuecomment-1906007083):
What is the difference between [`Hebrew (Israel)`](https://weblate.kuma.pet/projects/uptime-kuma/uptime-kuma/he_IL/) and [`Hebrew`](https://weblate.kuma.pet/projects/uptime-kuma/uptime-kuma/he/)?
