### ISSUE TITLE
Pls support threshold alarm

### ISSUE THREAD

**Issue by hadwinfu** [louislam/uptime-kuma#4599]
### 📑 I have found these related issues/pull requests

It is an awesome tool! Could you please add threshold range alarm feature in case to notify some jitters(for ping type).

Thanks~

Btw, page will auto scroll to top when switch period options, I think it's better not move.

**Comment by chakflying** [comment]
The scroll position issue for the PingChart period dropdown should be fixed in #4264.

**Comment by hadwinfu** [comment]
> The scroll position issue for the PingChart period dropdown should be fixed in #4264.

it's weird, I'm sure that I've deploied the lastest version..

**Comment by CommanderStorm** [comment]
https://github.com/louislam/uptime-kuma/pull/4264 is neither merged nor in the 1.x series.

**Comment by CommanderStorm** [comment]
This issue is really unclear what it wants.
How should this work exactly (what would you like to monitor?) what do you mean with threshold for jitter?

@hadwinfu
please fill out the whole form instead of just a single part with unrelated content.
There is a reason why we ask the other parts..
