### ISSUE TITLE
`CORSMissingAllowOrigin` in development

### ISSUE THREAD

**Issue by Saibamen** [louislam/uptime-kuma#460]
For latest commit in `master` branch, I can't connect to frontend.

https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS/Errors/CORSMissingAllowOrigin

![image](https://user-images.githubusercontent.com/905878/134491464-d63b67e9-241b-4f58-a73c-ae65bc993cba.png)

**Info**
Uptime Kuma Version:
Using Docker?: No
OS: Windows 10
Browser: Latest Firefox and Chrome

**Comment by louislam** [comment]
After recent change, setting NODE_ENV to development is a must.
