### ISSUE TITLE
TCP Port Monitoring

### ISSUE THREAD

**Issue by alfredudu** [louislam/uptime-kuma#4606]
### ⚠️ Please verify that this question has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

Hello, I have a problem with a host that constantly gives a refused connection, but I use Uptime Robot Monitoring which works very well

### 📝 Error Message(s) or Log

Flip UP to DOWN
connect ECONNREFUSED

### 🐻 Uptime-Kuma Version

1.23.11

### 💻 Operating System and Arch

Ubuntu 22.04

### 🌐 Browser

Chrome

### 🖥️ Deployment Environment

- Runtime: Node v20.11.1 / Ubuntu 22.04.2
- Database: Dont use
- Filesystem used to store the database on: ext4
- number of monitors: 25

**Comment by CommanderStorm** [comment]
`1.12.11` is ancient.
We don't support such old software => please upgrade


With the level of detail you have given, that could literally be anything from docker networking to a typo in the monitor…
=> Could you fill out the form? (including the deployment environment and the error messages + log). Without this remote debugging is way more painfull than it needs to.

Have you tried https://github.com/louislam/uptime-kuma/wiki/Troubleshooting?

**Comment by alfredudu** [comment]
Sorry my version is: 
Versão: 1.23.11

**Comment by alfredudu** [comment]
"Could you fill out the form? (including the deployment environment and the error messages + log)"

Where I do this?

**Comment by CommanderStorm** [comment]
Please edit the issue-description above and fill out the parts of the form which you ommited

**Comment by alfredudu** [comment]
Hello,

These are the errors that are constantly appearing on some monitors, which I don't understand why, if you need anything more, help me know how I can provide you with so we can resolve this problem, as the application is wonderful.

Flip UP to DOWN
connect ECONNREFUSED

**Comment by CommanderStorm** [comment]
Could you fill out this part of the form as well?

> Deployment Environment
Runtime:
Database:
Filesystem used to store the database on:
number of monitors:

**Comment by alfredudu** [comment]
Where do I get this information? I don't know...

**Comment by CommanderStorm** [comment]
Do the examples in the form help? What are you stuck on precisely?

![image](https://github.com/louislam/uptime-kuma/assets/26258709/39b1c255-afcc-4861-a06e-10221ca61c90)

**Comment by alfredudu** [comment]
Update the description

**Comment by CommanderStorm** [comment]
Okay, so not docker. That closes a few tangents that I was thinking off and not old node which also closes some tangents.
Have you tried to debug if this might be related to firewalls on the network path?

You can do tcp port pings via executing `telnet ip port`.

**Comment by alfredudu** [comment]
No debugging, because UpTime Robot I have these same monitors and they work perfectly, you know...

That's why I didn't try your help.

**Comment by alfredudu** [comment]
Via telnet, there are times when this message is given, and there are times when it isn't...
Unable to connect to remote host: Connection refused

**Comment by CommanderStorm** [comment]
So you have your first hint that there is some firewall/.. in place blocking the requests. I would recomend you to walk the network path towards the monitored service and re-check where this firewall/router doing DPI is.

**Comment by alfredudu** [comment]
OK.

Now could you help me in another situation, I have a reverse proxy on it, and I changed my DNS appointment to Cloudflare, but I'm getting the error:

ERR_TOO_MANY_REDIRECTS

**Comment by alfredudu** [comment]
I disable proxy from cloudflare, set only dns, and work...

**Comment by alfredudu** [comment]
Thanks for all.
