### ISSUE TITLE
Automatically restore after the render platform is deployed

### ISSUE THREAD

**Issue by ohyoxo** [louislam/uptime-kuma#4609]
### ⚠️ Please verify that this question has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

Automatically restore after the render platform is deployed

The database is set up, but it will still be restored to its original state

![image](https://github.com/louislam/uptime-kuma/assets/126952400/47bb217b-7376-4f0b-9d92-e0716be52838)

### 🐻 Uptime-Kuma Version

2.0.0-dev

### 💻 Operating System and Arch

Render

### 🌐 Browser

Google Chrome

### 🖥️ Deployment Environment

- Runtime: 
- Database: 
- Filesystem used to store the database on: 
- number of monitors:

**Comment by CommanderStorm** [comment]
> [!NOTE]
> v2.0 is not ready yet, see #4500 for further context on what needs to be done to get to said state.
> Please don't use it until it is stable or expect to be impacted by breaking bugs.
> 
> You can use our isntallation guide to install a stable version:
https://github.com/louislam/uptime-kuma/wiki/%F0%9F%94%A7-How-to-Install


For your issue it is quite unclear what you mean with
> Automatically restore after the render platform is deployed

Restore from where?

**Comment by ohyoxo** [comment]
> Note
> 
> v2.0 is not ready yet, see #4500 for further context on what needs to be done to get to said state. Please don't use it until it is stable or expect to be impacted by breaking bugs.
> 
> You can use our isntallation guide to install a stable version: https://github.com/louislam/uptime-kuma/wiki/%F0%9F%94%A7-How-to-Install
> 
> For your issue it is quite unclear what you mean with
> 
> > Automatically restore after the render platform is deployed
> 
> Restore from where?

After successfully deploying and registering, the login information will be deleted after a few hours and will be restored to the registration page.

**Comment by CommanderStorm** [comment]
So basically, your cloud provider is not persisting the database. Am I taking this correctly?

Could you please report all the details we asked in above form (`Error Message(s) or Log`,`Deployment Environment`)? It is really hard to remote-debug if don't.
Could you also please share the exact way you are deploying on render?

**Comment by chakflying** [comment]
Render would automatically shutdown idle web services after some delay for the Free tier. Most likely configuration is lost because of this.

https://docs.render.com/free#spinning-down-on-idle

**Comment by CommanderStorm** [comment]
That sounds very much like it. => closing as resolved.
Feel free to reopen if it is not

**Comment by ohyoxo** [comment]
> Render would automatically shutdown idle web services after some delay for the Free tier. Most likely configuration is lost because of this.Render 将在免费层延迟一段时间后自动关闭空闲 Web 服务。很可能因此而丢失了配置。
> 
> https://docs.render.com/free#spinning-down-on-idle

I have connected an external database in the environment variables, and the situation is the same.

**Comment by ohyoxo** [comment]
> So basically, your cloud provider is not persisting the database. Am I taking this correctly?因此，基本上，您的云提供商不会持久化数据库。我做对了吗？
> 
> Could you please report all the details we asked in above form (`Error Message(s) or Log`,`Deployment Environment`)? It is really hard to remote-debug if don't.您能否报告我们在上面表格（ `Error Message(s) or Log` ， `Deployment Environment` ）中询问的所有详细信息？如果不这样做，真的很难进行远程调试。 Could you also please share the exact way you are deploying on render?您能否分享一下您在渲染上部署的确切方式？

There were no error logs, the deployment was successful. The deployment method was simply importing the repository, keeping other settings as default, and then deploying.

**Comment by CommanderStorm** [comment]
What is your exact environment? (redacting secrets)

**Comment by CommanderStorm** [comment]
> There were no error logs

What are the logs of uptime kuma?
I somewhat doubt that there are no logs. 

> keeping other settings as default

When I was asking about the `Deployment Environment`, I was specifically asking what you consider those defaults.
Remember that I don't use render => don't know what these defaults are…

**Comment by ohyoxo** [comment]
> > There were no error logs
> 
> What are the logs of uptime kuma? I somewhat doubt that there are no logs.
> 
> > keeping other settings as default
> 
> When I was asking about the `Deployment Environment`, I was specifically asking what you consider those defaults. Remember that I don't use render => don't know what these defaults are…

![image](https://github.com/louislam/uptime-kuma/assets/126952400/7ea2a335-e289-4a15-be30-83d1217702b0)
![image](https://github.com/louislam/uptime-kuma/assets/126952400/76bbd0c3-d8f2-44ea-ac6c-f5e9662a2be5)
![image](https://github.com/louislam/uptime-kuma/assets/126952400/406b2a53-ce04-45d8-bf38-df8af55a6d57)
This is the settings and Log that I deployed, and I didn't see an error when logging in before

**Comment by chakflying** [comment]
The correct environment variable names (note that these are undocumented and unstable):

```shell
UPTIME_KUMA_DB_TYPE=mariadb
UPTIME_KUMA_DB_HOSTNAME=<your-database-hostname>
UPTIME_KUMA_DB_PORT=3306
UPTIME_KUMA_DB_NAME=<your-database-name>
UPTIME_KUMA_DB_USERNAME=<your-database-username>
UPTIME_KUMA_DB_PASSWORD=<your-database-password>
```

**Comment by ohyoxo** [comment]
> The correct environment variable names (note that these are undocumented and unstable):
> 
> ```shell
> UPTIME_KUMA_DB_TYPE=mariadb
> UPTIME_KUMA_DB_HOSTNAME=<your-database-hostname>
> UPTIME_KUMA_DB_PORT=3306
> UPTIME_KUMA_DB_NAME=<your-database-name>
> UPTIME_KUMA_DB_USERNAME=<your-database-username>
> UPTIME_KUMA_DB_PASSWORD=<your-database-password>
> ```

OK,I will try
Thx

**Comment by CommanderStorm** [comment]
I think the issue for using the development builds (not alpha/beta) of uptime kuma is resolved with this.
We can reopen if this is not the case ^^
