### ISSUE TITLE
Extend Monitor JSON Data evaluation with additional operators

### ISSUE THREAD

**Issue by qu4cks4lb3r** [louislam/uptime-kuma#4614]
### 📑 I have found these related issues/pull requests

No similar issues / prs found

### 🏷️ Feature Request Type

Change to existing monitor

### 🔖 Feature description

**Current implementation**
The monitor type "HTTP(s) - Json Query" allows to add an expression in JSONata format and compare agains an expected value. It is currently only possible to compare the expression via equals.

**Requested change**
Adding functionality to also allow using other operators such as !=, <, <=, >, >=

**Why** 
It is possible to define a JSONata expression with including the operator into the expression and turn it into a boolean expression that can be compared. However, it would be more clear to add the value to the monitoring configuration itself rather than to the expression. Also that way, the value could be added to the log of the monitor.

### ✔️ Solution

For the monitoring type "HTTP(s) - Json Query" 
- Add a new property that holds the compare operator (==, !=, <, <=, >, >=). 
- For not introducing a breaking change, the default operator should be == if not available in an existing configuration.
- Extend the UI to allow the user to select the operator s/he wants to use for comparison - Default == 

### 📝 Additional Context

If fine, I'd like to provide a PR for that change. Following the rules for adding PRs, I wanted to clarify if this feature request sounds interesting to the Uptime Kuma team first.

**Comment by CommanderStorm** [comment]
Seems like a reasonable change to improve the ergonomics of said feature.
I think squeezing this in before #3919 is possible.

From a UX side: please include this as a drop-down to the value-field.
I think adding a description ( **>=** value must be greater or equal) in the drop-down is good because otherwise the comparison direction might be beneficial.
