### ISSUE TITLE
container name ignored if it contains a `-` character due to missing url-encoding

### ISSUE THREAD

**Issue by arnonuem** [louislam/uptime-kuma#4620]
### 📑 I have found these related issues/pull requests

not really found anything related at least from the headlines - sorry

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### Description

When monitoring docker containers the monitoring is fine if i use the container-id or the container name if it is a simple name.
It does not work if the container name contains a dash (-) character. Then when saving the configuration it says: Request failed with 404. However when i use the container-id of that container then it works again. I want to avoid using container-ids as they can change.

### 👟 Reproduction steps

- create a docker container and name it something with a dash in the name.
- try to monitor it by referencing it using the name with the dash instead of the container id

### 👀 Expected behavior

Dashes, underscores and even whitespace should be allowed. 

If a REST endpoint is called in the background URL encoding might come handy.

### 😓 Actual Behavior

It fails with 404

### 🐻 Uptime-Kuma Version

1.23.11

### 💻 Operating System and Arch

Debian Bullseye

### 🌐 Browser

Brave (Chrome)

### 🖥️ Deployment Environment

- Runtime: Docker 26.0.0
- number of monitors: 3

**Comment by CommanderStorm** [comment]
We are currently constructing the url like this (your guess that we are not url-encoding is correct):
https://github.com/louislam/uptime-kuma/blob/45690a25a0c4dffb9555670af8b5dcdc6bd2856b/server/model/monitor.js#L720

In the meantime, you can manually url-encode your names until this is fixed

**Comment by karandhanwani16** [comment]
Hello 👋🏻,

I tried to review the problem and it seems that this problem no longer exists as I was able to create an container with name which has '-' in the name and I was able to create the monitor successfully, Please find below the screenshot for the same.

![image](https://github.com/louislam/uptime-kuma/assets/54567222/3bc0b6ae-f502-47e5-8e2a-d6a205090e88)

you can clearly see in the picture above that the container name is test-container and it is being monitored successfully.

Please let me know if I am understanding this issue completely wrong or I am correct.

Thank you!

**Comment by CommanderStorm** [comment]
> it seems that this problem no longer exists

Sorry, this is likely my bad.
I should have tried to reproduce the issue before adding the tags I did 😅

=> closing as resolved and sorry for the "wasted" effort
