### ISSUE TITLE
Is Updamus based on Kuma? You can get ideas from its UI

### ISSUE THREAD

**Issue by perpi** [louislam/uptime-kuma#4623]
### 📑 I have found these related issues/pull requests

Not related to any other issue.

### 🏷️ Feature Request Type

Dashboard

### 🔖 Feature description

Making different themes available

### ✔️ Solution

Inspiration

### 📝 Additional Context

It's here: https://my.updamus.com/guest (Demo, Auto-login)

In its explanation, it is stated that: "Updamus is aware of your site's uptime and will inform you as soon as possible if the site is down or has any other problem!"

Among its capabilities, it is mentioned that: "execution of arbitrary Python script for various applications such as real user simulation, testing of specific functions (registration, shopping cart, etc.), security evaluation tests, etc.", Also: "Alerting the right incident to the right person"

It supports multi datacenters:
![image](https://github.com/louislam/uptime-kuma/assets/7093244/81d05285-c9be-46f3-be7b-114f5e7b8f96)

It's kinda similar to Uptime-Kuma! Is Kuma at its heart?
![image](https://github.com/louislam/uptime-kuma/assets/7093244/46e46ab9-0434-4bcd-9742-2e80a9f1495a)

It also supports multi users' access to the dashboard.

**Comment by CommanderStorm** [comment]
Please limit yourself to one feature per feature request and perform a duplicate search for said feature. 
Like this, it is not managable. For example user management and remote executors have different issues.
=> closing as a duplicate

**Comment by perpi** [comment]
🤷‍♂️ 🤷‍♀️

**Comment by CommanderStorm** [comment]
Idk what you are confused about.
You only stated that you wanted

> Making different themes available

And then linked some features (unrelated to anything themeing) from another uptime monitoring provider which are already tracked in other issues.
