### ISSUE TITLE
Errors passing server parameters using PM2

### ISSUE THREAD

**Issue by simone80an** [louislam/uptime-kuma#4627]
### ⚠️ Please verify that this question has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

I'm running kuma without docker using Node.js under Windows server.
Im trying to start it using PM2 and tried the following command:

```bash
pm2 start "server/server.js --host=portalecm.europe.adnet --port=3001 --ssl-key=C:\certificati\europe_adnet.key --ssl-cert=C:\certificati\europe_adnet.crt" --name uptime-kuma
```

but it gives error:
```raw
[PM2][ERROR] Script not found: C:\uptime-kuma\server\server.js --host=portalecm.europe.adnet --port=3001 --ssl-key=C:\certificati\europe_adnet.key --ssl-cert=C:\certificati\europe_adnet.crt
```

using PM2 without passing the server arguments works without problems:
```bash
pm2 start server/server.js --name uptime-kuma
```

Starting directly using node and passing server arguments works without problems:

```bash
node server/server.js --host=portalecm.europe.adnet --port=3001 --ssl-key=C:\certificati\europe_adnet.key --ssl-cert=C:\certificati\europe_adnet.crt
```

Any help appreciated, thanks!

### 🐻 Uptime-Kuma Version

1.19.4

### 💻 Operating System and Arch

Windows Server 2019 Standard

### 🌐 Browser

Google Chrome 123.0.6312.58

### 🖥️ Deployment Environment

- Runtime: node.js 16
- Database: SQLite
- Filesystem used to store the database on: Windows
- number of monitors: 126

**Comment by CommanderStorm** [comment]
Given that the output is `Script not found: C:\uptime-kuma\server\server.js`:
Where is Uptime Kuma located on your disk? Is this located at the root?

**Comment by CommanderStorm** [comment]
nvm, when you do what you are doing you are telling pm2 that the filename is litteraly `server/server.js --host=portalecm.europe.adnet --port=3001 --ssl-key=C:\certificati\europe_adnet.key --ssl-cert=C:\certificati\europe_adnet.crt`.

See https://stackoverflow.com/questions/28980307/how-to-pass-execution-arguments-to-app-using-pm2 how to add execution arguments

**Comment by simone80an** [comment]
Solved, thanks!
