### ISSUE TITLE
Minecraft Bedrock Edition gamedig monitor queries Java edition server instead of Bedrock

### ISSUE THREAD

**Issue by Jayspek** [louislam/uptime-kuma#4635]
### 📑 I have found these related issues/pull requests

None

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### Description

When you create a gamedig monitor and select Minecraft: Bedrock Edition, it queries the server using the Minecraft Java Edition protocol. This results in no response when querying a Bedrock server. If you have a Java and Bedrock server at the same address, the monitor will receive a response from the Java Edition server.

I was able to fix this issue by doing the following:
Opening the games.txt file at \{server directory}\nodemodules\gamedig

Then editing the line:
```diff
- minecraftpe,minecraftbe|Minecraft: Bedrock Edition (2011)|minecraft|port=19132
+ minecraftpe,minecraftbe|Minecraft: Bedrock Edition (2011)|minecraftbedrock|port=19132
```

This change causes the Bedrock Edition monitor to query Bedrock Edition servers as intended.
I'm not sure if this is the most optimal place to make this change, but it worked for me without causing any other problems (as far as I can tell).

### 👟 Reproduction steps

Create a Minecraft: Bedrock Edition monitor and direct it to an address that is hosting a Bedrock Edition server.

### 👀 Expected behavior

The monitor will query the server using the Bedrock Editon protocol and get a response form the bedrock server.

### 😓 Actual Behavior

The monitor queries the server with the Java edition protocol, either getting no response or receiving a response from a Java server if there is also one of those at the same address.

### 🐻 Uptime-Kuma Version

1.23.11

### 💻 Operating System and Arch

Windows 11 23H2

### 🌐 Browser

Same across all

### 🖥️ Deployment Environment

- Runtime: nodejs 20.11.0
- Database: IDK? Whatever is built in
- Filesystem used to store the database on: NTFS
- number of monitors: 23

**Comment by CommanderStorm** [comment]
That is an upstream issue. (we don't modifiy the dependencys we have like gamedig as suggested by you).
I have not identified a specific issue on this in [their issue tracker](https://github.com/gamedig/node-gamedig/issues?q=is%3Aissue+minecraft).

Could you (as more of an expert) look thorugh their issues if this is tracked in another one?

These points from their [`v5.0.0-beta0` changelog](https://github.com/gamedig/node-gamedig/blob/master/CHANGELOG.md) might be relevant
> - Removed `minecraftping` (as it was deprecated and the same thing as `minecraft`) and `minecraftpe` (deprecated, which is now the same as `mbe` (Minecraft Bedrock Edition)).
> - Removed the `games.txt` file, the games definitions are now stored in-code (exported on `games`).

The specific issue tracking the upgrade to v5 is https://github.com/louislam/uptime-kuma/issues/4414, but nobody has yet done the work to migrate to said version.
v2.0 of uptime kuma will bump our minimum supported node version to 18 => said part is not a blocker anymore.
This dependency not having a stable release means that we currently won't spend core-maintainer time on such a migration and instead focus on other stuff like https://github.com/louislam/uptime-kuma/issues/4500

**Comment by CommanderStorm** [comment]
I am going to close this issue as as a duplicate, because this is likely also covered by https://github.com/louislam/uptime-kuma/issues/4414 => better tracked there as `minecraftpe` was remvoed in said beta0 of gamdig v5

**Comment by Jayspek** [comment]
Ok, thanks you for the insight!
