### ISSUE TITLE
[ntfy] There is no password escape

### ISSUE THREAD

**Issue by andreapx** [louislam/uptime-kuma#4638]
### 📑 I have found these related issues/pull requests

I'm using the ntfy notification service and with the password _F$LU6i2yKMBGW6bS_ I get:
`Error: Error: AxiosError: Request failed with status code 403 {"code":40301,"http":403,"error":"forbidden","link":"https://ntfy.sh/docs/publish/#authentication"}`
while with this password _hf3-Ph3bquifbdVV2bdw_ it works without problems.

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 👟 Reproduction steps

Use ntfy (maybe other services too) with a password with special characters like / in it

### 👀 Expected behavior

The system should escape the password (I'm not sure if this is the correct term, sorry!)

### 😓 Actual Behavior

The password is not escaped and if there is a special character the remote server refuses it

### 🐻 Uptime-Kuma Version

~~2.10.0~~
1.23.11

### 💻 Operating System and Arch

Ubuntu 20.04

### 🌐 Browser

Firefox 123

### 🖥️ Deployment Environment

- Runtime: Docker 25.0.4
- Database: sqlite
- Filesystem used to store the database on: ext3 on HDD
- number of monitors: 30

**Comment by CommanderStorm** [comment]
The relevant part of the docs is
https://github.com/louislam/uptime-kuma/blob/08f75b0b99a96a919158ce818d6f59ed61ff0dd2/server/notification-providers/ntfy.js#L18

The problem is that the ntfy docs don't say tat the password has to be encoded in any way:
https://docs.ntfy.sh/publish/#username-password

I would classify this as an upstream bug

=> What encoding of passwords is nessesary?

**Comment by CommanderStorm** [comment]
Wait a minute: `2.10.0` is not a version we ever released

**Comment by binwiederhier** [comment]
ntfy maintainer here. 2.10.0 is the ntfy version. The encoding is UTF-8.

Here's an example for use `ben` with password `abc äöß::'` (note the colon, space, quote and umlauts). Use `echo -n "ben:abc äöß::'" | base64` to generate the password:

```
curl -s -H  "Authorization: Basic YmVuOmFiYyDDpMO2w586Oic=" ntfy.example.com/v1/account | jq .
{
  "username": "ben",
  "role": "user",
 ...
```

I now that JS in the browser typically encodes with UTF-16, so maybe that's an issue?!

**Comment by binwiederhier** [comment]
Also works with `$` (`echo -n 'ben:abc $' | base64`):

```
 curl -s -H  "Authorization: Basic YmVuOmFiYyAk" localhost:2586/v1/account | jq .            
{
  "username": "ben",
  "role": "user",
```

**Comment by andreapx** [comment]
> Wait a minute: `2.10.0` is not a version we ever released

Sorry, as Binwiederhier mentioned, that is the ntfy version. I've corrected it.

**Comment by andreapx** [comment]
> Currently, I don't think this is an issue with our software, as node encodeds correctly on my machine
> 
> @andreapx have you double checked that you have not encoded the password as shown above before entering it into ntfy?

@CommanderStorm I haven't encoded the password when I've created the user in ntfy,

**Comment by CommanderStorm** [comment]
Even not accidentally?
Have you double-checked that the password is what you think it is?

```bash
echo -n 'ben:abc $' | base64"
curl -s -H  "Authorization: Basic INSERT_B64_TOKEN_HERE" localhost:2586/v1/account | jq .
```

Btw: If you don't respond to the questions asked, I cannot help you.

> => What encoding of passwords is nessesary? (making reporting this upstream possible)

**Comment by CommanderStorm** [comment]
Always happy to help, and please don't hesitate to reach out if you come across further problems ^^

**Comment by andreapx** [comment]
@CommanderStorm you're very kind, thanks a lot!
