### ISSUE TITLE
Database Couruption over NFS

### ISSUE THREAD

**Issue by awptechnologies** [louislam/uptime-kuma#4639]
### ⚠️ Please verify that this question has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

I run over 64 containers and 30 stacks that use ether mariadb or postgress both of which are accessed through a nfs share. Out of all these databases Uptime is the only one that gets corrupt. The last time i set it up it did fine for 6 months then all of a sudden it could no longer load.

### 📝 Error Message(s) or Log

I deleted stack once database was courrupt out of frustration since i have over 100 devices it monitors. 

### 🐻 Uptime-Kuma Version

1.23.11

### 💻 Operating System and Arch

Docker on Debian amd64

### 🌐 Browser

Firefox

### 🖥️ Deployment Environment

- Runtime: 
- Database: 
- Filesystem used to store the database on: 
- number of monitors:

**Comment by awptechnologies** [comment]
I know nfs isnt a good idea for database but any help or tips to keep my config would be awesome. The only reason i depend on nfs is because i use docker swarm and with my HA environment it makes it so much easier for swarm to relocate container if a host goes down.

**Comment by CommanderStorm** [comment]
Please refer [to the wiki](https://github.com/louislam/uptime-kuma/wiki/%F0%9F%94%A7-How-to-Install).
This is a fundamental limitation of nfs not implementing proper locking which sqlite cannot handle. We cannot get around this limitation of the file system.
Depending on your nfs variant or deployment strategy, there might also be other factors at play.

> [!WARNING]
> Filesystem support for POSIX file locks is required to avoid SQLite database corruption. Be aware of possible [file locking problems](https://www.sqlite.org/howtocorrupt.html#_file_locking_problems) such as those [commonly encountered with NFS](https://www.sqlite.org/faq.html#q5). Please map the /app/data-folder to a local directory or volume.

**Comment by CommanderStorm** [comment]
Please see https://github.com/louislam/uptime-kuma/issues/2668 for a more detailed discussion

**Comment by DarkJoney** [comment]
We also caught the same issue on the Fargate + EFS. It's a production one, and the issue is, you cannot quickly jump in into the fargate container or EFS and manipulate the stuff, like at the OpenShift. 

Is there a way how to give it a RDS? I don't want to switch to the EC2 host for the ECS, because it's way too much for this thing. 
![image](https://github.com/user-attachments/assets/24deb13d-4488-4246-84a4-0419e89f3822)

**Comment by CommanderStorm** [comment]
Please see #4500
Mariadb/mysql support has writing a data-migration from the v1 to the v2 datamodel left.
If you want to chip in...
