### ISSUE TITLE
Request to add http url response delay alarm

### ISSUE THREAD

**Issue by rookie-man-fack** [louislam/uptime-kuma#4644]
### 📑 I have found these related issues/pull requests

Unable to accurately predict between high latency and timeout

### 🏷️ Feature Request Type

New monitor, Dashboard

### 🔖 Feature description

I hope to add alarms and notifications for large request response delays in monitoring.

### ✔️ Solution

I hope to add alarms and notifications for large request response delays in monitoring, so that they can work in conjunction with request timeouts.

**Comment by CommanderStorm** [comment]
Closing as a duplicate of https://github.com/louislam/uptime-kuma/issues/1813 which has https://github.com/louislam/uptime-kuma/pull/4005 as an associated PR

If you want to help: Said PR can be tested via https://github.com/louislam/uptime-kuma/wiki/Test-Pull-Requests
