### ISSUE TITLE
docker build failed   when use docker/dockerfile

### ISSUE THREAD

**Issue by WangYunT** [louislam/uptime-kuma#4646]
### ⚠️ Please verify that this question has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

1.  i downloaded the source code, the branch is **master**
2.  upload the source to my server, the service is centos 7, installed docker .. 
![image](https://github.com/louislam/uptime-kuma/assets/20185229/405f1ebc-11e6-4906-baab-88b739494362)
![image](https://github.com/louislam/uptime-kuma/assets/20185229/a5dea43a-374c-4d7d-8f4b-604ce542e549)

3. then, i run the script `docker  build -f docker/dockerfile -t uptime-kuma:test .`  then  failed,
![image](https://github.com/louislam/uptime-kuma/assets/20185229/8583a298-88e1-4417-908a-e81d43b1605b)

### 🐻 Uptime-Kuma Version

master

### 💻 Operating System and Arch

centos 7

### 🌐 Browser

Google

### 🖥️ Deployment Environment

- Runtime: docker 25.0.3
- Database: 
- Filesystem used to store the database on: 
- number of monitors:

**Comment by CommanderStorm** [comment]
> docker build failed when use docker/dockerfile

What are you trying to do?
`v2.0` is not yet ready for public testing.
Please see https://github.com/louislam/uptime-kuma/issues/4500 for the bugs which still remain.

If you want to test PRs, this can be done via this guide https://github.com/louislam/uptime-kuma/wiki/Test-Pull-Requests
If you want to develop the project, this can be done via the contribution guide: https://github.com/louislam/uptime-kuma/blob/master/CONTRIBUTING.md

For your issue, please see https://github.com/louislam/uptime-kuma/blob/822ce5384b1c138ccea7a20112363358cdb67083/package.json#L39-L50

=> you need to run this command prior. Also the command you provided has extra options and some options are missing.
```bash
npm run build
```
