### ISSUE TITLE
Exclude time range from monitoring

### ISSUE THREAD

**Issue by dnno** [louislam/uptime-kuma#4648]
### 📑 I have found these related issues/pull requests

None

### 🏷️ Feature Request Type

Change to existing notification-provider, Change to existing monitor

### 🔖 Feature description

I have configured several monitors. Some of them target services that are hosted on a dynamic hostname. Every night when my internet connection gets reset, it takes sometime for the services to be available again. This is expected and predictable. I'd like to be able to configure time ranges that would be excluded from monitoring (or maybe just from sending notifications). I can't find an option, neither on monitor- nor on notification configuration that would allow me to do so.

### ✔️ Solution

Either monitor or notification configuration should provide an option to exclude one or more time ranges.

### ❓ Alternatives

None

**Comment by CommanderStorm** [comment]
> be able to configure time ranges that would be excluded from monitoring (or maybe just from sending notifications). I can't find an option, neither on monitor- nor on notification configuration that would allow me to do so.

The feature you are looking for is a scheduled maintanance period.
![image](https://github.com/louislam/uptime-kuma/assets/26258709/af502043-afbc-4a56-b951-0340cce9bf45)

See our docs: https://github.com/louislam/uptime-kuma/wiki/Maintenance

If you have concrete proposals which documentation would have helped you finding this better, we would be very open to feedback. The docs are work in progress, as in most open source software.

**Comment by dnno** [comment]
That's exactly what I need. I was just looking at a different place, should have read the documentation more carefully. Thanks for the pointer and all your work!
