### ISSUE TITLE
How can I push prometheus metrics out of kuma?

### ISSUE THREAD

**Issue by embcla** [louislam/uptime-kuma#4650]
### ⚠️ Please verify that this question has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

Hello

I run kuma on an internal vm that's not reachable from the prometheus db so kuma can't be scraped.
Is there something I can use to actively push the metrics to the db?

### 🐻 Uptime-Kuma Version

1.23.11

### 💻 Operating System and Arch

gcloud vm ubuntu 22.04

### 🌐 Browser

Google Chrome Version 123.0.6312.86

### 🖥️ Deployment Environment

- Runtime: 26.0.0
- Database: embedded
- Filesystem used to store the database on: linux/ext4
- number of monitors: 2

**Comment by CommanderStorm** [comment]
> Is there something I can use to actively push the metrics to the db?

That is not how prometheus metrics work. Prometheus is build around scraping.
You can obviously build a system to get around this (see [promehteus/pushgateway](https://github.com/prometheus/pushgateway) and build a script that periodically pushes the metrics there), but allowing prometheus to access the endpoint is the simplest solution.
