### ISSUE TITLE
Add a physical location field to monitor attributes

### ISSUE THREAD

**Issue by sprior** [louislam/uptime-kuma#4656]
### 📑 I have found these related issues/pull requests

Nothing found

### 🏷️ Feature Request Type

Change to existing monitor

### 🔖 Feature description

It would be very useful to add a physical location string field to the attributes for a monitor.  Unlike the freindly name field this doesn't have to appear in the monitor list, but would be visible at the top when someone clicks on the details page for that monitor.

### ✔️ Solution

Add a physical location string to the attributes for a monitor and display it on the monitor details page.

### ❓ Alternatives

It's common to have such an attribute

**Comment by CommanderStorm** [comment]
@sprior 
Why not add a tag like `datacenter:eu-central-1`, `location:frankfurt`, `az:primary`, ... (something that matches your deployment strategy).
I think this is already handled by said subsystem.

**Comment by sprior** [comment]
@CommanderStorm a tag would be appropriate for which datacenter as you were thinking, but I'm thinking on a smaller level like which rack within the datacenter and tags aren't as great for that.

**Comment by CommanderStorm** [comment]
Why could this not be coverend by a tag like  `room:2410.EG.006` or `room:MW 0450B`?
