### ISSUE TITLE
How to change username

### ISSUE THREAD

**Issue by Mgrsc** [louislam/uptime-kuma#4658]
### ⚠️ Please verify that this question has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

How to change username

### 🐻 Uptime-Kuma Version

1.23.11

### 💻 Operating System and Arch

docker

### 🌐 Browser

edge

### 🖥️ Deployment Environment

- Runtime: 
- Database: 
- Filesystem used to store the database on: 
- number of monitors:

**Comment by CommanderStorm** [comment]
There is currently no simple way of doing this. Do you feel comfortable with executing SQL commands?

**Comment by Mgrsc** [comment]
> There is currently no simple way of doing this. Do you feel comfortable with executing SQL commands?目前还没有简单的方法来做这件事。您是否愿意执行 SQL 命令？

In that case, I will have to modify the username by executing an SQL command. Hopefully, this feature can be added in the future.

**Comment by Techwizz-somboo** [comment]
For anyone that needs instructions on updating the username, here are the instructions.

## SQLite

If you don't already, ensure you have sqlite3 installed on your system. On Debian, that is `sudo apt install sqlite3`.

Then run `sqlite3 PATH/TO/kuma.db`. If you're using the docker image, it's most likely `/var/lib/docker/volumes/uptime-kuma/_data/kuma.db`.

execute `UPDATE user SET username = 'YOUR-NEW-USER' WHERE id = 1;`

## MariaDB/MySQL

Connect to your db `mysql -u USER -p PASSWORD`.

Use your database table

`USE kuma;`

Then execute: `UPDATE user SET username = 'YOUR-NEW-USER' WHERE id = 1;`
