### ISSUE TITLE
Ethernet Adapter Transition: Hyper-V Troubles and Web Interface Migration

### ISSUE THREAD

**Issue by sashkomel6** [louislam/uptime-kuma#4660]
### ⚠️ Please verify that this question has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

I had only one Ethernet adapter with the IP address 192.168.2.66. A few weeks ago, I activated Hyper-V with the address 172.28.0.1, and today I disconnected my main adapter with the address 192.168.2.66. My web interface "uptime kuma" moved to the Hyper-V adapter with the address 172.28.0.1. I tried to uninstall Hyper-V and took other measures, but it didn't yield any results.

### 📝 Error Message(s) or Log

no

### 🐻 Uptime-Kuma Version

1.23.11

### 💻 Operating System and Arch

Windows 10 Home

### 🌐 Browser

chrome

### 🖥️ Deployment Environment

nodejs
SSD

**Comment by CommanderStorm** [comment]
You forgot to ask a question. What are you having trouble with?

The standard procedure is:
- shut down uptime kuma
- copy the data (take a backup and ensure that the hashes match)
- start the instance at the new place

**Comment by sashkomel6** [comment]
how to switch back to the main ethernet adapter? I already tried to turn off, start when the virtual adapter is removed, etc. I tried to replace the data that was before, but it did not help, and can you explain why this happened?

**Comment by CommanderStorm** [comment]
It seems like a quite unrelated issue to the project you are asking in.
I have never administered anything windows => would not be competent to ask for help.

Really out of my depth here:
Have you tried the steps in https://superuser.com/questions/1192492/how-to-remove-a-hyper-v-virtual-ethernet-switch or the steps ChatGPT suggests?

**Comment by sashkomel6** [comment]
I removed all Ethernet adapters, leaving only my physical one. I uninstalled all Git, Node.js, cleared all registry data, and launched a clean client. However, it still didn't work, and my Ethernet adapter with the IP address 192.168.2.66:3001 remains empty.
![Знімок екрана 2024-04-09 120428](https://github.com/louislam/uptime-kuma/assets/45562029/a83755cc-bb45-4c8e-81be-7198c1a9fb5a)

**Comment by sashkomel6** [comment]
Is it possible to manually input my IP address somehow? Because it's working, notifications are coming through, but there's no web access.

**Comment by louislam** [comment]
By default, Uptime Kuma will try to bind to all interfaces (includes IPv4 addresses and IPv6 addresses).

You should check with `ipconfig /all`. Also your Node.js version is a bit too new, I haven't tested it yet. I would recommend you to try Node.js 20 LTS.


> Is it possible to manually input my IP address somehow? Because it's working, notifications are coming through, but there's no web

You can bind to a specified address by `UPTIME_KUMA_HOST` https://github.com/louislam/uptime-kuma/wiki/Environment-Variables

**Comment by sashkomel6** [comment]
Once again everything got deleted, all programs and data. Installed Node.js version 20 LTS, and also noticed that somehow an enhanced firewall got enabled in the antivirus program. Turned it off, and everything started working.
