### ISSUE TITLE
Default motitor parameters

### ISSUE THREAD

**Issue by Marceau-h** [louislam/uptime-kuma#4662]
### 📑 I have found these related issues/pull requests

I haven't found a related issue or pr

### 🏷️ Feature Request Type

Change to existing monitor, Dashboard

### 🔖 Feature description

Hi,

I think it would be really cool to be able to have a base config that would apply, unless specified for some monitors and parameters.

That would allow us to only modify the config at one place for thing like check for ssl certs ot retries before notification.

### ✔️ Solution

I imagine that it could through some environnement variables or with a "default" monitor that would be at the top of the list ?

### 📝 Additional Context

Also, thanks a lot for this project, it is really easy to use and the notifications support is really extensive !

**Comment by CommanderStorm** [comment]
Related #1323

**Comment by Marceau-h** [comment]
My bad, haven't found this issue !
I was thinking specifically having only one default, but having templates that can bulk modify many monitors would be even better !
