### ISSUE TITLE
add the possibility to incorporate another status page offered by external service

### ISSUE THREAD

**Issue by tradexsrl** [louislam/uptime-kuma#4665]
### 📑 I have found these related issues/pull requests

Hi , will be very helpfull if it will be added the possibility to incorporate a status page from an external company because there is no way to add these monitor since we do not know all server that compose the service offered
an example , i want to incorporate this status page: https://status.opiquad.it/796036916 in my status page because we use their emailbackup solution

### 🏷️ Feature Request Type

Status-page

### 🔖 Feature description

incorporate another status page offered by another company

### ✔️ Solution

maybe add a fake monitor just to have the possibility to insert the url and to be able to show this page on the status page of uptime kuma

### ❓ Alternatives

an html widget ?

**Comment by CommanderStorm** [comment]
Why not monitor the api said status page uses with the json-query monitor?
The api behind this is https://status.opiquad.it/api/getMonitor/loMNDsOmAM?m=796036916

**Comment by tradexsrl** [comment]
thank's fore the reply , since i'm not a developer can you give me an example based on this api page for uptime kuma json query monitor?
i've also asked this because i'm thinking to not "reinvent the wheel" and just use immediately the page as it is by inserting as a frame in my status page
thabk's

**Comment by tradexsrl** [comment]
thank's i will try to add this code
i would like to achieve a status page like this:

![immagine](https://github.com/louislam/uptime-kuma/assets/62424179/6ff8810c-449a-4444-ab57-bca2225668f3)

**Comment by CommanderStorm** [comment]
> query: `monitor.statusClass`
> expect: `success`

I consider this issue resolved. We can reopen it if it is not ^^

**Comment by tradexsrl** [comment]
yes it worked but i think the maintainer can consider the feature request because finding api page is not very simple

**Comment by CommanderStorm** [comment]
> finding api page is not very simple

I just went into the network tab and used the one API request.. not really whichcraft

Agree that config templates are something that would be nice. This is tracked in another issue (can't tag issue due to github mobile)

**Comment by tradexsrl** [comment]
hi what about this page: 
https://docebo.status.io/?utm_campaign=2017%2001%20Docebo%207.0&utm_source=hs_email&utm_medium=email&utm_content=43637061&_hsenc=p2ANqtz-8-ecyJI8wcFxIqul9YMHSYOtO1opqDEMHrfEpsr8DnW9dtTEuBRp9vEQPVcAXQ_pn6AVu_T5XAWmanCRvrnq7ymQHLpibtmurfiX_pbVbP5P8X-ag&_hsmi=43637061

i tried to look into the html source but i cannot find any api reference...i think this is the case that i'm looking for this feature request
at the moment i'm using https keyword

**Comment by CommanderStorm** [comment]
Their api is documented at https://statusio.docs.apiary.io/#reference/status/status-summary/status/summary?console=1 but https://api.status.io/v2/status/summary/58934032243c30490e0009f9 does not seem to work for some reason.

Idk what is the probelm 🤷🏻

**Comment by tradexsrl** [comment]
Is not a problem but a feature request as in my original post.
if i can include their page in my status page i have all details that i need , instead now i'm just testing the presence of keyword that say "all system are operational"

**Comment by CommanderStorm** [comment]
Core problem is that this needs to stay maintainable.
We are not a large team and don't have the resources to spend investing in all the status pages out there.

I don't see offering hundreds of monitors for all the differnet status page providers as an option that we can offer. I see https://github.com/louislam/uptime-kuma/issues/1323 as an approach that does not have such high maintenance effort and has 90% of the utility.

See https://github.com/louislam/uptime-kuma/pull/4619#issuecomment-2054155593 for a more in-depth rationale.

**Comment by CommanderStorm** [comment]
Don't see how this could fit into our design language.
#1323 can be made to be coherent with the rest of "the product"

**Comment by tradexsrl** [comment]
i don't understand how config template would fit into my needs...

**Comment by CommanderStorm** [comment]
Why not?

You want to

> incorporate another status page offered by another company

=> adding a pre-configured config template how to monitor said service seems like a good choice.

**Comment by CommanderStorm** [comment]
So you want to monitor another status pages' monitors

If https://github.com/louislam/uptime-kuma/issues/1323 gets implemented:
- use a pre-configured monitor, fill out a few fields
- create the nessesary setup for monitoring said monitors
- status page incorporated

**Comment by tradexsrl** [comment]
ok understand
