### ISSUE TITLE
be able to run tests on a postman style request

### ISSUE THREAD

**Issue by armandofcom** [louislam/uptime-kuma#4670]
### 📑 I have found these related issues/pull requests

being able to do surveys on the results returned by an example get request that returns a json and parse that json and create some queries, how we do a test in postman, example

```
var data = JSON.parse(responseBody);
pm.test("Status code is 200", function () {
    pm.response.to.have.status(200);
});
console.log(new Date().getTime()-Date.parse(data.items[0].lastConnection));

pm.test("Last Connection Date", function () {
    pm.expect(new Date().getTime()-Date.parse(data.items[0].lastConnection)).to.be.below(480000);
});
```

### 🏷️ Feature Request Type

New monitor

### 🔖 Feature description

being able to do surveys on the results returned by an example get request that returns a json and parse that json and create some queries, how we do a test in postman, example
<img width="999" alt="Captura de pantalla 2024-04-12 a las 12 54 28 a m" src="https://github.com/louislam/uptime-kuma/assets/12705691/5b222d0f-799c-4edf-84e1-b4e3b6039e78">

### ✔️ Solution

You should also keep in mind that it is possible that a new authentication method must be passed, which may be that you send a POST-style request where you send a raw style json and that you parse that response so that it can be used to consult the api or the enpoint a monitor

var data = JSON.parse(responseBody);
//postman.setEnvironmentVariable("token", data.token);
pm.globals.set("token", data.token);
<img width="634" alt="Captura de pantalla 2024-04-12 a las 12 53 22 a m" src="https://github.com/louislam/uptime-kuma/assets/12705691/a0f23dc7-7fe3-465d-9fdd-8b7fbc6382f8">
<img width="606" alt="Captura de pantalla 2024-04-12 a las 12 53 28 a m" src="https://github.com/louislam/uptime-kuma/assets/12705691/675458b4-f71e-45c1-9ab2-7bb99df9d114">
<img width="992" alt="Captura de pantalla 2024-04-12 a las 12 54 18 a m" src="https://github.com/louislam/uptime-kuma/assets/12705691/cc9c0221-1775-4aef-930d-63b8b7a79933">

**Comment by CommanderStorm** [comment]
I think with "survey" you mean you want to execute queries against `json`. 
Have you looked at the `json-query` monitor, which does exactly what you are proposing (doing a request, checking the result).

Unsure what you mean by 
> You should also keep in mind that it is possible that a new authentication method must be passed, which may be that you send a POST-style request where you send a raw style json and that you parse that response so that it can be used to consult the api or the enpoint a monitor

**Comment by CommanderStorm** [comment]
Given that you can attach said header, I think this issue is resolved
