### ISSUE TITLE
Is it intended that monitors assigned to a group are output twice when filtering?

### ISSUE THREAD

**Issue by Slin-nilS** [louislam/uptime-kuma#4671]
### 📑 I have found these related issues/pull requests

none

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### Description

Is it intended that monitors assigned to a group are output twice when filtering?

### 👟 Reproduction steps

Add a down Monitor, add it to a group and filter on "down".

### 👀 Expected behavior

Only the Group Monitor with the child monitor.

### 😓 Actual Behavior

The Monitor "DOWN SAMPLE" are twice in the List.

![Screenshot 2024-04-12 124305](https://github.com/louislam/uptime-kuma/assets/95978369/223e2c02-ad50-4c50-977f-6c1799c00047)

### 🐻 Uptime-Kuma Version

1.23.11

### 💻 Operating System and Arch

Home Assistant Addon

### 🌐 Browser

Chromium 123.0.6312.122

### 🖥️ Deployment Environment

- Runtime: 
- Database: 
- Filesystem used to store the database on: 
- number of monitors:

**Comment by CommanderStorm** [comment]
> Is it intended that
No, this is a bug.

Already Tracked in https://github.com/louislam/uptime-kuma/issues/4607
=> closing as a duplicate

**Comment by Slin-nilS** [comment]
I didn't see the existing issue.
Thanks @CommanderStorm
