### ISSUE TITLE
Add Email Notification Schedule

### ISSUE THREAD

**Issue by tbagwell** [louislam/uptime-kuma#4673]
### 📑 I have found these related issues/pull requests

None

### 🏷️ Feature Request Type

Other

### 🔖 Feature description

Would love to see an Email Notification Schedule.  I don't see a way to put one in. So it only would email to this address between hours or on some Schedule

### ✔️ Solution

Would love to see an Email Notification Schedule.  I don't see a way to put one in. So it only would email to this address between hours or on some Schedule

**Comment by CommanderStorm** [comment]
So you mean you want to put a monitor into a sheduled maintanance mode to disabling sending mails to said notification provider?
![image](https://github.com/louislam/uptime-kuma/assets/26258709/2fe9879a-a3eb-499e-ad16-2e4c1d9263c5)

**Comment by tbagwell** [comment]
I would want that monitor to be still working. I guess that can work by setting that up.  The idea was a way that one email used from like hours 7 am to 7pm. And then a different email used from like 7pm to 7am

**Comment by CommanderStorm** [comment]
You likely want to use grafana oncall as a notifcation provider to shedule your oncall shifts then.

I am going to close this as this is covered by https://github.com/louislam/uptime-kuma/issues/3375
