### ISSUE TITLE
Setting English as language in settings does not persist

### ISSUE THREAD

**Issue by CirnoT** [louislam/uptime-kuma#4691]
### 📑 I have found these related issues/pull requests

#4244

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### Description

Setting language in settings to English does not persist between reloads of page because internally, Uptime Kuma does not recognize that language as valid.

### 👟 Reproduction steps

1. Ensure auto-detected language is something else than English
2. Go to Settings -> Appearance -> Language and select English
3. Refresh page

### 👀 Expected behavior

Language settings is persisted according to user preference

### 😓 Actual Behavior

Language is reverted to auto-detected one based on locale

### 🐻 Uptime-Kuma Version

1.23.12

### 💻 Operating System and Arch

Docker

### 🌐 Browser

Chromium124.0.6367.61

### 🖥️ Deployment Environment

- Runtime: Docker version 25.0.4, build 1a576c5
- Database: sqlite/embedded
- Filesystem used to store the database on: ext4 via docker volume

**Comment by aliaghil** [comment]
Same issue here after updating to 1.23.12.
