### ISSUE TITLE
Error in working with local proxy

### ISSUE THREAD

**Issue by Druidblack** [louislam/uptime-kuma#4693]
### ⚠️ Please verify that this question has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

After updating to version 1.23.12, an error was found (Cannot set properties of undefined (setting 'valid') when working with local proxies
Rolling back to version 1.23.11 solved this problem.

I'm launching it in the docker.

### 🐻 Uptime-Kuma Version

1.23.12

### 💻 Operating System and Arch

Debian (docker)

### 🌐 Browser

Chrome

### 🖥️ Deployment Environment

- Runtime: Docker 26.0.1 
- Database: 
- Filesystem used to store the database on: 
- number of monitors:

**Comment by loveyu** [comment]
Had the same problem.

**Comment by ThomasHineXYZ** [comment]
I am also experiencing this issue.

**Comment by IceCodeNew** [comment]
Same problem here.

**Comment by meyergru** [comment]
Add me to the list... very annoying, since I have to use the proxy in order to make IPv6 funtion at all under Docker.

**Comment by CommanderStorm** [comment]
What do you mean concretely when you say "when working with local proxy"?

**Comment by meyergru** [comment]
As for me, I monitor a https URL which resolves to an IPv6 address and thus I use a "local" (as in: my own RFC1918 network) squid proxy which is reachable via IPv4.

**Comment by CommanderStorm** [comment]
Not what I was asking: where does the error occur?

**Comment by meyergru** [comment]
On the dashboard log and in the container log as well:

`
2024-04-19T12:55:17+02:00 [MONITOR] WARN: Monitor #28 'Internet (IPv6)': Failing: Cannot set properties of undefined (setting 'valid') | Interval: 60 seconds | Type: http | Down Count: 0 | Resend Interval: 0
2024-04-19T12:55:19+02:00 [MONITOR] WARN: Monitor #32 'Internet': Failing: Child inaccessible | Interval: 60 seconds | Type: group | Down Count: 0 | Resend Interval: 0
2024-04-19T12:56:17+02:00 [MONITOR] WARN: Monitor #28 'Internet (IPv6)': Failing: Cannot set properties of undefined (setting 'valid') | Interval: 60 seconds | Type: http | Down Count: 0 | Resend Interval: 0
2024-04-19T12:56:19+02:00 [MONITOR] WARN: Monitor #32 'Internet': Failing: Child inaccessible | Interval: 60 seconds | Type: group | Down Count: 0 | Resend Interval: 0
`

**Comment by Druidblack** [comment]
Using gluetun, I make myself a local proxy server.

> Что конкретно вы имеете в виду, когда говорите "при работе с локальным прокси"?

**Comment by Druidblack** [comment]
> What do you mean concretely when you say "when working with local proxy"?

Using gluetun, I make myself a local proxy server.

**Comment by meyergru** [comment]
@CommanderStorm : You were right about line #536 in 'server/model/monitor.js'. When I comment that out, everything works again. I just added a comment to your review...

**Comment by chakflying** [comment]
I think I understand how the error can occur, but strangely I can't reproduce this using a squid proxy connecting over HTTP. What is the protocol used connecting to the proxy when the error occurs?

**Comment by Druidblack** [comment]
> I think I understand how the error can occur, but strangely I can't reproduce this using a squid proxy connecting over HTTP. What is the protocol used connecting to the proxy when the error occurs?

HTTP

**Comment by meyergru** [comment]
I use http to connect to the Squid proxy and the monitored URL is https. I think it is exactly this which causes the problem, as I wrote here: https://github.com/louislam/uptime-kuma/pull/4630#discussion_r1572640951

**Comment by chakflying** [comment]
Okay, I'll implement the fix later today.
