### ISSUE TITLE
Remind down notification

### ISSUE THREAD

**Issue by taimaiduc** [louislam/uptime-kuma#4695]
### 📑 I have found these related issues/pull requests

In case some server is down. And we don't want to take a look now and can double-check on the next 2 days.
I will be helpful when we are reminded by notification again every day/hours (config) of some services 

use case low disk notification

### 🏷️ Feature Request Type

New notification-provider, Other

### 🔖 Feature description

In case some server is down. And we don't want to take a look now and can double-check on the next 2 days.
I will be helpful when we are reminded by notification again every day/hours (config) of some services 

use case low disk notification

### ✔️ Solution

Crontab check last down services then resend

**Comment by CommanderStorm** [comment]
I think you missed the `Resend Notification if Down X times consecutively` option of the monitor
=> closing as resolved. Let me know if there was a misunderstanding on my side

**Comment by taimaiduc** [comment]
Thank you so much. Missing that config
