### ISSUE TITLE
Ping monitoring returns garbled data upon failure

### ISSUE THREAD

**Issue by ghost** [louislam/uptime-kuma#4703]
### 📑 I have found these related issues/pull requests

No related issues found

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### Description

![image](https://github.com/louislam/uptime-kuma/assets/97371434/4567e11d-945f-4e78-b28d-df198cc0663e)

### 👟 Reproduction steps

A ping monitoring has been configured, and when a fault alarm occurs in the ping monitoring, the returned information is garbled

### 👀 Expected behavior

Will result in the inability to analyze and determine the specific cause of the malfunction

### 😓 Actual Behavior

The actual returned code is garbled and cannot determine the specific fault phenomenon

### 🐻 Uptime-Kuma Version

1.23.12

### 💻 Operating System and Arch

WindowsServer2012 Installed the relevant environment as required

### 🌐 Browser

Version 124.0.6367.61 (official version) (64 bit)

### 🖥️ Deployment Environment

- Runtime: WindowsServer2012 Node.js v20.12.2 npm10.5.0
- Database: sqllite
- Filesystem used to store the database on: ntfs
- number of monitors: 41

### 📝 Relevant log output

```shell
���� Ping IPaddress ���� 56 �ֽڵ�����: ����ʱ�� IPaddress �� Ping ͳ����Ϣ: ���ݰ�: �ѷ��� = 1���ѽ��� = 0����ʧ = 1 (100% ��ʧ)��
```

**Comment by louislam** [comment]
See https://github.com/louislam/uptime-kuma/issues/570

This issue is not easy to be fixed in our side unfortunately. You have to change your Windows' language to English in order to display it correctly.

**Comment by CommanderStorm** [comment]
> WindowsServer2012 

Please consider upgrading. That is a really old OS

> Is it calling the ping tool of the Windows system or?

The arguments for [`child_process.spawn`](https://nodejs.org/api/child_process.html#child_processspawncommand-args-options) code executing the ping on windows is found here:

https://github.com/louislam/node-ping/blob/master/lib/builder/win.js

**Comment by CommanderStorm** [comment]
What do you mean by reference method?

**Comment by CommanderStorm** [comment]
I don't get what happened here. @niujinkai what do you mean?

So you set the default character set in the Windows built-in command prompt and this fixes the character encoding issue?

**Comment by CommanderStorm** [comment]
Did it do it for the whole system (including uptime-kuma) or just the command prompt in question?

**Comment by CommanderStorm** [comment]
Does uptime-kuma still return garabled ping responses changing said setting?
