### ISSUE TITLE
Rename "status-page" to "status"

### ISSUE THREAD

**Issue by binarydad** [louislam/uptime-kuma#471]
I just feel it's more concise. That is all. Thank you!

**Comment by gaby** [comment]
👍🏻 for this! it also looks cleaner url wise.

**Comment by MAXOUXAX** [comment]
Why not just serve the public status page on the `/` endpoint?
I'm not sure if it's a good thing to redirect the user to `/dashboard` when they try to go to the root URL

**Comment by chakflying** [comment]
> Why not just serve the public status page on the `/` endpoint?
> I'm not sure if it's a good thing to redirect the user to `/dashboard` when they try to go to the root URL

That's a good idea too! I think as the status page matures, we can make it the true public facing front page of the app.

**Comment by louislam** [comment]
> Why not just serve the public status page on the `/` endpoint?
> I'm not sure if it's a good thing to redirect the user to `/dashboard` when they try to go to the root URL

You can config the entry page in the Setting page, but it is just redirect to /status-page

![image](https://user-images.githubusercontent.com/1336778/134774562-776699c4-aca6-4eaa-af41-f8c4fcfb941e.png)

**Comment by rezzorix** [comment]
This is already implemented as of v1.7.1 and can be closed.
