### ISSUE TITLE
Disabling a group of sensors.

### ISSUE THREAD

**Issue by ZuluPilgrim** [louislam/uptime-kuma#4711]
### ⚠️ Please verify that this question has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

Is there a way to enable/disable sensors on bulk. I thought that if I disable a parent sensor that the child ones would too but alas this is not the case.

### 🐻 Uptime-Kuma Version

1.23.12

### 💻 Operating System and Arch

Ubuntu 22.04

### 🌐 Browser

Brave

### 🖥️ Deployment Environment

- Runtime: Docker

**Comment by CommanderStorm** [comment]
Yes that is currently a bug. Please refer to https://github.com/louislam/uptime-kuma/issues/4696 for further details
Closing as a duplicate
