### ISSUE TITLE
Regex for JSON query's expected value (and in general for anything value search-like)

### ISSUE THREAD

**Issue by iGerman00** [louislam/uptime-kuma#4715]
### 📑 I have found these related issues/pull requests

- https://github.com/louislam/uptime-kuma/issues/4614
- https://github.com/louislam/uptime-kuma/issues/2735
- https://github.com/louislam/uptime-kuma/issues/1851

### 🏷️ Feature Request Type

Change to existing monitor

### 🔖 Feature description

Sometimes, for example when the response is a string and can vary, you would want to regex it, maybe something returns a big error, but it starts with the word error.

### ✔️ Solution

A regex option alongside the current expected value would be swell.

### ❓ Alternatives

Can't think of any

**Comment by CommanderStorm** [comment]
FYI:
jsonata already includes the regex expression https://docs.jsonata.org/regex
But yea, likely not as discoverable for devs.

The PR that would add further operators would be https://github.com/louislam/uptime-kuma/pull/4617

**Comment by raxod502** [comment]
@CommanderStorm I don't think #4717 actually addresses this feature request? It adds numeric comparison but the request here was for regex comparison, which is also the use case I am in search of.

This seems like something that would be pretty straightforward to add, would a pull request be welcome adding an option to the dropdown menu for regex?

**Comment by CommanderStorm** [comment]
here are the jsonata docs on how to use this feature

https://docs.jsonata.org/regex

**Comment by CommanderStorm** [comment]
I don't want to add more complexity to the legacy architecture at the moment.

If you want to help lift the http monitor towards the new condition logic, that would be an awsome contribution.

**Comment by raxod502** [comment]
Yeah, I know jsonata has a regex operator, however the issue is if I use that to check for a match, then when the match fails, I will not get the non-matching string in the Uptime Kuma error message, which makes it much harder to diagnose errors, especially if the non-conforming data is only transient.

Although now that I think on it again, I guess technically I could assign the output of my filter to a jsonata temporary variable, compare that against the regex, and then if it fails return the original filter output, else return `success`. Is that what you would suggest?

**Comment by CommanderStorm** [comment]
> Is that what you would suggest?

I don't things that make migrating to the new arch harder, so yes.
If you want to contribute the engineering towards that, I would be happy to guide you.

> especially if the non-conforming data is only transient

You can save the responses you get in these scenarios.
There has not been put engineering effort into making this system nice and integrate this into the fronted, but the backend collects them and you can add them to notifications.
