### ISSUE TITLE
Basic server monitoring

### ISSUE THREAD

**Issue by MichaelBelgium** [louislam/uptime-kuma#4716]
### 📑 I have found these related issues/pull requests

None

### 🏷️ Feature Request Type

New monitor, Other

### 🔖 Feature description

Would it be an idea .. to include some sort of server monitor in uptime-kuma? 

This could perhaps be called a "heartbeat monitor", where the server u monitor has to send data to uptime kuma in stead of other way around. If the server can send data about itself, you're sure it's up and on plus you get to track system parameters.

The monitor itself would show and track the history of
* % usage RAM
* % usage CPU
* % usage disk
* usage network
* and so on

This would make it able to add an alert, for example, if cpu usage is more than 90% for 5 minutes straight and so on.

In terms of showing this on the status page, it'd be nice to display it with a graph showing the current usage of all. eg like [hetrixtools](https://hetrixtools.com/feature/server-monitor/) or [Netweak](https://netweak.com/)

### ✔️ Solution

There are several ways to monitor a server but the easiest way is via an agent. You install an agent script on the server you wanna monitor and it'll send data to - in this case - uptime kuma.

It's possible to get some inspiration from the open source agents of [hetrixtools ](https://github.com/hetrixtools/agent) or [netweak](https://github.com/netweak/agent)

**Comment by CommanderStorm** [comment]
You can give https://github.com/louislam/uptime-kuma/issues/819 a thumps up ^^

=> closing as a duplicate
