### ISSUE TITLE
Bind Uptime Kuma to a physical interface

### ISSUE THREAD

**Issue by kristophercrawford** [louislam/uptime-kuma#4719]
### ⚠️ Please verify that this question has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

I am running Uptime Kuma in an LXC in Proxmox with two interfaces that are connected to two vlan's. Each vlan is part of a different VRF on my router and each VRF connects to a dedicated ISP. Is there a way to bind a monitor to a specific interface or bind Uptime Kuma to a specific interface? I am looking to monitor the same target through each ISP connection to be able to track latency and access.  

### 🐻 Uptime-Kuma Version

1.23.13

### 💻 Operating System and Arch

Ubuntu 22.04 x64

### 🌐 Browser

n/a

### 🖥️ Deployment Environment

- Runtime: 
- Database: 
- Filesystem used to store the database on: 
- number of monitors:

**Comment by CommanderStorm** [comment]
You can configure which IP-Adress Uptime Kuma connects to (thus also which interface) via the `HOST` Environment variable.
See https://github.com/louislam/uptime-kuma/wiki/Environment-Variables
