### ISSUE TITLE
Cannot update from 1.6.0 to 1.7.0

### ISSUE THREAD

**Issue by Panja0** [louislam/uptime-kuma#472]
**Is it a duplicate question?**
No

**Problem**
Cannot update to 1.7.0

**Info**
Uptime Kuma Version: 1.6.0 --> 1.7.0
Using Docker?: No

Node.js Version (Without Docker only): v14.17.6
OS: Ubuntu Server 20.04.3

**Error message**
`78 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities

> uptime-kuma@1.7.0 build /opt/uptime-kuma
> vite build

vite v2.5.10 building for production...
✓ 768 modules transformed.

<--- Last few GCs --->

[4633:0x626bb80]   252087 ms: Mark-sweep 477.8 (491.7) -> 473.8 (491.7) MB, 5090.1 / 0.0 ms  (average mu = 0.226, current mu = 0.105) allocation failure scavenge might not succeed
[4633:0x626bb80]   256194 ms: Mark-sweep 477.8 (491.7) -> 473.8 (491.7) MB, 3896.3 / 0.0 ms  (average mu = 0.156, current mu = 0.051) allocation failure scavenge might not succeed

<--- JS stacktrace --->

FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
 1: 0xa25510 node::Abort() [node]
 2: 0x9664d3 node::FatalError(char const*, char const*) [node]
 3: 0xb9a8be v8::Utils::ReportOOMFailure(v8::internal::Isolate*, char const*, bool) [node]
 4: 0xb9ac37 v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool) [node]
 5: 0xd56ca5  [node]
 6: 0xd5782f  [node]
 7: 0xd6566b v8::internal::Heap::CollectGarbage(v8::internal::AllocationSpace, v8::internal::GarbageCollectionReason, v8::GCCallbackFlags) [node]
 8: 0xd6922c v8::internal::Heap::AllocateRawWithRetryOrFailSlowPath(int, v8::internal::AllocationType, v8::internal::AllocationOrigin, v8::internal::AllocationAlignment) [node]
 9: 0xd3790b v8::internal::Factory::NewFillerObject(int, bool, v8::internal::AllocationType, v8::internal::AllocationOrigin) [node]
10: 0x107fbef v8::internal::Runtime_AllocateInYoungGeneration(int, unsigned long*, v8::internal::Isolate*) [node]
11: 0x1426919  [node]
Aborted (core dumped)
npm ERR! code ELIFECYCLE
npm ERR! errno 134
npm ERR! uptime-kuma@1.7.0 build: `vite build`
npm ERR! Exit status 134
npm ERR! 
npm ERR! Failed at the uptime-kuma@1.7.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
`

**Comment by louislam** [comment]
Cannot reproduce in my machine. You can try to increase the max size.
```bash
export NODE_OPTIONS="--max-old-space-size=4096"
npm run build
```

Ref: https://stackoverflow.com/questions/53230823/fatal-error-ineffective-mark-compacts-near-heap-limit-allocation-failed-javas

**Comment by Panja0** [comment]
@louislam 
Thanks! Trying to do the npm run build now but it's not doing anything after:

`
`> uptime-kuma@1.7.0 build /opt/uptime-kuma
> vite build

vite v2.5.10 building for production...
✓ 768 modules transformed.
`

**Comment by Panja0** [comment]
After a reboot I tried again and got this:

<--- Last few GCs --->

[1300:0x6412b80]   262308 ms: Mark-sweep 478.0 (491.9) -> 474.0 (492.2) MB, 3314.1 / 0.0 ms  (average mu = 0.169, current mu = 0.057) allocation failure scavenge might not succeed
[1300:0x6412b80]   265805 ms: Mark-sweep 478.1 (492.2) -> 474.1 (491.7) MB, 3198.7 / 0.0 ms  (average mu = 0.130, current mu = 0.085) allocation failure scavenge might not succeed


<--- JS stacktrace --->

FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
 1: 0xa25510 node::Abort() [node]
 2: 0x9664d3 node::FatalError(char const*, char const*) [node]
 3: 0xb9a8be v8::Utils::ReportOOMFailure(v8::internal::Isolate*, char const*, bool) [node]
 4: 0xb9ac37 v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool) [node]
 5: 0xd56ca5  [node]
 6: 0xd5782f  [node]
 7: 0xd6566b v8::internal::Heap::CollectGarbage(v8::internal::AllocationSpace, v8::internal::GarbageCollectionReason, v8::GCCallbackFlags) [node]
 8: 0xd6922c v8::internal::Heap::AllocateRawWithRetryOrFailSlowPath(int, v8::internal::AllocationType, v8::internal::AllocationOrigin, v8::internal::AllocationAlignment) [node]
 9: 0xd3790b v8::internal::Factory::NewFillerObject(int, bool, v8::internal::AllocationType, v8::internal::AllocationOrigin) [node]
10: 0x107fbef v8::internal::Runtime_AllocateInYoungGeneration(int, unsigned long*, v8::internal::Isolate*) [node]
11: 0x1426919  [node]
Aborted (core dumped)
npm ERR! code ELIFECYCLE
npm ERR! errno 134
npm ERR! uptime-kuma@1.7.0 build: `vite build`
npm ERR! Exit status 134
npm ERR! 
npm ERR! Failed at the uptime-kuma@1.7.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**Comment by louislam** [comment]
I tested on my Ubuntu, windows and Raspberry PI, cannot reproduce the problem.

Not quite sure what happen. You may need to try:

1. Clean install 1.7.0 in another directory 
2. If step 1 is failed, clean install 1.6.0 in another directory

```bash
git checkout 1.6.0
npm install --legacy-peer-deps 
node node_modules/esbuild/install.js 
npm run build
```

**Comment by Panja0** [comment]
I got the problem fixed.
Update Kuma is running on an Oracle Cloud vm (free tier) with 1GB ram.
I think the 1GB ram is the problem.

To fix the problem I created a swap partition:
`sudo dd if=/dev/zero of=/swapfile bs=128M count=32` (128M * 32 = 4096M)
`sudo chmod 600 /swapfile`
`sudo mkswap /swapfile`
`sudo swapon /swapfile`
`sudo swapon -s`

After that I edited the file `/etc/fstab` and added the following line to the end of the file:
`/swapfile swap swap defaults 0 0`
Save the file and rebooted the server.

Once the server was rebooted I ran the command:
`export NODE_OPTIONS=--max_old_space_size=4096`

**Comment by urbels** [comment]
I had the same problem with Oracle cloud, thank you!

**Comment by urbels** [comment]
Nvm even with swap it runs out of memory. Why it uses so much memory suddently running the build?

**Comment by chakflying** [comment]
Wow no kidding, on my Windows laptop `npm run build` has a peak memory usage of ~1.6GB. Maybe we should suggest users with low system spec to run docker instead.

**Comment by louislam** [comment]
It seems that it is a vite.js issue. https://github.com/mutoe/vue3-realworld-example-app/issues/41

Would try to prepare prebuilt files in the future release.

**Comment by Panja0** [comment]
Got the same problem when updating from 1.7.0 to 1.7.1
I needed to run the command again before updating:
`export NODE_OPTIONS=--max_old_space_size=4096`
