### ISSUE TITLE
Feature Request: Adding Option to Display URL in Custom Status Pages

### ISSUE THREAD

**Issue by handy-git** [louislam/uptime-kuma#4720]
### 📑 I have found these related issues/pull requests

not

### 🏷️ Feature Request Type

Status-page

### 🔖 Feature description

Currently, the custom status pages lack the functionality to display URLs. It would be beneficial to include an option to show URLs on these pages. This addition would provide users with the ability to include relevant links or references within their status updates, enhancing the overall usefulness and informativeness of the status pages.

### ✔️ Solution

Introduce a feature within the customization settings of status pages that allows users to enable the display of URLs. This feature could be implemented as a toggle switch or checkbox within the customization menu, providing users with flexibility in choosing whether to include URLs on their status pages.

**Comment by CommanderStorm** [comment]
Actually this option already exists in the monitors settings:
![image](https://github.com/louislam/uptime-kuma/assets/26258709/b498784d-4c1f-4d53-b3ad-03d87733a444)

Customising this link externally is tracked in https://github.com/louislam/uptime-kuma/issues/2507 instead

=> closing as resolved

**Comment by handy-git** [comment]
> Actually this option already exists in the monitors settings: ![image](https://private-user-images.githubusercontent.com/26258709/326225227-b498784d-4c1f-4d53-b3ad-03d87733a444.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQyNzMzNjcsIm5iZiI6MTcxNDI3MzA2NywicGF0aCI6Ii8yNjI1ODcwOS8zMjYyMjUyMjctYjQ5ODc4NGQtNGMxZi00ZDUzLWIzYWQtMDNkODc3MzNhNDQ0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI4VDAyNTc0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRiMGIxOGE4ZDE4MTEyMzYzYmQ3YmE1ZjFiMTllZjRmZmJkNmRkNTY0ZGExMGQ3ZGY1NjAxYmFiYjMyNjM0MDkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.0w9XWBRNi2B3GStgExQNTfNAtRrRf_yj-tvDy5lHT7g)
> 
> Customising this link externally is tracked in #2507 instead
> 
> => closing as resolved

Is there a batch operation available? It's quite complex to individually enable this feature for a large number of monitored websites.

**Comment by CommanderStorm** [comment]
No, currently no batch operators exist for this.
See https://pypi.org/project/uptime-kuma-api/ on how to get there without this being a configurable default.

**Comment by handy-git** [comment]
> No, currently no batch operators exist for this. See https://pypi.org/project/uptime-kuma-api/ on how to get there without this being a configurable default.

Thanks
