### ISSUE TITLE
Need help for integrating external database

### ISSUE THREAD

**Issue by jbrighthub** [louislam/uptime-kuma#4724]
### ⚠️ Please verify that this question has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

Hello Team,
I'm using uptime-kuma, I have one question, can we use external maria db and sqlite database for uptime-kuma.
if it's possible then give me guidance.

Thank you.

### 🐻 Uptime-Kuma Version

1.23.13

### 💻 Operating System and Arch

Ubuntu 18.0

### 🌐 Browser

124.0.6367.60 

### 🖥️ Deployment Environment

- Runtime: 
- Database: 
- Filesystem used to store the database on: 
- number of monitors:

**Comment by CommanderStorm** [comment]
I am unsure what you mean with the and in

> external maria db and sqlite database 

I am assuming you mean instead.

External MariaDB is a v2.0 feature. See #4500 for further details on the status of said release 
=> what needs to get done before we can release an initial beta and how to get involved in said process
