### ISSUE TITLE
Uptime kuma bulk monitoring hosts name import

### ISSUE THREAD

**Issue by najmulh** [louislam/uptime-kuma#4725]
### 📑 I have found these related issues/pull requests

Request to you for new feature bulk monitoring host name import. It is easy to manage multiple hosts imported in short time. 

### 🏷️ Feature Request Type

Dashboard

### 🔖 Feature description

Request to you for new feature bulk monitoring host name import. It is easy to manage multiple hosts imported in short time. 

### ✔️ Solution

Feature add request. 

### ❓ Alternatives

Request to you for new feature bulk monitoring host name import. It is easy to manage multiple hosts imported in short time. 

### 📝 Additional Context

Request to you for new feature bulk monitoring host name import. It is easy to manage multiple hosts imported in short time.

**Comment by CommanderStorm** [comment]
> [!NOTE]
> Thanks for reporting feedback, but please run a duplicate search first in the future and fill out the form fully.
> Filling out the form fully is a shared responsibility (this is not a company, we are all volunteers => please be respectfull of our time as well)

We track import features in (depending what you mean):
- https://github.com/louislam/uptime-kuma/issues/1323
- https://github.com/louislam/uptime-kuma/issues/1190
- https://github.com/louislam/uptime-kuma/issues/564

Depending on the actual usecase (you would need to be more specific than repeating two sentences 4x), you might also be looking for:
- https://github.com/BigBoot/AutoKuma
- https://uptime-kuma-api.readthedocs.io/
- https://github.com/louislam/uptime-kuma/issues/882
- https://github.com/louislam/uptime-kuma/issues/4233 
- https://github.com/louislam/uptime-kuma/issues/957
- https://github.com/louislam/uptime-kuma/issues/4308

=> closing s a duplicate
