### ISSUE TITLE
Uptime Kuma not Detecting Javascript for Custom Browser

### ISSUE THREAD

**Issue by Xliff** [louislam/uptime-kuma#4726]
### 📑 I have found these related issues/pull requests

None

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### Description

I have written a custom browser, and Uptime Kuma is not detecting its Javascript abilities. How is Uptime Kuma detecting Javascript compatibility, and what might I need to do to have it work for my code?

Thanks in advance.

### 👟 Reproduction steps

n/a

### 👀 Expected behavior

Javascript should work when I load the page.

### 😓 Actual Behavior

Javascript does not work when I load the page.

### 🐻 Uptime-Kuma Version

latest

### 💻 Operating System and Arch

Ubuntu Mantic 23.10

### 🌐 Browser

Custom Browser written in Raku

### 🖥️ Deployment Environment

- Runtime: 
Standard

- Database: 
File

- Filesystem used to store the database on: 
Ext4

- number of monitors: 
N/A

**Comment by CommanderStorm** [comment]
First of all, it is not a bug if we don't work in some likely non-spec compliant browser like `Custom Browser written in Raku`.
That is something that you can do, but not our problem => not a bug.

> I have written a custom browser

What do you mean here?
Do you mean that you have actually written a custom browser and now have compatibility problems? (have you tested yourself against the browsers test suites?)
What do you mean by detection in this case?

If you mean the noscript screen that users get if they are not executing JS:
- Have you checked that you are loading, compiling and executing JS?
- Have you debugged if you are handling modules and scripts correctly?
- Are you handling fetching of subresources correctly?
- Are you rendering the DOM Correctly => maybe your flexbox/grid/absolute/relative/... positioning rules is wrong (or like a thousand other things, CSS is a gift that keeps on giving)
- Using Happy Eyeballs? => maybe an DNS issue?

Thing is, that in a custom (= not one of the big 3) browsers, there are like a million things that can be wrong.

**Comment by Xliff** [comment]
Turns out I had the wrong frame visible and proper one was on the login page. Now closing this...

**Comment by Xliff** [comment]
Turns out I had the wrong frame visible and proper one was on the login page. Now closing this...
