### ISSUE TITLE
Version on all footers on all pages and API endpoint to fetch the version

### ISSUE THREAD

**Issue by solick** [louislam/uptime-kuma#4730]
### 📑 I have found these related issues/pull requests

The the version of the current instance cannot be fetched from the instance. Neither from the Dashboard or status pages eg in the footer, nor from an api endpoint.

### 🏷️ Feature Request Type

API / automation options

### 🔖 Feature description

Show the version of the instance in all footers of uptime numa.
provide an api endpoint to fetch the version for update check from third party tools

### ✔️ Solution

Show the version of the instance in all footers of uptime numa.
provide an api endpoint to fetch the version for update check from third party tools

**Comment by CommanderStorm** [comment]
What is your actual usecase for this?
We currently don't have a footer, what are expecting?

Users have previously requested this to NOT be the case. In `1.23.0`, we have removed this.
See https://github.com/louislam/uptime-kuma/issues/3374#issuecomment-1672861789:
> ⬆️ Security Fixes
> https://github.com/louislam/uptime-kuma/pull/3421 Hardening: Avoid exposing the Uptime Kuma version to the public

> [!NOTE]
> We do show a warning if you are running an outdated version (unless you disabled this).
> The version is shown in `/settings/about`.
> ![image](https://github.com/louislam/uptime-kuma/assets/26258709/b23a61c4-9b86-44d4-bb38-1556d93c0cb2)


> [!NOTE]
> we currently use the `"info"` socketio event. This event is send AFTER login. See #3421

**Comment by solick** [comment]
There are two use cases.

1. I would like to see the version in the first page (after login) in my dashboard. Not clicking 2 times to see it. 
2. I want to fetch the version from the API (also with API key, not public) to make automatic checks of the version and if updates are available for notification. I personally don´t got often to the dashboard I use the notification to mattermost. Therefore I do not see the update available notification on the dashboard. nor do I see if it's a major or minor update (based on the version number). I have a script which fetches those information from all my services I am hosting and check on regular bases the version and if there is a new update available. I want to do this also for Uptime Kuma.

**Comment by CommanderStorm** [comment]
> would like to see the version in the first page (after login) in my dashboard

In that case the banner seems suficcient to me => activate it (the default is on)

Our first draft at a non-socket.io API is tracked in #118 and this work has been done https://github.com/louislam/uptime-kuma/pull/3854

I think for your usecase, using the socker.io api should be fine if you just want to have a script => no need to wait for v2.1

**Comment by CommanderStorm** [comment]
FYI:
You can enter yourself to get notified for releases in github.

See 
![image](https://github.com/louislam/uptime-kuma/assets/26258709/ffbe6577-a0c2-496c-9755-8f97ac908e9a)


I think this resolves all your usecases => closing as resolved
