### ISSUE TITLE
Docker error when setting up second host

### ISSUE THREAD

**Issue by m3tc0n** [louislam/uptime-kuma#4734]
### ⚠️ Please verify that this question has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

Hi all, I'm trying to setup a second uptime kuma instance in docker on a second host by exposing the TCP port. I'm using the guidelines mentioned on https://github.com/louislam/uptime-kuma/wiki/How-to-Monitor-Docker-Containers (Method 2).

When I'm restarting the docker service, I'm getting an error message saying: 

Job for docker.service failed because the control process exited with error code. See "systemctl status docker.service" and "journalctl -xeu docker.service" for details.

When I look in "systemctl status docker.service", I see the following error: 

ExecStart=/usr/bin/dockerd --containerd=/run/containerd/containerd.sock (code=exited, status=1/FAILURE)

("journalctl -xeu docker.service" has no entries).

How to solve this problem?

### 📝 Error Message(s) or Log

See the description of my problem.

### 🐻 Uptime-Kuma Version

1.23.13

### 💻 Operating System and Arch

Debian 12 with Docker

### 🌐 Browser

Firefox

### 🖥️ Deployment Environment

- Runtime: Docker
- Database: 
- Filesystem used to store the database on: 
- number of monitors:

**Comment by CommanderStorm** [comment]
I really have no idea what might cause your dockerd to error out without additional error logs.
Have you tried increasing the log level?

**Comment by m3tc0n** [comment]
Yes I have tried to increase the log level to debug but I don't get additional logs.

**Comment by CommanderStorm** [comment]
just a hunch: your command above states containerd.. is that the new dockerd or do you need to adjust how to search for logs?

**Comment by m3tc0n** [comment]
Sorry but I don't understand what you mean.

**Comment by CommanderStorm** [comment]
Nevermind that one.

So logicallly I think the `daemon.json` is invalid somewhere and dockerd is not reporting an error about an error.
Could you share the file?

**Comment by SadGrimReaper** [comment]
I just ran into this problem myself and I was able to solve it, maybe it could help you too.

1. Create daemon.json file in /etc/docker:
` {"hosts": ["tcp://0.0.0.0:2375", "unix:///var/run/docker.sock"]}`

2. Add /etc/systemd/system/docker.service.d/override.conf
```
 [Service]
 ExecStart=
 ExecStart=/usr/bin/dockerd
```

3. Reload the systemd daemon:
` systemctl daemon-reload`

4. Restart docker:
` systemctl restart docker.service`

I tried it on an clean install.

**Comment by m3tc0n** [comment]
> I just ran into this problem myself and I was able to solve it, maybe it could help you too.
> 
>     1. Create daemon.json file in /etc/docker:
>        ` {"hosts": ["tcp://0.0.0.0:2375", "unix:///var/run/docker.sock"]}`
> 
>     2. Add /etc/systemd/system/docker.service.d/override.conf
> 
> 
> ```
>  [Service]
>  ExecStart=
>  ExecStart=/usr/bin/dockerd
> ```
> 
>     3. Reload the systemd daemon:
>        ` systemctl daemon-reload`
> 
>     4. Restart docker:
>        ` systemctl restart docker.service`
> 
> 
> I tried it on an clean install. Its a bit diffrent from the guide.

Thank you very much. That did the trick and solved my problem!
