### ISSUE TITLE
Unable to monitor Authentik healthcheck - Failing: unexpected end of file

### ISSUE THREAD

**Issue by csmith1210** [louislam/uptime-kuma#4736]
### ⚠️ Please verify that this question has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

Hi there, with a recent update, my check for my authentik instance has been failing with an unexpected end of file. However, going into the docker `curl -I https://my.domain/-/health/ready/` returns the correct HTTP 204 code.

Not sure if this is a bug or if I need to change the way the monitor is set up.

### 📝 Error Message(s) or Log

`[MONITOR] WARN: Monitor #16 'Authentik Backend': Failing: unexpected end of file | Interval: 60 seconds | Type: http | Down Count: 0 | Resend Interval: 0`
```
root@aada52cf0ce2:/app# curl -I https://my.domain/-/health/live/
HTTP/2 204
date: Fri, 03 May 2024 20:15:45 GMT
content-encoding: gzip
referrer-policy: same-origin
strict-transport-security: max-age=15552000; includeSubDomains; preload
vary: Accept-Encoding
x-content-type-options: nosniff
x-forwarded-proto: https
x-robots-tag: none,noarchive,nosnippet,notranslate,noimageindex
x-xss-protection: 1; mode=block
cf-cache-status: DYNAMIC
report-to: {"endpoints":[{"url":"cloudflare_url"}],"group":"cf-nel","max_age":604800}
nel: {"success_fraction":0,"report_to":"cf-nel","max_age":604800}
server: cloudflare
cf-ray: ***
alt-svc: h3=":443"; ma=86400
```

### 🐻 Uptime-Kuma Version

1.23.13

### 💻 Operating System and Arch

Windows 11 / macOS

### 🌐 Browser

Firefox

### 🖥️ Deployment Environment

- Runtime: Docker version 26.1.1, build 4cf5afa
- Database: sqlite
- Filesystem used to store the database on: btrfs on SSD
- number of monitors: 21

**Comment by CommanderStorm** [comment]
`HTTP/2 204` = [`204 No Content`](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/204).

What monitor are you using?

What service are you using or can you build a testcase to reproduce this? 
Might be a but on our end, hard to tell

**Comment by csmith1210** [comment]
I’m using an HTTP(s) monitor with method seat to HEAD and accepted status codes set to 200-299.

I can try to spin up a new instance of Authentik to see if it’s something with my current set up.

Is there anyway to have uptime-kuma spit out more info about the request in the logs? I have DEBUG=true set but it doesn’t seem to add much more info if any to the logs.

**Comment by codesterd** [comment]
> I’m using an HTTP(s) monitor with method set to HEAD and accepted status codes set to 200-299.
> 
> I can try to spin up a new instance of Authentik to see if it’s something with my current set up.
> 
> Is there anyway to have uptime-kuma spit out more info about the request in the logs? I have DEBUG=true set but it doesn’t seem to add much more info if any to the logs.

I had the exact same issue. Dropped back down to 1.23.11 and I was able to monitor Authentik again without that error. Version 1.23.12 was when it started showing the end of file error with Authentik.

**Comment by csmith1210** [comment]
> I had the exact same issue. Dropped back down to 1.23.11 and I was able to monitor Authentik again without that error. Version 1.23.12 was when it started showing the end of file error with Authentik.

Nice find! Yes I can confirm it works on 1.23.11 and fails on 1.23.12.

**Comment by Rudedog9d** [comment]
+1 to this happening on authentik, and 1.23.11 being a valid workaround. Thanks! :smile: 

I imagine this will be online for a bit if it's helpful for testing: https://auth.ctf.malteksolutions.com/-/health/ready/

**Comment by mcchots** [comment]
I was getting this error as well when I had the method set to `GET`, but got it working on `1.23.13` by changing to `HEAD`.

**Comment by csmith1210** [comment]
> I was getting this error as well when I had the method set to `GET`, but got it working on `1.23.13` by changing to `HEAD`.

Unfortunately this does not resolve the issue for me, I still get the end of file error.

**Comment by appuchias** [comment]
I just updated to 1.23.13 and have the same problem. Changing the method to HEAD did not solve it.

**Comment by zodac** [comment]
Chiming in to say I'm also seeing this on 1.23.13, and using HEAD also did not help.

**Comment by Aterfax** [comment]
Also seeing this same problem from UptimeKuma docker on a ARM64 host.

**Comment by thegcat** [comment]
We had the same issue and changing the request method to HEAD solved the problem for us.

**Comment by SuveenVundavalli** [comment]
I can also confirm that it works on `louislam/uptime-kuma:1.23.11-alpine`. Doesn't work on `louislam/uptime-kuma:1` when running in docker.

**Comment by JoeNyland** [comment]
> Nice find! Yes I can confirm it works on 1.23.11 and fails on 1.23.12.

I've found that in 1.23.12 of Uptime Kuma, Axios was upgraded from 0.27.0 to 0.28.1 and this changed how it handled 204 responses: see [here](https://github.com/axios/axios/issues/6327) for more info.

So, there's not much that can be done from Uptime Kuma's perspective, as it's not really where the issue is. 🙂

**Comment by kmbanahan** [comment]
Authentik update 2024.8 "Changed HTTP healthcheck endpoints status code" to return status code 200 instead of 204, and after updating authentik to this version Uptime Kuma appears to have no issue with it any longer.
