### ISSUE TITLE
Status page description field should be stripped of markdown for `<meta />` and manifest.json

### ISSUE THREAD

**Issue by JasonHK** [louislam/uptime-kuma#4739]
### 📑 I have found these related issues/pull requests

None

### 🏷️ Feature Request Type

Status-page

### 🔖 Feature description

The description field for status page supports Markdown syntax. But currently it only put the source to `<meta name="description" />` tag. For example if I put:

````markdown
[Hello world](https://example.com/)
````

It would just rendered as:

```html
<meta name="description" content="[Hello world](https://example.com/)">
```

I would like to put a full description for the page, and a short description for `<meta name="description" />` and manifest.json.

### ✔️ Solution

Separate the description setting into "Full description" and "Short description".

### ❓ Alternatives

Although less ideal, just strip the Markdown syntax would be fine as well:

```html
<meta name="description" content="Hello world">
```

**Comment by CommanderStorm** [comment]
Why do you think separating this into a short and long description would be better?

The only reason I can think of would be SEO and that is not a core goal.
=> I would think striping the tags from the rendered markdown would be better.

**Comment by CommanderStorm** [comment]
I don't think that we need to include a tuning knob for this.

**Comment by Nikogenia** [comment]
Hi, I have to agree to @JasonHK! In my opinion, it would be fantastic to have a separate description for the meta description tag. I want to use the normal description for contact details and other things too and think it should be important, to be able to set something different for the meta description. It matters because of links in social media apps, search engine results and so on ... Please implement it!!!

**Comment by Daulat1249** [comment]
Hey
It sounds like you're looking to implement Markdown rendering in the description field of your status page. Currently, the description is being placed directly into the <meta name="description" /> tag without being rendered, which means that any Markdown syntax is not being processed and appears as plain text.
To achieve proper Markdown rendering in the description field, you can follow these steps:
- 01. Use a Markdown parser (like marked.js, markdown-it, or similar) to convert the Markdown syntax into HTML before inserting it into the <meta> tag.
- 02. Update the Rendering Logic: Modify the logic that handles the description field to first convert the Markdown to HTML. For example, if you are using JavaScript, it might look something like this:
```
const markdown = "[Hello world](https://example.com/)";  
const html = marked(markdown); // Convert Markdown to HTML  
document.querySelector('meta[name="description"]').setAttribute("content", html);
```
- 03. Display HTML Properly: Ensure that the HTML is displayed correctly on the status page. If you want the description to be visible on the page itself (not just in the meta tag), you should insert the rendered HTML into a suitable element on your page, like so:
```
const descriptionElement = document.getElementById("description");  
descriptionElement.innerHTML = html; // Insert rendered HTML into the page
```
@JasonHK

**Comment by taisei-86** [comment]
@CommanderStorm @JasonHK 
Hey, I submitted a PR to fix it.

There was a suggestion that the issue should have both full and short explanations, but as a temporary measure they are being striping markdown.

https://github.com/louislam/uptime-kuma/pull/4968
