### ISSUE TITLE
change gmail smtp notification sender name

### ISSUE THREAD

**Issue by mamacodosacoazul** [louislam/uptime-kuma#4741]
how can i change the "me" to "Uptime Kuma" ?

![image](https://github.com/louislam/uptime-kuma/assets/167721595/c2fef371-e9e4-49bd-be09-94a5b635e01b)

-

![image](https://github.com/louislam/uptime-kuma/assets/167721595/552011a7-ed83-488c-98b5-4b682c9bbd29)

-

![image](https://github.com/louislam/uptime-kuma/assets/167721595/3c5fbbfd-f05e-4849-b920-1e2ff8c5e873)

**Comment by CommanderStorm** [comment]
@mamacodosacoazul Please look at what `me` really is.
If you use the same gmail adress to send as you recive it from, that is how gmail displays it.
=> use a differnent email adress
