### ISSUE TITLE
monitor in a group if down is reported double

### ISSUE THREAD

**Issue by tradexsrl** [louislam/uptime-kuma#4745]
### ⚠️ Please verify that this question has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

Hi , i have created many groups with inside some monitor , i notice that if only one is down , in the home page is reported double:
![immagine](https://github.com/louislam/uptime-kuma/assets/62424179/d4f82bce-8e91-4937-a8b1-c7f3dbbe7cc8)
this is the only one in the group website is down:
![immagine](https://github.com/louislam/uptime-kuma/assets/62424179/193f3dc7-2561-499d-ab3e-09d4346e5d69)

why ? is there a way to exclude the group in the count  ?

### 🐻 Uptime-Kuma Version

latest

### 💻 Operating System and Arch

docker

### 🌐 Browser

chrome - firefox

### 🖥️ Deployment Environment

- Runtime: 
- Database: 
- Filesystem used to store the database on: 
- number of monitors:

**Comment by CommanderStorm** [comment]
> why ?

groups are just regular monitors
=> them being included in this metric is intended behaviour as by current design

> is there a way to exclude the group in the count ?

Not currently

**Comment by ivancarlosti** [comment]
Maybe you should use tags instead of groups, groups generate alerts.

**Comment by tradexsrl** [comment]
Question: if i have monitors with name that start with A and C and S for example and i apply the same tag , if i have another montior with name that start with B , this will be listed after A-C-S or after A ? if it will be the second it's a problem because i have docker stack of 30 containers and i cannot have a list of mixed monitors that not belong to that stack

**Comment by CommanderStorm** [comment]
@tradexsrl @ivancarlosti 
This issue is about why groups are included in the count.

This issue is not about alerting, tags or ordering.
