### ISSUE TITLE
how to add a delay alert for ping

### ISSUE THREAD

**Issue by Ayyaaya** [louislam/uptime-kuma#4746]
### ⚠️ Please verify that this question has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

How to add a delay alarm for ping, such as triggering an alarm when ping>10ms

### 🐻 Uptime-Kuma Version

1.23.13

### 💻 Operating System and Arch

centos7

### 🌐 Browser

122.0.6261.70

### 🖥️ Deployment Environment

- Runtime: docker
- Database: 
- Filesystem used to store the database on: 
- number of monitors:

**Comment by CommanderStorm** [comment]
Currently, this is not a feature that we support.
You can have a look at https://github.com/louislam/uptime-kuma/pull/4005 and test if it works. We have not yet found the time to test+review it properly.

Issue is tracked in https://github.com/louislam/uptime-kuma/issues/1813 instead
Think this resolves your question
