### ISSUE TITLE
Environment Variable To Change Name

### ISSUE THREAD

**Issue by BigFlubba** [louislam/uptime-kuma#4748]
### 📑 I have found these related issues/pull requests

I cannot find anything relevant.

### 🏷️ Feature Request Type

Other

### 🔖 Feature description

I would like the ability to customize the name of everything with an environment variable. I am working on using multiple instances (one being routed through a VPN & one natively on my WAN (to monitor ping times and know if my VPN is having issues or if it is my WAN itself)) that I would have access to and I would want to have the ability to change the name of each instance so they are separate.

### ✔️ Solution

Added environment variable called `APP_NAME`.

### ❓ Alternatives

Ability to change the name in the settings on the web page.

**Comment by CommanderStorm** [comment]
You can disable the `Powered by` in the status page sidebar.
Given that you can have multiple status pages an enironment variable would not make sense

The name in the dashboard is intentionally not configurable. We are not some whitelabel commerical product, rather an open source project.
=> You can fork the project and maintain a fork if you want to change this part.

Adding a tag to the name to differentiate instances is tracked in https://github.com/louislam/uptime-kuma/issues/3827

> [!NOTE] 
> This won't be something that is configurable via environment variables. We try to keep those to the absolute minimum to simplify deployments. 

=> closing as not planed or a duplicate
