### ISSUE TITLE
`saveStatusPage` socket handler does not use `icon` specified in payload if not base64-encoded

### ISSUE THREAD

**Issue by jmolnar-comparative** [louislam/uptime-kuma#4749]
### 📑 I have found these related issues/pull requests

I did not find any related issues

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### Description

https://github.com/louislam/uptime-kuma/blob/dbbc79a05a2036176c8b011401c915c0db3384ca/server/socket-handlers/status-page-socket-handler.js#L139-L157

`config.icon` is never again referenced, only `config.logo`

### 👟 Reproduction steps

write to the status page socket handler with a payload like:
```json
{
    "icon": "/path/to/an/icon.svg"
}
```
or similar.

### 👀 Expected behavior

Status page should use provided icon.

### 😓 Actual Behavior

Status page keeps using whatever icon it is already using

### 🐻 Uptime-Kuma Version

1.23.13

### 💻 Operating System and Arch

Debian bookworm aarch64

### 🌐 Browser

Google Chrome 124.0.6367.119

### 🖥️ Deployment Environment

- Runtime: Docker 20.10.21 / nodejs 20
- Database: sqlite/embedded
- Filesystem used to store the database on: Debian/ext4 SSD
- number of monitors: 1

**Comment by CommanderStorm** [comment]
Yes that is a bug.
Thanks for digging into the code. Would you like to provide a PR => be attributed with this fix?
I am wondering: How did you come across this?

**Comment by jmolnar-comparative** [comment]
I have a PR almost ready, I'm just currently confirming on my patched local that it's possible to use the URL variant at all.

Assuming I can work out some CORS issues, then I'm expecting I can provide a simple one-liner.

As to how I came across it: I am automating a from-scratch status page setup, so the UI-driven upload flow is a no-go for me. I also don't really like the base64 upload because then I have to pull the current image and check if the contents match since I want to report whether I am changing the icon. I'd rather use either a cross-origin URL or a path relative to the data volume (I'm using the docker deployment variant).

**Comment by jmolnar-comparative** [comment]
I don't care about the attribution though; this is not my personal account

**Comment by jmolnar-comparative** [comment]
Confirmed that things work fine if I do this simple fix: https://github.com/louislam/uptime-kuma/pull/4750
