### ISSUE TITLE
api integration for displaying which monitors do have maintenance and give informations about it

### ISSUE THREAD

**Issue by blockiyt** [louislam/uptime-kuma#4752]
### 📑 I have found these related issues/pull requests

-

### 🏷️ Feature Request Type

API / automation options

### 🔖 Feature description

An endpoint or an section in the metrics api to display informations about maintenance, and which service it has, for how long, etc.

### ✔️ Solution

like already said above

### ❓ Alternatives

web-scraping the status page, and building the informations together for yourself

**Comment by CommanderStorm** [comment]
- we currenlty don't have a REST api see #118 for further context and the working plan to get there
- Please refer to https://uptime-kuma-api.readthedocs.io/en/latest/api.html#uptime_kuma_api.UptimeKumaApi.get_maintenances for a python api wrapper around the internal socket.io api
- or https://github.com/BigBoot/AutoKuma?tab=readme-ov-file#kuma-cli-- for a cli of the same

I think this is covered in #118 as the currently planned solution would essentially offer all current socket.io calls as REST endpoints
=> closed as a duplicate

**Comment by CommanderStorm** [comment]
Ah forgot about the metrics:

We already have this metric

```
# HELP monitor_status Monitor Status (1 = UP, 0= DOWN, 2= PENDING, 3= MAINTENANCE)
# TYPE monitor_status gauge
monitor_status{monitor_name="online",monitor_type="http",monitor_url="https://google.com",monitor_hostname="null",monitor_port="null"} 1
monitor_status{monitor_name="under maintenacne",monitor_type="http",monitor_url="https://example.com",monitor_hostname="null",monitor_port="null"} 3
```
