### ISSUE TITLE
Notifications for Diffrent Events

### ISSUE THREAD

**Issue by InvalidTeslaa** [louislam/uptime-kuma#4753]
### 📑 I have found these related issues/pull requests

Unable to find duplicates

### 🏷️ Feature Request Type

Change to existing notification-provider

### 🔖 Feature description

So for example members Not always Look at the Status Page and May miss then some upcoming maintenance or other changes

### ✔️ Solution

In My use-case it would be nice to include also other actions in webhooks like any changes to services, like changing tags, adding new service, changing maintenance status, scheduled maintenance, etc. This would give members the ability to receive the latest updates from the status page directly on different services and stay informed on what's upcoming and what happened

**Comment by CommanderStorm** [comment]
> members Not always Look at the Status Page and May miss then some upcoming maintenance

Sounds like you want either
- https://github.com/louislam/uptime-kuma/issues/916
- https://github.com/louislam/uptime-kuma/issues/2462

> changes to services, like changing tags, adding new service, changing maintenance status, scheduled maintenance

Here you likely want this for compliance reasons (at least I don't think you actually want notifications for tag changes) => you likely want
- https://github.com/louislam/uptime-kuma/issues/3481

That being said any of these sort of soft-depend on
- https://github.com/louislam/uptime-kuma/issues/508

I think this is already tracked in the existing issues, or am I missing something?
If yes, could you reword the issue to
- be less of a duplicate (= more concrete/resolvable)?
- Make sure to include the WHY (I think you have an [XY-Problem](https://en.wikipedia.org/wiki/XY_problem) => including why you want something makes it possible for us to avoid miscommunications)

Currently, I don't think we could ever close the issue as there will always be another thing which we could send notifications for which we are not.
=> I have changed this to a help-issue to reflect this ^^
