### ISSUE TITLE
Can't set timezone Europe/Kyiv

### ISSUE THREAD

**Issue by mmospanenko** [louislam/uptime-kuma#4754]
### 📑 I have found these related issues/pull requests

In current release

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### Description

Trying to sret timezone - getting an error 
<img width="354" alt="image" src="https://github.com/louislam/uptime-kuma/assets/2766211/80da5087-c2c0-4db6-bd04-cd39c9750ca0">

### 👟 Reproduction steps

1. go to /settings/general
2. set TZ: 
<img width="397" alt="image" src="https://github.com/louislam/uptime-kuma/assets/2766211/43e8aaa2-c417-418f-bd5d-d05a1c3819f5">
3. Save

### 👀 Expected behavior

Should be saved as expected

### 😓 Actual Behavior

Error message accured

### 🐻 Uptime-Kuma Version

1.23.13-alpine

### 💻 Operating System and Arch

Docker, Ubuntu, ARM64

### 🌐 Browser

Chrome latest

### 🖥️ Deployment Environment

- Runtime: docker
- Database: none
- Filesystem used to store the database on: ext
- number of monitors: 0

### 📝 Relevant log output

```shell
nothing
```

**Comment by CommanderStorm** [comment]
That is a known bug of the `-alpine` variant of images and one of the reasons we deprecated them.
Please use the regular images instead.
Support for `-alpine` can only dropped in v2.0 as by semver. Please see #4500 for further detais on said release.

- <details><summary><code>1-23.13-alpine</code></summary>
  <p>
  
  ![image](https://github.com/louislam/uptime-kuma/assets/26258709/ad712a4f-17b1-44db-86e3-52d43b8a7857)
  
  </p>
  </details> 
- <details><summary><code>1-23.13</code></summary>
  <p>
  
  ![image](https://github.com/louislam/uptime-kuma/assets/26258709/0db88853-0fcf-4265-8462-5e086fd52e58)
  
  </p>
  </details> 

I don't think investing time from our side why this is happening is worth it and think that the merged changes resolve this
=> closing as resolved

If you/somebody wants to debug this further and see why alpine is such a weird duck for some things that would be appreciated. (we accept bugfixes for v1, but at least my motivation to debug this dropped feature is not enough)
Our contribution guide is here: https://github.com/louislam/uptime-kuma/blob/master/CONTRIBUTING.md
