### ISSUE TITLE
Allow adding hyperlinks to monitors on status page

### ISSUE THREAD

**Issue by BBaoVanC** [louislam/uptime-kuma#476]
**Is your feature request related to a problem? Please describe.**

It would be nice to be able to configure it so each monitor could link to the service it's monitoring.

**Describe the solution you'd like**

Each monitor should have an option to make it link to the page it's monitoring. There should also be a text box to set a custom URL, in case it's different from the endpoint being monitored.

**Describe alternatives you've considered**

None

**Additional context**

[Upptime](https://demo.upptime.js.org) does this by clicking on the service (which views history), and then clicking on the service name again. There are probably other status page programs that do this too, but I couldn't find any easily.

**Comment by 401U** [comment]
Currently, you can enable the link for HTTP/HTTPS/Keyword monitors, it has a button as below.
![Y0316_214644](https://user-images.githubusercontent.com/52659312/225637460-46eedf9e-cf19-40c7-ad08-fcf32ad7e348.png)

But custom link for each monitor is not supported.

**Comment by CommanderStorm** [comment]
@BBaoVanC I think your issue is resolved. Please remember to close the issue if it is (only you or louis can do so)

**Comment by BBaoVanC** [comment]
> @BBaoVanC I think your issue is resolved. Please remember to close the issue if it is (only you or louis can do so)

How can it be done?

**Comment by CommanderStorm** [comment]
All monitors which have enough context to show an url have this option.
Monitors like the docker monitor don't, as it is not clear what url to display.
See https://github.com/louislam/uptime-kuma/issues/3784 for a duplicate of this issue.

**Comment by BBaoVanC** [comment]
> All monitors which have enough context to show an url have this option Monitors like the docker monitor don't, as it is not clear what url to display. See #3784 for a duplicate of this issue.
> 
> What monitor do you have? What url should be displayed?

I am using an HTTP(s) monitor. It should link to the URL of the service being monitored.

**Comment by CommanderStorm** [comment]
I cannot reproduce this behaviour. Could you please share screenshots?

![image](https://github.com/louislam/uptime-kuma/assets/26258709/e42afa4d-6c8b-4418-9f28-5ea5b4f1f039)
![image](https://github.com/louislam/uptime-kuma/assets/26258709/39f3a12c-af64-4ecf-a56a-a467719caa30)
![image](https://github.com/louislam/uptime-kuma/assets/26258709/5020617c-1b06-417a-9078-8202130fb36c)
![image](https://github.com/louislam/uptime-kuma/assets/26258709/83828fcf-6ce4-4335-9d68-3db88a34bad2)

**Comment by BBaoVanC** [comment]
> I cannot reproduce this behaviour. Could you please share screenshots?

After checking "Show Clickable Link" and then "Close", nothing happens, and if I click the settings cog again, then it's no longer checked.

![image](https://github.com/louislam/uptime-kuma/assets/17971474/77de9b69-ac4c-404b-9f29-ea6a0cd763dd)

After pressing close and then settings again:

![image](https://github.com/louislam/uptime-kuma/assets/17971474/e726124c-02ca-48bb-9368-52d2986ed4b2)

**Comment by CommanderStorm** [comment]
You need to click on the save-button to persist changes.
(can confirm the bug that on reopening the changes are reset to the previous saved status)

**Comment by BBaoVanC** [comment]
> You need to click on the save-button to persist changes. (can confirm the bug that on reopening modal resets to the previous saved status)

Alright, I guess it is solved. I will open a different issue for the modal reset bug (and some sort of indicator in the edit ui to show that clickable link is enabled)
