### ISSUE TITLE
Proxy option to notifications channel

### ISSUE THREAD

**Issue by MatanAmoyal1** [louislam/uptime-kuma#4760]
### 📑 I have found these related issues/pull requests

nope

### 🏷️ Feature Request Type

Change to existing notification-provider

### 🔖 Feature description

Proxy option to notifications channel. The same way we have the option to use proxy for monitoring. so enable the same option for notification channel, like Telegram.

### ✔️ Solution

.

### ❓ Alternatives

Adding the HTTP/S_PROXY env variable will solve it. but when adding the proxy radio like in monitoring, we can use a specific configured proxy from settings.

**Comment by CommanderStorm** [comment]
Duplicate of #616

**Comment by CommanderStorm** [comment]
Duplicate of #616
