### ISSUE TITLE
Add version info of app to uptime kuma

### ISSUE THREAD

**Issue by stevoh6** [louislam/uptime-kuma#4762]
### 📑 I have found these related issues/pull requests

I wasnt unable to find this feature request in existing issues.

### 🏷️ Feature Request Type

Dashboard

### 🔖 Feature description

Hi, it will be great if uptime kuma will be able to parse response and add version number to stats/dashboard to be able to see which application is up and running on which version. 

### ✔️ Solution

To be able see application version in stats/dashboard.

**Comment by CommanderStorm** [comment]
I don't know which of these you are requesting about:

- **Version information ABOUT uptime kuma**
  Please refer to https://github.com/louislam/uptime-kuma/issues/4730 for an in-depth discussion how we currently handle this, how we report being outdaed and how to recieve notifications for this
- **Version information ABOUT thrid party systems**
  How would we know this? Third party systems don't follow a set standard on this one
  => I think this part is kind of impossible unless I am missing something.

**Comment by stevoh6** [comment]
@CommanderStorm  hi, im talking about 3rd party systems. 

Im fully aware, that every system has "own" type of response. but Many users of uptime kuma are developer of that 3rd systems. So, if you create optional option ( you can chose whatever format you want - for example filed, when you put path to this version field or just you will hardly define where it should be) to enable and config this version info, we can adjust our system to provide such info. it will be really helpfull. Thank you.

**Comment by CommanderStorm** [comment]
Parsing the field automatically is tracked in https://github.com/louislam/uptime-kuma/issues/892
Adding public descriptions is tracked in https://github.com/louislam/uptime-kuma/issues/938

=> Think this resolves your question.

> [!TIP]
> As always, [Contributions welcome](https://github.com/louislam/uptime-kuma/blob/4794f9eb0bc47ebfe3eed3edaa7f880430052543/CONTRIBUTING.md) ^^
