### ISSUE TITLE
Enable Toast notification timeout to enable autoclosing `DOWN` toasts

### ISSUE THREAD

**Issue by jherriott35** [louislam/uptime-kuma#4766]
### ⚠️ Please verify that this question has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

I keep a computer on with the dashboard running to monitor equipment. When equipment goes down, there is a popup notification on the dashboard that never goes away until you manually X out of the popup to dismiss it, even if it has come back up already. I can also refresh the page and they all go away. I am looking for an option to either turn off those notifications, or automatically dismiss them after a few seconds, since the dashboard itself tells me when things are down. The pop-up notifications just seem to block the important views mostly. I will try to get my browser to automatically refresh every 30 seconds or so just to make sure they clear for me. Am I missing a setting somewhere?

### 🐻 Uptime-Kuma Version

1.23.11

### 💻 Operating System and Arch

Windows 10

### 🌐 Browser

Edge

### 🖥️ Deployment Environment

- Runtime: Docker
- Database: n/a
- Filesystem used to store the database on: NFS network share
- number of monitors: 54

**Comment by CommanderStorm** [comment]
> automatically dismiss [dashboard notification toasts] after a [configurable time]

The following PR has been merged and the setting will be avaliable in v2.0. Please refer to #4500 for steps needed before a beta can be published (or how to get involved ^^)
- https://github.com/louislam/uptime-kuma/pull/3441^

=> closing as resolved

> Filesystem used to store the database on: NFS network share

Please refer to the warning from our wiki.
=> Take regular backups and expect corruption at some point.

> [!WARNING]
> Filesystem support for POSIX file locks is required to avoid SQLite database corruption. Be aware of possible [file locking problems](https://www.sqlite.org/howtocorrupt.html#_file_locking_problems) such as those [commonly encountered with NFS](https://www.sqlite.org/faq.html#q5). **Please map the `/app/data-folder` to a local directory or volume**.
