### ISSUE TITLE
Correct MQTT Success Message from JSON Payload

### ISSUE THREAD

**Issue by IoT-CI-Ltd** [louislam/uptime-kuma#4767]
### ⚠️ Please verify that this question has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

I am monitoring some hardware and would like to use the MQTT monitor type.

My connected (UP) message (in JSON) is:

{"gatewayID":"[REDACTED_ID]","state":"ONLINE"}

What do I place in the MQTT Success Message ?

### 🐻 Uptime-Kuma Version

1.23.13

### 💻 Operating System and Arch

Ubunutu

### 🌐 Browser

Chrome

### 🖥️ Deployment Environment

- Runtime:  Docker
- Database: sqlite
- Filesystem used to store the database on: btrfs
- number of monitors: 5

**Comment by CommanderStorm** [comment]
What part of the returned response is a monitor for you?

I would expect that you would want:

```raw
{"gatewayID":"[REDACTED_ID]","state":"ONLINE"}
```

> [!TIP]
> We use `mqttSuccessMessage` ⊆ `receivedMessage` as the comparison. See
> https://github.com/louislam/uptime-kuma/blob/237a6e8da9ac492baa3f68a4db4679bf7ec833e6/server/monitor-types/mqtt.js#L31-L36
