### ISSUE TITLE
Response Time Chart/Graph does not show any data for 3hr or 6hr only 24hr and 1 Week. 

### ISSUE THREAD

**Issue by PortableDiag** [louislam/uptime-kuma#4770]
### 📑 I have found these related issues/pull requests

I dont see any existing issues about the response Time Chart/Graph. The bar chat for response time does not show any data for 3hr or 6hr only 24hr and 1 Week. It used to work but after upgrading, it no longer shows any data in those time frames.

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### Description

Response Time Chart/Graph does not show any data for 3hr or 6hr only 24hr and 1 Week. It used to work but after upgrading, it no longer does any data in those time frames.

### 👟 Reproduction steps

open the kuma dashboard and view any site details, check the Response Time chart, no data unless you switch it to 24hr

### 👀 Expected behavior

It should show the response time for the specified time period

### 😓 Actual Behavior

Shows nothing for 3hr 6hr only 24hr 1 week.

### 🐻 Uptime-Kuma Version

 Version: 1.23.13

### 💻 Operating System and Arch

Debian Bullseye

### 🌐 Browser

Mozilla Firefox

### 🖥️ Deployment Environment

- Runtime: years
- Database:  mongo
- Filesystem used to store the database on: ext4
- number of monitors: 37

**Comment by PortableDiag** [comment]
![Screenshot_20240517_092141](https://github.com/louislam/uptime-kuma/assets/1460320/f76d9634-9111-448e-ac60-260cf804a139)

**Comment by PortableDiag** [comment]
![Screenshot_20240517_092554](https://github.com/louislam/uptime-kuma/assets/1460320/0c0cfa53-d8be-486c-815c-39b1160e3552)

**Comment by CommanderStorm** [comment]
Hmm..
Cannot reproduce this issue on https://demo.kuma.pet/:
![image](https://github.com/louislam/uptime-kuma/assets/26258709/f69cb7fb-cdb0-4cd4-82e0-f7bbdb3d9587)

(=> recassifying accordingly)

=> Could recreate the monitor there to rule out if this is related to the monitor?

What seems "quite sus" to me is that the x-achsis is not showing 3 hours of data. In fact (depending on your timezone), it is showing more like a day and going into the future..

> Relevant log output: No response

=> Is there any `Relevant log output` (both server and browser)?

> Browser: Mozilla Firefox

Given the usage numbers of firefox are dwindeling ever further, I am not currently actively testing said platform. (behaviour differences are still bugs)
=> Is this reproducible in chrome?

> Runtime: years
> Database: mongo

We don't currently support mongodb as a database backend for uptime kuma. In v1, only sqlite is supported while in v2 we will be adding mariadb support.
=> Have you contacted whoever modified uptime-kuma and added mongodb as a db-backend?
