### ISSUE TITLE
Site access is normal, the system occasionally reports an error: `timeout of 48000ms exceeded`

### ISSUE THREAD

**Issue by Suery** [louislam/uptime-kuma#4772]
### 📑 I have found these related issues/pull requests

not reported

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### Description

![1](https://github.com/louislam/uptime-kuma/assets/55574045/f973edfd-26f5-463b-b36c-7178b866c69f)

### 👟 Reproduction steps

Cannot be reproduced by operation

### 👀 Expected behavior

not have

### 😓 Actual Behavior

error message

### 🐻 Uptime-Kuma Version

1.23.13

### 💻 Operating System and Arch

Windows 11

### 🌐 Browser

Microsoft Edge 125.0.2535.51

### 🖥️ Deployment Environment

Docker deployment

**Comment by CommanderStorm** [comment]
I have piped your responses through deepl.
I am going to spend the same amount of effort you spend on filling out the issue. You did not fill out most fields.

Network issues happen and lead to timeouts. This is expected.
=> consider either not considering them as errors by increasing your retry settings or make sure that there are no timeouts in the network you are using.
The level of retries nessesary depends on your networking setup and what the SLA of your service really is.
