### ISSUE TITLE
uptime-kuma files in centos

### ISSUE THREAD

**Issue by Blisk** [louislam/uptime-kuma#4776]
### ⚠️ Please verify that this question has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

I like to change password and update uptime-kuma, but I can not find where this is installed in centos 8. I didn't use docker but regular installation. I even don't know what to search which files.
Can anyone help, how to change password and update?

### 📝 Error Message(s) or Log

no error logs

### 🐻 Uptime-Kuma Version

don't know

### 💻 Operating System and Arch

centos 8

### 🌐 Browser

firefox

### 🖥️ Deployment Environment

- Runtime: centos 8
- Database: mariadb
- Filesystem used to store the database on: linux
- number of monitors: 6

**Comment by Blisk** [comment]
I found out for both.
https://github.com/louislam/uptime-kuma/wiki/Reset-Password-via-CLI

**Comment by CommanderStorm** [comment]
You already answered your question about the password reset.

> how to [..] update

Please refer to our wiki https://github.com/louislam/uptime-kuma/wiki/%F0%9F%86%99-How-to-Update

Think this resolves both issues. => Closing as resolved
If our docs are unclear on something it would be greatly to get more direct feedback where you were confused..
