### ISSUE TITLE
SMTP with special characters in credentials fail authentication

### ISSUE THREAD

**Issue by solidterre** [louislam/uptime-kuma#4777]
### 📑 I have found these related issues/pull requests

 I checked and didn't find similar issue.

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### Description

It seems that when using the Email (SMTP) notification type and using credentials with special characters ("/" or "\\" for example), the credentials can not be validated (I keep getting a 535 error).

<img width="1012" alt="image" src="https://github.com/louislam/uptime-kuma/assets/8171049/73e70b80-4fb8-4dca-880f-f32dd3ff3543">

I am sure these credentials are valid (checked multiple times) since they are the same (copy pasted, no additional spaces or invisible characters added) as the ones I use on another website and they work there.

It seems to me like this is due to an encoding issue ?

### 👟 Reproduction steps

1. Setup notification
2. Select Email (SMTP)
3. Fill in SMTP information
4. Use credentials with a special character (like "/" or "\\" f.e.)

### 👀 Expected behavior

It just works.

### 😓 Actual Behavior

"Invalid login" error.

### 🐻 Uptime-Kuma Version

1.23.13

### 💻 Operating System and Arch

Debian 12

### 🌐 Browser

Firefox

### 🖥️ Deployment Environment

- Runtime: Docker 26.1.3 + Caddy
- Database: SQLite
- Filesystem used to store the database on: 
- number of monitors: 6

**Comment by CommanderStorm** [comment]
We don't encode the password or username. 

- Before we go out and try replicating this:
Have you made sure that ALL the settings (including smtp-hostname+port, auth options, dkim, ...) are identical (not just username+PW)?
- Why do you think `special character (like "/" or "\" f.e.)` are at fault? (have you changed the password to be just alphanumeric? What was the result?)
- What mail provider are you using?

Unrelated:
`Database: MariaDB` is Conflicting with the version number. In v1, we only support sqlite as a database. See #4500 for further details.

**Comment by solidterre** [comment]
Actually it seems I was mistaken. For "pure" usage of SMTP tokens generated from AWS SES (which is the provider I use), I need to generate the SMTP password using a [special script](https://docs.aws.amazon.com/ses/latest/dg/smtp-credentials.html) - which I wasn't aware of before searching more thoroughly online.

Very sorry for the inconvenient time lost @CommanderStorm, my mistake. You can consider this closed.
