### ISSUE TITLE
TSL certificate error

### ISSUE THREAD

**Issue by Lihy6472** [louislam/uptime-kuma#4780]
### ⚠️ Please verify that this question has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

Error dialling a https address

### 📝 Error Message(s) or Log

write EPROTO C087507E347F0000:error:0A000172:SSL routines:tls12_check_peer_sigalg:wrong signature type:../deps/openssl/openssl/ssl/t1_lib.c:1594:

Time (Asia/Shanghai): 2024-05-22 09:01:10

### 🐻 Uptime-Kuma Version

1.23.10

### 💻 Operating System and Arch

Debian GNU/Linux 10 (buster)

### 🌐 Browser

124.0.6367.92

### 🖥️ Deployment Environment

docker deployment

**Comment by Lihy6472** [comment]
浏览器访问可以看到证书是有效的，

**Comment by CommanderStorm** [comment]
What do you mean by configuring chromium?

**Comment by Lihy6472** [comment]
> 配置 Chromium 是什么意思？

![image](https://github.com/louislam/uptime-kuma/assets/116717391/b5b9cade-4ce9-46a1-ae84-bc373f5fb13a)

![image](https://github.com/louislam/uptime-kuma/assets/116717391/b4d9748b-3489-4fd2-ad66-9917a69b8a1c)

**Comment by CommanderStorm** [comment]
can you please update to `1.23.13`?
We have made some improvements in this area in the last patch-releases.

**Comment by Lihy6472** [comment]
> 你能更新到吗`1.23.13`？ 我们在最近的补丁版本中对此领域做了一些改进。

* I am already in version 1.23.13 now

![image](https://github.com/louislam/uptime-kuma/assets/116717391/c27fb87d-05a0-4789-a7a5-ce3f3d2f5159)

**Comment by CommanderStorm** [comment]
What do you mean by cannot be monitored?

**Comment by Lihy6472** [comment]
> 无法使用 https 监控是什么意思？ 您可以分享您要监控的 URL 吗？（这对于远程调试来说确实很困难）
> 
> 您是否可以尝试使用 uptime.kuma.pet 是否会出现同样的行为？

* The following errors may occur when using HTTPS。

```
2024-05-27T09:00:50+08:00 [MONITOR] WARN: Monitor #3 '1': Failing: write EPROTO C047C726837F0000:error:0A000172:SSL routines:tls12_check_peer_sigalg:wrong signature type:../deps/openssl/openssl/ssl/t1_lib.c:1594:
 | Interval: 60 seconds | Type: http | Down Count: 0 | Resend Interval: 0
```

![image](https://github.com/louislam/uptime-kuma/assets/116717391/a2325f8b-30dd-4245-8a23-6a5dae9b4e97)

![image](https://github.com/louislam/uptime-kuma/assets/116717391/7b4fcb61-ca1a-4ea4-b0f9-c19f47c6ad2a)
