### ISSUE TITLE
An issue discovered in Axios 0.8.1 

### ISSUE THREAD

**Issue by Thajudecodes** [louislam/uptime-kuma#4782]
An issue discovered in Axios 0.8.1 through 1.5.1 inadvertently reveals the confidential XSRF-TOKEN stored in cookies by including it in the HTTP header X-XSRF-TOKEN for every request made to any host allowing attackers to view sensitive information.

**Comment by CommanderStorm** [comment]
We don't have a `XSRF-TOKEN`
=> if you include such a header, it is included if you don't it is not.
=> Not a security issue.

# ALSO DON'T REPORT SECURITY ISSUES IN PUBLIC ISSUES

Please refer to the issue template you ***DELETED***

> [!CAUTION]
> **DO NOT PROVIDE ANY DETAILS HERE. Please privately report to https://github.com/louislam/uptime-kuma/security/advisories/new.**
>
> **Why need this issue? It is because GitHub Advisory do not send a notification to @louislam, it is a workaround to do so.**
