### ISSUE TITLE
Docker Container Monitor Status Stuck on "Starting" (Yellow Bars)

### ISSUE THREAD

**Issue by zluckytraveler** [louislam/uptime-kuma#4786]
### ⚠️ Please verify that this question has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

I have a docker container for a discord bot that is for sure running and working properly as expected, however for some reason Uptime Kuma is showing the monitor "Down" with a status message of "Starting" with yellow bars rather than being "Up" with green bars. 

I have triple checked that the docker host connected is correct, the container name is correct, and have also tried using the container id in both short and long format.

I have many other monitors for Docker containers and they work as expected, it's only this one that is like this.

Why could this be and how can I fix this?

### 📝 Error Message(s) or Log

`[MONITOR] WARN: Monitor #71 'Markers': Pending: starting | Max retries: 4 | Retry: 0 | Retry Interval: 60 seconds | Type: docker`

<img width="869" alt="Screenshot 2024-05-22 at 8 52 48 AM" src="https://github.com/louislam/uptime-kuma/assets/97180817/780ee7d1-9fb7-48c9-8534-5cf778795723">

### 🐻 Uptime-Kuma Version

Version: 1.23.13

### 💻 Operating System and Arch

MacOS (Docker)

### 🌐 Browser

Safari, Chrome, Firefox

### 🖥️ Deployment Environment

- Runtime: Docker 4.30.0
- number of monitors: 66

**Comment by CommanderStorm** [comment]
> I have many other monitors for Docker containers and they work as expected, it's only this one that is like this.
> 
> Why could this be and how can I fix this?

Could you report the monitor status is via (only include the relevant line)
```bash
docker ps
```

The message says it is currently `starting`:
![image](https://github.com/louislam/uptime-kuma/assets/26258709/46f3200a-c009-4b0d-ac27-ddaf8e433b5b)
