### ISSUE TITLE
Modular Status Page with Resizable Groups

### ISSUE THREAD

**Issue by tyrellm04** [louislam/uptime-kuma#4787]
### 📑 I have found these related issues/pull requests

I couldn't locate any related FRs

### 🏷️ Feature Request Type

Status-page

### 🔖 Feature description

I would love the ability to customize the status page to be more modular. On a 16:9 or wider aspect ratio, there's a lot of unused "white space"... or "black space" if you choose to use dark-mode because you're not a degenerate 🤣. This space is both in the columns, but also in the middle of the monitors between their names/tags and the status bars.

### ✔️ Solution

I would love the ability to have the "groups" act more as "pods" that we could adjust into various sizes so that I could arrange them in such a way that it could eliminate the need to scroll by leveraging the empty space on the screen so that it could be used as a dashboard on a TV.

### ❓ Alternatives

I'm unaware of any alternative solutions for Uptime-Kuma that would allow for this. I did look through the "appearance" settings as well as the Status Page Settings.

I suspect I could try to hard-code the config with CSS, but I neither know CSS, nor would that be very flexible in nature.

### 📝 Additional Context

Given all of the space inside of the red boxes, I think I could fit all of the content on to a page I don't have to scroll for.
![image](https://github.com/louislam/uptime-kuma/assets/79353114/237d506e-e6d3-4676-8d89-acd63ea81fd8)

I use data analytics tools for work that are similar to PowerBi, but for the MSP space and they do a really good job on the UI to allow us to change the size, ratio, etc of the monitors to allow us to configure the boards however we need to. Something like this
![image](https://github.com/louislam/uptime-kuma/assets/79353114/98d61412-8d44-45e5-92d1-94c5137ac40a)

Having the ability to grab the corner of a "group" to re-size it would allow me to potentially group websites by category, then resize and arrange the groups on the page in a manner that would fit all of them onto the page.

Thanks again for the awesome tool!

**Comment by CommanderStorm** [comment]
Multi-collumn status pages are tracked in https://github.com/louislam/uptime-kuma/issues/592.

I don't think having a resisable and modular status page is something that we can allow in-scope. We are simple and being so modular is not simple.
=> closing as out of scope/wontfix

> [!NOTE]
> When you are looking for this level of customisability, you are likely looking for [grafana](https://grafana.com/) instead.

> [!TIP]
> We offer a pre-configured grafana dashboard which you can use and configure to your likings.
> See the **AWSOME** work which @MrDrache333 as contributed in https://github.com/louislam/uptime-kuma/pull/4680:
> ![uptime-kuma-dashboard](https://github.com/louislam/uptime-kuma/assets/22854641/4b7df766-0c7f-4442-9307-c84f25ea297c)
> We have documented how to set up metrics via grafana in https://github.com/louislam/uptime-kuma/wiki/Prometheus-Integration

**Comment by tyrellm04** [comment]
Thanks for the thoughtful and prompt response.
