### ISSUE TITLE
weblate zh-CN translation didn't sync to github

### ISSUE THREAD

**Issue by AnnAngela** [louislam/uptime-kuma#4788]
### ⚠️ Please verify that this question has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

https://weblate.kuma.pet/projects/uptime-kuma/uptime-kuma/#alerts

Lots of alerts saying that "The version control system (VCS) repository has too many changes compared to the upstream. Please manually merge the changes or set up a push to automate the process."

<details>
<summary>Alert screenshot</summary>

From my email:

![image](https://github.com/louislam/uptime-kuma/assets/9762652/b20e7bf9-ee52-4ac0-810e-35b46425c608)

</details>

And the [zh-CN.json](https://github.com/louislam/uptime-kuma/commits/master/src/lang/zh-CN.json) has not been updated from 4 months ago.

Please take a look at it, and if you are convenient, you can choose to recieve merge failure notification in weblate

**Comment by CommanderStorm** [comment]
Thanks for the headsup, merging #4394 (and related PRs) should resolve this issue. Feel free to contact us if this happens in the future and thanks for the translation work ^^
