### ISSUE TITLE
Auth failed login to SMTP server when special character in password

### ISSUE THREAD

**Issue by nidasfly** [louislam/uptime-kuma#4789]
### ⚠️ Please verify that this question has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

SMTP worked for Outlook months ago.
But I updated Uptime Kuma, it failed to work.
I reproduced this problem.
Then I registered a new outlook email, with no character in the password, it sent email successfully.

### 📝 Error Message(s) or Log

![image](https://github.com/louislam/uptime-kuma/assets/56987501/5e807c7c-3730-46aa-bb9c-4843b7c3bf1b)

### 🐻 Uptime-Kuma Version

1.23.13

### 💻 Operating System and Arch

fly.io

### 🌐 Browser

Chrome

### 🖥️ Deployment Environment

[build]
  image = 'louislam/uptime-kuma:1'

**Comment by Vishnu-01-cyber** [comment]
I am facing the same issue. Have you found any solution.

**Comment by nidasfly** [comment]
> I am facing the same issue. Have you found any solution.

Sorry no, I am not a developer of uptime-kuma.

What I did for notify is I used another email, which only contains letters as password.
Maybe you can try change the password to letters only?

**Comment by CommanderStorm** [comment]
> Gmail SMTP

Could you have a look at https://github.com/louislam/uptime-kuma/issues/2928#issuecomment-1477648543 and see if you have enabled the app password properly?

Also given that the error message you showed could you make double sure that ALL fields (not just username and password, also DKIM, SMTP hostname/port/...) are identical?
(We get a lot of issues from simple typos)

**Comment by nidasfly** [comment]
Yes with the gmail app pass, which has no special character, is working.
But other email provider, like outlook, with special character in password, is not working.
I've tested using python with the exact same config, it's working in python.

![image](https://github.com/louislam/uptime-kuma/assets/56987501/beea80b2-0a68-4b0c-b6fa-1f605cf158ee)

**Comment by CommanderStorm** [comment]
The reason why you did not find a place where we chage the password is that it does not exist.
I don't know what is happening with your email provider.

We just pass the username and password to nodemailer as you submitted it to the frontend...

The relevant code is:

https://github.com/louislam/uptime-kuma/blob/4df71af34f6e4333f5efb3178a71db885c2c3380/server/notification-providers/smtp.js#L38-L41
https://github.com/louislam/uptime-kuma/blob/4df71af34f6e4333f5efb3178a71db885c2c3380/src/components/notifications/SMTP.vue#L38-L46

Maybe a similar case as reported here?
- https://github.com/louislam/uptime-kuma/issues/4790

**Comment by CommanderStorm** [comment]
Yes, but that is not the issue..
=> please check the rest of your config for typos and retry again. Depending on your email provider you might also need to activate smtp or hop through additional steps like you have to do for Gmail, GMX or similar..

- <details><summary>without <code>!?</code></summary>
  <p>
  
  ![image](https://github.com/louislam/uptime-kuma/assets/26258709/433e4746-7cf3-427d-8ce0-4eb41ab9430b)
  
  </p>
  </details> 
- <details><summary>with <code>!?</code></summary>
  <p>
  
  ![image](https://github.com/louislam/uptime-kuma/assets/26258709/0750a474-cd59-44f2-bbe9-a5705e810c14)
  
  </p>
  </details>
