### ISSUE TITLE
Add Minecraft Server checking

### ISSUE THREAD

**Issue by realdeadbeef** [louislam/uptime-kuma#479]
It would be quite handy to have a way of checking the status of a Minecraft server. E.g. Number of players, tps, mspt...

**Comment by lexmozli** [comment]
I think this tool has a different purpose overall and won't get into this kind of specific checkups. You can check already check if a server is online and such by doing a port or ping check, it's enough for 99% of use cases.

**Comment by Ponkhy** [comment]
Yes @lexmozli is right, that's a bit out of scope for this project. You can also try to create a TCP Port Check on Port 25565 to just monitor the specific MC Server.

**Comment by louislam** [comment]
So creative, but I agree this is out of scope.

**Comment by comendantmc** [comment]
Checking player count may be out of scope, but it does make sense to add minecraft healthcheck, because it doesn't work properly with TCP check. My server is offline, but uptime-kuma doesn't detect it

**Comment by TheColetrain** [comment]
I am not asking for anything Fancy. But a guide on best practices to monitor a Minecraft service would be great. I'm still learning and the "ping" "monitor" seems to be erratic. Googling and found this for best practices.

Again, don't do anything different, just help me find best practices with existing setup.  Maybe this is elementary and I just don't know. Sorry/thanks.

**Comment by louislam** [comment]
In 1.20.1, you can monitor Minecraft with GameDig monitor type.

**Comment by OnCloud125252** [comment]
> Checking player count may be out of scope, but it does make sense to add minecraft healthcheck, because it doesn't work properly with TCP check. My server is offline, but uptime-kuma doesn't detect it

A bit late, but the reason is that Minecraft doesn't use the TCP protocol.

**Comment by magmaus3** [comment]
> A bit late, but the reason is that Minecraft doesn't use the TCP protocol.

This is not entirely true, Minecraft Java Edition uses tcp ([source](https://wiki.vg/Protocol#Definitions)), but Bedrock Edition uses udp ([source](https://wiki.vg/Bedrock_Protocol))

**Comment by adamnoffie** [comment]
I don't know how "best practice" it is, but this came up high in Google for me too so sharing here: I was able to setup a "GameDig" monitor and point it to port 19132 (UDP) on my Minecraft Bedrock Edition server and it seems happy enough with it so far.

**Comment by chris-coria** [comment]
> I don't know how "best practice" it is, but this came up high in Google for me too so sharing here: I was able to setup a "GameDig" monitor and point it to port 19132 (UDP) on my Minecraft Bedrock Edition server and it seems happy enough with it so far.

How did u manage to do that? Cannot configure it

**Comment by adamnoffie** [comment]
> How did u manage to do that? Cannot configure it

Here is my config for Minecraft Bedrock Edition server - you'll of course have to substitute in your own IP address or hostname for the Hostname field.

<img width="567" height="691" alt="Image" src="https://github.com/user-attachments/assets/c407cad4-f72b-4e97-8527-d5846d96f4db" />
