### ISSUE TITLE
Using docker compose to build local image

### ISSUE THREAD

**Issue by ivancarlosti** [louislam/uptime-kuma#4796]
### ⚠️ Please verify that this question has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

I am trying to run:
```docker compose up -d --build```
To build and run a local docker image, based on /docker/dockerfile, but it returns error, how could I build my local image using docker compose --build?

### 📝 Error Message(s) or Log

```
 => [uptime-kuma upload-artifact 4/7] RUN chmod +x /app/extra/upload-github-release-asset.sh                                                                                                         0.4s
 => ERROR [uptime-kuma upload-artifact 5/7] RUN cd /app && tar -zcvf dist.tar.gz dist                                                                                                                0.4s
------
 > [uptime-kuma upload-artifact 5/7] RUN cd /app && tar -zcvf dist.tar.gz dist:
0.381 tar: dist: Cannot stat: No such file or directory
0.387 tar: Exiting with failure status due to previous errors
------
failed to solve: process "/bin/sh -c cd /app && tar -zcvf $DIST dist" did not complete successfully: exit code: 2
```

### 🐻 Uptime-Kuma Version

1.12.13

### 💻 Operating System and Arch

Ubuntu 24.04

### 🌐 Browser

125.0.6422.78

### 🖥️ Deployment Environment

- Runtime: Docker 26.1.3
- Database: sqlite/embedded
- Filesystem used to store the database on: btrfs
- number of monitors: 65

**Comment by CommanderStorm** [comment]
What are you trying to do in the first place?
You are likely better off with one of the installation methods we actively support https://github.com/louislam/uptime-kuma/wiki/%F0%9F%94%A7-How-to-Install

Uptime-Kuma Version [`1.12.13`](https://github.com/louislam/uptime-kuma/releases/tag/1.12.13) is not a published version of our software.
=> you are likely refering to [`1.23.13`](https://github.com/louislam/uptime-kuma/releases/tag/1.23.13). In this case please use this docker image instead [`louislam/uptime-kuma:1.23.13`](https://hub.docker.com/layers/louislam/uptime-kuma/1.23.13/images/sha256-5ed40a58b56b689ec2af50230e8d28804503351fed5eb54b1aefe530a8ea1fdc?context=explore)

If you need to buid the docker image, please refer to previous comments on this matter: https://github.com/louislam/uptime-kuma/issues/4646#issuecomment-2034704023

Think this resolves the question.
Please still respond why you are trying to do this in the first place. This is not the only issue where users have asked about this, but we have to date never gotten a response on this one.

**Comment by ivancarlosti** [comment]
> What are you trying to do in the first place? You are likely better off with one of the installation methods we actively support https://github.com/louislam/uptime-kuma/wiki/%F0%9F%94%A7-How-to-Install
> 
> Uptime-Kuma Version [`1.12.13`](https://github.com/louislam/uptime-kuma/releases/tag/1.12.13) is not a published version of our software. => you are likely refering to [`1.23.13`](https://github.com/louislam/uptime-kuma/releases/tag/1.23.13). In this case please use this docker image instead [`louislam/uptime-kuma:1.23.13`](https://hub.docker.com/layers/louislam/uptime-kuma/1.23.13/images/sha256-5ed40a58b56b689ec2af50230e8d28804503351fed5eb54b1aefe530a8ea1fdc?context=explore)
> 
> If you need to buid the docker image, please refer to previous comments on this matter: [#4646 (comment)](https://github.com/louislam/uptime-kuma/issues/4646#issuecomment-2034704023)
> 
> Think this resolves the question. Please still respond why you are trying to do this in the first place. This is not the only issue where users have asked about this, but we have to date never gotten a response on this one.

Hi, I want to do some changes on build because the [ ] on subject mess up the Gmail thread system, some alerts are threaded with different ones because of it, also I would like to add on UP alerts the time that the outage took, as like Uptime Monitor does.
