### ISSUE TITLE
nginx reverse proxy does not work

### ISSUE THREAD

**Issue by yuanjie-ai** [louislam/uptime-kuma#4797]
### ⚠️ Please verify that this question has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

```
location ^~ /x/
{
    proxy_pass http://localhost:3001/;
    proxy_set_header Host localhost;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header REMOTE-HOST $remote_addr;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection $connection_upgrade;
    proxy_http_version 1.1;
    # proxy_hide_header Upgrade;
```

### 📝 Error Message(s) or Log

no response

### 🐻 Uptime-Kuma Version

1.10.0

### 💻 Operating System and Arch

linux

### 🌐 Browser

chrome

### 🖥️ Deployment Environment

no response

**Comment by CommanderStorm** [comment]
hi,

> [!TIP]
> First of all repeating the same content 3x is not very productive. Please include the content we are asking for the next time.
Doing below the minimum efffort and not filling out the fields (missing version and arch in `linux`, missing version in `linux`, no error message, no deployment environment, no "I did X, and then Y happend" in the problem description) just leads to worse support of your issue.

We have documented the process how to install nginx in our wiki at https://github.com/louislam/uptime-kuma/wiki/Reverse-Proxy#nginx
=> please follow the configuration we provide instead of writing your own.

> [!NOTE]
> Uptime Kuma does not support a `subdirectory` such as http://example.com/uptimekuma. Please prepare a domain or sub-domain to do that. A hacky way to produce subdirectory status pages [is listed here](https://github.com/louislam/uptime-kuma/wiki/Status-Page#custom-subdirectory--custom-html-on-status-pages).
> This issue is tracked in https://github.com/louislam/uptime-kuma/issues/147

**Comment by krivahtoo** [comment]
Hi.

I also ran into this issue even after using the config in https://github.com/louislam/uptime-kuma/wiki/Reverse-Proxy#nginx (`With SSL (Certbot):`). unless there is another option that i need to set.

compose.yaml: 
```yaml
  uptime:
    image: louislam/uptime-kuma:1
    container_name: uptime-kuma
    ports:
      - "3001:3001"
    volumes:
      - uptime-kuma:/app/data

```

**Comment by CommanderStorm** [comment]
> ran into this issue

Doubtfull, as this issue does contain no context what @yuanjie-ai issue actually was.
Next time, please open a dedicated issue and link to this one, as remote debugging is already hard (no need to make it harder when missing the context we ask in the issue form)

To your issue:
- Could you share your nginx configuration file?
- what do you mean by `PS: this is the initial setup, I should redirect to setup, but it doesn't`?
  What site are you accessing how? What are you seeing instead?

**Comment by krivahtoo** [comment]
Hi @CommanderStorm

I'll open new issue with more context.
