### ISSUE TITLE
getaddrinfo ENOTFOUND occasionally

### ISSUE THREAD

**Issue by sudoexec** [louislam/uptime-kuma#4798]
### 📑 I have found these related issues/pull requests

- https://github.com/louislam/uptime-kuma/issues/220
- https://github.com/louislam/uptime-kuma/issues/3992
- https://github.com/louislam/uptime-kuma/issues/4765

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### Description

There are some `getaddrinfo ENOTFOUND` errors occasionally(0-3 errors per day).

Uptime Kuma running in k8s. Upstream dns is k8s's coredns and coredns don't have any error logs.
I use `while true; do nslookup example.com && sleep 1; done` to test dns resolution and no errors.

The error occurs randomly and I can't reproduce it.
Is there any methods to find details about this error?

### 👟 Reproduction steps

Can't reproduce.

### 👀 Expected behavior

No getaddrinfo ENOTFOUND errors.

### 😓 Actual Behavior

getaddrinfo ENOTFOUND

### 🐻 Uptime-Kuma Version

1.23.11

### 💻 Operating System and Arch

k8s

### 🌐 Browser

125.0.6422.112 (Official Build) Arch Linux (64-bit) 

### 🖥️ Deployment Environment

- Runtime: k8s v1.18.1
- Database: sqlite
- Filesystem used to store the database on: local storage via hostpath
- number of monitors: 52

### 📝 Relevant log output

```shell
Failing: getaddrinfo ENOTFOUND
```

**Comment by CommanderStorm** [comment]
Same steps as in https://github.com/louislam/uptime-kuma/issues/4765

> `getaddrinfo ENOTFOUND test.xyz`

- What is the TTL of the domains you are using?
- Do you have DNS caching enabled in the settings?


Most commonly, this issue is caused by you using a DNS resolver which does not like the level of DNS requests it is getting.
=> your DNS Server is dropping SOME requests
=> have you enabled NSCD in the settings to lowered the amount of DNS requests to your TTL (instead of on every request)

**Comment by CommanderStorm** [comment]
I have no clue what could be causing this.

Lets rule out the stupid cauases first:
- could you look in the log if NSCD has been successfully started? (possible cause: using a custom UUID/GUID)
- have you verified that the TTL is actually 600?
- > coredns don't have any error logs
  
  Just to make sure: you have activated https://coredns.io/plugins/errors/ and/or https://coredns.io/plugins/log/?
  What are the logs?

**Comment by sudoexec** [comment]
> I have no clue what could be causing this.
> 
> Lets rule out the stupid cauases first:
> 
> * could you look in the log if NSCD has been successfully started? (possible cause: using a custom UUID/GUID)
> * have you verified that the TTL is actually 600?
> * > coredns don't have any error logs
>   
>   
>   Just to make sure: you have activated https://coredns.io/plugins/errors/ and/or https://coredns.io/plugins/log/?
>   What are the logs?

- `ps aux` show NSCD is running
- I'm sure TTL is 600
- I enable errors plugin but not log plugin. I'll try to enable log plugin to find more details.

**Comment by sudoexec** [comment]
@thielj Host machine is ubuntu 18.04.
Here are resolv.conf:
```
# Host
nameserver 119.29.29.29

# Container
nameserver 10.96.0.10                 # k8s coredns
search namespace.svc.cluster.local svc.cluster.local cluster.local
options ndots:5
```

Thanks for the info you provided, I've learned more abount DNS internal from it.

Additionally, I've added another nameserver to uptime kuma pod, and there're no errors in the past 2 days.

**Comment by CommanderStorm** [comment]
We should likely document this here
https://github.com/louislam/uptime-kuma/wiki/Troubleshooting

What is your second nameserver? (how did you find it's IP? Do you have multiple coredns instances running?)

(Not a kubernetes/dns wizard 😅)

**Comment by skrue** [comment]
I started seeing this behavior after setting up AdGuard Home. In my previous setup I only had Unbound DNS running on my OPNsense router/firewall. Now, AdGuard will relay all requests that it doesn't decide to block to Unbound, so AdGuard is the primary DNS. My entire home network is whitelisted in AdGuard as is the Uptime Kuma IP, so no blocking should be happening there. I am running Uptime Kuma as an LXC container on my Proxmox host. `getaddrinfo ENOTFOUND` errors pop up roughly once a day for each monitor that I have configured. I have now increased the retry value from 0 to 2, let's see if that helps.

**Comment by sudoexec** [comment]
Weeks age, I change my upstream DNS (which is provided by cloud service and managed by systemd-resolved) to another 2 public DNS server. There's no `getaddrinfo ENOTFOUND` error again.

**Comment by benoitjpnet** [comment]
> I started seeing this behavior after setting up AdGuard Home. In my previous setup I only had Unbound DNS running on my OPNsense router/firewall. Now, AdGuard will relay all requests that it doesn't decide to block to Unbound, so AdGuard is the primary DNS. My entire home network is whitelisted in AdGuard as is the Uptime Kuma IP, so no blocking should be happening there. I am running Uptime Kuma as an LXC container on my Proxmox host. `getaddrinfo ENOTFOUND` errors pop up roughly once a day for each monitor that I have configured. I have now increased the retry value from 0 to 2, let's see if that helps.

Having the same setup and same issue. I wonder what's wrong with Adguard... Nothing in the logs.

**Comment by bdavj** [comment]
Seeing the same issue here. Uptime Kurma, AGH. I'm seeing it on internal domains (delegated to UniFi via AGH), but AGH is set to reply even on fail if in cache so should still be ok on that end (and never saw any issues with PiHole forwarding to UniFi)

**Comment by antoniozh** [comment]
I'm getting the same issues on the regular, but not with Adguard. It's a VPS with tailscale and it's DNS installed

**Comment by jamesmacwhite** [comment]
You should check the DNS resolution status on the host OS. In my case, I have Docker installed on an Ubuntu host, the DNS resolution the host had failed through systems-resolved, after restarting the service things came back, but then docker needed to be restarted for the container to have working DNS again.
