### ISSUE TITLE
[ENHANCEMENT] Periodic Pause

### ISSUE THREAD

**Issue by Elpatii** [louislam/uptime-kuma#48]
Hello,

First, a huge thanks for this application. I was searching for an Uptime Robot alternative, and this is perfect.

A small idea for the next of this application: ability to set a periodic pause.
For example, I have an image automatic update of all of my containers in the night. 
When I wake up, I see alerts for all containers updated and their "OK" state just after.
With an automatic pause to selected monitored endpoint, every day, at 3am, for 10 minutes, this "problem" is resolved.

So if we can set for a monitor, a pause with a cron, it should be perfect!

Thanks :)

**Comment by Panja0** [comment]
We’ve got this covered already in https://github.com/louislam/uptime-kuma/issues/21

😃

**Comment by Elpatii** [comment]
Oh yes, not seen your post. Nice idea to group enhancements request :)
