### ISSUE TITLE
Problem with sending domains via AP

### ISSUE THREAD

**Issue by arlewis121** [louislam/uptime-kuma#4807]
### ⚠️ Please verify that this question has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

I have created API in Kuma also created Api on domain registrar side. 
My task is to import hundreds of domains from the Kuma system.

I have written a python script that links the registrar and Kuma but on the Kuma side I have some problem.
 
I am using 

kuma_api_url = ‘http://HERE_IS_MY_KUMA_UP:3001/api/v1/monitor’
kuma_api_key = ‘HERE_IS_MY_API’

But for example when going to pages:
http://HERE_IS_MY_KUMA_UP:3001/api/v1/monitor
http://HERE_IS_MY_KUMA_UP:3001/api/monitor
http://HERE_IS_MY_KUMA_UP:3001/monitor

I get a stub from kuma - page not found. 

Also when I run the script I get errors in the console such as

Failed to add domain ***** to Uptime Kuma

### 🐻 Uptime-Kuma Version

1.23.13

### 💻 Operating System and Arch

Ubuntu 24.04 LTS

### 🌐 Browser

-

### 🖥️ Deployment Environment

- Runtime: Docker version 24.0.7, build 24.0.7-0ubuntu4
- Database: apt install mysql-client-core-8.0  # version 8.0.35-1ubuntu2, or
apt install mariadb-client-core    # version 1:10.11.6-1

**Comment by CommanderStorm** [comment]
I don't know where you installed or what you installed, but the information does not line up at all.

We currently don't have an api. Please refer to my comment here for your options https://github.com/louislam/uptime-kuma/issues/118#issuecomment-2143409606

Also maridadb is not a database option in v1.23.13. Please refer to #4500 for further details
