### ISSUE TITLE
Reverse Proxy 

### ISSUE THREAD

**Issue by Fatih5252** [louislam/uptime-kuma#4809]
### ⚠️ Please verify that this question has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [x] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

hey i have a problem. i did host my website on github but a couple of hours ago i am not hosting in github anymore so now i did everything in the Reverse Proxy tab but this error is now comming can anyone maybe help? 
![image](https://github.com/louislam/uptime-kuma/assets/154845930/609112d9-c73c-40be-8880-d73ac2e0c011)

### 🐻 Uptime-Kuma Version

1.23.13

### 💻 Operating System and Arch

x64

### 🌐 Browser

Microsoft Edge

### 🖥️ Deployment Environment

- Runtime: nodejs v21.7.1
- number of monitors: 4

**Comment by CommanderStorm** [comment]
Given that you are being shown the GitHub page, your dns entry is pointing to GitHub.
Since you moved your site, the 404 page is being shown.

**Comment by Fatih5252** [comment]
so how can i fix this problem?

**Comment by CommanderStorm** [comment]
Either by not pointing your dns to GitHub (or by fixing the 404 error of GitHub pages)

**Comment by Fatih5252** [comment]
Yeah i deleted all the ip's cname things that has to do with github

**Comment by Fatih5252** [comment]
Or wait got it thanks!
