### ISSUE TITLE
Per-status-page robots.txt

### ISSUE THREAD

**Issue by BluCobalt** [louislam/uptime-kuma#4810]
### 📑 I have found these related issues/pull requests

I couldn't find any related issues.

### 🏷️ Feature Request Type

Status-page

### 🔖 Feature description

"Search engine visibility" should be toggleable for different status pages.

### ✔️ Solution

I have some status pages that should be public, and I have some that I don't want to be public. Being able to set only some status pages as hidden (or set them exempt from the instance-wide policy) would be really useful for that.

**Comment by CommanderStorm** [comment]
Non public status pages is not a feature that we currently offer.
If we would, those would not be included in that report.

I see no reason to make this into another setting.
Lets track this together with private status pages in the following issues:
- (parent) https://github.com/louislam/uptime-kuma/issues/1050
- (related, not duplicate) https://github.com/louislam/uptime-kuma/issues/938

=> closing as a duplicate
