### ISSUE TITLE
Add a Description to Monitor on Status Page

### ISSUE THREAD

**Issue by 14wkinnersley** [louislam/uptime-kuma#482]
**Is it a duplicate question?**
_Not that I am aware of._

**Is your feature request related to a problem? Please describe.**
The current status page does not have a description of each monitor for what it is/what it does.

**Describe the solution you'd like**
It would be great to add a small help icon next to the monitor that you can either hover over or click and it will show a description of what the service/monitor is. The description could be updated in the settings for each monitor. 

**Describe alternatives you've considered**
None that I can think of.

**Additional context**
![Capture](https://user-images.githubusercontent.com/1341459/134784662-e8700720-dfa0-4cef-8702-a4727d90c850.PNG)

**Comment by djbr22** [comment]
2nd this request. My titles are getting kind of long. Currently I'm displaying descriptions like "Website (https://domain.com)"

**Comment by jcvincenti** [comment]
Can I work on this issue?

**Comment by deefdragon** [comment]
> Can I work on this issue?

Pull Requests are always welcome!

You may wish to familiarize yourself with some of the other PRs that are in progress, should there be anything conflicting, and some of the other feature requests should anything be easily combined into one PR, but its far from required. Feel free to take a swing at whatever you want.

**Comment by chakflying** [comment]
Since this will be a database change related to the status page, be aware of the elephant in the room that is #863.
