### ISSUE TITLE
Question about group status percentage

### ISSUE THREAD

**Issue by fools12** [louislam/uptime-kuma#4822]
### ⚠️ Please verify that this question has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

I'm trying out Uptime Kuma, and just playing around, I have a group of two devices, one online, the other offline, On the status page, I'd expect for the uptime percentage to balance out at 50% since one device is online the other offline, but instead of what I expect, the uptime for the entire group drops to 0% over the course of about 30 minutes. 

For an end user looking at a status panel this looks very bad. Is there any way I could get the percentage to average between all devices in a group instead of just dropping to 0 ?

### 🐻 Uptime-Kuma Version

1.23.13

### 💻 Operating System and Arch

Windows 10 pro 22H2

### 🌐 Browser

Chrome 125.0.6422.142

### 🖥️ Deployment Environment

N/a

Running non-docker on a command line for testing purposes.
Windows 10 Pro 22H2

**Comment by CommanderStorm** [comment]
> [!TIP]
> Instead of posting on all different support platforms at the same time, please reconsider to only post on one the next time. Your reddit post: https://www.reddit.com/r/UptimeKuma/s/2BNrmC4BhJ


Groups of are up if ALL of their members are up.
So far, this is intended behavior.

Work in this area is dependent on https://github.com/louislam/uptime-kuma/pull/4395 getting merged first.
This issue is tracked in multiple other issues you can subscribe to/contribute on (search for groups in the issue-search ^^)
