### ISSUE TITLE
Disabling Popups bottom right

### ISSUE THREAD

**Issue by corincorvus** [louislam/uptime-kuma#4824]
### 📑 I have found these related issues/pull requests

No issue or request like mine found

### 🏷️ Feature Request Type

Settings

### 🔖 Feature description

At the moment the webgui shows many popups while sensors go in maintenance or show an error. Menu points are not usable, while the popups are overlapp this all.
![image](https://github.com/louislam/uptime-kuma/assets/21257329/cf12389c-42f3-4559-98b7-d2aa15eb1533)
![image](https://github.com/louislam/uptime-kuma/assets/21257329/53b1e94c-f2c4-46f1-ae23-976f3499e1e4)

I need to click active in the window to enable the timeout for blue and green popups. Red Popups i need to click away. 

### ✔️ Solution

A way to disable popups completely. i can see the problem in the log and left in the list. Also i can see the error in my notifications.

**Comment by CommanderStorm** [comment]
In v2.0 we will allow you to add timeouts for all of these toasts. I would need to look up if the roasts can be disabled.

**Comment by catataw** [comment]
+1
