### ISSUE TITLE
Latest version 1.23.13 cannot use MariaDB database

### ISSUE THREAD

**Issue by 3-commerce** [louislam/uptime-kuma#4826]
### 📑 I have found these related issues/pull requests

Related to #4728

### 🏷️ Feature Request Type

Dashboard, Deployment, Settings, Other

### 🔖 Feature description

Uptime Kuma is used in production level for monitoring atleast 20 databases, 30 API Endpoint path, and 10 Kubernetes Cluster. By using current Uptime Kuma database sqlite, my team finds unrealiable dashboard such as lagging, slow down, etc.

### ✔️ Solution

In the current master, i find [this line](https://github.com/louislam/uptime-kuma/blob/master/server/database.js#L7) for supporting database MariaDB. However, in version 1.23.13 that part is not pushed.

**Comment by louislam** [comment]
Will be available in 2.0.0

**Comment by CommanderStorm** [comment]
@3-commerce 
For the performance aspects of your question, please refer to the tips in #4500
