### ISSUE TITLE
Using Group Notifications as a Summary of Child Devices

### ISSUE THREAD

**Issue by alkcbs** [louislam/uptime-kuma#4829]
### ⚠️ Please verify that this question has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

New Uptime Kuma user here (a few weeks in). I am hoping to utilize groups to monitor various 'clusters' of equipment. For example, I am at the HQ location for my company, and we have branches 1, 2, and 3 as well. Within the HQ, we have multiple buildings. Therefore, in addition to monitoring some individual items, I'd also like to monitor "is branch 1 down" or "is the annex down" in addition to "is just the server at branch 1 down, but everything else is up."

I have found that when using group notifications, if something in that group is down, the email body simply states "[Group name] [Down] Child inaccessible." This unfortunately is not helpful, as I need to know which device(s) within the group are down. The only way I can find to do that is to alert on each device individually, which then makes the group notification redundant (if 1/5 devices is down, we get 2 notifications. If 5/5 devices are down, we get 6 notifications; one for each device and one for the group).

Is it possible to have the group alert email body to state something along the lines of:

"[Group name] [Down] 2/5 Children inaccessible.

DOWN: [device that is down]
DOWN: [device 2 that is down]
UP: [device 3]
UP: [device 4]
UP: [device 5]"

This would make it possible to configure alerts ONLY at the group level, so if an entire branch goes down, we get one summary email, instead of one notification per device.

Thank you!

### 🐻 Uptime-Kuma Version

1.23.13

### 💻 Operating System and Arch

Windows 11 Pro x64

### 🌐 Browser

Microsoft Edge Version 125.0.2535.85 (Official build) (64-bit)

### 🖥️ Deployment Environment

- Runtime: nodejs 22.2.0
- Database: whatever comes with a non-Docker Windows install by default
- Filesystem used to store the database on: Windows NTFS, SSD
- number of monitors: 58

**Comment by CommanderStorm** [comment]
Currently, I don't have a good answer to this. You could split them up into two channels depending on your usage, but this is likely not a good workflow.

This issue is already discussed in these issues.

- https://github.com/louislam/uptime-kuma/issues/4258
- https://github.com/louislam/uptime-kuma/issues/3750
- https://github.com/louislam/uptime-kuma/issues/1137
- https://github.com/louislam/uptime-kuma/issues/646

In some of these consensus has been reached, in some not ^^

**Comment by CommanderStorm** [comment]
Think the comment above resolves your question `Is it possible to have the group alert email body to state something along the lines of`. Forgot to close as resolved
