### ISSUE TITLE
get error when try upload a backup json

### ISSUE THREAD

**Issue by 9837i** [louislam/uptime-kuma#4834]
### ⚠️ Please verify that this question has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

I get an error message when I try to upload a json backup file
Before it went normally but now that I have more than 300 monitors I receive the following error message

> Obsolete: Since many features have been added and this backup feature has not been updated, it cannot generate or restore a full backup.
> 
> Please make a copy of the volume or folder with data(./data/) directly instead."

### 📝 Error Message(s) or Log

> Obsolete: Since many features have been added and this backup feature has not been updated, it cannot generate or restore a full backup.
> 
> Please make a copy of the volume or folder with data(./data/) directly instead."

### 🐻 Uptime-Kuma Version

1.23.13

### 💻 Operating System and Arch

linux pikapods

### 🌐 Browser

chrome

### 🖥️ Deployment Environment

- Runtime: 
- Database: 
- Filesystem used to store the database on: 
- number of monitors:

**Comment by CommanderStorm** [comment]
Idk what you are asking help for.
No such message exists in the backend => what is the actual error message?

About the message in the frontend:
We have deprecated that feature and will remove it in the v2.0 release (release is being tracked in #4500). See https://github.com/louislam/uptime-kuma/pull/3892#issuecomment-1949941292 for an explanation why we put the message in the frontend.

The following line still applies

> Please make a copy of the volume or folder with data(./data/) directly instead

**Comment by 9837i** [comment]
I would like to know if there is any other way to import the json backup, since I didn't make a backup of the "data" folder

**Comment by CommanderStorm** [comment]
Depends. What is the error message?

**Comment by 9837i** [comment]
> Depends. What is the error message?

I can normally restore a json backup with less than 300 monitors, but when it exceeds that, this message appears

"Obsolete: Since many features have been added and this backup feature has not been updated, it cannot generate or restore a full backup.

Please make a copy of the volume or folder with data(./data/) directly instead."

**Comment by CommanderStorm** [comment]
That deprecation warning in the frontend message that always appears in the frontend.
Please report the actual error message that is written to the log.

See uptime.kuma.pet:
![image](https://github.com/louislam/uptime-kuma/assets/26258709/41c37389-7745-4bdd-ac83-05bd8e3117f9)

**Comment by louislam** [comment]
As the message said, this backup feature is unmaintained.

If your json file was generated from older version, my suggestion would be to use an older version of Uptime Kuma, restore the backup, and then upgrade the Uptime Kuma to the latest version.

**Comment by CommanderStorm** [comment]
(I think the 300monitors blocking the DB and this making us fail the heal check is more likely. This is Why I am pushing for error messages)
