### ISSUE TITLE
Uptime-Kuma causing ping floods

### ISSUE THREAD

**Issue by MAMedici** [louislam/uptime-kuma#4837]
### ⚠️ Please verify that this question has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

I've had problems with uptime-kuma triggering IPS blocks due to excessive/abusive traffic.   This latest incident I was able to talk to a network engineer who sent me the logs, Looking at the logs I see my IP is pinging them almost  every  second, instead of 300s as configured in uptime-kuma for this host.

I ran a packet capture on my firewall and indeed see that uptime-kuma is flooding several hosts with unexpectedly-high ICMP traffic.

I double-checked my site and general configuration settings, and everything loose as it should.  Most of my entries are set for 5m (300s).  

Any idea what might be causing this and how to make it act as expected?  This is Uptime-Kuma 1.23.13 on docker 26.10 on  a Debian 12 container on Proxmox.  Nothing noteworthy appears in the Uptime-Kuma logs.  Firewall logs and capture attached.

### 📝 Error Message(s) or Log

[uptime-kuma ping capture.txt](https://github.com/user-attachments/files/15744821/uptime-kuma.ping.capture.txt)

### 🐻 Uptime-Kuma Version

1.23.13

### 💻 Operating System and Arch

Debian  12/Linux 6.5.13-5-pve/amd64

### 🌐 Browser

Firefox 126.0.1

### 🖥️ Deployment Environment

Runtime: Docker 26.10
Host: lxc Virtualization running Debian GNU/Linux 12 (bookworm) Linux 6.5.13-5-pve
Architecture: x86-64
Database: sqlite
Filesystem used to store the database on: 
number of monitors:

**Comment by CommanderStorm** [comment]
Cannot read the capture you send. Does somewhat look like the wrong interface was being captured, as having proxmox usually means running on a server and those usually don't run via wifi..

![image](https://github.com/louislam/uptime-kuma/assets/26258709/87dbaa60-f5ef-4305-a405-b866db2c6df6)

Have also tried looking at it in a text editor, but that looks like random data to me without an explaination
- what I would be looking at (what are the columns? What does the formatting shift indicate?)
- or where said data is coming from.

How many nodes do you have pinging away at said hosting provider with the firewall?

Btw: 1 ping/s = 1 packet/s I don't know why your provider considers this as flooding of multiple hosts. If I were a Provider, I would not worry about that.

**Comment by CommanderStorm** [comment]
Also could you link to the docs of your IPS?

I am assuming they don't outright block ICMP at 1 ping/s as
- that would be way below what would be needed (>= your avaliable bandwith) for a DDoS attack.
- If said limit wants to prevent network discoverability, you should lower it to 0/s, but I would not recommend this if you want to still have `Timeout`s, `Fragmentation`, `TTL` or `Service not Avaliable`

**Comment by CommanderStorm** [comment]
I have done a bit of digging. Here are the statistics from your capture assuming the second colllumn is the time in µs since the start.
delta s = time since the last ping of the same `ip1` and `ip2`

![image](https://github.com/louislam/uptime-kuma/assets/26258709/05518c5d-f867-4cd9-a26c-9e13441044ef)

Without additional context what you are actually doing, I don't know if anything is misbehaving

**Comment by MAMedici** [comment]
> Cannot read the capture you send. Does somewhat look like the wrong interface was being captured, as having proxmox usually means running on a server and those usually don't run via wifi..

Sorry, that was a text file that included the logs sent to me from the _hosting provider's IPS_ (top section), and copy-paste from Wireshark of the pcap from _my firewall_.  I've enclosed the pcap in the attached zip file.  
 
> How many nodes do you have pinging away at said hosting provider with the firewall?

I am pinging from one node on my end to one IP at the hosting provider.

> Btw: 1 ping/s = 1 packet/s I don't know why your provider considers this as flooding of multiple hosts. If I were a Provider, I would not worry about that.

Not flooding multiple hosts at the hosting provider.  But looking at the pcap, I can see Uptime Kuma is sending multiple pings several times to multiple hosts, at a rate of around 7-8/s.  My expectation (and desire) is that Uptime Kuma would send one ping per defined testing interval for each monitored host/ip.

[packetcapture-igb0-20240607155040.zip](https://github.com/user-attachments/files/15746272/packetcapture-igb0-20240607155040.zip)

**Comment by MAMedici** [comment]
> I have done a bit of digging. Here are the statistics from your capture assuming the second colllumn is the time in µs since the start. delta s = time since the last ping of the same `ip1` and `ip2`
> 
> ![image](https://private-user-images.githubusercontent.com/26258709/337828346-05518c5d-f867-4cd9-a26c-9e13441044ef.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc4MTcxNDYsIm5iZiI6MTcxNzgxNjg0NiwicGF0aCI6Ii8yNjI1ODcwOS8zMzc4MjgzNDYtMDU1MThjNWQtZjg2Ny00Y2Q5LWEyNmMtOWUxMzQ0MTA0NGVmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjA4VDAzMjA0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUyMTBmNzVkZWM5MDIxZGVlMGUxYjE0NWNiNzNiMjczZmI1MDFlZTVmN2M2YmFiNjYzMzdiOTcwM2NmYWNkNjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.jrmsnvgZOwr0ThhcmYb3jOfGIIGGlGMmD0QssWFS8KQ)
> 
> Without additional context what you are actually doing, I don't know if anything is misbehaving

Attached are the settings for 104.225.208.3
![firefox_bVuuSqsjJw](https://github.com/louislam/uptime-kuma/assets/121360684/892b8950-b215-4de5-8744-3212b753228a)

**Comment by CommanderStorm** [comment]
> 104.225.208.3

Assuming you mean `104.225.208.23`.
That monitor had 1 ping in the capture noted above from `74.XX.XX.XX`
See the diagram in https://github.com/louislam/uptime-kuma/issues/4837#issuecomment-2155781333

There are a few cases in which we send a retry:
- Can your host be resolved in all cases?
  If the host cannot be resolved via ipv4, we try again with ipv6 as our library does not provide an error message for this.
- Have you configured retries? If yes, how many and how often? How often are your moniors down?

In the 189 seconds of traffic that you have approximately the amount of pings that I would expect.

Could you retry this in a less noisy environment and report the results? (`docker run ...`, then pcap and report the results)
It is currently quite hard to guage if there is a problem or if this is just expected behaviour from my end..

**Comment by MAMedici** [comment]
I've temporarily removed uptime-kuma from my network as I'm working on another project atm.  I'll circle back  when I have time to devote my attention.
