### ISSUE TITLE
image update, but no new release

### ISSUE THREAD

**Issue by Zoey2936** [louislam/uptime-kuma#4840]
### ⚠️ Please verify that this question has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

some tags, like 1, latest and debian (and 1.23.11?) were updated yesterday: https://hub.docker.com/r/louislam/uptime-kuma/tags, but I can't find any changelogs. What was changed?/Why were the tags updated/why 1.23.11? I'm a bit confused

### 🐻 Uptime-Kuma Version

1.23.13

### 💻 Operating System and Arch

unrelated

### 🌐 Browser

unrelated

### 🖥️ Deployment Environment

- Runtime: Docker

**Comment by CommanderStorm** [comment]
@louislam ?

**Comment by louislam** [comment]
Ops, I pressed the wrong button yesterday, there is no update. But I need to fix the affected tags.

**Comment by louislam** [comment]
`latest`, `1`, `1-debian` and `debian` tags should be fixed.

Unfortunately, The `1.23.11` tag was overridden incorrectly, I have no idea how to recover it. I hope it won't affect many people as it is an older version tag.
