### ISSUE TITLE
Retag latest docker with previuos version 1.23.13

### ISSUE THREAD

**Issue by corasaniti** [louislam/uptime-kuma#4841]
### ⚠️ Please verify that this question has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

I noticed that you tagged the latest to an older version or are you wrong? Is there any bug?

### 🐻 Uptime-Kuma Version

1.23.13

### 💻 Operating System and Arch

Raspian OS

### 🌐 Browser

Chrome

### 🖥️ Deployment Environment

- Runtime: 
- Database: 
- Filesystem used to store the database on: 
- number of monitors:

**Comment by louislam** [comment]
I made a mistake yesterday, it rolled back to the correct image.

Repull the image if you pulled the latest tag yesterday.

See more: https://github.com/louislam/uptime-kuma/issues/4840#issuecomment-2156086153

**Comment by corasaniti** [comment]
@louislam 
Yes, I Repulled the latest image
Thank you
