### ISSUE TITLE
Can I change the prefix of onebot reply？

### ISSUE THREAD

**Issue by youyi0218** [louislam/uptime-kuma#4842]
### ⚠️ Please verify that this question has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

我I connected Uptime-Kuma to OneBot and now he replies with a prefix "UptimeKuma Alert:"just like this
![image](https://github.com/louislam/uptime-kuma/assets/135406843/e3eaedd8-b7da-4f02-b442-1c48c2c084e1)
Is there any way to remove or customize these？
I installed it with docker and uptimekuma version is 1.23.11.

### 🐻 Uptime-Kuma Version

1.23.11

### 💻 Operating System and Arch

wsl2 Ubuntu22.04.3

### 🌐 Browser

edge

### 🖥️ Deployment Environment

- Runtime: 
- Database: 
- Filesystem used to store the database on: 
- number of monitors:

**Comment by CommanderStorm** [comment]
We currently don't support adapting message templates. This is tracked in #646

If you need to change this, you can use the webhook notifications provider to add a way to interact with the notifications provider catering to your needs.
