### ISSUE TITLE
Ability to Change Root URL

### ISSUE THREAD

**Issue by Vikas-Konaparthi** [louislam/uptime-kuma#4844]
### ⚠️ Please verify that this question has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

I am currently using Uptime and would like to know that a feature that allows users to change the root URL instead of using the default "/".

Presently, the application uses "/" as the root URL, but for my use case, I need to serve the application from a different root URL path, such as "/app" or "/dashboard".

Would it be possible to implement a feature that allows users to specify a custom root URL during configuration or runtime? 

### 🐻 Uptime-Kuma Version

1.10

### 💻 Operating System and Arch

Ubuntu 20.0

### 🌐 Browser

Google Chrome

### 🖥️ Deployment Environment

- Runtime: Docker

**Comment by CommanderStorm** [comment]
This feature request is tracked in https://github.com/louislam/uptime-kuma/issues/147

=> The associated PR was found to be too buggy to merge into the v2.0 merge window given our current test coverage

Think this resolves your question
