### ISSUE TITLE
Fixing "Cannot assign requested address" errors

### ISSUE THREAD

**Issue by deviantintegral** [louislam/uptime-kuma#4845]
### ⚠️ Please verify that this question has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

I have a few ping monitors to check the general health of my internet connection. Every day or two, I have transient errors returning "Cannot assign requested address". They usually only last for a single check. I have about 30 total monitors.

I thought perhaps the app was running out of file descriptors, but increasing that didn't change anything.

Any ideas?

### 🐻 Uptime-Kuma Version

1.23.13

### 💻 Operating System and Arch

Proxmox 8.2 x64

### 🌐 Browser

N/A

### 🖥️ Deployment Environment

- Runtime: Docker 25.0.5
- Database: sqlite
- Filesystem used to store the database on: zfs
- number of monitors: 30

**Comment by CommanderStorm** [comment]
I don't have an intial guess, so lets gather more info to be on the same page.

- What is the `Error Message(s) or Log`?
- what are you monitoring precisely with the 30 ping monitors (ipv4/6, dns based or raw ip)?
- What kind of firewall, docker networks, physical network is between them?

**Comment by deviantintegral** [comment]
I did some deeper analysis of the logs, and realized I had to look >60 seconds into the past to see an additional error:

```
2024-06-11T21:29:06.659-04:00	metrics-docker	ping IPv6 error message: connect: Cannot assign requested address
2024-06-11T21:29:12.241-04:00	metrics-docker	2024-06-11T21:29:12-04:00 [MONITOR] WARN: Monitor #34 'Facebook': Failing: connect: Cannot assign requested address
2024-06-11T21:29:12.242-04:00	metrics-docker	| Interval: 60 seconds | Type: ping | Down Count: 0 | Resend Interval: 0
```

While I have IPv6 connectivity to the host, I don't have IPv6 connectivity to the docker container. Of course, my DNS server does return IPv6 addresses:

```
root@f22ecb287819:/app# nslookup facebook.com
Server:		127.0.0.11
Address:	127.0.0.11#53

Non-authoritative answer:
Name:	facebook.com
Address: 31.13.80.36
Name:	facebook.com
Address: 2a03:2880:f10e:83:face:b00c:0:25de
```

My guess is occasionally the order of the records returned is flipped, and the IPv6 comes first.

The container doesn't have an IPv6 address at all:

```
# ip a
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
31: eth0@if32: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default
    link/ether 02:42:ac:12:00:0d brd ff:ff:ff:ff:ff:ff link-netnsid 0
    inet 172.18.0.13/16 brd 172.18.255.255 scope global eth0
       valid_lft forever preferred_lft forever
```

Most consumer software will fall back to IPv4 in situations like this, which is probably why I'm not getting complaints that things are down.

Two possible ways this could be improved:

- It'd be good if the error message in the outage notification made clear what address it was trying to ping. If it showed "Facebook (<address>)" I probably would have quickly realized it was an IPv6 related issue.
- Perhaps monitors or uptime kuma itself could have a switch to control if you are monitoring IPv4, v6, or both? That looks to be covered by https://github.com/louislam/uptime-kuma/issues/1242.

**Comment by CommanderStorm** [comment]
> Most consumer software will fall back to IPv4 in situations like this, which is probably why I'm not getting complaints that things are down.

We first try to ping via ipv4 and then ipv6.
(I know not quite correct as by Happy Eyeballs, but.. 🤷🏻)

https://github.com/louislam/uptime-kuma/blob/fbf7b77cebc81707fa56cfa91ebd8f6dbaac0112/server/util-server.js#L126-L138

**Comment by CommanderStorm** [comment]
The debug message is indeed a bit misleading..

**Comment by deviantintegral** [comment]
Oh, that's interesting, So looking at that, it seems like it could be that there could be an underlying IPv4 outage first that's not being reported. IPv4 is down, it tries with IPv6 and only reports that via the address error.

**Comment by CommanderStorm** [comment]
No, the ipv4 outage is being reported.

`Cannot assign requested address` is ` e.message` => it is not retried

**Comment by deviantintegral** [comment]
I haven't been able to replicate this in the last month, so let's close this. Thanks for the feedback!

**Comment by ramazansancar** [comment]
The problem still seems to persist.

It occurs when sending IPv6 requests.

<img width="1920" height="656" alt="Image" src="https://github.com/user-attachments/assets/8a79e41d-586f-468b-9a18-ccbbec6eaeb6" />

**Comment by CommanderStorm** [comment]
Please follow the debugging steps shown in this issue and if it persists open a new issue with the steps tried and their results. This issue seems resolved.
