### ISSUE TITLE
Remove monitor warning in logs under maintenance

### ISSUE THREAD

**Issue by Lurikbolding** [louislam/uptime-kuma#4849]
### 📑 I have found these related issues/pull requests

I have not found related issues

### 🏷️ Feature Request Type

Other

### 🔖 Feature description

I have a monitor to check a service only 2h a day, so it is 22h a day on maintenance status.

But even on maintenance status, there is line of warning in log : 
2024-06-12T12:30:22+02:00 [MONITOR] WARN: Monitor #14 'NameMonitor': Under Maintenance | Type: keyword

As there is a lot theses warning line, i cannot find other useful line in log (ex : error of database, timeout of database).

### ✔️ Solution

Could we have a setting in monitor maintenance to avoid logging event.

a kind of switch in the maintenance setting : "do not log event when maintenance is on"

### ❓ Alternatives

I did not find alternative

### 📝 Additional Context

I would not have these lines id log : 

2024-06-12T12:30:22+02:00 [MONITOR] WARN: Monitor #14 'Monitor Name': Under Maintenance | Type: keyword

**Comment by CommanderStorm** [comment]
Don't think that we should add a setting for this or log this at a lower level.
Someone might be expecting a ping and not getting it otherwise.
Don't think that settings controlling how we log is a good idea. Forking the controll flow like this is not maintainable.

Please use a log aggregator like grafana Loki (or other software) to filter your logs instead

**Comment by Lurikbolding** [comment]
Ok, i understand that using grafana could help.

But as the monitor is under maintenance, why we need to ping these server?

as i understand, the monitor mode is to shut down any activity of the monitor?

**Comment by CommanderStorm** [comment]
We don't consider maintenance to be such a common occurrence => handling it as a short circuit is efficient enough for our use case. CPU impact should be minimal compared to more error prown alternatives like pausing the monitor

**Comment by Lurikbolding** [comment]
Ok, thank you for your quick answer.
