### ISSUE TITLE
[groups] More nesting and parent/child options

### ISSUE THREAD

**Issue by Reizake** [louislam/uptime-kuma#4851]
### 📑 I have found these related issues/pull requests

none i am aware of

### 🏷️ Feature Request Type

Other

### 🔖 Feature description

I would like to have the ability to have parent and child objects. 

### ✔️ Solution

for example you could have:

Firewall
|-Switch
|   |-Server
|-Switch
|-Switch

IF the firewall goes down than the switches are accepted as being down as well. that way they don't send alerts. only the parent object sends alerts

### ❓ Alternatives

you could allow for nested groups, and set primary objects for groups

### 📝 Additional Context

I am mainly interested in uptime for site monitoring. we have several firewalls and switches we want to know when they die. this seems like a great tool to monitor them in a clean simple way, but its a little less effective without parent and child objects

**Comment by CommanderStorm** [comment]
What you are refering to is tracked here instead:
- https://github.com/louislam/uptime-kuma/issues/2487
- https://github.com/louislam/uptime-kuma/issues/1089

Implementation is (as far as I see it) currently blocked by https://github.com/louislam/uptime-kuma/pull/4395 being in the https://github.com/louislam/uptime-kuma/labels/needs%3Areview stage

Closing as a duplicate
