### ISSUE TITLE
Edit the telegram notification message template

### ISSUE THREAD

**Issue by baxenko** [louislam/uptime-kuma#4852]
### ⚠️ Please verify that this question has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

How can I remove extra text when sending a message to telegram? What are some ways? Thank you. 

### 🐻 Uptime-Kuma Version

1.23.3

### 💻 Operating System and Arch

Uuntu 20.04 x86

### 🌐 Browser

Google Chrome

### 🖥️ Deployment Environment

- Runtime: 
- Database: 
- Filesystem used to store the database on: 
- number of monitors: 

![image](https://github.com/louislam/uptime-kuma/assets/36725292/5a6f4e0b-5307-46fa-9509-ea7406e12478)

**Comment by CommanderStorm** [comment]
> How can I remove extra text when sending a message to telegram?

That is currently not possible as https://github.com/louislam/uptime-kuma/issues/646 is not implemented.
I know that this is not what you want to hear, but CURRENTLY the only way is to fork the project, customise the telegram notification provider and run that version.

**Comment by CommanderStorm** [comment]
- [ ]
