### ISSUE TITLE
1.7.0 - Setup 2FA - Invalid Barcode - Google Authenticator

### ISSUE THREAD

**Issue by dbrennand** [louislam/uptime-kuma#486]
**Is it a duplicate question?**
No

**Describe the bug**
Invalid barcode error when setting up 2FA using the Google Authenticator app on IOS.

Error message: `The barcode 'REDACTED' is not a valid authentication token barcode.`

**To Reproduce**

Go to Settings > 2FA Settings > Open Google Authenticator App (IOS) > + Sign > Scan a QR code > Scan QR code from Uptime-Kuma > Error message is shown.

**Expected behavior**
The barcode is accepted and a time-based token is generated.

**Info**
Uptime Kuma Version: 1.7.0-debian
Using Docker?: Yes
Docker Version: 20.10.8
Node.js Version (Without Docker only): N/A
OS: Raspbian GNU/Linux 10 (buster)
Browser: Firefox 92.0.1

**Screenshots**
N/A

**Error Log**
N/A

Docker: `docker logs <container id>`
PM2: `~/.pm2/logs/` (e.g. `/home/ubuntu/.pm2/logs`)
N/A

**Comment by louislam** [comment]
Found related issue, it is a iOS' Google Authenticator only problem.

https://stackoverflow.com/questions/29173288/google-authenticator-on-apple-devices-certain-secrets-are-not-valid

Sometimes I am frustrated, why the Android's Google Authenticator is working and the iOS one is not working. It is so inconsistent.

**Comment by louislam** [comment]
Should be fixed, but I cannot verify it as I don't have a iOS device. 

You can try it in the next version or try nightly version now

**Comment by dbrennand** [comment]
I will test and get back to you 🙂
