### ISSUE TITLE
Webhook custom body {{msg}}

### ISSUE THREAD

**Issue by lordmofisto** [louislam/uptime-kuma#4861]
### ⚠️ Please verify that this question has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

I'm using a webhook notification (for RingCentral) and I'm using a custom body. 

I have an issue where the \n in the {{msg}} output is being rejected by RingCentral. 

All the other content I am sending works. 

Example: 

`
        {
          "type": "FactSet",
          "facts": [
            {
              "title": "Name:",
              "value": "{{monitorJSON['name']}}"
            },
            {
              "title": "Description:",
              "value": "{{monitorJSON['description']}}"
            },
            {
              "title": "Hostname:",
              "value": "{{monitorJSON['hostname']}}"
            },
            {
              "title": "Keyword:",
              "value": "{{monitorJSON['keyword']}}"
            },
            {
              "title": "Tags:",
              "value": "{{monitorJSON['tags']}}"
            }
          ]
        },`

I don't think this is a bug, it's just how RingCetnral is parsing the POST. 

If I take the {{msg}} out of the POST the message goes through no issues, but I miss the "is Up/is Down" message. 

I tried using {{heartbeatJSON['status'}}} but that is a 1 or 0, so that's not really the same from an end user readability standpoint. 

Looking for a way to deal with those "\n"'s so I can still get my nice message

### 🐻 Uptime-Kuma Version

1.23.13

### 💻 Operating System and Arch

Ubuntu Server 22.04

### 🌐 Browser

RingCentral

### 🖥️ Deployment Environment

- Runtime: 
- Database: 
- Filesystem used to store the database on: 
- number of monitors:

**Comment by CommanderStorm** [comment]
Shure this is possible. 
We have improved the docs on this one in https://github.com/louislam/uptime-kuma/pull/3636 already (Releasing said feature is blocked by #4500)

=> We support the full range of jsonata templates here.
See the [docs](https://liquidjs.com/filters/overview.html) and the [playground](https://liquidjs.com/playground.html).

If you have any other question, feel free to reach out ^^

**Comment by lordmofisto** [comment]
Perfect, that link to the Docs helped me figure out the syntax I needed to use: 

I added:

`{% assign cleaned_msg = msg | replace: '\n', '' %}`

To the top of my custom body

And

`            {
              "title": "Message:",
              "value": "{{ cleaned_msg }}"
            }`

To the section where I was using {{msg}} 


This worked for me on RingCentral. 

Thank you for the help

**Comment by lantinglou** [comment]
@lordmofisto same issue, fixed by your method.  THANK YOU.
