### ISSUE TITLE
Need help with the hostip display beneath the host name in the status page

### ISSUE THREAD

**Issue by BxtGeek** [louislam/uptime-kuma#4866]
### ⚠️ Please verify that this question has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

I created a status page, I need a suggestion and help like how I can add the clickable host ip beneath the hostname in the status page. Can someone please help
![Screenshot 2024-06-19 at 5 58 05 PM](https://github.com/louislam/uptime-kuma/assets/25264755/e5561093-63b9-4f74-8588-e7b21c06ea5a)

### 📝 Error Message(s) or Log

NA

### 🐻 Uptime-Kuma Version

 1.23.13

### 💻 Operating System and Arch

linux (inside a container)

### 🌐 Browser

chrome 

### 🖥️ Deployment Environment

- Runtime: NA
- Database: NA
- Filesystem used to store the database on: NA
- number of monitors: NA

**Comment by CommanderStorm** [comment]
Such deep customisation is currently not supported.
You can achieve it via forking the project.

You can enable clickable links via the status page items settings menu

**Comment by BxtGeek** [comment]
Thanks for sharing this
