### ISSUE TITLE
Failed to launch chromium in Ubuntu server 22.04.

### ISSUE THREAD

**Issue by asma019** [louislam/uptime-kuma#4868]
### ⚠️ Please verify that this question has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

How to fix the issue? I am installing it on my Ubuntu server. I am not using Docker. 
i am trying to install chromium using this command: `sudo apt install chromium-browser` , but not working.

What I do now?

### 📝 Error Message(s) or Log

browserType.launch: Failed to launch chromium because executable doesn't exist at chromium.

screenshot:
![Screenshot_7](https://github.com/louislam/uptime-kuma/assets/102788416/e9a5d934-47d9-43c2-907c-3f41e50c8edb)

### 🐻 Uptime-Kuma Version

1.23.13

### 💻 Operating System and Arch

Ubuntu 22.04

### 🌐 Browser

Google Chrome

### 🖥️ Deployment Environment

- Runtime: nodejs 20
- Database: N/A
- Filesystem used to store the database on:  N/A
- number of monitors: 1

**Comment by CommanderStorm** [comment]
Just so we are on the same page:
- What did you enter as a path in the settings?
- Where is chromium installed? (via `which ...`)

Without further context, my first guess is that you entered `chromium` into said field and that this relative path correct.

**Comment by asma019** [comment]
> Just so we are on the same page:
> 
> * What did you enter as a path in the settings?
> * Where is chromium installed? (via `which ...`)
> 
> Without further context, my first guess is that you entered `chromium` into said field and that this relative path correct.

Hey, I don't know how to add the path in the settings. can you guide me?
Thank you.

**Comment by CommanderStorm** [comment]
![Screenshot from 2024-06-20 15-32-34](https://github.com/louislam/uptime-kuma/assets/26258709/8b740514-8739-4b79-a496-f220efa1e49e)

This setting in the general settings

**Comment by asma019** [comment]
i am getting this issue:
![Screenshot_9](https://github.com/louislam/uptime-kuma/assets/102788416/7f8ca561-8c41-4631-bca2-eda22a01424c)

**Comment by asma019** [comment]
@CommanderStorm Hey, can you tell me how to setup Chromium in Uptime Kuma, and install it on Docker or node server?

**Comment by CommanderStorm** [comment]
Where is chromium located?
What does running `which chromium` return?

**Comment by asma019** [comment]
@CommanderStorm i don't know bro

**Comment by CommanderStorm** [comment]
Without you running the `which chromium` command, this is impossible to debug from my side, sorry.

Where snap (the package you installed is a transitional package to migrate people to `snap install chromium`) installs chromium is not simple for me to determine otherwise.

**Comment by louislam** [comment]
Even though op's replies were polite, it is still not the correct way to ask for help. You should at least try before asking and saying "I don't know".

And this question is the reason why Docker exists. I pre-configured everything you need in the Docker container.

If you think configuration is too hard for you, Installing Uptime Kuma via Docker should be the only solution for you. No other choices.

**Comment by asma019** [comment]
Ok, Thank You @louislam and @CommanderStorm
