### ISSUE TITLE
Setting up pushplus push via webhook, but not receiving pushes

### ISSUE THREAD

**Issue by mikelin8** [louislam/uptime-kuma#4870]
### ⚠️ Please verify that this question has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

As shown in the picture, after I configured this, the token is also correct

![QQ图片20240620183547](https://github.com/louislam/uptime-kuma/assets/144645914/3da472eb-4b67-450c-b025-6d34ce6c4e7e)

Clicking on test also prompts success without any errors being reported
![image](https://github.com/louislam/uptime-kuma/assets/144645914/2a8c0afa-3e36-4186-8926-ed1e9df72539)

Why am I still not getting pushes from pushplus? What's wrong with it?

### 📝 Error Message(s) or Log

![image](https://github.com/louislam/uptime-kuma/assets/144645914/4f4f9db9-3c5b-45ec-86f8-5e0cc14e9be7)
There are no error logs

### 🐻 Uptime-Kuma Version

1.23.11

### 💻 Operating System and Arch

centos 7.9.2009

### 🌐 Browser

edge

### 🖥️ Deployment Environment

- Runtime: 
- Database: 
- Filesystem used to store the database on: 
- number of monitors:

**Comment by CommanderStorm** [comment]
First of all, I translated your issue to english via deepl.com

The log you showed should not have caused a notification.
You have set retries=2 and only one retry is written into the log excerpt.

**Comment by mikelin8** [comment]
> First of all, I translated your issue to english via deepl.com
> 
> The log you showed should not have caused a notification. You have set retries=2 and only one retry is written into the log excerpt.

这些日志都是正常的日志，没有一个关于webhook的报错，目前的诉求是，我设置了推送，但是我的pushplus收不到推送

**Comment by CommanderStorm** [comment]
I don't think you are reading what I am writing as I mean it.
There is no ping that should be done based on the logs you have submitted.

=> Please submit the part of the log where you expected the notification

**Comment by crazybird** [comment]
Error log:

Error: Error: Error: getaddrinfo EAI_AGAIN www.pushplus.plus
    at Webhook.throwGeneralAxiosError (/app/server/notification-providers/notification-provider.js:38:15)
    at Webhook.send (/app/server/notification-providers/webhook.js:57:18)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Socket.<anonymous> (/app/server/server.js:1298:27)

**Comment by CommanderStorm** [comment]
@crazybird your issue is unrelated: Your issue is that your DNS Provider does not return a response for that dns entry. You will need to query fewer times or
- enable dns caching in the settings (for docker users)
- install an equivalend dns caching solution (for non-docker users)
