### ISSUE TITLE
Some TCP Monitors Fail after updateing docker-ce to 5:26.1.4-1~debian.11~bullseye

### ISSUE THREAD

**Issue by rtadams89** [louislam/uptime-kuma#4874]
### ⚠️ Please verify that this question has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

I have TCP monitors that start failing after an upgrade to docker-ce 5:26.1.4-1~debian.11~bullseye. These same monitors work fine on docker-ce 5:25.0.5-1~debian.11~bullseye and if I force a downgrade back to 5:25.0.5-1~debian.11~bullseye, the monitors start working again. Other monitor types (ping, HTTP) against the same host work without issue across versions.

From within the container, running:
/app # nc -v synology.subdomain.example.com 6690

returns:
synology.subdomain.example.com (10.20.20.10:6690) open

So it seems the port is accessible and up.

### 🐻 Uptime-Kuma Version

1.23.13

### 💻 Operating System and Arch

Debian GNU/Linux 11 (bullseye)

### 🌐 Browser

Firefox

### 🖥️ Deployment Environment

- Runtime: 26.1.4-1
- Database: embedded mariadb
- Filesystem used to store the database on: 
- number of monitors: 30

**Comment by CommanderStorm** [comment]
- embedded mariadb is not a supported database backend in the 1.X series. What version of the software are you running?
- what is logged?
- how have you deployed uptime Kuma?
- according to https://docs.docker.com/engine/release-notes/26.0/ docker is currently at v26, I am assuming this is what you mean by the version string. If you are still on v5, please update.
