### ISSUE TITLE
Go Alert Notifications Have No Data

### ISSUE THREAD

**Issue by TheCuteFoxxy** [louislam/uptime-kuma#4876]
### 📑 I have found these related issues/pull requests

None

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### Description

When a notification is sent to GoAlert, its empty. There is no monitor name or actual status provided.

### 👟 Reproduction steps

1. Setup GoAlert for notifications
2. Trigger a live (non-test) notification
3. Observe the empty alert created on GoAlert

### 👀 Expected behavior

GoAlert should be provided details, minimally which monitor triggered the alert.

### 😓 Actual Behavior

GoAlert is provided no details (or no details it can parse) resulting in a blank alert.

i.e `#14:            `

### 🐻 Uptime-Kuma Version

1.23.13

### 💻 Operating System and Arch

Ubuntu 22.04

### 🌐 Browser

Firefox 127.0.1

### 🖥️ Deployment Environment

- Runtime: Docker 26.1.4
- Database: DB Shipped with Kuma
- Filesystem used to store the database on: SSD
- number of monitors: 24

**Comment by CommanderStorm** [comment]
Not a bug. According to the goalert docs, this is not required. We should supply the summary and that should be displayed.
docs: https://goalert.me/docs/alerting/alerting-from-generic-api/

I don't have this notification provider setup => don't know how this looks.
Agree that just notifying with `msg` is likely a bit barebones.
If you'd like to have a more descriptive `details` field in said, you can provide such a change via [the way documented in our contribution guide](https://github.com/louislam/uptime-kuma/blob/master/CONTRIBUTING.md).
We require such changes to come from the community as tinkering with 100s of notification providers and making them work nicely does not scale. hope you understand ^^

**Comment by TheCuteFoxxy** [comment]
> Not a bug. According to the goalert docs, this is not required. We should supply the summary and that should be displayed. docs: https://goalert.me/docs/alerting/alerting-from-generic-api/
> 
> I don't have this notification provider setup => don't know how this looks. Agree that just notifying with `msg` is likely a bit barebones. If you'd like to have a more descriptive `details` field in said, you can provide such a change via [the way documented in our contribution guide](https://github.com/louislam/uptime-kuma/blob/master/CONTRIBUTING.md). We require such changes to come from the community as tinkering with 100s of notification providers and making them work nicely does not scale. hope you understand ^^

What we see when its sent via the API is this:
![image](https://github.com/louislam/uptime-kuma/assets/53378195/11a25ddb-acc3-44aa-95fe-02be865080a7)

Nothing seems to actually be provided to GoAlert, or at least nothing that can be parsed by it.

**Comment by CommanderStorm** [comment]
As far as I see from the screenshots on their Website, this is likely working as intended.
The `summary` is never shown in any case, other than the intial notification: https://github.com/target/goalert?tab=readme-ov-file#goalert

We don't provide `details` (this can be improved via a PR) ^^

**Comment by TheCuteFoxxy** [comment]
GoAlert may have changed perhaps, we don't get any details in the alerts
themselves either.

**Comment by CommanderStorm** [comment]
No goalert has not changed. We don't currently supply a description

**Comment by TheCuteFoxxy** [comment]
Something has clearly changed if you say its sent in the initial
notification.

Its not.

**Comment by CommanderStorm** [comment]
How does said notification look? (Your screenshot only shows the admin UI)

**Comment by TheCuteFoxxy** [comment]
We get voice notifications, when we do get them, there is nothing give
other than it saying there is a new alert.

"This is GoAlert with an alert notification. No summary provided.
[Ack/Close Options]"

Additional side note, it seems to be that the alert is only being sent to
goalert when the issue is resolved rather than when being down (we don't
have upside down turned on). Our other notifications such as email are
sending both when down and up.

**Comment by TheCuteFoxxy** [comment]
@CommanderStorm Bumping this. 

We have also confirmed the second issue (which I can create a new ticket for if needed) that alerts aren't triggering for GoAlert until it comes back up, not when it goes down. All other alerts fire when it goes down.

**Comment by CommanderStorm** [comment]
I tried to reproduce your issue but I can't.

My setup for testing is

- ```
  docker run -d -it --rm -p 8081:8081 goalert/demo
  docker run -d -it --network=host louislam/uptime-kuma:1.23.13
  ```
- <details><summary>how I set up the notification provider</summary>
  <p>
  
  ![image](https://github.com/louislam/uptime-kuma/assets/26258709/5bca933c-3a83-4991-a32d-a997644ee45e)
  
  </p>
  </details> 
- adding a monitor which does not exist
- <details><summary>result</summary>
  <p>
  
  ![image](https://github.com/louislam/uptime-kuma/assets/26258709/4e50e25d-ea1b-4b0d-8e8f-a1b6dabac7c3)
  
  </p>
  </details>

**Comment by TheCuteFoxxy** [comment]
After some more digging through other issues listed on this repo, I have found the issue. Our URL is proxied and tunneled, which means the data sent by Kuma isn't fully passed through to GoAlert.

We ended up explicitly setting the IP and port rather than the URL. On a side note, using localhost triggers an undefined "data" error.

**Comment by CommanderStorm** [comment]
I guess that resolves it.
Proxying notifications is tracked in https://github.com/louislam/uptime-kuma/issues/616 if you/somebody in the future wants to tackle this
