### ISSUE TITLE
Send alert via local USB stick

### ISSUE THREAD

**Issue by Andreik8s** [louislam/uptime-kuma#4882]
### ⚠️ Please verify that this question has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

Hi

Is there a way to send alert via a USB connected  GSM stick? I cannot see any info regarding this.

Running in Docker on AlmaLinux 8.10 
Thanks!

### 🐻 Uptime-Kuma Version

1.23.13

### 💻 Operating System and Arch

AlmaLinux 8.10

### 🌐 Browser

Safari 17.5

### 🖥️ Deployment Environment

- Runtime: 
- Database: 
- Filesystem used to store the database on: 
- number of monitors:

**Comment by Andreik8s** [comment]
There is no net on that stick, is just a GSM device. What I mean is that the stick will be identified as a device in /dev/ttyXX and the unknown is how to tell UK to use that to send the alert?

**Comment by Andreik8s** [comment]
After digging on the internet, there is a way with a bash script but UK does not have any way to refer  a path to a script in the notification section. (no script type notification). Other way can be a Webhook but a script should be also great. Maybe the next release will include this?

**Comment by CommanderStorm** [comment]
You are confusing me. Do you want to
- Send alert via a local USB stick to the internet
- Send alert about a local USB stick to the internet

If the device does not provide internet connectivity as you stated here https://github.com/louislam/uptime-kuma/issues/4882#issuecomment-2188627754, it does not make sense to route via it to access the interent.
On the other hand, you somehow want to do so in https://github.com/louislam/uptime-kuma/issues/4882#issuecomment-2188821600

I am not getting what you are trying to achieve.

**Comment by louislam** [comment]
Use `Push Monitor`.

Here are some example: https://github.com/louislam/uptime-kuma/tree/master/extra/push-examples

`bash-curl` should be suitable for you.

**Comment by minecraftchest1** [comment]
Do you mean sending a SMS message through use GSM dongle?

**Comment by Andreik8s** [comment]
Yes :).

**Comment by Andreik8s** [comment]
I found a solution using webhook, will have to test it this week sometimes.
