### ISSUE TITLE
Can I select a monitor and duplicate it so I can use all the same settings except for the site URL?

### ISSUE THREAD

**Issue by douglerner** [louislam/uptime-kuma#4883]
### ⚠️ Please verify that this question has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

I have some monitors, and they are mostly the same: checking for the same keyword, etc. I'm happy with the way they work. I want to add one more monitor and the only thing that will be different is the server URL. Is there a way I can duplicate a monitor so i can just edit the URL?

### 📝 Error Message(s) or Log

No errors.

### 🐻 Uptime-Kuma Version

latest

### 💻 Operating System and Arch

Whatever uptime kuma runs on

### 🌐 Browser

Google Chrome

### 🖥️ Deployment Environment

Run on uptime kuma.

**Comment by CommanderStorm** [comment]
You can duplicate a single monitor via the duplicate button.

Your question might also be related to:
- https://github.com/louislam/uptime-kuma/issues/1323

**Comment by douglerner** [comment]
Hmm... I don't see a duplicate button anywhere. I checked that other thread as well and while I see the duplicate button mentioned there it doesn't indicate how to fine it.

**Comment by douglerner** [comment]
I believe I stumbled across "Clone" somehow. Thanks.
