### ISSUE TITLE
Polyfill

### ISSUE THREAD

**Issue by TechnologyClassroom** [louislam/uptime-kuma#4888]
Have you seen this article about Polyfill? https://cyberinsider.com/polyfill-js-supply-chain-attack-affects-over-100000-websites/

I really appreciate Uptime Kuma.

**Comment by louislam** [comment]
https://raw.githubusercontent.com/louislam/uptime-kuma/master/package-lock.json

I don't find any `polyfill` packages in the `package-lock.json`. It should be not a problem in the current latest version.

**Comment by TechnologyClassroom** [comment]
I saw this line in the source of the dashboard and was not sure if it was relevant:

      <script nomodule crossorigin id="vite-legacy-polyfill" src="/assets/polyfills-legacy-COqB9mNb.js"></script>

**Comment by louislam** [comment]
No, `polyfill` is a general word: https://en.wikipedia.org/wiki/Polyfill_(programming)

I think the news that you had mentioned was confusing you. The attack is only related to `polyfill.io`, not `polyfill`. Just like `GitHub` is not `Git`.

Better news:
https://www.bleepingcomputer.com/news/security/polyfillio-javascript-supply-chain-attack-impacts-over-100k-sites/

**Comment by TechnologyClassroom** [comment]
Thank you for the explanation!
