### ISSUE TITLE
monitor_cert_days_remaining metrics

### ISSUE THREAD

**Issue by alekhinexxx** [louislam/uptime-kuma#4891]
### ⚠️ Please verify that this question has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

i am trying to get the monitor_cert_days_remaining metric to fetch from promenteus, but there is no such data in uptimekuma metrics nor in prometheus

### 📝 Error Message(s) or Log

![image](https://github.com/louislam/uptime-kuma/assets/145525019/48a58dc0-b690-41ef-b857-4cce4b77f87e)
![image](https://github.com/louislam/uptime-kuma/assets/145525019/b27ae2ac-d2a6-4dbe-988a-74142fb4c231)

### 🐻 Uptime-Kuma Version

Version: 1.22.1

### 💻 Operating System and Arch

Version: 1.23.12

### 🌐 Browser

brave

### 🖥️ Deployment Environment

Docker

**Comment by CommanderStorm** [comment]
Cannot reproduce on my system (runnting uptime kuma 1.23.12):
![image](https://github.com/louislam/uptime-kuma/assets/26258709/e158b8e2-6354-45c5-b778-f467a77e2892)

> [!TIP]
> The metric is not avaliable if the certificate expiry has been disabled via either of these settings on each monitor:
> ![image](https://github.com/louislam/uptime-kuma/assets/26258709/8a859165-fc32-41ec-a095-7b81d251149f)


About the version you reported: We don't support `1.22.1` anymore => please update

PS: You forgot to fill out Operating System/Arch and Deployment Environment

**Comment by alekhinexxx** [comment]
> Cannot reproduce on my system (runnting uptime kuma 1.23.12): ![image](https://private-user-images.githubusercontent.com/26258709/344429665-e158b8e2-6354-45c5-b778-f467a77e2892.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk2OTI4ODUsIm5iZiI6MTcxOTY5MjU4NSwicGF0aCI6Ii8yNjI1ODcwOS8zNDQ0Mjk2NjUtZTE1OGI4ZTItNjM1NC00NWM1LWI3NzgtZjQ2N2E3N2UyODkyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI5VDIwMjMwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBkYjc1YWY4MzM4NTBhMTgyOTM1MTFhZGIyM2UxY2YxNTMzZjUwNzExN2U0NjgzZjE1NmJjZmNiNmNiMTgyY2ImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.MQHKTUMwP0V42nkPw5e7VnWgqEKsaK83AdIBkJ74TFk)
> 
> Tip
> 
> The metric is not avaliable if the certificate expiry has been disabled via either of these settings on each monitor: ![image](https://github.com/louislam/uptime-kuma/assets/26258709/8a859165-fc32-41ec-a095-7b81d251149f)
> 
> About the version you reported: We don't support `1.22.1` anymore => please update
> 
> PS: You forgot to fill out Operating System/Arch and Deployment Environment

I've turned on the feature you mentioned, but still no data is showing up in the metrics

**Comment by CommanderStorm** [comment]
Bit lost what is different.

Just to be sure:
- The metrics page is cached for I think 1m or 5m. Did you wait before checking that metric does not exist?
- Did you hit 'Safe' at the bottom of the edit page? Our UX is a bit bad on this one imo

**Comment by alekhinexxx** [comment]
I still don't get those metric values ​​and I'm stuck here
