### ISSUE TITLE
How to change "Uptime Kuma" in dashboard and notifications?

### ISSUE THREAD

**Issue by sandyboxy** [louislam/uptime-kuma#4892]
### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)
- [X] I checked and didn't find similar issue

### 📝 Describe your problem

Hello,
I know this has been asked several times but I haven't found a solution.
Is there a way to change "Uptime Kuma" text in dashboard and in the notifications sent via Telegram, Discord, etc.?

### 🐻 Uptime-Kuma Version

1.23.13

### 💻 Operating System and Arch

Ubuntu 22.04 x64

### 🌐 Browser

Firefox 115.11.0

### 🖥️ Deployment Environment

docker image 1.23.13

**Comment by CommanderStorm** [comment]
You can fork the project and maintain your own version. The project is not intended as a white label solution => removing this from the admin dashboard is not something we will consider.

Templating notifications is something that we might do in the future if we have the engineering resources for this.
