### ISSUE TITLE
help

### ISSUE THREAD

**Issue by APIOFC** [louislam/uptime-kuma#4894]
### ⚠️ Please verify that this question has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

Can this handa only be used by 1 user?

### 🐻 Uptime-Kuma Version

latest

### 💻 Operating System and Arch

ubuntu

### 🌐 Browser

google chrom 

### 🖥️ Deployment Environment

- Runtime: 
- Database: 
- Filesystem used to store the database on: 
- number of monitors:

**Comment by CommanderStorm** [comment]
Yes, we currently allow for one user usage. See #118 for the issue tracking adding multi user auth.
