### ISSUE TITLE
Add option for expected results from a DNS query.

### ISSUE THREAD

**Issue by di-org** [louislam/uptime-kuma#4896]
### 📑 I have found these related issues/pull requests

N/A

### 🏷️ Feature Request Type

Change to existing monitor

### 🔖 Feature description

If someone were to perform a query such as "dig domain.com txt", there could be one to many results.  The current mechanism for this checks just verifies that there is a return, but does not have the ability to monitor of an expected result.  For example, if I wanted to make sure my SPF record hasn't changed, I could monitor for:

"v=spf1 include:mailserver.com ~all"

If that result doesn't match (e.g. changed, deleted), then it would alert.

### ✔️ Solution

Include a field / option to monitor for an expected result, similar as to the "HTTP(s) - Keyword".

As well, this should not just apply to TXT records.  It would be equally important for A, AAAA, MX, SOA, etc.

### ❓ Alternatives

N/A

### 📝 Additional Context

N/A

**Comment by CommanderStorm** [comment]
Checking the content of dns queries is tracked in https://github.com/louislam/uptime-kuma/issues/432 and the PR to resolve this will be https://github.com/louislam/uptime-kuma/pull/3919, but it will be a while before it gets implemented.

=> closing as a duplicate
