### ISSUE TITLE
Enhancement: Thresholds

### ISSUE THREAD

**Issue by aslmx** [louislam/uptime-kuma#49]
Thanks for this project! 
Its lean and seems to work so far!

What I'd really love to see extended is the notification functionality.

Wouldn't it be nice to have a threshold, for example for Pings, before an Alarm triggers? 

my Internet pretty much disconnects every 8-48 hours once for 1-2 minutes. 

Would be cool to tell Uptime Kuma to only send a notification if minimum X failed attempts happened.

Thanks for considering!

**Comment by Panja0** [comment]
We’ve got this covered already in https://github.com/louislam/uptime-kuma/issues/21

**Comment by aslmx** [comment]
Thanks for pointing out. Hadn't seen that when looking if it was already mentioned.
(working in QA, my experience is to address each thing in a single ticket/defect/issue, so it is easier to later resolve them one by one, instead of having one mutating issue which never gets closed ;-) - just a suggestion though).

**Comment by Panja0** [comment]
I get what you mean! Makes sense. 
I’ll leave it up to the dev which way he prefers. 

Cheers!

**Comment by louislam** [comment]
> Thanks for pointing out. Hadn't seen that when looking if it was already mentioned.
> (working in QA, my experience is to address each thing in a single ticket/defect/issue, so it is easier to later resolve them one by one, instead of having one mutating issue which never gets closed ;-) - just a suggestion though).

Agree with this, I actually added version number in the frontend which mentioned in #21, but it is hard to mark as resolved.

**Comment by Panja0** [comment]
@louislam 
Ok I understand. What do you suggest?
I can create tickets for all individual request or I can edit my post when something has been resolved. What works best for you?!

**Comment by louislam** [comment]
> @louislam
> Ok I understand. What do you suggest?
> I can create tickets for all individual request or I can edit my post when something has been resolved. What works best for you?!

![image](https://user-images.githubusercontent.com/1336778/125811679-3977f994-08d2-4b6b-b8b3-2b8fd83838cc.png)

I just discovered that github provides checkbox syntax. Maybe you can prepend a checkbox for each request, so that I can mark as resolved.

**Comment by Panja0** [comment]
@louislam done!

**Comment by louislam** [comment]
Implemented in 1.0.7
