### ISSUE TITLE
Are China users unable to pull Uptime Kuma Docker image now?

### ISSUE THREAD

**Issue by louislam** [louislam/uptime-kuma#4902]
### ⚠️ Please verify that this question has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

I heard Docker Hub was banned in China last month.

I would like to know if I can publish the official images of Uptime Kuma legally somewhere in China, so that you guys can download Uptime Kuma without "climbing over the wall".

### 🐻 Uptime-Kuma Version

Docker

### 💻 Operating System and Arch

ANY

### 🌐 Browser

N/A

### 🖥️ Deployment Environment

N/A

**Comment by binaryYuki** [comment]
Hi @louislam,

Currently, Docker Hub is no longer available in China. 

The best way to avoid this is by using private registries. 

Personally, I am using Azure Container Registry (azurecr), which is in the always free tier (100GB, 10 webhooks). I am quite satisfied with the speed, as I deploy it in the UK.
<img width="589" alt="截屏2024-07-04 10 04 00" src="https://github.com/louislam/uptime-kuma/assets/60097976/05b2b141-49ef-4f49-8cd7-115b165ee8a5"> (I am quite satisfied with the speed, as I deploy it in the UK)

Also there are other providers inside China.
- Aliyun (But they gradually limit the number of concurrent uploads or downloads at the user level on the personal edition)
- Tencent Cloud (ID verify required)

Hope this helps.

**Comment by binaryYuki** [comment]
![image](https://github.com/louislam/uptime-kuma/assets/60097976/a405c804-e3de-443b-a65f-ba2b2fc71d00)
This is a screenshot while I am trying to pull louislam/uptime-kuma:1 without any "technique".
The command line will stuck here till timeout

**Comment by louislam** [comment]
> Hi @louislam,
> 
> Currently, Docker Hub is no longer available in China.
> 
> The best way to avoid this is by using private registries.
> 
> Personally, I am using Azure Container Registry (azurecr), which is in the always free tier (100GB, 10 webhooks). I am quite satisfied with the speed, as I deploy it in the UK. <img alt="截屏2024-07-04 10 04 00" width="589" src="https://private-user-images.githubusercontent.com/60097976/345673359-05b2b141-49ef-4f49-8cd7-115b165ee8a5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA3NTczMTMsIm5iZiI6MTcyMDc1NzAxMywicGF0aCI6Ii82MDA5Nzk3Ni8zNDU2NzMzNTktMDViMmIxNDEtNDllZi00ZjQ5LThjZDctMTE1YjE2NWVlOGE1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzEyVDA0MDMzM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk1Nzc3OTBhNzM5NjIzNjBiYWEwMGFkMmU5NzIyNWU5MTBiYmZhNjMxZTdhNTFlY2QzNWZhNzcxM2MyNTc5YjYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ZcEMjphGIZY3n8nTnw7cLvUD14zP9Ev3oGl5vNeq8_o"> (I am quite satisfied with the speed, as I deploy it in the UK)
> 
> Also there are other providers inside China.
> 
>     * Aliyun (But they gradually limit the number of concurrent uploads or downloads at the user level on the personal edition)
> 
>     * Tencent Cloud (ID verify required)
> 
> 
> Hope this helps.

Thanks for the suggestion. Unfortunately, 100GB bandwidth is not enough, and the bandwidth cost is expensive for this project.

But good to know that Azure is providing Docker registry.

**Comment by alexislefebvre** [comment]
Would using the GitHub's registry avoid this issue? See:

- https://docs.github.com/packages/working-with-a-github-packages-registry/working-with-the-container-registry
- https://github.com/docker/build-push-action

**Comment by alexislefebvre** [comment]
Actually there already is a PR about GHCR:

- #213

**Comment by CommanderStorm** [comment]
Given that no user from china has commented on this issue, I think they have settled/resolved this for themselves and are using one of the proxy options avalible. 🤷🏻‍♂️
Since none of them have commented if ghcr.io is affected too, I am assuming this either does not matter or there is no need for this => closing as resolved

If I misinterpreted things, we can reopen ^^
