### ISSUE TITLE
Dashboard notification dismissal

### ISSUE THREAD

**Issue by TechnologyClassroom** [louislam/uptime-kuma#4903]
### 📑 I have found these related issues/pull requests

I could not find any related issues using the `is:issue notification` filter.

### 🏷️ Feature Request Type

Dashboard

### 🔖 Feature description

I leave the admin dashboard open most of the time and it helps me visually notice when something is down. When I see a red number in the tab, I often will see a full screen of flapped service notifications starting at the bottom-right corner of the screen. Many of them are not relevant anymore. I can click on them to dismiss them or refresh the page to start with a clean slate.

### ✔️ Solution

My first thought would be a "dismiss all" button of some sort that appears in the bottom-right when there are notifications. Instead of requiring n number of clicks for n number of notifications, this would require one click. The button could go away when there are no notifications.

### ❓ Alternatives

Another method to reduce the amount of notifications that would be needed to dismiss would be to automatically dismiss opposite pairs of notifications. If a service comes up, the down notification could be dismissed and vice versa. Then the user would only be presented with notifications of what is currently incorrect at this moment. Previous events would still be visually apparent with the red and green ovals and reduction in percentage.

### 📝 Additional Context

I recently started using Uptime Kuma and I really appreciate everything that you do.

**Comment by CommanderStorm** [comment]
A toast auto dismissal setting and the button that you are requesting was added in https://github.com/louislam/uptime-kuma/pull/3441
Said PR is waiting to be released in the `v2.0`-release. See #4500 for further details.

Dismissing oposite pairs is included in that if you set the toast timeout to be the monitoring period.
It is likely better better to show those events both as this way a user can get a less misleading insight into the state of the system => that it went down and then came back up.

Think this resolves your FR.

**Comment by TechnologyClassroom** [comment]
Wow! That's great. Thank you!
