### ISSUE TITLE
Certificate Expiry not shown on status page

### ISSUE THREAD

**Issue by sreu94** [louislam/uptime-kuma#4904]
### ⚠️ Please verify that this question has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

I am trying to monitor internal certificates, which is working in the dashboard.
However if I try to add the monitors to a status page the days until expiry are not shown.
Am I doing anything wring or is there a bug?
![image](https://github.com/louislam/uptime-kuma/assets/138495848/91e3efcc-0a0e-45ae-881c-69f194ca105d)
![image](https://github.com/louislam/uptime-kuma/assets/138495848/3f25cebb-ab33-4620-82fc-263a9698f23e)
![image](https://github.com/louislam/uptime-kuma/assets/138495848/c484e6f2-e212-4614-abea-7031d994c917)

### 📝 Error Message(s) or Log

None

### 🐻 Uptime-Kuma Version

1.23.13

### 💻 Operating System and Arch

Ubuntu 20.04 x64

### 🌐 Browser

Edge Version 126.0.2592.81 (Offizielles Build) (64-Bit)

### 🖥️ Deployment Environment

- Runtime: Docker 24.0.5
- Database: sqlite
- Filesystem used to store the database on: ext4
- number of monitors: 113

**Comment by sreu94** [comment]
So does anyone have the same issue and can relate or is it just me?

**Comment by CommanderStorm** [comment]
@sreu94 
Sorry, the issue likely slipped through the cracks.
internal certificates are likely self signed => they are currently not displayed  correctly
(This is also noted in another issue, but I am on GitHub mobile => cannot search for it)

As noted in the other issue: PRa welcome

**Comment by CommanderStorm** [comment]
@sreu94 
Sorry, the issue likely slipped through the cracks.
internal certificates are likely self signed => they are currently not displayed  correctly
(This is also noted in another issue, but I am on GitHub mobile => cannot search for it)

As noted in the other issue: PRa welcome

**Comment by CommanderStorm** [comment]
Closing as a duplicate
