### ISSUE TITLE
Uptime Kuma Cloud

### ISSUE THREAD

**Issue by AkarinLiu** [louislam/uptime-kuma#4905]
### 📑 I have found these related issues/pull requests

N/A

### 🏷️ Feature Request Type

Other

### 🔖 Feature description

I think is time to press Uptime Kuma Cloud

### ✔️ Solution

Using multi-user mode to allow create Status pages

### ❓ Alternatives

Serverless

**Comment by CommanderStorm** [comment]
multi user functionality is tracked here https://github.com/louislam/uptime-kuma/issues/128
Closing as a duplicate
