### ISSUE TITLE
HTTPS monitoring is normal, but the dashboard does not display curve data.

### ISSUE THREAD

**Issue by niubaoxing** [louislam/uptime-kuma#4907]
### ⚠️ Please verify that this question has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

HTTPS monitoring is normal, but the dashboard does not display curve data.

### 📝 Error Message(s) or Log

![1](https://github.com/louislam/uptime-kuma/assets/52197779/b8861774-288e-42a2-9492-971eb1f17235)

### 🐻 Uptime-Kuma Version

版本: 1.23.13

### 💻 Operating System and Arch

centos7.9

### 🌐 Browser

chrome 126.0.6478.127

### 🖥️ Deployment Environment

- Runtime:  Docker version 26.1.4, build 5650f9b
- Database: 
- Filesystem used to store the database on: 
- number of monitors:

**Comment by pprazzi99** [comment]
Might be stupid but did you try different web browser?
