### ISSUE TITLE
'SQLITE_CORRUPT'

### ISSUE THREAD

**Issue by diegoavitorino** [louislam/uptime-kuma#4909]
### 📑 I have found these related issues/pull requests

N/a

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### Description

   at Timeout.safeBeat [as _onTimeout] (/app/server/model/monitor.js:1034:25)
2024-07-05T10:19:15-03:00 [MONITOR] ERROR: Please report to https://github.com/louislam/uptime-kuma/issues
2024-07-05T10:19:15-03:00 [MONITOR] INFO: Try to restart the monitor
Trace: [Error: insert into `heartbeat` (`down_count`, `duration`, `important`, `monitor_id`, `msg`, `ping`, `status`, `time`) values (0, 21, false, 40, '200 - OK', 106, 1, '2024-07-05 13:19:14.170') - SQLITE_CORRUPT: database disk image is malformed] {
  errno: 11,
  code: 'SQLITE_CORRUPT'

### 👟 Reproduction steps

at Timeout.safeBeat [as _onTimeout] (/app/server/model/monitor.js:1034:25)
2024-07-05T10:19:15-03:00 [MONITOR] ERROR: Please report to https://github.com/louislam/uptime-kuma/issues
2024-07-05T10:19:15-03:00 [MONITOR] INFO: Try to restart the monitor
Trace: [Error: insert into `heartbeat` (`down_count`, `duration`, `important`, `monitor_id`, `msg`, `ping`, `status`, `time`) values (0, 21, false, 40, '200 - OK', 106, 1, '2024-07-05 13:19:14.170') - SQLITE_CORRUPT: database disk image is malformed] {
  errno: 11,
  code: 'SQLITE_CORRUPT'

### 👀 Expected behavior

'SQLITE_CORRUPT'

### 😓 Actual Behavior

Uptime error log

### 🐻 Uptime-Kuma Version

1.23.13

### 💻 Operating System and Arch

Kubernetes

### 🌐 Browser

Google Chrome

### 🖥️ Deployment Environment

- Runtime: 
- Database: 
- Filesystem used to store the database on: 
- number of monitors:

**Comment by CommanderStorm** [comment]
How did you deploy to kubernetes?
What is the file system you use? (NFS is not compatible with SQLite3 due to bad locking)

There are a lot of issues that we already answered. Have you looked through the existing issues?
For example https://github.com/louislam/uptime-kuma/issues/998 deployed with concurrent pods which is unsupported.

**Comment by basrieter** [comment]
We had the same issue while hosting it on Azure. The Azure persistent folder is a CIFS file share and that seem to cause corruption.
