### ISSUE TITLE
Created Incident message incorrect Timezone bug

### ISSUE THREAD

**Issue by mariushosting** [louislam/uptime-kuma#491]
**Is it a duplicate question?**
NO

**Describe the bug**
Created incident message on the Status Page does not show the right time for my Timezone even though the Timezone is set up correctly in my admin dashboard.

**Info**
Uptime Kuma Version: 1.7.0
Using Docker?: Yes
Docker Version: 20.10.3
Browser: Chrome Latest

**Screenshots**
![htimezone correct](https://user-images.githubusercontent.com/37554361/134824464-c8b8552f-d537-4b86-9c6d-b425e2e1d19b.png)
![aerror1](https://user-images.githubusercontent.com/37554361/134824465-decf23fc-6e3b-4484-859e-86b6eb61e9e3.png)

**Comment by chakflying** [comment]
If you're asking me, the frontend should always just use browser timezone anyway. We can then have the setting for notification rendering etc., things that doesn't have a browser context.

**Comment by Saibamen** [comment]
PR: https://github.com/louislam/uptime-kuma/pull/501
