### ISSUE TITLE
Prefer IPv6 if available

### ISSUE THREAD

**Issue by deavmi** [louislam/uptime-kuma#4914]
### 📑 I have found these related issues/pull requests

Not related

### 🏷️ Feature Request Type

Deployment

### 🔖 Feature description

Allow for IPv6 usage for things like the notifications. For example ntfy.sh is reachable over IPv6 (I am using DNS64 so a valid AAAA record is returned) however my container's IPv4 is not routable because I run IPv6 only, but that means that it (your app) should then try IPv6 records

### ✔️ Solution

Mentioned above

### ❓ Alternatives

No

**Comment by deavmi** [comment]
What I _really_ want is, if I insert a hostname for an HTTP/TCP or whatever check, let me specify that I want to test against the IP resolved via either A or AAAA record.

**Comment by CommanderStorm** [comment]
V2.0 will ship with a newer version of nodejs. See #4500 for what is currently blocking said release.
Given that newer versions of node have implemented happy eyeballs V2, I don't think this is an issue any more.
=> Going to close that part of the issue as likely resolved. (I have not verified nodes implementation, but if they claim to be spec compliant, that is likely enough)

Selecting the IP family is not possible in current versions of nodejs. See https://github.com/louislam/uptime-kuma/issues/1242 for a ore in-depth discussion.
=> Let's not open a duplicate on that one

**Comment by deavmi** [comment]
> V2.0 will ship with a newer version of nodejs. See #4500 for what is currently blocking said release. Given that newer versions of node have implemented happy eyeballs V2, I don't think this is an issue any more. => Going to close that part of the issue as likely resolved. (I have not verified nodes implementation, but if they claim to be spec compliant, that is likely enough)
> 
> Selecting the IP family is not possible in current versions of nodejs. See #1242 for a ore in-depth discussion. => Let's not open a duplicate on that one

Happy Eve-ballin will be fine then, dankie! Much appreciated
