### ISSUE TITLE
Logrotate on `error.log`

### ISSUE THREAD

**Issue by Gill-Bates** [louislam/uptime-kuma#4917]
### 📑 I have found these related issues/pull requests

x

### 🏷️ Feature Request Type

Maintenance

### 🔖 Feature description

I have noticed that the `error.log` becomes huge over time (here you can already see over 1 GB). Wouldn't a log rotate or automatic housekeeping make sense?

![WinSCP_ve8sTfRlXG](https://github.com/louislam/uptime-kuma/assets/25774289/48f72dfa-4d2c-4a61-9b27-2d4e05fceb97)

### ✔️ Solution

Implementing a Housekeeping

**Comment by CommanderStorm** [comment]
all our supported platforms already do that.
I don't think there is anything left to do.
- docker logrotation is [a runtime option](https://docs.docker.com/config/containers/logging/configure/)
- native via `pm2-logrotate`
