### ISSUE TITLE
Badge status N/A

### ISSUE THREAD

**Issue by marciorsrodrigues** [louislam/uptime-kuma#4918]
### ⚠️ Please verify that this question has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

Everything is working with the previous monitors, but now the badges for the new ones all show as N/A instead of UP, DOWN, etc.
Anyone can help me?

![image](https://github.com/louislam/uptime-kuma/assets/141336589/a7706ce5-9060-4e60-b99d-a780e3c9be06)
![image](https://github.com/louislam/uptime-kuma/assets/141336589/c54d5af0-8806-4091-a941-b3dd0ae32f15)

### 🐻 Uptime-Kuma Version

1.23.13

### 💻 Operating System and Arch

Ubuntu 20

### 🌐 Browser

Google Chrome

### 🖥️ Deployment Environment

- Runtime: nodejs
- Database: sqlite
- Filesystem used to store the database on: VM
- number of monitors: 543

**Comment by marciorsrodrigues** [comment]
Im checking the logs and i have:
![image](https://github.com/louislam/uptime-kuma/assets/141336589/942c824e-8335-47c5-a46a-7f2c6e236d41)

**Comment by CommanderStorm** [comment]
Did you click "safe" on the status page after adding the monitor to it? Without that, you will likely see `N/A`

**Comment by marciorsrodrigues** [comment]
@CommanderStorm :) you right.
The monitor need to be in a Status page or the status will be N/A.
