### ISSUE TITLE
API from external PHP application

### ISSUE THREAD

**Issue by assistenzakauky** [louislam/uptime-kuma#4920]
### ⚠️ Please verify that this question has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

Hi,
If I need to read or write data to Kuma from an external application in PHP what can I do?

Thanks

### 🐻 Uptime-Kuma Version

1.23.13

### 💻 Operating System and Arch

Ubuntu 24

### 🌐 Browser

Google Chrome

### 🖥️ Deployment Environment

Runtime: Laravel
Database: SQL
Filesystem used to store the database on: SSD
number of monitors: 100

**Comment by CommanderStorm** [comment]
We currently don't have an [official, stable api.](https://github.com/louislam/uptime-kuma/issues/118) Our plan to do so is https://github.com/louislam/uptime-kuma/pull/3854.

Please see these issues for your options:
- https://github.com/louislam/uptime-kuma/issues/4308
- https://github.com/louislam/uptime-kuma/issues/118
