### ISSUE TITLE
Logging config

### ISSUE THREAD

**Issue by deavmi** [louislam/uptime-kuma#4921]
### ⚠️ Please verify that this question has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

I want to know if there is a way to disable logging. I do frequent (20s) interval checks and don't want all the logs.

### 🐻 Uptime-Kuma Version

Latest

### 💻 Operating System and Arch

Ubuntu

### 🌐 Browser

Chrome

### 🖥️ Deployment Environment

- Runtime: 
- Database: 
- Filesystem used to store the database on: 
- number of monitors:

**Comment by CommanderStorm** [comment]
Think this answers your question:
https://github.com/louislam/uptime-kuma/issues/1072

> if you want an easy fix just add the environment variable to the docker
> 
> ```env
> UPTIME_KUMA_HIDE_LOG=debug_monitor,info_monitor
> ```
> 
> This disables the INFO log for the Successful Response
