### ISSUE TITLE
Microsoft Teams workflows

### ISSUE THREAD

**Issue by Denvek** [louislam/uptime-kuma#4922]
### 📑 I have found these related issues/pull requests

I could not find any other issues specifically relating to Microsoft Teams Workflows.

### 🏷️ Feature Request Type

Change to existing notification-provider

### 🔖 Feature description

Microsoft are deprecating O365 connectors https://devblogs.microsoft.com/microsoft365dev/retirement-of-office-365-connectors-within-microsoft-teams/ and asking everyone to move to workflows instead. Setting up a workflow in my Teams and then switching the webhook URL in Uptime Kuma to the new workflow one does not work - Kuma says a test was sent successfully but Teams says the workflow failed.

### ✔️ Solution

An update to the Microsoft Teams notification functionality to allow users to switch to using workflow webhooks.

### 📝 Additional Context

New O365 connectors using the existing method will not be able to be created after August 15th 2024. Existing connectors will stop working after October 1st 2024

**Comment by A-Matt** [comment]
Just about to open a ticket regarding the same thing 🤣
The full flow:
![image](https://github.com/louislam/uptime-kuma/assets/47449129/fdeb055d-a33a-43a5-b4a0-e1f41af26f53)

The Error from Power Automate is:
![image](https://github.com/louislam/uptime-kuma/assets/47449129/b5cc5e91-54a1-480d-ba88-29d56c617e6b)

**Comment by A-Matt** [comment]
This may already be fixed via this https://github.com/louislam/uptime-kuma/pull/4538

**Comment by Denvek** [comment]
I've updated the original post to explicitly include the dates from the Microsoft announcement. It looks to me like #4538 does fix this, but this needs to be released preferably before August 15th, and before October 1st at the latest.

**Comment by Stuart-harper** [comment]
Do we Know if there is any way to get the old way working if there isnt been an update to this?

**Comment by Reftek85** [comment]
I have the same issues,
as Microsoft is deprecating direct teams connector and force us to use PowerAutomate.
the automation reports this error
L'action « Send_each_adaptive_card » a échoué: The execution of template action 'Send_each_adaptive_card' failed: the result of the evaluation of 'foreach' expression '@triggerOutputs()?['body']?['attachments']' is of type 'Null'. The result must be a valid array.

would be nice to have the https://github.com/louislam/uptime-kuma/pull/4538 fix without having to wait till V2.0 release who know when.

**Comment by cvsickle** [comment]
For anyone here looking for a temporary solution for sending Uptime notifications to a Teams channel, you can setup an email notification. Each Teams channel can have an email address created for it, by right clicking the channel and selecting "Get email address."

As long as the setting "Anyone can send emails to this address" is selected, you can create an SMTP Email notification in Uptime Kuma to post to that channel.

This solution isn't ideal, as the notifications come formatted like an email address, but it is a workable solution if we get to the point where we can no longer create Incoming Webhook connectors before the update to Uptime Kuma has been released.

**Comment by CommanderStorm** [comment]
resolved in https://github.com/louislam/uptime-kuma/releases/tag/2.0.0-beta.0

**Comment by A-Matt** [comment]
Considering this is not a stable release, nor accessible for all types of users (only possible via docker).
This feels a little early to be closing this issue as being fixed. 😅

**Comment by CommanderStorm** [comment]
> Considering this is not a stable release [..] feels a little early to be closing this issue as being fixed

All other issues (such as switching the tag in the [update guide](https://github.com/louislam/uptime-kuma/wiki/%F0%9F%86%99-How-to-Update#--non-docker)) are unrelated to this issue
=> I am going to stick to my decision of close as resolved

**Comment by chusiang** [comment]
The "Microsoft Teams"  notification is working for workflow on docker image of `louislam/uptime-kuma:2.0.0-beta.3`.

<img width="564" height="679" alt="Image" src="https://github.com/user-attachments/assets/1acccd32-22cb-4112-a747-d68c2e75914a" />

> REF: #4538

Thank you. <[_ _]>
