### ISSUE TITLE
Info about the API

### ISSUE THREAD

**Issue by KevinKrueger** [louislam/uptime-kuma#4925]
### ⚠️ Please verify that this question has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

I would like to do something with the API, but I can't find more details anywhere. Except for API keys, which doesn't help me. I would like to test with Postman.

### 📝 Error Message(s) or Log

-

### 🐻 Uptime-Kuma Version

Current

### 💻 Operating System and Arch

Docker

### 🌐 Browser

Chrome

### 🖥️ Deployment Environment

Docker

**Comment by CommanderStorm** [comment]
We currently don't have an [official, stable api.](https://github.com/louislam/uptime-kuma/issues/118) Our plan to do so is https://github.com/louislam/uptime-kuma/pull/3854.

Please see these issues for your options:
- https://github.com/louislam/uptime-kuma/issues/4308
- https://github.com/louislam/uptime-kuma/issues/118
