### ISSUE TITLE
How to set up mTLS HTTP probes?

### ISSUE THREAD

**Issue by cdelanchy** [louislam/uptime-kuma#4927]
### ⚠️ Please verify that this question has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

I want to set up an HTTP probe that send an XML and check if the response is OK.

But, this exchange must use mutual TLS authentication.

There is a possibility in the menu to add the certificate, the key and the CA cert, but I can't find any information about the wanted format in the form (0 info in the Wiki about this feature).

Does the information below seems OK? Or is the wanted format is different? (because I have an SSL error)
And for the CA, I don't know what to fill in the form.

![image](https://github.com/louislam/uptime-kuma/assets/73339648/523072e5-c3f7-4496-bd5e-7d6012203f41)

Thank your for your help.

### 🐻 Uptime-Kuma Version

1.23.13

### 💻 Operating System and Arch

Ubuntu 22.04 LTS

### 🌐 Browser

Firefox 127

### 🖥️ Deployment Environment

- Runtime: Docker
- Database: 
- Filesystem used to store the database on: 
- number of monitors:

**Comment by CommanderStorm** [comment]
Is your private key decrypted?
https://github.com/louislam/uptime-kuma/pull/2531#issuecomment-1466367710

**Comment by cdelanchy** [comment]
Yes, it is.

I think the problem may be more focused on the CA cert. Does it need the whole chain? In which format?

**Comment by CommanderStorm** [comment]
I think the format is shown here https://github.com/louislam/uptime-kuma/pull/2531#issuecomment-1466367710. Does that work?

CC @doubles-ss

**Comment by doubles-ss** [comment]
@cdelanchy If CA not necessary you can omit it.
About format you should try pkcs8.

**Comment by cdelanchy** [comment]
CA is mandatory.

Thank you all for your answers: I put the CA chain in the CA form part with the format "----BEGIN CERTIFICATE--- blabla". Everything is working fine! So thanks a lot!

If I may suggest putting part of the issue details you provided to me in the Wiki would help other people? (Or I may be the only one stupid :P)

**Comment by CommanderStorm** [comment]
> If I may suggest [documenting this] part of the issue [..] would help other people

PRs appreciated.
The code for this is locaged her

https://github.com/louislam/uptime-kuma/blob/1a5a1a6e5d019b3dc58d114327f6765da0bee5f5/src/pages/EditMonitor.vue#L784

Our contribution guide is here: https://github.com/louislam/uptime-kuma/blob/1a5a1a6e5d019b3dc58d114327f6765da0bee5f5/CONTRIBUTING.md

**Comment by cdelanchy** [comment]
Thank you, I'll try to do this in August.
