### ISSUE TITLE
NOC view

### ISSUE THREAD

**Issue by ct-mbaumann** [louislam/uptime-kuma#4932]
### 📑 I have found these related issues/pull requests

None

### 🏷️ Feature Request Type

Status-page

### 🔖 Feature description

If you have many (100's or 1000's) of monitors it is hard to have a good overview of uptime even with groups. I would like to have a NOC view which basically tiles, or filtered by groups/tags all monitors and shows a green/yellow/red  square. Each tile should be clickable to the respective monitor.

### ✔️ Solution

Provide a new NOC view similar to what site like site24x7 provide
![Screenshot 2024-07-11 at 5 05 46 PM](https://github.com/user-attachments/assets/9403bf7e-1b68-4181-ab7e-310aa6508ecc)

**Comment by CommanderStorm** [comment]
Multi-collumn status pages are tracked in https://github.com/louislam/uptime-kuma/issues/592.

I don't think having a resisable and modular status page is something that we can allow in-scope. We are simple and being so modular is not simple.
=> closing as out of scope/ https://github.com/louislam/uptime-kuma/labels/wontfix

> [!NOTE]
> When you are looking for this level of customisability, you are likely looking for [grafana](https://grafana.com/) instead.

> [!TIP]
> We offer a pre-configured grafana dashboard which you can use and configure to your likings.
> See the **AWSOME** work which `@MrDrache333` as contributed in https://github.com/louislam/uptime-kuma/pull/4680:
> ![uptime-kuma-dashboard](https://github.com/louislam/uptime-kuma/assets/22854641/4b7df766-0c7f-4442-9307-c84f25ea297c)
> We have documented how to set up metrics via grafana in https://github.com/louislam/uptime-kuma/wiki/Prometheus-Integration
