### ISSUE TITLE
"Does the uptime monitoring of port speed and status test the communication network of the target machine from the currently deployed machine?"

### ISSUE THREAD

**Issue by usawjq** [louislam/uptime-kuma#4933]
### ⚠️ Please verify that this question has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

"Does the uptime monitoring of port speed and status test the communication network of the target machine from the currently deployed machine?"

### 🐻 Uptime-Kuma Version

latest

### 💻 Operating System and Arch

	 Ubuntu Server 22.04 LTS 64bit

### 🌐 Browser

google

### 🖥️ Deployment Environment

docker

**Comment by alexislefebvre** [comment]
What does “communication network” mean?

What type of monitor do you use? TCP port?
