### ISSUE TITLE
How to edit multiple monitors at once

### ISSUE THREAD

**Issue by santosh** [louislam/uptime-kuma#4941]
### ⚠️ Please verify that this question has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

How to edit multiple monitors at once?

I want to update Heartbeat Interval of multiple services. I have around 18 services. A manual edit is doable. But I'm wondering if there any GUI method or API to achieve this. 

### 🐻 Uptime-Kuma Version

1.23.13

### 💻 Operating System and Arch

Debian 12

### 🌐 Browser

Firefox 127.0.2

### 🖥️ Deployment Environment

- Runtime: Docker
- Database: sqlite (most probably as I didn't configure any database)
- Filesystem used to store the database on: ext4 on SSD (proxmox running debian)
- number of monitors: 18

**Comment by CommanderStorm** [comment]
We currently don't have a bulk edit functionality:
- #455
- #118

=> consider using third party tooling like https://uptime-kuma-api.readthedocs.io/ or similar.

If you want to contribute bulk-editing, our [contribution guide is here](https://github.com/louislam/uptime-kuma/blob/1a5a1a6e5d019b3dc58d114327f6765da0bee5f5/CONTRIBUTING.md).

**Comment by santosh** [comment]
Updating database directly was more feasible in my homelab environment.
