### ISSUE TITLE
Working API 

### ISSUE THREAD

**Issue by W01v3n** [louislam/uptime-kuma#4946]
### 📑 I have found these related issues/pull requests

Didn't find anything about that.

### 🏷️ Feature Request Type

API / automation options

### 🔖 Feature description

Hey,

I tried to work with the 3rd party API wrappers, couldn't make it work with either of them.
As of now I'm trying to add a new monitor in a monitor group, first listing all monitor groups to get the right one for the add function. My current use case is creating monitors of kind "Push". As far as I saw, that's not an option right now.

Plus, the 3rd party ones want to use username and password, while I feel it redundant if I have an API key.

### ✔️ Solution

I want to list monitor groups and their IDs via the API.
I want to be able to add monitors of kind "Push" under specific monitor groups via the API, and also get their URL in reponse.

### ❓ Alternatives

A CLI utility that can work with my specific server using an API key or something similar (just not my main username and password) and is able to do what I need.

**Comment by CommanderStorm** [comment]
Please see #118 for the current status.
Closing as a duplicate
