### ISSUE TITLE
Cannot connect to the socket server error

### ISSUE THREAD

**Issue by dustyhansen** [louislam/uptime-kuma#4947]
### ⚠️ Please verify that this question has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

I keep getting an error message where all of my monitors show as down and the CPU on my VPS skyrockets over 100% and the only way to resolve is to restart the machine. It shows the error message on top of the browser when it happens. This happens once or twice daily. 

### 📝 Error Message(s) or Log

![Screenshot 2024-07-17 065621](https://github.com/user-attachments/assets/29c9847f-4ff9-4502-80df-11c8be8e229f)

### 🐻 Uptime-Kuma Version

1.23.13

### 💻 Operating System and Arch

Ubuntu 22.04.4

### 🌐 Browser

Any

### 🖥️ Deployment Environment

- Runtime: Docker 27.0.3
- Database: sqlite
- Filesystem used to store the database on: 
- number of monitors: 17

**Comment by CommanderStorm** [comment]
Could you report the Servers Log?
Also please report
- the filesystem you use to store the database,
- the amount of retention configured and
- what type your monitors are.

**Comment by dustyhansen** [comment]
Where do I find the log?
How do I tell what filesystem I am using?
180 days
HTTPS Browser Engine, Steam Game Server, GameDig, TCP Port, and HTTP(s)

**Comment by CommanderStorm** [comment]
> Where do I find the log?

use `docker ps` to find the id and then use `docker logs <ID>` to get the logs for said monitor.
Here are the docs: https://docs.docker.com/reference/cli/docker/container/logs/

> How do I tell what filesystem I am using?

```bash
df -Th
```

**Comment by dustyhansen** [comment]
The logs are super long, not sure how I share them here?
![image_2024-07-19_064436851](https://github.com/user-attachments/assets/77d30804-f6b2-401f-ac30-c76854bd4b0b)

**Comment by dustyhansen** [comment]
[4119e2db0fa5058ab0709c0b8ff6fb8e322adb6b651cae19a5a4f6fb80187338-json.log](https://github.com/user-attachments/files/16311473/4119e2db0fa5058ab0709c0b8ff6fb8e322adb6b651cae19a5a4f6fb80187338-json.log)

**Comment by dustyhansen** [comment]
I believe this is the last time the error started.

[uptimekumaerror.log](https://github.com/user-attachments/files/16317553/uptimekumaerror.log)
