### ISSUE TITLE
Cloudflare service token authentication

### ISSUE THREAD

**Issue by jonathon2nd** [louislam/uptime-kuma#4951]
### ⚠️ Please verify that this question has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

I would like to use service token to connect to websites protected by cloudflare zero trust
https://developers.cloudflare.com/cloudflare-one/identity/service-tokens/
I can get it working with header
```
{
    "CF-Access-Client-Id": "",
    "CF-Access-Client-Secret": ""
}
```

It would be nice to not have `CF-Access-Client-Secret` in plain text.

Wondering if there is a way to do this already that I am missing.

I thought something like this might work, but not sure what to do about the URL
![image](https://github.com/user-attachments/assets/564b38b2-3d1c-48eb-85ff-780feff9fd0a)

### 🐻 Uptime-Kuma Version

Helm uptime-kuma:2.19.1

### 💻 Operating System and Arch

k8s

### 🌐 Browser

n/a

### 🖥️ Deployment Environment

Helm deployment: 
uptime-kuma:2.19.1

**Comment by CommanderStorm** [comment]
> would be nice to not have `CF-Access-Client-Secret` in plain text.

The headers field you noted is plain text.. am I missing something?

**Comment by jonathon2nd** [comment]
I was wondering if there was some way to have `CF-Access-Client-Secret` protected as a secret, and not have it in plain text.

**Comment by evelynmatson** [comment]
Can you share the whole config you used to get this working? i put in my access token to the headers field with the syntax you suggested, but it's still not working (always showing "up" even if the service is down, beause it's hitting the login page i believe)

**Comment by jonathon2nd** [comment]
Added the following to the headers section

```
{
    "CF-Access-Client-Id": "eee",
    "CF-Access-Client-Secret": "eee"
}
```

which sucks cause as I have stated, `CF-Access-Client-Secret` needs to be protected, and not stored in plain text here.

![image](https://github.com/user-attachments/assets/b3dc09d4-419e-4ca4-8cb3-f73f834a9fdc)

**Comment by bartoszcholewa** [comment]
> Can you share the whole config you used to get this working? i put in my access token to the headers field with the syntax you suggested, but it's still not working (always showing "up" even if the service is down, beause it's hitting the login page i believe)

@evelynmatson and for anyone to whom the server responds 200 OK using the service token, even though the application is down. Step-by-step:

1.  Make sure your application is actually unavailable behind Cloudflare Application Auth (im using Google Identity provider)
    Im using incongito mode for peace of mind
    
    ![1](https://github.com/user-attachments/assets/466aa29f-8136-48fc-b543-5a7cda5158c4)
    ![2](https://github.com/user-attachments/assets/db32d608-7fc1-4843-9bfd-a6b38152ddc7)
    
2. Create your Service Token `CF-Access-Client-Id` and `CF-Access-Client-Secret`
    
    
    ![3](https://github.com/user-attachments/assets/9cdb758a-0a22-481a-8243-0439236b7a58)


3. Add new policy to your application (dont extend your Access group, add it individualy)
    
    
    ![4](https://github.com/user-attachments/assets/28302c91-3126-4766-821b-83684ae3e726)

    
4. Fill up:
   - Policy Name: Your name
   - Action: Service Auth **>>>> IMPORTANT <<<<<**
   - Session Duration: No duration **OPTIONAL**
   - 401 Response Checked - If you want to get response 401 at no auth **OPTIONAL**
   - Include 
       - Selector: Service Token
       - Value: Your Token
       
    
    ![5](https://github.com/user-attachments/assets/6f81d5b1-2c9e-4538-84ea-c2a0054bb7b0)
    ![6](https://github.com/user-attachments/assets/a078c712-b0e2-4497-8c06-67e41857c563)
    
    Save
    
    
    ![6-1](https://github.com/user-attachments/assets/fc689f3b-8039-4ad3-94b8-f8d09113e293)

 
5. Go to Uptime Kuma, edit your monitor, add header, Save

    ![7](https://github.com/user-attachments/assets/027ea918-4ce7-48b2-8269-7e4929472ac5)
    
6. Done

    ![8](https://github.com/user-attachments/assets/7804f4a7-f23a-4a9f-a932-6510f1c1c1ec)


My setup:
- website on Dedicated Server on Cloud Provider
- Uptime Kuma on local
