### ISSUE TITLE
is uptime kuma able to show muti incident event

### ISSUE THREAD

**Issue by joebnb** [louislam/uptime-kuma#4953]
### ⚠️ Please verify that this question has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

it's seems uptime kuma only support one incident event to display,but in some case serval incident may happen in same time,in this case if i click create event  previous incident will deleted(unpin)

 is there have some configuration to keep them both

### 🐻 Uptime-Kuma Version

latest

### 💻 Operating System and Arch

Ubuntu

### 🌐 Browser

chrome 126

### 🖥️ Deployment Environment

- Runtime: Docker latest
- Database: sqlite
- Filesystem used to store the database on: Ext4
- number of monitors: 16

**Comment by joebnb** [comment]
may i create a PR to make mutiple incident event show at same time ?

**Comment by CommanderStorm** [comment]
1 pinned incident per status page makes sense to me. Having more pinned is not a common thing I imagine. Wat is true is that we should have a history to view past incidents. See the discussion around https://github.com/louislam/uptime-kuma/pull/4943 for more insights ^^

**Comment by joebnb** [comment]
i think show multiple incident and incident history are  two things.

show multiple incident is a indicator of current ongoing incidents.user can get insigh what and how many incidents current is happening.

incident history are look back of incidents.

if one incidents is still ongoing,but a new incident will replace it.when this case occur the old ongoing incident update use may not have a quick insight and cause a wrong illusion that that incidents was gone from status page(incident was resolve)

and the multiple incident case example
like cloudflare status page the "Billing issues relating to subscription adjustments" they were "pin" move than one month,during this period they also pin other incidents in top of page.
https://www.cloudflarestatus.com/
current only one incidents,if there more than one ill take a screenshot.


i think multiple incident and multiple maintain events(already supported ) sustain at same time is normal in large monitor system.pls consider let me to implement this.

**Comment by CommanderStorm** [comment]
Going from 1:1 to 1:n is likely fine.
The current UI + DB layout is not optimised for this though.

Make sure that:
- you include a migration 
- go over the UX to match the change

**Comment by joebnb** [comment]
> Going from 1:1 to 1:n is likely fine. The current UI + DB layout is not optimised for this though.
> 
> Make sure that:
> 
> * you include a migration
> * go over the UX to match the change

okay, when I have time, I'll follow the contribute guide to submit a pull request. please help review it then.

**Comment by joebnb** [comment]
i have done this in #4984, if need any further adjustments or specific terms included, let me know
