### ISSUE TITLE
Localhost problem

### ISSUE THREAD

**Issue by raman04-byte** [louislam/uptime-kuma#4954]
### ⚠️ Please verify that this question has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

I am not able to run the localhost:3001 and localhost:8000 
<img width="1140" alt="image" src="https://github.com/user-attachments/assets/82e984bb-09c2-420f-a99a-fd49cb115b90">

### 🐻 Uptime-Kuma Version

1.23.13

### 💻 Operating System and Arch

macOS

### 🌐 Browser

Chrome

### 🖥️ Deployment Environment

- Runtime: 
- Database: 
- Filesystem used to store the database on: 
- number of monitors: 10

**Comment by raman04-byte** [comment]
I tried to simply run it on the chrome and it's running smoothly

**Comment by CommanderStorm** [comment]
Have you allowed the docker container access to localhost outside of the container? (Read: are you running the container in host network mode)

https://github.com/louislam/uptime-kuma/wiki/Troubleshooting

**Comment by raman04-byte** [comment]
Well I have tried your solution and it's not working. 

Also have tried this solution as well: https://github.com/louislam/uptime-kuma#:~:text=If%20you%20want%20to%20limit%20exposure%20to%20localhost%20(without%20exposing%20port%20for%20other%20users%20or%20to%20use%20a%20reverse%20proxy)%2C%20you%20can%20expose%20the%20port%20like%20this%3A

**Comment by raman04-byte** [comment]
It's still down
![Uploading image.png…]()

**Comment by raman04-byte** [comment]
> Have you allowed the docker container access to localhost outside of the container? (Read: are you running the container in host network mode)
> 
> https://github.com/louislam/uptime-kuma/wiki/Troubleshooting

How to allow docker container to access the localhost?

**Comment by CommanderStorm** [comment]
You can allow access to the host network via `--network=host`.

**Comment by alexislefebvre** [comment]
On Linux, one Docker container can access to the host through the address `172.17.0.1`. and `host.docker.internal` should work on Mac (and some versions on Linux). See https://medium.com/@TimvanBaarsen/how-to-connect-to-the-docker-host-from-inside-a-docker-container-112b4c71bc66
