### ISSUE TITLE
Uptime-kuma cannot set multiple expected value judgments

### ISSUE THREAD

**Issue by heilongbo** [louislam/uptime-kuma#4958]
### ⚠️ Please verify that this question has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

To monitor the status of the Elasticsearch cluster, I hope to detect the string values ​​of "green" and "yellow", so I expect the expected value to be predictable, rather than a fixed value.

### 🐻 Uptime-Kuma Version

1.23.13

### 💻 Operating System and Arch

debian 12

### 🌐 Browser

google chrome 版本 126.0.6478.127

### 🖥️ Deployment Environment

- Node.js: 20.4
- npm: 9
- Filesystem used to store the database on: SSD
- number of monitors: 30

**Comment by CommanderStorm** [comment]
> I expect the expected value to be predictable, rather than a fixed value.

I don't know what you want.
This might be able to be solved via the json-query monitor, or you might need to break out the push monitor for fully custom logic.
Examples how to use the push monitor are here: https://github.com/louislam/uptime-kuma/tree/master/extra/push-examples

**Comment by heilongbo** [comment]
> I don't know what you want. 

I mean, can the expected value be matched by regular expression? For example, in the case of Elasticsearch, if the health status changes to green, it cannot be considered a failure. Only the health status red is considered a failure. So I tried to use regular expression to match the green and yellow characters in the expected value, but uptime-kuma could not recognize it!

**Comment by CommanderStorm** [comment]
Regex is tracked in #2735. Plan is to do this via https://github.com/louislam/uptime-kuma/pull/3919
We currently support this via https://docs.jsonata.org/regex
