### ISSUE TITLE
Uptime-Kuma behind nginx reverse proxy (location based routing)

### ISSUE THREAD

**Issue by tapasmallickin** [louislam/uptime-kuma#4963]
### ⚠️ Please verify that this question has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

We have a working copy of uptime-kuma deployed as a container and can be accessed directly or through nginx proxy (if location is set to "/") but not working if location is set to sub-path (e.g. http://<ip.of.uptime.kuma>/kuma/).

Here is the nginx configuration snippet:
```nginx
location /kuma/ {
        proxy_pass         http://localhost:3001/;
        proxy_set_header   X-Real-IP $remote_addr;
        proxy_set_header   X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header   Host $host;
        proxy_http_version 1.1;
        proxy_set_header   Upgrade $http_upgrade;
        proxy_set_header   Connection "upgrade";
        # tried following too
        # rewrite  ^/kuma/(.*)  /$1 break;
} 
```

But getting Error code 404

### 🐻 Uptime-Kuma Version

louislam/uptime-kuma:1

### 💻 Operating System and Arch

Docker x86_64

### 🌐 Browser

Google Chrome 126.0.6478.185

### 🖥️ Deployment Environment

- Runtime: 25.0.3
- Database: 
- Filesystem used to store the database on: 
- number of monitors:

**Comment by CommanderStorm** [comment]
Serving from a subfolder is currently not supported.
See https://github.com/louislam/uptime-kuma/issues/147 for further context.

The status of the support is https://github.com/louislam/uptime-kuma/pull/1092#issuecomment-1953125068 if you want to contribute ^^
