### ISSUE TITLE
is there a way to change the uptime percentage displayed for an item on dashboard? 

### ISSUE THREAD

**Issue by MeitarR** [louislam/uptime-kuma#4964]
### ⚠️ Please verify that this question has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

I am talking about this:
![image](https://github.com/user-attachments/assets/f58a43e8-0442-48d6-866e-b267752140eb)

Currently, it only displays uptime for the last 24 hours. Is there a way of configuring it for a lifetime? or even 1 year?

### 🐻 Uptime-Kuma Version

1.23.13

### 💻 Operating System and Arch

? x64

### 🌐 Browser

?

### 🖥️ Deployment Environment

- Runtime: 
- Database: 
- Filesystem used to store the database on: 
- number of monitors:

**Comment by CommanderStorm** [comment]
no, we don't currently offer such deep customisability

**Comment by MeitarR** [comment]
> no, we don't currently offer such deep customisability

Is it something that you are planning to do? 

If so, maybe I will open PR for it

**Comment by CommanderStorm** [comment]
I would not have put this at the top of the priority list.
Yearly uptime is only avalible in the upcoming v2 release. See #4500 for further context.
A PR making this part configurable would be great.

**Comment by S0ly** [comment]
This would be great to add
