### ISSUE TITLE
Cannot monitor URLs with a CNAME record

### ISSUE THREAD

**Issue by feld** [louislam/uptime-kuma#4966]
I'm seeing HTTPS monitoring failures for any URL where the domain is a CNAME record.

Uptime-kuma keeps reporting an error "getaddrinfo EAI_ADDRFAMILY" which makes no sense. It can be reached with other tools (curl, etc)

This is version 1.23.13 running on FreeBSD

**Comment by CommanderStorm** [comment]
> EAI_ADDRFAMILY
> The specified network host does not have any network
> addresses in the requested address family.

Have you made sure that what the CNAME is pointing at is valid?
