### ISSUE TITLE
All monitors stopped working 

### ISSUE THREAD

**Issue by zluckytraveler** [louislam/uptime-kuma#4967]
### ⚠️ Please verify that this question has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

All of my monitors are showing an error `getaddrinfo ENOTFOUND` 

### 🐻 Uptime-Kuma Version

1.23.13

### 💻 Operating System and Arch

Docker

### 🌐 Browser

Safari

### 🖥️ Deployment Environment

- Runtime:  
- Database:  
- Filesystem used to store the database on:  
- number of monitors:

**Comment by CommanderStorm** [comment]
Same steps as in https://github.com/louislam/uptime-kuma/issues/4765

> `getaddrinfo ENOTFOUND test.xyz`

- What is the TTL of the domains you are using?
- Do you have DNS caching enabled in the settings?


Most commonly, this issue is caused by you using a DNS resolver which does not like the level of DNS requests it is getting.
=> your DNS Server is dropping SOME requests
=> have you enabled NSCD in the settings to lowered the amount of DNS requests to your TTL (instead of on every request)

**Comment by zluckytraveler** [comment]
> * What is the TTL of the domains you are using?

I do not know, how would I even find that out?

Even simple https monitor for https://google.com is failing. I have over 50 monitors and they are all failing including docker as well.

> * Do you have DNS caching enabled in the settings?

No it’s disabled

> Most commonly, this issue is caused by you using a DNS resolver which does not like the level of DNS requests it is getting.

I’m not using anything like that.


> have you enabled NSCD in the settings to lowered the amount of DNS requests to your TTL (instead of on every request)

Yes it’s already enabled.

Additionally my Reverse proxy for Cloudflare tunnel is no longer working and the token is not being accepted.

`Couldn't resolve SRV record &{region1.v2.argotunnel.com. 7844 1 1}: lookup region1.v2.argotunnel.com. on 192.168.65.7:53: no such host`

Out of nowhere everything just suddenly stopped working yesterday.

**Comment by zluckytraveler** [comment]
@CommanderStorm I was able to figure out the issue was the server's ability to connect to the internet altogether due to Apple private relay being enabled as their system is currently down. Hope this helps you in suggesting to others to possibly check this as well. 

https://www.apple.com/support/systemstatus/

You can go ahead and close this issue.
