### ISSUE TITLE
Self Reset 

### ISSUE THREAD

**Issue by jpzone282** [louislam/uptime-kuma#4969]
### ⚠️ Please verify that this question has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

Hello, I have been running Uptime Kuma for around 11 days.  Just tried to login to check a few things and it randomly asked me to create an account. Its like it was "factory reset".  I already set things up and everything.  Have I missed a  setting?

### 🐻 Uptime-Kuma Version

Latest

### 💻 Operating System and Arch

Ubuntu 24.04 LTS

### 🌐 Browser

Chrome 126.0.6478.185

### 🖥️ Deployment Environment

- Runtime:    27.0.3
- Database: 
- Filesystem used to store the database on:  Ubuntu 24.04 LTS
- number of monitors:  8

**Comment by CommanderStorm** [comment]
Did you mount storeage? What is your concrete docker compose/docker command deployment?
I am assuming you deployed via docker as `Runtime: 27.0.3` is too high for node.

**Comment by jpzone282** [comment]
Yeah, it is mounted storage with it and running it with docker compose  

version: '3'
services:
  uptime-kuma:
    image: louislam/uptime-kuma:latest
    container_name: uptime-kuma
    restart: always
    ports:
      - "3010:3001"
    volumes:
      - uptime-kuma:/app/data

**Comment by CommanderStorm** [comment]
Weird, but good, this seems interesting.

let's debug deeper:
- could you provide the log? (docker log ...)
- what does your machine look like? (VM, hosted docker, serverless). Are there any systems in place that might while the containers storage? (Custom cronjob, ...)

**Comment by jpzone282** [comment]
Yes sure here is the log.
[dockerlog.txt](https://github.com/user-attachments/files/16424834/dockerlog.txt)
Its a Ubuntu laptop with Docker on it.  I have no cronjobs everything else running  on it really 
I am using ext4 filesystem type

**Comment by CommanderStorm** [comment]
No clues in there why storage is lost entirely sometimes..

Lets try a different option why this might be loosing storage:

what is the output of
```bash
sudo docker volume inspect uptime-kuma
```

**Comment by jpzone282** [comment]
Hm I am getting an Error response from daemon no such volume error for some reason.

**Comment by jpzone282** [comment]
Yeah i'll set mine up again and see what happens. Just found it really really odd that everything was like set back to factory defaults with no evidence of showing what happened

**Comment by CommanderStorm** [comment]
> Hm I am getting an Error response from daemon no such volume error for some reason. 

If no docker volume exists, we can't persist data..
Maybe docker compose has changed their behavior what happens when you `docker compose up -d`.
=> Could you try that and report the outcome of the volume existing?

**Comment by CommanderStorm** [comment]
@tismofied LXC and docker container are different. Since we don't maintain LXC containers, we can't really help you there. Please contact who packaged your container.
Similar debugging steps likely apply there too..

**Comment by jpzone282** [comment]
> > Hm I am getting an Error response from daemon no such volume error for some reason.
> 
> If no docker volume exists, we can't persist data.. Maybe docker compose has changed their behavior what happens when you `docker compose up -d`. => Could you try that and report the outcome of the volume existing?

`sudo docker-compose up -d`  just runs the container and seems fine

**Comment by CommanderStorm** [comment]
When you say run the container do you also mean create the volume?
What is the result of docker volume inspect uptime-kuna?

**Comment by louislam** [comment]
> Yeah, it is mounted storage with it and running it with docker compose

@jpzone282 Your compose file is missing the root `volumes:` section at the end. 

```
version: '3'
services:
  uptime-kuma:
    image: louislam/uptime-kuma:latest
    container_name: uptime-kuma
    restart: always
    ports:
      - "3010:3001"
    volumes:
      - uptime-kuma:/app/data
volumes:
  uptime-kuma:
```

But I personally would recommend using a relative path rather than a volume, this is more simple.

See:
https://github.com/louislam/uptime-kuma/blob/master/compose.yaml

**Comment by jpzone282** [comment]
I have done the relative path and still no change. 
Think I should start again and see what happens next time round. 
Unless there is more troubleshooting anyone wants to do.

**Comment by tismofied** [comment]
> I have done the relative path and still no change. 
> 
> Think I should start again and see what happens next time round. 
> 
> Unless there is more troubleshooting anyone wants to do. 

It might not have anything to do with it but I remember reading somewhere to get rid of "version" line in docker compose file. 
That's what I did and my container is working fine now.
