### ISSUE TITLE
uptime kuma "resets" with each reboot server

### ISSUE THREAD

**Issue by pickles4evaaaa** [louislam/uptime-kuma#4970]
### ⚠️ Please verify that this question has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

I have setup UTK on multiple servers without issue, but this time I am unable to do so...

I can install UTK with no problem, can create a user account, create monitors, etc.. 

But when I reboot my server, it looks like all of my work is erased and UTK is reset. After rebooting the machine, it will again ask me to setup and account on uptime kuma:3001.

I want to freshly restart and uninstall everything, including node. I have tried multiple times to uninstall uptime kuma, any help is appreciated. I think I need a fresh start to get Uptime Kuma to work again

### 🐻 Uptime-Kuma Version

1.23.13

### 💻 Operating System and Arch

Ubuntu Desktop latest

### 🌐 Browser

Safari

### 🖥️ Deployment Environment

- Runtime: nodes
- Database: unsure
- Filesystem used to store the database on: SSD
- number of monitors: 0

**Comment by CommanderStorm** [comment]
What does the log look like?
What filesystem are you using? (Are you using NFS by chance?)

**Comment by CommanderStorm** [comment]
@pickles4evaaaa for feedback: what was the resolution to your issue?

**Comment by pickles4evaaaa** [comment]
> @pickles4evaaaa for feedback: what was the resolution to your issue?

I ended up removing nvm and node and just running UTK in a container via CasaOs.
