### ISSUE TITLE
`/setup` is redirected to `/dashboard` and i am unable to register

### ISSUE THREAD

**Issue by VineetSadawari** [louislam/uptime-kuma#4982]
### ⚠️ Please verify that this question has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

I am using Version 1.22.1 and I have registered as admin user , I can login correctly.
But when I visit the `/setup` for registering with another user it redirects me to login page.
i am unable to register with new user.

what is the issue?

### 🐻 Uptime-Kuma Version

1.22.1

### 💻 Operating System and Arch

NA

### 🌐 Browser

Chrome 

### 🖥️ Deployment Environment

- Runtime: 
- Database: 
- Filesystem used to store the database on: 
- number of monitors: 0

**Comment by CommanderStorm** [comment]
> I am using Version 1.22.1

We don't support old versions. Please upgrade to the latest version


> I have registered as admin user [and now whant to] register with another user

`/setup` is avaliable for one user and is then deactivated.
This is intentional, we don't currently have multi-user support.
See #128 for further details.
