### ISSUE TITLE
Title of notification on Discord

### ISSUE THREAD

**Issue by sugarwsi** [louislam/uptime-kuma#4983]
### ⚠️ Please verify that this question has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

Hi all, I'm already using uptime kuma right now with alerting on Discord.
just wondering how we can get the title of notification "UP" when the message also has the status "UP"?
meaning, i want to know the status when the title of notification is shown on my Discord

### 🐻 Uptime-Kuma Version

1.23.13

### 💻 Operating System and Arch

Ubuntu 22

### 🌐 Browser

Google Chrome

### 🖥️ Deployment Environment

- Runtime: Docker
- Database: Docker
- Filesystem used to store the database on: Docker
- number of monitors: 20

**Comment by CommanderStorm** [comment]
Templating notifications is currently only supported for very few notification providers. Discord is not one of them.
See https://github.com/louislam/uptime-kuma/issues/646 for further context
