### ISSUE TITLE
How to enable user registeration?

### ISSUE THREAD

**Issue by ghaseminya** [louislam/uptime-kuma#4987]
### ⚠️ Please verify that this question has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

Hi to all,
How can i enable user registration?
Thanks.

### 🐻 Uptime-Kuma Version

1.23

### 💻 Operating System and Arch

Rocky 9

### 🌐 Browser

Firefox

### 🖥️ Deployment Environment

- Runtime: 
- Database: 
- Filesystem used to store the database on: 
- number of monitors:

**Comment by CommanderStorm** [comment]
Self registration is tracked in https://github.com/louislam/uptime-kuma/issues/1638 and blocked by https://github.com/louislam/uptime-kuma/issues/128

Testing the assoicated PR and reporting the findings in the attached PR is appreciated. For further details see https://github.com/louislam/uptime-kuma/pull/3571

**Comment by CommanderStorm** [comment]
(forgot to close as resolved)
