### ISSUE TITLE
Error reaching uptime-kuma via reverse proxy (Traefik) when more than 1 instances are behind the proxy

### ISSUE THREAD

**Issue by GBT55** [louislam/uptime-kuma#4993]
### ⚠️ Please verify that this question has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

If I create an instance of uptime-kuma and put it behind my reverse proxy, which is Traefik, everything works fine and I can access the web ui with no problem.
![image](https://github.com/user-attachments/assets/0e745405-ba68-44b5-b0d1-ffcf0bb42778)
![image](https://github.com/user-attachments/assets/300b7ee2-4b77-4c02-89ea-f24eaae9fce4)

Now, if I create more than 1 instance, say 2, I will not be able to access the web ui.
![image](https://github.com/user-attachments/assets/5f5050cd-69c4-49a6-a14f-38ec11aa4089)
![image](https://github.com/user-attachments/assets/e8d076c3-296d-4792-b9df-2c9885e7beae)

These are the tags that I'm using for the docker container
```
"traefik.enable=true",
"traefik.http.routers.uptime-kuma.rule=Host(`up.gbt55.es`)",
"traefik.http.routers.uptime-kuma.tls.certresolver=letsencrypt",
```
I have also noticed that no matter if the instances are all on one node or spread out between nodes, it will never work.

And yes, if I use `<serverIP>:<port>` I can access each instance of kuma individually
![image](https://github.com/user-attachments/assets/f051cfad-a9dd-4866-8a8e-863034bc0181)

### 🐻 Uptime-Kuma Version

1.23.13

### 💻 Operating System and Arch

NixOS aarch64 Linux 6.6.31

### 🌐 Browser

Chrome (127.0.6533.88) and Firefox (115.13.0)

### 🖥️ Deployment Environment

- Runtime: Docker 24.0.9 via Nomad
- Database: embedded
- Filesystem used to store the database on: NFS
- number of monitors: 4

**Comment by CommanderStorm** [comment]
Please separate the services on different routes.
The current architecture is not highly available
 => sharing a domain between different instances is not supported
