### ISSUE TITLE
editing `!important` in the prim-css editor is rendered exactly one character too wide

### ISSUE THREAD

**Issue by davinma** [louislam/uptime-kuma#4994]
### 📑 I have found these related issues/pull requests

Nothing to preview

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### Description

![image](https://github.com/user-attachments/assets/a24881a7-d02e-47f5-b440-4ecabd5ceac7)

### 👟 Reproduction steps

That is my screenshot, When I try to delete the extra semicolon, the word 'padding' after the semicolon gets partially deleted to become 'adding'. Currently, my only workaround is to delete the entire line and then re-edit it to avoid this issue.

### 👀 Expected behavior

Delete the extra semicolon

### 😓 Actual Behavior

The word after the semicolon gets partially deleted

### 🐻 Uptime-Kuma Version

1.23.13

### 💻 Operating System and Arch

macOS 14.5

### 🌐 Browser

Google Chrome 127.0.6533.89 (x86_64)

### 🖥️ Deployment Environment

- Runtime: nodejs 22.5.1
- Database: sqlite
- Filesystem used to store the database on: Windows
- number of monitors: 2

**Comment by CommanderStorm** [comment]
Can reproduce, seems like the `!important` is rendered exactly one character too wide
![Recording 2024-08-05 at 15 37 34](https://github.com/user-attachments/assets/405f7fb2-cc01-42cb-b1b3-dd5452c3267b)
