### ISSUE TITLE
The database seems to be full

### ISSUE THREAD

**Issue by feritkirikci** [louislam/uptime-kuma#4995]
### ⚠️ Please verify that this question has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

<img width="490" alt="image" src="https://github.com/user-attachments/assets/0c8deac6-2ede-4236-b768-0e947d907915">

The database is almost full and I can't do anything. There are 600 URLs, I can't clean or compress them. Is there a command that I can use to delete the history via the terminal?

Live :
<img width="1512" alt="image" src="https://github.com/user-attachments/assets/8636a2d9-c89e-4217-9e99-ae46a764da8c">

### 📝 Error Message(s) or Log

<img width="718" alt="image" src="https://github.com/user-attachments/assets/2739a439-e607-4975-8de0-8b0fc4caf4a8">

### 🐻 Uptime-Kuma Version

 1.23.13

### 💻 Operating System and Arch

 1.23.13

### 🌐 Browser

Chrome Mac

### 🖥️ Deployment Environment

- Runtime: 
- Database: 
- Filesystem used to store the database on: 
- number of monitors:

**Comment by CommanderStorm** [comment]
You are in for a fun time.
Please read through https://github.com/louislam/uptime-kuma/issues/4581

=> you need to free up more storage (f.ex. by deletign temporary files) to be able to delete rows in sqlite or increase your storage or delete your wal/shm (read the docs first!)

> [!TIP]
> Offopic tipp:
> File-sizes should be gotten via `du -sh` as otherwise directories are not listed with their content size
