### ISSUE TITLE
Monitors duplicate at status change

### ISSUE THREAD

**Issue by Badetuch** [louislam/uptime-kuma#4997]
### 📑 I have found these related issues/pull requests

None

### 🛡️ Security Policy

- [x] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### Description

![image](https://github.com/user-attachments/assets/6a710c36-8202-484a-a003-59ad6b274cab)

I run Kuma behind a traefik reverse proxy. When to state of a monitor changes, e.g. from 'Up' to 'Down' or vice versa, the state of the service does not change but rather duplicates itself with in the new state as seen on the screenshot I took.
Reloading the Page doesn't fix this either and it ends up creating a very messy ux, even though kuma detects the services correctly as 'up' or 'down' ass seen in the 'Quick Stats' section.

### 👟 Reproduction steps

I wanted to test if Kuma was working correctly and exited some of my monitored docker containers, in this case my teamspeak3 server and mysql database which I use as an external db for the ts3-server.
I monitor my 2 containers with the 'Docker Container' Monitor-type using the container name.
For the 'TeamSpeak - SSH' monitor I use the 'TCP Port' option.

### 👀 Expected behavior

The state of the monitors should change from 'up' to 'down' and vice versa.

### 😓 Actual Behavior

The monitors are being duplicated in the 'Quick Stats' Section.

### 🐻 Uptime-Kuma Version

1.23.13

### 💻 Operating System and Arch

Debian 12 

### 🌐 Browser

Brave Version 1.68.134 Chromium: 127.0.6533.88 (Official Build) (64-Bit)

### 🖥️ Deployment Environment

- Runtime: Docker Standalone 20.10.24+dfsg1, Traefik 2.11.0
- Database: embedded mariadb (i guess, I just copied the docker-compose.yml file)
- Filesystem used to store the database on: aws ebs ext4
- number of monitors: 5

**Comment by CommanderStorm** [comment]
> duplicates itself with in the new state as seen on the screenshot I took

Could you annotate where in the screenshot a duplicate monitor exists? I cannot find any (Am I blind?)

**Comment by Badetuch** [comment]
![image](https://github.com/user-attachments/assets/91e6089e-4235-481f-a10c-27721561aa4a)

**Comment by CommanderStorm** [comment]
Please see the thrid collumn.
Lets take the ssh monotor:
- 2:38 SSH went `DOWN`
- 2:41 SSH came `UP`
- 18:35 SSH went `DOWN`
- 18:37 SSH came `UP`
