### ISSUE TITLE
'Upgrade Required' Screen When Trying to Get To Dashboard with http://127.0.0.1:3001

### ISSUE THREAD

**Issue by rthidden** [louislam/uptime-kuma#4999]
### ⚠️ Please verify that this question has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

I tried to go to the Uptime Kuma dashboard and got a black screen with 'Upgrade Required' in the upper left corner. I had just installed Uptime Kuma today and was learning how it worked, trying to add domains, etc., but then it stopped working, and I got this screen.

![image](https://github.com/user-attachments/assets/3bc7c0c6-0bb4-45eb-86b2-50e78bf652d7)

I followed the [Update Instructions](https://github.com/louislam/uptime-kuma/wiki/%F0%9F%86%99-How-to-Update), and no change.

Any ideas what could be happening? Thanks for the help.

### 📝 Error Message(s) or Log

'Upgrade Required'

### 🐻 Uptime-Kuma Version

1.23.13

### 💻 Operating System and Arch

Windows 11

### 🌐 Browser

Google Chrome Version 127.0.6533.100 (Official Build) (64-bit), Microsoft Edge  Version 128.0.2739.5 (Official build) stable app, beta channel (64-bit)

### 🖥️ Deployment Environment

- Runtime: Docker Engine v27.0.3
- Database: Whatever comes with Uptime Kuma SQLite?
- Filesystem used to store the database on: Windows 11
- number of monitors: 4

**Comment by CommanderStorm** [comment]
Sorry to say, but that is not us
https://github.com/search?q=repo%3Alouislam%2Fuptime-kuma+%22Upgrade+Required%22&type=code

What are you running in terms of deployment?
Could another container be running on said port?

We display an outdated message, but that is a banner which can be ignored and disabled.

**Comment by rthidden** [comment]
Hi @CommanderStorm, Thanks for getting back to me. I don't know exactly how it happened, but there were two Docker images for Uptime Kuma. It may have happened when I tried to delete one and update it to get the message to go away. 

I deleted one Docker image, upgraded Docker, and got Uptime Kuma to come back up. But it only works with http://localhost:3001 now and not http://127.0.0.1:3001. I do not know if it doesn't make a difference. All my settings were lost, but I had not made it that far, so it was no big deal.

The 'Upgrade Required' message must have been coming from Docker. It's odd that it would stop working because it needed an upgrade. 

Now, I am trying to figure out how Groups work and how to get bulk upload to work. I have over 200 domains I need to add. 

Thanks again.

**Comment by CommanderStorm** [comment]
> Now, I am trying to figure out how Groups work and how to get bulk upload to work. I have over 200 domains I need to add.

Bulk uploading is not currently supported.
See these issues for optons to work around this limitation:
- https://github.com/louislam/uptime-kuma/issues/1323
- https://github.com/louislam/uptime-kuma/issues/455

Groups work as `any(child.is_down for child in children)` monitors

About the amount of monitors, see #4500 depending on your storage
