### ISSUE TITLE
Enhancement: Gotify priorities

### ISSUE THREAD

**Issue by aslmx** [louislam/uptime-kuma#50]
Thanks for releasing with the Gotify PR included so soon!

Makes it easier a lot - I had used Webhook to NodeRed and from there relayed to my Gotify as a workaround in the meantime.

As commented on the Commit already, I'd really love to see priorities being supported. I use different notification classes in the Gotify Android App. This way I could react on critical failures fast, while not getting woken up by minor things in the night (just an example ;))

Thx!

**Comment by philippdormann** [comment]
good suggestion, uptime-kume itself might require some more internal enhancements tho. cc @louislam 🧐

uptime-kuma currently only checks for available/unavailable states afaik.

For this functionality it would make sense to check status codes, response times, minimum counters/ threshholds (like statping does)

In the meantime, I implemented basic priority customization in PR #52 .
