### ISSUE TITLE
Notification time issue.

### ISSUE THREAD

**Issue by basil-thgnet** [louislam/uptime-kuma#5000]
### ⚠️ Please verify that this question has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

Hi,

The email notifications received from uptime-kuma has the time in UTC in its email headers instead of specifying the local time.

Is there a fix for it ?

Can we do something to sort this issue to dislapy the local time in email headers ?

I have checked deploying the application via both docker and without using docker.

Thank you.

### 🐻 Uptime-Kuma Version

1.23.13

### 💻 Operating System and Arch

Ubuntu 20.04

### 🌐 Browser

Chrome Version 127.0.6533.99 

### 🖥️ Deployment Environment

Runtime: Docker 20.10.9

**Comment by CommanderStorm** [comment]
[`nodemailer`](https://nodemailer.com/message/) sets the current time as UTC in that field.
Why do you want this field in local time?

**Comment by basil-thgnet** [comment]
if we receive a server downtime alert in email box from uptime-kuma, the email shows the local time which is in CEST, but the time in email header shows the time in UTC, which makes the person confused regarding the actual time the issue happened.

**Comment by basil-thgnet** [comment]
the last mail with monitoring is recevied on 10h50
it's the good time
but in the mail :

Time (UTC): 2024-08-06 08:50:44.225

I have attached the screenshot.

How can i show the local time on email header too ?
![time](https://github.com/user-attachments/assets/e09382df-ba8a-45e1-8600-f3df73ac875d)

**Comment by CommanderStorm** [comment]
The screenshot included by you does not show a header.

That part of the notification shows the servers timezone and local time since `1.22.0`.
https://github.com/louislam/uptime-kuma/commit/343a1d3344779ea10933637cae1c0f46eadfd90b#diff-127e639176c0431697ef001140696f0bfb56aa113da83f20a9ffa26d450804e1

You can change the servers timezone in the settings

**Comment by basil-thgnet** [comment]
In smtp.js, i have changed:

bodyTextContent = `${msg}\nTime (CST): ${heartbeatJSON["time"]}`;

to 

bodyTextContent = `${msg}\nTime (${heartbeatJSON["timezone"]}): ${heartbeatJSON["localDateTime"]}`;

and still shows the same issue.

The email notification received from uptime-kuma is attached.

Please let me know how this can resolved.
![time](https://github.com/user-attachments/assets/52ad176e-3884-4e3b-a2e7-948f76f9d103)

**Comment by CommanderStorm** [comment]
Double check your version and update.
As said: this was changed as requested in `v1.22.0`..

**Comment by basil-thgnet** [comment]
okay, let me check.

**Comment by basil-thgnet** [comment]
Hi,

1) The output of time/date

===========
root@kuma-docker-server:~/uptime-kuma# timedatectl 
               Local time: Mon 2024-08-12 13:19:17 IST
               Universal time: Mon 2024-08-12 07:49:17 UTC
               RTC time: Mon 2024-08-12 07:49:17    
               Time zone: Asia/Kolkata (IST, +0530)  
System clock synchronized: yes                        
NTP service: active                     
RTC in local TZ: yes 
===========

2) The uptime-kuma version

===========
root@kuma-docker-server:~/uptime-kuma# cat package.json | grep version
    "version": "1.23.13",
===========

3) The email showing UTC time instead of IST

===========
Return-Path: <basiludemy@gmail.com>
Received: from [127.0.0.1] ([193.105.133.252])
        by smtp.gmail.com with ESMTPSA id 5b1f17b1804b1-4290c72d551sm179900655e9.2.2024.08.12.00.48.24
        for <basiludemy@gmail.com>
        (version=TLS1_3 cipher=TLS_AES_256_GCM_SHA384 bits=256/256);
        Mon, 12 Aug 2024 00:48:24 -0700 (PDT)
From: basiludemy@gmail.com
To: basiludemy@gmail.com
Subject: Alert -Test
Message-ID: <55850fbc-7be1-fbf1-4e4f-8b2a543ed244@gmail.com>
Content-Transfer-Encoding: 7bit
Date: Mon, 12 Aug 2024 07:48:22 +0000
MIME-Version: 1.0
Content-Type: text/plain; charset=utf-8

My Email Alert (1) Testing
===========

See the screenshots attached.

I cannot see that the time in notification has been rectified in the versions above v1.22.0, as the current version mine is  v1.23.13.

Thank you.
![Uploading email.png…]()

**Comment by CommanderStorm** [comment]
That does not match what you have reported previously.
Here is the code for `1.23.X`

https://github.com/louislam/uptime-kuma/blob/1185b259c2f171758e75d92e6843c5efec652f04/server/notification-providers/smtp.js#L94

What have you set here in the settings?
![image](https://github.com/user-attachments/assets/1d0336d1-608a-4468-8717-9bec0c072da2)

> The email showing UTC time instead of IST

That is a different part of the email.
The Date-header is indeed set to UTC by `nodemailer`, but that is not the line (`Time ...`) [you reported here](https://github.com/louislam/uptime-kuma/issues/5000#issuecomment-2276066297).
Brings us back to my intial question:
Why do you want the headers (not message-content) in local time?

**Comment by CommanderStorm** [comment]
Why are your techs looking at the raw mail headers in the first place?
Headers are not really meant for humans, rather for machines or programs.
All email programs that I know of just convert times to localtime.
Converting from UTC in the display layer (in this case: mail-program) has advantages by putting the blame of having incorrect timezone-handling upstream.
See [The Problem with Time & Timezones](https://www.youtube.com/watch?v=-5wpm-gesOY) why I would like that handling as upsteam as possible.

The time is included in the body..

**Comment by basil-thgnet** [comment]
Thank you, it has been fixed now. Thank you for the support
