### ISSUE TITLE
How to block  Down] read ECONNRESET alert in uptime-kuma

### ISSUE THREAD

**Issue by Adith2cloud** [louislam/uptime-kuma#5002]
### ⚠️ Please verify that this question has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

I know this is error is caused by the sudden connetion termination between client and kuma. But I am monitoring fifty plus sites and man ECONNRESET are a handsome to deal with. I've tried api's of kuma to start and stop alert before. Like that using api's can I block this specific alert or is there any other way.

Thank you

### 📝 Error Message(s) or Log

 Down] read ECONNRESET

### 🐻 Uptime-Kuma Version

1.23.3

### 💻 Operating System and Arch

Linux server 

### 🌐 Browser

Brave

### 🖥️ Deployment Environment

- Runtime: Docker 20.10.9
- Database: mysql
- Filesystem used to store the database on: SSD
- number of monitors: 50

**Comment by CommanderStorm** [comment]
We don't currently have ways to confure something that deeply.
Consider if the retry setings can solve your issue (I think they can).

If they can't you will have to encode what means up/down into a push monitor. Examples for this [are located here](https://github.com/louislam/uptime-kuma/tree/master/extra/push-examples)

**Comment by Adith2cloud** [comment]
> We don't currently have ways to confure something that deeply. Consider if the retry setings can solve your issue (I think they can).
> 
> If they can't you will have to encode what means up/down into a push monitor. Examples for this [are located here](https://github.com/louislam/uptime-kuma/tree/master/extra/push-examples)

Oke, But i tried increasing the retries and done some tweaking in the confirugations there and there like time out and stuffs. It was oke for few days, maybe a month. But now the issue came suddenly like a tsunami. Kinda irritating.

Anyway thank you for your reply.

**Comment by CommanderStorm** [comment]
Consider that you actually might have an issue with `ECONNRESET` then which we are alerting to.

**Comment by Adith2cloud** [comment]
Yes, issue with ECONNRESET spamming. It would be better if we can block this particular alert.

**Comment by CommanderStorm** [comment]
No it would not be better. We are allerting to a valid issue.

"ECONNRESET" means the other side of the TCP conversation abruptly closed its end of the connection. This is most probably due to one or more application protocol errors. You could look at the API server logs to see if it complains about something.

If you don't like the way we alert, you can write your own monitor as suggested above
https://github.com/louislam/uptime-kuma/issues/5002#issuecomment-2278039073
