### ISSUE TITLE
Cannot connect to the socket server. [ Reconnecting ]

### ISSUE THREAD

**Issue by rajveer-bhati** [louislam/uptime-kuma#5011]
### ⚠️ Please verify that this question has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

Hello,

We are encountering a connection timeout issue when attempting to monitor. The system is deployed on a Linux server and managed using PM2. Despite configuring the environment to handle a large number of requests, the monitoring process fails with connection timeouts, leading to incomplete or failed checks for many of the URLs. Using nginx as reverse proxy. Below is the nginx configruation.

<details><summary><code>nginx.conf</code></summary>

```nginx
server {
    listen 80;
    listen [::]:80;
    server_name uptime.codiantdev.com;

    location /{
        return 301 https://uptime.codiantdev.com$request_uri;
    }
}

server {
   listen 443 ssl http2;
   #listen [::]:443 ssl http2;
   server_name uptime.codiantdev.com;
   client_max_body_size 200M;

   ssl_certificate /etc/nginx/ssl/codiantdev.crt;
   ssl_certificate_key /etc/nginx/ssl/codiantdev.key;

   access_log /var/log/nginx/uptime-access.log;
   error_log /var/log/nginx/uptime-error.log;
   access_log /var/log/monitoring/uptime-access.log updated_json_combined;


   location / {
       proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
       proxy_set_header X-Real-IP $remote_addr;
       proxy_set_header Host $host;
       proxy_set_header X-Forwarded-Proto $scheme;
       proxy_pass http://localhost:3001/;
       proxy_http_version 1.1;
       proxy_set_header Upgrade $http_upgrade;
       proxy_set_header Connection "upgrade";
   }
}
```

</details>

### 📝 Error Message(s) or Log

![connection](https://github.com/user-attachments/assets/c5473653-d4f2-4d22-a1a2-c2bc5b256a90)

### 🐻 Uptime-Kuma Version

3.3.17

### 💻 Operating System and Arch

Ubuntu 22.04

### 🌐 Browser

Chrome

### 🖥️ Deployment Environment

- Runtime: 
- Database: 
- Filesystem used to store the database on: 
- number of monitors:

**Comment by CommanderStorm** [comment]
![image](https://github.com/user-attachments/assets/5bc04d17-61a0-485d-9503-1ab4fbc044ca)

Seems to work on my end.
Could you please provide
- logs from the browser,
- logs from the server and
- fill out metadat such as the fields about `Deployment Environment`, `Browser` and `Uptime-Kuma Version` you ommited above?

**Comment by rthidden** [comment]
I am having the same issues. Deployed on PikaPod. Using the latest stable versions of Edge and Chrome browsers.

Error Logs:
Trace: TypeError: callback is not a function
at Socket.<anonymous> (/app/server/server.js:934:17)
at runNextTicks (node:internal/process/task_queues:60:5)
at listOnTimeout (node:internal/timers:538:9)
at process.processTimers (node:internal/timers:512:7)
at process.unexpectedErrorHandler (/app/server/server.js:1905:13)
at process.emit (node:events:517:28)
at emit (node:internal/process/promises:149:20)
at processPromiseRejections (node:internal/process/promises:283:27)
at processTicksAndRejections (node:internal/process/task_queues:96:32)
at runNextTicks (node:internal/process/task_queues:64:3)
at listOnTimeout (node:internal/timers:538:9)
at process.processTimers (node:internal/timers:512:7)

![image](https://github.com/user-attachments/assets/2a55ed6b-c496-4d61-87e0-304bdcee78eb)

![image](https://github.com/user-attachments/assets/82a82cbb-abf7-4360-a98e-0c079a5be16d)

![image](https://github.com/user-attachments/assets/dd1e0c29-2f1b-4163-9e7b-0f6e1795d3fd)

![image](https://github.com/user-attachments/assets/74089fbe-6303-4ce7-b099-64cc721ae622)

**Comment by CommanderStorm** [comment]
Please see https://github.com/louislam/uptime-kuma/issues/5010#issuecomment-2283550401
I don't know where that issue is coming from and it is not reproducible in any case.
Maybe some FS-corruption? I don't know..

Closing as a duplicate / other issue is a better fit for your issue

**Comment by rthidden** [comment]
When I searched for "Cannot connect to the socket server" for issues for the repo, I found 61 hits. 

Do you know if any solution has been offered to this at all? Or is it everyone's individual system that is causing issues, not the software, if you are not able to reproduce it?

**Comment by CommanderStorm** [comment]
not being able to connect to the socket server has 20 different root causes, but most of them boil down to
- something going seriously wrong on the network (router, firewall, reverse proxy, Content security policy, Add-blocker, Pi-Hole, ...) or
- the server (out of storage, too low IO, overloaded, bricked for some other reason like the bug from https://github.com/louislam/uptime-kuma/issues/5010#issuecomment-2283550401)

Depending on the problem you are having solutions mostly exist.
Lets root-cause your issue in a fresh issue with the full context about your environment and all the logs.
