### ISSUE TITLE
what  does publicmonitor mean? I can’t see it on the web. 

### ISSUE THREAD

**Issue by woniuzhang** [louislam/uptime-kuma#5019]
### ⚠️ Please verify that this question has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

 I want to use /api/badge/:id/uptime/:duration? to get availability data, then I found most of the monitor is N/A. I checked code and found these monitors are not public. So I got to web console and found nothing about public. I want to known what does public mean and how make these monitors public, can I just modify the database?

<img width="999" alt="图片" src="https://github.com/user-attachments/assets/71020703-e83b-43ae-94a3-6b0130f4791a">

### 🐻 Uptime-Kuma Version

1.23.11

### 💻 Operating System and Arch

k8s

### 🌐 Browser

Firefox

### 🖥️ Deployment Environment

- Runtime:  v1.24.6-aliyun.1
- Database: sqlite
- Filesystem used to store the database on: local file
- number of monitors:  about 40

**Comment by woniuzhang** [comment]
I execute sql "INSERT INTO monitor_group (monitor_id, group_id, weight) VALUES (50, 4, 5);"  to make monitor id 50 to be a publicmonitor, and then can get data from URL /api/badge/50/uptime/

**Comment by louislam** [comment]
Create a status page and add your monitors to the status page so as to make it public.
