### ISSUE TITLE
Can I really translate without programming skills?

### ISSUE THREAD

**Issue by MrEddX** [louislam/uptime-kuma#502]
I would like to translate, but actually can't figure it out: Am I doing it the right way?

Followed the instructions, but after running `npm run update-language-files` all language files in `src/languages/` have been processed. The `package-lock.json` file is also changed. I expected **only** the new file to be filled with something like a template.

So, what I did:

- OS Ubuntu 20.04 Headless
- Installed "fnm" with script: `curl -fsSL https://fnm.vercel.app/install | bash`
- Installed " Node v14.17.6 (x64)": `fnm install 14`
- Cloned the repository locally: `git clone https://github.com/louislam/uptime-kuma.git`
- CD into `~/uptime-kuma`
- Created the language file: `touch src/languages/bg-BG.js`
- Installed ESLint: `npm install eslint`
- Runing: `npm run update-language-files` finished without errors:
```
...
Processing tr-TR.js
Processing zh-CN.js
Processing zh-HK.js
Done. Fixing formatting by ESLint...
``` 
- The new language file `src/languages/bg-BG.js` is now populated with the English template
- `git status` shows that many files are changed as described above
- `git diff` shows lots of changes that I think shouldn't be done. The output is endless so the example below is for just one file:
```
--- a/src/languages/zh-HK.js
+++ b/src/languages/zh-HK.js
@@ -170,7 +170,7 @@ export default {
     "Avg. Ping": "Avg. Ping",
     "Avg. Response": "Avg. Response",
     "Entry Page": "Entry Page",
-    "statusPageNothing": "Nothing here, please add a group or a monitor.",
+    statusPageNothing: "Nothing here, please add a group or a monitor.",
     "No Services": "No Services",
     "All Systems Operational": "All Systems Operational",
     "Partially Degraded Service": "Partially Degraded Service",
```

I have no idea what is the magic behind `npm run update-language-files` but it doesn't look like an expected final result on my side. So, the questions are:

What am I doing wrong?
What am I missing from the [How to translate](https://github.com/louislam/uptime-kuma/tree/master/src/languages#how-to-translate) guide?

But for a guy without programming skills that was my best try.

If you have the time to assist me with this task it will be just GREAT!

**Comment by chakflying** [comment]
The diff that you posted is normal. Running that command fixes all language files by applying the newest update, so all the changes indicate that those languages have not been updated yet.

 If the previous single quotes problem is fixed, simply add ONLY your `bg-BG` file to git, commit, push, and you should be good to go.

**Comment by louislam** [comment]
Yes, it is required a bit of programming skills in order to translate.

> But for a guy without programming skills that was my best try.

Really appreciate it! You did a very good job already. I honestly don't expect someone who don't have programming skills know how to use git and create pull request. 

Let me know if you have finished the translation in https://github.com/louislam/uptime-kuma/pull/494, I can fix the single quotes for you.

**Comment by MrEddX** [comment]
Thank you guys!
What an awesome community!

> If the previous single quotes problem is fixed...

I think `npm install eslint` did the magic.

> You did a very good job already.

Really? Don't ask me how many hours I was trying to figure out how to do all that stuff.
Fingers crossed for my the next try.

**Comment by louislam** [comment]
Merged, thanks.
