### ISSUE TITLE
Single widget/icon to indicate if anything is down

### ISSUE THREAD

**Issue by bilogic** [louislam/uptime-kuma#5020]
### 📑 I have found these related issues/pull requests

https://www.reddit.com/r/UptimeKuma/comments/175q088/uptime_kuma_for_iphone_ipad_and_apple_watch_with/ but untested as I don't have an iOS device

### 🏷️ Feature Request Type

Status-page

### 🔖 Feature description

Problem: Can't tell straightaway if any services are down

I piped the status to Telegram, however, there are so many messages that it unclear what's the overall status when my list is very long.

It is good for fault finding and rectification, but for management, the numerous messages takes too much cognitive load to process.

### ✔️ Solution

# Mobile monitoring

1. A single icon/widget on my android to indicate if any service is down
2. Have a persistent notification if any service is down
3. Clicking on this notification will bring me to my self hosted page for deeper understanding
4. Can mute a downed service for 1, 4, 8 hours
5. When a service is muted, it is ignored from the overall status

# Desktop monitor (Windows)
1. A single icon/widget on my android to indicate if any service is down (in system tray)
2. Clicking on this notification will bring me to my self hosted page for deeper understanding
3. Can mute a downed service for 1, 4, 8 hours
4. When a service is muted, it is ignored from the overall status

- I have to say, Kuma is impressively comprehensive in configuration and reporting
- But presentation wise, emails and telegram messages are just not suitable
- In many cases especially homelabs, the situation is usually fluid and often self resolves
- Having a Windows + Android, then Linux/MacOS/iOS solution to this would be fantastic

### ❓ Alternatives

I have done a google, only found an iOS solution

**Comment by CommanderStorm** [comment]
I don't think that an IOs/Android apps or widgets fit into the scope or is even possible for a website to do.
Given out very limited engineering resources, I am going to reject this as out of scope / not planned.

If you decide to build an app, we can [link to it here](https://github.com/louislam/uptime-kuma/wiki/3rd-Party-Addons-Apps).
