### ISSUE TITLE
Health/Ping endpoint for Kuma itself

### ISSUE THREAD

**Issue by ribtoks** [louislam/uptime-kuma#5022]
### ⚠️ Please verify that this question has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

I'd like to configure health monitoring in Fly.io, but my question is also perfectly applicable to Docker/Kubernetes setup. I did not find in the source code any kind of `/health` or `/ping` endpoint for Kuma service itself - e.g. to verify it has started and running successfully. Maybe I missed it - in such case I'm sorry. Does such thing exist?

### 🐻 Uptime-Kuma Version

1.23.13

### 💻 Operating System and Arch

Linux

### 🌐 Browser

Firefox

### 🖥️ Deployment Environment

- Runtime: Fly.io
- Database: Sqlite
- Filesystem used to store the database on: N/A
- number of monitors: 1

**Comment by CommanderStorm** [comment]
Just request the a page like `/manifest.json` with a header only request. Should be fine and be zero overhead.

In V2.0, we have the `/setup-database-info` endpoint.
See #4500 for additional details.

**Comment by ribtoks** [comment]
Thank you!
