### ISSUE TITLE
What's the difference between images tagged :1 and :latest?

### ISSUE THREAD

**Issue by kosymodo** [louislam/uptime-kuma#5023]
### ⚠️ Please verify that this question has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

I'm wondering what the difference is between images tagged :1 and those tagged :latest?  It's just the OCD side of my brain wondering why all my other containers use images tagged :latest, but Uptime Kuma has always used :1 :grin

### 🐻 Uptime-Kuma Version

1.23.13

### 💻 Operating System and Arch

Pi running Portainer

### 🌐 Browser

Google Chrome 127.0.6533.120

### 🖥️ Deployment Environment

- Runtime: 
- Database: 
- Filesystem used to store the database on: 
- number of monitors:

**Comment by CommanderStorm** [comment]
See #4500
Latest always points to the latest version. We might change this to be V2.x, we might introduce another latest tag.
If you want stability, you should use the more explicit tags
