### ISSUE TITLE
multi region checks

### ISSUE THREAD

**Issue by pradip-allwyn** [louislam/uptime-kuma#5024]
### 📑 I have found these related issues/pull requests

n/a

### 🏷️ Feature Request Type

Change to existing monitor

### 🔖 Feature description

can we add multiple location monitor for the checks, this way we can be certain if its specific to a particular region

### ✔️ Solution

check the monitors from various region using satellites or tenants and report the result

### 📝 Additional Context

n/a

**Comment by Ionys320** [comment]
I also suggest creating groups, like a "Database" group, with different monitors, one per region.
