### ISSUE TITLE
为什么不能提供和prometheus 集成的能力

### ISSUE THREAD

**Issue by xzclinux** [louislam/uptime-kuma#5026]
### ⚠️ Please verify that this question has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

可以参考http-runner,https://httprunner.com/docs/user-guide/load-test/monitor/

### 🐻 Uptime-Kuma Version

1.10.0

### 💻 Operating System and Arch

centos7.6

### 🌐 Browser

chrome

### 🖥️ Deployment Environment

- Runtime: 
- Database: 
- Filesystem used to store the database on: 
- number of monitors:

**Comment by CommanderStorm** [comment]
You forgot to ask a question.
Our prometheus documentation is avaliable here: https://github.com/louislam/uptime-kuma/wiki/Prometheus-Integration
