### ISSUE TITLE
Diference between Browser Engine Monitor and HTTPS monitor

### ISSUE THREAD

**Issue by djovanov** [louislam/uptime-kuma#5031]
### ⚠️ Please verify that this question has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

Hello,

What is the difference between the https monitor and Browser Engine ?  I didn't found anything in the documentation. 

Thank you

### 🐻 Uptime-Kuma Version

1.23.13

### 💻 Operating System and Arch

Demo

### 🌐 Browser

Mozilla Firefox

### 🖥️ Deployment Environment

- Runtime: 
- Database: 
- Filesystem used to store the database on: 
- number of monitors:

**Comment by CommanderStorm** [comment]
Browser Engine runs chromium => bit fat on the memory/cpu side, but does execute JS.
http(s) does just fetch a http reponse => less resource intensive

**Comment by djovanov** [comment]
Thank you. 
But what is different in the uptime response ? Does the chromium have the ability to see any difference in the website rendering ?

**Comment by CommanderStorm** [comment]
Depends what you are looking for "difference" is quite vague.
We might support this, or you might be looking for changedetection.io

**Comment by djovanov** [comment]
Just interesting to understand the real difference betwen this 2
functionnalities. And I'm looking for a solution who alert me in the case
of my website is broken (plugin update, hack...)

Le jeu. 22 août 2024, 17:31, Frank Elsinga ***@***.***> a
écrit :

**Comment by CommanderStorm** [comment]
Depends how "broken" manifests.
You are not being specific enough..

If this manifests by being down => all options can catch that.
If this manifests by responding with JS, and the JS then does not put a keyword on the screen => Browser Engine can catch that.
If you want defacement/change detection/... => use https://changedetection.io/
