### ISSUE TITLE
How to build the docker images ?

### ISSUE THREAD

**Issue by sohitdeveloper** [louislam/uptime-kuma#5036]
### ⚠️ Please verify that this question has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

hi @louislam , first of all a big thanks for making this project as an open source. I am inspired with your journey and want contribute in the existing open issues...I have picked up coupled of issues and started fixing.

Now, before pushing the code, I want to test it on my local machine by building the docker images and running in my local.
So, I can test as well which ensures that everything will work fine if you merge my PR with the master branch.

So, it would be great that if you tell me the steps for creating the image locally, so I can test in local with the temporary docker image.

Thanks & Regards,
Sohit

### 🐻 Uptime-Kuma Version

1.23.13

### 💻 Operating System and Arch

Ubuntu, Mac

### 🌐 Browser

Google Chrome

### 🖥️ Deployment Environment

- Runtime: Docker 24
- Database: Sqlite
- Filesystem used to store the database on: 
- number of monitors: 15

**Comment by CommanderStorm** [comment]
off-topic: Making every 3rd world bold is quite distracting, please don't.

> I want to test it on my local machine

Please refer to our [contributuin guide](https://github.com/louislam/uptime-kuma/blob/2a820ab16d41a3aa4882854fa158850a5c5edc4c/CONTRIBUTING.md). You can run in development mode via
```
npm run dev
```

> [!TIP]
> For testing PRs, we have documented this workflow: https://github.com/louislam/uptime-kuma/wiki/Test-Pull-Requests

> steps for creating the image locally

You don't need this, but here is the command we use to build the production docker images:
```
npm run build-docker
```
