### ISSUE TITLE
Descriptions on the status page per monitor

### ISSUE THREAD

**Issue by MayhemBill** [louislam/uptime-kuma#5037]
### 📑 I have found these related issues/pull requests

None

### 🏷️ Feature Request Type

Change to existing monitor

### 🔖 Feature description

Small descriptions for each monitor, allows us to show additional notes for monitors

### ✔️ Solution

write a small description for each monitor that shows up under the monitor.

**Comment by CommanderStorm** [comment]
Duplicate of https://github.com/louislam/uptime-kuma/issues/3008
Closing as a duplicate
