### ISSUE TITLE
Allow using CLIs for notifications

### ISSUE THREAD

**Issue by mabed-fr** [louislam/uptime-kuma#5039]
### 📑 I have found these related issues/pull requests

not issue but idea

### 🏷️ Feature Request Type

Dashboard, Settings

### 🔖 Feature description

The functionality would bring a new menu called "hook" available in the settings (below Notifications)

The hooks can be added to one or more monitors

At my level the hooks will be able to add functionality like in CLI:

awscli: https://aws.amazon.com/en/cli/
cntb: https://help.contabo.com/en/support/solutions/articles/103000283067-what-is-the-cntb-tool-

This would allow restarts or other actions to be launched at providers

or open tickets (redmine....)

What do you think?

### ✔️ Solution

Add hook menu

**Comment by CommanderStorm** [comment]
Related, but on the monitor side: https://github.com/louislam/uptime-kuma/issues/1117

**Comment by mabed-fr** [comment]
> Related, but on the monitor side: #1117

Yes on monitor side is good  for first development but it can be add on parameter is more better for skip repeat.

**Comment by CommanderStorm** [comment]
Related != Duplicate
