### ISSUE TITLE
DNS server on same system but on different container monitor not working

### ISSUE THREAD

**Issue by hoovad** [louislam/uptime-kuma#5040]
### ⚠️ Please verify that this question has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

I have a Pi-hole server and an Uptime Kuma server on the same system. I setup the pi-hole web console monitor, and it works just fine. But then, when i try to setup the DNS monitor with resolver server as 192.168.1.44 (the local IP of the server) and the hostname as www.google.com, i get the following error:

![kuva](https://github.com/user-attachments/assets/d74bb985-0f78-4eae-baa6-7948cea46467)

The DNS server works just fine, as i am using it right now, and the DNS server is running on port 53, as intended. Is there any way to fix this?

### 🐻 Uptime-Kuma Version

1.23.13

### 💻 Operating System and Arch

Fedora 40 Server Edition x86_64

### 🌐 Browser

LibreWolf 129.0.1-1

### 🖥️ Deployment Environment

- Runtime: Docker 27.1.2
- Database: Default
- Filesystem used to store the database on: LVM2/xfs on nvme
- number of monitors: 3

**Comment by hoovad** [comment]
I ran netshoot on the uptime kuma container, and tried to `dig` www.google.com via 192.168.1.44 and it turns out that it timed out trying to connect to the DNS server.

**Comment by CommanderStorm** [comment]
We are alerting to a real issue as you noted in your last comment.

The rest is dependent on your docker network and docker DNS configuration. Since you did not share what your configuration there is, I can't make recommendations how to fix your issue.
