### ISSUE TITLE
Blank Page Via Reverse Proxy

### ISSUE THREAD

**Issue by jthompson222** [louislam/uptime-kuma#5044]
### 📑 I have found these related issues/pull requests

- #1275,
- #1006, and
- #930

none of these issues have been resolved.

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### Description

Whenever I connect to my instance via my domain and reverse proxy, I get a blank page, the URL is redirected to a pre-configured status page, but it is still blank. In the network tab /assets is not loaded and the error is TOO_MANY_REDIRECTS. Also, reverse proxy is enabled in the settings and I have followed the Nginx configuration guide. I did some testing with different versions of the containers on different machines, and I was able to connect to older versions through the reverse proxy.

### 👟 Reproduction steps

I have no idea what is causing this bug.

### 👀 Expected behavior

When connecting, the page should load and not be blank.

### 😓 Actual Behavior

The page is just blank, however, the URL does change to the default landing page (which is a status page).

### 🐻 Uptime-Kuma Version

1.23.13

### 💻 Operating System and Arch

Fedora 40, X86_64, Containerized with Podman

### 🌐 Browser

Google Chrome 127.0.6533.120, Firefox 129.0.2

### 🖥️ Deployment Environment

- Runtime: 
- Database: 
- Filesystem used to store the database on: 
- number of monitors:

**Comment by CommanderStorm** [comment]
Where are the redirects going and how is the nginy proxy configured?

**Comment by CommanderStorm** [comment]
Duplicate of https://github.com/louislam/uptime-kuma/issues/5010#issuecomment-2283550401
=> lets continue this there
=> closinga as a duplicate

Really don't know what is going on..
