### ISSUE TITLE
Kuma Bridge Device IP Clash

### ISSUE THREAD

**Issue by thehammy** [louislam/uptime-kuma#5061]
### ⚠️ Please verify that this question has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

Uptime Kuma running in Docker has a bridge device but the assigned IP is clashing with monitors.

I have monitors in the `172.27` network which aren't reachable due to this.

Is there a way to force Kuma to choose another IP range?

```
4: br-482e89231e91: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default
    link/ether 02:42:f1:e2:61:92 brd ff:ff:ff:ff:ff:ff
    inet 172.27.0.1/16 brd 172.27.255.255 scope global br-482e89231e91
       valid_lft forever preferred_lft forever
6: docker0: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc noqueue state DOWN group default
    link/ether 02:42:72:1c:52:05 brd ff:ff:ff:ff:ff:ff
    inet 172.16.0.1/16 brd 172.16.255.255 scope global docker0
       valid_lft forever preferred_lft forever
```

From Docker Inspect
```json
{
            "Networks": {
                "docker_default": {
                    "IPAMConfig": null,
                    "Links": null,
                    "Aliases": [
                        "uptime-kuma",
                        "kuma",
                        "6a6183771c61"
                    ],
                    "NetworkID": "412e89765e91e73c49be81db354dbf2691e60120c6ed36a7de7756d071449f31",
                    "EndpointID": "d21d7f9f1761b3dec0c3081f989d25865c839b8adbf9825763117354696fc15a",
                    "Gateway": "172.27.0.1",
                    "IPAddress": "172.27.0.5",
                    "IPPrefixLen": 16,
                    "IPv6Gateway": "",
                    "GlobalIPv6Address": "",
                    "GlobalIPv6PrefixLen": 0,
                    "MacAddress": "02:42:ac:1b:00:05",
                    "DriverOpts": null
}
```

### 🐻 Uptime-Kuma Version

1.23.13

### 💻 Operating System and Arch

Centos 7

### 🌐 Browser

Google Chrome 128.0.6613.85

### 🖥️ Deployment Environment

- Runtime: 
- Database: 
- Filesystem used to store the database on: 
- number of monitors:

**Comment by CommanderStorm** [comment]
Uptime kuma does not touch IPs, they are assigned by docker instead.
Please see external resources such as [this](https://stackoverflow.com/questions/50514275/docker-bridge-conflicts-with-host-network) on how to configure which IPs docker uses for which network.

Think that resolves your question
