### ISSUE TITLE
Actions in the body code

### ISSUE THREAD

**Issue by JPpascoal** [louislam/uptime-kuma#5062]
### ⚠️ Please verify that this question has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

I have a website that I'm monitoring with Uptime Kuma, and on one of the pages, I need to create a "floor." To do this, I have to click on two buttons first, but the problem is that everything happens on the same page. When I click on these buttons, one of them triggers a pop-up and not a different URL. In Kuma, I have a POST request to check if this "floor" has been created, but it always returns "request failed." If anyone can help, I'd appreciate it.

### 🐻 Uptime-Kuma Version

1.23.13

### 💻 Operating System and Arch

Windows 11

### 🌐 Browser

Google Chrome

### 🖥️ Deployment Environment

- Runtime: 
- Database: 
- Filesystem used to store the database on: 
- number of monitors:

**Comment by CommanderStorm** [comment]
You likely are not monitoring, but testing => consider using cypress, playwrigt or similar to build your testing script.
You can then string this together via the `Push`-minitors and a chron job.

Alternatively, look at https://changedetection.io

**Comment by JPpascoal** [comment]
I am trying to monitor it, but i can't because its a pop up in the page, and not an URL, is there something i can do?

**Comment by CommanderStorm** [comment]
Yes, you could to what I suggested?
Am I missing something?
Examples how to use the push monitor are avaliable here: https://github.com/louislam/uptime-kuma/tree/master/extra/push-examples

> consider using cypress, playwrigt or similar to build your testing script.
You can then string this together via the `Push`-minitors and a chron job.
>
> Alternatively, look at https://changedetection.io
