### ISSUE TITLE
Add custom text to a monitor got from an API call to a service (in status page)

### ISSUE THREAD

**Issue by PilaScat** [louislam/uptime-kuma#5063]
### 📑 I have found these related issues/pull requests

No issue found

### 🏷️ Feature Request Type

Status-page

### 🔖 Feature description

I have a DVR that gives me an API response with the channels in use, I would like to show them under the DVR monitor in the status page 

### ✔️ Solution

Custom text from external API

**Comment by CommanderStorm** [comment]
What do you mean by "custom text"?

**Comment by PilaScat** [comment]
add a list received from an api call below the monitor

**Comment by CommanderStorm** [comment]
Please see these issues:
- https://github.com/louislam/uptime-kuma/issues/3008
- #118

You can currently edit the status pages header/footer via a [third party api](https://uptime-kuma-api.readthedocs.io/)
