### ISSUE TITLE
Would like to be able to customise the title and icon

### ISSUE THREAD

**Issue by yuncheng2024** [louislam/uptime-kuma#5064]
### ⚠️ Please verify that this question has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

Hello Dear Author, I am a user from China, after using your project I think this project is very great and useful. Besides that, I hope that in the future update it is possible for the webmaster to customise the site title and icon to display announcements on the homepage. I look forward to your reply. I will continue to love and support your project whether it is adopted or not!

Edit: translated via [deepl](https://www.deepl.com/de/translator#zh/en-gb)

### 🐻 Uptime-Kuma Version

1.23.13

### 💻 Operating System and Arch

Windows11

### 🌐 Browser

edge

### 🖥️ Deployment Environment

- Runtime: 
- Database: 
- Filesystem used to store the database on: 
- number of monitors:

**Comment by CommanderStorm** [comment]
The title on status pages can be updated.
![image](https://github.com/user-attachments/assets/8b9960c2-5fd1-4df4-8d41-db39e82c254d)

The title of the dashboard cannot and will not be customisable.
If you want that, you can fork the project and maintain your fork. We are not a whitelabel solution, that you buy. Rather, we are an OSS-Project.
