### ISSUE TITLE
Customize the message for sending alarms

### ISSUE THREAD

**Issue by tianruyun** [louislam/uptime-kuma#5065]
### ⚠️ Please verify that this question has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

Is there a specific configuration template? How to customize the message format of alarm notification?

### 🐻 Uptime-Kuma Version

1.23.13

### 💻 Operating System and Arch

centos7

### 🌐 Browser

Google Chrome 128.0.6613.85

### 🖥️ Deployment Environment

- Runtime: 
- Database: 
- Filesystem used to store the database on: 
- number of monitors:

**Comment by CommanderStorm** [comment]
Duplicate of https://github.com/louislam/uptime-kuma/issues/646

At least I think you mean this by config. If you are referring to config templates instead, that is currently not implemented.
