### ISSUE TITLE
IP check

### ISSUE THREAD

**Issue by kennethwolfs** [louislam/uptime-kuma#507]
Maybe it is possible to check ip for blacklisting?

**Comment by rezzorix** [comment]
Hm usually blacklists provide APIs that you can query.
So you could add a new monitor with HTTP(s) Keyword and could check any blacklist that is available to you for whatever you require.

**Comment by CommanderStorm** [comment]
@kennethwolfs
I think this issue is resolved.
In addition, please note that uptime-kuma now includes the `json-query` monitor after the [`1.23` release](https://github.com/louislam/uptime-kuma/milestone/34) https://github.com/louislam/uptime-kuma/pull/3253

**Comment by CommanderStorm** [comment]
Given that the author has not provided additonal details what is menat by `check for blacklisting` and that without details there is no way to implement something I am going to close this as resolved by the `json-query` monitor as noted above
