### ISSUE TITLE
Weblate no longer adds the latest committed translations

### ISSUE THREAD

**Issue by cyril59310** [louislam/uptime-kuma#5070]
### 📑 I have found these related issues/pull requests

No

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### Description

Weblate no longer adds the latest committed translations

![image](https://github.com/user-attachments/assets/35bbf7af-4236-4527-b073-87fac07e9016)

### 👟 Reproduction steps

Go to https://weblate.kuma.pet/projects/uptime-kuma/uptime-kuma/

### 👀 Expected behavior

The latest committed translation keys should be added

### 😓 Actual Behavior

A conflict error is preventing the addition of the latest translation keys

### 🐻 Uptime-Kuma Version

1.23.13

### 💻 Operating System and Arch

debian

### 🌐 Browser

Chrome

### 🖥️ Deployment Environment

- Runtime: 
- Database: 
- Filesystem used to store the database on: 
- number of monitors:

**Comment by louislam** [comment]
Thanks for the report, it should has been fixed manually.

**Comment by CommanderStorm** [comment]
I have no clue how this happend this time around 👀

**Comment by louislam** [comment]
> I have no clue how this happend this time around 👀

Because of #4717, it removed a key `jsonQueryDescription`, which makes wondering:

- Is it a mistake? Because `jsonQueryDescription` is still using in https://github.com/louislam/uptime-kuma/blob/master/src/pages/EditMonitor.vue

- Why [prevent-file-change.yml](https://github.com/louislam/uptime-kuma/blob/master/.github/workflows/prevent-file-change.yml) did not block that pr, because modify language files should not be allowed.

**Comment by CommanderStorm** [comment]
> * Is it a mistake? Because `jsonQueryDescription`..

Kind of intentional
=> https://github.com/louislam/uptime-kuma/pull/4717/files#r1636935222

**Comment by CommanderStorm** [comment]
should apparently have merged weblate afterwards.
Really unfortunate, that this just silently fails instead..

**Comment by mattv8** [comment]
My apologies for creating an issue with this. I should have just cleared the strings rather than remove the keys...
