### ISSUE TITLE
How to modify robots.txt?

### ISSUE THREAD

**Issue by BrianZbr** [louislam/uptime-kuma#5073]
### ⚠️ Please verify that this question has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

I want my public dashboard to be indexed by Google. If I go to {my public domain}/robots.txt, or `curl localhost:3001/robots.txt`, I see that it disallows all. I don't see where this file exists so I'm not sure how to modify it. I tried putting my own in the main folder with `index.html` but this does nothing.

### 🐻 Uptime-Kuma Version

how to check?

### 💻 Operating System and Arch

official docker container

### 🌐 Browser

doesn't matter

### 🖥️ Deployment Environment

n/a

**Comment by CommanderStorm** [comment]
Please see our settings ^^
![image](https://github.com/user-attachments/assets/b9744544-7e92-4643-9ae5-d7eda1bf6d0c)
