### ISSUE TITLE
The location of the stored information is modified

### ISSUE THREAD

**Issue by lsx1205** [louislam/uptime-kuma#5081]
### ⚠️ Please verify that this question has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

kuma uses sqlite as the storage method, we want to do a unified, we use the cloud database to store information, is there any configuration can change the storage location to mysql?

### 🐻 Uptime-Kuma Version

1.23.13

### 💻 Operating System and Arch

rocky linux 9.4

### 🌐 Browser

google chrome 

### 🖥️ Deployment Environment

- Runtime: 
- Database: 
- Filesystem used to store the database on: 
- number of monitors:

**Comment by apio-sys** [comment]
This is on the roadmap for v2 see also #4500 .

**Comment by lsx1205** [comment]
Will the ability to access external databases be added in a later version?

**Comment by apio-sys** [comment]
Have a look in the v 2.0 description, it's in the roadmap.
