### ISSUE TITLE
kuma's certificate monitoring problem

### ISSUE THREAD

**Issue by lsx1205** [louislam/uptime-kuma#5083]
### ⚠️ Please verify that this question has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

Is there a way for kuma to configure it to monitor only the certificate expiration time and not the website itself? Because the site has many sites, it is possible that only one site is unavailable, not all of them

### 🐻 Uptime-Kuma Version

1.23.13

### 💻 Operating System and Arch

rocky linux 9.4

### 🌐 Browser

google chrome 

### 🖥️ Deployment Environment

- Runtime: 
- Database: 
- Filesystem used to store the database on: 
- number of monitors:

**Comment by lsx1205** [comment]
Is this heartbeat interval related to certificate monitoring? Is certificate monitoring updated once the heartbeat is performed?

**Comment by lsx1205** [comment]
Another question is whether kuma's logs can be mounted externally when using docker containers. Otherwise it is not very convenient to clean the log, or does kuma have a built-in log cleaning function?

**Comment by CommanderStorm** [comment]
> configure it to monitor only the certificate expiration time and not the website itself?

To monitor a certificate, we need to look at a website. I don't know what you are asking, but getting certificates from websites without asking the website for certificates is  impossible.

> Because the site has many sites, it is possible that only one site is unavailable, not all of them

We have group monitors available which function via the `any(monitor.status == DOWN for monitor in monitors)` method if that is what you are asking.
I don't see a problem with having more monitors (up to the scaling limit, see #4500)

**Comment by CommanderStorm** [comment]
> Is this heartbeat interval related to certificate monitoring? Is certificate monitoring updated once the heartbeat is performed? Or does the heartbeat have nothing to do with certificate monitoring, and an alarm is generated when the alarm period reaches?

Certificates get checked on every heartbeat if the option is enabled.
Checking them is extremely cheap on modern hardware => no need to optimised this part

**Comment by CommanderStorm** [comment]
> Another question is whether kuma's logs can be mounted externally when using docker containers. Otherwise it is not very convenient to clean the log, or does kuma have a built-in log cleaning function?

Which path did you deploy with? (Node vs docker)
You left that field blank.

Docker logs to standard out and is collected via the default driver. You can access logs via `docker logs ...`. Said driver by default rotates logs.
For pm2, please see our wiki how to set up pm2-logrotate.
