### ISSUE TITLE
Data too long for column `info_json` when monitoring cloudfunctions.net Endpoints

### ISSUE THREAD

**Issue by David-Development** [louislam/uptime-kuma#5087]
### 📑 I have found these related issues/pull requests

-

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### Description

When monitoring Google cloudfunctions `ER_DATA_TOO_LONG` errors are thrown in the logs and no Certificate Expiry dates are shown.

### 👟 Reproduction steps

Any fake cloudfunction url does the trick for testing even though it returns 404 - Like: https://abc.cloudfunctions.net/

### 👀 Expected behavior

No errors in the logs / Certificate Expiry etc. are displayed correctly. Considering that the JSON it's trying to save has a significant amount of characters it probably makes sense to strip some infos from it..? 

### 😓 Actual Behavior

No certificate expiry date is visible / errors are shown in logs

### 🐻 Uptime-Kuma Version

2.0.0-dev

### 💻 Operating System and Arch

Docker

### 🌐 Browser

Google Chrome 128.0.6613.114

### 🖥️ Deployment Environment

- Runtime: Docker
- Database: MariaDB 11.4.3
- Filesystem used to store the database on: HDD
- number of monitors: 5

### 📝 Relevant log output

```shell
uptime-kuma    |   code: 'ER_DATA_TOO_LONG',
uptime-kuma    |   errno: 1406,
uptime-kuma    |   sqlState: '22001',
uptime-kuma    |   sqlMessage: "Data too long for column 'info_json' at row 1",
uptime-kuma    |   sql: 'insert into `monitor_tls_info` (`info_json`, `monitor_id`) values (\'{\\"valid\\":true,\\"certInfo\\":{\\"subject\\":{\\"CN\\":\\"misc.google.com\\"},\\"issuer\\":{\\"C\\":\\"US\\",\\"O\\":\\"Google Trust Services\\",\\"CN\\":\\"WR2\\"},\\"subjectaltname\\":\\"DNS:misc.google.com, DNS:*.actions.google.com, 
....
:EC:'... 60832 more characters
uptime-kuma    | }
```

**Comment by louislam** [comment]
Thanks for the report. I think we have to review all VARCHAR/TEXT fields.

**Comment by Abhay2133** [comment]
I’m eager to contribute to this issue and have already run it locally. I've even fixed it by manually changing the database schema. Could you assign it to me?

**Comment by CommanderStorm** [comment]
We don't assign people to issues. Firstly, because only contributors and the issue createe can be assigned and we don't believe that the bureaucracy adds value.

Feel free to contribute a fix.
Also make sure that
- existing collumns create before any migration and
- the insertion into that collumn is are handled correctly
