### ISSUE TITLE
Help with configuration

### ISSUE THREAD

**Issue by vellanix** [louislam/uptime-kuma#5088]
### ⚠️ Please verify that this question has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

I need some help to configure a monitor.

I have to call a URL that return a JSON and then check a value in the JSON.

curl https://pool.braiins.com/accounts/profile/json/btc/ -H "SlushPool-Auth-Token: xxxxxxxxxxxxxxx"

that return

`{
  "username": "vellanix",
  "btc": {
    "low_workers": 0,
    "off_workers": 0,
    "ok_workers": 4,
    "dis_workers": 0,
  }
}`

and I want to check that the value of "ok_workers" is 4.

My monitoring setup is:
<img width="849" alt="Screenshot 2024-09-05 alle 11 45 32" src="https://github.com/user-attachments/assets/b14bac42-5c6a-4978-bae7-4f2864963833">

but unfortunately doesnt work, and in the LOG file I see:

`2024-09-05T11:46:21+02:00 [MONITOR] WARN: Monitor #8 'Workers': **Failing: Cannot read properties of undefined (reading 'toString')** | Interval: 60 seconds | Type: json-query | Down Count: 0 | Resend Interval: 0`

What's wrong?
Thank you

### 📝 Error Message(s) or Log

2024-09-05T11:46:21+02:00 [MONITOR] WARN: Monitor #8 'Workers': Failing: Cannot read properties of undefined (reading 'toString') | Interval: 60 seconds | Type: json-query | Down Count: 0 | Resend Interval: 0

### 🐻 Uptime-Kuma Version

1.23.13

### 💻 Operating System and Arch

docker

### 🌐 Browser

chrome

### 🖥️ Deployment Environment

- Runtime: 
- Database: 
- Filesystem used to store the database on: 
- number of monitors:

**Comment by CommanderStorm** [comment]
Sorry for the late reply

First of all, are you sure that the above is returned from the API? The reason I am asking is that that is not valid JSON (see the last `,`).

Could you try `$.btc.ok_workers`?
We have improved the provided docs for this, but this is waiting for #4500

If this does not work, I am asssuming this is because the invalid JSON issue noted above :eyes:
