### ISSUE TITLE
Send hourly status notification alert

### ISSUE THREAD

**Issue by yaihui** [louislam/uptime-kuma#5089]
### ⚠️ Please verify that this question has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

Hi, I am currently monitoring a few actuator endpoints (monitor type http). When one of them goes down, it will send an email (smtp) alert.

Question: I would like to configure an alert hourly, stating status UP or DOWN (not just on status change). I would expect an hourly status update. is possible to configure this? if so, how do I go about doing it?

### 🐻 Uptime-Kuma Version

2.19.3

### 💻 Operating System and Arch

Kubernetes

### 🌐 Browser

Google Chrome

### 🖥️ Deployment Environment

- Runtime: 
- Database: 
- Filesystem used to store the database on: 
- number of monitors:

**Comment by CommanderStorm** [comment]
Why would you like the have hourly spam for this? Monitoring is only effective if signal to noise is not oo high..

**Comment by yaihui** [comment]
I totally agree with what you said. Unfortunately this is a customer requirement to be alerted hourly on the status, thus am wondering if it can be configured.

**Comment by CommanderStorm** [comment]
It why??
We don't support this as I could not imagine a usecaee for this. The noise alone is just unbearable..

Please let them give this in writing to make sure that this is not a miscommunication.

You will need to use https://uptime-kuma-api.readthedocs.io/en/latest/ or similar to get the status and push them an hourly notification.

**Comment by yaihui** [comment]
The reason they gave was that as it is a critical system, they don't want to risk uptime kuma being down and they are not aware if the system really goes down. If they don't receive hourly alerts means uptime kuma is down.

Noted on your suggestion, thanks for the reply!

**Comment by apio-sys** [comment]
Then monitor your monitor to make sure it's up...

**Comment by CommanderStorm** [comment]
Given the level of noise, nobody would notice a few notifications missing. I don't believe your customers have thought this through.

Closing as not planned
