### ISSUE TITLE
if i run it and i go to the web there is nothing

### ISSUE THREAD

**Issue by Snzy027** [louislam/uptime-kuma#509]
![IMG_20210929_185010](https://user-images.githubusercontent.com/85831601/135262954-226d0293-3ee4-4f38-a6ad-8db712a89275.jpg)

**Comment by louislam** [comment]
It looks like you did not follow the installation guide. Can't help without detail.

**Comment by Snzy027** [comment]
after I reinstall the error appears like this (previously I renamed "./dist/index.html to index.js and the second ././index.html" , but the error is as above And in the console there is no error 
![Uploading IMG_20210929_193040.jpg…]()
)

**Comment by Snzy027** [comment]
after I reinstall the error appears like this (previously I renamed "./dist/index.html to index.js and the second ././index.html" , but the error is as above And in the console there is no error 
![Uploading IMG_20210929_193040.jpg…]()

**Comment by louislam** [comment]
Please install it on Linux/Windows/MacOS with Node.js or using Docker.

Replit is not supported.
