### ISSUE TITLE
Cannot login into /metrics 401

### ISSUE THREAD

**Issue by CrazyWolf13** [louislam/uptime-kuma#5095]
### 📑 I have found these related issues/pull requests

I couldn't really find any related things.

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### Description

I tried to setup prometheus, but cannot get the login to work, I always get 401, even tough I set it up exactly like here:
https://github.com/louislam/uptime-kuma/wiki/Prometheus-Integration

Edit: I have 2 FA enabled, but without it, it also seems like it doesn't work.

### 👟 Reproduction steps

1. Try to login into /metrics
2. Use the same credentials as uptime-kuma, as suggested in docs
3. get a 401 unathorized

### 👀 Expected behavior

I expect a successful login or better docs on what credentials to use for prometheus /metrics endpoint.

### 😓 Actual Behavior

I'm getting a 401 Unathorized on prometheus and a unsuccessful  (repeated) login on browser

### 🐻 Uptime-Kuma Version

1.23.13

### 💻 Operating System and Arch

Debian 12

### 🌐 Browser

Firefox 130.0

### 🖥️ Deployment Environment

- Runtime: Docker
- Database: embeded
- Filesystem used to store the database on: embeded
- number of monitors: 60

### 📝 Relevant log output

```shell
2024-09-09T07:18:14+02:00 [RATE-LIMIT] INFO: remaining requests: 60
2024-09-09T07:18:14+02:00 [API-AUTH] WARN: Failed API auth attempt: invalid API Key
```

**Comment by Nemric** [comment]
HI, did you set up an API key ?
In that case, you should read : https://github.com/louislam/uptime-kuma/wiki/API-Keys

**Comment by CrazyWolf13** [comment]
Ohh, thanks!!
Why was this this not written in the docs?

Will test in the evening and update here :)

**Comment by Nemric** [comment]
If I remember well it's written when you create the API key and ... I linked you the doc ;) I think you can close

**Comment by CrazyWolf13** [comment]
Yeh but not in the prometheus docs, but anyway, thanks it worked with the api key.

Thanks for the quick help!
