### ISSUE TITLE
Update Cloudflared to latest version

### ISSUE THREAD

**Issue by blockblue47** [louislam/uptime-kuma#5098]
### 📑 I have found these related issues/pull requests

Was trying to find a current request for this but doesn't seam like one was created for this in a while.

### 🏷️ Feature Request Type

Other

### 🔖 Feature description

Was looking, and it seems that Cloudflared has been updated a bunch of times since the current version bundled in the current version of Uptime Kuma.

Current Version: 2024.4.0
Latest Version: 2024.8.3

### ✔️ Solution

This isn't an urgent item at all and can be potentially updated with V2.0, but as I do use the Cloudflared config to reverse proxy my instance, having it on the latest version would be great to have to ensure that there aren't any issues or bugs.

**Comment by CommanderStorm** [comment]
If there is a reason for this comment, we can push out a patch release. As you did not say so, I am assuming the regular release cadence is sufficient.

We try to update dependencys before releases, but if you want to help us in this regard, single PRs updating dependencys (and looking at the change logs) would be appreciated.

**Comment by blockblue47** [comment]
Ahh, didn't know that the dependencies were updated before each release, guess it had been a while since the last one so didn't know.

Was just wanting to clarify if they are updated with each release, so I'll close this one then, as just wanting to validate if this would be updated going forward in future updates.
