### ISSUE TITLE
How do I set up to view the status of a monitored website without logging in and opening this app?

### ISSUE THREAD

**Issue by billowssun** [louislam/uptime-kuma#5099]
### ⚠️ Please verify that this question has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

How do I set up to view the status of a monitored website without logging in and opening this app?

### 📝 Error Message(s) or Log

NO

### 🐻 Uptime-Kuma Version

1.23.13

### 💻 Operating System and Arch

debian 5.10.218-1 

### 🌐 Browser

128.0.2739.67

### 🖥️ Deployment Environment

How do I set up to view the status of a monitored website without logging in and opening this app?

**Comment by CommanderStorm** [comment]
You could create a status page for the monitors you want to display publicly
