### ISSUE TITLE
Error when acces via internet

### ISSUE THREAD

**Issue by kry008** [louislam/uptime-kuma#510]
**Is it a duplicate question?** No
Please search in Issues without filters: https://github.com/louislam/uptime-kuma/issues?q=

**Describe the bug**
When I try to enter the status page, I always get an error, but when I click the status page button it shows correctly, but it is not possible to log in
I can only enter via the local IP address

Jak próbuje wejść na stronę statusu to zawsze wyświetla się błąd, ale gdy kliknę przycisk status page ukazuje poprawnie, ale brak możliwości zalogowania się
Mogę wejść tylko przez lokalny adres IP

**To Reproduce**

Apache2
node: 'v16.10.0', npm: '7.24.0'
Raspberry Pi 4 4GB RAM
Ubuntu 21.04 (GNU/Linux 5.11.0-1019-raspi aarch64)
pm2

**Expected behavior**
Operation in the local and external network
Działanie w sieci lokalnej i zewnętrznej

**Info**
Uptime Kuma Version: 1.7.1
Using Docker?: No
Docker Version:
Node.js Version (Without Docker only): 
OS: All
Browser: All

**Screenshots**
https://ibb.co/CmXsTL4
[https://statusowo.ml/](https://statusowo.ml/)
https://ibb.co/D86CgCR

**Comment by louislam** [comment]
Please read this: https://github.com/louislam/uptime-kuma/wiki/Reverse-Proxy

**Comment by kry008** [comment]
I have like that and still error

**Comment by louislam** [comment]
Have to provide your apache config.

**Comment by kry008** [comment]
`<IfModule mod_ssl.c>
<VirtualHost *:443>
        ServerName statusowo.ml
        ServerAlias www.statusowo.ml
        ServerAdmin webmaster@statusowo.ml
        ErrorLog ${APACHE_LOG_DIR}/error.log
        CustomLog ${APACHE_LOG_DIR}/access.log combined

        ProxyRequests Off
        <Proxy *>
          Order deny,allow
          Allow from all
        </Proxy>
        
        ProxyPass / http://127.0.0.1:3001/
        ProxyPassReverse / http://127.0.0.1:3001/
	RewriteEngine on
  	RewriteCond %{HTTP:Upgrade} websocket [NC]
  	RewriteCond %{HTTP:Connection} upgrade [NC]
  	RewriteRule ^/?(.*) "ws://localhost:3001/$1" [P,L]
        <Location />
          Order allow,deny
          Allow from all
        </Location>

   
Include /etc/letsencrypt/options-ssl-apache.conf
SSLCertificateFile /etc/letsencrypt/live/statusowo.ml/fullchain.pem
SSLCertificateKeyFile /etc/letsencrypt/live/statusowo.ml/privkey.pem
</VirtualHost>
</IfModule>
`

**Comment by kry008** [comment]
I'm change system to ubuntu LTS and now work
