### ISSUE TITLE
[Functional suggestion]   Alarm prompt function

### ISSUE THREAD

**Issue by lsx1205** [louislam/uptime-kuma#5101]
### ⚠️ Please verify that this question has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

Now there is such a situation, such as a domain name certificate alarm time, but this certificate is associated with other services, such as waf, should need a prompt function, the current expiration reminder content is [name] domain name information/remaining expiration time, can you add your own added prompt information when alarm, The current approach then adds something to the monitor name that needs attention

<img width="572" alt="1" src="https://github.com/user-attachments/assets/45d0b3d4-0931-442f-b477-68d72ed0c14d">

### 🐻 Uptime-Kuma Version

1.23.13

### 💻 Operating System and Arch

rocky linux 9.4

### 🌐 Browser

google chrome 

### 🖥️ Deployment Environment

- Runtime: 
- Database: 
- Filesystem used to store the database on: 
- number of monitors:

**Comment by lsx1205** [comment]
hello，have any suggestions ？

**Comment by CommanderStorm** [comment]
I have no clue what the question above is. 
I think you are angling for https://github.com/louislam/uptime-kuma/issues/646, but without a clear question this is not clear to me.

What might be helpfull to get better answers in the futures is [stackoverflows guidance on this](https://stackoverflow.com/help/how-to-ask)
