### ISSUE TITLE
Maximum number of redirects exceeded

### ISSUE THREAD

**Issue by zhangyingjieiloveyou** [louislam/uptime-kuma#5105]
### ⚠️ Please verify that this question has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

The page is redirected, the request status is 302, the browser accesses the page is normal, how to configure this? Please give me some advice, thank you!

### 📝 Error Message(s) or Log

WARN: Monitor #11 'web': Pending: Maximum number of redirects exceeded | Max retries: 3 | Retry: 1 | Retry Interval: 60 seconds | Type: http

### 🐻 Uptime-Kuma Version

1.23

### 💻 Operating System and Arch

CentOS Linux release 7.9.2009 (Core)

### 🌐 Browser

Google chrome 128.0.6613.120

### 🖥️ Deployment Environment

- Runtime: 
- Database: 
- Filesystem used to store the database on: 
- number of monitors:

**Comment by CommanderStorm** [comment]
How many redirects does said page take?

**Comment by zhangyingjieiloveyou** [comment]
> How many redirects does said page take?

I do not know the maximum number of redirects set by the page, but I have set the maximum number of redirects to 10000, and the effective status code has also added 302, or abnormal, do not know how to monitor the status of this redirected page, actually go to the browser to visit the web site is normal.

**Comment by CommanderStorm** [comment]
Lets ask the question a bit differently:
If you visit said page in the browser, how are you redirected?
If you do this via curl, how are you redicected?

I suspect that this is a difference in how your webpage reacts to a client which can execute js and one which cannot. What do you think about said hypothesis?

Can you share the url?

**Comment by zhangyingjieiloveyou** [comment]
> 让我们以不同的方式提出问题：如果您在浏览器中访问所述页面，您将如何重定向？如果你通过 curl 来做这个，你是如何被划分的？
> 
> 我怀疑这是你的网页对可以执行 js 的客户端和不能执行的客户端的反应的不同。你怎么看这个假设？
> 
> 您可以共享 URL 吗？



> Lets ask the question a bit differently: If you visit said page in the browser, how are you redirected? If you do this via curl, how are you redicected?
> 
> I suspect that this is a difference in how your webpage reacts to a client which can execute js and one which cannot. What do you think about said hypothesis?
> 
> Can you share the url?

Pages like this http://www.fjsn.gov.cn/; The actual access to this kind of web page is normal, but adding 302 will always be abnormal in Uptime Kuma. Is there any good way to monitor and judge this kind of web page whose redirection status is 302? Thank you for helping me.

**Comment by CommanderStorm** [comment]
![image](https://github.com/user-attachments/assets/6a0d9b45-5f89-404c-a91e-4c1e964d6238)

Yes, that is an infinite cylcle. Uptime kuma is allerting to a real issue

**Comment by zhangyingjieiloveyou** [comment]
> ![image](https://private-user-images.githubusercontent.com/26258709/367493387-6a0d9b45-5f89-404c-a91e-4c1e964d6238.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYyOTc3MjMsIm5iZiI6MTcyNjI5NzQyMywicGF0aCI6Ii8yNjI1ODcwOS8zNjc0OTMzODctNmEwZDliNDUtNWY4OS00MDRjLWE5MWUtNGMxZTk2NGQ2MjM4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTE0VDA3MDM0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWMzM2RjOTI4MjJkMDc3Y2RlYmE2NzNkYzFkOTk1NmFlNjllOGQ1ZTBhMWNkMzQ5ZGZhNTA4Mjk2NDA1NmZmY2EmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.aGz0gv2LFISvl3gpXFpK4lmJAapv9cCUBCUnGE21Amc)
> 
> Yes, that is an infinite cylcle. Uptime kuma is allerting to a real issue

Is this type of page not able to monitor whether the web page is normal?  There is still a good way for Uptime Kuma software to monitor the page as it works.
