### ISSUE TITLE
Trobule Updating to newest version

### ISSUE THREAD

**Issue by hopelesslylostadmin** [louislam/uptime-kuma#5106]
### ⚠️ Please verify that this question has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

Hi! I've recently inherited an UpdateKuma server that hasn't been updated in quite some time. I'm trying to update to the newest version and I've been having nothing but issues. I know such a massive edition jump is probably not going to be so clean, but I seem to be stuck. 

I've tried to manually update the dependencies that kept giving me deprecation errors, but i'm still getting the same errors. I'm still pretty inexperienced with Linux so there is  a very good chance I'm missing something.

I also do not know how to check Runtime. PLease let me know if there's any other information I should provide for this, thank you so much!

### 📝 Error Message(s) or Log

[2024-09-12T13_28_20_846Z-debug-0.log](https://github.com/user-attachments/files/16981049/2024-09-12T13_28_20_846Z-debug-0.log)

### 🐻 Uptime-Kuma Version

1.17.1

### 💻 Operating System and Arch

Ubuntu 22.04.4 LTS

### 🌐 Browser

Firefox 130

### 🖥️ Deployment Environment

- Runtime: no idea
- Database: sqlite
- Filesystem used to store the database on: ext4
- number of monitors: no idea how to check

**Comment by hopelesslylostadmin** [comment]
Thank you for your comment, I should have mentioned that I am following the steps under Non-Docker in the link you posted and that's what is giving me those errors.

However, the installation of make has allowed the npm install --production step to go through,'

However I'm getting errors when trying to run npm run download-dist.

This is the output i'm seeing:

> uptime-kuma@1.23.13 download-dist
> node extra/download-dist.js

Downloading dist
https://github.com/louislam/uptime-kuma/releases/download/1.23.13/dist.tar.gz
https://objects.githubusercontent.com/github-production-release-asset-2e65be/382496361/05a726c8-fc24-423e-9139-f62e6d772c8b?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=releaseassetproduction%2F20240912%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20240912T155821Z&X-Amz-Expires=300&X-Amz-Signature=ee550e5bff66bcfe062d1455b093a7801688202fc5733fdb544362839ebd3afd&X-Amz-SignedHeaders=host&actor_id=0&key_id=0&repo_id=382496361&response-content-disposition=attachment%3B%20filename%3Ddist.tar.gz&response-content-type=application%2Foctet-stream
node:events:491
      throw er; // Unhandled 'error' event
      ^

Error: read ECONNRESET
    at TLSWrap.onStreamRead (node:internal/stream_base_commons:217:20)
Emitted 'error' event on ClientRequest instance at:
    at TLSSocket.socketErrorListener (node:_http_client:481:9)
    at TLSSocket.emit (node:events:513:28)
    at emitErrorNT (node:internal/streams/destroy:157:8)
    at emitErrorCloseNT (node:internal/streams/destroy:122:3)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) {
  errno: -104,
  code: 'ECONNRESET',
  syscall: 'read'
}

**Comment by CommanderStorm** [comment]
Econreset usually means you have bad/non existent internet connectivity to the asset Server of GitHub. Could you please use curl to make sure that no firewall is blocking your connectivity?

**Comment by baokhuu-phoenix** [comment]
> Econreset usually means you have bad/non existent internet connectivity to the asset Server of GitHub. Could you please use curl to make sure that no firewall is blocking your connectivity?

Hi @CommanderStorm I have the same issue, because github was blocked on the server that I want to install uptimekuma, is there anyway that I can install without having access to github ?

**Comment by CommanderStorm** [comment]
Use the docker installation path instead. This way you don't need to git clone from github, but you need docker to be not blocked instead..

In the end, you need an allowance either way..
