### ISSUE TITLE
Notification Option - Wait for n number of down events before sending.

### ISSUE THREAD

**Issue by KevinFromUpThere** [louislam/uptime-kuma#5112]
### 📑 I have found these related issues/pull requests

I've searched but not found any related PRs

### 🏷️ Feature Request Type

Change to existing notification-provider

### 🔖 Feature description

You should add the option WAIT N NUMBER OF DOWN EVENTS BEFORE SENDING (default 1)

I get so many notifications that are just very temporary timeouts.  Then next check (1 minute usually) it's fine.  For services running on slower machines or whatever, I get a lot of these.  It makes too much noise, notifications are ignored and then what's the point of them.

### ✔️ Solution

In my use case, I would set WAIT 2 DOWN EVENTS BEFORE SENDING NOTIFICATION.

The volume of "noise" i would get would go down very substantially. 

### 📝 Additional Context

Also, at my work we use a different software, and the devs there would love this but don't have it, as they currently ignore notifications as 90% of them are back up in 1 minute.

**Comment by CommanderStorm** [comment]
I think the setting you are overlooking is the retry setting.
It does exactly as you want..
We changed this to default to 0 to prevent the high number of confused users

Closing as resolved

**Comment by KevinFromUpThere** [comment]
That's exactly it, thank you so much @CommanderStorm
