### ISSUE TITLE
all docker up state and ping are down as of today

### ISSUE THREAD

**Issue by IIIdefconIII** [louislam/uptime-kuma#5113]
### 📑 I have found these related issues/pull requests

i habe not but can unselect it

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### Description

![image](https://github.com/user-attachments/assets/dafe3c5b-3446-4c7f-a3a3-fb3ff3bd6de4)

### 👟 Reproduction steps

just open my internatl page and all is down

### 👀 Expected behavior

seeying docker containers and pings up

### 😓 Actual Behavior

see scrensit, noit rplying to docker containers an htpp/hptps local links wihle portainer say all it  up and evyerhting works  locallt

### 🐻 Uptime-Kuma Version

latest

### 💻 Operating System and Arch

Docker DSM Synology latest

### 🌐 Browser

Chomr

### 🖥️ Deployment Environment

- Runtime: 
- Database: 
- Filesystem used to store the database on: 
- number of monitors: 

### 📝 Relevant log output

```shell
i have  no atm
```

**Comment by IIIdefconIII** [comment]
hi dev, by any change saw my message here? other users i have spoken to personally dont have this problem

**Comment by CommanderStorm** [comment]
Could you clarify what `i have  no atm` means in regards to logs?

**Comment by IIIdefconIII** [comment]
> Could you clarify what `i have no atm` means in regards to logs? Could you please also clarify the `Deployment Environment` which you omitted above?
> 
> Above you stated that you are using http to monitor other docker containers. How have you configured your `docker network`

sure hes 1 example

![image](https://github.com/user-attachments/assets/eb3c8033-93bb-4160-9091-0f18a866c46e)
![image](https://github.com/user-attachments/assets/9b47493d-815c-4ff1-ba8f-4f6b3f7249ea)


The test says OK
![image](https://github.com/user-attachments/assets/3c778880-66fd-40de-ad2e-68414c4f7b0b)

its almsot like they pushed an update and since all monitors arew down even ping or docker socks

**Comment by IIIdefconIII** [comment]
it still all down for some reaon it also doesnt talk to the docker  envirmont anymore like this one:
As exmaple this container runs fine...
uptime just doesnt talk to the docker containers anymore ...

![image](https://github.com/user-attachments/assets/6d7357bc-2ad6-4069-b03e-17c9249c9fd2)
![image](https://github.com/user-attachments/assets/d917bfae-17c6-4fc0-a6b7-a63620e76abe)

**Comment by IIIdefconIII** [comment]
![image](https://github.com/user-attachments/assets/6e69158d-2b09-4bb9-9593-fd89e2d3044a)

**Comment by IIIdefconIII** [comment]
ther still down and even the docker up doesnt work so im kinda disappointed in the support here

**Comment by IIIdefconIII** [comment]
> Could you clarify what `i have no atm` means in regards to logs? Could you please also clarify the `Deployment Environment` which you omitted above?
> 
> Above you stated that you are using http to monitor other docker containers. How have you configured your `docker network`

yes i have, even the CF is up and running but all stays offline in the uptimekuma page

**Comment by IIIdefconIII** [comment]
> Could you clarify what `i have no atm` means in regards to logs? Could you please also clarify the `Deployment Environment` which you omitted above?
> 
> Above you stated that you are using http to monitor other docker containers. How have you configured your `docker network`

hi at that moment i didnt had acces to the logs, i have aquired brain injury so i takes some time for me to keep up everything

Here is a snap from the log files

}
[2023-04-06 03:14:08] [Error: insert into `heartbeat` (`down_count`, `duration`, `important`, `monitor_id`, `msg`, `ping`, `status`, `time`) values (0, 60, false, 11, '200 - OK', 920, 1, '2023-04-06 01:14:06.466') - SQLITE_BUSY: database is locked] {
  errno: 5,
  code: 'SQLITE_BUSY'
}
[2023-04-08 03:14:06] [Error: insert into `heartbeat` (`down_count`, `duration`, `important`, `monitor_id`, `msg`, `ping`, `status`, `time`) values (0, 60, false, 10, '200 - OK', 9, 1, '2023-04-08 01:14:05.745') - SQLITE_BUSY: database is locked] {
  errno: 5,
  code: 'SQLITE_BUSY'
}
[2023-04-08 03:14:08] [Error: insert into `heartbeat` (`down_count`, `duration`, `important`, `monitor_id`, `msg`, `ping`, `status`, `time`) values (0, 60, false, 22, '200 - OK', 66, 1, '2023-04-08 01:14:06.889') - SQLITE_BUSY: database is locked] {

**Comment by IIIdefconIII** [comment]
is there any one that might be able to helpe me try to solve this issue?

**Comment by CommanderStorm** [comment]
> kinda disappointed in the support here

Sorry, but that is the level of support that I can offer in my free time, next to the other projects...

> Here is a snap from the log files

Please have a look at the solutions in #4500
=> the issue will be resolved in v2.0, but in v1.x, you will need to apply the noted bandaid-fixes like getting faster storage, reducing retention or ping rate.

> i have aquired brain injury

get well soon

**Comment by IIIdefconIII** [comment]
> > kinda disappointed in the support here
> 
> Sorry, but that is the level of support that I can offer in my free time, next to the other projects...
> 
> > Here is a snap from the log files
> 
> Please have a look at the solutions in #4500 => the issue will be resolved in v2.0, but in v1.x, you will need to apply the noted bandaid-fixes like getting faster storage, reducing retention or ping rate.
> 
> > i have aquired brain injury
> 
> get well soon

hi, trhank for your answerr and will look furhter in it tonight,
you also got ABI? hope you get better soon, i took me 2 years before getting realy improvement

God bless!

**Comment by IIIdefconIII** [comment]
is there a way to already pull the v2 beta?
```
# UptimeKuma: Services Status__________
  uptimekuma:
    container_name: uptimekuma
    image: louislam/uptime-kuma:latest
    restart: always
    security_opt:
      - no-new-privileges:true
    ports:
      - 3001:3001
    environment:
      PUID: 0
      PGID: 0
      UMASK: $UMASK
      TZ: $TZ
      DOZZLE_LEVEL: info
      DOZZLE_TAILSIZE: 300
      DOZZLE_FILTER: "status=running"
    volumes:
      - $DOCKERDIR/uptimekuma:/app/data
      - /var/run/docker.sock:/var/run/docker.sock
```
      What image url should i use here?

**Comment by CommanderStorm** [comment]
> is there a way to already pull the v2 beta?

The beta is currently not ready.
Please see #4500 for further context.
You can subscribe to said issue or to our releases to get notifications when this is published.

We will publish a beta once all the harsh bugs are done and migration from v1 to v2 is possible (See #5075 for further context)

**Comment by IIIdefconIII** [comment]
> > is there a way to already pull the v2 beta?
> 
> The beta is currently not ready. Please see #4500 for further context. You can subscribe to said issue or to our releases to get notifications when this is published.
> 
> We will publish a beta once all the harsh bugs are done and migration from v1 to v2 is possible (See #5075 for further context)

thanks for ur readings and answer, i just removed all an setup it up again from the backup, while it does say its depricated, its now workign again
