### ISSUE TITLE
max DB size please

### ISSUE THREAD

**Issue by somethingstarted** [louislam/uptime-kuma#5114]
### 📑 I have found these related issues/pull requests

nothing exactly like this. but the closest i could find was someone with a full db https://github.com/louislam/uptime-kuma/issues/4995

### 🏷️ Feature Request Type

Settings

### 🔖 Feature description

in IP:port/settings/monitor-history, can you add a total max DB size that if it reaches this size, it starts pruning the DB even if we haven't reached number of days
![image](https://github.com/user-attachments/assets/b732c6b4-c2ce-440b-bb10-729e71e174a0)

### ✔️ Solution

ability to choose max db size, where it prunes oldest first even if max days haven't been reached yet. i'd like to have it store the max number of days worth of info in (size allocated for this container)

would also be cool if it checked the max space available if installed on a VM or bare metal. (idk of a way to do that if it's a container) 

### ❓ Alternatives

just that.

**Comment by CommanderStorm** [comment]
In V2 we only store aggregated information. This effectively makes the db-growth not an issue anymore.
See #4500 for further context.

I think this is resolved, or am I missing a part of the feature request or the reason you created it? 🤔
