### ISSUE TITLE
TImeout Issue 

### ISSUE THREAD

**Issue by hritik1432** [louislam/uptime-kuma#5121]
### 📑 I have found these related issues/pull requests

During the day numerous alerts of a monitor timing out with the message 'timeout of 48000ms exceeded' is reported. Then it works again, and then another timeout message is reported.

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### Description

During the day numerous alerts of a monitor timing out with the message 'timeout of 48000ms exceeded' is reported. Then it works again, and then another timeout message is reported.

### 👟 Reproduction steps

![Screenshot from 2024-09-20 12-48-37](https://github.com/user-attachments/assets/60fe4eb7-a200-4825-a102-d26d5bedcfa5)
as you it getting time out issue regular on fixed time .

### 👀 Expected behavior

Resolve the timeout issue in my uptime.

### 😓 Actual Behavior

Getting timeout issue in my uptime regulary on specific time like morning 9am IST i start getting timeout issue .

### 🐻 Uptime-Kuma Version

 Version: 2.0.0-dev

### 💻 Operating System and Arch

Ubuntu 22.04 

### 🌐 Browser

not using browser 

### 🖥️ Deployment Environment

- Runtime: nodejs 18.20.3
- Database: mysql
- Filesystem used to store the database on: SSD
- number of monitors: 26

### 📝 Relevant log output

```shell
nothing in log
```

**Comment by CommanderStorm** [comment]
Could you share the url?
This way we can rule out that this is a regression in V2 via https://uptime.kuma.pet
Also what are the request interval, retries, ...

**Comment by hritik1432** [comment]
usrl like : https://www.example.co.in/#/
Heartbeat Interval (Check every 60 seconds) : 60
retries:4

**Comment by furchtlos76** [comment]
I had the same, like for 3 days, but as a added google.com, too and all sites inkl. google.com are showing offline, timeout, and online again like 2-3 times a day for 3 days, my guess is, there where short problems with the machine where the uptime monitor is running on (vps) like firewall, connection something like this, and the timeouts came because uptime kuma could not get on?
