### ISSUE TITLE
Resend Notification Configuration Help

### ISSUE THREAD

**Issue by kirankumar-grootan** [louislam/uptime-kuma#5126]
### ⚠️ Please verify that this question has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

Hi,

I configured http monitor with resend notification 50. But only one notification is being send. 

IDK shouldn't Uptime Kuma send notification alert every 30 second for 50 times? or is my understanding wrong?
<img width="1113" alt="Screenshot 2024-09-24 at 12 02 36 AM" src="https://github.com/user-attachments/assets/20f9380f-4857-4687-8600-e827c9c1225b">

### 🐻 Uptime-Kuma Version

1.23.13

### 💻 Operating System and Arch

Docker

### 🌐 Browser

Chrome

### 🖥️ Deployment Environment

- Runtime: 
- Database: 
- Filesystem used to store the database on: 
- number of monitors:

**Comment by kirankumar-grootan** [comment]
I came to an understanding that 50 means it doesn't send the alert 50 times. it sends another alert on 50th failure. can anyone confirm this ?

**Comment by rtadams89** [comment]
Yes, it means it will resend a notification every 50 checks. I think the language is pretty clear already.

**Comment by CommanderStorm** [comment]
Don't think the suggested rephrasing in https://github.com/louislam/uptime-kuma/issues/5126#issuecomment-2369246488 is actually clearer.

What is true is that we might want to be a bit more visual in this, for example via a small ℹ️ -icon, which shows a small grafic. My rationale is that our community provided transaltions might be misunderstandable => aiding in this via a grafic might be benefitial.
PRs welcome, Given that the suggested rephrasing is not clerer, I am going to close this as resolved.
