### ISSUE TITLE
URLs not showing in uptime dashboard

### ISSUE THREAD

**Issue by RenuShellkode** [louislam/uptime-kuma#5129]
### 📑 I have found these related issues/pull requests

We have 90+ URLs in uptime , when we open the dashboard it is taking more than 45 minutes to list all the 
urls .

![image](https://github.com/user-attachments/assets/aea579c0-c765-4e23-b837-f38a1018d684)

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 👟 Reproduction steps

Add 40+ URLs

### 👀 Expected behavior

home page should load 

### 😓 Actual Behavior

home page taking more time load 

### 🐻 Uptime-Kuma Version

1.23.11

### 💻 Operating System and Arch

ubuntu 24

### 🌐 Browser

chrome

### 🖥️ Deployment Environment

- Runtime: 
- Database: 
- Filesystem used to store the database on: 
- number of monitors:

**Comment by tifirifi** [comment]
Hi,

The issue you mentioned is known and will be addressed in the upcoming 2.0 release of Uptime Kuma. Version 2.0 is focused on improving performance, especially for larger numbers of monitors. You can track the progress or contribute here: [GitHub Issue #4500](https://github.com/louislam/uptime-kuma/issues/4500).

For now, try reducing monitor history retention, increasing check intervals, or pausing less essential monitors to mitigate performance issues.

**Comment by CommanderStorm** [comment]
My bet would be that https://github.com/louislam/uptime-kuma/pull/5025 resolved this issue and have marked said PR as such
