### ISSUE TITLE
Adding a new monitor via API problem in NTFY

### ISSUE THREAD

**Issue by mrxorao** [louislam/uptime-kuma#5133]
### 📑 I have found these related issues/pull requests

kuma log

2024-09-28T03:36:15+01:00 [MONITOR] ERROR: Cannot send notification to kuma
Error: Error: AxiosError: Request failed with status code 400 {"code":40018,"http":400,"error":"invalid request: actions invalid; parameter 'url' is required for action 'view'","link":"https://ntfy.sh/docs/publish/#action-buttons"}
    at Ntfy.throwGeneralAxiosError (/app/server/notification-providers/notification-provider.js:38:15)
    at Ntfy.send (/app/server/notification-providers/ntfy.js:72:18)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Monitor.sendNotification (/app/server/model/monitor.js:1427:21)
    at async beat (/app/server/model/monitor.js:964:21)
    at async safeBeat (/app/server/model/monitor.js:1032:17)

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 👟 Reproduction steps

When I add it manually it works perfectly but when I add a new monitor via api with the NTFY notification it gives me this error. I've tested SMTP notification and it works fine.

### 👀 Expected behavior

Receive notification on NTFY

### 😓 Actual Behavior

I don't get the notification on ntfy

### 🐻 Uptime-Kuma Version

1.23.13

### 💻 Operating System and Arch

ubuntu 22

### 🌐 Browser

edge

### 🖥️ Deployment Environment

- Runtime: 
- Database: 
- Filesystem used to store the database on: 
- number of monitors:

**Comment by CommanderStorm** [comment]
This is fixed in v2.0 but has not been back ported to the 1.23.x series. See #4500 for additional details on said release

V2
https://github.com/louislam/uptime-kuma/blob/b287a25de735d14c6e078d57e99b4587f10697cd/server/notification-providers/ntfy.js#L59-L67

1.23.x
https://github.com/louislam/uptime-kuma/blob/936665aac32ae86834723af695b21e54c38f616a/server/notification-providers/ntfy.js#L54
