### ISSUE TITLE
Regarding the Status

### ISSUE THREAD

**Issue by Aakhyan** [louislam/uptime-kuma#5134]
### ⚠️ Please verify that this question has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

Hi,

I'm new to UptimeKuma and I was wondering that can I setup a 3rd status? i.e. **Green for Up/Success**, **Red for Down/Failed** & **Grey for no result**?
For Push Based Notifications.

Currently, as per the [URL](https://github.com/louislam/uptime-kuma/issues/279#issuecomment-1356352436), only Up or Down Status are allowed.

This will allow us to monitor a few more status which we get from the services.

@louislam any help would be appriciated.

### 🐻 Uptime-Kuma Version

1.23.13

### 💻 Operating System and Arch

AlmaLinux 9

### 🌐 Browser

Google Chrome

### 🖥️ Deployment Environment

- Runtime: NodeJS v20.17.0
- Database: sqlite
- Filesystem used to store the database on: SSD
- number of monitors: 1

**Comment by CommanderStorm** [comment]
That is not currently a feature we support

**Comment by Aakhyan** [comment]
@CommanderStorm Would it be possible to add this feature in the upcoming 2.0 version?
Or could you guide, if I want to add into the current code, then how could I perform it?

My request is like that:
A. If the PUSH request is OK, then its UP.
B. If the PUSH request if FAIL, then its DOWN.
C. If there is no PUSH request, then either show a 3rd status, or skip that entry (so that the status bar would show it like: Green-Grey-Green status).

**Comment by CommanderStorm** [comment]
What is your concrete goal? Is this possibly already covered via retries and the associated Pending status?

**Comment by Aakhyan** [comment]
@CommanderStorm 
I'm new to the UK, so i'm testing out the functionalities. What I liked the most about UK is its PUSH based notifications and its simplicity. 
The URL takes the status and msg status and post it to the UK monitor as per the values put.


So basically, i'm developing an dashboard for monitoring specific services which are logs based. Thus, I have built bash & powershell scripts to get their keywords.

So when these specific keywords are triggered, it sends the curl-based Push request to the UK for the status update.

Now, if these keywords are not found, I wish to have that day's status being skipped, rather than marking it as Up or down. If skip can't happen, then adding a 3rd status can be an option.

The logs check are daily based only.


Looking forward to your suggestions. If it can be done via the retries or anything else, i'm open to it.

**Comment by CommanderStorm** [comment]
We already handle your use case. No need to introduce a fith status (there is maintenance and pending too, next to up/down).
If you set retries=1 and check once a day, the system behaves as requested.

On receiving down, it goes into the (a bit confusingly names) pending mode. After 1 retry it either goes down or up based on the next push.
Failed check-ins are handled as if the monitor was set to down, but don't carry the message with the context you would otherwise set.
