### ISSUE TITLE
Uptime Kuma only showing last 11mins on status page

### ISSUE THREAD

**Issue by jl94x4** [louislam/uptime-kuma#5135]
### ⚠️ Please verify that this question has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

![image](https://github.com/user-attachments/assets/15a49bf4-c516-4e3b-8e7a-00fdb52e59b0)

I only see the last 11minutes, I was under the impression this would show the last 24 hours?

### 📝 Error Message(s) or Log

No errors

### 🐻 Uptime-Kuma Version

1.23.13

### 💻 Operating System and Arch

UNRAID 7

### 🌐 Browser

Chrome

### 🖥️ Deployment Environment

- Runtime: 
- Database: 
- Filesystem used to store the database on: 
- number of monitors:

**Comment by apio-sys** [comment]
That's just the current status bar (AFAIK showing up to the last 40 minutes). You can see much more detail drilling down in your monitor and selecting a time span in your graph.

**Comment by jl94x4** [comment]
> That's just the current status bar (AFAIK showing up to the last 40 minutes). You can see much more detail drilling down in your monitor and selecting a time span in your graph.

I see the extended stuff in the backend, is there no way to have this data shown on the status page?

**Comment by apio-sys** [comment]
Ah, I see what you mean. I'm usually only looking at backend. For the status pages, there is a discussion around this topic here #637 . So you can contribute there and close this here as duplicate/ungoing discussion.

**Comment by CommanderStorm** [comment]
Counfiguring the heartbeat range for the status page is tracked here
- https://github.com/louislam/uptime-kuma/issues/1888

https://github.com/louislam/uptime-kuma/issues/637 is about adding the ping graph (the one showing the latency over time)

In v2, this should be possible from a performance perspective, but needs implementing in the frontend.
