### ISSUE TITLE
add Access logs

### ISSUE THREAD

**Issue by firefart** [louislam/uptime-kuma#5136]
### 📑 I have found these related issues/pull requests

-

### 🏷️ Feature Request Type

Other

### 🔖 Feature description

Currently there are no access logs when run without a reverse proxy. 

### ✔️ Solution

https://github.com/expressjs/morgan

Should be as easy as

```js
var express = require('express')
var morgan = require('morgan')
var app = express()
app.use(morgan('combined'))
```

**Comment by CommanderStorm** [comment]
What operation are you missing need access logs for?

I don't think that [expressjs/morgan](https://github.com/expressjs/morgan) is quite what you want as this would spam the log with status page related events but would ommit the actual events via websockets..

**Comment by CommanderStorm** [comment]
To prevent an XY-Problem, why do you want access logs for http-requests?
Is this related to https://github.com/louislam/uptime-kuma/issues/3481 ?

**Comment by firefart** [comment]
To see who called the backend and the status page. Currently you need to put a reverse proxy in front of it to get access logs. Websockets are usually not part of the access logs

**Comment by CommanderStorm** [comment]
And why do you want to know that specifically? That seems pretty noisy and not actionable for me.

**Comment by firefart** [comment]
If you put something on the internet, you want to know what is happening. If you are concerned about being too noisy, make it optional.
It’s somehow related but I don’t need audit logs, just normal access logs like every webserver out there

**Comment by CommanderStorm** [comment]
>  want to know what is happening

We already do log for interesting events, no request logs required.
What are you concerned about specifically? Is there something which we are not logging that we should?

**Comment by firefart** [comment]
this conversation is leading to nothing if you don’t understand what access logs are and why they are needed. closing this issue and finding an alternative, thanks

**Comment by CommanderStorm** [comment]
I was mostly probing to see if this is a debug or info thing, but if this is not a need for you this is fine by be.

And yes, I don't quite understand why the noise of access logs is usefull for operating the system. (Request logs likely don't fulfill auditing requirements => not usefull for that)
