### ISSUE TITLE
Group as tag in Prometheus

### ISSUE THREAD

**Issue by mgoeppl** [louislam/uptime-kuma#5147]
### 📑 I have found these related issues/pull requests

Now with the possibility of grouping monitors, there should be a group tag in the prometheus /metrics endpoint.
I personally have multiple monitors with the same name in different groups (e.g. mysql monitoring in both Docker and the service monitoring itself for quicker identification of the fault). 
Also, in another setup, I have docker containers with the same name on multiple hosts. Identifying them with Prometheus alerts is not possible at this time.

### 🏷️ Feature Request Type

Other

### 🔖 Feature description

You should add the group name to the labels within the /metrics endpoint.

### ✔️ Solution

The following is the current layout of an example metric within the /metrics endpoint:
`monitor_status{instance="instance", job="uptime-kuma", monitor_hostname="null", monitor_name="example.com", monitor_port="null", monitor_type="http", monitor_url="https://example.com"}`

I'd like to be able to parse them by group, too:
`monitor_status{instance="instance", job="uptime-kuma", monitor_hostname="null", monitor_name="example.com", monitor_port="null", monitor_type="http", monitor_group="group", monitor_url="https://example.com"}`

**Comment by CommanderStorm** [comment]
Hi Moritz, agree with the feature but I think tracking this in https://github.com/louislam/uptime-kuma/issues/3905 is better => closing as a duplciate

Also there are some unresolved questions around how nested groups should be handeld in said issue.
