### ISSUE TITLE
Multiple Vulnerabilities in Base Image (Debian 12.7) used by uptime-kuma

### ISSUE THREAD

**Issue by EdgarPsda** [louislam/uptime-kuma#5150]
DO NOT PROVIDE ANY DETAILS HERE. Please privately report to https://github.com/louislam/uptime-kuma/security/advisories/new.

Why need this issue? It is because GitHub Advisory do not send a notification to @louislam, it is a workaround to do so.

Your GitHub Advisory URL: https://github.com/louislam/uptime-kuma/security/advisories/GHSA-m435-98xq-gf69

**Comment by louislam** [comment]
Op concerned that the docker image `base2` is outdated, but V2 is not yet released.
