### ISSUE TITLE
Guide on how to set uptime kuma on dirctadmin and cpanel

### ISSUE THREAD

**Issue by webdevkinsuk** [louislam/uptime-kuma#5155]
### 📑 I have found these related issues/pull requests

none

### 🏷️ Feature Request Type

Deployment, Other

### 🔖 Feature description

it a wiki for Guide on how to set uptime kuma on dirctadmin and cpanel

### ✔️ Solution

Guide on how to set uptime kuma on dirctadmin and cpanel

**Comment by CommanderStorm** [comment]
Repeating it 3x does not make it clearer..
What do you mean by "to set uptime kuma" precicely?
Monitoring something or deploying UK?

If you are asking about deploying:
- directadmin seems to be a PHP hosting thing with a lot of marketing fluff. We don't run PHP.
- cPanel can cooperate with docker, but won't help you managing it https://support.cpanel.net/hc/en-us/articles/360062418794-Can-I-run-docker-on-a-cPanel-server
  > While it is possible to run docker or k8s on a cPanel server, there are no features that would allow you to install or manage the containers from within the cPanel software.

Our installation guide is avaliable [here](https://github.com/louislam/uptime-kuma/wiki/%F0%9F%94%A7-How-to-Install) and I would recomend you to choose the docker route if you are a less experienced admin as this way comes with all the dependencys that we need in a box.

If you are asking about monitoring:
What are you trying to monitor precicely? How does it behave and what indicates `UP`?
