### ISSUE TITLE
Freeze in setting>monitor history

### ISSUE THREAD

**Issue by cyril59310** [louislam/uptime-kuma#5157]
### 📑 I have found these related issues/pull requests

none

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### Description

After going to the settings and the monitor history, it is then impossible to switch to another category.

https://github.com/user-attachments/assets/3e94e45f-d8b9-41a6-b1b5-f1e2cf07ce4d

### 👟 Reproduction steps

go to settings > monitor history and switch catégorie 

### 👀 Expected behavior

We should be able to switch from the monitor history to Docker Hosts or Tags ect

### 😓 Actual Behavior

We remain stuck on the monitor history

### 🐻 Uptime-Kuma Version

2.0.0-dev

### 💻 Operating System and Arch

windows

### 🌐 Browser

Google Chrome

### 🖥️ Deployment Environment

- Runtime: 
- Database: sqlite
- Filesystem used to store the database on: 
- number of monitors:

**Comment by mohit-nagaraj** [comment]
hey can i take his up?

**Comment by CommanderStorm** [comment]
That would be much appreciated ❤️

**Comment by louislam** [comment]
```
Uncaught (in promise) ReferenceError: process is not defined
    log util.ts:230
```

Should be related to #5118

**Comment by mohit-nagaraj** [comment]
Hey thanks for this i haven't looked into this yet as I was busy over the weekend will start on this today

**Comment by louislam** [comment]
> Hey thanks for this i haven't looked into this yet as I was busy over the weekend will start on this today

Never mind, I think I found a solution.
