### ISSUE TITLE
updating container with autoupdater style program

### ISSUE THREAD

**Issue by xxcriticxx** [louislam/uptime-kuma#516]
**Is it a duplicate question?**
NO

**Describe the bug**
I lost all my monitors when I update my docker using ouroboros/watchtower style programs. 

**To Reproduce**

1. let ouroboros/watchtower automatically update your container
 

**Expected behavior**
Not to lose all app monitors + settings. 

**Info**
Uptime Kuma Version: Version: 1.7.3
Using Docker?: Yes
Docker Version: 20.10.8
Node.js Version (Without Docker only):
OS: Ubuntu 20.04.3 LTS
Browser: Google Chrome 94.0.4606.61

**Screenshots**

**Error Log**
It is easier for us to find out the problem.

Docker: `docker logs <container id>`
PM2: `~/.pm2/logs/` (e.g. `/home/ubuntu/.pm2/logs`)

**Comment by xxcriticxx** [comment]
I used a bug because I dint know how to tag this post. I know all data is stored in volume but when the container came back after the update it was blank. I have to go through the initial settings again.

**Comment by louislam** [comment]
> I used a bug because I dint know how to tag this post. I know all data is stored in volume but when the container came back after the update it was blank. I have to go through the initial settings again.

You have to check whether the new container is still pointing to the same volume.

**Comment by xxcriticxx** [comment]
I am updating about 20 containers this way and never lost any information after the update. I will check the volume and see what happens with the next update.

**Comment by xxcriticxx** [comment]
also, the container uses UTC time when docker container TZ is set to America/New_York

**Comment by xxcriticxx** [comment]
Great piece of software you have given us. Thanks for your hard work!

**Comment by gaby** [comment]
@xxcriticxx This issue is related to how WatchTower works, not uptime-kuma. They already addressed your issue here: https://github.com/containrrr/watchtower/issues/410

As an alternative you can use an external volume, like this:
```
mkdir -p /opt/data/uptime-kuma/
docker run -d --restart=always -p 3001:3001 -v /opt/data/uptime-kuma/:/app/data --name uptime-kuma louislam/uptime-kuma:1
```

**Comment by xxcriticxx** [comment]
thanks @gaby I will adjust my setup
