### ISSUE TITLE
Custom Header support

### ISSUE THREAD

**Issue by rg9400** [louislam/uptime-kuma#517]
**Is your feature request related to a problem? Please describe.**
When monitoring services externally, a user may have those services behind some form of authentication. When using the https monitor, it may hit the authentication window but not be able to bypass it, preventing it from getting the actual status of the underlying application.

**Describe the solution you'd like**
An ability to add custom headers (value + token) and basic auth headers when configuring http monitors

**Describe alternatives you've considered**
The alternative is to open up the application (which can be a security risk or just not possible), use another service to monitor those, or try to monitor using the unauthorized http code. However, for the last option, sometimes the authentication mechanism is external to the application, such as when using a consolidated identity management system such as Organizr, Authelia, etc., and so that can give an incorrect status.

**Comment by louislam** [comment]
Duplicate of https://github.com/louislam/uptime-kuma/issues/11
