### ISSUE TITLE
Why does Uptime Kuma always connect to SQLite instead of MariaDB?

### ISSUE THREAD

**Issue by juanpablocaro7monroy** [louislam/uptime-kuma#5171]
### ⚠️ Please verify that this question has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

Hi,

I’m encountering an issue with the Uptime Kuma setup. Even though I’ve correctly configured the .env file to use MariaDB as the database, it always connects to SQLite instead of MariaDB, which I’ve specified.

### 📝 Error Message(s) or Log

Details of the issue:

Operating system: Ubuntu on a virtual machine (VM).
Uptime Kuma version: [specify the version if known].
Configured database: MariaDB.
.env file configuration:
env
Copiar código
DB_TYPE=mariadb
DB_HOST=localhost
DB_PORT=3306
DB_USER=uptimekuma
DB_PASSWORD=Qp1*z-Y.m_1#z8M.+g4H6
DB_NAME=uptimekuma
Logs: Every time I start Uptime Kuma, the logs show that it is connecting to SQLite instead of MariaDB:

shell
Copiar código
2024-10-08 18:23:45 [Info] : Starting Uptime Kuma with database type: sqlite
2024-10-08 18:23:45 [Info] : Database file: /app/data/data.sqlite
What I’ve tried:

Verify that MariaDB is running properly on the virtual machine.
Ensure that the .env file has the correct settings for MariaDB.
Restart the application multiple times, but it still keeps connecting to SQLite.
Check logs and configuration, but couldn’t find any indication of the issue.
My question is: Is there any reason why Uptime Kuma always uses SQLite instead of MariaDB, even after correctly configuring the .env file?

### 🐻 Uptime-Kuma Version

1.23.14-782-g59e70cb7

### 💻 Operating System and Arch

ubunto

### 🌐 Browser

google

### 🖥️ Deployment Environment

- Runtime: 
- Database: 
- Filesystem used to store the database on: 
- number of monitors:

**Comment by CommanderStorm** [comment]
@juanpablocaro7monroy please see #4500 Mariadb is a v2.0 feature
