### ISSUE TITLE
Inconsistent 'Online' Notifications for Push Monitor Using Telegram

### ISSUE THREAD

**Issue by Freekers** [louislam/uptime-kuma#5185]
### ⚠️ Please verify that this question has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

**Issue Summary**

I'm experiencing an issue with Telegram notifications while using UptimeKuma to monitor my servers. Specifically, I'm using the Push monitor type.

**Problem Details**

- Down Notification: The 'Down' notifications are working correctly; they arrive via Telegram without any issues.
- Online Notification: The 'Online' notifications, however, are inconsistent. Sometimes they are sent, but most of the time they are not.
- Web Interface: In the UptimeKuma web interface, the status changes are logged correctly, showing both the 'up' and 'down' states without issue.
- Affected Monitor Type: This problem only occurs with the Push monitor type. For all other types of monitors (e.g., HTTP, TCP), the notifications arrive just fine using the same Telegram bot token and chat.

I can't seem to figure out why the 'Online' notifications are not consistently being sent for the Push monitor. Am I doing something wrong here, or could this be a bug?

Any help or advice would be much appreciated!

### 🐻 Uptime-Kuma Version

1.23.15

### 💻 Operating System and Arch

Ubuntu 22.04

### 🌐 Browser

FireFox 131.0.2

### 🖥️ Deployment Environment

- Runtime: Docker 26.1.1
- Database: embedded mariadb
- Filesystem used to store the database on: ext4
- number of monitors:  33

**Comment by CommanderStorm** [comment]
Is there something logged in the log?

**Comment by Freekers** [comment]
> Is there something logged in the log?

Thanks for you reply. Unfortunately there is nothing in the container logs, or are you referring to another log(file)?

Thanks

**Comment by Freekers** [comment]
> Is there something logged in the log?

Looks like up notifications aren't being logged at all anymore, yet the status shows Up. I can't explain this behavior:

![afbeelding](https://github.com/user-attachments/assets/5fc44062-93bd-475c-a9e3-9dbe53075c9f)

These are the related entries in the container logging for October 14th. There is nothing else apart from these two loglines for October 14th:

```
2024-10-14T06:05:04+02:00 [MONITOR] WARN: Monitor #27 'XXXX': Pending: No heartbeat in the time window | Max retries: 3 | Retry: 1 | Retry Interval: 300 seconds | Type: push
2024-10-14T06:05:04+02:00 [MONITOR] WARN: Monitor #27 'XXXX': Pending: No heartbeat in the time window | Max retries: 3 | Retry: 1 | Retry Interval: 300 seconds | Type: push
```
