### ISSUE TITLE
DB size

### ISSUE THREAD

**Issue by jackzVZW** [louislam/uptime-kuma#5187]
### ⚠️ Please verify that this question has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

Hi there,
1.23.13 here.
current kuma.db is 6GB, with 200 monitoring targets (PING only). Is it normal? 
Keep 90 days monitoring history.

Thanks.

### 🐻 Uptime-Kuma Version

1.23.13

### 💻 Operating System and Arch

Rocky Linux 9.4

### 🌐 Browser

Chrome latest

### 🖥️ Deployment Environment

- Runtime: node 16.20.2
- Database: default
- Filesystem used to store the database on: linux file system 
- number of monitors: 200

**Comment by CommanderStorm** [comment]
Yes, this is normal.
Please see #4500 for the things that we are doing to aleviate that performance problem and for remidies for this.

https://github.com/louislam/uptime-kuma/pull/3595 might be nessesary to solve the disk size issue though.
