### ISSUE TITLE
Delete Docker-Host

### ISSUE THREAD

**Issue by GerdRuetten** [louislam/uptime-kuma#5190]
### ⚠️ Please verify that this question has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

I create in a Docker-Monitor a wrong Docker-Host.
How can i delete or edit this host?
I always can create a new host

TIA
Best regards
Gerd

### 🐻 Uptime-Kuma Version

1.23.15

### 💻 Operating System and Arch

linux/amd64

### 🌐 Browser

not browser specifik

### 🖥️ Deployment Environment

- Runtime: 
- Database: 
- Filesystem used to store the database on: 
- number of monitors:

**Comment by zoe-tek** [comment]
Top right, click account, click settings, click docker hosts, click the one you want to delete, click delete button.
![Screenshot_20241011_221430](https://github.com/user-attachments/assets/efb8b8c1-77d5-44e3-9251-ee54f4b88cad)

**Comment by GerdRuetten** [comment]
perfect!
Thank you so mutch.
