### ISSUE TITLE
Persist only neccesary files to VCS

### ISSUE THREAD

**Issue by dankkomcg** [louislam/uptime-kuma#5191]
### ⚠️ Please verify that this question has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

I need to persist the uptime-kuma configuration to replicate on diferent deployments.

I dont want to upload to my project all the content of uptime-kuma data directory.

What are the required files to store and upload to VSC service?

### 🐻 Uptime-Kuma Version

Latest

### 💻 Operating System and Arch

Ubuntu 22.04

### 🌐 Browser

Google Chrome

### 🖥️ Deployment Environment

- Runtime: 
- Database: 
- Filesystem used to store the database on: 
- number of monitors:

**Comment by CommanderStorm** [comment]
All files in the data directory are required for it to work correctly.

**Comment by dankkomcg** [comment]
> All files in the data directory are required for it to work correctly.

Any form to export the configuration for import? 
Upload to repository a .db file is the finally solution?

**Comment by CommanderStorm** [comment]
> Upload to repository

Aaah so you don't mean the `Vienna Scientific Cluster Service` (first result if you search for `VSC Service`)...

We might not currently support what you are looking for.

I think you are looking for a monitoring solution which is infrastructure as code. That simply is not us.
While you can use the deprecated backup functionality or write your own scripts do do what you need, I think what you are looking for is likely a different solution.

Checking your db into git might work as well if you are using git LFS, but be aware that the db-size will be larger the more heartbeats need to be retained. (see #4500)

Please have a look at [gatus](https://github.com/TwiN/gatus) instead if you want IAC.

**Comment by dankkomcg** [comment]
After publish the comment and save the repository that you mentioned, github suggest me this project: https://github.com/BigBoot/AutoKuma

I leave this link here to help who search this questions.

Ty!!
