### ISSUE TITLE
Disable browser pop up alerts

### ISSUE THREAD

**Issue by blancolandau** [louislam/uptime-kuma#5194]
### ⚠️ Please verify that this question has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

Is it possible the red up and down alerts that show in the browser?

### 🐻 Uptime-Kuma Version

1.23.15

### 💻 Operating System and Arch

Ubuntu 18.04.6 LTS

### 🌐 Browser

Google Crhome Version 129.0.6668.100 (Official Build) (arm64)

### 🖥️ Deployment Environment

- Runtime: Docker 24.0.2
- Database: 
- Filesystem used to store the database on: 
- number of monitors: 3

**Comment by CommanderStorm** [comment]
Not in v1, but v2.0 includes
- https://github.com/louislam/uptime-kuma/pull/3441

The status of v2.0 is noted here
- #4500

current (v2) version of this setting:

![](https://private-user-images.githubusercontent.com/3271800/254140790-c6b6dc5f-f78a-442b-8bfa-fa234e0ae116.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg4NjI1NDUsIm5iZiI6MTcyODg2MjI0NSwicGF0aCI6Ii8zMjcxODAwLzI1NDE0MDc5MC1jNmI2ZGM1Zi1mNzhhLTQ0MmItOGJmYS1mYTIzNGUwYWUxMTYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTAxMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEwMTNUMjMzMDQ1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MWZhZjBkZTY5YjI1ZDg5MmU0OTMxNDQxMTJjNjZlMzAyOWI1NGE1ZmVkNjQ0Mjc1MTk5MzAzM2E1MjRmOGNjOCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.q7r8F8XdG7iLMr0M_6yFgdJykPk-GJMyda3_9F3PDXA)
