### ISSUE TITLE
Update/change landing page name?

### ISSUE THREAD

**Issue by dotwest** [louislam/uptime-kuma#5195]
### ⚠️ Please verify that this question has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

Hi,
I would like to know if I can change/update the "Uptime Kuma" name on the landing page?
If so, where can I do that?
Thanks.

### 📝 Error Message(s) or Log

No error message or logs.

### 🐻 Uptime-Kuma Version

Version: 1.23.13

### 💻 Operating System and Arch

Ubuntu 22.04.4 LTS

### 🌐 Browser

Version 129.0.6668.90 (Official Build) (64-bit)

### 🖥️ Deployment Environment

- Runtime: -
- Database: -
- Filesystem used to store the database on: - 
- number of monitors: -

**Comment by CommanderStorm** [comment]
If you mean the status page:
You can change the name on the public status page here:
![image](https://github.com/user-attachments/assets/c39392a4-2f78-467f-b4bb-b96fda0286de)

If you mean the dashboard:
You can fork the project and maintain your own version. The project is not intended as a white label solution
=> removing this from the admin dashboard is not something we will consider.

**Comment by dotwest** [comment]
Hi @CommanderStorm,

Thanks for the reply and details.

I saw that you mentioned, where to create and add custom images and names but I was more talking about the landing page, the login page with the logo and name.

I do understand that you're encourage people not to change the default details but you said I should fork it and then make some changes, where should I look in the code to possibly change the name and the logo?

Please let me know.

Thanks 👍
