### ISSUE TITLE
Weblate no longer adds the latest committed translations 

### ISSUE THREAD

**Issue by cyril59310** [louislam/uptime-kuma#5197]
### 📑 I have found these related issues/pull requests

#5070

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### Description

same problem as #5070

![image](https://github.com/user-attachments/assets/58810b06-4fc4-44a5-a990-a59eff5ddd0e)

### 👟 Reproduction steps

.

### 👀 Expected behavior

.

### 😓 Actual Behavior

.

### 🐻 Uptime-Kuma Version

.

### 💻 Operating System and Arch

.

### 🌐 Browser

.

### 🖥️ Deployment Environment

- Runtime: 
- Database: 
- Filesystem used to store the database on: 
- number of monitors:

**Comment by louislam** [comment]
Related pull request: https://github.com/louislam/uptime-kuma/pull/5072#issuecomment-2392591828

**Comment by louislam** [comment]
Incidentally pushed to the master branch directly... Luckily, it did fix the issue: b719d115006635bcec61ed02f2b5dd3674abcd00
