### ISSUE TITLE
Backup via CLI

### ISSUE THREAD

**Issue by root9191** [louislam/uptime-kuma#520]
**Is it a duplicate question?**
Please search in Issues without filters: https://github.com/louislam/uptime-kuma/issues?q=

**Info**
Uptime Kuma Version:
Using Docker?: Yes
Docker Version: 1.7.3
Node.js Version (Without Docker only):
OS: Debian Bullseye
Browser:

Hello, i haven‘t seen which database Uptime uses. Can i do for a backup of the DB the `sqlite3 dbname .backup dbbackup` command?

**Comment by louislam** [comment]
It is `kuma.db`.

**Comment by root9191** [comment]
So Sqlite or MySQL or something Else?

**Comment by gaby** [comment]
> So Sqlite or MySQL or something Else?

Sqlite
