### ISSUE TITLE
Add description to groups in status pages

### ISSUE THREAD

**Issue by ghost** [louislam/uptime-kuma#5202]
### 📑 I have found these related issues/pull requests

Unable to find similar issue.

### 🏷️ Feature Request Type

Status-page

### 🔖 Feature description

It's currently only possible to enter the name of a group of monitors in a status page and not possible to add any other information. It'd be useful to have a description field for the group.

### ✔️ Solution

Add description field to group.

**Comment by apio-sys** [comment]
You can currently add a description in a status page below the slug and title when in editing mode. Also each group can have it's own description above it. Doesn't that fit your needs?

![Screenshot from 2024-10-15 15-34-40](https://github.com/user-attachments/assets/86234112-7b1f-4434-bf00-2a65d645bade)

**Comment by NesredinJemal** [comment]
I need to check my balance

**Comment by NesredinJemal** [comment]
i need to check my balance Sent from my phone-------- Original message --------From: NesredinJemal ***@***.***>Date: Tue, 15 Oct 2024, 18:23To: louislam/uptime-kuma ***@***.***>Cc: NesredinJemal ***@***.***>, Your activity ***@***.***>Subject: Re: [louislam/uptime-kuma] Add description to groups in status pages (Issue #5202)
I need to check my balance

**Comment by apio-sys** [comment]
When you add a "group" in becomes by default "Untitled Group" which you can change to read the text you want. And you can have as many as you want (ie. distinguish in front- and back-office machines). So you have those (unlimited) group descriptions, the header description and a free footer text. Quite some stuff to personalize IMHO.
