### ISSUE TITLE
Inconsistent Heartbeat Bar Length between versions 1.23.15 and 2.0.0-dev

### ISSUE THREAD

**Issue by candies404** [louislam/uptime-kuma#5204]
### ⚠️ Please verify that this question has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

![image](https://github.com/user-attachments/assets/b12fb25f-a697-4e0c-993e-271984c72a30)
![image](https://github.com/user-attachments/assets/3777ccf0-4d9f-4227-8411-3ae3a38d82fe)

The check frequency is set to 60 seconds for all monitors，
2.0.0-dev is based on the commit https://github.com/louislam/uptime-kuma/tree/b719d115006635bcec61ed02f2b5dd3674abcd00
1.23.15 is from https://github.com/louislam/uptime-kuma/archive/refs/tags/1.23.15.zip

### 📝 Error Message(s) or Log

no error

### 🐻 Uptime-Kuma Version

1.23.15 and 2.0.0-dev

### 💻 Operating System and Arch

windows11 

### 🌐 Browser

129.0.6668.90

### 🖥️ Deployment Environment

- Runtime: Docker Desktop 4.34.3 (170107)
- Database: sqlite
- Filesystem used to store the database on: ssd
- number of monitors: 1

**Comment by CommanderStorm** [comment]
That was an intentional change in response to feedback in https://github.com/louislam/uptime-kuma/issues/4365.
- https://github.com/louislam/uptime-kuma/pull/4376

Am I missing something?

**Comment by candies404** [comment]
I searched for this pr before, but I mean why is the length increased but the heartbeat status is not displayed

**Comment by CommanderStorm** [comment]
Thanks ❤️, Reverted said PR in https://github.com/louislam/uptime-kuma/pull/5207.
Fixing this better needs further looking into which I currently don't have the capacity for.
