### ISSUE TITLE
A single container shows as down even though it's up. Used to work.

### ISSUE THREAD

**Issue by devanteweary** [louislam/uptime-kuma#5213]
### 📑 I have found these related issues/pull requests

Didn't really find any related issues.

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### Description

This actually started happening months ago. I've just been too lazy to report it.  

Out of all my containers, one shows down even though it's up.  
I can add it as container name or as ID, it just shows down. (well pending)

It was working fine, then one day it stopped.   
Probably after an update or something.

I have a few dozen other ones that show up/down status just fine.  

The container in question is: **qmcgaw/ddns-updater**

Here're my settings:

![image](https://github.com/user-attachments/assets/37e460a8-9a5a-4738-a68c-f3634ce48f8b)

### 👟 Reproduction steps

There's no real triggering. It just doesn't show as up.

### 👀 Expected behavior

It should just show as up when up.

### 😓 Actual Behavior

It shows down.

### 🐻 Uptime-Kuma Version

1.23.15

### 💻 Operating System and Arch

Unraid v6.12.13

### 🌐 Browser

Brave v1.70.126

### 🖥️ Deployment Environment

- Runtime: Docker 24.0.9
- Database: I don't know. It's the **louislam/uptime-kuma** Docker container. There are no DB settings.
- Filesystem used to store the database on: btrfs on dual SSD pool setup (Unraid)
- number of monitors: 50

### 📝 Relevant log output

This is after a refresh and a little extra on each side.

```shell
source	timestamp

UptimeKuma[19182]:	2024-10-16 22:29:41.000
UptimeKuma[19182]: 2024-10-16T22:29:41-07:00 [MONITOR] WARN: Monitor #70 'ddns-updater': Pending: unhealthy | Max retries: 10 | Retry: 0 | Retry Interval: 60 seconds | Type: docker

UptimeKuma[19182]:	2024-10-16 22:29:00.000
UptimeKuma[19182]: 2024-10-16T22:29:00-07:00 [MONITOR] WARN: Monitor #47 'Network': Pending: Child inaccessible | Max retries: 0 | Retry: 0 | Retry Interval: 60 seconds | Type: group

UptimeKuma[19182]:	2024-10-16 22:28:59.000
UptimeKuma[19182]: 2024-10-16T22:28:59-07:00 [MONITOR] WARN: Monitor #48 'Docker': Pending: Child inaccessible | Max retries: 0 | Retry: 0 | Retry Interval: 60 seconds | Type: group

UptimeKuma[19182]:	2024-10-16 22:28:42.000
UptimeKuma[19182]: 2024-10-16T22:28:42-07:00 [MONITOR] INFO: Get Monitor: 70 User ID: 1

UptimeKuma[19182]:	2024-10-16 22:28:41.000
UptimeKuma[19182]: 2024-10-16T22:28:41-07:00 [MONITOR] WARN: Monitor #70 'ddns-updater': Pending: unhealthy | Max retries: 10 | Retry: 0 | Retry Interval: 60 seconds | Type: docker

UptimeKuma[19182]:	2024-10-16 22:28:41.000
UptimeKuma[19182]: 2024-10-16T22:28:41-07:00 [MANAGE] INFO: Resume Monitor: 70 User ID: 1

UptimeKuma[19182]:	2024-10-16 22:28:35.000
UptimeKuma[19182]: 2024-10-16T22:28:35-07:00 [MONITOR] INFO: Get Monitor: 70 User ID: 1

UptimeKuma[19182]:	2024-10-16 22:28:00.000
UptimeKuma[19182]: 2024-10-16T22:28:00-07:00 [MONITOR] WARN: Monitor #47 'Network': Pending: Child inaccessible | Max retries: 0 | Retry: 0 | Retry Interval: 60 seconds | Type: group

UptimeKuma[19182]:	2024-10-16 22:27:59.000
UptimeKuma[19182]: 2024-10-16T22:27:59-07:00 [MONITOR] WARN: Monitor #48 'Docker': Pending: Child inaccessible | Max retries: 0 | Retry: 0 | Retry Interval: 60 seconds | Type: group

UptimeKuma[19182]:	2024-10-16 22:27:59.000
UptimeKuma[19182]: 2024-10-16T22:27:59-07:00 [MONITOR] WARN: Monitor #70 'ddns-updater': Pending: unhealthy | Max retries: 10 | Retry: 0 | Retry Interval: 60 seconds | Type: docker
```

**Comment by julian-piehl** [comment]
In the log, I see 'Pending: Unhealthy', which suggests that while your container is running, the health check is failing. When you run `docker ps`, take a look at the "Status" column. If it says something like "Up 1 Hour (unhealthy)", it means the container itself is reporting an issue. However, if it says 'Healthy', it could be a bug in Uptime Kuma.

**Comment by devanteweary** [comment]
> In the log, I see 'Pending: Unhealthy', which suggests that while your container is running, the health check is failing. When you run `docker ps`, take a look at the "Status" column. If it says something like "Up 1 Hour (unhealthy)", it means the container itself is reporting an issue. However, if it says 'Healthy', it could be a bug in Uptime Kuma.

Yep sure enough, it shows cirremt;y "Up 16 hours (unhealthy)". 
Should I report that to the developer of the ddns-updater then?

If so, I'll close this out!

**Comment by devanteweary** [comment]
This issue was fixed in one of the last updates of ddns-updater.
Thank you!
