### ISSUE TITLE
SQLITE_CORRUPT

### ISSUE THREAD

**Issue by ori-21** [louislam/uptime-kuma#5224]
### ⚠️ Please verify that this question has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

I have deployed uptime-kuma with 3 replicas (assigned to three different nodes of the cluster).
It would help me so much if this error says something to somebody.
### 📝 Error Message(s) or Log

Trace: [Error: insert into `heartbeat` (`down_count`, `duration`, `important`, `monitor_id`, `msg`, `status`, `time`) values (0, 120, false, 1, 'write EPROTO 00B8792F117F0000:error:0A00010B:SSL routines:ssl3_get_record:wrong version number:../deps/openssl/openssl/ssl/record/ssl3_record.c:355:
', 0, '2024-10-21 08:09:37.955') - SQLITE_CORRUPT: database disk image is malformed] {
  errno: 11,
  code: 'SQLITE_CORRUPT'
}
    at Timeout.safeBeat [as _onTimeout] (/app/server/model/monitor.js:1034:25)
2024-10-21T10:09:37+02:00 [MONITOR] ERROR: Please report to https://github.com/louislam/uptime-kuma/issues
2024-10-21T10:09:37+02:00 [MONITOR] INFO: Try to restart the monitor
2024-10-21T10:10:11+02:00 [SOCKET] INFO: New polling connection, IP = 192.168.0.23
2024-10-21T10:10:14+02:00 [SOCKET] INFO: New polling connection, IP = 192.168.0.23
2024-10-21T10:10:27+02:00 [SOCKET] INFO: New polling connection, IP = 192.168.0.23
2024-10-21T10:10:36+02:00 [SOCKET] INFO: New polling connection, IP = 192.168.0.23

### 🐻 Uptime-Kuma Version

Version: 1.23.15 

### 💻 Operating System and Arch

Rancher Cluster

### 🌐 Browser

Firefox

### 🖥️ Deployment Environment

- Runtime: 
- Database: 
- Filesystem used to store the database on: 
- number of monitors:

**Comment by CommanderStorm** [comment]
> deployed uptime-kuma with 3 replicas (assigned to three different nodes of the cluster).

You mean 3 separate instances, right?
Sharing the DB between instances is not supported 

> Rancher

Using NFS 3 is not supported. Please use storage with proper locking support instead.
Our database (sqlite) needs to be able to lock the disk.

**Comment by ori-21** [comment]
> > deployed uptime-kuma with 3 replicas (assigned to three different nodes of the cluster).
> 
> You mean 3 separate instances, right? Sharing the DB between instances is not supported
> 
> > Rancher
> 
> Using NFS 3 is not supported. Please use storage with proper locking support instead. Our database (sqlite) needs to be able to lock the disk.

**Comment by ori-21** [comment]
regarding sharing the DB is ok because i can manage to run only one single instance.

while regarding storage i am not using NFS3 , i have longhorn storage on rancher and have bound a pvc, is this ok?

**Comment by CommanderStorm** [comment]
> sharing the DB is ok because i can manage to run only one single instance

Sharing the database is not something that we engineered for and is thus not suppored.

> i have longhorn storage on rancher

You are using nfs if you are attaching the same volume to multiple replicas.
https://longhorn.io/docs/1.7.2/nodes-and-volumes/volumes/rwx-volumes/

This might not be supported.
Please use local storage instead. Running a database off of network storage is likely not a great experience even if it works. See #4500 why this is a bigger problem than you are anticipating.

Our docs on this are pretty clear:

https://github.com/louislam/uptime-kuma/wiki/%F0%9F%94%A7-How-to-Install

> [!WARNING]
> Filesystem support for POSIX file locks is required to avoid SQLite database corruption.
> Be aware of possible [file locking problems](https://www.sqlite.org/howtocorrupt.html#_file_locking_problems) such as those [commonly encountered with NFS](https://www.sqlite.org/faq.html#q5).
> **Please map the `/app/data`-folder to a local directory or volume.**

**Comment by ori-21** [comment]
yes it is clear now, thank you for your support
