### ISSUE TITLE
Disable notifications of paused services

### ISSUE THREAD

**Issue by zwimer** [louislam/uptime-kuma#5226]
### ⚠️ Please verify that this question has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

I'd like notifications to be disabled if a paused service / groups goes down. Right now, if I pause a service / group then take the service down, Uptime Kuma will send notifications that the service is unavailable. Is there a way to do this?

Along the same lines, if I am on the Uptime Kuma site, it will spam me with red notifications that the service / group is down.

Much less important but related: Is there a way to stop Uptime Kuma from pinging these paused services?

### 🐻 Uptime-Kuma Version

1.23.15

### 💻 Operating System and Arch

Docker: louislam/uptime-kuma

### 🌐 Browser

Google Chrome 130.0.6723.59

### 🖥️ Deployment Environment

- Runtime: `Docker version 27.3.1, build ce12230`
- Database: From the docker image: louislam/uptime-kuma
- Filesystem used to store the database on: Docker: overlayfs
- number of monitors: 55

**Comment by zwimer** [comment]
@louislam I can convert this into a feature request if this functionality is not currently present?

**Comment by CommanderStorm** [comment]
pausing groups currently don't pause its children.
It being displayed as such is unfortunate.
The tracking issue to subscribe to is
- https://github.com/louislam/uptime-kuma/issues/4696

If you want to help, helping to test/review this PR is what is needed:
- https://github.com/louislam/uptime-kuma/pull/5248

We have documented how to test PRs here: https://github.com/louislam/uptime-kuma/wiki/Test-Pull-Requests

I am going to close this as a duplicate of #5248

**Comment by Suven-p** [comment]
> If you want to help, helping to test/review this PR is what is needed:
> 
> * [Convert filters and search text into query params #5248](https://github.com/louislam/uptime-kuma/pull/5248)
> 

I believe you mean https://github.com/louislam/uptime-kuma/pull/5193
