### ISSUE TITLE
Demo instance down

### ISSUE THREAD

**Issue by Zoobdude** [louislam/uptime-kuma#5229]
### 📑 I have found these related issues/pull requests

None related

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### Description

![image](https://github.com/user-attachments/assets/0e7f9c94-db09-420a-b1d8-6467e62564bb)

### 👟 Reproduction steps

Navigate to https://uptime.kuma.pet/
or
https://demo.kuma.pet/start-demo

### 👀 Expected behavior

Page should load

### 😓 Actual Behavior

Error 1033 - Argo Tunnel error

### 💻 Operating System and Arch

Windows 10

### 🌐 Browser

Google Chrome

**Comment by louislam** [comment]
Maybe it was network issues, it is fine now without any actions by my side.
