### ISSUE TITLE
Tolerance/debounce for network errors

### ISSUE THREAD

**Issue by luizkowalski** [louislam/uptime-kuma#5235]
### 📑 I have found these related issues/pull requests

-

### 🏷️ Feature Request Type

API / automation options, Settings

### 🔖 Feature description

Sometimes, there are network errors, small hiccups that immediately trigger a notification. They cause false positives and bring down the SLO, and the problem is resolved in the next check:

<img width="1177" alt="image" src="https://github.com/user-attachments/assets/f44dce08-6770-4bd0-a44f-db097f72b8f8">

### ✔️ Solution

I see two possible solutions: either an option to ignore certain error types or a change in the algorithm: when a check fails, instead of immediately triggering an error, it is registered as a warning. the warning does not affect the SLO. if the next check fails, then an error is triggered and the SLO is affected, otherwise, the warning is cleared.

**Comment by CommanderStorm** [comment]
> ENOTFOUND

Consider enabling NSCD in the settings to make the DNS resolver less likely to jeject you as spemmy. This has the downside of caching dns queries, which you might not want..

> when a check fails, instead of immediately triggering an error, it is registered as a warning

If you set `Retry` >= 1.
This is not the default as users kept asking why suddenly what they expect to be down is not.

> the warning does not affect the SLO

That reaaaly depends on how your SLIs are defined..
I don't know if retries are accounted as down/up, but in the end of the day both are sane choices imo 🤷🏻‍♂️. Idk..

**Comment by luizkowalski** [comment]
these are good tips, I will play around with these configs

**Comment by CommanderStorm** [comment]
In that case please check the TTL of the DNS record.
If the TTL is really low, this might also happen
