### ISSUE TITLE
Tags in the notifications and events

### ISSUE THREAD

**Issue by panos-stavrianos** [louislam/uptime-kuma#524]
Hello everyone, this is an amazing project, I build my own version twice but it does not compare to this! Thank you so much!

I really liked the `tags` feature and i can hope for a tree like grouping in the future, but for now 
it will help if tags are included in the notification message and in the event table (on the dashboard)

***Something like this***
![uptime_dashboad](https://user-images.githubusercontent.com/20128753/135635298-16e16afb-f3f5-4b98-8c05-791fd4c380f5.png)
![uptime_notification](https://user-images.githubusercontent.com/20128753/135635299-47442e34-58ff-4225-a78b-01fa2091cc4d.png)

The notification is from the Rocket.chat application

**Comment by CommanderStorm** [comment]
@panos-stavrianos Is this one of the issues which will be resolved by #2693?

**Comment by panos-stavrianos** [comment]
That PR would be absolutely perfect!
