### ISSUE TITLE
how to customize a application root prefix for reverse proxy setting?

### ISSUE THREAD

**Issue by Bigfoot0007** [louislam/uptime-kuma#5246]
### ⚠️ Please verify that this question has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

Hi, I integrate uptime with a reverse proxy, there are /dashboard , /api  /socket.io,   can uptime add a application root prefix and make the subpath under one APPROOT?

### 📝 Error Message(s) or Log

N/A

### 🐻 Uptime-Kuma Version

1.23.15

### 💻 Operating System and Arch

docker

### 🌐 Browser

firefox

### 🖥️ Deployment Environment

- Runtime: 
- Database: 
- Filesystem used to store the database on: 
- number of monitors:

**Comment by CommanderStorm** [comment]
Please refer to https://github.com/louislam/uptime-kuma/issues/147

**Comment by CommanderStorm** [comment]
(Closing as a duplicate)
