### ISSUE TITLE
V2 SNMP

### ISSUE THREAD

**Issue by plegrand1** [louislam/uptime-kuma#5247]
### 📑 I have found these related issues/pull requests

- https://github.com/louislam/uptime-kuma/pull/4717

### 🏷️ Feature Request Type

New monitor

### 🔖 Feature description

Hello,
I've just discovered Uptime Kuma and I must say i'm very pleased with this application.
It does everything I need it to, simply and efficiently.
I had a small question:
After reading a few pull requests where SNMP was mentioned, I wanted to know if version 2 of Uptime Kuma would include the possibility of setting up SNMP monitors.
Thanks

### ✔️ Solution

SNMP Monitor

**Comment by CommanderStorm** [comment]
As you can see from https://github.com/louislam/uptime-kuma/pull/4717, said PR has been merged into v2.0
See #4500 for furhter context
