### ISSUE TITLE
A2S and other game servers

### ISSUE THREAD

**Issue by utlilb** [louislam/uptime-kuma#525]
**Is it a duplicate question?**
No

**Is your feature request related to a problem? Please describe.**
Just a nice to have feature.

**Describe the solution you'd like**
Would love to see implementation for A2S and other game server protocols

**Describe alternatives you've considered**

**Additional context**
Might be a good place to start?
https://github.com/ourfourwalls/game-server-query

**Comment by 401U** [comment]
This should be resolved with #2566

**Comment by chakflying** [comment]
Fixed by #2566.
