### ISSUE TITLE
HTTP(s) checks fail when container starts earlier than Internet works

### ISSUE THREAD

**Issue by Feriman22** [louislam/uptime-kuma#5254]
### 📑 I have found these related issues/pull requests

-

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### Description

After a power outage, when the server is restarted, all HTTPS monitors in Uptime Kuma appear as down (red), even though the services are accessible. This state persists even after using the Pause/Start option for individual monitors, and only a full restart of the Uptime Kuma Docker container resolves the issue.

I found out that it's because the internet connection is not ready when Uptime Kuma starts.

### 👟 Reproduction steps

1. Set a HTTP(s) monitor to anything on the internet
2. Stop Uptime Kuma
3. Disable internet connection
4. Start Uptime Kuma
5. Enable internet connection
6. Check will remains red

### 👀 Expected behavior

It should be green (up) when the Internet connection has been established.

### 😓 Actual Behavior

The HTTP(s) monitor will remain red (down) until the container is restarted.

### 🐻 Uptime-Kuma Version

1.23.15

### 💻 Operating System and Arch

Debian 12.7

### 🌐 Browser

Google Chrome Version 130.0.6723.70 (Official Build) (64-bit)

### 🖥️ Deployment Environment

- Runtime: Docker version 27.3.1, build ce12230
- Database: Docker Container based DB
- Filesystem used to store the database on: ext4
- number of monitors: 26

### 📝 Relevant log output

```shell
getaddrinfo EAI_AGAIN feriman.com
```

**Comment by CommanderStorm** [comment]
> getaddrinfo EAI_AGAIN

Below would be my regular response.
I am unsure how the Internet connection plays into this.
Maybe it broke the DNS you have configured/is the default.
Is this reproducible? (if yes, what monitors, ..)

> That is a clue that your dns resolver is overwhealmed.
> - Are you using `nscd` (in the settings) to avoid overwhealming your dns server?
> - What is the TTL on the dns records?

**Comment by Feriman22** [comment]
It is reproducible. Only HTTP(s) monitors are affected, which monitor some websites on the internet. What exactly should I check when Uptime Kuma does this?

I have Google DNS servers (8.8.8.8 and 8.8.4.4) configured in my router, but nothing else (in Debian or even in Docker Compose).

**Comment by louislam** [comment]
![image](https://github.com/user-attachments/assets/74f9ec90-e996-4d02-a20d-a0c88fcebaf4)


Could be an upstream behavior, it cannot reproduce in my side. (I tested it by unplugging / plugging the lan cable)

**Comment by Feriman22** [comment]
It happened with another Docker Container as well (Nginx Proxy Manager), it also cannot reach the internet. I have no idea why, but it's not Uptime Kuma related issue.

Thanks for your support!
