### ISSUE TITLE
Non-nightly rootless docker images

### ISSUE THREAD

**Issue by zwimer** [louislam/uptime-kuma#5255]
### ⚠️ Please verify that this question has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

Given the following two PRs, it seems uptime kuma supports rootless docker images and `-rootless` docker image tags are desired to be applied to existing tags. Both of these were merged back in 2023, so I was wondering why the only `-rootless` docker image was `nightly`, if that is intentional, and if non-nightly `-rootless` images are awaiting something specific.
- https://github.com/louislam/uptime-kuma/pull/4052
- https://github.com/louislam/uptime-kuma/pull/2086

### 🐻 Uptime-Kuma Version

N/A

### 💻 Operating System and Arch

Linux/Docker

### 🌐 Browser

N/A

### 🖥️ Deployment Environment

- Runtime: Docker

**Comment by louislam** [comment]
2.0 is not released yet.
