### ISSUE TITLE
App dies after adding 482 sites to monitor to it

### ISSUE THREAD

**Issue by WorstPIlot** [louislam/uptime-kuma#5265]
### 📑 I have found these related issues/pull requests

I do not know about any other related issues

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### Description

I've added 482 site using python uptime-kuma-api on 483 site app dies, the application shows the list of sites as empty (offering to add a new one), API stops working.

### 👟 Reproduction steps

1) Add 482 sites via API or manually to monitoring

### 👀 Expected behavior

Sites will be added as they should, as long as the server hardware can handle the load

### 😓 Actual Behavior

The application opens for a long time (about 5 minutes), after which the list of sites is displayed as empty, and the API does not respond

### 🐻 Uptime-Kuma Version

1.23.15

### 💻 Operating System and Arch

Debian 12

### 🌐 Browser

Firefox 131.0.3

### 🖥️ Deployment Environment

- Runtime: Docker
- Database: sqlite
- Filesystem used to store the database on: btrfs on SATA M2 SSD
- number of monitors: 2

**Comment by CommanderStorm** [comment]
Please see #4500 for performance problems and how to "mitigate" them in v1.
Closing as resolved in v2.0

We are currently finishing up the migration guide. See https://github.com/louislam/uptime-kuma-wiki/pull/53 for furhter context
