### ISSUE TITLE
Public and private monitors on status page

### ISSUE THREAD

**Issue by zeiinsito** [louislam/uptime-kuma#527]
Let a monitor be marked as "private", so it won't show up on the public status page. Being logged in will show you all the monitors; hence being not logged in will only show the public tagged monitors. 

Currently this can be done by putting only public monitors in the status page, and watching for all the monitors on the dashboard, but the public/private monitor system will be a better solution, letting the user to quick view the monitors on the status page while maintaining some monitor privacy.

**Comment by CommanderStorm** [comment]
Related https://github.com/louislam/uptime-kuma/issues/1756 https://github.com/louislam/uptime-kuma/issues/1050

**Comment by CommanderStorm** [comment]
@chakflying 
I think the status page being different for logged in/out users would be too confusing.
=> should only be implemented via #1050

I would vote to close this issue in favor of #1050

**Comment by chakflying** [comment]
I agree that this proposal doesn't really work under the current architecture.
