### ISSUE TITLE
How to configure v2 for external MariaDB?

### ISSUE THREAD

**Issue by derekoharrow** [louislam/uptime-kuma#5274]
### ⚠️ Please verify that this question has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

I cannot find any reference how to configure the db-config.json file to use an external MariaDB database in v2.

I tried something along the lines of:

```json
{
  "type": "mariadb",
  "hostname": "192.168.1.14",
  "username": "root",
  "password": "mylongpassword",
  "port": "3306"
}
```

How do you configure v2 to use MariaDB?

(I understand that I'll have to export, convert and import my sqlite DB to MariaDB when working).

### 📝 Error Message(s) or Log

```
2024-10-29T15:03:12Z [SETUP-DATABASE] INFO: db-config.json is not found or invalid: Unexpected token ',', ..."username:", "root", "... is not valid JSON
2024-10-29T15:03:12Z [SETUP-DATABASE] INFO: kuma.db is found, generate db-config.json
2024-10-29T15:03:12Z [DB] INFO: Database Type: sqlite
2024-10-29T15:03:12Z [SERVER] INFO: Connected to the database

```

### 🐻 Uptime-Kuma Version

v2.0 beta

### 💻 Operating System and Arch

Ubuntu 22.04.2 LTS

### 🌐 Browser

n/a

### 🖥️ Deployment Environment

- Runtime: Docker version 27.3.1, build ce12230
- Database: MariaDB
- Filesystem used to store the database on: ext3
- number of monitors: 80+

**Comment by louislam** [comment]
if you would like to start with `db-config.json`, the format should be like this:

```
{
    "type": "mariadb",
    "port": 3306,
    "hostname": "",
    "username": "",
    "password": "",
    "dbName": "",
}

```
