### ISSUE TITLE
v2 tag values missing in UI

### ISSUE THREAD

**Issue by thehammy** [louislam/uptime-kuma#5277]
### ⚠️ Please verify that this question has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

Testing upgrade from v2 nightly to v2 beta rootless, appears values in tags are missing in the ui.
Can see these showing in docker logs and /metrics for prometheus.
Same behaviour for newly created checks also.
![2024-10-29_17-29-34](https://github.com/user-attachments/assets/b4b17733-7a8b-41fd-945c-21042795a2ae)

### 🐻 Uptime-Kuma Version

2.0 beta

### 💻 Operating System and Arch

Centos 7.9

### 🌐 Browser

Google Chrome 130.0.6723.70

### 🖥️ Deployment Environment

- Runtime: Docker 20.10.21
- Database: MariaDB Embedded
- Filesystem used to store the database on: xfs (SSD)
- number of monitors: 25

**Comment by louislam** [comment]
Maybe related to this pr #5025?

**Comment by louislam** [comment]
Based on the SELECT statement, it didn't seem to select the tag value. It maybe related to #5025

![image](https://github.com/user-attachments/assets/96f2cf8c-8f64-4311-929a-b2ce364c37b7)

**Comment by Ionys320** [comment]
May be fixed with #5298 then, the SELECT has been changed to add the tag value.
