### ISSUE TITLE
About the invalid TLS certificate expiration notification of uptime

### ISSUE THREAD

**Issue by zhenghongyang666** [louislam/uptime-kuma#5289]
### 📑 I have found these related issues/pull requests

Uptime's https certificate expiration reminder is not available. I have tested many versions myself and found that this function is invalid, including the latest version

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### Description

Uptime's https certificate expiration reminder is not available. I have tested many versions myself and found that this function is invalid, including the latest version

### 👟 Reproduction steps

Uptime's https certificate expiration reminder is not available. I have tested many versions myself and found that this function is invalid, including the latest version

### 👀 Expected behavior

Uptime's https certificate expiration reminder is not available. I have tested many versions myself and found that this function is invalid, including the latest version

### 😓 Actual Behavior

Uptime's https certificate expiration reminder is not available. I have tested many versions myself and found that this function is invalid, including the latest version

### 🐻 Uptime-Kuma Version

all

### 💻 Operating System and Arch

centos7

### 🌐 Browser

google

### 🖥️ Deployment Environment

Uptime's https certificate expiration reminder is not available. I have tested many versions myself and found that this function is invalid, including the latest version

### 📝 Relevant log output

```shell
Uptime's https certificate expiration reminder is not available. I have tested many versions myself and found that this function is invalid, including the latest version
```

**Comment by CommanderStorm** [comment]
Repeating a sentence 8x does not mean filling out the form.
Especially if cert-expiry is active (UI fix is in v2.0) and if you are monitoring an https monitor would be interesting..

=> Since effort goes both ways, please fill out the form properly and we can talk
