### ISSUE TITLE
Add failure threshold for notifications

### ISSUE THREAD

**Issue by wolfsilver** [louislam/uptime-kuma#5301]
### 📑 I have found these related issues/pull requests

no related issues

### 🏷️ Feature Request Type

Settings

### 🔖 Feature description

Add an option to create a monitor that sets the threshold for sending notifications.
For example, send notifications only when there are 3 consecutive failures

### ✔️ Solution

When sending a notification, determine if it fails 3 times in a row.

**Comment by CommanderStorm** [comment]
From what I read in your message, that sounds like the retry option.
Could you clairify, what the difference between the existing and proposed feature is? 🤔

**Comment by wolfsilver** [comment]
- In this case, I don't want to send notifications
![image](https://github.com/user-attachments/assets/425ca309-2ba4-40ea-b554-a43e34dd202d)

- Notifications are sent only if there are 3 consecutive failures
![image](https://github.com/user-attachments/assets/68d14406-3000-4917-9547-b4074ae64e3b)

**Comment by CommanderStorm** [comment]
If a website 404s that much, this seems concerning..
Anyway don't see a difference from the retry feature as said about=> closing as resolved 

If I missed something feel free to reopen
