### ISSUE TITLE
Beta build: DNS monitor auto add a condition

### ISSUE THREAD

**Issue by ivancarlosti** [louislam/uptime-kuma#5303]
### 📑 I have found these related issues/pull requests

It's a very small UI bug:

When you create, edit or clone a DNS monitor, it auto-add a condition.

To solve this, I recommend to not add an empty condition automatically or accept the monitor to save an empty one, ignoring it.

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### Description

New, edit or cloned DNS monitor auto-add condition:

![image](https://github.com/user-attachments/assets/924ba102-522f-4e19-bce6-3bfbc618e864)

### 👟 Reproduction steps

Create a new monitor and select "DNS" type, or edit an existent, or clone it.
It will not allow you to save before deleting the generated condition field.

### 👀 Expected behavior

Do not block saving process

### 😓 Actual Behavior

It blocks saving process

### 🐻 Uptime-Kuma Version

2.0.0-beta.0

### 💻 Operating System and Arch

Ubuntu 24.04

### 🌐 Browser

Chrome 130.0.6723.92

### 🖥️ Deployment Environment

- Database: external mariadb
- number of monitors: 16

**Comment by louislam** [comment]
It is also make me wondering what will happen if dns monitors from v1 to v2, since there are no conditions in v1. To be tested later.

**Comment by ivancarlosti** [comment]
> It is also make me wondering what will happen if dns monitors from v1 to v2, since there is no conditions in v1. To be tested later.

I made a v2 fresh install, so no monitor was imported, it happens creating a new, editing or cloning a v2 monitor

**Comment by Ionys320** [comment]
Mmmmh, I can fix it, but it seems to be normal.  @louislam or @CommanderStorm, if one of you can confirm me a fix is needed..

src\components\EditMonitorConditions.vue: 
```js
created() {
    if (this.model.length === 0) {
        this.addCondition();
    }
},
```
