### ISSUE TITLE
Add a random string / number to the monitored URL

### ISSUE THREAD

**Issue by SingHar** [louislam/uptime-kuma#5307]
### 📑 I have found these related issues/pull requests

Unable to find any related issue.

### 🏷️ Feature Request Type

Change to existing monitor

### 🔖 Feature description

It would be helpful if we can append a random string to URL to _potentially_ bypass web cache.

For example:
`https://www.example.com/wp-cron?doing_cron=[RAND_STRING]`

### ✔️ Solution

Inline tags as part of the URL being monitored that can be interpreted / parsed by the monitor.

OR

Additional field to append GET parameters with option to generate random `string` / `number` / `Unix timestamp` while executing the monitor.

### ❓ Alternatives

I cannot think of any alternate to this approach.

### 📝 Additional Context

This will be helpful when I need to monitor (or call) as URL but make sure that the results are not cached.

**Comment by Ionys320** [comment]
This could be easilly done. Just needing to ajust the URL called by Uptime Kuma by replacing `[UNIX_TIME]` with the current UNIX timestamp, or something like that.

**Comment by CommanderStorm** [comment]
resolved by https://github.com/louislam/uptime-kuma/pull/3525

![](https://private-user-images.githubusercontent.com/372067/258447532-0be54122-a24a-4ec3-9f1d-365bfebaff55.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE0Mzk3NjksIm5iZiI6MTczMTQzOTQ2OSwicGF0aCI6Ii8zNzIwNjcvMjU4NDQ3NTMyLTBiZTU0MTIyLWEyNGEtNGVjMy05ZjFkLTM2NWJmZWJhZmY1NS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTExMlQxOTI0MjlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zNTliOTM1YzlmYWZiZjFjYmVlMjMxMTcyNWY4MjEwOWQ0NzkwZDgyODBkOTJiY2RjZGUxMzk3MGFlZGUxN2ViJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.uAqor3fnkWMQNYAAN2525I5-XiV04V-9RlhPhADH19M)

**Comment by SingHar** [comment]
Thank you so much!

**Comment by Root-FTW** [comment]
I don't see the option, how can I activate it?

![image](https://github.com/user-attachments/assets/c6161d5e-c1c4-4c94-9dc4-48b7290599f8)

**Comment by CommanderStorm** [comment]
As stated in another thread:
This is a V2 only feature. Are you currently running the beta?
