### ISSUE TITLE
ghcr.io support

### ISSUE THREAD

**Issue by mariomare22** [louislam/uptime-kuma#5308]
### 📑 I have found these related issues/pull requests

Can you please provide also the updated image on ghcr.io?

### 🏷️ Feature Request Type

Other

### 🔖 Feature description

at the moment the image is available on docker hub only.

### ✔️ Solution

please publish it also to github container registry

**Comment by CommanderStorm** [comment]
Why do you want this? 🤔

**Comment by mariomare22** [comment]
I am running on mikrotik routerOS containers, but it allows using only one registry at time.

**Comment by alexislefebvre** [comment]
See:

- GH-53
- GH-213
- GH-2464, especially this comment: https://github.com/louislam/uptime-kuma/issues/2464#issuecomment-1596287082

**Comment by CommanderStorm** [comment]
> but it allows using only one registry at time

Looking roughly at the docs, it looks like this should be possible..
https://help.mikrotik.com/docs/spaces/ROS/pages/84901929/Container

At least `registry-url` is a parameter there..

**Comment by pascaliske** [comment]
> Why do you want this? 🤔

GHCR has better rate limits and it's also really useful in air-gapped scenarios.

Not to mention how trivial it is to implement this (see those numerous PRs which were opened in the past). 🙂

**Comment by CommanderStorm** [comment]
> better rate limits

The rate limits should not matter for pulling images.
Do they?

> useful in air-gapped scenarios

Could you link specifics?
The [docker docs](https://docs.docker.com/security/for-admins/hardened-desktop/air-gapped-containers/) don't talk about registry specifc limitations..

Doing effort is fine, but it needs to have a reason..
I currently don't see a benefit to switching registrys or having two registies.
Are there other projects that thid this? Could you link to the discussion in their issue tracker?

**Comment by mariomare22** [comment]
Take lsio, they for istance publish the images to every registry even if they have their own

https://docs.linuxserver.io/images/docker-homeassistant/

**Comment by mariomare22** [comment]
> > but it allows using only one registry at time
> 
> 
> 
> Looking roughly at the docs, it looks like this should be possible..
> 
> https://help.mikrotik.com/docs/spaces/ROS/pages/84901929/Container
> 
> 
> 
> At least `registry-url` is a parameter there..

This parameter is global not as per container

**Comment by mariomare22** [comment]
not compared to uptime-kuma but I do this for a fork of caddy I maintain (with dns challenge plugin) to keep the base image up to date.
https://github.com/mariomare22/caddy-dns I did not find it hard at all, but I only use latest/main tag

**Comment by louislam** [comment]
Just pushed the nightly images (don't use this on your production), it seems fine.

**Comment by mariomare22** [comment]
![image](https://github.com/user-attachments/assets/2bac70b5-2094-4cff-87dc-a2b6b55d7418)

<3
