### ISSUE TITLE
Brand customization

### ISSUE THREAD

**Issue by loan-talvat** [louislam/uptime-kuma#531]
Be able to change the logo and possibly a CSS overlay

**Comment by wywywywy** [comment]
I'd like to be able to change the title from "Uptime Kuma" to our brand name as well

**Comment by TheoCouss** [comment]
Yeah that sounds good

**Comment by markdesilva** [comment]
+1 on this

**Comment by jeliasson** [comment]
**+1**: In the meantime, one could (for those of us that uses a reverse proxy) use e.g. nginx's `sub_filter` to manipulate content before forwarding it to the client. For anyone interested, this might give you an idea on how to approach that.

**Filter**
```nginx
sub_filter_once on;
sub_filter_types text/html;
sub_filter '</head>' '</head><style>body { background-color: #0a1128; color: #f1f1f1; }</style>';
```

**Becomes**
![image](https://user-images.githubusercontent.com/865493/145573056-fc86cbd6-7899-46de-84b4-de2e6f2da165.png)

![image](https://user-images.githubusercontent.com/865493/145573364-df9517f9-8f3e-429d-8081-7ad3b3fa7f9b.png)

References
http://nginx.org/en/docs/http/ngx_http_sub_module.html

**Comment by CommanderStorm** [comment]
@loan-talvat 
Given that #712 is merged, is this issue still relevant? If this is resolved, could you please close the issue?
![image](https://github.com/louislam/uptime-kuma/assets/26258709/72c35e1d-1ded-4dfa-a414-fc3db4e77379)
![image](https://github.com/louislam/uptime-kuma/assets/26258709/5b20db8f-cf79-45a6-8c97-a70182ccd0fc)

**Comment by CommanderStorm** [comment]
Closing as resolved
