### ISSUE TITLE
Control Up/Down notifications 

### ISSUE THREAD

**Issue by arthar360** [louislam/uptime-kuma#5316]
### ⚠️ Please verify that this question has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

I want to notify only when the service is down and not when it becomes available again. How can I achieve this?

### 🐻 Uptime-Kuma Version

latest

### 💻 Operating System and Arch

Linux Mint 22

### 🌐 Browser

Any

### 🖥️ Deployment Environment

Doesn’t Apply

**Comment by CommanderStorm** [comment]
Filtering notifications is tracked here:
- https://github.com/louislam/uptime-kuma/issues/508

It is not currently implemnted.
If you want to reduce false-positives, consider using retrys instead.
