### ISSUE TITLE
[Toast] useToast not called properly in pages/EditMonitor.vue

### ISSUE THREAD

**Issue by Dorence** [louislam/uptime-kuma#5323]
### 📑 I have found these related issues/pull requests

No similar bugs have been reported

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### Description

Saving the monitor config not working in monitor editing page.

Look into dev console,

TypeError: Iu.error is not a function
    at Proxy.isInputValid (index-qm3xr2Qi.js:579:4928)
    at Proxy.submit ...

Changing `const toast = useToast;` to `const toast = useToast();` in src/pages/EditMonitor.vue can fix it.

### 👟 Reproduction steps

- Set any custom request body to a HTTP monitor
- Save (success)
- Change HTTP to TCP Port
- Save (failed, there should no be any header)

### 👀 Expected behavior

A toast shows to tell what is going wrong. And user can edit continuing.

### 😓 Actual Behavior

No toast shown and unable to edit.

### 🐻 Uptime-Kuma Version

2.0.0-beta.0

### 💻 Operating System and Arch

Ubuntu 2404 x64

### 🌐 Browser

Microsoft Edge 124.0.2478.80 x64

### 🖥️ Deployment Environment

- Runtime: nodejs 18
- Database: default sqlite
- Filesystem used to store the database on: ext4
- number of monitors: 20+

**Comment by CommanderStorm** [comment]
Since you already debugged this, would you like this change be credited to you (via an PR)?

**Comment by Dorence** [comment]
Sure, new PR https://github.com/louislam/uptime-kuma/pull/5333
