### ISSUE TITLE
Can monitors return to “active” automatically?

### ISSUE THREAD

**Issue by mklemme1** [louislam/uptime-kuma#5329]
### ⚠️ Please verify that this question has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

I monitor my websites with Uptime Kuma
A site may go down, but come back up 15 minutes later.
In that case I would expect the monitor to return to “active”. It would be nice to receive an email as well.
Instead, I apparently need to log in, pause the monitor, and then resume it again to get it back to “active”.

Am I missing something?

### 🐻 Uptime-Kuma Version

1.23.15

### 💻 Operating System and Arch

Docker image on Ubuntu

### 🌐 Browser

Firefox

### 🖥️ Deployment Environment

- Runtime: Docker version 27.3.1, build ce12230
- Database: sqlite/embedded
- Filesystem used to store the database on: EXT4
- number of monitors: 16

**Comment by CommanderStorm** [comment]
That is a bug.
Is the bug reproducible?
What monitors are you using?

**Comment by mklemme1** [comment]
Yes, it happened twice.

It is a monitor on a Nextcloud instance https://URL/status.php returns a JSON, but I did not add a JSON check in the configuration.
* Monitor Type: HTTP(s)
* URL:  ...
* Heartbeat Interval: 1800
* Retries: 10
* Resend Notification if Down X times consecutively: 0
* Method: GET
* Body Encoding: JSON
* Body: [empty]
* Accepted Status Codes: 200

I now tested it with another server, but could not reproduce the issue any more.
I have now deleted the monitor and recreated it.
Let's see what is happening.

**Comment by mklemme1** [comment]
The copied monitor works well.
Thanks for helping.
