### ISSUE TITLE
2FA, Authentication madness

### ISSUE THREAD

**Issue by jtagcat** [louislam/uptime-kuma#533]
![image](https://user-images.githubusercontent.com/38327267/135754693-68ae5c1a-fd34-42b0-a2f9-61dab6185dda.png)
![image](https://user-images.githubusercontent.com/38327267/135754698-86399d6f-20aa-480b-88a6-4c39d3b58270.png)
![image](https://user-images.githubusercontent.com/38327267/135754715-ab666394-0053-4941-adf1-68b9cb333e3f.png)

- [ ] Show 2FA status (is enabled/disabled) right on the settings page
  - [ ] Show 'Disable 2FA' right there. It asks for confirmation anyway.
- [ ] If the page hasn't been refreshed and the user is setting up 2FA again, old code is retained in the field, its old validation is in effect, yet the code is invalid to the new challenge.
- [ ] Verify token and Save button should be the same thing.
- [ ] No confirmation should be asked 'are you sure you want to turn on 2FA'. Not much terrible can happen. The user has already confirmed their access by providing a valid response to the challenge.
- [ ] Reauthentication should take place to enable/disable 2FA?
  - [ ] are you sure to disable can be replaced by 'auth to disable'
- [ ] Recovery code(s)? 
- [x] **With authentication disabled, enabling 2FA locks you out of the account.** (old password is used)
- [ ] Entering a wrong password and then entering a right password doesn't clear the 'wrong creds' error. It is retained in the 2FA section.
- [ ] 2FA login doesn't have any title. You place unnecessary titles everywhere, yet here there is space. What token? 2FA token? Bot token?
      ![image](https://user-images.githubusercontent.com/38327267/135755206-cbdceadd-d3e4-4a2a-ab04-c2edf38eb9ad.png)

This is dumb design! /friendly

**Comment by louislam** [comment]
> Dumb design! /friendly /pissed

Excuse me, are these bad words in English?

Could you please show some respect? All our contributors were using our free time to implement it. And please understand nothing in the world can be perfect in the first release. 

We accept enhancement suggestions or bug reports, but not the words like this.

**Comment by Ponkhy** [comment]
Please watch your language~
I entirely agree with @louislam! 

You are free anytime to make a PR about the complains you have.

**Comment by jtagcat** [comment]
Aight, I shall take back the insult.  
Still mad about the effort put in to making and translating unneeded buttons, that hide info, and clutter the UI.

I'm summoned from translations, otherwise I barely use uptime-kuma, I don't even use the mentioned features.  
I can be pinged for v0, but can't watch the whole repo.
