### ISSUE TITLE
Allow configuring of request method for webhooks

### ISSUE THREAD

**Issue by michel929** [louislam/uptime-kuma#5330]
### 📑 I have found these related issues/pull requests

I haven't found anything comparable but I may be wrong.

### 🏷️ Feature Request Type

New notification-provider

### 🔖 Feature description

A custom notification provider that issues a POST request as a notification.
So that you can use your own API, for example.

### ✔️ Solution

Create a new notification provider with the input fields:
 - url
 - Header 
 - Authentication
 - Body

**Comment by xiantiao233** [comment]
oh, i need it
please provide enough variables, thanks

**Comment by CommanderStorm** [comment]
The FR is already provided via the webhook monitor
![image](https://github.com/user-attachments/assets/9310d586-9420-4696-b2f1-5f0ef2d7e7eb)

If you need better templating than what v1 proivides, please use https://github.com/louislam/uptime-kuma/releases/tag/2.0.0-beta.0 instead.
