### ISSUE TITLE
nightly2 - Change to HTTP(s) monitor Request Timeout does not persist

### ISSUE THREAD

**Issue by matthuisman** [louislam/uptime-kuma#5337]
### 📑 I have found these related issues/pull requests

none

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 👟 Reproduction steps

Create http(s) monitor to https://www.example.com
Set the Request Timeout to 5
Save
Edit the monitor
Notice Request Timeout is back to its original value (cant recall - 46 seconds or something)

### 👀 Expected behavior

The monitor saves the new value for Request Timeout and uses it

### 😓 Actual Behavior

Monitor does not save the request timeout value

### 🐻 Uptime-Kuma Version

nightly2

### 💻 Operating System and Arch

Docker

### 🌐 Browser

Chrome

### 🖥️ Deployment Environment

- Runtime:  docker
- Database: builtin mariadb
- Filesystem used to store the database on: docker mounted volume
- number of monitors: 1

**Comment by louislam** [comment]
Confirmed. That is strange, I can't remember which pull request touched this.
