### ISSUE TITLE
Add PushPlus notification

### ISSUE THREAD

**Issue by vipmc838** [louislam/uptime-kuma#5338]
### 📑 I have found these related issues/pull requests

添加PushPlus通知

### 🏷️ Feature Request Type

New notification-provider

### 🔖 Feature description

添加PushPlus通知

### ✔️ Solution

添加PushPlus通知

### ❓ Alternatives

添加PushPlus通知

### 📝 Additional Context

添加PushPlus通知添加PushPlus通知

**Comment by CommanderStorm** [comment]
Duplicate of https://github.com/louislam/uptime-kuma/issues/3453
