### ISSUE TITLE
Sizing - Recommendations 

### ISSUE THREAD

**Issue by Ejant** [louislam/uptime-kuma#5341]
### ⚠️ Please verify that this question has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

Well, this is more a sort of question than an issue. 
I've been using Kuma for a while, it works great and I'm planning to put over 250 domains being monitored running in Docker. Are there any recommendations on this? Will this lead to perfomance issues? Is sqlite enough for this amount of domains?

### 🐻 Uptime-Kuma Version

1.23.15

### 💻 Operating System and Arch

Debian 11 x86_64

### 🌐 Browser

Chrome 

### 🖥️ Deployment Environment

- Runtime: Docker 24.04
- Database:  sqlite
- Filesystem used to store the database on: HDD
- number of monitors: 250

**Comment by CommanderStorm** [comment]
> Uptime-Kuma Version
> 1.23.15

Please run large deployoments only on v2.
You will notice the performance improvements.
See https://github.com/louislam/uptime-kuma/releases/tag/2.0.0-beta.0 for further context.

250 should not be an issue.
For sizing:
- Don't pay for more than one vCPU, current architecutre cannot use more.
- sqlite is likely suffient in v2 for 250 monitors, but we have not benchmarked anything currently.

**Comment by Ejant** [comment]
All good!
