### ISSUE TITLE
Bug: Uptime Kuma Settings Not Persisting After Changes.

### ISSUE THREAD

**Issue by homelab-alpha** [louislam/uptime-kuma#5349]
### 📑 I have found these related issues/pull requests

I have checked, but couldn’t find anything similar.

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### Description

It seems that some settings are not being saved. These include the following settings:

**Appearance:**

- Theme
  - Theme - Light/Dark/Auto
  - Theme - Heartbeat bar: Normal/Bottem/None
  - Elapsed time under the heartbeat bar: Show (no line)/Show (with line)/None

**Notifications:**

- Monitor Toast Notifications
  - Timeout for error notifications.
  - Timeout for success notifications.

When you change one or more settings, they are temporarily stored via a cookie in the browser. If you clear the cookies or do not store cookies, and close the browser, the settings will revert to the default settings.

I have checked the database, and the settings are not being saved. It seems that all settings you can adjust in Uptime Kuma should be automatically stored in the database to ensure they persist.

Screenshot:

![screenshot_uptime_kuma_db](https://github.com/user-attachments/assets/f191c364-e871-438b-96a5-bba6b2c15626)

### 👟 Reproduction steps

```docker-compose.yml
---
networks:
  uptime-kuma-beta_net:
    attachable: false
    internal: false
    external: false
    name: uptime-kuma-beta
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.20.3.0/24
          ip_range: 172.20.3.0/24
          gateway: 172.20.3.1
    driver_opts:
      com.docker.network.bridge.default_bridge: "false"
      com.docker.network.bridge.enable_icc: "true"
      com.docker.network.bridge.enable_ip_masquerade: "true"
      com.docker.network.bridge.host_binding_ipv4: "0.0.0.0"
      com.docker.network.bridge.name: "uptime-kuma"
      com.docker.network.driver.mtu: "1500"
    labels:
      com.uptime-kuma-beta.network.description: "is an isolated bridge network."

services:
  uptime-kuma-beta_db:
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "1M"
        max-file: "2"
    stop_grace_period: 1m
    container_name: uptime-kuma-beta_db
    image: mariadb:latest
    pull_policy: if_not_present
    volumes:
      - /docker/uptime-kuma-beta/db:/var/lib/mysql
    environment:
      PUID: "1000"
      PGID: "1000"
      TZ: Europe/Amsterdam
      MYSQL_ROOT_PASSWORD: "ThisIsADemoRootPassword"
      MYSQL_DATABASE: "uptime_kuma_db"
      MYSQL_USER: "uptime-kuma"
      MYSQL_PASSWORD: "ThisIsADemoPassword"
    command:
      [
        "--transaction-isolation=READ-COMMITTED",
        "--log-bin=binlog",
        "--binlog-format=ROW",
      ]
    hostname: uptime-kuma-beta_db
    networks:
      uptime-kuma-beta_net:
        ipv4_address: 172.20.3.2
    security_opt:
      - no-new-privileges:true
    labels:
      com.uptime-kuma-beta.db.description: "is an MySQL database."
    healthcheck:
      disable: true

  uptime-kuma-beta_app:
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "1M"
        max-file: "2"
    stop_grace_period: 1m
    container_name: uptime-kuma-beta
    image: louislam/uptime-kuma:2.0.0-beta.0
    pull_policy: if_not_present
    depends_on:
      uptime-kuma-beta_db:
        condition: service_started
    links:
      - uptime-kuma-beta_db
    volumes:
      - /docker/uptime-kuma-beta/app:/app/data
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /usr/local/share/ca-certificates:/app/data/docker-tls
    environment:
      PUID: "1000"
      PGID: "1000"
      TZ: Europe/Amsterdam
      # This is a certificate authority for demonstration purposes.
      # NODE_EXTRA_CA_CERTS: /app/data/docker-tls/root_ca_demo_cert.pem
      MYSQL_HOST: "uptime-kuma-beta_db"
      MYSQL_PORT: 3306
      MYSQL_NAME: "uptime_kuma_db"
      MYSQL_USER: "uptime-kuma"
      MYSQL_PASSWORD: "ThisIsADemoPassword"
    domainname: status.local
    hostname: status
    networks:
      uptime-kuma-beta_net:
        ipv4_address: 172.20.3.3
    ports:
      - "3001:3001/tcp" # HTTP
      - "3001:3001/udp" # HTTP
    security_opt:
      - no-new-privileges:true
    labels:
      com.docker.compose.project: "uptime-kuma-beta"
      com.uptime-kuma-beta.description:
        "is an self-hosted monitoring tool that allows you to monitor uptime,
        status, and notifications for various services and domains."
    healthcheck:
      disable: true
```

### 👀 Expected behavior

All settings should be persistently saved.

### 😓 Actual Behavior

Not all settings are being persistently saved.

### 🐻 Uptime-Kuma Version

2.0.0-beta.0

### 💻 Operating System and Arch

Ubuntu Server 24.04.1 LTS (GNU/Linux 6.8.0-48-generic x86_64)

### 🌐 Browser

Brave version 1.73.89 (Chromium: 131.0.6778.69) (Official Build) (64-bit)

### 🖥️ Deployment Environment

- **Runtime:** Docker version 26.1.0, build 9714adc
- **Runtime:** docker-compose version 1.29.2, build unknown
- **Runtime:** Portainer Business Edition version 2.21.4
- **Database:** MariaDB (external)
- **Filesystem used for the database:** Linux/ext4 on an SSD
- **Number of monitors:** 90

### 📝 Relevant log output

```shell
There is no relevant log output.
```

**Comment by louislam** [comment]
Duplicate of https://github.com/louislam/uptime-kuma/issues/1858

And it was by design. Software like Telegram Desktop also behave like this.

**Comment by homelab-alpha** [comment]
@louislam, I’m sorry, but Uptime Kuma is not Telegram Desktop; it is a separate entity. As an administrator, I would like the settings I’ve configured to be retained and not dependent on a cookie(s).

For people who prioritize security and ensure that all cookies are deleted when closing a tab or browser (since cookie hijacking is a serious risk), this is an important issue.

In issue #1858 (2022), you yourself indicated that this is a feature request. It seems to me that by now, in 2024 with Uptime Kuma 2.0, this could be implemented.

![label](https://github.com/user-attachments/assets/18207bc7-e6d6-49a3-b3a6-bf6d5998ba6d)


Please don’t take this as an attack on you or Uptime Kuma, but rather as constructive criticism.

I hope I can convince you to add this feature.
