### ISSUE TITLE
create an empty security issue

### ISSUE THREAD

**Issue by griisemine** [louislam/uptime-kuma#5351]
Your GitHub Advisory URL: https://github.com/louislam/uptime-kuma/security/advisories/GHSA-2qgm-m29m-cj2h

**Comment by Ionys320** [comment]
Hi @louislam, don't hesitate to reach me if it's urgent

**Comment by louislam** [comment]
Thanks. I have figured out how to fix it. I will release the patch for v1 and v2.

**Comment by CommanderStorm** [comment]
https://github.com/louislam/uptime-kuma/security/advisories/GHSA-2qgm-m29m-cj2h#event-390209
