### ISSUE TITLE
The group monitor is not functioning correctly and shows inaccurate counts.

### ISSUE THREAD

**Issue by Chris-sentbe** [louislam/uptime-kuma#5366]
### 📑 I have found these related issues/pull requests

nothing reported

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### Description

![화면 캡처 2024-11-21 174907](https://github.com/user-attachments/assets/a219b9b1-184e-496e-979b-8050ee97460d)
![화면 캡처 2024-11-21 175018](https://github.com/user-attachments/assets/7a26cd8f-7e8c-4a4b-8277-4d06774f0fb4)
![화면 캡처 2024-11-21 182147](https://github.com/user-attachments/assets/b55dd9db-79d2-488b-9773-3b5a2cd5f201)

### 👟 Reproduction steps

When I create a Test Group and assign Test Cases under it, the results marked as "offline" are not being counted in the Group.

### 👀 Expected behavior

The Offline values of the cases under the Group should be accurately reflected in the Group's SLA results.

### 😓 Actual Behavior

The test results under the Group are sometimes reflected in the Group's SLA results and sometimes not.

This issue particularly occurs when there is a short Offline period followed by recovery.

Could this be related to the heartbeat of the monitor group?

I believed the monitor group should contain all Offline status of its sub-items.

### 🐻 Uptime-Kuma Version

2.0.0 beta

### 💻 Operating System and Arch

amazon linux 2023 6.1.109-118.189

### 🌐 Browser

Chrome 130.0.6723.119

### 🖥️ Deployment Environment

- Runtime: Docker 25.0.6
- Database: sqlite
- Filesystem used to store the database on: AWS EBS XFS on a ssd
- number of monitors: 16

### 📝 Relevant log output

```shell
nothing speical in a docker logs
```

**Comment by CommanderStorm** [comment]
On what schedule have you set the group monitor to check the contained statues compared to the schedule of the statuses?

**Comment by Chris-sentbe** [comment]
<img width="1414" alt="제목 없음" src="https://github.com/user-attachments/assets/08453468-9224-4817-a3b7-d142f60f59e6">
it is all same

**Comment by Chris-sentbe** [comment]
It seems that "Group" does not check if a local item recovers within 20 seconds. Very brief interruptions are not included in the SLA, so it might not be considered a bug. Instead, I'll need to request a feature enhancement.
