### ISSUE TITLE
password protected status pages

### ISSUE THREAD

**Issue by nabz-polo** [louislam/uptime-kuma#5372]
### 📑 I have found these related issues/pull requests

password protected status pages

### 🏷️ Feature Request Type

Status-page

### 🔖 Feature description

password protected status pages

### ✔️ Solution

password protected status pages

### ❓ Alternatives

password protected status pages

### 📝 Additional Context

password protected status pages

**Comment by CommanderStorm** [comment]
Duplicate of https://github.com/louislam/uptime-kuma/issues/1050
