### ISSUE TITLE
Verify response data

### ISSUE THREAD

**Issue by markg85** [louislam/uptime-kuma#5383]
### 📑 I have found these related issues/pull requests

None

### 🏷️ Feature Request Type

API / automation options, Change to existing monitor

### 🔖 Feature description

When doing an HTTP request, specifically one that responds with json, i'd like to verify that the response is as expected.

### ✔️ Solution

Verify response data.

### ❓ Alternatives

None

### 📝 Additional Context

I have http endpoints where they return json content. In the event of the backend database not responding they still respond with json but just with an error message in that content. It would be cool if i could verify a response to a known value which would mean the service is up and running as intended.

There might well be an option for this already, i just wasn't able to find it.

**Comment by Ionys320** [comment]
Hi! Did you check "HTTP(s) - Json Query" monitor? It may match your needs!
![image](https://github.com/user-attachments/assets/5bc9ed41-85ab-4289-8550-19b6905ab89a)
