### ISSUE TITLE
Manually Triggering Uptime Kuma Notifications for Various Monitor Statuses

### ISSUE THREAD

**Issue by homelab-alpha** [louislam/uptime-kuma#5387]
### ⚠️ Please verify that this question has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

I have been working on updating and adding new features to `slack.js` (Slack Notifications) for some time now. Currently, I am testing notifications for **UP**, **DOWN**, **certificate expiry**, and the **Test button** status. For most monitor configurations, I can deliberately cause an error to generate a notification. However, this method of testing is not sustainable in the long run.

There are also other notifications, such as fallback notifications and those related to monitor types I am not familiar with or do not use. Unfortunately, I do not have the time or resources to go through the full documentation for each monitor option and set everything up in my homelab.

My question is: **Is there a way to manually trigger all the notifications that Uptime Kuma can generate?** Ideally, this would be possible for each individual monitor type. The main focus is on manually triggering the following notifications:

- **Status codes:**

  - 0 (DOWN)
  - 1 (UP)
  - 2 (PENDING)
  - 3 (MAINTENANCE)

- **Fallback notifications:**

  - Certificate expiry in X days
  - Fallback notifications without monitor/heartbeat status code

### 📝 Error Message(s) or Log

There is no relevant log output.

### 🐻 Uptime-Kuma Version

2.0.0-beta.0

### 💻 Operating System and Arch

Ubuntu Server 24.04.1 LTS (GNU/Linux 6.8.0-48-generic x86_64)

### 🌐 Browser

Brave version 1.73.89 (Chromium: 131.0.6778.69) (Official Build) (64-bit)

### 🖥️ Deployment Environment

- **Runtime:**
  - Docker version 26.1.0, build 9714adc
  - docker-compose version 1.29.2, build unknown
  - Portainer Business Edition version 2.21.4
  - MariaDB 11.6.2
- **Database:** MariaDB (external)
- **Filesystem used for the database:** Linux/ext4 on an SSD
- **Number of monitors:** 92

**Comment by homelab-alpha** [comment]
@louislam,  @CommanderStorm

Is there a way to manually trigger all the notifications that Uptime Kuma can generate?

**Comment by CommanderStorm** [comment]
There is currently no ergonomic way of doing this.
Current way is registering a monitor which is representing each message:
- UP (`https://google.com`),
- DOWN (`https://does-not-exist-sadlkfasfdln.com`) or
- has an expired cert (`https://expired.badssl.com`).

**Comment by homelab-alpha** [comment]
> There is currently no ergonomic way of doing this. Current way is registering a monitor which is representing each message:
> 
>     * UP (`https://google.com`),
> 
>     * DOWN (`https://does-not-exist-sadlkfasfdln.com`) or
> 
>     * has an expired cert (`https://expired.badssl.com`).

For the following monitors, everything is working:

- HTTP/HTTPS
- TCP Port
- Ping
- HTTP/HTTPS (Keyword)
- HTTP/HTTPS (JSON Query)
- DNS
- Docker Container
- MySQL/MariaDB

The following monitors are problematic, and I cannot guarantee they are working due to issues with `validURL`:

- gPRC/gPRCs (Keyword)
- HTTPS (Browser Engine Chrome/Chromium BETA)
- Steam Game Server
- GameDig
- MQTT
- RabbitMQ
- Kafka Producer
- Microsoft SQL Server
- PostgreSQL
- MongoDB
- RADIUS
- Redis

Perhaps you can point me in the right direction to where the notification call functions are in the code, so I can investigate how to trigger them manually, if that is possible.

**Comment by CommanderStorm** [comment]
Prefacing this:
I don't think you actually need to do this. That is a lot of effort with likely little benefit ^^

Depending on which monitor, they are
- still in "the blob" https://github.com/louislam/uptime-kuma/blob/master/server/model/monitor.js
- extracted into their own provider https://github.com/louislam/uptime-kuma/tree/master/server/notification-providers

**Comment by homelab-alpha** [comment]
@CommanderStorm, I agree that it's a lot of work with minimal benefits. If I ever have enough time, I'll try to create a script to test the internal notification system, including integration with the other notification providers. This script should be easy to use within Node, for example with `node testNotification.js`. But don't get too excited about it! It would take many hours, which I don't have at the moment—something for the future, perhaps. 😊
