### ISSUE TITLE
Publish new versions to Github container registry (ghcr.io)

### ISSUE THREAD

**Issue by nopoz** [louislam/uptime-kuma#5392]
### 📑 I have found these related issues/pull requests

did a search, didn't find anything related

### 🏷️ Feature Request Type

Deployment

### 🔖 Feature description

I hope you're doing well! I wanted to suggest publishing container packages to this repository (e.g., ghcr.io/) as an alternative to Docker Hub for pulling updates. Docker Hub’s daily rate limits for polling containers can be quite restrictive, so having another option would be incredibly helpful for users.

Thanks so much for considering this, and keep up the great work!

### ✔️ Solution

publish container versions to ghcr.io so users can pull container updates using an image path of ghcr.io/louislam/uptime-kuma:<version>

documentation reference: https://docs.github.com/en/packages/working-with-a-github-packages-registry/working-with-the-container-registry

### ❓ Alternatives

n/a

### 📝 Additional Context

n/a

**Comment by CommanderStorm** [comment]
We already do that
https://github.com/louislam/uptime-kuma/pkgs/container/uptime-kuma

**Comment by nopoz** [comment]
> We already do that https://github.com/louislam/uptime-kuma/pkgs/container/uptime-kuma

Yeah but there are no actual versions there - just nightlies and hash commits. Are there plans for adding versioned packages?

**Comment by CommanderStorm** [comment]
We will release future versions (anything after the V2 beta) there as well
