### ISSUE TITLE
[2.0.0-beta.0] Fix package.json « setup »

### ISSUE THREAD

**Issue by dugwood** [louislam/uptime-kuma#5394]
### 📑 I have found these related issues/pull requests

https://github.com/louislam/uptime-kuma/pull/5269 => same issue maybe (doesn't update automatically)
https://github.com/louislam/uptime-kuma/issues/5391 => seems related to v1.x

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### Description

Wrong git's branch in the `package.json`.

See https://github.com/louislam/uptime-kuma/blob/2.0.0-beta.0/package.json#L43C1-L44C1

Currently:
> "setup": "git checkout 1.23.15 && npm ci --production && npm run download-dist",

Should read:
> "setup": "git checkout 2.0.0-beta.0 && npm ci --omit=dev && npm run download-dist",

Can't it be set by reading the current git branch?

### 👟 Reproduction steps

Install 2.0.0-beta.0, then run `npm run setup` which shows the wrong version of git branch:
```
> uptime-kuma@2.0.0-beta.0 setup
> git checkout 1.23.15 && npm ci --production && npm run download-dist
```

### 👀 Expected behavior

Use the current git branch

### 😓 Actual Behavior

Forced version within the `package.json`

### 🐻 Uptime-Kuma Version

2.0.0-beta.0

### 💻 Operating System and Arch

Linux

### 🌐 Browser

Not relevant

### 🖥️ Deployment Environment

- Runtime: node 18
- Database: not relevant
- Filesystem used to store the database on: ext4
- number of monitors: not relevant

**Comment by louislam** [comment]
> Migration Steps (Non-Docker)
Beta is not available for non-docker yet.

https://github.com/louislam/uptime-kuma/wiki/Migration-From-v1-To-v2

**Comment by plegrand1** [comment]
Hello,
so if I want to test the new version of Uptime Kuma the procedure would be as follows?


```
cd <uptime-kuma-directory>

# Update from git
git fetch --all
git checkout 2.0.0-beta.0 --force

# Install dependencies and prebuilt
npm install --production
npm run download-dist

# Restart
pm2 restart uptime-kuma
```
As you can perhaps see, I'm not very familiar with github.
Merci pour votre aide.
Pascal

**Comment by dugwood** [comment]
@plegrand1 if you checkout from github on the `2.0.0-beta.0` branch, you just need the `npm` part (and the `pm2` depending on how you run it, in my case I use a dedicated script that just run `node server/server.js` in the background).
