### ISSUE TITLE
Cluster Uptime Kuma

### ISSUE THREAD

**Issue by matthewogrady** [louislam/uptime-kuma#5396]
### ⚠️ Please verify that this question has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

Single instance of uptime kuma uses 100% cpu but if i increase the workers this causes the dashboard websockets to fail.

looking to utilise more of the CPUby spreading the load across multiple node worker processes.

### 🐻 Uptime-Kuma Version

1.23.15

### 💻 Operating System and Arch

debian

### 🌐 Browser

chrome

### 🖥️ Deployment Environment

node js 18
embedded
btrfs

**Comment by CommanderStorm** [comment]
This is not currently possible.
If you want to reduce the load, please use the beta of v2. See #4500 or the release notes for details on the improvements made

**Comment by matthewogrady** [comment]
We don’t currently run uptime kuma in docker so cant update to the latest version?

When will this be released for non docker or is there an easy way to convert from standalone to docker instance?

**Comment by markku636** [comment]
I developed a clustered version of Uptime Kuma based on beta v2.0.5.

https://github.com/markku636/uptime-kuma-cluster/blob/main/README.en.md
