### ISSUE TITLE
JSON status page output

### ISSUE THREAD

**Issue by danielhoherd** [louislam/uptime-kuma#5399]
### 📑 I have found these related issues/pull requests

I could not find any related issues.

### 🏷️ Feature Request Type

Status-page

### 🔖 Feature description

I would like the ability to fetch status pages as JSON output.

### ✔️ Solution

I imagine this feature allowing the user to append `.json` to the end of a status page URL and have the result returend as json data.

### ❓ Alternatives

Alternatively I could parse the HTML contents of the status page to get the data I need. This is not nearly as portable, and is probably more brittle than having json output directly from the app itself.

**Comment by pprazzi99** [comment]
Not sure if that's helpful but you can use prom2json to scrape metrics as json, but built-in feature would be awesome!

**Comment by CommanderStorm** [comment]
what about the existing, undocumented API the status page uses? `/api/status-page/heartbeat/SLUG`

**Comment by danielhoherd** [comment]
@CommanderStorm that is interesting, and almost there. Unfortunately it doesn't include all of the data that is included on the status page, like the name of what is being monitored.

**Comment by CommanderStorm** [comment]
> Unfortunately it doesn't include all of the data that is included on the status page, like the name of what is being monitored

Status page config, incident, monitor list is avaliable via `/api/status-page/:slug`

> which is identical to the behavior of the status page

As an explainaition why this does have auth:
The metrics service exposes all services, not just the ones marked as public by putting them on a status page.

**Comment by gaby** [comment]
@CommanderStorm Am assuming that ":slug" means the name of the status page?
