### ISSUE TITLE
Which docker should i use for eligibility of mariadb?

### ISSUE THREAD

**Issue by berkayalan** [louislam/uptime-kuma#5407]
### ⚠️ Please verify that this question has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

Hey, I want to run uptime-kuma on aws ecs and use mariadb for permanent data. I was using latest docker image but i see that mariadb support is v2.0 feature.(https://github.com/louislam/uptime-kuma/issues/4500) Which docker image should I use for that?

### 📝 Error Message(s) or Log

I see that even though i configure it for mariadb:

2024-12-04T14:50:00Z [DB] INFO: SQLite config:
--
| 2024-12-04T14:50:00.701Z | [ { journal_mode: 'wal' } ]
| 2024-12-04T14:50:00.702Z | [ { cache_size: -12000 } ]
| 2024-12-04T14:50:00.704Z | 2024-12-04T14:50:00Z [DB] INFO: SQLite Version: 3.41.1

### 🐻 Uptime-Kuma Version

1.23.15

### 💻 Operating System and Arch

ECS Fargare

### 🌐 Browser

Google Chrome

### 🖥️ Deployment Environment

- Runtime:  AWS ECS Fargate
- Database: 
- Filesystem used to store the database on: 
- number of monitors:

**Comment by mabed-fr** [comment]
Hello,

The most optimal solution is 

louislam/uptime-kuma:beta-slim


docker pull louislam/uptime-kuma:beta-slim

All you have to do is configure the environment variables :)

**Comment by CommanderStorm** [comment]
https://github.com/louislam/uptime-kuma/releases/tag/2.0.0-beta.0

V2.0 is not a stable release => is currently behind the `beta` tag

**Comment by berkayalan** [comment]
Thanks @mabed-fr , i have already passed environment variables but using the right docker works for me. Thanks!
