### ISSUE TITLE
prevent ipv6 dns lookups

### ISSUE THREAD

**Issue by dduster** [louislam/uptime-kuma#5415]
### ⚠️ Please verify that this question has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

My instance (running as a docker container) is performing IPv6 (AAAA record) queries each time it performs DNS lookup (in addition to IPv4 A record lookup). This is not an issue in and of itself, but it does clobber my pi-hole logs...

Apparently, I am on a quest to remove as much IPv6 traffic from my network as possible.

I've verified IPv6 is disabled on the container, and played a bit with its resolve.conf - alas, no progress:

```
nameserver 192.168.10.4
nameserver 192.168.20.4
options ndots:0
options  single-request
```

Anyone knows how to prevent such queries?

Thanks!

### 🐻 Uptime-Kuma Version

1.23.11

### 💻 Operating System and Arch

Linux uptime-kuma 4.4.302+

### 🌐 Browser

Chrome 131.0.6778.110

### 🖥️ Deployment Environment

- Runtime: Docker version 20.10.23, build 876964a / Synology DSM 7
- Database: 
- Filesystem used to store the database on: 
- number of monitors: ~30

**Comment by CommanderStorm** [comment]
> Anyone knows how to prevent such queries?

That is not currently a feature we offer.

Lets track this in the other issues instead:
- https://github.com/louislam/uptime-kuma/issues/1242
- https://github.com/louislam/uptime-kuma/issues/1025
