### ISSUE TITLE
On Status Page : understand Specification: MicroProfile Health Version: 3.0

### ISSUE THREAD

**Issue by marteloudini** [louislam/uptime-kuma#5421]
### 📑 I have found these related issues/pull requests

hey,
i use many µServices Quarkus Camel, and on it have a HealthCheck, all µService expose /q/health url for say the health, live, readless of my µService.
It is MicroProfile Health output standard.
https://download.eclipse.org/microprofile/microprofile-health-3.0/microprofile-health-spec-3.0.html
`{
 "$schema": "http://json-schema.org/draft-04/schema#",
 "type": "object",
 "properties": {
   "status": {
     "type": "string"
   },
   "checks": {
     "type": "array",
     "items": {
       "type": "object",
       "properties": {
         "name": {
           "type": "string"
         },
         "status": {
           "type": "string"
         },
         "data": {
           "type": "object",
           "patternProperties": {
             "[a-zA-Z_]*": {
               "type": [
                 "string",
                 "boolean",
                 "number"
               ]
             }
           },
           "additionalProperties": false
         }
       },
       "required": [
         "name",
         "status"
       ]
     }
   }
 },
 "required": [
   "status",
   "checks"
 ],
 "additionalProperties": false
}`

Status 200 and the following payload:

```
{
  "status": "UP",
  "checks": [
    {
      "name": "Camel Route Check",
      "status": "UP",
      "data": {
        "key": "value",
        "foo": "bar"
      }
    }, 
{
      "name": "database check",
      "status": "UP",
      "data": {
        "key": "Name Of DataBase",
        "foo": "Schema."
      }
    }
  ]
}
```
is possible to generate **card** information. i will create "NEW MONITOR" -> "HTTPS" -> url/q/health and receive the json cf before. with for one up a little case in green, down case in red for each sub-status

not only Up or Down but more information because 1 µService https://localhost:1051/totoService/q/health can receive UP DataBase, UP Camel Context, UP Camel Exposed, etc.. , in one JSON to follow the schema spec MicroProfile Health..

thanks you
![Sans titre-22](https://github.com/user-attachments/assets/c7edcb6c-9bac-43fb-a5ed-5706df7699d1)

### 🏷️ Feature Request Type

Status-page

### 🔖 Feature description

Understand response body json Specification: MicroProfile Health
Version: 3.0
And add in tooltip (move over for example) all information json.

### ✔️ Solution

Thanks.

**Comment by CommanderStorm** [comment]
I think the display you are searching for is much to specific and would not be a good fit.
=> I am going to close the FR as not planned

Displaying the results on the dashboard is a valid feature request, but would require a bit more engineering effort to not run into the same performance traps from v1.
On a public status page this is a bit too niche imo.
