### ISSUE TITLE
Add Json Path expression on field in Monitor HTTP(s) Keyword or add new Monitor HTTP(s) JSONPath

### ISSUE THREAD

**Issue by marteloudini** [louislam/uptime-kuma#5423]
### 📑 I have found these related issues/pull requests

n/a

### 🏷️ Feature Request Type

New monitor, Change to existing monitor

### 🔖 Feature description

can use a JSONPath expression to evaluate is UP or DOWN.

example : if i want create a GROUPE with multiple Monitor HTTPS JSONPATH and can see what is down in sub-process.
$.status         --> UP
$.checks..[?(@.name == 'featureV2')].status                ---> DOWN

```
{
  "status": "UP",
  "checks": [
    {
      "name": "myCheck_serviceV1",
      "status": "UP",
      "data": {
        "key": "value",
        "foo": "bar"
      }
    },
     {
      "name": "featureV2",
      "status": "DOWN",
      "data": {
        "key": "value",
        "foo": "bar"
      }
    },
     {
      "name": "featureV3",
      "status": "UP",
      "data": {
        "key": "value",
        "foo": "bar"
      }
    }
  ]
}
```

### ✔️ Solution

yoiu can use the library .js 
https://storage.googleapis.com/google-code-archive-downloads/v2/code.google.com/jsonpath/jsonpath-0.8.0.js.txt

and you can use JsonPath Expression.

**Comment by CommanderStorm** [comment]
We alredy support jsonata expressions via the `HTTP - JSON` monotor.

In the longer term, there are refactorings on their way to migrate to shared infra (see the DNS monitor for further context), but this is not done.
If you'd like to help us in this endevour, our contibution guide is here and I'd love to review PRs in this direction https://github.com/louislam/uptime-kuma/blob/c0fe669cd8f8dcb4a7d3aefae834c7a70bc692db/CONTRIBUTING.md
