### ISSUE TITLE
Docker-compose MySQL Env not work

### ISSUE THREAD

**Issue by drexlma** [louislam/uptime-kuma#5439]
### 📑 I have found these related issues/pull requests

see title

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 👟 Reproduction steps

  uptime-kuma:
    container_name: uptime-kuma
    image: louislam/uptime-kuma
    volumes:
      - ./share/uptime-kuma/data:/app/data
    ports:
      - "3001:3001"
    environment:
      - UPTIME_KUMA_DB_TYPE=mariadb
      - UPTIME_KUMA_DB_HOSTNAME=xxxx
      - UPTIME_KUMA_DB_PORT=3306
      - UPTIME_KUMA_DB_NAME=uptimekuma
      - UPTIME_KUMA_DB_USERNAME=uptimekuma
      - UPTIME_KUMA_DB_PASSWORD=xxxx

### 👀 Expected behavior

see title

### 😓 Actual Behavior

see title

### 🐻 Uptime-Kuma Version

latest

### 💻 Operating System and Arch

Devian 12

### 🌐 Browser

lates

### 🖥️ Deployment Environment

- Runtime: Docker latest
- Database: Docker latest
- Filesystem used to store the database on: 
- number of monitors:

**Comment by CommanderStorm** [comment]
I am not going to investigate this given that you did not respect our time enough to fill out the template.

Effort needs to go both ways and `[..] not work` is not good enough of a description to invest time reproducing. Your issue might be resolved. Cannot tell given that `latest` is not a real version.
If you actually mean latest, you are running v1, where mariadb/mysql is not supported
