### ISSUE TITLE
CSP Problem when refresh

### ISSUE THREAD

**Issue by tony8077616** [louislam/uptime-kuma#5441]
### 📑 I have found these related issues/pull requests

Same with #3806 but I build with Docker and with external cloudflared

![image](https://github.com/user-attachments/assets/0b78d1ea-eada-460c-8056-aa85b4781565)
![msedge_2024-12-16_23-39-03-931](https://github.com/user-attachments/assets/a6f767a8-f269-4275-a026-a21a01da5554)

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### Description

CSP error without add `unsafe-eval` from the `default-src` Content Security Policy directive.

### 👟 Reproduction steps

Use with docker compose

```dockerfile
services:
  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: Cloudflared
    restart: 'unless-stopped'
    depends_on:
      - uptime-kuma
    command: tunnel run
    environment:
      - TUNNEL_TOKEN=
    deploy:
      resources:
        limits:
          memory: 256mb
  uptime-kuma:
    image: louislam/uptime-kuma:beta
    container_name: uptime-kuma
    network_mode: 'host'
    volumes:
      - "./uptime-kuma:/app/data"
    restart: always
    ports:
      - "3001:3001"
    deploy:
      resources:
        limits:
          memory: 256m
  
```
For Content-Security-Policy add to Cloudflare with this string in Modify response header 
`Content-Security-Policy: default-src 'self';     script-src 'self' static.cloudflareinsights.com;     style-src 'self';     img-src 'self' data:;     connect-src 'self';     font-src 'self';     frame-src 'self';`

### 👀 Expected behavior

I expected to see the admin account creation screen, and sure enough, if I use a browser extension to disable the Content Security Policy, everything works as expected.

### 😓 Actual Behavior

Blank screen and console error.

### 🐻 Uptime-Kuma Version

2:beta

### 💻 Operating System and Arch

Windows 11 x64

### 🌐 Browser

Microsoft Edge Canary 133.0.3016.0 x64

### 🖥️ Deployment Environment

- Runtime: Docker Desktop 4.36.0 (175267) 
- Database: sqlite/embedded
- Filesystem used to store the database on: Windows/NTFS
- number of monitors: 2

### 📝 Relevant log output

```shell
Uncaught EvalError: Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "script-src 'self' static.cloudflareinsights.com".

    at new Function (<anonymous>)
    at Wy (index-CgA63pu9.js:49:35380)
    at Py (index-CgA63pu9.js:49:8010)
    at Oy (index-CgA63pu9.js:49:6940)
    at index-CgA63pu9.js:49:15424
    at U (index-CgA63pu9.js:49:15271)
    at Object.B [as t] (index-CgA63pu9.js:49:15411)
    at Object.t (index-CgA63pu9.js:49:21603)
    at Proxy.$t (index-CgA63pu9.js:49:28209)
    at Proxy.data (index-CgA63pu9.js:515:20108)
```

**Comment by tony8077616** [comment]
> I guess you have set something on your Cloudflare like this: https://stackoverflow.com/questions/69853050/content-security-policy-problem-with-cloudflare
> 
Does uptime-kuma support like this?
https://scotthelme.co.uk/csp-nonces-the-easy-way-with-cloudflare-workers/
> FYI, my instance is working fine: https://status.kuma.pet/
> 
Work fine because you doesn't add CSP in header🤔
https://securityheaders.com/?q=https%3A%2F%2Fstatus.kuma.pet&followRedirects=on
![Screenshot_20241218-073309.png](https://github.com/user-attachments/assets/ce6b156c-1b1d-40a9-970d-2ce5cae71bd3)


> Alternatively, you can add a nginx or caddy container, and inject though headers following the Cloudflare docs:
> https://developers.cloudflare.com/fundamentals/reference/policies-compliances/content-security-policies/

Is this another way of saying that uptime-kuma website doesn't support CSP directly?

**Comment by louislam** [comment]
> Is this another way of saying that uptime-kuma website doesn't support CSP directly?

Just re-read your screenshoots, I find that CSP also block Vue.js due to `unsafe-eval` which is our frontend framework. So the answer is yes, Uptime Kuma doesn't support CSP directly currently.

https://stackoverflow.com/questions/65620412/content-security-policy-blocks-vue-js

**Comment by tony8077616** [comment]
> > Is this another way of saying that uptime-kuma website doesn't support CSP directly?
> 
> Just re-read your screenshoots, I find that CSP also block Vue.js due to `unsafe-eval` which is our frontend framework. So the answer is yes, Uptime Kuma doesn't support CSP directly currently.
> 
> https://stackoverflow.com/questions/65620412/content-security-policy-blocks-vue-js

Alright, Thanks your information 
I'll remove CSPs until I found how perfect to config it.💪
