### ISSUE TITLE
Tags cannot be deleted

### ISSUE THREAD

**Issue by koehn** [louislam/uptime-kuma#5442]
### 📑 I have found these related issues/pull requests

Couldn’t find any related issues/pull requests after searching for “tags” 

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### Description

Once added to a monitor, tags cannot be deleted. 

### 👟 Reproduction steps

1. Create a monitor with tags (more than one). Save.
2. Edit the monitor. 
3. When you try to delete a tag by clicking on the “x”, all tags disappear. 
4. If you click “save”, the tags all reappear.
5. If you save and come back to editing that monitor, none of the tags are deleted.

Screen recording:
https://github.com/user-attachments/assets/d29bd4b1-6cd7-4a46-b9b0-8937df900c71

### 👀 Expected behavior

1. Clicking the “x” on the tag would only delete that tag
2. The display would indicate when tags have been deleted
3. Once deleted and saved, tags would remain deleted

### 😓 Actual Behavior

There’s no way for the user to delete a tag. 

### 🐻 Uptime-Kuma Version

2.0.0-beta.0

### 💻 Operating System and Arch

Debian Bookworm on AMD64

### 🌐 Browser

Safari 18.2, Chrome 131.0.6778.140

### 🖥️ Deployment Environment

- Runtime: Docker 27.3.1
- Database: sqlite
- Filesystem used to store the database on: ext4
- number of monitors: 23

**Comment by homelab-alpha** [comment]
@koehn , This issue is addressed in 
- #5298.

See the original post: 
- #5296

**Comment by CommanderStorm** [comment]
@louislam could you publish another beta? 👉👈

**Comment by derekoharrow** [comment]
Sorry, but this doesn't seem to be fixed for me in 2.0.0-beta.1

**Comment by homelab-alpha** [comment]
@derekoharrow, Quick question, did you use the correct image: 'louislam/uptime-kuma:2.0.0-beta.1'?

I just upgraded to 2.0.0-beta.1 and it works correctly for me; I can remove the tags without any issues.

**Comment by derekoharrow** [comment]
> @derekoharrow, Quick question, did you use the correct image: 'louislam/uptime-kuma:2.0.0-beta.1'?
> 
> I just upgraded to 2.0.0-beta.1 and it works correctly for me; I can remove the tags without any issues.

Yes, I pulled the latest image down, an Kuma itself says it is running beta 1 now.

It's weird, with a bit more testing it does seem to be working on most monitors, but not all. Especially if there are multiple tags on the monitor.

I also see that it now shows the tag value as "null" if you don't put something in there, which I don't think is desired - I'll raise a separate issue for that.

**Comment by homelab-alpha** [comment]
@derekoharrow, that’s strange, but I haven’t had any issues with multiple tags either. Please check the video.

https://github.com/user-attachments/assets/3931e702-b799-402c-9599-d64f055e7bae

@louislam, I’ve tested with the built-in SQLite, as well as both internal and external MariaDB.

⚙️ Config file

<details><summary><code>docker-compose.yml</code>(click to expand)</summary>
<p>

```docker-compose.yml
---
networks:
  uptime-kuma-beta_net:
    attachable: false
    internal: false
    external: false
    name: uptime-kuma-beta
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.19.3.0/24
          ip_range: 172.19.3.0/24
          gateway: 172.19.3.1
    driver_opts:
      com.docker.network.bridge.default_bridge: "false"
      com.docker.network.bridge.enable_icc: "true"
      com.docker.network.bridge.enable_ip_masquerade: "true"
      com.docker.network.bridge.host_binding_ipv4: "0.0.0.0"
      com.docker.network.bridge.name: "uptime-kuma"
      com.docker.network.driver.mtu: "1500"
    labels:
      com.uptime-kuma-beta.network.description: "is an isolated bridge network."

services:
  uptime-kuma-beta_db:
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "1M"
        max-file: "2"
    stop_grace_period: 1m
    container_name: uptime-kuma-beta_db
    image: mariadb:latest
    pull_policy: if_not_present
    volumes:
      - /docker/uptime-kuma-beta/db:/var/lib/mysql
    environment:
      PUID: "1000"
      PGID: "1000"
      TZ: Europe/Amsterdam
      MYSQL_ROOT_PASSWORD: "ThisIsADemoRootPassword"
      MYSQL_DATABASE: "uptime_kuma_db"
      MYSQL_USER: "uptime-kuma"
      MYSQL_PASSWORD: "ThisIsADemoPassword"
    hostname: uptime-kuma-beta_db
    networks:
      uptime-kuma-beta_net:
        ipv4_address: 172.19.3.2
    security_opt:
      - no-new-privileges:true
    labels:
      com.uptime-kuma-beta.db.description: "is an MySQL database."
    healthcheck:
      disable: false
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s
      start_interval: 5s

  uptime-kuma-beta_app:
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "1M"
        max-file: "2"
    stop_grace_period: 1m
    container_name: uptime-kuma-beta
    image: louislam/uptime-kuma:2.0.0-beta.1
    pull_policy: if_not_present
    depends_on:
      uptime-kuma-beta_db:
        condition: service_healthy
    links:
      - uptime-kuma-beta_db
    volumes:
      - /docker/uptime-kuma-beta/app:/app/data
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /usr/local/share/ca-certificates:/app/data/docker-tls
    environment:
      PUID: "1000"
      PGID: "1000"
      TZ: Europe/Amsterdam
      # This is a certificate authority for demonstration purposes.
      # NODE_EXTRA_CA_CERTS: /app/data/docker-tls/root_ca_demo_cert.pem
      MYSQL_HOST: "uptime-kuma-beta_db"
      MYSQL_PORT: 3306
      MYSQL_NAME: "uptime_kuma_db"
      MYSQL_USER: "uptime-kuma"
      MYSQL_PASSWORD: "ThisIsADemoPassword"
    domainname: status.local
    hostname: status
    networks:
      uptime-kuma-beta_net:
        ipv4_address: 172.19.3.3
    ports:
      - "3001:3001/tcp" # HTTP
      - "3001:3001/udp" # HTTP
    security_opt:
      - no-new-privileges:true
    labels:
      com.docker.compose.project: "uptime-kuma-beta"
      com.uptime-kuma-beta.description:
        "is an self-hosted monitoring tool that allows you to monitor uptime,
        status, and notifications for various services and domains."
    healthcheck:
      disable: false
      test: ["CMD", "extra/healthcheck"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s
      start_interval: 5s
```

</p>
</details>

**Comment by koehn** [comment]
Deleting a tag in 2.0.0.beta.1 still makes them all disappear, but when after you save they are displayed correctly (and the tag remains deleted). Definitely an improvement.

**Comment by homelab-alpha** [comment]
@koehn I agree with you, it looks strange that all the tags disappear. It seems like all the tags are being removed, although that's not the case. Maybe @Ionys320 knows what's happening, as he was kind enough to create the fix for it.

- #5298

**Comment by Ionys320** [comment]
I'm investigating, you'll see a PR in some few hours!
