### ISSUE TITLE
Constant App Reboots with xhr poll error

### ISSUE THREAD

**Issue by gcortes** [louislam/uptime-kuma#5446]
### 📑 I have found these related issues/pull requests

There was on similar issue, but it had to do with access via BUNKERWEB.

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### Description

I set up the app a year ago and it ran fine initially. I mainly view it via Homepage. After a few months, Homepage started displaying a API error. I didn't say which one. Every so often it would display the status correctly and then error out later. I tried accessing the app with Safari. I get the login screen. When I try to log in, I get the error: [Error: xhr poll error] Reconnecting...
I tried it with Chrome and got in, but I still get the error about every ten seconds, the same as below.

The app is running in a CLX on Proxmox. I installed it with a script. I haven't done any updates to it. When I view the process, I see the CPU usage nearly peg and then drop back down. It does this about every ten seconds.

There's an update, but I don't want to install it when it's so unstable.

I tried disabling access to Uptime-kuma in Homepage. It didn't make any difference

### 👟 Reproduction steps

Log in if you can

### 👀 Expected behavior

No error every ten seconds

### 😓 Actual Behavior

[Error: xhr poll error] Reconnecting...

### 🐻 Uptime-Kuma Version

1.23.11

### 💻 Operating System and Arch

Debian version 12

### 🌐 Browser

Safari, Chrome

### 🖥️ Deployment Environment

- Runtime: 
- Database: 
- Filesystem used to store the database on: 
- number of monitors:

**Comment by gcortes** [comment]
It looks like I fixed it. I had a monitor for Postgresql that had been down for a long time. It took a dozen attempts to delete it. When I did the error went away and CPU usage went down to a small amount.

**Comment by paul-uz** [comment]
Seeing similar when leaving a Browser Engine monitor running that is always down (website is actually up)

Can we get recommended CPU/RAM recquirements?

I'd suggest this is a bug, as the system should'nt get bogged down like this.
