### ISSUE TITLE
Allow Specifying mTLS in addition to other authenticaiton methods

### ISSUE THREAD

**Issue by OrangeDrangon** [louislam/uptime-kuma#5447]
### 📑 I have found these related issues/pull requests

- #2531 
- #3049 
- #4927 
- #4251 

### 🏷️ Feature Request Type

Change to existing monitor

### 🔖 Feature description

Allow mTLS to be specified in addition to other authentication methods like HTTP Basic

### ✔️ Solution

I have mTLS guarding a few of my services endpoints. There is still authentication after mTLS passes. I would like to be able to specify client certificates + another authentication method.

If possible mTLS should be moved out of the authentication section into its own or I should be able to specify multiple authentication options.

### ❓ Alternatives

- removing authentication on any endpoint behind mTLS. This is good for device to device or service to service communication but does not allow for users to access their specific user in non mTLS aware applications.
- disable mTLS on these endpoints. This is possible but I would like to preserve the additional security mTLS provides
- specify the header instead of using the auth setting. this works for my specific case but may not if other people's does not use headers.

### 📝 Additional Context

Thanks for the cool project. If I get time I may give this a go myself. Just a problem I ran into while setting mTLS but not a huge deal. Cheers :)

**Comment by CommanderStorm** [comment]
Needing to auth twice seems strange.
Please use the header to specify HTTP Basic on top of another auth.

=> We won't support doing so as I don't think other people need to auth twice. Seems too nonstandard to support
