### ISSUE TITLE
Status page does not update when services go up/down

### ISSUE THREAD

**Issue by gtmadev** [louislam/uptime-kuma#546]
Very interesting project. Everything works, except...

if I force a service down, I immediately see this reflected on the dashboard. However, when I look at the status page, it never shows the item as down. And the only way I have found to have it show the change is to go to the status page while logged in and click edit button. I don't recall if I needed to actually save anything. But once I do that, or just change anything, the status page will finally show the true status of the service.

I am not behind any proxy at this time and everything is just plain http (port 3001) running on a single docker swarm node.

FYI: I did look at the browser dev console inside the status page, and I don't see any websocket traffic there at all. I also tried clearing cache (CTRL-F5) to refresh, etc. I even opened the status page in private mode just to be sure it was not due to me being logged in somewhere. Same result... item does not update up/down status.

Any ideas??

**Comment by louislam** [comment]
Good point. Currently status page is cached for 5 mins. 

What missing here is that if any services are down, it should not immediately clear the cache. I should improve it.

**Comment by Neer171** [comment]
Hi @louislam Can we add quick stats to status page too?

**Comment by Neer171** [comment]
sorry, I'm new to this technology, but I also want to learn and contribute to this project and learn new things. can you please tell me, from which point I can start?

**Comment by Neer171** [comment]
s

**Comment by Neer171** [comment]
sorry, I'm new to this technology, I'm in learning phase of this tech. can you please tell me, from which point I can start?

**Comment by gtmadev** [comment]
> Good point. Currently status page is cached for 5 mins.
> 
> What missing here is that if any services are down, it should not immediately clear the cache. I should improve it.

Noted, and thanks. I will continue to follow the project and do more testing.

**Comment by louislam** [comment]
> sorry, I'm new to this technology, I'm in learning phase of this tech. can you please tell me, from which point I can start?

I updated the technical skills in `CONTRIBUTING.md` yesterday.
Vue.js and SCSS are the most important skills in the case.
https://github.com/louislam/uptime-kuma/blob/master/CONTRIBUTING.md#key-technical-skills

Btw, it is off topic.

**Comment by louislam** [comment]
It should be improved in 1.9.1, the cache will be cleared if there are any important events.
