### ISSUE TITLE
A way to change notification messages from a setting 

### ISSUE THREAD

**Issue by MaitreGEEK** [louislam/uptime-kuma#5461]
### 📑 I have found these related issues/pull requests

https://github.com/louislam/uptime-kuma/issues/2109 it seems they needed to modify the message through the code. I want to be able to do it directly from the app

### 🏷️ Feature Request Type

Settings

### 🔖 Feature description

A way in the settings to change the notification content (from discord for example)

### ✔️ Solution

Well, I'll say adding a variable instead of the text in the file discord.js

### ❓ Alternatives

Maybe, editing it directly for each notification

**Comment by CommanderStorm** [comment]
So you want templating.
This is tracked in https://github.com/louislam/uptime-kuma/issues/646

=> Closing as a duplicate
