### ISSUE TITLE
Docker Hub v1.23.16 is missing

### ISSUE THREAD

**Issue by maxkratz** [louislam/uptime-kuma#5462]
### 📑 I have found these related issues/pull requests

Related to https://github.com/louislam/uptime-kuma/issues/4890.

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### Description

Docker Hub (https://hub.docker.com/r/louislam/uptime-kuma/tags) is missing the container image for v1.23.16.

### 👟 Reproduction steps

Run `$ docker pull louislam/uptime-kuma:1.23.16` on your system.

### 👀 Expected behavior

As with the previous releases (e.g., v1.23.15), the latest stable release should also be available on Docker Hub.

### 😓 Actual Behavior

```
Error response from daemon: manifest for louislam/uptime-kuma:1.23.16 not found: manifest unknown: manifest unknown
```

### 🐻 Uptime-Kuma Version

1.23.16

### 💻 Operating System and Arch

Debian 12

### 🌐 Browser

Safari 18.1.1

### 🖥️ Deployment Environment

- Runtime: Docker 27.4.0
- Database: sqlite
- Filesystem used to store the database on: Ext4
- number of monitors: None (yet)

**Comment by flammable** [comment]
Likely related to the move to GHCR, but it's also missing from there.

**Comment by louislam** [comment]
Thanks for the report, I just push again, it is available now.

It kind of surprised me that the `docker buildx build ..... --push` command does not throw an error if the push fails.

**Comment by maxkratz** [comment]
> Thanks for the report, I just push again, it is available now.
> 
> It kind of surprised me that the `docker buildx build ..... --push` command does not throw an error if the push fails.

Thank you for your fast response and the fix. I can pull the image now.

**Comment by webysther** [comment]
I got the same error again, the tag got missed again?

**Comment by maxkratz** [comment]
> I got the same error again, the tag got missed again?

As far as I can see, the tag is still there (https://hub.docker.com/layers/louislam/uptime-kuma/1.23.16/images/sha256-b4c3a4d186b4612b3a7bbb39c56a634626276615c21871c837a86e4a43d8e047) and pulling the image also works on my machine.

**Comment by webysther** [comment]
> > I got the same error again, the tag got missed again?
> 
> As far as I can see, the tag is still there (https://hub.docker.com/layers/louislam/uptime-kuma/1.23.16/images/sha256-b4c3a4d186b4612b3a7bbb39c56a634626276615c21871c837a86e4a43d8e047) and pulling the image also works on my machine.

On GHCR.

**Comment by maxkratz** [comment]
> On ghcr.io in my case hehe.

Ah, now I got it. Yep, on ghcr.io, I also cannot see the tag.

**Comment by louislam** [comment]
v1 is not available on ghcr.io.
