### ISSUE TITLE
Support external interface call operation

### ISSUE THREAD

**Issue by songzhibin97** [louislam/uptime-kuma#5470]
### 📑 I have found these related issues/pull requests

- 

### 🏷️ Feature Request Type

API / automation options

### 🔖 Feature description

It is possible to treat uptime-kuma purely as a service, with functional operations providing api for other services to use

### ✔️ Solution

You can select uptime-kume for integration in other integrations to provide monitoring content and corresponding notifications, which will give you more options

### ❓ Alternatives
https://github.com/lucasheld/uptime-kuma-api
https://github.com/MedAziz11/Uptime-Kuma-Web-API

**Comment by CommanderStorm** [comment]
implementing a stable, externally facing http API instead of the internal socket.io API is tracked here:
- #118

Closing as a duplicate
