### ISSUE TITLE
How can I create a regular user account that can only be used to browse the Uptime Kuma pages?

### ISSUE THREAD

**Issue by gesiwami** [louislam/uptime-kuma#5473]
### ⚠️ Please verify that this question has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

How can I create a regular user account that can only be used to browse the Uptime Kuma pages.

### 📝 Error Message(s) or Log

no

### 🐻 Uptime-Kuma Version

1.23.15

### 💻 Operating System and Arch

win10

### 🌐 Browser

google chrome131.0.6778.205

### 🖥️ Deployment Environment

- Runtime: 
- Database: 
- Filesystem used to store the database on: 
- number of monitors: 
no

**Comment by cyril59310** [comment]
For now, Uptime Kuma does not support the creation of user accounts. In future versions, it is planned to allow the creation of additional accounts, but only administrators https://github.com/louislam/uptime-kuma/pull/3571s.
