### ISSUE TITLE
Using nginx reverse proxy in intranet environment, DingDing can't send notification messages

### ISSUE THREAD

**Issue by sifanx** [louislam/uptime-kuma#5475]
### ⚠️ Please verify that this question has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

My server environment is an intranet environment, the server can not communicate with the Internet.

I built a nginx reverse proxy on the extranet server, this nginx server is able to access the Internet.
Through the network gate device to convert this extranet server IP to intranet IP, and then build Uptime Kuma in the intranet server through docker.
Intranet DNS Configure the domain name of the dingding robot, oapi.dingtalk.com, to be the intranet IP of the nginx server and then use the `curl -X POST` command to access https://oapi.dingtalk.com in the container.
This will prompt `SSL certificate problem: unable to get local issuer certificate`, if you add the `-k` parameter, `curl -k -X` can access https://oapi.dingtalk.com normally and send out the message.
If you configure DingDingi information in `/settings/notifications` and click the test button, it will prompt `Error: certificate has expired`, how to skip SSL authentication in Uptime Kuma system?

### 📝 Error Message(s) or Log

```
Error: Error: Error: certificate has expired 
    at DingDing.throwGeneralAxiosError (/app/server/notification-providers/notification-provider.js:38:15)
    at DingDing.send (/app/server/notification-providers/dingding.js:36:18)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Socket.<anonymous> (/app/server/server.js:1304:27)
```

### 🐻 Uptime-Kuma Version

v1.23.16

### 💻 Operating System and Arch

AlmaLinux 8.9

### 🌐 Browser

Google Chrome 131.0.6778.205

### 🖥️ Deployment Environment

- Runtime: Docker 26.1.0
- Database: sqlite

**Comment by CommanderStorm** [comment]
> certificate has expired

What you are currently trying to do is not posssibe and honestly that is quite outside the scope. Please make sure that your certificates have not expired.

I am going to close this as wontfix because adjusting a specific notification provider like DingDingi as requested is not something I see as generally usefull.
