### ISSUE TITLE
Translation error for '%d ago' and 'now' texts

### ISSUE THREAD

**Issue by hasanbahadirkoca** [louislam/uptime-kuma#5480]
### 📑 I have found these related issues/pull requests

As seen in the picture, '%m ago' and 'now' are not converted to Turkish. The first one is already in the language file and has not been converted. The second one is not in the language file at all.

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 👟 Reproduction steps

On dashboard and status pages

### 👀 Expected behavior

It should have been '%d önce' and 'şu an'

### 😓 Actual Behavior

Translation error

### 🐻 Uptime-Kuma Version

0.12.4

### 💻 Operating System and Arch

Home Assistant

### 🌐 Browser

Safari

### 🖥️ Deployment Environment

Home Assistant Addon

**Comment by louislam** [comment]
Translation please refer to this: https://github.com/louislam/uptime-kuma/blob/master/src/lang/README.md
