### ISSUE TITLE
Support for collections

### ISSUE THREAD

**Issue by ichilver** [louislam/uptime-kuma#549]
To add support for a collection of things so its one item on the status page.

For example.

Currently If I was monitoring 10 websites, I could create a group on the status page and it shows all ten in the group. The page gets busy fast and needs scrolling.

However it would be nice on the status page to show a single line based on a collection of things and to click on the collection to drill into what would effectively be a group.

Or maybe to have the groups collapsible and show the net result of everything under it.

**Comment by Mellowor** [comment]
Hi @louislam, I would like to work on this one.

**Comment by deefdragon** [comment]
> Hi @louislam, I would like to work on this one,could you assign it to me?

I don't think the project is at the point of assigning people to tasks. Feel free to just take it up and make a PR (don't forget to read the contributing docs.).

**Comment by ichilver** [comment]
It's half completed in the respect you can group items.

However the other half was to have the groups collapsible so on a status page you would see the groups collapsed.  The group would show the status graph which is a result of the items inside the group.  The group could then be clicked on to expand the items in the group to see all the items.

**Comment by CommanderStorm** [comment]
> However the other half was to have the groups collapsible so on a "status page" you would see the groups collapsed

For future reference:
This is tracked in
- https://github.com/louislam/uptime-kuma/issues/468
