### ISSUE TITLE
Bulk operation, links on quick stats, Quick Stats on status page

### ISSUE THREAD

**Issue by Neer171** [louislam/uptime-kuma#561]
**Is it a duplicate question?**
No

**Is your feature request related to a problem? Please describe.**
New feature which will be super useful
- Bulk operation (e.g. bulk edit/delete/pause)
- Domains links on quick stats or sorting option to see up and down domains on one place
- Quick Stats on status page

**Comment by CommanderStorm** [comment]
- bulk actions is tracked here: #2934
- sorting is tracked here: #1585
- quick stats on status page is tracked here: #312

=> I think this issue can be closed.
@Neer171 do you agree? (otherwise please elaborate)

PS: Please open one issue per feature to improve the issue-manageability 😅

**Comment by magnusviri** [comment]
I would love this feature as well. I was using the backup feature by modifying the backup and then restoring the modification, but with a lot of monitors, I haven't been able to get it to "restore".

**Comment by CommanderStorm** [comment]
> but with a lot of monitors, I haven't been able to get it to "restore".

Define a lot of monitors.
uptime-kuma currently does not work for more than 100..400 monitors (first limit being if run on embedded hardware with slow disks, second being related to https://github.com/louislam/uptime-kuma/pull/3515, https://github.com/louislam/uptime-kuma/pull/3380 and other performance problems)
=> should be better/fixed in `1.23`

**Comment by jaxjexjox** [comment]
Can we please consider just 1x Bulk operations entry?

I see one here:
https://github.com/louislam/uptime-kuma/issues/455 
here:
https://github.com/louislam/uptime-kuma/issues/2934
and of course this thread we're looking at here:
https://github.com/louislam/uptime-kuma/issues/561

As stated in other threads, I will paypal $30 USD for this feature as it would be extremely handy.
(yes, up $10 US from my other post, this is killing me at the moment and this little tool is so wonderful)

Thanks for the hard work!
