### ISSUE TITLE
Manually Set DNS server for http(s) checks?

### ISSUE THREAD

**Issue by revilo951** [louislam/uptime-kuma#562]
**Info**
Uptime Kuma Version: 1.7.3
Using Docker?: Yes
Docker Version: 20.10.8, build 3967b7d
OS: Ubuntu Server 21.04
Browser: Chrome

Is it possible to manually set the DNS server used for a particular check, or for the whole container? From my docker logs, it seems like a check is using 1.1.1.1 - and this means that can't check on internal services behind a reverse proxy.

Am I missing a config location, or is 1.1.1.1 hard-coded in for those checks?

**Comment by louislam** [comment]
Not hardcoded, it uses system's dns server.

You can override by using Docker's dns settings:
https://docs.docker.com/config/containers/container-networking/#dns-services

**Comment by revilo951** [comment]
That's sorted it, thanks!
