### ISSUE TITLE
Possibility to copy a monitor

### ISSUE THREAD

**Issue by adumont** [louislam/uptime-kuma#565]
**Describe the solution you'd like**
Be able to open a Monitor in dashboard, and have a boton Copy in the same row as the Edit and Delete buttons. It would copy the whole configuracion, and maybe rename it adding a " - Copy" suffix

**Comment by dginhoux** [comment]
Hi, 

Yes, this will very usefull when we have lot of monitors to create

**Comment by taimaiduc** [comment]
Up This will very useful in case we have a lot if config
