### ISSUE TITLE
The unit of time doesn't change if response time is high

### ISSUE THREAD

**Issue by SagnikSRHUSE** [louislam/uptime-kuma#571]
**Describe the bug**
The time unit stays in ms, as a result, when the latency of something is more than a second, it shows 1.52ms instead of 1.52s.

**To Reproduce**
I'm not sure if this can be easily replicated, I added a Google monitor to the demo.

**Expected behavior**
Either it shold be 1520ms or 1.52s.

**Info**
I tried it in the demo.

**Screenshots**
![image](https://user-images.githubusercontent.com/16162562/136136136-b1ef0b37-f4b3-43a1-b79d-3128a91daec8.png)
![image](https://user-images.githubusercontent.com/16162562/136136172-14a062a5-922c-46c5-ba71-b8d19fd8dc44.png)

**Comment by louislam** [comment]
It is not a dot.

`1,552 ms`
`1,019 ms`
