### ISSUE TITLE
Stuck in setup

### ISSUE THREAD

**Issue by Kevin-Konradi** [louislam/uptime-kuma#58]
So i installed uptime-kuma on my server and started it. When i did so, it showed me in the console "No user, need setup" so i went  to /setup on the website. I entered my credentials for the admin user and clicked on create. Now i am stuck on this screen, the create button is pale and i can't click it and nothing is happening

**Comment by hkpanchani** [comment]
I got stuch here too.. @Kevin-Konradi  how did you able to solve this error

**Comment by Kevin-Konradi** [comment]
I didn't

**Comment by fedenelli** [comment]
@hkpanchani @Kevin-Konradi Are you guys using caprover to deploy?
Basically, I solved it allowing the use of websockets on my app. If you are using nginx as your webserver, you should add this to your `location /` config:

`proxy_set_header Upgrade $http_upgrade;
proxy_set_header Connection "upgrade";
proxy_http_version 1.1;`

Hope it helps.

**Comment by dreadedhamish** [comment]
> @hkpanchani @Kevin-Konradi Are you guys using caprover to deploy? Basically, I solved it allowing the use of websockets on my app. If you are using nginx as your webserver, you should add this to your `location / {}` config:
> 
> ```
> proxy_set_header Upgrade $http_upgrade;
> proxy_set_header Connection "upgrade";
> proxy_http_version 1.1;
> ```
> 
> Hope it helps.

Are you running fine on Caprover? I'm getting responsetimes that are REALLY slow - 1300ms to the same datacanter, as opposed to 20ms from my home. Tried old versions and new and it's the same. I even added code you provided but no luck. From the VPS shell I get 200ms, from the Uptime Kuma container I get 200ms, but from within the Up[time Kuma panel I get 1300ms.
