### ISSUE TITLE
Ability to set custom email subject

### ISSUE THREAD

**Issue by PopcornPanda** [louislam/uptime-kuma#582]
**Is it a duplicate question?**
No

**Describe the solution you'd like**
It could be handy if we could change email subject to our own. There are some systems that expect specific subject structure to handle the message (like internal tagging in Helpdesk systems).

**Additional context**
The reason of this feature request is ability to use email2sms service which some SMS Gateway provide as alternative to REST API.

**Comment by NixNotCastey** [comment]
I just made a PR for this #627
