### ISSUE TITLE
Turn off healtcheck or change time between health checks

### ISSUE THREAD

**Issue by Unrepentant-Atheist** [louislam/uptime-kuma#583]
The build in healthcheks are spamming Portainer every couple seconds with

<html><body>

2021-10-06 23:55:43 | container | Unsupported event
-- | -- | --
2021-10-06 23:55:43 | container | Exec instance started
2021-10-06 23:55:43 | container | Exec instance created

</body>
</html>

There needs to be a command for docker run / docker-compose to either turn off the health checks or change times between each one.

**Comment by chakflying** [comment]
Closing as the upstream bug has been fixed.
