### ISSUE TITLE
Mastodon Notifications

### ISSUE THREAD

**Issue by MayhemBill** [louislam/uptime-kuma#587]
**Is it a duplicate question?**
Please search in Issues without filters: https://github.com/louislam/uptime-kuma/issues?q=
It is not a duplicate
**Is your feature request related to a problem? Please describe.**
I would like to be able to post on a bot account when something goes down/comes back up

**Comment by bt90** [comment]
Apprise added Mastodon support. It should be enough to use version v1.20.

**Comment by bt90** [comment]
The documentation for those who want to test it:

https://github.com/caronc/apprise/wiki/Notify_mastodon

**Comment by CommanderStorm** [comment]
@MayhemBill this issue seems solved, could you close it or comment if enhancements need to be made?

**Comment by thibaultmol** [comment]
> @MayhemBill this issue seems solved, could you close it or comment if enhancements need to be made?

why would it be closed though? it's not a native integration yet like every other option on Kuma

**Comment by MayhemBill** [comment]
Might not be native, but it works for me, as long apprise continues to support mastodon, it should be fine.
