### ISSUE TITLE
Cant start docker image 

### ISSUE THREAD

**Issue by simonhauck** [louislam/uptime-kuma#59]
Hello,

i tried to run your project as docker container with the following command `` docker run  -p 3001:3001 louislam/uptime-kuma`` on an ``x86_64 Ubuntu 20`` server. Unfortunately i can't get it up and running. The following error occurs and the service cant be reached at all:

````
Connect to Database

Load JWT secret from database.

(node:20) UnhandledPromiseRejectionWarning: Error: SELECT COUNT(*) FROM `user`  limit 1 - SQLITE_CORRUPT: database disk image is malformed

(Use `node --trace-warnings ...` to show where the warning was created)

(node:20) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)

(node:20) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
````

This error occurs for the latest version as well as version 1. Does anybody else have this issue and can it reproduce it?

**Comment by NiNiyas** [comment]
Same as #51 .

**Comment by louislam** [comment]
I am still investigating what possible can causes the sqlite db corrupted. I suspected that I did not implemented graceful shutdown for the current release, but still not sure.

I may try to use another volume, see if the error still occur.

**Comment by simonhauck** [comment]
After deleting the ``kuma.db`` file it worked and started successfully, thanks 👍 ! 
I retested it multiple times, the error occurs, at least for me, after every fresh installation. So just using creating a new container with a new volume is not enough :)

**Comment by louislam** [comment]
added graceful shutdown in 1.0.5, hopefully fixed this problem.

**Comment by simonhauck** [comment]
Tested it on my system and works like a charm 👍  Thanks!
