### ISSUE TITLE
API to create incidents from 3rd party tools

### ISSUE THREAD

**Issue by grimkroton** [louislam/uptime-kuma#591]
**Is it a duplicate question?**
No, did not find any.

**Is your feature request related to a problem? Please describe.**
I already tried to use https://cachethq.io/ but I struggled adding outages or incidents from a monitoring system like Nagios, Altermanager etc. due a missing API.

**Describe the solution you'd like**
If there is a easy to use API, I could create outages/incidents from anywhere. From another monitoring tool or my change management tool.

**Describe alternatives you've considered**
Use another tool

**Additional context**
It might look odd, but a integration in other tools through a API would be a great benefit.

**Comment by louislam** [comment]
Duplicate of #118
