### ISSUE TITLE
Deleted monitors still show in /metrics

### ISSUE THREAD

**Issue by hippsabq** [louislam/uptime-kuma#598]
**Is it a duplicate question?**
I looked and did not find anything

**Describe the bug**
If you remove a monitor from the dashboard, the monitor and its last status still show up in the metrics page. This also occurs if you modify the monitor_url. Changing the monitor url also creates a redundant line in the metrics output.

I am scraping these into Prometheus and using the Grafana Dashboard, but all deleted or modified monitors will show up and remain in my dashboard.

**To Reproduce**
the example I use in the screenshot is Plex. 

1. I first setup a Plex monitor to look at the "ipaddress:port" of my plex server
2. The monitor came back down since the plex web ui is under "ipaddress:port/web/"
3. I modified the Plex monitor to include the "/web" ending
4. Navigated to /metrics of my uptime-kuma server
5. Noticed that a duplicate "Plex" monitor was created and the first incorrect one was still there showing down
6. Deleted the "Plex" monitor altogether
7. Navigated to /metrics of my uptime-kuma server
8. Noticed that both "Plex" monitors were still output to the /metrics

**Expected behavior**
1. Modifications to a monitor do not create a duplicate /metrics output
2. Deleted monitors no longer show up in /metrics output

**Info**
Uptime Kuma Version: 1.7.3
Using Docker?: Yes
Docker Version: 20.10.9
Node.js Version (Without Docker only):
OS: Win 10
Browser: Brave

**Screenshots**
![image](https://user-images.githubusercontent.com/61252419/136444334-ee6d0002-2a16-4452-9583-530a989354ac.png)
![image](https://user-images.githubusercontent.com/61252419/136444726-46d14372-9f0b-4ccc-ac23-04769aede682.png)

**Error Log**

**Comment by deefdragon** [comment]
This appears to also happen if you change the name of the monitor.

**Comment by RisedSky** [comment]
> This appears to also happen if you change the name of the monitor.

Seems like the URL is changed, maybe it duplicates because of it ?

**Comment by louislam** [comment]
https://github.com/louislam/uptime-kuma/blob/master/server/prometheus.js

It seems that there is no "remove logic" in the current implement. May need to remove the monitor from all gauges if the monitor is stopped.

**Comment by x4FF3** [comment]
as i am not familiar with JS, is this going to be fixed anytime soon?

**Comment by gruessung** [comment]
+1

**Comment by Coliinnn** [comment]
Also experiencing this issue.

**Comment by chakflying** [comment]
Took a shot at it in #1136, please check.

**Comment by Proxymiity** [comment]
A quick and easy hack is to restart the container. Restarting seems to have cleared every duplicated monitor.
It's as easy as `docker-compose restart` or `docker restart uptime-kuma` :)

**Comment by kyuuk** [comment]
Little workaround:
To clean monitors that have been deleted/renamed i discovered that you need to clear all statistics from database in the settings, like this 
![image](https://user-images.githubusercontent.com/16566073/154796945-173d039a-8615-45df-9de2-c66a83e66d3e.png)

**Comment by nmcc1212** [comment]
Still an issue, and clearing all statistics didn't work

**Comment by louislam** [comment]
https://github.com/louislam/uptime-kuma/pull/1136

May need someone test this pr, as I dont using Prometheus.

**Comment by nmcc1212** [comment]
i am testing it with now, but you don't need prometheus to see if it works, just change/delete an endpoint and check `uptime-kuma:3001/metrics` and see if the value still exists/ has changed

**Comment by nmcc1212** [comment]
just tested it with prometheus, it works well nd is pretty much instant (less than 1 second delay between edit/release and updating prometheus
