### ISSUE TITLE
Accessing HTTP(s) Keyword with Basic Auth

### ISSUE THREAD

**Issue by theShameTrain** [louislam/uptime-kuma#599]
**Is it a duplicate question?**
No, didn't find anything similar

Attempting to access a URL using basic auth in the URL
https://user:password@HOSTNAME

It appears that the page is not loading.  This works in the browser.  Is it even possible to access a URL using basic auth in the URL or is there a different way to format the URL?

**Info**
Uptime Kuma Version: 1.7.3
Using Docker?: Yes
Docker Version:  20.10.7
Node.js Version (Without Docker only):
OS: Ubuntu 21.04
Browser: Chrome / Brave

**Comment by Abdulvoris-Urolov** [comment]
Basic Auth is not supported.

**Comment by CommanderStorm** [comment]
@Abdulvoris-Urolov 
#864 should include basic auth.
Could you open a help issue with the context what worked, what did not instead of necroposting on this issue?
