### ISSUE TITLE
Add Microsoft Teams alerting

### ISSUE THREAD

**Issue by djbr22** [louislam/uptime-kuma#60]
Please add the ability to use Microsoft Teams for alerts. I would like to deploy this at work, where our alerts to go a certain channel with multiple members. I've generated an Incoming Webook in Teams and pasted the URL into the "Webhook" field in Uptime Kuma, but it doesn't alert.

**Comment by louislam** [comment]
will be supported via apprise

**Comment by louislam** [comment]
added apprise in 1.0.6
