### ISSUE TITLE
[webhook] Allow ignoring certificates

### ISSUE THREAD

**Issue by BloodBlight** [louislam/uptime-kuma#602]
**Is it a duplicate question?**
Not that I can find.

**Is your feature request related to a problem? Please describe.**
Yes.
I am unable to (at least without getting into the console) send webhook notifications to services with self signed certificates (see second screenshot).

**Describe the solution you'd like**
Add the same "Ignore TLS/SSL error for HTTPS websites" option for webhook notifications.

**Describe alternatives you've considered**
I could get a proper cert, but I haven't had much luck getting it to work with non-standard ports.

**Additional context**
In a use case were someone has self signed certs of systems to monitor, it can also be assumed that any in house alerting/response systems they have might have might also be self signed (as in my case).

Add this:
https://imgur.com/a/FOvnCqg

To here:
https://imgur.com/a/j3M0e0o

**Comment by chris-si** [comment]
For a docker installation a walkaround is to add the environment variable `NODE_EXTRA_CA_CERTS=./certs/ca.crt` and mount the ca certificate to `/app/certs/ca.crt`

**Comment by Tobix99** [comment]
If you are running uptime-kuma in a Docker, you can add ```- NODE_TLS_REJECT_UNAUTHORIZED=0``` to the environment vars. But be careful, this will **disable** the SSL checking for the **entire** container.

**Comment by BloodBlight** [comment]
This doesn't seem to work unfortunately.

**Comment by Tobix99** [comment]
Can you share your complete curl command please? You can redact the Hostname/IP if you want. But the Environment disables the TLS-Check for the whole Node environment in the Docker-Container.

And a 404 HTTP Status Code indicates "Not Found", so maybe the Endpoint doesn't support "Post"?

**Comment by BloodBlight** [comment]
That was my assumption as well, that's why I ran the test with curl, as something seemed odd as ANY request to the URL is accepted right now.  So a copied and pasted URL returning a 404 seemed... Off.  :)

Here is the test from inside the docker:
```
root@c3794cc7fe6b:/app# curl https://192.168.xxx.xxx:1880/WebHook
curl: (60) SSL certificate problem: self signed certificate
More details here: https://curl.haxx.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.
root@c3794cc7fe6b:/app# curl --insecure https://192.168.xxx.xxx:1880/WebHook
{}root@c3794cc7fe6b:/app# 
```
Note that the second request returns "{}" and does trigger the web hook.

Docker YAML:
```
services:
  KumaMonitoring:
    image: louislam/uptime-kuma
    container_name: KumaMonitoring
    volumes:
      - /DockerVolumes/KumaMonitoring:/app/data
    ports:
      - 3001:3001
    environment:
      - NODE_TLS_REJECT_UNAUTHORIZED=0
    restart: unless-stopped
```

docker inspect KumaMonitoring  | grep TLS
```
                "NODE_TLS_REJECT_UNAUTHORIZED=0",
```

**Comment by Tobix99** [comment]
Curl without ```-X POST``` and the POST-Data is indeed a ```GET```request, which is not supported by Uptime-Kuma. Assuming you are running NodeRed (because of the 1880 Port) you just have to change in the Node from ```GET```to ```POST``` as seen in the Attachment.

A valid Curl Post Request is: ```curl -X POST -H "Content-Type: application/json" -d '{"key1":"value1", "key2":"value2"}' https://192.168.xxx.xxx:1880/WebHook```

![image](https://user-images.githubusercontent.com/22603015/183345848-6bf74fa6-4d8a-49ec-a75a-738c2afa0a9c.png)

**Comment by BloodBlight** [comment]
You are 100% correct!  That worked.  Thank you. :)

**Comment by CommanderStorm** [comment]
@BloodBlight given that it worked, is this issue resolved? (if yes, could you close it?) ^^

**Comment by CommanderStorm** [comment]
Closing as https://github.com/louislam/uptime-kuma/labels/wontfix.

Doing so (ignoring certs for notifications) could mean that an attacker intercepts these notifiations as they are no longer encrypted as [MITM attacks](https://en.wikipedia.org/wiki/Man-in-the-middle_attack) are possible in this case.

Users seeking this should either
- register the CA for the self-signed cert used by the `$Notificationprovider` server you host with uptime-kuma
- or provide said `$Notificationprovider` server with a valid cert (letsencrypt/...)

Notifications are very different from monitors, where this is handy.
For notifications, you don't want them going to a potentially different server.
