### ISSUE TITLE
Why heartbeat interval minimum is 20 seconds?

### ISSUE THREAD

**Issue by myesn** [louislam/uptime-kuma#606]
**Describe your problem**
Why heartbeat interval minimum is 20 seconds?

**Info**
Uptime Kuma Version: latest
Using Docker: Yes
Docker Version: 20.04
Browser: Chrome 95.0.4638.40 beta x64

**Comment by louislam** [comment]
According to my experiment, if it is too low, it could timeout unexpected and the cpu usage will be higher.

**Comment by tx-fz** [comment]
Would even 10 seconds be too low?

**Comment by gp-Airee** [comment]
Could we reopen this issue @louislam?

**Comment by vot** [comment]
@louislam +1 on reopening this issue.

Could we possibly allow lower values (as low as 5 seconds maybe) and display a warning that using low values for interval may cause instability?

Perhaps all that's needed is more testing to determine what the safe values are and perhaps some debouncing logic to ensure the previous attempt has finished before issuing the next request.
