### ISSUE TITLE
Give a 👍 to the enhancements that you love

### ISSUE THREAD

**Issue by louislam** [louislam/uptime-kuma#613]
There are a lot of good enhancements here, but unfortunately my free time is limited. 

I would choose the next task based on: 
- The complexity of the enhancement
- [Sort by 👍](https://github.com/louislam/uptime-kuma/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc+label%3Afeature-request)

If you are the op, don't forget to 👍 too.

**Comment by gaby** [comment]
I would suggest to start closing stale issues, or issues with questions not related to Uptime-Kuma. It seems in the last 2 weeks that has increased a lot.

**Comment by Saibamen** [comment]
> questions not related to Uptime-Kuma

Any examples?

**Comment by MayhemBill** [comment]
I would also like to know how my request is considered unrelated?

**Comment by kry008** [comment]
#779

**Comment by simphide** [comment]
Please change the link in the main post of this issue from "https://github.com/louislam/uptime-kuma/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc+label%3Aenhancement" to "https://github.com/louislam/uptime-kuma/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc+label%3Afeature-request".
