### ISSUE TITLE
Hacktoberfest

### ISSUE THREAD

**Issue by TUsToLET** [louislam/uptime-kuma#617]
Uptime Kuma is an awesome project and should participate at the Hacktoberfest. 
PR will get a Hacktoberfest label and you can get some goodies for PRs.
More infos can be found here https://hacktoberfest.digitalocean.com/

**Comment by louislam** [comment]
Lol, then let it go. I like to do what I like to do.

**Comment by gaby** [comment]
> Lol, then let it go. I like to do what I like to do.

??? I'm just quoting what the `Hacktoberfest` FAQ says.

**Comment by chakflying** [comment]
FYI I remember previously this event made a mess in Github, as people with little knowledge of open source spammed projects with useless PRs. Looks like this year they improved the guidelines, but I'm still skeptical.

**Comment by louislam** [comment]
> > Lol, then let it go. I like to do what I like to do.
> 
> ??? I'm just quoting what the `Hacktoberfest` FAQ says.

Yes, I understand. I am just not so interested with it after read the rule.

But for anyone care about this, feel free to ask to add the "hacktoberfest-accepted" label for you.
