### ISSUE TITLE
Reverse monitoring for discord bots

### ISSUE THREAD

**Issue by wolflu05** [louislam/uptime-kuma#624]
**Is it a duplicate question?**
No (only very far away from that request (reverse monitoring))

**Describe the solution you'd like**
Add an API route to Kuma to push status messages (reverse mode). This can be used to monitor not HTTP(s) working devices like discord bots or any other chatbots.

**Comment by mindlesstux** [comment]
I think what you are seeking is in the 1.8.0 release that just got pushed out.
