### ISSUE TITLE
SSL certs

### ISSUE THREAD

**Issue by markdesilva** [louislam/uptime-kuma#626]
Any chance to allow using ssl certs like let’s encrypt for this?

**Comment by deefdragon** [comment]
The normal method of deploying kuma is behind a reverse proxy, most of which have integration with certbot etc. for ssl cert updating and whatnot. 

Kuma itself appears to have code in place to use an ssl key if the file locations are passed in via the SSL_KEY and SSL_CERT environment variables, tho its undocumented, so I have no idea how well tested that methodology is.

**Comment by markdesilva** [comment]
> The normal method of deploying kuma is behind a reverse proxy, most of which have integration with certbot etc. for ssl cert updating and whatnot.
> 
> Kuma itself appears to have code in place to use an ssl key if the file locations are passed in via the SSL_KEY and SSL_CERT environment variables, tho its undocumented, so I have no idea how well tested that methodology is.

Thank you! I’ll give that SSL_KEY and SSL_CERT a try!

**Comment by louislam** [comment]
Configuring ssl cert through a reverse proxy is better. 

I believe you have to restart Uptime Kuma in order to renew the cert if you are using those env vars.

**Comment by markdesilva** [comment]
Thanks Louis!

We don't mind a quick controlled restart in the dead of the night, so long as past data is still accessible when the service restarts which I believe UK will do.
 
> Configuring ssl cert through a reverse proxy is better.
> 
> I believe you have to restart Uptime Kuma in order to renew the cert if you are using those env vars.
