### ISSUE TITLE
One-liners in php/shell or regex for HTTP(s)-keyword

### ISSUE THREAD

**Issue by markdesilva** [louislam/uptime-kuma#631]
Could HTTP(S)-Keyword be made to allow the keywords to be generated via a shell/php script or regex? This would allow a dynamic check of the keywords (which I assume will be checked in the html code and not just the displayed page) so that slightly more diligent defacement hackers would guess a keyword and use it in their defacement code.

I realize that someone with sufficient time can scan through the original html code and find the keyword if its in some format but creative content creators can dynamically create a keyword and hide it over multiple lines in the html code and extract the keyword though a script of their own making. Hence why allowing keyword via a script would be great and significantly better than using single line or regex but for full flexibility, all those methods should also be allowed.

Thank you.

**Comment by louislam** [comment]
Implementing in the pull request #518

**Comment by chakflying** [comment]
In broader terms, I don't understand why you would be monitoring a page with 3rd party content anyway. If it's a service that you control, having a dedicated `/healthcheck` endpoint or at least a page with static content would be much more reliable.

**Comment by markdesilva** [comment]
Heath checks and server status endpoints wouldn't allow the page content to be monitored, but that keyword in the site itself would and making it dynamic would make it more robust. In cases of defacement, the healthcheck/serverstatus endpoints would still report everything as ok, even if the content was maliciously changed. 

That's how I see it anyway, but I might be wrong as I do not have as much experience as everyone else here.

Thank you, cheers!

**Comment by markdesilva** [comment]
> Implementing in the pull request #518

Hi Louis, thank you!

**Comment by geekscrapy** [comment]
+1

**Comment by CommanderStorm** [comment]
@markdesilva I would suggest we close this issue.

Rationale:
- REGEX is tracked more clearly in https://github.com/louislam/uptime-kuma/issues/2735
- EXEC is tracked in https://github.com/louislam/uptime-kuma/issues/1117

**Comment by markdesilva** [comment]
Done! 

Thanks. 

> @markdesilva I would suggest we close this issue.
> 
> 
> 
> Rationale:
> 
> - REGEX is tracked more clearly in https://github.com/louislam/uptime-kuma/issues/2735
> 
> - EXEC is tracked in https://github.com/louislam/uptime-kuma/issues/1117
> 
> 
> 
> If you agree, could you please close this Issue, as duplicates only create immortal zombies and are really hard to issue-manage. ^^
