### ISSUE TITLE
[Feature Req.] Add markdown on incident + description of Uptime Kuma

### ISSUE THREAD

**Issue by RisedSky** [louislam/uptime-kuma#635]
**Is it a duplicate question?**
Found in a reply in the list of tasks to add, but seems to be ignored

**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Add markdown to the incident + description (here :)
![image](https://user-images.githubusercontent.com/23197999/136704775-fca87a4d-6bf6-44c3-8fee-25e8a66d032b.png)

**Comment by MagicLike** [comment]
Any updates on this?

**Comment by 401U** [comment]
This should be resolved by #2570
