### ISSUE TITLE
[Feature Req.] Status Page - Add sub-groups

### ISSUE THREAD

**Issue by RisedSky** [louislam/uptime-kuma#639]
**Is it a duplicate question?**
~~No~~
**Edit**:  Yes, see
- https://github.com/louislam/uptime-kuma/issues/468

**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Can you add sub-groups, it will help having "dedicated groups"

Like this : 
![Sans titre-1](https://user-images.githubusercontent.com/23197999/136706521-93d914fd-27e4-47e1-98c4-1143943666dd.png)

The "Maybe ?" is for the percentage of uptime, if we group all in the "docker" section, or per probe (vpn, nextcloud, ftp etc..)

**Comment by deefdragon** [comment]
Similar to #549, tho in this case, it specifically includes the addition of having a summarized-uptime/status which I think is a good feature.

**Comment by raphaelbernhart** [comment]
+1

**Comment by CommanderStorm** [comment]
@RisedSky 
https://github.com/louislam/uptime-kuma/pull/2693 has beeen merged and is avaliable in 1.22.
I think this issue is resoved. Could you give feedback if something is missing or close this issue?
