### ISSUE TITLE
Certificate Info err

### ISSUE THREAD

**Issue by phanlong95** [louislam/uptime-kuma#645]
![image](https://user-images.githubusercontent.com/32808933/136731300-b29a6fb7-02b5-4034-b24c-ca805049d520.png)

**Comment by phanlong95** [comment]
view in ver 1.7.3 
![image](https://user-images.githubusercontent.com/32808933/136731395-d1357ef2-3e66-4b6a-9748-40ecab0d2440.png)

**Comment by phanlong95** [comment]
i'm checkout branch master or 1.8.0 
view still null

**Comment by louislam** [comment]
I changed a bit in 1.8.0, you no longer to build the frontend. Instead:

`npm run download-dist`, which download the `dist.tar.gz` files from Github. You can also find this in the release page.

**Comment by phanlong95** [comment]
> I changed a bit in 1.8.0, you no longer need to build the frontend. Instead:
> 
> `npm run download-dist`, which download the `dist.tar.gz` files from Github. You can also find this in the release page.

i worked. thank you
