### ISSUE TITLE
[Feature Request] Provide incidents via API

### ISSUE THREAD

**Issue by hypervtechnics** [louislam/uptime-kuma#653]
**Is your feature request related to a problem? Please describe.**
I am using Homer as a landing page. To keep things dry I'd like Uptime-Kuma to also serve the active incident to the Homer site. The integration on the homer site is possible: https://github.com/bastienwirtz/homer/blob/main/docs/tips-and-tricks.md#get-the-news-headlines-in-homer . But Uptime-Kuma does not expose the required information as a REST API so that Homer can fetch that information.

**Describe the solution you'd like**
Provide a REST API endpoint which provides the active incident if there is one.

**Describe alternatives you've considered**
None so far. Currently I'll just copy and paste the message.

**Comment by meichthys** [comment]
> Maybe you can check if `/metrics` can give the information you request ?

Is 'metrics' a part of the undocumented api that we should not rely on? Or is this officially for public consumption?

**Comment by deefdragon** [comment]
@meichthys /metrics outputs standard prometheus-compatable metrics for consumption. 
see https://github.com/louislam/uptime-kuma/wiki/Prometheus-Integration
