### ISSUE TITLE
Bring Degraded services to top

### ISSUE THREAD

**Issue by 12nick12** [louislam/uptime-kuma#654]
This would be awesome to add a setting where the degraded service comes to the top. Not sure how this would work in a group, but maybe bring the whole group to the top then the down check to the top of that group? 

Thanks for the awesome work.

**Comment by amastelek** [comment]
This would be of great practical help.  Was search for precisely that.

**Comment by MichelBaie** [comment]
Why isn't this already done ??
Such a basic feature :(

**Comment by MichelBaie** [comment]
news?

**Comment by jeremyrnelson** [comment]
@12nick12 - it seems like we've got a lot of tickets open referencing the same features, which splits up the responses and keeps this from rising to the top.  Is there anything in this ticket that's not covered in #1585 where there's already a pull request?  If not, can you close this?

**Comment by CommanderStorm** [comment]
Closing in favor of https://github.com/louislam/uptime-kuma/issues/1308 and 
https://github.com/louislam/uptime-kuma/issues/3743 as handlng this in two PRs is likely better => having two issues is also better.

This third issue is not nessesary
=> closing as duplicate
