### ISSUE TITLE
Hey there 2 bugs in your code ;)

### ISSUE THREAD

**Issue by antoinegilles** [louislam/uptime-kuma#663]
Hey,

I just want to warn you of a bug.

FIRST : 
in server/model/monitor.js:161 
=> if (this.getUrl()?.protocol === "https:") 
solution : just delete the '?'

SECOND : 
in server/model/monitor.js:161
=> if (this.getUrl()?.protocol === "https:")
solution : delete the '?'

and the code is OK ! 👍

**Comment by louislam** [comment]
Not a bug, it is one of Node.js 14 features.

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Optional_chaining

You will run into problems if removed this.
