### ISSUE TITLE
Add MQTT monitor type

### ISSUE THREAD

**Issue by matthew-larner** [louislam/uptime-kuma#664]
**Describe the solution you'd like**
It would be great to have a MQTT monitor type. It would listen on a MQTT topic for an online/available message.
This would be perfect for monitoring of smart home systems.

**Additional context**
MQTT LWT docs here: https://www.hivemq.com/blog/mqtt-essentials-part-9-last-will-and-testament/

**Comment by louislam** [comment]
> @louislam I'm happy to get this built if you'd support the pull request?

Welcome! 

Here is a good example of how to implement a notification:

https://github.com/louislam/uptime-kuma/pull/650/files

**Comment by srgvg** [comment]
You **could** monitor the basic service with TCP - just like you could monitor a web server with TCP. 

MQTT is a messagebus, and testing on the application layer would involve sending a message and verifying you receive it back (probably best asynchronously, in a separate process.)

**Comment by mindlesstux** [comment]
Side note, I think to get MQTT _notification_ via apprise there needs to be one more package installed via pip in the docker image.

https://openbase.com/python/apprise/versions - Looking at 0.9.5.1
> MQTT Support added. (#443)
> Note that the MQTT Plugin depends on paho-mqtt having been pre-installed:
> **_pip install paho-mqtt_**
Also reinforced via: https://github.com/caronc/apprise/wiki/Notify_mqtt

Quick testing: Environment is an install without docker.  Sent test notification, looked successful but no message in MQTT.  Found that update for the apprise version and wiki page, did a quick pip3 install paho-mqtt, retested the notification and got the MQTT message.  Tried the same test on the 1.8.0 docker image, looks like it passes but really is a silent failure to me.

**Comment by louislam** [comment]
> Yep, I was referring to a MQTT monitor. A TCP monitor wouldn't work unfortunately. @louislam would you support a pull request if I arranged for this new monitor to be added?
> 
> The way I'd expect this to work would be to listen on a MQTT topic and listen for messages. On non-'online' message, the service can be flagged as down.

It is OK, but I probably need one more reviewer who is familiar MQTT to verify your pull request.

**Comment by Vartkat** [comment]
I've experienced the TCP monitor on my MQTT broker on port 1883 (default mqtt port) and this makes the broker logs report many connection attemps refused.
Not sure but this seems to overload the borker which seems to refuse legit connection.

We have to sort out two things here : 
1- Monitoring the broker health
2- Using the broker to monitor its clients health

Not the same

V.
