### ISSUE TITLE
Question - is it possible to save monitors configuration before update ?

### ISSUE THREAD

**Issue by yuriw** [louislam/uptime-kuma#672]
**Is it a duplicate question?**
Please search in Issues without filters: https://github.com/louislam/uptime-kuma/issues?q=

**Describe your problem**
Instead of re-creating all monitors manually, wonder if it's possible to save and restore all monitors' settings

**Info**
Uptime Kuma Version: 1.7.2
Using Docker?: Yes
Docker Version: Docker version 20.10.8, build 3967b7d
Node.js Version (Without Docker only): n/a
OS: Ubuntu 20.04
Browser: n/a

**Comment by louislam** [comment]
Btw you can go to the volume path, if you see `kuma.db` in their, you can backup the whole directory first
