### ISSUE TITLE
Importing a backup is too slow

### ISSUE THREAD

**Issue by NixNotCastey** [louislam/uptime-kuma#674]
**Is it a duplicate question?**
I didn't find any matching issue.

**Describe the bug**
Currently, importing a medium size backup (a little above 100 monitors) takes ages to do. I waited a few minutes, but nothing new shown up in the dashboard. I ended up splitting the backup to ~30 smaller files, which loaded nearly instantly. 

**To Reproduce**
Import a backup JSON with about 100 monitors.

**Expected behavior**
Simply, better import performance. A progress bar would be a nice addition.
If I recall correctly, monitors are stored in sqlite3 database, why not export backup as SQL statements?
There is any reason to pass all monitors one by one to monitor creation function?

**Info**
Uptime Kuma Version: 1.8.0
Using Docker?: Yes
Docker Version: 20.10.9
Node.js Version (Without Docker only):
OS: CentOS 8.4
Browser: Edge

**Error Log**
Noting was logged.

I know that's not a bug, it's a performance issue, but it's closer to bug than feature request.

**Comment by gaby** [comment]
This is a performance issue with your host, not uptime-kuma.

I have almost 300 monitors and the backup import takes 5-10secs. Running on 2cpu/2gb of ram in Docker + NGINX

**Comment by NixNotCastey** [comment]
I'm running uptime-kuma on kvm with 2x2.2 GHz and 6 GB ram, Docker + Caddy.

**Comment by NixNotCastey** [comment]
I have moved uptime-kuma to a better host and importing works well.
I guess it was a performance issue, like @gaby said.
