### ISSUE TITLE
When importing a backup, the notificationIDList is not saved

### ISSUE THREAD

**Issue by athlonUA** [louislam/uptime-kuma#677]
**Is it a duplicate question?**
I didn't find any matching issue.

**Describe the bug**
Currently, importing a backup doesn't save monitor's notifications list.

**To Reproduce**
Simply, import a backup. Then check monitor's notifications list.

**Expected behavior**
Monitor's notifications list must be set.

**Info**
Uptime Kuma Version: 1.8.0
Using Docker?: Yes
Docker Version: 20.10.9
Node.js Version (Without Docker only):
OS: CentOS 8.4
Browser: Edge

**Screenshots**

**Error Log**
Noting was logged.

**Comment by agarwalbikram** [comment]
Is there any update to fix this bug, This is still present in Version: 1.18.5

**Comment by tyleraharrison** [comment]
Can confirm, still a bug in 1.18.5

**Comment by agarwalbikram** [comment]
> Can confirm, still a bug in 1.18.5

not fixed
