### ISSUE TITLE
Broken manifest.json link

### ISSUE THREAD

**Issue by arch1v1st** [louislam/uptime-kuma#684]
In index.html, on the manifest rel line, the href should have a proceeding backslash.  This allows manifest.json to load regardless of where in the App routing the user is currently at (i.e. when 'Add to HomeScreen' is clicked within a mobile browser)

```
    <link rel="manifest" href="/manifest.json" />
```

I'm still working through some IDE/Github related issues over here.  Tried to submit this as a formal pull request without success, but rather than wait thought to share the fix here for the time being.

**Comment by louislam** [comment]
Please check "public" folder.
