### ISSUE TITLE
add proxy settings

### ISSUE THREAD

**Issue by Madmorgan007** [louislam/uptime-kuma#692]
Hi,

all my systems use a proxy to connect to the internet.

can you tell me how to add my proxy settings so this can work or can you add in an option to add proxy settings.

Thanks

**Comment by shawhall** [comment]
I'm also interested in this.  Setting environment variables for http_proxy inside the docker container did not seem to make a difference.  I verified the container itself has access to the internet via the proxy, but the uptime-kuma application does not seem to use the proxy by default.

**Comment by deefdragon** [comment]
Proxies for monitors is #470
Proxies for notifications is #616
Do either of those cover what you are looking for?

**Comment by louislam** [comment]
Not possible for the whole application, as not all connections could go through http proxy server.

Keep looking on #470 if you just need the http(s) monitor go through a proxy server.
