### ISSUE TITLE
Permissions issue causing a boot loop

### ISSUE THREAD

**Issue by poldim** [louislam/uptime-kuma#694]
**Describe your problem**
When starting uptime-kuma, it fails to change ownership of the data files ([entrypoint.sh](https://github.com/louislam/uptime-kuma/blob/master/extra/entrypoint.sh)).

I run a docker host that writes to volumes accessed over NFS on a NAS.  The docker host has read & write access to the folders mounted within the volumes.  Containers from this docker host can write data on the shared volume, create folders, etc, but cannot change ownership permissions.  This solution works great for many containers and I haven't seen a similar issue to this.    

**Info**
Uptime Kuma Version: **latest**
Using Docker?: **Yes**
Docker Version: **Docker version 20.10.9, build c2ea9bc**
OS: **Ubuntu**

```
==> Performing startup jobs and maintenance tasks
chown: changing ownership of '/app/data': Operation not permitted
==> Performing startup jobs and maintenance tasks
chown: changing ownership of '/app/data': Operation not permitted
==> Performing startup jobs and maintenance tasks
chown: changing ownership of '/app/data': Operation not permitted
==> Performing startup jobs and maintenance tasks
chown: changing ownership of '/app/data': Operation not permitted
==> Performing startup jobs and maintenance tasks
chown: changing ownership of '/app/data': Operation not permitted
==> Performing startup jobs and maintenance tasks
chown: changing ownership of '/app/data': Operation not permitted
==> Performing startup jobs and maintenance tasks
chown: changing ownership of '/app/data': Operation not permitted
```

**Comment by louislam** [comment]
SQlite won't be working on NFS, even though you pass the chown problems.

I also mentioned that in the Readme (https://github.com/louislam/uptime-kuma/wiki/%F0%9F%94%A7-How-to-Install).

Related issue: https://github.com/louislam/uptime-kuma/issues/127

**Comment by poldim** [comment]
> SQlite won't be working on NFS, even though you pass the chown problems.
> 
> I also mentioned that in the Readme (https://github.com/louislam/uptime-kuma/wiki/%F0%9F%94%A7-How-to-Install).
> 
> Related issue: #127

Is there a way to split the location of the configuration so it could be stored remotely on NFS while still using local storage for the database?

**Comment by louislam** [comment]
> > SQlite won't be working on NFS, even though you pass the chown problems.
> > I also mentioned that in the Readme (https://github.com/louislam/uptime-kuma/wiki/%F0%9F%94%A7-How-to-Install).
> > Related issue: #127
> 
> Is there a way to split the location of the configuration so it could be stored remotely on NFS while still using local storage for the database?

Backup approach such as rsync.
