### ISSUE TITLE
Let small changes to the source code take effect in running container

### ISSUE THREAD

**Issue by kaiyuhou** [louislam/uptime-kuma#700]
**Is it a duplicate question?**
No, to the best of my knowledge.

**Describe your problem**
I am using the Docker version of uptime-kuma, and want to make a small change to the UI. So I `exec` into the running container and I modified the `src/pages/DashboardHome.vue` file. But nothing changed in my browser. 

I have tried to switch browsers (to avoid cache), to restart the running container.

Is there a specific way for me to make the change effect? Thanks!

**Comment by chakflying** [comment]
Great point! The whole `/src` folder can probably be removed as well. But at this point most of the image size is in `node_modules`, whereas `/src` is just ~1MB, so the benefit is marginal.
