### ISSUE TITLE
Create Multiple User Logins with their own 2FA.

### ISSUE THREAD

**Issue by Trembler34** [louislam/uptime-kuma#701]
Hello,
I don't think this is possible as I haven't figured out a way so I'd like to request this as a new feature.. We have a need for multiple users to be able to login to the monitor with their own 2fa account. Problem is now with one user account and one 2fa. If another user wants to login with the master admin account the person with the 2fa setup to that account always has to be available to approve the request for them.. Becomes a big hassle. Also, maybe a toggle to allow those users to see the same monitors or have a blank slate to create their own? Hope that makes sense. Although I'd prefer any user that logs in to see all the same "master" monitors created from the master admin account.. Thank you! This tool is really turning out to be fantastic. Great work!

**Comment by deefdragon** [comment]
User management in general is #128. Having 2FA for each of those users is something that is rather important yes.
