### ISSUE TITLE
Do not allow duplicate tags per monitor?

### ISSUE THREAD

**Issue by fdcastel** [louislam/uptime-kuma#704]
**Is it a duplicate question?**
No.

**Is your feature request related to a problem? Please describe.**
Maybe.

**Describe the solution you'd like**
I was a bit surprised when I saw this:

![image](https://user-images.githubusercontent.com/629408/137261706-641daed5-25cc-4462-a9da-a17fe5b66283.png)

What is the value of  `t1` on `monitor1`?

I believe `monitor_tag` table should have a composite primary key (or an UNIQUE key/index) of `(monitor_id, tag_id)` blocking this occurrence in the db model.

**Describe alternatives you've considered**
None.

**Additional context**
If this is indeed the intended design, please disregard. However, I found the semantics of having one tag with multiple values somewhat strange (or that one tag could be "present" multiple times).

I discovered this while working on a PR for https://github.com/louislam/uptime-kuma/issues/686.

**Comment by chakflying** [comment]
in previous suggestions to implement this feature, tags are mostly used for filtering and grouping. So something like having both `DNS` and `DNS: TXT` make sense. Your use case did not even cross my mind when I made this, but I totally see that this will be useful as well. 

If you think your use case won't be dealing with duplicate tags, I guess we can just update the first tag we find with that name?

**Comment by fdcastel** [comment]
Understood. Thanks for the clarification @chakflying .

Yes. Updating the first tag is an option. I will update the PR for this scenario.

**Comment by CommanderStorm** [comment]
@fdcastel is this issue still relevant?
If not, could you close it? (otherwise this will become an immortal zombie)

**Comment by fdcastel** [comment]
Sure! 🧟 😄
