### ISSUE TITLE
Custom Notification Options (Working Hours, Afterhours) 

### ISSUE THREAD

**Issue by Trembler34** [louislam/uptime-kuma#707]
**Is it a duplicate question?**
Didn't see one

**Is your feature request related to a problem? Please describe.**
No, just a suggestion

**Describe the solution you'd like**
Right now all the systems we are monitoring and testing we have configured to poll at 60sec, retry twice (2 minutes) and then send an alert via SMS if the system is marked down after 2 minutes (works fine) This is fine during the day. However, we have some situations during the night, 2am , 3am etc.. It could be random where some machines may go down for 8 or 10 minutes then come back up. Then we get alerted at 2 or 3am in the morning (its not an emergency) is there a way to create a custom notification feature where you can specify your working hours for when the actual alerts will be sent during your normal thresholds configured? Say 8am to 5pm then once it hits 6pm until 7am the alerts are now set on the  "afterhours" setting which means unless a system is marked down for say 10+ minutes you won't get an alert? Hope that was clear.. Thank you!

**Comment by gweit** [comment]
Would it be possible to have some "Alert Reminders"?

Some sort of: if site down after 15min resend Alert-Notification?

**Comment by deefdragon** [comment]
Likely able to be tackled at the same time, the ability to silence a notification for a period of time, or until un-silenced, would be nice. (IE for when going on vacation and a non-critical service goes down etc.)

**Comment by chris-socialtap** [comment]
Would be really nice if there was an option for handling multiple notifications that are allowed within a period of time. For example, if 20 sites go down on the same server, I get 20 notifications down and 20 up, which means there is obviously a server problem (I don't need 40!). 

Perhaps if there was an option to set this globally that mutes any notifications after X over Y time - with only one notification after signaling there are more issues. I was thinking you could even optionally set the condition by tag, making further use of tags than just being a visual helper.

**Comment by chris-socialtap** [comment]
Cool idea!

Would be really nice if there was an option for handling multiple notifications that are allowed within a period of time. For example, if 20 sites go down on the same server, I get 20 notifications down and 20 up, which means there is obviously a server problem (I don't need 40!). 

Perhaps if there was an option to set this globally that automatically mutes any notifications after X over Y time - with only one notification after signaling there are more issues. I was thinking you could even optionally set the condition by tag, making further use of tags than just being a visual helper.

**Comment by csakaszamok** [comment]
+1

**Comment by louislam** [comment]
Maintenance Mode will be available in 1.19.0
