### ISSUE TITLE
Allows users to upload their own logo and set name of the page in place of the UK logo and words "Uptime Kuma"

### ISSUE THREAD

**Issue by markdesilva** [louislam/uptime-kuma#712]
**Is it a duplicate question?**
No

**Is your feature request related to a problem? Please describe.**
Not related to problem

**Describe the solution you'd like**
Allow users to set their own logo and name with a subtext "powered by Uptime Kuma". 

**Describe alternatives you've considered**
Manually editing the code

**Additional context**
-NA-

**Comment by deefdragon** [comment]
Agreed, Very similar to 607 tho it does specify adding to, and not replacing "powered by Uptime Kuma". 

Can you expand on what you want to place in that location @markdesilva ?

**Comment by markdesilva** [comment]
> Agreed, Very similar to 607 tho it does specify adding to, and not replacing "powered by Uptime Kuma".
> Can you expand on what you want to place in that location @markdesilva ?

Oh I just thought it would allow for user to have their own organization branding. I was thinking that the UK logo and words "Uptime Kuma" at the top left of both dash and status pages could be replaced by the user's own logo and wording but immediately below that would say "powered by Uptime Kuma". The footer "powered by Uptime Kuma" at the bottom of the status page doesn't need to change, that should always remain.

It could even be a paid option. But its alright, I understand having the original branding there is important for the propagation of the developer and project.

Cheers!

**Comment by deefdragon** [comment]
@markdesilva At least for the status page, if you edit it, you can already upload your own logo, and change the text that is displayed.

**Comment by deefdragon** [comment]
The ability to create/upload a custom theme is likely possible, but would probably be on the back-burner for now (See #531 for that).

As for the icon & text for the dashboard, its possible that should be changeable.

@louislam should this be re-opened with a title change to "Allow custom Dashboard Icon and Text like Status Page"? It feels like that is what is being asked for, and that comparing this to 607 was incorrect.

**Comment by dokbua** [comment]
> Related to #607
> 
> You can change the logo when creating a `Status Page`. I don't see the removal of the "Powered by uptime-kuma" happening unless you make your own fork

Actually nobody asked to remove the "powered by uptime-kuma" text. The suggestion was to be able to change the header text "Uptime Kuma" along with the logo image.  Seems a very minor change, making a fork for this would be overkill.

**Comment by ex0nuss** [comment]
Hi, an example for editing the "Uptime Kuma" title on the Dashboard would be, when having multiple Instances running. 
I have two hosts running Uptime Kuma and it would be nice to rename the Tab-title so I knew, which Tab corresponds to which instance :)

**Comment by MWGMorningwood** [comment]
Honestly shocked this isn't already a thing.
All of our internal hosted tools so far allow for rebranding, including favicon.

Currently, Uptime Kuma is the only sore thumb out of our backend tools.
Note that this doesn't take away from how great it is :)

**Comment by victorelec14** [comment]
I think it would be nice to implement a field in the configuration to change at least the title of the page. Thanks

![image](https://user-images.githubusercontent.com/543450/187695533-15053839-2c95-4d8d-8a0a-cbbb3908be3a.png)

**Comment by KorenMarvin** [comment]
It is possible to change the title if you really want.
![image](https://user-images.githubusercontent.com/36482784/197192031-ae0d3512-ea5f-438e-8355-43af2314178c.png)

This can be done by adding some css styling in the dist/index.html:

`header span[data-v-6080d853] {
    font-family: 'Montserrat', sans-serif!important;
    font-weight: 800!important;
    font-size: 0px!important;
}
	.title[data-v-6080d853]:after {
    font-weight: 700;
    content: "MK Vision Status";
    font-family: 'Montserrat', sans-serif!important;
    font-weight: 800!important;
    font-size: 22px;
    margin-left: 8px;
}`

**Comment by KorenMarvin** [comment]
Offcourse you can change the logo from the dist/ folder also. Just overwrite icon.svg/png :-)

**Comment by markdesilva** [comment]
Why does https://uptimerobot.com look like uptime-kuma? Did they use UK
code?

**Comment by KorenMarvin** [comment]
> Why does https://uptimerobot.com look like uptime-kuma? Did they use UK code?
> […](#)

I think it is the same framework. And a lot of the same code.

**Comment by louislam** [comment]
> Why does https://uptimerobot.com/ look like uptime-kuma? Did they use UK code?

No, I used UptimeRobot so many years. They existed before Uptime Kuma.

If you read again the README.md, I actually mentioned: It is a self-hosted monitoring tool like "Uptime Robot".

> I think it is the same framework. And a lot of the same code.

No and no, I built Uptime Kuma's UI on top of Bootstrap 5.

**Comment by KorenMarvin** [comment]
> > Why does https://uptimerobot.com/ look like uptime-kuma? Did they use UK code?
> 
> No, I used UptimeRobot so many years. They existed before Uptime Kuma.
> 
> If you read again the README.md, I actually mentioned: It is a self-hosted monitoring tool like "Uptime Robot".
> 
> > I think it is the same framework. And a lot of the same code.
> 
> No and no, I built Uptime Kuma's UI on top of Bootstrap 5.

Sorry I mean more the back-end code. And I do like the tool by the way ;-).

**Comment by markdesilva** [comment]
An ok, I though I recalled you saying you built UK cos you didn’t get
everything you wanted out of some other tool but I couldn’t remember what
it was. Good to know they didn’t rip you off.

**Comment by vish599** [comment]
> It is possible to change the title if you really want. ![image](https://user-images.githubusercontent.com/36482784/197192031-ae0d3512-ea5f-438e-8355-43af2314178c.png)
> 
> This can be done by adding some css styling in the dist/index.html:
> 
> `header span[data-v-6080d853] { font-family: 'Montserrat', sans-serif!important; font-weight: 800!important; font-size: 0px!important; } .title[data-v-6080d853]:after { font-weight: 700; content: "MK Vision Status"; font-family: 'Montserrat', sans-serif!important; font-weight: 800!important; font-size: 22px; margin-left: 8px; }`
> 
> Offcourse this is cheating a little bit ;-)
> 
> Offcourse you can change the logo from the dist/ folder also. Just overwrite icon.svg/png :-)

Hi @KorenMarvin  i unable to do this change

**Comment by KorenMarvin** [comment]
Is there a error that you get that i can debug?

**Comment by Woahai321** [comment]
> > It is possible to change the title if you really want. ![image](https://user-images.githubusercontent.com/36482784/197192031-ae0d3512-ea5f-438e-8355-43af2314178c.png)
> > This can be done by adding some css styling in the dist/index.html:
> > `header span[data-v-6080d853] { font-family: 'Montserrat', sans-serif!important; font-weight: 800!important; font-size: 0px!important; } .title[data-v-6080d853]:after { font-weight: 700; content: "MK Vision Status"; font-family: 'Montserrat', sans-serif!important; font-weight: 800!important; font-size: 22px; margin-left: 8px; }`
> > Offcourse this is cheating a little bit ;-)
> > Offcourse you can change the logo from the dist/ folder also. Just overwrite icon.svg/png :-)
> 
> Hi @KorenMarvin i am unable to do this change

Adding the style below into my head, and adjusting my data-v worked for me

`        <style>
        ##change data-v-xxxxxxxx##
        header span[data-v-6080d853] { 
            font-family: 'Montserrat', sans-serif!important; 
            font-weight: 800!important; 
            font-size: 0px!important; 
        } 
        ##change data-v-xxxxxxxx##
        .title[data-v-6080d853]:after { 
            font-weight: 700; 
            content: "Woah Uptime"; 
            font-family: 'Montserrat', sans-serif!important; 
            font-weight: 800!important; 
            font-size: 22px; 
            margin-left: 8px; 
        }
    </style>`
    
    
![image](https://user-images.githubusercontent.com/115117306/235039984-c8ae2e24-b6f3-4c12-930d-973828364914.png)

**Comment by TWSEQ** [comment]
Greetings! I attempted to make this change. I have the same need as others. We run multiple instances and it wanted to change the header only to reference the instance. 

First I have a standalone Windows Installation. I noticed when I made the changed mentioned above nothing happened. After some digging I noticed all the main files are being compressed (.gz) and the system is reading from the compressed file and not the actual .html or .css file that I edited. 

So my question is, what's causing the compressing and if it's part of Uptime, how do I force it to update the compressed files. If not maybe someone can guide me in the right direction!

Thanks in advance,

**Comment by pidev703** [comment]
@KorenMarvin  and @Woahai321 I am unable to change the name using that method, any help would be appreciated.

Adding the style below into the head second, and adjusting my data-v worked for me

**Comment by penwelldlamini** [comment]
I don't mean to ask a silly question but where is the directory for the html / css files located

**Comment by CommanderStorm** [comment]
It is unclear what you mean sad direcotry.
Do you mean the webclient? (that would be `src`)

Please have a look at https://github.com/louislam/uptime-kuma/blob/master/CONTRIBUTING.md for a description of our architecture/ how to set up a development environment/ how to build for production

**Comment by lucas-TagDev** [comment]
Add this in <head> in dist/index.html 
<script>
 document.addEventListener('DOMContentLoaded', function() {
    // Find the span element with the class 'fs-4 title'
    var spanElement = document.querySelector('.fs-4.title');

    // Check if the span element is found
    if (spanElement) {
        // Change the text content of the span element
        spanElement.textContent = 'Novo Título'; // Replace 'Novo Título' with your desired text
    } else {
        console.error('Span element not found');
    }
});

</script>

Reboot aplication

**Comment by srihackers** [comment]
any one here can change the "uptime kuma" home page name.

**Comment by CommanderStorm** [comment]
It is unclear what you mean by "home page name".
If you are referring to the status page, you can change the externally displayed name, favicon, title, ... via the image you upload and the `Title` you add in the respecitve status page settings.

As mentioned above, we won't change the name that is displayed in the dashboard. (I don't see a reason why you'd want to do that...)

**Comment by iaskeyz69** [comment]
> It is possible to change the title if you really want. ![image](https://user-images.githubusercontent.com/36482784/197192031-ae0d3512-ea5f-438e-8355-43af2314178c.png)
> 
> This can be done by adding some css styling in the dist/index.html:
> 
> `header span[data-v-6080d853] { font-family: 'Montserrat', sans-serif!important; font-weight: 800!important; font-size: 0px!important; } .title[data-v-6080d853]:after { font-weight: 700; content: "MK Vision Status"; font-family: 'Montserrat', sans-serif!important; font-weight: 800!important; font-size: 22px; margin-left: 8px; }`
> 
> Offcourse this is cheating a little bit ;-)
> 
> Offcourse you can change the logo from the dist/ folder also. Just overwrite icon.svg/png :-)

 i already tried to overwrite the icon.svg file, it seems its not working for me. Do i need to overwrite the png, 192x192.png,512x512.png file also?
