### ISSUE TITLE
<< and >> on dashboard reports not working?

### ISSUE THREAD

**Issue by markdesilva** [louislam/uptime-kuma#717]
**Is it a duplicate question?**
Not that I can find

**Describe the bug**
On the dashboard, the reports list on the right. At the bottom there are different pages of reports and you can go to the pages by clicking the ">" or "<", these work fine, but the go-to-first-page and go-to-last-page buttons "<<" and ">>" don't work.

**To Reproduce**

1. Go to 'Dashboard'
2. Click on '<<' or '>>'
3. Nothing happens

**Expected behavior**
Should go to the last page or first page of the reports

**Info**
Uptime Kuma Version:1.80
Using Docker?: Yes
Docker Version: 20.10.7
Node.js Version (Without Docker only):
OS: Ubuntu
Browser: Firefox, Chrome, Safari

**Comment by louislam** [comment]
They are not first/last buttons.

https://github.com/louislam/uptime-kuma/blob/2e24312f67352d71ec30cea32ecc7ff9d14bceb2/src/pages/Details.vue#L212-L220

**Comment by markdesilva** [comment]
Oh ok! Sorry, typically thats what those symbols mean.

Thank you!
