### ISSUE TITLE
Reduce browser load with lot of monitors

### ISSUE THREAD

**Issue by MichelBaie** [louislam/uptime-kuma#726]
Hi,
I'm still using more and more uptime-kuma and have reach 400~ monitors.
All those checks on the same home page slow down my browser.
Is here a way to had pages or something to lighten my browser ram and cpu ?

![image](https://user-images.githubusercontent.com/39345534/137595557-7963896f-1ea1-457d-9ae5-fe4cb19e7553.png)
![image](https://user-images.githubusercontent.com/39345534/137595567-52f0ddbc-ea99-46d6-9b56-3dd77a6e6081.png)

**Comment by MichelBaie** [comment]
yup, i'm impressed too by the low server load. But also using chrome is slow... And a little drop-down menu can be helpful on little computers... 

![image](https://user-images.githubusercontent.com/39345534/137619725-a214bb56-756b-4fa4-8532-19e870a55cdb.png)

**Comment by gaby** [comment]
I'm running into the same issue. Even worst when you open UK it doesnt show any data for 15-30, secs. 

The only fix I found so far is to set the auto-prune of metrics to 2-3 days.

**Comment by BananaHammock743** [comment]
> I'm running into the same issue. Even worst when you open UK it doesnt show any data for 15-30, secs.
> 
> The only fix I found so far is to set the auto-prune of metrics to 2-3 days.

How do you set prune metrics to 2-3 days? Is it “ Keep monitor history data for XX days”? I can’t seem to change this number, I get the error “Wrong data type” when trying to change this value.

**Comment by BananaHammock743** [comment]
> I'm running into the same issue. Even worst when you open UK it doesnt show any data for 15-30, secs.
> 
> The only fix I found so far is to set the auto-prune of metrics to 2-3 days.

@gaby how do you set prune metrics to 2-3 days? Is it “ Keep monitor history data for XX days”? I can’t seem to change this number, I get the error “Wrong data type” when trying to change this value.

**Comment by louislam** [comment]
> > I'm running into the same issue. Even worst when you open UK it doesnt show any data for 15-30, secs.
> > The only fix I found so far is to set the auto-prune of metrics to 2-3 days.
> 
> @gaby how do you set prune metrics to 2-3 days? Is it “ Keep monitor history data for XX days”? I can’t seem to change this number, I get the error “Wrong data type” when trying to change this value.

You should be using "No Auth" mode, it is a bug. Please update to 1.15.1.
https://github.com/louislam/uptime-kuma/releases/tag/1.15.1
