### ISSUE TITLE
Blank screen when accessing Uptime Kuma through FortiGate SSL VPN.

### ISSUE THREAD

**Issue by tompjep** [louislam/uptime-kuma#727]
Tried to access Uptime Kuma through Fortigate SSL VPN but only get blank screen. Page title and favicon is only thing working

**Comment by tompjep** [comment]
Tried to access Uptime Kuma via Apache reverse proxy and directly via ip and port. Both blank screen.

**Comment by louislam** [comment]
Duplicate of #632
