### ISSUE TITLE
Allow change of Ping and units for Push monitors (eg: ref #744 to monitor bandwidth)

### ISSUE THREAD

**Issue by markdesilva** [louislam/uptime-kuma#749]
**Is it a duplicate question?**
No

**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
For push monitors, allow user to change the "Ping" and "Average Ping" and "ms" to whatever they are trying to monitor (eg: "Ping" and "Average Ping" to "Bandwidth" and "Average Bandwidth" and "ms" to "Mbps" as for the case in #744 where user wants to monitor bandwidth). Ping (current) should also show units (eg: ms or Mbps etc)

**Describe alternatives you've considered**
No alternatives

**Additional context**
NA

![UK-pings](https://user-images.githubusercontent.com/59959024/138042397-cc8619e9-36df-429e-aee4-660eb4da98b2.jpg)

![UK-bw](https://user-images.githubusercontent.com/59959024/138044324-5cc0db1e-8493-4231-b72d-5a0b88b730ca.jpg)

**Comment by CommanderStorm** [comment]
I am going to merge this issue into #2256 as I think said issue is more specific and better written
=> closing as a duplicate (despite this being first ^^)

**Comment by markdesilva** [comment]
Thanks for finding it! Apologies for the duplicate.
