### ISSUE TITLE
`Sent Successfully` when clicking on `Test` button on empty form

### ISSUE THREAD

**Issue by Saibamen** [louislam/uptime-kuma#75]
1. Go to `/settings`
2. Click `Setup Notification`
3. Make sure to empty all fields
4. Click `Test` button

**Actual:**
`Sent Successfully`  notification will appear

![image](https://user-images.githubusercontent.com/905878/126062997-62abb48c-7e78-456b-8cab-7377bfc60ce9.png)

**Expected:**
No notification. Display required fields just like when we are clicking on `Save` button

**Comment by louislam** [comment]
Improved in 1.0.6
