### ISSUE TITLE
Optional backup encryption

### ISSUE THREAD

**Issue by deefdragon** [louislam/uptime-kuma#762]
**Is your feature request related to a problem? Please describe.**
While it is good to make sure that the backup is never in the wrong hands, it would be nice to encrypt it on Kuma's end should it ever actually happen.

**Describe the solution you'd like**
An option on export to encrypt the backup with a password.

**Describe alternatives you've considered**
It could be encrypted by hand once received, but that's extra steps that are probably best implemented on server before letting the backup travel over the network.

**Additional context**
Inspired by #761
Encryption is something that both Pf Sense and Truenas offer when you export a backup configuration.

**Comment by chakflying** [comment]
Obsolete as the backup feature has been dropped in https://github.com/louislam/uptime-kuma/pull/3892.
