### ISSUE TITLE
Add Helm Chart

### ISSUE THREAD

**Issue by dirsigler** [louislam/uptime-kuma#763]
Hello,

as some lovely people already provided instructions how to install this application on Kubernetes I took the idea a bit further and created a Helm Chart available under https://github.com/dirsigler/uptime-kuma-helm
This enables others to just add the application via Helm to their Kubernetes Cluster without running any `kustomize` and `kubectl apply`.

If you like you (or me) can add some documentation to the [k8s-unofficial Branch](https://github.com/louislam/uptime-kuma/tree/k8s-unofficial/kubernetes) to add instructions on how to additionally install the application via Helm.

**Comment by dirsigler** [comment]
Just a little hint here because I think (sadly) that this is needed:
My Helm Chart repository is obviously not perfect or anything near that.
This is also used for me to learn more about Helm, creating Charts and maintaining them (with proper testing included).

But I use my own Helm Chart quite successfully since yesterday, which also enables me to [install the Release via Terraform](https://registry.terraform.io/providers/hashicorp/helm/latest/docs/resources/release).

**Comment by malagant** [comment]
will try the chart and if I find something worth improving, I'll get back to you.

**Comment by deefdragon** [comment]
I suspect that this will remain unofficial in a similar manner to the k8s branch, but yes. Having documentation for and an option to use helm would be appreciated.

**Comment by Lefuneste83** [comment]
Currently migrating my docker stacks from Docker Swarm to a K3s Cluster orchestrated with Rancher and I would love to see this project officially ported to Helm.

**Comment by CommanderStorm** [comment]
We don't intend to maintain this in-tree as we are not using kubernetes anywhere.

We will leave this to the experts, such as https://github.com/louislam/uptime-kuma/wiki/%F0%9F%94%A7-How-to-Install#%EF%B8%8F-openshift-4-and-kubernetes-helm-3-chart-unofficial

There is also We don't intend to maintain this in-tree as we are not using kubernetes anywhere.

We will leave this to the experts, such as https://github.com/BigBoot/AutoKuma which does allow using CRDs.

Closing as not planned
