### ISSUE TITLE
Show another status ("Degraded Performance", "Mitigating Attack") on difference of a Traceroute Check

### ISSUE THREAD

**Issue by httpjamesm** [louislam/uptime-kuma#765]
**Is it a duplicated question?**
Please search in Issues without filters: https://github.com/louislam/uptime-kuma/issues?q=

No. 

**Is your feature request related to a problem? Please describe.**

Yes. Uptime Kuma cannot detect when my server's DDoS mitigation is enabled. This can be detected using a traceroute. 

**Describe the solution you'd like**

A check where Uptime Kuma does a traceroute and checks for a specific term. When doing a traceroute to my server during an attack, there is a hop called ddos-mitigation.xxx. 

**Describe alternatives you've considered**

None really. 

**Additional context**

**Comment by CommanderStorm** [comment]
> I actually want UK to show another status, such as "Degraded Performance" or "Mitigating Attack"

I would vote to close this issue in favour of #2911 as duplicate/`wont-fix` adding another level would likely mean modifying half of our notification providers.

@chakflying oppinions?

**Comment by chakflying** [comment]
Agreed, it's unlikely this would be implemented.
