### ISSUE TITLE
SMS API, free api

### ISSUE THREAD

**Issue by kry008** [louislam/uptime-kuma#779]
**Is it a duplicated question?** NO
Please search in Issues without filters: https://github.com/louislam/uptime-kuma/issues?q=

**Is your feature request related to a problem? Please describe.** NO

**Describe the solution you'd like** SMS API from your old phone and sim card

**Additional context**
All documentation:
[smsgateway.me](https://smsgateway.me/sms-api-documentation/messages/sending-a-sms-message)
It is POST API, free, but you need android phone and phone number

**Comment by Kero34** [comment]
You can use a webhook notification with the url+api from Freemobile.
`https://smsapi.free-mobile.fr/sendmsg?user=USERID&pass=PASSWORD&msg=SERVER%20X%20DOWN `

**Comment by kry008** [comment]
> You can use a webhook notification with the url+api from Freemobile. `https://smsapi.free-mobile.fr/sendmsg?user=USERID&pass=PASSWORD&msg=SERVER%20X%20DOWN `

You cannot use it in other countries, my 

> Or this https://telerivet.com/product/app

Is for your SIM card country

**Comment by CommanderStorm** [comment]
@kry008 Given that
-  https://github.com/smsgatewayme has not recieved an update,
- it is not in the playstore anymore and
- the website does not look maintained,

I don't think adding this notification provider would be a good choice.
=> Could you close this issue if you agree?

**Comment by chakflying** [comment]
Closing as obsolete.
