### ISSUE TITLE
How to add SSL cert to Uptime Kuma status page

### ISSUE THREAD

**Issue by Kriiiiiiiz** [louislam/uptime-kuma#786]
Hi , at first sorry for my bad English guys !

I think it would be great to have a tutorial (if there isn't one currently) for new users, about how to add an SSL cert to Uptime Kuma, like with CloudFlare, CertBot, etc...

Thank u all guys for making Uptime Kuma that great, i really appreciate it ! :P

**Comment by Kriiiiiiiz** [comment]
> To use the docker arguments with LetsEncrypt, I do the following:
> 
> 
> 
> 1) Get your SSL certs as standalone:
> 
> 
> 
> `/usr/bin/certbot certonly --standalone --email name@email.com -d  status.mydomain.com --agree-tos`
> 
> 
> 
> This will generate the pem files in the directory
> 
> 
> 
> `/etc/letsencrypt/live/status.mydomain.com/`
> 
> 
> 
> 2) Create the volume for your uptime-kuma container:
> 
> 
> 
> `docker volume create uptime-kuma`
> 
> 
> 
> You should now have the uptime-kuma docker volume directory:
> 
> 
> 
> `/var/lib/docker/volumes/uptime-kuma/_data/`
> 
> 
> 
> 3) Create a directory called "ssl" in the docker volume directory:
> 
> 
> 
> `mkdir -p /var/lib/docker/volumes/uptime-kuma/_data/ssl`
> 
> 
> 
> 4) Copy the *.pem files to the docker volume ssl directory you just created in step 3:
> 
> 
> 
> `cp /etc/letsencrypt/live/status.mydomain.com/*.pem /var/lib/docker/volumes/uptime-kuma/_data/ssl`
> 
> 
> 
> You should be able to see all the pem files when you do:
> 
> 
> 
> `ls /var/lib/docker/volumes/uptime-kuma/_data/ssl`
> 
> 
> 
> 5) You now have to create a crontab to attempt renewal of the LetsEncrypt ssl certs on every 1st and 15th of every month and then copy the renewed certs to the docker volume directory and restart the uptime-kuma docker container:
> 
> 
> 
> `0 0 1,15 * * /usr/bin/certbot renew --standalone  --preferred-challenges http; cp /etc/letsencrypt/live/status.mydomain.com/*.pem /var/lib/docker/volumes/uptime-kuma/_data/ssl; /usr/bin/docker restart uptime-kuma`
> 
> 
> 
> NOTE: This crontab will copy the pem files and restart the container whether the certs have expired or not. You can write a proper script to check if the certs are really expired before renewal, but the above is good enough for a start.
> 
> 
> 
> 6) Fiinally you can start the uptime kuma container using the docker arguments for ssl cert and key file:
> 
> 
> 
> `docker run -d --restart=always -p 3001:3001 -v uptime-kuma:/app/data --env SSL_KEY="/app/data/ssl/privkey.pem" --env SSL_CERT="/app/data/ssl/fullchain.pem" --name uptime-kuma louislam/uptime-kuma:1`
> 
> 
> 
> When you start the container, do a:
> 
> 
> 
> `docker logs -f uptime-kuma`
> 
> 
> 
> to see the startup process and make sure HTTPS is being used. You should see something like this:
> 
> 
> 
> ```
> 
> Welcome to Uptime Kuma
> 
> Node Env: production
> 
> ...
> 
> Version: 1.9.1
> 
> Creating express and socket.io instance
> 
> Server Type: HTTPS
> 
> Data Dir: ./data/
> 
> Connecting to Database
> 
> ...
> 
> ...
> 
> ```
> 
> 
> 
> This method works well for me, no need to worry about the websockets.
> 
> 

Many thanks Mark ! That worked for me, really appreciate it <3 and I'm sure this will help someone else :)

**Comment by markdesilva** [comment]
> Many thanks Mark ! That worked for me, really appreciate it <3 and I'm sure this will help someone else :)

Happy to help! Glad it worked 😊

**Comment by gaby** [comment]
@louislam Can the information on this post be added to a wiki page? I think it's very helpful for the users.

**Comment by pepa65** [comment]
It's so extremely easy with `caddy`, your `Caddyfile` just needs:
```
my.domain.with.a.record {
    reverse_proxy 127.0.2.2:3001
}
```
(This is based on `docker run -d --restart=always -p 127.0.2.2:3001:3001 -v uptime-kuma:/app/data --name uptime-kuma louislam/uptime-kuma:1`)
