### ISSUE TITLE
Add Free Whatsapp API

### ISSUE THREAD

**Issue by Sacred-Shadow** [louislam/uptime-kuma#787]
**Is it a duplicated question?**
✅

**Is your feature request related to a problem? Please describe.**
⛔

**Describe the solution you'd like**
It would be cool if Whatsapp were added as a notification channel.
There is the CallMeBot.com page which you can use to send Whatsapp messages.

The API call is also very easy - it would be nice if you could somehow incorporate that.
https://www.callmebot.com/blog/free-api-whatsapp-messages/

**Describe alternatives you've considered**
⛔

**Additional context**
⛔

**Comment by eduardogsilva** [comment]
> As far as I know, WhatsApp do not provide any free API. I guess callmebot is using some unauthorized 3rd party API to send your message via their number. It should be not reliable.
> 
> Reopen if I am wrong.

Hello @louislam callmebot is an unofficial WhatsApp API, but it's kind of reliable. I've been using their service for some time with homeassistant, and I would love to use it for Kuma notifications too.  

Can you please review this? 

Thank you!

**Comment by CommanderStorm** [comment]
@eduardogsilva the open PR for this is
https://github.com/louislam/uptime-kuma/pull/4605
