### ISSUE TITLE
Notification Levels

### ISSUE THREAD

**Issue by deathbybandaid** [louislam/uptime-kuma#795]
**Is it a duplicated question?**
I didn't see it.

**Is your feature request related to a problem? Please describe.**
No

Say you have an IT department with 3 levels of support:

Level 1) Basic helpdesk, doesn't touch servers.

Level 2) Does some server stuff.

Level 3) Works on server tickets that get escalated.

Level 4 Department Manager) Shouldn't see tickets from below levels unless they really escalate to this level.

Now imagine you have notifications for different services for different levels of support.

So the feature request is to designate when to automatically escalate to another notification:

Server can't ping 3 times, Level2.

Server still isn't pinging 10 minutes later, Level3.

Server is still down after 30 minutes, notify department manager to check on.

**Comment by CommanderStorm** [comment]
I think this should be handled in a dedicated App like https://github.com/louislam/uptime-kuma/pull/2783
Let's not overcomplicate this

**Comment by CommanderStorm** [comment]
@deathbybandaid 
We are consolidating duplicate issues a bit to make issue management easier.
I think, we should track this issue in #1315 as there is no functional difference (maybe just small naming differences, but nothing that would require a different issue imo)
⇒ I am going to close this as a duplicate.
