### ISSUE TITLE
Error: ENOENT: no such file or directory, stat 'dist\index.html'

### ISSUE THREAD

**Issue by Saibamen** [louislam/uptime-kuma#80]
`Error: ENOENT: no such file or directory, stat 'dist\index.html'` after starting backend (command: `npm run start-server`)

**Comment by Saibamen** [comment]
Dev documentation is wrong. You need to build you frontend as production environment (`npm run build`) first (sic!)...

**Comment by louislam** [comment]
It is expected for development, because it act as a websocket server only. You need to start the frontend sperately.
