### ISSUE TITLE
[Feature]: Nextcloud Talk integration

### ISSUE THREAD

**Issue by theoneandonly-vector** [louislam/uptime-kuma#814]
### 🏷️ Feature Request Type

New Notification

### 🔖 Feature description

Add Nextcloud Talk for Notifications

### ✔️ Solution

I want to send messages to my user via Nextcloud-Talk (not via Nextcloud itself)
This would allow me to receive my Notifications on the Phone.

### ❓ Alternatives

alternative would be to use matterbridge and then setup rocket.chat or similar and then bridge them

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar feature request

**Comment by idominiki** [comment]
Would be great if 'url_prefix' is also working in Uptime Kuma Setting
#https://github.com/caronc/apprise/issues/974
