### ISSUE TITLE
Telegram call notifications

### ISSUE THREAD

**Issue by Zegorax** [louislam/uptime-kuma#816]
### 🏷️ Feature Request Type

New Notification

### 🔖 Feature description

For critical systems, a Telegram call via the Bot API could be a really good alertor. By receiving a VoIP Call when a critical service goes down, you are sure that you will not miss the notification.

### ✔️ Solution

When a service goes down and that this service has the Telegram Call notification assigned, a call should be initiated from the Bot to the chat_id configured in the settings.

Here is an implementation in Python : https://github.com/MarshalX/tgcalls

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar feature request

**Comment by CommanderStorm** [comment]
@Zegorax 
We are consolidating duplicate issues a bit to make issue management easier.
I think, we should track this issue in #3295 as this is covered under the more general issue
⇒ I am going to close this as a duplicate. (despite this being the older issue)
