### ISSUE TITLE
[Feature]: <Multi-location checks>

### ISSUE THREAD

**Issue by stardevelop** [louislam/uptime-kuma#828]
### 🏷️ Feature Request Type

Other

### 🔖 Feature description

We want to verify incidents from multiple locations (in different countries) to prevent false-positives.

### ✔️ Solution

Add additional servers in multiple locations for monitoring a website.

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar feature request

**Comment by deefdragon** [comment]
Agreed. Duplicate of #84 and some of the issues I cross referenced in #468 (#324 specifically)

**Comment by CommanderStorm** [comment]
Actually, this is a duplicate of #4031 instead ^^
