### ISSUE TITLE
[Feature]: <Register/Login/Logout>

### ISSUE THREAD

**Issue by stardevelop** [louislam/uptime-kuma#830]
### 🏷️ Feature Request Type

UI Feature

### 🔖 Feature description

Please add:
Register an account using Full Name and Email and Password..
Login to an account using Email and Password.
Logout from an account.

### ✔️ Solution

Adding Register, Login, Logout

### ❓ Alternatives

Integrating Google Sign-In into the web app

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar feature request

**Comment by deefdragon** [comment]
Duplicate. User management in general is #128.
