### ISSUE TITLE
[Bug?]: User Data Leaked to Client Without Two Step Auth Token Verified

### ISSUE THREAD

**Issue by Co2333** [louislam/uptime-kuma#833]
### 👟 Reproduction steps

Input the right username and password but do not input auth-token.

### 👍 Expected behavior

Nothing send back.

### 👎 Actual Behavior

Sending monitor list back, with url in it.

<img width="634" alt="截屏2021-10-29 下午11 48 23" src="https://user-images.githubusercontent.com/25259084/139465445-850d0372-5dc7-434f-a04e-9d743cb84a04.png">

### 🐻 Uptime-Kuma version

1.9.1 ? current upstream master d4c9431

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

**Comment by louislam** [comment]
Thanks for the report, fixed in 1.9.2
