### ISSUE TITLE
[Help]: How can change the heartbeat time for <20

### ISSUE THREAD

**Issue by ccmaou** [louislam/uptime-kuma#836]
### 📝 Describe your problem

How can change the heartbeat time for <20 , and how can i change the notify message timezone ,it was wrong

### 🐻 Uptime-Kuma version

1.9.1

### 💻 Operating System

CentOS 7.9

### 🌐 Browser

Microsoft Edge

### 👀 Have you spent some time to check if this question has been raised before?

- [X] I checked and didn't find similar question

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

**Comment by louislam** [comment]
Duplicate of #606
