### ISSUE TITLE
[Feature]: Clear All Toasts

### ISSUE THREAD

**Issue by arch1v1st** [louislam/uptime-kuma#841]
### 🏷️ Feature Request Type

UI Feature

### 🔖 Feature description

Within the Web App, if there were many detected down times, the UI fills up with red Toasts that must be dismissed one by one.  Green 'up' messages timeout on their own, but the red 'down' messages remain.  It would be a good UX improvement to provide a 'close all' button.

### ✔️ Solution

A small semi-transparent X at the bottom right corner to clear all Toast messages.

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar feature request

**Comment by gaby** [comment]
👍🏻 for this feature. The library currently used supports a "Clear All" option.

Info here: https://github.com/Maronato/vue-toastification#clear-all-toasts

**Comment by mstraa** [comment]
I third this :)

**Comment by BercziSandor** [comment]
Hint: https://www.npmjs.com/package/vue-toastification#clear-all-toasts
