### ISSUE TITLE
[healthcheck error]: <Version 1.9.x onwards, the healthcheck.js script returns error status>

### ISSUE THREAD

**Issue by syed-faraz** [louislam/uptime-kuma#845]
### 👟 Reproduction steps

running the command 'node extra/healthcheck.js' from inside the container returns 'Health Check ERROR' due to which the container is restarting with tcp connection refused error message.

I compared the script from version '1.8.0', its the same and returns 'Health Check OK' status

### 👍 Expected behavior

Health Check OK

### 👎 Actual Behavior

Health Check ERROR

### 🐻 Uptime-Kuma version

1.9.2

### 💻 Operating System

Linux

### 🌐 Browser

Chrome

### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

**Comment by chakflying** [comment]
I think this is ENV variables again 🤦‍♂️.

**Comment by louislam** [comment]
You did not answer the Docker version, are you using k8s?

If yes, please read #741

**Comment by syed-faraz** [comment]
> You did not answer the Docker version, are you using k8s?
> 
> If yes, please read #741

Yes indeed! Thank you. Changing the service name helped.
