### ISSUE TITLE
[Help]: In new Version 1.10.0 embedding is not allowed anymore

### ISSUE THREAD

**Issue by root9191** [louislam/uptime-kuma#851]
### 📝 Describe your problem

Hello,

Since i made the Update via docker-compose to the Version 1.10.0 the embedded Page could not opened in Organizr.
Is there a Environment Variable to enable embedding again?

Best Regards

### 🐻 Uptime-Kuma version

1.10.0

### 💻 Operating System

Debian Bullseye

### 🌐 Browser

Firefox

### 🐋 Docker

20.10.10

### ⚠️ Please verify that this question has NOT been raised before.

- [X] I checked and didn't find similar question

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

**Comment by louislam** [comment]
Mentioned in the release note:

Fix CWE-1021 issue, iframe embed may be broken (Set UPTIME_KUMA_DISABLE_FRAME_SAMEORIGIN to 1 if you need this)

**Comment by root9191** [comment]
Thank you, works perfectly.
