### ISSUE TITLE
[Help]: Change docker container user chown maintenance issue

### ISSUE THREAD

**Issue by ElleshaHackett** [louislam/uptime-kuma#857]
### 📝 Describe your problem

Currently `docker exec uptime whoami` results in `root`. I want to run this whole container as a different user using this dockerfile.

````
FROM louislam/uptime-kuma:1
RUN adduser --system --group uptime
USER uptime
````

But I get a bunch of:
```
==> Performing startup jobs and maintenance tasks
chown: changing ownership of '/app/data/kuma.db': Operation not permitted
chown: changing ownership of '/app/data/kuma.db-wal.bak20211022112928': Operation not permitted
chown: changing ownership of '/app/data/kuma.db-wal.bak20211101090108': Operation not permitted
chown: changing ownership of '/app/data/kuma.db-shm.bak20211101090108': Operation not permitted
chown: changing ownership of '/app/data/kuma.db.bak20211022112928': Operation not permitted
chown: changing ownership of '/app/data/kuma.db.bak20211101090108': Operation not permitted
chown: changing ownership of '/app/data/kuma.db.bak0': Operation not permitted
chown: changing ownership of '/app/data/kuma.db-wal.bak0': Operation not permitted
chown: changing ownership of '/app/data/kuma.db-shm.bak20211022112928': Operation not permitted
chown: changing ownership of '/app/data/upload': Operation not permitted
chown: changing ownership of '/app/data/error.log': Operation not permitted
chown: changing ownership of '/app/data/kuma.db-shm.bak0': Operation not permitted
chown: changing ownership of '/app/data': Operation not permitted
``` 

This is because the user is switched and then apparently a miantenance task starts doing chown commands. How do I disable this task? Because I want to run it before my `USER` line instead. Something like 
````
RUN adduser --system --group uptime && \
    mkdir -p /app/data && \
    chown -R uptime:uptime /app
USER uptime
````

### 🐻 Uptime-Kuma version

1

### 💻 Operating System

Ubuntu 20

### 🌐 Browser

Chrome

### 🏷️ Docker Image Tag

louislam/uptime-kuma:1

### ⚠️ Please verify that this question has NOT been raised before.

- [X] I checked and didn't find similar question

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

**Comment by louislam** [comment]
You can change PUID and PGID to 1000

Details:
https://github.com/louislam/uptime-kuma/pull/436

Unfortunately, some users was experiencing some permission problems when it is not root user. I cannot find the reason, so use at your own risk.

If you want to use `USER`, you need to build your own image.
