### ISSUE TITLE
[Help]: What Docker capabilities are required?

### ISSUE THREAD

**Issue by ElleshaHackett** [louislam/uptime-kuma#858]
### 📝 Describe your problem

I am trying to limit the Docker capabilities of the uptime-kuma container. Ideally I want to add `cap_drop: ['ALL']` in my docker-compose file. But clearly that wouldn't not work. Is there any documentation on what the minimum required docker capabilities are for uptime-kuma to function properly?

### 🐻 Uptime-Kuma version

1

### 💻 Operating System

Ubuntu 20

### 🌐 Browser

Chrome

### 🏷️ Docker Image Tag

louislam/uptime-kuma:1

### ⚠️ Please verify that this question has NOT been raised before.

- [X] I checked and didn't find similar question

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

**Comment by unknownFalleN** [comment]
I startet kuma with portainer with default CAP. TCP Ping is not working with the default Cap 

`
CapAdd=[AUDIT_WRITE CHOWN DAC_OVERRIDE FOWNER FSETID KILL MKNOD NET_BIND_SERVICE NET_RAW SETFCAP SETGID SETPCAP SETUID SYS_CHROOT]` 

`
CapDrop=[AUDIT_CONTROL BLOCK_SUSPEND DAC_READ_SEARCH IPC_LOCK IPC_OWNER LEASE LINUX_IMMUTABLE MAC_ADMIN MAC_OVERRIDE NET_BROADCAST SYSLOG SYS_ADMIN SYS_BOOT SYS_MODULE SYS_NICE SYS_PACCT SYS_PTRACE SYS_RAWIO SYS_RESOURCE SYS_TIME SYS_TTY_CONFIG WAKE_ALARM]`

Currently I am looking for a solution for tcp ping. Ping, HTTP and Notification with matrix is working ;)

**Comment by ElleshaHackett** [comment]
I think it should not be closed and instead this should be documented.
