### ISSUE TITLE
[Help] Socket Timeout

### ISSUE THREAD

**Issue by morzan1001** [louislam/uptime-kuma#865]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

Hi, I am trying to host Uptime-Kuma as a Docker container. I just took the Docker command from the readme and added for the port `-p 127.0.0.1:3001:3001` so that the port 3001 is not reachable from outside my server. I also configured a Nginx as a reverse proxy to terminate SSL and then forward in requests into the container. 

This works so far, the website loads and I can see for example the status page, but as soon as I want to go to the dashboard I get the error message: 

`Cannot connect to the socket server. [Error: websocket error] Reconnecting...`

Does anyone have an idea what I can do? Thanks a lot!

### 🐻 Uptime-Kuma Version

louislam/uptime-kuma:1

### 💻 Operating System and Arch

Ubuntu 20.04.3 LTS

### 🌐 Browser

Firefox

**Comment by louislam** [comment]
Did you read this:
https://github.com/louislam/uptime-kuma/wiki/Reverse-Proxy

**Comment by morzan1001** [comment]
Well, thanks for answering, my Nginx-config was very close to this but i did not include the "Connection "upgrade""-Header. Now its working just fine :tada:
