### ISSUE TITLE
[Feature] Display all down status [RED] on top of the page on Status page 

### ISSUE THREAD

**Issue by cs-michaelc** [louislam/uptime-kuma#866]
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

UI Feature

### 🔖 Feature description

[Feature] Display all down status [RED] on top of the page on the Status page

### ✔️ Solution

Disply failed services on top

**Comment by deefdragon** [comment]
I think this is basically a duplicate of #654

**Comment by cs-michaelc** [comment]
Oops. Cool thank you
