### ISSUE TITLE
[Feature] Be able to monitor https services on custom ports

### ISSUE THREAD

**Issue by Kriiiiiiiz** [louislam/uptime-kuma#867]
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

Other

### 🔖 Feature description

Would be great (at least for me) to be able to monitor https services on custom ports not only 433 with Uptime Kuma.

### ✔️ Solution

If no port specified check on 443 but also be able to add monitor for other ports (https://mydomain.com:4433)

**Comment by chakflying** [comment]
The url format in your proposed solution already works.

**Comment by louislam** [comment]
Yes, close.

If you need help, please open a help issue.

**Comment by Kriiiiiiiz** [comment]
It Does not Work for me. Could it be cause i'm using a subdomain ? (https://eu.mydomain.com:8080)
