### ISSUE TITLE
`Valheim`/`udp` service monitoring

### ISSUE THREAD

**Issue by Setsua** [louislam/uptime-kuma#872]
I was looking for a way to monitor valheim with uptime kuma which is not (yet?) possible with Uptime Kuma.
But I found a workaround which could help a few people.

I've installed nginx on my valheim server.
I've added a cronjob which checks every minute if the process is running and post a 1 into a html file, if not echo a 0 into it.

`* * * * * if [ $(pidof ./valheim_server.x86_64) ]; then echo 1 > /var/www/html/index.html; else echo 0 > /var/www/html/index.html;fi`

Then I used the HTTP(s) Keyword request to look for a 1 at given address.

![keyword](https://user-images.githubusercontent.com/37017004/140230910-ea3993c9-502b-4a64-afed-72fc4a5d9715.png)

Note: If this "Issue" isnt valid just delete it.

#551
#9

**Comment by deefdragon** [comment]
This would likely be better done with a [push based monitor](https://github.com/louislam/uptime-kuma/issues/744#issuecomment-947219792). No need to go through with installing nginx on the machine. Just send the response to kuma directly.

**Comment by takaze212** [comment]
1. Create script
`nano /opt/check_service.sh`

```
#!/bin/bash

service=$1
url=$2

if [ -z "$url" ] || [ -z "$service"]
  then
    echo "argument missing"
    echo "usage check_service.sh [servicename] [push URL]"
    exit
fi

/bin/systemctl -q is-active "$service.service"
status=$?
if [ "$status" == 0 ]; then
    curl --silent --output /dev/null $url
fi
```
2. make executable
`chomd +x /opt/check_service.sh`

3. create contab, run every minute
`crontab -e`

`* * * * * /opt/check_service.sh [[YOUR_SERVICENAME_HERE]] [[YOUR_UPTiME_PUSH_URL_HERE]] > /dev/null`

4. enjoy :)

**Comment by Setsua** [comment]
> This would likely be better done with a [push based monitor](https://github.com/louislam/uptime-kuma/issues/744#issuecomment-947219792). No need to go through with installing nginx on the machine. Just send the response to kuma directly.

Thanks. Did not know of push api calls. Way better solution.

**Comment by rezzorix** [comment]
Could be more reliable and easier to check your Valheim Server status using the steam api...

You get your api key here: https://steamcommunity.com/dev/apikey

This would be the link to a site that gives you all information available for your server in json format:
`https://api.steampowered.com/IGameServersService/GetServerList/v1/?filter=\appid\892970\addr\your-server-ip:port&key=steamapikey`

The "appid" above is already the Valheim app ID - you can of course get this info for other servers, too, just check on steam.

You can see an example of  how it is implemented on a website [here](https://goodclan.net/game-servers/valheim/)

**Comment by louislam** [comment]
> Could be more reliable and easier to check your Valheim Server status using the steam api...
> 
> You get your api key here: https://steamcommunity.com/dev/apikey
> 
> This would be the link to a site that gives you all information available for your server in json format: `https://api.steampowered.com/IGameServersService/GetServerList/v1/?filter=\appid\892970\addr\your-server-ip:port&key=steamapikey`
> 
> The "appid" above is already the Valheim app ID - you can of course get this info for other servers, too, just check on steam.
> 
> You can see an example of how it is implemented on a website [here](https://goodclan.net/game-servers/valheim/)

If it is using steam server, uptime kuma is already supported it.

**Comment by rezzorix** [comment]
Yes, but in Uptime with Steam-Monitor you will only get the online status.

If you directly parse the json output of the API you get also things like "players online", "bots online", "server version", etc. etc. (depending on what the game provides)

**Comment by aarste** [comment]
What should be put into the hostname and port fields for Steam Game Server? I have an anonymously installed valheim server (via steamcmd) running public on a windows machine 192.168.1.11 with ports 2456-2458 exposed. Uptime Kuma also has my steam API in the settings but the check fails on with the following:

192.168.1.11
htpc.home
public IP
port 2456

This address returns a {"response":{}}
https://api.steampowered.com/IGameServersService/GetServerList/v1/?filter=\appid\892970\addr\<public ip>:2456&key=<key removed>

**Comment by rezzorix** [comment]
Is your server reachable from the outside on your public IP?
Did you configure correct port forwarding in your router?

**Comment by rezzorix** [comment]
Oh and just another note; if not explicitly set different, the query port for Valheim server should be  2457

**Comment by aarste** [comment]
> Oh and just another note; if not explicitly set different, the query port for Valheim server should be 2457

That port number fixed it for me, steam web api shows my stats and uptime kuma is able to see it now, thank you!

**Comment by MWGMorningwood** [comment]
> https://api.steampowered.com/IGameServersService/GetServerList/v1/?filter=\appid\892970\addr\your-server-ip:port&key=steamapikey

thank you massively for this- solid workaround to no gamedig in some situations

**Comment by InsertDisc** [comment]
> What should be put into the hostname and port fields for Steam Game Server? I have an anonymously installed valheim server (via steamcmd) running public on a windows machine 192.168.1.11 with ports 2456-2458 exposed. Uptime Kuma also has my steam API in the settings but the check fails with the following attempts:
> 
> 192.168.1.11 htpc.home public static IP port 2456
> 
> This address returns a {"response":{}} [https://api.steampowered.com/IGameServersService/GetServerList/v1/?filter=\appid\892970\addr\[public](https://api.steampowered.com/IGameServersService/GetServerList/v1/?filter=%5Cappid%5C892970%5Caddr%5C%5Bpublic) ip removed]:2456&key=[key removed]

I've installed a Satisfactory Server exactly the same way 'anonymous with steamcmd' and am also getting a no response and have no idea what I'm doing wrong. Tried every port that I can think of that the server uses to no avail.

**Comment by CommanderStorm** [comment]
Closing as valheim is supprorted via the `gamedig` monitor: https://github.com/gamedig/node-gamedig/blob/master/GAMES_LIST.md
No extra monitor nessesary
=> closing as resolved
