### ISSUE TITLE
[Feature] Change Uptime Kuma Branding

### ISSUE THREAD

**Issue by OrefaSol** [louislam/uptime-kuma#876]
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

UI Feature

### 🔖 Feature description

You should add a option to change Uptime Kuma Logo and name on top.

### ✔️ Solution

Uptime Kuma Branding should be changeable.

**Comment by ivanbratovic** [comment]
Related to #712 and #607. Conclusions for this topic have already been made so check out those threads.
