### ISSUE TITLE
[Feature] Configurable Timeouts

### ISSUE THREAD

**Issue by MaLub** [louislam/uptime-kuma#877]
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

Other

### Configurable Timeouts.

We want to get alarmed when our services doesn't response in a given time.

### ✔️ Solution

Setting a configurable timeout in which the service has to response.

### ❓ Alternatives

Similar functionality in uptime robot: https://blog.uptimerobot.com/uptimerobot-august-2021-update/

**Comment by HTDemony** [comment]
+1

**Comment by ppowalowski** [comment]
+1 It would be awesome to generate a warning if a certain response time is exceeded and a down-notice if a max threshold is exceeded.

**Comment by zenyr** [comment]
Just updated a PR that would help this use-case, hope you guys don't mind that I linked this issue!

**Comment by eaglerbits** [comment]
+1

**Comment by katsil** [comment]
+1

**Comment by pcgeek86** [comment]
I'd love to see configurable timeouts. Right now the HTTP timeout is hard-coded at 48 seconds, which is way too long for my monitors. I need to set timeouts around 3-10 seconds.

**Comment by LeBaronDeCharlus** [comment]
+1

**Comment by CommanderStorm** [comment]
@borgogelli @LeBaronDeCharlus @katsil @eaglerbits @HTDemony 

Please refrain from posting `+1` / requests for updates things on issues, as this makes issue-management harder.
Issues are for discussing what needs to be done how by whom.
[We use 👍🏻 on issues to prioritise work](https://github.com/louislam/uptime-kuma/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).
