### ISSUE TITLE
[Question] Should getaddrinfo EAI_AGAIN treated as down?

### ISSUE THREAD

**Issue by Co2333** [louislam/uptime-kuma#878]
According to this [wiki](https://datatracker.ietf.org/doc/html/draft-ietf-ipngwg-bsd-api), EAI_AGAIN (from getaddrinfo) is a **temporary** failure in name resolution, which means we should retry several times before marking this service as down.

And in my experience, EAGAIN may be also used for a non-blocking api telling user to try this api again for the final result. (such as libssh2)

It worth a discuss.

**Comment by louislam** [comment]
Which docker image are you using?

It usually happen on Alpine image.

Search this repo for more discussion.

**Comment by chakflying** [comment]
I remember reading somewhere that transparent retries are not recommended, since it can incur unexpected latency to the user. I guess it's possible to add a rule for EAI_AGAIN to automatically trigger the monitor level retry, but probably not worth it for such an edge case?

**Comment by Co2333** [comment]
Actually it’s not a edge case, running inside hyper-v with docked container, happening 2-3times/hour. I had set a 2 time retry and now it is working fine tho.
