### ISSUE TITLE
Support for "inverted" availability checking

### ISSUE THREAD

**Issue by k4ds3** [louislam/uptime-kuma#88]
Allowing to invert the "is-up"-condition of a monitor would allow to for example check if a firewall is working by adding a monitor which tries to access ports the firewall is blocking. 

Monitors could have an option called something like "Invert Availability" which tells the monitor that it actually expects to not reach the target host and therefore handles the non-reachability as the wanted outcome.

**Comment by louislam** [comment]
Implemented in 1.0.8
