### ISSUE TITLE
[Help] Send data x-www-form-urlencoded

### ISSUE THREAD

**Issue by lengmiguel** [louislam/uptime-kuma#881]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

Good morning, you can send parameters in the body x-www-form-urlencoded, if so, could you show me the steps.
Thank you very much and it is an excellent job

### 🐻 Uptime-Kuma Version

1.10.0

### 💻 Operating System and Arch

CENTOS 8

### 🌐 Browser

Google Chrome 95.0.4638.69

### 🟩 NodeJS Version

14.18.1

**Comment by gaby** [comment]
@lengmiguel Can you add a title to your issue.

**Comment by louislam** [comment]
Not supported currently

https://github.com/louislam/uptime-kuma/issues/799

**Comment by lengmiguel** [comment]
> Actualmente no es compatible
> 
> [N.º 799](https://github.com/louislam/uptime-kuma/issues/799)

Thank You
