### ISSUE TITLE
where is the rest api document of platform ? 

### ISSUE THREAD

**Issue by neginsadeghi** [louislam/uptime-kuma#888]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

I want to develop a new ui for some specefic features of your platform and in-order to do such I need document of the rest api and the rest api itself, is there any rest api for this platform ? 

thanks for your help

### 🐻 Uptime-Kuma Version

1.10.0

### 💻 Operating System and Arch

Ubuntu 20

### 🌐 Browser

Chrome

### 🐋 Docker Version

20

### 🟩 NodeJS Version

14.18

**Comment by louislam** [comment]
No api. #118
