### ISSUE TITLE
update timeouts

### ISSUE THREAD

**Issue by wolfman2g1** [louislam/uptime-kuma#889]
### Reproduction steps
 HTTP monitors with high latency will always time out. Says it timed out after 4800ms but in reality, it's basically instant though
### Expected behavior
I should be able to set a timeout on a monitor level to account for this, in some cases, I expect latency as high as 4 seconds in certain cases due to the location of the servers

 ### Actual Behavior
Servers with high latency immediately timeout

### Uptime-Kuma version
1.10.0

computer Operating System
Kubernetes 1.18

###  Browser
Any
 
### Docker
N/A

### Docker Image Tag
louislam/uptime-kuma:1

### NodeJS Version
N/A

 ### Relevant log output
Failing: timeout of 48000ms exceeded | Interval: 60 seconds | Type: http
 ### Security Policy
 I agree to have read this project Security Policy

**Comment by chakflying** [comment]
The default timeout should be 48 seconds for 60 seconds interval, so you might be facing another problem.

But this was also a known issue, I have been thinking about having a "warning latency" and "timeout latency", but haven't got around to implementing it.

**Comment by ionutvi** [comment]
I've been facing this problem. Do you have some advice to solve this type of errors? Thanks!

**Comment by lenusch** [comment]
I have same Problems. In my Case i use it for mailflow / Roundtrip Check. 
I need higher Timeout (1-2 mins). Is that possible?

**Comment by lenusch** [comment]
Anything?

**Comment by pdomineaux** [comment]
Hello, any update on this issue. I'm facing the same problem.
The two wordpress websites that I'm monitoring with uptime-kuma are marked as up but half of the request are in "timeout of 48000ms exceeded" status.
**By the way, thanks for your work on that awesome tool.**

**Comment by zenyr** [comment]
btw: #2142 would allow you to specify timeout milliseconds but still awaiting merge. 😅

Use my repo if you really need to.

**Comment by benisdev-py** [comment]
Any thing? I want to set the Timeout to like 80 secs. or like this and in this time the service should be displayed as online.
