### ISSUE TITLE
Webhook is not working

### ISSUE THREAD

**Issue by qingfengfenga** [louislam/uptime-kuma#890]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

I tried sending notifications via email, and it works very well. But I tried for a long time, Webhook has not been able to work properly, I can't find the documentation and examples

I use the Webhook method to test the Webhook addresses of the group robots of Wecom and DingDing, but none of them work

Also, I don’t see any related log output to tell me the error

### 🐻 Uptime-Kuma Version

1.10.0

### 💻 Operating System and Arch

centos7

### 🌐 Browser

chrome

### 🐋 Docker Version

docker 20.10.6

### 🟩 NodeJS Version

14.18.0

**Comment by louislam** [comment]
Webhook is not using in this way. Webhook is usually for developers who want to integrate with their applications. 

DingDing should be already support. For Wecom, you have to wait someone to implement it.

**Comment by qingfengfenga** [comment]
alright, thank you very much. We will try to support Wecom if possible
