### ISSUE TITLE
Update 1.10.1 

### ISSUE THREAD

**Issue by lengmiguel** [louislam/uptime-kuma#893]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [x] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

Good morning when I want to update according to the steps it indicates the following error: error: pathspec '1.10.1' did not match any file (s) known to git

![image](https://user-images.githubusercontent.com/22181854/140754092-229ec4fa-535b-432d-89cb-f88562719c86.png)

### 🐻 Uptime-Kuma Version

1.10.0

### 💻 Operating System and Arch

CENTOS 8

### 🌐 Browser

Google Chrome 95.0.4638.69

### 🟩 NodeJS Version

14.18.1

**Comment by louislam** [comment]
Fixed, I recreated the 1.10.1 tag and it is working now.

Run `git fetch --all` again.

**Comment by lengmiguel** [comment]
> Fixed, I recreated the 1.10.1 tag and it is working now.
> 
> Run `git fetch --all` again.

Thanks for the help
