### ISSUE TITLE
Database

### ISSUE THREAD

**Issue by capriciousduck** [louislam/uptime-kuma#894]
Is it possible to store app data in a database?

**Comment by louislam** [comment]
It is using SQLite.

If you are asking MySQL. It is not supported

**Comment by capriciousduck** [comment]
Ok.

**Comment by suhas-parvathakkal-rudresh** [comment]
@capriciousduck Any plans on adding MySQL support (for storing app data) ?

**Comment by CommanderStorm** [comment]
> @ louislam Any plans on adding MySQL support (for storing app data) ?

https://github.com/louislam/uptime-kuma/pull/3017
