### ISSUE TITLE
Multiple status page

### ISSUE THREAD

**Issue by Dhy19971** [louislam/uptime-kuma#896]
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

Other

### 🔖 Feature description

It would be very useful if it were possible to create different status pages if you need to create dedicated status pages.

Instead of being able to use only one status page.

### ✔️ Solution

Give the possibility to create more status pages reachable through different addresses.

Example:

http://192.168.178.52:3001/status1

http://192.168.178.52:3001/status2

**Comment by louislam** [comment]
Duplicate

**Comment by smirek1** [comment]
Hi, I will also be happy for the multi status page.
