### ISSUE TITLE
No option for UDP port check

### ISSUE THREAD

**Issue by 0mni** [louislam/uptime-kuma#9]
Would love to have a UDP port check.

**Comment by louislam** [comment]
I cannot find a suitable node.js library can do that. I guess UDP port checking is not possible technically.

**Comment by 0mni** [comment]
I did some checking on how statping is able to check, it seems to follow the same process as UDP, will do some quick tests.

Also did some quick googling, its not always possible apparently, can get false positives depending on how the firewall is configured.

https://stackoverflow.com/questions/9265669/how-to-test-a-remote-udp-port/9265820#9265820

**Comment by 0mni** [comment]
I just checked on my statping server, the check it does, does not work at all ... took down openvpn and it didn't register a change at all.

**Comment by louislam** [comment]
> I just checked on my statping server, the check it does, does not work at all ... took down openvpn and it didn't register a change at all.

Yes, UDP monitoring is not 100% reliable according to your stackoverflow link and my research. So I marked this issue as "wontfix"

**Comment by 0mni** [comment]
Yah, probably not worth spending time on it, but will keep it in the back of my mind, maybe a solution will present it self for specific services, such as Openvpn?

**Comment by choffmeister** [comment]
Ah, then I misread your comment

> I cannot find a suitable node.js library can do that. I guess UDP port checking is not possible technically.

I understood, that there is no UDP API. But you meant there is no way to check if an UDP packet arrived. My bad :smile:

**Comment by Medath** [comment]
Measuring the uptime of (some) UDP based services is definitely possible, but it's not as simple as just picking a hostname and a port.

What's necessary is the ability to specify a hardcoded UDP payload that should be sent in the packet. If we receive a response to that packet it means the service is up, if there was no response after a timeout it's down. Similar to the HTTPS Keyword monitor the UDP monitor could also check for specific byte sequences in the response.

Using Teamspeak3 as example, sending `\x54\x53\x33\x49\x4e\x49\x54\x31\x00\x65\x00\x00\x88\x0e\xdc\x3a\xe6\x00\x61\xd3\x7f\x2c\x2b\x73\x10\xd8\x00\x00\x00\x00\x00\x00\x00\x00` to a Teamspeak3 server will cause a response immediately. I took that byte sequence from a Wireshark capture when connecting to a Teamspeak3 server. This approach works for many game servers too.

It wouldn't be very clean and it wouldn't cover *all* UDP based applications, but it would be nice to have

**Comment by Khord** [comment]
How about netcat?

https://www.npmjs.com/package/netcat

```
❯ nc -vu vpn.example.com 1194
Connection to vpn.example 1194 port [udp/openvpn] succeeded!
```

**Comment by Medath** [comment]
netcat can indeed in some cases detect if something is not listening on a udp port.

Depending on the system configuration, some end systems respond with an icmp packet if they receive a udp packet on an unavailable port to signal an error. If this happens, netcat just exits with no output and it can be safely interpreted as a service being down.
However, many systems are configured not to send these icmp error messages. In that case netcat will just always say the connection succeeded, even when nothing is actually listening on that port. `nc -vu example.com 1` will "succeed" just like `nc -vu example.com 12345`. Even when your server is entirely offline or doesn't exist, netcat will say the connection succeeded `nc -vu 192.123.123.123 1234`.

**Comment by MadWalnut** [comment]
@choffmeister Since TeamSpeak has been mentioned in this issue I wanted to share my workaround. Instead of checking the main TS3 port I setup Uptime Kuma to check the ServerQuery ports on 10011 or 10022. These are TCP. Of course those have to be open on the firewall, but maybe it works for you.

**Comment by hexxone** [comment]
FYI, if the ServerQuery ports are not available (in my case), you might have luck with the "FileTransfer" Port `30033` instead.
In the ts3 docs it is listed as "required", so most servers should technically expose it.
Cheers.

**Comment by FrancYescO** [comment]
What about to implement something like 
https://serverfault.com/questions/262474/how-to-check-that-an-openvpn-server-is-listening-on-a-remote-port-without-using

for UDP servers that give specific response on a specific payload?

**Comment by CommanderStorm** [comment]
> <img alt="" width="300" src="https://user-images.githubusercontent.com/1336778/136912486-5248e42f-2ff7-434f-aab9-566fd1190b55.png">
> 
> The problem is that UDP server can ignore Uptime Kuma's request like the picture of above meme. Uptime Kuma never know what should be sent in order to get a response from a UDP server.

@addohm 
I don't see how what you want is technically possible.
What you likely want is really custom
=> using the push monitor is likely a better usecase.

If it can be demonstrated that our assumptions about UDP not being a reliable monitor are wrong, we can talk about how. Currently, I don't see how any protocol via UDP can meet the reliability needs of an uptime monitor. (how would we know something is `DOWN`? UDP does not have packets that need to be send back..)

**Comment by FrancYescO** [comment]
@CommanderStorm like in my example, there are services (and we want to monitor services not the "naked" UDP protocol...) that give some kind of reply (see OpenVPN example..)

If sometime the ack from the service is lost due to the unreliable UDP protocol is up to the user to adjust the already-here retry parameters 

ie. Also DNS monitor is using UDP Transport but we have a specific monitor for it...

**Comment by chakflying** [comment]
Then you would implement a monitor specifically for those services, instead of just UDP.

A UDP monitor is basically meaningless, since there is nothing to monitor.

**Comment by krot4u** [comment]
And no one nows about [Gatus](https://github.com/TwiN/gatus)?
The UDP check works fine there...

**Comment by CommanderStorm** [comment]
https://github.com/TwiN/gatus/blob/master/client%2Fclient.go#L88-L95

This is how they monitor UDP
=> they don't monitor UDP, but rather look at if the socket they try to connect to accepts their connection as far as I can see

**Comment by jordantrizz** [comment]
> https://github.com/TwiN/gatus/blob/master/client%2Fclient.go#L88-L95
> 
> This is how they monitor UDP => they don't monitor UDP, but rather look at if the socket they try to connect to accepts their connection as far as I can see

Wouldn't that be enough?
