### ISSUE TITLE
Https monitor shows down when its up

### ISSUE THREAD

**Issue by hkpanchani** [louislam/uptime-kuma#90]
My Server is up and it still shows monitor down..
unable to verify the first certificate

**Comment by rezzorix** [comment]
Can you give some more details?

**Comment by hkpanchani** [comment]
What exactly do you need.?? The error message is only that

**Comment by rezzorix** [comment]
What certificate are you using with your server?
Self-signed? Anything with an odd CA?

**Comment by louislam** [comment]
It is expected error if your didn't include ca-bundle in your website's web server.

If the website is using nginx, you need to concat the ca-bundle to your cert.
You can read this: https://gist.github.com/singhabhinav/132b8196abac026b43fa

**Comment by hkpanchani** [comment]
lets encrypt cert.. As i said works perfectly with uptime robot..
I am an devops engineer. I can understand the code.. So if there are log fle or console messages lets check on it..

**Comment by hkpanchani** [comment]
> It is expected error if your didn't include ca-bundle in your website's web server.
> 
> If the website is using nginx, you need to concat the ca-bundle to your cert.
> You can read this: https://gist.github.com/singhabhinav/132b8196abac026b43fa

I am using apache2 as reverse proxy. And have installed certificate with certbot and works perfect all other monitoring tools..
Any other suggestions?

**Comment by louislam** [comment]
> > It is expected error if your didn't include ca-bundle in your website's web server.
> > If the website is using nginx, you need to concat the ca-bundle to your cert.
> > You can read this: https://gist.github.com/singhabhinav/132b8196abac026b43fa
> 
> I am using apache2 as reverse proxy. And have installed certificate with certbot and works perfect all other monitoring tools..
> Any other suggestions?

Yes, it is ca problem on your website. Your website probably is not working on all browsers. 

If you are using certbot, using fullchain.pem can solve the problem.

![image](https://user-images.githubusercontent.com/1336778/126429336-a6210c78-605b-438d-91d8-b697b52d9be9.png)

**Comment by louislam** [comment]
"unable to verify the first certificate" is ssl error from axios. Before http error, so there is no code.

**Comment by hkpanchani** [comment]
I am using 
privkey.pem
cert.pem
chain.pem currently..

Shall I replace cert.pem with fullchain.pem?

**Comment by hkpanchani** [comment]
Adding `SSLCertificateChainFile` in apacheproxy solved the errror

**Comment by louislam** [comment]
> Adding `SSLCertificateChainFile` in apache proxy solved the errror

Glad that Uptime Kuma helped you to find a potential problem which other monitoring tools do not :)
