### ISSUE TITLE
How to monitor sites under nginx basic auth?

### ISSUE THREAD

**Issue by Horuyuki** [louislam/uptime-kuma#901]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

I have some sites that is protected with nginx proxy manager, and uptimekuma shows that they are down.

Is there a way to bypass that or a way to directly monitor if the systemd service is running properly?

### 🐻 Uptime-Kuma Version

1.10.0

### 💻 Operating System and Arch

Ubuntu 20.04

### 🌐 Browser

Firefox

### 🐋 Docker Version

Compose 3.3

### 🟩 NodeJS Version

Don't know

**Comment by fcqpl** [comment]
You can set headers for HTTP request:
https://en.wikipedia.org/wiki/Basic_access_authentication#Client_side
![image](https://user-images.githubusercontent.com/46460263/141033760-c377ba09-6742-4caa-acf3-6879a92a8479.png)

**Comment by louislam** [comment]
Duplicate of #768
