### ISSUE TITLE
Loginpage on IP is working but at the domain it gives an error

### ISSUE THREAD

**Issue by mrcsdl** [louislam/uptime-kuma#903]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

Hey when i try to open the Loginpage via 
https://xxxx/dashboard it gives me the error
Cannot connect to the socket server. [Error: websocket error] Reconnecting...

when i try it with the specific ip like http://88.218.227.72:3001/dashboard its working fine.
Can you help me with that?

### 🐻 Uptime-Kuma Version

1.10.2

### 💻 Operating System and Arch

Docker / debian10

### 🌐 Browser

Chrome latest update / Edge latest update

### 🐋 Docker Version

Docker version 20.10.10

### 🟩 NodeJS Version

i dont really know where i can find this

**Comment by louislam** [comment]
Did you search `reverse proxy in this repo`?
