### ISSUE TITLE
window.webkitStorageInfo is deprecated and can be easily replaced

### ISSUE THREAD

**Issue by Goro2030** [louislam/uptime-kuma#904]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### Description

An audit on my uptime website, thrown this:

```
Deprecation / Warning | Source

'window.webkitStorageInfo' is deprecated. Please use 'navigator.webkitTemporaryStorage' or 'navigator.webkitPersistentStorage' instead. | …scripts/invisible.js:1:5162


```

2nd warning is :

```
URL | Map URL

/assets/vendor.66254805.js(uptime.achicrip.org) |  
Large JavaScript file is missing a source map


```

### 👟 Reproduction steps

Run a web Page quality report, using https://web.dev/measure/ on your uptime-kuma site.

### 👀 Expected behavior

All API's should be bumped up to the latest version

### 😓 Actual Behavior

Recommendation is thrown

### 🐻 Uptime-Kuma Version

louislam/uptime-kuma            latest    957e1ceb8ac4   4 weeks ago    323MB

### 💻 Operating System and Arch

ubuntu Impish

### 🌐 Browser

Edge latest

### 🐋 Docker Version

Docker latest

**Comment by louislam** [comment]
Doesn't seems to be a bug.

And this project do not use window.webkitStorageInfo, I believe that it is used by one of the libraries. If you find which libraries, just report to them.
