### ISSUE TITLE
Some errors and issues with updating/editing monitors

### ISSUE THREAD

**Issue by cien-fuegos** [louislam/uptime-kuma#905]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

I have 182 monitors. I keep getting an error I have seen a time or two when searchin
![Knex: Timeout](https://user-images.githubusercontent.com/92477134/141157489-f3318b52-d0bb-45f7-9eea-8cac367c97c9.png)

I'm wondering if the Knex timeout could be due to low memory/resources allocated to the AWS instance I'm using? But when I use top to see what is going on I don't get higher than 65% most of the time. 

I also got a different error today when attempting to edit a monitor:

![2021-11-10 10_29_30-Uptime Kuma](https://user-images.githubusercontent.com/92477134/141157760-9c85016c-0e57-42e0-b130-cf617d440620.png)

I've gotten a couple different errors lately. I was getting very long load times and not finding any monitors at all when loading but that seems to have been resolved. I just occasionally get the Knex error and now getting that other error when attempting to edit one. 

I still have several monitors that are in an Unknown state and I can't pause them because I get an error. I've tried to find the error logs but cannot seem to find the correct path. 

### 🐻 Uptime-Kuma Version

Version: 1.10.1

### 💻 Operating System and Arch

Deep Learning AMI (Ubuntu 18.04) Version 50.0

### 🌐 Browser

Chrome

### 🐋 Docker Version

3.3

**Comment by louislam** [comment]
I think the db is too busy

Check the system load average by `top` command.

**Comment by cien-fuegos** [comment]
![Top](https://user-images.githubusercontent.com/92477134/141162983-7bf2139b-eace-4861-a2e4-65067ab73c3c.png)
