### ISSUE TITLE
Shorter slack notifications

### ISSUE THREAD

**Issue by streamthing** [louislam/uptime-kuma#907]
Could you make shorter notifications for slack?
If more things goes down, uptimekuma makes too much spam in channel.

Look at uptimerobot notifications:
![obraz](https://user-images.githubusercontent.com/90110072/141213304-29791840-5b6c-496b-bbc3-ba5fc991204f.png)

**Comment by deefdragon** [comment]
I'm working on letting the notifications allow templates in #646. This would allow you to shorten/lengthen the message as you see fit, but it is a lot of work, and reliant on a lot of testing. It will, in the best case, but quite some time until they are implemented across the board.

**Comment by xeruf** [comment]
@deefdragon @streamthing how do they currently look for you in Slack? I only get `Uptime Kuma Alert: MONITOR_NAME` which does not even communicate the up/down status, is that correct?

**Comment by streamthing** [comment]
UptimeKuma vs UptimeRobot on Slack:
![slack_W3qt0RzvDh](https://user-images.githubusercontent.com/90110072/161067592-d6c828b8-78a9-4e0c-9bbb-58f178451b3f.png)
![slack_TnZroCdojD](https://user-images.githubusercontent.com/90110072/161067597-829e6be6-63b1-4fe6-a4a9-d5cedd5c839e.png)
