### ISSUE TITLE
Uptime-Kuma API to add services monitoring

### ISSUE THREAD

**Issue by DerLinkman** [louislam/uptime-kuma#909]
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [x] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

API

### 🔖 Feature description

An API which can be used by docker services to add themselves to the status dashboard. (Or maybe docker flags?)
(For example a complete mailstack built in docker).

### ✔️ Solution

Docker Services will add themselves during the initial initialisation (or boot) of uptime-kuma via the API.
Plus the option to automatically add them to the status dashboard after added via API.

### ❓ Alternatives

Manually add them to the monitoring and the dashboard

**Comment by louislam** [comment]
Duplicate

**Comment by pbdco** [comment]
Check out this repo! https://github.com/MedAziz11/Uptime-Kuma-Web-API

**Comment by gaby** [comment]
https://github.com/lucasheld/uptime-kuma-api
