### ISSUE TITLE
Setting up Line Messenger (Notification) Error 400

### ISSUE THREAD

**Issue by adamh2021** [louislam/uptime-kuma#913]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

When attempting to setup Line Messenger, I have been receiving the following error:

`Error: Error: Request failed with status code 400 {"message":"The property, 'to', in the request body is invalid (line:-, column:-)"}`

I have check the API setup and that's correct. Anyone else come across this issue?

### 🐻 Uptime-Kuma Version

1.10.2

### 💻 Operating System and Arch

Ubuntu 20.04

### 🌐 Browser

Chrome

**Comment by suminb** [comment]
I'm having the same issue. Any progress on this?

**Comment by CommanderStorm** [comment]
No, there has not been a PR to adress any defects in the line messanger or its documentation.
I don't have this messanger set up => cannot currently test it
From the error message, it seems like your `lineUserID` is invalid

See our contribution guide here: https://github.com/louislam/uptime-kuma/blob/5b6522a54edad9737fccf195f9eaa25c6fb9d0f6/CONTRIBUTING.md

@Ponkhy this notification provider [was introduced by you](https://github.com/louislam/uptime-kuma/pull/227). This has now moved to https://github.com/louislam/uptime-kuma/blob/master/server/notification-providers/line.js 
Do you have any clues why this is failing?

**Comment by chakflying** [comment]
- Looks like an outage was reported recently for the Line API ([source](https://api.line-status.info/))
- The `to` property is used to set the receipant of the message. Maybe you can check Line's [API documentation](https://developers.line.biz/en/reference/messaging-api/#send-push-message-request-body) to see if you have set the value correctly.
