### ISSUE TITLE
Allow running uptime-kuma without websockets

### ISSUE THREAD

**Issue by wummel** [louislam/uptime-kuma#914]
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

UI Feature

### 🔖 Feature description

The GUI explicitely removes the polling transport option from socket.io (see [socket.js](https://github.com/louislam/uptime-kuma/blob/daef238a70b8b5bcd3eb7c87f0f657d653894464/src/mixins/socket.js#L71) ).
The default transport options from socket.io are ["polling", "websocket"], socket.js sets it to just ["websocket"].

Is it possible to reenable the polling option?
I'd like to use uptime kuma in an environment where websockets are not allowed.

Thanks 

### ✔️ Solution

I used ["polling", "websocket"] for transport options and was able to install and use uptime-kuma in my environment.

```
diff --git a/src/mixins/socket.js b/src/mixins/socket.js
index affac4f..5994ce3 100644
--- a/src/mixins/socket.js
+++ b/src/mixins/socket.js
@@ -68,7 +68,7 @@ export default {
             }

             socket = io(wsHost, {
-                transports: ["websocket"],
+                transports: ["polling", "websocket"],
             });

             socket.on("info", (info) => {

```

### ❓ Alternatives

I have not found an alternative for my case (running uptime-kuma without websockets), but if there are alternatives I can try them.

**Comment by CommanderStorm** [comment]
Could you open a PR to discuss this change?
In what way would enabling this option as you proposed in the inital description be breaking?
Why do you disable `websocket` in the comment?

**Comment by CommanderStorm** [comment]
resolved since https://github.com/louislam/uptime-kuma/pull/4216

**Comment by 250king** [comment]
Well, I have this problem because my website host isn't no allow websocket. Are there any solution to disable the websockets?
