### ISSUE TITLE
Support telegram proxy configuration items

### ISSUE THREAD

**Issue by vfiee** [louislam/uptime-kuma#915]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

telegram proxy configuration

### 🐻 Uptime-Kuma Version

1.10.2

### 💻 Operating System and Arch

Ubuntu 20

### 🌐 Browser

Google Chrome

### 🐋 Docker Version

Docker version 20.10.5, build 55c4c88

**Comment by deefdragon** [comment]
Can you please expand on what you are requesting? Potentially with a link to an API or example?

**Comment by VFiee** [comment]
My service is deployed in an area where the telegram service cannot be accessed without proxy configuration. Telegram notification cannot be reached. Can I access the telegram api by configuring proxy server

![image](https://user-images.githubusercontent.com/42051272/142708852-e2c7fa50-e66a-485e-8479-17561eda6d10.png)

**Comment by deefdragon** [comment]
Interesting problem. I think proxy configuration is likely going to be something that should probably be available for all (minus email) notifications. It may be possible to reuse much of the code&work in #840 (proxies for monitors) for notifications as well.

**Comment by ugurerkan** [comment]
Agree, we are able to accomplish notification to proxy relation and implement to any axios request. 
There is a [`createAgents` method](https://github.com/louislam/uptime-kuma/blob/61606650ae360e942ecd378a9311d91a49ed898d/server/proxy.js#L93) for the creation of HTTP and HTTPS agents with a given proxy entity.  Proxy entities are independent of monitors, so can be related to different objects as well.

```js
const { Proxy } = require("proxy"); 
// https://github.com/louislam/uptime-kuma/blob/61606650ae360e942ecd378a9311d91a49ed898d/server/proxy.js

 // axios request options
const options = {};

if (proxy_id) {
    const proxy = await R.load("proxy", proxy_id);

    if (proxy && proxy.active) {
        const { httpAgent, httpsAgent } = Proxy.createAgents(proxy);

        options.proxy = false;
        options.httpAgent = httpAgent;
        options.httpsAgent = httpsAgent;
    }
}

await axios.request(options);
```

**Comment by RuioWolf** [comment]
I have another idea is about to use a custom Telegram API server instead of using a proxy, while proxy may down for network reasons, in this case both monitoring and notification goes down. But using a custom API server can prevent such thing happen, all you need is a properly configured nginx or Cloudflare worker deployed and you are good to go.

**Comment by RuioWolf** [comment]
> I have another idea is about to use a custom Telegram API server instead of using a proxy, while proxy may down for network reasons, in this case both monitoring and notification goes down. But using a custom API server can prevent such thing happen, all you need is a properly configured nginx or Cloudflare worker deployed and you are good to go.

Also, using proxy server may increase monitoring latency. Or maybe we can choose trun proxy server on or off by toggle "use for monitor", "use for notification" switch?

**Comment by cubanitoalex** [comment]
> Hello, I see that it is not just me who is asking for this option in the project, in my work, which is a Hospital, the output is by proxy and I wanted to use this wonderful project but I cannot get the Telegram notifications by proxy.

Well I share with you the solution I found while searching.
1- npm install node-global-proxy --save
2- add in file
#https://github.com/louislam/uptime-kuma/blob/master/server/notification.js
const proxy = require("node-global-proxy").default;

proxy.setConfig("proxy:port");
proxy.start();

and WORKING 100%

**Comment by ebrahimghane** [comment]
I also have the same issue
