### ISSUE TITLE
Lost every config during update

### ISSUE THREAD

**Issue by tuxevil** [louislam/uptime-kuma#918]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

Hi guys, i just followed the update instructions
https://github.com/louislam/uptime-kuma/wiki/%F0%9F%86%99-How-to-Update

And after completing it, it is like a new installation, i had to recreate my admin user, and i lost all my monitors and settings

How can i get my monitors and settings back? Did i missed something?
I have to reconfig everything?

### 🐻 Uptime-Kuma Version

1.10.2

### 💻 Operating System and Arch

Popos 20.10 x86_64

### 🌐 Browser

Google Chrome 95.0.4638.69

### 🐋 Docker Version

Docker version 20.10.2

**Comment by fcqpl** [comment]
You didn't setup volume for data from Uptime Kuma container.

**Comment by tuxevil** [comment]
how can i check that? 
i see only 1 container and only 1 volume

**Comment by tuxevil** [comment]
i just restored my yesterday's backup
what i should do to update it without loosing the config

**Comment by louislam** [comment]
Did you setup volume previously?
Which installation guide did you follow?

You can list volumes by `docker volume ls`.

**Comment by tuxevil** [comment]
i followed this video of technotim
https://www.youtube.com/watch?v=r_A5NKkAqZM

i dont see any volume with that command, just
DRIVER    VOLUME NAME

**Comment by louislam** [comment]
Since technotim is using docker-compose, you should use docker-compose command to update the container.

I think you can check the volume location in docker-compose.yml.

- stop the current container
- cd to docker-composer.yml directory
- `docker-compose up --force-recreate`

More reference: https://github.com/louislam/uptime-kuma/issues/672

**Comment by tuxevil** [comment]
> Since technotim is using docker-compose, you should use docker-compose command to update the container.
> 
> I think you can check the volume location in docker-compose.yml.
> 
> * stop the current container
> * cd to docker-composer.yml directory
> * run `docker-compose up --force-recreate` to update and restart the container
> 
> More reference: #672
> 
> If it is still not working, please post the content of docker-composer.yml

i stopped the container and run your command and got this output
`sudo docker-compose up --force-recreate
Recreating uptime-kuma ... done
Attaching to uptime-kuma
uptime-kuma    | ==> Performing startup jobs and maintenance tasks
uptime-kuma    | ==> Starting application with user 0 group 0
uptime-kuma    | Welcome to Uptime Kuma
uptime-kuma    | Node Env: production
uptime-kuma    | Importing Node libraries
uptime-kuma    | Importing 3rd-party libraries
uptime-kuma    | Importing this project modules
uptime-kuma    | Prepare Notification Providers
uptime-kuma    | Version: 1.8.0
uptime-kuma    | Creating express and socket.io instance
uptime-kuma    | Server Type: HTTP
uptime-kuma    | Data Dir: ./data/
uptime-kuma    | Connecting to Database
uptime-kuma    | SQLite config:
uptime-kuma    | [ { journal_mode: 'wal' } ]
uptime-kuma    | [ { cache_size: -12000 } ]
uptime-kuma    | SQLite Version: 3.36.0
uptime-kuma    | Connected
uptime-kuma    | Your database version: 10
uptime-kuma    | Latest database version: 10
uptime-kuma    | Database no need to patch
uptime-kuma    | Database Patch 2.0 Process
uptime-kuma    | Load JWT secret from database.
uptime-kuma    | Adding route
uptime-kuma    | Adding socket handler
uptime-kuma    | Init the server
uptime-kuma    | Listening on 3001
uptime-kuma    | Monitor #1 'Ricoh': Successful Response: 1 ms | Interval: 120 seconds | Type: ping
uptime-kuma    | Monitor #4 'Ubiquiti APPB': Successful Response: 1 ms | Interval: 120 seconds | Type: ping
uptime-kuma    | Monitor #5 'Espon Sur': Successful Response: 11 ms | Interval: 120 seconds | Type: ping
uptime-kuma    | Monitor #6 'Ubiquiti APPA': Successful Response: 1 ms | Interval: 120 seconds | Type: ping
uptime-kuma    | Monitor #7 'Central Telefonica': Successful Response: 1 ms | Interval: 120 seconds | Type: ping
uptime-kuma    | Monitor #8 'Camara IP 1': Successful Response: 1 ms | Interval: 120 seconds | Type: ping
uptime-kuma    | Monitor #9 'Camara IP 2': Successful Response: 2 ms | Interval: 120 seconds | Type: ping
uptime-kuma    | Monitor #10 'Ubiquiti APSUR': Successful Response: 31 ms | Interval: 120 seconds | Type: ping
uptime-kuma    | Monitor #11 'Enlace Netlife': Successful Response: 2 ms | Interval: 120 seconds | Type: ping
uptime-kuma    | Monitor #12 'Enlace Claro': Successful Response: 10 ms | Interval: 120 seconds | Type: ping
uptime-kuma    | Monitor #13 'Ubiquiti APPA2': Successful Response: 1 ms | Interval: 120 seconds | Type: ping
uptime-kuma    | Monitor #14 'Ubiquiti APMANTA': Successful Response: 8 ms | Interval: 120 seconds | Type: ping
uptime-kuma    | Monitor #16 'Router Sur': Successful Response: 9 ms | Interval: 120 seconds | Type: ping
uptime-kuma    | Monitor #17 'Router Manta': Successful Response: 8 ms | Interval: 120 seconds | Type: ping
uptime-kuma    | Monitor #18 'Epson Manta': Successful Response: 42 ms | Interval: 120 seconds | Type: ping
uptime-kuma    | Monitor #19 'Musica Manta': Successful Response: 10 ms | Interval: 120 seconds | Type: ping
uptime-kuma    | Monitor #15 'Epson Matriz': Failing: PING 192.168.1.8 (192.168.1.8) 56(84) bytes of data.
uptime-kuma    | From 192.168.3.1 icmp_seq=1 Destination Host Unreachable
uptime-kuma    | From 192.168.3.1 icmp_seq=2 Destination Host Unreachable
uptime-kuma    | From 192.168.3.1 icmp_seq=3 Destination Host Unreachable
uptime-kuma    | From 192.168.3.1 icmp_seq=4 Destination Host Unreachable
uptime-kuma    |
uptime-kuma    | --- 192.168.1.8 ping statistics ---
uptime-kuma    | 4 packets transmitted, 0 received, +4 errors, 100% packet loss, time 37ms
uptime-kuma    | pipe 4
uptime-kuma    |  | Interval: 120 seconds | Type: ping
uptime-kuma    | Monitor #20 'Respaldos': Successful Response: 1 ms | Interval: 120 seconds | Type: ping
uptime-kuma    | Monitor #21 'Test Server': Successful Response: 0 ms | Interval: 120 seconds | Type: ping
uptime-kuma    | Monitor #22 'DVR Matriz': Successful Response: 1 ms | Interval: 120 seconds | Type: ping
uptime-kuma    | Monitor #23 'DVR Sur': Successful Response: 9 ms | Interval: 120 seconds | Type: ping
uptime-kuma    | Monitor #24 'DVR Manta': Successful Response: 9 ms | Interval: 120 seconds | Type: ping
uptime-kuma    | Monitor #25 'LMS': Successful Response: 1 ms | Interval: 120 seconds | Type: ping`

on the web gui it still says version 1.8.0 and it seems is not doing anything else than showing me the working status

my docker-compose.yml is this
`---
version: "3.1"

services:
  uptime-kuma:
    image: louislam/uptime-kuma:1
    container_name: uptime-kuma
    volumes:
      - /home/tuxevil/docker_volumnes/uptime-kuma/data:/app/data
    ports:
      - 3001:3001
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
`

**Comment by louislam** [comment]
You can try these answers:
https://stackoverflow.com/questions/49316462/how-to-update-existing-images-with-docker-compose

**Comment by tuxevil** [comment]
thanks, i will try, and if i cant get it working, i already found the data folder with the configs, i will backup and try to install as you said in the readme

thanks

**Comment by tuxevil** [comment]
grear job btw, its an awesome piece of software

**Comment by tuxevil** [comment]
well, i just did the this, and it worked as expected, it is updated to 1.10.2 with all my monitors and settings

docker pull louislam/uptime-kuma:1
docker stop uptime-kuma
docker-compose up -d --force-recreate
