### ISSUE TITLE
Possibly add GitHub Discussions to Repo?

### ISSUE THREAD

**Issue by Spiritreader** [louislam/uptime-kuma#92]
I've seen that there are lots of interested people and also possible contributors. 
For that reason, I think it is possibly beneficial to use the new [GitHub discussion feature](https://docs.github.com/en/discussions/quickstart).

This could be for topics that are not inherently issues, but more for clarification, sharing ideas on design and sketching rough feature ideas.

**Comment by louislam** [comment]
Thank you, I never know it.

**Comment by louislam** [comment]
After tested it for a week, I found out that using "Issues" only is more centralized and it is more well-known for most Github user. So I disabled it again.
