### ISSUE TITLE
Ping sensor working with IP Address not host name

### ISSUE THREAD

**Issue by pakpoom2516** [louislam/uptime-kuma#923]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

I just setting monitoring for the web server. When I set to ping to IP Address (I put it in the host name field). It running with no error. but when I edit the IP Address to host name which already map to dns server, It reported server down.

IP is 27.131.178.177
host name : speedhub.kirz.com

what should I do?

### 🐻 Uptime-Kuma Version

1.9.1

### 💻 Operating System and Arch

Centos 8

### 🌐 Browser

firefox

**Comment by louislam** [comment]
What is the error? I tested in my side, it is working fine.

**Comment by deefdragon** [comment]
This is very likely a DNS problem inside/outside the container. You may be able to verify this by shelling into the container and running a ping the hostname.

**Comment by pakpoom2516** [comment]
Now I manage to work with LXC not docker. It seem that docker is not recognize DNS

**Comment by MarcS1975** [comment]
I have the same issue. Ping works for external IP but not hostname.
