### ISSUE TITLE
Add support for healthcheck heartbeat keep alive type monitor

### ISSUE THREAD

**Issue by ninthwalker** [louislam/uptime-kuma#924]
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

New Monitor

### 🔖 Feature description

If Uptime Kuma goes down, then you don't know if the rest of what it is monitoring goes down. I saw one request for this but he didn't seem to accurately descrive what was wanted. [611](https://github.com/louislam/uptime-kuma/issues/611)

If Uptime Kuma could have an option to ping an external service/endpoint then something else could check that Uptime Kuma is still good. An example of this is that you run Uptime Kuma on your internal network so don't want to open it to the internet. If Uptime Kuma could ping heathchecks.io (one example) then that external monitoring service would know if it goes down.

See this application for reference:
[Chiadog redundant monitor](https://github.com/martomi/chiadog#redundant-monitoring-for-chiadog)

### ✔️ Solution

Add a healthcheck/keep alive/heartbeat type monitor to allow Uptime Kuma the option to ping/post to an endpoint itself.

### ❓ Alternatives

You could run 2 Uptime Kuma. With one looking for the ping of the other. This is similar to what I want, but with not having to selfhost another monitor somewhere else and have it built in.

### 📝 Additional Context

Thanks for your project!

**Comment by zimbres** [comment]
Looks like you already gave a solution, you can create a HTTP Type Monitor pointing to healthchecks.io Ping URL, if Uptime Kuma goes down and stop trying this monitor, healthchecks.io will produce an alert.

**Comment by ninthwalker** [comment]
I'll close this. lol.
I guess I was thinking of it backard, where uptime checks if something is up, which of course emans its doing a call to that service so that service (healthchecks.io in this case) knows that its endpint was hit.
Thanks again!
