### ISSUE TITLE
composed checks

### ISSUE THREAD

**Issue by rubvaz** [louislam/uptime-kuma#929]
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

Other

### 🔖 Feature description

Some applications may need a composed check to have correct a proper operation

### ✔️ Solution

In my case we need that more than one check to have an application working, so if one of the checks is down all the composed check should be done.

**Comment by deefdragon** [comment]
Are you referring to only marking something as up/down based on the combination of the statuses of a group of monitors? Or are you describing having a monitor know that it relies on another monitor, and if that monitor is down, automatically going down?

Regardless, going to reference #468 (216 specifically) as I think this is a duplicate, but if you have more details/believe its not a duplicate, feel free to expand on the problem.
