### ISSUE TITLE
Uptime Kuma show blank screen

### ISSUE THREAD

**Issue by ranrinc** [louislam/uptime-kuma#930]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

UptimeKuma did not show anything just plain blank screen from dashboard and status. Reinstall uptimekuma wont help since setup also shown blank. How could I fixed this?

### 🐻 Uptime-Kuma Version

1.10.2

### 💻 Operating System and Arch

Debian 11

### 🌐 Browser

Google Chrome 96.0.4664.45

### 🐋 Docker Version

20.10.9

**Comment by louislam** [comment]
Are you using a reverse proxy?
If yes, search "reverse proxy" in this repo.

Otherwise, you may need to provide more info that show how you set up it.
