### ISSUE TITLE
no notification via apprise "Join" on android phone

### ISSUE THREAD

**Issue by olvier** [louislam/uptime-kuma#932]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### Description

Tested to send notification to "Join" via apprise
[https://github.com/caronc/apprise/wiki/Notify_join](https://github.com/caronc/apprise/wiki/Notify_join)

Test-message and monitor-changes are sent and arrived at least on my google chrome, MacOS, so its working as expected.
Same URL is working in "[changedetection.io](https://github.com/dgtlmoon/changedetection.io)", too.
And there it arrives the android phone, too. Never had any problems with any devices.

### 👟 Reproduction steps

Add some simple monitor and test via "Join".
Chrome arrives, Android phone not.

### 👀 Expected behavior

Arrive on Android, too ;)

### 😓 Actual Behavior

described before :)

### 🐻 Uptime-Kuma Version

1.10.2

### 💻 Operating System and Arch

docker on raspberry 4

### 🌐 Browser

Chrome :)

**Comment by louislam** [comment]
Please transfer to apprise.

**Comment by novakin** [comment]
Hi, 

Not sure if I should open another issue so i'll comment on this, let me know if it's a mistake. 

Feels like there is an issue with Join notification with uptime-kuma. I don't get the notification if sent via the web interface but a test via docker works fine as bellow: 

```
 docker exec -it uptime-kuma apprise -vv --title 'Agile Joke' \
--body 'Did you see this one yet?' \
--attach https://i.redd.it/my2t4d2fx0u31.jpg \
'join://XXXXXXXXXXX/XXXXXXXXXXX'
```
