### ISSUE TITLE
Any way to reset MFA?

### ISSUE THREAD

**Issue by Giraffaman** [louislam/uptime-kuma#933]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

Phone died and the only backup I'm missing is that of my authenticators - is there any way to reset or disable the admin's MFA config? I'm running uptime-kuma in docker.

I just have a handful of monitors which I can easily rebuild, but saw no documented way for this so I thought I'd ask. 

### 🐻 Uptime-Kuma Version

1.10.2

### 💻 Operating System and Arch

debian 10 x64

### 🌐 Browser

any

**Comment by louislam** [comment]
Good point. There is no reset 2FA currently.

I will get back you soon.

**Comment by louislam** [comment]
Implemented, will be available for the next release. For now, you can temporarily switch to nightly version to use this function.

1. change the docker image to louislam/uptime-kuma:nightly and start the container.
2. `docker exec -it <container name> npm run remove-2fa`
3. change back to louislam/uptime-kuma:1

cc: @sickoo0

**Comment by Giraffaman** [comment]
@louislam this worked perfectly, thank you! The command asks for final confirmation before disabling MFA, then went through successfully. After running this I was able to log back into the dashboard and configure MFA with my new authenticator again.

Thank you for your help.

**Comment by NetworkTest** [comment]
What's the equivalent command to "docker exec -it <container name> npm run remove-2fa" for non-Docker installations?

This is on an Ubuntu 22.04 LTS box, where Uptime Kuma starts with a command like this:

pm2 start npm --name uptime-kuma -- run start-server -- --port=3001 --hostname=127.0.0.1

Thank you!

**Comment by louislam** [comment]
`npm run remove-2fa`

**Comment by NetworkTest** [comment]
Bingo. Worked perfectly when run from the uptime-kuma directory. Thank you!
