### ISSUE TITLE
Password reset

### ISSUE THREAD

**Issue by sickoo0** [louislam/uptime-kuma#936]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

Hi louislam

Nice app you have made :-)

I have reset my password with "docker exec -it uptime-kuma npm run reset-password" but now it aske for token, have can i disable token or reset it ?
![image](https://user-images.githubusercontent.com/11561313/142371373-6e836676-6eee-4f4a-aa41-c60f42bdbd72.png)
 

### 🐻 Uptime-Kuma Version

1.10

### 💻 Operating System and Arch

Ubuntu 20.04

### 🌐 Browser

Chrome

**Comment by louislam** [comment]
Focus on #933
