### ISSUE TITLE
Shared configuration settings ("profiles") between monitors

### ISSUE THREAD

**Issue by etfz** [louislam/uptime-kuma#937]
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

UI Feature, Other

### 🔖 Feature description

Some way to manage settings of multiple monitors using a single profile. So, I guess, Heartbeat interval, Retry count and Retry interval.

### ✔️ Solution

Configuring multiple monitors using the same settings.

**Comment by CommanderStorm** [comment]
I am going to merge this issue with https://github.com/louislam/uptime-kuma/issues/1323 as said proposal is simpler to implement (no tangling of monitors to some different system as suggested here).
Updating montiors should be handled via mechanisms such as proposed in https://github.com/louislam/uptime-kuma/issues/455

=> closing as a duplicate / not planned. If you disagree, lets continune such a discussion in https://github.com/louislam/uptime-kuma/issues/1323 how such a feature should work.
