### ISSUE TITLE
Slack notification failed with status code 400 invalid_blocks

### ISSUE THREAD

**Issue by radespiel** [louislam/uptime-kuma#941]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

i'm not recieving notifications through slack, checking the logs:

"Cannot send notification to Slack Channel
Error: Error: Error: Request failed with status code 400 invalid_blocks"

notifications sended by test button works fine. someone knows what could be?

### 🐻 Uptime-Kuma Version

1.10.2

### 💻 Operating System and Arch

Ubuntu 20.04

### 🌐 Browser

Google Chrome 95.0.4638.69

**Comment by louislam** [comment]
Cannot reproduce, please provide more details.

![image](https://user-images.githubusercontent.com/1336778/142660256-192432cc-8323-4bb6-abd1-d65df17035f7.png)

**Comment by radespiel** [comment]
Sorry for taking so long, apparently my problem was the Primary Base URL without "https://".
