### ISSUE TITLE
Best way to backup/restore data with AWS Elastic Beanstalk deployment

### ISSUE THREAD

**Issue by woozyking** [louislam/uptime-kuma#947]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

We have a bare setup of kuma using the following Dockerfile

```dockerfile
FROM louislam/uptime-kuma

EXPOSE 3001

CMD ["node", "server/server.js"]
```

Which is deployed through AWS Elastic Beanstalk (Docker running on 64bit Amazon Linux 2), roughly depicted by the deployment workflow below

```shell
# init .elasticbeanstalk/config.yml
eb init --platform "Docker running on 64bit Amazon Linux 2" --region "us-east-1" uptime

# select environment
eb use uptime-dev

# deploy app with label, $GITHUB_SHA is the git commit hash supplied by GitHub Actions
eb deploy --label uptime-$GITHUB_SHA
```

Everything works great, with the obvious catch that every time a deployment happens, all past data gets erased, including monitor configs.

What would be the best way to backup and restore the data? Perhaps mounting the data directory on an AWS EFS? Any suggestions and examples are greatly appreciated.

### 🐻 Uptime-Kuma Version

1.9.1

### 💻 Operating System and Arch

Docker running on 64bit Amazon Linux 2

### 🌐 Browser

Firefox 94.0.1

**Comment by louislam** [comment]
Don't make your life complicated, go EC2/VPS without Docker is much easier.

With Docker you can move your container/volume everywhere. With these Amazon things, you are no way to go.

**Comment by woozyking** [comment]
> Don't make your life complicated, go EC2/VPS with Docker is much easier.
> 
> With Docker you can move your container/volume everywhere. With these Amazon things, you are no way to go.

That's fair, though it'd be nice to see if any users attempted and succeeded with a relatively elegant solution (with something like EFS to mount the data directory). We'll keep trying too, and follow up in this thread if we get anywhere.
