### ISSUE TITLE
Help: Get status of service at particular port & GET request

### ISSUE THREAD

**Issue by Naam** [louislam/uptime-kuma#952]
Hello,

I have configured a few sensors on different services, mostly ping. For this one, I'd like to go a bit more in-depth and actually parse a status answer. I've configured my service as such:

![2021-11-23 13_10_38-Window](https://user-images.githubusercontent.com/2959826/143130355-04beae8a-90d0-4ef3-8ead-56971e56aeb8.png)

If I copy-paste the URL in my browser, I can see the JSON reply. This API endpoint shouldn't require any cookies and verified it by clearing them and using the same endpoint with the token to access it.

However, the status in Kuma always shows:
`Down	2021-11-23 13:14:16	timeout of 48000ms exceeded`

Other sensors on the same host are working, I've tried both the local domain name and the IP, which didn't help. I've also tried to move the API key part into the "body" section in a JSON format, try GET and POST, without success.

Any idea?

Thanks

**Comment by Naam** [comment]
Mainly, I could try debugging it further, but I don't know if there is any more logging than the one done in the docker console. It would help if I could access the whole request made and the response received.

**Comment by chakflying** [comment]
Timeout means it didn't receive anything. I think the easiest way to debug is still to open a shell in the uptime-kuma container and run `curl` to see if you can access your service first.

**Comment by Naam** [comment]
Hi @chakflying, thanks for the tip. Should have thought about that, curl wasn't installed by default, and for some reason, I thought I couldn't install it.

As for the experiments went (two last lines are the ones of most interest):

```
root@3b5abe3d5388:/app# curl -v -k -L server:20080 |& grep HTTP
> GET / HTTP/1.1
< HTTP/1.1 302 Found
> GET /web HTTP/1.1
< HTTP/1.1 301 Moved Permanently
> GET /web/ HTTP/1.1
< HTTP/1.1 200 OK
root@3b5abe3d5388:/app# curl -v -k -L server:8080 |& grep HTTP
> GET / HTTP/1.1
< HTTP/1.1 302 Found
* Using HTTP2, server supports multi-use
* Connection state changed (HTTP/2 confirmed)
* Copying HTTP/2 data in stream buffer to connection buffer after upgrade: len=0
> GET / HTTP/2
< HTTP/2 200 
root@3b5abe3d5388:/app# curl -v -k -L server:8989 |& grep HTTP
# hang there doing nothing, I have a bunch of other services that are well alive on other ports that also exhibit this behavior.
```

I've also tried `curl -v telnet://server:8989/` to see if I could reach the port at all but it hangs similarly.
I'm not sure it has anything to do with Kuma, indeed. So I'd appreciate any pointers but am happy with closing this as well if preferred.

Thank you

**Comment by Naam** [comment]
Confirmed, some tweaking in the Docker networks brought back up some services from Kuma's point of view. Sorry for the noise.
