### ISSUE TITLE
Nginx Https 

### ISSUE THREAD

**Issue by LeSchurke** [louislam/uptime-kuma#962]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

I would like to have Kuma with https cert by Nginx Proxy Manager, but i get this message if i use https and my custom URL.
Cannot connect to the socket server. [Error: websocket error] Reconnecting...
![image](https://user-images.githubusercontent.com/79398820/143478349-70998e71-fe77-4b02-9daf-2849ed9164b0.png)

### 🐻 Uptime-Kuma Version

1.10.2

### 💻 Operating System and Arch

Debian 11.1.0

### 🌐 Browser

Google Chrome 96.0.4664.55

**Comment by MrEddX** [comment]
Did you enable the  [Websocket] option in NGINX Proxy manager?

**Comment by LeSchurke** [comment]
> Did you enable the [Websocket] option in NGINX Proxy manager?

perfect, thx!
It works!

**Comment by MrEddX** [comment]
It is a good idea to read the documentation before asking for help by the way. The wiki page is all yours [here](https://github.com/louislam/uptime-kuma/wiki/Reverse-Proxy#nginx-proxy-manager). 😉
