### ISSUE TITLE
Resource/Server monitoring

### ISSUE THREAD

**Issue by znillax34** [louislam/uptime-kuma#964]
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

Other

### 🔖 Feature description

It would be nice to have a Server Monitor etc. like HetrixTools has, where you can view how much resources the server uses.

I have linked to a status page that has this; [https://status.blare.host](https://status.blare.host)

### ✔️ Solution

^^

**Comment by chakflying** [comment]
The resource monitor part is a Duplicate of #819

**Comment by znillax34** [comment]
Oops, didn't notice that
