### ISSUE TITLE
Automatically add Monitors to status page based on tags

### ISSUE THREAD

**Issue by tomasnorre** [louislam/uptime-kuma#965]
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

UI Feature

### 🔖 Feature description

Have a lot of services monitored, it would be helpfull to have new monitors added to the status page automatically based on tags. 

### ✔️ Solution

Given I Have tag "Websites" 
AND I create a new Monitor with Tag "Websites" 
I want to see this automatically on the Status page under the Website Section

**Comment by GeoCookie** [comment]
Hi there,
I'm also very interested in this feature. And maybe add the ability to automatically add monitors based on tag color.

**Comment by handtema** [comment]
I second this request :)

Even if I would prefer to have a configpage where I can chose wich tags should be status pages

**Comment by EDIflyer** [comment]
Great idea - links to #1609 too.
