### ISSUE TITLE
Grid view for the status page

### ISSUE THREAD

**Issue by FabianKielmann** [louislam/uptime-kuma#968]
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

UI Feature

### 🔖 Feature description

We've set up Uptime Kuma in our small IT team and would love to have a separate display for all the soo in the room that displays the status page. But if you have a lot of services on that status page, you soon need to scroll to see the full list. So a grid view would be awesome. Would even consider adding it myself in a fork. Would take me some time though, because I'm not very familiar with vue.

### ✔️ Solution

Add a grid view for the status page and make it an option to switch to.

### ❓ Alternatives

Alternatively you could add something like a "minimal" view for the existing list.

**Comment by CommanderStorm** [comment]
Multi column status pages is tracked in #592

I am going to close this issue as I don't see a difference between the proposals.
We can reopen if there is one that I am missing ^^

=> closing as a duplicate
