### ISSUE TITLE
Subuser

### ISSUE THREAD

**Issue by eliaskyt** [louislam/uptime-kuma#970]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

Hi, 
is it possible to add Administrator-Subuser in Uptime Kuma?
I want to give my System-Administrators Access to the Tool.

Dear Wishes
Elias Krückeberg
EKNetworkHosting.de

### 🐻 Uptime-Kuma Version

1.10.2

### 💻 Operating System and Arch

Debian 10

### 🌐 Browser

Google Chrome 96.0.4664.45 at Windows 11

**Comment by louislam** [comment]
Duplicate of #181
