### ISSUE TITLE
Uptime Kuma Pushover testing successful.

### ISSUE THREAD

**Issue by matthew-larner** [louislam/uptime-kuma#971]
Once a week on a Saturday, I get a push notification to my Pushover notification with content "Uptime Kuma Pushover testing successful.".

1. Where is this configured?
2. How can I turn it off?

Thanks 
Matt

**Comment by louislam** [comment]
It is a bug of current Pushover implementation

It should send you the certificate expiration notification, but it sent a wrong message to you.

**Comment by matthew-larner** [comment]
What certificate is the warning for?
How can I stop this? I've been woken up every Saturday at 6am!

**Comment by louislam** [comment]
1.11.1 should show the correct msg now.

**Comment by matthew-larner** [comment]
@louislam is there any way to turn it off or change the time? It keeps coming at 6am every Saturday and wakes me up.

**Comment by louislam** [comment]
> @louislam is there any way to turn it off or change the time? It keeps coming at 6am every Saturday and wakes me up.

Sorry about that, but there is no option to turn this off.

What kind of cert are you using? Because the warning will be sent only if it closes to be expired.

**Comment by matthew-larner** [comment]
I'm using let's encrypt on Nginx reverse proxy. It would be great if the user could either:
a) turn this feature off
b) choose the time that the notification comes
c) choose which notification type to use (so I could do a low priority one that doesn't wake me up)
