### ISSUE TITLE
Website does not load on iOS device

### ISSUE THREAD

**Issue by simphide** [louislam/uptime-kuma#973]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### Description

The website isn't loading on my iPhone with Safari (iOS 15.1) while it is perfectly loading on my MacBook with Chrome 96.0.4664.55 (macOS 12.0.1)

iOS:
![image](https://user-images.githubusercontent.com/8183517/143674694-b13f703e-2c46-4994-a497-90d435829abb.png)

macOS:
![image](https://user-images.githubusercontent.com/8183517/143674697-f5067af6-3ef3-4f6c-be75-5462e6c0d04f.png)

### 👟 Reproduction steps

Open the website with an iOS Device

### 👀 Expected behavior

The website should load properly

### 😓 Actual Behavior

The website didn't load becasue the server stopped responding.

### 🐻 Uptime-Kuma Version

1.10.2

### 💻 Operating System and Arch

Ubuntu 20.04

### 🌐 Browser

Chrome 96.0.4664.55

### 🐋 Docker Version

20.10.11

### 🟩 NodeJS Version

-

### 📝 Relevant log output

```shell
Nothing useful in the logs.
```

**Comment by louislam** [comment]
Sounds like it is your network issue.
