### ISSUE TITLE
Auto update the status page

### ISSUE THREAD

**Issue by the-lazy-fox** [louislam/uptime-kuma#978]
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

UI Feature

### 🔖 Feature description

I have noticed that the status page main service status section is not automatically refreshed if something is going on.
It still displays "All Systems Operational" until you hit F5.

### ✔️ Solution

It will be great to have an event based system to refresh this section is something is happening and trigger a browser tab "update alert" with the favicon changing like on your email client when a new email arrived.

### ❓ Alternatives

Otherwise at least refresh this section every x seconds

**Comment by TONYRSL** [comment]
I use firefox module " Tab auto refresh " for this. 
Mais oui, ce serais bien d'avoir une actualisation automatique.

**Comment by scottmando2000** [comment]
I also think having a auto updating status page would be good, means I wouldn't have to stay on the dashboard page or my discord channel constantly.

**Comment by stijn-stadium** [comment]
I would also love to see this built-in.
Meanwhile I'm also resorting to a browser extension to make it work for me.

**Comment by Salamafet** [comment]
I think this function already exist:
https://github.com/louislam/uptime-kuma/blob/db3ef3805b1d9152820ada6ff63f3ca994e85c32/src/pages/StatusPage.vue#L556-L560

I watched the status-page and an automatic request is sent every 5 minutes. However, I don't know if the page content is modified if a service goes down.
If this is the case, maybe an option for changing the Heartbeat interval.

**Comment by gutocarvalho** [comment]
Auto refresh is a pleasant feature, I'm using firefox autorefesh too.

Perhaps autofresh with a configuration on settings to define the refresh time that you want in seconds.

Another good thing is to have a timestamp of the last refresh on top of the page, with that we'll known that the refresh is working.

**Comment by gaby** [comment]
Related: https://github.com/louislam/uptime-kuma/issues/1316 https://github.com/louislam/uptime-kuma/issues/546

**Comment by mrforsythexeter** [comment]
This feels like a really important feature to add to the settings

**Comment by MrRyanM** [comment]
I agree that this would be great to have. Thanks

**Comment by louislam** [comment]
Just closed several duplicated feature requests. I reply all here.

As [Salamafet](https://github.com/Salamafet) said, auto-refresh is already existing, but I agree it is not clear though.

As status page is using normal REST API and it not using WebSocket, it cannot be so reactive like in the dashboard.

The reason for using REST API is that it can handle many users to view the page.

But I think we can improve this by:
- Display next refresh countdown
- Ability to set the refresh interval

**Comment by T3uZ** [comment]
> Acabei de fechar várias solicitações de recursos duplicados. Eu respondo tudo aqui.
> 
> Como disse [Salamafet](https://github.com/Salamafet) , a atualização automática já existe, mas concordo que não está claro.
> 
> Como a página de status está usando a API REST normal e não usando WebSocket, ela não pode ser tão reativa como no painel.
> 
> A razão para usar a API REST é que ela pode lidar com muitos usuários para visualizar a página.
> 
> Mas acho que podemos melhorar isso:
> 
> * Exibir contagem regressiva da próxima atualização
> * Capacidade de definir o intervalo de atualização

Olá, não sei se ja teve sucesso nessa atualização, conseguiu fazer essa melhora?

**Comment by TonyGaspro** [comment]
> Ability to set the refresh interval

This would be fantastic in the settings section. Thanks for your hard work on this.

**Comment by chakflying** [comment]
Closing this in favor of #3103, since this feature already exist, and the only remaining problem is specifically related to that issue.

**Comment by kPKfQKhuz86** [comment]
hey @louislam @chakflying ,

first of all, I love the project, and thank you very much for it. I do appreciate all the people's time involved in it. It's the best tool for the job its doing :)

Please take into consideration the fact the the current refresh method does not update the page when the following happens:

- monitor is added / removed
- incident is created for a dashboard

In both cases, actual page reload needs to happen (at the time of writing). Harshly speaking, I hardly see any value in current method of a refresh every X minutes for monitors retrieved during the dashboard load. It doesn't show incidents once we create them, and this is the most crucial information for our team (as we have a TV always displaying the dashboard).

We have to reload the page every X minutes to have the incident actually reflected on the dashboard (which is "always" displayed vs periodically accessed).

I don't know how to implement it, but I wanted to give you the feedback regarding this specific feature.

Auto refresh of tab done in the browser does the job, but I was thinking that maybe a simple switch when editing the dashboard would be beneficial:

> `Hard refresh` vs `Soft refresh`

- Hard refresh - does hard reload / refresh of the page
- Soft refresh - does this API call to retrieve information for monitors which are loaded when dashboard page is retrieved

All in all, the current refresh method doesn't build a trust that it will relay all necessary information (incident, monitor changes).

Best
