### ISSUE TITLE
Restrict IP for Admin Portal 

### ISSUE THREAD

**Issue by malaniarpit** [louislam/uptime-kuma#979]
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

API, UI Feature

### 🔖 Feature description

It would be really nice to restrict Admin Portal with specific IP and Status Page is accessible over the public internet.

### ✔️ Solution

I can think of one of two solutions:

1) The server can selectively drop requests based on IP Addresses.
2) Ability to run uptime-Kuma containers in two-mode where the first one will be Admin/Writer (Restricted IP) and the other mode will be reader mode(No IP Restriction). The assumption is that there is a common DB/NFS or EFS Filesystem.

### 📝 Additional Context

This will help reduce any potential security issues.

**Comment by deefdragon** [comment]
This is likely better handled by a reverse proxy hosting UK.

**Comment by rihards-simanovics** [comment]
I'm pretty sure you can achieve this by providing specific Nginx/Apache commands in a config file to block access to particular pages. I never saw the need for that though, as you got a 2fa feature that on its own is a good enough deterrent from trying to hack the site. Though I understand that everyone has different needs so perhaps a good feature for the future?

**Comment by malaniarpit** [comment]
@rihards-simanovics You are right we can rely on 2FA as a good enough deterrent from hacking.
