### ISSUE TITLE
Multiple docker instances problem

### ISSUE THREAD

**Issue by Skyfay** [louislam/uptime-kuma#982]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

I want to install several docker containers with uptime-kuma.
But if I set the port from e.g. 3001:3001 to 3002:3002, then the container can no longer be reached.
How can I get this to work?

Thanks for help, i like this project!

### 🐻 Uptime-Kuma Version

1.10.2

### 💻 Operating System and Arch

Ubuntu 20.04

### 🌐 Browser

Google Chrome

### 🐋 Docker Version

version 20.10.7, build 20.10.7-0ubuntu5~20.04.2

### 🟩 NodeJS Version

v16.13.0

**Comment by Skyfay** [comment]
> 3001:3001 3002:3001 3003:3001

I've already thought about that.
But does it really work if they all point to the same docker internal port?

**Comment by gaby** [comment]
> > 3001:3001 3002:3001 3003:3001
> 
> I've already thought about that. But does it really work if they all point to the same docker internal port?

Yes, that's the magic of port forwarding.

**Comment by Skyfay** [comment]
> Yes, that's the magic of port forwarding.

Okey ...
I just don't understand how this is technically possible because with normal port forwarding only one port can be used at a time.
Thanks in advance then I'll do it that way :)

**Comment by Elkhunder** [comment]
You can think of it like forwarding from a router to multiple computers.  Each computer is unaware of the internal ports on other computers.  The router can then specify different ports for forwarding data to the same ports on different devices.  The containers are unaware of the internal ports of other containers.

**Comment by Skyfay** [comment]
> You can think of it like forwarding from a router to multiple computers. Each computer is unaware of the internal ports on other computers. The router can then specify different ports for forwarding data to the same ports on different devices. The containers are unaware of the internal ports of other containers.

So does every docker container has his own network range?

**Comment by louislam** [comment]
Docker container looks a bit like a virtual machine. Each machine is able to open 3001 port.
 
If you want to learn more, you should check more online material like this: https://stackoverflow.com/questions/55192991/multiple-docker-containers-with-same-container-port-connected-to-the-same-networ/55202766

**Comment by Skyfay** [comment]
> Docker container looks a bit like a virtual machine. Each machine is able to open 3001 port.

Allright, I did not know that.
That's really interesting to know.
that makes docker even more attractive for me.

Thanks for your help and patience!

**Comment by rezzorix** [comment]
This can be closed 🔐
