### ISSUE TITLE
Duplicati "HTTP Report Url"

### ISSUE THREAD

**Issue by mcfrojd** [louislam/uptime-kuma#987]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

I used to use duplicati's "HTTP Report Url" advanced add-on to send a "push" to my self hosted "healthchecks" service.
It was a simmilar "ping" url as the ones you can use with uptime-kuma "push" monitor type.

But when i try to use a uptime-kuma push-url i get a error message in duplicati saying:

`30 nov 2021 11:31: HTTP Response: 404 - Not Found: <!DOCTYPE html> <html lang="en"> <head> <meta charset="utf-8"> <title>Error</title> <script async src='/cdn-cgi/challenge-platform/h/b/scripts/invisible.js'></script></head> <body> <pre>Cannot POST /api/push/DKUODSY1z5</pre> <script type="text/javascript">(function(){window['__CF$cv$params']={r:'6b63680f1c287276',m:'_ilPVQGPLo0_ONFU6vWg3iWf.RANAXfP81EycIBeD1w-1638268290-0-AZQYNVJFbdxnspfntkHZoNF+FPZU7yxjbxbm4tMSdqPHGrW2OpwigVGzBkjn4XKavyEQK7XOrzx7VzvbEVMiQ6yAumE7W62K97pRazkqMkYgvOgBEb/XCVvdShGlqLA2cSa+21uogq8hFv3mAsh6T7joDGXxH3HyLMIPLa6Hcv3/',s:[0x88dd14746f,0xf971dd32bb],u:'/cdn-cgi/challenge-platform/h/b'}})();</script></body> </html>`

I have tried a lot of diffrent settings in duplicati but no success.
I would love to use uptime-kuma as monitor for all my duplicati backups, but im not sure if this is something that can be fixed on the uptime-kuma side, or if it needs to be fixed on the duplicati side.

Have anyone else made this work with running a script after backup maybe? (I have not tried the script way)

### 🐻 Uptime-Kuma Version

1.10.2

### 💻 Operating System and Arch

Ubuntu 20.04

### 🌐 Browser

Chrome Version 96.0.4664.45

### 🐋 Docker Version

Docker 20.10.11

**Comment by chakflying** [comment]
The push monitor only responds to GET requests, and looks like your Duplicati is sending POST request. For now I think you might have to look for another method of reporting in Duplicati.

**Comment by bluefrg** [comment]
While this isn't the most elegant solution, I use Node-RED, and instead of Duplicati POSTing directly to Uptime Kuma (which only accepts GET requests), I post to a Node-RED flow that accepts a POST and then makes a GET to the Uptime Kuma ping address.
