### ISSUE TITLE
Create uptime-kuma umbrel app

### ISSUE THREAD

**Issue by phaus** [louislam/uptime-kuma#991]
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

Other

### 🔖 Feature description

[Umbrel](https://getumbrel.com/) is a new Kind of local node setup (primarily but not exclusively aimed for crypto currency).
Umbrel support an App Framework (aka Docker + config) for a one-click install (https://github.com/getumbrel/umbrel/blob/master/apps/README.md).
Other Applications like Pi-Hole and Nextcloud are already present.

I would like to try to create an Umbrel Application Wrapper for uptime-kuma, but it would be great to do this in an "official" context.

So maybe you @louislam can find some time to have a read and give me your thoughts about this.

### ✔️ Solution

Crate a uptime-kuma App 

### ❓ Alternatives

N/A

### 📝 Additional Context

https://github.com/getumbrel/umbrel/blob/master/apps/README.md

**Comment by louislam** [comment]
Since I have already containerized Uptime Kuma, I think you just need to make a pull request to their repo.

Uptime Kuma is under MIT license. As long as you don't wipe my copyright info, you are free to do anything with it.

**Comment by phaus** [comment]
👍 

I just created https://github.com/getumbrel/umbrel/pull/1148
So let's see how this one goes :-) 

Your App is very useful btw. :-)

**Comment by phaus** [comment]
Hi @louislam, there was the question from the Umbrel Team, if there is any kind of proxy configuration present in Kuma, so that it could be used over a TOR Tunnel?
I couldn't find anything of the regards in the Docker Parameters?

**Comment by phaus** [comment]
Since uptime-kuma uses axios, the default proxy value should work (see https://github.com/axios/axios/pull/366) 
I will do some testing, I guess.

**Comment by louislam** [comment]
This was discussed before, HTTP_PROXY is not fully working in the current status,

**Comment by phaus** [comment]
done.
https://twitter.com/getumbrel/status/1470365887827877893
