### ISSUE TITLE
Setup with proxy

### ISSUE THREAD

**Issue by demogratias** [louislam/uptime-kuma#995]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### 📝 Describe your problem

Hi,

Can't install with proxy : download-dist don't download dist.tar.gz.

Proxy configuration for npm :

`
npm config set proxy "my.proxy.lan:8080"
npm config set https-proxy "my.proxy.lan:8080"
`

Error message :

> root@vm:~/uptime-kuma# npm run setup
> 
> > uptime-kuma@1.10.2 setup
> > git checkout 1.10.2 && npm ci --production && npm run download-dist
> 
> HEAD est maintenant sur bf64095 update to 1.10.2
> npm WARN EBADENGINE Unsupported engine {
> npm WARN EBADENGINE   package: 'uptime-kuma@1.10.2',
> npm WARN EBADENGINE   required: { node: '14.*' },
> npm WARN EBADENGINE   current: { node: 'v12.22.5', npm: '8.1.4' }
> npm WARN EBADENGINE }
> npm WARN deprecated har-validator@5.1.5: this library is no longer supported
> npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
> npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
> npm WARN deprecated core-js@2.6.12: core-js@<3.3 is no longer maintained and not recommended for usage due to the number of issues. Because of the V8 engine whims, feature detection in old core-js versions could cause a slowdown up to 100x even if nothing is polyfilled. Please, upgrade your dependencies to the actual version of core-js.
> 
> added 430 packages, and audited 431 packages in 22s
> 
> 26 packages are looking for funding
>   run `npm fund` for details
> 
> 9 moderate severity vulnerabilities
> 
> To address issues that do not require attention, run:
>   npm audit fix
> 
> To address all issues, run:
>   npm audit fix --force
> 
> Run `npm audit` for details.
> 
> > uptime-kuma@1.10.2 download-dist
> > node extra/download-dist.js
> 
> Downloading dist
> https://github.com/louislam/uptime-kuma/releases/download/1.10.2/dist.tar.gz
> events.js:291
>       throw er; // Unhandled 'error' event
>       ^
> 
> Error: connect ETIMEDOUT 140.82.121.4:443
>     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1138:16)
> Emitted 'error' event on ClientRequest instance at:
>     at TLSSocket.socketErrorListener (_http_client.js:427:9)
>     at TLSSocket.emit (events.js:314:20)
>     at emitErrorNT (internal/streams/destroy.js:92:8)
>     at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
>     at processTicksAndRejections (internal/process/task_queues.js:84:21) {
>   errno: 'ETIMEDOUT',
>   code: 'ETIMEDOUT',
>   syscall: 'connect',
>   address: '140.82.121.4',
>   port: 443
> }
> npm ERR! code 1
> npm ERR! path /root/uptime-kuma
> npm ERR! command failed
> npm ERR! command sh -c git checkout 1.10.2 && npm ci --production && npm run download-dist
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR!     /root/.npm/_logs/2021-12-02T12_22_50_235Z-debug.log

Thanks.

### 🐻 Uptime-Kuma Version

1.10.2

### 💻 Operating System and Arch

Debian 11

### 🌐 Browser

Firefox

**Comment by ugurerkan** [comment]
Hi, the error looks like related with Node.js version, could you try with node version >= 14

> npm WARN EBADENGINE Unsupported engine {
> npm WARN EBADENGINE package: 'uptime-kuma@1.10.2',
> npm WARN EBADENGINE required: { node: '14.*' },
> npm WARN EBADENGINE current: { node: 'v12.22.5', npm: '8.1.4' }

**Comment by louislam** [comment]
You can download dist.tar.gz manually in the release page.

https://github.com/louislam/uptime-kuma/releases/tag/1.10.2

**Comment by prbond** [comment]
Hi, where is the full path fo dist ?

**Comment by demogratias** [comment]
Find a workaround :

When installation script fails, edit uptime-kuma/extra/download-dist.js and look at this line :

`const url='https://github.com/louislam/uptime-kuma/releases/download/${version}/${filename}';`

Download this file, where X.X.X is the last release :

``https://github.com/louislam/uptime-kuma/releases/download/X.X.X/dist.tar.gz`;``

Upload dist.tar.gz on a local webserver or a local NextCloud (so, no proxy used), and retreive download URL. Edit the "const url" line on download-dist.js with this new URL, like it :

`const url='http://cloud.network.local/index.php/s/xxxxxxxxx/download/dist.tar.gz';`

Save the file and relaunch :

`pme2 delete all ; bash -f kuma_install.sh`

Now installation will be OK.

**Comment by demogratias** [comment]
> You can download dist.tar.gz manually in the release page.
> 
> https://github.com/louislam/uptime-kuma/releases/tag/1.10.2

Tried it but script still trying to check online. It always download, even with dist.tar.gz on directory.
