### ISSUE TITLE
Database corrupted with new pod

### ISSUE THREAD

**Issue by fernandoscruz** [louislam/uptime-kuma#998]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### Description

I'm having trouble running the app on kubernetes.
When a pod (a container) is working fine, and I start a new pod with a change, the new pod uses the same database and corrupts the data.

Whenever a new change enters, the database is bad.

Has anyone experienced this problem?

I used a volume from kubernetes to have data persistence.

Thanks

### 👟 Reproduction steps

[2021-12-02 20:03:52] [Error:
            SELECT AVG(ping)
            FROM heartbeat
            WHERE time > DATETIME('now', -24 || ' hours')
            AND ping IS NOT NULL
            AND monitor_id = 13  limit 1 - SQLITE_CORRUPT: database disk image is malformed] {
  errno: 11,
  code: 'SQLITE_CORRUPT

### 👀 Expected behavior

Having a working pod, new pod going into production without leaving a bad database

### 😓 Actual Behavior

1 - Pod running with volume
2- New pod using same volume
3 - corrupted database

### 🐻 Uptime-Kuma Version

1.10.2

### 💻 Operating System and Arch

ROM louislam/uptime-kuma@sha256:b2323f186a49a9437e53557ae99e81d129f775336bed7bbb5737ec2ed9f4228a

### 🌐 Browser

Chrome

### 🐋 Docker Version

K8S

### 🟩 NodeJS Version

ROM louislam/uptime-kuma@sha256:b2323f186a49a9437e53557ae99e81d129f775336bed7bbb5737ec2ed9f4228a

### 📝 Relevant log output

```shell
NA
```

**Comment by louislam** [comment]
Usually it is caused by hard shutdown of sqlite. You have to google to find how to repair the sqlite database.

**Comment by fernandoscruz** [comment]
With me it happens 100% of the time a new pod is created.

I believe the solution is to use an external database.

If I keep using uptime-kume, I'll try to work on it.

thanks

**Comment by louislam** [comment]
The second reason could be that sqlite cannot be running on any type of network drive.

**Comment by telmich** [comment]
This sounds like concurrent access from multiple pods - are you using multiple pods, @fernandoscruz ?

**Comment by fernandoscruz** [comment]
Hi @telmich 
I'm not using multiple pods.
But in a new deploy, for a while kubernetes keeps two pods, at that moment it causes my problem.

Ideally, we had a database outside the pod.

I will try to work on it, using mysql.

 thanks

**Comment by davralin** [comment]
> But in a new deploy, for a while kubernetes keeps two pods, at that moment it causes my problem.

Try this in your manifest:
````yaml
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kuma
  namespace: kuma
  spec:
    selector:
      matchLabels:
        app: kuma
    replicas: 1
    strategy:
      type: Recreate
````

The important part being Recreate.

This will bring your original Pod down first, then create a new one - ensuring two pods are never started simulateously.
For more info, check here: https://kubernetes.io/docs/concepts/workloads/controllers/deployment/#recreate-deployment
