### ISSUE TITLE
Viewing Group-results in status page without displaying all node in this group

### ISSUE THREAD

**Issue by barto95100** [louislam/uptime-kuma#999]
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

UI Feature

### 🔖 Feature description

Possibility to view juste the result of Group in status page without all node in this group

### ✔️ Solution

When to view the status page just view the information per group is it's ok and if selected the group it's expand to view all node in this group

**Comment by remyd1** [comment]
Maybe an alternative would be to create multiple status pages ?

**Comment by robkooper** [comment]
I think having multiple status pages is a good thing. This way I don't have to create many uptime-kuma instances for different projects. But it would be nice to have a collapsing grouping option. This way I can show:

Service 1:
- web
- api
- something else

Service 2:
- web
- api

and just collapse them both as, and allow the user to quickly see that both service1 and service2 are up, but if any of the underlying services is down then they can uncollapsed.

It would be really nice if I can use the tag to create one of these groups, and if I create a new monitor it is automatically added to this group.

**Comment by CommanderStorm** [comment]
@PopcornPanda  I think this has been implemented+merged.
Any version after [`1.22.0-beta.0`](https://github.com/louislam/uptime-kuma/releases/tag/1.22.0-beta.0) supports this.
![image](https://github.com/louislam/uptime-kuma/assets/26258709/2b8673a3-214f-449f-a7fd-675c6dacc8db)
![image](https://github.com/louislam/uptime-kuma/assets/26258709/2a188e08-0774-402e-92e7-c18da04c0026)
![image](https://github.com/louislam/uptime-kuma/assets/26258709/3a19abac-fd44-430b-84e0-8be09d9e6031)

Could you close this Issue if this has been resolved?

**Comment by robkooper** [comment]
From the screen shot it looks like alphabet has its own monitor from the two services below it. So if one of the sub services (google and youtube in this case) are down, is alphabet marked down, or degraded?
